### ISSUE TITLE
NEI Flakes Crash.

### ISSUE THREAD

**Issue by madolinn** [ReikaKalseki/Reika_Mods_Issues#10]
With new and improved actual information!

http://pastebin.com/V2tqrGCu

It happens when you click on Flakes that have recipes for things that aren't installed. Like DartForce Flakes.

**Comment by zemerick** [comment]
I don't have anything specific to help with this off hand, but I do want to say thank you for getting the information, especially the extra details.

That being said, this does sound familiar. I believe it has cropped up before, and I'll see if I can track that down.

**Comment by theswedishchef1** [comment]
bork bork bork bork bork!

**Comment by zemerick** [comment]
Looks like the one I was thinking of was an unrelated issue. Still checking a few others.

I did find a second pastebin of the same issue, but from a different person with a different NEI version. I couldn't find any actual post from the person though.

http://pastebin.com/02ca3cYy

OP: Are you able to test changing mods easily? We might want to try a bare minimum, which I think would be DragonAPI, Codechickencore, NEI and Rotarycraft.

**Comment by madolinn** [comment]
I absolutely can do if you give me about an hour I'll get back to you (apologies for the wait).

**Comment by zemerick** [comment]
No need to apologize:)

I did get a minimum test done myself in the mean time. DragonAPI 6f, RoC 6f, CCC 35, NEI 90.

It crashed as soon as I pressed R on a flake from a mod not in the pack. The creative menu properly shows only the flakes available, but NEI lists them all. I will try to look at the code, but this is unfortunately not one of my strong suits:)

**Comment by Kolatra** [comment]
Reika is looking at this.

**Comment by madolinn** [comment]
Crashed with the minimum just to triple check, exactly the same log.
[Hurray.](http://pastebin.com/xepeLvfy)

**Comment by Kolatra** [comment]
Reika says he fixed this. :)
