### ISSUE TITLE
Chromaticraft crashing with pylon power (6f)

### ISSUE THREAD

**Issue by Mettra** [ReikaKalseki/Reika_Mods_Issues#100]
I have been getting quite a few crashes when trying to use the pylon power in v6f.

This first one triggered as soon as I placed a ritual table down that tried to draw power for an upgrade.
http://pastebin.com/2ppFMbxq

This second one happened when trying to place a rune to complete a repeater in the temple.
http://pastebin.com/gjV7THZg

And finally this crash occurred when I was re-loading the repeaters from the last crash.
http://pastebin.com/Eqy7RkiG

**Comment by ReikaKalseki** [comment]
CMEs are sporadic and nearly impossible to track down.

Try removing mods and/or a new world.
