### ISSUE TITLE
[RoC] [Minor] Odd freeze in NEI

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1000]
Looking at Tool Charging in NEI, attempting to go to page 2 freezes the client for about 15 seconds, then does nothing. I have been unable to successfully see page 2 yet. Nothing in the console.

**Comment by ReikaKalseki** [comment]
Does this happen reliably? I do not have this issue.

![](http://i.imgur.com/DeqnLgX.png)

**Comment by TomeWyrm** [comment]
@Zsashas Is this reproduce-able using only DragonAPI, ChromatiCraft, CodeChickenCore, and NEI?
