### ISSUE TITLE
[Suggestion] Void Monster Enchanted Books

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1002]
Instead of having a set three books, and only those three, why not have it simply generate books of a certain enchanting level? Or random enchants, perhaps vanilla only, at high levels? You only need so many Infinity books, after all.

**Comment by TomeWyrm** [comment]
Please, if you do implement this, whitelist the enchants you can obtain from the void monster. If you can do it in the config, more the better. There are some mods whose enchants shouldn't be granted outside of their own mechanics for various reasons. Maybe not amazingly airtight ones, but that's still the kind of thing where a bit of forethought can avoid headaches down the road.

**Comment by Builderb0y** [comment]
*cough* chromatic enchanter *cough*

**Comment by Shahelion** [comment]
@TomeWyrm true, that's why I suggested maybe only vanilla enchantments.

**Comment by TomeWyrm** [comment]
@Builderb0y I am aware of that and enchanting plus and think that TT's osmotic enchanter did it better with the whitelist. A lot of mods use enchantments that shouldn't be obtainable outside their mechanics. Which is one of my issues with those systems :-p

**Comment by ReikaKalseki** [comment]
Done.
