### ISSUE TITLE
Update to v15 of DragonAPI, ElectriCraft, ReactorCraft, RotaryCraft from v13 and the server crash

### ISSUE THREAD

**Issue by catchra** [ReikaKalseki/Reika_Mods_Issues#1003]
The server worked with no problem before the update

the mods installed are

http://paste.ee/p/xW7ak

the error log

http://paste.ee/p/EpW6s

Edit: Spammy copypasta fixed by TomeWyrm because it was seriously bugging him.

**Comment by ghost** [comment]
Please put the log on pastebin or gist next time.

**Comment by 3TUSK** [comment]
Remove Thaumic Infusion.
#895 #995 TheDrunkMafia/ThaumicInfusion#81

**Comment by ghost** [comment]
Please put the log on pastebin.

**Comment by TomeWyrm** [comment]
There, I edited his post to include a link to a paste site... sometimes these issues _sigh_
