### ISSUE TITLE
[CC] Loot Chests can be opened with a block on top of them

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1006]
The first thing that led me to believe this was actually a bug is the cracked shielding stone in the crystal burrows above the three chests, implying you'd have to break it to open the chests, but you don't. Also the new village structure, you can just go under the house (as it seems to always spawn floating) and open the chest without having to break the crafting table.

**Comment by ReikaKalseki** [comment]
I know this to be false from personal and recent experience, and cracked stone is special.
