### ISSUE TITLE
RotaryCraft/ComputerCraft - Not recognizing peripherals

### ISSUE THREAD

**Issue by Sadumon** [ReikaKalseki/Reika_Mods_Issues#1008]
I started with the FTB infinity evolved pack, and then added in version v15a of RotaryCraft, ReactorCraft, and DragonAPI.

When I put a ComputerCraft (v1.75) computer next to any RotaryCraft Machine (e.g. Extractor, Industrial Coil, CVT), the computer does not appear to recognize that there is a peripheral on that side.  For example, peripheral.isPresent(<side>) returns false.  I've tested the computer on other mods entities and it does find them without issue.

I know this used to work -- in an old modpack I had a computercraft computer managing a coil, CVT, and Extractor to make sure the coil and CVT were working as efficiently as possible based on the contents of the Extractor inventories.  I make no assumption that the old code will still work, but there is something else interfering with ComputerCraft and RotaryCraft integration.  

My log seems to indicate it should be forcing compatibility, unless I'm misunderstanding what this means:
[16:17:34] [Client thread/INFO]: ROTARYCRAFT: Forcing compatibility with ComputerCraft

**Comment by ReikaKalseki** [comment]
It works in OpenComputers, but apparently CC requires you attach an adapter...which cannot be connected to noncubic blocks.

**Comment by Builderb0y** [comment]
> apparently CC requires you attach an adapter...which cannot be connected to noncubic blocks.

Not necessary if the computer is directly adjacent to the machine.

**Comment by Sadumon** [comment]
> Not necessary if the computer is directly adjacent to the machine.

Correct.  I know in the previous modpack I was using, I had to make sure everything was touching the computer itself because I couldn't use the modems/cables, but as long as the components I wanted to work with were attached to the computer, I could access them using the perhiperal API.  It was working with ComputerCraft 1.74 and v9b of your mods in the pack I had before.  I don't believe there are any configuration files that turn on or off the integration, at least none that I could see in either mod config file.

**Comment by ReikaKalseki** [comment]
I have not changed the CC interfacing since 1.6.4.
