### ISSUE TITLE
[Rotorycraft] [Issue/suggestion] dynamic search for ores to enable/disable extractor items

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#101]
I realize that part of this is a suggestion however there is a problem as well. A dynamic search system of ore searching to determine extractor items needs to be implemented in order to prevent crashes linked non existant ores in extractor recipes. This also makes the NEI screen look much cleaner when looking at flakes among other products produced by the extractor 

There is also a vague reference to this in the custom extracts config but a search and enable system would keep those that are not config savvy from accidentally causing a crash and wondering why it happened (crashing fixed luckily in v7).

**Comment by ReikaKalseki** [comment]
> but a search and enable system would keep those that are not config savvy from accidentally causing a crash and wondering why it happened.

Unused ones will not crash.

Also, this is not going to work if you have NetherOres installed, because it looks in the OreDict for uses of the ores, and adds them if it finds any. This will mean it finds the flakes, tricking RC into thinking the ores are needed.

**Comment by Zedrimar** [comment]
I know the nether ores situation and luckily the crash does get fixed (hopefully) in v7 but you have to admit even with the nether ores thing, it does clean things up in NEI.

sorry for derping in the description, I already forgot that the crash is going to be fixed in v7 :(

**Comment by Zedrimar** [comment]
@ReikaKalseki If you want to give it a try, here is what I suggest on doing;

Tell RoC to skip the Nether ores mod as nether ores only looks for overworld ores and their uses when determining what needs to be enabled and not. After all, all nether ores does is add nether versions and allows you to get 2x the amount! Doing so keeps RoC from generating the extra un-used ores in the nether and the extra flakes are disabled if the feature is to ever be implemented. :)
If the nether flakes are to be kept the machine will have to check the first slot to see what TYPE of ore it is unless you remove the nether flakes and use the overworld versions instead and just allow for quadupling in the first part of the extraction rather than the whole thing, Either way, people will get a metric crap ton of ore!!

This should work as long as nether ores only does its check when loading the nether dimension so by then the extras are disabled and netherores shouldn't be able to see them.

**Comment by ReikaKalseki** [comment]
> Tell RoC to skip the Nether ores mod as nether ores only looks for overworld ores and their uses when determining what needs to be enabled and not.

I treat NetherOres blocks separately, and they are registered under different tags.

**Comment by Zedrimar** [comment]
ok

**Comment by ReikaKalseki** [comment]
Done.
