### ISSUE TITLE
[ChromatiCraft] Heat Lamp imbalance (maybe) with Steam Boiler from ReactorCraft when using specific tools from other mods

### ISSUE THREAD

**Issue by 3TUSK** [ReikaKalseki/Reika_Mods_Issues#1010]
This is discovered by my friends in a server. 
Usually, player cannot directly attach Heat Lamp on Steam Boiler in ReactorCraft, but someone in that server accidentally found that, with any of following means, attaching Heat Lamp adjacent to Steam Boiler is possible:
- Wand Focus: Dislocation, from Thaumic Tinkerer (require a thaumcraft wand obviously);
- Crane, from OpenBlocks;
- Cardboard box, from Mekanism. 

As such, Steam Boiler can produce steam (almost) for free. 

> Most people in that server consider this as imbalance and hope that I can report it asap. And now I finished the mission, XD

**Comment by Aivech** [comment]
From a lore standpoint this makes sense, but from a gameplay standpoint this is horribly broken.
Also, I thought the heat lamp only got just hot enough for yeast to grow properly in colder climates.

**Comment by ReikaKalseki** [comment]
This may not be fixable, and since it requires fundamentally "breaking" the way something works (i.e. block placement)...

**Comment by 3TUSK** [comment]
At least we can blacklist Heat Lamp in mekanism iirc...

**Comment by Aivech** [comment]
As far as I know all of those items work in a strange manner to begin with. Many of them also have blacklists.
