### ISSUE TITLE
Lumen Repeater recipe returning bucket with metadata

### ISSUE THREAD

**Issue by Keyarose** [ReikaKalseki/Reika_Mods_Issues#1011]
Just crafted my first set of lumen repeaters and the bucket left behind in the casting table had a metadata of 1.  Its not a significant issue but its inconvenient to have to fill and empty the bucket just to stack it again.

Version 15a

**Comment by ReikaKalseki** [comment]
Ooops...

**Comment by ReikaKalseki** [comment]
Fixed.
