### ISSUE TITLE
Electricraft OpenComputers function getCurrent() returns voltage

### ISSUE THREAD

**Issue by Eb-** [ReikaKalseki/Reika_Mods_Issues#1012]
![2016-06-30_20 56 24](https://cloud.githubusercontent.com/assets/2814500/16508859/2d4a4972-3f05-11e6-8e51-8e854c6d30cb.png)

Looks like the problem is [here](https://github.com/ReikaKalseki/ElectriCraft/blob/a572d4f1e5446b4fad1d083c5cf634f8dcd9d32e/Auxiliary/Lua/LuaGetCurrent.java) on line 25.

**Comment by ReikaKalseki** [comment]
Derp.

**Comment by ReikaKalseki** [comment]
Fixed.
