### ISSUE TITLE
Chromaticraft Crash on first launch

### ISSUE THREAD

**Issue by Saereth** [ReikaKalseki/Reika_Mods_Issues#1014]
Getting a client side chromaticraft crash on first launch, reported by at least half a dozen players, and experienced by myself as well. v15a. Here is a copy of the full crashlog

https://dl.dropboxusercontent.com/u/28829658/crash-2016-07-01_10.16.59-client.txt

This seems to resolve on subsequent restarts oddly enough.

**Comment by HellFirePvP** [comment]
I also get the crash even when setting up just DragonAPI and CC (+ Forge 1614) on a clean install.

After the initial crash, it never happens again.

**Comment by ghost** [comment]
This is because of AE2 rv3. 

Either disable "exportItemNames" inside config/AppliedEnergistics2/CustomRecipes.cfg or downgrade to rv2. Or, just keep crashing once and crashing again one time a mod is added/removed.

**Comment by TomeWyrm** [comment]
log or it didn't happen @HellFirePvP
