### ISSUE TITLE
[CC] Out-of-place Lexicon page

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1015]
Tinted Crystal Lenses are in the basic crafting section of the row, yet they require Item Casting, alloys, and something else that I still haven't discovered at this point (just barely at item casting). Also, I have no idea what they are even used with.

**Comment by ReikaKalseki** [comment]
I moved it up a couple tiers. It is still required for things like the relay source, so it cannot be pushed far.
