### ISSUE TITLE
[ChromatiCraft] Crash when providing Herba Essentia to Growth Lamp with Essentia Relay and Aspect Jar (ChC ver.)

### ISSUE THREAD

**Issue by 3TUSK** [ReikaKalseki/Reika_Mods_Issues#1019]
http://paste.ee/p/4Av8F Test under Forge 10.13.4.1614, DragonAPI v15a + ChromatiCraft v15a, Thaumcraft 4.2.3.5.
Steps to reproduce:
1. Place an Aspect jar, with Essentia Relay atop.
2. Fill jar with herba essentia.
3. Place a Growth Lamp, with Essentia Relay below. Between two Essentia Relays is a distance of several blocks.
4. Game freeze for seconds and then crash.

**Comment by ReikaKalseki** [comment]
Only Herba? Only the Growth Lamp?

**Comment by 3TUSK** [comment]
Well, at least, following the steps, the game should crash.
Im gonna test other stuff...

**Comment by 3TUSK** [comment]
Wait. I set up a new world and now everything seems fine to me now. Tested with Lamp of Growth, Lamp of Fertility, and several Crucible recipes.
But that didn't explain why I have that crash.

**Comment by 3TUSK** [comment]
And now everything seems fine in the world that cause the crash. Between the crash and the second test, I did nothing other than re-open the game...

**Comment by TomeWyrm** [comment]
Welcome to why I hate computers sometimes. They're intricate systems built from amazingly complex software running on extremely complex (and widely varied) hardware. Which leads to all kinda of bugs and glitches that, while deterministic, might as well be magic thanks to our inability to understand them.

I'm going to close this now
