### ISSUE TITLE
Buildcraft gates and extractor with bedrock drill

### ISSUE THREAD

**Issue by SamuelFoster** [ReikaKalseki/Reika_Mods_Issues#102]
Buildcraft gates (specifically tested Basic and Iron OR Gates) appear to register the bedrock drill as an "item in inventory" in the extractor. I.e., a buildcraft gate on the "Items in Inventory" setting does not output a signal when an empty extractor has no bedrock drill, but does output when a bedrock drill is added.

(This may be intended, but it seemed strange.)

**Comment by ReikaKalseki** [comment]
The bedrock drill is stored as an item in the tenth (invisible) inventory slot. I wrote some gate handling code, but asie never replied when I asked if it was correct.

**Comment by KennyBurch** [comment]
I can confirm this issue still exists, both with bedrock drill and an updated config to have the non-bedrock extractor drill take damage. 

Side note: When looking for alternatives I noted that the Steve's factory manger does not seem to be able to 'see' the inventory slots of the extractor (works with other equipment like the grinder) /shrug RFTools Screen can SEE the inventory slots, but I am still unable to find a good substitute to monitor a good 'items exit' metric.  Time to start messing with one of the computer mods i guess.

**Comment by ReikaKalseki** [comment]
I know. This one is likely to go unfixed for some time.

**Comment by TomeWyrm** [comment]
@asiekierka
Care to weigh in?

**Comment by asiekierka** [comment]
getAccessibleItems from ISidedInventory is a good way to tell the BuildCraft gates what can and cannot be seen.

**Comment by ReikaKalseki** [comment]
Fixed.
