### ISSUE TITLE
[CC] Ore Harvester does not work on CC Ores

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1021]
Further tested on more of the hidden ores, still isn't silk touching them, along with Cave Crystals.

**Comment by TomeWyrm** [comment]
Cave crystals are not ores, and CC ores cannot be obtained in block form without cheats.

**Comment by Shahelion** [comment]
Alright. I thought the Ore Harvester was supposed to Silk Touch whatever (hence the crystals).

**Comment by Builderb0y** [comment]
It's supposed to cleanly cut ores from the ground, without letting the stone around them crumble. Because it totally makes sense for ChC ores to somehow loose their magic properties as soon as you touch them. Yeah.

**Comment by TomeWyrm** [comment]
Yeah, the gap in their functionality makes sense from a meta perspective if you think about it, but man is it inconsistent from a mechanics/gameplay perspective... then again Silk Touch is like that too.
