### ISSUE TITLE
[CC] Turbocharged & enhanced CompoundRepeater in CrystalBroadcaster

### ISSUE THREAD

**Issue by KevTheCrafter** [ReikaKalseki/Reika_Mods_Issues#1022]
Hi,

if you build the enhanced structure for the CompoundRepeater in the CrystalBroadcaster, the check for the CrystalBroadcaster failed.

Version:
DragonAPI: V15a
Chromaticraft: V15a

**Comment by ghost** [comment]
Perhaps this could also be a way to "enhance" the broadcaster as well if Reika doesn't want to add an entire special structure for it.

**Comment by KevTheCrafter** [comment]
"Enhance" the broadcaster makes no sense.

The broadcaster has the highest throughput of 100.000 Lumen: https://github.com/ReikaKalseki/ChromatiCraft/blob/master/TileEntity/Networking/TileEntityCrystalBroadcaster.java#L93

Compared to the TileEntityCompoundRepeater:
Normal: 1000
Turbocharged: 12000
Enhanced: 20000

**Comment by ReikaKalseki** [comment]
Done.

**Comment by ghost** [comment]
It's never sent 100,000 lumens. The most its sent is maybe 20.
