### ISSUE TITLE
[CC] Suggestion: Particle Renderer

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1023]
Why not add the 16 element symbols as particle options? I was surprised this wasn't already an option.

**Comment by TomeWyrm** [comment]
Huh, what an obvious suggestion for me to miss. Thanks @Zsashas, I totally think it's a great idea!

**Comment by ReikaKalseki** [comment]
Not implementable, because all of the element symbols are pretinted and thus not compatible with color select, as well as the fact the supported icons on the spawner are and need to be registry-based. Besides, most flash.
