### ISSUE TITLE
Request for cave control Configs

### ISSUE THREAD

**Issue by bookerthegeek** [ReikaKalseki/Reika_Mods_Issues#1024]
Request for the following to be added to the configs:
- Stronghold;
  - Distance: To determines how far strongholds are from the spawn and other strongholds.
  - Count: The number of strongholds that exist per world.
  - Spread: Determines how concentrated strongholds are around the spawn. 
- Mineshaft;
  - Chance: Determines how common mineshafts are (from 0.0 to 1.0, default is 0.01). Higher number would make them more common.

**Comment by ReikaKalseki** [comment]
Done, but spread and count are tied together as they work that way in the generator.

**Comment by bookerthegeek** [comment]
Sweet. Thank you so much.  Look forward to using this.  :)
