### ISSUE TITLE
[ReactorCraft] Neutrons Ignore the First Block They Enter

### ISSUE THREAD

**Issue by ErdrickXLII** [ReikaKalseki/Reika_Mods_Issues#1025]
I set up a block of fuel cores like this:
![reac1](https://cloud.githubusercontent.com/assets/4296894/16575622/bd73294c-4257-11e6-9296-91c433caca10.png)
And that worked just fine.  But when I changed the setup to this:
![reac2](https://cloud.githubusercontent.com/assets/4296894/16575626/c1714542-4257-11e6-9afd-7a1c369a4f7f.png)
Even with the control rods down, the fuel cores were still getting hot enough to make steam.  Raising the control rods causes it to explode in about 7 seconds.

I was confused as to why what is basically the same setup would have wildly different results, so I played around with it a bit and discovered that when neutrons are emitted from a fuel core, they do not interact with the first block they hit at all.

I originally wasn't even going to report it, since it seems to be just some Vanilla bug you wouldn't be able to fix anyway, but it doesn't _look_ intended, so I figured it might as well be put to record.  (Plus, even if it could be fixed, fixing it would have serous ramifications on existing reactor setups, necessitating people tear down their reactors before updating so they don't explode.)

**Comment by ReikaKalseki** [comment]
Your two setups are not equivalent at all, and control rods do not stop all neutrons.

**Comment by ErdrickXLII** [comment]
I'm sorry, I should have used a better example.

A 2x2 or 3x3 of fuel cores surrounded by a single layer of bedrock ingot blocks spews neutrons all over the place because the neutrons are ignoring the bedrock ingot blocks.  And I'm not talking about the 1 in 40 that should be getting through, I mean most of them are getting through.

**Comment by Aivech** [comment]
So the bug you are reporting is this?

> discovered that when neutrons are emitted from a fuel core, they do not interact with the first block they hit at all

Because reactors that should be unstable being stabilized by neutron poisons is not exactly surprising.
Also, as above mentioned, the two reactor setups are not the same.

**Comment by ReikaKalseki** [comment]
> discovered that when neutrons are emitted from a fuel core, they do not interact with the first block they hit at all

Experience tells me that this is false, as well as the lack of other corroborating reports, especially since the neutron code has not changed since 1.6.4.

**Comment by Aivech** [comment]
> discovered that when neutrons are emitted from a fuel core, they do not interact with the first block they hit at all

Also I'm pretty sure you mean "do not interact with any blocks adjacent to the fuel core that emitted them" and not this.
Note that neutrons from fuel cores don't go up, down, or diagonal.

**Comment by ErdrickXLII** [comment]
I think i found the reason for the behavior I noticed, I just didn't post it because I didn't think anyone cared.
[DragonAPI/blob/master/Base/ParticleEntity.java](https://github.com/ReikaKalseki/DragonAPI/blob/master/Base/ParticleEntity.java#L138) starting at line 138 checks if the neutron has entered a new block.  If so, it's sets the variables keeping track of the block is was in to the new values and runs the onEnterBlock function on the block it now occupies.  Except it doesn't, because line 145 (an if statement meant to check other conditions like "can this interact with the block it spawned in?") only lets it run onEnterBlock if the entity has existed for at least 5 ticks.  As a result, if the entity is able to travel from its starting position to the next block over within 5 ticks, it still updates its oldBlockX/Y/Z variables but will not run onEnterBlock at that position.

P.S. -- Sorry about the confusion.  DaMachinator's wording is far less ambiguous than mine.  I generally count Air as a block.

**Comment by ReikaKalseki** [comment]
Hopefully fixed.
