### ISSUE TITLE
[CC] Lumen Repeaters don't drop when mined

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1026]
What the title says.

**Comment by KevTheCrafter** [comment]
Did you use silktouch enchantment?
Or use Shift-Rightclick with the manipulator.

**Comment by Shahelion** [comment]
Did not realise that either of those was required.

Shift-right-clicking works, although the Repeater doesn't stack with ones that haven't been placed yet.

**Comment by TomeWyrm** [comment]
There's a reason silk touch goes on all my "working" tools... well there's a few, mainly more blocks I want to drop will drop, and it tends to save inventory space... there are a couple fringe benefits as well, but that's generally it.
