### ISSUE TITLE
[CC] Suggestion: Lumen Repeaters

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1027]
When you right click, have the dotted lines appear so you can see what that repeater is connected to.

**Comment by ReikaKalseki** [comment]
They do.

**Comment by Shahelion** [comment]
Well, they don't for me. Right clicking them with it just plays the error sound.

**Comment by ReikaKalseki** [comment]
Then that means it is not connected.
