### ISSUE TITLE
Chromaticraft Lock Timer Crash

### ISSUE THREAD

**Issue by Shadows-of-Fire** [ReikaKalseki/Reika_Mods_Issues#1028]
So I placed one of these in creative for some random reason, and upon right clicking it, it crashes.

https://gist.github.com/Shadows-of-Fire/fe4575f9813beaae6ffaab44b6956b7e

**Comment by ReikaKalseki** [comment]
That will not happen as of v16, but you are not supposed to spawn technical blocks.

**Comment by Shadows-of-Fire** [comment]
Is it safe to also assume that [this](https://gist.github.com/Shadows-of-Fire/06d03311047cd2289a5ed338f11115ef) issue with the Elemental lock is also fixed?

**Comment by ReikaKalseki** [comment]
No.

**Comment by ReikaKalseki** [comment]
No.
