### ISSUE TITLE
Crash after Updating to 15a

### ISSUE THREAD

**Issue by Inamatus90** [ReikaKalseki/Reika_Mods_Issues#1029]
Just updated your mods (Dragon API, Rotarycraft,Reactorcraft and Electricraft) that i am using on my private server from V12e (not played much recently but has been working fine while i was).

Keep getting this crash report upon trying to load the server. 
http://pastebin.com/a3Vjf0ms

Not sure if I've done something wrong or am missing something obvious, if so i apologize. (its late at night).

Thanks.

**Comment by ReikaKalseki** [comment]
#963, #906 #902 #914 #916 #919 and #921.

**Comment by TomeWyrm** [comment]
Linking the relevant issue for AOBD: ganymedes01/Another-One-Bites-the-Dust#125
