### ISSUE TITLE
[RotaryCraft] [Bug/Feature Req.] Redstone nightmares with Multi-directional clutch

### ISSUE THREAD

**Issue by cosmicdan** [ReikaKalseki/Reika_Mods_Issues#103]
Hi,

Multi-directional clutch only seems to work with vanilla redstone. From what I understand, it's impossible to have Project RED Red Alloy Conduit and the like placed "on" non-opaque cubes so that's fair enough, but it's a real pain trying to get vanilla redstone hooked up e.g. underneath when you have multiple outputs.

Is there any kind of improvement or work-around that could be implemented? I tried the free-standing variant of Project RED wires and Ender IO's freestanding ones too, to no avail.

Thanks in advance.

EDIT: I also have Expanded Redstone installed, though I've not explored it yet but maybe something can be done here as a compromise?

EDIT2: Running the 6f release.

**Comment by ReikaKalseki** [comment]
Only vanilla redstone is analog.

**Comment by cosmicdan** [comment]
Aha, thanks so much for that reminder. I just tried MFR's RedNet Cable and it works perfectly :dancers: 

Apologies for my ignorance and cheers for the time and glory you've put into RotaryCraft - I'm having a blast playing with it (and ElectriCraft) as exclusively as I can. Wish you all the best!

**Comment by ReikaKalseki** [comment]
:)
