### ISSUE TITLE
[CC] Suggestion: Amulets & Baubles Support

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1030]
It seems weird to just be carrying around amulets in my inventory, and they work.

**Comment by ReikaKalseki** [comment]
As far as I know, using baubles means a hard dependency, and even if not, you can only have one pendant, and noone only uses one pendant. This is not useful.

**Comment by Aivech** [comment]
Who says you have to wear an amulet around your neck (apart from the name of course)?
More useful would be the ability to equip the focus pouch in the belt slot.
Nonetheless non-essential. Mostly useful for cheesing Witchery...

**Comment by TomeWyrm** [comment]
_cough_ tinker's belt _cough_

There's a LOT of known ways to cheese the spirit world.

**Comment by Shahelion** [comment]
Huh, wasn't even thinking of that. Baubles go to the Spirit World? o_o

**Comment by Aivech** [comment]
yes, but they're counter-cheesed by making them inaccesible except via hotkey

**Comment by TomeWyrm** [comment]
All alternative inventories broke witchery's inventory clear/store behavior. Eimonoph broke a few such methods, but far from all.
