### ISSUE TITLE
[Request] Pulse Jet Furnace Mekanism support

### ISSUE THREAD

**Issue by Keyarose** [ReikaKalseki/Reika_Mods_Issues#1032]
Currently the Pulse Jet Furnace does not recycle Mekanism armor.  I'm assuming that recipes for recycling using the furnace are generated automatically from crafting recipes, and since Mekanism armor uses a custom crafting method it is not registered.  Right now I only know of one mod which has a method of recycling Mekanism armor: AppleMilkTea.

**Comment by ghost** [comment]
I think it is added manually and not automatically.

**Comment by ReikaKalseki** [comment]
Osmium armors?

**Comment by Shadows-of-Fire** [comment]
Mekanism adds armors of Steel, Osmium-Glowstone, Osmium-Obsidian, and Osmium.  
O-G and O-O are I think Glowstone Ingots and Obsidian Ingots to Mekanism.

**Comment by Keyarose** [comment]
Osmium, bronze, and steel armors are all supported by AppleMilkTea for recycling, I don't know about the Lapis armor.  The armors made from Mekanism only ingots, O-G and O-O are not for sure.
Despite Railcraft Steel armor being recyclable in the furnace Mekanism's is not.

**Comment by Aivech** [comment]
Links to all Mekanism-added armors on the Mekanism Wiki:
- [Lapis Lazuli Armor](http://wiki.aidancbrady.com/wiki/Lapis_Lazuli_Armor) uses Lapis Lazuli
- [Bronze Armor](http://wiki.aidancbrady.com/wiki/Bronze_Armor) uses Bronze Ingots
- [Osmium Armor](http://wiki.aidancbrady.com/wiki/Osmium_Armor) uses Osmium Ingots
- [Glowstone Armor](http://wiki.aidancbrady.com/wiki/Glowstone_Armor) uses Glowstone Ingots
- [Steel Armor](http://wiki.aidancbrady.com/wiki/Steel_Armor) uses Steel and Iron Ingots
- [Obsidian Armor](http://wiki.aidancbrady.com/wiki/Obsidian_Armor) uses Obsidian Ingots

They are made in different fashions. 

Bronze is made by infusing copper ingots with tin dust in the [Metallurgic Infuser](http://wiki.aidancbrady.com/wiki/Metallurgic_Infuser).

Osmium is an ore added by Mekanism.

Steel in Mekanism is made in the Metallurgic Infuser by infusing iron ingots with a source of Carbon to make Enriched Iron, and then infusing Enriched Iron with carbon to get Steel Dust. This is then smelted.
Coal, Charcoal, and Compressed Carbon all work as carbon sources, with Coal being worth 10 points, Charcoal 20, and Compressed Carbon 100. Making an iron ingot into Steel Dust requires 20 carbon, 10 for each stepp.

Glowstone and Obsidian ingots are an alloy of Osmium and Glowstone Dust or Refined Obsidian Dust, respectively, in the [Osmium Compressor](http://wiki.aidancbrady.com/wiki/Osmium_Compressor).

**Comment by ReikaKalseki** [comment]
Are all the armors standard recipes of the expected number of ingots, and of nothing else?

**Comment by Shadows-of-Fire** [comment]
The steel armor is a mix of iron and steel.

**Comment by Keyarose** [comment]
I think it was done with a mix of iron and steel to avoid a recipe conflict with mods like Railcraft and Metallurgy.
Since the furnace doesn't have multiple output slots maybe it could just return 3-4 steel as a "cost" to recycling it? (4 being the 3 needed to make it + the 2 iron equalling 1 steel)

**Comment by Aivech** [comment]
> Are all the armors standard recipes of the expected number of ingots, and of nothing else?

Most of the armors are standard recipes of the standard number of ingots, and nothing else. 

Exceptions:
- The lapis armor uses lapis lazuli pieces in place of special ingots.
- The steel chestplate uses 3 pieces of iron in place of some of the steel.
- The other steel armor parts only replace 2 steel ingots with iron.

Full recipes are on the wiki pages I linked above.

**Comment by ReikaKalseki** [comment]
Can someone get me /mt hand or similar registry names for the relevant items?

**Comment by Shadows-of-Fire** [comment]
https://github.com/aidancbrady/Mekanism/blob/1.7.10/src/main/java/mekanism/tools/common/ToolsItems.java
I think that's what you need, but I'm not entirely sure.

**Comment by ReikaKalseki** [comment]
No, but I forgot I had a handler for this. I do not need the registry names.

**Comment by ReikaKalseki** [comment]
Done.
