### ISSUE TITLE
Request: Chromaticraft & Agricraft

### ISSUE THREAD

**Issue by bookerthegeek** [ReikaKalseki/Reika_Mods_Issues#1035]
Request for the following:
- ChromatiCraft seeds plantable on Crop Sticks
- Require a block after the seeds in progression to be underneath for mutation and growing
- Follow the "No vanilla Farming" config option if enabled in agricraft

:) Great mod by the way. Also, what would be a full block after the seeds in progression?

**Comment by ReikaKalseki** [comment]
Crystal Blooms are not compatible in their render, function, growth states, or planting behavior.
