### ISSUE TITLE
[CC] Suggestion: Particle Renderer Color Options

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1036]
Additional color options: random for each particle, and shifting rainbow.

**Comment by ghost** [comment]
You should change the title of this, it is the exact same title as the other particle spawner suggestion you made.

**Comment by ReikaKalseki** [comment]
Cycling color has been implemented; random color will not be, mostly because of lack of GUI space but also as most randomly-generated colors look terrible, and people will want things that are not actually random without realizing it.
