### ISSUE TITLE
[CC] Cannot enter Chroma dimension.

### ISSUE THREAD

**Issue by krzysztofKKW** [ReikaKalseki/Reika_Mods_Issues#1039]
I was trying to explore the mod in creative mode.
I made portal as in Chroma Lexicon and it's active.
As i walk in it throws me back.
Am i missing something?
How does it look like: https://i.gyazo.com/ad931b992fcb2790a18148ab936245dd.mp4

**Comment by Ariaxis** [comment]
If you don't give yourself the progress up to that point then it will toss you back same as if you were in a normal game.

**Comment by krzysztofKKW** [comment]
Then can i give myself achievements from cc or make dungeons in superflat? <:U

**Comment by ghost** [comment]
Use "/chromaprog maximize all" and you'll be able to go through the portal.
