### ISSUE TITLE
Neutrons despawning

### ISSUE THREAD

**Issue by Keridos** [ReikaKalseki/Reika_Mods_Issues#104]
Please make Neutrons be destroyed/voided/set to null when they leave the chunkloaded area, this can lag a server to hell even with much blocks around a reactor when the server runs a long time.

**Comment by ReikaKalseki** [comment]
There is no way to make an entity do anything once it unloads, because by definition its code stops running. Insulate your reactor.

**Comment by Keridos** [comment]
I am fairly certain that in OpenModularTurrets we have a way to make projectiles despawn on chunk unload. Take a look here: https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/107

**Comment by ReikaKalseki** [comment]
That also causes them to be voided on world save and reload.
