### ISSUE TITLE
Players randomly get DC 

### ISSUE THREAD

**Issue by lightning02** [ReikaKalseki/Reika_Mods_Issues#1041]
http://pastebin.com/X73hi5uM
The logs say something about Dragon API

**Comment by zemerick** [comment]
Need some more of the info, such as mod list, and if there was anything specific that player was doing when he got disconnected. If they received a crash log, that would be helpful. The full server log would be quite useful, as it would include the mod list, versions, java versions, etc.

**Comment by lightning02** [comment]
Here are the logs, I really hope those can help..
https://www.dropbox.com/s/miwl1ag6wfytjz9/fml-server-3.log?dl=1
https://www.dropbox.com/s/3hnj4fao2ku8b65/latest.log?dl=1
Until [15:16:01 INFO]: 4Space remote version found: 4.1.9 it is just the loading, when galacticraft check for updates the server is already ready and done with loading

**Comment by zemerick** [comment]
Use Forge. Thermos and such are not supported.
