### ISSUE TITLE
(RotaryCraft/ReactorCraft) Van de Graaff Generator shocking not only electrolyzer

### ISSUE THREAD

**Issue by MajorGeneralRelativity** [ReikaKalseki/Reika_Mods_Issues#1042]
Hello again!

I have the following setup: http://imgur.com/kVmkcj0 . I provided it with approximately 4 GW of power, and the Van de Graaff generator began powering the electrolyzer with sufficient energy for the electrolyzer to function. However, it also began to power myself with enough energy for me to be electrocuted to death multiple times (with enough force to penetrate even my Draconic Armor and actually kill me once). I was hovering over 4 blocks from the Electrolyzer/ Van de Graaff setup, and it continued to hit me with a bolt usually every 45 seconds.

I'm running RotaryCraft/ReactorCraft 1.7.10 v15A

Please let me know if any more information is needed.

**Comment by MajorGeneralRelativity** [comment]
Um. How is this user error? There wasn't exactly an explanation

**Comment by redelman** [comment]
You don't need 4GW of power, for one. That's more than overkill. I don't think I've ever given one more than 16MW.

**Comment by TomeWyrm** [comment]
You assumed that a VDG would only power the thing you wanted it to power, not shock everything in range. The VDG shocks everything in range. Hence Not a Bug, and User Error.

"Van de Graaff Generator shocking not only electrolyzer" is intended behavior. Which should be obvious from "Not a Bug"

**Comment by MajorGeneralRelativity** [comment]
TomeWyrn, it has only electrocuted the electrolyzer before, until I updated. I conferred with others, and they agreed that it was unusual. Hence the issue creation.

Redelman, I'm trying to create a lot of deuterium

**Comment by redelman** [comment]
In some cases, it's better to use many machines rather than a single one with outrageous power requirements.

4 VDG/electrolyzer setups at 16MW each should create deuterium faster than you can use it.

**Comment by MajorGeneralRelativity** [comment]
redelman, I'm in the process of implementing that right now, but I still wanted to bring the issue to attention

Edit: 3 VDG/electrolyzers at 1.8 GW each still have a taste for human flesh

**Comment by ReikaKalseki** [comment]
> TomeWyrn, it has only electrocuted the electrolyzer before, until I updated. I conferred with others, and they agreed that it was unusual. Hence the issue creation.

This is why you read the changelogs.

**Comment by MajorGeneralRelativity** [comment]
Reika, I did read the changelog, I must have missed it

Also, now I look like an idiot for creating two user error issues in one week :(

**Comment by TomeWyrm** [comment]
Hey, I played on his dev server and I pulled user errors that I got more experienced people to come and investigate... I was teased pretty hardcore because, frankly? I'm a complete idiot sometimes :-p

At least all the times I remember having to get Reika, it was an actual error. @Builderb0y was one of the ones that got to tell me I'm a dumbass what can't think his way out of a wet paper bag (much nicer than that, of course)

**Comment by Builderb0y** [comment]
When was that? o_0

**Comment by TomeWyrm** [comment]
Remeber when I couldn't power the filling station?

**Comment by Builderb0y** [comment]
I do not remember this, no; but the filling station _is_ pretty easy to power.

**Comment by ReikaKalseki** [comment]
I remember this instance, if nothing else; If I remember correctly, its TESR was not rendering the power IO, which I fixed a few minutes later.

**Comment by TomeWyrm** [comment]
Yep that was the problem I was having. Honestly I don't recall who came over to help me most of the times I was being dense. But y'all were very helpful.
