### ISSUE TITLE
Crash on load (server)

### ISSUE THREAD

**Issue by AlexanderADM** [ReikaKalseki/Reika_Mods_Issues#1043]
I've tried installing ChromaticCraft on a FTB Infinity instance with Mekanism(core/tools/generators) and Ars Magica 2 added to it but as soon as I attempt to push the version to the server aka not simply testing in single player ( I've already taken care of the potion and biome ID conflicts between AM2/BoP and CC). I keep receiving the same error this one: 
http://pastebin.com/4ZJJgvYX 

I did a bit of research around and If I'm not mistaken this should only show up when a single player only mod is installed. I tried starting up the server with a batch of 25 extra mods added to Infinity and excluding the mods one by one I've remained with only DragonAPI and ChromaticCraft which resulted in the above crash log. I am using the latest versions for 1.7.10 and there are no conflicts between any mods on any IDs.

At this point I'm not sure what else to try as I don't really want to give up on adding your mods.
Also hope I'm not posting a duplicate.

Cheers!

**Comment by zemerick** [comment]
Try without dragonAPI and ChCr....I don't see anything of Reikas in that error, and the only mod listed in it is Ender IO.

**Comment by AlexanderADM** [comment]
I did write I started without anything of reikas and dragonapi and it works perfectly fine

**Comment by AlexanderADM** [comment]
I've looked into the CC and Ender IO compatibility and I've found a ticket posted by Reika and a version in which Ender IO actually fixed its issue which would be 2.3.0.426_beta while FTB Infinity comes with 2.3.0.424_beta. I'll update Ender IO and come back with more info. I apologize if I wasted anyones time!

**Comment by AlexanderADM** [comment]
I update Ender IO (and EnderCore) to the latest 1.7.10 version (recreated the config files) and attempted to run again with ChromaticCraft. Once again it broke down to the same point with the same error ( RotaryCraft/ReactorCraft/ElectriCraft and GeoStrata work flawlessly just ChromaticCraft has this issue).
Seeing as the error keeps on pointing to Ender IO I'll keep looking for a fix as this doesn't seem to be CCs fault afterall ( even if it works when removed)

Sorry again for the useless issue!

**Comment by ReikaKalseki** [comment]
#834
