### ISSUE TITLE
Unable to Produce Silicon Powder

### ISSUE THREAD

**Issue by Keyarose** [ReikaKalseki/Reika_Mods_Issues#1044]
Due to the nature of my mod pack there is no simple method to obtain the Rotarycraft aluminium powder required to make Silicon Powder.  All recipes for producing aluminium powder make ether Tinker's Construct powder or Immersive Engineering grit.  This is with how the recipes configure themselves by default, with none of them being altered by Minetweaker or configs.
I attempted to use the T'sC powder however it did not work:
![2016-07-16_19 58 31](https://cloud.githubusercontent.com/assets/1906772/16897733/681b14cc-4b90-11e6-8840-06556b7df732.png)

Searching through NEI shows only one way of producing Rotarycraft aluminium powder, Minechem's Chemical Synthesis Machine:
![2016-07-16_19 58 39](https://cloud.githubusercontent.com/assets/1906772/16897744/a8ab9de0-4b90-11e6-88f4-8edfd5d84a68.png)

Would it be possible to add other mod's aluminium powder as acceptable input?

**Comment by ReikaKalseki** [comment]
Aluminum powder is also produced in the Extractor, and other dusts are not usable by default.

**Comment by Keyarose** [comment]
Ah, I see.  Since NEI doesn't index extractor bonuses as production methods it wasn't appearing when I looked for it.  Thank you for pointing it out.
