### ISSUE TITLE
[CC] Void cells can't be preformattet (again)

### ISSUE THREAD

**Issue by DKnuchel** [ReikaKalseki/Reika_Mods_Issues#1047]
I already took a look into #398 but it seems that the cells are still not working.
I´m using the lastest version of chromaticraft and the lastest version of Applied energistics. (rv2 stable-10)

After trying to preformatte the void cell in the cell workbench Minecraft crashed (I just tried to put it in)
http://pastebin.com/iJvCK9ds

Talking to one of my friends who has some experience about reading error logs he said that there was sent a request to the second slot of the void cell althought it does not have a second slot.

**Comment by ReikaKalseki** [comment]
Already known and fixed.
