### ISSUE TITLE
Potion Tick Entity Crash

### ISSUE THREAD

**Issue by theTyrfing** [ReikaKalseki/Reika_Mods_Issues#1048]
Hello Reika,

I encounter a bug that causes a crash whenever I come close a the Chromicraft Crystals. They applied a potion effect in my proximity and caused a tick entity crash as seen in the crash logs. I try to fix it myself but I found I could not. Any suggestions or ways to solve this that I missed?

My Modpack: Modified FTB Evolved with Power Converters, Tardis Mod, Magical Crops, DragonAPI, Chromicraft, Rotarycraft, Reactorcraft, Meterorcraft, Electricraft, Condensed Ores (Forget the name), and Lootbags. (You may or may not have the install all of this to reproduce the bug)

Pastebin link to Crash log: [http://pastebin.com/thEUE0MG](http://pastebin.com/thEUE0MG)

Thanks in advance.

**Comment by ReikaKalseki** [comment]
You have a potion ID mismatch between client and server.

**Comment by theTyrfing** [comment]
Great, now to fix it....Will look for answers. I may comeback if I can't figure it out myself.

Thanks Reika!

**Comment by theTyrfing** [comment]
Okay, I really have no idea how to fix the id mismatch...

**Comment by TheGuyRunningSouth** [comment]
It should be in the configs. You're going to have to compare the configs from the server to your client configs. I'd start with the Chromaticraft configs since it's the Chromaticraft Crystals applying the potion effect.

**Comment by Shahelion** [comment]
Chromaticraft Crystals apply vanilla effects, though, don't they?

**Comment by ReikaKalseki** [comment]
A few are not.

**Comment by DeLourium** [comment]
Either I´ve misunderstood something or this error is hiding in another one of your mods aswell.

1. I get nearly the same crash without having ChromatiCraft installed.
Here´s the log:
http://pastebin.com/U6fzkM0B

I noticed a few differences like a minor difference in some lines of the crash log aswell as another entity being ticked in my log (here it´s a bat)

2. What´s the exact difference between client and server config?

I´ve set my potion ID´s so they don´t conflict (In the client config I guess).
Afterwards, I´ve created a singleplayer world and after a couple of minutes (I was just reading through a TiCon manual I found) It crashed.

**Comment by theTyrfing** [comment]
It is best to be patient for Reika's response, but let see if I can help.

From what I can gather, Rotarycraft adds one potion effect and does not have any native blocks that would apply any of these effects without player intervention at some point. However, what modpack are you playing so that I could replicate your results? Is this FTB?

**Comment by DeLourium** [comment]
I use FTB Infinity but I added a lot of mods on my own (mostly addons to common mods like Thaumcraft or Tinkers Construct along with some bigger mods like GregTech, Galacticraft and Pneumaticcraft)

EDIT: I forgot to mention, that -prior to experiencing this issue- I added RotaryCraft to my pack without any issues. Afterwards I temporarily disabled it and reenabled it. Then the crash started to occur (Version stayed the same)
PS: Thanks in advance
