### ISSUE TITLE
Bypass shaft junction limitation

### ISSUE THREAD

**Issue by themechman** [ReikaKalseki/Reika_Mods_Issues#1049]
Im a bit hesitant to post this as this classifies as a complete mod breaker, but shaft junctions merging have a 4 engine limitation without bedrock upgrade. I can exceed this without bedrock.

I found this by merging engine outputs through shaft power buses. This masks that the power came from an engine. Since they have only one input, you can merge 4 into the input, and then stack more.

![2016-07-18_16 14 07](https://cloud.githubusercontent.com/assets/2990361/16928809/af9e5a16-4d02-11e6-9b4d-401f88dfc726.png)

I've never used shaft power buses before honestly and just kinda goofing off. That is five, Tier 1 magnetostatics.

The angular transducer says the endpoint is receiving power only from the directly connected magnetostatic.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by themechman** [comment]
Thanks :)
