### ISSUE TITLE
[Reactorcraft] Tritium lamp usage recipe render glitch

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#105]
![2015-06-18_10 32 45](https://cloud.githubusercontent.com/assets/8153290/8246700/df8f3ddc-15f7-11e5-9004-d3379cf9e861.png)

**Comment by ReikaKalseki** [comment]
NEI stops drawing the GUI textures outside a certain box, ignoring the actual GUI size. This is annoying but entirely on its end.

EDIT:

I have an idea to try, but I doubt it will work.

EDIT 2:
It did not.

**Comment by Zedrimar** [comment]
ok.
