### ISSUE TITLE
Question: Whether to update to 1.10.2 ?

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#1051]
I found that 1.7.10 has long been unable to meet the needs of the server, BUG too much, too poor, and so on, in particular, there is no suitable server software ( KCauldron and Thermos really is ...... You know ...... Not very well ).
1.10.2 repair a lot of BUG, optimization is also good, and now Forge also a stable version, and Sponge is not perfect, but at least in the development of. I am considering whether to give up 1.7.10? Of course, we can continue to support the 1.7.10, but whether it should be considered to upgrade it?
I came to ask this question, just to consider the future development of my server. RotaryCraft played an important role in my server, I have to follow the footsteps of Reika. If you decide to keep the 1.7.10 version, I'll never think about that again, but if you decide to upgrade to 1.10.2, then I will follow.
Thank you for all you have done.

**Comment by ghost** [comment]
First of all, Reika doesn't want to update until he ABSOLUTELY has to. A lot of other mods are still updating on 1.7.10 since they don't want to make the 1.9/1.10 jump.

Secondly, 1.10 might've fixed some things but it made lighting updates terrible. They don't update 7/8ths of the time which is rather annoying.

**Comment by redelman** [comment]
98% of mods are waiting for 98% of mods to update before they will. As is
always the case with updates.

**Comment by TomeWyrm** [comment]
Actually most of the "major" mods appear to have done one of: moved past 1.7, are multi-releasing, or have ceased being maintained.

Not saying 1.7 is dead, nor that moving past it won't be an epic chore. Just saying that my observation is that 1.7 is basically at glacial movement now. Not quite dead, but not far from it either.

**Comment by ghost** [comment]
OK, I know that, I always support Rekia all the time.
