### ISSUE TITLE
Gas Turbines aren't starting after restart until I get close to them

### ISSUE THREAD

**Issue by HarrisFauntleroy** [ReikaKalseki/Reika_Mods_Issues#1052]
I've been trying to solve this issue, assuming it was chunk load based. Doesn't appear to be the case. 
I'm using both Chicken Chunk loaders and Dimension loader to ensure the world is loaded after restart. However no matter what I do, the gas turbines won't turn on till I get within like 5 blocks of them.

What on earth would be the cause of this?

**Comment by TomeWyrm** [comment]
Client/server desync most likely. Best way to test this is with some energy storage method hooked up to the engines in question, as those update on the server-side.

**Comment by HarrisFauntleroy** [comment]
Maybe, the only reason I know its not entirely chunk loading related is because the gas turbine is powering grinders filling a tank with lube, the lube is sent out via ender tanks to other places. The tank empties, then when I get close to the grinder it kicks in because when the tank is low its meant to turn on.

but ill test the energy storage idea

**Comment by ReikaKalseki** [comment]
That does not sound like desync, but more like whatever trigger system you are using does not properly reinitialize.

**Comment by HarrisFauntleroy** [comment]
Good point. Ill try setting up a standalone engine with no redstone control or anything.

**Comment by ReikaKalseki** [comment]
So...
