### ISSUE TITLE
[CC Suggestion] NEI Middle-click items into Casting Delegate

### ISSUE THREAD

**Issue by bpwhelan** [ReikaKalseki/Reika_Mods_Issues#1053]
When you middle click an item, in NEI, it gives a phantom stack of that item to your cursor. AE2 allows this to work in it's pattern terminal for manually entering in recipes. It would be nice to be able to do the same thing in the casting delegate for top-left slot that allows you to select a recipe by entering an item. Not sure if this is plausible, but it would sure beat scrolling through hundreds of recipes if you have crafted most, if not all recipes in ChC.

Expected Functionality if plausible:

![2016-07-18_21 44 02](https://cloud.githubusercontent.com/assets/8314499/16935888/db9d100c-4d30-11e6-98f8-afa7af62b15d.png)
![2016-07-18_21 44 04](https://cloud.githubusercontent.com/assets/8314499/16935889/dbb90f78-4d30-11e6-894f-a014dfcf00c8.png)
![2016-07-18_21 44 25](https://cloud.githubusercontent.com/assets/8314499/16935890/dbbb41d0-4d30-11e6-8acf-dfd023b765f0.png)

**Comment by ReikaKalseki** [comment]
That is not how the casting delegate works.

**Comment by bpwhelan** [comment]
I'm not sure if I'm misunderstanding you or you misunderstood me. I wasn't
saying this is how it should work, and it's broken. I was just trying to
suggest an alternative (when you dont have the desired item in stock) to
clicking hundreds or thousands of times in the delegate gui. Unless there
is another alternative I'm unaware of.

**Comment by ReikaKalseki** [comment]
Use shift or ctrl.

**Comment by bpwhelan** [comment]
Shift and Ctrl work great for creating multiples of one item, but I'm asking about expediting the process of selecting an item. Shift and ctrl have no functionality as i can see for scrolling through recipes.

**Comment by ReikaKalseki** [comment]
Yes, they do.

**Comment by bpwhelan** [comment]
Ahhh, took me a while to see what they did. I apologize.
