### ISSUE TITLE
pylon damage not preventable

### ISSUE THREAD

**Issue by shadoxxhd** [ReikaKalseki/Reika_Mods_Issues#1054]
a pylon was able to kill me while I was wearing draconic armor even though my entropy level was at 0%

**Comment by kolatra** [comment]
That means it's working, great!

**Comment by shadoxxhd** [comment]
could you please at least add a config option? It's not like being instakilled by pylons is a core mechanic of the mod or something.

**Comment by ReikaKalseki** [comment]
Yes, it is.

**Comment by shadoxxhd** [comment]
Is there any way I can disable this mechanic apart from bytecode modification?

**Comment by kolatra** [comment]
Yes, by progressing through the mod and accepting that you'll die once in a while.

**Comment by shadoxxhd** [comment]
It's essential that they deal damage. I don't have anything against that. I'd even be cool with the old HP=HP-5 way of things (at least you knew how close you were to your death). But now, I was at full HP + shield for a couple bursts, and then suddenly died.
What I'd like is a way to toggle the special anti-OP-armor code - the blood magic drain increase seems fine to me, but the dmg=max_float part is just trying to win a game of power creep and doesn't add anything to the gameplay.

**Comment by Builderb0y** [comment]
> I'd even be cool with the old HP=HP-5 way of things

It **still does** only do 2.5 hearts of damage per hit, but has no cool down so you can get unlucky and get hit 4 ticks in a row. Also, in future versions it will attack for 1/4'th of your maximum health so you can't survive for longer than normal by having additional max health.

**Comment by shadoxxhd** [comment]
seems like it does ... my bad. I was confused since I also have a mod that changes how health is displayed. Thanks for clearing this up, I was thinking I still had full health when I suddenly died!

**Comment by ReikaKalseki** [comment]
> bytecode modification

Do that and your pack will never be approved. **Ever**.

**Comment by 1Matthias** [comment]
Later on in CrC, there is an ability that prevents pylon damage. However, you have to get through some of CrC to get to it.

**Comment by shadoxxhd** [comment]
@ReikaKalseki I wasn't aiming to add the modified mod to a modpack anyway (just for personal use). Also, seeing all you did to prevent it (from signed files to live hash checking), trying it is probably not worth the effort.

@1Matthias I knew that. As I said above, my problem was that it seemed to me as if the pylon would one-hit me at random times.
