### ISSUE TITLE
[ReactorCraft] Thorium Fuel Cores Process Any Liquid As LiFBe Fuel

### ISSUE THREAD

**Issue by cdl1051** [ReikaKalseki/Reika_Mods_Issues#1057]
Any liquid I test piped into the top of a thorium fuel core which is hotter than 636C will be consumed and turn into Hot Beryllium Fluoride.  Lava and MFR sewage are both valid fuels in V15a.

**Comment by ReikaKalseki** [comment]
Fixed.
