### ISSUE TITLE
[ElectriCraft] [Request] Extending IC2 support to IC2 Classic

### ISSUE THREAD

**Issue by DracoScythem** [ReikaKalseki/Reika_Mods_Issues#1058]
IC2 Classic (I'm referencing to [Speigers version](http://forum.industrial-craft.net/index.php?page=Thread&threadID=11201&s=9d3ad8e8bd228e9dfcb343a4e1edbd34bb4a5460) only) currently works with ECs ic2 integration (there are no crashes), but the EU Cable is uncraftable (energy dust only exists in ic2exp wich results in a fallback) and the EU Storage Battery, as well as the EU Splitter are slightly buggy (Feeding a RBSU off another RBSU will blow it up).
The first one could be fixed by changing the recipe to use ECs energy crystal dust if ic2c is being used, whilst the second one should be fixable by changing the in/out tiers accordingly (from 4 to 7 if I remember correctly).

The differentiation between IC2exp and IC2c could be done like this:
`Loader.instance().getIndexedModList().get("IC2").getName().equals("Industrial Craft Classic")`

Also - for reference - the IC2 Classics voltage/tier table (by the formula of: voltage = 8 << tier*2):

_Tier 0 : 8 EU/t
Tier 1 : 32 EU/t
Tier 2 : 128 EU/t
Tier 3 : 512 EU/t
Tier 4 : 2048 EU/t
Tier 5 : 8192 EU/t
Tier 6 : 32768 EU/t
Tier 7 : 131072 EU/t
Tier 8 : 524288 EU/t
Tier 9 : 2097152 EU/t
Tier 10 : 8388608 EU/t
Tier 11 : 33554432 EU/t
Tier 12 : 134217728 EU/t
Tier 13 : 536870912 EU/t_

...IC2Cs IEnergyStorage...

_package ic2.api.tile;
import net.minecraftforge.common.util.ForgeDirection;
public abstract interface IEnergyStorage
{
  public abstract int getStored();
  public abstract void setStored(int paramInt);
  public abstract int addEnergy(int paramInt);
  public abstract int getCapacity();
  public abstract int getOutput();
  public abstract double getOutputEnergyUnitsPerTick();
  public abstract boolean isTeleporterCompatible(ForgeDirection paramForgeDirection);
}_

...and its IMultiEnergySource Interface (wich is being used for Transformers)

_package ic2.api.energy.tile;
public abstract interface IMultiEnergySource extends IEnergySource
{
  public abstract boolean sendMultibleEnergyPackets();
  public abstract int getMultibleEnergyPacketAmount();
}_

**Comment by ReikaKalseki** [comment]
I remember energium dust existing all the way back in 1.5.2 (which was the earliest serious use of it for me, as I was...unimpressed in 1.2.5).

**Comment by DracoScythem** [comment]
Still a thing in v16

Also: Congratulations on your MASc :smile:

**Comment by DaFuqs** [comment]
I just wanted to craft one of those, but it seems my line in CraftTweaker was automatically commented out. Bummer.

How about those two alternatives for IC2 Classic:

Obsidian Dust (obsidian in macerator, not oredicted): IC2:item.itemObsidianDust
Advanced Alloys (3 iron, bronze and tin in compressor): IC2:item.itemPartAlloy

Both require already some bit of progression in IC2C itself.

**Comment by ReikaKalseki** [comment]
I selected advanced alloy, and did the tier change.
