### ISSUE TITLE
World crash from rainbow leaf being on fire

### ISSUE THREAD

**Issue by Alrena** [ReikaKalseki/Reika_Mods_Issues#1059]
The private server we're running has hit a sudden problem. Every time a certain person logs in, the server immediately crashes. Looking through the crash report I was a little confused to find it trying to access the Mystcraft API, even though we don't have the mod installed, but looking through it further seemed to show that one of the rainbow leaves is on fire. I suspect that every time someone logs in and loads that particular chunk the server immediately crashes for some reason. For the moment we're using an external editor to remove the affected blocks, but any further information would be appreciated.

http://pastebin.com/tYuiGnaY

**Comment by ReikaKalseki** [comment]
#1018
