### ISSUE TITLE
RotaryCraft Filling Station crashes upon placing comparator.

### ISSUE THREAD

**Issue by BlueAgent** [ReikaKalseki/Reika_Mods_Issues#1060]
[TileEntityFillingStation.java](https://github.com/ReikaKalseki/RotaryCraft/blob/52ad7e1dd740208eb8a50dc25958e5f6f11d4bcb/TileEntities/Auxiliary/TileEntityFillingStation.java)

[Line 56](https://github.com/ReikaKalseki/RotaryCraft/blob/52ad7e1dd740208eb8a50dc25958e5f6f11d4bcb/TileEntities/Auxiliary/TileEntityFillingStation.java#L56) updateEntity
[Line 154](https://github.com/ReikaKalseki/RotaryCraft/blob/52ad7e1dd740208eb8a50dc25958e5f6f11d4bcb/TileEntities/Auxiliary/TileEntityFillingStation.java#L154) canFill
[Line 212](https://github.com/ReikaKalseki/RotaryCraft/blob/52ad7e1dd740208eb8a50dc25958e5f6f11d4bcb/TileEntities/Auxiliary/TileEntityFillingStation.java#L212) getRedstoneOverride

The filling station crashes with a comparator when there is no item to fill.

For getRestoneOverride(), add hasFillable() check before calling canFill()

[Crash Log](http://pastebin.com/4gfMQbs7)
RotaryCraft 1.7.10 V15a

**Comment by ReikaKalseki** [comment]
Fixed.
