### ISSUE TITLE
DragonAPI/Chromaticraft Chat Error Spam config ignored

### ISSUE THREAD

**Issue by OmegaCenti** [ReikaKalseki/Reika_Mods_Issues#1066]
\config\Reika\DragonAPI.cfg

```
B:"[L4787555C] Log errors to chat"=false
```

Expected Behavior: No errors logged to chat
Actual Behavior:
![](http://i.imgur.com/vmMcfn9.png)

To replicate, a user on server is crafting Zambarau Potion Crystals

**Comment by ReikaKalseki** [comment]
Are you absolutely certain of this? The code implies very strongly that this is not the case. And if this is on a server, the setting needs to be changed on the client.

**Comment by ReikaKalseki** [comment]
Hello?

**Comment by OmegaCenti** [comment]
Sorry, just now noticed the email and notification, I will have to get back to you on this by Sunday. My apologies for late reply
