### ISSUE TITLE
[Question|Issue?|Intentional?]ChC crashes if forestry trees/bees/butterfly modules are disabled

### ISSUE THREAD

**Issue by steelshot** [ReikaKalseki/Reika_Mods_Issues#1067]
Pretty generic question, I have the tree/bee/butterfly modules disabled as I am not going to use them or any1 on my server at all, and i'd like to retrogen only apatite for the farm. Seems to work fine if they are enabled again.

I'm presuming some research in ChC is requiring one of those modules, and it cant find the items/blocks from them because they are disabled?

Forestry 4.2.14
ChromatiCraft, LegacyCraft, ExpandedRedstone, ElectriCraft, ReactorCraft, RotaryCraft and DragonAPI are all v15a(re-updated/downloaded on july 25th).

Crash Report
http://pastebin.com/2H1XxugK

**Comment by Aivech** [comment]
Related to #983.

And yes, with Forestry installed, it requires the bees module for Crystal Hives. Whether this will change is up to Reika.

**Comment by ReikaKalseki** [comment]
To my knowledge, I have no way to identify if specific Forestry modules are available, and as such can only assume that bees are present if Forestry is. Given that this is the first such report, I also question the importance of changing this due to an apparent extreme rarity of this use case.

**Comment by steelshot** [comment]
I decided to re-enable bees, it wont hurt me too much, i just didnt need em.

Anyway thank you for answering the question
