### ISSUE TITLE
Crash using DanglingVanillaFixer-1.0.jar while attempting to remove DragonAPI and RotaryCraft

### ISSUE THREAD

**Issue by Kalbintion** [ReikaKalseki/Reika_Mods_Issues#107]
Attempting to remove DragonAPI and RotaryCraft causes world to be unusable, after looking over the main site, found the information about using the DanglingVanillaFixer-1.0.jar mod to permit clean removal of the mods. I re-added the DragonAPI and RotaryCraft into the pack, without the patch mod, and re-loaded the world to ensure no issues or conflicts would still exist and the world loaded perfectly fine. I closed the game, removed the mods and added the DanglingVanillaFixer-1.0.jar file and attempted to load the world back up, FML says missing blocks/items and I proceed, the game continues to load the world and then proceeds to crash with a Ticking memory connection, see http://pastebin.com/9YHLw0T6 for the full report. Have attempted using the fixer installed while loading worlds that were never attempted to be loaded without the mods and have had the same crashing.

For a quick reference on versions being used:
Minecraft 1.7.10
Forge 1424 (10.13.3.1424)
DragonAPI 6f
RotaryCraft 6f

For a full list of mods and versions being used:
https://docs.google.com/spreadsheets/d/1qIQYfLTU_phP1IQcBzPz6_J1GYPzEC7TNTaMnhG62Lw/edit#gid=0

**Comment by ReikaKalseki** [comment]
Unfortunately, that error log is of little help to me since the crash is
occurring in vanilla code.

That said, the error was likely a Forge version issue. The tool was written
against 1208, seems to work with 1291, and likely does not with 1400s
versions.

**Comment by ReikaKalseki** [comment]
Also, amusing note: I thought this was an email and replied to it, and GitHub automatically posted it here. O_o

**Comment by ReikaKalseki** [comment]
Your only recourse is a backup, and possibly trying again with Forge 1291.

**Comment by Kalbintion** [comment]
When did github offer email responses to issue threads? That's interesting.

I figured it was crashing in the vanilla portion of the code based on the log, but considering it was only showing up on the removal of the mods, it seemed a bit odd. Some of the mods require the liquid updates forge has done, I will attempt to try it with older forge versions as far back as possible.

It has so far crashed using FML 1395, 1401, 1424

I will be attempting to try some other versions (newer past 1424) to see if they somehow correct any issues within FML - would you say this may be a bug within FML itself and the version the mods are for?

Edit: has also failed for the latest version, 1470 and fails with the oldest legal forge version I could get to install and work with the mods, 1387 (newest version of the mods required was 1385 but the jar/installer was always corrupted)

**Comment by madolinn** [comment]
Did you try with the 1291 FML?

**Comment by Kalbintion** [comment]
see the last bit of my previous message, specifically the parenthesis information indicating the lowest version any of those mods will accept, of forge, is 1385.

**Comment by ReikaKalseki** [comment]
Then remove some mods and try with 1291.

**Comment by Kalbintion** [comment]
Not an option, removing said mods would cause their blocks and items to disappear, unless you are aware of something with forge that I am not. I will however try to come up with an alternative solution even if it means bypassing the fixer mod.

**Comment by ReikaKalseki** [comment]
Back up the world first. :P

**Comment by Kalbintion** [comment]
So be it, decided to go with testing it on 1291 - After duplicating the pack and removing the mods that relied on the fluid update, tested the world to still work on Forge 1291 and it did. Removed DragonAPI and RotaryCraft and inserted the fixer mod. World loaded without issues with the fixer mod installed. Removing the mod and the world still loaded fine (as expected) - however with the many missing blocks/items from Blood Magic and TiC

**Comment by madolinn** [comment]
It's weird that you'd be missing blocks. Blocks shouldn't be handled differently between versions of Forge (unless we've got spaghetti coders). What I expected to happen was the blocks cease to function because of Forge dependencies, but they'd remain in their temporary corrupted places.

So that's mildly unfortunate. But at least it's something a little /gamemode 1 can't fix.

**Comment by Duckfan77** [comment]
Except Kalbintion had to remove the mods, as they wouldn't load with the older forge, so the blocks were removed, the same as loading a world in vanilla.

**Comment by Kalbintion** [comment]
It's also not exactly that simple as "gamemode 1", one of the mods that had to be removed, tinkers' construct, had world gen being done with it, so all of the ores, and other worldgen blocks, it would have spawned are now gone with the removal of the mod. I also use a custom loot script via minetweaker that inserted various tinkers construct, extratic, and blood magic items into dungeon chests generation chance, so these would also have disappeared from the world.

**Comment by ReikaKalseki** [comment]
Thus the problem is indeed one of Forge version.

**Comment by ReikaKalseki** [comment]
Is this still an issue? Back when I moved to 1558 I checked and the relevant code seemed unchanged.

**Comment by Kalbintion** [comment]
I'll give it a shot over the next few days and report back.

**Comment by Kalbintion** [comment]
Just to post an update, I am doing the test today, my apologies for taking so long to get to it.

**Comment by Kalbintion** [comment]
Didnt cause issues like it had before - works as intended on forge 1558 and 1566.

**Comment by ReikaKalseki** [comment]
Even though it never changed. Lovely.

**Comment by ReikaKalseki** [comment]
A new label for you. ^

**Comment by Kalbintion** [comment]
I do want to look into why it failed before in more detail btw, I'll be doing a clean forge with only rotarycraft and dragonapi on the old forge to see if it still crashes on removal with the fixer. Hopefully it'll show if it was actually the forge version, or what in more detail was causing it. Could have been a weird mod interaction with it being removed as well.

And thanks for the new label i guess.
