### ISSUE TITLE
|Chromaticraft| Portal functioning incorrectly.

### ISSUE THREAD

**Issue by Laukannen** [ReikaKalseki/Reika_Mods_Issues#1070]
I have finished the Portal Beacon, the beam of light is shown within the middle of the Portal Rifts indicating as much, but as soon as I attempt to jump in, it just 'Trampolines' me out, as if I were stepping on a singular block of Portal Rift... with the usual heartbeat-esque sound following. I've been attempting to rule things out slowly, placement, placing leylines of different colors nearby, etc. but nothing seems to be fixing such an issue. Checking the console, there also doesn't seem to be any indication of actually 'entering' the portal, either. Am I missing something obvious, or is it bugged at all?
![2016-07-27_22 12 49](https://cloud.githubusercontent.com/assets/20212833/17192867/54d43928-5448-11e6-9f3f-91d65fabdf35.png)
![2016-07-27_22 13 02](https://cloud.githubusercontent.com/assets/20212833/17192868/54dc4488-5448-11e6-9ebe-0be181ab246d.png)
![2016-07-27_22 13 10](https://cloud.githubusercontent.com/assets/20212833/17192869/54e24c70-5448-11e6-8c4a-3bdacb543167.png)

**Comment by ReikaKalseki** [comment]
You cannot just build things in creative and expect them to work.

**Comment by Duckfan77** [comment]
To clarify what Reika is saying, you lack the required progression to make use of the portal. I'm not sure of the command used to provide all progression, but try playing around with /chromaprog to give it to yourself in order to make use of the portal.
