### ISSUE TITLE
DragonAPI/RotaryCraft V15 KCauldron

### ISSUE THREAD

**Issue by Fently** [ReikaKalseki/Reika_Mods_Issues#1074]
This is an issue with RotaryCraft or more possibly DragonAPI. Alone without any mods on my KCauldron server, it produces this big ol' error: pastebin.com/qC3ZvU26

I doubt a bug like this can be fixed on the spot but I am looking forward to a patch for maybe v16??? That'd be awesome, I wouldn't want to remove my favourite mod after all 😜

**Comment by HellFirePvP** [comment]
Reika's mods don't support KCauldron or any Bukkit+Forge server software. It's made and supported for Forge alone.

**Comment by Aivech** [comment]
We should compile a list of Forge mod alternatives to Bukkit plugins...

**Comment by kolatra** [comment]
I second that. I've gotten way too many reports for mods and mod packs from people that use Bukkit plugins. It's getting tiresome.

**Comment by Fently** [comment]
Things is, people don't always put the effort into the mods that they do in the plugins. Take ForeEssentials for example, they are developing but very slowly and what they currently have isnt nearly as nicely functional as the real Bukkit Essentials. There are just plugins there that Forge doesnt have that owners need to run a server, simple as that. I guess I'll just remove Rotarycraft then since it isn't supported anymore

**Comment by 1Matthias** [comment]
There are plenty of plugins/mods that can completely replace
Bukkit/KCauldron. Also, Bukkit has never, and probably will never be,
supported by RoC.

**Comment by Aivech** [comment]
There are alternatives to Forge Essentials, like FTBUtils. TerritoryZone is good, IC2 has a built-in shop system, AdminCommandsToolbox is good, and there's more than that...

**Comment by kolatra** [comment]
There may be things that appeal to a server owner in Bukkit plugins, but no mod or pack developer is going to support it because of the many things that these hacks break. It's impossible.

**Comment by ReikaKalseki** [comment]
The biggest problem is inertia; unless KCauldron and all alternatives become entirely unavailable, people will continue to use them purely because it is what they are used to.

**Comment by Aivech** [comment]
Now, Spigot (for vanilla servers) is genuinely useful and provides a lot of functionality that vanilla does not. And it's incompatible with Forge last I checked.
KCauldron, Thermos, and the endless Bukkit derivatives patched to "work" with Forge are less useful because Forge mods can do the same thing for far less pain.

**Comment by ghost** [comment]
@Xopharios Hi! Sir! I can fix this!
DO NOT USE KCAULDRON, please using Thermos! Thermos is trying to support any mod, and KCauldron is not updated, and KCauldron's author I don't like him(...).
In addition, if you have a certain understanding of Java, you can submit your own code!

@DaMachinator 
And, sir, I have something want to tell you:

> Yes, you are right, but there are some big problems:
> If quit using Bukkit, choose what server software and it must have PLUGINS function?
> Is it really only use mojang's server software with forge?
> You know, if there is no plugins, you can not protect the server, to achieve more functionality, such as login(like AuthMe), and Plots(like PlotSquared) and some plugins like WordGuard and more and more.
> And if there is no plug-in, how anti-cheat? Disable some items(You know some of the items are dangerous, can destroy the server and players' efforts)?
> There are many problems simply can not be expressed in words. And Reika do not upgrade to 1.8 or 1.9, only support 1.7.10. There are many excellent Mod such as IC2, TF, but they only support 1.7.10, either. (1.8 and 1.9 has Sponge, it's great but it only support 1.8+).
> And if using 1.7.10, you can only choose KCauldron or Thermos...............
> So, would you please tell me how should I do? Give up all this?
> It is obvious that all this is a contradiction.

This is a friend of the server admin said, I think it makes sense. For example, like WorldGuard, it was very useful to DISABLED the Items and PROTECT any place I want and not like FTBUtil, only can protect a Chunk. For plug-in compatibility, we have no idea for that, but for us, easy to use, powerful is the most important.

And @Xopharios , sir, please do not give up, in fact, @ReikaKalseki  is supported. Just KCauldron too long time not updated. But we have Thermos. We still have a lot of hope. Reika is not a responsible developer, he will try to solve any problem, even if he said he would not support some problem ..... Actions speak louder than words. So please go on, just like me, like everyone else. Have fun !!!

**Comment by Aivech** [comment]
> Is it really only use mojang's server software with forge?

Yes, it's really just use the vanilla server + forge.

FTBUtil can protect as many chunks as you want. Minetweaker can remove any items you want. And most mods have configs allowing you to disable destructive portions thereof. 

Why would you need a login plugin? As long as you aren't running your server in offline mode, it should be fine. 

FTBUtils allows chunk claiming. TerritoryZone should allow "plots" but don't quote me on this.

And Thermos is ALSO not supported by Reika.

**Comment by ghost** [comment]
@DaMachinator No, sir, You're wrong.
1. FTBUtil can only protect chunks, but if I want to protect a place of coordinates? It can't be done.
2. Minetweaker and Modtweaker CAN NOT support Rekia's mod, because of Items ID.
3. We must have a login plugin, Mojang's server is not very safe. A few days ago, a hacker group claimed to break the Mojang server.
4. TerritoryZone I know it, but where is Manual? We can't use a Mod with out Manual. The user is not a tester and a scout.

Yes, Thermos not supported by Reika, but if you really choose not to support the complete, this is the way to break that mods own future. 99% Mod Server Admin are using the Cauldron series (Especially large servers), Forge efficiency is low, we can not simply rely on Mod to manage the server, for a large server, it is not possible.

There are too many questions. But I support Rekia to upgrade to 1.10.2, rather than continue to adhere to 1.7.10, because there are too many contradictions.

Sir, I do not have malicious, I just elaborate my point of view, if there is any place that is not appropriate, please forgive me. :)

**Comment by Aivech** [comment]
> TerritoryZone I know it, but where is Manual? We can't use a Mod with out Manual. The user is not a tester and a scout.

[TerritoryZone Manual and Things](https://sites.google.com/site/reikasminecraft/territoryzone)
Supports coordinate protection.

**Comment by ghost** [comment]
@DaMachinator Thank you sir, but I think we need a more detailed manual.

**Comment by Aivech** [comment]
You could always ask for directions on the MCF page. 

Also, in response to 

> Minetweaker and Modtweaker CAN NOT support Rekia's mod, because of Items ID.

There is an option in the Rotarycraft configuration file to disable terrain destruction by things (although this probably will not disable the Boring Machine, Pile Driver, or Sonic Borer, as those are mining machines)

**Comment by Fently** [comment]
@SourcePowered Thank you. I have never even heard of Thermos which is very strange

@DaMachinator I have looked for many plugin alternatives while only finding a few that work up to my needs there are also smaller plugins that aren't expected to be supported by a mod. To use as an example again, Essentials is an 'essential' plugin that adds alot more functionality than the forge alternatives I have found thus far. 

For the first while I have been able to manage with Forge Alternatives, like ForgeEssentials as I said, but alas I hit walls over and over again which Is why I started looking for a bukkit forge. Found MCPC+ which I linked to Cauldron which I then linked to KCauldron. I'll try Thermos and see how that goes!

**Comment by Fently** [comment]
@SourcePowered Cool man it worked! After giving Thermos a try it was not only easier to install than KCauldron, it also works with RotaryCraft/DragonAPI and also TConstruct/Mantle. KCauldron didn't work with those two before! Thanks for the shoutout man, now I can control my server with much more ease without the worry of having to remove two important mods

**Comment by ghost** [comment]
@Xopharios You are welcome! Sir! Enjoy your time!
