### ISSUE TITLE
Exception in server tick loop  cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Reika/ChromatiCraft/TileEntity/Transport/TileEntityRift (This time with railcraft aparently)

### ISSUE THREAD

**Issue by Milii20** [ReikaKalseki/Reika_Mods_Issues#1075]
Hello!, i found a bug with chromaticraft, and i found the same problem was happening before with enderIO, and engineers toolbox, and other mods sadly, so i started taking mods out from the modpack i am playing until i found now railcraft is the problem aparently, for the record, all reika's mods are V15a and railcraft is 9.12.2.0, and taking out railcraft fixes the issue aparently

here is the crash-report
[crash-2016-07-30_21.39.12-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/392177/crash-2016-07-30_21.39.12-server.txt)

**Comment by ReikaKalseki** [comment]
#964, #845, #804
