### ISSUE TITLE
[ChromatiCraft] Not fixed Mod Interacion Recipe Lag

### ISSUE THREAD

**Issue by SeppDE** [ReikaKalseki/Reika_Mods_Issues#1076]
Hey there,

For the last versions there is something broken with GregTech 5u and ChromatiCraft.
If you look for the usage of an item who got an recipe involved in Gregtech there is an extremly lag of recipes which last up to one hour. I tested both versions of GT5u (08 and 09) which ended up the same.
If you waited one time you can instantly look for the Usage the next time. But if the server/SSP is restarted, the process start again.

Used Versions:
Forge: 10.13.4.1614
IC2-exp: 2.2.822
GT5u: 5.09.22 and 5.08.33
DragonAPI: 15a
RotaryCraft: 15a
ChromatiCraft: 15a
ElectriCraft: 15a
Reactorcraft: 15a
NEI: 1.0.5.120
CodeChickenCore: 1.0.7.47

Log GT 5.09 https://gist.github.com/SeppDE/1359f35029842dc9ffebd90ee67503b9
Log GT 5.08 https://gist.github.com/SeppDE/a5212cc1899678937c2cc62c41372560

GT-Post: https://github.com/Blood-Asp/GT5-Unofficial/issues/590
Old Post here: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/668

Perhaps the solution would be to save all values till the system get changed? (New Blocks/Items got collected?)

**Comment by ReikaKalseki** [comment]
Why did you open a new issue?

**Comment by SeppDE** [comment]
The reason was that the "old" one was called fixed and there was no post since the last update 20 days ago. But good to see that you reopen the old one. So all fine there. 
Thanks Reika. :)
