### ISSUE TITLE
DragonAPI crashing after getting into world (5-10s after starting)

### ISSUE THREAD

**Issue by Nestyy** [ReikaKalseki/Reika_Mods_Issues#1079]
I am not sure if it's solely due to DragonAPI but its the name i noticed in the log.
http://pastebin.com/MZ9ZTus8

**Comment by ReikaKalseki** [comment]
This is a JVM crash. Try giving it more memory (you are on Java x64, yes?).

**Comment by Nestyy** [comment]
Yea 64bit Java, I tried going up to 12GB (bit excessive) and it was still crashing. After messing around with my mod list for a bit it turns out it was thaumic infusion causing the crash.

**Comment by DracoScythem** [comment]
ThaumicInfusion is known to be incompatible due to the ASM Patches is applies to minecrafts internal classes (in this case namely the BlockFire). Also TheDrunkMafia declared TI on 1.7 as a testing version and thus as unsupported.

(https://github.com/TheDrunkMafia/ThaumicInfusion/issues/81)

**Comment by ReikaKalseki** [comment]
#995, #1003
