### ISSUE TITLE
ElectriCraft Problems

### ISSUE THREAD

**Issue by Fatmice** [ReikaKalseki/Reika_Mods_Issues#108]
Hello,

It's been a while but I've gotten back to playing some MC and have returned to Reika mods.  It seems EC still suffers from some nasty path recursion problems.  Strangely, /tps does not report appreciable increase in update time.  However, Opis does report a significant increase in update time, and so does VisualVM.

Line point charge is also reporting erroneous values (either 0 or max_int) depending on situations.

Please play around with the attached world and look at images for a better feel of these problems.
World is running the followings
MCP v.9.0.5
FML v7.10.99.99
MineCraft Forge 10.13.4.1448
Mods:
  DragonAPI 1.7.10 V6f
  ElectriCraft 1.7.10 V6a
  ExpandedRedstone 1.7.10 V6a
  ReactorCraft 1.7.10 V6e
  RotaryCraft 1.7.10 V6f
  CodeChickenCore-1.7.10-1.0.7.46-universal
  dimensional-anchor-59.0.3
  immibis-core-59.1.1
  immibis-microblocks-59.1.0
  MobiusCore-1.2.5_1.7.10
  NotEnoughItems-1.7.10-1.0.5.111-universal
  Opis-1.2.5_1.7.10
  redlogic-59.1.11
  Waila-1.5.10_1.7.10
  WR-CBE-1.7.10-1.4.1.9-universal

![reika-ec-path_recursion_bug](https://cloud.githubusercontent.com/assets/8956281/8319318/11b285f6-19d3-11e5-95d8-a747690211ca.png)

VisualVM(1.3.8) <a href=http://www.mediafire.com/download/f3nqe1bva7wuhod/Reika-EC-path_recursion_bug.nps>Snapshot</a>
World <a href=http://www.mediafire.com/download/wo1ncim5doogeie/EC_Battery.zip>download</a>
More <a href="//imgur.com/a/bWtrd">Images</a>

**Comment by ReikaKalseki** [comment]
Are any chunks unloading? If so, I think this is the same issue @Demosthenex already reported.

**Comment by Fatmice** [comment]
No, test world only has EC entities in two chunks.  When you load world, you are standing in those two chunks.

And why is that image not uploaded...Nvm, fixed.

**Comment by 1Matthias** [comment]
Side note. Are you Fatmice of Uranium power from Factorio?

**Comment by Fatmice** [comment]
Yes =P

**Comment by 1Matthias** [comment]
Ha! Figured. I have some fun setups involving Uranium power and Youki's. :P

**Comment by Fatmice** [comment]
A quick note, update time is heavily impacted only when batteries are full and are being asked to simultaneously charge and discharge.  A non-full battery has no impact on update time in the same situation.

**Comment by ReikaKalseki** [comment]
I think I remember fixing this for v7.

**Comment by Fatmice** [comment]
Okay, I'll see when v7 comes out.

What about the point charge being display incorrectly?

**Comment by Fatmice** [comment]
Hm, seems you're sick.  What you doing on Github then?

Get well soon. =)

**Comment by Fatmice** [comment]
Okay v7a seems to have fixed the ElectriCraft network lag.

However, deleting wire connecting a source on the network will generate this error message

[01:06:09] [Server thread/ERROR] [FML]: ELECTRICRAFT ERROR: Forge Event Bus unregistration error, network 0/0/0#[];{636057836}$[[]] could not be cleaned. If you see many of these messages, consider restarting soon.

Also, if there is a source on the network that is turned off, the voltage will either 0 or max_int.

**Comment by ReikaKalseki** [comment]
The error message is a known problem that comes out of Forge, though I just thought of a potential fix.

As for the voltage problem, please elaborate.

**Comment by Fatmice** [comment]
This seems to be a render or reporting problem.  Say there are two or more sources on the network,  if all of them are providing power, then the voltage and amp reading on the lines as reported by Waila or holding Tab is as expected.  Now turn any one of the sources off, the voltage on the lines will disappear and either turn into 0 or max_int.  However, the actual power being received by the sinks remain the same.

This behavior was present in ElectriCraft v6a and persisted into the current version v7a.  I think it is not a game breaking bug so I would classify it a low priority fix.

**Comment by ReikaKalseki** [comment]
Are you using Waila or the Angular Transducer? This counts like a client/server desync.

**Comment by Fatmice** [comment]
Confirm "network could not be cleaned" errors fixed.

Neither Waila nor Angular Transducer reports the right voltage when one of the source on the network is off while others are on.

The source from the creative industrial coil is off, the turbine is on.
![2015-07-08_19 27 46](https://cloud.githubusercontent.com/assets/8956281/8585470/bed89542-25a7-11e5-8095-116ab3ae9aaa.png)

Both on.
![2015-07-08_19 27 58](https://cloud.githubusercontent.com/assets/8956281/8585486/e4ff4982-25a7-11e5-85dd-40d480859c1e.png)

**Comment by ReikaKalseki** [comment]
Does relogging fix it?

**Comment by Fatmice** [comment]
No?  This test world is on a local server on a local client.

I found a minimal case, place two induction generators in a cross, supply one with power and leave the other one empty.  You should see 0 voltage and some amp reading when connecting that network to a sink.

**Comment by ReikaKalseki** [comment]
With extensive debugging, this too is fixed.

**Comment by Fatmice** [comment]
Confirm all problems in this ticket fixed in v7e.
