### ISSUE TITLE
FML security? 

### ISSUE THREAD

**Issue by Grassyloki** [ReikaKalseki/Reika_Mods_Issues#1081]
im adding some mods to the space astronomy pack for private use with me and my friends. when i add dragonapi the pack wont start and it leaves these errors: http://paste.feed-the-beast.com/view/71f0d5fa
Thanks for the help

**Comment by 1Matthias** [comment]
Please read the previous issues, thank you. #1077 #998 #989 (The solution, BTW, is to update fastcraft.)
