### ISSUE TITLE
ChromatiCraft Sprite Backgrounds not Transparent

### ISSUE THREAD

**Issue by darius-lam** [ReikaKalseki/Reika_Mods_Issues#1082]
@ReikaKalseki Hi I just installed ChromatiCraft but am having rendering errors with the sprites.  I am using version V15a downloaded from CurseForge and am using a Macbook Pro 2012 model.  My first thought was that it was due to transparency in the sprites, but it seems like the other sprites (the sparkles atop pylons) are rendering fine.  This is a small issue but one that I think messes up the beauty of Chromaticraft, so it would be much appreciated if there were a fix.

Here are two examples: 

![sprite_01](https://cloud.githubusercontent.com/assets/4073615/17487394/6f51c5cc-5d49-11e6-9db8-e780edf39595.png)

![sprite_02](https://cloud.githubusercontent.com/assets/4073615/17487442/aef289c8-5d49-11e6-9fa9-689cffdbfdb6.png)

**Comment by ReikaKalseki** [comment]
Your OpenGL is not handling blending modes properly. Update OpenGL, remove all other mods, and see if it still happens.

**Comment by darius-lam** [comment]
As far as I know Macs can't update OpenGL since it's provided by Apple? I will check the specific version I'm running

**Comment by 1Matthias** [comment]
Yet another reason to hate Apple... Looks like Macs are locked to one specific version of OpenGL.

**Comment by darius-lam** [comment]
Hmm... I uninstalled and re-installed the mod and for some reason it's working!  Not sure what the reason is, but things are looking much better! Thanks all.

![working](https://cloud.githubusercontent.com/assets/4073615/17500397/02615cb6-5d8a-11e6-99a6-7351d07307b6.png)
