### ISSUE TITLE
Can't push new fuel or pull spent fuel/wastes to/from fuel cores.

### ISSUE THREAD

**Issue by Cl0ne2O12** [ReikaKalseki/Reika_Mods_Issues#1084]
I've tried to use both EnderIO and Thermal Dynamics items as a means of transferring new fuel into the fuel cores and wastes into the spent fuel containers and waste disposal drums, but neither method is working. First thing I thought was that I forgot to change the redstone behavior for each method, but that wasn't the case (EnderIO Item Conduits were configured for extraction without a redstone signal, while TD Itemducts have both Servos AND Retrievers installed and redstone signals applied to each). I thought it might be an issue with EnderIO initially, which is why I tried Thermal Dynamics next, but no such luck. I know I've been able to do this in the recent past using EnderIO, so I don't know what would be different now. Any ideas?

**Comment by Yamakaja** [comment]
Could you show us your setup? And are you sure that you're inserting from the top and extracting from the bottom?

**Comment by Cl0ne2O12** [comment]
Oh boy, this is rather embarrassing. I was trying to insert from the bottom and extract from the top. I guess my memory was backwards about the setup I used before. It never even occurred to me until I saw your comment. Thanks a bunch.

**Comment by Yamakaja** [comment]
Lol, better close this report then before anybody notices xD
