### ISSUE TITLE
Fermenter Crashes Client When Making Sludge?

### ISSUE THREAD

**Issue by DeadlyHarbinger** [ReikaKalseki/Reika_Mods_Issues#1085]
Crash Log:
http://pastebin.com/w3P0Ru76
Oh. Apparently this crashed me because i wasn't powering the fermenter with redstone to make sludge, as i discovered whilst taking screenshots for this. Oh well. I'll leave this here if you want to look into it, but otherwise, just close it.

**Comment by ReikaKalseki** [comment]
This is a mod interaction. Try removing mods.

**Comment by ReikaKalseki** [comment]
So?

**Comment by ReikaKalseki** [comment]
Hello?
