### ISSUE TITLE
[CC] Weak Repeater: Lack of documentation / malfunction

### ISSUE THREAD

**Issue by Yamakaja** [ReikaKalseki/Reika_Mods_Issues#1086]
As the title indicates i cannot get a weak repeater to connect to a pylon. I have already talked to multiple people on IRC and tried many different things, but i just can't get it to work...

**Comment by HellFirePvP** [comment]
It does connect and you can draw lumen through them, as long as you're placing them on top of a log.

It doesn't display it as nicely as the "normal" crystal repeaters if you rightclick them with the elemental manipulator, if that's what you're defining as "doesn't connect"

**Comment by Yamakaja** [comment]
Now matter how i place the repeater it always makes that err noise ... I can record a video of it / stream it if you want me to ...

**Comment by HellFirePvP** [comment]
I just told you it doesn't tell you that it connects if you rightclick them with an elemental manipulator - read what i'm telling you. Just place them in a line and try to draw lumen through them.

**Comment by Yamakaja** [comment]
Oh, i thought you meant visuals with "display", i'm sorry then
