### ISSUE TITLE
chromaticraft lava river

### ISSUE THREAD

**Issue by jsrfuture** [ReikaKalseki/Reika_Mods_Issues#1089]
is there a way to remove the lava river from the top of the nether? 

If it's not the case, I would like to request that option in the config. The lag caused by this huge amount of lava flow. Unless they have a purpose beside aesthetic that i don't know.

**Comment by ReikaKalseki** [comment]
No, they do not. Non-updating liquids do not cause lag.

**Comment by Builderb0y** [comment]
The fluids it generates are NOT non-updating, as evidenced by the fact that they flow into unpopulated chunks upon generation. Regardless, this is not the main source of generation lag either. Lighting updates are. DragonAPI has a hook that allows these streams to not cause lighting updates upon generation, which helps spread them out over many ticks as the server thread periodically does random lighting updates; though this hook is currently incompatible with fastcraft, so it does not get applied if fastcraft is detected in your instance. Still, fastcraft adds its own optimizations to the lighting system; so it's better than nothing, but not as good as DragonAPI alone in this particular case.

**Comment by ReikaKalseki** [comment]
> The fluids it generates are NOT non-updating, as evidenced by the fact that they flow into unpopulated chunks upon generation

Because that causes block updates, which triggers recalculation.

> Regardless, this is not the main source of generation lag either. Lighting updates are

He is complaining about ongoing tick lag.

**Comment by jsrfuture** [comment]
i'm complaining about lag caused by chunk generation by people exploring. Once the lava have droped all the way down to the bedrock roof and stop moving it do not lag anymore. There is like a lava fall in every 2 chunk on the nether roof.  Maybe it's the lava flow maybe it's the lighting caused by the lava flow, i don't know. But without the lava river the lava fall would go away and it would'nt cause that absurb amount of lag. 

If you do not wan't to add an option to remove the lava river maybe one to remove the lava fall under them?

**Comment by ReikaKalseki** [comment]
The lava falls are a bug, caused by the way MC generates terrain.

**Comment by jsrfuture** [comment]
you know more about that then me, but doesnt that mean that the only way to get rid of it is to get rid of the lava river and the floating flowstone on top of the nether?
we use rotarycraft too, and even with the boosted jet pack we do not have any kind of lag other then this.
If you were aware of that bug, why did you choose to do it that way anyway?

**Comment by Builderb0y** [comment]
Because the bug isn't in his code. It's a vanilla bug, which he can't fix. And I've already mentioned that he did add his own code to reduce the lag they cause. (the lighting hook thing)

**Comment by jsrfuture** [comment]
yes, thanks about mentionning it with such great details, sadly you said it wouldnt work with fastcraft. The performance gain with using fastcraft is significant, in general, even if dragon api would do a better job for that particular issue. English is not my main language and i'm not a coder, it isnt always simple for me to explain what I'm trying to say.
