### ISSUE TITLE
Rotarycaft and Electrical age mod connect idea !

### ISSUE THREAD

**Issue by tvk1372** [ReikaKalseki/Reika_Mods_Issues#109]
Hy Reika I am a 27 year old Engineer boy,and a giant fan of electricity and minecraft. 
And I was thinking about Dolu's Electrical age mod and your Rotarycraft mod to work together
Is ther any way that you or Dolu make a rotational generator or dynamo that supports Electrical age power?
I think that would be awesome,because ELN mod has a tons of headroom to use energy.
And combine the Gas turbine with the eln supported dynamo it would be like a turbine generator like in a real life gas turbine powered power plant.And than you have a ton of energy to consume with the ELN mod,it would be a new power plant for minecraft.And with that power you can power a whole minecraft city to use ELN different voltage lamps,mining machine,turret cannon and other cool stuffs.
And of course you can store that energy in different types of batteries of ELN and transform in to 50v-3200V with an ELN trasformer.The Gas turbine is the storngest so I think the ideal voltage is 3200V 15KW for it.
And of course the other Rotarycraft engines can connect to it,but they  will generate less power just like in real life!
I asked Dolu about my idea yesterday late night,I am waiting for his response.
Please if is ther any way,please do this!! :(
Please answer!
What do you think?

**Comment by ReikaKalseki** [comment]
I am not against adding a generator or converter, but I would need to talk with Dolu himself.
