### ISSUE TITLE
Crystal Repeater Network Breaking on Teleport.

### ISSUE THREAD

**Issue by arceus179** [ReikaKalseki/Reika_Mods_Issues#1090]
When teleporting to another dimension, or using my advanced charm of dislocation a little bit, the repeaters suddenly break, like they become disconnected from the pylons, as well as my lumen tree. It's fixed b reloading the world but that can get tedious. Was wondering if this was a common thing.

**Comment by ReikaKalseki** [comment]
If a world unloads, everything stops.
