### ISSUE TITLE
[Chromaticraft] Balance issue : Spawner reprogrammer can configure spawners for bosses

### ISSUE THREAD

**Issue by mergendil** [ReikaKalseki/Reika_Mods_Issues#1091]
Could you add a config to blacklist some possibilities ?

Issues includes : ender dragon, wither, gaia guardian (boss), thaumcraft boss (eldritch guardian), hardcore ender expension's ender dragons

It currently allows for major progression bypass in those mods

**Comment by ReikaKalseki** [comment]
Most or all of those _are_ blacklisted.

**Comment by mergendil** [comment]
After testing, Draconic Evolution and Et futurum's Ender dragons are available, so it's a mod interaction issue (tested on Revolution 3 modpack)

**Comment by ReikaKalseki** [comment]
What are their entity registry names?

**Comment by mergendil** [comment]
etfuturum.ender_dragon and DraconicEvolution.EnderDragon   (I'm not sure if those are what you seek)

**Comment by ReikaKalseki** [comment]
Those look correct.

**Comment by ReikaKalseki** [comment]
Done.
