### ISSUE TITLE
pneumatic item pump to scalable chest, intensive on cpu when full

### ISSUE THREAD

**Issue by jsrfuture** [ReikaKalseki/Reika_Mods_Issues#1093]
the setup is boring machine ->vanila chest -> pneumatic item pump(powered by dc electric engine with redstone torch) -> rotarycraft scalable chest(powered with microturbine).

Once the scalable chest is full, 17page, the cpu go from 5% to 100% and stay there until the item pump is stoped or if we make room in the scalable chest.

I can reproduce with just vanila chest -> pneumatic item pump (powered by dc electric engine with redstone torch) -> rotarycraft scalable chest (powered with microturbine)

It only happen with scalable chest.

using forge 1558, java 8u102 on a debian 8.4 dedicated server, i'm going to try to reproduce in single player at this moment.

edit : i can reproduce in single player with forge 1558, java 8u102 on windows 7, with only mods : dragonapi and rotarycraft.

My server is using a 4790k and my single player computer is a 5820k. In single player i was able to monitor the cpu more accuratly and there was constent cpu spike when the dc electric engine is on, the spike disapear when it is off.

**Comment by ReikaKalseki** [comment]
#548
