### ISSUE TITLE
[Thaumic Infusion Crashes Dragon API] SOLVED!

### ISSUE THREAD

**Issue by MaxBernstein** [ReikaKalseki/Reika_Mods_Issues#1094]
(Using MultiMC) I click play, 10 seconds later the games crashes and it even had time to initialize the opengl window of minecraft. It crashes before the game opens. Is the first time I experience this.
http://pastebin.com/JaL1Fhyr
This is a new modpack that I'm creating (only for me and one friend, not public) and even with only dragon api it crashes. But using resonant rise 4 (ATLauncher) as base, I added Reika's mods and no crash.
My "new modpack" is pretty much equal to resonant rise 4. I guess.
It can be a easy thing or a dumb thing. But thanks for reading. ^^

**Comment by ljfa-ag** [comment]
That looks like Advanced IC2 Tools is crashing. I see no mention of Reika's mods in that crash.

**Comment by HellFirePvP** [comment]
The crashlog's modlist doesn't have any of Reika's mods, thus this crash happens even without DragonAPI.
Why are you posting that here if its not caused by any of his mods? Or did you post the wrong crashlog?

**Comment by MaxBernstein** [comment]
I posted 'cause Reika's mod crashes. If I remove Dragon API from modpack it runs. If I put it back, it gives this weird crash. And I already removed Advanced IC2 Tools. Thanks for answering ^^

**Comment by HellFirePvP** [comment]
"If I put it back, it gives this weird crash" - apparently not since the crashlog you posted _doesn't_ include any of his mods, which brings me again to the assumption you posted the wrong crashlog or that this crash is unrelated to his mods.

**Comment by MaxBernstein** [comment]
Ohhhhhhhhhhhhhhhh
Sorry my mistake, the crash that I mention with Dragon API is not on that crash 'cause for some reason it doesn't generate crash log, sorry. But here is a MultiMC Log:
http://pastebin.com/JaL1Fhyr

**Comment by HellFirePvP** [comment]
Related to #995 and #1003 - Remove Thaumic infusion

**Comment by MaxBernstein** [comment]
Yeap, worked. Thank you so much! <3
I didn't know what I was looking for so I created a new issue but thanks for helping me!

**Comment by SvEgiiVEteR** [comment]
removing mods is not the solution.
you can then any problems to fix and play without any mods
I helped this parameter
-noverify
