### ISSUE TITLE
Texture Errors

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1095]
https://gist.github.com/Zsashas/d93d770c242c076a5d9529479c6c7037

**Comment by Shahelion** [comment]
I've never really understood why these error appear, because often it says textures are missing for things that I can in fact SEE already, in-game, so they clearly aren't missing.

**Comment by Aivech** [comment]
Doesn't Reika use a special renderer instead of the regular way of making blocks?

**Comment by ReikaKalseki** [comment]
Those errors are because the blocks have no bound icons. I never bothered because they all use TESRs anyways.

**Comment by ReikaKalseki** [comment]
I am not going to bother with this.
