### ISSUE TITLE
Crash on startup with custom pack

### ISSUE THREAD

**Issue by HimitsuYami** [ReikaKalseki/Reika_Mods_Issues#1096]
I seem to be having a crash when trying to start with a new pack i'm putting together. as far as i can tell the involved mods are Rotarycraft, DragonAPI, and Mystcraft tried disabling a few other mods that errored in a previous copy of this crash to no avail.
[crash-2016-08-16_03.17.31-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/419720/crash-2016-08-16_03.17.31-client.txt)

**Comment by ReikaKalseki** [comment]
What MystCraft version are you using? This works for me.

**Comment by HimitsuYami** [comment]
mystcraft-1.7.10-0.11.0.00 i think there was a newer one i tried in a different pack but it gave me issues as well

**Comment by ReikaKalseki** [comment]
Update MystCraft.

**Comment by HimitsuYami** [comment]
Updating fixed the startup crash but what version of mystcraft should I use? The newest one crashes when I use the writing desk

**Comment by ReikaKalseki** [comment]
Take that to XComp. I use 0.12.
