### ISSUE TITLE
[RoC] Stacks of buckets filled from reservoir stay stacked

### ISSUE THREAD

**Issue by TeamDman** [ReikaKalseki/Reika_Mods_Issues#1097]
I'm not sure if this is intentional, but right clicking on a reservoir with a stack of 2 buckets can fill both buckets, draining 2L of fluid. Emptying the stack into a reservoir still yields 2 buckets worth of fluid, but right clicking on a pulse jet furnace to put jet fuel inside will yield only 1 L of fuel, and will void the extra bucket of fuel (along with the bucket)

**Comment by ReikaKalseki** [comment]
Fixed.
