### ISSUE TITLE
Ore Harvester harvests Redstone as DragonAPI:minecraft:lit_redstone_ore_technical

### ISSUE THREAD

**Issue by PaladinOne** [ReikaKalseki/Reika_Mods_Issues#1098]
This is a re-opening of #227 because I just encountered it again. v15a. Mining Redstone Ore with an Ore Harvester lights it up, then the resulting block dropped is in Lit form, which cannot be processed in a RoC Extractor.

In order to actually harvest Redstone, you kind of need to trick it by whacking it to light it, waiting a few moments, then starting to mine it and have the lit status expire during the mining time of the Harvester.

**Comment by ReikaKalseki** [comment]
Fixed.
