### ISSUE TITLE
Railcraft + Electricraft error: can't load ItemCrowbar

### ISSUE THREAD

**Issue by sapid** [ReikaKalseki/Reika_Mods_Issues#110]
The crash occurs at launch when DragonAPI, Rotarycraft, Electricraft, and Railcraft are all in the mod folder.

https://gist.github.com/sapid/29949aeb5f4c94e5b4d3

I found a related issue over at the Railcraft Github where it's marked "not railcraft." https://github.com/CovertJaguar/Railcraft/issues/622
I didn't see anything on the mod thread on MCF and couldn't find a related issue for it, so I'm not sure if @craft90 got in touch with you or not. (For anyone searching, the first line of the crash log is cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mods/railcraft/common/items/ItemCrowbar ).

According to that person, Electricraft is trying to call out to the Railcraft API and isn't finding what it's looking for. Given the stack of the crashlog, it looks like one of the mods isn't finding Buildcraft and is trying to handle that improperly. Adding Buildcraft to the mix does let everything launch correctly.

**Comment by ReikaKalseki** [comment]
Caused by: java.lang.ClassNotFoundException: buildcraft.api.tools.IToolWrench
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 47 more

RailCraft needs the BC API.
