### ISSUE TITLE
Client Crash with Shift+Right Click 

### ISSUE THREAD

**Issue by Jizanthapus** [ReikaKalseki/Reika_Mods_Issues#1102]
Client crashes when I Shift+Right Click on a Shaft Junction with a screwdriver. The shaft junction was in merge power mod and I was attempting to change to split mode. The server did not crash - only the client. Upon restarting the client and entering the server, the shaft junction was in split mode. This crash has occurred twice under similar circumstances.
RotaryCraft & DragonAPI: V15a

[Crash Report](https://paste.ee/p/a8cpb)

P.S. How does one charge the ReactorCraft Reactor CPU Remote Control?

-Thanks

**Comment by zemerick** [comment]
It looks like Weather2 is the source. Try removing that and testing.

**Comment by ReikaKalseki** [comment]
No, this is another one of those "TileEntity is null yet its TESR still runs" issues.
