### ISSUE TITLE
[Reactorcraft]whay it can't working

### ISSUE THREAD

**Issue by 657366738** [ReikaKalseki/Reika_Mods_Issues#1104]
![1](https://cloud.githubusercontent.com/assets/21245013/17977525/ad768d2c-6b24-11e6-8053-3df5ff05b2b2.jpg)
![2](https://cloud.githubusercontent.com/assets/21245013/17977535/b3b011f4-6b24-11e6-982c-e06e1932a461.jpg)
![3](https://cloud.githubusercontent.com/assets/21245013/17977544/bf259f5e-6b24-11e6-8b40-5ca35b92efd1.jpg)

**Comment by zemerick** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=1399#c28353

That touches on the details you need to know. You can search my post history there for more details.

Also: The issue tracker is for issues with the mods, not questions on how to do things. Those are best asked on the forums, where you will get faster and better responses.
