### ISSUE TITLE
Crash on Initialization for Chromaticraft

### ISSUE THREAD

**Issue by mathwiz617** [ReikaKalseki/Reika_Mods_Issues#1106]
This only occurred after I added Applied Energistics 2 to a custom pack containing Chromaticraft. The pack works fine with either AE2 or ChC being disabled, which leads me to believe it's a mod interaction bug between the two. All mods in the pack are up-to-date.

[http://pastebin.com/cySEBtWs](http://pastebin.com/cySEBtWs)

**Comment by LukaPix** [comment]
i often get this error too just try starting your game multiple times sometimes it starts

**Comment by mathwiz617** [comment]
Well, I'm trying to get this custom pack on a private server, so "sometimes" might not be good enough.

I looked in the config files for both mods, but neither one has an option to disable the interaction.

**Comment by ReikaKalseki** [comment]
#481, #931
