### ISSUE TITLE
[CC] Worldgen Crash

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1107]
This crash was odd, as instead of force-closing my client, it stayed open, but frozen. I switched over to check the console, and saw the crash...followed by the dialogue for saving a world that happens when it's paused. Never seen that before.

https://gist.github.com/Zsashas/ebff1f95bbc5c24acaa4bbd9178f4638

**Comment by ReikaKalseki** [comment]
This issue should be impossible unless someone is calling generators with a null world argument. But that stacktrace appears to be vanilla.

Can you reproduce this? Because pylons generate normally almost without fail, and I have _never_ seen this issue.

**Comment by Shahelion** [comment]
I was flying over an ocean in an Amplified world, if that matters. In the overworld. Loading up the world again right now, to see what happens.

**Comment by Shahelion** [comment]
I may have found the problem...

This pylon seems to have been sliced by a chunk border for some reason, maybe because it crashed in the middle of generating, and in addition to that, because the world is Amplified, it generated too high. First time I've ever seen this. Should probably add a height check for pylon generation, if you don't already have one. It likely hasn't come up before since not many people play on Amplified worlds.

![2016-09-01_12 25 13](https://cloud.githubusercontent.com/assets/6917535/18181285/628d4d44-703f-11e6-9a7d-853904c9a979.png)

**Comment by ReikaKalseki** [comment]
Well _that_ is new...

**Comment by ReikaKalseki** [comment]
Fixed.
