### ISSUE TITLE
[CC] Request: Pylon Worldgen

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1108]
If possible, please make them generate after as much as possible. I keep finding pylons that have been rendered unusable by things like Roguelike Dungeons, Witchery's village walls, or even just regular village houses. They still cause the colored overlay to appear, even when the actual pylon orb is completely gone.

![2016-08-31_06 23 21](https://cloud.githubusercontent.com/assets/6917535/18167948/21e8cb6a-7008-11e6-8de0-5f3305c80006.png)
![2016-09-01_05 24 51](https://cloud.githubusercontent.com/assets/6917535/18167949/21ebe20a-7008-11e6-88bf-6ad409780689.png)

**Comment by ReikaKalseki** [comment]
The bigger issue here is when generation from one chunk spreads into another and overwrites previous structures. On top of that, the pylons have very specific generation timing to prevent issues like generating in trees.
