### ISSUE TITLE
[Rotarycraft] Crash with Flywheel

### ISSUE THREAD

**Issue by VexMex** [ReikaKalseki/Reika_Mods_Issues#1111]
Version: V15 of DragonAPI, Rotarycraft, Reaktorcraft
Other Mods: FTB Infinity Evolved 2.6.0 with Mekanism
Setup:

Hydrokinetik wheel (x2)- 16:1 Gearbox(speed) - Flywheel(Gold) - Dynamometer - Grinder

As soon as the flywheel spins up my server crashes to a point it wont do anything anymore
If you want to see a video of what happened, i will have it uploaded today in my LP (link https://youtu.be/yPbrmajPlr0?t=12m35s)
Cant add crashlog because there is no, it jsut hangs up until i just exit the console, and the usual log also says absolutely nothing)

Also could reproduce this bug several times 

Another bug is a fluctuating power output of the Hydrokinetik wheel as soon as i start to stack them to the same waterfall (thats why the flywheel, to prevent the grinder from cutting the progress all the time ebcause i couldnt figure out why it would happen on this specific hydrokinetic wheel, because ive build another waterfall again with 2 stacked wheel and those are working fine)

**Comment by ghost** [comment]
Flywheels are fixed in v16.

**Comment by Builderb0y** [comment]
#1046, #1034, #820, #794, #769, #734.

**Comment by TheGuyRunningSouth** [comment]
Out of curiosity (not trying to rush anybody), how feature complete is V16?
