### ISSUE TITLE
Rotarycraft start crash

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#1112]
http://pastebin.com/T4kJj5rQ. The game close and i get this crash. I did not tried with only the dragon api. I searched in the issues but only found something about null item stacks in the config file but nothing related found on rotarycraft/dragon api config file. Also super interesting mod. Sorry for my bad english.

**Comment by ReikaKalseki** [comment]
This is a mod interaction. Try removing mods.

**Comment by ReikaKalseki** [comment]
This is in fact a duplicate of #1085.

**Comment by ghost** [comment]
Thanks for the support. The cause of the conflict was forestry version 4.2.15.63.

**Comment by ReikaKalseki** [comment]
...What changed in that version?

**Comment by ghost** [comment]
I tried with various forestry 4.0.0+ versions and all versions crashed. I did not tried any 3.0.0- version.

**Comment by ReikaKalseki** [comment]
4.2.12.60 works for me.

**Comment by ghost** [comment]
Still crash :(.

**Comment by ReikaKalseki** [comment]
Have you done anything to Forestry? Do you have a broken addon?

**Comment by ghost** [comment]
No, only forestry.

**Comment by ReikaKalseki** [comment]
...

**Comment by ghost** [comment]
I tried with the last 3.X.X version and it still crash. I'm starting to hate forestry.

**Comment by ReikaKalseki** [comment]
3 - anything will not work.

**Comment by ghost** [comment]
Suddenly, it works.
![2016-10-01_19 46 57](https://cloud.githubusercontent.com/assets/21972487/19017472/04698fa4-8811-11e6-84e3-1f21532b6c11.png)
![2016-10-01_19 47 59](https://cloud.githubusercontent.com/assets/21972487/19017473/0470a118-8811-11e6-8a1b-713fbf569764.png)

**Comment by ghost** [comment]
Really really thanks for the support man.

**Comment by TomeWyrm** [comment]
@Voidcao which version of Forestry did you end up using?

**Comment by ghost** [comment]
4.2.15.63.
