### ISSUE TITLE
Extremely high tick demand from Relay Source

### ISSUE THREAD

**Issue by Castone22** [ReikaKalseki/Reika_Mods_Issues#1114]
Replcation:
I stick down a relay source block within range some crystal relays.
As the relay source gains more power (~30% on 10/16 elements) its tick time starts to ramp up drastically, clear up to ~30ms per tick.   At this point it starts causing server timeouts.

No error log provided though if there is any way you can think of to debug this let me know, or if more information would be helpful.

Thanks for your time.

**Comment by ReikaKalseki** [comment]
This is a known issue I think I fixed in v16.

**Comment by Castone22** [comment]
Alright, thanks.
