### ISSUE TITLE
[Request] charcoal in HSLA steel production

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#1116]
Can charcoal be possibly added as a way of creating HSLA steel too? After all coal and charcoal are mainly carbon... Or will adding that off-balance something?

**Comment by Aivech** [comment]
I believe you can make coal coke with charcoal. I could be wrong, though.

**Comment by ghost** [comment]
Charcoal to coal coke was removed a while ago.

**Comment by ReikaKalseki** [comment]
Added.
