### ISSUE TITLE
Adjacency Cores drop incorrect cores when mined with Silk Touch.

### ISSUE THREAD

**Issue by Roonas** [ReikaKalseki/Reika_Mods_Issues#1118]
Mining any Chromaticraft Adjacency Core (Efficiency Augment non-inclusive) with a Silk Touch pickaxe drops a respective level Efficiency Core, rather than the original core type. 
(Yes, I understand this is not how cores were intended to be moved around!)

Reproducible: Yes
Version: v15a

**Comment by ReikaKalseki** [comment]
Fixed.
