### ISSUE TITLE
FastCraft No longer the issue

### ISSUE THREAD

**Issue by Iridescent97** [ReikaKalseki/Reika_Mods_Issues#1121]
[crash-2016-09-30_12.50.53-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/503721/crash-2016-09-30_12.50.53-client.txt)

Updated to fastcraft version 1.23 as well as CodeChickenLib from 1.1.3.138 to 1.1.3.140

It got futher, but stopped when initializing.

**Comment by HellFirePvP** [comment]
AOBD works on an outdated version of RotaryCraft's API it seems - it fails when trying to add ores to process to the Extractor, resulting in the crash you got.

Edit: The AOBD version you're running is outdated. v2.9.2 dropped support for RotaryCraft

**Comment by ReikaKalseki** [comment]
Do not create a new issue for each crash you have.

**Comment by TomeWyrm** [comment]
@Iridescent97 Continue to use this issue if any more errors occur.

First thing you need to do is update nearly all the included mods to their latest versions. 

One example of that "nearly" exception would be AE2... don't ask me which version you need to update to, but I know it's the latest 1.7 revision number, just not the latest BUILD on that revision.

My suggestion would be to use the curse voice client and use it to build a 1.7 pack with all the mods that you can get from the Resonant Rise list, to get the latest 1.7 versions of those mods that are available on curse.

You can then simply update the mod folder in the resonant rise pack and tadah! You'll almost certainly have to fix some configs afterwards, but you would anyway. Reika's mods end up conflicting with other mods' assignments for potion, biome, and formerly item/block ID's all the time (something I wish had better conflict resolution from Mojang or Forge _sigh_)
