### ISSUE TITLE
[ChromatiCraft 15a] Aspect Jar consumes phials and warded jars

### ISSUE THREAD

**Issue by Not-February** [ReikaKalseki/Reika_Mods_Issues#1123]
Right-clicking on an aspect jar with a phial of essentia or a warded jar that contains essentia(the jars I've tried were not full, not sure if it makes a difference) puts the essentia into the aspect jar, but eats the jars and phials. Since I can't hold the aspect jar in my hand and take essentia out of alembics and whatnot(it just places the jar when I right click, even though i'm not sneaking), and essentia tubes don't work to pipe things into it, it's a bit of a pain that I have to keep consuming jars or phials just to put stuff in it.

I'm using CC and DragonAPI versions 15a. AKA the latest release that I am aware of. This is being attempted on a dedicated server if it makes a difference. I doubt it's an inter-mod issue but I can provide a mod list upon request.

Please let me know if there is more information I can provide to assist in resolving this issue. I don't see anything in either the server or client logs that's out of the ordinary, so I'm not sure what to provide in that regard, if anything.

**Comment by ReikaKalseki** [comment]
This is fixed in v16.
