### ISSUE TITLE
[Void Monster] [Request] Light Source Blacklist

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1124]
It seems that the Fabric of Reality, which is used a great deal in the Dimensional Doors dimensions, counts as a light source (light in those is backwards in a way) so when a Void Monster floats up within range, the whole thing starts falling apart. Can't really set a dimensional blacklist, as the dimensions are dynamically created, and each pocket plane makes a new dimension.  Would obviously not allow vanilla light sources to be blacklisted.

A dimension whitelist instead of blacklist would accomplish a similar end result.

Third option, don't even know if this is possible, but apparently the DimDoors dimensions all use the same provider, but I don;t know if blacklisting that would work.

**Comment by Baughn** [comment]
@Zsashas Isn't the Dimensional Doors mod still 1.6.x only?

**Comment by Zsashas** [comment]
https://github.com/CannibalVox/DimDoors

**Comment by Shahelion** [comment]
Looks like the whitelist option has been implemented, so I'll go ahead and close this.

And no, there's a 1.7.10 version of DD that seems to be working just fine.
