### ISSUE TITLE
[ChromatiCraft 15a]Using the casting table on a dedicated server spams my friend's chat and console

### ISSUE THREAD

**Issue by Not-February** [ReikaKalseki/Reika_Mods_Issues#1125]
My friend has done little to no ChromatiCraft progression, and is set up relatively near me in the world. Whenever I use my casting table to create something and he is online, his chat is spammed with an error - an error that -I- myself do not get.

The log he sent me:

https://paste.ee/p/gmxqB

An image he sent me of his chat log:

http://imgur.com/S2Sal7Q

**Comment by ReikaKalseki** [comment]
The replacement of "en" - even in the middle of words - with "`<PREFERRED LANGUAGE>`" makes the log unreadable.

**Comment by 1Matthias** [comment]
Mind reposting those logs using pastebin or gist? Looks like paste.ee also
sees a bunch of stuff in the log as an email address, which it then
protects... >.<

**Comment by HellFirePvP** [comment]
That just looks like the known issue of the casting table "forgetting" the player that placed it down and thus fails for adding data to the player's NBT on clientside. It doesn't have a performance impact or anything..

**Comment by Not-February** [comment]
I will try to have my friend re-send me the log when I can instruct him on how to use another service for it(and when he is not asleep). Sorry for the inconvenience.

The main weirdness here was that it was spamming his chat with the error message, rather than just the log itself.

**Comment by HellFirePvP** [comment]
It does spam the player's chat in case it happens on clientside and not serverside.

Looking through the log it is the same as #1080 - please see the information provided for that issue, as well as the ones they are referencing if you're looking for further information.

**Comment by Not-February** [comment]
Should I still re-post the log or would that be redundant at this point?

**Comment by ReikaKalseki** [comment]
> Looking through the log it is the same as #1080

Then this is a duplicate.
