### ISSUE TITLE
[RoC/ReC/GT5 Interaction] GT-ERR-01 from rotarycraft.item.modingots.65 Magnetite Gem

### ISSUE THREAD

**Issue by PaladinOne** [ReikaKalseki/Reika_Mods_Issues#1128]
So GregTech loves to complain when other mods do things a little odd, and I'm seeing one of those right now from the shapeless crafting recipe that converts a ReactorCraft Lodestone [gemMagnetite] into a RotaryCraft Magnetite Gem. The log file for GT-ERR-01 reads "A Recipe used an OreDict Item as Output directly, without copying it before" "This is a typical CallByReference/CallByValue Error"

RoC/ReC v15a

**Comment by ReikaKalseki** [comment]
That is only an issue if someone starts modifying recipe objects reflectively, but OK...

**Comment by ghost** [comment]
Actually this leads to unavailability of lodestone in gregtech-based packs w/o minetweaker tweaks. Recipe to convert Magnetite gem to Lodestone stops working; and mining magnetite yields Magnetite Gem. V16 is still affected.

**Comment by ReikaKalseki** [comment]
Fixed.
