### ISSUE TITLE
Lost Chromaticraft progress after server restart

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#1129]
Server is small LAN server. What has changed: server IP (new hardware), added 2 mods (Ars Magica & industrialcraft). All pages are in place in my Lexicon, but all recipes I know are covered with Question marks and I am getting all the `achievements` again (starting from ground up - magic forest, hell visit, etc etc)

**Comment by HellFirePvP** [comment]
probably/most likely the same as #1113

**Comment by ghost** [comment]
Difference is, I did not get a new set of books.

**Comment by ghost** [comment]
Okay, one more restart later I have a whole new set of books, too. Bye-bye Morph.
