### ISSUE TITLE
RotaryCraft v16a/Mekanism Interaction Crash

### ISSUE THREAD

**Issue by RoloEdits** [ReikaKalseki/Reika_Mods_Issues#1131]
http://pastebin.com/2tY4QPPv

**Comment by vagaprime** [comment]
Is it best just to stay with v15 for now or is the problem fixed with v16a file on curseforge?

**Comment by ReikaKalseki** [comment]
Hopefully fixed.

**Comment by RoloEdits** [comment]
Still crashing http://pastebin.com/ADn7csQY

**Comment by ReikaKalseki** [comment]
Did you update everything to v16b?

**Comment by RoloEdits** [comment]
```
UCHIE   RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V16b.jar)
UCHIE   ElectriCraft{1.0} [ElectriCraft] (ElectriCraft 1.7.10 V16b.jar)
UCHIJ   DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V16b.jar)
UCHIJ   GeoStrata{1.0} [GeoStrata] (GeoStrata 1.7.10 V16b.jar)
UCHIJ   ExpandedRedstone{1.0} [Expanded Redstone] (ExpandedRedstone 1.7.10 V16b.jar)
UCHIE   ReactorCraft{1.0} [ReactorCraft] (ReactorCraft 1.7.10 V16b.jar)
UCHIJ   ChromatiCraft{1.0} [ChromatiCraft] (ChromatiCraft 1.7.10 V16b.jar)
```

**Comment by vagaprime** [comment]
I can confirm the crash even after updating. Hope this might help. Its the full counsel log from my own pack  from the newest launch after updating.

http://paste.ee/p/RmSay

**Comment by Aivech** [comment]
I'm running Mekanism 9.1 with all of Reika's mods (16a, didn't notice the update until just now) and am NOT getting this crash.

**Comment by vagaprime** [comment]
@DaMachinator Are you using the tools part of Mek as well. from what I saw @RoloEdits and myself are not.

**Comment by Aivech** [comment]
I have both the base mod and the Generators and Tools modules.

**Comment by vagaprime** [comment]
Then you might have the tools that Rotarycraft is looking for where as we do not.

**Comment by ReikaKalseki** [comment]
Try temporarily installing Mekanism Tools. Is that the issue?

**Comment by ReikaKalseki** [comment]
Fixed.
