### ISSUE TITLE
v16 Woodcutter: Working range, voiding saplings

### ISSUE THREAD

**Issue by PaladinOne** [ReikaKalseki/Reika_Mods_Issues#1132]
So I just updated a world from v15 to v16, and immediately my two Infinity-enchanted Woodcutters started behaving oddly.
- Search range: In v15, the Woodcutters would search a 2x3 area in front of them for whenever a Tree grew, and chop it down. In v16, only the trees with a log directly in front of the Woodcutter are getting hit.
- Saplings: The Woodcutter stores several Saplings within itself, as they drop (for re-planting). However, if a different type of saplings (such as a different color of CrC saplings) drops from the tree it's chopping, it voids the saplings it's holding and starts collecting the new type. For contrast, on v15, I was collecting large stockpiles of different Sapling colors, with each Woodcutter harvesting 6 different colors of trees.

Note: If a Woodcutter holding Saplings is broken, it drops its stored Saplings.

**Comment by ReikaKalseki** [comment]
> In v16, only the trees with a log directly in front of the Woodcutter are getting hit.

That is how it was always intended.

> However, if a different type of saplings (such as a different color of CrC saplings) drops from the tree it's chopping, it voids the saplings it's holding and starts collecting the new type.

It does not void them; it drops them. This is also intended.

It is entirely possible one or both of those was broken, but that is how I wanted it to work since 1.5 when I added the machine.

**Comment by PaladinOne** [comment]
> It does not void them; it drops them. This is also intended.

I had an Item Vacuum nearby sucking up items; it was perfectly happily picking up the logs and berries, but the Saplings were not getting dropped anywhere either I or the Vacuum would grab them. Where exactly does the Woodcutter drop those Saplings (relative to itself)?

**Comment by ReikaKalseki** [comment]
Below it, like everything else. Also, it will automatically inject to an inventory in that location.

**Comment by PaladinOne** [comment]
Ah. I had it placed on flat ground, so the items were going ???.

**Comment by ReikaKalseki** [comment]
Everywhere.
