### ISSUE TITLE
[CC] Ethereal Luma

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1133]
Two things. First, it seems to flow without causing a block update and extremely quickly, which is particularly odd looking if you pour a bucket onto an ocean. When collecting it back up, the water didn't fill in the gaps until I picked up a bucket of water and placed it again.

![2016-10-06_03 29 17](https://cloud.githubusercontent.com/assets/6917535/19149132/2f5385aa-8b75-11e6-90fb-3293eb360c01.png)

Second, only source blocks grant the Void Gaze effect (no idea what that even does) the flowing blocks seem to act like water.

**Comment by ghost** [comment]
It's intentional that you need to stand in source blocks to get the Void Gaze effect.

**Comment by ReikaKalseki** [comment]
That is a normal interaction between two Forge fluids, and the luma has an extremely low viscosity.

**Comment by Shahelion** [comment]
I had a feeling it was like that. Submitted on the off chance that it was a bug. c:
