### ISSUE TITLE
[RoC/ReC] CCE chat spam when breaking the bottom block of a Solar Tower with Sodium Heat Exchanger

### ISSUE THREAD

**Issue by PaladinOne** [ReikaKalseki/Reika_Mods_Issues#1134]
I built a Solar Tower in a SSP test world. The tower is 12 Tower blocks, the ring of mirrors, a (2 block) Sodium Cycler on top, and a Sodium Heat Exchanger on the bottom. I discovered that if the bottommost Tower block is broken (the one above the Exchanger), my chat (and log) are spammed with this error:

[14:50:35] [Client thread/ERROR] [FML/]: DRAGONAPI ERROR: Tile Entity Solar Tower @ DIM0: -370, 3, -65 [CLIENT] is throwing class java.lang.ClassCastException on update: null
[14:50:35] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ClassCastException

This error is generated at a rather rapid rate (once every tick?) until either the broken Tower block is replaced or the Heat Exchanger at the bottom is removed. (-370,3,-65 is the coordinate of the missing tower block.) This actually occurs whether or not a Sodium Cycler has been placed on top of the tower.

**Comment by ReikaKalseki** [comment]
Can you get me an actual stack trace?

**Comment by PaladinOne** [comment]
The log file (fml-client) was not printing a stack trace, it was only printing that. Where should I go to get one? DragonAPI Debug Mode?

**Comment by ReikaKalseki** [comment]
If anything is being printed to chat, it is also logged to the console.

**Comment by PaladinOne** [comment]
That's what I mean though; the standard FML log was _only_ showing that chat spam. Is there some extra setting or log file other than fml-client that I should look at to find an actual stacktrace for this?

**Comment by ReikaKalseki** [comment]
The chat spam _is_ the stacktrace.

**Comment by ReikaKalseki** [comment]
I redid solars recently and noticed no issue, so it probably has been resolved.
