### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by a-sakharov** [ReikaKalseki/Reika_Mods_Issues#1135]
server: KCauldron 1.7.10 1614.201
launch command: java -Xmx4G -noverify -jar KCauldron.jar

latest.log: http://pastebin.com/w6RBxFve
hs_err_pid8204.log: http://pastebin.com/10GjLE7x
replay_pid8204.log: http://pastebin.com/vHvmu8Pr

No crash-log created. 

If don't use "-noverify" param it crashes in other place:
latest.log: http://pastebin.com/8QYDtcRE
crash-2016-10-07_01.09.30-server.txt: http://pastebin.com/d5cndWVf

Thanks.

**Comment by HellFirePvP** [comment]
Reika's mods don't support KCauldron and won't.
