### ISSUE TITLE
Chromaticraft: Genetic insight hides pristine/ignoble info for princesses

### ISSUE THREAD

**Issue by xilni** [ReikaKalseki/Reika_Mods_Issues#1137]
As per our reddit chat, Genetic Insight is modifying the tooltip and because of [this line](https://github.com/ReikaKalseki/ChromatiCraft/blob/5666c5bf2c5facba3fc0e4f77f4850bcdb604871/Auxiliary/AbilityHelper.java#L1909) the pristine/ignoble only shows on Queens.

See http://i.imgur.com/LCT8h3t.png and http://i.imgur.com/oO7tkkd.png. One is pristine and the other isn't as per beealyzer page 2.

```
if (type == EnumBeeType.QUEEN)
    evt.toolTip.add(evt.toolTip.size(), EnumChatFormatting.YELLOW.toString()+EnumChatFormatting.ITALIC.toString()+(ReikaBeeHelper.isPristine(evt.itemStack) ? "Pristine Stock" : "Ignoble Stock"));
```

should be 

```
if (type == EnumBeeType.QUEEN || type == EnumBeeType.PRINCESS)
    evt.toolTip.add(evt.toolTip.size(), EnumChatFormatting.YELLOW.toString()+EnumChatFormatting.ITALIC.toString()+(ReikaBeeHelper.isPristine(evt.itemStack) ? "Pristine Stock" : "Ignoble Stock"));
```

Using the 16a CrC and DragonAPI of course.

**Comment by ReikaKalseki** [comment]
Fixed.
