### ISSUE TITLE
[DragonAPI v16b] Crashes on startup, references 'flower seeds' in the error?

### ISSUE THREAD

**Issue by Not-February** [ReikaKalseki/Reika_Mods_Issues#1138]
https://gist.github.com/Febilian/322403dad4edad18b129715a654e0aa8

If this is a user error I apologize, but I tried fiddling with various configs already with the same result, and it was only after updating your mods to 16b that this began to happen. It also appears that only DragonAPI and the mods that rely on it are affected.

Let me know if there is more info I can somehow provide.

EDIT: I must also add that if CaveControl has a 16b version available for download, I did not see it when I put this together. Downloading the latest version resulted in another file appended with 16a. Just to get that out of the picture.

**Comment by ReikaKalseki** [comment]
Which of [these](https://github.com/ReikaKalseki/DragonAPI/blob/master/ModRegistry/ModCropList.java#L44) are present in your pack?

**Comment by Not-February** [comment]
Out of those, in this pack are just these based on the mod names:

```
MANA(ModList.THAUMCRAFT, 0x55aaff, "blockManaPod", "itemManaBean", 0, 0, 0, 3, VarType.INSTANCE),
PAM(ModList.HARVESTCRAFT, 0x22aa22, HarvestCraftHandler.getInstance()),
ENDER(ModList.EXTRAUTILS, 0x00684A, "enderLily", 7, VarType.INSTANCE),
```

**Comment by Dulciphi** [comment]
Hi, I have the same [issue](http://pastebin.com/yijgkSGC),

Out of that list, I have: 
    BARLEY(ModList.NATURA, 0xCDB14D, "crops", "seeds", 0, 0, 0, 3, VarType.INSTANCE),
    COTTON(ModList.NATURA, 0xE366F5, "crops", "seeds", 0, 4, 6, 8, VarType.INSTANCE), 
    BERRY(ModList.NATURA, 0x55ff33, BerryBushHandler.getInstance()),
    OREBERRY(ModList.TINKERER, 0xcccccc, OreBerryBushHandler.getInstance()),
    ENDER(ModList.EXTRAUTILS, 0x00684A, "enderLily", 7, VarType.INSTANCE),

All of the above are disabled via their respective configs. Ie the items are present in NEI but not generating or craftable.

And:
    PAM(ModList.HARVESTCRAFT, 0x22aa22, HarvestCraftHandler.getInstance()),
    MANA(ModList.THAUMCRAFT, 0x55aaff, "blockManaPod", "itemManaBean", 0, 0, 0, 3, VarType.INSTANCE),

No Agricraft.

Thank you

**Comment by thorondev** [comment]
Hi, same error log as Dulciphi above. But we only have have these:
- OREBERRY(ModList.TINKERER, ...
- ALGAE(ModList.EMASHER, ...
- PNEUMATIC(ModList.PNEUMATICRAFT, ...

**Comment by Baughn** [comment]
Same error. I've got Natura, Harvestcraft and Pneumaticraft. Although Pneumaticraft should no longer have any seeds, AFAIK?

**Comment by Builderb0y** [comment]
Pneumaticcraft does still have seeds, they're just not generated in-world anymore. Plastic production has been oil-based instead of plant-based for quite a long time now, but the seeds are still there for backwards compatibility with worlds that were generated before that change.

**Comment by PaladinOne** [comment]
Similar crash. _None_ of those mods present in the pack. http://hastebin.com/inakewudux.sql

**Comment by ReikaKalseki** [comment]
I found the issue. It is a very simple fix; I slightly expanded the AgriCraft handler - one function - and since its signature (return type) depends on an AgC class, it is crashing when initializing the class.
