### ISSUE TITLE
Loading crashes since v16

### ISSUE THREAD

**Issue by Haringat** [ReikaKalseki/Reika_Mods_Issues#1139]
Hi Reika,
today I downloaded v16b (cause your mods friendly hinted me at downloading them...) and now minecraft keeps crashing at load whenever I tried to start the game (at loading before it reaches the main menu).
Crash log: https://gist.github.com/Haringat/a5910783f262177e7bc4a3fd2997c579

While that at first glance looks similar to the AE2 bug we have for a while this one cannot be worked around with just trying again.

**Comment by PaladinOne** [comment]
#1138

**Comment by ProNoob135** [comment]
I get the same issue, even with no other mods installed.
Latest version of Forge (as of 10/7/2015)

**Comment by Haringat** [comment]
@ProNoob135 Reika already fixed it. You can download v16c from curse.

**Comment by PaladinOne** [comment]
Quick turnaround. Yay.

**Comment by ProNoob135** [comment]
oh thanks lol
