### ISSUE TITLE
Chromaticraft Crash after breaking Lumen Tree

### ISSUE THREAD

**Issue by chareon** [ReikaKalseki/Reika_Mods_Issues#1141]
Chromaticraft crashed after breaking my lumen tree and a meteor tower fired.

http://pastebin.com/ezbrjR5x

**Comment by ReikaKalseki** [comment]
Bad timing perhaps, or perhaps a caching issue. Does it happen when breaking a lumen tree and making some other sort of network request?

**Comment by chareon** [comment]
I tested it again with both the casting table and waiting for the meteor tower, and I'm unable to replicate the issue at this time.
