### ISSUE TITLE
Chromaticraft Void Reed forcing Server shutdown

### ISSUE THREAD

**Issue by Keyarose** [ReikaKalseki/Reika_Mods_Issues#1142]
When looking at a Void Reed a NetworkDispatcher exception is thrown and the server is forced into shutdown.  This happens every time, and also happens with the bulb plant that grows on tree leaves.

Version 16b&c

Full fml log: https://gist.github.com/Keyarose/3cd9dc7fb9895307dd125fd452f0f81a
Relevant fml log entry(around line 108242):

> [13:00:12] [Netty Client IO #0/ERROR] [FML/factorization]: NetworkDispatcher exception
> java.lang.IllegalArgumentException: Payload may not be larger than 32k
>     at net.minecraft.network.play.client.C17PacketCustomPayload.<init>(SourceFile:38) ~[iz.class:?]
>     at cpw.mods.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:120) ~[FMLProxyPacket.class:?]
>     at cpw.mods.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:434) ~[NetworkDispatcher.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
>     at factorization.fzds.network.WrapperAdapter.write(WrapperAdapter.java:36) ~[WrapperAdapter.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
>     at mods.immibis.core.impl.NetworkingManager$FakeSpecialPacketHandler.write(NetworkingManager.java:499) ~[NetworkingManager$FakeSpecialPacketHandler.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
>     at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
>     at net.minecraft.network.NetworkManager$1.run(NetworkManager.java:174) [ek.class:?]
>     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [SingleThreadEventExecutor.class:?]
>     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [NioEventLoop.class:?]
>     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
>     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by ReikaKalseki** [comment]
This is not my doing, and that log implies Factorization may be involved.

**Comment by Keyarose** [comment]
Alright, I though it could have been a issue created by changes made to the packet listed in the change log since it wasn't happening in V15.  I've been considering dropping factorization for awhile, so I guess the time has come.

**Comment by ReikaKalseki** [comment]
It does not happen for me, and there is nothing unusual about void reeds.

**Comment by Keyarose** [comment]
I just updated to V16d and removed factorization, unfortunately the crash still happens. I noticed that both this time and the previous time it happens immediately after dragonAPI pipelines the hud font. 

New crash log entry:

> [15:24:05] [Client thread/INFO] [FML/]: DRAGONAPI: Pipelining texture from Reika.ChromatiCraft.ChromatiCraft to Textures/Font/hud_font.png
> [15:24:05] [Netty Client IO #0/ERROR] [FML/]: NetworkDispatcher exception
> java.lang.IllegalArgumentException: Payload may not be larger than 32k
>     at net.minecraft.network.play.client.C17PacketCustomPayload.<init>(SourceFile:38) ~[iz.class:?]
>     at cpw.mods.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:120) ~[FMLProxyPacket.class:?]
>     at cpw.mods.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:434) ~[NetworkDispatcher.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
>     at mods.immibis.core.impl.NetworkingManager$FakeSpecialPacketHandler.write(NetworkingManager.java:499) ~[NetworkingManager$FakeSpecialPacketHandler.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
>     at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
>     at net.minecraft.network.NetworkManager$1.run(NetworkManager.java:174) [ek.class:?]
>     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [SingleThreadEventExecutor.class:?]
>     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [NioEventLoop.class:?]
>     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
>     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
> [15:24:05] [Netty Client IO #0/INFO] [THAUMCRAFT/]: Restoring client configs.
