### ISSUE TITLE
[chromaticraft] crystal tank won't fill the last 1000 buckets *water *bedrock pipes *DPA

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1144]
The tank has stopped at 2 million buckets and won't fill the last 1000 buckets, I am using  bedrock pipes and a dew point aggregator powered by a gas turbine.

**Comment by ReikaKalseki** [comment]
Their max capacity _is_ 2M buckets.

**Comment by lAimBotl** [comment]
then I guess its a gui bug?

**Comment by ReikaKalseki** [comment]
?

**Comment by PaladinOne** [comment]
Does the GUI show 2,001,000 buckets capacity? If it does, that could be a minor GUI bug.

**Comment by InitHello** [comment]
Maybe ... bear with me here ... maybe a screenshot would be in order?

**Comment by lAimBotl** [comment]
ah sorry lol i have a screenshot 
![2016-10-12_00 49 52](https://cloud.githubusercontent.com/assets/10777735/19333941/ef197454-90ce-11e6-86ba-720d697fb024.png)

**Comment by InitHello** [comment]
@PaladinOne called it. Looks like the GUI isn't reflecting the actual max capacity.

**Comment by ReikaKalseki** [comment]
Fixed.
