### ISSUE TITLE
[CC] Ethereal Luma crash when Void Gaze is re-applied while world is still re-rendering after losing it

### ISSUE THREAD

**Issue by PaladinOne** [ReikaKalseki/Reika_Mods_Issues#1145]
(Will edit with actual crash log, posting so I don't forget it)

So I had the bright idea of going scouting by flying around with a bucket of Ethereal Luma, digging holes, and looking down through the world. Unfortunately, while doing this I encountered a long series of Exception Access Violation crashes, caused usually when I stepped out of my Luma pool, then stepped in again just after the Void Gaze effect expired and the world was frantically trying to re-render itself.

**Comment by PaladinOne** [comment]
Okay so this doesn't actually produce a Minecraft crash log because it's a JVM crash. http://hastebin.com/inewonusux.tex
... And for some unknown reason my JVM thinks I'm running windows 8.1? This is Win 10...

**Comment by ReikaKalseki** [comment]
That is likely involved, and there is nothing I can do about this.
