### ISSUE TITLE
Chromaticraft Area Breaker Crash

### ISSUE THREAD

**Issue by chareon** [ReikaKalseki/Reika_Mods_Issues#1148]
Area breaker causes a client crash when interacted with in some instances. Specifically it crashed for me when I set it to the "conical circles"? setting, and then tried expanding the "distance" (shift+rmb) on it. (I think this is the right terminology. I honestly have yet to make the Area Breaker work, and was in the process of trying to learn how when I ran into this.) It may crash with other settings as well, but definitely doesn't crash on them all. It has crashed both with and without energy in it.

Crashes in MP do not affect the server, just the client, but do affect the client every time the entity is loaded. Confirmed crashes also affect single player.

http://pastebin.com/tPccyDqQ

**Comment by ReikaKalseki** [comment]
This is either fixed or a result of something screwing with the tessellator.

**Comment by nmarshall23** [comment]
Sorry to tell you this, I too have experienced this bug, on my server.

I did have fastcraft installed, when I first caused this crash. I removed it, and still crashed.
I could not log back in untill, I used a server command to replace the area breaker block.

http://pastebin.com/pCAreZSx

**Comment by ReikaKalseki** [comment]
@freyskol Did you not see this recently?
