### ISSUE TITLE
Request: expose getSteam() to Lua

### ISSUE THREAD

**Issue by Fatmice** [ReikaKalseki/Reika_Mods_Issues#115]
I would like to request that the function getSteam() be added to the Lua Interface for blocks that transport or consume steam, for example, steam line, steam grate.

The function will allow one to monitor steam level from Opencomputer, or ComputerCraft, and regulate steam distribution.

**Comment by Fatmice** [comment]
Closing.  I'll make request on the MCF forum.

**Comment by ReikaKalseki** [comment]
Implemented as per the thread.
