### ISSUE TITLE
[Chromaticraft] Craft on startup with recent version of Forestry

### ISSUE THREAD

**Issue by TheOnlyRupert** [ReikaKalseki/Reika_Mods_Issues#1150]
Forge: 1614
Chromaticraft: 16d
Forestry: 4.2.16.64

http://pastebin.com/B1pYw98K

Mods installed:
![image](https://cloud.githubusercontent.com/assets/3703153/19394502/6ec9977c-9207-11e6-8b8e-19b88be010d5.png)

**Comment by ReikaKalseki** [comment]
[Do you have backpacks disabled](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Auxiliary/RecipeManagers/RecipesCastingTable.java#L738)?

**Comment by TheOnlyRupert** [comment]
Ahh.. yes I do... I didn't even think to reload my config files. Let me do that now to pinpoint that for you.

**Comment by TheOnlyRupert** [comment]
Enabling backpacks fixes the crash.

**Comment by ReikaKalseki** [comment]
This was fixed a long time ago.
