### ISSUE TITLE
[CC] Crash when right-clicking a Rune with a Replication Star 

### ISSUE THREAD

**Issue by PaladinOne** [ReikaKalseki/Reika_Mods_Issues#1151]
Was trying to mass-produce Repeaters. Wasn't working so I started right-clicking on the template Repeater in different ways. Then this happened.

http://hastebin.com/agubujezoc.sql

**Comment by HellFirePvP** [comment]
Persistent pastebin-link: http://pastebin.com/Zd4vkzjx

(hastebin deletes pastes 1 day or so after creation)

**Comment by Shahelion** [comment]
Hastebin link still works, btw.

**Comment by ReikaKalseki** [comment]
It works fine for me, so this must have been fixed a long time ago.
