### ISSUE TITLE
Chromaticraft Ethereal Barrier/Key suggestion

### ISSUE THREAD

**Issue by chareon** [ReikaKalseki/Reika_Mods_Issues#1152]
I've seen elsewhere you suggest that it would be difficult to implement multiple owners for ethereal barriers. Would it be difficult to make it possible to duplicate keys and then have all keys with the same id unlock the barrier? The owner would obviously still be the only one able to change the key id linked with the barrier, but this would allow barriers to be used when playing multiplayer with friends.

**Comment by ReikaKalseki** [comment]
Done.
