### ISSUE TITLE
Reika mods Java memory crash and lag spikes.

### ISSUE THREAD

**Issue by origamerpro** [ReikaKalseki/Reika_Mods_Issues#1153]
DragonAPI V16a-d
Thermos server/client minecraft
Server: End start server Java memory crash with low memory...
Client : Start world and more lags and 1 fps.
with DragonAPI v15a all good.
The problem of leakage in the memory using the latest version mod.
The client and the server uses all available memory(on server or computer) and begin to lag or crash the client to the server.
Removing mod leads all in normal and play all normal. That problem only mod.
Maybe uncompatable with Matter Override (in step recipe generation for matter).Not confirmed.
log java crash : https://yadi.sk/d/ZpuHwH7dwsQm4

**Comment by zemerick** [comment]
Thermos is not supported. You will need to start by removing that.

**Comment by origamerpro** [comment]
okay but client minecraft suppoted? big lags?
I understand the problem with a memory leak. with mod using 6+ GB memory and 0-1 fps. without - 700 mb and 100+ fps.
