### ISSUE TITLE
[ChromatiCraft/DragonAPI] Crash when burning rainbow leaves w/o MystCraft

### ISSUE THREAD

**Issue by RavynousHunter** [ReikaKalseki/Reika_Mods_Issues#1154]
[Applicable Pastebin](http://pastebin.com/p5EciLyC).

Long story short, I was traveling around my Overworld looking for underground burrows, and immediately crashed with the aforementioned error.  Apparently, a rainbow tree spawned near a lava pool or something and the burning leaves keep causing this error and subsequent crash.  I've tried twice to load the world, and the crash keeps occurring.  I don't have MystCraft installed (since its functionality is replicated by RFTools) on my instance, which may be the cause of the issues.

Looking thru ChC and DragonAPI, it seems that the integration between them and MystCraft isn't explicitly disabled if MystCraft isn't present, which might be the source of the crash.

**Comment by RavynousHunter** [comment]
ADDENDUM: Added latest (0.12.3.03) version of Mystcraft to my instance and the crash no longer occurs.

**Comment by ReikaKalseki** [comment]
I fixed this in v16.

**Comment by HellFirePvP** [comment]
line 144 in the crashlog:

UCHIJAAAA   ChromatiCraft{1.0} (ChromatiCraft 1.7.10 V16d jar)

he used the latest version.

Edit:
Adding @ModDependent at
https://github.com/ReikaKalseki/ChromatiCraft/blob/master/ChromaticEventManager.java#L865
should fix that.

**Comment by RavynousHunter** [comment]
Can confirm, am using v16d of ChromatiCraft, as well as the latest versions of all of Reika's mods.  The problem is _not_ an old version.

**Comment by ReikaKalseki** [comment]
Fixed.
