### ISSUE TITLE
Armor, held item and username clearly visible behind fluids, portals, shield block, ect...

### ISSUE THREAD

**Issue by ArthixFR** [ReikaKalseki/Reika_Mods_Issues#1157]
Using latest version of RotaryCraft (V16d) and DragonAPI (V16d) with forge 1614. Tested without RotaryCraft and DragonAPI and working.

Screenshots : 
![2016-10-16_03 43 44](https://cloud.githubusercontent.com/assets/5109234/19414629/df48e074-9352-11e6-88fd-405a960bd7ba.png)
![2016-10-16_03 44 09](https://cloud.githubusercontent.com/assets/5109234/19414630/e92e3fe4-9352-11e6-8d9c-e4bb005561e0.png)

And I think there is an other bug witch is "duplicate" graphically the item in hand : 
![2016-10-16_03 40 01](https://cloud.githubusercontent.com/assets/5109234/19414645/48414990-9353-11e6-9b3d-88238a127024.png)
![2016-10-16_03 39 58](https://cloud.githubusercontent.com/assets/5109234/19414646/53a94256-9353-11e6-8b01-3ae8dde90e4f.png)

**Comment by HellFirePvP** [comment]
The first 2 screenshots is Draconic Evolution's fault.

The 2nd 2 screenshots are known to me, yet i don't know if that's coming from Reika's mods or not since i've seen that multiple times already and afaik that also happens without his mods.

**Comment by ArthixFR** [comment]
I've just tested with only RotaryCraft and DragonAPI, same thing : 
![2016-10-16_15 43 15](https://cloud.githubusercontent.com/assets/5109234/19417865/ccb8128a-93b7-11e6-90c0-0aa7200503f7.png)
![2016-10-16_15 44 50](https://cloud.githubusercontent.com/assets/5109234/19417866/d5f78fa6-93b7-11e6-92b5-433f7d9d02c1.png)
![modlist](https://cloud.githubusercontent.com/assets/5109234/19417876/fceba5c0-93b7-11e6-941b-a0ded5598dab.png)

**Comment by ArthixFR** [comment]
@HellFirePvP This is not DraconicEvolution's fault. Just watch the other screenshots.

**Comment by Builderb0y** [comment]
Dragon API does overwrite the player renderer for donator rendering and glowing skins. I believe glowing skins render in the alpha pass, which would explain them rendering in front of portals, but it wouldn't explain why only armor is doing that, and not the rest of the skin.
