### ISSUE TITLE
Unable to load with v16d version of DragonAPI

### ISSUE THREAD

**Issue by Filvandrel** [ReikaKalseki/Reika_Mods_Issues#1160]
Hello! I can not load my game client with the latest version of Dragon API. I am assuming this is an ASM error, but I have no idea what to do with it, so I am providing a load log. I'd appreciate the help in solving this issue.

http://pastebin.com/Qz7Ac7yD

Thanks!

Edit:
It appears to be a mod conflict, cause it does run fine on clean installation. I have so far narrowed down the incompatible mod list to Applied Energistics, Biomes o' plenty, Mariculture, Twilight Forest, Waila and Fastcraft. I am still testing the other ones in my mod pack, will update when I scoop all of them.

**Comment by ReikaKalseki** [comment]
#1081 #1077 #998 #989
