### ISSUE TITLE
Entering Farlands - Getting Kicked out

### ISSUE THREAD

**Issue by devanchya** [ReikaKalseki/Reika_Mods_Issues#1161]
Upgraded our servers from 16c to 16d.   after the upgrade all casting tables could only be removed by creative.   When entering the Farlands the player is ported back to spawn 1000 blocks up.  If you enter in Creative mode it works, so the DIM is loading.

A debug of my user shows I have all the proper rights to go in.  I was able to go in prior to the upgrade.

No details in the server logs.    

Is there a way I can debug this further to provide better tests.

**Comment by ReikaKalseki** [comment]
Has player NBT/progression been lost? Have UUIDs changed?

**Comment by devanchya** [comment]
Thanks for replying Reika,
- NBT progress did not appear to be lost, doing a /chromaprog debug showed expected information
- I copied the world to a separate location, removed my user, then used chromaprog maximize all on my fresh user, still same issue
- Once removed the Casting tables work normally once rebuilt and releveled
- The FarLands dim was moved from DIM 63 to DIM 3 according to Haggle's change notes.   Moving it back to DIM 63 crashed my client, reverted back to DIM 3 with no more testing
- Entering in Godmode works
- UUIDs did not change

**Comment by devanchya** [comment]
Just did a test upgrade again and confirmed the following are happening to users:
- All Lumens is lost from the player
- Casting Tables cannot be broken
- Entering Farlands causes user to be transported back to spawn 1000 feet in the air.

**Comment by devanchya** [comment]
Found the following in the Error log on another attempt at upgrading:

`[03:27:17] [Server thread/ERROR] [FML]: A TileEntity CCchroma.table(Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
Reika.DragonAPI.Exception.MisuseException: DragonAPI or one of its subclasses or methods was used incorrectly!
The current error was caused by the following:
You cannot key a null itemstack!
        at Reika.DragonAPI.Instantiable.Data.KeyedItemStack.<init>(KeyedItemStack.java:41) ~[KeyedItemStack.class:?]
        at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.readRecipes(TileEntityCastingTable.java:573) ~[TileEntityCastingTable.class:?]
        at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.func_145839_a(TileEntityCastingTable.java:530) ~[TileEntityCastingTable.class:?]
        at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116) [aor.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496) [aqk.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
`

**Comment by ReikaKalseki** [comment]
Oh...I have an idea, but it is not a good one....@Haggle1996: What mods or items were removed?

**Comment by devanchya** [comment]
Reika let me know if you need better information than this:

Changes in 3.4.0
http://revolutionpack.info/post/340/

Changes in 3.4.1
http://revolutionpack.info/post/341/

The issue can be concentrated on the 3.4.0 release however where I can recreate the break.    There was a lot of changes in this pack, the main one being an upgrade for Reika mods 16b to 16d.  The Frar Lands Dim also changed from DIM 60 to DIM 3

**Mods Added**
- Advanced Rocketry
- libVulpes - Advanced Rocketry Dependency

**Mods Updated**
- ChromatiCraft v16d
- DragonAPI v16d
- ElectriCraft v16d
- ReactorCraft v16d
- RotaryCraft v16d
- Logistics Pipes 0.9.3-128

**Removed Mods**
- GalactiCraft and related
- Galaxy Space

**Comment by Haggle1996** [comment]
@devanchya have you tried removing Thermos from your server and then trying? I can't replicate your problem on any of my servers, upgraded or fresh, nor in my test worlds (and no one else has reported this problem, so I'd look at what makes your instance unique).

**Comment by devanchya** [comment]
The server hasn't been Thermos since the last map wipe.  It's fully Forge which is what is confusing me at the moment if no one else has reported an issue.

**Comment by ReikaKalseki** [comment]
My best guess right now is that an item previously crafted on that table or by that player no longer exists in game. For that to be possible, it would need to be disabled or its source mod removed. As there is [a limited number](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Auxiliary/RecipeManagers/RecipesCastingTable.java#L730) of non-CC items castable on the table, there are not many possibilities.

**Comment by Haggle1996** [comment]
The only mods removed during that timespan are the three Galacticraft mods and GalaxySpace (a galacticraft addon). As I don't modify your recipes, or change your content...I just don't know what it could be.

**Comment by devanchya** [comment]
Looking at the list, could someone have used the table to create some type of Tinkers item that used ore that was from Galaxy?   I don't see why that would affect all the tables, or the CrC dim.

**Comment by Haggle1996** [comment]
The only mod in Reika's list that had something removed would be TiCon. I had a custom material I added called Chromastone, which I removed before the CC v16/R3 3.2.0 cycle so that it wasn't confused with the material added by CC. And this is certainly before the 3.4.0 update you're having problems with. Potentially, you have a TiCon item with an unknown material, but TiCon handles that pretty gracefully.

**Comment by ReikaKalseki** [comment]
I notice there are armors on the list; were any armors removed?

**Comment by devanchya** [comment]
no armor changes that we can see.
I think I'm going to have to consider this a weird map corruption and call it a day

**Comment by Haggle1996** [comment]
Not from Tinkers -- all the armors have been disabled for a long time. The GalactiCraft armors were of course removed along with the mod.

**Comment by ReikaKalseki** [comment]
@devanchya Did you craft any of them?

**Comment by devanchya** [comment]
One of my players may have.  There's 34 regulars

**Comment by ReikaKalseki** [comment]
This is going to be untraceable...
