### ISSUE TITLE
Lumen Beacons troubles with Lumen Tree

### ISSUE THREAD

**Issue by chareon** [ReikaKalseki/Reika_Mods_Issues#1163]
Lumen Beacons seem to have troubles connecting with lumen trees (or at least enhanced lumen trees).

A storage crystal charger placed on the source side will draw through the repeaters from the tree correctly. A charger placed on the remote side will not draw lumens for a colour if the cached source is from the tree. If the tree is disabled it will start to work.

**Comment by ReikaKalseki** [comment]
They are not supposed to be connected directly.
