### ISSUE TITLE
[CC] Suggestion: Second, non-resetting Chroma dimension

### ISSUE THREAD

**Issue by keybounce** [ReikaKalseki/Reika_Mods_Issues#1164]
So I understand that the Chroma Dimension normally has puzzles that people have to solve. And, in multiplayer, that means it must reset in order for new people to be able to solve the puzzles.

But I've also noticed that people want to build a base out there for the pretties.

Suggestion: Have a second Chroma Dimension that does not have any of the puzzles, but does have the other resources/things, that does not reset, and can be used for building a base / mining CC resources.

**Comment by ghost** [comment]
How would you even get to the second dimension?

**Comment by HellFirePvP** [comment]
Wouldn't make much sense lore-wise

And on second thought, the rendering there is already quite expensive. now imagine having your whole base there. i can already see the fps disappear.

**Comment by Barhandar** [comment]
Can't you just spatial-pylon part of the dimension away, or copy it with a Builder?

**Comment by ReikaKalseki** [comment]
> Can't you just spatial-pylon part of the dimension away, or copy it with a Builder?

No, because most of what makes it what it is are the large-scale terrain, the biomes, or the atmospheric rendering.

> the rendering there is already quite expensive

I actually get better FPS in the dimension than I do in the overworld.

However, this is not happening:

> Wouldn't make much sense lore-wise
> 
> How would you even get to the second dimension?

**Comment by keybounce** [comment]
How to get there: After completing all 16 puzzles, you unlock a knowledge that corresponds to a stable area in the chroma dimension, and a slightly different portal -- you've gone from an unstable portal to a stable one.

**Comment by ReikaKalseki** [comment]
At that point you are not going to be moving your base.
