### ISSUE TITLE
[CC] Crystal Orchestra drops nothing when broken

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1165]
I have tried with a diamond pickaxe, a silk-touch TiCon pickaxe, and a Matter Overdrive Omni Tool. I've lost two Orchestras this way so far.

**Comment by ReikaKalseki** [comment]
What about a silk-touch vanilla pick?

**Comment by Shahelion** [comment]
Will try this soon. Will report back within 3 hours.

EDIT Never promise times. Always disappointment.

**Comment by ReikaKalseki** [comment]
![](http://i.imgur.com/MiSTkCK.png)

**Comment by Shahelion** [comment]
Ok, so did some testing just now...

Diamond pickaxe with Silk Touch: works
TiCon pickaxe with silk touch: does not work

TiCon Bedrock pickaxe (RoC bedrock) with silk touch: doesn't even break it, destroyed the tool, and hurt me by half a heart. What the hell? I only tried this one because of the "infinite" durability and absurd mining level, just to make sure I actually could.

**Comment by ReikaKalseki** [comment]
See #1166. And TiC tools are not "Enchanted" per se.
