### ISSUE TITLE
[RoC] Bedrock Tinkers' Construct Tools are not only useless, but dangerous

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1166]
Attempting to use several different tools, made entirely out of bedrock alloy parts. Shovel on dirt, pickaxe on stone, all break completely on the first hit, but with two differences.

1: It doesn't even break the block I was trying to harvest
2: The tool doesn't become "broken" and require repairs, it vanishes entirely

The tools say they have effectively infinite durability, and absurdly high mining level. Maybe it's too high?

https://gyazo.com/caf9d4cc453b634a8c90eee41d2106bc

**Comment by ReikaKalseki** [comment]
Several tool parts are disabled as RotaryCraft already has native bedrock tools. Tools that are spawned in with those parts destroy themselves.
