### ISSUE TITLE
[RoC] Furnaces powered by Friction Heater still accept fuel w/ automation

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#1168]
Example: rubber (rubber drops from MFR can be used as fuel), when inserted via pipes into furnace - it gets into lower slot.
Workaround is to fill slots with some kind of fuel preimptevely.

**Comment by ReikaKalseki** [comment]
This is not possible to change.

**Comment by Builderb0y** [comment]
So put things into the top of furnaces, not the sides. Unless another mod is overwriting its ISided behavior, the fuel slot isn't accessible from the top.
