### ISSUE TITLE
minor github issue- "useful TNT" label never used in any issue.

### ISSUE THREAD

**Issue by 321nick** [ReikaKalseki/Reika_Mods_Issues#1169]
as the title says, it has never been used in any closed or open issue
is its existence needed? i'm sorry if this issue is wasting your time but i mean, if it has no apparent purpose then surely it can just be removed, if possible? 

also, off topic but do you know where the 1 github issue was with the guy on the server that had the recipe to grind canola seeds disabled or something , and his base got destroyed? offtopic i know, but still.

i am so sorry if i wasted your time with this.

**Comment by Aivech** [comment]
GitHub administration wiped the accounts of the server administrators - the issue no longer contains their posts.

**Comment by ReikaKalseki** [comment]
> as the title says, it has never been used in any closed or open issue
> is its existence needed? i'm sorry if this issue is wasting your time but i mean, if it has no apparent purpose then surely it can just be removed, if possible? 

Why would "noone has reported a UsefulTNT error" ever be the same as "there is no point for having a UsefulTNT tag"?

**Comment by 321nick** [comment]
oh, well in that case, what is its purpose?

**Comment by redelman** [comment]
The same as the Rotarycraft and Reactorcraft labels. To tag issues reported from that mod.

**Comment by 321nick** [comment]
OH! i forgot @ReikaKalseki  was making a mod called useful tnt. my apologies.
