### ISSUE TITLE
Ask for Repost Permission

### ISSUE THREAD

**Issue by ExtraMeteorP** [ReikaKalseki/Reika_Mods_Issues#117]
Hi, my name is Meteor, I really like your mod. There are just so many useful machines and funny items ! I wonder if I can repost this mod on MCBBS which is the largest Chinese minecraft forum. Due to the barrier of language, most Chinese players are not able to play or even find this great mod. Thus I would like to introduce this mod to more Chinese players so that they can enjoy your mod as well. I will also help with the zh_CN.lang file update on your Github.
The entire repost will obey the rules list below and your own special requests.
I will NOT take any credits of the mod and I will clearly state your official website (Curseforge and Github) at the head of my repost page.
I will give the official download link directly and clearly note that "This is the official download link, please click here first"
(Optional) In case of the network firewalls (government policy stuff...) and net work speed, I probably prepare another mirror link for backup. The mirror will direct to a Ad-free page (very like Dropbox). 
Last but not the least, I will not use this mod to get profit/benefit in terms of money, etc... And I will clearly state that anyone who use this mod must not use it to make money.
I will be really appreciate if you can give me the permission.
Anyway, thank you for bring us such an amazing mod and so much fun.

**Comment by ReikaKalseki** [comment]
Is Google Sites enabled in China? If so, all you need is to link to my downloads page. Even if they do not understand English, mod titles and URLs are fairly obviously download links. We could also try offering some sort of non-english version of a page (assuming Google Sites does not already have a built-in "language" feature, something I would expect).

**Comment by ExtraMeteorP** [comment]
Mediafire and Google Sites have been blocked by government, can you provide a download link on CurseForge?

**Comment by ReikaKalseki** [comment]
CurseForge currently has license issues - namely voiding most of mine the instant my mods go on it - making that not really an option.

That said, I am open to providing access to China. Perhaps an alternate hosting on my end, and then some alternative link repository? What sites _are_ available in China?

**Comment by 1Matthias** [comment]
If you want, I can look at filehosting on my server. It would not be that
hard, and I have unlimited data, although there is a bandwidth cap.

**Comment by ReikaKalseki** [comment]
Would it be available in China?

**Comment by 1Matthias** [comment]
Eeh. I truly do not know the firewall specs that China has set up, so...

**Comment by ExtraMeteorP** [comment]
One Drive is available in China

**Comment by ReikaKalseki** [comment]
Is that helpful?

**Comment by trajing** [comment]
Well, filehosting. Besides that... IDK. I don't use OneDrive that much.

**Comment by ReikaKalseki** [comment]
What would the link repository be?

**Comment by ExtraMeteorP** [comment]
MEGA is also okay, put the download link on the minecraftforum

**Comment by ReikaKalseki** [comment]
MCF is available?

**Comment by ExtraMeteorP** [comment]
Yes

**Comment by ReikaKalseki** [comment]
In that case, the best idea might be to have separate download links and put them in a spoiler in my post.

**Comment by ExtraMeteorP** [comment]
That's great, thx for doing that

**Comment by ExtraMeteorP** [comment]
https://github.com/ExtraMeteorP/Reika_Mods_ChineseLocalization
The chinese localization of your mods.

**Comment by ljfa-ag** [comment]
Has this been resolved now? Do you have the downloads?

**Comment by ReikaKalseki** [comment]
v8 will be posted on CurseForge, which will fix this (as well as apparent similar issues in Brazil).
