### ISSUE TITLE
Crash on Startup with ExtraPlanets 1.0-Pre3.7.0

### ISSUE THREAD

**Issue by MaxineBean** [ReikaKalseki/Reika_Mods_Issues#1170]
Mod versions: 
Reika's Mods: v16D
ExtraPlanets: 1.0-Pre3.7.0

Description: Crash on startup of either client or server. I know ti is ExtraPlanets because I just updated from ExtraPlanets 1.0-Pre 3.1.6.13 to ExtraPlanets 1.0-Pre3.7.0. 

Reproducing the crash: Launch the client or server with these mods.

Crash reports: https://gist.github.com/MaDmaxwell311/1459d033214382f9e43d8795bc919dea

NOTE: I have already reported this to ExtraPlanets Dev, and he requested I report this here as "Its a dragon api issue, im not doing anything apart from registering blocks and items and ore dictionary stuff which is all vaild"

**Comment by ReikaKalseki** [comment]
Is he registering any ores as both a vanilla type and a modded type?

**Comment by MaxineBean** [comment]
No idea, @MJRLegends Would know though.

**Comment by MJRLegends** [comment]
@ReikaKalseki What you mean you can find all my source, https://github.com/MJRLegends/ExtraPlanets

**Comment by MJRLegends** [comment]
Found the issue, a fix will be out for my addon in the next hour, sorry to waste your time @ReikaKalseki
