### ISSUE TITLE
Feature request: config options to disable integration with other mods

### ISSUE THREAD

**Issue by maximumsomething** [ReikaKalseki/Reika_Mods_Issues#1173]
Often, some obscure issue in a mod results in it—or another mod—being incompatible with how DragonAPI wants to interact with it (for example: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1172), or, DragonAPI is incompatible with the version of another mod that you're using (ex: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/229) and you don't really need interaction with that particular mod. A simple config would really help in that case.

**Comment by ReikaKalseki** [comment]
No.

**Comment by maximumsomething** [comment]
Can you explain why not?

**Comment by ReikaKalseki** [comment]
I have no intention of giving options that disable content.

**Comment by maximumsomething** [comment]
There are options that disable non-essential content already. Why is this so bad? (eg item cannon, light bridge)
