### ISSUE TITLE
[RotaryCraft] Liquid Pipe instantly bursts when placed next to/under certain tanks from other mods full of fluid

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1174]
Note that it's not tank instantly pushing too much of fluid into the pipe, it happens with tanks that cannot push fluid at all. Specifically affected are ExU drums (with any fluid), AgriCraft water tanks, and RailCraft water tanks (which normally push fluids into horizontally adjacent other tanks, but don't into the liquid pipe). Presumably anything that contains more than the pressure-capacity of the liquid pipe will burst it.

The liquid pipe refuses to drain lubricant from a drum (but lubricant pipe works), so it must be on RoC's side.

**Comment by Rubyheart** [comment]
Lubricant won't go into a liquid pipe at all.  That's why lubricant pipes exist.

**Comment by redelman** [comment]
TE tanks are affected too, but I was smart and put a bedrock pipe under them. Really don't see how this is a bug. User error more than anything, IMO.

**Comment by zemerick** [comment]
Indeed, everything mentioned so far is as it's designed.

**Comment by Barhandar** [comment]
> Really don't see how this is a bug.

The pipes aren't supposed to _pull_ fluids from these tanks at all.

> Lubricant won't go into a liquid pipe at all. That's why lubricant pipes exist.

Lubricant is only involved there to check whether it was the pipe or the tank pushing too much water.

**Comment by ReikaKalseki** [comment]
> The pipes aren't supposed to pull fluids from these tanks at all.

Yes, they will, if placed accordingly.

**Comment by Barhandar** [comment]
> Yes, they will, if placed accordingly.

Please mention that (along with "they'll try to pull the entire amount of fluid contained in the tank" and "they'll instantly burst if that amount happens to be higher than pressure limit for the pipe") in the handbook.

**Comment by ReikaKalseki** [comment]
> they'll try to pull the entire amount of fluid contained in the tank

They do not.

> they'll instantly burst if that amount happens to be higher than pressure limit for the pipe

Are their pressure limits not stated?

**Comment by Barhandar** [comment]
> They do not.

Then why do they _instantly_ burst until the fluid amount in the tank is brought lower than pressure limit?

> Are their pressure limits not stated?

Not as the exact amount required to reach that pressure in 1 block, no. Which is only visible if you check how much fluid was drained from the tank during the 1 tick that pipe existed for.

**Comment by ReikaKalseki** [comment]
> Then why do they instantly burst until the fluid amount in the tank is brought lower than pressure limit?

It is not instant unless the difference happens to be large enough that the first-tick amount causes a pressure excess. Either way, they do not pull the entirety of a tank, and this fact is itself the root of numerous bug reports and complaints about my pipes not fully draining tanks.

> Not as the exact amount required to reach that pressure in 1 block, no. Which is only visible if you check how much fluid was drained from the tank during the 1 tick that pipe existed for.

There is no "max amount" of fluid coded for a pipe. I calculate pressures realistically - using the ideal gas law, for example, for gases - and that means taking into account multiple variables including temperature and fluid type.
