### ISSUE TITLE
[CC] Excavation Star, Fortune V, and Chromaflora

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1175]
It seems that the effect of Fortune V is not applied to all chromaflora, only some of them. For example, using my enchanted star on an Aura Bloom gives me a much larger amount of Aura Dust, whereas using it on an Enderflower only gives me a single Motive Dust, same with the Resonant Clover.. With Luma Beans, it's hard to tell if it's being increased or not, or just slightly.  Haven't tested some of the others yet.

EDIT: Alright, further testing results:

Broke two of each plant, one by hand and one with the star. Each plant gave a single dust when broken by hand, except Vibrant Pods, which seem to give 2 every time, or Essence Lilies which give 4.

Fortune amounts:

Aura Bloom: 11
Resonant Clover: 1
Enderflower: 1
Luma Lotus: 1
Essence Lily: 52! c:
Void Reeds: 1
Vibrant Pod: 8
Element Bulbs: 27
Aura Ivy: 1
Radiance Bush: 26

I couldn't find any Rock Flowers to test, and I have no jungle for Ether Berries. It seems I also have a single plant left to discover... yay.

Overall, seems rather hit-and-miss. Unless there is some reason as to why it only works on some of them...

**Comment by HellFirePvP** [comment]
Intended.

Hint: some are farmable, some are not.

**Comment by Shahelion** [comment]
I guess that makes sense, although the Luma Lotus seems to be the exception...

Also those Essence Lily drops...so much. So, so much...

Still, shouldn't Fortune V at least increase it from ONE?
