### ISSUE TITLE
Dragon Api Crop list crash

### ISSUE THREAD

**Issue by Reginald-Halifrax** [ReikaKalseki/Reika_Mods_Issues#1176]
I'm not positive whats happening here... i was trying to get Chromaticcraft for a mod pack i play on with some pals of mine. I test it on the server before everything else. first i had some biome conflicts but that wasn't a a problem so i fixed that.

But Dragon Api crashed and returned this report... any help would be appreciated. if its my fault let me know heh.

[Error.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/551643/Error.txt)

If you need the RAW output from the server and not the report let me know.

**Comment by Reginald-Halifrax** [comment]
I should mention anything involving magical crops and

**Comment by Reginald-Halifrax** [comment]
I should mention Magical crops and actually addition are brand new to it as well (tested the server without chromaticcraft and dragon API and it launched just fine so it isn't them)

**Comment by Reginald-Halifrax** [comment]
Tested the other mods function so that leaves dragonapi having some issue that I don't see where it would be coming from

**Comment by ReikaKalseki** [comment]
Try without MagicCrops.

**Comment by Reginald-Halifrax** [comment]
[Error-2.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/554196/Error-2.txt)

Returned the same error...

**Comment by ReikaKalseki** [comment]
Try removing other mods with crops in them.

**Comment by Reginald-Halifrax** [comment]
ive removed 7 mods so far in attempt to spot a cause with no change. there are so many mods in here i cant even recall what ones make crops anymore. Why the reliance on checking other mods crops exactly? just to add support for them?

**Comment by Reginald-Halifrax** [comment]
Well i think i ultimately narrowed down the crash to 2 files simply being out of date and dragon api not being able to communicate with them... Agricraft and Enderio... so i have magical crops introduced as well so they werent to blame. ill update if it changes its mind.

**Comment by ReikaKalseki** [comment]
Try updating AgriCraft.

**Comment by Reginald-Halifrax** [comment]
I literally typed out that I found the issue and solved it but failed to comment it. Ender io and agricraft were in fact to blame and I updated them. Fixed it right up. Didn't have to lose any mods to fix it as a result! 

Thank you for supporting me. Amazing work by the way I'm glad that this is working so me and my pals can enjoy your brilliant work unhindered.
