### ISSUE TITLE
[CC Suggestion] compatibility with avaritia singularities

### ISSUE THREAD

**Issue by Renegade2** [ReikaKalseki/Reika_Mods_Issues#1177]
If block versions of Chromaticraft alloys (firaxite,chromastone,chroma alloy,etc.) are ever added to the game,would you consider adding compatibility for Avaritia's singularities?

**Comment by HellFirePvP** [comment]
Knowing Avaritia's requirements to form 1 single singularity, getting a chromastone-block one would take literally forever without any EMC system or related.

Seems unlikely to be added.

**Comment by Renegade2** [comment]
True with chromastone,but there's still the possibility of the other alloys like firaxite.

**Comment by ReikaKalseki** [comment]
Which are nothing like endgame. Not even Chromastone is.

**Comment by Renegade2** [comment]
Most of the singularities added by avaritia and its addons are sometimes just common materials like coal/charcoal blocks, iron blocks,and all the metallurgy materials.The items used to make singularities are not always endgame materials themselves,they just add to the difficulty of making the catalyst by having a wide variety of different materials needed.

**Comment by HellFirePvP** [comment]
And by crafting like 80k of one single ore block. consider the need for crafting 80k chromastone blocks without any cheaty system like EMC or whatever. you'll be there literally forever.

**Comment by Renegade2** [comment]
Well,you must have your config numbers maxed out.I use some extra singularities, so the amount to form a singularity is set to 6708 per singularity at the moment.

![singularities](https://cloud.githubusercontent.com/assets/14224750/19746556/c80733e8-9b8b-11e6-9963-80b00b6f3169.png)

![singularity 2](https://cloud.githubusercontent.com/assets/14224750/19746626/16dd87d8-9b8c-11e6-8305-e7eb2df12a02.png)
