### ISSUE TITLE
DragonAPI crash, cannot cast items and non-recipies

### ISSUE THREAD

**Issue by Mrs-Feathers** [ReikaKalseki/Reika_Mods_Issues#1178]
Hello! I love your reactorcraft mod and i am updating it in a modpack of mine, however i am having issues with DragonAPI.

here is the error:
http://pastebin.com/UEUhe0nA

I am using V16d of ReactorCraft, RotaryCraft, and DragonAPI.
I'm not 100% sure of what's going on, thought cast meant the smelters from IC2, but i removed IC2 and all supporting mods and still got the same error.

again, i'm not sure what is going on so i'm not sure what information would be useful, if i've left out anything, please ask for it.

**Comment by ReikaKalseki** [comment]
#1172
