### ISSUE TITLE
Shaft junction 4-engine limit counted through semi-connections

### ISSUE THREAD

**Issue by mostlikely4r** [ReikaKalseki/Reika_Mods_Issues#118]
The setup as shown below does not transmit shaft-power across all 5 junctions but does cause the 4-engine limit to be reached.
![explosive_setup](https://cloud.githubusercontent.com/assets/13133260/8452674/4cdd3fe8-1fed-11e5-8e87-36651f69c4eb.png)
The result is this:
![after_explosion](https://cloud.githubusercontent.com/assets/13133260/8452675/519097a6-1fed-11e5-8f50-2a60b69b3026.png)

For comparison the setup below works fine:
![good_setup](https://cloud.githubusercontent.com/assets/13133260/8452676/53d0c220-1fed-11e5-9fc6-662870ebb4e9.png)

**Comment by ReikaKalseki** [comment]
Sounds like it might be an error in the read logic. This could be a nightmare to debug.

Could you try checking to see if this happens in all directions?

**Comment by mostlikely4r** [comment]
Wall of test below. I like to stress that this is a relatively trivial bug. The setup ideally should use bevel gears for the non-merging junctions. Non-lazy use of equipment bypasses this problem. I don't recommend spending too much time on it in case the (search for a) solution is significant.

It is however a bug in the code which might have consequences elsewhere. For a tdlr please skip to '[Code problem and solution]'

The setup does not depend on map direction (I tested north to south, west to east and reverse) all act the same.

I continued to test 4 situations where I made variations on the left most junctions: 
1) No-shaft against no-shaft: No explosion = Good
2) input-shaft against no-shaft: No explosion = Good
3) output-shaft against input-shaft: Explosion = Good
4) no-shaft against input-shaft: Explosion = Bug

1) OK
![2015-07-01_22 50 46](https://cloud.githubusercontent.com/assets/13133260/8464724/a8372352-2044-11e5-8f0a-71e58c238d6b.png)

2) OK
![2015-07-01_22 45 50](https://cloud.githubusercontent.com/assets/13133260/8464729/b4336300-2044-11e5-8f46-ad57dba86dfa.png)

3) OK
![2015-07-01_22 46 49](https://cloud.githubusercontent.com/assets/13133260/8464744/d1d4744e-2044-11e5-85ca-21c682869d01.png)
![2015-07-01_22 46 54](https://cloud.githubusercontent.com/assets/13133260/8464745/d41f1fa6-2044-11e5-9544-2160876ef92d.png)

4) nOK
![2015-07-01_22 48 58](https://cloud.githubusercontent.com/assets/13133260/8464755/e83b21d8-2044-11e5-8a1e-f0d8087a3218.png)
![2015-07-01_22 49 05](https://cloud.githubusercontent.com/assets/13133260/8464757/eaa66c3e-2044-11e5-964c-2a68feec8d18.png)

I then mirrored above setup making the rightmost the odd one out and the bug occurs in the exact mirror situation ie. input-shaft against no-shaft.

Note that the junction furthest from the odd-junction explodes.

I then started to suspect the junction on the right (test situation 4) cycles along the input-shafts (recursively) and counts engines. It doesn't necessarily counts if those input sides are attached to a junction's output-shaft to keep going.

To test my hypothesis I tried the setup below (5) input-shaft against input-shaft. This did not explode (which I think is fine)

5) Ok?
![2015-07-01_23 07 38](https://cloud.githubusercontent.com/assets/13133260/8464927/34c15012-2046-11e5-9ec6-43ae5a421ab3.png)

So I have to supplement my hypothesis and it becomes as follows:

[Code problem and solution]
To see if a junction has to overload, the algorythm looks along input-shaft sides to count engines. When input-shaft side is attached to output-shaft side 'or' non-shaft side of a junction, add that junction to the list to include in the search.

To solve this problem non-shaft sides should be excluded along with input-shaft sides.

**Comment by ReikaKalseki** [comment]
Fixed.
