### ISSUE TITLE
[Chromaticraft] Energy Boosters create energy.

### ISSUE THREAD

**Issue by GPeckman** [ReikaKalseki/Reika_Mods_Issues#1181]
I was messing around in creative after installing Chromaticraft v16d and I observed a possible bug. When I place an energy booster adjacent to a Thermal Expansion Dynamo or an extra utilities generator, the dynamo/generator begins producing power. Without any fuel.

**Comment by ReikaKalseki** [comment]
Lovely...

**Comment by ReikaKalseki** [comment]
I fixed the TE one, and cannot fix the ExU one (and so removed that functionality).
