### ISSUE TITLE
[CC] Excavation Star cannot harvest Hardcore Ender Expansion blocks

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1182]
End Powder requires any pickaxe, acts unbreakable to the star.

Igneous Ore requires a redstone-level pickaxe, is simply destroyed when mined.

Instability Ore requires an obsidian-level pickaxe, acts unbreakable.

Endium Ore requires any pickaxe, acts unbreakable.

Stardust Ore, Sphalerite, and Sphalerite Stardust Ore require an obsidian-level pickaxe, and act unbreakable with the star. (Sphalerite forms small meteorites floating in the void)

**Comment by Shahelion** [comment]
Seems it also cannot harvest Ravaged Dungeon Bricks of any variation or any of the three decorative endstone types. Not even the Spooky Logs, which break in an instant with bare hands.

**Comment by ReikaKalseki** [comment]
I am not sure I can fix this. @chylex?

**Comment by chylex** [comment]
Uh, what exactly does Excavation Star do? HEE ores don't do anything too special, mostly just playing with the drop amount which should not interfere with any modded picks. The only "weird" block is the Ravaged Brick which changes hardness based on the amount of spawners.

**Comment by ReikaKalseki** [comment]
It is essentially a more powerful and flexible tool form of VeinMiner (using the onBlockStartBreak method). I had it set to return true for all cases of block harvestability, which leads me to wonder why it cannot break some at all. It uses getDrops() for the drop list.

https://www.youtube.com/watch?v=2gX4tRGlwDg&feature=youtu.be

**Comment by chylex** [comment]
It seems that all blocks it cannot break use Forge's harvest tool level method, could that be the cause?

**Comment by Shahelion** [comment]
Doesn't the excavation star have a blacklist for certain blocks? I know it includes smoothstone, netherrack, and endstone, does it include anything else?

**Comment by Shahelion** [comment]
Looks like the star is also unable to harvest decorative blocks from Matter Overdrive, and _mossy cobblestone from vanilla_.

**Comment by ReikaKalseki** [comment]
> Doesn't the excavation star have a blacklist for certain blocks? I know it includes smoothstone, netherrack, and endstone, does it include anything else?

No.

> Looks like the star is also unable to harvest decorative blocks from Matter Overdrive, and mossy cobblestone from vanilla.

!?

I do not think mossy cobble even has its own _class_...

**Comment by Shahelion** [comment]
...I am a _special_ person. 

So...I forgot that I had died, and hadn't recharged lumens since then.._.I was out of lumens._ Feel free to slap as many User Error tags on this issue as you feel necessary.

If the blocks turn out to STILL be unharvestable WITH lumens, I'll re-open this. But I doubt they will.
