### ISSUE TITLE
[CC] Vibrant Pods drop nothing if the attached log is broken

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1183]
No beans.

I was using a TiCon Lumber Axe, if that matters, although Ether Berries dropped when I broke the leaves with a Scythe...

**Comment by Builderb0y** [comment]
Vibrant pods are a tiered plant, so they follow the same rules as aura blooms/rock flowers/etc… None of them drop anything if their attached block is broken because they can't check the progression of the player who broke it. Ether berries on the other hand are not tiered, so they drop normally.

**Comment by Shahelion** [comment]
That...makes a lot of sense.
