### ISSUE TITLE
Server Crash involving EnderIO and DragonAPI

### ISSUE THREAD

**Issue by WillDaSilva** [ReikaKalseki/Reika_Mods_Issues#1184]
[Reddit thread on /r/FeedTheBeastCrashes](https://www.reddit.com/r/FeedTheBeastCrashes/comments/5aaamp)

[Crash Report before using MCEdit](http://pastebin.com/rKaipwky)

[Crash Report after using MCEdit](http://pastebin.com/7xVaZ4wN)

The server is a FTB:IE server with some of Reika's mods added. The server was working fine, and was running the latest versions of all of Reika's mods that were installed. After a normal shutdown, the server would not start. The error appeared to have something to do with an EnderIO capacitor bank located in the spawn area near (0,0,0). I removed it using MCEdit. Afterwards, the server still crashed during launch, this time producing a very similar error. The new error has something to do with an EnderIO Alloy Smelter and DragonAPI.

**Comment by ReikaKalseki** [comment]
You have a Block/TileEntity mismatch.

**Comment by DFliyerz** [comment]
I'm having a similar issue to this, affecting multiple worlds, although luckily just test worlds.
https://gist.github.com/DFliyerz/5c1e24cdbea35cf06c4ffd62ebfd7040

**Comment by WillDaSilva** [comment]
Reverting my world to the most recent backup solved this issue for me. I am unsure as to what caused the issue.
