### ISSUE TITLE
Dragonapi crashing on MultiMC

### ISSUE THREAD

**Issue by LukaPix** [ReikaKalseki/Reika_Mods_Issues#1186]
I get this REALLY weird error when trying to start minecraft on multimc with DragonAPI installed ...

Modlist in Log
http://pastebin.com/1fqYQPGH

**Comment by Aivech** [comment]
Thaumic Infusion for 1.7.10 is not compatible with DragonAPI. In addition, the Thaumic Infusion author (TheDrunkMafia) has requested that people not use the 1.7.10 version of Thaumic Infusion. See https://github.com/TheDrunkMafia/ThaumicInfusion/issues/81.

Duplicate of https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1003 & https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1079

**Comment by ReikaKalseki** [comment]
and #895 #995 #1094
