### ISSUE TITLE
Reactorcraft and computercraft connection?

### ISSUE THREAD

**Issue by tvk1372** [ReikaKalseki/Reika_Mods_Issues#119]
Hy Reika!
Is there anyway to control the Fusion reactor with computercraft/opencomputers,or monitor the generated RF/t from the Generator (high-pressure turbine + generator),like in reactorcraft?
Its Important for me,because I build a Fusion power plant (4 plasma injectors+4 high-pressure turbine generators) for my future GIANT Minecraft city.
So the problem is I cant measure the generated RF,I am building a control room also for the Fusion reactor,but I dont know how to turn on/of the fusion reactor from far away,I need computer control for this.
Can you do with this something to computercraft do the generated RF/t read from the turbine generator and the generated steam values  and also the fusion reactor control please?
Please help me with these.

**Comment by ReikaKalseki** [comment]
Have you tried?

**Comment by tvk1372** [comment]
For original RF read I use some energy cell reader program,it reads the flow rate until the cell's are full.
But in this version its use less,because the flow rate is super high.and it gives me false values.
And for the fusion control I combine ELN mod in this way and it works:
-I put a ELN signal to redstone converters next to the creative coil's  so I can give them redstone signal.
And I connect a wireless receiver to the ELN signal to redstone  so I can turn on and off the redstone signal from far away with wireless buttons.But the other problems are unsolvable for me like the
-Generators RF/t read
-Steam production read
-Fuel quantity
So these are the problems.

**Comment by ReikaKalseki** [comment]
All of those values are instantaneous and constantly changing, and not a single one is stored as a value inside the machine blocks.
