### ISSUE TITLE
Corium﻿ causes excessive amounts of radiation, leading to 1 FPS and thousands of entites

### ISSUE THREAD

**Issue by TheDestroyerKSP** [ReikaKalseki/Reika_Mods_Issues#1190]
Steps to reproduce:
1: Build a terrible reactor that will melt down
2: Have it built on sandstone so corium will fall a decent distance (thanks to explosion crater)
3: witness allmighty world-killing lag
http://images.akamai.steamusercontent.com/ugc/400086242623137130/3F82AA3E7EB315201CC947D42836CE88676E6F20/
After using /cofh killall radiation
http://images.akamai.steamusercontent.com/ugc/400086242623141829/338148263F755E6747BB11C9DCA9B26AB6FA44F1/

This continues to go on and on, the radiation keeps coming back at alarming rates. One I killed the corium (blocking its source block) then it stopped.
Using V16D

**Comment by ReikaKalseki** [comment]
Possibly fixed.
