### ISSUE TITLE
[CC] [GS] Excavation Star and Lavarock

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1191]
Even without the Silk Touch enchantment on the Star, it still seems to be silk-touching the lavarock.

**Comment by ghost** [comment]
This might be on purpose, perhaps try breaking it with a pickaxe and see what happens.

**Comment by Shahelion** [comment]
Unenchanted pickaxe makes all lavarock drop as the same type.

**Comment by Shahelion** [comment]
So...the Star is SUPPOSED to silk-touch the lavarock without Silk Touch? Because nothing else does.
