### ISSUE TITLE
Possible Visual Glitch with Performance Engine and Gearboxes.

### ISSUE THREAD

**Issue by MaxineBean** [ReikaKalseki/Reika_Mods_Issues#1192]
This is a weird issue, not sure how to describe it, so I will link to a video of it.

https://drive.google.com/file/d/0B41K4g3LbSceU3UxZkJRSnBpaW8/view?usp=sharing

Modlist: https://gist.github.com/MaDmaxwell311/3cdec3c04f4ef3e2b6c277caf6cd1217

EDIT: After further testing, this still happens:
1. After a restart, of both server and client and the comupter they are hosted on.
2. if there are shafts in between the gearboxes, 
3. if the gearboxes are 8:1, 8:1, 8:1
4. if there are 2-4 performance engines.

EDIT 2: Fixed the video link

**Comment by ReikaKalseki** [comment]
Your video does not load. Is it [this issue](https://i.redd.it/x92rwk7wtiqx.gif)?

**Comment by TheGuyRunningSouth** [comment]
I managed to view the video with the Drive app for android. The issue in
the video shows two diamond gearboxes connected in a row to a jet furnace.
The first gearbox is running fine, the second gearbox's GUI power field
switches between 0 and 262.1 kW and the speed indicator in the furnace GUI
switches between 0 and full.

**Comment by MaxineBean** [comment]
Sorry about that, I copied the wrong link, here is the updated one. https://drive.google.com/file/d/0B41K4g3LbSceU3UxZkJRSnBpaW8/view?usp=sharing

**Comment by ReikaKalseki** [comment]
This is the long-standing gearbox power desync issue.

**Comment by ReikaKalseki** [comment]
I might have fixed this.
