### ISSUE TITLE
Chromaticraft: Fissure can intrude on dimension puzzles

### ISSUE THREAD

**Issue by Kimano** [ReikaKalseki/Reika_Mods_Issues#1193]
In my case specifically it's a Ruzova/laser puzzle which itself was unaffected; the fissure just happened to go right through the core room. All the air blocks in the core room, as well as the core itself, are replaced by shielding cloak. The rest of the structure is undamaged.

![2016-11-05_02 17 55](https://cloud.githubusercontent.com/assets/473234/20028079/175d0052-a2fe-11e6-9ef8-b33152f11165.png)

Not a huge deal since you can just leave and generate a new puzzle, but it's irritating after solving to realize your core is gone.

**Comment by ReikaKalseki** [comment]
I cannot prevent it from overwriting air, but I can prevent it from destroying the core.

**Comment by ReikaKalseki** [comment]
Done.
