### ISSUE TITLE
[Request] Practical Logistics compatibility

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1195]
Currently Practical Logistics Energy Reader with Node on RoC machinery displays nothing, while Info Reader displays generic info + a curious "ENERGY RF" category with all variables in it named "Connects:", displaying current and maximum temperature, and for engines, output power in watts. The identical variable names make it useless too.

Please collaborate to allow Practical Logistics to read: 
* Non-bugged-name current and maximum temperature
* Non-bugged-name current power output (engines)
* Current and maximum torque and speed (shaft power transmitters)
* Current power (shaft power transmitters)
* Ratio and direction of conversion (gearboxes, worm gears, CVT)
* Input and output torque and speed (gearboxes, worm gears, CVT)
* Current and maximum power (engines)
* Output torque, output speed, current and maximum energy and whether it's set to input or output (industrial coil)
* Input and maximum torque and speed, and output quantity and type (conversion engines)

https://github.com/SonarSonic/Practical-Logistics/issues/104

**Comment by ReikaKalseki** [comment]
Half of the things you ask for do not exist as variables in the machines, and several more - like engine max power and converter type - need not be stated due to their being either blindingly obvious, required knowledge in order to have made it this far/made the machine/wanted the machine, or available in the machine GUI or similar.

**Comment by Barhandar** [comment]
> like engine max power and converter type - need not be stated due to their being either blindingly obvious, required knowledge in order to have made it this far/made the machine/wanted the machine, or available in the machine GUI or similar.

Practical Logistics allows automation (redstone output) based on settings, not just display. Specifically the maximum power thing allows checking for "performance engine ran out of additive" or "turbine is spinning up/down".

**Comment by ReikaKalseki** [comment]
Looking at his code, it appears there is nothing for me to hook into.
