### ISSUE TITLE
[CC] Chromastone tool parts are too good

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1196]
The absurd repair speed is constantly interrupting mining progress, making it much slower overall. Not sure what can be done about this, though, really.

**Comment by ReikaKalseki** [comment]
The "reset mining progress on tool change" is fairly new (1.7) behavior.

**Comment by Shahelion** [comment]
Perhaps lower the frequency of repairs, but have it repair more than one durability at once? Is that possible?

**Comment by ReikaKalseki** [comment]
It does not fix the issue.

**Comment by Builderb0y** [comment]
> The "reset mining progress on tool change" is fairly new (1.7) behavior.

Actually, I've downloaded a few old versions and can confirm this behavior was added in 1.4.3.

**Comment by DracoScythem** [comment]
Would it be possible to "hack" the durability bar to show a nbt-based "charge", which emulates durability?
(Or make it unbreakable but have it consume the players lumens whenever used?)
(I know it is possible with normal tools but I have no idea if the TCon API has support for something like that, so... don't mind me if my suggestions are crap ^^)

**Comment by ReikaKalseki** [comment]
Changing NBT will probably also reset break progress, since that is what stores tool durability. I need to either find an alternative to gradual repair - unlikely - or put in an exception to the vanilla behavior.

**Comment by Shahelion** [comment]
The only real issue is that it repairs too often. Like I suggested up above, what about repairing more than one durability at once, at a lower frequency? Moss has a low frequency, and it works fine.

**Comment by Barhandar** [comment]
Can "tool is being used" be detected? Then you could just not repair while it's being used, and maybe forcibly repair anyway if durability gets too low.

**Comment by ReikaKalseki** [comment]
Possibly.

**Comment by ReikaKalseki** [comment]
[Done](http://i.imgur.com/rmwICgF.png).
