### ISSUE TITLE
chromaticraft instant crash

### ISSUE THREAD

**Issue by Null-Codes** [ReikaKalseki/Reika_Mods_Issues#1197]
whenever i startup Minecraft, it instantly crashes.
here is crash report: http://pastebin.com/C8iVhtt4
here is log: http://pastebin.com/8JYfeU7e
here is game output: http://pastebin.com/SAb7TViy
i am sorry if all of this is not needed, i just want to play minecraft with chromaticraft and all of the other mods i have (i was going to test them all out, but it crashed)

**Comment by WaffleMan0310** [comment]
I was about to report this issue, to add to this, it's not guaranteed to happen. I just had a crash followed by a successful launch with no modifications.

**Comment by marlyn-x86** [comment]
Lines 119-126 of the crash report:

```
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    ThermalExpansion: -[1.7.10]4.1.4-247
    TConstruct Environment: Environment healthy.
    ThermalDynamics: -[1.7.10]1.2.0-171
    Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
    Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client:
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
```

**Comment by ReikaKalseki** [comment]
#1014 #710 #661 #599 #592 #481
