### ISSUE TITLE
Unresponsive Biome Painter UI

### ISSUE THREAD

**Issue by Reginald-Halifrax** [ReikaKalseki/Reika_Mods_Issues#1198]
The biome painter has an issue, where the biome selection UI is completely unresponsive unless you have gui scaling set to auto... I run in normal mode, and auto sets it to even larger than large.

Luckily a biome painter isn't something I'm using often so it isn't that huge a deal. But I'm putting this out anyhow.

**Comment by ReikaKalseki** [comment]
This is in v16?

**Comment by Reginald-Halifrax** [comment]
Mc 1.7.10 version V16d

**Comment by Reginald-Halifrax** [comment]
I'm not saying it's lagging I'm saying it simply won't accept clicks unless it's in a different GUI scale

**Comment by ReikaKalseki** [comment]
That sounds like a positioning error. Try clicking other areas.

**Comment by Reginald-Halifrax** [comment]
I have clicked everywhere and still no clicks... what's interesting is I can still hover over the buttons and highlight them, the cursor buttons also seem to work fine

**Comment by DFliyerz** [comment]
Still having this problem as well.

**Comment by ReikaKalseki** [comment]
I think this is fixed in v17.

**Comment by ReikaKalseki** [comment]
Fixed.
