### ISSUE TITLE
[CC] Suggestion: Item Casting Stands ease of use

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1199]
Current behavior:
 Right-click to insert a single item, and again to insert the whole stack (in that slot)

Possible improved behavior:
Right-click with an item to insert one, and right-click with a stack of items to insert them one at a time. Shift-right-click to insert a whole stack.

Right-click with empty hand to empty would remain unchanged.

Constantly having to divide stacks in my inventory, because I only want to make two of an item, not 1 or a whole stack, gets tedious after a while.

**Comment by Builderb0y** [comment]
Shift right clicking with items doesn't even notify the item stands that they've been clicked on, and you can get around the dividing stacks thing with the stack spreading behavior: shift right click 10 different stands with an empty hand > right click any one of them with another item > it splits the stack in your hand and puts 1/10'th of the items in each stand. Leftover items are left in your hand.

**Comment by Shahelion** [comment]
...I had no idea this was possible. Again, not stated anywhere at all. But thank you.
