### ISSUE TITLE
AutoCrafting Unit Causes Server Crash with AE2 Installed if ME Network isn't Attached.

### ISSUE THREAD

**Issue by madolinn** [ReikaKalseki/Reika_Mods_Issues#12]
http://pastebin.com/rMBggtZJ

Crash only happens if AE2 is installed and the AutoCrafting unit is powered while no ME Network is present. You either have to MCEdit the power source out or removed the mod to preserve the world.

Without AE2 installed it functions normally.

~~Attempting to connect an ME Network still nets the same result.~~

![Oops](https://cloud.githubusercontent.com/assets/10469156/7222986/5f12e47c-e6e7-11e4-9c27-36278521683b.png)

ME Networks must be attached to the top to be read. This is not a valid setup, and will still cause a crash.

ME Network is using Non-creative mode items and has stacks of wood within the drive. AutoCrafting Unit has Wood Planks -> Sticks recipe.

**Comment by quedral** [comment]
I am running 8 AutoCrafters without any issues. Yes, they do increase TPS however they don't crash my world. I am running AE rv2.beta build 18.

I assume you are running later or alpha version since you haven't provided AE version info?

**Comment by 1Matthias** [comment]
>        appliedenergistics2{rv2-beta-26} [Applied Energistics 2] (appliedenergistics2-rv2-beta-26.jar) >Unloaded->Constructed->Pre-initialized->Initialized->Post- >initialized->Available->Available->Available->Available 
He appears to be running a more up to date version. Have you tried different versions of AE to see which are having the issue?

**Comment by madolinn** [comment]
Previously I was using the Stable Rv1 stable version and it would crash upon placing the table, powered or not. Reika suggested updating AE2, and between that and the new patches of RoC at the time, placing no longer crashed the server.

However I hadn't bothered to try many intermediate AE2 beta patches because they appeared to change very small amounts of code to fix major issues, seemingly unrelated to their Mod API.

**Comment by madolinn** [comment]
For everyone that says their crafting units are working fine, I'm curious if they're all using them connected to an ME Network.

It's more likely that it's trying to call the method on the chest, or an air block, rather than AE2 being broken. I'll try multiple setups to test my theory though in a bit.

**Comment by quedral** [comment]
@madolinn 
Yea mines are connected directly to ME network.

**Comment by madolinn** [comment]
The bug is that it tries to call the method regardless of the block above it, resulting in the crash.

**Comment by ReikaKalseki** [comment]
I am using mine fine too, so it has to be AE version related.

**Comment by madolinn** [comment]
Perhaps we should wait for the next AE2 Stable release to be sure which method they stick to and fix accordingly.

**Comment by ReikaKalseki** [comment]
I have hopefully fixed it for v7, with a more stable approach.
