### ISSUE TITLE
ChromatiCraft crash

### ISSUE THREAD

**Issue by marco6971** [ReikaKalseki/Reika_Mods_Issues#120]
http://pastebin.com/xCxHyx1E

**Comment by Duckfan77** [comment]
Please provide information as to what you were doing at the time of the crash.
Based on the crash log, it appears to be similar to [issue 100](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/100).

**Comment by ReikaKalseki** [comment]
This is the same issue.
