### ISSUE TITLE
[CC] Multi-Aura Repeaters locked to one color

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1200]
I have four multi repeaters in a line, then they branch into a Karmir line in one direction, and Vadali in the other direction. The multi repeaters started pulling Vadali into a Relay Source, but seem to be unable to pull Karmir (attempting the Arrow Shield ritual). Verified that the entire Karmir line is connected properly up to the Multis, there is a clear line of site, and the multis clearly work for Vadali.

Also, no matter which color is displayed, or how it's set up, the multis ALWAYS play the error sound when right-clicking with the Manipulator with the single exception of when they are already drawing lumens.

![2016-11-07_17 13 31](https://cloud.githubusercontent.com/assets/6917535/20083903/f4239aa2-a513-11e6-84c4-808b13f64e2a.png)
![2016-11-07_19 01 02](https://cloud.githubusercontent.com/assets/6917535/20085300/c0c37fd4-a51c-11e6-8706-d5959b5322d5.png)
![2016-11-07_17 51 18](https://cloud.githubusercontent.com/assets/6917535/20083905/f42c122c-a513-11e6-8218-85daf717ff3b.png)

**Comment by ghost** [comment]
Has the relay source been completely filled with Vadali? Sometimes another color will not fill the receiver. Note: It _might_ need the 15 other colors before it will begin filling Karmir, though I usually have all 16 colors hooked up before I use a relay source.

**Comment by Shahelion** [comment]
I ended up switching to only single-color repeaters, still can't get the multis to work. With single color ones, it filled up all three (I have a link to Kuro now) alternating between them.

I would have waited, but I wanted to power up my Lumen Fence. I then put the relay source away for now, since it was draining my pylons dry.

**Comment by ReikaKalseki** [comment]
This is probably a LOS failure. I know these work.
