### ISSUE TITLE
[CC] Opening the Ritual Table GUI does not cancel the right click event

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1201]
For example, if I'm holding a block and right-click the table to open it, it also places the block. Even if the block would be placed inside my own bounding box.

https://gyazo.com/0fafc502689005f48ab0cd5b4b321fac

Steps to reproduce:
1: Place a Ritual Table
2: Stand on top of it
3: While holding any block, right-click to open the GUI.

**Comment by ReikaKalseki** [comment]
Fixed.
