### ISSUE TITLE
Rainbow Tree Mystcraft call crash?

### ISSUE THREAD

**Issue by Reginald-Halifrax** [ReikaKalseki/Reika_Mods_Issues#1203]
This would be the third report i've made and i feel like i'm becoming annoying with it.

I accidentally burnied some leaves of a rainbow tree on fire. and eventually consumed it.... and it returned a crash for a call for some mystcraft class.... a mod that we don't have....

[crash-2016-11-09_14.27.25-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/581677/crash-2016-11-09_14.27.25-server.txt)

_-I edited this as we did some testing to find it was not a lumen tree that crashed it._

**Comment by ReikaKalseki** [comment]
#1154

**Comment by Reginald-Halifrax** [comment]
so you fixed it in a version not yet released I guess?
