### ISSUE TITLE
Crafting patterns nor working with Blast Furnace

### ISSUE THREAD

**Issue by ZorbaHerbalist** [ReikaKalseki/Reika_Mods_Issues#1204]
Latest version (16d) RotaryCraft, like https://www.reddit.com/r/feedthebeast/comments/4rmyvs/rotarycraft_crafting_pattern_for_blast_furnace/
there is no way to save crafting pattern for Blast Furnace.

**Comment by ReikaKalseki** [comment]
The pattern does not have the "left slots" required for alloy-type recipes.

**Comment by DFliyerz** [comment]
It also can't do things like 3x3 coal to make 9 coal coke.

**Comment by ReikaKalseki** [comment]
That is because that recipe is coded differently; there are actually two kinds of Blast Furnace recipes, which that is the former.

**Comment by DFliyerz** [comment]
Too bad the pulse jet furnace is so slow for making HSLA and has no bonus :P

**Comment by ReikaKalseki** [comment]
Done (as per #1338).
