### ISSUE TITLE
[CC] Request: Different error sound for different problems

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1205]
Since the same sound plays, I can't tell if the pylon was simply drained (without going all the way out to it) or the repeaters aren't connected properly, or something else entirely.

**Comment by ReikaKalseki** [comment]
One, a pathfinding failure is a failure; it carries no data about why. Second, this is a slippery slope that leads to 30 other things having distinct error sounds.

**Comment by Shahelion** [comment]
Fair enough...but why does it fail when it still connects, just the pylon is empty? Why does this count as a pathfinding failure?

**Comment by ReikaKalseki** [comment]
Because empty pylons cannot transmit.
