### ISSUE TITLE
Missing Mystcraft Api, burning rainbow leaves causes recurring crash

### ISSUE THREAD

**Issue by Diresheep** [ReikaKalseki/Reika_Mods_Issues#1207]
So a thunderstorm lit a rainbow tree on fire, now whenever a player loads the base near that tree, my server crashes with this log:  http://pastebin.com/fnkRQrFH

is there anything i can do? i think installing mystcraft might fix the crash, but I'd rather not do that if I can help it

**Comment by ghost** [comment]
#1154, #1203

**Comment by Diresheep** [comment]
thank you, just not resolved in v16d then
