### ISSUE TITLE
 java.lang.NullPointerException: Ticking entity crash when standing in liquid chroma

### ISSUE THREAD

**Issue by DweiaCaelum** [ReikaKalseki/Reika_Mods_Issues#1208]
Issue: 
I got this crash when I stood in liquid chroma for the first time. The progress unlock sound played and minecraft crashed. When I tried to open the game again, I got the same crash.

Log: http://paste.feed-the-beast.com/view/06726894
I am using the latest versions of chromaticraft and DragonAPI.

I searched the forums and this github for a similar crash but couldn't find anything. I posted at the ftb forums too, but no help there. I don't know anything code-related, I just want to know if there is a fix for this or should I just revert to a backup? 

Thank you very much in advance.

**Comment by AshIndigo** [comment]
Something went with liquid chroma giving its effects. Can you check for potion ID conflicts with Chromaticraft and other mods? Primarily 38 and 39.

**Comment by DweiaCaelum** [comment]
There was an ID conflict but it was between Witchery and Ars magica 2, not Chromaticraft. I still fixed the conflict but it crashed again. I'll check all the potion IDs, but just in case, here is the log:
http://paste.feed-the-beast.com/view/dd0c8d02

Thanks for helping :)

Edit: Fixed all ID conflicts I could find. Still crashing.

**Comment by ReikaKalseki** [comment]
This is not on my end.
