### ISSUE TITLE
Two Issues - Iguana Tweaks / Mob Grinder & Extracells endless jet fuel

### ISSUE THREAD

**Issue by TraXza** [ReikaKalseki/Reika_Mods_Issues#121]
Hi Reika,

I am not sure whose side these issues sit with but thought I would let you know either way:

Iguana Tweaks Tools & Rotraycraft Mob Grinder:
When using Iguana Tweaks if I run the mob grinder with any tinkers tool in my hand it will continuously credit me with the kills (seen in chat via COFH & Thaumcraft special mobs) & the Skill XP of the tools will climb as if I was killing the mobs.  Apparently it credits me with the kills even if I am not logged in, that may have been a server lag issue though.  This is 100% repeatable & only effects the player that placed the mob grinder or possibly the player that made it.

Extracells:
Jet fuel is not consumed from the Extracells storage drives.  Output method is via fluid export bus into EnderIO pressurized conduit & into ECU's.  This works on both the gas turbine & the microturbine.  The same problem occurs when I feed directly via the fluid bus, with or without the ECU or EnderIO conduits.  Other fluids in the system are used - eg: water, lava, mek fluids, etc. (didn't test LN2 & lubricant :$)

Both these issues where present on older versions of the mods, the server was updated to listed versions yesterday (excluding your mods which where always V6a/f) & those issues are still there:

appliedenergistics2-rv2-stable-9.jar
ExtraCells-1.7.10-2.2.73b129.jar
TConstruct-1.7.10-1.8.5.jar
IguanaTinkerTweaks-1.7.10-2.1.5.jar
DragonAPI 1.7.10 V6f.jar
RotaryCraft 1.7.10 V6f.jar
ElectriCraft 1.7.10 V6a.jar
Forge 10.13.4.1448

Let me know if you need anymore info & thanks for the awesome mods!

**Comment by 1Matthias** [comment]
The first one has already been seen, and is apparently a result of the way that Iguana's tweaks count levelling and kills. The second issue has not been seen before, and does sound like a major issue.

**Comment by TraXza** [comment]
Ah, sorry about that I did look through the issues & didn't see anything related.

Shout if you need more info / testing regarding the second issues.

**Comment by 1Matthias** [comment]
It is ok, it was never officially reported, just told to Reika over VOIP.

**Comment by ReikaKalseki** [comment]
There is nothing special about my fluids except the fact they do not have a block. Try lubricant and some other fluids without blocks.

**Comment by TraXza** [comment]
Thanks I will raise it with DrummerMC I think he's running EC2 now.

**Comment by ReikaKalseki** [comment]
A similar issue was reported yesterday, though the no-block point was not specified as the duplicated fluid was lava.

https://github.com/ExtraCells/ExtraCells2/issues/252#issuecomment-118644292

**Comment by TraXza** [comment]
Cool, I will let EC2 Github know your comments it may help them.

**Comment by TraXza** [comment]
Reika your too quick, I see you already beat me to it on EC2 Github :P
