### ISSUE TITLE
[CC] Crystal Repeaters don't work when built sideways

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1211]
Referring to the single-color 4-block high Crystal Repeaters, I have been told more than once now that they can supposedly be built sideways, yet I have never had it work. Just would like to verify either way.

Also, if they currently don't, consider this a suggestion to allow them to work when built sideways.

**Comment by ghost** [comment]
Is it the multiblock itself not forming or just not being able to connect to the rest of the network? Since it is [working for me.](http://imgur.com/a/fezS6)

**Comment by Shahelion** [comment]
Not sure, since it's all the same error sound.

**Comment by ghost** [comment]
Does the repeater have glow-y particles inside it? If not, that means it is missing the multiblock.
Also, the usual error is that the repeaters cannot connect due to the angle (sometimes caused by direction, as seen in the last two imgur images of my last comment) or out of range (32m).
