### ISSUE TITLE
[CC] Replication Star does not work

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1212]
I have at least 50k of each required color (according to the book, Kuro, Zambarau, and Galazio) yet I cannot even replicate a single block of smoothstone with a stack in my inventory, let alone anything else.

![2016-11-11_20 51 20](https://cloud.githubusercontent.com/assets/6917535/20235787/5b0f1800-a851-11e6-9657-f02e26a31484.png)

**Comment by ReikaKalseki** [comment]
Are you using it correctly?

**Comment by Shahelion** [comment]
Is it used differently than the others?

 Shift right click to set or clear, right click to place?

**Comment by ReikaKalseki** [comment]
Yes.

**Comment by ReikaKalseki** [comment]
Does it work in creative? I have used it repeatedly.

**Comment by ReikaKalseki** [comment]
Hello?

**Comment by OvermindDL1** [comment]
For note, as another data point, I've had the same issue.

1. Shift-Right-Click one location.
2. Shift-Right-Click another location, or the same location, a single block is fine to test with.
3. Right click somewhere else.

It only works about 10% of the time for me.  I've completed the monument and my power is maxed at whatever millions.

In Creative it does seem to work more reliably, but not fully reliable still, maybe 80% of the time.

Maybe some sound effects or particle whenever you Shift+Right+Click something to help do an indicator of successful targeting or not?

**Comment by ReikaKalseki** [comment]
It is working fine for me, but I did add some audible feedback.
