### ISSUE TITLE
[CC] Cannot Activate Rituals

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1213]
Trying to activate Arrow Shield (since that's the only one I have the colors for right now) and it gets as far as me floating above the altar, then it switches to this weird zoomed out first person view, and I'm standing on the altar, but I don't have the ability. I've tried this three times now, and the same thing happens every time.

![2016-11-12_19 57 57](https://cloud.githubusercontent.com/assets/6917535/20243568/c59a8576-a912-11e6-8e45-9c20aea4f5ac.png)
![2016-11-12_20 02 41](https://cloud.githubusercontent.com/assets/6917535/20243583/7c1d0710-a913-11e6-9008-3277f66178d9.png)

Weird first-person view: https://i.gyazo.com/d5f0c570c01f4693ddd2750aa88f06ce.mp4

**Comment by ReikaKalseki** [comment]
Do you know how to activate abilities? I know this works.

**Comment by Shahelion** [comment]
The ability is still greyed out in the middle click selection menu.

**Comment by ReikaKalseki** [comment]
Then it did not complete properly.

**Comment by Shahelion** [comment]
Yes but why?

**Comment by ReikaKalseki** [comment]
Maybe it never got enough lumens? Maybe you stepped out too early? Maybe it failed to write to player NBT?

**Comment by Shahelion** [comment]
It showed a full circle of Karmir, and the dot turned from yellow to green, as shown in the screenshot.

I just waited floating in the air until it dropped me down by itself.

How long is it supposed to take - after it gets the lumens - to infuse, for example, Arrow Shield? Maybe it's stopping too soon.

**Comment by ReikaKalseki** [comment]
It has never failed before, nor will it terminate early without cause.
