### ISSUE TITLE
Disallow Chromic Lexicon from insertion into Item casting stand

### ISSUE THREAD

**Issue by Savallator** [ReikaKalseki/Reika_Mods_Issues#1218]
Hi,
if one accidently clicks an item casting stand with the Chromic Lexicon, it takes a long time to Place it inside (several minutes at worst). The removing of the lexicon is fast as usual.
I suspect that is due to the amount of NBT data associated with the Lexicon. However, when crafting  and looking up recipes, that happens quite often for me.
Maybe it would be a good and simple Workaround to Blacklist certain items (the lexicon by default, and maybe configurable other items) for the Casting stand.
I have read somewhere you dont like pull requests, so i will not write a proposal code, but i think it should be a simple thing just adding that in 
`public ItemStack onRightClickWith(ItemStack item, EntityPlayer ep)`
in TileEntityItemStand.java.
It is not a gamebreaking bug, but very annoying to wait several minutes everytime i accidently right glick an item.
Another question: I think you know about the problem with Lag in NEI when gregtech (especially tools i think) makes the lumen fabrication calculation tree very large. Do you intend on working on that in the future? If not - would you appreciate if someone else works on that and present working, well commented code? If so, have you any special build-instructions to compile chromaticraft?
If you say you don't want that at all, thats ok as well. I just really like Chromaticraft and want to assist in working out bugs.

**Comment by ReikaKalseki** [comment]
I have accidentally put my lexicon in the stands many times with no issues. Your computer is probably just slow.

That said, seeing as I never intend to make a recipe use a lexicon, I will still blacklist it from the stands to save annoyance.

**Comment by Savallator** [comment]
My Computer is hardware-wise quite fast, as well as the server (i7 4790k), so i suspect some other mod to interfere with it at well and make it worse. However, i am not quite sure what is taking so long. The Rotarycraft book shows the same behavior, and it seems to be a Server issue, as other Players tend to disconnect at the exact time, while for me it only hangs. But it is only really annoying with the Chromaticraft book, because it can accidently happen very easily.

**Comment by ReikaKalseki** [comment]
> The Rotarycraft book shows the same behavior

It has no NBT.

**Comment by ReikaKalseki** [comment]
Done.
