### ISSUE TITLE
Loos all Progress after was in the first dimension of CrC

### ISSUE THREAD

**Issue by t3rraz** [ReikaKalseki/Reika_Mods_Issues#1219]
No crashlog, only few lines server side

Here the lines from log

http://pastebin.com/LW1NdvRQ

seems like a big bug, ist now the second Player that loost all his Progress on our server
wer plaing Revolution 3.4.4 Haggle pack

**Comment by ghost** [comment]
This is known to happen extremely randomly, though iirc, Reika added a feature that would restore progress, but it doesn't seem to always work.

**Comment by t3rraz** [comment]
how can i fix that ? or do we Need to wait for a update from reika? my team mates doesnt want go in the dimension now.

**Comment by ghost** [comment]
You'll have to restore it manually through the /chromaprog command.
