### ISSUE TITLE
Fusion reactor plasma !

### ISSUE THREAD

**Issue by tvk1372** [ReikaKalseki/Reika_Mods_Issues#122]
Hy Reika!
I download a mod called Mekanism and I find an interesting portable tank.
It has Fusion plasma,but I can't connect it to the injector,it wont connect to the magnetic pipe.
Is there anyway to connect other pipes to the magnetic pipe to use that tank?
Or the injector could connect other pipes to use this? 
It would  be helpful.

**Comment by jeremiahwinsley** [comment]
Mekanism fusion plasma is for their fusion reactor. It's not compatible with ReactorCraft.

**Comment by ReikaKalseki** [comment]
jeremiah is incorrect. It is ReC fusion plasma, but fusion-handling ReC blocks are hardcoded only to connect to each other.
