### ISSUE TITLE
Casting table returns wrong amount of items

### ISSUE THREAD

**Issue by Aivech** [ReikaKalseki/Reika_Mods_Issues#1220]
I was casting crystalline stone variants for making a pair of lumen beacons and noticed this:

When casting items such that more than one stack of items would be returned, it returns only whole stacks of items, rounding **up**. Thus:

Cast 106 crystalline stone columns. 

Input: 106 crystalline stone (2 * 53 crystalline stone)

Output: Two stacks of crystalline stone beams (2 * 64 crystalline stone beams).

I have a Tier 4 table in a casting complex, with a loot chest to hold the output items next to the casting table. 

Casting items such that a multiple of 64 items or less than 64 items will be returned behaves as expected.

**Comment by Aivech** [comment]
I assume you've been able to replicate this?

**Comment by Builderb0y** [comment]
He's been playing other games for the past few weeks, so unlikely. As a result, this will probably have to wait to be fixed until he does get back to doing minecraft stuff.

**Comment by HellFirePvP** [comment]
I can remember that happen to me even on Reika's pack, however ihave been unable to replicate this consistently.

**Comment by ReikaKalseki** [comment]
Fixed...I hope.
