### ISSUE TITLE
Game and server crash when loading DragonAPI

### ISSUE THREAD

**Issue by benstuwie** [ReikaKalseki/Reika_Mods_Issues#1221]
Whenever I try to run my ResonantRise3 server or client, with the addition of DragonAPI it crashes
http://pastebin.com/HMShYVAq that's the client log
http://pastebin.com/22v2JwdA that's the server log

I tried removing AE2/Reliquary/fast craft but it still wouldn't load

**Comment by ReikaKalseki** [comment]
#1160 #1081 #1077 #998 #989
