### ISSUE TITLE
Still crashing with fastcraft updated to 1.23

### ISSUE THREAD

**Issue by benstuwie** [ReikaKalseki/Reika_Mods_Issues#1222]
http://pastebin.com/c3ETB28B
The other reports you linked me to mentioned updateing fast craft, so I did that
I updated fastcraft from 1.21 to 1.23, but the game still crashes.
http://pastebin.com/VA1Rd1Qc
that's the crashlog for the server. I updated the fastcraft there too, but still no luck

**Comment by ReikaKalseki** [comment]
#919 #902 #906 #914 #916 #921 #924 #963 #1029 #1078
