### ISSUE TITLE
Still crashing after AOBD fix and update of fastcraft

### ISSUE THREAD

**Issue by benstuwie** [ReikaKalseki/Reika_Mods_Issues#1223]
So I updated fast craft from 1.21 to 1.23, but I was still crashing, so I looked through all the issues you linked, and I followed them. I updated AOBD and I changed the config to have them all say false. Still no luck, game crashes right at the end of 5/7 on the forge loading screen
http://pastebin.com/6Ssciwdf

**Comment by DracoScythem** [comment]
> CONFLICT: Potion IDs: com.emoniph.witchery.brewing.potions.PotionSprouting@6b9a0014 @ 35 (PotionSprouting & FreezePotion)
**Check your IDs and change them if possible.**
**This is NOT a mod bug. Do not post it or ask for support or you will look lazy or extremely foolish..**

**Comment by benstuwie** [comment]
Sorry, I just have no idea how to tell what causes crashes
Im really bad with this kind of thing

**Comment by ReikaKalseki** [comment]
You are also very bad at reading instructions.
