### ISSUE TITLE
[CC] Hardcore Ender Expansion Ender Dragon kill does not trigger progression

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1224]
You have to use commands to summon a vanilla dragon for it to trigger properly. I thought I'd already reported this but I guess not...

**Comment by ReikaKalseki** [comment]
What is its entity name or class?

**Comment by HellFirePvP** [comment]
chylex.hee.entity.boss.EntityBossDragon

Superclass: EntityLiving

Implemented interfaces: IBossDisplayData, IEntityMultiPart, IMob

**Comment by Builderb0y** [comment]
As my todo list states, this should probably be done for draconic evolution's re-summoned dragons too. Entity class [here](https://github.com/brandon3055/Draconic-Evolution/blob/1.7.10/src/main/java/com/brandon3055/draconicevolution/common/entity/EntityCustomDragon.java).

**Comment by HellFirePvP** [comment]
@Builderb0y 
It seems it already catches the event in case that is a DE-Enderdragon since DE's does extend EntityDragon whereas HEE's doesn't

EventHandler:
https://github.com/ReikaKalseki/ChromatiCraft/blob/master/ChromaticEventManager.java#L1372

**Comment by ReikaKalseki** [comment]
Done.
