### ISSUE TITLE
[CC] Pylons can damage Openblocks Luggage

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1227]
The Luggage is supposed to be immune to all damage, even falling into the void (it just pops back next to you anyway) yet Pylons can apparently take it down to 0.1 health, although I'm still not sure if they can't kill it, or mine just got really lucky.

![2016-11-23_10 37 15](https://cloud.githubusercontent.com/assets/6917535/20574432/3eccb5a0-b169-11e6-81c1-1883ea44e206.png)

**Comment by ReikaKalseki** [comment]
Done.
