### ISSUE TITLE
Suggestion: change how range boost works. Chromaticraft

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1229]
When I was using range boost to clear some land with a super enchanted bedrock shovel I ended up shoveling blocks I didn't want to break that were pretty far away, I suggest making it so you could "boost" the ability like you could with the others (like health boost) and make it that every 1 bar you add would add 2+ to your range (more or less)

**Comment by ReikaKalseki** [comment]
The problem is that would either add far too many increments, have very large increments - 16+ blocks - or reduce the max range. The last of those is out of the question, and the first two will make it nearly unusable.

**Comment by Builderb0y** [comment]
Non-linear scale maybe? First level adds one block, next level adds 2 more on top of that (3), 3rd level adds 3 more on top of that (6), 4th level adds 4 more (10), etc... That would make 19 incremental levels for a max range of +190 blocks.

**Comment by DracoScythem** [comment]
I'd second the idea of non-linear scaling... although I'd prefer exponential (boostLevel^2) over factorial (boostLevel!) scaling... that's just personal preference though.
Another solution might be having perhaps just 3-5 level with pre-set values (like 10 Blocks (twice vanilla), 30 Blocks (about as far as one could target (and hit) a Block with a bow (without any zoom feature)), and finally the current limit (128 if I recall correctly).
The problem with the way it currently works is that the targeted block is often out of view...

**Comment by ReikaKalseki** [comment]
How about 8 (no power), 12, 16, 32, 64, 128, and 192 (current max)?

**Comment by DracoScythem** [comment]
Seems fine to me - it would definitely allow for a much better control when building without becoming tedious to use :)

**Comment by Builderb0y** [comment]
Would that be 8 blocks total, or 8 blocks longer than normal?

**Comment by ReikaKalseki** [comment]
Total.

**Comment by Builderb0y** [comment]
Then I like that scale.

**Comment by ReikaKalseki** [comment]
Done.
