### ISSUE TITLE
Rock melter UI hotspots mislocated

### ISSUE THREAD

**Issue by Baughn** [ReikaKalseki/Reika_Mods_Issues#123]
![2015-07-07_00 43 01](https://cloud.githubusercontent.com/assets/45811/8535793/3a881220-2441-11e5-90ea-2fe14f53055a.png)

As you can see. Most of the UI shows up as "recipes", which makes extracting netherrack difficult to say the least. The lava volume tooltip, when I hover over that section, is also displaced far down and to the right on the screen, deep into the NEI area.

**Comment by ReikaKalseki** [comment]
The former is a result of the NEI gui being different from the actual GUI. The latter...is an error that appears a great deal.
