### ISSUE TITLE
dragon api is conflicting with electrical age 

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#1231]
dragon api is making the lights in electrical age not light properly
![2016-11-24_11 38 08](https://cloud.githubusercontent.com/assets/23726306/20656084/80ce1cae-b4ee-11e6-8890-d66cf8d62802.png)

**Comment by bloxgate** [comment]
The relevant issues in ElectricalAge are: Electrical-Age/ElectricalAge#474, Electrical-Age/ElectricalAge#505, and Electrical-Age/ElectricalAge#539
