### ISSUE TITLE
[REQUEST] Make Diamond Ore a rare ore for Extractor processing

### ISSUE THREAD

**Issue by Aivech** [ReikaKalseki/Reika_Mods_Issues#1232]
Diamond ore is rarer than both platinum (especially ElectriCraft platinum) and emerald, and you need more of it (especially for RotaryCraft) than either.

Rarity estimates:
Putting a mekanism digital miner in an Extreme Hills biome, vanilla terrain:

* Over a stack of emerald ore
* Approximately a stack of platinum ore (mostly ElectriCraft platinum, only ~7 shiny ore)
* About 1/2 stack diamond ore

**Comment by ReikaKalseki** [comment]
Diamond ore is nowhere near rare enough to warrant the category.

**Comment by Shahelion** [comment]
Of course you'll find more emerald in the only biome that generates it ..
