### ISSUE TITLE
Suggestion: abilities use hotkeys too. Chromaticraft

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1234]
I like the abilities in crc, but most of the time you can only use them ahead of time or on immobile or slow predictable enemies. fireball/sky strike/bolt of power/ instead of being a single use when activated maybe it could stay on and you have to hit a hotkey to use it, or shift right/left click?

**Comment by AshIndigo** [comment]
Or possibly have an option to set your favorite ability which can they be used with the keybind. For abilities that activate and deactivate pressing the button would toggle them. For abilities that are one use just press the button and it will activate

**Comment by ReikaKalseki** [comment]
And when that ability needs a power level?

**Comment by AshIndigo** [comment]
Perhaps when you mark it as a favorite the power level currently selected is the one that is auto used when the key bind is pressed

**Comment by lAimBotl** [comment]
I was thinking it would be activated like how it is now, but it wouldn't use the ability, it would show up on the right like the others after you activate it

**Comment by ReikaKalseki** [comment]
What is the point if it does not use the ability?

**Comment by Aivech** [comment]
I'd second this for "passive" abilities like health leech, instant health, and arrow shield which you would only really use at certain times when using the menu would be too slow.

If the ability has a power level, I'd say make the player determine that when assigning a hotkey to it.

**Comment by lAimBotl** [comment]
I mean it wouldn't use it in the way it is used now, it would be activated similarly to health boost and you would use a hotkey to use the effect after activating it.

**Comment by DracoScythem** [comment]
My idea on how to do that would be a tad different: Why not have 3-5 keys registered as 'CC Ability Hotkey [1-5]' (defaulting to <none>), which can be assigned to any ability by using Ctrl + [Key] whilst in the ability "wheel" (the power level would be set to the one currently defined in the menu) - when assigned pressing them outside the ability selector they will either toggle or activate the bound ability.
[Cosmetic idea: Display the abilities on the right, with a "no-color-filter" like when the ability isn't unlocked yet, along with the defined hotkey (for toggleables: return to the colorful design while active) ; just something I think would look nice]

**Comment by ReikaKalseki** [comment]
This is too difficult to implement and too niche a use case to justify the time expended.
