### ISSUE TITLE
[CC] Avolite fragments reveal themselves too soon

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1235]
I have the revealed fragments for Avolite lamp, defense laser, and one other thing, yet Avolite itself remains scrambled in NEI and invisible in-world.

**Comment by Savallator** [comment]
There are several other fragments which are weirdly out of place.
->Enchantment Decomposer revealing before having access to the relay system
->The Structure for the Green Meteor Tower and the Lumen tree are revealed prior to being able to craft the central blocks, i think it is just the other way round (block reveals before multiblock) for the Energy focus, but i am not 100% sure about that.
->The Lumen Beacon Structure reveals quite early too, but i am not sure how early.

There are some other similar cases, i will post them here when i remember them.

**Comment by Aivech** [comment]
Lumen beacon structure reveals just before the fragments you need to build it do - crystal repeaters.

**Comment by Savallator** [comment]
But the Lumen Beacon also needs the Lumen Beacon Transmitter Block, and although i am not 100% sure, i think it revealed quite some stages later. But however, i think especially the Enchantment Decomposer is the most annyoying thing. When trying to get the "Lumen Harnessing", i at first tried to use the Enchantment Decomposer with the wooden repeaters and could not see why it was not working. That was rather frustrating, so i would suggest to either reveal this fragment only after Broadcasting, or explicitly state in the Description that it is using the relay system. Also, that there is an Icon for the power system when holding Shift should definitely be stated somewhere, as this is really not obvious.

**Comment by Aivech** [comment]
The transmitter block unlocks at the same time crystal repeaters do. Also, the relay system is available with wooden repeaters.

**Comment by Shahelion** [comment]
I was told that the wooden repeaters ONLY worked with the Ritual Altar.

**Comment by Aivech** [comment]
You were told wrong.

**Comment by Savallator** [comment]
But the wooden repeater only unlock the progression if used with the Ritual Altar. at least, thats what i found.

**Comment by ReikaKalseki** [comment]
Also false.

**Comment by ReikaKalseki** [comment]
Fixed.
