### ISSUE TITLE
[RoC] Make certain blocks not OpenComputers components

### ISSUE THREAD

**Issue by Aivech** [ReikaKalseki/Reika_Mods_Issues#1236]
As it is, every single functional block in RotaryCraft is an OpenComputers component. Would it be possible to make this not be the case, so that even slightly more complicated setups don't require a server with component buses installed to run?

Things that really don't need to be components:

**Things computers can't really do anything with**
- Shaft junction & bevel gear
- Bevel gears
- All pipes - This in particular can take a setup from "requires a T3 CPU" to "cannot be run even with the best possible server available to a survival player"
- All shafts
- Ground and overhead sprinklers
- Chain Drive and Belt Hub
- Self-Destruct Mechanism

**Things better interacted with by blocks that OC itself provides, such as the Transposer or a redstone component**
- Anything controlled only by a redstone signal
- Anything which emits a redstone signal under certain conditions and does nothing else
- Gearboxes: read tank with a transposer (or just don't let it run out of lubricant, possibly one of the easiest things to automate)
- Resevoirs: read tank with a transposer
- Fertilizer: read inventory with a transposer or just automate it

**Special cases**
Production machines and engines are useful to have as components for dynamic control purposes.
This applies especially to the Extractor, since AFAIK nothing can see most of its internal inventory.

**Comment by MajorGeneralRelativity** [comment]
I too believe this would be useful. I would like to write control programs for many RotaryCraft machines, but I do not want to have to up the component limits in my OpenComputers configuration file. This issue has my vote for the change.

**Comment by MyNameIsKodos** [comment]
> I do not want to have to up the component limits in my OpenComputers configuration file.

I cannot emphasize how badly this breaks OC's balance.  If there was only one reason to make this change (Not including the fact that it's silly block behavior anyway), it's this.

**Comment by ReikaKalseki** [comment]
This has been discussed ad nauseam. Change the config if you are hitting the limits.

> I cannot emphasize how badly this breaks OC's balance. If there was only one reason to make this change (Not including the fact that it's silly block behavior anyway), it's this.

I do not buy this for a second. That is like saying "There's a pylon near my world spawn! It is killing everyone! Make pylons not kill people/Not generate near spawn" then saying that moving your world's spawn wrecks the balance. Or that you want a bigger inventory because you spawn with too many books and turning some of them off breaks balance.

**Comment by Aivech** [comment]
Is it possible to make them at least not connect to each other as they do? (As in, make them not behave like cables to each other)

On the balance (which I don't _really_ care about, but I'm still not going to change the configs):

The limitations on program size and attached components and the tiering are a large part of what sets OpenComputers apart from ComputerCraft and provide a large portion of its appeal over CC.

**Comment by ReikaKalseki** [comment]
> Is it possible to make them at least not connect to each other as they do? (As in, make them not behave like cables to each other)

No. There are effectively two values for connectivity. Network component and cable, and not accessible whatsoever.

**Comment by Vexatos** [comment]
What about the "cable but not a component, component being accessible through adapter instead" I explained how to use to you a few months ago? In fact, shouldn't it [already be a thing](https://github.com/ReikaKalseki/DragonAPI/blob/master/Base/TileEntityBase.java#L862)?

**Comment by Vexatos** [comment]
... [shouldn't un-commenting this](https://github.com/ReikaKalseki/DragonAPI/blob/6754e1bce281743a5d146fa66dfc2fda0b4e0204/DragonAPIInit.java#L503-L505) make it work?

**Comment by ReikaKalseki** [comment]
Last I remember, that was dependent on a new experimental build of OC that few use. Also, it had classloading issues.

**Comment by Vexatos** [comment]
It wasn't; it should be working just fine, even in OpenComputers 1.5. For what it's worth, OC 1.6 had been released some weeks ago.

**Comment by ReikaKalseki** [comment]
I distinctly remember it causing "have to ship the OC API or get a crash". Even things like @Injectable failed.
