### ISSUE TITLE
[CC] Random Crash every now and then

### ISSUE THREAD

**Issue by zzApotheosis** [ReikaKalseki/Reika_Mods_Issues#1238]
64-bit Java 1.8.0_112-b15
Minecraft 1.7.10
MCP v9.05
FML v7.10.99.99
Minecraft Forge 10.13.4.1614
DragonAPI 1.7.10 V16d
ChromatiCraft 1.7.10 V16d

Now I have no idea why this happens, but every now and then, the client will crash at around stage 5 of 7 during loading with [this crash report](https://drive.google.com/open?id=0B_wljXPJi507akFhQ040MW9HOFE). The crashes are inconsistent and I don't know how to reproduce them since it happens randomly every now and then, but if you want my modpack to test, just let me know. 

I took a look at the report, and it looks like sometimes Forge has trouble finding
Reika.ChromatiCraft.Registry.ChromaResearchManager$ResearchLevel.
I know for a fact ChromatiCraft and DragonAPI are both installed properly, so it's confusing to me why Forge sometimes can't find this class definition.

This and #1237 are all of the issues I could find so far. Hopefully these help!

**Comment by Aivech** [comment]
This is a minor incompatibility with AE2-rev3's custom recipes feature. Disable some things in customrecipes.cfg, detailed in issue https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/481, to fix.
