### ISSUE TITLE
RoC ComputerCraft cannot get power details

### ISSUE THREAD

**Issue by Sil3ntStorm** [ReikaKalseki/Reika_Mods_Issues#1239]
Calling `getPower();` on any machine (tested Extractor, Grinder, Refrigerator) in CC only returns a number with the power value, instead of an array containing the rad/s and torque as well (as is mentioned in the few Google results I found). It does appear to (intend to) do that in https://github.com/ReikaKalseki/RotaryCraft/blob/master/ModInterface/Lua/LuaGetPower.java#L24 however when using v16d and CC 1.75 calling the getPower function just returns a number.

I then tried to read the values using getNBTTag but that just throws an NPE when called like `getNBTTag("omega");`

Using DNS Techpack for MC 1.7.10, but updated your mods.

**Comment by ReikaKalseki** [comment]
It returns an array. Arrays are converted to tables, as is claimed by both CC and OC (and which does occur in the latter). Are you using the correct Lua code? If it is genuinely not working, there is nothing I can do.

**Comment by Builderb0y** [comment]
They're not converted into tables. As I've said before, they're converted into multiple return values. The correct way to get this information would be:
`local power, torque, speed = machine.getPower()`

**Comment by ReikaKalseki** [comment]
Close enough. Either way, Lua-side.

**Comment by Sil3ntStorm** [comment]
@Builderb0y thanks, that didn't occur to me. I expected it to return a table which, as far as I know, is pretty much the array equivalent in Lua.
Works fine now, sorry for the trouble.

**Comment by redelman** [comment]
It did, at one time, return a table. Not sure when that changed.

**Comment by EyeDeck** [comment]
@Sil3ntStorm At least you didn't waste 3 hours trying to parse a newline-delimited string before you remembered about Lua's multiple return thing, like I did one time. That was not my finest moment.
