### ISSUE TITLE
Crash with Gendustry 1.5.2 107 and DragonAPI v7a

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#124]
http://pastebin.com/E1dyPU6Z

This may be related to the earlier issue with the Forestry API change ReikaKalseki/Reika_Mods_Issues#116.

With DragonAPI v7a only added (all other of your mods removed entirely), Gendustry explodes with the above error. This specific version of Gendustry functioned fine with DragonAPI v6f.

Also logged an issue at bdew/gendustry#110

**Comment by ReikaKalseki** [comment]
No, this was a jar packaging error.
