### ISSUE TITLE
ComputerCraft calling doc claims Method not found

### ISSUE THREAD

**Issue by Sil3ntStorm** [ReikaKalseki/Reika_Mods_Issues#1240]
Using ComputerCraft 1.75 and v16d of your mods I noticed that calling `doc` claims the Method does not exist for most methods returned by `peripheral.getMethods(side);` namely
```
getName
getCoords
hasItem
getPlacer
isTankFull
getBlock
getNBTTag
readTank
getSlot
getPower
getSizeInv
isFull
fluidColor
getTanks
printInv
```
This was tested on a few machines from RotaryCraft, they showed the same behavior. Using DNS Techpack for MC 1.7.10, but updated your mods.

**Comment by ReikaKalseki** [comment]
Can you actually call the methods? If so, the issue is on CC's side. If not...it might still be; it works with OC.

**Comment by Sil3ntStorm** [comment]
OpenComputers doesn't list doc as a function on things at all as far as I can tell.
OC lists only the 15 functions mentioned above whereas CC lists 32 in Total, including things like pullItem, getStackInSlot which do get called and work as expected. I can also call functions mentioned above in CC and they work.
`Extractor.pullItem("UP", 1, 10);` in CC for example will remove 10 pieces of Ore from the Chest on top of it and process those in the Extractor.

**Comment by ReikaKalseki** [comment]
pullItem is not one of the functions listed above. Do those ones work?

**Comment by Sil3ntStorm** [comment]
spot checked a few (getPower, getPlacer, getName) and yes those do work.

**Comment by ReikaKalseki** [comment]
Then it is in CC's doc implementation.
