### ISSUE TITLE
A fatal error has occured and the connection is terminated with ChromatiCraft

### ISSUE THREAD

**Issue by shagejack** [ReikaKalseki/Reika_Mods_Issues#1241]
When the ChromatiCraft structure generate in the client render distance then the server terminated the connection.But for a little while the client can join the server again.

Server log(Sorry,because some reason I can not use the pastebin,and sorry about my poor grammer...):

> [15:12:59] [Server thread/ERROR]: FMLIndexedMessageCodec exception caught
> java.lang.NullPointerException
> [15:12:59] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
> java.lang.NullPointerException
> [15:12:59] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
> java.lang.NullPointerException
> [15:12:59] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
> java.lang.NullPointerException
> [15:12:59] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
> java.lang.NullPointerException
> [15:12:59] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
> java.lang.NullPointerException
> [15:12:59] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
> java.lang.NullPointerException
> [15:12:59] [Server thread/WARN]: More than one exception was raised. Will report only the first one and log others.
> java.lang.NullPointerException
> [15:12:59] [Server thread/ERROR]: FMLIndexedMessageCodec exception caught
> java.lang.NullPointerException
> [15:12:59] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
> java.lang.NullPointerException
> [15:12:59] [Server thread/WARN]: More than one exception was raised. Will report only the first one and log others.
> java.lang.NullPointerException
> [15:12:59] [Netty IO #2/INFO]: Client protocol version 2
> [15:13:00] [Netty IO #2/INFO]: Client attempting to join with 219 mods : BuildCraft|Silicon@7.1.17,Enchiridion2@2.0.2a,notenoughIDs@1.4.3.4,ReactorCraft@1.0,CustomOreGen@1.2.24,ExtraBees@2.0-pre14,HardcoreEnderExpansion@1.8.6,essentialcraft@4.6.1710.63,TWarden@1.1.1,Botany@2.0-pre14,FortuneOres@2.0.5,endercore@1.7.10-0.2.0.36_beta,Mystcraft@0.12.3.03,RotaryCraft@1.0,exastris@MC1.7.10-1.16-36,BuildCraft|Robotics@7.1.17,PneumaticCraft@1.12.7-150,technom@0.12.5,BiomesOPlenty@2.1.0,baublesstuff@2.1.2,MineFactoryReloaded|CompatForestry@1.7.10R2.8.1,technomCore@0.12.5,ForgeMultipart@1.2.0.345,BiomeTweaker@2.0.182,BrandonsCore@1.0.0.12,RedstoneArsenal@1.7.10R1.1.2,CoFHCore@1.7.10R3.1.3,powersuits@0.11.0.301,RTG@0.7.0,Talismans 2@1.1.6,fz.scrap@0.8.105,ExtraTrees@2.0-pre14,MariTech@1.0,gendustry@1.6.3.132,bt@1.0.2,BuildCraft|Energy@7.1.17,modtweaker2@0.9.6,IC2@2.2.823-experimental,ExtraTiC@1.4.6,advgenerators@0.9.20.123,minechem@5.0.5.406,arsmagica2@1.4.0.009,IguanaTweaksTConstruct@1.7.10-2.1.6.163,FML@7.10.99.99,Natura@2.2.0,NEIAddons|Forestry@1.12.14.40,ThE-core@1.0.0.1,BiblioWoodsNatura@1.5,factorization@0.8.105,<CoFH ASM>@000,ThermalDynamics@1.7.10R1.2.0,TMechworks@0.2.15.106,LogisticsPipes@0.9.3.122,arcane_engineering@0.2.7,TU@1.0,NotEnoughItems@1.0.5.120,Thaumcraft@4.2.3.5,Waila@1.5.10,Dynmap@2.3-163,simplyjetpacks@1.5.3,appliedenergistics2-core@rv3-beta-6,NEIAddons@1.12.14.40,factorization.notify@1.0,RArm@1.7.10-1.2.0-41,BiblioCraft@1.11.5,BuildCraft|Core@7.1.17,OpenModsCore@0.9.1,cookingbook@1.0.140,ThermalSmeltery@v1.1,AM2-Preloader@0.0.3,betterloadingscreen@1.3.9,SolarExpansion@1.6a,bdlib@1.9.4.109,NEIAddons|Developer@1.12.14.40,tcinventoryscan@1.0.11,MCVanillaTweaks@1.0,DummyCore@1.13,MineFactoryReloaded|CompatAppliedEnergistics@1.7.10R2.8.1,inventorytweaks@1.59-dev-152-cf6e263,MineFactoryReloaded|CompatBuildCraft@1.7.10R2.8.1,Morpheus@1.7.10-1.6.21,JourneyMapServer@1.0.5_MC1.7.10,OpenBlocks@1.5.1,ForbiddenMagic@1.7.10-0.575,EnderTech@1.7.10-0.3.2.405,MineFactoryReloaded|CompatForgeMicroblock@1.7.10R2.8.1,CarpentersBlocks@3.3.8,EnderIO@1.7.10-2.3.0.429_beta,CustomMainMenu@1.8,neiintegration@1.1.2,Enchiridion@1.3,immersiveintegration@0.6.8,SolarFlux@1.7.10-0.8b,NEIAddons|Botany@1.12.14.40,<DragonAPI ASM>@0,SonarCore@1.1.3,numina@0.4.0.131,thaumicenergistics@1.0.0.5,CodeChickenCore@1.0.7.47,BigReactors@0.4.3A,CoreTinkerTailor@Whatever,Mekanism@9.0.1,MekanismTools@9.0.1,MineTweaker3@3.0.10,BinniePatcher@1.8.2,ThaumicTinkerer-preloader@0.1,aobd@2.9.2,openradio@0.6.1,TravellersGear@1.16.6,gadomancy@1.0.7.2,MorePlanet@1.2.9,Baubles@1.0.1.10,ArchitectureCraft@1.4.1,SilentGems@1.3.14,Forestry@4.2.15.63,OpenMods@0.9.1,RIO@2.4.0,GalacticraftCore@3.0.12,BiblioWoodsBoP@1.9,flansmod@4.10.0,HardcoreQuesting@4.4.4,TinkersTailor@1.0,ForgeMicroblock@1.2.0.345,iChunUtil@4.2.2,rftools@4.23,Ztones@1.7.10,autopackager@1.5.9a,ThaumicExploration@0.6.0,EnderZoo@1.7.10-1.0.15.32,MagicBees@2.4.3,factorization.misc@0.8.105,ae2stuff@0.5.0.56,DragonAPI@1.0,OpenComputers@1.6.0.7-rc.1,CustomChestLoot@1.1.1,McMultipart@1.2.0.345,Mariculture@1.7.10-1.2.4.2a,ExtraUtilities@1.2.12,Micdoodlecore@,climatecontrol@0.4,IC2NuclearControl@2.4.1a,ThermalFoundation@1.7.10R1.2.5,MineFactoryReloaded|CompatVanilla@1.7.10R2.8.1,StevesCarts@2.0.0.b18,ThaumicHorizons@1.1.9,BiblioWoodsForestry@1.7,FastCraft@1.23,Forge@10.13.4.1614,OpenComputers|Core@1.6.0.7-rc.1,ThaumicTinkerer@unspecified,MineFactoryReloaded|CompatChococraft@1.7.10R2.8.1,JABBA@1.2.2,enviromine@1.3.124,MineFactoryReloaded|CompatIC2@1.7.10R2.8.1,AppleCore@1.3.2,TiCTooltips@1.2.5,bigtrees@0.2,MCA@1.7.10-5.1.2,HungerOverhaul@1.7.10-1.0.0.jenkins75,NEIAddons|CraftingTables@1.12.14.40,NEIAddons|ExNihilo@1.12.14.40,WailaHarvestability@1.1.6,Botania@r1.8-249,Hats@4.0.1,yegamolchattels@1.1.2,Avaritia@1.11,FTBU@1.0.18.2,exnihilo@1.38-53,TConstruct@1.7.10-1.8.8.build988,extracells@2.3.14,factorization.dimensionalSlice@0.8.105,BinnieCore@2.0-pre14,factorization.truth@0.8.105,ivtoolkit@1.2.1,ImmersiveEngineering@0.7.7,NuclearCraft@1.9c,wawla@1.3.1,Genetics@2.0-pre14,mcp@9.05,Mantle@1.7.10-0.3.2.jenkins191,journeymap@5.1.4p1,appliedenergistics2@rv3-beta-6,MineFactoryReloaded|CompatTConstruct@1.7.10R2.8.1,DraconicEvolution@1.0.2h,harvestcraft@1.7.10j,ChromatiCraft@1.0,TaintedMagic@1.1.6.4,UtilityMobs@3.1.1,ThermalExpansion@1.7.10R4.1.4,BuildCraft|Factory@7.1.17,MineFactoryReloaded|CompatThaumcraft@1.7.10R2.8.1,AgriCraft@1.7.10-1.5.0,NEIAddons|AppEng@1.12.14.40,ElectriCraft@1.0,RadixCore@2.1.1,FTBL@1.0.18.2,chococraft@4.1.5,GalacticraftMars@3.0.12,MineFactoryReloaded@1.7.10R2.8.1,BuildCraft|Compat@7.1.5,wailaplugins@MC1.7.10-0.2.0-23,ThermalCasting@0.0.3,AWWayofTime@v1.3.3,IronChest@6.0.60.741,MineFactoryReloaded|CompatThermalExpansion@1.7.10R2.8.1,thaumicbases@1.3.1710.2,SpiceOfLife@1.3.2,AnimationAPI@1.2.4,Calculator@1.9.11,WitchingGadgetsCore@1.1.10,NetherOres@1.7.10R2.3.1,tinker_io@release 1.5.0,BuildCraft|Transport@7.1.17,TCBotaniaExoflame@1.0,chisel@2.9.5.11,WitchingGadgets@1.1.10,PotionIDHelper@1.0.4,BuildCraft|Builders@7.1.17,chiseltones@@VERSION@
> [15:13:00] [Netty IO #2/INFO]: CLIENT
> [15:13:00] [Netty IO #2/INFO]: Attempting connection with missing mods [kimagine, fc-dummy] at CLIENT
> [15:13:01] [Server thread/INFO]: yfk2012 lost connection: Disconnected
> [15:13:01] [Server thread/ERROR]: FMLIndexedMessageCodec exception caught
> java.lang.NullPointerException
> [15:13:01] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
> java.lang.NullPointerException
> [15:13:01] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
> java.lang.NullPointerException
> [15:13:01] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
> java.lang.NullPointerException
> [15:13:01] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
> java.lang.NullPointerException
> [15:13:01] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
> java.lang.NullPointerException
> [15:13:01] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
> java.lang.NullPointerException
> [15:13:01] [Server thread/WARN]: More than one exception was raised. Will report only the first one and log others.
> java.lang.NullPointerException
> [15:13:01] [Server thread/ERROR]: FMLIndexedMessageCodec exception caught
> java.lang.NullPointerException
> [15:13:01] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
> java.lang.NullPointerException
> [15:13:01] [Server thread/WARN]: More than one exception was raised. Will report only the first one and log others.
> java.lang.NullPointerException
> [15:13:08] [User Authenticator #24/INFO]: UUID of player yfk2012 is 5395b807-3ad3-30f8-8d97-991470df7d7e
> [15:13:09] [Netty IO #0/INFO]: Client protocol version 2
> [15:13:09] [Netty IO #0/INFO]: Client attempting to join with 219 mods : BuildCraft|Silicon@7.1.17,Enchiridion2@2.0.2a,notenoughIDs@1.4.3.4,ReactorCraft@1.0,CustomOreGen@1.2.24,ExtraBees@2.0-pre14,HardcoreEnderExpansion@1.8.6,essentialcraft@4.6.1710.63,TWarden@1.1.1,Botany@2.0-pre14,FortuneOres@2.0.5,endercore@1.7.10-0.2.0.36_beta,Mystcraft@0.12.3.03,RotaryCraft@1.0,exastris@MC1.7.10-1.16-36,BuildCraft|Robotics@7.1.17,PneumaticCraft@1.12.7-150,technom@0.12.5,BiomesOPlenty@2.1.0,baublesstuff@2.1.2,MineFactoryReloaded|CompatForestry@1.7.10R2.8.1,technomCore@0.12.5,ForgeMultipart@1.2.0.345,BiomeTweaker@2.0.182,BrandonsCore@1.0.0.12,RedstoneArsenal@1.7.10R1.1.2,CoFHCore@1.7.10R3.1.3,powersuits@0.11.0.301,RTG@0.7.0,Talismans 2@1.1.6,fz.scrap@0.8.105,ExtraTrees@2.0-pre14,MariTech@1.0,gendustry@1.6.3.132,bt@1.0.2,BuildCraft|Energy@7.1.17,modtweaker2@0.9.6,IC2@2.2.823-experimental,ExtraTiC@1.4.6,advgenerators@0.9.20.123,minechem@5.0.5.406,arsmagica2@1.4.0.009,IguanaTweaksTConstruct@1.7.10-2.1.6.163,FML@7.10.99.99,Natura@2.2.0,NEIAddons|Forestry@1.12.14.40,ThE-core@1.0.0.1,BiblioWoodsNatura@1.5,factorization@0.8.105,<CoFH ASM>@000,ThermalDynamics@1.7.10R1.2.0,TMechworks@0.2.15.106,LogisticsPipes@0.9.3.122,arcane_engineering@0.2.7,TU@1.0,NotEnoughItems@1.0.5.120,Thaumcraft@4.2.3.5,Waila@1.5.10,Dynmap@2.3-163,simplyjetpacks@1.5.3,appliedenergistics2-core@rv3-beta-6,NEIAddons@1.12.14.40,factorization.notify@1.0,RArm@1.7.10-1.2.0-41,BiblioCraft@1.11.5,BuildCraft|Core@7.1.17,OpenModsCore@0.9.1,cookingbook@1.0.140,ThermalSmeltery@v1.1,AM2-Preloader@0.0.3,betterloadingscreen@1.3.9,SolarExpansion@1.6a,bdlib@1.9.4.109,NEIAddons|Developer@1.12.14.40,tcinventoryscan@1.0.11,MCVanillaTweaks@1.0,DummyCore@1.13,MineFactoryReloaded|CompatAppliedEnergistics@1.7.10R2.8.1,inventorytweaks@1.59-dev-152-cf6e263,MineFactoryReloaded|CompatBuildCraft@1.7.10R2.8.1,Morpheus@1.7.10-1.6.21,JourneyMapServer@1.0.5_MC1.7.10,OpenBlocks@1.5.1,ForbiddenMagic@1.7.10-0.575,EnderTech@1.7.10-0.3.2.405,MineFactoryReloaded|CompatForgeMicroblock@1.7.10R2.8.1,CarpentersBlocks@3.3.8,EnderIO@1.7.10-2.3.0.429_beta,CustomMainMenu@1.8,neiintegration@1.1.2,Enchiridion@1.3,immersiveintegration@0.6.8,SolarFlux@1.7.10-0.8b,NEIAddons|Botany@1.12.14.40,<DragonAPI ASM>@0,SonarCore@1.1.3,numina@0.4.0.131,thaumicenergistics@1.0.0.5,CodeChickenCore@1.0.7.47,BigReactors@0.4.3A,CoreTinkerTailor@Whatever,Mekanism@9.0.1,MekanismTools@9.0.1,MineTweaker3@3.0.10,BinniePatcher@1.8.2,ThaumicTinkerer-preloader@0.1,aobd@2.9.2,openradio@0.6.1,TravellersGear@1.16.6,gadomancy@1.0.7.2,MorePlanet@1.2.9,Baubles@1.0.1.10,ArchitectureCraft@1.4.1,SilentGems@1.3.14,Forestry@4.2.15.63,OpenMods@0.9.1,RIO@2.4.0,GalacticraftCore@3.0.12,BiblioWoodsBoP@1.9,flansmod@4.10.0,HardcoreQuesting@4.4.4,TinkersTailor@1.0,ForgeMicroblock@1.2.0.345,iChunUtil@4.2.2,rftools@4.23,Ztones@1.7.10,autopackager@1.5.9a,ThaumicExploration@0.6.0,EnderZoo@1.7.10-1.0.15.32,MagicBees@2.4.3,factorization.misc@0.8.105,ae2stuff@0.5.0.56,DragonAPI@1.0,OpenComputers@1.6.0.7-rc.1,CustomChestLoot@1.1.1,McMultipart@1.2.0.345,Mariculture@1.7.10-1.2.4.2a,ExtraUtilities@1.2.12,Micdoodlecore@,climatecontrol@0.4,IC2NuclearControl@2.4.1a,ThermalFoundation@1.7.10R1.2.5,MineFactoryReloaded|CompatVanilla@1.7.10R2.8.1,StevesCarts@2.0.0.b18,ThaumicHorizons@1.1.9,BiblioWoodsForestry@1.7,FastCraft@1.23,Forge@10.13.4.1614,OpenComputers|Core@1.6.0.7-rc.1,ThaumicTinkerer@unspecified,MineFactoryReloaded|CompatChococraft@1.7.10R2.8.1,JABBA@1.2.2,enviromine@1.3.124,MineFactoryReloaded|CompatIC2@1.7.10R2.8.1,AppleCore@1.3.2,TiCTooltips@1.2.5,bigtrees@0.2,MCA@1.7.10-5.1.2,HungerOverhaul@1.7.10-1.0.0.jenkins75,NEIAddons|CraftingTables@1.12.14.40,NEIAddons|ExNihilo@1.12.14.40,WailaHarvestability@1.1.6,Botania@r1.8-249,Hats@4.0.1,yegamolchattels@1.1.2,Avaritia@1.11,FTBU@1.0.18.2,exnihilo@1.38-53,TConstruct@1.7.10-1.8.8.build988,extracells@2.3.14,factorization.dimensionalSlice@0.8.105,BinnieCore@2.0-pre14,factorization.truth@0.8.105,ivtoolkit@1.2.1,ImmersiveEngineering@0.7.7,NuclearCraft@1.9c,wawla@1.3.1,Genetics@2.0-pre14,mcp@9.05,Mantle@1.7.10-0.3.2.jenkins191,journeymap@5.1.4p1,appliedenergistics2@rv3-beta-6,MineFactoryReloaded|CompatTConstruct@1.7.10R2.8.1,DraconicEvolution@1.0.2h,harvestcraft@1.7.10j,ChromatiCraft@1.0,TaintedMagic@1.1.6.4,UtilityMobs@3.1.1,ThermalExpansion@1.7.10R4.1.4,BuildCraft|Factory@7.1.17,MineFactoryReloaded|CompatThaumcraft@1.7.10R2.8.1,AgriCraft@1.7.10-1.5.0,NEIAddons|AppEng@1.12.14.40,ElectriCraft@1.0,RadixCore@2.1.1,FTBL@1.0.18.2,chococraft@4.1.5,GalacticraftMars@3.0.12,MineFactoryReloaded@1.7.10R2.8.1,BuildCraft|Compat@7.1.5,wailaplugins@MC1.7.10-0.2.0-23,ThermalCasting@0.0.3,AWWayofTime@v1.3.3,IronChest@6.0.60.741,MineFactoryReloaded|CompatThermalExpansion@1.7.10R2.8.1,thaumicbases@1.3.1710.2,SpiceOfLife@1.3.2,AnimationAPI@1.2.4,Calculator@1.9.11,WitchingGadgetsCore@1.1.10,NetherOres@1.7.10R2.3.1,tinker_io@release 1.5.0,BuildCraft|Transport@7.1.17,TCBotaniaExoflame@1.0,chisel@2.9.5.11,WitchingGadgets@1.1.10,PotionIDHelper@1.0.4,BuildCraft|Builders@7.1.17,chiseltones@@VERSION@
> [15:13:09] [Netty IO #0/INFO]: CLIENT
> [15:13:09] [Netty IO #0/INFO]: Attempting connection with missing mods [kimagine, fc-dummy] at CLIENT
> [15:13:21] [Server thread/INFO]: [Server thread] Server side modded connection established
> [15:13:21] [Server thread/INFO]: SMP: Sync dimensions to client
> [15:13:21] [Server thread/INFO]: yfk2012[/119.247.231.204:53326] logged in with entity id 20092 at ([world] -100.69999998807907, 77.0, -202.89852130908451)
> [15:13:21] [Server thread/INFO]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
> [15:13:21] [Server thread/INFO]: Sending server configs to client for tehnut.redstonearmory.ConfigHandler
> [15:13:21] [Server thread/INFO]: Sending server configs to client for tterrag.wailaplugins.config.WPConfigHandler
> [15:13:21] [Server thread/INFO]: Sending mutations to player: yfk2012
> [15:13:21] [Server thread/INFO]: Player GCEntityPlayerMP['yfk2012'/20092, l='world', x=-100.70, y=77.00, z=-202.90](yfk2012 at -100.69999998807907,77.0,-202.89852130908451) connected. Sending ping
> [15:13:21] [Server thread/INFO]: npe choco
> [15:13:21] [Server thread/INFO]: Sent config to 'yfk2012.'
> [15:13:21] [Server thread/INFO]: SMP: Player logged in: Sync diminfo to clients
> [15:13:21] [Server thread/INFO]: Sync dimension info to clients!
> [15:13:21] [Server thread/INFO]: Send validation data to the client
> [15:13:24] [Server thread/INFO]: syncToClient: style = STYLE_FLAT_GRADIENT
> [15:13:26] [Server thread/INFO]: DRAGONAPI: Player yfk2012 passed hash check for ElectriCraft. Hash: F10584FE8601DE3118A2E7B8319FB5605F006D0557F90FCB9A9FA834AC68FD20
> [15:13:26] [Server thread/ERROR]: There was a critical exception handling a packet on channel DragonAPIData
> java.lang.NullPointerException
> [15:13:36] [Server thread/INFO]: yfk2012 lost connection: A fatal error has occured, this connection is terminated

**Comment by ReikaKalseki** [comment]
That part of the log is not helpful.

**Comment by AshIndigo** [comment]
And please put your logs on pastebin
