### ISSUE TITLE
[GeoStrata] Constant spam of "Server thread/ERROR" message in console + a small visual bug

### ISSUE THREAD

**Issue by Carnaxus** [ReikaKalseki/Reika_Mods_Issues#1242]
Hey Reika.  I'm running a custom modpack, and my console is being spammed with "[16:11:29] [Server thread/ERROR]: A TileEntity type Reika.GeoStrata.TileEntityGeoOre has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException"

[Full modlist (in alphabetic order)](http://pastebin.com/7QVVutMt)

I did just notice where it says "has throw an exception" instead of "has thrown an exception."  I suppose this could be another modder trying to interfere with your mods because they for some unknown reason hate you.

Regarding the "small visual bug," WAILA's popup on any GeoStrata ore type (copper in basalt, tin in limestone, etc) says "Coal Granite Ore."  It does drop the correct item (copper ore, tin ore, etc), but it did confuse me at first.

**Comment by ReikaKalseki** [comment]
The ores are only half-implemented.

**Comment by Carnaxus** [comment]
Ah.  So the console bug is also related to the ores then?

**Comment by ReikaKalseki** [comment]
Considering it mentions GeoOre....

**Comment by Carnaxus** [comment]
Oh.  Right.  Sorry.  Posting late at night is a bad idea even when _not_ drunk, it seems.
