### ISSUE TITLE
Fractation unit doesn't require all 6 ingredients to create jet fuel

### ISSUE THREAD

**Issue by bermovick** [ReikaKalseki/Reika_Mods_Issues#1243]
As the screenshot shows, the fractation unit only seems to require all 6 input slots to be filled with one of its ingredients, but allows you to use the same ingredient in all slots.

(semi-related, should charcoal even be valid?  The recipe calls for coal only.  Coal coke doesn't work but charcoal does)

![2016-12-03_21 59 24](https://cloud.githubusercontent.com/assets/24364331/20863981/17d8a29a-b9a4-11e6-8f64-b07523d9f531.png)

**Comment by ReikaKalseki** [comment]
Done.

**Comment by ianleeder** [comment]
Commenting with the correct spelling of "Fractionation" so that this issue appears in searches.
