### ISSUE TITLE
Possible conflict between NEI and Rotarycraft ? Client Crashing when looking at recipes on server.

### ISSUE THREAD

**Issue by Camo-Steve** [ReikaKalseki/Reika_Mods_Issues#1244]
Hello,

When trying to play on my custom minecraft server, my client crashes when trying to look at any recipe. It looks like there is a conflict between Rotartycraft and NEI. However, that was all I could deduced from the crash log (I'm not a programmer.) 

If there's already a solution out there, I apologize. I didn't see it in any of my searches. 

(MultiMC crash log)
http://paste.ee/p/n56bf

**Comment by DracoScythem** [comment]
Try updating NEI to 1.0.5.120 (Never had issues with that version with ~300 mods running)

**Comment by Camo-Steve** [comment]
I just tried that with no luck. I still get the same client crash.

**Comment by Camo-Steve** [comment]
Ok, I figured out a weird fix. If you set up a singleplayer adventure world, click a recipe, leave the server, then pop on the multiplayer server, you will no longer crash.  However, you have to do that every time you load up your client.

**Comment by ReikaKalseki** [comment]
I do not have any such issues.

**Comment by Camo-Steve** [comment]
Hmm, if you can't reproduce it. Then perhaps it's a combination of not just Rotarycraft and NEI, but also other mods from my modpack.

**Comment by ReikaKalseki** [comment]
Keep testing.

**Comment by Camo-Steve** [comment]
I'm already working on it, however I have to spread it over a weekish period, or I will burn myself out of MC for a few months.

**Comment by Builderb0y** [comment]
Or just use a binary split search. Even with 140 mods installed that should take no longer than a few hours.

**Comment by ReikaKalseki** [comment]
More like fifteen minutes.

**Comment by Camo-Steve** [comment]
Ok, I got tired of trying to figure out the conflict, so I made a fresh modpack with the latest versions of the mods and I trimmed the mod count to 105. I no longer have the client crash issue anymore. So i'm just going to close this, even though I never discovered the problem. ty.
