### ISSUE TITLE
[CC] server startup crash

### ISSUE THREAD

**Issue by wormzjl** [ReikaKalseki/Reika_Mods_Issues#1245]
http://pastebin.com/DPv1qBrR
Umm did I done something wrong here?

**Comment by wormzjl** [comment]
Ok this only happens when both CC and immibis microblocks are installed.
WTF-.-???

**Comment by ReikaKalseki** [comment]
This looks like a CC bug...are you sure it only happens with Microblocks?

**Comment by wormzjl** [comment]
Yeah, this does not happen with only one of them and only on server

**Comment by ReikaKalseki** [comment]
In that case, he is probably calling something from an invalid side.
