### ISSUE TITLE
Energy Acceptor not accepting energy when using a specific setup

### ISSUE THREAD

**Issue by Rewyn** [ReikaKalseki/Reika_Mods_Issues#1248]
Tested with Rotarycraft and DragonAPI v16d, as well as ae2 rv3 beta 6.
Only other mods present were NotEnoughItems and CodeChickenCore.

http://i.imgur.com/JEMiCbE.png
(Picture taken with the Revolution 3 Modpack, v3.4.4)

The Energy Acceptor in the bottom row does not accept power, the 3 rows above do.
All Shaft Junctions are on split mode.
If the block right before the Energy Acceptor is something else besides a Shaft Unit, it works, as shown in the topmost row. Tested with a 2:1 Bedrock Gearbox as well.
Only managed to reproduce if the 2 blocks infront of the energy acceptor were the Shaft Junction (Split mode) and a Shaft Unit. Anthing before that did not seem to affect the outcome.

**Comment by ReikaKalseki** [comment]
The RC API works because ReC does. AE is either using a wrong version or using it incorrectly.

**Comment by Rewyn** [comment]
At least it wasn't just me being completely derpy there. Thanks for the quick reaction!
