### ISSUE TITLE
Unreachable update sever will make client launch very slow

### ISSUE THREAD

**Issue by wormzjl** [ReikaKalseki/Reika_Mods_Issues#1249]
Seems that in places like china the update server can be unreachable due to internet censorship
Which means with each reika's mod installed the client need to wait for more time for the update checker to time out
Is it possible to make the update check a separate thread instead of blocking the game from launching? 
Or simply decrease the timeout time?

**Comment by ReikaKalseki** [comment]
#473

**Comment by wormzjl** [comment]
guess that I have to find some alternative solution

**Comment by redelman** [comment]
Put the update server URL, whatever it is, in your hosts file, pointing to localhost. The update check will fail immediately and not wait for a timeout.

**Comment by ReikaKalseki** [comment]
No, that will not work.
