### ISSUE TITLE
Reactor CPU Remote Control Crash, Central Control GUI is off-centered

### ISSUE THREAD

**Issue by Fatmice** [ReikaKalseki/Reika_Mods_Issues#125]
Linked reactor CPU remote control will CTD upon activation.

https://gist.github.com/Fatmice/5fe0cb7b8abcd466913d

Central Control GUI is off-centered
![2015-07-08_03 54 58](https://cloud.githubusercontent.com/assets/8956281/8566753/e39edfa8-2525-11e5-8bd1-cbe22497492d.png)

Mods:
  ChromatiCraft 1.7.10 V7a
  DragonAPI 1.7.10 V7a
  ElectriCraft 1.7.10 V7a
  ExpandedRedstone 1.7.10 V7a
  ReactorCraft 1.7.10 V7a
  RotaryCraft 1.7.10 V7a
  CodeChickenCore-1.7.10-1.0.7.46-universal
  MobiusCore-1.2.5_1.7.10
  NotEnoughItems-1.7.10-1.0.5.111-universal
  Opis-1.2.5_1.7.10
  Waila-1.5.10_1.7.10
Savegame:
http://www.mediafire.com/download/yk45a2182gutkk2/Remote_CPU.zip

**Comment by ReikaKalseki** [comment]
The crash log only points to vanilla packet code and is thus untrackable.

I will fix the GUI issue.

**Comment by ReikaKalseki** [comment]
OK, I fixed the crash too. With a hack, to be sure, but it works now.
