### ISSUE TITLE
[CC] Ethereal Barrier Rendering

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1251]
Inside corners don't render properly/at all.

![2016-12-09_12 55 09](https://cloud.githubusercontent.com/assets/6917535/21064517/08018fa6-be10-11e6-9a90-1b16a638ff0b.png)
![2016-12-09_12 55 16](https://cloud.githubusercontent.com/assets/6917535/21064518/0801ca7a-be10-11e6-9ffc-e1956669817f.png)

**Comment by ReikaKalseki** [comment]
Not fixable.

**Comment by Shahelion** [comment]
Yeah, I figured that might be the case.
