### ISSUE TITLE
Breaking gearbox with 0 durability pick doesn't drop item

### ISSUE THREAD

**Issue by bermovick** [ReikaKalseki/Reika_Mods_Issues#1253]
It's such a freak occurrence I can't (easily) test for other blocks that would be affected.

**Comment by Builderb0y** [comment]
That's vanilla behavior; the item being used for mining gets processed first, and the block being mined gets processed later. So the pick breaks first, then the block thinks it got mined with an empty hand. This is also why silk touch doesn't work on the final use of a tool.
