### ISSUE TITLE
[CC] Casting Table Item Stands, Incorrect Item Consumed on Last(?) Tick

### ISSUE THREAD

**Issue by PaladinOne** [ReikaKalseki/Reika_Mods_Issues#1254]
So I was running a Casting Table crafting of Crystal Stars, and within the final moment of the crafting, misclicked on one of the Item Stands and replaced the Crystal Core on it with a Bedrock Sword. The recipe promptly completed and ate the sword.

**Comment by HellFirePvP** [comment]
Can confirm that happening, however your timing needs to be *on point* to replicate this properly.

**Comment by ReikaKalseki** [comment]
Fixed.
