### ISSUE TITLE
[CC] Crystal Repeater Rendering AIOOB

### ISSUE THREAD

**Issue by PaladinOne** [ReikaKalseki/Reika_Mods_Issues#1255]
Don't think I was doing anything special, just kind of standing around waiting for a Casting Table to fill up on power.

http://pastebin.com/ibLDTbE6

**Comment by ReikaKalseki** [comment]
Does this happen consistently? This looks like invalid tile data.

**Comment by ReikaKalseki** [comment]
Hello?
