### ISSUE TITLE
[Chromaticraft/Rotarycraft] Suggestion: Lumen gearboxes

### ISSUE THREAD

**Issue by AshIndigo** [ReikaKalseki/Reika_Mods_Issues#1256]
Theres already mana consuming gear boxes, so why not gearboxes that use lumens from the relay system to keep themselves un-damaged.

Materials for crafting:
The stone version can use crystalline stone to craft or perhaps shielding stone.
The wooden one can use shimmering wood to craft

Lumens used:
They would probably use Vadali or Karmir or a combination of them to keep the box repaired.
Then Galazio or Asveste could be added to potentially increase the speed in the gearbox without requiring more engines.

**Comment by Aivech** [comment]
Might I recommend to you the Kurauri adjacency core?

**Comment by AshIndigo** [comment]
Those only work for one block at a time though. Kind of inane to make a bunch of cores for gearboxes considering each one uses a crystal star will get expensive fast.

**Comment by Aivech** [comment]
Then I would suggest keeping your gearboxes lubricated properly or using bedrock/diamond gears. Lubricant is cheap.

**Comment by AshIndigo** [comment]
Then by that regard, whats the point of mana gearboxes. This suggestions is just an alternate for those if Botania is not installed

**Comment by Aivech** [comment]
I honestly have no idea.

**Comment by AshIndigo** [comment]
I can imagine a minor usage for the stone gearboxes because of there higher torque and speed limits

**Comment by ghost** [comment]
Lumens aren't easily obtained till the end of mid-game. There are weak repeaters, yes, but those explode eventually. Mana can be made within the first 10 minutes of Botania, lumens can't be harnessed that fast. 

Assuming it used relay power, would it be worth it to make relays all the way to where I'd have the gearbox just for the limits of stone level torque and speed? If it was a diamond level, maybe, otherwise it's not worth it.

**Comment by HellFirePvP** [comment]
It doesn't seem to be worth it though. By the time you get to a point where lumens become uniformly useable anywhere, you don't care about lubricant or similiar things anymore. A feature without practical use is not needed.

**Comment by AshIndigo** [comment]
I would be perfectly good with higher level boxes but I was following what Reika did with the mana gearboxes
