### ISSUE TITLE
Chromaticraft research crash?

### ISSUE THREAD

**Issue by Reginald-Halifrax** [ReikaKalseki/Reika_Mods_Issues#1257]
Was attempting to update mods to a modpack i use and chromaticraft spat out a crash report i cant make much sense out of.

[crash.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/647832/crash.txt)

If it helps at all the mods i updated are:

> Academy craft,
> Applied energistcs 2,
> Biomes o plenty,
> computercraft,
> ex compressum,
> Forbidden Magic,
> Forestry,
> Growthcraft COMMUNITY edition,
> ICBM from Darkguardsman,
> Iguana tinker tweaks,
> immersive Engineering,
> Industrial craft,
> Mantle and tinkers construct,
> Matter overdrive,
> Modtweaker and minetweaker i think,
> modular powersuits and numina,
> NEI,
> Opencomputers,
> Openmodularturrets,
> Origin,
> Projecte,
> Tainted magic,
> Technomancy
> Thaumic energistics,
> Voltz engine,
> And Waila plugins.

Any help would be appreciated

**Comment by ReikaKalseki** [comment]
#1238, #1197, #1106, #931, #661, #599, #481
