### ISSUE TITLE
[Rotarycraft/Agricraft] Missing canola seed texture in Agricraft seed storage block

### ISSUE THREAD

**Issue by AshIndigo** [ReikaKalseki/Reika_Mods_Issues#1259]
Heres a screenshot, http://imgur.com/a/LlOZ8

To reproduce:
Get a seed storage block.
Get an identified canola seed so it can be inserted into the seed storage.
Insert the seed into the storage
And then you get the missing icon

**Comment by ReikaKalseki** [comment]
That is on him to handle IItemRenders properly.
