### ISSUE TITLE
Reika mod updates cause black screen with Thaumcraft warp events

### ISSUE THREAD

**Issue by NEbuddy** [ReikaKalseki/Reika_Mods_Issues#126]
I don't know if this has been reported yet, but is there any chance you could change the default way that the notifications pop up to indicate an update to the various Reika mods is available? I'm on a server (so I don't have control of when the mods update), but the aggressive update notification causes the screen to go black when Thaumcraft warp events occur. I can still see the contents of inventories when they're open and Waila info, but everything else in the screen is black. The only way to fix it is to restart the client. As a result, it means having to log out in areas that might not be safe (like above a lava lake in the nether). I know that the aggressive update notification can be turned off in the config, but the black screen it can cause for those that are unaware of the config setting still seems like a bit of a bug to me. Any chance you could put the update notifications back in the chat area like EVERY other mod? Thanks

**Comment by coolsquid** [comment]
Version? Quite sure this was fixed ages ago.

**Comment by ReikaKalseki** [comment]
It was.

**Comment by NEbuddy** [comment]
The problem persists with DragonAPI V6f, ElectriCraft V6a, RotaryCraft V6f, and ReactorCraft V6e. So unless V7 of the Reika mods have been out for "ages" (because I guess about 24 hours is "ages" now), it's a fairly recent version that has the problem.

Oh, and btw, thanks for closing the bug report before giving me ANY chance to post any additional info like the versions of the mods that are installed.

**Comment by ReikaKalseki** [comment]
I remember fixing this in v6, and yes, the v7 version of the update checker does indeed redesign the overlay and prevent this issue from happening again.

Also, getting upset when you report something that was fixed in a previous version and the thread is closed is hardly reasonable.

**Comment by NEbuddy** [comment]
I wasn't getting upset. Frustrated maybe, but not upset. It's kind of frustrating to have someone say that a fix was released ages ago when the server I'm on is running v6f of DragonAPI (as I understand it the lastest release before v7a) and v7 was just released yesterday. Feelings don't really translate through text all that well. I also never had a chance to post any kind of a response before you closed the report, so saying that it's "hardly reasonable" is debatable. If you fixed it in one of the v6 releases, the fix was removed or didn't work in v6f of DragonAPI because I've had to regularly restart my client because of black screens. Also, looking at the changelog, it only mentioned the overhaul of the update checker for the v7 release.

I only posted the issue because I wasn't sure if you were aware of the problem with v6f.

**Comment by ReikaKalseki** [comment]
You say the issue has been plaguing you for some time; v6 has been out for about three months; why did you only report this now?

**Comment by NEbuddy** [comment]
By regular black screens, I meant that they've been happening regularly ever since the new update was released yesterday and the update notification popped up. Up until v7 was released, I had never seen the update notifications before. Hence why I posted the issue today.

Edit: The server that I'm on just added your mods to the pack we're playing a few weeks ago. If there was an update that was released in that time, the pack was updated before I ever saw the notification. So this is the first time I've experienced the problem.

**Comment by ReikaKalseki** [comment]
> By regular black screens, I meant that they've been happening regularly ever since the new update was released yesterday and the update notification popped up. Up until v7 was released, I had never seen the update notifications before. Hence why I posted the issue today.

Derp. That makes sense. :P
