### ISSUE TITLE
Ticking Entity crash (Potion Effects) caused by RotaryCraft

### ISSUE THREAD

**Issue by DeLourium** [ReikaKalseki/Reika_Mods_Issues#1260]
When I installed RotaryCraft, I started to get the following crash.
It´s quite similar to the one being mentioned here:
#1048 

BUT: I don´t have ChromatiCraft installed. In fact I´ve tried to figure out, which mod caused this crash
and I found out that the crash starts occuring when I installed RotaryCraft.

Here´s the log: http://pastebin.com/U6fzkM0B

**Comment by DeLourium** [comment]
closed, without any kind of response?

**Comment by theTyrfing** [comment]
Replying in issue #1048.
