### ISSUE TITLE
chromaticraft crashes my server on load

### ISSUE THREAD

**Issue by benstuwie** [ReikaKalseki/Reika_Mods_Issues#1261]
http://pastebin.com/4mNmukuC
From my googling it seems that error means that I have a client mod in my server mods folder. However, the error goes away and the server loads fine when chromaticraft isn't installed. So it's a little weird. I'm using version 16d which I think is the newest. There also didn't seem to be a server version when I was downloading the mod.
I did modify the config for chromaticraft, because my server wouldn't load before because of a whole lot of id conflicts it was having with other mods. I changed all the potion Id's to go from 200-204 instead, but it's the same for my client and that loads just fine

**Comment by Builderb0y** [comment]
Well, there's an error I haven't seen in quite a while. Update ender IO.
