### ISSUE TITLE
[Chromaticraft] Server crash with RF Radiators and World Rifts - StackOverflowException

### ISSUE THREAD

**Issue by AshIndigo** [ReikaKalseki/Reika_Mods_Issues#1263]
Log: http://pastebin.com/RafAhZ0f

Reproducing Steps:
1. Setup a system where the radiators will feed back into the world rift providing it power.
     - I can get a screenshot if you want
2. Enjoy the corrupted world

**Comment by ReikaKalseki** [comment]
Fixed.
