### ISSUE TITLE
2 Possible bugs with bedrock pick & spawners with EnderIO

### ISSUE THREAD

**Issue by bermovick** [ReikaKalseki/Reika_Mods_Issues#1265]
I'm not sure if this is intentional or not.

When you break a spawner with a bedrock pick, about a dozen of that spawner's enemies spawn.  This might be intentional, but it happens if you place and re-break the spawner again.  Just makes it pretty easy to get any drops.

Also if EnderIO is installed (I don't have any other mods that also drop some type of spawner when harvested), the bedrock pick drops both its broken spawner and the unbroken spawner (and does so again if placed and rebroken)

**Comment by ghost** [comment]
The first issue is intentional, though it _might_ have a config option to disable it.

The second issue has already been reported before: #722

**Comment by bermovick** [comment]
Ahh! Sorry about that; I missed it.
