### ISSUE TITLE
[CC] Energy Stabilizer doesn't want to be festive

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1269]
![2016-12-23_21 41 45](https://cloud.githubusercontent.com/assets/6917535/21465456/09d1322e-c959-11e6-890b-c96fe6fad41e.png)

Only the side textures are missing.

**Comment by ReikaKalseki** [comment]
Already fixed in code, and check my thread for a temporary fix.
