### ISSUE TITLE
[Electricraft] Induction Motors hissing/sizzling

### ISSUE THREAD

**Issue by ranger135xp** [ReikaKalseki/Reika_Mods_Issues#1270]
Hey Reika,

Okay, I just updated my own private pack and I went from v9b to v16d for RoC, ReC, ElC, and DrA but I'm having a strange issue and I'm not sure where to ask. After scouring over many Google searches, possible tutorial videos, open and closed tickets, and the in-game guide book, I am puzzled at what is happening.

I have a network that is operating from 8 ethanol engines (4x2) going to 2 induction generators and into the proper superconductive wire. From there, it passes 2 relays and then goes into an induction motor for a small setup for jet fuel. The induction motor is upgraded with a 4x amplifier (tungsten). When I have the 4096V 32A circuit active, the induction motor hisses like when lava meets water.

As the motor is upgraded fully, I'm really confused on why this is happening. It worked in v9b but I don't see anything in the change logs that points to any modifications. From what I remember before, this noise was caused when a standard motor or a 2x upgraded motor had exceeded its maximum power sources from the network. The setup is 2 generators > 5 super cable > relay > 3 super cable > relay > 4 super cable > 1 motor. Any thoughts? Thank you for your time.

**Comment by ReikaKalseki** [comment]
It *is* the source-sink limits.

**Comment by ranger135xp** [comment]
Where can I find documentation about the source-sink limits? The motor says it has a 4x amplifier. Is something else required to allow it to accepts more sources? The in-game book gives the impression that it can be upgraded through various stages but no real detail past that.

https://www.google.com/search?q=electricraft+source+sink+limits

There's next to nothing about Electricraft no matter where I turn. Every spotlight or tutorial is vastly outdated material.

**Comment by ReikaKalseki** [comment]
No, four is the limit. And this *includes* engines being merged, where each counts as an individual source.
