### ISSUE TITLE
[Suggestion] Particle Spawner: Additional Abilities

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1271]
First of all, particles for the elements. Was surprised I couldn't already have Portokali runes flying around the place. Either greyscale or locked to the appropriate color, doesn't really matter.

Secondly, rotational movement. Not sure how possibly this is, but the way I thought of this was a set of new options for movement and location:

X Y and Z radius. Relative to the location the particle is created, not the spawner itself. Maybe limit it to only one of the axes at once?

Directional velocity. Positive for clockwise, negative for counter-clockwise.

Both options would of course have the variance fields as well.

With the existing options, no matter what I do I have been unable to make the particles curve in their path.

**Comment by ReikaKalseki** [comment]
> Secondly, rotational movement.

Not possible.

> X Y and Z radius. Relative to the location the particle is created, not the spawner itself.

??

> Directional velocity

You already have that.

Curves are not possible. And never will be. They require *acceleration*.

**Comment by Shahelion** [comment]
The radius would be how far out it rotates around the spawn point of that particle. Axis-specific would work better, I figured, than any alternative.

Directional velocity was meant to be basically forwards or backwards on the axis specified, rotating around the center, not along the axis.

Is acceleration not possible in Minecraft?

**Comment by Builderb0y** [comment]
IIRC, vanilla particles can only accelerate downward, though you can specify a negative downward acceleration to make them go up instead. The only mod that I know of that can have particles rotate around a point is ars magica, and it uses its own [controller](https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/particles/ParticleOrbitPoint.java) for that.

**Comment by ReikaKalseki** [comment]
More importantly, a curve requires acceleration *in a changing direction*, and, if non-circular, of a changing magnitude. A given curve's acceleration is only really specifiable with a mathematical function of time.

Neither of those are representable with a simple option.
