### ISSUE TITLE
Reika Server crash

### ISSUE THREAD

**Issue by leytilera** [ReikaKalseki/Reika_Mods_Issues#1276]
when i start my server it crashes. crashlog: http://pastebin.com/QatpMz8M

**Comment by ReikaKalseki** [comment]
I remember fixing this. Try removing mods that add crops and plants.

**Comment by leytilera** [comment]
ohh thats a problem. immersiv engineering is the only mod that adds crops, but i need that for the concept.

**Comment by ReikaKalseki** [comment]
Try removing mods.

**Comment by leytilera** [comment]
i have removed evry mod exept dragonapi and chromaticraft and i get this crashlog: http://pastebin.com/QhpebS4m

**Comment by ReikaKalseki** [comment]
That makes no sense. Redownload everything.

**Comment by leytilera** [comment]
yes this makes no sense but after a redownload its the same crash. i think the cropregestry for servers are broken in this version

**Comment by ReikaKalseki** [comment]
Does it work on the client?

**Comment by leytilera** [comment]
yes

**Comment by ReikaKalseki** [comment]
That...helps.

**Comment by ReikaKalseki** [comment]
Does this happen with only DragonAPI, or is CC required?

**Comment by Builderb0y** [comment]
Well, I can't reproduce it on a dedicated server with v16d. (same forge version too, 1614)

**Comment by leytilera** [comment]
it also happens only with dragonapi

**Comment by ReikaKalseki** [comment]
I could not reproduce it in the dev environment either. Reinstall Forge and MCServer.

**Comment by ReikaKalseki** [comment]
So?

**Comment by leytilera** [comment]
I get the same error when i Reinnstall forge

**Comment by ReikaKalseki** [comment]
Did you also reinstall the libraries?

**Comment by leytilera** [comment]
yes

**Comment by ReikaKalseki** [comment]
I am officially out of ideas. This happens with just DragonAPI - and as such ModCropList is empty - and noone else can reproduce it.

**Comment by OvermindDL1** [comment]
I happened to be looking at the code and I see a couple of possibilities for this, however I need more information to determine which one for sure.  @MineProjectZ is there any way that you could zip/package up an entire and complete server directory that represents this issue and link it here temporarily as I've not been able to test it myself (I get an entirely different dedicated server issue interestingly, I might link it here as a new issue if I cannot resolve it myself)?
