### ISSUE TITLE
[RotaryCraft] Conversion engines stay on acceleration profiles

### ISSUE THREAD

**Issue by roc13x** [ReikaKalseki/Reika_Mods_Issues#1279]
Conversion engines such as the Magnetostatic engine keep consuming energy at the 1.5x rate, even after reaching max speed.
The issue seems to come from here: https://github.com/ReikaKalseki/RotaryCraft/blob/master/Base/TileEntity/EnergyToPowerBase.java#L304

Would something like this fix it?

```java
int maxspeed = this.isEmitting() ? this.getMaxSpeed() : 0;
float mult = 1;
if (this.hasEnoughEnergy()) {
    if (omega < maxspeed) {
        mult = 1.5F;
        omega += 4*ReikaMathLibrary.logbase(maxspeed+1, 2);
        if (omega > maxspeed)
            omega = maxspeed;
    }
}
else {
    if (omega > 0) {
        omega -= omega/256+1;
    }
}
```

**Comment by ReikaKalseki** [comment]
They are not 100% efficient.
