### ISSUE TITLE
Solar Tower Entity NPE (v7b)

### ISSUE THREAD

**Issue by redelman** [ReikaKalseki/Reika_Mods_Issues#128]
After upgrading to v7b (this may happen on v7a, I don't know, I had upgraded direct to v7b on my server), I started getting NPEs on my solar tower. I removed it and replaced (as I had to do the same with my water pump since it had stopped working...) but I still get this NPE. It doesn't matter if there are solar mirrors or not, and the size of the tower seems to not matter either. At least the game doesn't crash, but the chat and log spam are pretty bad.

Stacktrace here:
https://gist.github.com/redelman/0400333b87dbdcf7539d

**Comment by ReikaKalseki** [comment]
Fixed.
