### ISSUE TITLE
[RoC] Sonic borer is not working

### ISSUE THREAD

**Issue by hedgehog1024** [ReikaKalseki/Reika_Mods_Issues#1282]
According to handbook, minimum power and torque to supply sonic borer with power are 65536W and 4096Nm. The same is written in inventory power tooltip. I use a gasoline engine (which produces the exact power needed to feed sonic borer) and two gearboxes to to increase torque from 128Nm to 4096Nm. However, sonic borer attached to shaft does nothing.
Screenshot of my setup: http://imgur.com/a/wmgrK
FML log: http://pastebin.com/Me8aQCgK
I use the latest vesion at the moment, v16d.
Reproduced with only RoC and DragonAPI installed.

**Comment by ReikaKalseki** [comment]
Insufficient pressure.
