### ISSUE TITLE
[ElC] battery charging without input

### ISSUE THREAD

**Issue by gallowglass** [ReikaKalseki/Reika_Mods_Issues#1283]
I was trying out ElectriCraft (v16d) and am having this issue.

![2016-12-30_18 11 11](https://cloud.githubusercontent.com/assets/7349888/21574118/961aa744-cebb-11e6-9eaf-cde2c1398a62.png)
![2016-12-30_18 11 16](https://cloud.githubusercontent.com/assets/7349888/21574120/9ad8eaca-cebb-11e6-8f70-722e5061dcd3.png)

The engine is out of fuel (has been for a while), and the battery charge just keeps increasing....

**Comment by gallowglass** [comment]
If I harvest that battery and put down another, the new one doesn't charge.

**Comment by gallowglass** [comment]
On a possibly related note, if I put fuel in the engine with the new battery there it **doesn't** charge.
![2016-12-30_18 19 39](https://cloud.githubusercontent.com/assets/7349888/21574193/bd228da6-cebc-11e6-83b4-68209dc545a2.png)

If I break the battery and place it again, it works.
![2016-12-30_18 20 05](https://cloud.githubusercontent.com/assets/7349888/21574194/c824ac16-cebc-11e6-814e-08e28519d144.png)

**Comment by ReikaKalseki** [comment]
I suspect this is #1274.

**Comment by ranger135xp** [comment]
That's what I was experiencing.

**Comment by ReikaKalseki** [comment]
Alright, closed until evidence of presence in v17.
