### ISSUE TITLE
[Chromaticraft] Buckets in a level 3 casting table/structure

### ISSUE THREAD

**Issue by metnavman** [ReikaKalseki/Reika_Mods_Issues#1284]
I've yet to test this other versions/levels of the casting structure setup. This is occurring when using an Iron Bucket to craft the Wooden Repeater in a 3-diamond table in the second level casting structure.

The metadata item tag on the Iron Bucket is changing from it's default item number of 265(256?) to a tagged item of 265(256?):1. This causes the bucket to register as a different item, rendering it useless. It can no longer collect liquid, and can no longer be used.

Chromaticraft version: 16d
Minecraft version: 1.7.10

Please let me know if I need to add anything extra, or you'd like me to dive further in to try and reproduce in different settings, or if this has already been reported, and I'll toddle back off into the Nether. I'll be around!

**Comment by ReikaKalseki** [comment]
Already fixed.

**Comment by metnavman** [comment]
<3 You. Is it an easy fix like "I could jump into something and edit a line" or "haha you're boned until the next update, but it was easy for me" kinda' fix? 🥇 

Edit: I'm a derp, this was reported in Nov and for V15. Should learn to use my label filters better. Hope the holidays were good for ya and you're having fun in Elite Dangerous!

**Comment by ReikaKalseki** [comment]
The fix was a trivial one, but there is no easy means for you to do much about it.

**Comment by metnavman** [comment]
Gotcha! I'll just edit in normal buckets as needed!

**Comment by Aivech** [comment]
Are you _sure_ it can't pick up fluids? I've been "fixing" mine by using them to pick up water from a pond and then either use the water or put it back.

**Comment by metnavman** [comment]
Let me craft another item that uses the chroma bucket in the recipe and try that. I'd only tried scooping up more Chroma to keep making what I was making, and then scoop up some lube (was the closest thing around to scoop). Neither of those was playing ball, but I didn't give good ole' water a try.

Edit: Heyyyyy look at that! Scooping up good ole' water resets the bucket from 325:1 to regular 325. Nice!
