### ISSUE TITLE
[RoC] Unnecessary extraction products

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1286]
The various "gems", "items", and "dusts" that are interchangeable with the actual item (Moonstone gems, Vinteum dusts, etc) Why doesn't the extraction just give the actual item?

**Comment by amesgen** [comment]
I am also interested why these even exist. Their existence is no problem, but I don't know any other mod that uses own "versions" of the products of its machines.

**Comment by ReikaKalseki** [comment]
Because Extractor outputs are generated dynamically.
