### ISSUE TITLE
Client crash when viewing recipes in NEI

### ISSUE THREAD

**Issue by iczero** [ReikaKalseki/Reika_Mods_Issues#1287]
The client crashes when attempting to view recipes in NEI. Removing RotaryCraft fixes the issue.
Crash report: https://hastebin.com/ememipewuv.rb

**Comment by ReikaKalseki** [comment]
Try removing other mods.

**Comment by iczero** [comment]
Removing AOBD fixes the probem. May be related to ganymedes01/Another-One-Bites-the-Dust#72

**Comment by ReikaKalseki** [comment]
Try updating AOBD.

**Comment by iczero** [comment]
AOBD is at the newest version (2.9.2) from CurseForge.

**Comment by ReikaKalseki** [comment]
In that case...@ganymedes01, does AOBD add fluids, in particular metal ones?
