### ISSUE TITLE
AC Electric Engine stops working when close by.

### ISSUE THREAD

**Issue by webmilio** [ReikaKalseki/Reika_Mods_Issues#1289]
I found the problem myself, although some notice would've been nice. It makes sense: if you have a shaft core on you and you're currently close, it'll stop working. It wasn't written anywhere so I thought it was a bug. Cheeky cheeky.

P.S.: I'm fairly certain I read the book through and through.

**Comment by redelman** [comment]
Been a while since I looked at the book, but I think it is at least hinted at. Should have been pretty obvious though. :)

**Comment by webmilio** [comment]
Yea thats why I edited the issue right after posting it. I realised my mistake after reading myself.
