### ISSUE TITLE
Here's an interesting one

### ISSUE THREAD

**Issue by metnavman** [ReikaKalseki/Reika_Mods_Issues#1292]
Chromaticraft ME Distributor placed on top of a Rotarycraft grinder. Set it to check for Cave Crystals, and then set a random Crystal Shard color as the output. Set the ME Distributor to check Fuzzy/Ore match and ignore NBT. Input whatever Cave Crystals to the ME Network you want. All Crystal Shards will be output as the shard color you set in the distributor, regardless of the color Cave Crystal placed in the network.

Edit: Further testing shows that it's actually changing the CAVE CRYSTAL into the selected color. Just turned a random assortment of Cave Crystals all to Zambarau and sat by the Grinder to pull them all out.

**Comment by ReikaKalseki** [comment]
Fixed. This one was painful.
