### ISSUE TITLE
[CrC] Dimension Reset SSP

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#1293]
I don't know if this is intended or not, but the ChromatiCraft dimension will reset in singleplayer if you save and quit to title or crash to desktop. This can be an issue when you're crashing a lot, or if you have a chunk error cutting a large swathe through a puzzle structure that would require going back to the title to fix.

**Comment by HellFirePvP** [comment]
The dimension resets every time you leave it. be it a crash, quit or related. If noone is in the dimension (specifically multiplayer related) the dimension will reset.

In regards to chunk errors: Run a bit away from it and come back again.. Other than that, not much that can solve that.
