### ISSUE TITLE
[BUG (I think)] DragonAPI crashes on server startup.

### ISSUE THREAD

**Issue by TheRedCrafter344** [ReikaKalseki/Reika_Mods_Issues#1294]
When the server starts, DragonAPI crashes the server with a java.lang.VerifyError: Inconsistent stackmap frames at branch target 388 when it tries to set the loot of dungeons and such.

Crash report: http://pastebin.com/qXQW6kwn

--------------------------------------------------
I am not completely sure if this is the mod's fault, my fault or KCauldron's fault.

**Comment by HellFirePvP** [comment]
Reika's mods don't support KCauldron.

**Comment by TheRedCrafter344** [comment]
Really? I saw another bug report on KCauldron that got fixed.

**Comment by TheRedCrafter344** [comment]
Oh nvm.
