### ISSUE TITLE
DragonAPI V12e +AE2rv3b6

### ISSUE THREAD

**Issue by SvEgiiVEteR** [ReikaKalseki/Reika_Mods_Issues#1296]
https://gist.github.com/80bf6a3ed90566406a98e833579736da
del DragonAPI and all OK
    B:enabled=false
    B:exportItemNames=false
did not help
or
https://gist.github.com/9cb1cf5dc7b9686b4e8526717a75e724

**Comment by redelman** [comment]
V12 isn't supported, of course. Try with latest.

**Comment by SvEgiiVEteR** [comment]
and? 16 is also not supported.
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/857
I need to play with 30 fps?
better tell me what to do.. maybe something to configure?

**Comment by SvEgiiVEteR** [comment]
the way to fix this is, or not?

**Comment by ReikaKalseki** [comment]
> the way to fix this is, or not?

Nobody knows or cares. Old versions are not supported. **End of story**.

**Comment by SvEgiiVEteR** [comment]
bad that no one... :( 
and new is also not supported
13b-16d fps has not changed
