### ISSUE TITLE
Casting Table not Recognizing Casting Complex

### ISSUE THREAD

**Issue by FinderOfWays1** [ReikaKalseki/Reika_Mods_Issues#1297]
Probably user error, but I can't see any problem in the structure. Do I need a higher level table?
Table works fine for casting room and temple (if I replace the diamond/glowstone with gold/redstone the casting table works as if in a temple), but does not see the casting complex structure at all.

Repeaters on the external ring seem functional (I connected the colors needed for what I am trying to craft, and the repeaters I connected have depth within the repeater network when I use the manipulator on them. All repeaters have the particle effect indicating a valid multiblock, including the ones which do not have any connection to a pylon. Repeaters all have different rune colors, but the error also occurs when runes are all the same).

This is on a locally hosted world, if that matters. I don't have any logs I can paste since there is no crash.

I have all progress up to "top-tier crafting." (Had to use /chromaprog to get enderdragon kill progress, probably due to Hardcore Ender Expansion changing the dragon's code)

This is in a personal pack using forge 10.13.4.1558 with the latest version of chromaticraft as of a couple weeks ago when I made the pack. (I think this issue is probably internal or user stupidity, but if you need the modlist, I'll get it).

To change from temple to complex I added the ring of crystalline stone and the ring of obsidian followed by the 16 repeaters and the 4 corner structures, then changed the "capstones" from gold and redstone to diamond and glowstone.

![2017-01-12_10 58 09](https://cloud.githubusercontent.com/assets/25083705/21897468/a9a1544c-d8b7-11e6-836d-e62bb911be79.png)
![2017-01-12_10 58 23](https://cloud.githubusercontent.com/assets/25083705/21897467/a9a05204-d8b7-11e6-9b66-b718ddfd4ddd.png)
![2017-01-12_10 58 48](https://cloud.githubusercontent.com/assets/25083705/21897466/a9a01672-d8b7-11e6-88bb-47eaeba295cb.png)

**Comment by AshIndigo** [comment]
Your missing crafting EXP in your casting table, go craft some multiblock casting stuff.

PS: Whats the book above your manipulator from and what armor do you have?

**Comment by FinderOfWays1** [comment]
Thanks a bunch!
The book and armor are from the same mod, actually: Essential Craft 3. It's pretty strange, but very cool. It's a magic-themed tech mod. It's not the most polished of mods, but makes up for it with some unique/interesting features and flavor, IMO.
