### ISSUE TITLE
Engines exploding?

### ISSUE THREAD

**Issue by xxxdoomslayerxxx** [ReikaKalseki/Reika_Mods_Issues#13]
My engines are exploding, how can I prevent this?

**Comment by 1Matthias** [comment]
Please provide more details, such as the type of engine, cooling, etc.

**Comment by xxxdoomslayerxxx** [comment]
The magmatic egines, I hook up the conduit, set the power level, and kaboom.

**Comment by Kolatra** [comment]
Magnetostatic you mean? If so, you need to give them liquid nitrogen.

**Comment by xxxdoomslayerxxx** [comment]
Why do these keep getting nerfed, might as well remove them if you don't want anyone using them -_-

**Comment by zemerick** [comment]
Reika is just moving them into their intended uses. He never wanted a simple workaround to his mod, as these originally provided. The LN2 goes along with all of his machines after the basic DC engine having requirements to meet. ( Fuel, magnetized core, lubricant, etc. )

The magnetostatic isn't the only engine that requires cooling in fact. ( Well, they don't explicitly require it. It's based off of the heat which comes from power and tier. )
