### ISSUE TITLE
Hydrokinetic engines aren't chaining

### ISSUE THREAD

**Issue by Xavion3** [ReikaKalseki/Reika_Mods_Issues#130]
See the images, all the engines are generating the same amount of power for reference and the shaft registers them all as sources but it's only turning with the power of one of them.
![2015-07-10_13 05 26](https://cloud.githubusercontent.com/assets/3487253/8612946/78c47618-271c-11e5-8e84-6f64d373e8a5.png)
![2015-07-10_13 05 44](https://cloud.githubusercontent.com/assets/3487253/8612947/78cd20ce-271c-11e5-8182-eca2adb27329.png)

**Comment by TomeWyrm** [comment]
I'm going to ask what is a potentially obvious question. Did you enhance some of those (but not all) with bedrock?

**Comment by Xavion3** [comment]
No, you can tell by the fact the textures aren't different. When you add bedrock shafts the paddles getting notably darker close to the center. Enhancing with bedrock seems to do nothing if it matters.

**Comment by ReikaKalseki** [comment]
I forgot to multiply in getArrayTorqueMultiplier()....
