### ISSUE TITLE
Elemental Lock Key Dissapear/Crash

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#1306]
I was trying to solve the Elemental Lock puzzle for the first time when one of the keys didn't drop because I placed it in the wrong place and tried to pick it back up, and it turned invisible and was no longer able to be broken. So I instead tried spawning in a key, and placed that on another pad, which didn't register as being activated and caused this crash when I broke it.

https://gist.github.com/DFliyerz/d0dcab20408ea6b0fd977bad7d2e43c9

**Comment by ReikaKalseki** [comment]
Spawned keys do not work. That said, I will make them not crash.

**Comment by DFliyerz** [comment]
What about the disappearing key?

**Comment by ReikaKalseki** [comment]
I have no idea what you mean.

**Comment by DFliyerz** [comment]
Both times I've attempted this puzzle I've had a key just dissappear when breaking/placing it, making the puzzle uncompleteable.

**Comment by AshIndigo** [comment]
Ive done this puzzle around 4-5 times Ive never had a key disappear on me. The only issue I found was that one of keys wouldnt open a door despite being the right channel. I exited and found another puzzle but I havent managed to get them glitch again.

**Comment by ReikaKalseki** [comment]
> Both times I've attempted this puzzle I've had a key just dissappear when breaking/placing it,

That sounds like lag.

> The only issue I found was that one of keys wouldnt open a door despite being the right channel.

That can happen if the dimension half-resets, clearing the structure data from RAM.
