### ISSUE TITLE
Mystcraft/Rotarycraft/Chromaticraft(?) Crash

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#1307]
I got a crash when turning my boring machine in a Mystcraft dimension on via wireless redstone, and I think it has something to do with the fact that while flying around the Chroma dimension, if I fly faster than the world loads it'll say I'm in the biome "Extreme Hills+".

https://gist.github.com/DFliyerz/ca5d91afb9737bde70bcaa64e24eede7

**Comment by ReikaKalseki** [comment]
This is on MystCraft's end.

**Comment by DFliyerz** [comment]
Do you know of any fixes? This causes me to crash when trying to reload the world, so I have to restore a backup.

**Comment by ReikaKalseki** [comment]
This is a long-standing issue with MystCraft in general, going well into 1.6.

**Comment by DFliyerz** [comment]
Alright, any idea if RFtools has this issue? I'm assuming this is somewhat related to compatibility, since that thing with the Extreme Hills+ showing up in the Chroma dimension.

**Comment by ReikaKalseki** [comment]
I have never used it.

**Comment by DFliyerz** [comment]
Fair enough, I'll figure it out later.
