### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by nathanwe** [ReikaKalseki/Reika_Mods_Issues#1308]
I was playing revolution 3. I made a tool dynamism tablet(thaumic tinker) and had it right click on a loot chest(chromaticraft) with a glove(extra utilities), to trigger enviromine food rotting in the chest. After I built this contraption, I started crashing whenever I opened the GUI of a rotarycraft or chromaticraft machine. destroying the tool dynamism tablet stopped the crashes. What was going on?

[crash-2017-01-18_20.54.34-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/715853/crash-2017-01-18_20.54.34-server.txt)

**Comment by AshIndigo** [comment]
My best guess is that the chest tried to find the player that was opening the chest. But since there wasn't an actual player opening the chest the player received is null and crashes the game. Since your playing Rev3 why not use one of the improved chests for now.

**Comment by HellFirePvP** [comment]
I rather suspect the Dynamism tablet.

It tends to be VERY unstable and breaks in a lot of packs on very different occasions.

**Comment by nathanwe** [comment]
@AshIndigo I'm not sure that's how it worked? whenever I walked near the tablet the gui opened like I had clicked on the chest. also, what improved chest are you refering to? the chromaitcraft one that simulates inventory? or a expensive one with lots of space?

**Comment by AshIndigo** [comment]
The chests that include emerald, diamond those ones (I forgot the name of the mod).

**Comment by ReikaKalseki** [comment]
I will make loot chests not interactable by fake players.
