### ISSUE TITLE
[ReC] Centrifugal Fluid Extractor not working

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#1309]
I can't get the centrifugal fluid extractor to work and make heavy water, even after putting it in an ocean at y=41 with plenty of space around it and enough power to make it spin.

**Comment by ReikaKalseki** [comment]
I know it works, having used it many times previously. Additionally, every other time someone reports an error with it it turns out to be missing one or more requirements.

**Comment by DFliyerz** [comment]
I'll try it in some other conditions

**Comment by DFliyerz** [comment]
Ok, maybe I shouldn't have closed this issue. I still can't get it to work, even with the requirements more than met. http://i.imgur.com/fXUKkE8.png
