### ISSUE TITLE
Hydrokinetic engine fluid balance is broken

### ISSUE THREAD

**Issue by Xavion3** [ReikaKalseki/Reika_Mods_Issues#131]
Current issues are that density is irrelevant if 128 or more due to speed becoming the limiting factor which is purely dependent off viscosity and the balance for viscosity making it way out of whack. Also water only needs to fall 14 blocks as a result of all this. See the pictures which show the minimum fall distance of water to generate max power with RotaryCraft V7d. For reference density >= 128 and viscosity <= 339 should be the requirements from what I can tell for a fluid to generate max power with a 2 block fall which is the minimum as far as I can tell.
![2015-07-10_13 05 00](https://cloud.githubusercontent.com/assets/3487253/8612984/f4c04a9e-271c-11e5-9078-22753efa762a.png)
![2015-07-10_13 05 26](https://cloud.githubusercontent.com/assets/3487253/8612985/f4c289a8-271c-11e5-8c52-872b7a685a32.png)

**Comment by ReikaKalseki** [comment]
OK, I have changed the curves to be closer to the original values and to reduce the effect of viscosity.
