### ISSUE TITLE
The fusion plasma no go in circle

### ISSUE THREAD

**Issue by Sw3d15h-F1s4** [ReikaKalseki/Reika_Mods_Issues#1312]
So I built the fusion reactor perfectly. But when I feed it plasma, the toroidal magnets dont work. I have them fully charged and the solenoid is running. I have no idea what to do. Please help!

**Comment by 1Matthias** [comment]
You have coolant in them?

**Comment by Sw3d15h-F1s4** [comment]
It did not say anywhere in the tutorial on youtube to put cooland into the magnets

**Comment by Sw3d15h-F1s4** [comment]
Thanks, did not know you had to. Fixed!

**Comment by ghost** [comment]
The video is extremely outdated; I recommend you read the handbook if something similar happens again.

**Comment by 1Matthias** [comment]
@ReikaKalseki Honestly, I would take that tutorial down/create a new one. At this point, it only serves to confuse people and create new issues.

**Comment by ReikaKalseki** [comment]
No, because everything in it remains valid.
