### ISSUE TITLE
Strange optical glitch

### ISSUE THREAD

**Issue by Sw3d15h-F1s4** [ReikaKalseki/Reika_Mods_Issues#1313]
![2017-01-21_19 52 02](https://cloud.githubusercontent.com/assets/25266672/22178962/1d5a5674-e013-11e6-99e4-ae2f10ced03b.png)
As you can see, a strange optical glitch happens occasionally with the turbine, steam, and magnetic pipes. Only in that area though.

**Comment by Sw3d15h-F1s4** [comment]
![2017-01-21_19 58 32](https://cloud.githubusercontent.com/assets/25266672/22178990/3ccef54a-e014-11e6-8d1f-e11fe97db6e3.png)
Seems to only happen with steam. The torodial magnets are redrawing the circle thing, the bevel gears are showing the colored boxes, and the pipes are glitching. Seriously, what is going on?

AND IT JUST CRASHED MINECRAFT

**Comment by ghost** [comment]
This can be found [here.](https://sites.google.com/site/reikasminecraft/faq) 

It's the, "I get a weird render error where engines and machines glitch out and switch directions (and types/models/materials), with the I/O boxes going wild," one.
