### ISSUE TITLE
Didn't you say that the neutron absorbers couldn't melt...

### ISSUE THREAD

**Issue by Sw3d15h-F1s4** [ReikaKalseki/Reika_Mods_Issues#1314]
Well they did.
![2017-01-21_19 54 31](https://cloud.githubusercontent.com/assets/25266672/22178966/70c54b84-e013-11e6-9990-8eb868fb4d59.png)

**Comment by Builderb0y** [comment]
Who ever said that? They've always been able to melt. At the time of me writing this, their max temperature is 1500°.

**Comment by Sw3d15h-F1s4** [comment]
But then what is the point of having them if they just melt instantly? Do they need to be cooled as well?

edit: Cooled, not fooled

**Comment by ReikaKalseki** [comment]
You do not know how to use them.

**Comment by Sw3d15h-F1s4** [comment]
Then how do i?

**Comment by ReikaKalseki** [comment]
You have been following some guide, haven't you?

**Comment by Sw3d15h-F1s4** [comment]
Yes. Your video and this page

**Comment by Sw3d15h-F1s4** [comment]
All your video said, which I presume is outdated due to other comments, that "You dont have to worry about them melting." But apparently I do, so I am just a little stuck.

**Comment by ReikaKalseki** [comment]
The video is very, *very* old, and even when new was explicitly stated to not be comprehensive. If you do not understand the underlying mechanics, you will be stuck.
