### ISSUE TITLE
[CrC] Ortho Crystals

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#1316]
Having just recently completed the Chroma dimension, I was interested in making the Mineral Extractor, but noticed that it requires Ortho Crystals. Looking through the lexicon and NEI yeilded no information about how to obtain them, and neither did a Google search. Are they simply unobtainable, or am I missing something?

**Comment by ReikaKalseki** [comment]
They exist and are obtainable.

**Comment by DFliyerz** [comment]
Uhh... can I get a hint? :P
