### ISSUE TITLE
Autocrafting Sustain Mode

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#1317]
If the autocrafter is set to do recipes that require multiple of the same item, say a 3x3 of blaze essence to make blaze rods, and the ME system doesn't have enough of that item to do the recipe, the ME terminal will show as having 2.1 billion of that item.

**Comment by ReikaKalseki** [comment]
I have seen the 2.1 billion bug before under many different situations, none of them involving sustain mode and several not involving the autocrafter. I suspect this is internal to AE.

**Comment by metnavman** [comment]
Seconding the internal to AE. Have the same thing with the Autocrafter in Continuous Mode. It's persistent, but nothing more than a visual nuisance. As the mod (AE) is not likely to see another 1.7.10 update, it's probably here to stay.
