### ISSUE TITLE
Dimensional Flare Proximity Causes Accidental Attacks

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#1319]
After completing the monument the dimensional flares won't attack you.. generally. The issue is that they'll still follow you and stay very close to you, meaning that if you try to mine something with a flare hugging you there's a good chance you'll accidentally hit it and get thrown out.

**Comment by ReikaKalseki** [comment]
I will see what I can do about this.

**Comment by HellFirePvP** [comment]
To me you said this is intentional :V

**Comment by ReikaKalseki** [comment]
...When?

**Comment by ReikaKalseki** [comment]
Hopefully at least partially fixed.
