### ISSUE TITLE
Issue with the new Forge splash screen

### ISSUE THREAD

**Issue by robaimes** [ReikaKalseki/Reika_Mods_Issues#132]
Not sure what specifically is causing the issue. I have a lot of mods installed, but installing DragonAPI and RotaryCraft causes the new splash screen to fail where it would normally open the main menu.

It does work if the new splash is disabled, however it is activated by default which is the main reason I mention this.

This may be an issue between 2 or more conflicting mods, but again, I am not entirely sure. Will be doing some more testing soon.

Forge Log: https://dl.dropboxusercontent.com/u/76791645/fml-client-SplashCrash.log

**Comment by ReikaKalseki** [comment]
The crash is vanilla code. And I do nothing to the splash screen. I do not even know _how_ to interact with it.

**Comment by ljfa-ag** [comment]
I would guess that it is a problem with Forge. Try to find a minimal set of mods that causes this.

**Comment by Reignofmagic** [comment]
Here is my modlist, you can safely cross all these off your list if any overlap. I'm able to boot up just fine. Note I am running forge v 1448
http://pastebin.com/xyTk70gj

**Comment by ReikaKalseki** [comment]
So...any update?

**Comment by robaimes** [comment]
Been away for a while, will take a look with latest version soon.

**Comment by Bogdan-G** [comment]
Usually recommended to switch off splash screen. Since not all mod and stuff with them to work.
