### ISSUE TITLE
Casting from ME System

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#1321]
I know that the Casting Delegate can pull items from an ME system, but is there a way to start a recipe from an ME terminal? No offense, but the Casting Delegate GUI is awful, requiring ridiculous amounts of clicking or having the item on hand to find a recipe. If there's not already a way to do this, perhaps one could be added?

**Comment by ReikaKalseki** [comment]
I highly doubt this is possible, and most of the AE team is rarely willing to be helpful to me.

**Comment by DFliyerz** [comment]
At the very least, maybe a better way of accessing recipes in the Casting Delegate, like a scrollable list or search bar could be added?

**Comment by ReikaKalseki** [comment]
Those are far easier said than done.

**Comment by metnavman** [comment]
Did you know you can hold shift or control to skip duplicate/similar patterns? Just found that out yesterday. Blew my mind.

**Comment by DFliyerz** [comment]
Yeah, but it's still a huge pain.
