### ISSUE TITLE
Reactorcraft Clientcrash on Serverjoin

### ISSUE THREAD

**Issue by LukaPix** [ReikaKalseki/Reika_Mods_Issues#1323]
Yesterday i built a very big fission reactor (just the Fuel Cores Coolant Cells etc, no pipes or anything connected because it was not finished) around 150 Fuel Cores and 700 boilers and i had no problems besides HUGE fps drop when looking at it. Today i tried joining the Server and my Client crashed out.
Optifine did not make any difference and the game also crashed with same error on a friend of mine.
I found nothing like this in the github search or google.

Version: V16d

Crash: [https://hastebin.com/osuhopacug.rb](https://hastebin.com/osuhopacug.rb)

**Comment by redelman** [comment]
What could you possibly need a reactor that big for? Just build the fusion reactor already. :)

**Comment by LukaPix** [comment]
We are trying to build the Tjernobyl Reactor. Its more like a challenge keeping a reactor that big cool and at least a bit efficient. Also we wanted to see what the limits of Reactorcraft were. 
We probably already reached the limit since i have around 8 fps looking at it. :D

**Comment by ReikaKalseki** [comment]
Does this issue happen reliably?

**Comment by LukaPix** [comment]
yes

**Comment by LukaPix** [comment]
but only on login if i login like 20 chunks away it wont crash even if i fly there.

**Comment by LukaPix** [comment]
after reading the other post ... we just built the Reactor and the High Pressure Turbine(max size),Generator Multiblocks they werent even running a single time.

EDIT: I just figured out that im only crashing if the Multiblocks are on a Chunk border and i am logging in in a place where only one of the Chunks the Multiblocks are in is loaded.
Now the Issue is the Max size Turbine+Generator are so big i cant move them into one Chunk :/

**Comment by ReikaKalseki** [comment]
These structures can handle chunk borders fine. However, you need to keep the chunks loaded.
