### ISSUE TITLE
EnderIO Compat Crash

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#1325]
I get this crash sometimes when loading worlds, even if they don't contain any EnderIO conduits or anything EnderIO related. https://gist.github.com/DFliyerz/4f247025f7b7829f9e556265934fef02 I can usually launch the world fine after this, but it's still strange.

**Comment by ReikaKalseki** [comment]
This is a Block/TileEntity mismatch.

**Comment by DFliyerz** [comment]
It's not corruption though, the world works fine after it crashes.

**Comment by ReikaKalseki** [comment]
Corruption can be temporary.

**Comment by DFliyerz** [comment]
Any idea what could have caused this issue?

**Comment by ReikaKalseki** [comment]
Minecraft itself can manage to f--- this up, but it is more common with certain mods or blocks/items that unsafely modify blocks or TileEntities.

**Comment by DFliyerz** [comment]
Alright. Since it's not a huge problem and only seems to affect my test worlds for some reason, I'll probably just not worry about it.
