### ISSUE TITLE
Broken Pylon Restoring as New Color

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#1326]
I had a Ykri pylon that I broke a while ago since I had a plyon of that color closer to me, but when I flew by it while working on turbocharging my network I'd noticed that it had turned to Asveste, and was no longer broken. Additionally, another pylon that was Tahara which I had broken as well also repaired itself and was now Ruskea. I'm certain I never ran the command to randomize pylons in my world, although I may have accidentally loaded into the world while still in debug mode for a moment before changing the mode. Of course, I'm not complaining, considering this new Asveste pylon is twice as close as my old one, but I'm still not sure what caused this. Also, these new pylons weren't fully charged when I went up to them, unlike most freshly generated pylons.

**Comment by HellFirePvP** [comment]
"I may have accidentally loaded into the world while still in debug mode for a moment before changing the mode." Even 1 tick is enough to make them randomize their color in case the pylon is incomplete in debug mode.

**Comment by DFliyerz** [comment]
Good to know.
