### ISSUE TITLE
Geostrata ArrayIndexOutOfBoundsException in TileEntityVent

### ISSUE THREAD

**Issue by Ilddor** [ReikaKalseki/Reika_Mods_Issues#1328]
I just wanted to point this error: http://pastebin.com/biCWhyFk
Seems to happen everytime I try to generate really big map (using chunkgen). I try to generate really big map: 1000x1000 chunks (I just really like to run around and don't want to have generating lag) and around half way it crashes in this place.

**Comment by ReikaKalseki** [comment]
Something is setting the metadatas of random blocks. Possibly related to #752; Do you have an older version of Glenn's gases?

**Comment by Ilddor** [comment]
Problem is I don't use Glenn's gases mod, I'll try to find mod that sets metadata on in (oh boy, over 100 candidates).

**Comment by ReikaKalseki** [comment]
It could be one of two things; a mod could be setting metadatas to keep track of things (the RC Pile Driver used to do this, as did Glenn's Gases) or it could be trying to modify itself and passing in incorrect coordinates (TC hungry nodes did this for a while).
