### ISSUE TITLE
ChromatiCraft StackOverflowError at WorldGen

### ISSUE THREAD

**Issue by Ilddor** [ReikaKalseki/Reika_Mods_Issues#1329]
During generation of really big wolrd - 1000x1000 chunks I'm getting this crash: https://gist.github.com/Ilddor/5c7dcd6bd11e932cda32f8570ab6d412 but this one occured like once or twice, rest of times I was getting another one from Geostrata I've already created issue for.

**Comment by ReikaKalseki** [comment]
Hopefully fixed, but unfixable if not.
