### ISSUE TITLE
Crash when clicking on second blank button in RotaryCraft manual

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#133]
http://pastebin.com/Vds7kSdF

http://imgur.com/mcoFanm

With minimal modset (dragonapi and rotarycraft), click on the button in the RotaryCraft manual, as circled in red in the image. Immediate crash to desktop with the error recorded in the pastebin.

Latest v7d of RotaryCraft/DragonAPI

**Comment by ReikaKalseki** [comment]
Fixed.
