### ISSUE TITLE
I swear I find every little bug

### ISSUE THREAD

**Issue by metnavman** [ReikaKalseki/Reika_Mods_Issues#1331]
Edit:

User Error, please ignore the idiot.

**Comment by ReikaKalseki** [comment]
???

**Comment by OvermindDL1** [comment]
Heh, they originally posted:

> http://imgur.com/a/ft8Ce
> 
> The Casting Complex just up and quit registering. I've neither added nor removed anything to it. The ME infrastructure that can be seen has been working with the Casting Delegate just fine. I've even torn it all out to see if the complex just needed to update to no avail. I've put my backup casting table into it with the same result, and even leveled a new table to a second diamond with the same result. Everything past the first diamond is crossed out now and it throws a HORRIBLE error if I try to craft anything via the delegate with it. The game will crash to the LAN screen before going back to the MC title screen.
> 
> The only thing I've done to the world around me is placed my Aura Locus, and like I said, I was crafting just fine after doing so. This has persisted to a backup I attempted to revert to, so I'm not exactly sure when the problem initiated. I will go back further and see if it's permanent, though I don't know if that points at some other problem.

So I'm guessing it ended up being a user issue, though it would be nice if that were explicitly stated so we know what was going on.  ^.^

**Comment by metnavman** [comment]
> So I'm guessing it ended up being a user issue, though it would be nice if that were explicitly stated so we know what was going on. 

Winner. I edited OP and if this sort of thing happens again (never) it will be done so from the get go.
