### ISSUE TITLE
Possible Performance Issue with TerritoryZone

### ISSUE THREAD

**Issue by DracoScythem** [ReikaKalseki/Reika_Mods_Issues#1333]
[deleted]

**Comment by ReikaKalseki** [comment]
You do not know how to read the profiling data. The logger is on its own thread, which it of course will consume 100% of (and about which there is little reason to care about). You only care about the server thread.

**Comment by Leguan12** [comment]
>.<

Could you do my a favor by slapping a User Error Label on this? I'm obviously too stupid to read (or rather skim through) official docs for software I use...
