### ISSUE TITLE
[Request] More configurable Void Monster

### ISSUE THREAD

**Issue by DracoScythem** [ReikaKalseki/Reika_Mods_Issues#1334]
As the Void Monster is a quite unique and interesting Boss to have 'sneaking' around, and it can be a major balancing 'tool' for Modpack makers (like, making the DeepDark more dangerous, or having to deal with major consequences if one breaks the lowest layer of Bedrock), it would be nice to have some more config Options for it - especially regarding the dimensions it can spawn in.
At the moment, if one has the goal to make the Void Monster only spawn below the Overworld and the DeepDark, it results in config files multiple hundreds of lines in length, as there is no way to turn the blacklist into a whitelist or prevent it from spawning in Void/Skyland MystCraft dimensions by any simpler means.
Also some Option to change its' drops would be great (it being a perfect candidate to allow the aquisition of Green Hearts from TCon for example)

**Comment by ReikaKalseki** [comment]
I can look into allowing for drops to be added, as well as a blacklist/whitelist toggle.

**Comment by ReikaKalseki** [comment]
Alright, I made a hook into the LuaBlock system for VoidMonster drops and added a config to make the dimension IDs in the config actually be a whitelist.

**Comment by AshIndigo** [comment]
Any chance of a config being added to modify its stats? I feel like the default one is to slow to be a major threat while running around on the nether roof.

**Comment by ReikaKalseki** [comment]
That gets very complicated, very quickly. That said, I can make the difficulty factor affect its velocity.

**Comment by ReikaKalseki** [comment]
Done.
