### ISSUE TITLE
Rotarycraft Crafting Pattern

### ISSUE THREAD

**Issue by metnavman** [ReikaKalseki/Reika_Mods_Issues#1338]
A Crafting Pattern set to "Blast Furnace Recipe" cannot be taught to craft Coal Coke in a Blast Furnace. 1 piece up to 9 pieces makes no difference; there is no output and therefore no way to tell it that coal = coke.

**Comment by metnavman** [comment]
I know that AE crafting patterns have that toggle that creates a "processing" tab. It adds a couple slots for the output. Would it be possible to have the crafting pattern gain "Blast Furnace" tabs when you toggle it to that setting? Instead of the typical 3x3, it gains the additional slots that the furnace has, and then you basically have access to "assign" the item you want to the slot. It seems like that sort of control would solve all the issues.

**Comment by DFliyerz** [comment]
Also, even if you couldn't get it to recognize the 3x3 coke recipe, you could make it so that patterns that are invalid stay on the pattern when exiting the GUI, so you could use them anyways.

**Comment by ReikaKalseki** [comment]
#1204 

> Also, even if you couldn't get it to recognize the 3x3 coke recipe, you could make it so that patterns that are invalid stay on the pattern when exiting the GUI, so you could use them anyways.

I will try that.

**Comment by metnavman** [comment]
Awesome!
