### ISSUE TITLE
Construction Star Extreme Lag

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#1339]
When taking out my Construction Star to build in a decently large area (~150 blocks), my framerate will drop to a fraction of a frame per second, rendering Minecraft unplayable until I kill the process. Even pressing escape doesn't help, locking me into the menu so I can't get back to the game. The log gets kinda filled with junk, reading this: https://gist.github.com/DFliyerz/9bfbb27e39d559a5ceb7da5db4e1f6b7

**Comment by ReikaKalseki** [comment]
Were you looking at stone?

#1318

**Comment by DFliyerz** [comment]
Yes
