### ISSUE TITLE
Infinite coal with thermal foundation

### ISSUE THREAD

**Issue by Xavion3** [ReikaKalseki/Reika_Mods_Issues#134]
Coal dust melts into 250mB of liquifacted coal in the rock melter but only takes 100mB in the fluid crystalliser to create a piece of coal. The fluid crystalliser should be adjusted up I'm pretty sure. It's the only one of the TE fluids that is buggy, so nothing else has the loops.

**Comment by ReikaKalseki** [comment]
Which one is the correct value?

**Comment by Xavion3** [comment]
100mB is the correct value as far as I can tell.

**Comment by ReikaKalseki** [comment]
In TE machines?

**Comment by ljfa-ag** [comment]
Yes, one pulverized coal gives 100 mb of liquifacted coal.

**Comment by ReikaKalseki** [comment]
Fixed.
