### ISSUE TITLE
I get kicked out of the world  if i use the elemental manipulation wand 

### ISSUE THREAD

**Issue by Ryius** [ReikaKalseki/Reika_Mods_Issues#1340]
Every time i select the elemental manipulation wand i get kicked out of my world .
with the Error : payload may not be larger than 32k .
Log : 
http://pastebin.com/qUrs3YxN

**Comment by OvermindDL1** [comment]
> payload may not be larger than 32k .

This immediately says to me that you most likely have some *massive* things in your inventory, do you have bags full of bags or items with utterly massive NBT data (like large books) or so forth?

**Comment by Ryius** [comment]
oh wait the complet Chromic lexicon

**Comment by Ryius** [comment]
okey this happens only with the elemental manipulation wand in the Inventory

**Comment by ReikaKalseki** [comment]
The manipulator stores no NBT. However, it will trigger your player data to be synced, and something else has filled with with massive amounts of garbage.

**Comment by Ryius** [comment]
how can i fix it ?

**Comment by Ryius** [comment]
ow and this happens only in one world .
And if i reset the progress it starts working again .
And after maximizing it kicks me out again

**Comment by OvermindDL1** [comment]
> ow and this happens only in one world .
> And if i reset the progress it starts working again .
> And after maximizing it kicks me out again

@Ryius What other items are in your personal inventory, need a complete and entire list including armor and all?

**Comment by Ryius** [comment]
wait i gonne make a screen shot

**Comment by Ryius** [comment]
okey i cleard my inventory completly only thing i have in my inventory is the Elemental manipulator . And still if i select this item i get kickt out

**Comment by OvermindDL1** [comment]
> okey i cleard my inventory completly only thing i have in my inventory is the Elemental manipulator . And still if i select this item i get kickt out

Hmm, no armor?  No baubles?  No anything at all that may sync with the user inventory from other mods?  Can you replicate this with only ChC and DragonAPI and nothing else?

**Comment by Ryius** [comment]
ok

**Comment by Ryius** [comment]
ehm that only in my main world

**Comment by Ryius** [comment]
what do the Elemental Manipulator trigger in the Inventory

**Comment by Ryius** [comment]
it has to do something with the Progression .After i reseted all the progress from Chromaticraft with the comment Chromaprogress the problem stopt .But after i gave me the progress back with the same Comment maximize progression the same bug started again

**Comment by OvermindDL1** [comment]
Is the chromaprogress sent on a player sync and not in its own packet?  Or has it gotten too large for its own packet?

**Comment by ReikaKalseki** [comment]
ChromatiCraft progress is only a couple hundred entries at most; it is nowhere near big enough that it cannot be on player sync.

**Comment by Ryius** [comment]
okey what does the Elementar manipulator trigger that something with 32k is comming up

**Comment by ReikaKalseki** [comment]
That has already been repeatedly explained.

**Comment by Ryius** [comment]
Okey how can i clear my player data

**Comment by ReikaKalseki** [comment]
You do *not* want to do that.

**Comment by Ryius** [comment]
and why

**Comment by Ryius** [comment]
i know i gonne lose all my stuff in my inv but yeah thats not a problem can store them in a chest

**Comment by Aivech** [comment]
You lose more than just all your stuff. Your player is reset to the state that it is at when you first join the game.

**Comment by Ryius** [comment]
i dont have a problem with that

**Comment by Ryius** [comment]
Thats still better than the problem that i have

**Comment by Ryius** [comment]
okey i thing i did corrupt my level.data .I had the same problem last year only way how i noticed to solve it is to go back to a backup of my world and replace it with the broken world .

**Comment by Ryius** [comment]
okey i finaly gath it to work. deleted the player data with NBT editor . I gonne watch what the trigger of this problem is .Thanks for the support

**Comment by MrAmazoni** [comment]
And how to fix it?

**Comment by MrAmazoni** [comment]
I have this message as well when I'm looking at some ore from chromatic.

**Comment by SayethWe** [comment]
Issue still exists in latest version. not tried with no inventory. upon world load, have to look away form rune. Holding repeater block may be related. Has happened before in nether ceiling structures as well.

**Comment by OvermindDL1** [comment]
I would love to have one of your player nbt files to examine if someone could post it?

**Comment by SayethWe** [comment]
Github cannot accept the .dat file. Do you want a paste, or is there a better method? 

also, can now reliably recreate it by moving the elemental manipulator into player hand by any means. Also randomly happen when looking at runes.

looked at the nbt file myself-39Kb. Morph Occupied from 0x11b0 to 0x44754. deleting all morphs made the file 11kb and after one last crash swapping to the manipulator, it seems fixed.

I consider myself humbled, and apologize for misleading you.

**Comment by OvermindDL1** [comment]
Ah, I wouldn't have guessed that morph would fit it's a huge data amount on the player itself, that's a bad place to put it!  o.O
