### ISSUE TITLE
CrC Fertility Bloom and RoC Bedrock Shears

### ISSUE THREAD

**Issue by metnavman** [ReikaKalseki/Reika_Mods_Issues#1342]
Found out through some testing, but it's repeatable and reliable.

Using the Bedrock Shears from Rotarycraft on either an Enrichment Vine or Fertility Bloom returns a corrupted version of each, with weird "chromaticraft.plant.2.blahblah" tag under it. Viewing it in the world is the same, but the WAILA tag is bugged.

Attempting to place these in the world crashes the world with a stacktrace error, and attempting to place the Fertility Bloom on top of the Enrichment Vine with either bugged like this does the same. Having one placed in the world AFTER it's bugged out, crashes the game, and then reloads causes a Nullpointer crash if you attempt to mouse over them. 

I have not attempted this on any of the other "utility" plants from CrC.

Cheers!

**Comment by Builderb0y** [comment]
#1228, #1311
