### ISSUE TITLE
Advanced Rocketry issue: "Rutile ore" (titanium) -> "Rutile Ingot"

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#1343]
Advanced rocketry adds an ore called Rutile, which is an ore for Titanium. 

This ore is oredicted as "oreRutile" and "oreTitanium". 

Rotarycraft processes that to "Rutile ingot" instead of titanium ingot, which is oredicted as "ingotRutile" and is not usable anywhere:
![screenshot from 2017-02-11 00-45-16](https://cloud.githubusercontent.com/assets/3796961/22848325/dae3e940-eff3-11e6-847e-09f7b9396a01.png)
![screenshot from 2017-02-11 00-45-24](https://cloud.githubusercontent.com/assets/3796961/22848326/dae76606-eff3-11e6-81ca-961ec0f70a30.png)

I've AOBD installed, but I've tested this without AOBD and still have that problem. 

relevant bug in AR bugtracker: https://github.com/zmaster587/AdvancedRocketry/issues/154

**Comment by ghost** [comment]
To add on that, issue only exists in extractor: grinder is fine.

**Comment by metnavman** [comment]
Are you playing in Revolution|3? If so, run that ore through an IE Crusher into an Arc Furnace or back over to your Rotarycraft Friction Heater furnaces. There's a bit of wonkyness with titanium in Rev|3, but it's more of the modpack caretakers fixing the recipes to better match oredict.

**Comment by ghost** [comment]
Nope, self-made mod pack.

**Comment by Barhandar** [comment]
Does removing oreRutile entry from the ore change the output?

**Comment by ghost** [comment]
Yep, if I remove the oreRutile oredict entry using minetweaker it works fine.

**Comment by ReikaKalseki** [comment]
Rutile was originally added for another mod (I forget which) which did *not* treat it the same as Titanium; I do not think I have the ability to fix this without breaking that.

**Comment by ghost** [comment]
Thanks for the reply. This bug is already fixed on Advanced Rocketry side.

Also titanium ore is treated much differently in Mariculture &Gregtech  - I think thats' it.

**Comment by ghost** [comment]
Also there is inconsistency: grinder treats that in a different way than extractor does.

**Comment by ReikaKalseki** [comment]
Wait, really? What is the difference?

**Comment by ghost** [comment]
extractor ->rutile flakes
grinder->titanium flakes

That might be because that ore has two oredict tags (oreRutile, oreTitanium)

**Comment by ReikaKalseki** [comment]
That probably is why.
