### ISSUE TITLE
Thermos 1.7.10 server crash report

### ISSUE THREAD

**Issue by Saintanic** [ReikaKalseki/Reika_Mods_Issues#1346]
**How can I (or U) fix that server crash?**

``---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 14.02.17 11:11
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/world/World.func_72903_x()V @47: invokestatic
  Reason:
    Type 'net/minecraft/world/ChunkCoordIntPair' (current frame, stack[0]) is not assignable to 'net/minecraft/entity/player/EntityPlayer'
  Current Frame:
    bci: @47
    flags: { }
    locals: { 'net/minecraft/world/World', 'java/util/Iterator', 'net/minecraft/world/ChunkCoordIntPair' }
    stack: { 'net/minecraft/world/ChunkCoordIntPair' }
  Bytecode:
    0x0000000: 2ab4 0157 b909 4101 002a b401 feb6 0942
    0x0000010: 2ab6 07da b609 46b6 094b 4c2b b902 dc01
    0x0000020: 0099 005a 2bb9 02e0 0100 c007 ce4d 2cb8
    0x0000030: 0951 9a00 602a b401 572c b909 5202 0057
    0x0000040: 2cb4 0955 2cb4 0958 b809 5a42 2ab4 01fe
    0x0000050: 2103 b609 5e57 2a2c b409 552c b409 58b6
    0x0000060: 0315 9a00 162a c001 e2b4 0961 2cb4 0955
    0x0000070: 2cb4 0958 b609 6457 a7ff a32a b402 1413
    0x0000080: 0966 b603 6b2a b605 cbb4 01f6 3c1b 9d00
    0x0000090: 04b1 1100 c804 1b2a b401 27b9 03d9 0100
    0x00000a0: 6487 2ab4 0127 b903 d901 0087 6f14 0967
    0x00000b0: 638e b809 6db8 0970 3d2a b609 7336 0515
    0x00000c0: 0504 a200 0ebb 0975 5913 0977 b709 78bf
    0x00000d0: 2a2a 1309 7913 017c 1c04 6086 1301 7c6a
    0x00000e0: 1309 7a6e b809 7db8 097f 5ab5 0180 b501
    0x00000f0: 7e03 3606 1506 2ab4 0127 b903 d901 00a2
    0x0000100: 0108 2ab4 0127 1506 b903 dd02 00c0 0531
    0x0000110: 3a07 1907 b405 3214 0578 6fb8 04ce 3608
    0x0000120: 1907 b405 3514 0578 6fb8 04ce 3609 1508
    0x0000130: 1509 b809 5a37 0a03 2ab4 01fe 160a b609
    0x0000140: 82b8 096d 360c 2ab4 01fe 160a 150c 0460
    0x0000150: 93b6 095e 572a b401 57bb 07ce 5915 0815
    0x0000160: 09b7 07d1 b909 5202 0057 0336 0d15 0d1c
    0x0000170: a200 912a b401 34b6 0985 9900 0704 a700
    0x0000180: 0402 2ab4 0134 1505 b602 0568 360e 2ab4
    0x0000190: 0134 b609 8599 0007 04a7 0004 022a b401
    0x00001a0: 3415 05b6 0205 6836 0f15 0e15 0860 150f
    0x00001b0: 1509 60b8 095a 3710 2ab4 01fe 1610 b609
    0x00001c0: 889a 003a 2a15 0e15 0860 150f 1509 60b6
    0x00001d0: 0315 9900 292a b401 fe16 1002 b609 5e57
    0x00001e0: 2ab4 0157 bb07 ce59 150e 1508 6015 0f15
    0x00001f0: 0960 b707 d1b9 0952 0200 5784 0d01 a7ff
    0x0000200: 6f84 0601 a7fe f02a b402 14b6 0374 2ab4
    0x0000210: 0207 9e00 0d2a 59b4 0207 0464 b502 072a
    0x0000220: b402 1413 098a b603 6b2a b605 cbb4 098d
    0x0000230: 9900 7e2a b401 27b9 0762 0100 9a00 722a
    0x0000240: b401 342a b401 27b9 03d9 0100 b602 0536
    0x0000250: 062a b401 2715 06b9 03dd 0200 c005 313a
    0x0000260: 0719 07b4 0532 b804 ce2a b401 3410 0bb6
    0x0000270: 0205 6008 6436 1219 07b4 0533 b804 ce2a
    0x0000280: b401 3410 0bb6 0205 6008 6436 1319 07b4
    0x0000290: 0535 b804 ce2a b401 3410 0bb6 0205 6008
    0x00002a0: 6436 142a 1512 1513 1514 b609 9057 2ab4
    0x00002b0: 0214 b603 74b1                         
  Stackmap Table:
    append_frame(@27,Object[#729])
    same_frame_extended(@120)
    chop_frame(@123,1)
    append_frame(@146,Integer)
    full_frame(@208,{Object[#2],Integer,Integer,Top,Top,Integer},{})
    append_frame(@244,Integer)
    full_frame(@365,{Object[#2],Integer,Integer,Top,Top,Integer,Integer,Object[#1329],Integer,Integer,Long,Integer,Integer},{})
    same_frame(@385)
    same_locals_1_stack_item_frame(@386,Integer)
    append_frame(@412,Integer)
    same_locals_1_stack_item_frame(@413,Integer)
    chop_frame(@507,1)
    full_frame(@513,{Object[#2],Integer,Integer,Top,Top,Integer,Integer,Object[#1329]},{})
    chop_frame(@519,1)
    same_frame(@543)
    same_frame_extended(@686)

	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:288)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/world/World.func_72903_x()V @47: invokestatic
  Reason:
    Type 'net/minecraft/world/ChunkCoordIntPair' (current frame, stack[0]) is not assignable to 'net/minecraft/entity/player/EntityPlayer'
  Current Frame:
    bci: @47
    flags: { }
    locals: { 'net/minecraft/world/World', 'java/util/Iterator', 'net/minecraft/world/ChunkCoordIntPair' }
    stack: { 'net/minecraft/world/ChunkCoordIntPair' }
  Bytecode:
    0x0000000: 2ab4 0157 b909 4101 002a b401 feb6 0942
    0x0000010: 2ab6 07da b609 46b6 094b 4c2b b902 dc01
    0x0000020: 0099 005a 2bb9 02e0 0100 c007 ce4d 2cb8
    0x0000030: 0951 9a00 602a b401 572c b909 5202 0057
    0x0000040: 2cb4 0955 2cb4 0958 b809 5a42 2ab4 01fe
    0x0000050: 2103 b609 5e57 2a2c b409 552c b409 58b6
    0x0000060: 0315 9a00 162a c001 e2b4 0961 2cb4 0955
    0x0000070: 2cb4 0958 b609 6457 a7ff a32a b402 1413
    0x0000080: 0966 b603 6b2a b605 cbb4 01f6 3c1b 9d00
    0x0000090: 04b1 1100 c804 1b2a b401 27b9 03d9 0100
    0x00000a0: 6487 2ab4 0127 b903 d901 0087 6f14 0967
    0x00000b0: 638e b809 6db8 0970 3d2a b609 7336 0515
    0x00000c0: 0504 a200 0ebb 0975 5913 0977 b709 78bf
    0x00000d0: 2a2a 1309 7913 017c 1c04 6086 1301 7c6a
    0x00000e0: 1309 7a6e b809 7db8 097f 5ab5 0180 b501
    0x00000f0: 7e03 3606 1506 2ab4 0127 b903 d901 00a2
    0x0000100: 0108 2ab4 0127 1506 b903 dd02 00c0 0531
    0x0000110: 3a07 1907 b405 3214 0578 6fb8 04ce 3608
    0x0000120: 1907 b405 3514 0578 6fb8 04ce 3609 1508
    0x0000130: 1509 b809 5a37 0a03 2ab4 01fe 160a b609
    0x0000140: 82b8 096d 360c 2ab4 01fe 160a 150c 0460
    0x0000150: 93b6 095e 572a b401 57bb 07ce 5915 0815
    0x0000160: 09b7 07d1 b909 5202 0057 0336 0d15 0d1c
    0x0000170: a200 912a b401 34b6 0985 9900 0704 a700
    0x0000180: 0402 2ab4 0134 1505 b602 0568 360e 2ab4
    0x0000190: 0134 b609 8599 0007 04a7 0004 022a b401
    0x00001a0: 3415 05b6 0205 6836 0f15 0e15 0860 150f
    0x00001b0: 1509 60b8 095a 3710 2ab4 01fe 1610 b609
    0x00001c0: 889a 003a 2a15 0e15 0860 150f 1509 60b6
    0x00001d0: 0315 9900 292a b401 fe16 1002 b609 5e57
    0x00001e0: 2ab4 0157 bb07 ce59 150e 1508 6015 0f15
    0x00001f0: 0960 b707 d1b9 0952 0200 5784 0d01 a7ff
    0x0000200: 6f84 0601 a7fe f02a b402 14b6 0374 2ab4
    0x0000210: 0207 9e00 0d2a 59b4 0207 0464 b502 072a
    0x0000220: b402 1413 098a b603 6b2a b605 cbb4 098d
    0x0000230: 9900 7e2a b401 27b9 0762 0100 9a00 722a
    0x0000240: b401 342a b401 27b9 03d9 0100 b602 0536
    0x0000250: 062a b401 2715 06b9 03dd 0200 c005 313a
    0x0000260: 0719 07b4 0532 b804 ce2a b401 3410 0bb6
    0x0000270: 0205 6008 6436 1219 07b4 0533 b804 ce2a
    0x0000280: b401 3410 0bb6 0205 6008 6436 1319 07b4
    0x0000290: 0535 b804 ce2a b401 3410 0bb6 0205 6008
    0x00002a0: 6436 142a 1512 1513 1514 b609 9057 2ab4
    0x00002b0: 0214 b603 74b1                         
  Stackmap Table:
    append_frame(@27,Object[#729])
    same_frame_extended(@120)
    chop_frame(@123,1)
    append_frame(@146,Integer)
    full_frame(@208,{Object[#2],Integer,Integer,Top,Top,Integer},{})
    append_frame(@244,Integer)
    full_frame(@365,{Object[#2],Integer,Integer,Top,Top,Integer,Integer,Object[#1329],Integer,Integer,Long,Integer,Integer},{})
    same_frame(@385)
    same_locals_1_stack_item_frame(@386,Integer)
    append_frame(@412,Integer)
    same_locals_1_stack_item_frame(@413,Integer)
    chop_frame(@507,1)
    full_frame(@513,{Object[#2],Integer,Integer,Top,Top,Integer,Integer,Object[#1329]},{})
    chop_frame(@519,1)
    same_frame(@543)
    same_frame_extended(@686)

	at net.minecraftforge.common.ChestGenHooks.init(ChestGenHooks.java:59)
	at net.minecraftforge.common.ChestGenHooks.<clinit>(ChestGenHooks.java:39)
	at Reika.DragonAPI.Libraries.World.ReikaGenHelper.addChestLoot(ReikaGenHelper.java:77)
	at Reika.DragonAPI.Instantiable.Worldgen.LootController.registerToWorldGen(LootController.java:33)
	at Reika.RotaryCraft.RotaryChests.addToChests(RotaryChests.java:67)
	at Reika.RotaryCraft.RotaryCraft.load(RotaryCraft.java:355)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Thermos Version: cyberdynecc:Thermos:1.7.10-1614.58
	Plugins: 
	Disabled Plugins: 
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 803630312 bytes (766 MB) / 1056309248 bytes (1007 MB) up to 2130051072 bytes (2031 MB)
	JVM Flags: 9 total; -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -Xms1G -Xmx2G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (Thermos-1-7-10-1614-server.jar) 
	UCHI	Forge{10.13.4.1614} [Minecraft Forge] (Thermos-1-7-10-1614-server.jar) 
	UCHI	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHI	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHI	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V16d.jar) 
	UCHE	RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V16d.jar) 
	UCHE	ElectriCraft{1.0} [ElectriCraft] (ElectriCraft 1.7.10 V16d.jar) 
	UCHE	ReactorCraft{1.0} [ReactorCraft] (ReactorCraft 1.7.10 V16d.jar) 
	UCHI	RTG{1.7.10-1.1.1.3} [Realistic Terrain Generation] (RTG-1.7.10-1.1.1.3.jar) 
	Profiler Position: N/A (disabled)
	Player Count: 0 / 10; []
	Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by ghost** [comment]
#658
