### ISSUE TITLE
Possible issue loading the Nether

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1348]
https://github.com/ForestryMC/MagicBees/issues/4

I have no idea which of the mods involved is actually causing the issue, but it just keeps going until I kill the instance.

**Comment by metnavman** [comment]
Says there's a stackoverflow in that massive mess, and terraingen is causing it. Reads to me like you've got a couple different mods fighting over what they want to put in a spot, which causes the whole thing to give up.

**Comment by Shahelion** [comment]
From what I can remember, mods that would be generating are Chromaticraft roof stuff, Magic Bees hives, Arcana RPG nether towers, Thaumcraft nodes, Automagy node altar things, Magic Cookies dark shrines, and vanilla fortresses.

Other than removing one of those mods (only Magic Bees could be removed without causing problems at this point) is there anything I can do?

**Comment by metnavman** [comment]
Considering Chromaticraft does all sorts of things to the Nether roof and I have no idea what, if anything, those other mods do up there (but apparently something), I'd say probably not.

**Comment by Shahelion** [comment]
None of the others generate on the roof, at least. Automagy makes wisp spawner tower things in large lava pools, Magic Cookies has dark shrines that generate like fortresses, and smaller dark shrines, and apparently some quartz things under the lava seas, and Arcana Rpg towers just appear wherever on land.

Going to attempt removing Magic Cookies, as it has the biggest nether generation after Chromaticraft...hope it works.

**Comment by Shahelion** [comment]
Nope, still borked even without Magic Cookies. Going to try and let it sort itself out, see how long it takes...

**Comment by ReikaKalseki** [comment]
Why are you reporting this to me? The issue is clearly "gibby" dungeons.

**Comment by Shahelion** [comment]
CC is also mentioned in it, and how was I supposed to know which mod it was? I figured if I posted it to the mods involved, I would get an answer on how to fix it. Also, Arcana RPG doesn't have an issue tracker, although I have posted on the MC forum thread.
