### ISSUE TITLE
ReactorCraft Toroid / Van De Graaff issue

### ISSUE THREAD

**Issue by aetherpirate** [ReikaKalseki/Reika_Mods_Issues#1349]
Running a custom pack with V16d DragonAPI, RotaryCraft, ReactorCraft, ElectricCraft, many other mods. 

Forge 1614, no Thermos, bukkit, etc. 

I am using Fastcraft 1.23

After placing 8 Van De Graaff's below my Toroids and powering them with DC Engines, I logged off. My server lagged hard. Warmroast capture attached. 

I tried editing dragonapi.cfg and turning down Particle Limit to 2000, then 1000. 

I also tried enabling Remove Erroring Tiles and Entities in forge.cfg

Attempts to log back into the server result in eventual timeout and log off. No chunks load, though I can see the sky and sun. 

![reika](https://cloud.githubusercontent.com/assets/11506409/22987540/1ad8ec30-f37d-11e6-8b09-0a2861e8fa26.png)

**Comment by ReikaKalseki** [comment]
Did you not chunkload the reactor?

**Comment by aetherpirate** [comment]
I did, with FTB Utilities. I'll try another chunkloader in case this one is misbehaving

**Comment by aetherpirate** [comment]
It does seem to have been a chunk loading issue. I used a Dimensional Anchor instead of FTB Utilities chunk loading, and things are much better now.
