### ISSUE TITLE
Issue with updating your mods on a server

### ISSUE THREAD

**Issue by Muretsu** [ReikaKalseki/Reika_Mods_Issues#135]
I have been running Bevo's tech pack with Rotary, Reactor and Electricraft added as well as some other magic mods on a private server.  I updated all of your mods and when I open any of my saves in single player it loads up with no issues; however, when I try to load the server it gives me a large list of missing items.  I have included the server load log since the game isn't crashing at this point.  Thank you for your time, any help would be appreciated.

https://gist.githubusercontent.com/anonymous/27ba46c019fc9fa6028d/raw/FML-SERVER-LATEST

**Comment by ljfa-ag** [comment]
Looks like it couldn't read the .jar files for Reika's mods. Maybe try to redownload them.

**Comment by Muretsu** [comment]
Awesome! That was it.  I did notice the original updated downloads had + signs in the file name.  Thanks, for the assist!
