### ISSUE TITLE
AC Electric Engine duplication

### ISSUE THREAD

**Issue by herp21** [ReikaKalseki/Reika_Mods_Issues#1351]
I am currently on V16d of Rotarycraft, and every time i break any one of me AC electric engines, if there is any shaft core that is magnetized inside of the inventory, when it is broken with a pickaxe, the engine will drop plus 2 shaft cores, both magnetized to the same amount. Example, currently I have 6 Shaft cores magnetized to 87 microTeslas, i put one inside of my non-operational Ac engine and break the engine, Two shaft cores pop out of it at 87 microTeslas, so now I have 8 shaft cores at 87 microTeslas.

Here is 3 images as well showing the issue as best I can, Thank you and have a good day.

![2017-02-16_21 37 59](https://cloud.githubusercontent.com/assets/6326259/23050432/5b9c3984-f490-11e6-8659-d6bbb9a5c4f4.png)
![2017-02-16_21 38 10](https://cloud.githubusercontent.com/assets/6326259/23050434/5ba3352c-f490-11e6-93e4-189d9fc2ecb3.png)
![2017-02-16_21 38 14](https://cloud.githubusercontent.com/assets/6326259/23050433/5b9e9300-f490-11e6-9254-0bedebc4c349.png)
![2017-02-16_21 40 36](https://cloud.githubusercontent.com/assets/6326259/23050496/ad0bd914-f490-11e6-85ce-63edec6d2a2a.png)

**Comment by ReikaKalseki** [comment]
Are one of those clientside ghost items?

**Comment by Builderb0y** [comment]
They can't be, the server controls when players pick up items, and you can see the quantity increased in his inventory.

**Comment by ReikaKalseki** [comment]
No, that can happen clientside as well.

**Comment by Builderb0y** [comment]
Items in your inventory can be desync'd, but a ghost dropped item entity cannot be picked up, let alone remain desync'd in your inventory after doing so.

**Comment by Barhandar** [comment]
If they can be interacted with and persist through full inventory refreshes, they're serverside entities. Also, which mod adds that melt-boil-weight data?

**Comment by herp21** [comment]
Sorry about the late response, however these items that drop are useable by both myself and my friend in any engine we choose and they persist no matter whether we leave and join back or the server restarts. As for the other mod that is The wonderful Gregtech..

**Comment by ReikaKalseki** [comment]
This is not happening for me. You must have a mod interacting with it.

![](http://i.imgur.com/DXicPus.png)
