### ISSUE TITLE
[Geostrata] Thaumcraft Excavation Focus and Lava Rock

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1352]
The excavation focus seems to have a silk-touch effect when harvesting lava rock, even unmodified. No idea if anything can be done to fix this.

**Comment by ReikaKalseki** [comment]
Not a bug.

**Comment by Shahelion** [comment]
Every other method of mining so far yields the same block for all types of lava rock except this. They all give the mostly lava variant.
