### ISSUE TITLE
Lumen Broadcast Transmitter

### ISSUE THREAD

**Issue by metnavman** [ReikaKalseki/Reika_Mods_Issues#1353]
This is what I get for trying to play with every aspect of Chromaticraft, haha.

Setting up the Transposition Gates seems to require Lumen Network power at both locations. Easy enough, I'll just build a pair of those super-cool Broadcast Transmitters and put the place I wanna' build at way far away. Set up first tower no problem. Connects, particles in the Transmitter block, and banging on it gives the happy sound.

Repeat process down the line, about 1200 or so blocks away. Lined them up, right Y-level, particle effects in the Transmitter block showing the structure is built right.... and nothing. Removed Fastcraft to see if that was borking something up. No dice. Reloaded the game completely to reset anything that might need resetting. Nadda'.

http://imgur.com/a/Aa42c

Towers are built North/South in a straight line from each other and there's nothing impeding their view for the entire distance between them. That was actually quite fun (ever seen The World is Not Enough?), haha. 

Anyways, hope it's not that they're spotty and possibly borked in certain situations until V17!

**Comment by ghost** [comment]
Transposition Gates can work with just one having energy. Pretend A has energy and you also have B & C gates:
A -> B/C
B/C -> A
However, you can't do 
C -> B
B -> C
You could go from B to A, and then C, but not directly without using a powered gate.
I have had problems with Lumen Beacons in the past, but I never needed them in survival. They do "fizzle out" each other if they're too close though, and might require a minimum of 2k blocks, but I'm not sure.

**Comment by redelman** [comment]
IIRC Lumen Beacons are borked in v16d. They're entirely useless until you have turbocharged lumen transmitters.

**Comment by metnavman** [comment]
> They're entirely useless until you have turbocharged lumen transmitters.

My network is fully-realized. That's a non-issue. The issue is that correctly built/aligned Transmitters aren't hooking up.

> They do "fizzle out" each other if they're too close though, and might require a minimum of 2k blocks, but I'm not sure.

As per the code seen [here](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/TileEntity/Networking/TileEntityCrystalBroadcaster.java#L27) , they will cause interference only if they are within 384 blocks of one another, and their minimum range is 512 blocks. Both of these are accounted for, as can been seen in the linked pictures. They are over 1200 blocks apart. 

Thank you for that information on the Transposition gates. I will fiddle with them further. This info removes the need for the Broadcast Transmitter, but I'd still like to know why these cool-looking towers don't want to play ball. :(

**Comment by ReikaKalseki** [comment]
Are you *sure* they are correctly aligned?

**Comment by OvermindDL1** [comment]
_/me is just passing through_
Wish the transmitters operated based on, say, a color frequency, but did not need to be aligned, but maybe they have to be 'high enough' or something...  It is surprisingly hard to align at distance.  However, if holding the core block of the structure showed a line base on other alignments would make setup significantly easier.

**Comment by metnavman** [comment]
> Are you sure they're correctly aligned?

The imgur link I put is a picture of me standing dead center on top of each tower. The Y-lvl and X-lvl sync up, and the distance ticks the code requirements. Don't know what else i can do to make em happy.

**Comment by ReikaKalseki** [comment]
Maybe the mechanic for them needs to be revisited (no LOS restriction, for example)...

**Comment by metnavman** [comment]
I thought it may have had to do with that persistent bug I have with Revolution and the Crystal Network in SSP(network still craps out when changing dimensions until game reload), but that wasn't the case. The two towers(ha) just won't link up. 'Tis a shame, but that info for the Transposition Gates got me to my end-goal anyways, so now there's just a pretty tower hangin' around out back. I'm okay with it.

**Comment by ReikaKalseki** [comment]
OK, I just changed the broadcaster mechanics. They no longer need line of sight between each other - this also has the side effect of removing the orthogonality restriction, though I could manually implement it or something similar if desired - but need "clear air" around the upper region of the structure.

**Comment by OvermindDL1** [comment]
> this also has the side effect of removing the orthogonality restriction

Huh, does that mean all towers of a given player are basically 'linked together' (if far enough away), or all towers of any players can cross-talk?

Would be nice to be able to key them so certain ones can only talk to certain other keyed ones, like via certain color rune patterns in the structure or so, though unsure if that is really useful...

**Comment by ReikaKalseki** [comment]
They can - and always could - cross-communicate.

**Comment by metnavman** [comment]
Oh man, that's huge. That will let them function in the way I described to you with my crappy MS Paint drawing on Reddit during your AMA. If you couple this with the throughput change you've talked about, once a network is fully-realized, you can funnel a bunch of far-away colors into a big tower, mainline it to your base, and then offload into your local network. That would clean up soooo many pylons and make for some awesome-looking setups, at the cost of redoing your network for an "end game" state.
