### ISSUE TITLE
Reactorcraft: Empty Canister

### ISSUE THREAD

**Issue by metnavman** [ReikaKalseki/Reika_Mods_Issues#1355]
Little QoL stuff:

* Cannot be crafted in an ME Crafting Terminal, but CAN be auto-crafted via Molecular Assembler and inserted into an AE network that way.

* When "un-stacked" from the initial stack of 16, empty canisters do not re-stack, remaining singular in the player inventory or chest. AE storage and Barrels(innate stacking storage) are unaffected.

**Comment by ReikaKalseki** [comment]
The latter is intentional; the former is not within my control.
