### ISSUE TITLE
Feature Request: Reduce stack size whilst using patterns

### ISSUE THREAD

**Issue by syntax-error** [ReikaKalseki/Reika_Mods_Issues#1356]
I've spent a few hours tonight examining methods to automate efficient Blast Furnace HSLA Steel production, and machine crafting. My research has turned up very little, save for mods which allow for item slot specific insertion, which are few and far between. Whilst I do understand that there is a config change for automating machine crafting (by allowing them to built in a regular crafting grid), I feel this limits the purpose and minor tiering that using using the worktable provides. And, of course, that still doesn't allow automation for efficient use of the blast furnace..

That being the case, I'd like to suggest limiting the stack size for each slot in a worktable or blast furnace to one (1), but only when using a pattern. That way vanilla hoppers, and any number of mods (AE2, Botania, Thaumcraft, Automagy, etc) can be utilised to provide automation of these blocks. Restricting the stack size only when using a pattern means that manual, general-purpose uses of the blocks remain unaffected by the change.

**Comment by ReikaKalseki** [comment]
I need to consider this, because it hampers high-throughput production.

**Comment by syntax-error** [comment]
Well. You can only craft as fast as your blast furnace bakes, or as fast as you send a red stone signal to the table. Many mods have an item insertion speed to match that. I presume even your own item pump should be able to match a fairly fast red stone clock. You don't lose throughput if you replenish before the next craft finishes.

**Comment by ReikaKalseki** [comment]
Have you never 1-tick-operated a Blast Furnace?

**Comment by ReikaKalseki** [comment]
I did [one better](http://i.imgur.com/PlyuWkI.png).

![](http://i.imgur.com/PlyuWkI.png)
