### ISSUE TITLE
Worktable loses items when output full

### ISSUE THREAD

**Issue by syntax-error** [ReikaKalseki/Reika_Mods_Issues#1357]
Playing around with automating a worktable, I placed inside the materials for 64 crafts of Stone Shafts (5 stacks of slabs, 1 stack of stone rods) then hooked a redstone repeater clock to the table. After 8 crafts, the output reached 64, but the worktable continued to craft. After the crafting was completed, I retrieved the items from the output, and recovered the 64 Stone Shafts. The inputs are missing, and yet I'm short 448 Stone Shafts. I tested with a number of other recipes too. It affects machine construction (regardless of whether the output is in multiples of 8, or 1) but does not affect machine deconstruction. When deconstructing 96 DC engines, the table will pause if any of the outputs are full.

**Comment by ReikaKalseki** [comment]
This is vanilla crafting code....does it happen when manually crafting?

**Comment by syntax-error** [comment]
No, since you have to pick up from the outputs to craft manually multiple times. Or shift click, which sends it directly to your inventory. This only happens when you force crafting with a red stone signal.

**Comment by Duckfan77** [comment]
This is an issue that occurs with vanilla crafting as well, for example when shift decrafting blocks without enough space in your inventory. It will void the items that don't fit in that case.

**Comment by OvermindDL1** [comment]
> This is an issue that occurs with vanilla crafting as well, for example when shift decrafting blocks without enough space in your inventory. It will void the items that don't fit in that case.

Might be a mod I have but it stops for me when space runs out and I cannot craft anymore via shift+clicking, I can still non-shift-click to grab an output though and toss it on the ground if I want.

**Comment by ReikaKalseki** [comment]
Fixed.
