### ISSUE TITLE
Fusion Reactor cooling

### ISSUE THREAD

**Issue by metnavman** [ReikaKalseki/Reika_Mods_Issues#1359]
I was under the impression that a change went in some time ago that reduced the amount of coolant required for the Toroids to a less ludicrous amount.

Currently _each Refrigeration unit has a 67MW magnetostatic with a 2:1 gear on it for torque. Each machine is producing 2000 mb every 1.95sec. 8 total._

The reactor is laughing at that amount.

Edit:

Also Magnetic Containment pipes are being ridiculous - http://imgur.com/a/RtiKA

I've been having them melt INSIDE the Plasma Injector, even with a 64MW and 8MW VDG pumping charge into the piping setup(if I go higher than 8MW on the second VDG, it explodes. It's wonderful). I've extended the pipes out a couple blocks from the injector and the end result is that they "seem" to not be melting, (even though that's adding more pipes that need charged???) but I get that error in the screenshot + I can't keep the reactor going long enough to see anything else happen because it burns through 36 drums of 256 buckets of coolant w/the 8 Refrigeration units running in about 3 minutes. Not even close to keeping up.

**Comment by ReikaKalseki** [comment]
1000 mB/s is *nowhere* near enough, nor is it anywhere near your production limit with eight machines.

**Comment by metnavman** [comment]
Errr, yeah, I could see where you'd get that from. I've edited the OP to better describe my cooling setup.

Each Refrigeration unit has a 67MW magnetostatic with a 2:1 gear on it for torque. _Each machine_ is producing 2000 mb every 1.95sec. 

In reality, I'm more interested in the magnetic pipe chat error, since I can always just throw more raw machine power at the cooling problem, even if the cooling requirements aren't intended. The error I can't really fix or figure out solo.

**Comment by Builderb0y** [comment]
Don't max out on torque. Or speed. There's a sweet spot that gets you the most LN2 over time, and that sweet spot is the minimum amount of speed required to get it to 1-tick ops, and no faster. At that speed, just one refrigeration unit at 67 MW is enough to supply the whole fusion reactor.

**Comment by metnavman** [comment]
> Don't max out on torque. Or speed. There's a sweet spot that gets you the most LN2 over time, and that sweet spot is the minimum amount of speed required to get it to 1-tick ops, and no faster. At that speed, just one refrigeration unit at 67 MW is enough to supply the whole fusion reactor.

Just plugging a 67MW Magnetostatic directly puts one unit at 2 operations a tick. With proper ice supply, it's got the whole reactor topped off permanently. 

That one unit produces more L. Nitrogen than 16 units producing 2k mB at 1.95sec. Unreal.... 
Having watched Reika's setup for cooling last year, I'd have never even thought that it was capable of this.

Thank you

In other news, the pipes stopped melting for that run of the reactor, and I have no idea why, lol. Put it back to the original configuration, broke and replaced the Van De Graffs, same power output, and it's functioning. I swear...
