### ISSUE TITLE
Crashed with AE

### ISSUE THREAD

**Issue by TehporP** [ReikaKalseki/Reika_Mods_Issues#136]
Well that's sound a little bit ridiculous
But this is true 
When I  try to update RotaryCraft and DragonAPI and start the game Them crashed
here is the report
http://pastebin.com/fVVjNmLs

Well because I am low on English so i cannot explain this situation well 
If you feel annoyed or thinking this is AE‘s fault  just close this issue and Sorry about that

**Comment by ljfa-ag** [comment]
Did you find out the problem or why did you close it?

**Comment by TehporP** [comment]
I am trying  But I think it is a little bit offensive so i closed it

**Comment by TehporP** [comment]
Well Forge 1490 still didnt work 
When I deleted DragonAPI and RotaryCraft and my client run perfectly

**Comment by ljfa-ag** [comment]
Next time please put the crash report on something like Pastebin.

**Comment by TehporP** [comment]
Sorry  this is my first time.....

**Comment by ReikaKalseki** [comment]
Update AE.

**Comment by TehporP** [comment]
I do updated AE to least verison but sitll crashed
I dont why

**Comment by ReikaKalseki** [comment]
Uh oh...

**Comment by TehporP** [comment]
And i found a strange situation If I changed AE mod file name Them minecraft will be crashed

**Comment by ReikaKalseki** [comment]
....

**Comment by TehporP** [comment]
Yes That is really ridiculous Right？  If you dont believe me just forget it.....At least I dont wanna update ROC for a while..And sorry for bothering you

**Comment by ReikaKalseki** [comment]
Yes, you **do** want to.

**Comment by TehporP** [comment]
No mean to offend And sorry about that

**Comment by ReikaKalseki** [comment]
That was a warning. :P
