### ISSUE TITLE
RotaryCraft or DragonAPI that is crashing

### ISSUE THREAD

**Issue by SJS184** [ReikaKalseki/Reika_Mods_Issues#1361]
Hey ReikaKalseki I was playing minecraft and i was using RotaryCraft and DragonAPI and when I was using the mod CloneCraft it crashed. The errors are not from CloneCraft it was DragonAPi and for some reason RotaryCrafts event manager. it came from the function onRemoveArmor so can you please try to find a way to fix it please. Also here is a pastebin link to the crash report.
http://pastebin.com/qmYzPrGm thank you for taking the time to read this and have a great day.

**Comment by ReikaKalseki** [comment]
Clonecraft is firing a BoneMeal event - or modifying the existing ones - to have a null world. This is invalid.
