### ISSUE TITLE
Fusion Reactor causing world-ending lag on dimension change

### ISSUE THREAD

**Issue by metnavman** [ReikaKalseki/Reika_Mods_Issues#1362]
**Fusion Reactors don't like not being chunk-loaded in their entirety!!!** 

Edit: Writing this down made my brain question some things, so I dug deeper on World Anchors and their effective range. I'm swapping out regular anchors for "admin" ones to ensure loading and adding a couple more on the possibility that my chunk coverage was not sufficient. 

Edit2: It does indeed look like a couple 1-2 block wide sections were getting missed in corners by the chunk-loaders. I've got it fired back up and am sitting in the other dimension to see if the lag builds up again, but I'm fairly confident that it was a chunk-loading issue that needed sorted out on my end.

Edit3: Indeed it was.

**Comment by OvermindDL1** [comment]
Game-killing lag still sounds like a bug, regardless of user error in back-end game mechanics of chunkloading though...

**Comment by ReikaKalseki** [comment]
There is nothing I can do about it. Entities, once unloaded, do not tick and thus run no code.

**Comment by metnavman** [comment]
Having learned that Fusion Reactor neutrons are no longer 100% absorbed by Absorbers compounded this issue for me, as I'm having to go back and completely shield the entire array, since they are most definitely escaping (including through the Plasma Injectors). I'm having success with 2 Bedrock blocks and some concrete in-line to get as close to 100% as feasible. 

Sucks for my building layout though. :(

**Comment by metnavman** [comment]
Regarding neutrons and escaping:

Will lag on game start-up or dimension change or anything else cause neutrons to momentarily "jump up or down" a level? This would explain why there's irradiated sections in spots where there's no business being any. Steam boilers are transparent to neutrons, but I've seen radiation dots that look to be 1 level above/below them, as well as in a couple places directly behind the Plasma injectors. If a lag event allows the neutron entity to jump up/down long enough to register as being on a different y-level, that would put it perfectly in line with what I'm seeing.

**Comment by ReikaKalseki** [comment]
Neutrons should never move vertically.
