### ISSUE TITLE
Chromaticraft Kurauri pendant 

### ISSUE THREAD

**Issue by metnavman** [ReikaKalseki/Reika_Mods_Issues#1363]
The pendant, when in the player's inventory or the CrC pouch, is applying the regen effect to all entities in whatever it's range is. This includes hostile mobs and boss mobs. This does not occur if the pendant is placed into the CrC Pouch and "deactivated", but will start occurring again once it's "activated" in the pouch. It will always occur if the player attacks a hostile mob in melee range with the pendant in the inventory. The mob, if not 1-shot, gains regen.

**Comment by Builderb0y** [comment]
Intended. You can negate this effect with the purification gem.

**Comment by metnavman** [comment]
So, the Kurauri pendant puts Regen on the mobs, and the Tahara pendant turns around and removes Regen from the same mob? I understand if that's a limitation in the code for the pendant (unable to make the Regen target only the player), but if that's _not_ a limitation, that seems rather wonky and makes the game do calculations for no real reason. The Regen pendant will apply faster than Tahara can take it off. End result is you need to turn the Regen pendant off if you're in melee and you're not going to 1-shot the target (ie Boss mobs or buffed HP mobs).

Again, if that's how it has to be from a game limitation standpoint, it's whatevs.

Edit: Now that I think about it, does it work that way for every pendant? Are we unknowingly buffing the crap outta' mobs in melee with Resistance, Speed, etc?

**Comment by Builderb0y** [comment]
It was done to make them slightly more balanced, and it's not a limitation of the code. Every time you attack a mob with active pendants in your inventory, it applies those pendant effects to the mob you attacked. I think the same applies to them attacking you, though I've never tested that. This applies to all pendant colors, so enjoy giving them poison and wither with kijani and kuro pendants.

**Comment by metnavman** [comment]
Yeah, the debuff ones make sense, as does their counter-effect in the Nether (that was a fun first trip after making 3/4 of the pendants and forgetting to deactivate them when I went there!).

Cool cool. Seems like the intent is to have you turn off the Regen pendant when fighting, so you're not unbelievably unkillable, only mostly. :P

**Comment by ReikaKalseki** [comment]
> it applies those pendant effects to the mob you attacked. I think the same applies to them attacking you, though I've never tested that.

It does not.

> This applies to all pendant colors, so enjoy giving them poison and wither with kijani and kuro pendants.

This is the primary reason: Otherwise those pendants would be worthless.
