### ISSUE TITLE
Chromaticraft "Life Steal" altar ability

### ISSUE THREAD

**Issue by metnavman** [ReikaKalseki/Reika_Mods_Issues#1364]
The altar ability that grants "Life steal on striking enemies" is applying an aura to the player that randomly fires off. If the player is at full health, the player has a 1-2 sec sprinkle of green "0s" flash above their head, indicating no healing done but healing attempted. This is just standing around not attacking anything. 

This is consistent, and turning the CrC ability off removes the green "0"s.

**Comment by ReikaKalseki** [comment]
Do you have things killing on your behalf (eg Lumen Turrets)?

**Comment by metnavman** [comment]
There just so happens to be a BIG-ASS BALL OF LIGHT at my main base laying waste to everything that gets within ~100 blocks of it, lol. :D 

Aura Locus even murders dudes underground, so that would make sense that it's almost constantly triggering with the ability active. Seems unintended!

**Comment by ReikaKalseki** [comment]
I probably cannot change this, but I will check.

**Comment by ReikaKalseki** [comment]
It is coded as a pylon attack, which should not be tied to a player doing damage.
