### ISSUE TITLE
Pneumatic Item Pump throwing NPE when facing empty space

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1365]
hi,
I temporally disabled my fermenting setup to test the fluid radiator (no idea why it isn't working) by removing one fermenter and ever since then the item pump here has been throwing a NPE twice a second.  

![2017-02-25_17 01 41](https://cloud.githubusercontent.com/assets/5174562/23332746/0193a422-fb7f-11e6-99cb-026790ba2700.png)

http://pastebin.com/HXDp2Kvd

using v16d.

**Comment by ReikaKalseki** [comment]
Fixed.
