### ISSUE TITLE
crashing....

### ISSUE THREAD

**Issue by AndrewFishelium** [ReikaKalseki/Reika_Mods_Issues#1366]
if i use 10.13.4.1614 and olders the game crashes with rotarycraft my game dont make thath why this is happening (i hate my english)

**Comment by ReikaKalseki** [comment]
This contains no useful information and is not a helpful report.

**Comment by ghost** [comment]
Please don't report crashes without a crash log (use Pastebin/gist). We can't figure out the problem when the info is missing the key.

**Comment by ReikaKalseki** [comment]
So...?
