### ISSUE TITLE
Using a recall tablet sets the player to be null (?)

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1367]
hi,
Ok this is an odd one, but I just tested it in a creative flat world.  

After using an recall tablet I am unable to break blocks and eventually crash with the following NPE in ForgeHooks.onBlockBreakEvent :

http://pastebin.com/CPgRyYVG

https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/src/main/java/net/minecraftforge/common/ForgeHooks.java#L459

**Comment by ReikaKalseki** [comment]
More likely the netServerHandler is null, but **why**...

**Comment by Turmfalke2** [comment]
Well I haven't looked at the code for the recall tablet, but teleporting the player isn't exactly rocket science and other mods are able to do that without crashing.

**Comment by Turmfalke2** [comment]
Reproduce it in a clean minecraft instance using forge 1614, DragonApi and chromaticraft. It is not a chrossmod interaction.  

Another interesting observation: I can avoid the crash after using a tablet by dying - presumably the move to spawn part from respwning fix it.  

I have the feeling the cult print is the test EntityPlayerMP. Are you sure it is safe to just create a new one?

**Comment by ReikaKalseki** [comment]
I do not create new players. Teleporting a player is as simple as setting the position.

**Comment by Turmfalke2** [comment]
To me this looks like you a creating a new EntityPlayerMP to test for collisions. 
https://github.com/ReikaKalseki/ChromatiCraft/blob/66389daf061fa868cc6e8b8ba1d62882e21bea9f/Items/Tools/ItemWarpCapsule.java#L58

**Comment by ReikaKalseki** [comment]
Fixed.
