### ISSUE TITLE
Chromaticraft Transposition Gate

### ISSUE THREAD

**Issue by metnavman** [ReikaKalseki/Reika_Mods_Issues#1368]
Just a heads up, as this pertains to #927 

The Transposition Gate is being affected by whatever "residual light" thinger that Thaumcraft Arcane Lamps do. It breaks the gate, until all Arcane Lamps are moved out of range. I'd wager the Railcraft tomfoolery would do the same thing, though I have those blocks disabled.

**Comment by ReikaKalseki** [comment]
Like there, there is nothing I can do here.

**Comment by ReikaKalseki** [comment]
...Maybe.

**Comment by OvermindDL1** [comment]
As long as https://github.com/ReikaKalseki/DragonAPI/blob/master/Instantiable/Data/BlockStruct/FilledBlockArray.java#L413 is the same in all other areas (I've not checked) then it should not be an issue...

Actually, checking...  It looks like air gets stuffed into the structures at setBlock, which gets stuffed into a BlockKey, which is https://github.com/ReikaKalseki/DragonAPI/blob/master/Instantiable/Data/Immutable/BlockKey.java which has no air testing calls at all, so nope, structures look broken.  Probably should be a test in BlockKey, looks like `match` and `matchInWorld` is not specialized for air at all, should test if it is a Block.Air and if so then test if the block it is matching to is `block.isAir` or whatever the test was, so yeah, DragonAPI has a bug there, and there is where it should be fixed.  ^.^
