### ISSUE TITLE
HSLA Steel Scythe has Infinite Durability

### ISSUE THREAD

**Issue by Reignofmagic** [ReikaKalseki/Reika_Mods_Issues#137]
This is the same as issue #88 

I am using the latest available version of Rotarycraft (v7d) and the HSLA Steel scythe has infinite durability. Note I made this scythe in my ME System, I am in survival and I am currently using it to cut down grass in a Savanna biome

Just thought I would let you know, I don't mind this particular bug, but it is a bug none the less.

**Comment by ReikaKalseki** [comment]
I fixed this in v7....

**Comment by Reignofmagic** [comment]
Huh, that is odd because it most definitely has infinite durability for me. The only configs I have changed for rotarycraft are machine volume, and destructive machines block damage set to false. 

Wonder if it might be some odd cross mod bug. See link for a pastebin of my mod-list. If I were to hazard a guess It would be ExtraTic since its latest iterations pulls all metals and makes them tinkers tools even if it doesn't know what to do with them... Although that is just a stab in a very dark room

http://pastebin.com/xyTk70gj

If you want any other information or troubleshooting ideas let me know.

Before picture 
![2015-07-12_01 27 35](https://cloud.githubusercontent.com/assets/10967885/8636702/6fc2620e-2835-11e5-985f-7fe1b9322f82.png)

After Picture (did a large area after doing a far larger area of 3x3 chunks for a large farm I have in mind). All with the same scythe, many flowers and leaves chopped and not a single point of durability damage.
![2015-07-12_01 28 07](https://cloud.githubusercontent.com/assets/10967885/8636700/63bf0598-2835-11e5-857f-0e4835878008.png)

**Comment by ReikaKalseki** [comment]
And now fixed. Again. :P
