### ISSUE TITLE
Plasma Injector MultiBlock missing check for Lower Left Corner

### ISSUE THREAD

**Issue by zemerick** [ReikaKalseki/Reika_Mods_Issues#1371]
https://github.com/ReikaKalseki/ReactorCraft/blob/456e14ac97d60a10585d005305c4c34addaa5f9a/Blocks/Multi/BlockInjectorMulti.java

Lines 101-106 are the check for the lower corners. It is missing the second set, where the - of the offset would check. This allows building a working Injector with only 9, instead of the 18, Lower Corner pieces. ( Confirmed in-game. )

**Comment by ReikaKalseki** [comment]
So add this?

		for (int i = 0; i <= 8; i++) {
			Block b = world.getBlock(x+dir.offsetX*i-left.offsetX, y-1, z+dir.offsetZ*i-left.offsetZ);
			int meta = world.getBlockMetadata(x+dir.offsetX*i-left.offsetX, y-1, z+dir.offsetZ*i-left.offsetZ);
			if (b != this || meta != 1)
				return false;
		}

Done.
