### ISSUE TITLE
Fluid Radiator particles- massive FPS lag

### ISSUE THREAD

**Issue by Zero-ui9** [ReikaKalseki/Reika_Mods_Issues#1374]
![fluid radiator](https://cloud.githubusercontent.com/assets/14851471/23491054/e7b5f69c-fec9-11e6-8afb-ba2fba3b9d03.jpg)

Far too many fluid particles are made (and as a side note I'd suggest changing the particles to be like the RF radiator- just different colours based on the liquid- using the liquid tile texture just doesnt look very good)

**Comment by metnavman** [comment]
It's the same thing that the cobblestone-making plants use. Likely similar coding.

**Comment by ReikaKalseki** [comment]
Reduced somewhat, which is as far as it can go.
