### ISSUE TITLE
Autocrafting unit bug

### ISSUE THREAD

**Issue by roc13x** [ReikaKalseki/Reika_Mods_Issues#1376]
To reproduce:

-Set up a simple AE2 network with a controller, storage chest and crafting CPU. Leave the storage empty.
-Attach an Autocrafting Unit to it, set it to Sustain mode.
-Create an autocrafting pattern for 1 Block of Diamond -> 9 Diamond.
-Put it into the autocrafter, set the sustain amount to 999.

The autocrafter will perform the crafts despite the AE2 network being empty, so you're now getting infinite free diamonds. It seems to work for some recipes, but not all I've tried.

**Comment by ReikaKalseki** [comment]
Hopefully fixed.
