### ISSUE TITLE
java.lang.NullPointerException: Ticking entity when selecting tinker's tool

### ISSUE THREAD

**Issue by therodet** [ReikaKalseki/Reika_Mods_Issues#1377]
Chromaticraft v16d
"java.lang.NullPointerException: Ticking entity", client side only, when I have a Tinker's tool in my hand. First line of the crash report mentions "chromastoneTools", but I do not have any tools made with chromastone.
The crash first occurred after placing two 256x Acceleration Cores next to two Botania Dayblooms.
No mods were updated or reconfigured recently prior to the issue, but it now happens 100% of the time when I try to select a Tinker's tool. I have used NBTExplorer to change my selected item so that I can successfully log back in to my world.
Full crash report: [http://pastebin.com/GDqJS8Bn](http://pastebin.com/GDqJS8Bn)

**Comment by ReikaKalseki** [comment]
This one looks somewhat familiar; try again in v17.

**Comment by therodet** [comment]
Thank you fir the prompt reply. Really looking forward to v17. Any suggestions to try in the mean time? I'm not above some NBT editing, or if Tinker's integration can be disabled...
Thanks for an amazing mod

**Comment by therodet** [comment]
Still happening in v17a :-(
https://pastebin.com/3CaapZee

**Comment by ReikaKalseki** [comment]
One last attempt.
