### ISSUE TITLE
Ticking block entity  java.lang.ExceptionInInitializerError (mod pack) (Chromaticraft)

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1378]
[crash-2017-03-06_16.36.11-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/822594/crash-2017-03-06_16.36.11-server.txt)

v16d 

Not sure how similar this is to the "**java.lang.NullPointerException: Ticking entity when selecting tinker's tool**" issue . . .

**Comment by ReikaKalseki** [comment]
> Caused by: Reika.DragonAPI.Exception.MisuseException: DragonAPI or one of its subclasses or methods was used incorrectly!
The current error was caused by the following:
Cannot create a BlockKey from a null block!
	at Reika.DragonAPI.Instantiable.Data.Immutable.BlockKey.<init>(BlockKey.java:37)
	at Reika.DragonAPI.Instantiable.RayTracer.addTransparentBlock(RayTracer.java:84)
        at Reika.ChromatiCraft.Magic.Network.PylonFinder.<clinit>(PylonFinder.java:437)

https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Magic/Network/PylonFinder.java#L437

Is ExU installed? If so, try upgrading it.

**Comment by lAimBotl** [comment]
yeah its ExU, but latest version still crashes it (ExU v1.2.12)

ha it was the config! now it works. thanks.

**Comment by ReikaKalseki** [comment]
Wait, you had the block disabled? I should probably handle that.

**Comment by lAimBotl** [comment]
was disabled by the pack (I like to add mods to sp packs sometimes, er and buff the configs lol)

**Comment by ReikaKalseki** [comment]
Fixed.
