### ISSUE TITLE
Elemental awareness progression bug (Chromaticraft) (debugtest used)

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1379]
(not much info yet)
Okay, I know for sure I unlocked these before the bug: rainbow forest,magical trees,technicolor trees.

I did /debugtest to repair a completely dead pylon, killed by other world gen had to cycle through every color, the tabs that show up on the top right appeared for all of them, checked nei and all the crystal shards had their names, also got every color on my wand.

![2017-03-09_00 27 55](https://cloud.githubusercontent.com/assets/10777735/23737185/4633b16a-045f-11e7-9080-246fbde2da07.png)

![2017-03-09_00 28 02](https://cloud.githubusercontent.com/assets/10777735/23737187/4abf0658-045f-11e7-8e9f-a9e6d02d25df.png)

I checked in a creative world to see if just rushing to it in debug mode would recreate it, it didn't.

just posting this here in case you want to deal with this, since I doubt most people would find this bug.
will prob see if I can replicate it tomorrow since its 12:00 :) . will prob just cheat past it for now.

**Comment by ReikaKalseki** [comment]
There is no progression bug here. Also, what is that first screenshot?

**Comment by lAimBotl** [comment]
Was showing that I had every color in my wand, yet didn't unlock elemental awareness, last time I did crc I did that to unlock it.
