### ISSUE TITLE
[CC][RC] Client Crash on placing fertility bloom after shearing with Bedrock Shear

### ISSUE THREAD

**Issue by svipthedrunk** [ReikaKalseki/Reika_Mods_Issues#1380]
What have I done:
1. Crafted a fertility bloom (Tooltip shows correct name)
2. placed it on soil
3. sheared it with bedrock shears (I get a tile.ChromaticPlant2.name item)
4. tried to place it again
 --> client crash
Server keeps running. The tile.ChromaticPlant2.name is still in inventory and no object was placed after restarting the client and logging into the server.
Shearing with vanilla shears works without a problem (correct item name).
Enrichment Vine has same problem.

Report:
[crash-2017-03-11_10.46.42-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/835647/crash-2017-03-11_10.46.42-client.txt)

**Comment by Builderb0y** [comment]
#1342, #1311, #1228
