### ISSUE TITLE
Terraformer not working with Buildcraft Markers

### ISSUE THREAD

**Issue by nmarshall23** [ReikaKalseki/Reika_Mods_Issues#1381]
I placed four Buildcraft markers and activated them. Then placed the Terraformer.

In my chat this error is posted:

> DRAGONAPI ERROR: Tile Entity Terraformer @ DIM0: -899, 65, 311 [SERVER] is throwing class java.lang.ClassCastException on update: Reika.DragonAPI.Instantiable.Data.Immutable.Coordinate cannot be cast to java.lang.Comparable

[Here](http://pastebin.com/HFv25j3T) is the full expectation from that was logged on the server.

After when I power it, I am unable to use the Terraformer it doesn't have any titles selected. 

I haven't tried using the Rotarycraft Tile selectors. I've never used it. Buildcraft markers are easier to use.

**Comment by ReikaKalseki** [comment]
Fixed.
