### ISSUE TITLE
"A fatal error has occurred" when trying to join server.

### ISSUE THREAD

**Issue by Thaumcraft4Lyfe** [ReikaKalseki/Reika_Mods_Issues#1383]
Singleplayer works just fine, but in Multiplayer it seems to have problems spawning the Void Monster. I don't think it is an Entity ID mishap, as I use AntiIDConflict and it states that there is no conflict between it and another entity.  The error can be found here - https://hastebin.com/facayagoge.css

I don't see anything that would infer a mod incompatibility, and the server/client configs are the same. I'm not sure why it works SP but not MP.

**Comment by zemerick** [comment]
Can you post the full log please?

**Comment by ReikaKalseki** [comment]
You almost certainly have an ID mismatch. Either modlist differences, or Forge version differences, or something.

**Comment by Thaumcraft4Lyfe** [comment]
Full Client Log - https://hastebin.com/vadelepogu.md

The full server log won't fit, so here's as far as it went back - https://hastebin.com/atatapufah.vbs

There couldn't be mod differences since I copy/pasted the mods to the server (but deleted client-side mods), and both are using Forge 10.13.4.1614 for 1.7.10. The configs are also the same since I copy/pasted them too.

**Comment by ReikaKalseki** [comment]
That log contains no new information.

**Comment by Thaumcraft4Lyfe** [comment]
Sorry for the late response, but I finally got a full log! It's a horrible chunk of text, but here it is. https://paste.ee/p/wfYkZ

I even installed ServerSync, a mod that syncs client and server config, and got the error still. What would be causing the ID mismatch?

**Comment by OvermindDL1** [comment]
> java.lang.RuntimeException: Could not spawn mod entity ModID: VoidMonster EntityID: 24 at ( 2857.5,-3.0, 2666.125) Please contact mod author or server admin.

So, yes, your configs are not in sync with the server, you need the configs to be in sync.  ServerSync is not something that is really useful, at all.
