### ISSUE TITLE
Issues with fluid link anchors

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1385]
hi,
First of all could we have a way to tune down the laser show created by just having a few fluid link anchors around ones base?
![2017-03-21_20 39 27](https://cloud.githubusercontent.com/assets/5174562/24168435/6fb8a0ca-0e7a-11e7-9f57-374eda4142bc.png)
I would prefer if the lasers only showed when it is actually transfering something, or maybe while one is selected by the player.

While we are it, could the selection hit box for the fluid link anchor be the same as it's collision size? I keep breaking them because I expect to be able to interact with the block "behind" them.
![2017-03-21_20 40 08](https://cloud.githubusercontent.com/assets/5174562/24168541/d80fbcd0-0e7a-11e7-99bc-43627c157252.png)
Please make them more like levers/torches and less like chests or full blocks in terms of selecting them.

Thank you.

**Comment by ReikaKalseki** [comment]
Their hitbox *does* change to that of the orientation, but MC engine limitations mean that it will not match until triggered to do so (such as interacted with).

**Comment by Turmfalke2** [comment]
I am not sure I am following, you are saying the first time I open their gui (interact with them) their hotbox changes? I am pretty sure this is not the case, because every time I place one the first thing I do is configure them.

**Comment by OvermindDL1** [comment]
> I am not sure I am following, you are saying the first time I open their gui (interact with them) their hotbox changes? I am pretty sure this is not the case, because every time I place one the first thing I do is configure them.

I've seen the exact same thing, their 'hitbox' is a not 'quite' a fullblock but it is close, only a couple of pixels from the edge, that mixed with their selectionbox is not more tightly around the actual fluid link it makes it difficult to interact with the block they are on (plus I've repeatedly destroyed them on accident by trying to break other blocks around them...).

https://github.com/ReikaKalseki/ChromatiCraft/blob/e26e8fb75fa60607238fe205ecea6766a2dcb672/TileEntity/Transport/TileEntityFluidRelay.java#L308-L312 looks correct, so I'm wondering why it does not come in further from the edge...

But yeah, I have broken many-a-fluid-link by trying to break a block, say, above them when the cursor was no where near the visible fluid link itself, it definitely does not 'fit' right.

**Comment by ReikaKalseki** [comment]
I fixed the hitbox issue (it is the same as #1414), but I cannot make the lines only render when transferring fluid (nor would that have a particularly large effect on the visuals, given the high rate of checking). I can, however, make them fade or alternate to become less of a mess.

http://imgur.com/O3Jv4Vb
![](http://imgur.com/O3Jv4Vb)
