### ISSUE TITLE
[Suggestion] Config option to enable / disable various mod / energy system integrations

### ISSUE THREAD

**Issue by wormzjl** [ReikaKalseki/Reika_Mods_Issues#1386]
Through I imagine this can be a massive work

**Comment by ReikaKalseki** [comment]
This is never going to happen.

**Comment by wormzjl** [comment]
any reasons?

**Comment by ReikaKalseki** [comment]
Complexity, slippery slope of that triggering requests for similar configs for native features, slippery slope of version-agnostic handlers.
