### ISSUE TITLE
Chromaticraft - moving player progress from online to offline mode

### ISSUE THREAD

**Issue by dieselfuelonly** [ReikaKalseki/Reika_Mods_Issues#1387]
When changing a server from online to offline mode I was wondering how I would move player progress.  Changing the playerdata user IDs apparently isn't enough - the player seems to maintain the majority of their progress, such as in the Lexicon and their research progress that can be checked with chromaprog debug - however, the users ability to break and use their structures is removed.  What needs to be updated/changed with the new offline mode user ID?

**Comment by ReikaKalseki** [comment]
It will not work, and cannot work.

**Comment by OvermindDL1** [comment]
@dieselfuelonly For more detail, the tile entities of the blocks would likely have to have the owner ID changed (guessing they are stored on the TE's, if not then where-ever they are stored if stored in a cache elsewhere), you could do that via a world NBT editor, but it will be slow going unless you make a script for it.

**Comment by dieselfuelonly** [comment]
Ok, thanks.  I away from home and don't always have access to the internet and was hoping to be able to play my world.  Thanks for the replies.
