### ISSUE TITLE
Pipes bursting when connected to CrC crystal tanks

### ISSUE THREAD

**Issue by dieselfuelonly** [ReikaKalseki/Reika_Mods_Issues#1388]
Once I get enough fluid inside CrC crystal tanks, RoC pipes burst when connected, either to the bottom or the top of the tanks.  Bedrock pipes would work for normal liquids, but not for jet fuel, etc.  What about making fuel lines, lubricant hoses and the other various non-standard fluid pipes upgradeable to a bedrock tier that could withstand unlimited pressure?

**Comment by ReikaKalseki** [comment]
I will make bedrock pipes be able to carry the fluids normally reserved for hoses and fuel lines.
