### ISSUE TITLE
Chromaticraft + Mystcraft: Wrong plants in Single-Biome Ender Forest world

### ISSUE THREAD

**Issue by kutschkem** [ReikaKalseki/Reika_Mods_Issues#1390]
I'm on V14d of Chromaticraft, but scanning the changelog didn't reveal any related fixes in newer versions as far as I can tell. I have created a single-biome Ender Forest world with Mystcraft, but the plants there are not Resonant Clover and Ender Flower, I find instead Aura bloom, Elemental bulbs, and vibrant pods.

Mystcraft version is 0.12.3.03

**Comment by ReikaKalseki** [comment]
Those are not biome-specific plants, and thus will spawn with the appropriate page. If the others do not spawn, you either lack the page (if one exists) or they simply were coded to spawn in the overworld only.
