### ISSUE TITLE
Casting Delegate won't craft Crystallin Stone Bricks

### ISSUE THREAD

**Issue by tristanrussell2000** [ReikaKalseki/Reika_Mods_Issues#1391]
Casting delegate is set up properly with connection to ME network and works for other recipes. When I try to craft Crystalline Stone Bricks, it places the Crystalline Stone wrong in the casting table and doesn't craft.
![2017-03-25_23 10 45](https://cloud.githubusercontent.com/assets/5078332/24329114/4aa81204-11b1-11e7-937f-43da555cfb18.png)
![2017-03-25_23 10 50](https://cloud.githubusercontent.com/assets/5078332/24329113/4aa5de1c-11b1-11e7-99d7-5db3128383ac.png)

**Comment by ReikaKalseki** [comment]
Fixed.
