### ISSUE TITLE
Nether Freeze

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [ReikaKalseki/Reika_Mods_Issues#1392]
I was throwing together a bunch of mods to see what worked together and what didn't. I found out Magic Bees conflicted with ChromatiCraft worldgen and caused the game to freeze when entering the Nether for the first time, so I removed Magic Bees and without it the Nether generates properly. However, if I add ChromatiCraft back in the Nether starts lagging a short time after entering it and pretty soon it freezes again. One thing I noticed is that adding ChromatiCraft back into the pack considerably increases the amount of memory needed to generate the Overworld and even moreso the Nether without running into an out of memory error. Also, Minecraft seemed to be either re-rendering or re-generating chunks that were within my FOV after they had already been generated. Even if you can't fix this it would still be much appreciated if you could give me clues as to what mod conflict is causing this. I don't know if this is the correct information to provide but here is my MultiMC log:

[ChromatiCraft Nether Freeze MultiMC log 1 2017-03-26.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/871056/ChromatiCraft.Nether.Freeze.MultiMC.log.1.2017-03-26.txt)

**Comment by Thaumcraft4Lyfe** [comment]
Chromaticraft adds a lot of worldgen, especially with pylons. It also adds a complete new area to the nether located above the bedrock.
