### ISSUE TITLE
Chromaticraft crash with certain Tcon config settings

### ISSUE THREAD

**Issue by aurumvorax** [ReikaKalseki/Reika_Mods_Issues#1393]
Crashlog http://pastebin.com/AbZKRwab

This crash occurs when Tcon is present, but the Smeltery is disabled through TinkersModules.cfg.
I assume this is because Chromaticraft is registering something in the smeltery, without checking that the smeltery is actually enabled, just that Tcon is present.  A bit of an edge case, I know, but at least it should be easy to fix :)

**Comment by ReikaKalseki** [comment]
Fixed.
