### ISSUE TITLE
Cant get lumen beacons to transmit lumens / connect to the  repeater network

### ISSUE THREAD

**Issue by Kannei** [ReikaKalseki/Reika_Mods_Issues#1394]
Felt like testing the lumen beacons to see how they worked, but so far they dont work at all. Considdering the text describes them as practical, i dont see them - not working with how I have set it up - to be intended. First with 2 that do have a clear line of view (not that you can see them as they are 2k blocks apart). and are at the exact same Y level. But they are at a approx 45 degree angle to eachother. Didnt connect.

Then seeing as how the multiblock structure is contructed, with that angle the beacon blocks cant "see" eachother. So i placed a third beacon in a straight line north from 1(so same Z coardinate) and a straight line(with a 5 block or so offset, but almost same X coardinate) west  from the other, then the beacon blocks can "see" eachothers. Asumed that should work - but no. So eigther ther eis 0 logic here or they are bugged - not working. all 3 beacons is on the same y level and have line of sight

Im playing on Revolution 3 on 3.5.0 so on chromaticraft version v16d.

**Comment by ReikaKalseki** [comment]
They have been redesigned in the next version. Try them again then.
