### ISSUE TITLE
NoClassDefFoundError - mystcraft is not installed

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1395]
hi,
I just blew up a repeater (one of the wooden ones) when suddenly my game crashed.
Here is part of the log: https://pastebin.com/AnJKRcj9

It seems like it is expecting to find a mystcraft class, but mystcraft is not installed and during the start of the modpack DragonAPI even reports that:  

[31/3/2017 16:39:58 PM] [Client thread/INFO] [FML]: DRAGONAPI: Mystcraft not detected in the MC installation. No special action taken.

E: Restarting the game instantly crashes the game again, looking me out of my world.

**Comment by ghost** [comment]
#1154

**Comment by Turmfalke2** [comment]
Oh alright, requesting new version please :-)

**Comment by ghost** [comment]
Patience.
