### ISSUE TITLE
Rotarycraft models suddenly broken

### ISSUE THREAD

**Issue by Kowalskicore** [ReikaKalseki/Reika_Mods_Issues#1396]
For some reason, the Rotarycraft models suddenly broke for no apparent reason, I can't find an obvious error in the log either.

![2017-04-01_08 46 35](https://cloud.githubusercontent.com/assets/19490808/24576218/22ee3cb4-16b8-11e7-89f3-fb0110478bc4.png)

As you can see, not all blocks are affected. It appears pipes are completely fine while other blocks are completely broken. The other working models are from Reactorcraft, which is fully working.

Here's the log:
https://pastebin.com/Vq8kDTXP

This install only has DragonAPI, Rotarycraft and Reactorcraft, so it shouldn't be a compatibility issue.

I have already restarted Minecraft, rebooted my PC, reinstalled the pack, downloaded DragonAPI, Rotarycraft and Reactorcraft again, reinstalled my Minecraft launcher of choice (ATLauncher) and reinstalled Java. Needless to say, I am stumped.

Minecraft version: 1.7.10
Forge version: 1.7.10-10.13.4.1614-1.7.10
DragonAPI version: V16d
Rotarycraft version: V16d
Reactorcraft version: V16d

**Comment by ljfa-ag** [comment]
Look at the calendar, then you see the reason ^^

It will be like that today and tomorrow.

**Comment by Kowalskicore** [comment]
Ah, okay then.

Now I feel like an idiot for falling for it xD
