### ISSUE TITLE
Rotarycraft Textures missing when installed into FTB infinity.

### ISSUE THREAD

**Issue by arceus179** [ReikaKalseki/Reika_Mods_Issues#1398]
Getting back into minecraft today i installed rotarycraft into my ftb infinity mods like normal. But then i get this. It's impossible to play now, so I really hope it's easy to find a fix. [Picture](https://puu.sh/v6FhB/5a0c51aea3.png)
Edit: I did some checking around and this happens in every version that i install rotarycraft in. Even a clean install of just forge and NEI.

**Comment by ljfa-ag** [comment]
These are the April Fools textures. They will go away tomorrow.

**Comment by arceus179** [comment]
Yea sadly i figured that out a bit too late. Not used to checking closed threads.
