### ISSUE TITLE
Shaft junction does not transmit rotation to next shaft junction (mode - spletting power).

### ISSUE THREAD

**Issue by KonstantinBel** [ReikaKalseki/Reika_Mods_Issues#140]
Shaft junction in spletting power not transmit power to other shaft junction in all directions.
![bag](https://cloud.githubusercontent.com/assets/8530829/8636644/c1b3248a-2886-11e5-988a-8d1ca4de45ef.png)

**Comment by zoteman94** [comment]
I can confirm the shaft junction isn't working properly in v7d. Also the hydro kinetic engines aren't adding torque anymore.
Also, placing the hydro kinetic engine facing away from the junction causes:
![img_20150712_133506](https://cloud.githubusercontent.com/assets/10402786/8639566/f0efd3c4-289a-11e5-9313-33e9bce10157.jpg)

**Comment by ReikaKalseki** [comment]
Do not blend a bunch of unrelated issues into one issue posting.

Also your stacktrace is cut off and thus useless. Post it properly in a new thread.
