### ISSUE TITLE
openAL error if DragonAPI is installed without ChromatiCraft

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1400]
hi,
When I start minecraft with just forge and DragonAPI I get the following openAL error:
https://pastebin.com/GXZZ1XhD

This prevents sound from being played and eventually crashes the game.

If I additionally add Rotarycraft the same thing happens, however adding Chromaticraft appears to fix it?

versions:
forge-1614
DragonAPI 1.7.10 V16d

**Comment by ReikaKalseki** [comment]
Does this happen reliably? I imagine something like this would have been reported by now.

**Comment by Turmfalke2** [comment]
I agree, but I can reproduce it reliably. I suspect it is something load order depended. I only found this bug when I was trying to reproduce another in a minimal setup.

**Comment by ReikaKalseki** [comment]
I cannot do anything about an error I have never seen and for which there is no information.
