### ISSUE TITLE
Freezing when loading world

### ISSUE THREAD

**Issue by Lucas0231** [ReikaKalseki/Reika_Mods_Issues#1401]
Hi,

Today, I installed Chromaticraft with Dragon API. After installing the mod, I launch my game, but I have a freeze when I try to open a world or create a new, I have just a freezed black screen and the interface.

I tried to remove Chromaticraft and my problem is 

PS : Sorry for my bad english, is not my language...

**Comment by OvermindDL1** [comment]
You really should supply the log file, hard to know what the issue is without it.

**Comment by zemerick** [comment]
It's been over 2 weeks without a response. Closing this until the logs are posted.
