### ISSUE TITLE
texture loss in crc book with draconic armor (Chromaticraft)

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1402]
without draconic armor:

![2017-04-05_22 20 15](https://cloud.githubusercontent.com/assets/10777735/24734930/3bdbb60e-1a4e-11e7-8e02-3764bf3a779e.png)

 with draconic armor:
![2017-04-05_22 20 24](https://cloud.githubusercontent.com/assets/10777735/24734944/4fee1a4c-1a4e-11e7-9d07-57cb47e414e5.png)
![2017-04-05_22 20 59](https://cloud.githubusercontent.com/assets/10777735/24734946/526b7fa8-1a4e-11e7-9468-b0dce9a90dba.png)

**Comment by ReikaKalseki** [comment]
I have seen this (very rarely); it is probably an OpenGL state issue on the part of another renderer (eg the armor), and not the lexicon renderer.
