### ISSUE TITLE
Delay and Fallout of world loading into server with major rotarycraft base.

### ISSUE THREAD

**Issue by sk1tt1sh** [ReikaKalseki/Reika_Mods_Issues#1404]
Mods:
RotaryCraft 1.7.10 V16d
ReactorCraft 1.7.10 V16d
DragonAPI 1.7.10 V16d

Okay I'm not 100% sure this is rotary/reactorcraft but it's very likely. The issue is a base that is not chunk loaded if the user logs off for some extended period of time (at least 12hr) and then logs back it the chunks take forever to load (falling out of the world, and timeout disconnects happen) and using "/kill @e[type=Item]" seems to help. Typically though just brutforce log-in-log-out-log-in seems to get everything to load.

It is not being chunk loaded due to safety issues (nuclear reactor etc). 

Block types:
~150 shafts (diamond)
~40 bevel gears
~15 shaft junctions

~300 liquid pipe
~50 fuel line
~150 lubricant line

5 stage turbine
10 block reactor w/ccontrol & 4x control rods (Rods stay in until needed)

I remember seeing a YT video that mentioned something about reactors being chunkloaded. Is this that situation?

There's an AE2 system with a few dozen i/o buses and such but it's nowhere near an advanced level AE2 system.

**Comment by ReikaKalseki** [comment]
Reactors *need* to be chunkloaded. You likely have a neutron pileup.
