### ISSUE TITLE
[Feature Request] Peace Broker config

### ISSUE THREAD

**Issue by Kataiser9** [ReikaKalseki/Reika_Mods_Issues#1405]
I humbly request a config option to move Peace Broker to the Endgame or Elemental Mastery tiers.

It's great that your mods offer extreme power for the right price, and Peace Broker's placement is great for the average modpack, where mobs are mostly just obnoxious. However, this ability is a problem in more survival-oriented packs (e.g. Revolution), where protecting yourself from mob attacks is a major part of the game - a major part which can be completely bypassed once you hit CrC midgame. It's not a matter of "this is a tool that makes it easier"; it straight-up makes that aspect of survival irrelevant at a relatively early stage.

I realize that playstyle may not be your cup of tea, but adding a config like this would be really nice for survival-y packs (and I imagine it would be easy to implement.)

**Comment by ReikaKalseki** [comment]
Peace Broker is not midgame, and the progression system is not designed to be flexible; moving entries around has a very high risk of creating dependency loops.
