### ISSUE TITLE
Redstone Pump + Redstone Signal = Crash

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#1408]
Log Upload: [http://paste.atlauncher.com/view/46c936f7](http://paste.atlauncher.com/view/46c936f7)

DragonAPI: v16d
Expanded Redstone: v16b

When placing a redstone pump and giving it a redstone signal, the server (and client in SSP) crashes completely.  This was tested by placing a pump, and activating a vanilla lever next to it.

**Comment by ReikaKalseki** [comment]
Fixed.
