### ISSUE TITLE
Chromaticraft - memory leak

### ISSUE THREAD

**Issue by CaptClockobob** [ReikaKalseki/Reika_Mods_Issues#1415]
So, I just installed Chromaticraft in my modpack, and was playing for about an hour with no problems. Eventually, I decided to look for a pylon, and after finding one, my frame-rate dropped drastically, my memory usage skyrocketed, and my game froze. I am positive that it is Chromaticraft.

Modlist:
http://i.imgur.com/rlCa2m3.png

**Comment by OvermindDL1** [comment]
Hard to tell the cause without a trace, can you hook up a memory profiler and cause that issue again?

**Comment by CaptClockobob** [comment]
You mean like Opis? I can try. I've never used Opis before though...

**Comment by zemerick** [comment]
No, you'll need some sort of java profiler.

**Comment by CaptClockobob** [comment]
Any specific one?

**Comment by ReikaKalseki** [comment]
I use VisualVM.

**Comment by CaptClockobob** [comment]
Well, I tried. The game freezes when I try to profile it with VisualVM. I tried running a new instance with just Chromaticraft, but was unable to reproduce the problem. It must be in conjunction with another mod.
