### ISSUE TITLE
Exception in server tick loop  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by UltraVolta425** [ReikaKalseki/Reika_Mods_Issues#1417]
Hey

I recently managed to build the whole Reika's reactorcraft fusion reactor, and as soon as everything was built and the plasma was flowing nicely, I continued building on my single player map on 1.7.10. After a while, however, the game crashed. The game starts - if I load a backupsave - but after a few minutes, I always get the crash report linked here.
I tried removing Coak Oven blocks using MCedit, seeing as that generated a problem in another issue, but to no avail.

`https://pastebin.com/wMSj8AUf`

Would you please be so kind as to look at it?

**Comment by zemerick** [comment]
Can you paste the full server log with the crash? That one doesn't have any of Reikas code in it, and it doesn't list what the target was.

Also, did you get increasing latency until this happens, or is it fine one second...crash the next?

**Comment by UltraVolta425** [comment]
Hey

Which log is it that I should be uploading? Latest.log, something else?
And also: it's fine one second, crash the next. No latency issues.
It's on a single player map.

**Comment by zemerick** [comment]
fml-client-latest.log should have everything. ( As long as the last time you launched it, is when it crashed. )

The file size should be quite a bit bigger.

**Comment by jstaff62** [comment]
I'm going to report the same issue, but with the log i think you're looking for. I get the same crash, even mentioning the codechicken chunkloaders. I start the reactor, then after more or less a couple of minutes the game goes from running seemingly fine, to instant crash. I removed all chunkloaders in the area, but if that is the problem then that didn't work, and would suggest having them anywhere in any dimension would cause a crash. my suspicion is that the toroids or another component is chunkloading like a fuel core and clashing with the chunk loaders, but obviously you'd know better than me, so here's the full log from the last time this happened:


[2017-07-18-4.log.gz](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1164636/2017-07-18-4.log.gz)

It's a custom pack so all mods are always the latest versions

**Comment by OvermindDL1** [comment]
```
[05:39:20] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 7/18/17 5:39 AM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
	at codechicken.chunkloader.PlayerChunkViewerManager.update(PlayerChunkViewerManager.java:103)
	at codechicken.chunkloader.ChunkLoaderEventHandler.serverTick(ChunkLoaderEventHandler.java:26)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_532_ChunkLoaderEventHandler_serverTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
Looks like a crash in `codechicken.chunkloader`?

**Comment by jstaff62** [comment]
Then why does it only ever come up while the fusion reactor is on? I've never had an issue with them otherwise,

**Comment by jstaff62** [comment]
I don't even know if it's worth posting to Chicken-Bones' github since he's not working on 1.7.10 anymore. I see lots of issues with crashes, but these are at best a year old. if it is just a CodeChicken bug then something the fusion reactor is doing is definitely triggering it.

**Comment by jstaff62** [comment]
Posted to his github anyway just to be sure. Again I doubt he will want to go back but whatever. If neither Reika or Chicken-Bones are able to resolve it then I guess I'll try uninstalling ChickenChunks and replace it with RoC chunkloaders.

**Comment by OvermindDL1** [comment]
Just for further note:

This 'could' be exacerbated by Rotarycraft fusion reactor, maybe it is calling chunk load registration during an unexpected callback or so, but regardless this:
```javascript
java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
	at codechicken.chunkloader.PlayerChunkViewerManager.update(PlayerChunkViewerManager.java:103)
```
Absolutely without a doubt is a bug in codechicken.chunkloader.  This error is caused by iterating a Java Collection (I.E. having an instanced/unfinished iterator) and they are (allowing) mutating the array somehow (adding/removing elements) during the iteration.

The most simple example is just iterating an array and removing the elements you are iterating over, you will get that same error.  In reality this error is often caused far deep down the stack, you are iterating a collection, calling callbacks with the elements, then some callback down in the stack tree modifies the collection (adding/removing elements), then when it returns and the iterator is attempted to have `.next()` (implicitly by `for` most of the time) then it will throw that exception because the underlying collection was mutated.

This is very well documented in the Java documentation.  \*DO\*NOT\*MODIFY\*COLLECTIONS\*WHILE\*AN\*ITERATOR\*IS\*ACTIVE\* kind of thing.

Anytime, and I do mean every-single-time you see a `java.util.ConcurrentModificationException` error in MC it is become some modder does something monumentally stupid.  Always.  It may not always be the mod that the exception is thrown from, it could be some callback registered by 'another' mod that then calls back to mutate it (assuming the interface is documented as "Don't Do That!", otherwise it is the first mods fault), but it is always that 'some' modder had bad code.

**Comment by jstaff62** [comment]
Well i'm not a programmer so I'm not really sure what most of that means, but would it have something to do with my initial assumption that basically both mods are doing checks at the same time and chickenchunks is getting confused and falling flat on its face? either way i got rid of chickenchunks in favour of Reika's chunkloaders so my world is just filled to the brim with rotarycraft now haha. so far all is well now and about half an hour with no crashes has been enjoyed :D thanks for the help! now to figure out how to use all this RF...

**Comment by OvermindDL1** [comment]
> Well i'm not a programmer so I'm not really sure what most of that means, but would it have something to do with my initial assumption that basically both mods are doing checks at the same time and chickenchunks is getting confused and falling flat on its face? either way i got rid of chickenchunks in favour of Reika's chunkloaders so my world is just filled to the brim with rotarycraft now haha. so far all is well now and about half an hour with no crashes has been enjoyed :D thanks for the help! now to figure out how to use all this RF...

Heh, not really confused, rather it is 'assuming' things without enforcing it, and you know what they say about 'assume'.  ;-)

Still though, this might be fixable by the Fusion code, depends on if it does anything related to chunkloading (probably just defer'ing a chunk related call to the next TE tick would fix it), but the original problem still stems from chickenchunks.  ^.^

**Comment by jstaff62** [comment]
> depends on if it does anything related to chunkloading

I'm almost certain the toroid magnets do. got this crash randomly as plasma got to a magnet that was on (or extremely close to) a chunk boundary when starting up

`(ForgeChunkManager.java:343)
	at Reika.DragonAPI.Auxiliary.ChunkManager.forceTicketChunks(ChunkManager.java:124)
	at Reika.DragonAPI.Auxiliary.ChunkManager.loadChunks(ChunkManager.java:105)
	at Reika.DragonAPI.Auxiliary.ChunkManager.loadChunks(ChunkManager.java:111)
	at Reika.ReactorCraft.TileEntities.Fusion.TileEntityToroidMagnet.setActive(TileEntityToroidMagnet.java:166)
	at Reika.ReactorCraft.TileEntities.Fusion.TileEntityToroidMagnet.updateEntity(TileEntityToroidMagnet.java:113)
	at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:498)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`

but yes I too have no doubt now chicken chunks is the culprit, since uninstalling it fixed the issue right away, and also because it's always apparent  just how damn well written and thought out Reika's mods are.

**Comment by OvermindDL1** [comment]
Well that line is:  https://github.com/ReikaKalseki/DragonAPI/blob/master/Auxiliary/ChunkManager.java#L124
```java
		ImmutableSet<ChunkCoordIntPair> ticketChunks = ticket.getChunkList();
```
Which is a fine way to iterate something, however it is crashing on the `getChunkList` call, which is a bit of a wtf there.  I'm wondering if chickenchunks or some other annoyance decided to ASM something there...

**Comment by lAimBotl** [comment]
[crash-2020-06-21_15.16.06-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4810121/crash-2020-06-21_15.16.06-server.txt)

**Comment by ReikaKalseki** [comment]
Why did this get an update today?

**Comment by UltraVolta425** [comment]
I am just as surprised as you are. Suddenly I received an email from some [AimBot] with nothing more than a linked .txt file in it.
In any case, you may consider this thread truly Closed.
