### ISSUE TITLE
Thorium Reactor Piping Issue

### ISSUE THREAD

**Issue by InstantKor** [ReikaKalseki/Reika_Mods_Issues#1419]
Recently I have been mocking up some reactors and started to play around with the Thorium reactor. Something I noticed that was strange that creating the fuel takes the fuel lines to route it out of the fuel enhancer but to input in into the Thorium core it has t o use a normal liquid pipe. The same for the hot beryllium. 

Something else too I can not figure out a way to incorporate the fuel dump valve. Placing the FDV under a Thorium core (which is the  logical location) blocks the liquid pipe that extracts out the hot beryllium.

**Comment by ReikaKalseki** [comment]
It turns out there was an issue where you could not pull fuel out the sides. Granted, that is less sensible than bottom extraction, but if you have a FDV it is your only option.
