### ISSUE TITLE
Rotarycraft industrial coil not properly storing energy

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#142]
This was a problem i noticed first in version 7b and as of the 7d appears to still be a bug. The industrial coil only seems to store the energy amount calculated in the first tick of operation. 
This is the setup i used to test the issue.
![setup](https://cloud.githubusercontent.com/assets/13296811/8639654/2a7ddc5a-289e-11e5-8efb-91a501d65d1f.png) 
I set the creative coil to output at 1024 rad/s and 256 Nm. When the coil is turned on only 13.107 kJ of energy is stored in the coil.
![storedenergy](https://cloud.githubusercontent.com/assets/13296811/8639663/7543bf8e-289e-11e5-8c00-c61a08c6aa8f.png)

The coil outputs this stored energy just fine and when turned off takes in the exact same amount of energy again but does not continue to add energy to its stores. I also tested this with an energy output of 1.024 kW using the same setup and the amount stored in the coil was only 51.20 J consistent with only one tick calculated.

**Comment by ReikaKalseki** [comment]
Not a bug. Coils now have varying torque and power requirements to charge. See the changelogs.

**Comment by Ayepocsz** [comment]
I think the variables need some tweaking as i was only able to decently charge a normal 720MJ coil using i think 1 MW input, nearly all converted to torgue, using 2 16:1 and 1 4:1 gearbox?

Do you have a table or function as such specifications were not given in the changelog?

**Comment by ReikaKalseki** [comment]
There was a 20x factor missing.
