### ISSUE TITLE
Chromaticraft Coloured saplings/leaves/flowers white in inventory GUI after progress view

### ISSUE THREAD

**Issue by jamesb6626** [ReikaKalseki/Reika_Mods_Issues#1420]
Once the Chromic Lexicon's progress page is looked at, a lot of the coloured items in the inventory turn white (in the inventory GUI). This seems to persist through the saving and quiting then reloading of the save, an F3+T reload and a change of resource pack. The only way to fix it so far seems to be restarting Minecraft.

Start (same after just viewing chromic lexicon without viewing progress)
![Start](https://cloud.githubusercontent.com/assets/7932999/25394436/e64a0258-29d5-11e7-9b3e-9e5aa6261e75.png)

Starting creative tab
![Start Tab](https://cloud.githubusercontent.com/assets/7932999/25394574/49c9b8a0-29d6-11e7-9137-8cac16faa73e.png)

Progress page
![Progression Technicolor](https://cloud.githubusercontent.com/assets/7932999/25394654/902d2dae-29d6-11e7-87d7-88fba54f5d95.png)
![Progression Magical](https://cloud.githubusercontent.com/assets/7932999/25394680/a0f7fdf8-29d6-11e7-9840-2ea8279a9dc8.png)

After
![After](https://cloud.githubusercontent.com/assets/7932999/25394777/e2f3663e-29d6-11e7-9beb-62e473259470.png)
![After Tab](https://cloud.githubusercontent.com/assets/7932999/25395697/d8b71e6a-29d9-11e7-8132-59f2a2523ee6.png)

The screenshots and log ([latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/955677/latest.txt): waited for a bit (in case things were happening in background), then has chat messages after the creative tab was looked at (scrolled through), after the progress page was opened, and after the creative tab was looked at the second time, in case that is usefull) are from using only DragonAPI (v16d) and Chromaticraft (v16d).

**Comment by ReikaKalseki** [comment]
That does not happen for me, and the cause is Minecraft's item rendering system ignoring item's specified render colors. This is not my doing.

**Comment by jamesb6626** [comment]
@ReikaKalseki 
I've just checked this creating a fresh minecraft profile (using Curse (now Twitch) desktop app) and downloaded the same versions of those mods using that (just your mods, as above). All of the configs and settings are definitely unchanged from the defaults. Just creating a fresh creative world, opening the progress tab, then opening the creative chromaticraftworldgen tab gives the results seen above
Is it specific to my computer, using the curse client, Java args, ...?
I can reproduce it on an ubuntu install on the same computer (mods installed manually), so is it hardware specific?
I can also reproduce #950 on both windows and ubuntu, and I see that seems to be hardware specific (probably unrelated, but in case that is useful).

It seemed to happen a little differently with a large number of mods installed - it only affected the leaf lexicon pages and only affected the leaf items when being moved in the inventory, as I'm playing with that it will be less annoying. Here's a [latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/964050/latest.txt) (has some biome id conflicts I need to fix) with a debug crash at the end to list the mods and jar names. Probably useless, but in case it helps.
