### ISSUE TITLE
[Chromaticraft Suggestion] Wiping of Chromaticraft Dimension Adjustments

### ISSUE THREAD

**Issue by kingofrunes** [ReikaKalseki/Reika_Mods_Issues#1421]
Greetings Reika! I have a suggestion I'd like to make in regards to how you are currently handling the Chromaticraft Dimension and it regenerating everytime it reloads.

For servers if the generation takes too long and you get booted due to time out you have to start all over with exploring all over again. On top of that there are some puzzles that take way too long to solve. Logging out essentially removes all progress you have made in that puzzle necessitating that you start all over from the beginning of relocating the dimensional core structure and resolving the puzzles.

Is it possible to only wipe the chromaticraft dimension after you leave it through the falling through the void? Or is there some other way in which I can maintain my progress without losing everything cause I need to take a breather or a break.

**Comment by ReikaKalseki** [comment]
The dimension has to be unloaded in order to be safely deleted, and that comes long (in computer time) after the player has left the dimension.
