### ISSUE TITLE
[ChromatiCraft Suggestion] Anti Cheat Locks and Keys Puzzle

### ISSUE THREAD

**Issue by kingofrunes** [ReikaKalseki/Reika_Mods_Issues#1422]
Hey Reika seeing that you put in anti cheat mechanisms on all the other puzzles. Is there a way you can also do the same for the Locks and Keys Puzzle? Currently you can use items like the Staff of the Traveller to bypass the colored doors and thus bypass the entire puzzle by just teleporting through, picking up all the locks as you go and putting them into their proper slots in each section of the puzzle.

Granted currently you do have to at least grab all the locks and put them in their right spots at the end of each section to be able to get at the core. Just thought you'd like to know about it.

**Comment by ReikaKalseki** [comment]
Aside from guaranteeing that the keys end up in the final locations, how does one guarantee that it was solved legitimately?

Also, I thought I blacklisted that item from even being brought into the dimension.

**Comment by kingofrunes** [comment]
The Staff of the Traveller can't seem to go through Ethereal barriers. So I suppose the only way to fix that is to double check that it blacklists the staff of the traveller from being brought in. I'm pretty sure I have the most up to date Chromaticraft but it seems the blacklist isn't being recognized on the server for some reason or another.

Although if you changed the colored locks to be Ethereal barriers but then it would lose the whole telling sign of how to complete the puzzle :(

I did notice that it won't allow the RFTools Porter to be used to teleport. says that you can't teleport in this dimension but the Staff of the Traveller seems to bypass that somehow except in the case of the afore mentioned Ethereal barriers. If it was possible to add w/e is in the Ethereal Barrier code to the elemental locking doors that prevents it from being teleported past with that staff that would do the trick if it's not too difficult to do.

**Comment by ReikaKalseki** [comment]
Hopefully fixed.
