### ISSUE TITLE
[Chromaticraft] Sky Ember and other really Endgame rituals available without appropriate research fragments

### ISSUE THREAD

**Issue by kingofrunes** [ReikaKalseki/Reika_Mods_Issues#1424]
I noticed a bug when it comes to the really late game rituals. I believe these rituals are supposed to be gated behind the CTM stage of progression. However it seems that Sky Ember, Matter Phase, Fabrication Duplication, Piercing Vision all show up in the Enhanced Ritual Table, can be selected and activated without actually reaching the CTM stage. I've completed getting up to solving the last puzzle of the chromaticraft dimension and going through that amazing light show you had there (Which was absolutely amazing. Props to that, but that's beside the point). 

The only progression I haven't done is the Turbocharging one which I believe is the final gating if I'm not mistaken here? Either way these rituals are available to me without me having the research fragments for them and the blank pages aren't giving me the research fragments for them either.

**Comment by ReikaKalseki** [comment]
This is not happening for me; it may have been fixed since v16 was released. Try again in v17.

**Comment by kingofrunes** [comment]
Okay, I would but I just completed Turbo Charging and got the research pages for those rituals anyways :/
Hopefully it is fixed in v17 though.

**Comment by OvermindDL1** [comment]
It was happening for me in v16 as well, in fact I had about 70% of the rituals unlocked the second I had the ritual table, and got the rest sometime later (before I went through the portal) and got them all, then got the researches for each even later.

**Comment by ReikaKalseki** [comment]
So...
