### ISSUE TITLE
RF Transfer Cable connection issue

### ISSUE THREAD

**Issue by Kataiser9** [ReikaKalseki/Reika_Mods_Issues#1425]
RF Transfer Cables will not connect to certain blocks that should accept RF. (Examples: RFTools Dimension Builder, EnderIO Capacitor Banks.) Screenshot [here.](http://image.prntscr.com/image/d3f2afea9bc04777bd2beff8265526f3.png)

I know little about the technical details of Minecraft modding, but I did notice a probable (partial) cause while poking around the code. The RF transfer cable class has this for the "connectsToTile" method:

`		return te instanceof IEnergyHandler && ((IEnergyHandler)te).canConnectEnergy(dir.getOpposite());`

I believe this should also account for IEnergyProvider and IEnergyReceiver, unless this was an intentional design decision, which seems unlikely. This would explain the issue in some cases, like with the Dimension Builder, which is an IEnergyReceiver but not an IEnergyHandler. Still not sure what the deal is with the capacitor bank, though.

I'd test the obvious fix myself, but I don't have a dev environment set up (sorry!).

**Comment by ReikaKalseki** [comment]
This dates to when there was no such thing as IEP/IER, only the IEnergyHandler.

**Comment by ReikaKalseki** [comment]
Fixed.
