### ISSUE TITLE
[ReactorCraft] Fluid Extractor full of Molten Lithium returns bucket of Heavy Water

### ISSUE THREAD

**Issue by ianleeder** [ReikaKalseki/Reika_Mods_Issues#1427]
I set up a Centrifugal Fluid Extractor in the overworld, I can see with WAILA that the tank is full of Molten Lithium.  If I attach a Fluiduct it extracts Molten Lithium.  However if I right-click the Fluid Extractor with an empty vanilla bucket, I receive a bucket of Heavy Water.

This is using v16d.

**Comment by ReikaKalseki** [comment]
Fixed.
