### ISSUE TITLE
[ReactorCraft] Uranium Processor full of LiFBe return canister of UF6

### ISSUE THREAD

**Issue by ianleeder** [ReikaKalseki/Reika_Mods_Issues#1428]
Similar to #1427, I set up a Uranium Processor for LiFBe production.  I can see with WAILA that the tank is full of LiFBe. If I attach a Fluiduct it extracts LiFBe. However if I right-click the Uranium Processor with an empty canister, I receive a canister of UF6.

In addition if there is no Fluorite in the processor, I receive an error message "Tried to access slot 0 which is empty", but I still receive the LiFBe.  I did have Fluorite in there for the first reaction, which may be required to reproduce.

**Comment by ReikaKalseki** [comment]
Fixed.
