### ISSUE TITLE
Problem with industrial coil

### ISSUE THREAD

**Issue by zoteman94** [ReikaKalseki/Reika_Mods_Issues#143]
Hello, I'm having the same issue as #142 
The coils aren't charging even with a gas turbine or creative coil at 16384 Nm and 16384 rad/s.

![img_20150712_183031](https://cloud.githubusercontent.com/assets/10402786/8640904/77bba516-28c5-11e5-8ea5-c2fd09a42828.jpg)

**Comment by kolatra** [comment]
Please do not create duplicate issues. You may post that you are still having this problem on the original thread, though I believe this is user error because of recent changes to the coils.

**Comment by zoteman94** [comment]
My bad, I'm new to GitHub and since I cannot reopen a thread I thought that I should make a new thread referencing the other.

I made it because it doesn't seem like user error. I'm giving it 256MW and still doesn't charge. That's more than two times the highest engine's power for the first tier coil.

**Comment by TomeWyrm** [comment]
Torque is the important factor on charging.
http://i.imgur.com/I8C95fG.png

**Comment by Fatmice** [comment]
It would help if the power and torque requirements be documented in the handbook.  People will continue to complain about this issue.  Some math formulas that they can use to figure out the proper charging torque and power.

**Comment by TomeWyrm** [comment]
Even a note that storing power requires progressively more torque might help. Though I'm betting everyone mentioning this is a former user that made an (obviously incorrect) assumption

**Comment by ReikaKalseki** [comment]
> Even a note that storing power requires progressively more torque might help

It does say that.

https://github.com/ReikaKalseki/RotaryCraft/blob/master/Resources/trans.xml#L31

**Comment by Fatmice** [comment]
Clearly it is vague enough that people thinks it is a bug.  Personally, I would just leave a formula or two in place of so many words that eyes tend to glaze over.

**Comment by ReikaKalseki** [comment]
There is no more space; as it is the description completely fills the text box.

**Comment by TomeWyrm** [comment]
That is pretty unambiguous, I'm betting they didn't check the handbook though. Or if they did, they didn't notice the added text

**Comment by ReikaKalseki** [comment]
Nine chances out of ten the handbook has not been read.

**Comment by PedroPerez22** [comment]
I can understand that the power and torque rises over time, I find it more realistic than the previous one, but it's suppossed to do so after one tick?

I connected every engine I have to the coil and they all charged the power output of one tick. I tried putting gearboxes on the engines to build up torque (thinking I may have enough power but not torque).

Although the handbook isn't big enough to show the formulas, can you put it here so we can check if the charge is right? I tried putting gearboxes on the engines to build up torque (thinking I may have enough power but not torque).

Using an AC engine and a 8:1 gearbox it charges up to 6,554 kJ, using a 16:1 gearbox it goes up to 52,429kJ. Putting another gearbox after the 16:1 doesn't build any more power (probably hit the power max of the engine).

Do we need more than the 131 kW of the AC engine to get so little stored power?

**Comment by Fatmice** [comment]
It was stated in another thread the relationship between stored energy, power, and torque applied.

For 2^n J, a power of n^4 W at n^3 Nm must be applied.
For 2^n J stored, if n<5 max torque released is 1Nm, if n=5, max torque released is 2 Nm, else 2^((n-6)/2+1) Nm is the max torque released.

There is also the image linked by TomeWyrm that you did not check before asking for formulas.  Looking at that image, it is fairly obvious why you are getting what you're getting.

**Comment by TomeWyrm** [comment]
You need to pump in 1 megawatt at 32kw of torque in order to fully charge (and risk exploding) an industrial coil.

AC engines produce 131kw. Even at 8,192 nm you're not going to pump much power into a coil. Yes that means that until you get past an AC engine, you're likely going to be completely unable to use a coil.

Try a Hydrokinetic (or two) run through a 16x gearbox for torque. You'll get MUCH better results.

Edit: Note that I could EASILY be reading the graph wrong.

**Comment by PedroPerez22** [comment]
But... to do that I'll need to heat the blast furnace to 1150C and I don't seem to find a way to do that.

In fact, I was trying to store the energy in the coil to heat the blast furnace to make the paddles for the hydrokinetic.

I read that you get 12 \* log2(power) \* log2(torque). I tried connecting a couple of gasoline engines in the nether and got close to it but not enough.

**Comment by ReikaKalseki** [comment]
Also, for those who were not on the IRC, v7 had a bug that made charging coils too difficult.

Basically, the stored power variable is actually 20x larger than is reported, because of tick-based adding rather than second based. All calculations and displays compensate for this, but the requirement formulae did not. This is fixed in v8.
