### ISSUE TITLE
[ChromatiCraft] [SP] Crash on startup

### ISSUE THREAD

**Issue by aking4125** [ReikaKalseki/Reika_Mods_Issues#1431]
When adding ChromatiCraft V16d. The game crashes on startup. Removing Chromaticraft fixes the issue. 

I'm sorry if this problem was posted before. 

https://pastebin.com/SbkhEuYM

**Comment by Armagedon13** [comment]
try re-launch the game

**Comment by ReikaKalseki** [comment]
#481 #661 #1197 #1257 #1280
