### ISSUE TITLE
[Rotarycraft] Fractionation unit works with incorrect ingredients

### ISSUE THREAD

**Issue by ianleeder** [ReikaKalseki/Reika_Mods_Issues#1434]
This is version V16d.

I insert my ingredients into the fractionation unit via an AE2 export bus.  At some point it must have run out of magma cream, and before the next one was crafted another coal got inserted.  I came back and found my fractionation unit like this:
![extra coal](https://cloud.githubusercontent.com/assets/8241300/26227457/0cf6ee72-3c76-11e7-8137-e34b45826e34.png)
And yet it still produces jet fuel when powered.

I fired it up in a creative world, and found that you can have all 6 slots containing the same ingredient, and as long as it's 1 of the 6 required ingredients, it will produce fuel:
![all ethanol](https://cloud.githubusercontent.com/assets/8241300/26227477/26f728b4-3c76-11e7-9fc7-dbfd0bf4860a.png)
![all netherrack dust](https://cloud.githubusercontent.com/assets/8241300/26227506/55991402-3c76-11e7-962e-e409a1c4806d.png)

**Comment by Duckfan77** [comment]
Already reported, and fixed in the new version #1243

**Comment by ianleeder** [comment]
Thanks @Duckfan77.  I don't suppose you know why when I search issues for the keyword "fractionation" that issue doesn't show?
![image](https://cloud.githubusercontent.com/assets/8241300/26231487/e7ff31e8-3c92-11e7-901b-27a47e02a02a.png)

I tried to see if there was already an issue raised, but nothing relevant showed up.

Edit: Ignore.  The linked issue is spelt wrong.  "Fractation"
