### ISSUE TITLE
[v17a] Crash on enter world

### ISSUE THREAD

**Issue by roc13x** [ReikaKalseki/Reika_Mods_Issues#1437]
My game crashes upon loading a world. This includes newly-created worlds.
The only installed mods are DragonAPI and RotaryCraft. Crash only occurs with those two installed.

Report: https://pastebin.com/8r6cHi4t

**Comment by ReikaKalseki** [comment]
This is a new DragonAPI ASM. Are you using the newest Forge? Do you have Streams?

**Comment by roc13x** [comment]
Thanks for the suggestion. Seems its not compatible with the Recommended forge build, only Latest :)
