### ISSUE TITLE
CaveControl config seems to be messed up

### ISSUE THREAD

**Issue by AnrDaemon** [ReikaKalseki/Reika_Mods_Issues#1439]
Comparing to the v16 config, I've found these changes:

## Moved from biomes to global config (which makes sense).
    D:"Stronghold Count"=3.0
    D:"Stronghold Distance Factor"=1.0

## Left in the biome config (which doesn't make much sense)
    B:"Generate Strongholds"=true => "gen_strongholds"

## Disappeared entirely (but probably should have been in biome block)
    B:"Generate Dungeons"=true

Overall, it seems the `B:"Generate Strongholds"` should've been moved to global config, and `B:"Generate Dungeons"` take its place in the biome block.

**Comment by ReikaKalseki** [comment]
Strongholds actually do have per-biome sensitivity. As for the dungeon option, that is because there is a frequency factor instead.

**Comment by AnrDaemon** [comment]
Frequency factor is not the same as enable/disable genration, IMO.

**Comment by AnrDaemon** [comment]
Well, I can divide them by zero, I guess…

**Comment by ReikaKalseki** [comment]
Multiply.

**Comment by AnrDaemon** [comment]
While we're on the topic of config. Is there a command for CC to dump biome ID's for config?

**Comment by ReikaKalseki** [comment]
DragonAPI has /dumpids.

**Comment by AnrDaemon** [comment]
Thanks!
