### ISSUE TITLE
Issue with RotaryCraft and some suggestions.

### ISSUE THREAD

**Issue by anishin** [ReikaKalseki/Reika_Mods_Issues#144]
Hello.
Firstly, thank you very-very much for your work!
Secondly, I have issue with RotaryCraft.
Extractor doesn't works with any ores from mods (but NEI shows, that it can!). I tested in creative with creative industrial coil and BUNCH of power. All vanilla ores extractor processes instantly. Any "common" (not dense or poor) ores from any mods it places in first slot (=> it can process ones), but do nothing!
Should I add all ores from all mods into config file? (I think RotaryCraft should detect ones itself...)
Thirdly, I have some suggestions for your mods.
1) Please, add tooltips in machines and NEI showing type and amount of liquid. Or should I guess these values?)
2) Creating materials with friction heater - it is very intereting mechanic. But using vanilla furnace in mid- and end-game ... is very strange. Maybe you should move these recipes to blast furnace...
3) Please, check new format of CoFH's config files. And change "coolants" to "Coolants", "fuels" to "Fuels" etc.. Otherwise ThermalExpansion will ignore all these values.
4) Add compatibility with other mods' tools (such as screwdrivers and wrenches). I'm tired to carry three or four wrenches and screwdrivers.

And again, great thanks for your work!
P. S. Sorry for my English. I'm from Russia.

**Comment by Fatmice** [comment]
1/ The angular transducer will tell you the amount.  You can also hold tab over the object to see values of the nbt tags.
2/ Blast furnace is not for "common" smelting so moving whatever recipes to it makes no sense.  You don't seem to understand the concept of a blast furnace.  Blast furnace is not an upgraded vanilla furnace.  A vanilla furnace heated with a friction heater can smelt many times faster than without one and also generates xp orbs.  There are other end game furnaces that you can use if you erk at the sight of a vanilla furnace.
4/You can already can use other screwdrivers on the RoC blocks.

**Comment by TomeWyrm** [comment]
Do you have AOBD (Another One Bites The Dust)? If so, that is why your extractor is broken.

1) I would like to second that. It's a rather common GUI convention among tech mods now.
3) Thanks for bringing this one up. COFH recently updated.

2) This one is unlikely to get picked up, the blast furnace is for making special alloys. The furnace heater + vanilla furnace is for smelting things.
4) That would be something to ask other mods. Their wrench needs to support blocks, not the other way around.

**Comment by TomeWyrm** [comment]
If you DO have AOBD?
Change "B:RotaryCraft=true" to "B:RotaryCraft=false" in aobd.cfg

**Comment by anishin** [comment]
Thanks to all for the quick response. I already understood that this is AOBD bug. I fixed it on my modpack ( @TomeWyrm, great thanks!)
Perhaps, for now that's all.

I'll close this issue as soon as suggestion #3 (in first post) will be applied.

**Comment by ReikaKalseki** [comment]
1) is WAILA, not NEI, and it is already handled.

2) No. The Blast Furnace is for alloying or bedrock crafting.

3) I need a log to know what changed.

4) My screwdriver is an omni-tool - aside from IC2 machines which I cannot seem to get working. Use that.

**Comment by anishin** [comment]
@ReikaKalseki 
1) I'm talking about recipes in NEI. For example, I see in some recipes black fluid(s). But what is it? Liquifacted Coal? Oil? Sludge? Or something else? Please, add tooltips for liquids in NEI recipes (in all GUI of machines it's made already).
3) My config file (config/cofh/thermalexpansion/fuels.cfg):

```
##########################################################################################################
# Coolants
#--------------------------------------------------------------------------------------------------------#
# You can add Coolants in this section. Fluid names only, as they are registered in Minecraft. Currently only used by the Compression Dynamo.
##########################################################################################################

Coolants {
    I:cryotheum=4000000
    I:ice=2000000
    I:water=400000
}


Fuels {

    ##########################################################################################################
    # Steam
    #--------------------------------------------------------------------------------------------------------#
    # You can adjust fuel values for the Steam Dynamo in this section. New fuels cannot be added at this time.
    ##########################################################################################################

    Steam {
        I:charcoal=40000
        I:coal=40000
        I:wood=7500
    }

    Enervation {
        I:redstone=160000
    }

    ##########################################################################################################
    # Magmatic
    #--------------------------------------------------------------------------------------------------------#
    # You can add fuels to the Magmatic Dynamo in this section. Fluid names only, as they are registered in Minecraft.
    ##########################################################################################################

    Magmatic {
        I:lava=180000
        I:pyrotheum=2000000
    }

    ##########################################################################################################
    # Compression
    #--------------------------------------------------------------------------------------------------------#
    # You can add fuels to the Compression Dynamo in this section. Fluid names only, as they are registered in Minecraft.
    ##########################################################################################################

    Compression {
        I:bioethanol=500000
        I:biofuel=500000
        I:coal=1000000
        I:fuel=1500000
        I:oil=300000
    }

    ##########################################################################################################
    # Reactant
    #--------------------------------------------------------------------------------------------------------#
    # You can add fuels to the Reactant Dynamo in this section. Fluid names only, as they are registered in Minecraft.
    ##########################################################################################################

    Reactant {
        I:biomass=450000
        I:creosote=200000
        I:glowstone=750000
        I:mobessence=500000
        I:redstone=600000
        I:seedoil=250000
        I:sewage=12000
        I:sludge=12000
    }

}


coolants {
    I:"liquid nitrogen"=40000
}


fuels {

    compression {
        I:"rc ethanol"=125000
    }

}
```

ThermalExpansion ignores last two sections ("coolants" and "fuels"). You should only change names to "Coolants", "Fuels" and "Compression".

**Comment by ReikaKalseki** [comment]
Looking into 3), the code is done via [IMC](https://github.com/ReikaKalseki/DragonAPI/blob/master/ModInteract/RecipeHandlers/ThermalRecipeHelper.java#L21), and neither "coolants" nor "Coolants" is used.

@KingLemming: Has the format changed, and if so, what is the correct IMC format?

**Comment by ReikaKalseki** [comment]
Also, 1) has been implemented.

**Comment by ReikaKalseki** [comment]
According to King, it should work fine as is.
