### ISSUE TITLE
Bedrock pipe issues

### ISSUE THREAD

**Issue by dieselfuelonly** [ReikaKalseki/Reika_Mods_Issues#1441]
Playing with the bedrock pipe updates in v17b I have found a few issues:

1.  Cannot connect to Fractionation Unit
2.  Pipe capacity is a bit... absurd.  Attaching a single piece of bedrock pipe to a max-sized 2 million bucket Crystal Tank full of jet fuel drained approximately half of the fuel out.  Breaking said pipe when it was accidentally placed, well... that hurt :P

Will update this if I run into any other issues as I play with them.

**Comment by ReikaKalseki** [comment]
The second...cannot really be fixed.

**Comment by ReikaKalseki** [comment]
Fixed the first.
