### ISSUE TITLE
Autocrafting Unit Crafts Items for Free

### ISSUE THREAD

**Issue by Brickmastercat** [ReikaKalseki/Reika_Mods_Issues#1442]
I am running the most recent version of Rotarycraft, 17b, and I play with a couple of friends on a server, and we have noticed that the Autocrafting Unit, for some recipes, does not require the necessary materials to craft an item, for example if we have one bedrock alloy ingot, we can make a recipe for a bedrock alloy ingot block, and put that recipe into the unit, and it will craft them from nothing, and this works with many recipes, but not all of them, including recipes for items from other mods.

**Comment by ReikaKalseki** [comment]
I thought I fixed this...

**Comment by ReikaKalseki** [comment]
Fixed.
