### ISSUE TITLE
Fog / blindness effect after visiting the viod in a crystal mountain biome, not going away

### ISSUE THREAD

**Issue by Kannei** [ReikaKalseki/Reika_Mods_Issues#1443]
So I was testing if RFTools generate the outerlands biomes as you do get dimlets for it and made a world with 3 of them including crystal mountains. The dim looks to only generate the crystal mountain so far but it also generate with no bedrock layer at the bottom. That seem to contain  not a normal void and a voidmonster that didnt seem to be able to attack you nor leve the void.
I fell into the void quite far before i activated flight to fly up again.

The issue os that after this I ahve a fog/blindness effect (not a potion effect) that is not going away, including an extra square in the E Inventory GUI thats purpule that when i click gives me a missing texture background inventory GUI of sorts with "Lumen Incineration" headder. And this effect is not going away. Not with a Tahara potion crystal lamp / enhanced pendant or taking a dip in liquid chroma or etherial Luma.

Is this an intended effect that there is a function that removes? if not it seems to be a bug to me. I asume dying wil celar it but....

**Comment by ReikaKalseki** [comment]
Those biomes are not supposed to be available. As a result, any issues caused by them being in RFTools or similar is not worth caring about.
