### ISSUE TITLE
Long time to load NEI usage recipes for some items

### ISSUE THREAD

**Issue by Rongmario** [ReikaKalseki/Reika_Mods_Issues#1444]
In the console, when pressing U on lots of different items in NEI, this is logged:

`[18:53:19] [Client thread/ERROR] [NotEnoughItems]: Error loading recipe: 
java.lang.ArrayIndexOutOfBoundsException`

[https://i.gyazo.com/35892bdd8cecee7834c3bbb65f8d1ad4.png](url)

The first instance of when I press U, it takes roughly 5 minutes or less to load (depending, if its GregTech items, it takes 5 minutes (metadata?))

**Comment by ReikaKalseki** [comment]
#668
