### ISSUE TITLE
Unable to get lumen transmision tower / lumen beacon to form a complete structure V17

### ISSUE THREAD

**Issue by Kannei** [ReikaKalseki/Reika_Mods_Issues#1445]
Had the hope of now lumen beacons works.. but cant even get them to form a structure / activate.
Made it in v 16 and it did form a complete structure, but it have a tendensy or loosing that on server restarts. So then removing the beacon block then placing it again and it is active again. But now in v17 that does not work.

Cant see any changes in its construction eigther so. Tested with both turbocharged beacon + multi repeater and normal once.

**Comment by ReikaKalseki** [comment]
Does it have air around?

**Comment by Kannei** [comment]
yes, its built ontop a tower to get it high enough to have a clear LOS to the other tower thats some 1800 blocks away. There is likely some 9 blocks radius to the nearest block on any side of the tower. 
Sidenote: snow is that structures enemy, as snowfall will prevent it from forming a strucure. Might want to fix that ?

**Comment by ReikaKalseki** [comment]
Fixed.
