### ISSUE TITLE
Lumen Incineration Missing Texture in newest version?

### ISSUE THREAD

**Issue by Thaumcraft4Lyfe** [ReikaKalseki/Reika_Mods_Issues#1447]
I just downloaded the newest version of ChromatiCraft and DragonAPI and now there's an odd purple square in the inventory that leads to a "Lumen Incineration" GUI with a missing texture background. Is this a bug or is there some file I'm missing somehow? http://imgur.com/a/aySPZ

**Comment by ReikaKalseki** [comment]
Already fixed.
