### ISSUE TITLE
Error:. FTB Infinity Evolved MC - 1.7.10 #DragonAPI v17c

### ISSUE THREAD

**Issue by Elianthony** [ReikaKalseki/Reika_Mods_Issues#1448]
`* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (@aeversion@ from DragonAPI 1.7.10 V17c.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:ON, RotaryCraft:ON, RC:ON, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 21.20.16.4534, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.`

Well, I'm Brazilian and I'm using Google Translate ..: D I'm really looking forward to playing Reactor Craft in the FTB Infinity Evolved (1.7.10) mod pack, but it appears this error and does not allow it to start. I discovered your mods today Congratulations on the work, if you can give an attention.

**Comment by ReikaKalseki** [comment]
What you posted is not an error.

**Comment by Elianthony** [comment]
So what is it? Do you have a solution?

I'm sorry if I named or misplaced it, it's my first experience with forums ..: /

**Comment by Elianthony** [comment]
It does not allow the minecraft to start, returning to the FTB Launcher screen, and this is a last message on the console

**Comment by OvermindDL1** [comment]
Need the entire log file results.  Should be something like fml-client-latest.log or so.  You can upload it to, say, a github gist or so.

**Comment by Elianthony** [comment]
Well, I installed antiidconflict, because I saw that maybe the same error happened in this case here:
[https://forum.feed-the-beast.com/threads/reactorcraft-ftb-infinity-1-7-10-crash.112229/](url)

[https://www.reddit.com/r/feedthebeast/comments/45tghc/reikas_mods_wont_launch/](url)

 I'm starting minecraft now, so if I get a conflict I'll get the error log, I'll post it here already.

**Comment by Elianthony** [comment]
I was able to solve the problem, it's the same as the case I mentioned, the ID :. 35 is already used by the witcher for potion.spiked. As I also installed Ars magica 2 the same ID is also used by it causing a conflict with the 3 mods (Rotarycraft, Ars Magica 2 and Witchery) but I changed the IDs by Valid ID's (77 and 80) and it's ready, it was a mistake Simple but very annoying, thanks for the help now I'm going to have fun with the mod.
