### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1449]
Something with Thaumcraft and/or Gadomancy and/or infusion enchanting.

https://hastebin.com/uwonesawug.swift

**Comment by ReikaKalseki** [comment]
This is not on my end.

**Comment by Shahelion** [comment]
The thing is, it didn't happen until after I updated DragonAPI, Chromaticraft, and Geostrata. Probably should have mentioned that first, my bad.

**Comment by ReikaKalseki** [comment]
I do not see how I can be causing a crash in the TC API when another mod is adding recipes...
