### ISSUE TITLE
ReactorCraft handbook Turbine description does not mention lubricant

### ISSUE THREAD

**Issue by thePalindrome** [ReikaKalseki/Reika_Mods_Issues#1451]
The entry for the Turbine in the handbook mentions nothing about requiring lubricant (although it probably should go without saying)

Given the spirit of the mod, I can imagine this was done on purpose. I simply wanted to ensure this was done on purpose.

**Comment by ReikaKalseki** [comment]
I will add it.

**Comment by ReikaKalseki** [comment]
Done.
