### ISSUE TITLE
[CC] Discovering a new color plays the discovery sound twice, slightly offset

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1453]

**Comment by ReikaKalseki** [comment]
Did you also discover pylons?

**Comment by Shahelion** [comment]
It happens with each new color.

**Comment by Shahelion** [comment]
It seems that the first time is just the notification whereas the second is both the notification and the rerendering of the world.

**Comment by ReikaKalseki** [comment]
This is not happening for me.
