### ISSUE TITLE
Electricraft Induction motors counts sources behind Batterys v17a

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1454]
If you charge a battery with 4 Engines you can't use an induction motor, even with tungsten upgrade, without loss, because the motor will count the 4 engines + the Battery as source.

**Comment by Kannei** [comment]
To add to this: If you have 1 source battery that you connect to lower tier batterys via relays  that you connect to motors.(motor is only directly connected to that 1 lower tier battery that gets input energy from a higher tiered ONLY when relay is connected) (this to not loose power) Electricrat count every single battery conncted in that circut as a source for each motor. 

So if you have 5 motors connected to that 1 source battery in this way(via lower tier batterys), None of the motors connected wil not run optimally even with a tungsten upgrade.

**Comment by ReikaKalseki** [comment]
Source counts passing through batteries is probably intentional to prevent the use of batteries to bypass combination limits. However, this is an unintended result.

**Comment by Kobra331** [comment]
Maybe a bedrock upgrade for induction Motors would be useful. Especially in endgame i dont see any reason for a Source limit. If i want to use more than 4 engines i can junction them with Shaft junctions + bedrock upgrade for the same effect but with less comfort and makes Electricraft for this case nearly useless.

And for the midgame: I think the battery ingredients are enough progression controlling. For the 1 MW-Battery I need an inductive ingot which needs an pulse jet furnace on that state of progression i can use a gas turbine which produces 63 MW of power. 
So i think its ok for the progression if i want to charge my 1 MW battery with 24 Wind turbines for fanciness/style even if i could use a gas turbine.

greets :)

**Comment by ReikaKalseki** [comment]
I added a bedrock tier upgrade to the motors which raises the limit to 1000.
