### ISSUE TITLE
Blindness From Void Monster Does Not Go Away

### ISSUE THREAD

**Issue by InstantKor** [ReikaKalseki/Reika_Mods_Issues#1455]
Whenever I get near the void monster my character gets blinded on the latest version. In the past when the void monster touched the character blindness would occur but now this effect happens when just in the presence of the void monster. In addition to this the darkness does not go away unless the client relaunches the game, there is no potion timer either.

**Comment by ReikaKalseki** [comment]
Is this true blindness or the normal distance and black fog that happens whenever you look at it?

**Comment by InstantKor** [comment]
Its both of them, but the negative potion effect timer not appearing was due to the Taharara Potion pendent.  Another observation I noticed was that the blindness (one with a timer) does go away on its own but if you teleport away while under blindness the timer ticks away but the effect stays. Now the darkness that lets you see the surrounding with a 1 chunk range does not go away at all.

**Comment by erplsf** [comment]
Can confirm having same issue, one chunk radius vision stays even in Overworld. Restarting helps.

**Comment by gr8pefish** [comment]
Can confirm this happened to me as well.

**Comment by Kannei** [comment]
Addendum:
It just so happened that I was traveling in the overworld on the surface while another player on the server was on the nether roof and triggered hte void mosnter coming to him.. before it even reached him in the nether... the "ghost" voidmonster that sometime shappens to appear in the overworld came to me and gave me the blindness that does not go away unless I restart the clinet.

Sooo there seem to be 2 bugs in this. 1: you get a perma blindness and 2: the vodimonster glitches up to the overworld surface and is not just a visual glitch as that too gives you perma blindness. The void monster i "encountered" in the overworld surface did not damage me however, but the blindness efect did.

**Comment by DracoScythem** [comment]
Persists on v18a - get to close to the VoidMonster and ones Range of View is reduced to ~4 Blocks until the Client is restarted (no Blindness Potion Effect, only the black Fog).

It also seems that getting to close due to the chunk taking longer to load than expected will trigger the fog aswell.

**Comment by Kannei** [comment]
Addendum 2:
So i view this as connected/corrolating. I went to the nether roof to explore the buildings, did not encounter the voidmonster. However - I did get a redused vision range still also noticed that a view blocker got activated that made it so visual effects like journeymap weypoint markers and the sun and stars is blocked out when looking directly at them and i do not see the skycolour at all but do see the fog colour and night stars..

So it does seem that something messes with your view merely by going to the nether roof that does not go away when exiting? 
However asking Ignotis he have gone there without encountering it and it then did not happen to him. So could be I triggered it but didnt notice/look at it?

**Comment by ReikaKalseki** [comment]
Nothing I could do would reproduce the issue:
https://www.youtube.com/watch?v=tPYntTQDdz8

**Comment by DracoScythem** [comment]
Turns out I didn't properly clean out my Testing Environment... >.<
It is being caused by FastCraft - its' culling feature to be precise...
Although I'm not sure why that causes the VoidMonsters visual effects (and no others) to go haywire - culling bugs generally tend to make things _disappear_ o.O

**Comment by ReikaKalseki** [comment]
Well, we finally have a cause. And it is nothing I can do anything about.
