### ISSUE TITLE
DragonAPI V17C crashes the game on world creation

### ISSUE THREAD

**Issue by TheEnemyCube** [ReikaKalseki/Reika_Mods_Issues#1457]
As the title states, when I try to create a world while 'DragonAPI 1.7.10 V17c.jar', and only that, nothing else, is in the mods folder, the game displays 'Loading World' for about a second before crashing directly back to the launcher to display this error.

The game crashed whilst exception in server tick loop
The game crashed whilst exception in server tick loop
Error: java.lang.VerifyError: Expecting a stackmap frame at branch target 259

This does not occur when the .jar is not in the mods folder, and continued to happen after a fresh reinstall of minecraft and the appropriate 1.7.10 minecraft forge version. Speaking of forge, if it's at all relevant, the thing below the play button says 'forge-1.7.10-10.13.4.1558-1.7.10', in case that has some sort of use to help troubleshoot.

A link to the crash log can be found [here.](https://pastebin.com/PbR6syWS)

I'll be honest, this is my first foray into trying to mod Minecraft in the past few years, so I'm probably missing something incredibly obvious. I'd appreciate any help I can get, even if it's just something along the lines of 'you idiot, you need to do x and then x', or 'you need to put x in folder x'.

**Comment by ReikaKalseki** [comment]
Update Forge.

**Comment by seemuth** [comment]
What version of Forge is required? The newest (10.13.4.1614 as of this comment)?
**For future visitors: 10.13.4.1614 indeed works.**

**Comment by TheEnemyCube** [comment]
Ooh, that explains it. I was running the recommended version, fairly sure I saw a different version with a higher number, but I wasn't sure if it'd be safe to run it. Thanks for the assistance nonetheless!
