### ISSUE TITLE
crash wish  Superflat

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#1458]
[crash-2017-05-31_11.06.51-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1040251/crash-2017-05-31_11.06.51-server.txt)
del tofucraft
[crash-2017-05-31_11.18.00-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1040250/crash-2017-05-31_11.18.00-server.txt)
[crash-2017-05-31_11.27.37-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1040252/crash-2017-05-31_11.27.37-server.txt)
at 16d nothing

**Comment by ReikaKalseki** [comment]
Fixed.
