### ISSUE TITLE
[V17c]Essentia Relays sending visual rays when they shouldn't

### ISSUE THREAD

**Issue by kutschkem** [ReikaKalseki/Reika_Mods_Issues#1459]
I don't think that's intended:

![chromaticraft](https://cloud.githubusercontent.com/assets/1106888/26691436/5c09c8a4-46fd-11e7-9599-e6dfabe5f470.png)
![chromaticraft_2](https://cloud.githubusercontent.com/assets/1106888/26691438/5c0f871c-46fd-11e7-85fe-4f36af033435.png)

The alchemical construct isn't crafting anything, still the rays show up. After i break the middle relay (only the one on the alchemical construct left), rays go between the two ignis jars. They go away when I break the relay on the construct. This problem can be reproduced without having one of the nodes on the constructs. The "left-over" rays work for jars other than ignis, too, given they contain the same essentia.

**Comment by ReikaKalseki** [comment]
They will send between filtered jars if one is not full, as it is trying to fill them from some source. There is no way around this.

**Comment by kutschkem** [comment]
Hmm imho this could be solved by taking into account the suction of endpoints in EssentiaNetwork.removeEssentia, or do I miss something? Actually, now that I see your code, you even have a SuctionComparator, but I don't see where it is used?

**Comment by ReikaKalseki** [comment]
The essentia relays work differently than pure suction. Notably in this case, they try to fill any labelled jars in range, pulling from any valid source.

**Comment by kutschkem** [comment]
Ok I guess I can just take away the label from the second jar then.
