### ISSUE TITLE
[1.7.10] ChromatiCraft V17c Crafting-Room (Bug?!?)

### ISSUE THREAD

**Issue by accessdenied0** [ReikaKalseki/Reika_Mods_Issues#1461]
Hello everyone...

I normally don't do that because it actually might not belong here, but I'm a bit desperately... I searched in Google and tried to troubleshoot this.

I'm unable to setup a Crafting-Room (maybe a Temple too but I can't get there)

I have all the required knowledge, didn't cheat anything, replaced it entirely used runes and not and build the required setup... BUT it doesn't work. It doesn't even seem to recognise the structure (only one Diamond is lit). 

Setup:
http://imgur.com/a/edaNe

Can someone say what I'm doing wrong? Or is it a bug at the end? I'm so sorry if is just a simple thing.

access_denied

**Comment by DragGon7601** [comment]
The issue can be seen in the second picture. You say "only one Diamond is lit". But the second diamond isnt just unlit, its not there! This means you haven't used that table enough. You need to make more stuff on that table. It will eventual make a different sound and a second diamond will appear. If it isnt part of the structure then the diamond will be crossed out. If it is part of the structure and the diamond is still crossed out, try braking and putting the table back down (it may just need to refresh its self).

Best of luck.

**Comment by accessdenied0** [comment]
@DragGon7601 Thank you for your help, but I have a question:
How much or what do I have to craft exactly? I pretty much crafted / casted all "Basic-Crafting" (because it is the only possible and highest crafting tier I have available) up and down... I do not get the feeling of any progress... (and it didn't changed the number of diamonds)

Edit: never mind... after crafting a lot of stuff it upgraded... The only thing I have to critic here that there are no hints you have to do that... but well... it was my fault.

Thank you alot @DragGon7601

**Comment by OvermindDL1** [comment]
> Edit: never mind... after crafting a lot of stuff it upgraded... The only thing I have to critic here that there are no hints you have to do that... but well... it was my fault.

There really should be some kind of indicator.  Not like an XP bar for the table or so, but perhaps if you hover the mouse over the diamond row then it says something like "Need to craft more on this table to learn how to use it better" or "Need a casting temple to activate" or something...

**Comment by ReikaKalseki** [comment]
> There really should be some kind of indicator. Not like an XP bar for the table or so, but perhaps if you hover the mouse over the diamond row then it says something like "Need to craft more on this table to learn how to use it better"

People are expected to actually use the items available to them, not ignore them in a rush to some later-game tool.

**Comment by OvermindDL1** [comment]
> People are expected to actually use the items available to them, not ignore them in a rush to some later-game tool.

One thing that happened was an explosion that destroyed my table (friggin mobs...) in my playthrough (I was already at the chroma-dimension).  I had to make a new table, then alter my temple for 'each' level as I had to work it back up (would be nice of lower-experienced tables could use higher-level crafting temples and so forth).

So yes, sometimes we do try to rush it, after having already built everything we could up to that point (many times in many cases).

**Comment by accessdenied0** [comment]
Didn't expect to get a discussion this big out of my mistake...
Well... I just can tell why this happened to me: 
I explored some Structures in the Nether and Ocean got a lot fragments and obtained a lot of the necessary Casting-Room materials (Crystal Stones) from 2 Villages... 
At this point the Casting Room was available for me and I didn't had to use other kind of Castings. 
(Except the Pylon Compass). There was no need (imo) to this time...

**Comment by ReikaKalseki** [comment]
> One thing that happened was an explosion that destroyed my table (friggin mobs...) in my playthrough (I was already at the chroma-dimension). I had to make a new table, then alter my temple for 'each' level as I had to work it back up (would be nice of lower-experienced tables could use higher-level crafting temples and so forth).

> So yes, sometimes we do try to rush it, after having already built everything we could up to that point (many times in many cases).

This is a different use case entirely, and I believe the table is explosion-proof.

**Comment by OvermindDL1** [comment]
> This is a different use case entirely, and I believe the table is explosion-proof.

Not to mod-mobs apparently.  I think it used wither style damage so that could be related (I had a *lot* of damage to repair, not just the table)...

But yes, it is a different use-case entirely, sometimes rushing through the table does have legitimate uses as per this use-case.  ^.^

**Comment by ReikaKalseki** [comment]
Recovering table progression is valid - though preventing its loss in the first place would be preferable - but this would not be the means to do it.

Also, I just checked, and the casting table is immune to explosions, and all CC (and RC) tiles are immune to the EnderDragon and the Wither. Whatever this entity did probably involved raw setBlock, which I cannot protect against.

**Comment by OvermindDL1** [comment]
> Whatever this entity did probably involved raw setBlock, which I cannot protect against.

Yeah a lot of mods do `setBlock`, a whole lot of mods, so it would not be surprising.
