### ISSUE TITLE
[CC] Subterranean Route Finder cannot pathfind through doors, even when open

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1463]
It does everything from creating a path that actually heads downwards into a pool of lava then stops, a path through solid iron bars, or across the ceiling of an underground chasm. None of these routes have been possible to follow, and in every situation there was a walkable route to the surface that barely required jumping that it could have used, but for some reason chose not to.

**Comment by Shahelion** [comment]
Edited to be more clear. The route finder shouldn't be leading into solid blocks or across thin air 40+ blocks up, should it?

Looks like the problem is that it cant pathfind through doors, even if they are open. I was using it in a stronghold.

**Comment by ReikaKalseki** [comment]
It does not use walking pathing.
