### ISSUE TITLE
[CC] Progress "lost" when first visiting every dimension

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1465]
So far has happened with the Twilight Forest, Nether, and End. The first time entering the dimension only, every time after that is fine. Also, nothing appears to be actually lost, but why is this happening? Apologies for taking a picture and not copy/pasting but my laptop is having issues with my internet browser.

![14964468541991074699838](https://cloud.githubusercontent.com/assets/6917535/26748406/5856ab4a-47b2-11e7-8d7c-8cabd170634e.jpg)

**Comment by ReikaKalseki** [comment]
The cache is...broken.

**Comment by ReikaKalseki** [comment]
I added one more backup system; we shall see if this works.
