### ISSUE TITLE
ArrayOutOfBoundsException thrown during init with RotaryCraft+ExtraTiC+Metallurgy

### ISSUE THREAD

**Issue by elfifae** [ReikaKalseki/Reika_Mods_Issues#147]
I've encountered an interesting issue while updating to the latest version of DragonAPI and RotaryCraft. At the end of MC's initialisation, an exception is thrown during loading that seems to be caused by a bad item stack being added as a recipe output, according to Glassmaker. (Tail of client log available here: http://pastebin.com/jS7RdQ1P -- can upload gzip of full log on request)

What's strange though is that this is not because of ExtraTiC's now-deprecated Rotarycraft support as one would expect -- it occurs whether or not that's enabled, which is the first thing I checked when I encountered this error. Instead, after some further troubleshooting, I've discovered that it seems dependent on whether ExtraTiC's Metallurgy mod support is enabled, which is what I find perplexing. I've tested this with both the current stable Metallurgy build and the latest beta, with no change in behaviour.

For readability's sake, a file listing of jars in use is available here: http://pastebin.com/w0FaShDg

As a note, the oredicted HSLA steel config option is disabled per default configurations.

**Comment by kolatra** [comment]
I don't think this is a RotaryCraft or DragonAPI issue if it is dependant on ExtraTiCs Metallurgy support. Confirm @ReikaKalseki?

**Comment by elfifae** [comment]
I reported it here based on a factor of elimination -- RotaryCraft is the only thing that had updates among the three since the last working group of mods, and RotaryCraft has made significant changes by way of implementing Tinker's Construct materials.

**Comment by ReikaKalseki** [comment]
This is caused by ExtraTiC trying to reference an item that does not exist (metadata 16 of the gear unit items). RC does not have any mapping for this and crashes trying to load its name. This is entirely on ExtraTiC's end, and is similar to past issues with the BC facades doing the same for BlockDeco.

It is not recipe code on my end, because I do not try crafting with items that do not exist.

**Comment by ReikaKalseki** [comment]
I found out the problem. It is not recipe code, but I can put a fix in.
