### ISSUE TITLE
Solar tower produces hot sodium with one Mirror

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1470]
The Solar tower with the Sodium Cycler + Sodium heat exchanger produces 4 mb Hot Sodium per tick with only one mirror even in the night at 14°.
The "Sodium Consuming mode" without Sodium heat exchanger works too.

**Comment by ReikaKalseki** [comment]
Some amount is normal, even at night (moonlight). However, the rate will be minimal. How does 4mB compare to midday operation?

**Comment by Kobra331** [comment]
On day the Tower produces 4 mB too with only 1 Mirror.

some more mirrors pushes it to 6 mb on Day. If I put 44 Mirrors on them it produces 7 mB and more Mirrors are wasted it just outputs 7 mB regardless the temperature of the Sodium cycler(300°-1500°)

The tower seems to be buffed in the last versions:
On version 15 it produces enough to run a small turbine for few minutes per day if i save it up on day and start the turbine at night, on v17 i need more then 1 turbine even if it runs nonstop.

greets

**Comment by ReikaKalseki** [comment]
Fixed, I hope.
