### ISSUE TITLE
[Rotarycraft 17c] Infinite duplication of fluorite blocks

### ISSUE THREAD

**Issue by patchworkspider** [ReikaKalseki/Reika_Mods_Issues#1471]
An autocrafter set up with patterns to craft calcite or any color of fluorite into the corresponding blocks creates those blocks every three or four ticks, even when the source chest for that autocrafter is totally empty.  Verified that these still exist through world reboots; at first I suspected they were some kind of lag thing, but no.

**Comment by ReikaKalseki** [comment]
#1442
