### ISSUE TITLE
Casting table crash

### ISSUE THREAD

**Issue by GhostFireXD** [ReikaKalseki/Reika_Mods_Issues#1474]
It sometimes crashes when i open the casting table, not all the times.
I don't even know how to replicate this cause it is random and the circumstances were very different.
It happened two times, the first with a Tier 0 Casting table, the second with a Tier 1.
Here the crash report: https://pastebin.com/Bcc5fVwZ

**Comment by ReikaKalseki** [comment]
#855 #1358 #1423 #652 #590 #161
