### ISSUE TITLE
RotaryCraft Water Pump: Paddle wheel disappears and water stops pumping [needs damage indicator]

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#1478]
(ATLauncher "Survival Industry" Share Code: A6xGGaap)

I've been playing Survival Industry for a while, and once in a while, I discover the (RoC) steam engines stop receiving water (usually when they stop working).  When I go to check the water pump, I discover that the pump's internal paddle-wheel is missing, and the pump is not pumping water.

The paddle wheel (and pump functionality) can be restored simply by breaking and re-placing the water pump.

So far, I've not seen this happen first-hand; it always happens when I'm elsewhere.

**Comment by ReikaKalseki** [comment]
Is the power negative? A missing renderer implies the power entered an illegal value - the aforementioned gearbox issue is triggered by such a case - which would also have obvious functional effect.

**Comment by ghost** [comment]
The water pump is being run by two steam engines joined by a shaft junction.  The resulting power is then maximized by an undamaged steel 8:1 gearbox in speed mode.  The gearbox, I might add, did not suffer from the same issue; its gears were still there.  The engines, junction, gearbox, and pump are all within the same chunk, so whatever is happening isn't happening due to chunk boundaries.

According to the angular transducer, the pump is receiving 32.768kW @ 4096 rad/s.  Next time the issue occurs, I'll grab the angular transducer and measure the power.

**Comment by ReikaKalseki** [comment]
Oh, wait. Is your pump damaged? Eating creatures can do that.

**Comment by ghost** [comment]
How can I tell if it's damaged?  WAILA doesn't seem to include a "damage" value, and the transducer just shows power transmission.

**Comment by ReikaKalseki** [comment]
The NBT debug overlay might show it (default key `Tab`).

**Comment by ghost** [comment]
After feeding enough zombies to it in a fresh world, I was able to make it break.  However, there is no indication of any breakage in the transducer or WAILA.  As for the NBT debug overly... I'm not finding how to do that in a search.  Unless "default key" means something specific.

**Comment by Duckfan77** [comment]
It needs to be enabled in the config file, it's the DragonAPI.cfg file.
`Show TileEntity NBT when using Debug Key"=false` change to `=true`

May look different for you, this from an old config file.

**Comment by ReikaKalseki** [comment]
So there needs to be a WAILA tooltip or something.

**Comment by ghost** [comment]
Either that, an output for the angular transducer, or perhaps you can add a new tool to the mod that gives diagnostic info on breakable equipment.

Side question: does the pump lose efficiency as it takes damage in the same vein as gearboxes and gas turbine?

**Comment by ReikaKalseki** [comment]
Yes.

**Comment by ReikaKalseki** [comment]
A WAILA indicator has been added.
