### ISSUE TITLE
[ChromatiCraft 17c] Creating the Charged Aura Cleaner via Thaumcraft infusion causes a crash consistently

### ISSUE THREAD

**Issue by Not-February** [ReikaKalseki/Reika_Mods_Issues#1479]
This has happened at least twice in different circumstances now, right as the infusion should be ending. I'd chalk it up to a Thaumcraft 4 issue based on the log, but absolutely  _no other_ item I've infused via Thaumcraft 4's infusion altar has done anything like this at all; I even did the crystalline wand core - also from ChromatiCraft - without any issues like this whatsoever.

The first time I was dealing with a ton of flux goo and gas and my altar was cramped to boot, so I figured it was an odd interaction with my current setup or poorly placed stabilizers constantly being removed due to the gas/goo, so I spent the next few hours revamping my altar setup with tons of stabilizers outside of the room(but still within range, of course). After accumulating the required essentia for the charged aura cleaner once again, I gave it another go with far fewer bad effects from the infusion itself compared to before, but right as it tried to absorb the very last item, the server crashed again.

Thereafter, as long as the infusion for the charged aura cleaner item remains active(the inert aura cleaner on the center pedestal still being there and whatnot), loading the chunk it's in causes the same exact crash unless the item is removed from the altar immediately after logging back in - before it has the chance to try to do whatever it's doing again.

Here is the crash log:

https://gist.github.com/Febilian/1f76f6f7d203254c1bc34a7c2ecb38e3

The crash may mention Thaumcraft specifically and not ChromatiCraft, but as I said, this has only ever happened with the same infusion consistently - and that one infusion is one from ChromatiCraft. Therefore, I thought it might be a good idea to tell you about it. If this turns out to be something not on your end I apologize.

Thanks for your time.

**Comment by Not-February** [comment]
Okay, it appears that logging back in after the second crash/restart actually completed the item, but the fact that it causes a crash to begin with is still kind of odd. Leaving this here because of that.

**Comment by HellFirePvP** [comment]
~~Code-part in question:~~

`[Random].nextInt(50 - this.recipeInstability * 2)`

~~You might've just accumulated too much instability and it caused a crash. This seems unrelated to Reika's mods specifically.~~

Nevermind, recipeInstability is defined by the Recipe registration, so adding a recipe with 25 or more instability will crash Thaumcrafts internal handling for recipe instability.

**Comment by ReikaKalseki** [comment]
> so adding a recipe with 25 or more instability will crash Thaumcrafts internal handling for recipe instability

...WTF...**WHY** was it implemented like this?

**Comment by HellFirePvP** [comment]
There is no safety mechanism so i suppose he relied on the "goodwill" of modders not to add something that has equal or higher instability than 25

(granted, "dangerous" is 10, so 25 is 2,5x higher than that.. well.. w/e)

**Comment by ReikaKalseki** [comment]
> "dangerous" is 10,

Wait, is there a table somewhere?

**Comment by HellFirePvP** [comment]
No, i decompiled Thaumcraft and looked it up :P

**Comment by ReikaKalseki** [comment]
Can I have a screenshot of that bit of code?

**Comment by HellFirePvP** [comment]
https://hastebin.com/qutotohoto.cs

specifically: i know that the advanced node stabilizer is dangerous:
` ConfigResearch.recipes.put("NodeStabilizerAdv", ThaumcraftApi.addInfusionCraftingRecipe("NODESTABILIZERADV", new ItemStack(ConfigBlocks.blockStoneDevice, 1, 10), 10,`

**Comment by ReikaKalseki** [comment]
Oh, so you do not know the divisions, just one data point.

**Comment by HellFirePvP** [comment]
I know that this instability parameter is then just an int in the final recipe class which then becomes TileInfusionMatrix.recipeInstability the recipe instability when the crafting process starts. The actual instability that can increase during the infusion is a different field in the tileentity.

It's not divided or processed any other way as far as infusions go.

**Comment by ReikaKalseki** [comment]
By 'divisions' I meant the thresholds between Minor/Moderate/High/Dangerous.

**Comment by DracoScythem** [comment]
From thaumcraft.client.gui.GuiResearchRecipe.class:
`/* 1289 */       int inst = Math.min(5, ri.getInstability() / 2);`
`/* 1290 */       text = StatCollector.translateToLocal("tc.inst") + " " + StatCollector.translateToLocal(new StringBuilder().append("tc.inst.").append(inst).toString());`

Corresponding Lines from en_US.lang:
`tc.inst.0=§1Negligible§0`
`tc.inst.1=§9Minor§0`
`tc.inst.2=§5Moderate§0`
`tc.inst.3=§eHigh§0`
`tc.inst.4=§6Very High§0`
`tc.inst.5=§4Dangerous§0`

So:
0-1 = Negligible
2-3 = Minor
...
10-24 = Dangerous

With everything above 24 crashing the Infusion Matrix' internal instability calculator...
(It's internal instability is capped at 25 anyways, but it still bugs me that it is impossible to actually force having a decent chance for that to be reached...)

**Comment by ReikaKalseki** [comment]
Fixed.
