### ISSUE TITLE
Crash when RotaryCraft/DragonAPI loads before FunkyLocomotion

### ISSUE THREAD

**Issue by maxpowa** [ReikaKalseki/Reika_Mods_Issues#148]
DragonAPI/RotaryCraft appear to be messing with the framesapi. Tested with only Funky Locomotion (contains framesapi), DragonAPI, RotaryCraft and FFS (FFS implements IMoveCheck from framesapi) Test cases below.

FFS/FL both loading after DragonAPI/RotaryCraft: http://hastebin.com/ogodojawit (crashes)
FFS loads before and FL loads after DragonAPI/RotaryCraft: http://hastebin.com/repevaqoda (crashes)
vs
FL loading before DragonAPI/RotaryCraft and FFS loading after: http://hastebin.com/junifonahi (doesn't crash) and FL/FFS both loading before DragonAPI/RotaryCraft: http://hastebin.com/oneqawopeb (doesn't crash)

Control case: FFS loading before FL without DragonAPI/RotaryCraft: http://hastebin.com/emobequzam (doesn't crash)

(Copied from [Lordmau5/FFS #7](https://github.com/Lordmau5/FFS/issues/7#issuecomment-121763658) for visibility)

**Comment by ReikaKalseki** [comment]
I made DragonAPI forcibly load after FunkyLocomotion. Will this fix it?

**Comment by maxpowa** [comment]
That should at least fix the crash.

**Comment by ReikaKalseki** [comment]
Good. Because classloading errors are impossible for me to fix.
