### ISSUE TITLE
ThaumicInfusion + DragonAPI 1.7.10 V17c

### ISSUE THREAD

**Issue by SvEgiiVEteR** [ReikaKalseki/Reika_Mods_Issues#1480]
found the conflict(ThaumicInfusion + DragonAPI 1.7.10 V17c).
log:
https://gist.github.com/e8bf7f81ff90ae1d20b64a5ecbac96bb

> `Caused by: java.lang.VerifyError: Bad type on operand stack
> Exception Details:
>   Location:
>     net/minecraft/block/BlockFire.func_149674_a(Lnet/minecraft/world/World;IIILjava/util/Random;)V @9: invokestatic
>   Reason:
>     Type integer (current frame, stack[3]) is not assignable to 'net/minecraft/world/World'
>   Current Frame:
>     bci: @9
>     flags: { }
>     locals: { 'net/minecraft/block/BlockFire', 'net/minecraft/world/World', integer, integer, integer, 'java/util/Random' }
>     stack: { 'net/minecraft/world/World', integer, integer, integer, integer, integer, integer }
> `  Bytecode:`
any solution?

**Comment by ReikaKalseki** [comment]
#895 #1003 #1186

**Comment by SvEgiiVEteR** [comment]
I helped this parameter
-noverify

**Comment by HellFirePvP** [comment]
Disabling the Verifier doesn't solve the issue, it just moves it to a later stage. Means it'll start up fine, but if you run across the code that previously would've crashed your client on startup, it'll now crash you whenever that point in the execution is reached.

**Comment by SvEgiiVEteR** [comment]
@HellFirePvP I thing that the game run, so what is the solution. if the creators of the mods can't do that.
initially, all mod FORG was compatible and now do not understand what is happening...

**Comment by 1Matthias** [comment]
@SvEgiiVEteR Removing thaumic infusion might be best. As noted in a previous thread, TI 1.7.10 is an abandoned version, no longer intended for use.
