### ISSUE TITLE
[ChromatiCraft]LaserPuzzle is not generated

### ISSUE THREAD

**Issue by Mr-kk** [ReikaKalseki/Reika_Mods_Issues#1481]
The room is occupied like a picture.
https://gyazo.com/d09d0900e7a57b1ecb19225e1bf4329c

LaserEffector are generated in StructShield.
I could not find the log "Could not load structure data for laser level".

Version
MC1.7.10 SMP
ModList
Forge10.13.4.1614
DragonAPI v17c
ChromatiCraft v17c

**Comment by ReikaKalseki** [comment]
This has never happened before. Does it occur consistently?

**Comment by Mr-kk** [comment]
Yes.
I made save data several times but it happens every time.
Regenerating the dimensions does not produce the LaserPuzzle correctly.
When it is v16d it is confirmed that it is generated normally. This phenomenon is from v17c.

**Comment by Mr-kk** [comment]
My opinion may be wrong, but I will mention the points I noticed.

1.The binary data of "StructureData / Laser" is different in v16d and v17c, but is it intentionally changed?
2.As a result of the above changes, is there a possibility that the variable Wall of line 104 of "LaserLevel.java" is true?

**Comment by ReikaKalseki** [comment]
> but is it intentionally changed?

Yes.

**Comment by Animal7865** [comment]
I too have the same issues.  I need 3 remaining Dimensional Cores and each time I goto any of the 3 remaining puzzle dungeons I get this same entity.  There is no way in but I did excavate one and it went on for a long ways.  Large room with a corridor connecting them.

**Comment by ReikaKalseki** [comment]
[It is working fine for me](http://i.imgur.com/u27jBMI.png).
![](http://i.imgur.com/u27jBMI.png)

**Comment by lAimBotl** [comment]
I just ran into this :). Here are some screen shots, after going in creative to dig into it.

![2017-07-13_23 07 04](https://user-images.githubusercontent.com/10777735/28196670-13a26b7c-6820-11e7-9d52-dcbfc488db30.png)

![2017-07-13_23 06 53](https://user-images.githubusercontent.com/10777735/28196673-1799d1d4-6820-11e7-81d5-25f8d076d228.png)

![2017-07-13_23 06 36](https://user-images.githubusercontent.com/10777735/28196677-1b07c150-6820-11e7-85eb-13dc5d2191f1.png)

**Comment by ReikaKalseki** [comment]
Can you get rid of all the dirt around (use DragonAPI's /blockreplace command) and show me the overall shape?

**Comment by lAimBotl** [comment]
Happened twice at the karmir puzzle area.
All the rooms are solid.

![2017-07-14_17 47 29](https://user-images.githubusercontent.com/10777735/28232087-e1fc03e2-68bc-11e7-95cd-418782a35e56.png)


![2017-07-14_17 47 54](https://user-images.githubusercontent.com/10777735/28232088-e4fb8f0e-68bc-11e7-972e-328a0ebe53ce.png)



![2017-07-14_17 48 11](https://user-images.githubusercontent.com/10777735/28232090-e7993158-68bc-11e7-9c26-2cb605d08496.png)



![2017-07-14_17 48 40](https://user-images.githubusercontent.com/10777735/28232094-e9e77c8a-68bc-11e7-9938-98e3f1eeb75a.png)

On the bright side the hallways are clear :).

![2017-07-14_17 50 46](https://user-images.githubusercontent.com/10777735/28232117-00907662-68bd-11e7-9112-cba847ca8be2.png)

![2017-07-14_17 54 20](https://user-images.githubusercontent.com/10777735/28232209-881b0912-68bd-11e7-8883-6bfa80153d0a.png)


![2017-07-14_17 54 28](https://user-images.githubusercontent.com/10777735/28232213-8a744502-68bd-11e7-9f3f-26e24ef13ed1.png)


![2017-07-14_17 54 35](https://user-images.githubusercontent.com/10777735/28232217-8d6e42a8-68bd-11e7-9023-413971543309.png)

**Comment by Animal7865** [comment]
I dont use any privileged commands, but when i used the Sonic Blast to
basically tunnel on top of the structure, I saw a similar structure that
kept going into the distance.

**Comment by ReikaKalseki** [comment]
Can you clear the ores, too? It is too hard to see.

**Comment by Animal7865** [comment]
I guess if it helps, i could go over in my world and excavate the top of
one with Sonic Blast.  Thanks to Inventory Warps  and a large ME system
:)..  What exactly are you looking for?

**Comment by ReikaKalseki** [comment]
I want to see the overall shape.

**Comment by Animal7865** [comment]
[image: Inline image 1]

Reika,

This is what the start of the puzzle structure looks like when excavated.
I also confirmed with 2 others on the server i am on that they too have the
same issues.  Since this appears to be a rare issue, what is the minimum
amount of "cheating" that we can do in order to get us past this hurdle and
continue on our quest to completing the Chromaticraft content?  I have a
total of 3 puzzles that all show the exact same.(Galazio, Vadali, and
Zambarau).  We discussed and agreed that we would "Give" us these
progressions and the associated Dimensional Core's. To do so, what commands
should we run in order to accomplish this?

Thanks

**Comment by ReikaKalseki** [comment]
![](http://i.imgur.com/WH6d5RF.png)

**Comment by OvermindDL1** [comment]
> [image: Inline image 1]

Cannot send images over email to github, have to use the web interface (or link it directly).

**Comment by Mr-kk** [comment]
Probably caused by the isBlockInside function of BlockBox.java of Dragon API.
In v 17, when min == max of BlockBox, the return value becomes false.
It does not seem to occur in the next version.

**Comment by ReikaKalseki** [comment]
> It does not seem to occur in the next version.

And was reverted for the very next release.
