### ISSUE TITLE
[ChromatiCraft]AdjacencyUpgrades works without supplying energy

### ISSUE THREAD

**Issue by Mr-kk** [ReikaKalseki/Reika_Mods_Issues#1482]
Set "Adjacency Upgrades Require Energy = true" from the config file.
However, the AdjacencyUpgrades operates without the Ambient Lumen Distributor.

Version
MC1.7.10 MP
ModList
Forge10.13.4.1614
DragonAPI v17c
ChromatiCraft v17c

**Comment by ReikaKalseki** [comment]
Which ones and where?

**Comment by Mr-kk** [comment]
AdjacencyUpgrades will work.
In my recognition, "Adjacency Upgrades Require Energy = true" requires energy to run AdjacencyUpgrades.
But now AdjacencyUpgrades is running without supplying energy.
This usually happens in the Overworld as well as in other dimensions.
I confirmed that TileAccelerator, BlockShuffle, EnergyBooster will work.

**Comment by ReikaKalseki** [comment]
Fixed.
