### ISSUE TITLE
[Suggestion] Multi-directional clutch for choosing input

### ISSUE THREAD

**Issue by kutschkem** [ReikaKalseki/Reika_Mods_Issues#1485]
There seems no easy way to dynamically change the input direction of a shaft/clutch/...

I suggest a mode for the multi-directional clutch to choose input side instead of output.

(What I am trying to do is run all four stages of the extractor with a single gasoline engine, my idea was to use multi-directional clutches to send power along different paths depending on redstone input... but now I am stuck because there seems to be no way to reunite the paths, with only one path at the time having power. Shaft junction doesn't work as both input sides need power, multi-directional clutch doesn't work. My only idea includes electricraft, but there i need at least a dc engine to offset the voltage loss, i think)

**Comment by ReikaKalseki** [comment]
> Shaft junction doesn't work as both input sides need power

This is untrue.
