### ISSUE TITLE
[Chromaticraft] Worldrifts transfers  wrong steam/liquid amount

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1486]
Hi!

Same Setup: 2 Heat exchanger each with 5 Steam boiler(water) 1 bucket of hot sodium.
Pumped them via Pipe pump into 1 Steam line.
Without World rift: 121 Steam
Transfered through world rift: 88 Steam.

Another bug with liquids: Filled 1 Bucket in Reservoir piped into a world rift into another reservoir : 1138 mB (of course no rain)

Maybe it depends on the height of the World Rifts.

I tested this in Singleplayer, i don't know if this bug exists in Multiplayer too.
http://www.directupload.net/file/d/4757/alw6yggx_jpg.htm

edit: a higher world rift produces more Water

**Comment by ReikaKalseki** [comment]
Check to see if the next block after the 121 was 88. The world rifts might count as one or two pipe blocks themselves.

Also check totals - is this just a transfer/throughput disparity, or are the rifts actually voiding fluid?

**Comment by Kobra331** [comment]
The World rifts doesn't voiding fluids. They produce them too. I tested it with liquid chroma and water. Both got a "Bonus" amount on the destination depending on the input world rifts height. A higehr input world rifts gives more "Bonus" output.

If the World rifts counting as pipes the pipepump should pumping the steam out of them. Every other steam line is empty.

**Comment by OvermindDL1** [comment]
I saw the same oddities with worldrifts in v16 but I chalked it up to potentially some odd interactions (plus I got some extra very valuable fuel), but I did not test in detail.

**Comment by ReikaKalseki** [comment]
Fixed. It was a client/server sync issue.
