### ISSUE TITLE
Ticking memory connection (Crash)

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1488]
[crash-2017-06-21_17.27.53-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1092993/crash-2017-06-21_17.27.53-server.txt)

The crash only happens with other mods.
It happens when changing a gears mode with the screw driver.

**Comment by Duckfan77** [comment]
Upload it to something like [gist](https://gist.github.com), otherwise I don't think anyone will look at it. I for one know that I won't be downloading a random text file.

**Comment by ReikaKalseki** [comment]
#1474 #855 #1358 #1423 #652 #590 #161

**Comment by lAimBotl** [comment]
ah so it is vanilla?, forgot to remove the "open" tag when searching for these sorry 

hm if i hit escape every time i change a gearbox it doesn't crash :) guess i will just do that lol
