### ISSUE TITLE
Flywheel infinite energy

### ISSUE THREAD

**Issue by JoshuaBowerman** [ReikaKalseki/Reika_Mods_Issues#149]
I found a bug!

The flywheels do not discharge and will remain at the output levels regardless of the machines its running or the time it is left on.
I am assuming you would like a log file, i would gladly put one on pastebin if you tell me the path.

I have been able to reproduce this on releases as far back as 6-7 months ago

**I built this when i found that the fly wheel in my survival world was not spinning down.**
**It is a flywheel connected to a cvt that is set to 32 torque and that charges the coil which can discharge back into the wheel.**
![img width='663' height='385'](http://i.imgur.com/QYO7ltu.png)
**I charged the coil to about 300 MJ of energy, i then discharged it into the flywheel at 1410 rad/s and 4096 nm**
![img width='661' height='384'](http://i.imgur.com/SAntlgb.png)
**I let it drain until it hit about 50 MJ of energy left**
![img width='656' height='381'](http://i.imgur.com/i8gvCUb.png)
**I then let the coil charge.**
!img width='654' height='380'](http://i.imgur.com/xU8kXbY.png)
**The coil charged to 1.0 GJ without the flywheel slowing down at all.**
![img width='651' height='378'](http://i.imgur.com/Na9FzuV.png)
**I am using these versions of your mods:**
- Dragon API : 1.7.10 V7f
- RotaryCraft : 1.7.10 V7f
- ElectriCraft : 1.7.10 V7e
- ReactorCraft: 1.7.10 V7f

**Screenshot of my mod folder:**
![img width='581' height='471'](http://i.imgur.com/TVrdHNv.png)

**Comment by JoshuaBowerman** [comment]
I was able to replicate the bug as far back as i can go in 1.6.4 V25f
it could go back much farther but i cant test back any farther

**Comment by ReikaKalseki** [comment]
It likely dates back to v20, when the power transfer code was rewritten and @Varogh's TorqueUsage class broke and could not be properly repaired.

**Comment by JoshuaBowerman** [comment]
do you know which class is causing it?

**Comment by ReikaKalseki** [comment]
Probably [TorqueUsage](https://github.com/ReikaKalseki/RotaryCraft/blob/master/Auxiliary/TorqueUsage.java).

**Comment by ReikaKalseki** [comment]
I am working on this. The substantial rewrites to TorqueUsage might fix it as well as #69.

**Comment by ReikaKalseki** [comment]
#69 is confirmed fixed.

**Comment by ReikaKalseki** [comment]
And this bug is confirmed not fixed. The whole looping and CVT setup is superfluous; the actual problem is that the coil seems not to be putting a "load" on the flywheel.

**Comment by ReikaKalseki** [comment]
Fixed. Hopefully this breaks nothing else.

**Comment by JoshuaBowerman** [comment]
It also works with machines other than the coil, you can power anything once you spin it up. In v7f you can boil water with the coil and spin and turn that back to shaft power, that also works

**Comment by ReikaKalseki** [comment]
I noticed. That was fixed too.
