### ISSUE TITLE
[Chromaticraft] Unable to join world after importing .mid file for the Crystal Orchestra, bad packet IDs and VarInt too large errors

### ISSUE THREAD

**Issue by Thaumcraft4Lyfe** [ReikaKalseki/Reika_Mods_Issues#1490]
Me and a friend on an SMP finally got the Crystal Orchestra. I (the server host, same machine as the client) managed to get a midi import to work but when my friend tried the same it booted us from the server with an error. Rejoining continues to boot us as soon as we load in with the same error.

Main Error - https://pastebin.com/5m7MWT1n
Full Client Log - https://www.dropbox.com/s/a1d7p60a4rpkpr0/ErrorLog.txt?dl=0 (Log was too big to put into pastebin)

**Comment by ReikaKalseki** [comment]
Try another MIDI; it works for me.

**Comment by Thaumcraft4Lyfe** [comment]
That isn't the problem, @ReikaKalseki. I got one midi to work, then my friend tried one and our world is literally unplayable now. Is there some way to unload the midi from the orchestra or something?

**Comment by ReikaKalseki** [comment]
Deleting the orchestra will work.

**Comment by duncan19990** [comment]
@ReikaKalseki Hello, im his friend, what @Thaumcraft4Lyfe is trying to say is that when i tried to put in my midi, the server kicked us, and now we are unable to even join the world, backups ignored, is their anyway to get rid of the orchestra without having to log into the server? If so, could you give us specific instructions? (Note that @Thaumcraft4Lyfe is the server host). Thanks

**Comment by Duckfan77** [comment]
Use MCEdit, or something of the like, and delete the Crystal Orchestra using that.

**Comment by duncan19990** [comment]
@Duckfan77 we tried our hardest, be we couldn't get the world to even load, in mc edit, it keeps saying that  our would had not been loaded before

**Comment by duncan19990** [comment]
@Duckfan77  @ReikaKalseki  we managed to delete the crystal orchestra in mc edit, but we are still unable to load in

**Comment by Duckfan77** [comment]
Is the log the same?

**Comment by Thaumcraft4Lyfe** [comment]
It was. We managed to fix it by loading the world on @crustybuns's computer in a single-player world. Guess the bug is caused by a non-host player trying to load a midi of their own, which can be solved by allowing it to load then cancelling it in-game. A potential solution to this would be to either implement a way for non-hosts to upload their own .mid files to the orchestra or simply prevent them from doing so. Thanks for the help!

**Comment by ReikaKalseki** [comment]
Non-host players work fine...

**Comment by Thaumcraft4Lyfe** [comment]
@ReikaKalseki I did a bit more testing and was able to reproduce the error with a specific midi file. I think it might just be that the file is too big (160kb) and by playing the same midi i got the same error message on joining, abeit with different packet numbers. Maybe the multiplayer server can't keep up with the large midi file, hence the packet being too large?

**Comment by ReikaKalseki** [comment]
160KB in **one MIDI**!?!

Yes, it sounds like your problem is the sheer amount of data.

**Comment by Thaumcraft4Lyfe** [comment]
Maybe you could implement a solution that would prevent that large of a file from playing on a server? This seems like a bug quite a few people could encounter, and it breaks the world.

**Comment by ReikaKalseki** [comment]
I can impose some arbitrary filesize limit, but I have no idea what is safe, nor is there a good way to tell the player "too large".

**Comment by OvermindDL1** [comment]
> I can impose some arbitrary filesize limit, but I have no idea what is safe, nor is there a good way to tell the player "too large".

As I recall I think a mod 'data' packet is limited to 65535 bytes (unsure if that counts packing overhead or not).  You could compress the content and get a little more in to it too.

But yeah, a 160kb midi is *huge* when it only needs one instrument...

**Comment by ReikaKalseki** [comment]
I put the limit at a flat 60000 bytes to be safe.
