### ISSUE TITLE
[Tip] How to use Applied Energistics 2 rv3 with ChromatiCraft

### ISSUE THREAD

**Issue by MineBartekSA** [ReikaKalseki/Reika_Mods_Issues#1493]
In few days ago i wanted to add to my mod pack and update some mods, so i updated Applied Energistics 2 to rv 3 and all Reika's mod, then i added ChromatiCraft ver 17c. I had some trouble with modpack beacuse it was giving me errors (obviously) but i solve those errors and now i have my upgraded modpack. I maded it work with no AP2 or CC config editing, just other mods config (in my case TwilightForest and BiomesOPlenty). My friend wanted to upgrade it on his own and he rege quited the task downgrading AP2 to rv 2. So then i done some reschearch how to simply do this and i wanted to share this knowledge.
I just want here to say that this is a posible suggestion to add info how to do this somewhere.

## How to in steps!
**Firstly if you are upgrading your old modpack i suggest to backup yours eddited config files and maps.**

To start just download mods and copy them to your mods folder.
You should delete or rename your config folder to make sure you will be succesfull but it's not nessesery

1. Start minecraft to check what problem we have. 
    If you have and error like this
    ```
    [Client thread/ERROR] [FML]: Caught exception from ChromatiCraft
    java.lang.NoClassDefFoundError: Could not initialize class  Reika.ChromatiCraft.Registry.ChromaResearchManager$ResearchLevel
    ```
    go to the 2 A
    but if you have an error like this 
    ```
    Reika.DragonAPI.Exception.IDConflictException: The mods were not installed correctly:
    CONFLICT: Biome IDs: biomesoplenty.common.biome.overworld.BiomeGenChaparral@5cedfae7 @ ID 48 (BiomeGenChaparral & BiomeRainbowForest)
    Check your IDs and change them if possible.
    This is NOT a mod bug. Do not post it or ask for support or you will look lazy or extremely foolish..
    ```
    go to 2 B

2. A: You just have to edit something in Applied Energistics 2 config.
    Go to your config folder, next to AppliedEnergistics2 folder and open CustomRecipes.cfg file and edit the value exportItemNames form true to false. Evrything should be working fine now.
    
    B: You have to fix thsi Biome ID Conflict but i suggest to not to change ID in ChromatiCraft config because those biomes are needed to progress.
    Whne you done that start your minecraft it sometimes work but if you get the error like this
    ```
    [Client thread/ERROR] [FML]: Caught exception from ChromatiCraft
    java.lang.NoClassDefFoundError: Could not initialize class  Reika.ChromatiCraft.Registry.ChromaResearchManager$ResearchLevel
    ```
    go to 2 A but you don't get any error the evrything should work fine.
    In my modpack i just fix the Biomes ID Conflicts and evrything is working just fine.

That's all!
If this help you fix your modpack or something else then i'm glad to help.
If i make a mistake please comment this i make sure to edit this.

For the end i hope you will have a good time playing!

**Comment by ReikaKalseki** [comment]
Helpful but not appropriate here.

**Comment by Aivech** [comment]
There's also another issue somewhere describing how to make AE2 rev3 compatible with CrC, something to do with disabling custom recipes in an AE2 config file.
