### ISSUE TITLE
[Rotarycraft] Drop Processor NEI Recipe View bugging out.

### ISSUE THREAD

**Issue by nmarshall23** [ReikaKalseki/Reika_Mods_Issues#1494]
The Drop Processor's NEI view all recipes dialog is broken. In the item to be Processed Box it very quickly switches between items. On the Items Dropped area, is full of items that could be dropped.

To Reproduce open the Drop Processor GUI and click on the hidden view NEI Recipes. This can opened by clicking on the progress arrow, when the Recipes text pops up. Or do click the same area while viewing an this dialog for one item.

I found that if you look up an item that could be dropped from a Forestry's Crated, the dialog is bugged. However If you look at what that Forestry Crated while drop it's correct.

For example in NEI lookup how to get Apples, in the Drop Processor dialog you will see other items droped by other Forestry Crates. However if you look up the Crated Apple the Drop Processor dialog show 9 Apples has drops.

**Comment by ReikaKalseki** [comment]
This is not fixable, nor a very big deal anyways.
