### ISSUE TITLE
[Rotarycraft] [Feature Request] Drop Processor - Forestry Hives

### ISSUE THREAD

**Issue by nmarshall23** [ReikaKalseki/Reika_Mods_Issues#1495]
I'd like the Rotarycraft Drop Processor to process Forestry Hives into Bees.

My Silktouch Boring Machines are a constant source of Rock, Pure and Crystal Hives. Having to break them myself is taking far to much time.

**Comment by ReikaKalseki** [comment]
Does it not do so already?

**Comment by nmarshall23** [comment]
I just checked again. Nope no Hives are processed. Tryied Hives from Forestry, ChromatiCraft, and Extra Bees.

**Comment by ReikaKalseki** [comment]
It should fit under the normal 'block drops' processing. I have expanded that slightly to test.
