### ISSUE TITLE
Crash when Witchery HobGoblin with HSLA Pick and Config Option.

### ISSUE THREAD

**Issue by nmarshall23** [ReikaKalseki/Reika_Mods_Issues#1496]
If the Config Option, "Increased Harvest Level for HSLA" is true. And a Witchery Hobgoblin is given a HSLA Pick to mine with. A crash is triggered when checking HarvestLevel.

`java.lang.NullPointerException: Ticking entity
    at Reika.RotaryCraft.Items.Tools.Steel.ItemSteelPick.getHarvestLevel(ItemSteelPick.java:60)
    at com.emoniph.witchery.entity.ai.EntityAIDigBlocks.tryHarvestBlock(EntityAIDigBlocks.java:220)`

[Pastebin](https://pastebin.com/cgKTMPs2) to crash report.

Soon as that option is turned off, the HobGoblin can use the HSLA Pick with no problems.

**Comment by ReikaKalseki** [comment]
This is a Witchery bug; it is supplying null as a tool class (it should be a string like "pickaxe").

**Comment by Aivech** [comment]
I know this is almost a month old, but is this something you could add a check for on your end to prevent crashes? The Witchery dev is MIA and Witchery is closed-source.

**Comment by ReikaKalseki** [comment]
I understand that, but I do not want to set a precedent either building in checks for things that should never happen, or worse, making it look like I am taking responsibility for someone else's error.
