### ISSUE TITLE
Flywheel Max Speeds

### ISSUE THREAD

**Issue by EbonyDean** [ReikaKalseki/Reika_Mods_Issues#1497]
Last update to Rotarycraft increased the Max speed Flywheels can accept to 2Grad/s. ALL OF THEM. But I didn't see this change reflected in changelogs. Is it intended behavior or is it an unexpected change?
I observed it after installing Reactorcraft.

These are the mods I currently have of yours:
Dragon API V17c
Rotarycraft V17c
Electricraft V17a
Reactorcraft V17a
Condensed Ores V17a

All observed in Local Single Player.

Thanks beforehand.

**Comment by EbonyDean** [comment]
A little bit more information on the topic: I noticed that flywheels (Specially Gold) wind down amazingly slow. I was running one from a Solar Tower and it would retain 510 rad/s through the whole night, even if I broke the shafts connecting the flywheel. This behavior is not observed in Iron, though they do take quite a while to go down.

**Comment by ReikaKalseki** [comment]
Fixed. In other news, Java apparently does not mind referencing final variables before they are set, which seems stupid.

**Comment by OvermindDL1** [comment]
> Fixed. In other news, Java apparently does not mind referencing final variables before they are set, which seems stupid.

Yeah if you look at the bytecode you see why.  Final variables are nothing but a compiler annotation really, they are still normal allocations and can be referenced as such well before they are set, including even statically.  It's the JVM...  >.>
