### ISSUE TITLE
How to fix bug with render?

### ISSUE THREAD

**Issue by danilbor11** [ReikaKalseki/Reika_Mods_Issues#1498]
http://imgur.com/U1hx3Ja

**Comment by OvermindDL1** [comment]
What is your video card and what drivers are they currently using, precisely?
Are you using Optifine?
What is your complete and entire mod list?
What is your entirely complete and most recent log file?

**Comment by ReikaKalseki** [comment]
You probably ran out of graphics memory or something.

**Comment by danilbor11** [comment]
i can give my yesterday crash.you can find all their                                                                                                                
https://pastebin.com/dzeDM7fx

**Comment by OvermindDL1** [comment]
> i can give my yesterday crash.you can find all their
> https://pastebin.com/dzeDM7fx

That is not giving all the information that is needed for 'this' specific issue though, I especially need all of these with the most important bits at the top:

* What is your video card and what drivers are they currently using, precisely?
* Are you using Optifine?
* What is your complete and entire mod list?
* What is your entirely complete and most recent log file?

**Comment by OvermindDL1** [comment]
For note, you are using Optifine:  `Optifine OptiFine_1.7.10_HD_U_D6`
That is heavily bugged, you should *NOT* be  using it, try removing it first.
