### ISSUE TITLE
Insane network lag

### ISSUE THREAD

**Issue by creeperdude400** [ReikaKalseki/Reika_Mods_Issues#15]
So I run a server and it's lagging HARD cuz of rotarycraft. Its kind of ok if everything is off (still not great tho) but as soon as any players turn anything on half of them disconnect andthe other have feel like the server is lagging to oblivion. i can't have this, so if it's not fixed soon were going to remove your mod.

**Comment by coolsquid** [comment]
Please provide some kind of profiling information.

**Comment by zemerick** [comment]
We also need specifics. What items exactly are the problem? How are they set up? Can you provide pictures?

Is Rotarycraft the only one installed, or are there others of Reikas mods?

**Comment by creeperdude400** [comment]
No idea what that means, but I can confirm breaking all the machines makes it go away, so it's gotta be the machines.

**Comment by TomeWyrm** [comment]
Can you run Opis?

**Comment by frogfigther** [comment]
without any profiling data there is nothing, we can do to fix a potential issue.

also what version of rotarycraft are you using

**Comment by creeperdude400** [comment]
Opis shows alot of lag from the server, doesn't say what mods though.

@frogfigther this is the recommended version.

**Comment by coolsquid** [comment]
Screenshot the Opis window.

**Comment by creeperdude400** [comment]
![](http://i.gyazo.com/800c2f106d5825178ab36a24a5532e1a.png)

again, removing the rotarycraft blocks fixes it, so I know it's rotarycraft! and look, the rest of my mods aren't gonna do it!

Advanced Buildcraft Objects	1.0.7.560
Advanced Genetics	1.4.1
Agriculture	1.2.15
Alternate Terrain Generation	0.9.4
AOBD	1.3.1
Applied Energistics	14.finale3
Aroma1997core	1.0.1.3
ArmorStatusHUD	1.1.5
AutoUtils	1.0.1
Backpacks	1.27.34
bdlib	1.2.0.38
Better Storage	0.8.0.45
BiblioCraft	1.5.5
BiblioWoods - BoP	1.3
BiblioWoods - Forestry	1.3
BiblioWoods - Highlands	1.1
BiblioWoods - Natura	1.1
Big Reactors	0.3.0A
Binnie's Mods	1.8.0
Biomes O Plenty	1.2.1.416
Blood Magic	1.0.0b
bspkrsCore	5.2
Buildcraft	4.2.2
Calclavia Core	1.1.1.68
Chicken Chunks	1.3.3.4
Chisel	1.5.0fix
CodeChickenCore	0.9.0.9
COFHcore	2.0.0.2
Compact Solars	4.4.19.278
Compact Windmills	1.0.3.0
ComputerCraft	1.58
Craft Heraldry	1.0.3
DamageIndicators	2.9.2.3
denlib	3.2.6
denPipes	2.1.18
denPipes - Emerald	1.1.6
denPipes - Forestry	1.1.8
DragonAPI	19b
DyeTrees	19
Dynamic Tanks 2	0.0.8a
Electricraft	19b
Emasher's Resource	1.2.3.4
Enderstorage	1.4.3.6
EnderIO	1.0.0.343
Endernet	latest
Engineer's Toolbox	1.1.8.3
Enhanced Portals 3	3.0.0.b5c
EVOC	1.0.0a
Expanded Redstone	19
Extra Cells	1.6.7d
Extra Utilities	1.0.3a
Factorization	0.8.34
Flatsigns	1.4.0.15
Forestry	2.3.1.1
Forge Multipart	1.0.0.250
GasCraft	2.0.4.3
Gate Copy	3.1.4
Gendustry	1.1.0.61
GeoStrata	19b
Highlands	2.1.7a
Hopper Ducts	1.2.2
iChunUtil	2.4.0
Industrial Craft 2 Exp	2.0.397
Inventory Tweaks	1.5.6-b77
Iron Chests	5.4.1.697
JABBA	1.1.2c
JourneyMap	3.3.2
Logistic Pipes	0.7.4.dev.125
Lycanites Mobs	1.4.9d
Magic Bees	2.1.12
Magical Crops	3.2.0beta15a
Mariculture	1.2.1e
MeteorCraft	19b
MFFS	 3.6.2.9
Mimicry	1.3.8.2
MineFactoryReloaded	2.7.8-482
MineTweaker	2.3.1
MobiusCore	1.1.0
Modular Powersuits	0.9.0-84
Morpheus	1.2.32
Mystcraft	0.10.12.01
Natura	2.1.14
NEI Addons	1.10.4.64
NEI Plugins	1.1.0.6
Nether Ores	2.2.2-55
Not Enough Items	1.6.1.9
Not Enough Keys	0.0.4
Nuclear Control	1.6.2e
Numina	0.1.1-53
Obsidiplates	2.0.0.15
OpenBlocks	1.2.7
OpenMods Lib	0.4b
OpenPeripheral Addons	0.1.3
OpenPeripheral Core	0.3.3
Opis	1.2.0
Portal Gun	2.0.2
Power Converters	2.4.0.pre3
PowerCrystalsCore	1.1.8-10
Powersuits Addons	1.6.4-884
Project Red	4.3.5.30
qCraft	1.1
QuarryPlus	1.0.3
Railcraft	8.4.0.0
Random Things	1.9
ReactorCraft	19b
Redstone Arsenal	1.0.0.0
Rei's Minimap	3.4.01
Reliquary	1.1.2b
RemoteIO	1.11
Revamp	1.2.2
Roguelike Dungeon Mod	1.5.0
RotaryCraft	19b
Sort Fix	1.0
Special Mobs	2.6
StatusEffectHUD	1.19
Steve's Carts	2.0.0.b10
Switches	1.3.0.25
Sync	2.1.1
Thaumcraft 4	4.1.0g
Thaumcraft Mob Aspects	1e-b2
Thaumic Tinkerer	2.3-130
Thaumic Tinkerer KAMI	j6
Thermal Expansion	3.0.0.2
Tinker's Construct	1.5.3
Tinker's Mechworks	0.1.4.2
Torch Levers	1.3.2
Twilight Forest	1.20.5
Universal Electricity Core	3.0.1.27
Waila	1.5.2
WRCBE	1.4.0.7
Zan's Minimap	1.6.4

**Comment by ljfa-ag** [comment]
Opis can give you a list of which tile entities produce how much lag. Can you show us that?

**Comment by frogfigther** [comment]
are you using FTB monster?

**Comment by ljfa-ag** [comment]
>  RotaryCraft 19b
The newest version for Minecraft 1.6.4 is 25z. Even though Monster is not being maintained anymore, please update to 25z first and see if it fixes that.

**Comment by creeperdude400** [comment]
I can't update, none of my players are able to figure it out, and I have better things to do than walk 139 players through it all. Please fix v19 and update it.

**Comment by coolsquid** [comment]
We can't 'fix' anything if you're not willing to update.

**Comment by frogfigther** [comment]
we cant fix an old version that is already published.

**Comment by creeperdude400** [comment]
Look, it's not my fault your too lazy to fix the frakking mod! Your mod is killing my server and I want it fixed!

**Comment by zemerick** [comment]
Older versions WERE fixed. That's what a new version is. v25z is your best bet.

Your opis log shows everything going back down to relatively normal after some time. Is there anything you can think of that's doing this?

I do seem to also recall something from back around then. A config option to do with how often the rotarycraft network is updated or something. Can you provide a copy of your rotarycraft / dragonapi configs? Might be able to make a tweak to at least help.

**Comment by coolsquid** [comment]
Since Zemerick seems to think he can help you, I'll leave this open. 1 more "fix this because you suck" comment, and I'll permanently lock the issue.

**Comment by creeperdude400** [comment]
Sigh. You just don't get it do you. Let me make it real simple:

I. CANT. UPDATE. This is why we use packs, so that normal people (you know, the kind that don't make mods) can use it.


Configs:
# Configuration file

####################
# achievement ids
####################

"achievement ids" {
    I:BEDROCKBREAKER=24012
    I:BEDROCKSHAFT=24016
    I:BEDROCKTOOLS=24017
    I:BORER=24006
    I:CUTKNOT=24034
    I:CVT=24015
    I:DAMAGEGEARS=24023
    I:DIAMONDGEARS=24024
    I:DOUBLEKILL=24038
    I:EXTRACTOR=24002
    I:FLOODLIGHT=24022
    I:GIGAWATT=24026
    I:GPR=24005
    I:GPRENDPORTAL=24033
    I:GPRSPAWNER=24032
    I:GRAVELGUN=24029
    I:JETCHICKEN=24018
    I:JETENGINE=24009
    I:JETFAIL=24019
    I:JETFUEL=24007
    I:LANDMINE=24030
    I:LIGHTFALL=24020
    I:MAKERAILGUN=24010
    I:MAKESTEEL=24000
    I:MAKEYEAST=24001
    I:MASSIVEHIT=24036
    I:MRADS32=24025
    I:NETHERHEATRAY=24031
    I:OVERPRESSURE=24037
    I:PCB=24003
    I:PUMP=24004
    I:RAILDRAGON=24027
    I:RAILKILLED=24028
    I:RAREEXTRACT=24035
    I:RECYCLE=24008
    I:SPRINKLER=24021
    I:STEAMENGINE=24013
    I:STEELSHAFT=24014
    I:SUCKEDINTOJET=24011
}


####################
# control setup
####################

"control setup" {
    B:"Allow Bedrock Breaker to Break Y=0"=false
    B:"Allow Bedrock Pickaxe to Harvest Spawners"=false
    B:"Allow Blast Glass to be Used as TE Hardened Glass"=false
    B:"Allow Build Blocking of Some Machines"=true
    B:"Allow Craftable Bedrock"=false
    B:"Allow Gravel Gun PvP"=false
    B:"Allow RC steel to be used in other mods"=true
    B:"Allow TNT Cannon"=false
    I:"Bait Box Range"=0
    B:"Block Damage from Destructive Machines"=false
    I:"Block Ram Range"=0
    I:"Breeder Range"=0
    I:"Cave Scanner FOV"=16
    I:"Chest Generation Tier"=0
    B:"Color Blind Mode"=false
    B:"Conservative Jetpack Firing"=true
    B:"Crafting Table can Make Machines"=true
    B:"Crash on hostile interference from other mods"=false
    I:"Difficulty Control"=2
    B:"Direct Block Damage from Machine Failures"=false
    B:"Disable Silver Iodide Cannon Rain"=true
    I:"EMP Charging Speed"=0
    B:"Enable Achievements"=true
    B:"Engine Running Sounds"=false
    B:"Explode jetpack if player is in lava"=true
    I:"Fluid Flow Speed"=1
    B:"Force Inter-Mod Ore Compatibility"=true
    B:"GPR Renders Ores"=false
    B:"Instant Woodcutter"=false
    D:"Iron Ore Density"=1.0
    B:"Jetpack Uses Jet Fuel"=false
    B:"Jetpack bypasses allow-flight property"=false
    B:"Lock enchants on bedrock tools"=true
    B:"Log Block Placement and Removal"=false
    D:"Machine Volume Multiplier"=0
    B:"Machine Warning Alarms"=false
    I:"Max Aerosolizer Range"=0
    I:"Max Bait Box Mob Count"=0
    I:"Max Bridge Range"=0
    I:"Max Fan Range"=0
    I:"Max Floodlight Range"=0
    I:"Max Force Field Range"=0
    I:"Max Heat Ray Range"=0
    I:"Max Sonic Weapon Range"=0
    I:"Max Vacuum Range"=0
    B:"Owner-Only Machine Use"=false
    I:"Player Detector Range"=0
    B:"Railgun Block Damage"=false
    B:"Reload Handbook Data on Open"=false
    B:"Render projector lines"=true
    B:"Rotate Hose/Pipe/Fuel Line Recipes"=false
    B:"Show Force Fields"=true
    I:"Sonic Borer Range"=0
    B:"Spawn Mobs When Harvesting Spawners By Hand"=false
    B:"Spawn with RC Handbook"=true
    I:"Spawner Mob Limit"=0
    I:"Sprinkler Particle Density"=0
    B:"Terraformer Block Editing"=false
    B:"Tools Clear Chat"=false
    B:"Turrets can target players"=false
}


####################
# crafting item ids
####################

"crafting item ids" {
    I:"Borer Crafting Items"=30630
    I:"Engine Crafting Items"=30629
    I:"Gear Units"=30641
    I:"Heat Ray Crafting Items"=30628
    I:"Shaft Crafting Items"=30631
}


####################
# extra block ids
####################

"extra block ids" {
    I:"Beam Block"=460
    I:"Bedrock Slice"=4092
    I:"Blast Glass"=459
    I:"Blast Glass Pane"=458
    I:Canola=455
    I:"Deco Block"=4093
    I:"Decorative Tank"=4091
    I:"Light Bridge"=457
    I:LightBlock=454
    I:"Mining Pipe"=456
}


####################
# item ids
####################

"item ids" {
    I:"Bedrock Boots"=30532
    I:"Bedrock Chestplate"=30530
    I:"Bedrock Helmet"=30529
    I:"Bedrock Helmet of Revealing"=30563
    I:"Bedrock Jetpack"=30534
    I:"Bedrock Leggings"=30531
    I:"Bedrock Spring Boots"=30546
    I:"Canola Seeds"=30507
    I:"Ethanol Crystals"=30506
    I:"Ethanol Jetpack"=30543
    I:"Explosive Shell"=30527
    I:"HSLA Steel Boots"=30541
    I:"HSLA Steel Chestplate"=30539
    I:"HSLA Steel Helmet"=30538
    I:"HSLA Steel Leggings"=30540
    I:"High-Strength Spring"=30542
    I:"I/O Goggles"=30524
    I:"Night Vision Goggles"=30518
    I:"Night Vision Helmet"=30519
    I:"Projector Slide"=30525
    I:"RailGun Ammunition"=30521
    I:"Spring Boots"=30545
    I:"Wind Spring"=30508
    I:Yeast=30505
}


####################
# itemblock ids
####################

"itemblock ids" {
    I:"Advanced Gear Items"=30642
    I:"Engine Items"=30634
    I:"Flywheel Items"=30643
    I:"Gearbox Items"=30640
    I:"Machine Items"=30616
    I:"Shaft Items"=30639
    I:Spawner=30636
}


####################
# machine blocks
####################

"machine blocks" {
    I:"Advanced Gears"=490
    I:"Basic Machines"=499
    I:"D-Type Machines"=491
    I:"DM-Type Machines"=493
    I:"DM-Type Machines 2"=509
    I:"DMI-Type Machines"=492
    I:Engines=494
    I:Flywheels=496
    I:GPR=495
    I:Gearboxes=497
    I:"I-Type Machines"=498
    I:"M-Machines 2"=508
    I:"M-Type Machines"=501
    I:"MI-Machines 2"=505
    I:"MI-Type Machines"=500
    I:"Mod Interface"=507
    I:Piping=502
    I:Shaft=503
    I:"Solar Receiver"=506
    I:Transmission=504
}


####################
# other ids
####################

"other ids" {
    I:"Freeze Potion ID"=35
    I:"Growth Hormone ID"=36
}


####################
# resource item ids
####################

"resource item ids" {
    I:"Compactor Items"=30633
    I:"Extractor Items"=30632
    I:"Mod Interface"=30646
    I:"Mod Ore Extractor Items"=30644
    I:"Mod Ore Ingots"=30645
    I:Powders=30635
}


####################
# tool item ids
####################

"tool item ids" {
    I:"Angular Transducer"=30501
    I:"Bedrock Axe"=30516
    I:"Bedrock Grafter"=30561
    I:"Bedrock Handsaw"=30562
    I:"Bedrock Hoe"=30548
    I:"Bedrock Pickaxe"=30515
    I:"Bedrock Scythe"=30558
    I:"Bedrock Shears"=30552
    I:"Bedrock Shovel"=30517
    I:"Bedrock Sword"=30550
    I:Bucket=30522
    I:"Cannon Key"=30526
    I:"Ethanol Minecart"=30528
    I:"Fireball Launcher"=30514
    I:"Gravel Gun"=30513
    I:"HSLA Steel Axe"=30536
    I:"HSLA Steel Hoe"=30549
    I:"HSLA Steel Pickaxe"=30535
    I:"HSLA Steel Scythe"=30559
    I:"HSLA Steel Shears"=30553
    I:"HSLA Steel Shovel"=30537
    I:"HSLA Steel Sword"=30551
    I:"Handheld Crafting Tool"=30520
    I:"Knockback Gun"=30512
    I:"Magic Wand"=30502
    I:"Motion Tracker"=30510
    I:"Music Box Record"=30555
    I:"Portable Backup Fuel Tank"=30547
    I:"RotaryCraft Handbook"=30504
    I:Screwdriver=30500
    I:"Spring-Powered Grafter"=30560
    I:"Spring-Powered Pump"=30544
    I:"TNT Cannon Targeting Aid"=30523
    I:"Tile Selector"=30533
    I:Ultrasound=30509
    I:Vacuum=30511
    I:"WorldEdit Tool"=30503
    I:item.craftpattern=30557
    I:item.engineupgrade=30556
    I:item.flamethrower=30554
}

**Comment by coolsquid** [comment]
First of all, being rude won't help you. Secondly, use Pastebin for long texts like configs. Thirdly, we don't support outdated versions. We can't magically fix this without having you update. It's technically impossible.

**Comment by zemerick** [comment]
For walls of text, please use pastebin or something similar that is better suited to it. ( pastebin also has a few other advantages to it, so it's recommended. )

Unfortunately, I don't see the config option in there. Either it hadn't been added yet, or it's in a different config file. I don't remember if dragonAPI had it's own config back then. ( We are talking like 2 years ago after all. )

We understand that some situations are hard to update, but in those cases you just have to live with the consequences of using an old version of something. You can't blame Microsoft if you are trying to watch a blu-ray movie on Windows 95.

If there isn't a dragonAPI config from back then, the only other choice is to hope one of your players made a really bad build that is causing the lag. If so, it's a matter of finding this source of the problem, and fixing what they did wrong. ( Similar to buildcraft looping pipes. ) If there's no such bad build, it's probably a problem specific to the version, and your options are indeed update or remove the mod(s). It doesn't hurt Reika or Rotarycraft if you remove the mods, so feel free to do so.

**Comment by creeperdude400** [comment]
Alright, gonna nuke all the rotarycraft bases and then remove the mod. Gonna tell the rest of the servers on my network too.

Seriously though if you want people to use your mod you can;t pull stunts like this.

**Comment by zemerick** [comment]
A number of people tried to help in a number of ways. It's not our fault if you refuse our help. ( BTW: It's not our mod. It's Reikas. We are just trying to help him where we can, so he can focus on coding. )

Well, I think you can do the thing now Coolsquid.

**Comment by 1Matthias** [comment]
As @zemerick said, this is like asking for support, not for Windows 95, but for Windows NT 3.1. Updating would actually be very simple with the FTB launcher, as all your users would have to do is basically download v25z, click the "Edit pack" button on the FTB launcher, and remove the old versions, and put in the new. Also, they would have to get the right configs from you. This would not be very hard, nor would it take that long, even for really non tech savvy players. Also, it will be just as hard for you, if not harder, to remove RotaryCraft, than it will be to update. With this information, please reconsider.

**Comment by 1Matthias** [comment]
I have unlocked the conversation so that @creeperdude400 can respond, but being rude will result in this being locked again.

**Comment by TomeWyrm** [comment]
No matter what you do to fix this @creeperdude400, you're going to have to have your users change their mods. It is almost exactly the same effort for them to remove RoC as it would be for you to have them update to 25z, a version which is obtainable at the following link
https://sites.google.com/site/reikasminecraft/rotarycraft

Note that you will also need version 25z for 1.6.4 for each of the following mods
https://sites.google.com/site/reikasminecraft/dragonapi
https://sites.google.com/site/reikasminecraft/dyetrees
https://sites.google.com/site/reikasminecraft/electricraft
https://sites.google.com/site/reikasminecraft/expanded-redstone
https://sites.google.com/site/reikasminecraft/reactorcraft

Even easier would be having your players switch to version 1.1.2 of monster, which uses 23b of Reika's mods, though we would greatly prefer you update to 25z as technically you're ineligible for support if you're not using the latest version of Reika's mods for your version of MC, and there are a lot of bugs that were fixed between 23b and 25z.
