### ISSUE TITLE
ElectriCraft, a problem with the battery discharge

### ISSUE THREAD

**Issue by KonstantinBel** [ReikaKalseki/Reika_Mods_Issues#150]
Batteries are discharged at the same rate.
![1](https://cloud.githubusercontent.com/assets/8530829/8715657/f5d73a7e-2b9e-11e5-94e2-a77562f2ce0e.png)

**Comment by ReikaKalseki** [comment]
Battery discharge rate is fixed.

**Comment by KonstantinBel** [comment]
It's a pity (((
