### ISSUE TITLE
Structures disappear from elemental awareness ability when close

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1500]
Not sure if this intended or not but

![2017-07-06_12 22 16](https://user-images.githubusercontent.com/10777735/27921567-2cee850a-6246-11e7-85b9-568da169c32e.png)

![2017-07-06_12 26 20](https://user-images.githubusercontent.com/10777735/27921650-5cded8d2-6246-11e7-999e-885ac3698ccb.png)

![2017-07-06_12 23 43](https://user-images.githubusercontent.com/10777735/27921576-318e0450-6246-11e7-9f8f-4e4be1df5799.png)

**Comment by ReikaKalseki** [comment]
I have never seen that before.

**Comment by OvermindDL1** [comment]
> I have never seen that before.

Oh, I thought that was normal; when I get 'near' to one of the indicators it has always vanished for me too.

**Comment by ReikaKalseki** [comment]
Fixed.
