### ISSUE TITLE
Items from various mods turn based on player orientation when placed in Bibliocraft labels

### ISSUE THREAD

**Issue by novasolarius** [ReikaKalseki/Reika_Mods_Issues#1502]
*sigh* This is going to be a pain to explain. I'm using Bibliocraft labels to label my chests based on content, one of which being dedicated to Chromaticraft. I originally intended to use a manipulator as Chromaticraft's label item, but found a strange issue.

Basically, what happens is that the item doesn't always render at the same angle. Instead, the angle changes depending on the player's orientation. This has the unfortunate result of the item frequently rendering behind the label, a position generally occupied by a solid block or chest. It can also turn in such a way that the back of the item is exposed, resulting in the item becoming invisible.

I have since tested several other items, namely crystal shards, various kinds of Chromaticraft dust and the chromic lexicon, and this error occurs with all of them. Blocks render correctly, as tested with the casting table.

Edit: Hm, it appears that at least HSLA steel and the Rotarycraft, Reactorcraft and Electricraft books do the same.

Second edit: might as well include the versions of the relevant mods.
Forge: 10.13.4.1614
Bibliocraft: 1.11.7
DragonAPI: 17c
Chromaticraft: 17c
Rotarycraft: 17c
Reactorcraft: 17a
Electricraft 17a

**Comment by ReikaKalseki** [comment]
The label is rendering the item as if it was held in hand. This cannot be fixed as there is no way to tell it is not actually in hand. Additionally, in-world renders should not use that render type.

**Comment by Aivech** [comment]
I've noticed this happening with Reika's mods items in item entity form as well.

**Comment by OvermindDL1** [comment]
I'm guessing the issue is at:
https://github.com/ReikaKalseki/DragonAPI/blob/530f105290ce9338e2822f8b58f01f1f02bb79b9/Auxiliary/ReikaSpriteSheets.java#L165-L166
```java
GL11.glRotatef(180.0F - RenderManager.instance.playerViewY-90, 0.0F, 1.0F, 0.0F);
GL11.glRotatef(-RenderManager.instance.playerViewX, 1.0F, 0.0F, 0.0F);
```
The players view should in no way be part of the item rendering function (MC should have already set up your render state unless you are doing something very wrong).

**Comment by ReikaKalseki** [comment]
For the hundredth time, my items are rendered differently, and the IItemRenderer does not already have the transformations applied. So I was forced to do them manually, which for held-in-hand items includes the rotation.
