### ISSUE TITLE
Fusion Reactor Central Permanent Magnet Hub not conencting to power source

### ISSUE THREAD

**Issue by SJS184** [ReikaKalseki/Reika_Mods_Issues#1503]
i I built the central permanent magnet hub but it won't connect to bedrock shaft I even tried
 using a  van de graaff generator to power it but it would not work either 
![image](https://user-images.githubusercontent.com/11613529/27991271-0e90bbd2-643f-11e7-88ea-443a79d3750b.png)

**Comment by ReikaKalseki** [comment]
Did you build it correctly?

**Comment by SJS184** [comment]
I built it with the Hysteresis Rod in the center block of the Solenoid Hub  or was it you place the Hysteresis Rod in the bottom part of the Solenoid Hub.

**Comment by ReikaKalseki** [comment]
The hub is only two blocks thick, not three.
