### ISSUE TITLE
[Rotarycraft] Crash with ender fluid pipes connected to steam engine

### ISSUE THREAD

**Issue by Armagedon13** [ReikaKalseki/Reika_Mods_Issues#1504]
https://pastebin.com/L51PtiKx
RC: 17c
Ender io: last

**Comment by lAimBotl** [comment]
Weird, all my steam engines have ender fluid conduits attached to them

this is my eio version : EnderIO-1.7.10-2.3.0.429_beta.jar
my roc is the same as yours

**Comment by Armagedon13** [comment]
Mmm, i don't know what is the problem here,  because, the game start to crash when i put Ender Io fluids to RC steam engines. And the last modification to my Word it was, With a pickage breack "worktable and blast furnace".

**Comment by lAimBotl** [comment]
Are you just pumping water into them?

**Comment by Armagedon13** [comment]
I have a mod called "pressure pipes", has a block called "infinite water", I have connected pipes that draw water to the steam engine

**Comment by Armagedon13** [comment]
i can stay 1 or 2 minutes in my world 
http://imgur.com/a/mgIOU here the images

**Comment by lAimBotl** [comment]
Funny that is exactly what I am using too. 
you do any creative testing to confirm btw?
maybe I will see if I can get a world to crash . . .
hm maybe get the exact eio version I have, I got it off curse forge

**Comment by Armagedon13** [comment]
yes, tested, When the engine starts to run.
i have version EnderIO-1.7.10-2.3.0.429_beta.jar

**Comment by lAimBotl** [comment]
Does it still crash if you take eio roc/dragonapi and pressure pipes and put it into a instance by themselves?

**Comment by Armagedon13** [comment]
yes, i tested all, and still crashed my world
EDIT: i'm only tested with RC,ReactorC, Dragon api, pressure pipes and enderio. The game works normaly and i tested the set up and don't crash my, so... i don't know what is the real problem to the game. i wait for reika answer.

**Comment by Armagedon13** [comment]
well i solved it, it for cance the configuration for fluid extraction ender io pipes.
in the tested world works, but in my survival world it's not solved, i don't know but , i think wath is the problem

**Comment by Armagedon13** [comment]
nothing work

**Comment by ReikaKalseki** [comment]
This crash is entirely within EnderIO.

**Comment by Armagedon13** [comment]
some help?

**Comment by OvermindDL1** [comment]
@Armagedon13 

>     at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
>     at java.util.ArrayList$Itr.next(Unknown Source)
>     at com.enderio.core.common.util.Scheduler.runTasks(Scheduler.java:120)
>     at com.enderio.core.common.util.Scheduler.onClientTick(Scheduler.java:113)

This means that enderio is doing the remarkably stupid thing of adding/removing elements from an arraylist *while* they have an open iterator to that arraylist.  Report it to them.

Just looked through their code, oh holy hell the bugs pending in it that I see similar to ones here in Reika's mods, there is arraylist mutation happening through calls after calls after calls in a an iteration loop that are hell to track down.  Never ever ever ever allow any arraylist that can be iterated to be exposed publicaly and be sure to batch alterations to them for after the iteration is done (set a sentinel value and if set put 'modification commands' in another list then iterate that one to modify the main one every time an iteration of the main one is complete).

Gull, so so many mod authors do this and I have fixed so many of them, utterly tired of it, let them fix their own bugs, go report it...
