### ISSUE TITLE
RotaryCraft crashing while loading

### ISSUE THREAD

**Issue by MinCrin** [ReikaKalseki/Reika_Mods_Issues#1505]
My game crashes while loading when using RotaryCraft

https://gist.github.com/MinCrin/44488fd673b4cb4465a1c26ba1962eb8

**Comment by ReikaKalseki** [comment]
Try removing mods.

**Comment by OvermindDL1** [comment]
I'd start with removing whatever mod is `mod.mcreator`, like wtf...  Do you have two copies/versions of it installed or so or is it just weirdly bugged?

**Comment by ReikaKalseki** [comment]
Hello?

**Comment by lAimBotl** [comment]
guess he died suddenly
mod.mcreator could be a mod from (or could be) MCreator, some easy way to make mods for people who don't know code.
