### ISSUE TITLE
[Rotarycraft] [Feature Request] Screw Down Fluid Pipes

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1506]
Hi,
it would be nice to screw the fluid pipes tight.
They are made of Bedrock alloy or HSLA steel and every child without any tool can just break them faster than leafs and can destroy the entire reactor cooling or destroy expensive fluids like ammonia in one second.
Maybe it would be useful to increase the hardness to Obsidian or at least Stone via shift+ right click with the screwdriver for Pipes which i don't want to remove in the next time.
This could prevent the accidentally breaking while using a pickaxe in the near of them too.

**Comment by ReikaKalseki** [comment]
There is a config for pipe hardness.
