### ISSUE TITLE
[Versions.dat parsing error] DragonAPI error upon postinitialazation

### ISSUE THREAD

**Issue by ERYK500** [ReikaKalseki/Reika_Mods_Issues#1507]
I think error might been a cause of me disabling auto update checking on all mods DragonAPI checks and it throws a error when 5 part of MC startup starts. However there might be a typo in the code look at the seventh line of the crash report, either it has extra '[' or it is missing ']'. (My English isn't that great.)

[crash-2017-07-10_20.19.01-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1136634/crash-2017-07-10_20.19.01-client.txt)

**Comment by ReikaKalseki** [comment]
Try deleting /config/versions.dat.

**Comment by ERYK500** [comment]
I don't have that File (.minecraft/config/versions.dat)

**Comment by ERYK500** [comment]
It didn't exist already.

**Comment by ReikaKalseki** [comment]
And /saves/DragonAPI/ucheck.dat?

**Comment by ReikaKalseki** [comment]
Also hopefully fixed.

**Comment by ERYK500** [comment]
It is fixed, thank you for help.
