### ISSUE TITLE
[RotaryCraft/ChromatiCraft] Killing Ender Dragon with RailGun does not unlock CC progression

### ISSUE THREAD

**Issue by cyip92** [ReikaKalseki/Reika_Mods_Issues#1509]
Killing the Ender Dragon with a RailGun crafted and placed in survival mode doesn't count as killing for the purposes of ChromatiCraft progression.  I was able to replicate this in a fresh world by doing the following:
1. In creative mode, I did the minimal prerequisites for the Dragon progression ("World Floor", "The Evil Realm", "Monster Slayer")
2. I built an end portal and went into it.  Upon arrival, the End progression ("The Alien Realm") was unlocked.
3. At this point, I spawned in a few RC items, copied the world save, and changed to survival mode.  Then...
- Player Kill world: One-hit kill with a spawned-in Gravel Gun.   Dragon-killing CC progression ("Aerial Predator") was unlocked.
- RailGun Kill world: Crafted a new RailGun, placed down a Gas Turbine and connected up some shafts and the RailGun.  Then I inserted some ammo and started the turbine up.  It also killed the dragon, but the CC progression did _not_ show up.

(Yes, I was definitely aiming for the achievement.  I can confirm that part worked in my survival world!)

**Comment by ReikaKalseki** [comment]
Done.
