### ISSUE TITLE
ElectriCraft, source-to-motor calculations

### ISSUE THREAD

**Issue by KonstantinBel** [ReikaKalseki/Reika_Mods_Issues#151]
I use ElectriCraft V7e. Motor-to-motor connection have the same problem.
![2](https://cloud.githubusercontent.com/assets/8530829/8715711/b4fe352e-2b9f-11e5-8459-8a07132a5902.png)
![3](https://cloud.githubusercontent.com/assets/8530829/8715712/b500d5a4-2b9f-11e5-98c2-072ea311fd56.png)

**Comment by ReikaKalseki** [comment]
Fixed.

Also, I am amazed this has gone on so long unnoticed - it has been present since ElC was written.

**Comment by Fatmice** [comment]
I told you about it long before this guy did.  You just never did anything about it.  Your retort was something along the line that it splits amp among sinks evenly then restrict flow according to resistor.  If flow is less than resistor allowance, then it will let it pass.

**Comment by ReikaKalseki** [comment]
That is the main behavior, but the problem was actually not related to that. The problem was that limited paths were not considered valid for "spillover" current.

**Comment by Fatmice** [comment]
I told you about that too =P.  Oh well, I'm glad it is fixed now.

**Comment by ReikaKalseki** [comment]
> I told you about that too =P

I have no memory of this...
