### ISSUE TITLE
DragonAPI V17c crashed on server

### ISSUE THREAD

**Issue by shagejack** [ReikaKalseki/Reika_Mods_Issues#1511]
What cause it and how can i fix it?

Crash-Report:
https://pastebin.com/teRYq9bD

**Comment by shagejack** [comment]
I see. Close this issues please.

**Comment by shagejack** [comment]
But i remember that the problem doesn't happen when i using v15a. Why don't put the older version on curse?

**Comment by ReikaKalseki** [comment]
Update everything, including Forge.

**Comment by 1Matthias** [comment]
@ReikaKalseki This might be the problem. 
Details:
    Minecraft Version: 1.7.10
    KCauldron Version: pw.prok:KCauldron:1.7.10-1614.170
