### ISSUE TITLE
Chromaticraft Registration Error

### ISSUE THREAD

**Issue by ryu777mtg** [ReikaKalseki/Reika_Mods_Issues#1513]
Game crashes with Chromaticraft Registration Error

Reika.DragonAPI.Exception.RegistrationException: CHROMATICRAFT has a registration error:
Failed to load REPEATERLAMP due to a missing class: java.lang.NoClassDefFoundError: Reika/ChromatiCraft/TileEntity/Transport/TileEntityRift
Contact Reika immediately!

Here is the full error in a paste.ee link expires within 1 month
https://paste.ee/p/7Oohp

**Comment by ReikaKalseki** [comment]
#1450

**Comment by ryu777mtg** [comment]
Ah thanks for the insight so it's just API issues.

Any idea how I would be able to modify the .jar files and use them with Curse/Twitch uploads considering the MD5 and SHA changes.

When that happens usually modpacks get denied due to the mismatch. The only other way is to hopefully get the mod author to make a release of a newer version that fixes the issue and that could take some time just thought I'd ask.

Also thanks for the quick reply I most definitely sure it's old API of Thaumic Energistic or similar mod in my list.

**Comment by ReikaKalseki** [comment]
Try removing mods to see.

**Comment by ryu777mtg** [comment]
Yeah I have deduced it to Dimensional Pockets newest version.
It has outdated OC API

Within Dimensional Pockets archive
/li/cif/oc/api/

**Comment by ReikaKalseki** [comment]
Delete it from that mod's jar.

**Comment by ryu777mtg** [comment]
I know that I was asking how to get it to be compatible for upload to Curse/Twitch

They will not accept .jar changes from 3rd party

**Comment by ReikaKalseki** [comment]
You have no recourse for that other than removing Dimensional Pockets from your pack.

**Comment by OvermindDL1** [comment]
> I know that I was asking how to get it to be compatible for upload to Curse/Twitch

Simple, don't use Curse/Twitch, they are an absolutely horrible service.

**Comment by ReikaKalseki** [comment]
> Simple, don't use Curse/Twitch, they are an absolutely horrible service

However, not allowing third-party modified jars is not a reason for that. Nine times out of ten such a jar has been tampered with for malicious purposes.

**Comment by OvermindDL1** [comment]
> Nine times out of ten such a jar has been tampered with for malicious purposes.

That is why mod authors should sign their jar's so they don't load if they've been tampered/broken as such.  FML added that functionality for a reason.

**Comment by ryu777mtg** [comment]
Look the issue has been resolved no need to talk so much about nothing or what is already common knowledge....

I came here to resolve a problem not start a dispute.

I've already contacted NPException

> NPException
> 
> Posted 16 hours ago
> I'll take a look when I'm back home. With a bit of luck it's an easy fix. No promises though.
>  Report   Reply   Quote   Multi-quote
> 
> ﻿
> ryu777mtg
> 
> Posted 14 hours ago
> Alright hope it's manageable
> 
> Thanks for the response
>  Report   Reply   Quote   Multi-quote

**Comment by ReikaKalseki** [comment]
> FML added that functionality for a reason.

It barely works, and most people - Lex included - harshly frown on its use.

**Comment by OvermindDL1** [comment]
> It barely works, and most people - Lex included - harshly frown on its use.

Lex is not the shining example here, cpw is the one that worked in the industry, and it did work quite well for doing what it was supposed to, ensuring non-corruption.  People could still override it if necessary, but it caught the stupid stuff.  :-)

**Comment by ReikaKalseki** [comment]
> Lex is not the shining example here, cpw is the one that worked in the industry, and it did work quite well for doing what it was supposed to, ensuring non-corruption. People could still override it if necessary, but it caught the stupid stuff. :-)

It does not change the fact that even *mentioning* using it draws ire from 40+ people, many in high places.

**Comment by OvermindDL1** [comment]
> It does not change the fact that even mentioning using it draws ire from 40+ people, many in high places.

And that is only because the general person is stupid and does not do research.  When it was first announced when the ability was added by CPW a few notable idiots in the community yelled about how it was DRM (interesting DRM when it had an option to disable...) and a lot of people took that up.  It's purpose was for jar verification to make sure it was not tampered (important for modpacks to ensure the clients matched the server in code), but it was trivially disableable on an either per-jar basis or in an entire install.

**Comment by NPException** [comment]
Just wanted to give an update from my side. I updated Dimensional Pockets.
Stupid past me was unnecessarily shipping the OC API within my .jar, even though I was already using the `@Optional` anotations for it.

**Comment by OvermindDL1** [comment]
> Just wanted to give an update from my side. I updated Dimensional Pockets.
> Stupid past me was unnecessarily shipping the OC API within my .jar, even though I was already using the @Optional anotations for it.

Ooo was it dimensional pockets?  I've never used that mod, I should take a look at it.  :-)
