### ISSUE TITLE
[CC] Pressing "e" while typing a file name for the Crystal Orchestra closes the menu

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#1515]
This makes it impossible to import files with the letter "e" in the path without copy/pasting from an external source. An easy way to fix this would be to add an exit button instead for that menu.

**Comment by ReikaKalseki** [comment]
Use copy-paste. Adding a 'close' button will not prevent the inventory key from closing the GUI.

EDIT:
Maybe I might be able to intercept it...maybe.

**Comment by ReikaKalseki** [comment]
Done.
