### ISSUE TITLE
[Chromaticraft] UnknownArtefact is not generated?

### ISSUE THREAD

**Issue by Mr-kk** [ReikaKalseki/Reika_Mods_Issues#1516]
Although it may be wrong, it seems that UnknownArtefact will not be generated for the following reasons.

1. When we look at UnknownArtefact creation condition, we monitor it with tick function in ArtefactSpawner.java and generate it if "canSpawnArtefactNearPlayer == true".
When tracing to the end, it is "UAChunks.contains (Player.x, Player.z)" of "UnknownArtefactGenerator.java".
However, since the "RetroGenController.instance.addHybridGenerator (UnknownArtefactGenerator.instance ...)" is commented out at present, the generate function is not called and UAChunks appears to be empty.

2. Looking at UnknownArtefact creation condition, it is monitored by the tick function in ArtefactSpawner.java and generated when "UnknownArtefactGenerator.canGenerateArtefactAt == true".
Here, looking at the canGenerateArtefactAt function, it is as follows.

```
public static boolean canGenerateArtefactAt(World world, int x, int y, int z) {
		Block b = world.getBlock(x, y, z);
		if (b != Blocks.dirt && b != Blocks.grass)
			return false;
		if (!world.getBlock(x, y+1, z).isAir(world, x, y+1, z))
			return false;
		if (world.getBlock(x, y-1, z) != Blocks.dirt)
			return false;
		for (int i = 0; i < 6; i++) {
			ForgeDirection dir = ForgeDirection.VALID_DIRECTIONS[i];
			if (dir != ForgeDirection.UP) {
				for (int d = 1; d <= 3; d++) {
					int dx = x+dir.offsetX*d;
					int dy = y+dir.offsetY*d;
					int dz = z+dir.offsetZ*d;
					if (!world.getBlock(dx, dy, dz).isAir(world, dx, dy, dz))
						return false;
				}
			}
		}
		return true;
}
```
Here, it says "if (world.getBlock (x, y - 1, z)! = Blocks.dirt) return false", and"if (!world.getBlock(dx, dy, dz).isAir(world, dx, dy, dz)) return false". Y-1 is not soil, and it is not air.

Version
MC1.7.10 SMP
ModList
Forge10.13.4.1614
DragonAPI v17c
ChromatiCraft v17c

**Comment by ReikaKalseki** [comment]
You do not understand how the artefacts are supposed to generate (1) and I know this works as have tested it (2).

**Comment by Mr-kk** [comment]
I understand. I will check again.
However, to me, it seems that "HashSet <ChunkCoordIntPair> UAChunks.add ()" pointing to the place where UA is generated will not be executed.

**Comment by ReikaKalseki** [comment]
Not in the IWG, because that was removed in favor of another method.

**Comment by Mr-kk** [comment]
I do not understand enough so please tell me.

UA manages generation with ArtefactSpawner.java.
In that procedure,
① Player's block destruction event (checkPlayerBreak is executed from the server side)
② If "UnknownArtefactGenerator.instance.isUAChunk" is true send a packet to the client side
③ Execute "checkPlayerBreakClient" on the client side and send a packet to the server side if "isOnTopOfArtefact" is true (isOnTopOfArtefact checks whether the coordinates under the broken block are included in "ArrayList <SpawnedArtefact> artefacts")
④ Execute "confirmUA" on the server side and set UA to the coordinates of the broken block.

Is there sometime when "UnknownArtefactGenerator.instance.isUAChunk" in ② becomes true?
In this method, it is "return this.canGenerateIn (world) && UAChunks.contains (new ChunkCoordIntPair (cx, cz));" but UAChunks.add is executed only by "calculateUAChunks" There is a need for "IWorldGenerator.generate" to be executed.
How is this done?

**Comment by ReikaKalseki** [comment]
Read the rest of `ArtefactSpawner.java`. Also, what chunks are UA candidates are not determined by the UA spawner or the generator, but something else entirely.

**Comment by Mr-kk** [comment]
is that true? I tried searching for that treatment today but could not find it. Is it a process involving Dragon API? I will look for it a little more. Thank you for your response.

**Comment by Mr-kk** [comment]
Is UnknownArtefact properly generated even in the new world?

As expected, have you run the 495th line of ChromatiCraft.java in the past in Reika's development environment?
(RetroGenController.instance.addHybridGenerator (UnknownArtefactGenerator.instance ~)
Then would RetroGenController record UnknownArtefactGenerator to be invoked later?

Therefore, in Reika's development environment UnknownArtefact is generated, but it seems not to be generated in the new world.

**Comment by ReikaKalseki** [comment]
UnknownArtefactGenerator is never run. This is not a bug. As I said before.

**Comment by Mr-kk** [comment]
If so, each method of ArtefactSpawner calls UnknownArtefactGenerator.instance.isUAChunk () like the [first image](https://gyazo.com/f65730012e29a2f12d818eff65b4469e), is it true?

Like the [second image](https://gyazo.com/ecc12584f362aeeabe0ec7445b714a4b), UnknownArtefactGenerator.instance.isUAChunk () checks canGenerateIn () & UAChunks.contains ().

As in the [third image](https://gyazo.com/6cd9578dcf14b5bc4673464f73fb8457), is UAChunks empty unless calculateUAChunks () is executed?
Then UnknownArtefactGenerator.generate () should be executed.

**Comment by ReikaKalseki** [comment]
There is a lazyloader to populate the cache.
