### ISSUE TITLE
(Rotarcraft) (Suggestion) Flame thrower turret

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1517]
I have noticed that most turret mods seem to forget the flamethrower . . .

It could be filled with ethanol or jet fuel to work maybe even nitrogen/oxygen.
Range: 20 blocks (based off of m2 flamethrower).

Possible recipe:
,Reservoir ,Compressor(Or if oxygen/nitrogen:pipe) ,Sintered tungsten
,Fuel pipe ,Ignition unit ,Heat ray barrel
,Reservoir ,Shaft ,Turret Aiming unit

**Comment by ReikaKalseki** [comment]
That could be quite fun...

![](https://i.redd.it/as42k5wgs25z.png)

**Comment by lAimBotl** [comment]
heh maybe I could brush up on my 3d skillz and make a model for it lol or at least a rough draft

**Comment by Aivech** [comment]
While Factorio's aesthetics hardly fit with Rotarycraft, a handheld flamer to go with it would also be awesome.

It would probably run on jet fuel, because that's basically kerosene?

**Comment by ReikaKalseki** [comment]
![http://i.imgur.com/TKTqETQ.png](http://i.imgur.com/TKTqETQ.png)
![http://i.imgur.com/VlUSeB1.jpg](http://i.imgur.com/VlUSeB1.jpg)
![http://i.imgur.com/GoedAWR.jpg](http://i.imgur.com/GoedAWR.jpg)
