### ISSUE TITLE
DragonAPI Update Error

### ISSUE THREAD

**Issue by EbonyDean** [ReikaKalseki/Reika_Mods_Issues#1518]
This crash happened twice during loading. I deleted the DragonAPI Save file that seemed related to update, just in case that caused the issue. Deleting the file allowed me to load the game. For further info: It stopped loading during phase 5 of Forge Loading.

This started happening after a crash when returning from an RFTools dimension, but that crash is not related to this.

https://pastebin.com/heGBBd73

**Comment by ReikaKalseki** [comment]
#1507
