### ISSUE TITLE
Cannot connect shafts through Mystcraft portals

### ISSUE THREAD

**Issue by raelik** [ReikaKalseki/Reika_Mods_Issues#1519]
I'm not sure if I'm doing something wrong with this, but I have my two portals (one in the Overworld, one in the Mystcraft age) at exactly the same coordinates, built the same size and orientation, and I cannot seem to get power to transfer from my Mystcraft age to the Overworld. The output side of the shaft providing power is against one of the portal block faces, and that extends the shaft into the portal. I placed the receiving shaft on the opposite side of the corresponding portal block on the other portal, with the input side facing the portal block, and no power is transmitted. I've tried various combinations of link book locations (near the portal, on top of the portal frame, within the portal itself), nothing helps.  All chunks are chunk loaded (FTB Utilities), and the portals are contained entirely within a single chunk, and the link book locations are linked to a coordinate in that chunk.

**Comment by ReikaKalseki** [comment]
Do other portal types work? I tested Nether ones recently.

**Comment by raelik** [comment]
No idea, haven't tried one. I'll do that right now.

**Comment by raelik** [comment]
No, it doesn't work with Nether portals either.  When I place the receiving shaft with the input side against the portal face, it doesn't extend a shaft into it.  I wasn't sure if that was supposed to happen on both ends.

**Comment by raelik** [comment]
Figured I should add that this is with Mystcraft version 1.7.10-0.12.3.02

**Comment by ReikaKalseki** [comment]
If Nether portals do not work either, the issue is not the MystCraft handling.

**Comment by raelik** [comment]
I didn't expect that it was, just being thorough.

**Comment by ReikaKalseki** [comment]
Fixed.

![http://i.imgur.com/djwNWE8.png](http://i.imgur.com/djwNWE8.png)

**Comment by raelik** [comment]
Figured for completeness I'd note that this is definitely fixed. :+1:
