### ISSUE TITLE
Class cast exception when breaking blocks on turbine

### ISSUE THREAD

**Issue by DarkGuardsman** [ReikaKalseki/Reika_Mods_Issues#152]
Was helping someone figure out an issue with a turbine. After I broke a few blocks I got this exception. 

http://pastebin.com/Sa7PSDxG

The solution looks like it calls for an instanceof check around this line of code
https://github.com/ReikaKalseki/ReactorCraft/blob/master/Blocks/Multi/BlockTurbineMulti.java#L249

**Comment by ReikaKalseki** [comment]
Fixed.
