### ISSUE TITLE
[Chromaticraft] Missing Requires for Inventory Simulator

### ISSUE THREAD

**Issue by chaos234** [ReikaKalseki/Reika_Mods_Issues#1521]
Hey Reika,

will be glad if you can fix the problem shown in the image below: https://puu.sh/wSEJF.png
Can you tell me what this block requires to work or if it's fully implemented? Sometimes also I have some "#null" messages which I'll collect and add them here.

Version: latest available Version of CrC

**Comment by chaos234** [comment]
Here are som other #NULL! Messages:

Enchantments Fragment: https://puu.sh/wT5tS.png
Village Replanisher Frargment: https://puu.sh/wT5LN.png (Text overlaps a bit and since it isn't currently implemented with a casting recipe it is only a hint ;) )

If I finde more while I am exploring the mod I'll post the next ones :)

**Comment by ReikaKalseki** [comment]
The Village Replenisher is unfinished.

**Comment by ReikaKalseki** [comment]
Fixed.
