### ISSUE TITLE
[Request|RoC] Smelting Flakes in TiC Smeltery

### ISSUE THREAD

**Issue by chaos234** [ReikaKalseki/Reika_Mods_Issues#1523]
Hey,

I wondered why the flakes are not smeltable in the TiC semltery so I used CraftTweaker to add them with the values like the ingots are molten.

But after reloading it the lines got commented out from DragonAPI meaning that it is not wanted what I not understand, since smelting in a furnace or in the smeltery is the same because of it's output.

Please add the Flakes to the Smeltery since they give you mostly the same output like a molten ingot it does (e. g. Iron Ore Flakes = Iron Ingot = 144mB Molten Iron). So it does not matter if they are smelted in a furnace or in the smeltery but as I use the smeltery as my central alloying part it will be good if they are also smeltable in the TiC Smeltery.

**Comment by ReikaKalseki** [comment]
They are supposed to be smeltable there already.

**Comment by chaos234** [comment]
Well, but they are not listed over NEI - e. g. the iron flakes - nor does the smeltery start melting them.
If I am back again I'll make a short video with a few flakes and link it here :)

**Comment by chaos234** [comment]
Here the video like staded: https://youtu.be/sxWT0MFSvUQ - I hope my spoken englisch is not to bad ^^

**Comment by ReikaKalseki** [comment]
Done.

Also, your English is fine (what is it with people from Germany having better English than a lot of native speakers yet thinking it is bad? :P). Though "NEI" is usually pronounced with each letter separately, not "nye".

**Comment by chaos234** [comment]
Thanks for your respons and for fixing it :)
