### ISSUE TITLE
AC engine starts without nothing

### ISSUE THREAD

**Issue by traso56** [ReikaKalseki/Reika_Mods_Issues#1524]
after magnetizing a shaft core to use in the AC engine it just started without redstone nor the shaft

http://i.imgur.com/l3xOqgz.png

it is completley empty and no redstone clock

**Comment by waterlubber** [comment]
If  I remember correctly, walking near the engine with the shaft in your inventory will cause it to operate.

This may have been changed, but I think it is still implemented.

**Comment by traso56** [comment]
okey but why it operates without AC signal?

**Comment by ReikaKalseki** [comment]
https://en.wikipedia.org/wiki/Faraday%27s_law_of_induction

**Comment by traso56** [comment]
i believe the shaft core is one of these

http://www.cnczone.com/forums/attachment.php?attachmentid=296036&d=1445948469&thumb=1

i may be wrong but i don't think a motor can run without one since it is what actually produces movement
