### ISSUE TITLE
[CrC] Splash Gun kills players without PvP enabled on server

### ISSUE THREAD

**Issue by chaos234** [ReikaKalseki/Reika_Mods_Issues#1525]
I have disabled pvp to test the Chain Gun and the Splash Gun server side and the Splash Gun does damage to the player which is within it's radius but the Chain Gun isn't hurting the Player so I assume that it maybe is a bug.

Also why does the Splash Gun the damage effect to the player who activates it but without hurting this player? Is a bit confusing.

**Comment by ReikaKalseki** [comment]
Fixed.
