### ISSUE TITLE
Sprinkler won't work if connected to a bedrock pipe roc v17c

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1526]
Sprinkler won't work if connected to a bedrock pipe 

![2017-07-27_18 19 50](https://user-images.githubusercontent.com/10777735/28694550-4c95d300-72f8-11e7-91bb-66f436f0dcc2.png)

![2017-07-27_18 19 58](https://user-images.githubusercontent.com/10777735/28694552-4f972824-72f8-11e7-8624-bce3f0f99d96.png)

**Comment by ReikaKalseki** [comment]
Yet it visually connects, implying something deeper is at work...

**Comment by lAimBotl** [comment]
maybe its pressure/something compared to the pipe er like how "full" it is

**Comment by ReikaKalseki** [comment]
Fixed.
