### ISSUE TITLE
Jetpack upgrades don't respect worktable config change

### ISSUE THREAD

**Issue by gr8pefish** [ReikaKalseki/Reika_Mods_Issues#1527]
If the config option is changed to allow crafting of items in a normal crafting table, i.e.: `B:"Crafting Table can Make Machines"=true`, the player will expect everything can be crafted in a normal crafting table. The jetpack can be, but you _cannot apply the jetpack upgrades in a normal crafting table_ (it has to be in a workbench). I think it would be more clear to keep it consistent, and it should be a relatively simple fix.

Thanks for the great mod by the way, I'm finally getting the chance to play through RC, CC, and your other mods and am loving it! I, among others, would love to see it on newer MC versions, but simultaneously completely understand why you are not (heck I'm having difficulty finding the motivation to do it for mine, and my mods are barely a small fraction as large as yours). Anyways, I sincerely love the work you do, so thanks!

**Comment by ReikaKalseki** [comment]
The jetpack is not a normal recipe, and vanilla crafting does not support NBT.

**Comment by OvermindDL1** [comment]
> The jetpack is not a normal recipe, and vanilla crafting does not support NBT.

Well it 'can' if you make a custom recipe handler.  Just not via the normal classes.

**Comment by gr8pefish** [comment]
^ Yup, it's not that hard either, I can speak from personal experience.

Either way it's not a huge deal, but I still feel as if it will confuse players needlessly if it is kept this way.

**Comment by ReikaKalseki** [comment]
> Well it 'can' if you make a custom recipe handler. Just not via the normal classes.

I have never had a custom recipe handler work.

**Comment by gr8pefish** [comment]
[Here](https://github.com/gr8pefish/IronBackpacks/blob/master-1.7.10/src/main/java/main/ironbackpacks/crafting/BackpackIncreaseTierRecipe.java#L29) is an example of an IRecipe for Iron Backpacks where a backpack can be crafted to a higher tier while keeping its old contents and upgrades (i.e. new NBT data with old NBT data persisting). It's registered [here](https://github.com/gr8pefish/IronBackpacks/blob/master-1.7.10/src/main/java/main/ironbackpacks/crafting/ItemRecipeRegistry.java#L99) (sorry for the abstraction, don't have a clearer example handy).

I would think about doing a PR for you, but I read your stance on them, so I'll just be available for help if needed (I'm on discord as well).

**Comment by ReikaKalseki** [comment]
So a custom recipe *object*, not a handler. That will at least be more reliable.

**Comment by gr8pefish** [comment]
Yes, correct. Sorry for the poor terminology. 

Once again, feel free to let me know if you need anything else.

**Comment by ReikaKalseki** [comment]
I know how this would be implemented; I am just debating whether it is worth the effort.

**Comment by gr8pefish** [comment]
True, it's a small thing. As long as you document it somewhere (e.g. in the handbook, or perhaps even as a comment in that config option) that could work as well; it was more of a "_why_ isn't this working" than an "it should work _this_ way" (if that makes sense).

**Comment by ReikaKalseki** [comment]
Is it not in the handbook already?

**Comment by OvermindDL1** [comment]
> So a custom recipe object, not a handler. That will at least be more reliable.

Er, yes, it was called IRecipeHandler in older MC code.  It is what allows you to make any kind of recipe you want for normal recipe crafting.  You have to be sure to 'do things right' or things that autocraft, like ME can break on it, but it is not hard to do it right.

A nice effect of it, you can put all your recipes in a hash based recipe lookup handler and you can have MC skip its entire *linear* recipe lookup.  Those mods that add 500k recipes (GT5) switched to using a hashmap lookup handler so as to have no speed cost.  But even installing a ton of mods that use a lot of vanilla recipes can still get the recipe lookups to be deathly slow, freezing the game on every craft.

_/me thinks that MC using a linear recipe lookup structure is utterly and beyond *stupid*_

**Comment by gr8pefish** [comment]
I think we may have gotten a little off track here. After reconsideration, this is a non-issue, it's minor enough that drawing your attention away from other things isn't worth it.

Yes, it is in the handbook. I read it, but not carefully enough it seems. It could be slightly clearer, but honestly at this point I'd say just ignore this issue and leave it closed (and I'll stop posting here so as to not give any notifications). I thought it would be a trivial little change, but it's trickier than I thought and more work than it's worth, so leaving it as-is seems to be just fine and dandy.
