### ISSUE TITLE
Projector Wont show anything no matter what

### ISSUE THREAD

**Issue by RezaSmith** [ReikaKalseki/Reika_Mods_Issues#1529]
i tried everything , and yes it is powered but it doesnt show anything , i've seen some youtube videos but not even the string thingys get connected . help please
btw im playing on Multiplayer server ( tried on SP also) .
the back contains basically infinity evolved pack + rotarycraft

**Comment by RezaSmith** [comment]
update : the thing is , it doesnt show anything instantly , but when i left the server for like 10minutes or so and came back , it was displaying , but if i break it place it there again it wont show again , whats happening?

**Comment by ReikaKalseki** [comment]
You did not build a correct screen. I just tested and it works fine.

**Comment by RezaSmith** [comment]
would you mind tell me what is wrong? the problem is when i left the server for 10 minutes and come back it works perfectly , but if i break it and place it in the exact same place it will stop working

**Comment by ReikaKalseki** [comment]
This is the correct setup:

![](http://vignette1.wikia.nocookie.net/rotarycraft/images/f/fa/2013-12-15_04.36.41.png/revision/latest?cb=20131215094002)
