### ISSUE TITLE
[Rotary][Enhancement] Move higher gear units itemstack counter to other side

### ISSUE THREAD

**Issue by gr8pefish** [ReikaKalseki/Reika_Mods_Issues#1530]
Instead of a 4x gear looking like [G^4], with the 4 in the bottom right, would it be possible to move that 4 to the bottom left so that it doesn't overlap with the Vanilla stack size number? 

[Here](http://i.imgur.com/AROYheY.png) is a picture to demonstrate the issue, and my fix suggestions should be semi-obvious. I don't know if it is a dynamically generated number via code, or on the texture directly, but either way moving it over a few pixels shouldn't be too tricky (in theory).

Thanks!

**Comment by 1Matthias** [comment]
Er...That number doesn't exist on my instance. Have you tried checking your texture pack? EDIT: What the gears look like for me: http://i.imgur.com/ptk2lFY.png

**Comment by HellsingDarge** [comment]
If you're using Unity Resource Pack - it's pack's problem, not the mod itself

**Comment by ReikaKalseki** [comment]
And this is why I was unhappy with that texture pack. Does the author have an account here?

**Comment by HellsingDarge** [comment]
Yes - CyanideX

**Comment by ReikaKalseki** [comment]
@CyanideX: Remember when I said this would happen?

**Comment by CyanideX** [comment]
@ReikaKalseki I don't remember you ever saying that to me but **_WOW_**... was I drunk when I did that? I wasn't thinking at all. 😕

**Comment by ReikaKalseki** [comment]
About 1.5 years ago, when you first released those textures (shortly before the "why does the floodlight have thin ridges on it" twitter post) and someone showed them to me. I said (probably also on Twitter, which I remember given my distaste for the platform) it conflicted with the stack size. I do not remember if I got a response, but if I did, it was obviously "it will be fine".

**Comment by CyanideX** [comment]
It definitely wasn't an "it will be fine". In fact, it bothered me so much just now that[ I had to fix it](https://github.com/CyanideX/Unity/commit/517bc605c8eefb871f7453dfeccb1371eb27992c). 😛 

I would probably redo the textures to not have the numbers if I were to ever update them.

**Comment by gr8pefish** [comment]
Sweet, thanks @CyanideX 

Sorry, didn't think about it being a texture pack thing @ReikaKalseki. Glad it was an easy solution.
