### ISSUE TITLE
[Rotary][Enhancement] Toggle jetpack's glider

### ISSUE THREAD

**Issue by gr8pefish** [ReikaKalseki/Reika_Mods_Issues#1531]
The glider is amazing most of the time, but can definitely be a hindrance at times (e.g. when a mob hits you you get knocked up and glide forward back into them). As far as I know, there is no way to remove an upgrade, so having the ability to toggle the glider (and possibly perhaps the jet boost as well) would be a welcome addition. 

This could be accomplished via a keybinding, or the way to remove/disable an upgrade, or something else you may think of; whatever is easiest for you.

**Comment by ReikaKalseki** [comment]
I have no interest in adding one more keybinding to the cancer that is the 2700 keybindings in a large modpack.

**Comment by 1Matthias** [comment]
Actually, I agree with this. I have the RoC jetpack w/ glider, and although the glider is awesome, it can also be a pain. (Going down ladders/stairs is a good example.) Edit: Also, I keep getting trapped in the rafters of my factory (Immersive engineering scaffolding) because the glider forces you up ladders or any block that acts like a ladder. Amusing though it's, it's also very annoying.

**Comment by gr8pefish** [comment]
Yes, I agree that key bindings can be a pain. Here's an alternate suggestion:

- Shift right click the jetpack (as an ItemStack) to simply toggle between glider enabled and disabled.

**Comment by ReikaKalseki** [comment]
That is a better solution.

**Comment by 1Matthias** [comment]
Hmm. Only thing with that is, it requires taking the jetpack etc off, then putting it back on, then taking it back off, etc. I can easily see that getting more annoying than a keybinding.

**Comment by ReikaKalseki** [comment]
I do not expect you will need to toggle it that frequently. Also, it has already been implemented.

**Comment by gr8pefish** [comment]
Sweet, thanks Reika!

**Comment by 1Matthias** [comment]
Er.. I can definitely see toggling it about once every minute or more in my instance.

**Comment by gr8pefish** [comment]
Yes, it's not perfect, and personally I'd like a keybind too, but it's ultimately up to Reika. And this is much better than nothing!

The problem is that having the toggle functionality without removing the pack and without a keybind is near impossible. If you can think of another suggestion that may work then say it, but I can't think of a workaround with those constraints.

**Comment by 1Matthias** [comment]
Would it be possible (Just throwing the idea out there) to have a config option for remove and toggle vs keybinding?

**Comment by ReikaKalseki** [comment]
No. It is too much work for something that has no business existing in the first place.
