### ISSUE TITLE
[Rotary][Suggestion] Filling Station via buckets

### ISSUE THREAD

**Issue by gr8pefish** [ReikaKalseki/Reika_Mods_Issues#1532]
It would be nice to be able to fill the FIlling Station via a simple right click with a bucket of a valid fluid (ethanol, jet fluid, liquid nitrogen, etc.) instead of mandating that it be pumped in via pipes. Alternatively, you could allow one of the "filling slots" to work as a way to empty a bucket into the station. 

Essentially if I have a bucket of fluid I would like to be able to put it into the filling station directly, without resorting to pipes.

P.S. I hope GH issues are the right place for these, I wasn't entirely sure if I should put it here or on the MCF forums.

**Comment by gr8pefish** [comment]
Ignore me, it has to be powered. Sorry, creative testing.

To be fair, it's not documented in the handbook, but it's more user error than anything else.

Edit: Well the direct right click doesn't work (you may want to still change that), but you can still get liquid from a bucket to the station via a slot.

**Comment by ReikaKalseki** [comment]
This is how it has always been intended to work.

**Comment by gr8pefish** [comment]
Okay, as long as that's what you intended it should be fine.

Thank you for your patience by the way! I'm enjoying exploring the mod, but instinctively have an eye out for bugs/changes/improvements (as that's what I do with my own mods) and don't hesitate to report them most of the time.

**Comment by ReikaKalseki** [comment]
> Thank you for your patience by the way!

*That* is a first. :P

**Comment by gr8pefish** [comment]
Hehe, I like to err on the side of politeness :)
