### ISSUE TITLE
A bug with chroma dim maze

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#1533]
This maze is solid,This bug occurs on two servers,they are all use 17c,and i'm sorry my english is very bad
![tim 20170801101041](https://user-images.githubusercontent.com/19620848/28806746-40f9015c-76a4-11e7-9bb4-efc69e4f28c2.jpg)
![tim 20170801101049](https://user-images.githubusercontent.com/19620848/28806747-41002298-76a4-11e7-87bf-967882c89b14.jpg)
![2017-08-01_10 22 58](https://user-images.githubusercontent.com/19620848/28806768-5a52cf20-76a4-11e7-9d58-a03ce3073f3b.png)
![2017-08-01_10 23 11](https://user-images.githubusercontent.com/19620848/28806767-5a52a22a-76a4-11e7-9682-ed75e1c97e23.png)
![2017-08-01_10 26 02](https://user-images.githubusercontent.com/19620848/28806769-5a6a3e26-76a4-11e7-97cd-7b7fff67dba9.png)

**Comment by ReikaKalseki** [comment]
#1481

**Comment by KuroPeach** [comment]
New bug at my friends servers,the keys can't open door.@ReikaKalseki 
first time
![tim 20170801205011](https://user-images.githubusercontent.com/19620848/28826150-8d0657a0-76fb-11e7-92ea-d2025f2f6347.jpg)

second time
![tim 20170801204621](https://user-images.githubusercontent.com/19620848/28826166-9e826226-76fb-11e7-9200-bb85d53cb2fc.jpg)

**Comment by ReikaKalseki** [comment]
Was the dimension unloaded/exited at any point?

**Comment by KuroPeach** [comment]
yep,but it not always have this bug

**Comment by ReikaKalseki** [comment]
Unloading the dimension clears the puzzles from memory. If the chunks fail to delete for whatever reason, you will be left with a nonfunctional structure.

**Comment by KuroPeach** [comment]
emmm,I've understood the wrong meaning before,he not leaving this dim,this bug happen at any point,Forgive me for this bad grammar

**Comment by yuanjie000** [comment]
Let me correct his words.
When my friend put the **lock key** in the **shield**, the **color lock** did not open sometimes.
As the @Leaveleaf  picture shows 
This looks like an accident.
He does not leave the **proxima** dimension during this time.
Sorry for the poor English.     _(:з」∠)_

**Comment by ReikaKalseki** [comment]
I have never seen this happen without the dimension being unloaded at some point. Easy way to verify: Does the Elemental Sonar ability show the structure here or far away?

**Comment by KuroPeach** [comment]
Elemental Sonar It's normal,this bug happen again at other point,I don't know what's going on,because i told he don't do something at first time (:з」∠)
![tim 20170803080149](https://user-images.githubusercontent.com/19620848/28900265-918bc3c8-7822-11e7-845e-d3aa2102ea64.jpg)
