### ISSUE TITLE
Using GeoStrata stairs on partial bound blocks crashes the client

### ISSUE THREAD

**Issue by kenish25** [ReikaKalseki/Reika_Mods_Issues#1534]
relevant portion of the log

[B#349]  [16:59:52] [Client thread/FATAL]: Unreported exception thrown!
[B#349]  java.lang.ClassCastException: Reika.GeoStrata.Blocks.BlockPartialBounds$TilePartialBounds cannot be cast to Reika.GeoStrata.TileEntityGeoBlocks
[B#349]  	at Reika.GeoStrata.Blocks.BlockGeoStairs.func_149720_d(BlockGeoStairs.java:61) ~[BlockGeoStairs.class:?]
[B#349]  	at Reika.GeoStrata.Blocks.BlockPartialBounds.func_149720_d(BlockPartialBounds.java:99) ~[BlockPartialBounds.class:?]
[B#349]  	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4232) ~[blm.class:?]
[B#349]  	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255) ~[blm.class:?]
[B#349]  	at Reika.DragonAPI.Instantiable.Event.Client.RenderBlockAtPosEvent.fire(RenderBlockAtPosEvent.java:54) ~[RenderBlockAtPosEvent.class:?]
[B#349]  	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181) ~[blo.class:?]
[B#349]  	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530) ~[bma.class:?]
[B#349]  	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187) ~[blt.class:?]
[B#349]  	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011) ~[blt.class:?]
[B#349]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
[B#349]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
[B#349]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
[B#349]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
[B#349]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
[B#349]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#349]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[B#349]  [16:59:52] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
[B#349]  // Hey, that tickles! Hehehe!
[B#349]  
[B#349]  Time: 8/3/17 4:59 PM
[B#349]  Description: Unexpected error
[B#349]  
[B#349]  java.lang.ClassCastException: Reika.GeoStrata.Blocks.BlockPartialBounds$TilePartialBounds cannot be cast to Reika.GeoStrata.TileEntityGeoBlocks
[B#349]  	at Reika.GeoStrata.Blocks.BlockGeoStairs.func_149720_d(BlockGeoStairs.java:61)
[B#349]  	at Reika.GeoStrata.Blocks.BlockPartialBounds.func_149720_d(BlockPartialBounds.java:99)
[B#349]  	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4232)
[B#349]  	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255)
[B#349]  	at Reika.DragonAPI.Instantiable.Event.Client.RenderBlockAtPosEvent.fire(RenderBlockAtPosEvent.java:54)
[B#349]  	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
[B#349]  	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530)
[B#349]  	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
[B#349]  	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
[B#349]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
[B#349]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[B#349]  	at net.minecraft.client.main.Main.main(SourceFile:148)
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#349]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#349]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#349]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#349]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[B#349]

**Comment by ReikaKalseki** [comment]
Fixed, by way of disallowing stairs and slabs as covers.
