### ISSUE TITLE
[CrC] Double Enchantment

### ISSUE THREAD

**Issue by chaos234** [ReikaKalseki/Reika_Mods_Issues#1535]
Hey,

how ever I have done this but I have one enchantment twice:

![2017-08-04_10 52 49](https://user-images.githubusercontent.com/340106/28961653-5cc304e4-7903-11e7-984c-b700fdc21ad1.png)

It is Magical Resistance (I - IV) which comes from Ars Magica 2 if I am right. Normaly it should only be there ones but may it be possible that two different mods adding it so it can be twice on the armor?

**Comment by ReikaKalseki** [comment]
That would not be on my end.
