### ISSUE TITLE
[CrC] More missing texts

### ISSUE THREAD

**Issue by chaos234** [ReikaKalseki/Reika_Mods_Issues#1536]
In addition to #1521 

Text Missing:

![2017-08-04_12 36 24](https://user-images.githubusercontent.com/340106/28965556-e0c3669a-7911-11e7-802d-057cf3429113.png)

![2017-08-04_12 41 09](https://user-images.githubusercontent.com/340106/28965611-35f690e2-7912-11e7-9eda-e5c0b5a12e97.png)

![2017-08-04_12 41 54](https://user-images.githubusercontent.com/340106/28965646-68737f9e-7912-11e7-82ec-c4e5bbb14581.png)

Not implemented yet?:

![2017-08-04_12 40 12](https://user-images.githubusercontent.com/340106/28965591-1320b444-7912-11e7-9a22-05f5fd4c586e.png)

![2017-08-04_12 41 57](https://user-images.githubusercontent.com/340106/28965658-7637fd58-7912-11e7-9ecd-4ba2792be012.png)

![2017-08-04_12 41 58](https://user-images.githubusercontent.com/340106/28965661-78bb8518-7912-11e7-8510-182a059dc570.png)

**Comment by ReikaKalseki** [comment]
Done.
