### ISSUE TITLE
ReC turbine generator works on backwards turbine

### ISSUE THREAD

**Issue by RezaSmith** [ReikaKalseki/Reika_Mods_Issues#1537]
hello sorry to bother , i tried searching my issue but i couldnt find anything useful so 
the problem is i have set a turbine with fission reactor and everything worked fine , but today i added a turbine generator into it , now the problem is i usually added the lubricant from the front of turbine , now that i added the turbine generator i cant do that anymore , i have to break the multiblock and its kinda annoying , i was wondering if this is intended? where can i add lubricant into my turbine other than front?
thanks
https://i.imgur.com/tUk4j5l.jpg

**Comment by lAimBotl** [comment]
You can add it to the rear too.
The turbine gen turns shaft power (only from turbines) into rf, so you have the turbine facing the wrong way.

**Comment by ReikaKalseki** [comment]
It is built entirely incorrectly.

**Comment by RezaSmith** [comment]
interesting , its funny to note that with the way i built it i can get shaft power and RF at the same time , guess this is not intended then xD

**Comment by ReikaKalseki** [comment]
Wait, what?

**Comment by lAimBotl** [comment]
Finally, confirmed it :)

![2017-08-04_21 53 12](https://user-images.githubusercontent.com/10777735/28991990-63b85de2-795f-11e7-8a72-e5a4ebe3eb3d.png)

![2017-08-04_21 53 17](https://user-images.githubusercontent.com/10777735/28991991-6886cbb0-795f-11e7-972a-c998254f7d41.png)

**Comment by ReikaKalseki** [comment]
Fixed.
