### ISSUE TITLE
Cross-mod interaction with Witchery causes crash 

### ISSUE THREAD

**Issue by joral** [ReikaKalseki/Reika_Mods_Issues#1538]
I have run into this a couple of times now while exploring, which causes my server to crash and restart.  

The entity which is referenced as causing the crash is the coven witch from witchery.

https://pastebin.com/KpASNP7z

**Comment by ReikaKalseki** [comment]
Why are there entities ticking in worldgen code?

**Comment by DaFuqs** [comment]
Same with OceanCraft, it seems. "OCCannibal (com.Oceancraft.common.EntityCannibal)"

Just had that happen now when exploring.

Edit: Full paste: https://pastebin.com/UjEsenVj

**Comment by ReikaKalseki** [comment]
I might be able to no-op the tick-entities method.

**Comment by ReikaKalseki** [comment]
Done.
