### ISSUE TITLE
[CrC] Sound problems

### ISSUE THREAD

**Issue by chaos234** [ReikaKalseki/Reika_Mods_Issues#1539]
Hey Reika,

may it be possible that you add a snd Volume controller to audijust the volume for e. g. the Lumen Turrets?
Only with the Master Volume it's possible to change the sound volume and this isn't rly good.

Will be nice if you can check this out and add on or add them to the Blocks Volume section :)

**Comment by ReikaKalseki** [comment]
They use the same sound as pylons, so no, that is not possible without introducing other issues.

**Comment by chaos234** [comment]
Thats bad since with your added controll it is not reduceable. Sure I can place a sound muffler but this comes from another mod so without a sound muffler it is not possible to reduce the volume.

Only solution is to add for those sounds an additional control or a sound muffler but saying that it is impossible is false because it is possible because other mods are controlled by the default different sound controls to. I also wonder why your added control does not affect then too so it is in addition a bug, sorry but this is the truth.

⁣Gesendet mit BlueMail ​

**Comment by chaos234** [comment]
Ok, I tested a few more things out and for me the additional Sound Control for CrC is useless because also the error sound for the tables and for the item casting stand are not assinged to it so only a muffler will do the work.

And since the pylon sound is the same for the focus frame which will not harm any player it isn't a good way to let it only be adujist able over the Master Volume Control.

Well, if a normal controll where available other players may complain why they are killed instantly because of deactivated sounds but then it's there own fault since they decided to turn them off.

I also could not get it through looking into the source code for what your added volume controll rly is but at the end a muffler block or smth. similar should do the work if you won't add the sounds to the normal categories like each other mod it does (normaly).
