### ISSUE TITLE
[Chromaticraft][Mod-Interaction] Luminous Cliffs not Spawning with Biomes O' Plenty in BIOMESOP world type

### ISSUE THREAD

**Issue by lazerous42** [ReikaKalseki/Reika_Mods_Issues#1540]
Hello, I do believe I have encountered a progression breaking bug when is Chromaticraft used with Biomes O' Plenty.  If you are using Biomes O' Plenty and your world type is BIOMESOP, the Luminous Cliffs biome(s) do not spawn.  Just having Biomes O' Plenty installed is not enough to cause the problem, the world type must be BIOMESOP.  

This was first brought to my attention by my players of Ascension of the Technomancer, and I have subsequently confirmed this by generating ~30 worlds and using the /findbiome command.  If Biomes O' Plenty is not present or if the world type is DEFAULT, I always got hits within 8 to 16 km from spawn.  Anytime the world type was BIOMESOP, there were no hits on Luminous Cliffs out to 64km.  I'm fairly certain this will break progression at some point down the line (no access to Luma Lotus I believe), so It seems like a significant issue.  If I am missing something here then just let me know so I can give it a try and pass it on to my users

I also tried cranking up the weight in the Chromaticraft config files, but this appears to have no effect on the spawn rate.  I was reviewing the code a bit to try and see what the spawning requirements for this biome are, and after reviewing (ChromaticraftOptions.java and Chromaticraft.java) it looks like the weigh is not currently being used, in favor of replacing some existing biome instances based on their properties (I don't know Forge and I mainly code in Python at work so my Java is a bit fuzzy).

To make reproducing this issue a bit easier on you, I have packed up the instance I was using for testing into a RAR file and posted it to my Google drive.  It's a stripped down core of my pack that only contains APIs and key mods, plus the jars of interest required to see the problem.  For reference, the ID for Luminous Cliffs is 150, and the LC Edge is 147 (I've tried shifting the IDs to the lower 128.  This had no effect)  It's a full MultiMC instance and is intended to just be dropped into your instances folder.  Thank you very much for your time and dedication, link to the instance is below.

[Chromaticraft Luminous Cliffs Bug.rar](https://drive.google.com/open?id=0B70Z83Oiudg6LUVFVG5sb1I0MTQ)

**Comment by DragGon7601** [comment]
I know this will not be the info you want to hear, I hope Im out of date and this is no longer relevent... But there have been other issues with BoP in the past, I dont know if any of them have been fixed. All I know is that these issues are why Haggle1996 removed BoP from the Revolution Mod pack. How well have Ocean Temples been spawning in your pack? That was one of the major issues Haggle1996 had:

https://github.com/Haggle1996/RevolutionPack/issues/477

It would be nice to hear they spawn fine now.

**Comment by ReikaKalseki** [comment]
Considering that the cliffs are added via ASM into the normal biome GenLayer system, this is no surprise. However, this cannot be fixed without input from BoP's end, and guess how likely that is, especially for 1.7.10.

**Comment by OvermindDL1** [comment]
Or ASM'ing their generators, and that would be a pain...
But that is something that someone else could make a mini-mod to do...

**Comment by ReikaKalseki** [comment]
> that would be a pain

And something I could not get away with.

**Comment by lazerous42** [comment]
@DragGon7601 ~ Since you we're curious.  Ocean Temples spawn fine.  I found two in my northern sea about 1.7km apart, so there is no need to worry about that.

**Comment by Barhandar** [comment]
Basically, use ExtraBiomesXL instead. Better configurability, too!

**Comment by ReikaKalseki** [comment]
I ended up finding a simple fix for v21.
