### ISSUE TITLE
[CrC] Sound problems #2

### ISSUE THREAD

**Issue by chaos234** [ReikaKalseki/Reika_Mods_Issues#1541]
Referencing #1539 since I will not accept your reject since u closed it before I could do any reactions. Pls take a look into it and yes it is definitly solveable and sorry but as long as this isn't resolved it will get reported instantly from my side.

I like your mods because they are great but you should sometimes listen to your users carefully and not ignoring them because this is in my eyes exactly happen here.

Also I don't understand why the sound from the Turrets and the Pylons are only coverd by the Master Volume Control but a CrC Volume Control implemented is ... this confuses me.

**Comment by ReikaKalseki** [comment]
Do not do this.
