### ISSUE TITLE
[Expanded Redstone] [Singleplayer] world reload some receivers stop outputting signal

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1542]
selfie time! 

It seems to effect almost all of them every world reload.

The paste is red when it has a redstone signal.
 As you can see the transmitter is on, under the receiver (I them it for lights, was hoping it would help me, plus i think it looks nice )
![2017-08-05_19 37 35](https://user-images.githubusercontent.com/10777735/28999471-0622028e-7a16-11e7-9c0b-e1e5490365fd.png)

both are the same channel

![2017-08-05_19 37 41](https://user-images.githubusercontent.com/10777735/28999476-4efcc4b2-7a16-11e7-9fbd-48ac5b3f7966.png)

![2017-08-05_19 37 45](https://user-images.githubusercontent.com/10777735/28999478-542c4804-7a16-11e7-9ecd-24b5eabc73f3.png)

It seems this one also has bugged after reloading the world

![2017-08-05_19 37 58](https://user-images.githubusercontent.com/10777735/28999484-78b4adce-7a16-11e7-9a03-42a10039b520.png)

 Same channels too

![2017-08-05_19 38 03](https://user-images.githubusercontent.com/10777735/28999488-836d9a8c-7a16-11e7-9a07-899dcaacc1fa.png)

![2017-08-05_19 38 05](https://user-images.githubusercontent.com/10777735/28999491-86c44550-7a16-11e7-84c5-95ba1549268d.png)

My lights finally updated (down is off up is on) 

![2017-08-05_19 38 18](https://user-images.githubusercontent.com/10777735/28999495-9eb922d4-7a16-11e7-8628-23b7ba30aac0.png)

Fixed

![2017-08-05_19 38 27](https://user-images.githubusercontent.com/10777735/28999510-e2a8e6a0-7a16-11e7-9b65-d032ad72b3e7.png)

All of these are not connected to something yet (reworking everything atm)

**Comment by Aivech** [comment]
This does seem pretty major, especially if these are for something like a fail-safe reactor shutdown that doesn't care about damaging the reactor as long as it stays contained...

**Comment by ReikaKalseki** [comment]
Yes, but it is also near impossible to debug, and the likely cause is something horrible in MC map loading.

**Comment by ReikaKalseki** [comment]
I added some code to cache values and automatically trigger updates on world load. It is my only idea.

**Comment by ReikaKalseki** [comment]
Is it fixed in v18?

**Comment by lAimBotl** [comment]
looks like they died on my old map. channels 8,7,6, 3,2, don't work in my 0 to 10 test area

**Comment by ReikaKalseki** [comment]
??

**Comment by lAimBotl** [comment]
my hypothesis is that the cache is stuck or something.
okay seems they will only update on world reload. sometimes a little after. you cannot change them unless you reload world.

All on (one was turned off before i went in this world)
![2017-08-23_16 16 22](https://user-images.githubusercontent.com/10777735/29636463-bb1725aa-881e-11e7-85e3-732a93f6a37a.png)

all off on world without closing and reopening world
![2017-08-23_16 16 38](https://user-images.githubusercontent.com/10777735/29636465-bda4f540-881e-11e7-952e-47f51f6ac614.png)

World reload with all off
![2017-08-23_16 17 09](https://user-images.githubusercontent.com/10777735/29636469-c00b140e-881e-11e7-8be9-b8e2d909cef6.png)

all on without world reload
![2017-08-23_16 17 34](https://user-images.githubusercontent.com/10777735/29636473-c36cf216-881e-11e7-922a-d1162ed6c461.png)

hm does github have spoilers?

**Comment by ReikaKalseki** [comment]
I tested them after the previous fix attempt and they worked fine.

**Comment by OvermindDL1** [comment]
@lAimBotl You may need to upload a world with just reika's mods that can reproduce the issue so it can be properly tested.  :-)

> hm does github have spoilers?

<details> 
  <summary>A spoiler</summary>
  The hidden stuff
</details>

```html
<details> 
  <summary>A spoiler</summary>
  The hidden stuff
</details>
```
