### ISSUE TITLE
[CrC] Missing description again (Glowing Daisy), Mystracft Crystalline Stone in this Biome?

### ISSUE THREAD

**Issue by chaos234** [ReikaKalseki/Reika_Mods_Issues#1543]
Oh man ... toke me hours to finde the Luminous Cliffs but finally found them, incl. problems ^^.

~~The Glowing Daisy isn't giving any pice of Glowstone Dust like stated in the pictures below and~~ (EDIT: It dropped but rly, rly rare, is this intended to be?) also the text in the right window is stated to #NULL too.

I think, that there will be a lot mor of such things coming up ... sadly :/

Edit: Rly large amount of those Crystal Stone from Mystcraft to build portals with them. I wounder, if this is intendet to be happen ^^.

Images:

![2017-08-08_03 54 08](https://user-images.githubusercontent.com/340106/29052992-a171f50e-7bed-11e7-9984-d492482f6dfa.png)

![2017-08-08_04 01 25](https://user-images.githubusercontent.com/340106/29053118-7f7b575a-7bee-11e7-8f32-f64e9331684b.png)

![2017-08-08_04 57 40](https://user-images.githubusercontent.com/340106/29054376-2593d58e-7bf6-11e7-877b-e6d7ad510bb8.png)

**Comment by DaFuqs** [comment]
The flavour text on the right are also #NULL for: 
- Refactory Gems
- Lumen Overload

(Btw: The new mechanic for overloading the wooden repeaters is awesome!)

EDIT: The entry for the crystal orchesta in the lexicon is pretty generic. You may want to expand that one, too. How to set it up is never mentioned.

**Comment by ReikaKalseki** [comment]
I am getting tired of literally every thought about the mod that crosses your mind being reported as a potential bug. I have fixed the missing descriptions/texts; nothing else is a bug.

**Comment by chaos234** [comment]
I am sorry for that but at last I have corrected my opening post and replaced it with question if "this" is intended or not. Smth. which must not be responded at all but at the end it will be fine.

Next time I'll look closer to it ;)
