### ISSUE TITLE
DragonAPI V18 Crash

### ISSUE THREAD

**Issue by Xorbah** [ReikaKalseki/Reika_Mods_Issues#1546]
My game didn't generate a direct crash log, it just said 'Sorry, unexpected crash.' here's my output log. Hope it helps. I was trying to use DragonAPI and RotaryCraft with my pack.

[API.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1211905/API.txt)

**Comment by ReikaKalseki** [comment]
This is an ASM crash. Are you using Bukkit/KCauldron/etc?

**Comment by ReikaKalseki** [comment]
Hello?

**Comment by Xorbah** [comment]
No, i'm using Forge. No Bukkit or Cauldron involved.

**Comment by ReikaKalseki** [comment]
Are you using an old version of anything? Try removing mods.
