### ISSUE TITLE
The Chinese localization for RotaryCraft.

### ISSUE THREAD

**Issue by UUUii** [ReikaKalseki/Reika_Mods_Issues#155]
Hello @ReikaKalseki , my partners @IamAchang, @bakaxyf and I have finished the Chinese localization for [RotaryCraft](https://github.com/UUUii/Reika_mods_Localization/tree/master/Rotarycraft). We love this mod, so we are willing to do this work. Here, I want to ask if you can add the Simplified Chinese localization to RotaryCraft, also I have a little request that can you add a credit.md?
Anyway, thank you for bring us so much fun.

**Comment by ReikaKalseki** [comment]
I have implemented the new localizations. What is credit.md?

**Comment by 3TUSK** [comment]
From my understanding, he may mean that he updates the localization and ask for merging it manually.

**Comment by ReikaKalseki** [comment]
I have already implemented the new files for v8.

**Comment by 3TUSK** [comment]
Understand. By the way, does the manual support localization? I remember that you have said that it requires a subfolder named like "zh_CN" or "ru_RU" in order to include them.

**Comment by ReikaKalseki** [comment]
Yes, and you are correct. You just need to edit the file and translate it. Be careful about %d, %f, and %s tags. Those are placeholders for injected data, and removing or adding them can cause crashes.

**Comment by 3TUSK** [comment]
Thanks for explanation.
