### ISSUE TITLE
java.lang.NoSuchMethodError: Reika.DragonAPI.Libraries.World.ReikaWorldHelper.getMaterial(Lnet/minecraft/world/World;III)Lnet/minecraft/block/material/Material;

### ISSUE THREAD

**Issue by levicc00123** [ReikaKalseki/Reika_Mods_Issues#1550]
[Stacktrace](https://gist.githubusercontent.com/levicc00123/0a4127b286c895ef9b46b4fa17bad239/raw/fd28835f6687d2b59d5409dc44dedcc3b9719877/crash-2017-08-13_04.24.52-server)
[Full Log](https://gist.githubusercontent.com/levicc00123/0a4127b286c895ef9b46b4fa17bad239/raw/fd28835f6687d2b59d5409dc44dedcc3b9719877/latest.log)

The game crashes either when joining a world, or seconds afterwards. I saw farseek mentioned in the stacktrace, so I tried disabling it, but nothing changed. I'm using DragonAPI 18b.

Thank you for your time, and have a great day.

**Comment by krzysztofKKW** [comment]
I have exactly the same issue when walking around in Ender Forest.

**Comment by ReikaKalseki** [comment]
Use ChromatiCraft v18b.

#1548
