### ISSUE TITLE
Expanded Redstone - place any block causes crashes

### ISSUE THREAD

**Issue by lee321987** [ReikaKalseki/Reika_Mods_Issues#1553]
Seems all Expanded Redstone blocks cause it.
Crash report: [crash-2017-08-14_19.39.27.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1223748/crash-2017-08-14_19.39.27.zip)

Mods installed:
- DragonAPI v18b
- Expanded Redstone v18a
- NEI

**Comment by lee321987** [comment]
I have a countdown timer and a clock already placed in my main world and they're working.  I can rotate them with the screwdriver, and manipulate their timings, but if i break it and place it back down, game crashes.

**Comment by ReikaKalseki** [comment]
Use v18b.
