### ISSUE TITLE
[Suggestions - CrC] - Adding small white boarder to darker colors

### ISSUE THREAD

**Issue by chaos234** [ReikaKalseki/Reika_Mods_Issues#1555]
I suggest, since it is rly bad to see even with a bigger indication, to give darker color a white boarder.

Best one will be Kuro/Black since it is rly hard to see on the Lumencircle or on the indication circle at the pylon/focus frame how full it is.

Maybe 1px line arround it/then should be fine :)

**Comment by ReikaKalseki** [comment]
No, that will look terrible.
