### ISSUE TITLE
[CrC] Pathfinding for Lumen broken or only totaly weird?

### ISSUE THREAD

**Issue by chaos234** [ReikaKalseki/Reika_Mods_Issues#1556]
I don't even know why but the following image let me laugh because I did not understand why the pathfinding for lumen - and yes, I turned on to find the shortest path - goes such a weird way:

![2017-08-18_19 32 58](https://user-images.githubusercontent.com/340106/29470507-025586d0-844d-11e7-8fe7-c81c3f734044.png)

Eventually there is a possibility to resolve this or having the normal repeaters a higher priority as the MAR ones?

In the image above Kuro is going over at last 5 hops to the casting table instead of only using 3. But if it's going into the IF then it goes a much better way as you can see below:

![2017-08-18_19 42 05](https://user-images.githubusercontent.com/340106/29470589-55fbb75a-844d-11e7-9e0e-ad3c619dd05e.png)

And yes - even if it's more lose than worse - I use MAR instead of placing repeater-towers of mor than 3 colors since I can spend the repeater block into an MAR block to transport them over one repeater which is smaller at the end ^^.

Hopefully, if this is rly a bug, you can find any solution and if not then I have - and all others to - to accept it how it currently works because I think the code behinde the pathfinding is not easy, isn't it?

**Comment by ReikaKalseki** [comment]
Do you want ten-second lagspikes to calculate the shortest paths? No? Then this is what you get.
