### ISSUE TITLE
Can't login to map

### ISSUE THREAD

**Issue by homieman** [ReikaKalseki/Reika_Mods_Issues#1557]
loads but not quite. works without rotery.

**Comment by chaos234** [comment]
I suggest to add at last the client log if you haven't received any crash-report to add it's log.

**Comment by ReikaKalseki** [comment]
Yes, post a crash report or something because "I can't login" is only marginally more helpful than your bug report being [a frowny face](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1069).

**Comment by homieman** [comment]
Nah

**Comment by homieman** [comment]
You'r not gonna fix it?

**Comment by homieman** [comment]
Nah.

**Comment by ReikaKalseki** [comment]
Nah

**Comment by homieman** [comment]
Why are you being an asshole?

**Comment by truenachtara** [comment]
He's not being an asshole, you're just incapable of providing any information that can help your situation

**Comment by chaos234** [comment]
I also don't get his problem. Posting log files is a) so easy and b) doesn't hurt anyone. It is a simple thing which should be attached to any issue report if needed and here it is needed. Don't get it ...

**Comment by homieman** [comment]
not my problem

**Comment by 1Matthias** [comment]
@homieman It is your problem. If you don't provide information, nobody can or will help you.

**Comment by ReikaKalseki** [comment]
Or will even care enough to try.

**Comment by OvermindDL1** [comment]
@homieman How do you expect an issue to be fixed when there is no information about what the issue is, specifically no log file supplied of the issue?  Imagine you were told the same thing you put in your initial post, what information do you have to go looking for where in the code the problem might lay?
