### ISSUE TITLE
[CrC] Proplem with the Replication Star

### ISSUE THREAD

**Issue by chaos234** [ReikaKalseki/Reika_Mods_Issues#1558]
I am not sure why I have such many problems and I don't do this on purpose it normaly happens to me.

Well, the problem is that the Replication Star isn't doing well. But to write down the problem is bad so I
made a video again which u can finde here: https://youtu.be/mh0wjgiB-EM

**Comment by ReikaKalseki** [comment]
The star has a max volume (progression dependent) which is ignored in creative.

**Comment by chaos234** [comment]
Ok, but why is it progression oriented @ReikaKalseki ? That makes no sense to me since I am at last at the Dimension progression and the sound is always the same if I do a sneak + right-click. Maybe change
the snd sound a bit higher or the first one a bit deeper to indicate the selection state or the things (or
one of them) out of the video.

Also, why then not notifying the player about this in the book? I know you want the player to find things out but this is a bit to hard, since if the area was picked fales, it can or maybe will end badly which isn't good.

So I hope that at last a few hints and/or a section higlight will be implemented like the one shown in my video from the used ability @ReikaKalseki

**Comment by ReikaKalseki** [comment]
> Ok, but why is it progression oriented @ReikaKalseki ?

To gate the laggier and more powerful ability. Like everything else.

> Also, why then not notifying the player about this in the book?

And good luck telling a player how to calculate the volume.

**Comment by chaos234** [comment]
> And good luck telling a player how to calculate the volume.

It is a simple formula: `a*b*c` or to be correct `l*h*w`. Will be the secound formula in the Book with the one for the Crystal Tank Controller.

So if you want to copy e. g. a building with `l = 5, h = 3 and w = 9` then u'll get `5*3*9`=135 as volume. Now u can write smth. like:

10 Progression = 50 Volumen/Blocks
15 Progression = 75 Volumen/Blocks
...

I now some players are younger and haven't had volume calculation in school but there for then is the text and since anybody can (or should can) count blocks in length, height and width, they should then be able to replace those variables with the counted blocks or am I wrong? After doing that and typing it in the calculator they then know what volume they have and if it's possible todo a copy or not compaired to the progression state.

I know that there will be a small group which will not get it but such groups exists over the hole world, means that other mods are also dealing with them but why care about them, if the hole community -
 which supports your mods - is bigger?

**Comment by OvermindDL1** [comment]
> It is a simple formula: a x b x c or to be correct l x h x w. Will be the secound formula in the Book with the one for the Crystal Tank Controller.

Technically `*` is the multiplication symbol in algebra, not `x`.  ^.^

`L*W*H`

**Comment by chaos234** [comment]
@OvermindDL1 My problem was that the star symbol caused italic text ransformation and I haven't had any idea how to solve this so I choosed the X instead of the star for multiplication ^^

**Comment by OvermindDL1** [comment]
> @OvermindDL1 My problem was that the star symbol caused italic text ransformation and I haven't had any idea how to solve this so I choosed the X instead of the star for multiplication ^^

Ah, github uses markdown format so to 'escape' a character so it performs no formatting, just prefix it with the backslash of \\, so you can do L\\\*W\\\*H, which becomes L\*W\*H, or better yet, put it in inline code blocks using the tilde of \` on both sides like:
```
`L*W*H`
```
Which becomes `L*W*H`, everything in it is considered precisely and pre-escaped.  To do what I did just above you use code fences like:
\`\`\`
\`L\*W\*H\`
\`\`\`
:-)

**Comment by chaos234** [comment]
@OvermindDL1 - I have updated my post and now it looks better and the reading should also be better.
Hopefully @ReikaKalseki will take a look on it if he has time. However, I can understand him but on the other side it should not hurt to implement this. May I ask what's your opinion to this problem which I have shown here, incl. my idea how to get a better controlling for it?
