### ISSUE TITLE
RotC v7f: AC Electric engines, Shaft junctions, and Flywheels; power distribution problems

### ISSUE THREAD

**Issue by Braidedheadman** [ReikaKalseki/Reika_Mods_Issues#156]
Hi there, Reika.

So, as the title suggests, I'm having problems with distributing power from a series of AC electric engines when chained through several shaft junctions to first combine their torque, gearing the resultant output for speed, and finally separating the shaft power to run a series of machines on the other end. The use case for this report will include eight shaft core magnetizing units as power consumers, illustrated below:

![Uploading [2015-07-12] RotC v.7f - AC Electric Engines, Shaft Junctions, and Flywheels.png…]()

[Edit] I don't appear able to upload screenshots. Here is a link to the same image on tinypic:

http://i61.tinypic.com/35m05dv.png

Machine overview: 

1.) A computercraft computer block supplying a two-clock red stone signal via EnderIO insulated redstone conduits to the AC Electric engines and magnetizing units.
2.) Four AC electric engines
3.) Three shaft junctions plus a beveled gear assembly taking the power output from all four AC electric engines, combining them to a total of 2048Nm torque at 256 rad/s.
4.) Two diamond shafts transmitting shaft power to,
5.) Two 16:1 diamond gearboxes, both geared for speed, converting the shaft power into 8Nm torque at 65536 rad/s.
6.) Six shaft junctions, assorted shaft units and beveled gears to split the remaining torque eight ways for 1Nm Torque at 65536 rad/s into,
7.) Eight magnetizing units receiving power at the shaft junction outputs (charging shaft core units to a maximum of 32768 microteslas)

Description:

Up until recently, this arrangement has worked fine. However, ever since we updated our server to v7x (currently v7f), the shaft junctions in combination with the AC electric engines have produced some odd behavior. Namely, while the AC electric engines will output power at a near-constant rate of 512Nm \* 256 rad/s on a two-clock RSS signal with only minor, intermittent fluctuations in speed (as it always has), the attached shaft junctions will start and completely stop rotating at random(?) intervals independently of each other, which has the effect of interrupting power distribution down the chain.

In order to better visualize what is happening, I have produced a short video detailing the issues observed above. In order to eliminate the possibility of this being the result of client-server latency, I duplicated the same machine arrangement as used in our SMP server in a SP environment. The odd behavior with the shaft junctions was precisely duplicated in this environment:

https://www.youtube.com/watch?v=ua2dAx0i3sY

Note that this is not the same issue as the one where shaft junctions were not outputting their power at all, which as fixed in v7e. Indeed, shaft junctions that are connected/chained to other engines, like ethanol/performance engines, do seem to merge/split power without any of the issues described in this report.

At first I thought that this might be intended behavior, that this was done in order to enforce use of flywheels in power chains involving AC Electric engines, which up until now have not strictly been needed. If this is indeed the case, I can fully appreciate the direction that you wish to move these engines in. However, and I apologize if this seems like I'm mixing issues but, to the best of my knowledge, the flywheels have not worked properly in this configuration (for me at least) for quite some time.

If I replace one of the shaft units with a flywheel, there are several things that will happen:

1.) If attached to an output that is currently generating shaft power while the flywheel's output is simultaneously connected (inline) to an input that leads to machines where work is to be done (friction losses), the flywheel will not turn, neither receiving nor sending power through the chain.
2.) If the connection on the output side of the flywheel is removed and if it is still receiving power on its input side, it will begin turning until it has stored power equivalent to what it is receiving from its input, as expected.
3.) If the flywheel's output is then reconnected to the chain at any point while it is rotating with stored shaft power (not necessarily but including 100% of the input shaft power), the following exceptions are instantly thrown (retrieved from chat logs):

http://pastebin.com/jh4tHpzj

These are spammed to the chat messaging area, particularly the line, "Tile Entity Gold Flywheel @ DIM0: -869, 4, 452 is throwing class java.lang.NullPointerException on update: null[]", which repeats ad infinitum for as long as the the flywheel is transmitting power to perform work through its output.

4.) Possibly unrelated, but I feel it should be mentioned that the flywheel's sound effects can be heard while its output is not connected to anything. However, it is suspended the moment that it the output is connected to anything that will perform work in addition to throwing the exceptions mentioned above.

5.) The power distribution/interruption issues observed above are resolved by the flywheel, given that it is compensating for the intermittent power fluctuations coming from the AC Electric engine/shaft junction chain ahead of it. Note that the shaft junctions themselves continue to behave... oddly.

Conclusion: 

In arrangements involving AC electric engines with shaft junctions merging their power, the shaft junctions do not appear to be combining the outputs from the AC-ElecE's properly, being observed to rotate out of sync with each other, sometimes stopping altogether and disrupting power distribution down the chain. Flywheels seemed like the intuitive fix; however, these are bugged and throw java class exceptions when their outputs are required to perform work. This report's use case involved shaft core magnetizing units; however, this behavior can be observed with any/all machines in similar arrangements. 

I tried to capture as much information as I could, I don't think I've forgotten anything, and this has already gotten rather verbose :p. If you feel like there's anything that I've missed or would like me to test further, I'll gladly make myself available. RotC is by far my favorite tech mod and I do hope that this information is helpful.

Peace!

**Comment by ReikaKalseki** [comment]
The issue you are having with the AC engines is that EiO conduits only conduct power serverside, meaning clientside the machines stop operating. Mousing over them forces a sync, hence why they appear to stop and start.

This likely cropped up in v7 because I turned power transfer on client back on (it was turned off in v3) to fix several other issues.

As for flywheel issues, those have already been reported and fixed.

**Comment by Braidedheadman** [comment]
OK! Thanks for the pointer! So, I've tested every RSS wiring media that I can think of. Insofar as I can tell, the only two RSS wires that provide a viable work around are vanilla redstone wiring and framed red alloy wire (oddly enough, the normal red allow wire suffers from the same problem). Both are rather aesthetically displeasing, but at least these machines should work again. Cheers! :D

**Comment by ReikaKalseki** [comment]
I know ProjectRed wires and MFR rednet work fine.

**Comment by Braidedheadman** [comment]
Indeed, I use the MFR wires most often in my MP server builds (cheap, easy to make, reliable, accept levers directly onto their input face). However, they were producing the same results as observed above in our SMP environment. In the use case above, I selected the EiO wires in order to see if I would achieve different results from what I had previously observed on the the server. 

If I may add, there's an odd interaction with the MFR wires powering machine control blocks. When given a RSS, the engines that they are controlling are "turned off" in that they no longer consume fuel but they are still animated, as are any shafts/gearboxes/junctions/etc that are connected to them. Additionally, readings taken using the angular transducer show that there are intermittent periods where rad/s increase/decrease and power is being generated/transferred although no work takes place in any connected machines. It's probably related to what you described above, but if you like I can open a new issue and mark down my observations in a little more detail.

**Comment by ReikaKalseki** [comment]
That is the same issue.
