### ISSUE TITLE
bug bug bug bug bug bug bug

### ISSUE THREAD

**Issue by headyman70** [ReikaKalseki/Reika_Mods_Issues#1560]
![](http://cfile23.uf.tistory.com/image/26388C5058BD5ED4219FB4)

**Comment by ReikaKalseki** [comment]
Fun. Now let's try being helpful for a change.

**Comment by Barhandar** [comment]
Numeric mismatch between your WAILA entries ("Fuel:") and external WAILA generic tank capacity display (X / Y mB Z).

**Comment by ReikaKalseki** [comment]
The first line is not my entry.
