### ISSUE TITLE
DragonAPI crash on initial worldgen

### ISSUE THREAD

**Issue by Savallator** [ReikaKalseki/Reika_Mods_Issues#1561]
I have a (reproducable) crash on Initial worldgen with a quite large pack.
However, i cannot find anything ion the crashreport about other mods, only about DragonAPI.
I am using 18b of your mods

https://pastebin.com/qa1y9q5Y

**Comment by Savallator** [comment]
Okay, after further Testing, the Crash disappeared after removing Chisel. Quite funny.

**Comment by ReikaKalseki** [comment]
This is a worldgen issue, and not on my end. Something is generating null.
