### ISSUE TITLE
ConcurrentModificationException for RoC Autocrafting Unit

### ISSUE THREAD

**Issue by WidjettyOneTwo** [ReikaKalseki/Reika_Mods_Issues#1563]
This often happens when I load my world ([Millionaire mod pack](https://minecraft.curseforge.com/projects/minecraft-millionaire), version 1.5 of the pack, v18b of your mods):
https://pastebin.com/BMb7mP9C

I have an autocrafting unit that is set up to autocraft the components of jet fuel: cinderpearls -> blaze powder, blaze powder + slime -> magma slime, sugarcane -> sugar, sugarcane -> plant balls (so IC2 can macerate them into dirt).

I think it's arguably MineTweaker's fault - it takes some time after the world loads for all of the MineTweaker scripts to load, and so the autocrafting unit ticks while the recipes are still changing. A hacky fix would be to pass in "new ArrayList(...) " to wrap "CraftingManager.getInstance().getRecipeList()" on line 476 of TileEntityAutoCrafter.java, but that's probably not performant, and might allow things to be crafted with the pre-MineTweaker recipes. A better solution would be to hold off on ticking the autocrafting unit until MineTweaker has finished loading. This [issue](https://github.com/stanhebben/MineTweaker3/issues/297) might be a similar thing.

**Comment by ReikaKalseki** [comment]
@Rivaryn had this recently, and the issue was a classloading error triggered by launching MC through Steam. Perhaps for you as well?

> A better solution would be to hold off on ticking the autocrafting unit until MineTweaker has finished loading.

I doubt this to be possible. If your guess as to a cause is correct, then this represents a serious design problem in either MC itself or Minetweaker.

At any rate, this is not my doing and almost certainly unfixable on my end.

**Comment by WidjettyOneTwo** [comment]
No, I'm launching it through MultiMC. Oddly enough, when I restart the instance from MultiMC, I haven't had it crash twice in a row - perhaps the second time, the minetweaker script files have been memory-mapped and so load faster?

A similar [issue](https://github.com/BuildCraft/BuildCraft/issues/3470) with buildcraft claims that MineTweaker tweaks the recipes on both the server and client threads, and when a single-player integrated server is launched, the recipe list is shared by both. Which means that when your Autocrafter is ticking on the server thread, it is racing with MineTweaker doing its thing on the client thread. 

That said, I don't know enough Minecraft modding to be sure. It seems dangerous to share the recipe list across both threads (but that's an MC design decision?), and the MineTweaker maintainer's comments sound like he doesn't understand thread-safety. I think you're probably doing the right thing and MineTweaker is not. 

Would the solution of copying the list of recipes before iterating over them be too much of a problem? Or alternatively, just catch the ConcurrantModificationException and skip that tick if it happens (it shouldn't happen often). It's a bit of a hack, but as it is, the Autocrafting Unit is semi-unusable for single-player games that use MineTweaker (which is nearly every modpack). Unfortunately, MineTweaker is no longer being updated for 1.7, so either you hack something around it, or it doesn't get fixed.

**Comment by ReikaKalseki** [comment]
> Would the solution of copying the list of recipes before iterating over them be too much of a problem

Yes, as you guessed, the performance cost of that - especially in a large pack with 200k recipes - would be insane.

> just catch the ConcurrantModificationException and skip that tick if it happens (it shouldn't happen often

No. That is like putting wallpaper over a rotting spot in the wall; it merely masks the problem until it becomes too large to ignore.

> the Autocrafting Unit is semi-unusable for single-player games that use MineTweaker (which is nearly every modpack)

I use both without issue. Something else is exacerbating or even outright causing it.

**Comment by WidjettyOneTwo** [comment]
Is there anything you'd like me to try to debug it? I can give you a world download?

[Here's](https://pastebin.com/yFcFbKP2) more of the log, showing that MineTweaker executes tweaks on the client thread just before the exception is thrown on the server thread.

The exacerbating factor might just be that I have a fairly slow computer (Core i5 2.6 GHz). I don't think Millionaire's minetweaker scripts are particularly large compared to, say, Revolution|3.

I managed to force it to happen again, even after a successful startup, by doing "/mt reload": [log here](https://pastebin.com/1gRNMZZC). In this case, it looks like the tweaks were applied on the server thread, and then the crash happened on the client thread? I'm not sure, it's not clear to me which thread the exception was thrown from.

**Comment by ReikaKalseki** [comment]
> The exacerbating factor might just be that I have a fairly slow computer (Core i5 2.6 GHz)

Possibly.

And the error is always coming from the client thread.

Now, I have a policy of not doing *anything* for "stupid" mistakes on the parts of other mods (eg null worlds to `IWorldGenerator` objects, `setBlock` with a null argument, etc), and that would normally apply here. However, it is probably the case that the AutoCrafter should not be trying to do crafting clientside.

I will make that run serverside only, and if that does not fix it - or if said limit already exists - then there is nothing that will (or even really can) be done.

**Comment by ReikaKalseki** [comment]
It did not have such a limit, but now it does.

**Comment by WidjettyOneTwo** [comment]
Thanks, we'll see how it goes.
