### ISSUE TITLE
Reika mods server crash

### ISSUE THREAD

**Issue by Cenbes** [ReikaKalseki/Reika_Mods_Issues#1564]
I know i duplicating this, but it is some kind of game/server breaking bug.
I played reika mods since it released and settuping up my personal modpacks can be really pain in ass by only one version of mods evry time (but i understand why you want keep them on most updated point and dont let lower version to go ou, or why you want to keep them updated for ppl). 
But when im trying to setup KCauldron server (i read it is not supported) im comming across a crash what i can´t fix at all.

https://pastebin.com/ecJSa2pP

Im using lates version of forge and i found this for server KCauldron-1.7.10-1614.201. But it seams there is still big problem. I found this crash on lower version of forge in client.

Normaly it will not be a problem, but i want to make server for my friends and their friends. It mean i need LWC, WG, WE and Pex

**Comment by Cenbes** [comment]
I dont know why you marking this as spam or stop reporting this when Your mods are only one what are marked as errored. Even tho it seams there is no really a point to you to write a litlle bit to someone who really playing your mods...

And show me, what is abusive in my comment up here...

**Comment by HellFirePvP** [comment]
Because this issue has been reported 200+ times by now at least and you seem to be even aware that it's been reported 200+ times. And as stated 200+ times, Bukkit/KCauldron/Related server software is not supported.

**Comment by Cenbes** [comment]
Ok thank you for answer.

**Comment by Cenbes** [comment]
But still, reika mods are Single player only or there is way how to make normal server with them with plugins ?

**Comment by 1Matthias** [comment]
Bukkit/kcauldron are absolutely not supported, and do not work with Reika's mods, as they modify parts of the base game that Reika's mods require unmodified to operate correctly. Reika's mods are multiplayer compatible, but only in a purely Forge environment.

**Comment by DracoScythem** [comment]
Most of the functionality you usually want on a Server and are not provided by Forge are can be archieved on a 'vanilla' Forge Server using ForgeEssentials (WorldEdit, WorldGuard, Warps, Homes, Permissions, ...)

Also, KCauldron usually causes far more problems than it solves (many of which only arise after investing possibly hundreds of hours...)

**Comment by 1Matthias** [comment]
@DracoScythem Exactly.

**Comment by 1Matthias** [comment]
@ReikaKalseki You need a "If one more person reports this, I'm gonna scream" tag. ;P
