### ISSUE TITLE
Instant Server-DC when trying to access the IF with some DraconicEvolution Tools

### ISSUE THREAD

**Issue by chaos234** [ReikaKalseki/Reika_Mods_Issues#1565]
I did not know why this happends and why this only happens to DE Tools which are crafted and not
given with OP over NEI, but when I want to access the Item Fabricator from CrC with an Wyvern Chestplate (or any other weapon/armor) I got DCed from my Server with `Internal Server Error`.

Images:

![2017-08-23_23 08 25](https://user-images.githubusercontent.com/340106/29638805-b6218984-8858-11e7-9289-db6f60dbb465.png)

DC-Screen: https://puu.sh/xhRXH.png
Konsole Output: https://puu.sh/xhRY3.png

No Error is shown in the Client-Log and only this piece of Error is thrwon. Also this maybe a low-prio ModInteraction bug since it only occoures with tools from DE (latest available Version), so that I can at last use the IF with other tools in my hand.

EDIT: This also happened again a few seconds ago as I wanted to access the Filling Station from RoC so maybe it is triggered from the DragonAPI since all your mods req. it.

**Comment by chaos234** [comment]
Ok, if they are charged up with RF (means greater then 0 RF) then the error did not occour. Maybe it is a *null* error problem? Since the RF is 0 after crafting the wyvern tools.

**Comment by ReikaKalseki** [comment]
#652 #1358 #1423 #1474 #1488

**Comment by chaos234** [comment]
Ok, that is rly hard but thanks for the links :)
