### ISSUE TITLE
Dragon API (Version 18b) Causes Game to Crash and Gives Error, "Exception in server tick loop" When Loading a World

### ISSUE THREAD

**Issue by Zebralear** [ReikaKalseki/Reika_Mods_Issues#1566]
Here is a detailed (at least I hope it is) description of my experiences with a crash log and some errors that show up in the game console: -https://pastebin.com/f5W3PLN5

**Comment by OvermindDL1** [comment]
> java.lang.VerifyError: Expecting a stackmap frame at branch target 259

Well, that is certainly a borked ASM'ing!  o.O

> The mod DragonAPI is expecting signature 32:F5:F4:E8:44:C0:EA:C8:6F:46:8A:8E:F3:05:05:7B:6F:90:0F:78 for source DragonAPI 1.7.10 V18b.jar, however there is no signature matching that description

Hmm, bad download, or does DragonAPI not include a signature?

Either way, is it possible for you to upload that world folder as a zip somewhere and give here the download link?  :-)

**Comment by OvermindDL1** [comment]
Also just to clean it up, the paste is in full (slightly cleaned up here too):

> So, I am using forge version 10.3.4.1558-1.7.10 and I only have DragonAPI installed (I originally had RotaryCraft, ReactorCraft, ElectriCraft, and ChromatiCraft installed at version 18b. When this started happening, I began to uninstall them one-by-one to see what mod was crashing it [DragonAPI]. I don't know how to read the crash report myself so it may be a simple problem, sorry if it is.)
> 
> My Computer: MacBook Pro (15-inch, Late 2011)
> (Hope that's enough information, I am new at this but the internet wouldn't help so I had to do it)
> 
> I'm not using Java executables.
> ```
> My JVM arguments are: -Xmx4G -Xms4G -Xmn4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
> ```
> 
> I always get this error in the game log a few seconds after the mod starts loading:
> ```
> The mod DragonAPI is expecting signature 32:F5:F4:E8:44:C0:EA:C8:6F:46:8A:8E:F3:05:05:7B:6F:90:0F:78 for source DragonAPI 1.7.10 V18b.jar, however there is no signature matching that description
> ```
> And this when I try to open a world:
> ```
> Encountered an unexpected exception
> java.lang.VerifyError: Expecting a stackmap frame at branch target 259
> Exception Details:
>   Location:
>     net/minecraft/world/gen/layer/GenLayerShore.func_75904_a(IIII)[I @260: ifnull
>   Reason:
>     Expected stackmap frame at this location.
>   Bytecode:
>     0x0000000: 2ab4 000e 1b04 641c 0464 1d05 6015 0405
>     0x0000010: 60b6 0012 3a05 1d15 0468 b800 183a 0603
>     0x0000020: 3607 1507 1504 a203 1f03 3608 1508 1da2
>     0x0000030: 0310 2a15 081b 6085 1507 1c60 85b6 001e
>     0x0000040: 1905 1508 0460 1507 0460 1d05 6068 602e
>     0x0000050: 3609 1509 b800 243a 0a15 09b2 0028 b400
>     0x0000060: 2ca0 00a1 1905 1508 0460 1507 0460 0464
>     0x0000070: 1d05 6068 602e 360b 1905 1508 0460 0460
>     0x0000080: 1507 0460 1d05 6068 602e 360c 1905 1508
>     0x0000090: 0460 0464 1507 0460 1d05 6068 602e 360d
>     0x00000a0: 1905 1508 0460 1507 0460 0460 1d05 6068
>     0x00000b0: 602e 360e 150b b200 2fb4 002c 9f00 2415
>     0x00000c0: 0cb2 002f b400 2c9f 0019 150d b200 2fb4
>     0x00000d0: 002c 9f00 0e15 0eb2 002f b400 2ca0 0016
>     0x00000e0: 1906 1508 1507 1d68 60b2 0032 b400 2c4f
>     0x00000f0: a700 0f19 0615 0815 071d 6860 1509 4fa7
>     0x0000100: 023a 190a c6ff ff19 0ab6 0036 1238 a6ff
>     0x0000110: ff19 0515 0804 6015 0704 6004 641d 0560
>     0x0000120: 6860 2e36 0b19 0515 0804 6004 6015 0704
>     0x0000130: 601d 0560 6860 2e36 0c19 0515 0804 6004
>     0x0000140: 6415 0704 601d 0560 6860 2e36 0d19 0515
>     0x0000150: 0804 6015 0704 6004 601d 0560 6860 2e36
>     0x0000160: 0e2a 150b b700 3c99 001e 2a15 0cb7 003c
>     0x0000170: 9900 152a 150d b700 3c99 000c 2a15 0eb7
>     0x0000180: 003c 9a00 1619 0615 0815 071d 6860 b200
>     0x0000190: 3fb4 002c 4fa7 ffff 150b b800 4499 000e
>     0x00001a0: 1509 b200 47b4 002c a000 c819 0515 0804
>     0x00001b0: 6015 0704 6004 641d 0560 6860 2e36 0b19
>     0x00001c0: 0515 0804 6004 6015 0704 601d 0560 6860
>     0x00001d0: 2e36 0c19 0515 0804 6004 6415 0704 601d
>     0x00001e0: 0560 6860 2e36 0d19 0515 0804 6015 0704
>     0x00001f0: 6004 601d 0560 6860 2e36 0e15 0bb8 004a
>     0x0000200: 9a00 1b15 0cb8 004a 9a00 1315 0db8 004a
>     0x0000210: 9a00 0b15 0eb8 004a 9900 1219 0615 0815
>     0x0000220: 071d 6860 1509 4fa7 0046 2a15 0bb7 004d
>     0x0000230: 9900 1e2a 150c b700 4d99 0015 2a15 0db7
>     0x0000240: 004d 9900 0c2a 150e b700 4d9a 0016 1906
>     0x0000250: 1508 1507 1d68 60b2 0050 b400 2c4f a700
>     0x0000260: 0f19 0615 0815 071d 6860 1509 4fa7 00cc
>     0x0000270: 1509 b200 2fb4 002c 9f00 b515 09b2 0053
>     0x0000280: b400 2c9f 00aa 1509 b200 56b4 002c 9f00
>     0x0000290: 9f15 09b2 0059 b400 2c9f 0094 1905 1508
>     0x00002a0: 0460 1507 0460 0464 1d05 6068 602e 360b
>     0x00002b0: 1905 1508 0460 0460 1507 0460 1d05 6068
>     0x00002c0: 602e 360c 1905 1508 0460 0464 1507 0460
>     0x00002d0: 1d05 6068 602e 360d 1905 1508 0460 1507
>     0x00002e0: 0460 0460 1d05 6068 602e 360e 150b b800
>     0x00002f0: 4a9a 001b 150c b800 4a9a 0013 150d b800
>     0x0000300: 4a9a 000b 150e b800 4a99 0015 1906 1508
>     0x0000310: 1507 1d68 6015 09b8 005e 4fa7 000f 1906
>     0x0000320: 1508 1507 1d68 6015 094f a700 0f19 0615
>     0x0000330: 0815 071d 6860 1509 4f84 0801 a7fc f084
>     0x0000340: 0701 a7fc e019 06b0                    
>   Stackmap Table:
>     append_frame(@34,Object[#26],Object[#26],Integer)
>     append_frame(@44,Integer)
>     same_frame_extended(@224)
>     append_frame(@243,Integer)
>     chop_frame(@255,1)
>     append_frame(@258,Integer,Object[#32])
>     chop_frame(@389,2)
>     full_frame(@408,{Object[#2],Integer,Integer,Integer,Integer,Object[#26],Object[#26],Integer,Integer,Integer,Top,Integer,Integer,Integer,Integer},{})
>     same_frame(@427)
>     same_frame_extended(@539)
>     full_frame(@554,{Object[#2],Integer,Integer,Integer,Integer,Object[#26],Object[#26],Integer,Integer,Integer,Top,Integer,Integer,Integer,Integer},{})
>     full_frame(@590,{Object[#2],Integer,Integer,Integer,Integer,Object[#26],Object[#26],Integer,Integer},{})
>     append_frame(@609,Integer)
>     chop_frame(@621,1)
>     append_frame(@624,Integer)
>     chop_frame(@780,1)
>     append_frame(@798,Integer)
>     chop_frame(@810,1)
>     append_frame(@813,Integer)
>     chop_frame(@825,1)
>     chop_frame(@831,1)
>     full_frame(@837,{Top,Top,Top,Top,Top,Top,Object[#26]},{})
> 
> 	at net.minecraft.world.gen.layer.GenLayer.func_75901_a(GenLayer.java:79)
> 	at net.minecraft.world.biome.WorldChunkManager.<init>(WorldChunkManager.java:40)
> 	at net.minecraft.world.biome.WorldChunkManager.<init>(WorldChunkManager.java:48)
> 	at net.minecraft.world.WorldType.getChunkManager(WorldType.java:143)
> 	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:61)
> 	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:44)
> 	at net.minecraft.world.World.<init>(World.java:244)
> 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
> 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
> ```
> I tried loading the 16d version of the mod and it gave the same first error but loaded a world just fine, so I tried loading THAT world (a world that already existed) with the newest version of the mod but it wouldn't work and gave me the same error as shown above. I don't have this problem with any other mods that I've tried (about a dozen) so I'm guessing it doesn't have anything to do with my end.
> 
> 
> Another thing, I get the same first error with the other mods (ReactorCraft, RotaryCraft, etc..." but instead of saying "DragonAPI" it says "MODNAMEHERE" (the signature may be different, I haven't checked)
> ```
> 
> ---- Minecraft Crash Report ----
> // Oops.
> 
> Time: 8/24/17 2:42 PM
> Description: Exception in server tick loop
> 
> java.lang.VerifyError: Expecting a stackmap frame at branch target 259
> Exception Details:
>   Location:
>     net/minecraft/world/gen/layer/GenLayerShore.func_75904_a(IIII)[I @260: ifnull
>   Reason:
>     Expected stackmap frame at this location.
>   Bytecode:
>     0x0000000: 2ab4 000e 1b04 641c 0464 1d05 6015 0405
>     0x0000010: 60b6 0012 3a05 1d15 0468 b800 183a 0603
>     0x0000020: 3607 1507 1504 a203 1f03 3608 1508 1da2
>     0x0000030: 0310 2a15 081b 6085 1507 1c60 85b6 001e
>     0x0000040: 1905 1508 0460 1507 0460 1d05 6068 602e
>     0x0000050: 3609 1509 b800 243a 0a15 09b2 0028 b400
>     0x0000060: 2ca0 00a1 1905 1508 0460 1507 0460 0464
>     0x0000070: 1d05 6068 602e 360b 1905 1508 0460 0460
>     0x0000080: 1507 0460 1d05 6068 602e 360c 1905 1508
>     0x0000090: 0460 0464 1507 0460 1d05 6068 602e 360d
>     0x00000a0: 1905 1508 0460 1507 0460 0460 1d05 6068
>     0x00000b0: 602e 360e 150b b200 2fb4 002c 9f00 2415
>     0x00000c0: 0cb2 002f b400 2c9f 0019 150d b200 2fb4
>     0x00000d0: 002c 9f00 0e15 0eb2 002f b400 2ca0 0016
>     0x00000e0: 1906 1508 1507 1d68 60b2 0032 b400 2c4f
>     0x00000f0: a700 0f19 0615 0815 071d 6860 1509 4fa7
>     0x0000100: 023a 190a c6ff ff19 0ab6 0036 1238 a6ff
>     0x0000110: ff19 0515 0804 6015 0704 6004 641d 0560
>     0x0000120: 6860 2e36 0b19 0515 0804 6004 6015 0704
>     0x0000130: 601d 0560 6860 2e36 0c19 0515 0804 6004
>     0x0000140: 6415 0704 601d 0560 6860 2e36 0d19 0515
>     0x0000150: 0804 6015 0704 6004 601d 0560 6860 2e36
>     0x0000160: 0e2a 150b b700 3c99 001e 2a15 0cb7 003c
>     0x0000170: 9900 152a 150d b700 3c99 000c 2a15 0eb7
>     0x0000180: 003c 9a00 1619 0615 0815 071d 6860 b200
>     0x0000190: 3fb4 002c 4fa7 ffff 150b b800 4499 000e
>     0x00001a0: 1509 b200 47b4 002c a000 c819 0515 0804
>     0x00001b0: 6015 0704 6004 641d 0560 6860 2e36 0b19
>     0x00001c0: 0515 0804 6004 6015 0704 601d 0560 6860
>     0x00001d0: 2e36 0c19 0515 0804 6004 6415 0704 601d
>     0x00001e0: 0560 6860 2e36 0d19 0515 0804 6015 0704
>     0x00001f0: 6004 601d 0560 6860 2e36 0e15 0bb8 004a
>     0x0000200: 9a00 1b15 0cb8 004a 9a00 1315 0db8 004a
>     0x0000210: 9a00 0b15 0eb8 004a 9900 1219 0615 0815
>     0x0000220: 071d 6860 1509 4fa7 0046 2a15 0bb7 004d
>     0x0000230: 9900 1e2a 150c b700 4d99 0015 2a15 0db7
>     0x0000240: 004d 9900 0c2a 150e b700 4d9a 0016 1906
>     0x0000250: 1508 1507 1d68 60b2 0050 b400 2c4f a700
>     0x0000260: 0f19 0615 0815 071d 6860 1509 4fa7 00cc
>     0x0000270: 1509 b200 2fb4 002c 9f00 b515 09b2 0053
>     0x0000280: b400 2c9f 00aa 1509 b200 56b4 002c 9f00
>     0x0000290: 9f15 09b2 0059 b400 2c9f 0094 1905 1508
>     0x00002a0: 0460 1507 0460 0464 1d05 6068 602e 360b
>     0x00002b0: 1905 1508 0460 0460 1507 0460 1d05 6068
>     0x00002c0: 602e 360c 1905 1508 0460 0464 1507 0460
>     0x00002d0: 1d05 6068 602e 360d 1905 1508 0460 1507
>     0x00002e0: 0460 0460 1d05 6068 602e 360e 150b b800
>     0x00002f0: 4a9a 001b 150c b800 4a9a 0013 150d b800
>     0x0000300: 4a9a 000b 150e b800 4a99 0015 1906 1508
>     0x0000310: 1507 1d68 6015 09b8 005e 4fa7 000f 1906
>     0x0000320: 1508 1507 1d68 6015 094f a700 0f19 0615
>     0x0000330: 0815 071d 6860 1509 4f84 0801 a7fc f084
>     0x0000340: 0701 a7fc e019 06b0                    
>   Stackmap Table:
>     append_frame(@34,Object[#26],Object[#26],Integer)
>     append_frame(@44,Integer)
>     same_frame_extended(@224)
>     append_frame(@243,Integer)
>     chop_frame(@255,1)
>     append_frame(@258,Integer,Object[#32])
>     chop_frame(@389,2)
>     full_frame(@408,{Object[#2],Integer,Integer,Integer,Integer,Object[#26],Object[#26],Integer,Integer,Integer,Top,Integer,Integer,Integer,Integer},{})
>     same_frame(@427)
>     same_frame_extended(@539)
>     full_frame(@554,{Object[#2],Integer,Integer,Integer,Integer,Object[#26],Object[#26],Integer,Integer,Integer,Top,Integer,Integer,Integer,Integer},{})
>     full_frame(@590,{Object[#2],Integer,Integer,Integer,Integer,Object[#26],Object[#26],Integer,Integer},{})
>     append_frame(@609,Integer)
>     chop_frame(@621,1)
>     append_frame(@624,Integer)
>     chop_frame(@780,1)
>     append_frame(@798,Integer)
>     chop_frame(@810,1)
>     append_frame(@813,Integer)
>     chop_frame(@825,1)
>     chop_frame(@831,1)
>     full_frame(@837,{Top,Top,Top,Top,Top,Top,Object[#26]},{})
> 
> 	at net.minecraft.world.gen.layer.GenLayer.func_75901_a(GenLayer.java:79)
> 	at net.minecraft.world.biome.WorldChunkManager.<init>(WorldChunkManager.java:40)
> 	at net.minecraft.world.chunk.storage.AnvilSaveConverter.func_75805_a(SourceFile:129)
> 	at net.minecraft.server.MinecraftServer.func_71237_c(MinecraftServer.java:162)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:59)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
> 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.7.10
> 	Operating System: Mac OS X (x86_64) version 10.12.6
> 	Java Version: 1.8.0_74, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 3657369560 bytes (3487 MB) / 3865509888 bytes (3686 MB) up to 3865509888 bytes (3686 MB)
> 	JVM Flags: 6 total; -Xmx4G -Xms4G -Xmn4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
> 	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 5 mods loaded, 5 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
> 	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
> 	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
> 	UCHIJAAAA	DragonAPI{v18b} [DragonAPI] (DragonAPI 1.7.10 V18b.jar) 
> 	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
> 	Profiler Position: N/A (disabled)
> 	Player Count: 0 / 8; []
> 	Type: Integrated Server (map_client.txt)
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 
> ```
> Sorry if I didn't give anything or enough useful information, like I said earlier, this is my first time doing this.
> 
> If you could respond and tell me how helpful (or not) this was, that would be amazing. If this is something on my end, and you know what it is (and have time), a bit of help would be nice.
> 
> Thanks for your time.

**Comment by ReikaKalseki** [comment]
Update Forge.

#1437
