### ISSUE TITLE
[CC] Crash when brown pylon and cave crystal applies effect on player

### ISSUE THREAD

**Issue by DweiaCaelum** [ReikaKalseki/Reika_Mods_Issues#1569]
Whenever a Brown pylon zaps me or a brown cave crystal applies an effect on me, I get this crash:

http://paste.feed-the-beast.com/view/3c40c3bf

I'm using v18b, but I had the same crash before I updated as well. After the crash, I can't log back in unless I revert to an earlier backup. 

I checked for conflicting potion id's but I couldn't find any.

**Comment by ReikaKalseki** [comment]
I have seen this before, and the cause was some other mod modifying the way potions work. That error contains none of my code.

**Comment by DweiaCaelum** [comment]
I see, sorry for wasting your time. Is it too much to hope that you'd remember which mod it might be?

**Comment by ReikaKalseki** [comment]
It has been a long time, so no, I do not remember.

**Comment by DweiaCaelum** [comment]
Thanks anyways. Sorry to waste your time.
