### ISSUE TITLE
Extractor taking too long or UI drawing issue

### ISSUE THREAD

**Issue by clubpetey** [ReikaKalseki/Reika_Mods_Issues#157]
Background: I have a Performance engine connected to a CVT that alternates between 4x Torque and 16x Speed powering an Extractor.

RotC: 7f
DragonAPI: 7f
ReactorCraft: 7f
Forge: 1388
MC: 1.7.10

When I pull up the extractor UI I have several problems.
1. When in "Torque mode" running phases 1 and 4, the UI shows that I don't have power for phases 1 and 4, however, you can see the phase 4 progress icon moving.  
2. The phase 4 progress icon fills up but no flake is produced.  The progress icon continues past complete and draws into the upper input box.  After some time, the flake is produced.  So I'm not sure if phase 4 is supposed to take longer than the progress Icon, or if the timing is right, but the UI drawing is wrong.

![2015-07-19_01 48 38](https://cloud.githubusercontent.com/assets/2221486/8765316/4b8ad7e6-2dbb-11e5-9ba4-8a1a8750c834.png)
1. Similarly, the Phase 1 progress icon fills and continues past and starts showing the phase 4 icon. You can also see again here that the Torque bars show that phase 2/3 are good, but phase 1 is the one currently running.

![2015-07-19_01 49 54](https://cloud.githubusercontent.com/assets/2221486/8765320/7a1abc16-2dbb-11e5-8d25-81e8fec884f8.png)

**Comment by ReikaKalseki** [comment]
The GUI drawing code is a simple fraction, `currentTick*pixelHeight/requiredTicks`. It should never exceeed the value pixelHeight, because once currentTick reaches requiredTicks the operation should be performed and the timer would reset.

I suspect a client-server desync, such that the time on the server is longer on the client (lower speed serverside).

**Comment by clubpetey** [comment]
That may be the case, as I do not get this behavior in a single player world.  Could FastCraft be causing this?  Also, do you know of a way to either see the server tick rate or force the client to sync?

Also, I noticed that the progress rendering of stages 2 and 3 do not show this issue.

**Comment by ReikaKalseki** [comment]
I suspect FastCraft is not the culprit - the code involved is power transfer - but you can try.

**Comment by ReikaKalseki** [comment]
Question: Is the CVT in redstone mode, and if so, what is the signal source? Try using a vanilla lever next to it.

I have a strong suspicion I know what is wrong.

**Comment by clubpetey** [comment]
The CVT is in redstone mode, the source is a redstone torch linked to EnderIO Insulated Redstone Conduit linked to the CVT.  I'll try a standard redstone torch when I get on later tonight.

**Comment by ReikaKalseki** [comment]
Bingo. EnderIO only gives redstone on the server, making the clientside CVT still in torque mode, having a lower speed.

**Comment by clubpetey** [comment]
Yep.  Standard torch works correctly, but EnderIO, ProjectRed Cable, and MFR Rednet Cable all show the same issue.  Is there a way to get the CVT to update correctly in this scenario?

**Comment by ReikaKalseki** [comment]
I know from experience ProjectRed works perfectly.
