### ISSUE TITLE
[RC][ChC] List of issues and suggestions #2

### ISSUE THREAD

**Issue by DaFuqs** [ReikaKalseki/Reika_Mods_Issues#1570]
It seems like my resolution to try out every item and machine is prone to cause errors. I'm sorry to cause all this uproar. :|
Here's another collective list of issues and some suggestions, because I don't want to spam the respository with all the individual issues that may even be fully intended that way.

Mods used are v18b SMP

# BUGS:

## Rotarycraft:

1. When a Light Bridge is started, destination chunks unloaded/reloaded and the Light bridge then unpowered, there sometimes are a few unbreakable bridge blocks left behind. (That might very hard to fix, though)

## Chromaticraft:
1. Capture Star: Catching a Forestry Butterfly crashes the client. The butterfly is successfully catched, though. https://pastebin.com/EeS3tJQm
2. Construction Star: Using it on Forestry leaves places "for.leaves.corrupted Leaves" when in creative. In suvival mode sheared forestry leaves cannot be placed at all. A reference test on mob spawners showed that using the replication star will default to pigs instead of the original mob. Guess NBT is not checked/set correctly?
3. Crystal Furnace: There exists a feedback loop with Gendustry's gene samples. Those should be excluded from the smelting multiplication to prevent duping. Item ID [gendustry:GeneSample] (contains NBT with the gene type) is smelted / cleared to 2 [gendustry:GeneSampleBlank], which can be imprinted and smelted again to 4 clear ones.
4. RF Distribution Node: Trying to push RF to machines disconnects the client shortly after the first pulse. This happens only in SMP, not SSP/Lan. https://pastebin.com/wR9gjZej
5. Ritual Table: After entering the Dimension / Finding the first elemental core I've unlocked a small list of new rituals. The Fragments are all in the handbook, but the rituals are not available on the Second Tier Ritual Table. 
~~6. Progression: Pylon Turbocharging is unlocked right after entering the dimension, but is (afaik) only available after the elemental core of the right color is aquired. Change the required progression step to STRUCTCOMPLETE?~~ (I'm dumb)

# SUGGESTIONS

## Rotarycraft
1. Music Box: Allow increasing the range with scaled power. Also maybe reuse the midi loader and parser the CC crystal Orchestsa has? (separate from the rcmusic files)
2. Particle Display: Allow shaft power input instead of wind springs only, that need to be replaced every now and then.
3. Force and Containment Fields: Those fields look very... makeshifty. Guess those are one of your very early machines? Looking at the more recent models in Chromaticraft you surely improved a lot and could make way nicer textures for the fields instead of a few lines only, making them actually viable to use.
4. Projector: The trace lines are very distracting. Maybe remove them or make them partially translucent?
5. Drop Processor: Generate XP on block break, like ores. If that would even be possible, that is.

## Chromaticraft:
1. Glowing Ornaments: The gold, obsidian and quartz based ones are not craftable. Why is that? They seem fully functional in creative and look really nice.
2. Crystal Cell: Ability to store vanilla dyes (the Chromaticraft ones are disabled by default after all), the framed, glowing ornaments, and the different versions of Lumen Relays (should anyone ever want to craft the not omni ones for reasons I don't understand)
3. Handbook: When clicking on a progression item, like the Dimension one, there are a lot of prerequisites. Could the lines to the other progression items be colored red/green based of on if the prerequisite is fullfilled?
4. Dye Flowers: Make them replaceable on block placing, like grass and vanilla flowers. Would make building in a Rainbow Forest way easier.

**Comment by ReikaKalseki** [comment]
> Construction Star: Using it on Forestry leaves places "for.leaves.corrupted Leaves" when in creative. In suvival mode sheared forestry leaves cannot be placed at all. A reference test on mopb spawners showed that using the replication star will default lto pigs instead of the original mob. Guess NBT is not checked/set correctly?

This is not something I can safely fix. Copying all NBT would also copy location-specific information, which would lead to a great many crashes.

> RF Distribution Node: Trying to push RF to machines disconnects the client shortly after the first pulse. This happens only in SMP, not SSP/Lan.

I need a serverside log.

> Progression: Pylon Turbocharging is unlocked right after entering the dimension, but is (afaik) only available, after the elemental core of the right color is aquired. Change the required progression step to STRUCTCOMPLETE?

I am not changing that, but I do agree that there needs to be some indication.

> Music Box: Allow increasing the range with scaled power.

Not possible. Sounds play for a max of 16 blocks. unless they do not attenuate at all.

> Particle Display: Allow shaft power input instead of wind springs only, that need to be replaced every then and now.

It is not possible to make a machine require both, and I am not going to make it require shaft power.

> Projector: The trace lines are very distracting. Maybe remove them or make them partially translucent?

There is a config to do this.

> Drop Processor: Generate XP on block break, like ores. If that would even be possible, that is.

I am against this idea, not for balance reasons but implementation: There are only two options, dropping orbs by the machine - which gets messy and potentially laggy if there is no cleanup system - or adding an xp handling system like the Vacuum, which is far too much to implement for this.

> Glowing Ornaments: The gold, obsidian and quartz based ones are not craftable. Why is that?

Yes they are...

> Crystal Cell: Ability to store vanilla dyes (the Chromaticraft ones are disabled by default after all), the framed, glowing ornaments, and the different versions of Lumen Relays (should anyone ever want to craft the not omni ones for reasons I don't understand)

The Crystal cell looks for `ItemCrystalType`, and none of those items you suggested are that type.

> Dye Flowers: Make them replaceable on block placing, like grass and vanilla flowers. Would make building in a Rainbow Forest way easier.

Vanilla flowers are not either - at least not in vanilla - and I strongly dislike such mechanics.

**Comment by DaFuqs** [comment]
> I need a serverside log.

I'll see what I can do.

> Yes they are...

Just checked. Yes, they really are, you are right. But the NEI recipe key doesn't work on them for me. Whyever that is.

> The Crystal cell looks for ItemCrystalType, and none of those items you suggested are that type.

That's why I've suggested those additional types ;)

**Comment by OvermindDL1** [comment]
> This is not something I can safely fix. Copying all NBT would also copy location-specific information, which would lead to a great many crashes.

The general workaround for this is just to not set the built-in TE standard coords.  Blocks should work fine in that case and those that need to be location aware generally will contain a copy and detect when it changes from the base set (this was popularized way way back in the RedPower 2 days when frames crashed mods when the mods assumed no moving, so this style was done by many to detect that).

**Comment by ReikaKalseki** [comment]
> The general workaround for this is just to not set the built-in TE standard coords.

That is not enough. Many machines have other location-sensitive data that is not updated - or even *updateable* - if you move it.

**Comment by OvermindDL1** [comment]
> That is not enough. Many machines have other location-sensitive data that is not updated - or even updateable - if you move it.

There was a PR going in to forge at one point that marked a TE as moveable so a mod would know what was safe and what was not, if only it got in long ago.  As I recall it died.  ^.^;

Though it died only because the method I described worked 'well enough' for everyone involved.

But overall, if machines have other location-sensitive data that is not updated, well it should not be updated.  The way moving worked is that you copied the NBT over except for the Stock/Standard coordinate data.  The TE 'itself' (not the mover) either does not care about its location and does nothing (like Forestry's leaves), or they keep a copy of their coords in another field and compared that to the actual coords, and if it changed then it updated everything else as appropriate (or explode, mod choice depending).  Most mods work fine with this style (I can't think of any that I've tried moving blocks of in 1.7.10 that crashed using this method, they either moved fine, moved smart, or exploded depending on what the mod wanted to do, though I've never tried moving any blocks from Reika's Mods (this was not the question anyway)).

**Comment by ReikaKalseki** [comment]
Wires (that are part of a network object), for example.

**Comment by OvermindDL1** [comment]
> Wires (that are part of a network object), for example.

Yep, you'd just have it store a copy of its coordinates and on tick then test if they are the same, if not then reset it's state to like it was just placed down as one possible example.

**Comment by ReikaKalseki** [comment]
And if I do not control the wire's code?

**Comment by OvermindDL1** [comment]
> And if I do not control the wire's code?

Then whoever does let them do whatever they do, it's their fault they do not follow the way that mods have been doing for 3-4 years for supporting moveability or not.  Most mods that move things around usually support a blacklist of things to DoNotMove (some do a whitelist, like AE2 uses a whitelist for its ability to move blocks via Pylons), but in general most things will 'just work'.  (I could even see some hueristics like if NBT is above a certain size then don't unless whitelisted, if smaller then do unless blacklisted, perhaps some other tests as well, but eh, too much there).

Still though, if a TE crashes 'later' after its been moved, that should be reported to the author of that mod because that can even happen in some vanilla MC cases (usually when chunks get swapped around, which *STILL* rarely happens in 1.7.10, grr).

**Comment by ReikaKalseki** [comment]
Whenever I am even tangentially involved in a crash, the other developer almost without fail points the blame at me. Your approach is a recipe for endless headaches.

**Comment by OvermindDL1** [comment]
> Whenever I am even tangentially involved in a crash, the other developer almost without fail points the blame at me. Your approach is a recipe for endless headaches.

Could go the GT route and throw `NotMyFaultException`'s.  ^.^

_/me is entirely for yelling at the rightful cause of errors_

With better Type Systems such issues would just categorically not be possible, which sadly Java entirely lacks...  I really hate Java...

**Comment by ReikaKalseki** [comment]
I just redid the force field:

![http://i.imgur.com/OHRvfJk.jpg](http://i.imgur.com/OHRvfJk.jpg)
![http://i.imgur.com/v9f0mGE.jpg](http://i.imgur.com/v9f0mGE.jpg)

GIF:
https://imgur.com/lqkWZ3j

**Comment by DaFuqs** [comment]
Now THAT looks like a force field worth using. Awesome!

**Comment by ReikaKalseki** [comment]
It should be rather more performant, too.

**Comment by ReikaKalseki** [comment]
Everything that had fixes or code changes planned is done.
