### ISSUE TITLE
Using the "Fusion Plasma Injector" block causes the backup system from forgeessentials to crash

### ISSUE THREAD

**Issue by nightcore500** [ReikaKalseki/Reika_Mods_Issues#1571]
Hey, 
I'm not sure if it is a forgeessentials or a reactorcraft problem. As soon as I place a fusion plasma injector block and execute a backup the backup module of forgeessentials crashes.
I have the console output uploaded here:
https://pastebin.com/Tc7Pe2Sn

**Comment by ReikaKalseki** [comment]
It is a `NoSuchMethodError`, i.e. if this were a code error on my end the mod would not even compile due to calling a nonexistent function. Therefore, this has to be classloading-related or something, and almost certainly on someone else's end.
