### ISSUE TITLE
DragonAPI seems to break Reliquary's Tome of Alkahest crafting recipes

### ISSUE THREAD

**Issue by Lonemind** [ReikaKalseki/Reika_Mods_Issues#1572]
When using DragonAPI and Reliquary together the Tome of Alkahest no longer recognizes it's own recipes. The Tome is meant to be used as a duplication device, allowing you to use an internal storage of redstone to duplicate items such as dirt, cobble, iron ingots, etc. at the cost of said redstone.
With DragonAPI installed trying to craft any of these recipes simply does not show or give an output.

I tried adding in a recipe (dirt) using MineTweaker and that worked for one single crafting of the item. It damaged the Tome (which is what's supposed to happen) but then trying it a second time failed. I assume because the Tome's metadata had changed.

**Comment by ReikaKalseki** [comment]
This is probably a variation on the ExU enchanted wood recipe issue. The fix is on their end, to not register the recipe in pre-init.

You can verify this cause by looking into the logs; you will see a great many warnings about pre-init recipes, one of which should be this one.

**Comment by Lonemind** [comment]
Ah, yes. I see that you are correct. Dragon API removed these recipes for that reason. Is there no workaround? Sadly, Reliquary no longer supports 1.7.10. I appreciate you looking at the report.

Edit: If I re-add the recipes using MineTweaker would that still cause the problems that having them in the pre-init would cause?

**Comment by ReikaKalseki** [comment]
Minetweaker adds its recipes very, very *late*, so it will not be subject to this issue, but may possibly be to something else. However, this is likely a special recipe object, something Minetweaker cannot create.
