### ISSUE TITLE
[Chromaticraft] Can not get progress without crushing Crystal Hive

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1573]
Hi,
You Stuck in the CC Progression on the Power Crystal Fragments when you did not have installed Forestry.

**Comment by ReikaKalseki** [comment]
Not true, and I saw your post on MCF and you are not understanding what you are seeing. Unless you actually *do* have Forestry, in which case this is not a bug.

**Comment by Kobra331** [comment]
I have not Forestry installed!

**Comment by ReikaKalseki** [comment]
Well, the progress flags dependent on it are not stopping you.

**Comment by ReikaKalseki** [comment]
Well, I did find a different issue regarding a Forestry dependency, and *that* is now fixed.

**Comment by Kobra331** [comment]
I don't know what you have fixed, but i can't understand why you don't believe me. Since 2 years i try to help to find bugs ( i know not 100% correct and sometimes my fault, but i do my best) and i played 3 Times through the complete Chromaticraft Progression on my own private Server without cheating.
I haven't Forestry installed.
I had every visible Progression in the Chroma lexicon except Mysterious Relics.
I crafted all Energized Cores, all not Energized Cores and every item which got them in it except the Alloying Tank.
I didn't got the Power crystal fragment.
"/Chromaprog debug all" says missing progression "BEEALYZE"

ONLY after creative placing the Crystal hive and breaking them i got the Progress AND the Power crystal Fragment (and some others) and the Notification that i am now in the endgame of Chromaticraft.

Funfact: ~2 Years ago on my first Playthrough through Chromaticraft i had the same problem with the crystal hive to reach "early game" where you have written "this is a non gating Progression". But it was.

Greets

**Comment by ReikaKalseki** [comment]
> "/Chromaprog debug all" says missing progression "BEEALYZE"

Yes, and you did not understand what you were seeing. This is why players are not supposed to use debug tools. That said, I have changed the command so that non-gating entries will not be shown.

**Comment by Kobra331** [comment]
Thats right, im not understand everything from the command, it was just another try to find the missing progression because i tried nearly everything other.
