### ISSUE TITLE
[CrC] Shape problem with the Area Brealer

### ISSUE THREAD

**Issue by chaos234** [ReikaKalseki/Reika_Mods_Issues#1574]
Here is an image from the area breaker set to 10

![2017-08-29_06 03 53](https://user-images.githubusercontent.com/340106/29993045-33154b5c-8fab-11e7-9dd6-336f53b78223.png)

Problem is that I selected the cuboid image but at the last few lines it ended up to build a pyramid shape like stlye which I think is not intended.

Latest Version is used.

**Comment by ReikaKalseki** [comment]
This is in fact intentional.
