### ISSUE TITLE
Crash on using a Glowing Pylon

### ISSUE THREAD

**Issue by SigurdCole** [ReikaKalseki/Reika_Mods_Issues#1576]
Chromaticraft 18b, had a complete client freeze after successfully right-clicking a glowing pylon into activation. MC log is completely empty of related events (just saving chunks from pauses etc). World not corrupted, progress entry unlocked on world load.

Modlist: AppleCore 1.3.9, CodeChickenCore 1.0.7.47, FastCraft 1.23, FastLeafDecay 1.4, Journeymap 5.1.4p2, NEI 1.0.5.120, NEResources 0.1.0-122, Waila 1.5.10, Wawla 1.0.5.120

Happy to submit anything useful! And it was a really cool charging-up effect!

**Comment by ReikaKalseki** [comment]
That cannot be your entire modlist - for example, it does not ChromatiCraft. Also, I cannot do anything without more information, and if you were not given more, then that cannot change.
