### ISSUE TITLE
[VoidMonster] is rendered clientside

### ISSUE THREAD

**Issue by DaFuqs** [ReikaKalseki/Reika_Mods_Issues#1577]
I've modified the default VoidMonster config file to look like this:

  # Configuration file
  
  "control setup" {
    I:"Banned Dimensions" <
        0
        -1
     >
    B:"Dimension list is actually whitelist"=true
    I:"Sound Interval in Ticks"=80
    D:"Void Monster Difficulty Factor"=1
  }

Regardless of "Dimension list is actually whitelist" (on both client and server) there exists a clientside void monster in mystcraft worlds, most noticeable in void and island worlds with the "no seas" page. It even applies the visual effects clientside, but does never move or deal real damage outside of the teleporting.

**Comment by ReikaKalseki** [comment]
Clientside void monster is an artifact of vanilla code and server desync, and cannot be fixed. However, it only exists where a serverside one does.

**Comment by ReikaKalseki** [comment]
I prevented all clientside spawns.
