### ISSUE TITLE
RoC v18b Magnetizing Unit charging multiple Shaft Cores at once

### ISSUE THREAD

**Issue by Rewyn** [ReikaKalseki/Reika_Mods_Issues#1578]
This test was done with nothing but DragonAPI, Rotarycraft, NEI, CodeChickenCore, EnderCore and EnderIO.
Versions used
DragonAPI 1.7.10 V18b
RotaryCraft 1.7.10 V18b
EnderIO-1.7.10-2.3.0.429_beta
EnderCore-1.7.10-0.2.0.39_beta

Basically just a chest hooked up to the Magnetizing Unit with Item Conduits from EnderIO
Since the Item Conduits transport 4 (with upgrades up to a stack, as seen in the screenshots) items at once, the magnetizing unit receives 4 (or more) cores and charges them all at once.
http://imgur.com/a/R4CAe

**Comment by ReikaKalseki** [comment]
I am not sure this is a bug.

**Comment by Rewyn** [comment]
I just realized, you can also put in more than one by hand... Not sure if that was different in the past, or why I thought it to be strange. Maybe they didn't charge when you had more than one inserted..?

Going by the model (and somewhat common sense) it looks/"feels" rather wrong to be able to insert more than one at a time at least. Also having to charge up to a full stack at once for maximum efficiency feels... rather wrong as well.
Maybe just me. If that's the case, don't mind me.

**Comment by ReikaKalseki** [comment]
I will deliberate on this.

**Comment by ReikaKalseki** [comment]
Cores are no longer magnetizable in stacks.
