### ISSUE TITLE
Cannot process non-vanilla ores in Extractor

### ISSUE THREAD

**Issue by clubpetey** [ReikaKalseki/Reika_Mods_Issues#158]
I've tried ores from Thermal Expansion, Forestry, and Tinker's Construct.  None of them will process through phase 1 in the extractor.  Iron/Gold process just fine. I know I saw this bug in v6 and a note that it was fixed in v7.  I was using config files from v6, and upgraded to v7, so if there's a config setting to make the non-vanilla ores work, let me know.

RotC/DragonAPI: 7f
Forge: 1388

Thanks
-pete

**Comment by Braidedheadman** [comment]
Try disabling RotaryCraft integration in the Another One Bites the Dust (AODB) config file. This fixed my extractor, which was having similar problems.

**Comment by ljfa-ag** [comment]
Duplicate of #144 (or somethnig else)
