### ISSUE TITLE
Please, support Uranium.

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#1581]
Cauldron, KCauldron, Thermos is absolutely dead. However, one server side has always been updated: Uranium. Which not only fixes a lot of BUG, is compatible with the latest SpigotAPI, and even supports 1.8+ title and actionbar.
Uranium project: https://ci.xjboss.net/job/Uranium-dev/
My server completely removed all Reika's Mod when Thermos stopped updating. I can't only use Forge to make a server. The emergence of Uranium made me see hope.
So, can you try to support it? It's just ASM's problem.
Thank you very much!

**Comment by OvermindDL1** [comment]
I'm guessing you don't realize how much work it is to ASM into different codebases?  If you wrote it and PR'd it (not withstanding the entire lack of a build and testing infrastructure in Reika's code, which is extremely horrible I do admit) then Reika 'might' accept it if it remained compatible in the future.

**Comment by ghost** [comment]
I'm not a developer. I'm just a server master and a gamer. I only know one thing, that is, a Mod should adapt to more things, let players benefit, rather than take a strange route. If a Mod is unable to meet the needs of the players, then I will not hesitate to delete, abandon it. After all, there are lots of great Mod.
This is just a suggestion (and a request), not imposed on you.
If can not, that doesn't affect me, either. I just give expression to many server master's aspirations. @

**Comment by OvermindDL1** [comment]
@SourcePowered Do remember that Reika makes their mods primarily for their own use, hence why it is still on 1.7.10 instead of newer as well.  Doing ASM for platforms you do not use is *incredibly* hard due to the sheer amount of time it takes to do and test, so asking someone to just add it in is disingenuous at best.  If Reika had a half-decent build system I'd even be PR'ing things in as it has a *lot* of bugs, but I just can't be bothered to (if Reika won't make it easy to PR then why should I care to make PR's, like the model work fixes I'd probably have had done by now).

_/me is still of the opinion that the spigot servers are fairly useless_
Really though I don't see the point of them, mods on forge can already do what it does, can make your own easily enough as well, if you need to lock down, say, area protection I prefer in-game methods for that, like force fields and so forth, not magical unexplainable-in-world commands that make no sense in gameplay....

**Comment by ReikaKalseki** [comment]
> (if Reika won't make it easy to PR then why should I care to make PR's, like the model work fixes I'd probably have had done by now

I always want to code things myself anyways.

**Comment by OvermindDL1** [comment]
> I always want to code things myself anyways.

Heh, I relate, but still, jumping into OGL efficient model handling is not something light.  ^.^;

Still does not seem easy to recreate and set your workspace if your everything caught fire or something though.  I put setups in repo's where all I have to do is `git clone` it then usually just run a single command to get everything fully setup and ready again.  I'm lazy so I like to minimize work.  ^.^

**Comment by ReikaKalseki** [comment]
I deliberately make my workspace impossible to clone, so I do not have to worry about people making illegitimate copies of my mods.

**Comment by OvermindDL1** [comment]
> I deliberately make my workspace impossible to clone, so I do not have to worry about people making illegitimate copies of my mods.

Uh, isn't it still easy enough to setup a new gradle project for forge, dump the source in, and compile (maybe fixing up a few things)?  That sounds painful to fix up if your everything caught fire...  o.O

Not to mention just simple bytecode editing (of which I've done excessively to fix mods that have broken things when the authors have vanished).

**Comment by ReikaKalseki** [comment]
No, you would be missing several things required to run my code, as well as build jars that resemble mine.

**Comment by OvermindDL1** [comment]
> No, you would be missing several things required to run my code, as well as build jars that resemble mine.

Eh, worst case could just decompile the jar (I have probably a hundred directories of decompiled jars on my home system currently to more easily examine how they break things as I bug hunt non-open source mods), also not that hard.

**Comment by ReikaKalseki** [comment]
No, because the jar, if dropped into a dev environment, would throw hundreds of errors. Also, the jars themselves contain additional metadata.

**Comment by OvermindDL1** [comment]
> No, because the jar, if dropped into a dev environment, would throw hundreds of errors. Also, the jars themselves contain additional metadata.

Of course, if someone wants to edit it then could just decompile it through MCP, easy to do.

If someone wants to make a mod on top of something like rotarycraft, that is what dev/deobf jars are for (or just reflect dynamically).

**Comment by ReikaKalseki** [comment]
> Of course, if someone wants to edit it then could just decompile it through MCP, easy to do.

No, that is not what I mean. My MCP mappings are custom, there are classes/methods not part of the base installation, and there are all sorts of other "invalid code appearance" cases.

**Comment by OvermindDL1** [comment]
> No, that is not what I mean. My MCP mappings are custom, there are classes/methods not part of the base installation, and there are all sorts of other "invalid code appearance" cases.

The mappings can be custom, that is fine, the distributed jar though is obfuscated with stock MC mappings as it has to load into stock MC, from there you can remap them to anything you wish.  The distributed jar is fully operational so even if they call into 'MC' methods that are added via assembly those are easily and individually remappable even via script, and finding them is fairly trivial as well via a class scanner.  All stuff I've done innumerable times in the past.  Java is *anything* but secure.  ^.^
