### ISSUE TITLE
Dragon API/Reactorcraft/Rotarycraft Crash with Mystcraft

### ISSUE THREAD

**Issue by 69759** [ReikaKalseki/Reika_Mods_Issues#1583]
So I've been trying for a few hours and I just fixed a comparability error between Forestery and AM2 caused by Dragon API or related mods as it works without Dragon API and now I'm getting an error with Mystcraft, any help?

Crash event in the fml launcher code: https://pastebin.com/47Xmmquq

**Comment by ReikaKalseki** [comment]
#1566 #1437
