### ISSUE TITLE
[RotaryCraft] Waila RF consumption incorrect

### ISSUE THREAD

**Issue by roc13x** [ReikaKalseki/Reika_Mods_Issues#1585]
Magnetostatic engines consume a very different amount of RF/t than the amount they display in Waila.
In the example below you can see Waila reports the engine using 208k RF/t while it actually uses 312k. Which amount is supposed to be the correct one?

![w08jb1u](https://user-images.githubusercontent.com/829449/30522899-5e84454c-9bcf-11e7-9a7e-182a6bfe1edb.png)

![9a7v4wg](https://user-images.githubusercontent.com/829449/30522901-62ff63b8-9bcf-11e7-8e77-0cd9617738d0.png)

**Comment by ReikaKalseki** [comment]
The larger value; the other was not taking engine inefficiencies into account.

**Comment by ReikaKalseki** [comment]
I just checked, and the display value does read the inefficiency. But a 150% consumption rate is *exactly* that of an engine still spinning up.

EDIT:
OK, the spinup penalty apparently always applied. Fixed.

**Comment by roc13x** [comment]
Aha, that explains it. Thanks!
