### ISSUE TITLE
[CC] Adjacency checks energy-dependent

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1586]
Hi, i tested it in single player and on a Server. The effiency and the Performance Adjacency Augments don't work on the mineral extractor anymore. It extracts even with max level Cores only unsilktouched ores at maximum cost. I didn't read any changes in the changelog about this.
I tried a Lumen distribution node to charge them but nothing happens. ( From the config: B:"Adjacency Upgrades Require Energy"=false)

Edit: i changed the config entry to "true" now the cores get energy and work on the extractor

**Comment by ReikaKalseki** [comment]
Fixed.
