### ISSUE TITLE
[Chromaticraft] Crash to desktop when shift+right clicking to open lexicon

### ISSUE THREAD

**Issue by Rythern** [ReikaKalseki/Reika_Mods_Issues#1587]
[Crash Report](https://pastebin.com/xria2WRd)

On latest Chromaticraft/DragonAPI; using a self-made modpack of ~95 mods. 

Have tried a few things to isolate the issue to no avail. Happens ONLY when playing on server, have tested on two different machines/usernames which produce the same error. Works fine when playing single player. Tried making another world for the server, same result. Tried spawning in a new lexicon, resetting chroma prog, deleting user / chroma dat on the server + restarting both client and server.

Curiously, the issue seemed to come out of nowhere. Was working normally until today, which is probably the most frustrating part. Seemed to happen when updating from v16d -> 18b. I thought it might have been related to the world due to the update, or perhaps because of attempted retrogen that didn't play nice with the server, but a new world would logically rule those things out. Moreover, it seems to be client side, but _only_ when playing on server/multiplayer. (That is, the server does not crash or show any errors, merely that the user disconnected; again, loading a SP world and shift+right clicking does not reproduce the issue). 

I'm not very savvy with code, but cursory searching seemed to lead me to think it's related to some reference to the GUI. (The shift+right click on the lexicon is the only GUI to produce this issue; I attempted a number of client-side things like adjusting graphics settings and disabling NEI/WAILIA to no avail, but have yet to try all-together removing client-side mods, though given that it happens server-side only, I'm dubious that this would prove effective).

Any help is extremely appreciated. Apologies in advance if the error is obvious and I'm just a derp.

**Comment by ReikaKalseki** [comment]
Your progression data does not match between client and server, be that due to a modlist difference, config changes, or anything else. In particular, there are fewer progression entries on the client than the server.

**Comment by Rythern** [comment]
Thank you, Reika! I'll give it another look.
