### ISSUE TITLE
[Rotarycraft] Electric Generator Bug found

### ISSUE THREAD

**Issue by Maur0Mal** [ReikaKalseki/Reika_Mods_Issues#1588]
Hi Reika and thanks for your mods i use they everydays!
I want report to you a bug never fixed in Rotarycraft:
When i use Electric Generator connected to Superconductor EU cable or Glass fibre cable, when i close my game and reload the world or sometime when i change area and i return to that area the generator does not transfer the energy to the destination machine inventory and i must remove and replace the cable for make it to function.
The problem is the connection between the generator and the cable ( if you attach a glass fiber cable you can see a "disconnect" effect on it when the bug is going on).
If you want i can attach a screenshot.
Thanks in advice i hope i can help, and i hope you can fix it.

**Comment by ReikaKalseki** [comment]
Does a block update fix the problem? This is probably a tile load order issue.

**Comment by Maur0Mal** [comment]
No it doesn't fix the problem. I Tested it in creative and survival, differents worlds and modpacks.
This strange issue is really strange. (i play 17 and 18 versions of your mods in two differents saves both have this problem). For see this event it's simple: place the generator and the cable and exit to main menu and reload or change area or dimension and return (glass fiber give a grafical effect, superconductive Eu cable no but both does not transfer power). 
Here a screenshot.
![2017-09-18_21 31 07](https://user-images.githubusercontent.com/28701704/30560927-aa0ffcd2-9cb9-11e7-8cd0-f338b321b859.png)

**Comment by ReikaKalseki** [comment]
The problem *does* go away with a block update. So generators will trigger block updates once every 1.5 seconds just to ensure the connectivity is rebuilt. Not a perfect fix, but the best that can be done.

**Comment by Maur0Mal** [comment]
Ok thanks for the support! I'm your big fan :)
Bye!
