### ISSUE TITLE
[Reactorcraft] smelting thorium gets you a weird double arrow item that is useless

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#159]
Smelting thorium in a furnace gives a "Thorium Fuel Pellet" with the same entry in the ore dict as the ingot (ingotThorium) but this item is completely useless!! See picture for recipe...
![2015-07-19_21 00 02](https://cloud.githubusercontent.com/assets/8153290/8769804/26434aa0-2e5a-11e5-92e1-db056010c5e7.png)

I didn't hover over the item though, I will get another screenshot that shows more info

**Comment by ReikaKalseki** [comment]
Out of date texture pack.

**Comment by Zedrimar** [comment]
its not from a texturepack

**Comment by Zedrimar** [comment]
its just the mod's image itself

**Comment by Zedrimar** [comment]
reika, what do you want me to do to prove this huh?

**Comment by Zedrimar** [comment]
I am not lying XD

**Comment by Zedrimar** [comment]
want a clip? its gonna prob. shred my CPU to bits but I can make one just to prove that this is not a texture pack that is outdated!

infact I will show you that even with no texture pack this is existant... Video quality will not be good due to me having an old PC

**Comment by Zedrimar** [comment]
![mods list](https://cloud.githubusercontent.com/assets/8153290/8770019/812510c6-2e5e-11e5-9a42-a258709ac8fe.PNG)

Video is uploading and I will update the comment with the link to the dropbox file when its done

Update: https://www.dropbox.com/s/lpe4jo9awe6d9wx/Reactorcraft%20derp.avi?dl=0

This video is UN-EDITED and shows that there are NO texture packs in the runtime and that what is shown is REAL. However if somehow some way you refuse to believe the facts, go test it yourself :P

**Comment by Zedrimar** [comment]
Also I should add that the only ways I have found to obtain this "fuel pellet" is to go get the dust and combine that in a crafing bench to get the "fresh" thorium fuel pellet. You most likely forgot to put in a new texture for the item in the item atlas therefore the "border" is added in as the item's texture instead. That or the wrong texture and item was referenced to be used instead, causing the strange scenario where not only the item is COMPLETELY USELESS and that it has no true texture

**Comment by ReikaKalseki** [comment]
Thorium is not yet implemented. Being useless is not a bug. Also, as for the texture, thorium fuel pellets are one of the first things that had textures added.

**Comment by Zedrimar** [comment]
@ReikaKalseki ok, but why did the texture thing glitch out? only pink border is shown :/ (sorry for being so harsh earlier)

Sorry about earlier since I got confused due to having that spawn and no real use for it, but the texture thing is strange and that IS most likely a bug since there is only one type of thorium pellet and that is the "fresh" pellet. thats probably the pellet that was meant to be used (unless I am false again) since this thing has nothing as far as textures goes.

**Comment by Xavion3** [comment]
I can corroborate this, I don't use a texture pack and in NEI the fuel pellets have that same texture. Maybe you made a typo or something went wrong saving some time but it has that wrong texture. AOBD adds the recipes I believe.

The actual item is ReactorCraft:reactorcraft_item_ingots and it has a metadata of 8 if that's enough to help you track down the issue but it's definitely a bug with the texture or the item or possibly a cross mod thing with another mod not being supposed to give it as a result of smelting Thorite.

**Comment by Zedrimar** [comment]
@Xavion3 it seems to be the mod it self as I tested with the bare minimum with the dragon API rotorycraft and reactorcraft but added NEI just for good measure that I was doing something right (optifine and fastcraft had no affect on the results of the expiriment)

**Comment by jeremiahwinsley** [comment]
I can reproduce this using a minimal set of mods.

Forge 1291
RotaryCraft v7f
ReactorCraft v7f
DragonAPI v7f
NEI

Processing Thorite through the grinder or extractor, and smelting the flakes, gives the result `RotaryCraft:rotarycraft_item_modingots:84`. This ingot has textures.

Processing Thorite through a vanilla furnace gives a different result, `ReactorCraft:reactorcraft_item_ingots:8`.  This ingot does not have textures.

The texture for this item, [`items1.png`](https://github.com/ReikaKalseki/ReactorCraft/blob/bad869a423c6b6c2cea76b2ff142c555273a9b5e/Textures/Items/items1.png) at position 40, has the empty texture shown here.

So in this case, the bug is either a missing ingot texture and wrong name ( since this is an ingot, not a fuel pellet ), or producing the wrong ingot ( if the RotaryCraft ingot is the intended result ).

**Comment by ReikaKalseki** [comment]
lanaver said the fuel pellet was missing textures, not the ingot. Yes, the ingot does not yet have any code or texture.

**Comment by Zedrimar** [comment]
well that is out of the way, the next big release will probably be the one to implement the ingot luckily.
