### ISSUE TITLE
[RoC/IC2E/GT5U] Electric Motor/Generator issues with IC2E EU/GT5U

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1591]
RotaryCraft V18b, IC2E 2.2.827, GT5U 5.09.30.

Electric Generator does not function or has non-obvious requirements. I've tried with Gasoline Engine, Gas Turbine and Creative Coil as input, and MFSU/BatBox/Tin Cable into BatBox/Glass Fiber into BatBox, the batteries do not charge and EU Reader on the Generator shows all zeroes. IC2E's cables still connect visually. 

Electric Motor only functions when connected to IC2E's sources, and is not recognized by GT5U as valid IC2-EU-conversion target (GT5U will charge IC2E BatBoxes, but it won't charge the Motor). Magnetostatic Engine _is_ recognized by GT5U as valid RF container, so I think the issue is with the Electric Motor.

**Comment by ReikaKalseki** [comment]
#1590
