### ISSUE TITLE
I've been stuck on a crash and I have no clue how to fix it

### ISSUE THREAD

**Issue by brandyyn** [ReikaKalseki/Reika_Mods_Issues#1592]
Ive tried normal forge with Reikas mods + BOP and NEI and no crash but the only thing my crash report mentions is BOP which still happens when I remove BOP

https://pastebin.com/yLFSmsL2

Heres a newer report, I dont know if anything would of changed: https://pastebin.com/2UqNLywV

**Comment by ReikaKalseki** [comment]
Something tried to place null into the world.

**Comment by brandyyn** [comment]
What do I do? As I literally have 0 clue how to fix this, normally im pretty good with crash reports but this ones giving me autism.

**Comment by OvermindDL1** [comment]
At this point it is time to start removing mods to find which is the cause.  ^.^

**Comment by brandyyn** [comment]
Ahah, 300 mods and 8 minutes to start the game up each time, fucking great hahahah

**Comment by Duckfan77** [comment]
Binary split search. Basically remove half the mods, see if the error goes away, if it does, try the other set. Repeat with whichever set crashes until you find the minimum set of mods to cause the issue.

**Comment by brandyyn** [comment]
Yeah but issues arise when mods rely on eachother..

**Comment by Duckfan77** [comment]
Hence "minimum set of mods." Or if you were referring to dependencies, obviously make sure you keep dependencies together with their dependents.

**Comment by brandyyn** [comment]
yeah, its hard tho cuz i dont remember what dependents go with what mods, fml haha

**Comment by Barhandar** [comment]
Take a working pack, compare modlist, remove differing mods from yours until it stops crashing.
