### ISSUE TITLE
Crafting Pattern issue in Blast Furnance

### ISSUE THREAD

**Issue by ZorbaHerbalist** [ReikaKalseki/Reika_Mods_Issues#1594]
I'm trying automate Blast Furnance with maxing chance to HSLA Steel bonus. So, when use Crafting Pattern to put Iron in Blast Furnance it works perfectly. But, when Crafting Pattern is in Blast Furnance there is no way to insert coal, gunpowder and sand. I tried Hoppers on each side and also tried Item Router from Router Reborn to put in specific slot's. With Crafting Pattern in Blast Furnane Item Router this not work, when remove it from Furnance Router output items to specified slots.

**Comment by ReikaKalseki** [comment]
This is a known behavior for a long time without a realistic fix. Remove the pattern and supply surplus iron after spreading some into all nine slots.

**Comment by ZorbaHerbalist** [comment]
Is there any possibility to remove pattern without user interaction? Automatic, I mean

**Comment by ReikaKalseki** [comment]
No.

**Comment by ReikaKalseki** [comment]
The patterns no longer override the left three slots; that is the best I can do.
