### ISSUE TITLE
[CC] [GT5U] Glow Cracks/Mineral Enricher can generate GT ore blocks... but GT determines ore block type by TileEntity data, not its BlockID/metadata combo, so it generates "blank" ores

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1597]
Specifically it generated `gregtech:gt.blockores:13` for me, ItemStack for which is obviously-should-not-exist Oxygen Ore. Said itemstack, when placed in world, results in `gregtech:gt.blockores:2` instead, with TileEntity having a short variable `m` set to `13` and byte variable `n` set to `0`.

Said `m` variable is the same as relevant itemstack's damage value (so GT iron ore is blahblah:32 in inventory, and placed in world it would have `short m = 32`) and is the MaterialID of the relevant material from `config/GregTech/MaterialProperties.cfg`.  
The `n` variable determines whether the block is natural or player-placed, and is presumably `1` for worldgen ores.

**Comment by ReikaKalseki** [comment]
Do all ores share the same block ID?

**Comment by Barhandar** [comment]
I don't know, going to check once my instance loads. The ID associated with gt.blockores only had stone ores visible, but visibility in NEI doesn't matter much due to GT autohiding extraneous itemstacks that nonetheless still generate.

**EDIT**: If GalactiCraft/GalacticGreg is present, the ores for it use `gregtech:gt.blockores.gc`. All other ores do share single BlockID, `gregtech:gt.blockores`.  

The material of that block depends on shift in MaterialID. ID straight is stone, +1000 is netherrack, +2000 is end stone, +3000 is black granite, +4000 is red granite, +5000 is marble, +6000 is basalt. So for example basalt lithium ore is damage value/`m` 6006.  
There are also small ores, starting at shift of +16000 for stone, and advancing by a thousand for the same sequence of base materials (small basalt is thus +22000).  
GC-GT ores follow the same pattern and small also start at +16000, but there is just 4 possible materials for them: moon dirt, moon rock, ??? (does not seem to correspond to any GC/GCPlanets stone) and mars stone.

Oh, and Mineral Enricher can also generate GT ores too, both regular and GC, with the same issue present, and seemingly generates GT-GC ones more often than plain GT.

**Comment by ReikaKalseki** [comment]
There needs to be a clean DragonAPI function for this.

**Comment by OvermindDL1** [comment]
> Do all ores share the same block ID?

In GT5/GT6 itself yes, but any associated mods can use other ID's.  GT5/GT6 has a meta-class that uses NBT to store extra data, such as the ore types, density of the ores, etc... and more.  Including it's simple things like stones, metal blocks, etc...  But yes, just ores tend to be on a single block ID in GT5/GT6 itself (and yes, things like galactigreg and some others add in more ores on a new ID).  As always though, the ore dictionary should work fine for them for 'detecting', but when creating them then you really need to create the same items that GT6 does (like via the creative menu, which is a great way to get the ore list with valid ore metadata/nbt on the itemstacks).  Just spawning in raw ID/Damage ItemStack's will fail in *many* cases, not just in GT5/GT6 but in some other mods as well.

**Comment by ReikaKalseki** [comment]
> (like via the creative menu, which is a great way to get the ore list with valid ore metadata/nbt on the itemstacks)

You mean the client only method?

**Comment by Barhandar** [comment]
In GT5U, itemstacks have appropriate OD entries (if GT ore itemstack does not have OD entry, it means the ore you're trying to spawn is not enabled for the material), you just have to resolve itemstack's damage into TileEntity data. They don't have any NBT.  
GT6, I dunno, might've started using NBT instead of the damage's robustness.

**Comment by OvermindDL1** [comment]
I know GT6 better than GT5 internally.  GT6 uses a lot of NBT on items, but yes it does use damage for basic mappings into a global registry, but it also uses NBT for extra metadata (which may not be on ores now that I think of it).

And GT6 leaves its creative inventory accessors on the server for direct access, though if you have that access anyway it is better to use it's single-call methods to build an itemstack of whatever style you want then.  ^.^

But yes, oredict'd ones should work fine (just be sure to copy it).

**Comment by Barhandar** [comment]
GT5 _kinda_ uses tons of NBT for crafted items/disassembly (but not items from NEI... or covers popped off of pipes). Neither is relevant here.

**Comment by ReikaKalseki** [comment]
Fixed.
