### ISSUE TITLE
`You cannot key a null itemstack!` caused by mod/item removal

### ISSUE THREAD

**Issue by cleverca22** [ReikaKalseki/Reika_Mods_Issues#1598]
https://gist.github.com/cleverca22/540b0d952916453aaab1ff7599f1042f

i believe the problem, is that an item from a deleted mod is in the whitelist of my inventory warp (the ItemInventoryLinker), and every time i pick up an item, the server kicks me due to the exception

i was able to reproduce it by having a player throw a normal melon seed at me, instant crash upon trying to pick it up

it also crashes when attempting to open the GUI to clear the filter

**Comment by ReikaKalseki** [comment]
That would do it. Temporarily re-add the mod; I am not going to change a core DragonAPI class for this.

**Comment by cleverca22** [comment]
i just deleted the item and cheated a replacement back in

but the real killer problem, is that after crashing out, you re-login ontop of the item, and crash again

**Comment by ReikaKalseki** [comment]
?

**Comment by cleverca22** [comment]
the server kicked me out when i attempted to pick up an item, because of a null itemstack in the filter

upon relogging, i was at the same position, ontop of the same item, and was kicked out with the same error

there is now no way to sign in and fix the problem, until another player picks the item up, or an op does `/tp` the instant you login
