### ISSUE TITLE
Casting Temple can't see items in outer ring of stands

### ISSUE THREAD

**Issue by TiranDirth** [ReikaKalseki/Reika_Mods_Issues#1599]
I have used this Casting Temple a fair amount, including using the outer ring of stands.

More recently I had to remove some stands to replace them with runes to craft some crystal clusters.

Having removed the runes and replaces the item casting stands in the area, the casting temple appears to detect a valid structure but does not show the items in the UI when right clicked and does not craft the item when used with the elemental manipulator.

I've attached a screenshot showing the UI view in the table with the background showing items visible on the stands in both the inner and outer ring. The pulverised coal on the inner ring is visible in the UI while the gold bar is not.

Running CC v18b
DragonAPI v18b
Forge 10.13.4.1614

Happy to provide any other help I can!

![2017-09-28_02 35 03](https://user-images.githubusercontent.com/10141991/30945550-d670ea04-a3f6-11e7-9f82-f1b9ecb24481.png)

I'm also seemingly at an impasse where I can't progress any more as I seem to be able to craft Lumen Repeaters but nothing to draw the lumens to, however I'm pretty sure I just need to make, craft or find more stuff and was hoping the lamp might either use Lumens or I could use it around the base anyway.

**Comment by EyeDeck** [comment]
Stands don't contribute to the structure check. Review their placement in the lexicon.

**Comment by ReikaKalseki** [comment]
You build the structure wrong.

**Comment by Barhandar** [comment]
Wait, it doesn't even check for the ring of blocks on the same level as the stand, as well as allows quartz(?) in the color ring?

**Comment by Savallator** [comment]
You have a misunderstanding here i had as well, so just to make it clear: You never have to "downgrade" your casting temple or build another one for the simpler craftings. It all fits in one, and you can replace crystalline Stone with Runes when needed.

**Comment by TiranDirth** [comment]
Is that right Savallator?

The recipe for crystal clusters shows runes on level 0 in the exact positions where the stands go. If I can just ignore these runes that's cool, but the book appears to draw a distinction between level 0 (where the table is) and level -1 (one level below), with casting stands going on level 0.

As for building it wrong, I'll take a look in a little bit and see. If I remove a crystalline stone then the table loses sight of all of the stands both inner and outer row. I definitely have created items using those outer stands before but maybe I did something else silly.

**Comment by TiranDirth** [comment]
Assuming I have made an error, any suggestions as to where would be tremendously helpful.

![2017-09-28_13 34 24](https://user-images.githubusercontent.com/10141991/30966744-e3a9d5cc-a451-11e7-890f-119ecefba341.png)

![2017-09-28_13 33 10](https://user-images.githubusercontent.com/10141991/30966755-ea068672-a451-11e7-9bf3-ab098a7172e4.png)

**Comment by Savallator** [comment]
The outer stands are in the wrong position. Look it up in the book. There is no collision between Runes and Casting stands.

**Comment by TiranDirth** [comment]
Aah, I'm a dumbass!

**Comment by Savallator** [comment]
But actually, it would be a nice feature to have a tooltip for the dots in the Casting Table. 
It is very confusing for new players if the Structure is wrong or you just need to level it more.

**Comment by TiranDirth** [comment]
Now back to my other problem of not being able to build anything to draw energy from a pylon...

I think I have something that uses energy (the Elemental Lamp, right) and I have repeaters to draw it, but I think I need an intermediary (the relay)? But I can't make the relay block as it needs something (an advanced crystal cluster or something) I haven't discovered yet.

I guess maybe I need to dig around until I find one of the underground rooms. We found one but someone else went in first and so while I know what it looks like I can't trigger the achievement.

**Comment by Savallator** [comment]
I think what you are looking for is not the elemental lamp. You should have something else to use the wooden repeaters with, something to ... enhance yourself.

**Comment by TiranDirth** [comment]
Aah, I wondered about that, I already built the table for it but wasn't sure how it worked, probably best to take it closer to the colours I need!

Thanks for the help!

**Comment by Savallator** [comment]
remember the table alone is not sufficent
Edit: But this bugtracker is probably not the right place for this discussions.

**Comment by TiranDirth** [comment]
I have no pattern in the book for any structure to go around it yet and two chests worth of blank fragments.

That said, yeah, we should chat elsewhere, thank you for the help!
