### ISSUE TITLE
Endstone meteors not providing some end ores.

### ISSUE THREAD

**Issue by Xavion3** [ReikaKalseki/Reika_Mods_Issues#160]
So at least in my pack I've noted they only contain endstone and pitchblende from reactorcraft, the other three end ores that don't seem to spawn are endium from gany's end, ender amethyst from biomes o' plenty and draconium ore from draconic evolution.

**Comment by ReikaKalseki** [comment]
None of those three are in my [registries](https://github.com/ReikaKalseki/DragonAPI/blob/master/ModRegistry/ModOreList.java#L40).

Well, amethyst is, but it is marked as an overworld ore.

I can add all three (which will also add Extractor/Grinder/MineralExtractor/etc support) but that means I need the following data about each ore:
- Any and all OreDict names in common usage
- The normal product type (gem, ingot, etc) and its OreDict name
- How many units of resource are typically given per ore without fortune (take an average if it varies) 
- Which [OreRarity](https://github.com/ReikaKalseki/DragonAPI/blob/master/Interfaces/OreType.java#L32) is closest
- One (or two, if a gradient) colors that typically represent the ore
- Display Name
- Any metadata/NBT variances (such as metadata 1 being the nether version), especially if different block IDs are used

**Comment by kolatra** [comment]
Here's some info on the Draconium Ore:
OreDict: oreDraconium
Product: One Draconium Dust, OreDict name is draconiumDust
Rarity: Rare in the Overworld and Nether, and quite common in the end, meteors can be found that contain up to 100 of the ore if I recall correctly.
Color: Purple
Name: Draconium Ore
No metadata differences for the ores that I'm seeing, it seems to change texture depending on which dimension you're in.

**Comment by Xavion3** [comment]
For endium
- oreEndium
- ingot, ingotEndium
- Just drops the ore with one ingot per ore
- scattered
- Based off the ore or the ingot? Because the ore uses a very dark purple while the ingot uses a relatively bright one.
- Raw Endium
- No metadata or NBT as far as I can tell

For ender amethyst it's different from normal amethysts, possibly an issue for you though as it has no oredict name.
- No oredict name (id is BiomesOPlenty:gemOre)
- Gem, no oredict entry (id is BiomesOPlenty:gems)
- 1 Gem
- Scarce
- A bright pink color, d5d is about right.
- Ender Amethyst Ore for the ore and Ender Amethyst for the gem.
- They both have a metadata of zero.

**Comment by ReikaKalseki** [comment]
For the colors, please give me color codes. Either hex or RGB are fine.

@Kolatra 

Please give me the exact OreRarity value. As for all these ores: Are they TileEntities?

As for Amethyst, it needs to be in the OreDict or it will not work. That said, I can force it from my end but would rather avoid it if I can, as writing ModHandlers is a pain.

**Comment by kolatra** [comment]
Overworld and Nether: Rare
The End: Average
Color code: 9F01E2

**Comment by ReikaKalseki** [comment]
I have found [a problem in the Draconic Evolution code. It uses the world for the renderer](https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/common/blocks/DraconiumOre.java#L53), meaning that the dimension of the meteor, not its stone type, will determine the texture.

**Comment by Xavion3** [comment]
Draconium isn't Average in the end by the way, massively more common than it is in the nether and the overworld but it would still only be the higher end of Scarce for rarity, could be considered Scattered I suppose, definitely not Average though. For endium a color of 372356 should be right.

On the note of missing ores a quick look through NEI only gives Tanzanite, Topaz, Malachite, and Mithril as other missing ores. The values for them for you.

Any and all OreDict names in common usage
The normal product type (gem, ingot, etc) and its OreDict name
How many units of resource are typically given per ore without fortune (take an average if it varies)
Which OreRarity is closest
One (or two, if a gradient) colors that typically represent the ore
Display Name
Any metadata/NBT variances (such as metadata 1 being the nether version), especially if different block IDs are used

Tanzanite
- oreTanzanite
- gem, gemTanzanite
- 1
- Rare
- 7323d4
- Tanzanite Ore
- Biomes O' Plenty has it with a metadata of 8, know of no other mods which add it.

## 
- oreTopaz
- gem, gemTopaz
- 1
- Rare
- da4904
- Topaz Ore
- Biomes O' Plenty has it with a metadata of 6, know of no other mods which add it.

## 
- oreMalachite
- gem, gemMalachite
- 1
- Rare
- 29b17f
- Malachite Ore
- Biomes O' Plenty has it with a metadata of 10, know of no other mods which add it.

## 
- oreMithril
- ingot, ingotMithril
- 1
- I'm not sure of any mod that causes it to spawn naturally, it's a magically modified form of silver in TE though.
- 7ac6f6
- Mana Infused Ore
- TE's block for it has a metadata of 6

**Comment by ReikaKalseki** [comment]
Those BoP ores were specifically excluded for being mostly useless.

**Comment by ReikaKalseki** [comment]
Draconium and Endium have been implemented. Amethyst will not be because of its low utility and handling difficulty.
