### ISSUE TITLE
Crash when using Chisel + Reikas mods

### ISSUE THREAD

**Issue by brandyyn** [ReikaKalseki/Reika_Mods_Issues#1600]
crash: https://pastebin.com/ThKnhfpC
modslist: http://prntscr.com/gqt7jj

this was after i updated from v16 to v18

**Comment by ReikaKalseki** [comment]
Something tried to worldgen a null block.

**Comment by brandyyn** [comment]
Yeah, Its chisel and the mod creator wont update it because they dont care about 1.7.10 anymore AND It only started happening after I updated to v18 for your mods, I really like Chisel, Is there anything you can do?

**Comment by ReikaKalseki** [comment]
No, and placing null will corrupt the map anyways.

**Comment by brandyyn** [comment]
But chisel is fine on its own, only when adding your mods it crashes

**Comment by brandyyn** [comment]
https://github.com/Chisel-Team/Chisel/issues/561#issuecomment-332925411
