### ISSUE TITLE
[v18b | 1.7.10 | DragonAPI ] Minecraft unable to launch

### ISSUE THREAD

**Issue by nigrum-dente** [ReikaKalseki/Reika_Mods_Issues#1601]
So I decided add rotary craft to my game, but each time I try launch the game the launcher disapear and come back 5 second later.

I have found that dragonapi seem to be the cause as it can happen without rotarycraft.

Here is a gist with the latest.log: https://gist.github.com/nigrum-dente/b4cf9b9e426a818964c085b71413c08e

**Comment by ReikaKalseki** [comment]
Remove Thaumic Infusion.

#895 #1003 #1186 #1480 #995 #1094 #1079
