### ISSUE TITLE
[CC V18b] NPE: Rendering Block Entity client crash

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1603]
https://gist.github.com/Barhandar/631edd4bb0734fe2cc5d3d6c979545e1

Might be caused/uncovered by Forge Relocation, but I am not using any content from that/Funky Locomotion.

**Comment by ReikaKalseki** [comment]
Your world is in an invalid state, such as a null entry added to the loaded TileEntity list or a chunk with a null for the list itself.

**Comment by Barhandar** [comment]
The possible cause for the invalid state is #1604 - this crash happened some time after it and neither happened since (re-loading the world and playing afterwards worked fine). It doesn't happen after the #1100 crashes.
