### ISSUE TITLE
[CC V18b] breakPaths/Repeater.onFirstTick CME

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1604]
https://gist.github.com/Barhandar/ccc5e802012850943c0a5314ef85e095

It might be related to #1100, but is a different log. This happened while I had 4 turbocharged multichromic repeaters in a network consisting of mostly single-color non-turbo repeaters plus a few more non-turbo multichromic ones.

**Comment by ReikaKalseki** [comment]
It is #1100, or a variant of it.
