### ISSUE TITLE
Is there a way to disable the chest structures and the buildings with the nether portals in on top of the nether from chromaticcraft?

### ISSUE THREAD

**Issue by brandyyn** [ReikaKalseki/Reika_Mods_Issues#1606]
Especially the nether portals as there is supposed to be no nether portals in my pack

**Comment by Aivech** [comment]
Given that those structures are progression-gating, I'm pretty sure there isn't, and there won't be.

**Comment by brandyyn** [comment]
the chests and nether portal buildings are progression gating ? what?

**Comment by lAimBotl** [comment]
you ever play chromaticraft boi?

**Comment by brandyyn** [comment]
No, Ive never, And I want to as soon as Im done with my pack and the nether portal structure is quite an issue since there are no nether portals in the pack so I need it gone

**Comment by lAimBotl** [comment]
is your pack public? did ya get rekias perms?

though I agree it shouldn't be pre-lit.

**Comment by brandyyn** [comment]
Its not public no, Just small private one

**Comment by brandyyn** [comment]
Could you tell me how they are progression gating & if theres anyway to disable the netherportal atleast

**Comment by ReikaKalseki** [comment]
No, and there never will be.

**Comment by DaMachinator** [comment]
Have you actually progressed through chromaticraft?
