### ISSUE TITLE
[Suggestion]: Protection Block/pylon thing [Chromaticraft]

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1607]
Kinda like how Chromaticraft puzzle pylons stop you from mining some blocks till you break it, but with redstone and a adjustable radius.
 Was thinking you would use a item to get 2 corners to get the protection radius, or
 you could make it like paint, so you have to mark every block.

**Comment by ReikaKalseki** [comment]
The oldest block in ChromatiCraft?
