### ISSUE TITLE
minecraft crash

### ISSUE THREAD

**Issue by marco6971** [ReikaKalseki/Reika_Mods_Issues#1608]
https://pastebin.com/eiAWBNCX
it happens when i try to see the recipe for certains items

**Comment by ReikaKalseki** [comment]
Try removing mods.

**Comment by ReikaKalseki** [comment]
Hello?

**Comment by marco6971** [comment]
sorry i don't have so much time during the week. can you wait until weekend?
thanks

**Comment by marco6971** [comment]
it happens when AdvancedSystemsManager-1.7.10-0.2.0 is installed, with items like ether berries

**Comment by ReikaKalseki** [comment]
Does that mod change recipes?

**Comment by marco6971** [comment]
i don't know, how can i see that?

**Comment by ReikaKalseki** [comment]
Perhaps it registers null to the item registry or Ore Dictionary. One way or another, however, it is changing something such that the item registry or my grinder recipes - possibly ones created via the OreDict - contains invalid entries.

This is on its end, and I cannot really say more without input from the mod author (feel free to ping them here).
