### ISSUE TITLE
Reactorcraft crash while setting up Uranium Processing

### ISSUE THREAD

**Issue by ProxyPlayerHD** [ReikaKalseki/Reika_Mods_Issues#1609]
https://pastebin.com/PQNCX3f8

Forge Version: 10.13.4.1614
RC/RC/EC Verison: V18b
all i did was place 3 Centrifuges and tried to hook them up, the world is lost now.

**Comment by ReikaKalseki** [comment]
Their fluid tanks are full by more than their capacity...how the hell did you manage that?

It can be fixed with MCEdit by deleting the processors, or editing their NBT to change the tank fill levels.
