### ISSUE TITLE
Crash on closing rotarycraft GUI's

### ISSUE THREAD

**Issue by aurumvorax** [ReikaKalseki/Reika_Mods_Issues#161]
So this is a bit of an odd one, I first noticed it on v6f, but I thought it might go away when you released v7.  Running on v7f now, and it still persists.  Sometimes(and only sometimes) I get a ticking memory connection crash when I close the gui of a rotarycraft machine.  I've noticed it on industrial coils being charged, and blast furnaces being powered by friction heater, so it may have something to do with other blocks transferring power/heat.  From the crashlog, it looks like a vanilla crash, but circumstances would suggest something in rotarycraft making vanilla unhappy.

crashlog:  http://pastebin.com/uzaki2md

**Comment by kolatra** [comment]
This does not point anywhere near RotaryCraft code. Try removing other mods that could be causing a conflict, or you could also try using Forge 1291 to see if that changes anything. Please report back when you have any updates. Thanks!

**Comment by ReikaKalseki** [comment]
So...any update?

**Comment by aurumvorax** [comment]
I did some testing with simple worlds(just RoC/ReC/NEI, etc)  and wasn't able to recreate the crash, just in that one world.  That world has since been corrupted, and I've started a new one with the same modpack.  If it reappears, I'll let you know.  Sorry I can't be more helpful than that, I think intermittant errors are the bane of any engineer :)

**Comment by syf097** [comment]
i don't think so.when i was creating a new world,it crashed again

**Comment by ReikaKalseki** [comment]
Why are you commenting about #250 here?
