### ISSUE TITLE
Gatling Gun Crash on Server

### ISSUE THREAD

**Issue by MajorGeneralRelativity** [ReikaKalseki/Reika_Mods_Issues#1610]
When I attempt to operate a RotaryCraft Gatling Gun, I get a crash on my server. This crash re-occurs every time I spawn in, making the server impossible to operate. It appears to happen whenever I get hit by the ammunition, but I cannot confirm that. Please let me know if I need to include more data.

Crash log here: https://gist.github.com/MajorGeneralRelativity/335f0d00ce2bf82a216cdb38e616d1b4
Forge v1614 for MC 1.7.10
Modlist here: https://gist.github.com/MajorGeneralRelativity/f8a16bc338ef5ab1529d7e642bdd5431

**Comment by Aivech** [comment]
The only relevant place I could find that refers to an EntityFX is https://github.com/ReikaKalseki/RotaryCraft/blob/master/Entities/EntityGatlingShot.java#L73 if that helps.

**Comment by MajorGeneralRelativity** [comment]
I'm guessing from the tags added that this is an issue with RotaryCraft and will be fixed in a future release? This bug delays implementation of my naval ship with ~100 Gatling Guns + other heavy armament :)

**Comment by ReikaKalseki** [comment]
Fixed.
