### ISSUE TITLE
[CC] [TC4] Pylon-Nodes allow drawing their compound aspects directly by wands with barely any progression necessary, circumventing Thaumcraft's mechanics

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1612]
There is a lot of aspects in each pylon, far more than in Thaumcraft's nodes, and they can be drawn as soon as you have a wand, done a miniscule amount of TC research and come close enough to the glowball.  
Normally you need Compound Recharge Focus to be able to utilize compound aspects, and even then it requires Wand Recharge Pedestal, and there is no way in Thaumcraft itself, or the generally most used mods for it, to manually draw compounds from nodes (being able to convert other kinds of energy into vis is a different issue, though could be a Chroma ability).

**Comment by ReikaKalseki** [comment]
There is a config to gate this behind CC and TC progression.

**Comment by Barhandar** [comment]
And the config option is called how? If you mean `    B:"Make ThaumCraft integration require ThaumCraft progression"`, Master Node Tapping isn't "gating", it's the fourth research a reasonable player _does_ at the very start of the mod before they even do anything else, and I don't see anything that gates it behind CC progression. If the same option does, the "progression" necessary is similarly close to nonexistent, as I can draw from pylons despite the reach of my Chroma progression being "can craft the crystal manipulator and has visited all colors".

Requiring Chroma-TC4 researches would be gating. Requiring Compound Recharge Focus's research (or the _actual_ compound recharge focus + wand recharge pedestal in range of a pylon ball/relay network) would be gating. Master Node Tapping for _instant full wand recharging_ at almost any nearby pylon? Not gating.

**Comment by ReikaKalseki** [comment]
Better?

![https://i.imgur.com/WelV1fy.png](https://i.imgur.com/WelV1fy.png)
