### ISSUE TITLE
StackOverflow when using Subterranean Route Finder

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1613]
hi,
I have been trying to figgure out how to use the Subterranean Route Finder. Sofar I found out that while being on the surface a shift rightclick with the Subterranean Route Finder causes excessive recursion in 
Reika.DragonAPI.Instantiable.Data.BlockStruct.BlockArray.recursiveAddCallbackWithBounds(BlockArray.java:648) and then runs into a StackOverflowError.
I assume this is not the intended behaviour?
On a first glance the function appears to perform a depth first search of sorts. Maybe it could be rewritten to use a queue instead of recursion?

DragonAPI 1.7.10 V18b
ChromatiCraft 1.7.10 V18b

**Comment by ReikaKalseki** [comment]
...What? It uses a tick-based iterative, not recursive, algorithm.

**Comment by ReikaKalseki** [comment]
EDIT: Never mind.

**Comment by ReikaKalseki** [comment]
Fixed.
