### ISSUE TITLE
Fusion reactor solenoid stops spinning after running for long periods

### ISSUE THREAD

**Issue by raelik** [ReikaKalseki/Reika_Mods_Issues#1614]
This appears to just be a rendering glitch, as the solenoid continues to function, but as the title suggests, after the solenoid runs for a long period of time (some number of real-world days), it stops spinning.  Server restarts have no effect on this. The only way to make it spin again is to break the multiblock and re-establish it.

**Comment by ReikaKalseki** [comment]
Possible rotation overflow, maybe. I would need to check the code to be sure.

**Comment by MajorGeneralRelativity** [comment]
I have experienced the same bug, but I didn't post an issue because I wasn't sure if it was from a few details with my setup.

**Comment by ReikaKalseki** [comment]
The rotation amount is indeed being written to NBT, which would eventually cause overflow. This is a trivial fix.
