### ISSUE TITLE
[CC] [Mystcraft] Crash when opening a certain mystcraft collation folder 

### ISSUE THREAD

**Issue by AO77777** [ReikaKalseki/Reika_Mods_Issues#1616]
![2017-10-10_09 14 31](https://user-images.githubusercontent.com/20087128/31376096-af2ffd5a-ad9b-11e7-8309-defe21f24d95.png)

I used to be able to open it but it just starting crashing for some reason. Also crashes when viewing it while its in a writing desk.

[crash-2017-10-10_09.15.09-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1371076/crash-2017-10-10_09.15.09-client.txt)

**Comment by ReikaKalseki** [comment]
`java.lang.RuntimeException: Resource not found at Reika/ChromatiCraft/Textures/mystpages_n.png`

The shaders mod is assuming things it should not.
