### ISSUE TITLE
[CC] Energy focal point (pylon turbo) breaks pylon structure check

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1618]
"Nearby" being 5 blocks orthogonally and 4 diagonally, effectively everything inside focal ring. Vertical reach seems to vary, but is at least up to the level of pylon core and one block below the floor.

I think this is the actual issue behind #1615.

**Comment by ReikaKalseki** [comment]
Can you post a screenshot of an example?

**Comment by Barhandar** [comment]
The outermost glitch-reach seems to vary by pylon: the spawned-in one in the gif doesn't break if blocks are placed and broken against the broadcaster's taller columns on y-8 and y-7, while the world-genned one I've also tested it at does.
https://gfycat.com/gifs/detail/DishonestDetailedErne

**Comment by ReikaKalseki** [comment]
Fixed.
