### ISSUE TITLE
Command Coliding with ChunkPregenerator

### ISSUE THREAD

**Issue by Speiger** [ReikaKalseki/Reika_Mods_Issues#1619]
I read in a comment where a server owner wanted to use my chunk pregenerator with your mod installed. But DragonAPI has also a /pregen command (with the same use i know) and blocks my /pregen command.

So my question is: What do we do?
I would like to keep my command but i don't want to prevent people from using it.

Thanks for reading Speiger

**Comment by Aivech** [comment]
One option would be for one or the other of you to change your command to /\<modname> pregen, so /dragonapi pregen, etc.

**Comment by Speiger** [comment]
I thought of that too. But my mod is called ChunkPregenerator so /pregen would be the mod name in the first place.

**Comment by ReikaKalseki** [comment]
This is fixed in v19. (@EyeDeck)
