### ISSUE TITLE
Ball Lightning circumventing cap somehow

### ISSUE THREAD

**Issue by Savallator** [ReikaKalseki/Reika_Mods_Issues#1620]
Hi, I noticed via Opis that i got vast amounts of ball lightning entities somewhere on the server:

![opis](https://user-images.githubusercontent.com/10967188/31587735-3ce013ca-b1e7-11e7-93f6-1c233864c6d6.PNG)

I have my base near (but not in) a Rainbow forest. Maybe it is the same problem forestry had a while ago with the butterflies - IIRC They got stuck on the edge of the loaded area trying to move into an unloded chunk, and were no longer counted against the cap, but still there?
However, i get the impression it is not intendet like this.

**Comment by Savallator** [comment]
Also, they build up very fast. I killed 40k Ball lighning entities 2 hours ago, and now 28k again.

**Comment by Rewyn** [comment]
1,2k pigs? That doesn't exactly sound intended either...

**Comment by Savallator** [comment]
But the pigs did not spawn back after killing, while i had to make a cronjob to kill 5k Ball lighnings every hour.

**Comment by Savallator** [comment]
The numbers are going up. There are now ~30k Ball lighnings respawning per hour, but i have no idea where in the world they are. Does excessive Pylon usage spawn them? I have begun using the Fabricator for some things.

**Comment by ReikaKalseki** [comment]
No.

**Comment by Savallator** [comment]
I might add that there is not nearly the performance impact one would expect. If i had 30k chickens, it would lag like hell. Maybe this is due do the pathfinding is less complicated with flying intities, but it almost seems like they are not really there. I could also not find them in the world until now, and opis cannot give me coordinates because they show only in the "by type" tap and are not visible as distinct entities. It seems almost like they are not really in a loaded chunk, but i scouted the borders of the chunkloaded area and did not find anything.
While it is not an big problem for me now - killing them every hour with a cronjob works fine - if you need me to do more tests to pin down the cause, just tell me what you need.

**Comment by ReikaKalseki** [comment]
> I might add that there is not nearly the performance impact one would expect. If i had 30k chickens, it would lag like hell. Maybe this is due do the pathfinding is less complicated with flying intities, but it almost seems like they are not really there

Ball lightnings do not do much update code.

**Comment by Savallator** [comment]
After two days, the numbers have gone down drastically. There are now about 300 Entities spawning after one hour, which i would consider normal. I will test to remove the auto-killing. I did not change anything, the only thing different is that i progressed other mods in the meantime and did not do much Chromaticraft stuff.

**Comment by ReikaKalseki** [comment]
I put some new limit code in.
