### ISSUE TITLE
DragonAPI RC and EC crashing my custom modpack with NEI?

### ISSUE THREAD

**Issue by manikminer123** [ReikaKalseki/Reika_Mods_Issues#1623]
Haii, I created an account just for this anyway:
So I use the technic launcher for my modpacks and I have made my own modpack with around 150 mods. It's a lot I know so It's extremely unstable and buggy however I recently made a semi-stable version of it which ran fine but the only issue I'm having is whenever I press 'R' to view a recipe in NEI my game freezes and crashes. I've looked round the internet and tried different solutions like updating mods, removing recently added mods. I think I've narrowed it down to either Thermal Expansion (CoFH Mods) or Reika mods. I know both these mods are fine but I only think it might be Reika mods is because of the crash report. (I have no crash report experience so sorry if it has nothing to do with Reika). So my game crashes and here is the game's most recent crash report:
[Modpack Crash 1.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1391903/Modpack.Crash.1.txt)

And I updated my Reika mods (RC, EC and D-API) from version V9 to version V18 (All three)
When I update them my game just doesn't load, in case it is crashing here is the most recent crash report from the technic launcher (Not modpack):
[Launcher Crash 1.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1391906/Launcher.Crash.1.txt)

I know It's a lot of logs and text to read so if you TL;DR that's fine, don't expect anyone to go out on a limb to help but if you do, thank you if you try to help regardless of the outcome :) Peace -Manik

**Comment by Aivech** [comment]
Uploaded logs to Gist:
https://gist.github.com/DaMachinator/d771d228f5c4f11665fb291c28af56f2
https://gist.github.com/DaMachinator/92fb4e19da8e0174ddc0bc9f3203ff4e

**Comment by ReikaKalseki** [comment]
Your first issue is ancient (~3 years) and your second is not even a crash. Did you run out of RAM?

**Comment by manikminer123** [comment]
@ReikaKalseki I have no idea how to check if I did run out or not and by ancient you mean the NEI bug? Thx anyway :)

**Comment by ReikaKalseki** [comment]
Yes.
