### ISSUE TITLE
[Chromaticraft] Dedicated Server Incompatibility with EnderIO

### ISSUE THREAD

**Issue by TsumiHokiro** [ReikaKalseki/Reika_Mods_Issues#1625]
When  trying to start a server with EnderIO and Chromaticraft (along with  their dependences) you get a "Exception in server tick loop:  NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP". 
Link:  https://pastebin.com/rSmKAJPh
To note, when starting Chromaticraft alone the server does not get this  error, and without the need of stating, EnderIO alone also does not have this  problem.  @HenryLoenwind has stated that this is a problem in Chromaticraft side, hence I'm reposting it here. SleepyTrousers/EnderIO#4337

Steps to reproduce:
Put both Chromaticraft (along with DragonAPI) and EnderIO on mods folder Start a Forge Server Crash ...   

Affected Versions:
ChromatiCraft 1.7.10 V18b.jar 
DragonAPI 1.7.10 V18b.jar
EnderIO: 1.7.10-2.3.0.422_beta.jar
EnderCore: 1.7.10-0.2.0.39_beta.jar
Minecraft: 1.7.10
Forge: 10.13.4.1614-1.7.10-universal.jar

--

**Comment by Barhandar** [comment]
It's not Chromaticraft's problem, [it's EIO's problem](https://github.com/SleepyTrousers/EnderIO/issues/3298 ). Update EIO, you're on an outdated version that does not have the fix.

**Comment by TsumiHokiro** [comment]
Thank you very much for pointing it out for me since Loenwind told me to look for the solution here.
