### ISSUE TITLE
[CC] Dupe using Transmutation Flame and Nugget forms of Ingots

### ISSUE THREAD

**Issue by ReactivePlatypus** [ReikaKalseki/Reika_Mods_Issues#1626]
Using Chromaticraft’s Transmutation Flame, one can dupe metal ingots with nugget versions by first inserting the desired ingot, crafting a second ingot into 9 nuggets, and throwing the nuggets in. Each nugget seems to have a lumen exchange value equal to that of its equivalent ingot in the latest version, so doing this yields a large net profit of ingots.

This has been tested using only Chromaticraft and DragonAPI installed. Both vanilla iron and gold nuggets can be duped in this way. 

Adding on COFH Core and Thermal Foundation showed that Thermal Foundation’s Copper, Lead, Tin, Silver, Ferrous/Nickel, and Shiny/Platinum can also be duped like this, with a profit of 5 ingots per 9 nuggets in all cases except Shiny/Platinum, which yields 4. It doesn't work with any of TF's alloy ingots.

It also works with diamonds and both EnhancedPortals and Translocators versions of diamond nuggets, however these haven’t been tested in an isolated environment.

**Comment by Savallator** [comment]
on a seperate Note, with Gt5u most metals (and alloys, eg. Titanium, Tungsten, Tungestensteel and most other) can be duped by smelting back cables or plates in the Crystal Furnace, and some other, like Magnesium, by smelting ingots into 18 nuggets.

**Comment by ReikaKalseki** [comment]
This has been fixed, as nuggets now have 1/10th the value of an ingot.
