### ISSUE TITLE
Fabrication blacklist/whitelist [Suggestion] [Chromaticraft]

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1628]
Maybe make it like the "Alternate blast furnace materials" so you can only add (or not add) some things to the blacklist and/or a whitelist.

**Comment by ReikaKalseki** [comment]
The Fabricator system is hardcoded and built on premises that are not amenable to modification. That said, if you want something specific added, go ahead and suggest it.
