### ISSUE TITLE
[RoC] Iodine Cannon "Tried to access Slot -1, which is < 0"

### ISSUE THREAD

**Issue by Savallator** [ReikaKalseki/Reika_Mods_Issues#1629]
I have an Iodine Cannon with sawdust which is working fine, however, it does not consume the sawdust on use, but is putting the mentioned error in the chat.
It only works if i fill at least the first two slots with sawdust (one each is enough), but then if will work forever without consuming it. I have it supplied by two steam engines and am using TE sawduist, if that matters.

**Comment by ReikaKalseki** [comment]
The bug is indeed with the use of modded sawdust. Fixed.
