### ISSUE TITLE
Tile Accelerator not affecting decay rate of wastes in Nuclear Waste Storage Drum

### ISSUE THREAD

**Issue by Fatmice** [ReikaKalseki/Reika_Mods_Issues#163]
I finally have some time to write this up properly.

As explained <a href=http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=1095#c22197>here</a> and <a href=http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=1090#c22098>here</a>, the current implementations, as introduced by v7, is not producing the intended behavior.

The implementation is spread across many files but the code in question is <a href=https://github.com/ReikaKalseki/ReactorCraft/blob/8acf4625f4951fb25ae2d8f1a9715a9a2face062/Base/TileEntityWasteUnit.java#L60-L77>here</a>

``` java
protected final void decayWaste(int mult) {
        for (int i = 0; i < this.getSizeInventory(); i++) {
            if (inv[i] != null && inv[i].getItem() == ReactorItems.WASTE.getItemInstance()) {
                List<Isotopes> iso = WasteManager.getWasteList();
                Isotopes atom = iso.get(inv[i].getItemDamage());
                if (ReikaRandomHelper.doWithChance(mult*0.5*ReikaNuclearHelper.getDecayChanceFromHalflife(Math.log(atom.getMCHalfLife())))) {
                    //ReikaJavaLibrary.pConsole("Radiating from "+atom);
                    if (this.leaksRadiation() && rand.nextBoolean())
                        this.leakRadiation(worldObj, xCoord, yCoord, zCoord);
                }
                //ReikaJavaLibrary.pConsole(ReikaNuclearHelper.getDecayChanceFromHalflife(atom.getMCHalfLife()));
                if (ReikaNuclearHelper.shouldDecay(atom)) {
                    ReikaInventoryHelper.decrStack(i, inv);
                    this.onDecayWaste(i);
                }
            }
        }
    }
```

<a href=https://github.com/ReikaKalseki/ReactorCraft/blob/master/TileEntities/TileEntityWasteStorage.java>Nuclear Waste Storage Drum</a> calls <a href=https://github.com/ReikaKalseki/ReactorCraft/blob/master/TileEntities/TileEntityWasteStorage.java#L44>this</a> to decay its wastes.

``` java
this.decayWaste(this.getAccelerationFactor(world, x, y, z));
```

The above essentially passes as `this.decayWaste(int mult)`
<i>mult</i> is only used in deciding whether to emit neutron.

``` java
if (ReikaRandomHelper.doWithChance(mult*0.5*ReikaNuclearHelper.getDecayChanceFromHalflife(Math.log(atom.getMCHalfLife())))) {
//ReikaJavaLibrary.pConsole("Radiating from "+atom);
    if (this.leaksRadiation() && rand.nextBoolean())
        this.leakRadiation(worldObj, xCoord, yCoord, zCoord);
}
```

Since Nuclear Waste Storage Drum does not emit neutron, the above is mute.

Waste decay is only governed by

``` java
if (ReikaNuclearHelper.shouldDecay(atom)) {
    ReikaInventoryHelper.decrStack(i, inv);
    this.onDecayWaste(i);
}
```

Clearly <i>mult</i> is not used anywhere in that block of code.  As such, Title Accelerator has no affect on Nuclear Waste Storage Drum even though <i>mult</i> is computed based on their presence and passed in to decayWaste().

The solution of course is to implement <a href=https://github.com/ReikaKalseki/DragonAPI/blob/master/Libraries/MathSci/ReikaNuclearHelper.java#L40-L44>shouldDecay()</a> as `shouldDecay(Isotope iso, int mult)`

The new code could then be this

``` java
public static boolean shouldDecay(Isotopes iso, int mult) {
        double chance = mult * getDecayChanceFromHalflife(iso.getMCHalfLife());
        chance *= 6;
        return ReikaRandomHelper.doWithChance(chance);
}
```

**Comment by ReikaKalseki** [comment]
So the whole thing was the result of an oversight....
