### ISSUE TITLE
Spawner Controller won't work when player out of range

### ISSUE THREAD

**Issue by dieselfuelonly** [ReikaKalseki/Reika_Mods_Issues#1631]
Revolution|3 pack updated with current version of Reika's mods, and manually updated RTG (so Luminous Cliffs biomes spawn).

Spawner controllers won't spawn mobs when I'm not nearby.

They are chunkloaded by the RoC Chunk Loader.  Also tested with the Railcraft World Anchor, issue still exists.

Everything works fine when I'm nearby, but when I go to my new base which is about 5km away, the spawners stop working.  I know chunks are being loaded because other machines in the remote base near the mob spawners work fine.

I've tried vanilla mob spawners moved with a Thaumic Tinkerer dislocation focus, vanilla mob spawners broken with a RoC Boring Machine (which become RoC spawners), as well as spawners run through the CrC Spawner Reprogrammer.  All three of the aforementioned spawners work fine with the Spawner Controller when the player is nearby, but not when the player is away.  I am not 100% sure about the player-to-spawner distance at which the spawners stop working.

**Comment by ReikaKalseki** [comment]
Fixed.
