### ISSUE TITLE
[ElC] Please explain what's happening there and what's missing in my understanding

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1634]
https://i.imgur.com/sxh3mJn.png

Presented: gasoline engine feeding into Induction Generator through a 2x gearbox, resulting in 2048V/32A in the superconducting wire. It is then split with two 16A resistors in parallel, wire from one going directly into an Induction Motor 1. The other wire goes into two 8A resistors in parallel, one of which feeds into motor 4, and othe other feeds into two motors, 2 and 3 (based on my understanding and previous experiments, this should split the current equally between these two motors). 
The expected result is that I would have 16A=128Nm on motor 1, 4A=32Nm on motors 2 and 3 each, and 8A=64Nm on motor 4.  
The actual result is 8A=64Nm on all four motors, seemingly completely ignoring resistors. One of 16A has 24A of point current after it, one of 8A has 16A after it.

https://i.imgur.com/UNjAPJB.png

Presented: same gasoline engine into generator setup, feeding into 4 parallel resistors of 16, 2, 2 and 12 amperes limit. Expectation is that they would get the full current each. Practical result is that 16A resistor has 14A pass through, and wire directly after the generator has 30A instead of expected 32A. Same, but with 29A from generator and 13A on the 16A resistor, happens if 2 2A resistors are replaced with 1 4A one.  
Does it not understand amperage limits that are not powers of two and serial resistors, given 16-4-4-8 parallel split results in correct outputs?

**Comment by ReikaKalseki** [comment]
This is probably an artifact of how paths and resistors are implemented; resistors limit the current of a path going through, not the total current passing through a point. So if you have a generator powering two motors through a 6A resistor, the resistor will ensure each motor receive no more than 6A, not 3A each.

**Comment by Barhandar** [comment]
That explains the first one (need to read book harder...). It doesn't explain second one with vanishing amperage.  

Splitting between 4 parallel 4A resistors and 1 16A/plain wire also results in 30A instead of 32A. Or even, given the path information, splitting between 1 4A resistor going into 4 motors, and plain wire into 1 motor.  
Plain wire with 2 motors results in 14A on the wire split and 7A on motors. 3 motors result in 12A on the wire split, with 4A on motors, and generator outputting 28A. And only when there's 4 motors on it, it outputs correct amperage on generator. Feels like a path math error, given that 16 is definitely divisible by 1 and 2 (and splitting 16A into 3 motors probably should result in 5A on each, not 4A). Does it attempt to give all sinks equal fraction of power, regardless of resistors and amount of free power remaining?

**Comment by ReikaKalseki** [comment]
> Feels like a path math error

I think it might be an artifact of integer math. 15/4 = 3, 32/6 = 5, and so on.

**Comment by Barhandar** [comment]
>I think it might be an artifact of integer math. 15/4 = 3, 32/6 = 5, and so on.

I don't understand what you meant by this. Also, I think part of the issue is that it might be doing division where I expect it to be doing subtraction - specifically, subtracting path amperage from total amperage, starting with most complex path, and leaving any cases of motors getting 0A player's responsibility.

**Comment by ReikaKalseki** [comment]
If a generator is generating, say, 17A, and splitting among five paths, each path gets 3A, with 2A "destroyed" by rounding error. Then the resistor logic comes in, but the current redistribution logic does not bring back that 2A.
