### ISSUE TITLE
[RoC] [GT5U] Request: Block Drop Processor additions - Crate and Brittle Charcoal processing

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1635]
GregTech allows using a crate and 16 of various materials, ~~with~~ without metaitem system, to be packaged (in aptly named Packager) into a single Crate of X. BDP currently does not allow opening these. 

Brittle Charcoal can be broken with an axe into 1-2 vanilla Charcoal items. Anything else drops just the Brittle Charcoal block or nothing. It would be extremely nice if it could be processed automatically without requiring a tool-using machine.

**Comment by ReikaKalseki** [comment]
I can add this if you show me some way to identify these items and - in the case of the first - determine the outputs.

**Comment by Barhandar** [comment]
Brittle Charcoal is `gregtech:gt.blockreinforced:4`. [This is the charcoal amount code](https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/blocks/GT_Block_Reinforced.java#L207).

On closer inspection, GT5U Crates are in fact _not_ meta-enabled, albeit still using metamaterial system, and can only package 6 items: neodymium dust (crate `gregtech:gt.metaitem.03:67` contains `gregtech:gt.metaitem.01:2067`), manganese ingot (crate `gregtech:gt.metaitem.03:1031` contains `gregtech:gt.metaitem.01:11031`), bronze ingot (crate `gregtech:gt.metaitem.03:1300` contains `gregtech:gt.metaitem.01:11300`), damascus steel ingot (crate `gregtech:gt.metaitem.03:1335` contains `gregtech:gt.metaitem.01:11335`), steel ingot (crate `gregtech:gt.metaitem.03:1305` contains `gregtech:gt.metaitem.01:11305`), and chrome dust (crate `gregtech:gt.metaitem.03:30` contains `gregtech:gt.metaitem.01:2030`).  
Crated thing's ID is `gregtech:gt.metaitem.03`, shared with circuits (but these start at shift +32000), damage values match the respective meta materialID, with a +1000 modifier for ingots. The containing items' ID is `gregtech:gt.metaitem.01`, damage is also materialID with +2000 modifier for dusts and +11000 for ingots. Additionally, the crates all have OD entries in the form of `crateGt[PascalCased OD entry of the packaged item]`, for example `crateGtDustChrome`. In case of bronze it has two OD entries, the real material `crateGtIngotBronze` and fake crafting material `crateGtIngotAnyBronze`.  
All of these are packaged in groups of 16, returning the crate, which is ID `gregtech:gt.metaitem.01:32403`, along with the items.

**Comment by ReikaKalseki** [comment]
Is there an internal function that can be called (like I do [here](https://github.com/ReikaKalseki/RotaryCraft/blob/master/TileEntities/Processing/TileEntityDropProcessor.java#L594) or [here](https://github.com/ReikaKalseki/RotaryCraft/blob/master/TileEntities/Processing/TileEntityDropProcessor.java#L712)) rather than hardcoding a bunch of mappings?

**Comment by Barhandar** [comment]
I do not have necessary knowledge to answer this. Here are the functions that look relevant (or can lead to relevant ones): it seems it _can_ create one for any ingot, plate, dust or gem metaitem, but only generates these 6 (and recipes for them) because only they are registered for loot.
https://github.com/Blood-Asp/GT5-Unofficial/blob/master/src/main/java/gregtech/loaders/postload/GT_BookAndLootLoader.java#L121
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/loaders/oreprocessing/ProcessingCrate.java

P.S. Any way to disable BDP's NEI integration? Or could you at least please only have things with non-obvious drops (blocks which drop not themselves and scrapboxes/lootbags, not crates which clearly name what they contain) show up in it?

**Comment by ReikaKalseki** [comment]
Done.
