### ISSUE TITLE
[Reactorcraft v18b] steam line entity causing a null pointer exception every time a HP turbine is formed or broken

### ISSUE THREAD

**Issue by jstaff62** [ReikaKalseki/Reika_Mods_Issues#1636]
[2017-10-24-7.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1411932/2017-10-24-7.log)

Here's the full log.
this only seems to happen with certain specific turbines, though i'm not 100% certain of this, if that helps at all.

**Comment by ReikaKalseki** [comment]
You have a block ID and metadata of a pipe pump without actually having the TileEntity there. This should never happen.

**Comment by jstaff62** [comment]
oh, okay world corruption. i imagine an error with the codechicken chunk handler would be related to this, and i don't suppose there's any way i can get around this on my endis there? say, if i knew the position of the entity in question?

**Comment by Barhandar** [comment]
> i imagine an error with the codechicken chunk handler would be related to this

Verily.
>there's any way i can get around this 

Stop using EnderStorage, ChickenChunks, and WR-CBE (ChickenBones' block-adding mods) to prevent this particular issue from reoccuring. Then yeah, turn Forge's config to delete erroring TEs on and erase all ones that crash instead of self-destructing manually. Also keep backups.

**Comment by jstaff62** [comment]
thought so, i got a crash mentioning codechicken (not chicken chunks because i uninstalled that last play-through as that was also causing crashes) i'm starting to dislike his mods more and more as they cause so many problems, i only keep some because of how useful they are, despite how they haunt me. i've decided to leave it as it is though because all the turbines/steam lines work fine when they are formed apparently, and there's no reason to break any of them. thank you both for seeing to my problem :)
