### ISSUE TITLE
[RoC] Spillway removes flowing water blocks in a waterfall (instantly replaced by water spreading on block update), above or on consuming side, without gaining any water

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1637]
The "place next to the water pond to drain whole pond while not causing block updates and thus water regen" function works correctly. "Get water from a column without draining it" seems to not.

Also, would be a neat, albeit niche (I know of spillway because I accidentally spotted it in creative menu, and it's in the tail end of the book) feature if pond-drainer part worked with arbitrary fluids. Like lava, or MFR sludge.

**Comment by ReikaKalseki** [comment]
V19 adds a new interaction with falling columns of water, so this is likely going to become overridden.
