### ISSUE TITLE
[RoC V18b] Fan uses incorrect range formula, resulting in range being 1 block less than it should be

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1638]
Ingame, it claims the range formula is 8+(Power-MINPOWER)/1024. The _actual_ formula is 8+(Power-MINPOWER*2)/1024, because the variable used to clamp power has MINPOWER subtracted from it, and the actual range formula also has MINPOWER subtraction.

**Comment by ReikaKalseki** [comment]
Now to determine which is the intended one...

**Comment by Barhandar** [comment]
I think it's the one in the book, for two reasons. 1: Neat 8 blocks of range when on 1024W; 2: The subtraction in clamp is easier to have added accidentally and overlooked, if it was intended to subtract 2048 it would probably be in the formula calculation proper, not outside it.

**Comment by ReikaKalseki** [comment]
This is true.

**Comment by ReikaKalseki** [comment]
Fixed.
