### ISSUE TITLE
Repeater not connecting

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1639]
hi,
So I found that my red lumen repeater line was no longer connect to my casting temple. Suspecting a tree to have grown in the way I travelled all the way along the line until I found the first one still connected.  
I then discovered that no matter what, I couldn't get a repeater to connect.

![2017-10-28_21 12 24](https://user-images.githubusercontent.com/5174562/32137693-4392e524-bc25-11e7-83ab-840412906c8e.png)

In this picture the left repeater is connected while the right one is not.

chromaticraft v18b

**Comment by Turmfalke2** [comment]
Restarted the modpack and now it is working against, but the tahara one broke. Fortunately all I had to do to fix that one was travel to the pylon.

**Comment by ReikaKalseki** [comment]
This is an issue fixed in v19.

**Comment by Turmfalke2** [comment]
Nice, can't wait to see v19 released. I am spending to much time on maintenance.
