### ISSUE TITLE
Casting delegate fails to cast a heat lamp

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1640]
hi,
I do have the resources and if I remove one of the 3 firaxite it refills it, but it won't place the remaining 5 nor the iron ingot.

![2017-10-29_13 59 25](https://user-images.githubusercontent.com/5174562/32143924-87c90cdc-bcb1-11e7-8561-2f56e7088303.png)

v18b

**Comment by Turmfalke2** [comment]
flawed focus crystal has the same issue

**Comment by ReikaKalseki** [comment]
This is also fixed in v19.
