### ISSUE TITLE
Casting delegate crash

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1641]
hi,
The game crashed after I did the following:
I placed a crystal repeater in the top left slot of the casting delegate.
I noticed it didn't show the recipe for it and that the name label was empty.
I pressed the next recipe button.

https://pastebin.com/3CTS415C

v18b

**Comment by ReikaKalseki** [comment]
This should not be possible. However, I have redesigned large parts of the Casting Delegate for v19; try again then.
