### ISSUE TITLE
NEI Crash 1.7.10 (B)

### ISSUE THREAD

**Issue by manikminer123** [ReikaKalseki/Reika_Mods_Issues#1643]
Reika mods are causing my modpack to crash when looking up a recipe.
Game crash report: https://pastebin.com/NTfuPzvz
I reported this to the minecraft forums and they said to update my Reika mods. I did so and now my modpack won't load. I updated them from V9 to V18b. I use the Technic launcher (Platform) and here's the crash report for the launcher (Modpack): https://pastebin.com/8CTM3Nkz

**Comment by ReikaKalseki** [comment]
Do not re-paste old issues. #1623
