### ISSUE TITLE
Heat lily not working as expected

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1644]
hi,
If I put a heat lily on a block of water and then place a reservoir of liquid chroma next to it instantly freezes the water and breaks the lily, dropping it as an item.

Isn't the heat lily supposed to prevent water around it from freezing?

**Comment by ReikaKalseki** [comment]
DragonAPI's temperature code needs to fire an ice freeze event.

**Comment by ReikaKalseki** [comment]
Fixed.
