### ISSUE TITLE
Crash after placing down 1944

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1646]
hi,
I found one of those glowing towers I think (chromaticraft). I mean the ones with kind of crystal and laser pointing into the sky. Anyway I wondered I could break it, wamila said I could so I used my bedrock pickaxe on it. What I got was an item called 1944 with a missing texture, deciding that I probably shouldn't have that I tried putting it back again the game crashed.

https://pastebin.com/9qYHwtYa

v18b

**Comment by ReikaKalseki** [comment]
This has already been fixed in that the block was never supposed to be mineable.
