### ISSUE TITLE
Item Distribution Node keeps throwing Null Pointer Exception on client side

### ISSUE THREAD

**Issue by notchriss** [ReikaKalseki/Reika_Mods_Issues#1648]
I have Item Distribution Node connected directly to ME system (Applied Energistics 2). Every time I enter the general area near it where it probably loads for the client, I get something like this:

![2017-11-04_16 24 33](https://user-images.githubusercontent.com/8706925/32406208-bedfb35e-c17c-11e7-9c83-48a1dd6a91ae.png)

It happens just once upon entering the area, and again if I leave/come back or relog, i,e. does not spam it. And other than this Item Distribution Node system seems to work fine, items get inserted and extracted with nodes, etc.

I did try breaking and replacing it, placing it on different cables different parts of ME system, making sure there's always a free channel etc., nothing helped, but then again it's nothing gamebreaking.

I don't know how to copy/paste the exception in a more readable format, Twitch launcher has no console and error does not show up on a server side, and also nothing in crash reports obviously since the game does not crash.

**Comment by ReikaKalseki** [comment]
This has been fixed in v19.
