### ISSUE TITLE
Player Imitation Core not working as expected

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1649]
hi
I just spent 3 hours trying to get the player imitation core to work. From what the books tells me I should able to gain experience from my zambarau crystals. However nothing I try works. I has power, but appears to do nothing.

v18b

**Comment by ReikaKalseki** [comment]
It has been working for me for many weeks.
![https://i.imgur.com/7qwTQ7z.jpg](https://i.imgur.com/7qwTQ7z.jpg)

**Comment by Turmfalke2** [comment]
@ReikaKalseki 
And here is a screenshot of it not working.
![2017-11-05_10 16 06](https://user-images.githubusercontent.com/5174562/32413487-6161fa34-c212-11e7-97ca-a49a723ef89d.png)

Are you sure you are using v18b and that it working isn't related to your dev environment? 

E: better screenshot

E2: Also what is the difference between the different player imitation core tiers?

**Comment by ReikaKalseki** [comment]
No, I am not using v18, as I have coded a great deal since then. And that image is on the dev server, not in the dev environment.

**Comment by Turmfalke2** [comment]
@ReikaKalseki with v19 it still isn't working, but now I have got some /by zero exceptions for you.

https://pastebin.com/64MUjjEh

**Comment by ReikaKalseki** [comment]
Do you have a Tile-Accelerated Argia core? And it is still working for me.

**Comment by Turmfalke2** [comment]
Tile-accelerated argia core? As in connecting a tile accelerator to the player imitation core? No I haven't done that, but I could try.

Edit: it seems to throw the exception once per tick, so even if it is working for you there is clearly a bug here.

**Comment by Turmfalke2** [comment]
@ReikaKalseki Ok, checked the code and apparently a newly crafted core is of tier 0. Dividing 70/0 throws above exception. I have upgraded by core to tier 1 and now it is working.

**Comment by ReikaKalseki** [comment]
Fixed.
