### ISSUE TITLE
Biome painter forgets selected biome

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1650]
hi,
The biome painters forgets the selected biome instantly when opening the biome page and not just when selecting a new one. This is an issue as following shows.

- Open the biome painter gui, note how the active biome is none and the brush is set to 1x1 pixel.
- Hit the right arrow and search for a biome, select it by clicking on it. Note how the active biome is now displayed in the bottom of the window.
- Hit the right arrow again to select a bigger brush.
- Now hit left twice and try to paint, you will see that active biome has reverted back to none because you passed through the biome selection window on the way back from the brush selection.

This means currently you always have to adjust brush size before you can select the biome.

**Comment by ReikaKalseki** [comment]
Fixed.
