### ISSUE TITLE
RotaryCraft unifying GregTech/Pneumaticraft lubricant containers to RoC lubricant

### ISSUE THREAD

**Issue by lazerous42** [ReikaKalseki/Reika_Mods_Issues#1651]
Title pretty much says it all,  if I fill a container with GregTech lubricant cells (I uses an OpenBlocks tank, my bug report mentioned drums as well) then break it, the item on the ground will be a tank of RotaryCraft lubricant  At first I thought that this was a GT Unification setup problem, but I can reproduce it with Pneumaticraft lubricant as well, without GT installed.  I did see a passing mention of this issue in  #1621, but since the liquid registry is different than the oredict, I figured I warranted having a separate issue for proper documentation.

My original reported issue is here
https://github.com/lazerous42/Ascension-of-the-Technomancer/issues/41

**Comment by ReikaKalseki** [comment]
I have no such unification, and my fluid is on a dedicated name that is not going to conflict; someone else is doing something.

**Comment by Barhandar** [comment]
Said dedicated name being "rc lubricant". Someone else might be either mishandling spaces or partial-matching their strings.  
Or worse, messing with the drops, causing two fluids with same _display_ name to drop same itemstack. If that's the case two ethanols would have the issue as well.

**Comment by ReikaKalseki** [comment]
I did a stupid:

https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1621#issuecomment-342590600
