### ISSUE TITLE
Teleportation pump GUI throws nullPointer exception and crashes the client

### ISSUE THREAD

**Issue by notchriss** [ReikaKalseki/Reika_Mods_Issues#1652]
https://pastebin.com/3tVA2dVv

Sometimes it crashes immediately on right click before the GUI is even displayed, and sometimes it happens immediately after the GUI is displayed.

**Comment by ReikaKalseki** [comment]
This crash should be impossible, and I have used it repeatedly with no issues.

**Comment by notchriss** [comment]
Curious. I am going to test a few different cases, remove some other mods, change some settings and what not, and let you know the results.

**Comment by notchriss** [comment]
OK so after a few hours of removing mods one by one with no results, I got this bright idea to update my graphics card drivers and java. It did help ;) Not sure which one, but I think it was graphics drivers, since the latest version was released long after I started playing with this version of Chromaticraft. In any case problem was on my end.

**Comment by ReikaKalseki** [comment]
That should not have any effect, but OK...

**Comment by OvermindDL1** [comment]
Actually that specific error has been around for a long time and is not video card related.  It really is happening because a NULL is being passed in to `drawTexturedModelRectFromIcon` and is solved by just checking the arguments for null before hand.

However, Reika's icon is populated via a call to https://github.com/ReikaKalseki/DragonAPI/blob/master/Libraries/IO/ReikaLiquidRenderer.java#L134:

```java
	public static IIcon getFluidIconSafe(Fluid f, boolean flowing) {
		IIcon ico = flowing ? f.getFlowingIcon() : f.getStillIcon();
		if (ico == null) {
			DragonAPICore.logError("Fluid "+f.getID()+" ("+f.getLocalizedName()+") exists (block ID "+f.getBlock()+") but has no icon! Registering missingtex as a placeholder!");
			//ico = Blocks.bedrock.getIcon(0, 0);
			ico = ReikaTextureHelper.getMissingIcon();
			f.setIcons(ico);
		}
		return ico;
	}
```
Which you think would be safe, *however* an IIcon can hold data inside of it that can point to invalid information or even just an outright null itself.  So I'd bet money that the IIcon from the `Fluid f` or the `ReikaTextureHelper.getMissingIcon()` (though I doubt that one) is invalid and this function should change the `if` to check if the IIcon is valid as well, not just not null.

**Comment by ReikaKalseki** [comment]
That sounds more like something for my sanity checker.

**Comment by notchriss** [comment]
OK if its not graphics card related, could have java update fix it? Could the act of restarting client itself fix it somehow, idk, reseting some configs or fixing something that was previously corrupted by minecraft crashes? I mean I certainly haven't changed the code OvermindDL1 cites ;) Or does this bug sometimes happen sometimes not and nothing was fixed and I should expect crashes in the future?

**Comment by OvermindDL1** [comment]
> That sounds more like something for my sanity checker.

I'd agree, it is entirely a mod bug of whatever mod set that IIcon.

> could have java update fix it?

It is entirely possible that the other mod happened to hit a Java bug, it happens, the JVM is buggy hence why you always want to stay updated (I've seen *so* many JVM bugs...).

> Or does this bug sometimes happen sometimes not and nothing was fixed and I should expect crashes in the future?

This is also entirely common sad to say, the JVM is a very mutable world.

**Comment by ReikaKalseki** [comment]
The only default implementation of `IIcon` is `TextureAtlasSprite`, a vanilla class which is not normally even able to be constructed or modified by mod code; I find it unlikely that it has invalid internal values, much less ones that cause crash on render.

**Comment by OvermindDL1** [comment]
> I find it unlikely that it has invalid internal values, much less ones that cause crash on render.

I've seen it before though, maybe an Optifine thing (would not at all be surprising) or something.

**Comment by notchriss** [comment]
Right. It worked fine all day yesterday, but tonight the same crash again. Just this time not immediately, I managed to scroll through a few liquids before the crash occurred, if that matters in any way. Well in any case you seem to have found the problem causing code so I'll just wait for the version with fix before using the pump :)

**Comment by ReikaKalseki** [comment]
I have not made any code changes; there is not really much I *can* (or should attempt to) change, especially without ASMing into the class.
