### ISSUE TITLE
Chromaticraft tank reports its max possible size when asked for capacity of a particular tank

### ISSUE THREAD

**Issue by notchriss** [ReikaKalseki/Reika_Mods_Issues#1653]
I am a bit surprised this hasn't been reported yet, or maybe I just didn't find it in which case I'm sorry :)

RF Tools mod has this Tank module for it's display Screen where you Shift+Right Click a tank with a module, insert module into the screen and it displays tank's contents in Mb and also in percentage relative to max size (i.e. capacity) of that particular tank. However with my Crystal Tanks it seems to be displaying roughly 1/3 pp of what it's supposed to display. I.e. when the tank is full, Screen only shows 30%

Open Computers has this Adapter with TankController upgrade. It's API function getFluidInTank returns a table with capacity as one of its properties. And the property capacity is always 2 billions milibuckets (2,000,000,000). In my case, dividing full tank worth of Mbs by capacity is again the same number, 0.3 or 30%

So the obvious conclusion comes to mind that the tank api reports the max possible size of a Crystal Tank in general, as opposed to the size (capacity) of the particular tank I am trying to measure. 

For me it's no big deal I guess I can just use CrystalTank component's GetTankFraction() instead, which does work as expected. But many players just use RfTools screens or OpenComputer programs they downloaded, and those won't work.

**Comment by ReikaKalseki** [comment]
This i not a bug, since fluid tank sizes cannot be dynamic. Use getTankFraction instead.
