### ISSUE TITLE
"TileEntityReactorGenerator Contact Reika immediately!"

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1654]
https://pastebin.com/XSTAqPrL

Clean install on multimc (with codechickencore)
to be sure it wasn't anything in my pack :) .

**Comment by ReikaKalseki** [comment]
This looks like an accidental ElectriCraft dependency.

**Comment by lAimBotl** [comment]
Yey, hope it can be fixed easily (and soon) itching to update reika mods! 👍

**Comment by ReikaKalseki** [comment]
Hopefully fixed.
