### ISSUE TITLE
[CC V19a] NPE on initialization: CastingRecipe.getIDString

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1656]
https://gist.github.com/Barhandar/104da17a04d1bca38cc84d8b8654a3e3

Changed V18b mods to V19a, tried to launch, crashed. Going to try launching again in case it was an one-time error, but I suspect mod integration issues.

Nope, same error on relaunching, including after turning DAPI debug mode on.

**Comment by ReikaKalseki** [comment]
You have TiC installed but not the weapons; I already have a handler for this, but it was not used here.
