### ISSUE TITLE
Bug when disabling update notification

### ISSUE THREAD

**Issue by BradonDavis** [ReikaKalseki/Reika_Mods_Issues#166]
Self proclaimed "Community Loving Modder", Reika has created a new system which he believes will change the way how all users will think, or do not think. This genius has created this new system to allow these users of "lower intelligence" to be able to correctly perform a bug report. The way how this new and amazing feature works is that it will literally have the face of Reika (with a tail on his head) at the top of your screen, if you do any act which the dragonmaster disagrees with, the screen will flash black and blue and his face will start shouting at you. I tried having a look at the source code to see when this change was made and how dangerous it could be, but on the Github the only change I could find was called “Update”, which I doubt contains the code.

After hearing of this "genius" feature, we seeked after Reika for an interview. After weeks of searching we found him in a cave, resting above a brightly coloured egg, after a large amount of coaxing (including the soul of a young child) the only thing he had to say was - "This will finally stop the harassment of incorrect bug reports I gained on the FTB and Minecraft forums. Using this time I will finally be able to recreate the modding community into something which is more suitable for me.." We were then told to leave the premise because we were told that we were "Bullies who were witch hunting him", with the fire from his flamethrower hat making the back of my hair catch alight. 

Some modders have been claiming that this is a piece of propaganda to create the "furtopia" that one of Reikas 12 disciples called “JeasePudas” leaked the concept of. Creator of the one and only spaceship, KingLemming was the head of the anti support group trying to destroy the "vicious destruction of our community". KingLemming told us that "When I created the Minecraft community on a dark sunday after I launched the shuttle to Galacticraft, I did not envision a so called 'modder' like Reika trying to claim control over it. This propaganda will end my reign of control over what I hold dear." KingLemming was then found etching 'You will end up like Greggy' on a Redstone infused Invar Sickle.

Now we are all unsure as to what will happen with this “Machine of propaganda”, which the Lemming-meister later called it, but I believe there could be a even more devilish idea behind this monstrous “feature”. At this point I do not know what will happen to me after posting these truths that I found, I fear that there are certain individuals that may come for me. Because of that I have posted my finding with the gracious people of r/FTB. I hope this will serve you well.

**Comment by zerotheliger** [comment]
umm what did i just read.

**Comment by zmaster587** [comment]
Troll bug much?

**Comment by zerotheliger** [comment]
Nobody delete this till reika sees it please. This is golden.

**Comment by zerotheliger** [comment]
But yeah about that bug...

**Comment by asiekierka** [comment]
> Joined on Jul 24, 2015
> 1 issue reported

This seems sketchy.

**Comment by zerotheliger** [comment]
Still a better love story than twilight.
Sooo about that bug...

**Comment by zmaster587** [comment]
troll much?

**Comment by zerotheliger** [comment]
Z i wouldn't exactly call it a troll...

**Comment by mDiyo** [comment]
Github isn't exactly the best place for fan fiction.

**Comment by techno156** [comment]
mDiyo, FanFiction is one way of putting it...

**Comment by ghost** [comment]
@BradonDavis  What is the bug exactly? Github isnt exactly made for stories. You should use ftb reddit for that instead.

**Comment by zerotheliger** [comment]
I think what happened is he posted it to ftb reddit and it got removed because i cant find it

**Comment by zmaster587** [comment]
@BradonDavis Have you tried turning your brain off and turning it back on?

**Comment by techno156** [comment]
@zerotheliger I don't remember him saying that he posted it to the subreddit...

**Comment by zerotheliger** [comment]
the part where it says "Because of that I have posted my finding with the gracious people of r/FTB."

i think it was probably deleted because i cant find anything.

**Comment by techno156** [comment]
@zerotheliger oh, missed that bit. :p 
That is entirely possible, or that it was never posted at all in the first place.

**Comment by trajing** [comment]
_\* trajing blinks_

**Comment by TomeWyrm** [comment]
I check my GitHub notifications and see the title, my first instinct is a report that a previous version (probably v6) had notifications that wouldn't disable properly (which is a known issue).

I get here and it's the kind of fanfiction most people think of when they think of fanfic (which is sad, I've read some amazing fan-created fiction.). I actually couldn't read the entire thing due to a combination of the absurdity and the intolerance inherent to the word choice. If this wasn't full of vitriol and bile, it might've actually gotten some traction on /r/feedthebeast as a whimsically satirical re-imagining of events.

I suggest we keep this one open, because the comment thread amuses me to no end. Though renaming the "issue" to Fan Fiction like CoolSquid did would certainly be less misleading.

**Comment by ReikaKalseki** [comment]
Comment on it all you want, but I am not leaving it open.

**Comment by asiekierka** [comment]
@ReikaKalseki - this is clearly @&#%?!. I think you removing that label is very unjust.

**Comment by ReikaKalseki** [comment]
The "@&#%?!" tag is for bugs that make no sense.

**Comment by TomeWyrm** [comment]
Never knew that you wanted the "@&#%?!" tag for bugs specifically. I thought it was for general WTF-ery. Thanks for the clarification.
