### ISSUE TITLE
Dew point agregator broken in 1.19

### ISSUE THREAD

**Issue by notchriss** [ReikaKalseki/Reika_Mods_Issues#1661]
![2017-11-11_12 57 02](https://user-images.githubusercontent.com/8706925/32688798-5997a024-c6e0-11e7-8278-9fa62b80414b.png)

Power is being received, WAILA shows producing a crapload per tick, but actually agregator is empty and pipe is empty and attached fluid tank is empty. (The pipe with water further away is not connected, it has some water from before the update). Breaking and replacing pipes/tanks/fins/agregators/power source didn't help. 

It happened it 1.19a but 1.19b haven't fixed it either

**Comment by ReikaKalseki** [comment]
You need to cool the fins now.

![https://i.imgur.com/u1fUihS.png](https://i.imgur.com/u1fUihS.png)
