### ISSUE TITLE
Bedrock shovel broken in v19.

### ISSUE THREAD

**Issue by RealityAnomaly** [ReikaKalseki/Reika_Mods_Issues#1662]
Whenever a block is broken with the bedrock shovel in v19 the game will crash immediately.
This did not happen in v18 (reverting fixes it).

# Server

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 11/11/17 10:41
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: Could not initialize class Reika.DragonAPI.ModInteract.ItemHandlers.TinkerBlockHandler
	at Reika.RotaryCraft.Items.Tools.Bedrock.ItemBedrockShovel.getDigSpeed(ItemBedrockShovel.java:112)
	at net.minecraft.entity.player.EntityPlayer.getBreakSpeed(EntityPlayer.java:811)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:134)
	at net.minecraft.block.Block.func_149737_a(Block.java:643)
	at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:172)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 980626152 bytes (935 MB) / 2545512448 bytes (2427 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D8 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	asielib{0.4.8} [asielib] (AsieLib-1.7.10-0.4.8.jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJAAAA	BioLock{2.2.pr1} [BioLock] (BioLock-v2.2.pr1-1.7.10.jar) 
	UCHIJAAAA	CCLights2{0.4.3} [CCLights 2] (CCLights2-1.7.10-0.4.3.jar) 
	UCHIJAAAA	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	DragonAPI{v19b} [DragonAPI] (DragonAPI 1.7.10 V19b.jar) 
	UCHIJAAAA	ChromatiCraft{v19b} [ChromatiCraft] (ChromatiCraft 1.7.10 V19b.jar) 
	UCHIJAAAA	computronics{1.6.5} [Computronics] (Computronics-1.7.10-1.6.5.jar) 
	UCHIJAAAA	RotaryCraft{v19b} [RotaryCraft] (RotaryCraft 1.7.10 V19b.jar) 
	UCHIJAAAA	ElectriCraft{v19b} [ElectriCraft] (ElectriCraft 1.7.10 V19b.jar) 
	UCHIJAAAA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b197.jar) 
	UCHIJAAAA	GeoStrata{v19a} [GeoStrata] (GeoStrata 1.7.10 V19a.jar) 
	UCHIJAAAA	IGWMod{1.1.12-34} [In-Game wiki Mod] (IGW-Mod-1.7.10-1.1.12-34-universal.jar) 
	UCHIJAAAA	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
	UCHIJAAAA	ImmibisPeripherals{59.0.3} [Immibis's Peripherals] (immibis-peripherals-59.0.3.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJAAAA	OCS{1.7.5} [OpenCCSensors] (openccsensors-1.7.5.jar) 
	UCHIJAAAA	openfm{0.1.0.40} [OpenFM] (OpenFM-1.7.10-0.1.0-40.jar) 
	UCHIJAAAA	OpenMods{0.9.1} [OpenMods] (openmodslib-1.7.10-0.9.1.jar) 
	UCHIJAAAA	OpenPeripheralCore{1.3} [OpenPeripheralCore] (openperipheral-1.7.10-AIO-7.jar) 
	UCHIJAAAA	OpenPeripheral{0.5.1} [OpenPeripheralAddons] (openperipheral-1.7.10-AIO-7.jar) 
	UCHIJAAAA	OpenPeripheralIntegration{0.5} [OpenPeripheralIntegration] (openperipheral-1.7.10-AIO-7.jar) 
	UCHIJAAAA	ReactorCraft{v19b} [ReactorCraft] (ReactorCraft 1.7.10 V19b.jar) 
	UCHIJAAAA	TickProfiler{1.0} [TickProfiler] (TickProfiler-1.7.10.jenkins.37.jar) 
	UCHIJAAAA	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:ON, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['CitadelCore'/286, l='Last Chance', x=195.30, y=64.00, z=187.29]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_D8
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 16
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 387.92
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

# Client

---- Minecraft Crash Report ----
// You're mean.

Time: 11/11/17 11:06
Description: Unexpected error

java.lang.ExceptionInInitializerError
	at Reika.RotaryCraft.Items.Tools.Bedrock.ItemBedrockShovel.getDigSpeed(ItemBedrockShovel.java:112)
	at net.minecraft.entity.player.EntityPlayer.getBreakSpeed(EntityPlayer.java:811)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:134)
	at net.minecraft.block.Block.func_149737_a(Block.java:643)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78743_b(PlayerControllerMP.java:177)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1409)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1948)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at Reika.DragonAPI.Instantiable.Data.Immutable.BlockKey.<init>(BlockKey.java:44)
	at Reika.DragonAPI.ModInteract.ItemHandlers.TinkerBlockHandler.<init>(TinkerBlockHandler.java:234)
	at Reika.DragonAPI.ModInteract.ItemHandlers.TinkerBlockHandler.<clinit>(TinkerBlockHandler.java:28)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Reika.RotaryCraft.Items.Tools.Bedrock.ItemBedrockShovel.getDigSpeed(ItemBedrockShovel.java:112)
	at net.minecraft.entity.player.EntityPlayer.getBreakSpeed(EntityPlayer.java:811)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:134)
	at net.minecraft.block.Block.func_149737_a(Block.java:643)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78743_b(PlayerControllerMP.java:177)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1409)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['CitadelCore'/280, l='MpServer', x=188.95, y=63.62, z=201.38]]
	Chunk stats: MultiplayerChunkCache: 289, 298
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (200,64,216), Chunk: (at 8,4,8 in 12,13; contains blocks 192,0,208 to 207,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8037600 game time, 8042716 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 32 total; [EntitySquid['Squid'/1398815, l='MpServer', x=239.47, y=57.25, z=246.50], EntityItem['item.item.reeds'/1316760, l='MpServer', x=173.88, y=61.00, z=196.88], EntityItem['item.item.item.canola'/1770900, l='MpServer', x=175.13, y=61.15, z=203.13], EntityChicken['Chicken'/19, l='MpServer', x=117.53, y=62.46, z=171.06], EntityBat['Bat'/1792002, l='MpServer', x=256.44, y=34.00, z=268.91], EntityItem['item.item.item.canola'/1178545, l='MpServer', x=175.13, y=61.23, z=203.13], EntityItem['item.item.reeds'/1819195, l='MpServer', x=182.50, y=61.13, z=188.19], EntitySheep['Sheep'/40, l='MpServer', x=166.13, y=63.00, z=128.28], EntityItem['item.item.item.canola'/49, l='MpServer', x=175.13, y=61.39, z=203.13], EntityBat['Bat'/1792303, l='MpServer', x=152.78, y=13.00, z=274.72], EntitySkeleton['Skeleton'/170164, l='MpServer', x=46.42, y=-0.02, z=21.30], EntityBat['Bat'/1448480, l='MpServer', x=227.16, y=36.71, z=163.34], EntityZombie['Zombie'/170165, l='MpServer', x=37.76, y=-0.03, z=12.30], EntityItem['item.item.item.canola'/826166, l='MpServer', x=175.13, y=61.29, z=203.13], EntitySheep['Sheep'/62, l='MpServer', x=184.19, y=63.00, z=146.91], EntityItem['item.item.item.canola'/1339563, l='MpServer', x=175.13, y=61.17, z=203.13], EntityClientPlayerMP['CitadelCore'/280, l='MpServer', x=188.95, y=63.62, z=201.38], EntityChicken['Chicken'/73, l='MpServer', x=197.41, y=63.00, z=143.44], EntityItem['item.item.item.canola'/1793617, l='MpServer', x=176.13, y=61.13, z=202.38], EntityItemFrame['entity.ItemFrame.name'/75, l='MpServer', x=194.50, y=59.50, z=215.94], EntityItemFrame['entity.ItemFrame.name'/76, l='MpServer', x=192.50, y=59.50, z=215.94], EntityItemFrame['entity.ItemFrame.name'/77, l='MpServer', x=196.94, y=59.50, z=214.50], EntityItemFrame['entity.ItemFrame.name'/78, l='MpServer', x=196.94, y=59.50, z=212.50], EntityItemFrame['entity.ItemFrame.name'/79, l='MpServer', x=192.50, y=59.50, z=211.06], EntityCow['Cow'/85, l='MpServer', x=210.25, y=63.00, z=128.50], EntityBat['Bat'/1727693, l='MpServer', x=258.78, y=19.00, z=168.63], EntityBat['Bat'/1692484, l='MpServer', x=261.69, y=19.00, z=170.88], EntityPig['Pig'/95, l='MpServer', x=233.03, y=63.00, z=145.03], EntityItem['item.item.item.canola'/1591034, l='MpServer', x=175.13, y=61.15, z=203.13], EntityBat['Bat'/1807487, l='MpServer', x=112.13, y=21.00, z=176.44], EntityBat['Bat'/1653500, l='MpServer', x=156.47, y=15.00, z=273.13], EntityItem['item.item.reeds'/1180780, l='MpServer', x=178.66, y=61.13, z=188.84]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 807644800 bytes (770 MB) / 2792407040 bytes (2663 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D8 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	asielib{0.4.8} [asielib] (AsieLib-1.7.10-0.4.8.jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJAAAA	BioLock{2.2.pr1} [BioLock] (BioLock-v2.2.pr1-1.7.10.jar) 
	UCHIJAAAA	CCLights2{0.4.3} [CCLights 2] (CCLights2-1.7.10-0.4.3.jar) 
	UCHIJAAAA	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	DragonAPI{v19b} [DragonAPI] (DragonAPI 1.7.10 V19b.jar) 
	UCHIJAAAA	ChromatiCraft{v19b} [ChromatiCraft] (ChromatiCraft 1.7.10 V19b.jar) 
	UCHIJAAAA	computronics{1.6.5} [Computronics] (Computronics-1.7.10-1.6.5.jar) 
	UCHIJAAAA	RotaryCraft{v19b} [RotaryCraft] (RotaryCraft 1.7.10 V19b.jar) 
	UCHIJAAAA	ElectriCraft{v19b} [ElectriCraft] (ElectriCraft 1.7.10 V19b.jar) 
	UCHIJAAAA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b197.jar) 
	UCHIJAAAA	GeoStrata{v19a} [GeoStrata] (GeoStrata 1.7.10 V19a.jar) 
	UCHIJAAAA	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
	UCHIJAAAA	ImmibisPeripherals{59.0.3} [Immibis's Peripherals] (immibis-peripherals-59.0.3.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJAAAA	OCS{1.7.5} [OpenCCSensors] (openccsensors-1.7.5.jar) 
	UCHIJAAAA	openfm{0.1.0.40} [OpenFM] (OpenFM-1.7.10-0.1.0-40.jar) 
	UCHIJAAAA	OpenMods{0.9.1} [OpenMods] (openmodslib-1.7.10-0.9.1.jar) 
	UCHIJAAAA	OpenPeripheralCore{1.3} [OpenPeripheralCore] (openperipheral-1.7.10-AIO-7.jar) 
	UCHIJAAAA	OpenPeripheral{0.5.1} [OpenPeripheralAddons] (openperipheral-1.7.10-AIO-7.jar) 
	UCHIJAAAA	OpenPeripheralIntegration{0.5} [OpenPeripheralIntegration] (openperipheral-1.7.10-AIO-7.jar) 
	UCHIJAAAA	ReactorCraft{v19b} [ReactorCraft] (ReactorCraft 1.7.10 V19b.jar) 
	UCHIJAAAA	TickProfiler{1.0} [TickProfiler] (TickProfiler-1.7.10.jenkins.37.jar) 
	UCHIJAAAA	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:ON, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 387.92, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Nullification]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)
	OptiFine Version: OptiFine_1.7.10_HD_U_D8
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 16
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 387.92
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by ReikaKalseki** [comment]
Try updating TiC.

![https://i.imgur.com/vci5B5w.png](https://i.imgur.com/vci5B5w.png)

**Comment by RealityAnomaly** [comment]
Tinker's Construct is not installed. (as the mod list shows)

**Comment by ReikaKalseki** [comment]
OH...

Fixed.
