### ISSUE TITLE
crafting crystal repeaters in item casting delegate  v19

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1664]
hi,
In v19 I still can't put a crystal repeater in the top left slot of the item casting delegate, if I do I fails to find the recipe and the item name label is empty.

**Comment by ReikaKalseki** [comment]
It is working fine for me, both for default and boosted repeaters:

![https://i.imgur.com/sPCzysN.png](https://i.imgur.com/sPCzysN.png)
![https://i.imgur.com/uN0k98b.png](https://i.imgur.com/uN0k98b.png)

EDIT:
You *have* crafted repeaters on that table, yes?

**Comment by Turmfalke2** [comment]
Yes, maybe there is a difference between your presumably spawned in repeaters and the ones I pulled from my me system? Also the same happens with the multi repeater.

**Comment by ReikaKalseki** [comment]
It has nothing to do with them being spawned, but previously *placed* ones had an issue. Now fixed.

**Comment by Turmfalke2** [comment]
@ReikaKalseki Should this have retroactivly fixed the old repeaters? Because this is now with V19c my situation:
putting a repeater from my me system into the to left slot:
![2017-11-14_16 17 15](https://user-images.githubusercontent.com/5174562/32787732-94c9f63c-c957-11e7-821f-80d8b774f800.png)

selecting from the list:
![2017-11-14_16 17 28](https://user-images.githubusercontent.com/5174562/32787760-adba489a-c957-11e7-93a1-f2f0988efd46.png)

**Comment by ReikaKalseki** [comment]
Yes, it would have. And I *did* test it.

**Comment by Turmfalke2** [comment]
The ender crystal has the same issue for me. In v19c I have crafted my first ender crystal by placing the items manually, I have then crafted one by selecting it from the list and now I can't craft it by dropping one in the top left slot.

**Comment by ReikaKalseki** [comment]
What is the NBT on the item you are using as a filter?

**Comment by Turmfalke2** [comment]
/itemnbt says it has my ownerid, other than that nothing.

**Comment by ReikaKalseki** [comment]
That is probably the issue. What is the exact output?

**Comment by Turmfalke2** [comment]
ownerid: "b22f48b3-1055-4ee7-aef6-877dbe200043"
