### ISSUE TITLE
CME in the nether DragonAPI.IO.ThrottleableEffectRenderer.doRenderParticles

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1665]
hi,
I just went into the nether and killed a ghast, the moment I did that I crashed.

https://pastebin.com/36fMYtTN

**Comment by ReikaKalseki** [comment]
Is this reliable?

**Comment by Turmfalke2** [comment]
Haven't killed that many ghasts, but I doubt it is related to them. So at the moment it isn't.

**Comment by ReikaKalseki** [comment]
Hopefully fixed.

**Comment by Turmfalke2** [comment]
@ReikaKalseki meanwhile I was able to reproduce the bug.

**Comment by ReikaKalseki** [comment]
Reliably?

**Comment by Turmfalke2** [comment]
Somewhat, I can reliably trigger it within 30 minutes by fighting monsters in the nether.

**Comment by ReikaKalseki** [comment]
That is not at all reliable. But it is probably resolved.

**Comment by mcadventurecity** [comment]
I can reproduce this issue, but it happens for me seconds after loading my world. I am on v19b.
