### ISSUE TITLE
Void monster drops nothing upon death

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1666]
Hi,
Since v19 the void monster no longer drops any xp or items when it dies. It just create a lightning strike and disappears into some smoke clouds. It also appears to respawn pretty much instantly.

In the log I can see that items were added to it's loot table.

**Comment by ReikaKalseki** [comment]
Its drops were probably destroyed by the lightning.

**Comment by ReikaKalseki** [comment]
OK, that will not happen anymore.
