### ISSUE TITLE
Pendants show "wearing off" effect every cycle

### ISSUE THREAD

**Issue by dieselfuelonly** [ReikaKalseki/Reika_Mods_Issues#1670]
Not sure if this was intended, but in v19b the pendants cause the "wearing off" effect to be displayed every cycle.  For example, the nightvision pendant will cause the screen to flash light and dark as the potion timer nears zero.  Not a huge deal, but definitely an annoyance as this didn't occur in older versions.

Haven't tested this with the regular pendants, but its definitely occurring with the enhanced ones.

**Comment by ReikaKalseki** [comment]
Only the night vision, or other pendants as well?

**Comment by dieselfuelonly** [comment]
Appears to be only nightvision now that I look at it again.  I could have sworn I saw the FoV change with the run speed pendant timer running out, but maybe I was just sprinting at the wrong time :P

**Comment by ReikaKalseki** [comment]
Pendant code has not changed in any semantic way since v13 (May of 2016), and even *that* was minor...

EDIT: I know what is happening; it has nothing to do with pendants directly at all.
