### ISSUE TITLE
StructureCache encryption is complete bollocks, also buggy.

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1671]
hi,
So I have been trying to figure out that strange issue with sometimes NBT not getting written/read. For this I had a closer look at the StructureCache and found that you in  DragonAPI/Instantiable/IO/NBTFile.java you implemented an "encryption" that is used for the StructureCache. This encryption consists of reversing the bytes with in the file. I have no idea why you would do that. Do you want to make it more difficult to debug?
Ignoring the minimal time required to reverse the file this wouldn't be an issue, however the read/write functions are bugged. Every time I load the world, it is reversing the file again. This means every second time I load the world it fails to read the nbt tags because the file is already in the correct order.

Suggested fix: Remove the silly encryption.

**Comment by ReikaKalseki** [comment]
Reading the file from disc and unencrypting it does not edit the actual file. And it has nothing to do with the crystal network. And it is effective at what it was designed to do - break NBT editors. And it will not be removed.

**Comment by Turmfalke2** [comment]
@ReikaKalseki OK maybe you missed the part were this isn't working? Like I still consider breaking NBT editors for the sake of it pretty stupid, but your current solution also breaks your own mods every second time it attempts to load the file.

For example I had the following file in the StructureCache and no I didn't not temper with it (renamed to zip):
[ocean.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1464422/ocean.zip)

This file can be read by any NBT editor, but your mod fails to do so.

**Comment by ReikaKalseki** [comment]
What are you talking about? It flips it once when reading it from disk to RAM and once when writing back to disk. Two flips cancel each other out.

**Comment by Barhandar** [comment]
In my experience it was flipped about half the time while I was having crystalnetwork crashes.

**Comment by Turmfalke2** [comment]
@ReikaKalseki that is how it is supposed to work, but in practice it doesn't.
Test setup:
- forge 1614
- DragonApi v19b
- ChromatiCraft v19b  

Steps to reprduce
- start the minecraft instance
- create a new world
- inspect the burrow.dat file as it is saved to the disc, note that it ends with redaeh and end with atad
- quit to main menu
- enter the world from step 2 again
- inspect the burrow.dat file as it saved to the disc, note that it starts with data and ends with header.

Every time I load the world the file as it saved to the disc gets flipped, which means half the time your mod fails to read it and throws an exception.
