### ISSUE TITLE
Some repeaters can transmit lumens at a 45* angle while others can't.

### ISSUE THREAD

**Issue by dieselfuelonly** [ReikaKalseki/Reika_Mods_Issues#1672]
Upgraded from v18b to v19b.  Network stopped working for the most part except for a few pylons.

Network is set up on every pylon just like the following:

https://i.imgur.com/1UmDLYf.jpg

Removed and replaced the repeater blocks on this vertical-to-horizontal area both working and non-working networks.  Ones that worked prior to breaking the blocks, still work.  Ones that didn't work, still don't work even after removing/replacing.

**Comment by dieselfuelonly** [comment]
A little more info after some experimenting:

All the repeaters transmitting 45* from South to North (like in the picture from the previous post) are working.

All the repeaters transmitting 45* from North to South (like this:  https://i.imgur.com/n3R3Zhs.jpg) are not working.

I don't have any going West to East or vice versa so I can't attest to whether they are working or not.

**Comment by ReikaKalseki** [comment]
Transmitting at a 45-degree angle fails most line of sight checks. V19 made the pathfinding more deterministic (it previously worked in cases where it should not).

**Comment by Barhandar** [comment]
Working in one case but not the other isn't really more deterministic than working in both cases.

**Comment by ReikaKalseki** [comment]
The problem before was that it might work one way and not the other, which is very undesirable.

**Comment by Aivech** [comment]
I don't know when you made these changes but in v19 beta I had this problem, except it appeared to depend on color rather than direction.

**Comment by ReikaKalseki** [comment]
These changes were made after you left the server.
