### ISSUE TITLE
Suggestion: Cliff Farmland accept agricraft crops

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1679]
Hi,
this would be nice otherwise you must change the biome to something else, make all dirt to farmland and then change to luminous cliffs back.

Additonally the biome painter doesn't paint in the luminous cliffs biom correctly but changes the biome. The change is only visible if you open the painter again

greets

**Comment by ReikaKalseki** [comment]
You can plant AgriCraft - and any other crop - directly on grass in the cliffs.

**Comment by EyeDeck** [comment]
Agricraft has a soil whitelist. In config\agricraft\SoilWhitelist.txt, add:
ChromatiCraft:chromaticraft_block_cliffstone:3
