### ISSUE TITLE
Chromaticraft Rendering Crash

### ISSUE THREAD

**Issue by TiranDirth** [ReikaKalseki/Reika_Mods_Issues#1680]
This is Railcraft related too,  so I understand if the issue is there (and I can just turn off the hidden blocks), but figured it doesn't hurt to let you know!

While Optifine is on, I have reproduced the same crash without Optifine in the exact same situation.

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 16/11/17 02:30
Description: Unexpected error

java.lang.ClassCastException: mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to Reika.ChromatiCraft.Block.Decoration.BlockAvoLamp$TileEntityAvoLamp
	at Reika.ChromatiCraft.Block.Decoration.BlockAvoLamp.func_149668_a(BlockAvoLamp.java:95)
	at net.minecraft.world.World.func_147472_a(World.java:3317)
	at net.minecraft.item.ItemBlock.func_150936_a(ItemBlock.java:159)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:333)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Reika.ChromatiCraft.Block.Decoration.BlockAvoLamp.func_149668_a(BlockAvoLamp.java:95)
	at net.minecraft.world.World.func_147472_a(World.java:3317)
	at net.minecraft.item.ItemBlock.func_150936_a(ItemBlock.java:159)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:333)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['TiranDirth'/28130868, l='MpServer', x=-144.61, y=69.32, z=106.79]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (36,64,256), Chunk: (at 4,4,0 in 2,16; contains blocks 32,0,256 to 47,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 94349417 game time, 95855432 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 135 total; [EntityVillager['Villager'/28130978, l='MpServer', x=-205.09, y=69.00, z=167.41], GCEntityClientPlayerMP['TiranDirth'/28130868, l='MpServer', x=-144.61, y=69.32, z=106.79], EntityMobEnderman['Enderman'/28119224, l='MpServer', x=-93.50, y=31.00, z=173.50], EntityBat['Bat'/28132536, l='MpServer', x=-221.00, y=34.00, z=92.50], EntityCartChest['entity.MinecartChest.name'/28130996, l='MpServer', x=-131.25, y=47.50, z=180.50], EntityCartChest['entity.MinecartChest.name'/28130995, l='MpServer', x=-132.81, y=47.50, z=180.50], EntityCartChest['entity.MinecartChest.name'/28130994, l='MpServer', x=-134.38, y=47.50, z=180.50], EntityTier1Rocket['Tier 1 Rocket'/23330684, l='MpServer', x=-47.50, y=70.90, z=200.50], EntityPainting['Painting'/28130953, l='MpServer', x=-109.00, y=67.00, z=159.94], EntityPainting['Painting'/28130952, l='MpServer', x=-105.06, y=67.50, z=155.50], EntityPainting['Painting'/28130951, l='MpServer', x=-105.06, y=67.50, z=157.50], EntityChicken['Chicken'/28130950, l='MpServer', x=-111.59, y=11.00, z=158.41], EntitySkeleton['Skeleton'/28130947, l='MpServer', x=-85.56, y=42.00, z=46.66], EntityZombie['Zombie'/28129949, l='MpServer', x=-90.56, y=39.00, z=47.59], EntitySheep['Sheep'/28130972, l='MpServer', x=-212.19, y=68.00, z=31.44], EntityZombie['Zombie'/28129948, l='MpServer', x=-82.84, y=41.00, z=52.38], EntitySkeleton['Skeleton'/28129950, l='MpServer', x=-80.50, y=41.00, z=55.50], EntityBabySkeleton['Baby Skeleton'/28129945, l='MpServer', x=-83.84, y=38.00, z=70.63], EntityItem['item.item.bone'/28129947, l='MpServer', x=-82.69, y=39.13, z=59.69], EntityMobEnderman['Enderman'/28130964, l='MpServer', x=-188.16, y=35.00, z=13.38], EntityChicken['Chicken'/62, l='MpServer', x=-92.56, y=39.00, z=170.38], EntitySpark['Spark'/64, l='MpServer', x=-91.50, y=65.50, z=166.50], EntitySpark['Spark'/65, l='MpServer', x=-88.50, y=65.50, z=169.50], EntityChicken['Chicken'/66, l='MpServer', x=-82.22, y=64.00, z=176.22], EntityItem['item.item.bone'/28130025, l='MpServer', x=-116.31, y=39.13, z=155.13], EntityItem['item.item.feather'/28130024, l='MpServer', x=-112.66, y=11.13, z=158.38], EntityMobEnderman['Enderman'/28132072, l='MpServer', x=-192.50, y=55.00, z=7.50], EntityChicken['Chicken'/28130026, l='MpServer', x=-120.47, y=57.00, z=157.16], EntitySheep['Sheep'/28130021, l='MpServer', x=-111.81, y=67.00, z=178.38], EntityCow['Cow'/28130020, l='MpServer', x=-115.28, y=67.00, z=178.50], EntityChicken['Chicken'/28130023, l='MpServer', x=-113.38, y=11.00, z=155.47], EntitySheep['Sheep'/28130018, l='MpServer', x=-111.47, y=67.00, z=176.09], EntityBat['Bat'/28132862, l='MpServer', x=-201.26, y=33.41, z=139.32], EntityBat['Bat'/28132857, l='MpServer', x=-203.47, y=34.32, z=141.47], EntityBat['Bat'/28132856, l='MpServer', x=-210.07, y=33.81, z=142.65], EntitySheep['Sheep'/28131021, l='MpServer', x=-117.91, y=67.00, z=178.75], EntitySheep['Sheep'/28131020, l='MpServer', x=-112.16, y=67.00, z=177.22], EntityBabySkeleton['Baby Skeleton'/28132300, l='MpServer', x=-179.50, y=53.00, z=132.50], EntitySheep['Sheep'/28131023, l='MpServer', x=-116.69, y=67.00, z=177.22], EntitySheep['Sheep'/28131022, l='MpServer', x=-117.91, y=67.00, z=179.91], EntityCelestialFake['entity.CelestialScreen.name'/100, l='MpServer', x=-47.50, y=1202.38, z=200.50], EntitySheep['Sheep'/28131017, l='MpServer', x=-117.19, y=67.00, z=176.09], EntityBabySkeleton['Baby Skeleton'/28132297, l='MpServer', x=-181.50, y=53.00, z=123.50], EntityCelestialFake['entity.CelestialScreen.name'/101, l='MpServer', x=-47.50, y=1202.38, z=200.50], EntitySheep['Sheep'/28131016, l='MpServer', x=-117.91, y=67.00, z=177.34], EntityBabySkeleton['Baby Skeleton'/28132296, l='MpServer', x=-180.29, y=53.00, z=124.62], EntityCelestialFake['entity.CelestialScreen.name'/102, l='MpServer', x=-47.50, y=1202.38, z=200.50], EntityPig['Pig'/28131019, l='MpServer', x=-114.13, y=67.00, z=176.09], EntityBabySkeleton['Baby Skeleton'/28132299, l='MpServer', x=-179.50, y=53.00, z=127.50], EntityCelestialFake['entity.CelestialScreen.name'/103, l='MpServer', x=-47.50, y=1203.38, z=200.50], EntitySheep['Sheep'/28131018, l='MpServer', x=-115.44, y=67.00, z=179.91], EntityBabySkeleton['Baby Skeleton'/28132298, l='MpServer', x=-179.50, y=53.00, z=130.50], EntityCelestialFake['entity.CelestialScreen.name'/104, l='MpServer', x=-47.50, y=1204.38, z=200.50], EntityBabySkeleton['Baby Skeleton'/28132293, l='MpServer', x=-179.51, y=53.65, z=123.25], EntityCelestialFake['entity.CelestialScreen.name'/105, l='MpServer', x=-47.50, y=1205.38, z=200.50], EntityCelestialFake['entity.CelestialScreen.name'/106, l='MpServer', x=-47.50, y=1206.38, z=200.50], EntityBabySkeleton['Baby Skeleton'/28132295, l='MpServer', x=-180.50, y=53.00, z=126.50], EntityLocomotiveSteamSolid['Steam Locomotive'/28131014, l='MpServer', x=-126.59, y=47.50, z=180.50], EntityCelestialFake['entity.CelestialScreen.name'/107, l='MpServer', x=-47.50, y=1207.38, z=200.50], EntityBabySkeleton['Baby Skeleton'/28132294, l='MpServer', x=-177.59, y=53.00, z=131.63], EntityCelestialFake['entity.CelestialScreen.name'/108, l='MpServer', x=-47.50, y=1208.38, z=200.50], EntityCelestialFake['entity.CelestialScreen.name'/109, l='MpServer', x=-47.50, y=1209.38, z=200.50], EntityCelestialFake['entity.CelestialScreen.name'/110, l='MpServer', x=-47.50, y=1210.38, z=200.50], EntityChicken['Chicken'/28130009, l='MpServer', x=-118.22, y=67.00, z=175.78], EntityChicken['Chicken'/28130005, l='MpServer', x=-106.59, y=11.00, z=167.63], EntityCow['Cow'/28131028, l='MpServer', x=-115.50, y=67.00, z=177.28], EntityItem['item.item.bone'/28130006, l='MpServer', x=-100.81, y=33.13, z=161.19], EntityPig['Pig'/28131025, l='MpServer', x=-115.78, y=67.00, z=176.09], EntityPig['Pig'/28131024, l='MpServer', x=-116.66, y=67.00, z=178.63], EntitySheep['Sheep'/28131027, l='MpServer', x=-113.88, y=67.00, z=177.50], EntitySkeleton['Skeleton'/3710, l='MpServer', x=-10.95, y=-107.11, z=37.07], EntitySheep['Sheep'/28131026, l='MpServer', x=-116.63, y=67.00, z=179.91], EntityBat['Bat'/28132649, l='MpServer', x=-75.63, y=44.79, z=94.00], EntityMobEnderman['Enderman'/28132136, l='MpServer', x=-233.41, y=37.00, z=94.34], EntityHat['unknown'/28550, l='MpServer', x=-221.00, y=34.00, z=92.50], EntityPainting['Painting'/28130951, l='MpServer', x=-105.06, y=67.50, z=157.50], EntityPainting['Painting'/28130952, l='MpServer', x=-105.06, y=67.50, z=155.50], EntityPainting['Painting'/28130953, l='MpServer', x=-109.00, y=67.00, z=159.94], EntityMobEnderman['Enderman'/28131637, l='MpServer', x=-190.34, y=39.00, z=136.13], EntityBabySkeleton['Baby Skeleton'/28131636, l='MpServer', x=-184.75, y=36.98, z=136.75], EntityHat['unknown'/423, l='MpServer', x=-144.61, y=69.32, z=106.79], EntityXPOrb['Experience Orb'/28131075, l='MpServer', x=-221.13, y=33.25, z=217.75], EntityTrail['unknown'/431, l='MpServer', x=-144.61, y=69.32, z=106.79], EntityBat['Bat'/28132382, l='MpServer', x=-87.03, y=41.82, z=44.25], EntityBabySkeleton['Baby Skeleton'/28132885, l='MpServer', x=-176.50, y=38.00, z=51.50], EntitySheep['Sheep'/28130925, l='MpServer', x=-195.50, y=67.00, z=35.50], EntitySheep['Sheep'/28130927, l='MpServer', x=-197.47, y=66.00, z=36.47], EntitySheep['Sheep'/28130926, l='MpServer', x=-196.53, y=70.00, z=36.47], EntityMobEnderman['Enderman'/28130921, l='MpServer', x=-201.09, y=33.00, z=139.34], EntityMobEnderman['Enderman'/28130920, l='MpServer', x=-196.84, y=31.00, z=138.47], EntityMobEnderman['Enderman'/28130922, l='MpServer', x=-200.69, y=33.00, z=136.75], EntityBlock['unknown'/457, l='MpServer', x=-6.75, y=26.00, z=217.25], EntityBabySkeleton['Baby Skeleton'/28130919, l='MpServer', x=-204.50, y=34.00, z=140.50], EntityItem['item.item.bone'/28130918, l='MpServer', x=-201.97, y=33.13, z=139.59], EntityBat['Bat'/28130913, l='MpServer', x=-92.75, y=45.10, z=89.25], EntityBabySkeleton['Baby Skeleton'/28130912, l='MpServer', x=-90.50, y=45.00, z=91.13], EntityChicken['Chicken'/28130914, l='MpServer', x=-210.56, y=62.45, z=72.53], EntitySheep['Sheep'/28130941, l='MpServer', x=-219.91, y=68.00, z=139.94], EntityItem['item.item.bone'/28130940, l='MpServer', x=-209.28, y=33.13, z=142.28], EntityChicken['Chicken'/28130943, l='MpServer', x=-217.56, y=62.06, z=86.56], EntitySheep['Sheep'/28130942, l='MpServer', x=-219.53, y=68.00, z=142.19], EntityBabySkeleton['Baby Skeleton'/28130937, l='MpServer', x=-194.44, y=32.00, z=156.09], EntityItem['item.item.bone'/28130936, l='MpServer', x=-193.56, y=27.13, z=145.13], EntityVillager['Villager'/28130939, l='MpServer', x=-193.31, y=76.00, z=151.69], EntityBat['Bat'/28130938, l='MpServer', x=-198.75, y=32.10, z=149.25], EntityChicken['Chicken'/28130935, l='MpServer', x=-195.53, y=46.00, z=155.41], EntityBat['Bat'/28130934, l='MpServer', x=-183.38, y=32.07, z=147.09], EntitySkeleton['Skeleton'/28130928, l='MpServer', x=-110.70, y=24.00, z=39.50], EntityBat['Bat'/28130930, l='MpServer', x=-109.81, y=24.89, z=38.56], EntityBabySkeleton['Baby Skeleton'/28130893, l='MpServer', x=-97.28, y=44.00, z=94.16], EntityZombie['Zombie'/28130892, l='MpServer', x=-198.50, y=40.37, z=95.30], EntityMobEnderman['Enderman'/28130895, l='MpServer', x=-151.91, y=50.00, z=131.53], EntityMobEnderman['Enderman'/28130894, l='MpServer', x=-152.81, y=51.00, z=129.53], EntityBabySkeleton['Baby Skeleton'/28130889, l='MpServer', x=-186.50, y=40.00, z=56.50], EntityBat['Bat'/28130891, l='MpServer', x=-125.25, y=58.10, z=123.00], EntityItem['item.item.rottenFlesh'/28130885, l='MpServer', x=-172.13, y=11.13, z=122.88], EntityBabySkeleton['Baby Skeleton'/28130884, l='MpServer', x=-164.50, y=15.00, z=122.50], EntityHat['unknown'/34793, l='MpServer', x=-210.07, y=33.81, z=142.65], EntityMobEnderman['Enderman'/28130887, l='MpServer', x=-174.75, y=39.00, z=52.72], EntityBat['Bat'/28130886, l='MpServer', x=-166.59, y=17.10, z=123.53], EntityBabySkeleton['Baby Skeleton'/28130883, l='MpServer', x=-112.66, y=31.00, z=89.56], EntityBabySkeleton['Baby Skeleton'/28130882, l='MpServer', x=-136.50, y=25.00, z=99.50], EntityItem['item.item.bone'/28130909, l='MpServer', x=-95.88, y=43.13, z=91.75], EntityMobEnderman['Enderman'/28130908, l='MpServer', x=-210.38, y=41.00, z=82.53], EntityBat['Bat'/28132447, l='MpServer', x=-188.32, y=56.11, z=128.41], EntityItem['item.item.bone'/28130910, l='MpServer', x=-95.88, y=44.13, z=90.47], EntityBabySkeleton['Baby Skeleton'/28130907, l='MpServer', x=-209.72, y=41.00, z=84.69], EntityBabySkeleton['Baby Skeleton'/28130906, l='MpServer', x=-208.38, y=42.00, z=86.31], EntityBabySkeleton['Baby Skeleton'/28130901, l='MpServer', x=-190.50, y=40.00, z=134.50], EntityBabySkeleton['Baby Skeleton'/28130900, l='MpServer', x=-191.50, y=40.00, z=134.50], EntityItem['item.item.bone'/28130903, l='MpServer', x=-185.72, y=53.13, z=132.09], EntityItem['item.item.bone'/28130897, l='MpServer', x=-200.72, y=43.13, z=98.88], EntitySkeleton['Skeleton'/25597, l='MpServer', x=-23.81, y=-107.31, z=46.35], EntityBabySkeleton['Baby Skeleton'/28130899, l='MpServer', x=-105.50, y=46.00, z=102.53], EntitySheep['Sheep'/28130898, l='MpServer', x=-203.66, y=63.00, z=111.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4448045432 bytes (4241 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6144m -Xmx6144m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D8 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (modpack.jar) 
	UCHIJA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJA	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJA	BuildCraft|Core{7.1.22} [BuildCraft] (buildcraft-7.1.22.jar) 
	UCHIJA	BuildCraft|Transport{7.1.22} [BC Transport] (buildcraft-7.1.22.jar) 
	UCHIJA	BuildCraft|Factory{7.1.22} [BC Factory] (buildcraft-7.1.22.jar) 
	UCHIJA	BuildCraft|Silicon{7.1.22} [BC Silicon] (buildcraft-7.1.22.jar) 
	UCHIJA	BuildCraft|Robotics{7.1.22} [BC Robotics] (buildcraft-7.1.22.jar) 
	UCHIJA	BuildCraft|Energy{7.1.22} [BC Energy] (buildcraft-7.1.22.jar) 
	UCHIJA	BuildCraft|Builders{7.1.22} [BC Builders] (buildcraft-7.1.22.jar) 
	UCHIJA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UCHIJA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJA	ForgeMultipart{1.2.0.347} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCHIJA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar) 
	UCHIJA	HardcoreEnderExpansion{1.8.6} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.6.jar) 
	UCHIJA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.1a2.jar) 
	UCHIJA	Forestry{4.2.16.64} [Forestry for Minecraft] (forestry_1.7.10-4.2.16.64.jar) 
	UCHIJA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
	UCHIJA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJA	DragonAPI{v18b} [DragonAPI] (DragonAPI 1.7.10 V18b.jar) 
	UCHIJA	ChromatiCraft{v18b} [ChromatiCraft] (ChromatiCraft 1.7.10 V18b.jar) 
	UCHIJA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHIJA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b197.jar) 
	UCHIJA	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UCHIJA	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
	UCHIJA	ExtraTiC{1.4.6} [ExtraTiC] (ExtraTiC-1.7.10-1.4.6.jar) 
	UCHIJA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.502.jar) 
	UCHIJA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.502.jar) 
	UCHIJA	GalaxySpace{1.1.9} [GalaxySpace] (GalaxySpace-1.1.9 STABLE.jar) 
	UCHIJA	GeoStrata{v18a} [GeoStrata] (GeoStrata 1.7.10 V18a.jar) 
	UCHIJA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJA	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCHIJA	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UCHIJA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJA	Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281.jar) 
	UCHIJA	MekanismGenerators{9.1.0} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.0.281.jar) 
	UCHIJA	MekanismTools{9.1.0} [MekanismTools] (MekanismTools-1.7.10-9.1.0.281.jar) 
	UCHIJA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJA	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) 
	UCHIJA	modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar) 
	UCHIJA	Morpheus{1.7.10-1.5.26} [Morpheus] (Morpheus-1.7.10-1.5.26.jar) 
	UCHIJA	OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
	UCHIJA	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UCHIJA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHIJA	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
	UCHIJA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UCHIJA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJA	ForgeMicroblock{1.2.0.347} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCHIJA	McMultipart{1.2.0.347} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCHIJA	aobd{2.9.2} [Another One Bites The Dust] (AOBD-2.9.2.jar) 
	UCHIJA	IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13474 Compatibility Profile Context 22.19.162.4' Renderer: 'AMD Radeon R9 200 Series'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	CoFHCore: -[1.7.10]3.1.4-329
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.2.1-172
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * Optifine is installed. This is NOT supported.
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                  * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from Railcraft_1.7.10-9.12.2.0.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon R9 200 Series GL version 4.5.13474 Compatibility Profile Context 22.19.162.4, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D8
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13474 Compatibility Profile Context 22.19.162.4
	OpenGlRenderer: AMD Radeon R9 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by ReikaKalseki** [comment]
> mods.railcraft.common.blocks.hidden.TileHidden

**Comment by TiranDirth** [comment]
Yeah, I figured as much, thought it best to let you know anyway in case my interpretation was wrong.
