### ISSUE TITLE
crash at start

### ISSUE THREAD

**Issue by marco6971** [ReikaKalseki/Reika_Mods_Issues#1681]
every time i update, add or remove some mod from my modpack at the first run i obtain this crash https://pastebin.com/uu7zvXje, after minecraft starts correctly

**Comment by marco6971** [comment]
ok... v19 out.

**Comment by marco6971** [comment]
nope, it happens again.

**Comment by ReikaKalseki** [comment]
#1493 #1257 #1280 #1238 #481
