### ISSUE TITLE
[Chromaticraft] Mana booster gamecrash

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1682]
Hi,
i posted it on the forum already:

If you place 2 mana boosters and they start working after a short time the game crashes with this crashlog. My Server shuts down after a short time after restart and in the singleplayer it crashes if i place them again.

https://pastebin.com/qMgUZALL

**Comment by ReikaKalseki** [comment]
I have been using them for multiple weeks without issue. This makes no sense.

**Comment by Kobra331** [comment]
Ok i tested some around.
It seems to be a very special bug which has to do with a producing flower (endoflame in my case) which is binded with the forest wand to a Mana booster + another mana booster whith a functional flower (loonium or clayconia in my case) under them. Something like this: https://ibb.co/gmExa6
its really hard to reproduce but if its happen the server will crash over and over again until you break some parts fast enough. Additionally this reset my Chromaticraft Progression.

**Comment by ReikaKalseki** [comment]
That still makes no sense. Mana Boosters do not interact with each other or with functional flowers.

**Comment by sfmiyuki** [comment]
Excuse me, but I can't get the point how mana booster works.
![tim 20180610132643](https://user-images.githubusercontent.com/8622253/41204400-0316516e-6cb2-11e8-9b03-0329a2dd0e47.png)

**Comment by ReikaKalseki** [comment]
I do not think it can send to pools at the same Y-level as it.

**Comment by sfmiyuki** [comment]
Sure it can't send to any pools, whatever at the same Y-level or not. 
![2018-06-13_17 38 48](https://user-images.githubusercontent.com/8622253/41379720-bdec22e0-6f30-11e8-85dd-8b9bd781d397.png)
Is it my problem to use it? Mana booster can be treated as a spreader when I bind to generating flower with wand of the forest, but this spreader do nothing after binding.

**Comment by ReikaKalseki** [comment]
Now it is below the flowers. Why did you do that?

Also, you are filling this issue with repeated and unrelated (and user error at that) discussion.

**Comment by ReikaKalseki** [comment]
Possibly fixed.

**Comment by BritishCynic** [comment]
I figured I'd post this here than a new thread. Getting a crash related to Reika.ChromatiCraft.ModInterface.TileEntityManaBooster with ChromatiCraft v20a.

https://pastebin.com/8jimpm8t

Mod List as of now:

https://pastebin.com/q8RPuchR

**Comment by ReikaKalseki** [comment]
So basically you are saying it crashes without Botania?

**Comment by BritishCynic** [comment]
That was my original hypothesis, but I was unable to recreate it in a minimalist environment with just the following mods:

DragonAPI
ChromatiCraft
CodeChickenCore
NotEnoughItems
BuildCraft
BuildCraft Compat

**Comment by ReikaKalseki** [comment]
I looked at the BuildCraftCompat code and it appears to be the case that he iterates over the entire list of block/metadata pairs, with no regard to whether some are valid. He does catch exceptions, but in the case of mod-dependent ones, the error raised is a higher level than that, and will not be caught (thus crashing the game).

This is only raised with CC + BC + BC Compat + Immibis Microblocks and NOT Botania.

I have a potential fix.

**Comment by ReikaKalseki** [comment]
With no further mentions of errors since v20, I am going to consider this fixed.
