### ISSUE TITLE
Chromaticraft V19c crashes on start

### ISSUE THREAD

**Issue by philzin** [ReikaKalseki/Reika_Mods_Issues#1684]
Not much else I can say, game just crashes after forge initialization
https://pastebin.com/G96fjpjB

configs for dragonapi and chromaticraft are default

**Comment by philzin** [comment]
Fixed by enabling backpacks module in Forestry

**Comment by ReikaKalseki** [comment]
Well that is going to be easy to fix.

**Comment by ReikaKalseki** [comment]
Done.
