### ISSUE TITLE
Turbines always form and, but then deform multiblock

### ISSUE THREAD

**Issue by Teranis** [ReikaKalseki/Reika_Mods_Issues#1685]
I buld a Turbine multiblock. At first, the parts joined and formed a multiblock. But when I started inputting steam, the multiblock will despawn. Instead, the single turbines can be seen facing the wrong way. In addition, the massage "Tile Entity Turbine @ DIMO: -12, 119, 442 [CLIENT] is thrwing class java.lang.NullPointerException on update: null []" is spammed in the chat. The lubricant pipes I build will also dejoin. I think am using the v19c Reactorcraft versio with the v19c RotaryCraft mod on a FTB InfinetyEvolved v3.0.2 server. Heres a picture showing my problem.
![turbinebug](https://user-images.githubusercontent.com/33847528/33044313-c3ac301e-ce48-11e7-9e88-b2e11f880186.PNG)
I just hope I didn't do s stupid mistake.
Thanks for the help in advance,
Teranis
@ReikaKalseki

**Comment by Kobra331** [comment]
This is a vanilla bug AFAIK and caused by the blockupdates from the steam blocks. Just place a stone behind the turbines where the steam streams out or use a steam scrubber to delete unneccessary steam blocks.

**Comment by ReikaKalseki** [comment]
That and the fact this has been on my FAQ for two years.
