### ISSUE TITLE
RayTracer not handling ExU block disabling (Chromaticraft V19c)

### ISSUE THREAD

**Issue by TheSappySamara** [ReikaKalseki/Reika_Mods_Issues#1686]
All mods except Chromaticraft were present before this issue started to occur. I've done the best I 
could to figure it out, but to no avail. I hope this is fixable because i'd love to be able to use it. :(

Hopefully it isn't anything too obvious.

(Original report was removed to save you scrolling time, and is the same as the one below, except I had Extra Utils installed at the time.)

**Comment by Turmfalke2** [comment]
First of all, please either attach the log as a file, or a use a pastebin service/gist.
NoClessdefFound for a chromaticraft internal class sounds a bit odd, could your jar file have been corrupted?  

The md5sum for ChromatiCraft 1.7.10 V19c.jar should be d3569e41c7cb35bfde0c6f36d93bf8f2

Actually, scratch that. There is an exception above about a misuse of the DragonAPI, which happens when one of the blocks added by PylonFinder is suddenly null. I think the block in question is Ethereal Glass from Extra Utilities.  Have you done anything to disable Ethereal Glass?

**Comment by TheSappySamara** [comment]
No, but ill try that right now. Thanks for the quick response! :D
(I just took out extra utils altogether)

Sorry about the report format, this is the first time I've resorted to GitHub assistance.

**Comment by TheSappySamara** [comment]
https://pastebin.com/ejky4BGE  (here's a properly done report)

We appear to still have an issue after Extra Utils was removed and a new world was generated.

**Comment by Turmfalke2** [comment]
That crash is the same one as above with ExtraUtilities:
     UCHIJAAAA   ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 

What did you remove? Could you have had 2 versions of ExtraUtilities in your mods directory?

**Comment by TheSappySamara** [comment]
I don't think so, but ill give it another look.

Edit: There is no current instance in my mods folder, so I'm not sure what happened there. Trying again in hopes of a better result.

Another edit: So now the screen is stuck on "Building terrain" and the console is stuck on [WARNING] Missing or invalid block! (). We have been here 5 minutes.

**Comment by Turmfalke2** [comment]
Try crashing it and post another log. Maybe F3+C for 5 seconds works for that.

E: Could you be running low on RAM?

**Comment by TheSappySamara** [comment]
Removing Extra Utils and remembering to add ram to my new forge profile have done the trick. Thank you for the help!

**Comment by Turmfalke2** [comment]
Well this still shouldn't happen with Extra Utils installed, could you check your extra utils config whether there is something like B:EtherealBlockEnabled=false?

**Comment by TheSappySamara** [comment]
It was disabled from the beginning, I just fully removed it because you suggested it and it was disabled, so I thought it was something beyond what the config could fix.

**Comment by Turmfalke2** [comment]
It should not be, at least at the moment DragonAPI/Chromaticraft can't handle that. So you can either play with ExtraUtils and EtherealBlocks enabled or completely without ExtraUtils.

@ReikaKalseki not sure what the best way to handle this would be, maybe just check whether the extra util blocks are null and in that case don't add them to the raytracer list? Parsing the extra util config file feels wrong.

**Comment by ReikaKalseki** [comment]
Fixed.
