### ISSUE TITLE
Graphical glitch with the alloy tank

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1687]
Sometimes the alloy tank looks like this:
![2017-11-21_20 24 10](https://user-images.githubusercontent.com/5174562/33092601-ee10c538-cefa-11e7-9c7a-8ef93a039649.png)

other times it looks like this (note in the border at the bottom):
![2017-11-21_20 24 15](https://user-images.githubusercontent.com/5174562/33092623-fc1b29ac-cefa-11e7-9b6f-8aaaa3463df9.png)

And then the really bad one when it looks like this:
![2017-11-21_20 26 57](https://user-images.githubusercontent.com/5174562/33092672-1a069ad2-cefb-11e7-9354-4f06fd772b3f.png)

I suspect at least the last one is related to one of the other blocks around me/in view, but I haven't been able to figure out which one. I am using ae2, rotarycraft and a bit of enderio/bloodmagic around it, but none of my tests managed to locate the faulty block.

**Comment by ReikaKalseki** [comment]
Fixed.
