### ISSUE TITLE
Industrial Coils accept one tick of power only.

### ISSUE THREAD

**Issue by BeardedGrue** [ReikaKalseki/Reika_Mods_Issues#169]
This has been reported by other twice now, and disregarded as an inability to read the manual.  Be assured that I have read the RC manual and extensively tested this issue.

The Steel Industrial Coil will accept power for exactly one tick, and only if it has no power stored.  If you  attach a machine to the coil, and use a lever for the redstone signal, you can drain the power from the coil.  When the signal is removed, the next power source the coil is attached to will relay exactly one tick and stop.

If you attach 4 engines w/ junction boxes, you will get 1 tick worth of energy, and it stops.  If you use different engines, you get a different amount of power depending on the power output.  It should be noted, the amount of torque has no impact on this issue.  I connected a 16:1 speed conversion to a coil, and exact same amount of power was captured before the coil refused to accept more power.  

This is a kitchen sink type pack, so identifying other mods that may be causing this issue will be difficult.  If there is further information I can provide, please let me know.  Do note though that this is not a problem with diminishing returns from constant torque.  With 0 power stored, a gasoline engine should not hit "max charge" in 1/20th of a second of play time when connected directly.

**Comment by ljfa-ag** [comment]
Hm, from look at the code: if the coil has 2^n J stored, you will need more than n^4 W power and n^3 Nm torque to charge it. So a gasoline engine will really only charge one tick.

I didn't test it and I don't know how Reika intends the numbers but for small n, n^3 and n^4 are quite a bit larger than 2^n.

**Comment by ReikaKalseki** [comment]
Intended as per v7 and triplicate.

**Comment by ljfa-ag** [comment]
Neverless this behavior seems a bit counterintuitive. One wouldn't expect that the coil be completely useless for weak engines, and probably also not that it abruptly stops charging after only one tick.

**Comment by ReikaKalseki** [comment]
It only charges for a tick if the power given is so low that any amount of stored energy pushes the requirements outside the engine's capability.
