### ISSUE TITLE
Grinder grinds down Canola even with internal tank nearly full (leading to lost lubricant)

### ISSUE THREAD

**Issue by Tyler799** [ReikaKalseki/Reika_Mods_Issues#1690]
EDIT: Rotarycraft V19C

This may not sound like a problem, but it's a massive problem and incredibly frustrating.

Let's say that I have a grinder with a single MB left in its internal tank.

It will grind canola it has, even though clearly all the lubricant produced will be wasted.

Now normally, this would only happen once, so who cares, right?

But sadly, this is not the case. Let's say I have a single grinder running at 6 megarads, constantly feeding a supply of 3 turbines via pipes from the Pressure Pipes mods.

Now, since those 3 turbines are _constantly_ consuming lubricant, the tank in the grinder is _always_ partially empty.

So if I toss in a stack of canola, it gets instantly obliterated, with more than 90% of the lubricant never actually being produced. In actuality, I really only need to toss in a piece of canola once or twice per second to keep up with the demand from the turbines. 

But because of this bs, I can't build up a backup in the grinder, so all of my canola is constantly feeding into it unnecessarily. 

I know that the grinder does produce a "random" amount of lubricant. But that amount _is_ bounded. Just have the grinder not grind canola unless it has at _least_ the minimum amount in it tank. Preferably, not unless it has its maximum possible amount, but I could see some people not liking that.

**Comment by novasolarius** [comment]
You can try using a hopper to reduce the rate at which canola seeds are inserted and ground up. It won't fix the issue but it might save you some canola. Or you could try using Practical Logistics and make a small setup to switch the engine powering the grinder off when the tank is nearly full. A solution in Rotarycraft would be nice though.

**Comment by Tyler799** [comment]
Yeah, a hopper might be an option. If it's not fast enough, an omnidirectional hopper from pneumaticraft would likely do the trick with some tweaking.

I can't "switch the engine powering the grinder off" because it's being powered directly by a turbine, providing 6 megarads after a CVT.

I should split the power more or something. Eventually. 

I'd definitely appreciate this being fixed though. Despite being labeled a "suggestion" this is clearly a bug. To just void any excess lubricant and grind when there's not enough space seems silly to me. Especially because under normal circumstances, the grinder does stop on its own accord. It's just this edge case where it becomes a problem

**Comment by ReikaKalseki** [comment]
Normally canola is so cheap and easy to produce by the million that people do not care. As is evidenced by the fact that you are the first to raise the issue in *six years*.

**Comment by Tyler799** [comment]
Yeah. It's definitely cheap enough that it doesn't matter in almost all cases. But when you have a grinder doing 8 operations per tick and you only need a tiny amount for your usage, it ends up becoming a problem very quickly. No matter how much you could possibly produce, it'll just destroy it.

**Comment by Rewyn** [comment]
A rather simple solution would be just having a buffer tank, and only run the grinder, when the buffer tank falls below a certain threshold (and stop when it fills up).

**Comment by Tyler799** [comment]
I can't "not run the grinder". The grinders power source is directly from a turbine. I can't shut it off. There's no way to AFAIK. And it does currently feed into a buffer tank. As I said, that doesn't help.

**Comment by Rewyn** [comment]
There is. There's a shaft that you can shut off with a redstone signal. It's called Clutch, if I remember right.

**Comment by redelman** [comment]
Does the clutch no longer exist? Now I havent used Rotarycraft since v14, but running the extractor directly off a turbine like that is a huge waste.  I was supplying lubricant to many more turbines than that with a single grinder running with much less power.

**Comment by Tyler799** [comment]
I had forgotten the clutch existed. I suppose I'll use that for now.

I'd still like this issue with the grinder essentially voiding tons of lubricant to be fixed at some point, but with the clutch I can work around it now.

Thanks!

**Comment by redelman** [comment]
It's really nothing more than user error. At low speeds, it stops as it is supposed to. When insanely overpowered, it works as it's supposed to and you lose a lot of lubricant. You either automate it to shut off when not needed and use a buffer tank, put up with it, or if the amount of canola you are losing is a problem, increase your canola production. Fixing this isnt really worth anybody's time, IMO.

**Comment by Braidedheadman** [comment]
> A rather simple solution would be just having a buffer tank, and only run the grinder, when the buffer tank falls below a certain threshold (and stop when it fills up).

A late reply, perhaps, but this has always been my solution in all use cases where I'm storing consumable goods. Combine your storage media with an SR-Latch logic circuit to control input/output and you're golden --- never experience shortages or overages again. Rednet controllers work very well for this purpose and have been a staple in most of my builds, although more recently I've taken to coding my own in LUA for that extra challenge.

**Comment by ReikaKalseki** [comment]
I made it wait for the average amount of space to be available.
