### ISSUE TITLE
Crash when accessing all item fabrication recipes

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1691]
hi,
I was wondering why my fabricator was drawing well over 500k kitrino, so I decided to check the list of all item fabrication recipes in NEI. This instantly crashes the game.

https://pastebin.com/zp5cfPCx

V19c
NotEnoughItems-1.7.10-1.0.5.120-universal.jar

**Comment by ReikaKalseki** [comment]
This is entirely on InvTweak's end. It is attempting to get the player inventory in a non-inventory GUI.

However, that error gives me an idea for [something totally unrelated](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1696).
