### ISSUE TITLE
Memory leak in Chroma dimension?

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1693]
hi,
First of all, holy sh** I just entered the chroma dimension for the first time and that place is nothing like anything I have seen before. Swimming through the lumen streams has something hypnotic, really impressed with what you have done here. 

However I even after reaching the end of a stream I still haven't found any structures as mentioned in the book and the game starts to  judder because the garbage collector is constantly trying to free up memory. Is the chroma expected to require that much ram? In this case it reached 6G.

**Comment by Turmfalke2** [comment]
Nevermore.. I didn't realise I was way up in the air and that I travelled like 11k blocks with the worldgen not catching up. I guess that explains everything.

**Comment by ReikaKalseki** [comment]
The structures are not reached via the lumen stream. Also, while inside one, worldgen does not run.
