### ISSUE TITLE
Crash at "finishing up" on launch.

### ISSUE THREAD

**Issue by HotelFoxtrot** [ReikaKalseki/Reika_Mods_Issues#1694]
I get [this crash](https://pastebin.com/Th9hjJUZ) on startup with 19c in a custom private pack.  The pack worked before updating with the same mods (all are on latest version except spice of life and AE2 which is on rev2):

DragonAPI (by ReikaKalseki)
RotaryCraft (by ReikaKalseki)
ReactorCraft (by ReikaKalseki)
Thaumcraft (by azanor)
Forbidden Magic (by Assassinfox)
CodeChickenCore (by chicken_bones)
Thaumic Exploration (by nekosune)
Thaumic Tinkerer (by nekosune)
Thaumic Horizons (by TheKentington)
Botania (by Vazkii)
Witchery (by Emoniph)
Blood Magic (by WayofTime)
Mantle (by mDiyo)
Tinkers Construct (by mDiyo)
Immersive Engineering (by BluSunrize)
Tinkers' Mechworks (by mDiyo)
Immersive Integration (by UnwrittenFun)
EnderCore (by tterrag1098)
Ender IO (by CrazyPants_MC)
CoFH Core (by TeamCoFH)
Thermal Foundation (by TeamCoFH)
Thermal Expansion (by TeamCoFH)
Railcraft (by CovertJaguar)
Thermal Dynamics (by TeamCoFH)
Buildcraft (by CovertJaguar)
ChromatiCraft (by ReikaKalseki)
The Twilight Forest (by Benimatic)
Mekanism Generators (by aidancbrady)
Storage Drawers (by jaquadro)
Storage Drawers: Misc Pack (by jaquadro)
Storage Drawers: Forestry Pack (by jaquadro)
Storage Drawers: Biomes O' Plenty Pack (by jaquadro)
Storage Drawers: Natura Pack (by jaquadro)
Natura (by mDiyo)
Chisel (by tterrag1098)
Pam's HarvestCraft (by MatrexsVigil)
Waila (by ProfMobius)
BiblioCraft (by JDSinclair)
NotEnoughItems (by chicken_bones)
AgriCraft (by InfinityRaider)
Carpenter's Blocks (by Syntaxial)
NEI Addons (by bdew)
NEI Integration (by tonius111)
CoFH Lib (by TeamCoFH)
Simply Jetpacks (by tonius111)
ExtraCells2 (by Destroyer7128)
AppleCore (by squeek502)
The Spice of Life (by squeek502)
BiblioCraft: BiblioWoods Natura Edition (by JDSinclair)
Another One Bites the Dust (by ganymedes01)
Buildcraft Compat (by buildcraftchildsplay)
Thaumcraft NEI Plugin (by DjGiannuzz)
Thaumic Energistics (by Nividica)
PneumaticCraft (by MineMaarten)
BiblioCraft: BiblioWoods Forestry Edition (by JDSinclair)
Waterhook (by Henry_Loenwind)
Ender IO Addons (by Henry_Loenwind)
Custom NPCs (by Noppes)
Steve's Carts 2 (by Vswe)
Mystcraft (by XCompWiz)
BiblioCraft: BiblioWoods Biomes O'Plenty Edition (by JDSinclair)
MovingWorld (by darkevilmac)
Davincis Vessels (by darkevilmac)
StacksOnStacks (by Madxmike856)
Player API (by Divisor82)
Pistronics 2 (by Letiu)
DecoCraft2 (by RazzleberryFox)
Fast Leaf Decay (by Olafskii)
FastCraft (by Player)
JourneyMap (by techbrew)
OpenModsLib (by OpenMods)
OpenBlocks (by OpenMods)
Applied Energistics 2 (by AlgorithmX2)
Mekanism (by aidancbrady)
Extra Utilities (by RWTema)
Forestry (by SirSengir)
Magic Bees (by MysteriousAges)

**Comment by Turmfalke2** [comment]
You are using Biomes O'Plenty? I can only see BiblioCraft/Storage Drawer support mods for it in your list. If you do, are you using a non default config for it? ChromatiCraft is trying to access some items from it and at least one of them is unexpected null.

**Comment by HotelFoxtrot** [comment]
I do indeed have BOP and, as I understand it, the jar file itself was edited to make some biomes amplified.  I had a look at the config files themselves and other than the ID changes that were necessary they seem to be standard.

**Comment by ReikaKalseki** [comment]
One of the internal BoP blocks is null, probably one of its decorative plants. Are those disabled (and is this done by config or jar editing)?

**Comment by HotelFoxtrot** [comment]
Looks like it must have been in the jar itself.  Updated to the most recent version of BoP and it started right up.  It's possible that the edited jar was for a version that was too old; looks like I'll have to leave the amplified version behind until I can figure out how to make the changes to the newer jar.

Thanks for the quick responses!
