### ISSUE TITLE
[Suggestion] Lumen beacon Transmitter Sound limitation

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1695]
Hi,
at first i liked the new sounds from the lumen beacon. Everytime i crafted something i heard some nice extra sounds from the beacon.
But now it is extreme annoying because i dare to use an Adjacency core and every...single...second. OMG OMG he consumed a Lumen! BOOOM Sound effect. The sound is hearable over 200 blocks away and is only scaleable down with the Master Volume. I didn't found any config entry for this. At the moment i placed 2 Sound muffler on them.

Maybe it would be better if the Sound only appears if a High amount of lumen was transferred, or with a chance of 1 percent per lay line. Or a cap: Only 1 Sound every 5-10 minutes for each color.

greets

**Comment by ReikaKalseki** [comment]
The sound was an explicit request to know when it is transferring lumens.

**Comment by Kobra331** [comment]
maybe a possibility to scale the sound down with redstone, config entry or something WITHOUT turning off the Master volume.

**Comment by ReikaKalseki** [comment]
Redstone shuts down repeaters, so that is not feasible.
