### ISSUE TITLE
Screen freezes when loading music in the dimension

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1699]
hi
When ever the game appears to load a new piece of music in the chroma dimension the screen freezes for a second or two. Could the music maybe be loaded in it's own thread?

**Comment by Kobra331** [comment]
I have the same issue. For me it freezes for more than ~20 seconds every single track.
My friend  on the same server has no freezes. Maybe it is an soundcard / mainboard issue.

**Comment by ReikaKalseki** [comment]
#1302
