### ISSUE TITLE
Write to NBT Hybrid Tank crash

### ISSUE THREAD

**Issue by zemerick** [ReikaKalseki/Reika_Mods_Issues#17]
http://pastebin.com/wp3j2esk

Only happened once on world load. Second attempt to load succeeded.

Flat world, with a simple fusion reactor. It was the second toroid on the north side, going CCW ( as seen from above. )

2 liquid pipes above it, then a capped reservoir with LN2 and used Magic Wand for infinite LN2.

The reactor was on and running when I logged off last.

Appears to be the same issue, but different block and version, as:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=6581

**Comment by frogfigther** [comment]
according to the crashlog you appear to be using v6e of reactorcraft, try updating, and see if you can replicate it. (try just reloading the world a bunch of times)

**Comment by 1Matthias** [comment]
v6e is the newest for ReactorCraft.

**Comment by ReikaKalseki** [comment]
This is a known issue that has eluded fix since 1.6.4. However, a new update to Forge may be related to it and fix it.

**Comment by zemerick** [comment]
Do you want more crash reports or logs for this, or should we wait until the forge update?

My fusion test world is getting pretty good at giving this crash:) About 2/3 of the time.

**Comment by ReikaKalseki** [comment]
Try the new Forge version and see if it works.

**Comment by zemerick** [comment]
1389?

In the middle of some other testing right now, but I'll look into it soon as I can.

**Comment by ReikaKalseki** [comment]
No rush.

**Comment by zemerick** [comment]
Bah.

I have the new forge ready to go, but before actually switching to it I wanted to verify I could still somewhat reliably get the crash. No dice. I'm crash free without making any external changes.

I redesigned my reactors coolant input, including switching from magic wand reservoirs, to proper production. ( RU -> Tess -> Tess -> Drum -> Liquid Pipe -> Toroid )

I tried creating about 50 more toroids standing by themselves, with the magic wand reservoirs, but that isn't doing it either.

Oh, 1 of the crashes before was a reservoir, and the toroids, it doesn't appear it was ever the same toroid that caused it.

**Comment by zemerick** [comment]
Well, I'm out of ideas. It's not doing it at all.

For now, cross your fingers that the new forge did fix it. I'll stay on 1291, and hope I get into a place that I can replicate it again. If so, I'll drop everything I'm doing then and update forge to try and verify whether or not it was fixed before it vanishes again:)

**Comment by ReikaKalseki** [comment]
I have not seen this since...this crash seems to do that, come back and go away for months at a time...

**Comment by Solidflip** [comment]
I believe i have the same issue:
http://pastebin.com/BmWf1Pbm

Im using forge version 1492 and the most updated versions of your mods (reactor/rotary) V9b

User placed lubricant into the reservoir and the server crashed, then upon restarting the server the same action didnt cause a crash nor throw any errors in console.

Just adding this to see if it helps you out with this sporadic issue.

**Comment by ReikaKalseki** [comment]
This is it.

Oddly, I have not seen it in well over six months now. Try with only my mods.

**Comment by Solidflip** [comment]
Ill try it out tonight and get back to you

**Comment by kolatra** [comment]
Closing due to lack of information.
