### ISSUE TITLE
Spawner Controller fails to work if player is out of range

### ISSUE THREAD

**Issue by abatewongc** [ReikaKalseki/Reika_Mods_Issues#170]
Just like it says. If you go out of the range, the spawner stops. v7f.

Screenshots:
http://imgur.com/a/8OWjJ

**Comment by ReikaKalseki** [comment]
I cannot reproduce this, and mobs are spawning up to at least their render distance. Check that Witches do not have special spawn conditions.

![](http://i.imgur.com/oMksDKZ.png)
![](http://i.imgur.com/aruoTN9.png)
![](http://i.imgur.com/Ewmhf5R.png)
