### ISSUE TITLE
Chromaticraft (v19c) gun throwing player around at random and spawning duplicate guns with every shot.

### ISSUE THREAD

**Issue by TheSappySamara** [ReikaKalseki/Reika_Mods_Issues#1703]
I can't really put this into words, but here's a GIF of the ridiculousness that just occurred: 
https://gfycat.com/gifs/detail/IgnorantAcclaimedKilldeer

I'm just going to leave this here. I don't know what is happening, or what could possibly be causing this, but I was trying out some things in creative. I tried to shoot this gun, and instead of doing anything logical, it tossed me into the air and threw dupes everywhere.

I am in creative, but I don't _think_ any of this should occur regardless. Could be wrong. 😛 

It crashed right as I stopped recording, but the report doesn't seem to do much to give answers. I'm sure you could make more sense of it than I could. 

Report:
https://pastebin.com/d7YXLABd

**Comment by ReikaKalseki** [comment]
You do not have the required progression.
