### ISSUE TITLE
Lumen essence renders incorrect in RoC Reservoir

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1705]
Booth the hole on the left and the reservoir next to it contain the same liquid (Lumen essence).
![2017-11-26_14 23 55](https://user-images.githubusercontent.com/5174562/33240382-73bdbbb0-d2b5-11e7-90e1-0a577802cb39.png)

**Comment by ReikaKalseki** [comment]
Fixed by #1728.
