### ISSUE TITLE
Void gaze not working

### ISSUE THREAD

**Issue by darthumbris** [ReikaKalseki/Reika_Mods_Issues#1707]
Hello,

Void Gaze doesn't seem to work when surrounded by blocks of underground biomes construct.
![void gaze](https://user-images.githubusercontent.com/34023742/33259237-8f3ac3b8-d35c-11e7-9a62-1c0553e280c0.png)
![void gaze 2](https://user-images.githubusercontent.com/34023742/33259253-9bdac618-d35c-11e7-843b-448a99cf1185.png)

**Comment by ReikaKalseki** [comment]
Do those blocks have special rendering?

**Comment by darthumbris** [comment]
Sorry, I just now noticed that it doesn't work for any blocks not just underground biomes constructs.

![void gaze 3](https://user-images.githubusercontent.com/34023742/33264088-778e18fe-d36c-11e7-9a76-5d885f269cb6.png)

**Comment by AssasinAsha** [comment]
You need a certain progression level before it works.
Try in a creative world with maximised progression.
