### ISSUE TITLE
[CC] Lumentree leaves stops growing on 26245000 lumen

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1709]
Hi,
the lumen tree leaves stops growing even after several hours on exactly 26245000 Lumen. At least on the enriched lumen tree. I harvested once Kijani and Kuro leaves.

edit: I tried to break the battery block and get a server crash: https://pastebin.com/8LxaUPgj

**Comment by ReikaKalseki** [comment]
The lumen tree does not grow forever.

**Comment by Kobra331** [comment]
but the leaves are not full grown. after harvesting the battery i lost all my lumen energy and ALL of them stops by that amount of lumen.

**Comment by ReikaKalseki** [comment]
> but the leaves are not full grown

Are you sure?

**Comment by Kobra331** [comment]
yes, they don't regrow to the maximum state as before v19:

https://imgur.com/a/liqh4

the first image is my entire tree, all color leaves are on the maximum grow stage except Kuro and Kijani which i harvested some days ago.

After i breaked the lumen battery and got the server crash all colors started at 1000 lumen again and stopped at 26245000 Lumen. Before i broke the battery they was fully charged(dont remember the exactly number but much more than 26245000).

i can try to kill the entire tree and rebuild them, maybe this fix it.

**Comment by ReikaKalseki** [comment]
Try that.

**Comment by Kobra331** [comment]
ok i tried that,
a complete empty enhanced tree get exactly the same problem: https://imgur.com/a/9wmki
All colors stops on that stage.

But i found a solution: break a block of the enhancing part to get the normal Lumen tree and nearly instant it grows a lot of new leaves. If the unenhanced tree is filled, add the missing block to enhance and the tree can be fully charged

**Comment by ReikaKalseki** [comment]
The enhanced tree has a far greater capacity; this is not a surprise.

**Comment by Kobra331** [comment]
Of course the enhanced tree have a greater capacity, the surprise is that the Enhanced tree can't spawn more leaves than on my last screenshot, you have to downgrade them, wait to grow and reupgrade it to get the full capacity,.

**Comment by EyeDeck** [comment]
For what it's worth, the same issue was happening for me. If you check my lumen tree on the dev server, all of its leaves are probably still at the ~26 million stage.

**Comment by ReikaKalseki** [comment]
Turns out this was a simple case of integer overflow in the "is the tree at least 95% full" logic (which was itself introduced in v19).
