### ISSUE TITLE
[DragonAPI] Direct Furnace Recipes

### ISSUE THREAD

**Issue by BritishCynic** [ReikaKalseki/Reika_Mods_Issues#1711]
I understand the reasons made for the Replacement Smelter Handling code, however, this is causing undesired functionality with the removal of several recipes of other mods, such as the Silicon Dust -> Silicon Ingot smelting recipe for GT5u, among others.

DragonAPI 19c
GregTech 5 Unofficial 05.09.32pre1
Pastebin of DragonAPI Direct Furnace Logging: https://pastebin.com/nZy5DP0S

**Comment by ReikaKalseki** [comment]
The recipe interface layer should be fully transparent; any recipes should remain unaffected.

**Comment by BritishCynic** [comment]
Is there a way to prevent these recipes from being overridden?

**Comment by ReikaKalseki** [comment]
Nothing should be getting overridden in the first place.

**Comment by BritishCynic** [comment]
Well, as soon as DragonAPI is added to the mix, it happens; once removed, the problem rectifies.

You can replicate my base testing environment as follows:

* CodeChickenCore 1.0.7.47
* DragonAPI 19c
* GregTech 5 Unofficial 5.09.32pre1
* IndustrialCraft 2 2.2.827
* Not Enough Items 1.0.5.120

**Comment by ReikaKalseki** [comment]
What exactly is happening?

**Comment by BritishCynic** [comment]
So, let's take the Silicon Dust -> Silicon Ingot recipe as an example. Before the introduction of DragonAPI into the mod ecosystem, I can place the Silicon Dust (along with some fuel) into a normal Furnace to smelt it into a Silicon Ingot.

Once DragonAPI is inserted, this is no longer possible, and the recipe has disappeared from NEI.

**Comment by ReikaKalseki** [comment]
How is this recipe added?

**Comment by draknyte1** [comment]
It's added in the same way GT adds any material recipe. https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/util/GT_ModHandler.java#L432

My brief understanding of your handler is just to rebuild the furnace recipe map. Don't see where this would be cause for issue.

**Comment by ReikaKalseki** [comment]
I do not just rebuild the map, I outright replace it with an entirely different data structure. However, the system is explicitly designed so that it behaves indistinguishably from the outside, including any modifications to its underlying map.

**Comment by ghost** [comment]
It also happens on my local instance as well, all gregtech recipes of pure dusts to ingots are removed from the game.

**Comment by psilver2001** [comment]
This was happening to me as well with gregtech 5.0.9.31 (Infitech 2u pack), and just for fun I tried downgrading dragonapi and rotarycraft to version 17c and the problem went away.  Whatever the issue is it seems to have been introduced after version 17c.  I can't find any other intermediate versions of dragonapi to try - it is a workaround at least if anyone is stuck on this.

Thank you Reika for all the hard work on these awesome unique mods.

**Comment by BritishCynic** [comment]
Well, 18b didn't have this issue, I only encountered it in 19b and 19c, but it more than likely started in 19a. Hard to say without a download link for it to test.

**Comment by ReikaKalseki** [comment]
See #1846.

**Comment by ReikaKalseki** [comment]
Fixed.
