### ISSUE TITLE
RotaryCraft - screwdriver rotating to invalid positions

### ISSUE THREAD

**Issue by LemADEC** [ReikaKalseki/Reika_Mods_Issues#1716]
As of V19c, you can use the screwdriver to rotate vanilla levers into invalid orientation, making them fall the next time you trigger name.

![image](https://user-images.githubusercontent.com/4776032/33968463-515ce51c-e068-11e7-99ad-227f68481de2.png)

**Comment by ReikaKalseki** [comment]
Turns out this is a vanilla bug, as the lever is not properly handling a call to `rotate`:
![https://i.imgur.com/XtrKivL.png](https://i.imgur.com/XtrKivL.png)
