### ISSUE TITLE
RotaryCraft - Autocrafting Unit doesn't pull/craft from chest/hopper/pump

### ISSUE THREAD

**Issue by LemADEC** [ReikaKalseki/Reika_Mods_Issues#1717]
As of V19c, Autocrafting Unit won't craft sugar cane to sugar:
![image](https://user-images.githubusercontent.com/4776032/33969441-a95e31bc-e06d-11e7-9aae-e180dd451acc.png)

On top of Autocrafting Unit, I've tried placing a chest, a Hopper, or (as on picture) a Pneumatic Item Pump, all with sugar cane in it.
Inside the unit, a simple sugar cane to sugar recipe is defined:
![image](https://user-images.githubusercontent.com/4776032/33969546-23410770-e06e-11e7-811a-b4f503801f22.png)

**Comment by Kobra331** [comment]
And i thought i was to dumb to use them.
But AFAIK you have not to pump the items in, only put a chest with the crafting materials above the table

**Comment by LemADEC** [comment]
I've tried putting a chest on top and on the side, but that didn't help.
My understanding is that the Autocrafting unit has no inventory, it pulls what's needed from inventory on top side, then push to whichever side is free.

**Comment by Kobra331** [comment]
for me it works only 1 time per mode switch.

**Comment by ReikaKalseki** [comment]
Pumps are not inventories.

**Comment by Raeffi** [comment]
I have the same issue. I put a hopper on top of the autocrafting unit, powered it and put patterns in it but it does not do anything. Not even switching mode makes it do anything.

I am on V19c too and the problem occours on a multiplayer server.

**Comment by ReikaKalseki** [comment]
Items are not pumped into the crafter; they are put into an inventory on top of it.

**Comment by LemADEC** [comment]
So it's pulling from any sides but top, then push results into top inventory?

**Comment by Raeffi** [comment]
no, input is on top and output is everywhere else, it seems to work in request mode but not in continuous mode

**Comment by ReikaKalseki** [comment]
It caches the inventory above it - and it has to be an inventory, not a item pipe, conduit, pump, or duct - and uses that as the source of ingredients. Output items are added to its own inventory and can be extracted as normal.

**Comment by Raeffi** [comment]
I am 99% sure i tested a chest on top too.

PS:
In request mode it seems to pull the items without any problems with my setup, when i set it to continous mode it doesnt do anything.

**Comment by ReikaKalseki** [comment]
Whereas I *only* use it in continuous mode.

**Comment by Kobra331** [comment]
Maybe you could show us an example setup? For me the continous mode doesn't work. Even with enough power,
Chest on top with one stack oak wood. Rotarycraft crafting pattern for workbenches in recipe mode: crafting recipe + enderIO item conduit for the output on the side of the table.

Nothing happens.

**Comment by T5UN4M1** [comment]
I have the same problem.
I have a world that was created with the last version of DNS techpack for 1.7.
After updating all mods from v15 to v19c and adding CC my autocrafting unit (used for magical crops in continuous mode) stopped working.
The sustain mode with an AE network seems to work but it has been a bit glitchy:
I had two crafting unit, one worked and another didn't, when I transferred one of the patterns from the one that was working to the one that wasn't, it started working, somehow.

**Comment by the-vindex** [comment]
Same here, can't make it work.

**Comment by fotoply** [comment]
I can replicate this issue as well using a basic chest and continuous mode. Request mode works fine for the recipes.

This is my setup: https://imgur.com/a/7cFa2

**Comment by Deloyar81** [comment]
I can confirm this issue too.

I tested it on my MP Server.

272 Mods loaded
Forge 10.13.4.1614
Dragon API V19c
Chromaticraft V19c
ElectriCraft V19b
RotaryCraft V19c
ReactorCraft V19c
Expanded Redstone V19a

I directly hooked up the AU to my ME System in continuous mode without a chest on top; if I put a pattern in it, it works, but not for long. After a period of time (sometime minutes, sometime hours) it stop working. Even a network restart by breaking the ME connection won't revive it, not until I replace a pattern in the AU.

I change my setup to a chest on the top with an Export bus, but the same issue appears.

Edit: After spending hours of testing, it seems that if no player is around for minutes, this issue appears, whether a chunkloader is in range or not. Can anyone confirm this?

**Comment by ReikaKalseki** [comment]
It is working perfectly well for me.

![https://i.imgur.com/ntKFuSH.png](https://i.imgur.com/ntKFuSH.png)
![https://i.imgur.com/Ot14nzb.png](https://i.imgur.com/Ot14nzb.png)
![https://i.imgur.com/kcdGY7Z.png](https://i.imgur.com/kcdGY7Z.png)
![https://i.imgur.com/RQt0fzO.png](https://i.imgur.com/RQt0fzO.png)

**Comment by LemADEC** [comment]
Have you tried reproducing in SMP or just dev single player ?

**Comment by ReikaKalseki** [comment]
Both.

**Comment by sfmiyuki** [comment]
I thing it's the same to you but nothing happens...v19c @ReikaKalseki 
![1](https://user-images.githubusercontent.com/8622253/40455620-d7ffad12-5ebb-11e8-8ea1-4721250ee3bd.png)
![2](https://user-images.githubusercontent.com/8622253/40455678-121569ec-5ebc-11e8-840e-ed086d8a6c9c.png)
![3](https://user-images.githubusercontent.com/8622253/40455622-d81cce60-5ebb-11e8-9d54-0eca82f14dca.png)

**Comment by ReikaKalseki** [comment]
A storage drawer block is not an inventory.

**Comment by sfmiyuki** [comment]
I replaced it with chest or hopper,  still doesn't work. And the request mode is working without any problem.
Even tried it in a new world, nothing happen, just like it's broken
![4](https://user-images.githubusercontent.com/8622253/40457533-f77b2ffa-5ec4-11e8-872a-c777c9210c2d.png)


Then I create a new instance only with roc, it works. That's very confusing. Some mods prevent AU works

**Comment by sfmiyuki** [comment]
Now I found the source, AE2 rv2 prevent it works. Can you fix it?

**Comment by ReikaKalseki** [comment]
That made me realize the problem. Fixed.
