### ISSUE TITLE
RotaryCraft - Microturbine not accepting jet fuel

### ISSUE THREAD

**Issue by LemADEC** [ReikaKalseki/Reika_Mods_Issues#1719]
As of V19c, a Microturbine will attach to the top block when no side/bottom exist.
However, when attached to top:
1- the fuel line still only connects to bottom instead of top.
2- the Microturbine doesn't accept jet fuel from any side.

![image](https://user-images.githubusercontent.com/4776032/34064015-497e9432-e1f6-11e7-8ba9-7ebc91fab93f.png)

I propose to allow jet fuel feeding from top when Microturbine is attached to top. It's more consistent and allow a more compact setup with Pulse jet furnace for example.

**Comment by ReikaKalseki** [comment]
Fixed.
![https://i.imgur.com/txfZg8G.png](https://i.imgur.com/txfZg8G.png)
