### ISSUE TITLE
HSLA Steel Jetpack Unrepairable

### ISSUE THREAD

**Issue by madolinn** [ReikaKalseki/Reika_Mods_Issues#172]
The Jetpacks are missing 

```
@Override
public boolean getIsRepairable(ItemStack tool, ItemStack item) {
...
}
```

So they have no valid repair recipe using the anvil, and since they're not tools they can't be grindstoned. Basic tools and armor do have them, however.

**Comment by ReikaKalseki** [comment]
Fixed.
