### ISSUE TITLE
Blocks Deleting Snow?

### ISSUE THREAD

**Issue by adlwar137** [ReikaKalseki/Reika_Mods_Issues#1721]
Whenever I place a block on snow from Reika's mods it deletes the snow and places it in the snow's place
![ezgif-4-49bc6058d1](https://user-images.githubusercontent.com/26043937/34073205-64fcfcc8-e262-11e7-88c1-4c0d531a9208.gif)

**Comment by ReikaKalseki** [comment]
This might just be the oldest bug ever reported; it goes all the way back to **1.2.5**, from some of the very oldest code in DragonAPI, added something like *six* years ago. (Snow blocks, not snow *layers*, were specified as 'soft', i.e. replaceable).
