### ISSUE TITLE
Cannot craft Portal rift - Indefinite time remaining?

### ISSUE THREAD

**Issue by bokeustermans** [ReikaKalseki/Reika_Mods_Issues#1722]
I just finished gathering and crafting all the required materials to create the portal rift blocks.
Placed them all on the altar, all runes available.
Altar allows the crafting to start, however, when hovering over the altar while it is 'crafting' the symbol still shows the orange light indicating it needs more lumens (though it is full) or needs to be started.

Left this for about 15-20 minutes to see if maybe it was a visual bug, but seems to be an actual issue, lightning and explosions happening but no end to the craft at all.

I have completed all progress required and only need other worlds (mysterious relics and glowing towers irrelevant, but incomplete as well)

It also seems to be spamming the same sound very quickly in succession.

I've stopped the craft and started it again, rebooted client and server and also destroyed table, set back up and placed all items again, to no avail.

**Comment by bokeustermans** [comment]
Screenshot showing icon and lumens in altar - https://imgur.com/a/soQBf

Lumen tree is connected with more than 4 mil of each lumen type.

**Comment by ReikaKalseki** [comment]
How much energy is actually in the table (use debug overlay or NBT edit)?

**Comment by bokeustermans** [comment]
I added an image to the album

https://imgur.com/a/soQBf

I have tried to craft with lumens since but nothing has allowed me to finish the craft

Edit/update:

The crafting now works, but the graph with lumens show 15/16 types as so full they are out of my screen bounds.
My lumen tree is now also fully charged when it was 25% of the way mostly earlier, and I do not have power crystals on most

**Comment by ReikaKalseki** [comment]
All of those values are absurdly large. What happened?

**Comment by ReikaKalseki** [comment]
So...

**Comment by bokeustermans** [comment]
Sorry, own mistake. Please disregard, turns out I had line of sight issue with Portokali which I missed until I tried tocraft the Focal points ...
