### ISSUE TITLE
[Mod Interaction] Thaumic Horizon Ethereal Shard + Chromaticraft Elemental Mastery Server Crash.

### ISSUE THREAD

**Issue by TsumiHokiro** [ReikaKalseki/Reika_Mods_Issues#1725]
Thaumic Horizon has a Node-like Block called Ethereal Shard which stores aspects but does not regen. When trying to right click it with my Elemental Manipulator (I do have Elemental Mastery) it gives a NullPointerException: Ticking Memory Connection Server Crash as is displayed in more details in the [crash report](https://gist.github.com/TsumiHokiro/8867dd0480955ba3dd53820749fdf63e).

**Comment by ReikaKalseki** [comment]
It tried adding it to the crystal network like it would a normal node. I can blacklist it if I know the block type/ID.

**Comment by TsumiHokiro** [comment]
Block name is: ThaumicHorizons:synthNode, no meta (0). I assume this is what you mean by block type/ID?

**Comment by ReikaKalseki** [comment]
Yes.

**Comment by ReikaKalseki** [comment]
Done.
