### ISSUE TITLE
Electricraft ores not showing up in NEI searches

### ISSUE THREAD

**Issue by arceus179** [ReikaKalseki/Reika_Mods_Issues#1727]
Any of the electricraft ores, such as Nickel or Aluminum do not seem to register in NEI. When I search it using the box, it can neither find it using the gold outlined box mode, nor is it visible in the block menu. I have electricraft installed on the infinity evolved modpack so that might be an issue. When looking through the logs I see no issue that pertains to said ores. Current version is latest, 19c

**Comment by ReikaKalseki** [comment]
Fixed.
