### ISSUE TITLE
Lumen Essence does not render correctly in RoC Filling Station [no color blend]

### ISSUE THREAD

**Issue by TsumiHokiro** [ReikaKalseki/Reika_Mods_Issues#1728]
https://imgur.com/UQHsq91
https://imgur.com/NI2iaUd
Both the Filling Station and the Decorative Tank have Lumen Essence.

**Comment by arceus179** [comment]
This is a dupe of 1705.

**Comment by ReikaKalseki** [comment]
Fixed. In reservoirs and pipes as well.
