### ISSUE TITLE
Chromaticraft Chromic Lexicon display issues

### ISSUE THREAD

**Issue by Saereth** [ReikaKalseki/Reika_Mods_Issues#173]
A player on our server is having an issue seeing the entire contents of his Lexicon. We had him try various gui scale settings and it made no difference. We are on v7e chromaticraft. I can look at his book and see everything, when he looks at it however the information is missing. I have two screenshots here, one that he took when looking at it, and one that I took when he handed me his book. Very strange.

His view:
http://i.imgur.com/m2PmoSh.png

My View of his book:
http://i.imgur.com/IU6T4cf.png

(Also I realize in my SS I'm on the crafting tab and he's not on his, but its the same result whichever tab I vew it on)

**Comment by Saereth** [comment]
It looks like the issue resolved on its own today for him, no idea how to reproduce it, which I know is terribly useless heh. If we are able to recreate under controlled circumstance I'll let you know what we were able to find.

**Comment by ReikaKalseki** [comment]
Until then, closed because I remember fixing this half a year ago.
