### ISSUE TITLE
[RoC] DecoTank Issues

### ISSUE THREAD

**Issue by TsumiHokiro** [ReikaKalseki/Reika_Mods_Issues#1730]
1) DecoTank, of clear glass, will depending on the slot it is occupying have a different texture (Lighter) [[Screen 1](https://imgur.com/CsXILZ5)] (Both the upper row and the one highligthed have Decotanks)
1.1) It may not have a texture at all if upgraded with Obsidian [Screen 2](https://imgur.com/HPHwPCa) (Placing the cursor beside it and it shows the texture).
2) DecoTank when "upgraded" with either Obsidian or Glowstone will not fill up with liquid unless it's first been placed in the world.

**Comment by ReikaKalseki** [comment]
This is not happening for me; it is likely another mod not cleaning up after itself during rendering some item.

That said, I have put in some code that might help, but if not, there is nothing more I can do.

![https://i.imgur.com/XCb0dKM.png](https://i.imgur.com/XCb0dKM.png)
