### ISSUE TITLE
Can't craft ME item distributor / void cell / possibly other AE2 related things

### ISSUE THREAD

**Issue by T5UN4M1** [ReikaKalseki/Reika_Mods_Issues#1731]
I hope this isn't a mistake on my end but if that's the case I am very sorry.
I've triple checked that the recipes are correct and don't require any runes.

![2017-12-26_21 57 15](https://user-images.githubusercontent.com/12467635/34364995-c51e8906-ea8b-11e7-8a91-f25b6e0fe46b.png)

![2017-12-26_22 05 17](https://user-images.githubusercontent.com/12467635/34364996-c54a3bd2-ea8b-11e7-84a9-c116021e436c.png)

Trying to activate the table with the wand produces the "wrong" sound.

Using latest versions of CC and AE2 (V19c & rv3 beta 6 respectively)

**Comment by ReikaKalseki** [comment]
I have crafted those things many times, including in v19. Are you using a modified version of AE? Have you swapped the positions of processors? Do you have a texture pack changing processor names/textures with each other?

**Comment by T5UN4M1** [comment]
I'm so sorry and confused... It was worse than swapping processors positions, turns out I was using aluminium ingots... But I don't understand how this is possible, because my aluminium has an "ugly" 16x16 texture while iron has 32x32 ... It's like my aluminium ingots stole iron ingots texture ... While it was unnoticeable yesterday, it was very obvious this morning. (I didn't remove the components from the casting table between yesterday and today)
