### ISSUE TITLE
[CC] crash on start if Applied Energistics2 installed

### ISSUE THREAD

**Issue by nuclear123** [ReikaKalseki/Reika_Mods_Issues#1732]
if i delete CC game work
if i delete AE2 game work
if both CC and AE2 installed game crash on start
version of CC v19c
version of AE2 rv3-beta-6
version of Forge 10.13.4.1614
use MultiMC to play 1.7.10
crash report https://pastebin.com/uRAE2a1W

sorry for my bad english

**Comment by ReikaKalseki** [comment]
#1683 #1681 #1493 #1257 #1280 #1238 #481
