### ISSUE TITLE
Luminous Cliffs biome size and distribution issue

### ISSUE THREAD

**Issue by Ieldra2** [ReikaKalseki/Reika_Mods_Issues#1733]
Both biome size and distribution appear to be out of the desirable ranges too often. 

As for size, the "smallest" "Luminous Cliffs" biome I found was about 5 times the typical size of other biomes, the largest took over a continent and spanned three JourneyMap pages zoomed out as far as possible. 

As for distribution, using "findbiome" and exploring I get anything from one instance at short distances (<2000m) that turned out to be that continent-sized monster mentioned above, to about 12 instances clustered at a very far distance (>16000m) and covering a relatively small area.

This was found in an environment with only your mods and NEI, AntiIDConflict, XRay-47, JourneyMap and FMP installed. World type was "default", and I did not change any biome weights. 

To replicate the continent-sized biome, generate a world with the seed 1188539007 and fly north to around -1700 or -2000

**Comment by ReikaKalseki** [comment]
What you are seeing is intentional. The biome is both far rarer and far larger than most (using Mega Taiga or Mesa type behavior, rather than standard weighted biome distributor).
