### ISSUE TITLE
Help! | Fusion reactor refuses to work

### ISSUE THREAD

**Issue by greengameplayer** [ReikaKalseki/Reika_Mods_Issues#1735]
https://1drv.ms/f/s!Anhj5SXHa5LVqUW-D2arSJjrGciV

No matter what, I cannot get it to work. I've included some of my logs and my world.

(please don't tell me that I didn't submit an issue right. I KNOW. I am a total noob at GitHub. {I just made my account today})

**Comment by arceus179** [comment]
The rings arn't in the correct positioning. That's why the plasma is spilling out.

**Comment by greengameplayer** [comment]
No, they are all right. They all say 1b on Next.

**Comment by redelman** [comment]
One of the pictures makes it look like a single magnet is not placed correctly. But the plasma is spilling out well before that, so that isn't the cause. If you watched Reika's old reactor build video then look for something newer as that is quite out of date. You're missing stuff. :)

**Comment by Aivech** [comment]
Being cryptic about this helps exactly no one. This is a tech mod, not internet archaeology.

@greengameplayer You need to supply the electromagnet rings with liquid nitrogen. Look up SentinalHMC's fusion reactor build video to see how to do it properly.

**Comment by ReikaKalseki** [comment]
I suspect the intent is to avoid providing sufficient information to enable simple imitation, only enough to provoke further research.
