### ISSUE TITLE
Rotarycraft Lubricant hose and Liquid pipe renders liquid very strangely.

### ISSUE THREAD

**Issue by arceus179** [ReikaKalseki/Reika_Mods_Issues#1736]
https://imgur.com/a/UH8Fl
https://imgur.com/a/Ug4vl

This seems to happen consistently even after restart. I am not completely sure if it's optifine, because I remember using optifine with another modpack and this working just fine. It seems this only happens near machines, as the lines look fine just traveling across the land.

**Comment by ReikaKalseki** [comment]
Your second screenshot is of some other game. Also see #343.

**Comment by arceus179** [comment]
It seems i messed up my link. I'll edit it and get back to you.

Edit: Alright I checked it out and some carpenters stairs that were decorating my building was the issue. Thank you.
