### ISSUE TITLE
[Chromaticraft] Village structure not triggering completion of "A...less than honorable attempt"

### ISSUE THREAD

**Issue by TetraNomic** [ReikaKalseki/Reika_Mods_Issues#1737]
Entering the failed casting room no longer gives this bit of progression for some reason. To confirm that this was indeed a problem with ChromatiCraft, I tested this on a fresh 1.7.10 install with the latest versions of DragonAPI and ChromatiCraft.

![2018-01-03_00 05 13](https://user-images.githubusercontent.com/35055019/34509680-ed018aec-f01a-11e7-8550-8f7913f9f803.png)

**Comment by arceus179** [comment]
The progression pings when you look into the shielding stone chest underneath the crafting bench.
