### ISSUE TITLE
Chromaticraft has a recipe conflict with itself?

### ISSUE THREAD

**Issue by leytilera** [ReikaKalseki/Reika_Mods_Issues#1738]
Crashlog: https://pastebin.com/5FunnRiq

**Comment by ReikaKalseki** [comment]
This does not happen for me; what modded armor sets are in the game?

**Comment by leytilera** [comment]
modded armor sets, hmm, many. thermal foundation armoers, modular powersuit, modular armour, enderio, rotarycraft, ic2 and many more.(328 mods)

**Comment by ReikaKalseki** [comment]
Try removing mods that add armor to determine which it is.

**Comment by leytilera** [comment]
Ok, i fixt this error. i can start minecraft, but when i create a world i get this: https://pastebin.com/HC7Yv8WR

**Comment by ReikaKalseki** [comment]
You have something else invalid, probably a stack of null registered to the ore dictionary. Ztones would be the first thing I would check.

**Comment by leytilera** [comment]
techguns adds a stack of null to the ore dict but i tried it only with techguns and chromaticraft and there is no crash, so the error must be somwhere else

**Comment by ReikaKalseki** [comment]
Try removing mods.
