### ISSUE TITLE
ReC: Setting "Generate X Ore Even If Other Mods Do" to "false" does not work even though CondensedOres already generates that ore.

### ISSUE THREAD

**Issue by Ieldra2** [ReikaKalseki/Reika_Mods_Issues#1739]
As the title says. ReactorCraft will always generate its ores, even if another mod (CondensedOres in this case) already generates the same ore and the aforementioned option is set to "false". Also, there is no option for fluorite, which is most likely to clutter up the underground with its several versions. 

I've used the ore discretization option to get the kind of generation I want instead, but that wouldn't help in cases where generation of a specific ore is to be moved off-dimension, or to be restricted by biome.

**Comment by ReikaKalseki** [comment]
By "other mods" it means other mods adding an ore of the same type. It has no way of knowing that other mods are generating its own blocks.

That said, there should be a native way for CondensedOres to override generation.
