### ISSUE TITLE
Industrial Coil isnt usable anymore since v7

### ISSUE THREAD

**Issue by Maupfel** [ReikaKalseki/Reika_Mods_Issues#174]
I have played Rotarycraft and noticed that the Industrial Coil isnt usable anymore because when given a reasonable energy input it just stores several MJ. and I used a Gas Turbine, the most powerful engine of the mod. Reika, please patch this
![2015-07-31_00 50 02](https://cloud.githubusercontent.com/assets/5236739/8997128/375e5e84-371e-11e5-95d7-37348d454f38.png)
![2015-07-31_00 50 09](https://cloud.githubusercontent.com/assets/5236739/8997131/42c3c6b0-371e-11e5-949c-a2c2f92bdbcc.png)

**Comment by ReikaKalseki** [comment]
Quadruplicate and read the changelog or the handbook.
