### ISSUE TITLE
CromatiCraft v19c crash on world load

### ISSUE THREAD

**Issue by RealShadowFury** [ReikaKalseki/Reika_Mods_Issues#1740]
I have an issue with chromaticraft when loading the world.

I get a "The game crashed whilst exception in server tick loop
Error: java.lang.VerifyError: Expecting a stackmap frame at branch target 259" crash when loading the world.

the mods I have installed are:
chromaticraft V19c
CodeChickenCore-17.10-1.0.7.47
DragonAPI v19c
ElectriCraft V19B
ForgeMultipart-1.7.10-1.2.0.345-universal
Reactorcraft V19c
Rotarycraft V19c

crash pastebin: https://pastebin.com/SVEf3WAC

**Comment by ReikaKalseki** [comment]
#1437 #1566 #1583
