### ISSUE TITLE
[suggestion] Electricraft transformer for endgame

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1741]
Hi,
it would be nice to have a (lossless) Transformer with infinite limits for current.
I tried a nitrogen and fin cooled tranformer but i can't transform the power of 2 Auroral batteries due to the heat generation. I have to use an induction motor, some bedrock gearboxes and an induction generator only to provide the Induction Motors with the right voltage. But even for low voltage i would use the gearbox setup, because the decision between a loss of 25% + cooling for a simple 16:1 transformation vs 100% efficiency is easy.
A new "super conducting"/bedrock transformator is only to save space and makes it easier to hide cables between 2 walls for some machines which are used at home and not as a part of a factory.

**Comment by ReikaKalseki** [comment]
> I have to use an induction motor, some bedrock gearboxes and an induction generator only to provide the Induction Motors with the right voltage.

As is the intent. I deliberately designed transformers not to supplant gearboxes.
