### ISSUE TITLE
Liquid nitrogen over-production bug

### ISSUE THREAD

**Issue by fmike11** [ReikaKalseki/Reika_Mods_Issues#1743]
Found this kind of by accident. So i'm playing a modpack with v19c of rotary/reactorcraft chromaticraft, and was putting ~ 10 gigawatts of power into a refrigeration unit. 131072 rads at the source, and was originally torquing it down to 512 rads and making ~ 2-4 buckets of liquid nitrogen per operation. The set up was induction motor -> 16x gear box ->  - > 16x gear box -> refrigeration unit.

 I switched out the second 16x gear box to an 8x and it produced 700,000 buckets of liquid nitrogen per operation. I repeated this a few times with different gearings and could only reproduce it at 1024 rads. I started a creative world with an industrial coil and tried the same set up and repeated the bug... but only at 1024 rads and high torques (i don't know the exact torque at which it happens, but 88knm seems to do it reliably. 
![2018-01-11_19 06 11](https://user-images.githubusercontent.com/27322400/34853650-e9dbf566-f702-11e7-8eca-9b3de473f928.png)
![2018-01-11_19 04 15](https://user-images.githubusercontent.com/27322400/34853658-f3749ace-f702-11e7-85dd-aade28592ae6.png)
![2018-01-11_19 04 06](https://user-images.githubusercontent.com/27322400/34853662-fe587136-f702-11e7-9012-53df59c68050.png)

little update -> it's at exactly 10 gigawatts where it happens. any less, 2 buckets. any higher torquing at 10 gigawatts, 2 buckets. But at 10+ gigawatts at 1024 rads, it'll create somwhere ~ 700k buckets per operation

**Comment by ReikaKalseki** [comment]
This is not happening for me, and the math does not work out anyways.

![https://i.imgur.com/eJ8TwKU.png](https://i.imgur.com/eJ8TwKU.png)
