### ISSUE TITLE
Cannot connect shafts through Nether Portals

### ISSUE THREAD

**Issue by raelik** [ReikaKalseki/Reika_Mods_Issues#1745]
This may be related to #1519, and it may also be ignorance on my part, but I can't seem to get shafts to connect through Nether portals.  Do the portals have to be located at the exact same coordinates like Mystcraft portals?  If so, that seems odd since the Nether portals self-connect with the Nether coordinate x8 math.

**Comment by Kobra331** [comment]
the nether portals have to be synced. And AFAIK you can only link nether to nether portals and mystcraft to mystcraft portal. but both on exakt the same coordinates. I had the same problem some years ago on minecraft 1.6
on 1.7 i use the world rifts from chromaticraft

**Comment by raelik** [comment]
@Kobra331 What do you mean by synced? Do you mean they have to be on the exact same coords, or that you need to "manually" link them by building the first one in the overworld at x,y,z coords divisible by 8 (say 464,70,464) and then destroying the auto-created portal and manually re-creating the Nether side at x/8,z/8 with the same y coord (i.e. 58,70,58)?  If so, that would explain my difficulty, but that's easy enough to do.

**Comment by ReikaKalseki** [comment]
> @Kobra331 What do you mean by synced? Do you mean they have to be on the exact same coords, or that you need to "manually" link them by building the first one in the overworld at x,y,z coords divisible by 8 (say 464,70,464) and then destroying the auto-created portal and manually re-creating the Nether side at x/8,z/8 with the same y coord (i.e. 58,70,58)? If so, that would explain my difficulty, but that's easy enough to do.

All of that. Also both sides need to be chunkloaded.

**Comment by raelik** [comment]
@ReikaKalseki Thanks, I'll give this a shot when I get home!

**Comment by raelik** [comment]
Looks good, though I notice you can only run one shaft through the portal. You can put as many on the input side as you want, but you can only get power from one of them on the other side.

**Comment by ReikaKalseki** [comment]
> You can put as many on the input side as you want, but you can only get power from one of them on the other side.

Show me.

**Comment by raelik** [comment]
Here's the input side:
![input](https://gist.githubusercontent.com/raelik/d8c7b45ef929e975d718d7401678aee0/raw/e76b331780fe7e055ce2c0e6f644a46133c0f943/2018-01-13_09.36.57.png)

All three of those shafts are putting out 8GW.

And on the output side:
![output](https://gist.githubusercontent.com/raelik/d8c7b45ef929e975d718d7401678aee0/raw/e76b331780fe7e055ce2c0e6f644a46133c0f943/2018-01-13_09.38.26.png)

Only the far shaft is receiving power.  The middle shaft (the one with no dyno) is also receiving no power.
I get around this by simply junctioning them all together.  Oddly, when I do that, I send the power to the center block on the top row, but it is still the far block that receives the power.

**Comment by ReikaKalseki** [comment]
The odd portal size might be throwing it off, though I doubt it.

That said, the system is not supposed to care about multiple shafts in one portal - they do not interact.

**Comment by raelik** [comment]
It's not a big deal, it was really a better idea to send all of that power through one shaft anyway, because on the Nether side I needed to send it all the way to the ceiling (breaking tons of bedrock), and one long run of superconducting wire made more sense anyway.  I just used resistors to split off the power that wasn't for the bedrock breaker.
