### ISSUE TITLE
[Chromaticraft] Strong Energy Boosters useless with Thermal Expansion Dynamos

### ISSUE THREAD

**Issue by I-Enderlord-I** [ReikaKalseki/Reika_Mods_Issues#1746]
Because Thermal Expansion Dynamos can only output 2 x their maximum production, using Energy Booster Tier 4 to 7 only increases their efficiency up to the point where they produce energy out of nothing:

![xxx](https://user-images.githubusercontent.com/22118126/34908475-01caaa92-f888-11e7-8eac-486176a89ca3.png)

(infinite RF with Energy Booster Tier 7; I have some Cryo-Stabilised-Fluxducts running into a RF Storage Battery from Electricraft next to it and no Lava input)

I think it would be possible to use the Method `es.setMaxTransfer((this.getBaseGeneration(te) + gen) * 2)` above this [line](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/TileEntity/AOE/Effect/TileEntityEnergyIncrease.java#L395)  to fix this issue.

I don't know how to set it back to the default value incase the Energy Booster is broken, but I'm sure you will figure something out.

**Comment by ReikaKalseki** [comment]
I am not sure leaving behind the increased I/O is really a big deal, since it has no gameplay effect whatsoever. I did put in a bit of code to try to reset it, though.
