### ISSUE TITLE
[BORKEN] Latest of Latestest Forge not working with 19c

### ISSUE THREAD

**Issue by theArhar** [ReikaKalseki/Reika_Mods_Issues#1747]
20:58:43 | DragonAPI | The mod DragonAPI is expecting signature 32:F5:F4:E8:44:C0:EA:C8:6F:46:8A:8E:F3:05:05:7B:6F:90:0F:78 for source DragonAPI 1.7.10 V19c.jar, however there is no signature matching that description
-- | -- | --
20:58:45 | RotaryCraft | The mod RotaryCraft is expecting signature 32:F5:F4:E8:44:C0:EA:C8:6F:46:8A:8E:F3:05:05:7B:6F:90:0F:78 for source RotaryCraft 1.7.10 V19c.jar, however there is no signature matching that description
20:58:45 | ReactorCraft | The mod ReactorCraft is expecting signature 32:F5:F4:E8:44:C0:EA:C8:6F:46:8A:8E:F3:05:05:7B:6F:90:0F:78 for source ReactorCraft 1.7.10 V19c.jar, however there is no signature matching that description

Forge 1.7.10 10.13.4.1614
DragonAPI, RotaryCraft, ReactorCraft V19c

**Comment by theArhar** [comment]
Probably Optifine causing it!
Clean install does not have this error

**Comment by ReikaKalseki** [comment]
That message has nothing to do with any error that would prevent the game from loading, and I use my mods with the latest Forge and Optifine with no issue.
