### ISSUE TITLE
ReactorCraft doesn't work with ComputerCraft

### ISSUE THREAD

**Issue by t0msk** [ReikaKalseki/Reika_Mods_Issues#1749]
Hello,
I am very big fan of your ReactorCraft mod, I really like it, but I try to connect it with ComputerCraft and it is not working, could you help me? Or is it supported?

I coded this:
https://i.imgur.com/7ZqI1TB.jpg

And this is a result:
https://i.imgur.com/NpRf2uf.jpg

Thank you very much

I hope I will see this mod in 1.10+ ^^

**Comment by ReikaKalseki** [comment]
I do not use ComputerCraft with mods enough to know the proper terminology or process, but I can tell you that RC/ReC/ElC/CC machines are not connected with adapters/peripherals/etc but instead directly, as they are components in and of themselves.

**Comment by t0msk** [comment]
And do you know how can I connect computer with a reactor (which command)?

**Comment by ReikaKalseki** [comment]
No, because I use OpenComputers.

**Comment by OvermindDL1** [comment]
Really, don't use ComputerCraft @t0msk , it is *very* poorly designed as a gameplay mod, OpenComputers is far far superior in every way.

**Comment by I-Enderlord-I** [comment]
Please upload an image of your setup.

**Comment by t0msk** [comment]
@ReikaKalseki I switched to OpenComputers and it is awesome, but I have one problem and it is a max supported components.

Let's say that my reactor is about 27x27 blocks and it is about 729 components.. (in future I plan to expand reactor to height)

**Comment by OvermindDL1** [comment]
@t0msk That is when you set up server banks in OpenComputers, just like you would in real life.  :-)

I've not tested though, can't you control the whole reactor from only one part?

**Comment by t0msk** [comment]
I can control reactor only by using control rods.. but problem is that OpenComputer gets all blocks (components) from reactor, so I see in components neutron reflector too.

I can have for example 2 computers, one for getting fuel rods temperature and another for controlling rods, but I don't know how, because my computer wants to get all blocks (like components) from reactor (do you understand me?  @:D )

**Comment by ReikaKalseki** [comment]
> I have one problem and it is a max supported components.

If all else fails, those limits are configurable.

**Comment by I-Enderlord-I** [comment]
That's why I still use ComputerCraft. It's a lot easier to use. Of course it isn't "designed as a gameplay mod", because it shouldn't be.

**Comment by OvermindDL1** [comment]
> That's why I still use ComputerCraft. It's a lot easier to use. Of course it isn't "designed as a gameplay mod", because it shouldn't be.

Not just that, ComputerCraft can easily kill a server, is less functional, less balanced, less capable, etc...

OpenComputers can *do* more than ComputerCraft, a lot more.

**Comment by t0msk** [comment]
OK and if I use OpenComputer to monitor a reactor, is possible to monitor only some blocks? For example I don't know to have **Steam Line**, **Steam Grate**, **Neutron Reflector** in components.

**Comment by OvermindDL1** [comment]
As for the many components, old issue, see (and @ReikaKalseki should see):  https://github.com/MightyPirates/OpenComputers/issues/910

**Comment by I-Enderlord-I** [comment]
> Not just that, ComputerCraft can easily kill a server

It won't if you use it right. It works good for singleplayer worlds.

> OpenComputers can do more than ComputerCraft, a lot more.

What exactly? Which features can not be realized in ComputerCraft?
As far as I know OC just makes things like creating networks a lot easier. On the other side ComputerCraft is cheaper and doesn't need different componets to get a Computer running.
You said that ComputerCraft isn't as balanced as OC and that's true. But I don't see the need for expansive and huge structures when setting up small monitoring systems.

**Comment by OvermindDL1** [comment]
> It won't if you use it right. It works good for singleplayer worlds.

`if you use it right`, which you absolutely cannot trust someone on a server to do.

> What exactly? Which features can not be realized in ComputerCraft?
As far as I know OC just makes things like creating networks a lot easier. 

Especially networks, those are some features that I've used excessively.

But other than those, server racks and how they communicate, nanites (oh I love nanites), 3D Printer, holograms (though I think CC has an addon to do this, but it was missing some features as I recalled), touch-screen interfaces, Tablets, etc...

> On the other side ComputerCraft is cheaper and doesn't need different componets to get a Computer running.

Which makes it more of a cheat mod than a game mod, and if someone is playing Reika's mods they really should not be cheating (that is more of a ThermalEtc... mods style of gameplay).

**Comment by I-Enderlord-I** [comment]
> if you use it right, which you absolutely cannot trust someone on a server to do.

I already said that I'm only speaking of singleplayer.

> What exactly? Which features **can not be realized** in ComputerCraft?
> As far as I know OC just makes things like creating networks a lot easier.

> Especially networks, those are some features that I've used excessively.

I know it is easier to setup networks with OC. I want to know what isn't possible with CompoterCraft. You are telling me what is easier with OC.

> Which makes it more of a cheat mod than a game mod, and if someone is playing Reika's mods they really should not be cheating.

You know how the Extractor works, right? When using Reikas mods it's so easy to get all parts of OC Computers. Because of that, there isn't much difference is that case.

No, it's not a cheat mod. It's just cheap. It doesn't give you items or replaces machines. It's purpose is to be used for automation and monitoring and lua programs like games. That's not cheating!

**Comment by OvermindDL1** [comment]
> I know it is easier to setup networks with OC. I want to know what isn't possible with CompoterCraft. You are telling me what is easier with OC.

See this:
> But other than those, server racks and how they communicate, nanites (oh I love nanites), 3D Printer, holograms (though I think CC has an addon to do this, but it was missing some features as I recalled), touch-screen interfaces, Tablets, etc...

And I cannot actually run Reika's mod, his abysmal model code kills my framerate to unplayable <1fps areas in any area that get to be more than a dozen or two complex (in terms of models) machines.  There's another issue around here somewhere that speaks of that.

> No, it's not a cheat mod. It's just cheap. It doesn't give you items or replaces machines. It's purpose is to be used for automation and monitoring and lua programs like games. That's not cheating!

It allows automation of the rank of what a player is generally required for on specific tasks with an absolutely trivial cost and no real upkeep, that is effectively being able to duplicate yourself to perform repetitive tasks that you yourself would be unwilling to sit there and do, so yes, it is game-breaking (I.E. cheaty).  A mod that does something like give you free diamonds is above the rank of cheat and onto the rank of creative mode, those are distinct levels.  Something that breaks gameplay in a way that trivializes work but has no ongoing cost and/or replacement is a cheat (along the lines of, say, an aim-bot in FPS's in terms of breaking of gameplay).

And of course there is nothing wrong with that for a given person, however Reika does not make his mods with that in mind and as such will not perform anything that allows them to be used as such (though generally does nothing against it either), thus if using Reika's mods you generally have to assume a certain style of play.

**Comment by t0msk** [comment]
@OvermindDL1 So that too many components aren't already fixed somehow?

**Comment by OvermindDL1** [comment]
> @OvermindDL1 So that too many components aren't already fixed somehow?

Reika needs to not have every single one of his TE's act like cables...  >.>

I thought that was fixed like years ago, but apparently not?

**Comment by ReikaKalseki** [comment]
As has been discussed repeatedly, in a large RC setup, and in basically any ReC reactor there is no space to run a cable to the desired machine, and that means the only option is to be able to connect *through* my machines.

**Comment by t0msk** [comment]
@ReikaKalseki Yes I understand what do you mean.. but you could make something like "filter", I mean that some blocks like **Steam Line**, **Neutron Reflector** etc.. should not count like component, because they are useless to count like component.

**Comment by ReikaKalseki** [comment]
Steam lines *should* only count as conduits.

**Comment by Braidedheadman** [comment]
> It allows automation of the rank of what a player is generally required for on specific tasks with an absolutely trivial cost and no real upkeep, that is effectively being able to duplicate yourself to perform repetitive tasks that you yourself would be unwilling to sit there and do, so yes, it is game-breaking (I.E. cheaty). A mod that does something like give you free diamonds is above the rank of cheat and onto the rank of creative mode, those are distinct levels. Something that breaks gameplay in a way that trivializes work but has no ongoing cost and/or replacement is a cheat (along the lines of, say, an aim-bot in FPS's in terms of breaking of gameplay).

I lurk these fora more often than not, but I just love comments like this.

A "cheap" computercraft terminal is meaningless to the person who doesn't know how to, or doesn't want to, learn how to write code. They can craft one and it will sit there and do precisely, and exactly, nothing. Crafting the terminal is not where the cost in using that mod ought to be determined. It's price has always been accounted for in player acumen; it's power (or lack thereof) in direct proportion to the player's knowledge and skill.

But I suppose that, in your view, taking the time to code a Computercraft program in LUA doesn't count as "effort" and trivializes "work" now? 

I also suppose that, in your view, forcing players to craft more gubbins in order to assemble all of the many parts in order to make all of the things constitutes "balance" rather than busywork and needless tedium --- all of that on top of the time and effort it takes to manually write code? Oh, wait... 

I forgot, writing code trivializes work and effort. My bad.

May as well throw in the towel now, Reika, your efforts are all for naught according to this guy! =\

**Comment by ReikaKalseki** [comment]
> It's price has always been accounted for in player acumen; it's power (or lack thereof) in direct proportion to the player's knowledge and skill.

People always just download prewritten programs. Hell, ComputerCraft has a built-in feature to do exactly that, to alleviate that very requirement.

**Comment by Braidedheadman** [comment]
Indeed, but down this avenue lies the garden path of collective punishment, which I feel mods like Open Computers endorses. If the argument being made is something akin to, "This mod is too powerful, let us make it cost more in resources and tedium in order to use as compensation," should this not ring all too familiar? 

At the end of the day, those increased requirements won't stop those who wish to cheapen their experience by downloading prewritten LUA scripts (or by watching Youtube / reading wikis in order to copy other people's optimal builds) from demonstrating their stupidity and laziness when their projects ultimately end in catastrophic failure.

**Comment by ReikaKalseki** [comment]
The point is that a powerful device needs *something* to balance it, and ComputerCraft effectively has nothing. OpenComputers has *something*, whether or not it is the ideal approach.

**Comment by Braidedheadman** [comment]
I just think that the 6 hours I spent today coding a new program for an idea that I had constitutes that _something_ and I rather don't need to be told that I need to spend yet more time grinding out gubbins for parts. Nor do I wish to concern myself with the additional logistics of feeding it a constant power supply, trivial though it may seem to some; trivial matters add up quickly, especially in larger modpacks, however; and whatever else they've come up with which to strangulate Open Computers.

Everyone is going to have their own preferred playstyle, naturally. I just happen to fundamentally disagree with the premise upon which this criticism of Computercraft is based. My time is valuable enough and is a fair trade in kind, in my opinion, insofar as "balance" in a an open sandbox world is concerned.

At any rate, I do not wish to derail this thread any further. To each his own.

**Comment by traso56** [comment]
probably not a good place to comment but ty for telly me i don't have to connect the cable directly to the reactor CPU, i was redesigning the whole thing to let the cable connect lol, can  you tell me a good OC tutorial? i'm very new to the mod

**Comment by ReikaKalseki** [comment]
Reflectors no longer act as full components.
