### ISSUE TITLE
Crash on start of breeder reactor.

### ISSUE THREAD

**Issue by anishin** [ReikaKalseki/Reika_Mods_Issues#175]
Title says it all.
Crash report: http://pastebin.com/9zDb4nW7

**Comment by ReikaKalseki** [comment]
This should be impossible. Does it happen reliably? If so, try an older Forge.

**Comment by anishin** [comment]
I'm using Forge 1448 (recommended build). I'm afraid I can't use older version, because it's incompatible with other mods in my modpack.
This problem occurs not immediately after the start. It occurs when any Sodium Heater generates first 100 mB of Hot Molten Sodium. And it happens reliably.

**Comment by ReikaKalseki** [comment]
NBTTagCompound.getInteger, in the version of the code I have, can only throw an NPE if either its internal hashmap is null. Something likely changed the way NBT tags work.

> I'm afraid I can't use older version, because it's incompatible with other mods in my modpack.

Remove mods and try an older version.

**Comment by ReikaKalseki** [comment]
Anything?

**Comment by ReikaKalseki** [comment]
Hello?

**Comment by anishin** [comment]
Sorry for long waiting. Problem in other mods in my modpack. Some mods had problem with entity syncing. After update all is fixed.
