### ISSUE TITLE
issue with dragonAPI

### ISSUE THREAD

**Issue by coltoncrafter** [ReikaKalseki/Reika_Mods_Issues#1751]
i have attempted to use reactorcraft along with dragon api and rotarycraft respectively.
every time i start the game it does not work. the startup document displays this error message:

The mod DragonAPI is expecting signature 32:F5:F4:E8:44:C0:EA:C8:6F:46:8A:8E:F3:05:05:7B:6F:90:0F:78 for source DragonAPI 1.7.10 V19c.jar, however there is no signature matching that description

i have the LATEST version for forge (10-13-4-1614) not the recommended version i have tried reinstalling forge. 

PLEASE READ WHOLE THING I HAVE HAD ROBOTIC LIKE RESPONSES FROM OTHER MOD DEVS BEFORE

please help me with this so i can set up reactorcraft.

**Comment by ReikaKalseki** [comment]
Perhaps those responses are due to you posting random messages insisting they are errors - when they are not - and then failing to provide any actual useful information, almost verbatim from every list of "what NOT to say to get help".

**Comment by coltoncrafter** [comment]
i have never posted this before... and like i said the game does not start.

**Comment by coltoncrafter** [comment]
what "useful information" do you need?

**Comment by coltoncrafter** [comment]
please don't be mean... i'm not trying to offend you. i'm not insisting they are errors... i'm just trying to understand why i cant use your amazing looking mod.

**Comment by arceus179** [comment]
I can help you. Post a link to a pastebin that contains your crash log please. That's the first step.

**Comment by ReikaKalseki** [comment]
> what "useful information" do you need?

The actual crash log would be a good place to start.

**Comment by coltoncrafter** [comment]
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1643098/latest.log)

is this what you need?

**Comment by coltoncrafter** [comment]
i have no idea what a "pastebin" is.

**Comment by coltoncrafter** [comment]
NVM i found what it was here 

https://pastebin.com/s4LVTQ83

**Comment by OvermindDL1** [comment]
I'm not really seeing any errors there...  What error is the game itself giving you when you start it up?

**Comment by OvermindDL1** [comment]
Although the log does look cut off, is that really all of it?

**Comment by coltoncrafter** [comment]
yes it is that's the whole log . it just shows a white screen and then it stops working if i click anywhere or do anything while its loading. i usually have to manually close it with the task manager.

**Comment by OvermindDL1** [comment]
> yes it is that's the whole log . it just shows a white screen and then it stops working if i click anywhere or do anything while its loading. i usually have to manually close it with the task manager.

Interesting, that says to me that either your audio drivers are broken (depending on what dragonapi does in that injection) or dragonapi has a bug...

**Comment by OvermindDL1** [comment]
And based on:
https://github.com/ReikaKalseki/DragonAPI/blob/2da0e4d0876a8177435130af274be63076f6dd14/Libraries/IO/ReikaSoundHelper.java#L273-L287

It appears that neither should be the cause...  There really is not more log?  Or a core dump from java?  Or an error specific mod file?

**Comment by coltoncrafter** [comment]
listen. im not a coder or anything. i have no idea what a core dump is or a error specific mod file either.

also what are audio drivers?

**Comment by redelman** [comment]
You're only giving Minecraft 1GB of RAM. Give it at least 4 and see what happens.

**Comment by coltoncrafter** [comment]
redelman?

how do you do that?

**Comment by redelman** [comment]
Assuming you're using the new minecraft launcher, you'd go to the launch options tab, select whatever pack you are using, and set at least -Xmx to a value similar to what's highlighted in the screenshot below.

![image](https://user-images.githubusercontent.com/73338/35107456-95a187a2-fc36-11e7-85d1-eac9304e2383.png)

**Comment by coltoncrafter** [comment]
i only have the game directory and resolution switches

**Comment by coltoncrafter** [comment]
nvm i had to turn on advanced

**Comment by coltoncrafter** [comment]
there is no "server" in the  JMV arguments

**Comment by redelman** [comment]
Pay attention man. Just the highlighted parts. That's all you need to add/change in your JVM arguments.

**Comment by coltoncrafter** [comment]
i turned the XMX value to four and dose not work.

there is no XMS 

i have a computer with 8 gigabites.

**Comment by redelman** [comment]
Now pastebin the latest log please.

**Comment by coltoncrafter** [comment]
https://pastebin.com/B9CV3jT7

**Comment by coltoncrafter** [comment]
hello?

**Comment by redelman** [comment]
The log still shows only 1GB RAM allocated. Aside from that it does look fairly complete. fml-client-latest.log would provide more info than latest.log, though.

**Comment by coltoncrafter** [comment]
im done

**Comment by coltoncrafter** [comment]
with this crap

**Comment by ReikaKalseki** [comment]
And we are done with you. Good riddance.
