### ISSUE TITLE
i'm sorry... i just need help

### ISSUE THREAD

**Issue by coltoncrafter** [ReikaKalseki/Reika_Mods_Issues#1753]
i'm not a coder... i'm not a modder... i'm thirteen.

i'm just trying to figure this out.

i don't know about any technical things like the word allocated or data dumps.

i am just frustrated because i don't understand what i'm doing wrong.

**Comment by coltoncrafter** [comment]
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1644309/latest.log)

here is the crash report if you need it...

**Comment by Rewyn** [comment]
Alright, I'll bite. I'm bored anyways, so let's see if I'll have more success. And if we can do this before Reika closes it again. :p
First off: That's not a crash report. In your minecraft folder (where the "logs", "mods" etc folders are located), is there a folder called crashlog? If not, in the folder the latest.log file is in, are there any other files?
As for allocating more memory (which means allowing the game to use more of your computers resources); You found the "Launch Options" tab in the minecraft launcher, right? Just post a screenshot of that, similar to the picture in the old issue.

**Comment by coltoncrafter** [comment]
while it doesn't crash... i doesn't load and i have to manually crash it.

**Comment by coltoncrafter** [comment]
![screenshot 2](https://user-images.githubusercontent.com/35539125/35120942-556dae08-fc5f-11e7-83d9-3456368528bc.png)

**Comment by Rewyn** [comment]
change the first part "-Xmx1G" to "-Xmx4G"

**Comment by coltoncrafter** [comment]
it didn't work.

**Comment by coltoncrafter** [comment]
i gotta leave school soon. at 3:30

**Comment by coltoncrafter** [comment]
the loading bar stops when initialing mods phase one dragonapi

**Comment by Rewyn** [comment]
Those don't help anyone. Logfiles do.

**Comment by ReikaKalseki** [comment]
Also, what are you doing running MC or on here when you are at school?

**Comment by coltoncrafter** [comment]
what are logfiles?

**Comment by coltoncrafter** [comment]
i'm in special ed.

**Comment by coltoncrafter** [comment]
https://pastebin.com/s4LVTQ83 here is a pastebin of the mc startup log found in the logs folder

**Comment by coltoncrafter** [comment]
OMG

**Comment by coltoncrafter** [comment]
i dont know what  i did!

it started!

**Comment by coltoncrafter** [comment]
wait... its not working again...

**Comment by coltoncrafter** [comment]
i found something out. it just takes a really long time to load.

**Comment by coltoncrafter** [comment]
i'm sorry for wasting your time

**Comment by OvermindDL1** [comment]
You've not played, say, the Infitech2/3 pack have you, it can take a good 20 minutes to load...  ^.^;

**Comment by redelman** [comment]
It'll take even longer, and then still fail, when you've not bothered to listen at all and are continuously trying to load modded minecraft with only 1GB RAM assigned to it.

**Comment by coltoncrafter** [comment]
I'M GIVING IT FOUR NOW YOU RETARD!
STOP WHINING!

**Comment by redelman** [comment]
That wasn't what the logs showed before, but regardless, you can go away now.

**Comment by ReikaKalseki** [comment]
There is a certain irony in you calling people "retard" given your aforementioned description of your educational situation. And that is where your interactions here will end.
