### ISSUE TITLE
Feature Suggestion: Allow gating behind the worktable instead of the blast furnace

### ISSUE THREAD

**Issue by Zekromaster** [ReikaKalseki/Reika_Mods_Issues#1754]
This is a bit of a naive suggestion but I was thinking about how HSLA Steel is not usable in modpacks as the sole type of steel if you're gating RotaryCraft behind other mods - the only gating option is changing the blast furnace material.

A good solution to this would be to be able to replace the bricks in the worktable. This would allow the use of RotaryCraft components in recipes, while still being able to move RC to mid-game, and thus make standardization easier for modpackers.

**Comment by ReikaKalseki** [comment]
So you are basically asking for the ability to specify gating materials on the Worktable? I am open to that, though replacing *all* of the brick is a problem due to the fact the block's texture is primarily bricks.

**Comment by Rewyn** [comment]
There's also the issue with the config, that allows you to make machines in regular crafting tables (which would be required for crafting through ae2 for example).

**Comment by Zekromaster** [comment]
@ReikaKalseki Maybe replacing the stone slabs instead? Or one of the HSLA ingots? 

@Rewyn Using those two together is at your risk, if you're gating RC machines behind other mods then automating their crafting being more difficult would be justifiable. Or just gating the Blast Furnace and not unifying the steel could also remain an option. Compromises are needed here.

**Comment by Rewyn** [comment]
I wasn't saying I was against it, just that that's something to keep in mind when gating the Worktable instead of the Blast Furnace.
Also, I can see the reports coming "I made the worktable require xyz, but people can just use a regular crafting table! Why are your mods so stupid?! No, I don't use default configs, so what? Wait, you're making me use my brain when changing configs?!"...

**Comment by ReikaKalseki** [comment]
> Also, I can see the reports coming "I made the worktable require xyz, but people can just use a regular crafting table! Why are your mods so stupid?! No, I don't use default configs, so what? Wait, you're making me use my brain when changing configs?!"...

Agreed, though I can lock the two configs together - i.e. disallow gating (with a hard crash if necessary) if the gating would be meaningless.

**Comment by ReikaKalseki** [comment]
Done.
