### ISSUE TITLE
Electrified magnetic containment pipe melting

### ISSUE THREAD

**Issue by InitHello** [ReikaKalseki/Reika_Mods_Issues#176]
I've tested this in a creative world running 1.7.10 with ReactorCraft and RotaryCraft (as well as DragonAPI, of course) installed, versions are all V7f.

When the preheater starts generating fusion plasma, the first few magnetic containment pipes almost always turn into lava. If I remove the pipes from the preheater unit to the top of the multiblock, and wait until the preheater has a decent amount of plasma before replacing the pipes, this seems to happen less often. Something with low amounts of plasma overriding the check for magnetization, perhaps?

Additionally, the VDG is running off a creative coil set to 64kN at 64k rads/second.

**Comment by ReikaKalseki** [comment]
This seems unlikely. Are you sure all the pipes are sufficiently magnetized, and that nothing is shorting them? Also, one VDG is nowhere near sufficient for a whole reactor.

**Comment by InitHello** [comment]
Oh no, one per plasma injector:
![Screenshot](http://i.imgur.com/3iO7p3k.png)

The toroid magnets have one each at NE, NW, SW, SE, and contain the plasma nicely that way. As you can also see, the magnetic pipes are containing the plasma fine now that I replaced them a few times.

Although your question about short circuiting does make me wonder if grass blocks would be sufficient to sporadically cause containment failure.

**Comment by InitHello** [comment]
I'll be damned, without the grass around the VDG, the pipe didn't melt. NOTABUG WONTFIX at your leisure.

**Comment by ReikaKalseki** [comment]
Grass blocks are not conductive, and should not count...

**Comment by InitHello** [comment]
Aha. It was, as you probably guessed, user error. I managed to replicate it by standing next to the pipe where it exits the preheater multiblock. Maybe it's shorting through my brain or something.

**Comment by Duckfan77** [comment]
Contact with a player will short the pipes.

**Comment by davebx** [comment]
And shorting my brain makes me not realize that until 7 hours later. My bad.

**Comment by blackendsuns** [comment]
i am also having this issue, except the pipes are melting inside the plasma injector multiblock, the plasma balls are fluctuating just enough that they end up touching the first 1 or 2 pipe blocks as they pass through, and cause them to melt? this seems like a code issue, any help? please!!

**Comment by ReikaKalseki** [comment]
No, not enough charge.

**Comment by TomeWyrm** [comment]
@blackendsuns Magnetic Containment Pipe require more charge from a VDG than you probably think. I'd give you an idea, but I can't remember and don't feel like waiting a quarter hour for my instance to boot up so I can test and give you actual numbers.

Also make sure the charge isn't jumping off of the pipe anywhere, and no water is touching the pipe.
