### ISSUE TITLE
[Feature Suggestion] Kaowool

### ISSUE THREAD

**Issue by kenish25** [ReikaKalseki/Reika_Mods_Issues#1762]
In Rotarycraft the steam engine requires fire below it to work, but fire burns wool which you need to silence the machine rendering the steam engine effectively unsilenceable. So can we have some sort of high temperature insulation that won't burn?

**Comment by redelman** [comment]
It's been forever since I tried, but does TE rockwool not work?

**Comment by Kobra331** [comment]
cover the wool with stones or use extra utilities sound muffler.

**Comment by ReikaKalseki** [comment]
Rockwool works, and this is not enough of a feature to warrant the time required to implement a new dedicated block.

**Comment by TomeWyrm** [comment]
Fire can only spawn in an air block. Put non-flammable non-air blocks around your wool on all faces.

Microparts are very cheap and can do this *nearly* invisibly. Though honestly, simply covering them with stone should work quite well. If you're coating a thing in wool for sound an extra layer of blocks is rarely a deterrent.
