### ISSUE TITLE
fusion reactor killing my servers

### ISSUE THREAD

**Issue by floven1** [ReikaKalseki/Reika_Mods_Issues#1763]
I cannot seem to get a server to behave once I build the tokamak and fire it up, every time i try, the server (while not appearing to lag at all, even /forge tps returned everything normal when I could actually run the dang command and get a response) runs for a bit, but as soon as I log out, I cannot log back in, looking at the performance, the server actually maxes out for a few minutes, then levels out at about 14% - 25% processor and 2.5 gigs ram, the strangest thing about all of this is I can build and operate the tokamak just fine in single-player on the same computer, this issue has persisted across OS's (the first box I tried this on was running Ubuntu, the second, windows 10, same result) and seems to be independent of everything I have tested

here is my original forum post, just in case it has more info that I have forgotten to post here:
http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mods-discussion/2884453-reactorcraft-tokamak-breaking-my-servers

here are my configs, if that helps, sorry about the lack of hard data.
[GeoStrata.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1658627/GeoStrata.zip)

I really hope that this is just something obvious about setting up a server that I have missed somehow, because if this cannot be fixed, it ruins a lot of my future plans

**Comment by Kobra331** [comment]
I build 3 fusion reactors on 3 different servers and all works fine, only some framedrops on my client. Windows 7 and 6 GB RAM allocated. Did you chunkloaded the entire Reactor? AFAIK if you log out and it is not chunkloaded the neutrons could make massive lags and problems.

**Comment by redelman** [comment]
I've not played with Reika's mods since v14, and I've always built the fusion reactor in a different dimension meant only for it, but I've never had this problem. I've seen plenty of others have it though, and in all cases the fusion reactor wasn't 100% chunkloaded, which causes huge buildups of neutrons and all kinds of lag problems. But I've always seen huge tps drops reported with this, too.

**Comment by floven1** [comment]
thought it might be something I was missing, I will test this and report back

**Comment by floven1** [comment]
looking good so far,  it let me log back in a minute after leaving, going to leave it running overnight and see what happens

**Comment by floven1** [comment]
alright, it works, after running all night, here's the proof, the second reactor I just world-edited in for kicks and to see what would happen, I was surprised at how smoothly it went, only had to use the wand on the liquid nitrogen reservoirs to make them infinite again
![2018-01-25_09 29 52](https://user-images.githubusercontent.com/19882085/35399828-6f8ff004-01b2-11e8-90d8-2a55aa422941.png)

**Comment by floven1** [comment]
the only thing I have to comment on now is that all of my glass-lidded reservoirs retained the infinite flag, but the ones that didn't have a glass lid on them (the liquid nitrogen reservoirs) needed to be right clicked with the wand again, maybe something to look into? or not, it is a minor rare-circumstance bug.

**Comment by ReikaKalseki** [comment]
I am surprised that copying worked on the blocks at all; I would have expected a crash.
