### ISSUE TITLE
DragonAPI v19 completely disables minetweaker 

### ISSUE THREAD

**Issue by innfamy** [ReikaKalseki/Reika_Mods_Issues#1765]
Does there are any way to prevent DragonAPI doing it? Minetweaker doesn't even change anything on any reikas mods, but it completely disables all the scripts. Minetweaker used to work fine as v18.
I can provide console log's if needed but Im pretty sure dragonAPI does that on purpose, I just I want to know if there is a way to disable it.

**Comment by ReikaKalseki** [comment]
DragonAPI does *not* do that, and dozens of packs with both, including my own, prove it.

**Comment by innfamy** [comment]
Sorry but I didn't want to make a false accusation, I not a programmer so I don't know much, but my problem happened after updating dragonAPI.
After doing the command _/mt reload_, a lot of DragonAPI errors showed up on the console, which didn't showed on the previous version, it says there's an error on the scripts, but they worked just fine on the previous version, if the error has no to do with DragonAPI then you can close the issue again
Here is the console log after usind _/mt reload_
I apologize if there's nothing to do with your mod, but minetweaker doesn't support 1.7 anymore and if its nothing to do with DragonAPI i'll just have to give up

**Comment by ReikaKalseki** [comment]
You did not actually link anything, but I can tell you that any errors you might have are due to errors in the zs scripts themselves.

If DragonAPI is showing up in the console, it might be because it is trying to process the recipes you added, which are somehow invalid.

**Comment by innfamy** [comment]
https://gist.github.com/innfamy/236fec0928ee44c7b0ce90c727a1ed38

I'ts what you said indeed, but they used to work before updating, I must have screwed something on the update. I didn't added any recipe, they are from a modpack. Sorry for bothering you.

**Comment by innfamy** [comment]
I've downgraded to v18 of DragonAPI and everything is working fine now. No changes to the scripts

**Comment by ReikaKalseki** [comment]
Show me the minetweaker script.

**Comment by innfamy** [comment]
https://gist.github.com/innfamy/245782db02443f26d050c5a618b3ec75

**Comment by redelman** [comment]
That's not the minetweaker script. And nobody wants to go through a 14,000 line log file. Especially when there doesn't appear to be anything related to Reika's mods in it.

**Comment by innfamy** [comment]
Ok, but which minetweaker script? There is a lot of them for different mods on the folder.

**Comment by OvermindDL1** [comment]
@innfamy You can put them all up at once on a single page at gist.github.com.

**Comment by innfamy** [comment]
https://gist.github.com/innfamy/724264a3812cb979213a00edd8fe24b2 There's all the scripts. I didn't make any of them.
I'm don't believe it's a DragonAPI problem anymore, I just gave up honestly. For some reason it works with v18 but not v19.
