### ISSUE TITLE
Infinite RF with battery

### ISSUE THREAD

**Issue by traso56** [ReikaKalseki/Reika_Mods_Issues#1767]
https://i.imgur.com/LUY3cRy.gifv

**Comment by ReikaKalseki** [comment]
Does it persist after a save/reload?

**Comment by traso56** [comment]
no

**Comment by kutschkem** [comment]
Possibly related to #1413

**Comment by ReikaKalseki** [comment]
This is actually the fault of the cables, not the battery; I cannot reproduce it when using other conduits.

**Comment by ReikaKalseki** [comment]
Hopefully fixed.
