### ISSUE TITLE
Crashed by getting block type in world when launching the GC rocket

### ISSUE THREAD

**Issue by FuYang001** [ReikaKalseki/Reika_Mods_Issues#1768]
Crash report:
https://pastebin.com/8nZX0zbQ

It seems like a chunk generation problem happened when I was launching the Galacticraft rocket. After I deleted your mods I launched the rocket again and game didn't crash. I'm not sure is this your mod's problem but I really don't know how to solve this...or should I report this to GC's author?

DragonAPI V19c
RotaryCraft V19c
ReactorCraft V19c
Galacticraft 1.7-3.0.12.503
GalaxySpace-1.1.9

**Comment by vrnRaptor** [comment]
I also get crash at launch rocket tier 3. When using version v15a everything was fine.

**Comment by ReikaKalseki** [comment]
#1734
