### ISSUE TITLE
[CC] Excavation star deletes blocks

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1769]
Hi,

I used the excavation star to harvest the Thermal evaporation blocks from Mekanism, but it deletes them entirely. I dont know if this is on mekanisms end or on yours because i have not found other blocks with this issue.

**Comment by ReikaKalseki** [comment]
They probably have a special drops system, especially if the blocks are used for multiple machines. I doubt RC or CC machines would work either. But that is not what the Excavation star is for anyways.
