### ISSUE TITLE
Crash with dragonapi/chromaticraft and Project e

### ISSUE THREAD

**Issue by eletrolitico** [ReikaKalseki/Reika_Mods_Issues#177]
the new project e update (1.7.10-PE1.8.0) changed its api and crashes with this report: http://paste.ee/p/0PBgU

**Comment by ReikaKalseki** [comment]
Duplicate and already fixed.

**Comment by TomeWyrm** [comment]
For V8, I assume? Because they VERY recently re-updated the API

https://github.com/sinkillerj/ProjectE/commit/63cfa93d9badaae562091faf41578b44c3bc30cc

**Comment by eletrolitico** [comment]
That's what I meant
