### ISSUE TITLE
[CC] Knowledge Entaglement Pedestal is confusing/requires too much progression to be useful

### ISSUE THREAD

**Issue by thePalindrome** [ReikaKalseki/Reika_Mods_Issues#1770]
The KEP itself requires a silk-touched zambaru crystal and a diamond, meaning that it is likely a player will have the chromatic enchanter before crafting the KEP itself.

The Structure requires a Multichromic rune, which requires the Casting Temple to craft, and cannot be achieved later.

This ultimately means that I am far beyond the progression and pages of the other players, meaning that I cannot link with them.

From the comments at https://www.reddit.com/r/feedthebeast/comments/7g0ov5/how_does_the_chromaticraft_knowledge_entanglement/, the "the same unlocks in the book" are required, which I'm not sure if it refers to the pages in the lexicon, or the progression "achievements".

My assumption of the KEP's purpose is to quickly boost the progression of friends, marking them as "worthy" so that they can use some of the constructs I've built, but it seems that the only way it's useful is if it was pre-placed for a new player.

If I'm misunderstanding this entirely, then this bug is still useful for "KEP lexicon entry is very confusing"

**Comment by thePalindrome** [comment]
As a follow up, after some cheats to put us at the same point, I bound us using the KEP (assuming the method of doing so is to use the manipulator on it while the other person stands on it, it made a sound and my client saw him float, but nothing else happened) and it didn't give him the progression nor any fragments I picked up afterwards.

**Comment by ReikaKalseki** [comment]
The system does not sync fragments, but those can be copied anyways.

**Comment by thePalindrome** [comment]
Aye, given how easy they are to duplicate (although it does take a bit of time to sift through what they already have) I wasn't expecting that. I'm more confused as to why the progression didn't sync. It is entirely possible that it didn't link properly (as I said, on my client, my friend jumped into the air, but my friend didn't move on his screen)

**Comment by ReikaKalseki** [comment]
Check both of your player NBT; it will mention linking, if any.

**Comment by thePalindrome** [comment]
Scanning our playerdata, the only mention to CC is the ProgressionCache folder, and there's no mention of linking. If you like I can make a git build and test against that (the pack I'm playing is a mess of brokenness, the game will crash weirdly often, and I had to manually update your mods (Revolution 3))

**Comment by ReikaKalseki** [comment]
I replaced the multichromic rune with a glowstone block, and expanded the lexicon entry.
