### ISSUE TITLE
[CC] Crystal tank Comparability still broken

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1772]
Hi,
i use the Chromaticraft Crystal tanks for lubricant, Nitrogen, mekanism Deuterium and Tritium but it seems that none of them update the comparator signal if not replaced or changed the comparing redstone signal.

**Comment by ReikaKalseki** [comment]
That is because comparators only update with a block update, and spamming updates like that would wreck your framerate. Use a computer mod instead.

**Comment by Kobra331** [comment]
But why the comparator works with barrels and other tanks really fine? This issue is only with Chromaticraft Crystal tanks.

**Comment by TomeWyrm** [comment]
Because the other tanks use block updates. If the Crystal Tank did this your game would be nearly unplayable near any Crystal Tank.

**Comment by Kobra331** [comment]
ok thank you and thank you for your advice with the computermod i will try that. Could it work without framedrops if only the main block of the crystal tank use block updates?

**Comment by TomeWyrm** [comment]
Theoretically, yes. But not only are there ways around the issue (ComputerCraft/OpenComputers directly, and the use of a buffer tank to detect fullness more indirectly), I'd wager that there's good performance reasons why even making the controller issue semi-constant block updates would be bad.

**Comment by ReikaKalseki** [comment]
That would not help at all; even one block update triggers a chunk rerender; 218 of them still only trigger one rerender (if all in the same tick).

**Comment by OvermindDL1** [comment]
> That would not help at all; even one block update triggers a chunk rerender; 218 of them still only trigger one rerender (if all in the same tick).

On the function that marks a block dirty you can mark whether it is a 'state' change, a 'graphical' change, or both (it defaults to both unless you specify otherwise, and it has a few others related to networking).  State change without graphical will cause things like the comparator to update without causing a chunk re-render.  And likewise, stating a graphical change occurred forces a chunk re-render without updating surrounding block states.

However, I'd not say really work on updating comparators, they are programmed *so* very poorly in vanilla (they can cause a surprising amount of lag) that they should never be used and rather something like OC or whatever else should.

Plus a player can also cause block updates on the comparator in a variety of ways anyway if they want to have it be a 'polling' system (which is even more inefficient, but whatever).

**Comment by Kobra331** [comment]
Ok thank you for your answers, advices amd time. I will use buffer tanks now, maybe there is in the future a chromaticraft crystaltank reader or something like the turbine dynamometer. Its just nice to automate the production/consumption of some fluids based on the amount inside the tanks.

**Comment by TomeWyrm** [comment]
Yes it is, and that can easily be done with OpenComputers or ComputerCraft right now. And I do actually mean easy. You only require a basic knowledge of scripting to do it yourself, and it's a simple enough task that you could learn the bare minimum to do it in an hour or two of directed learning. The resources are out there, and with a program that simple? You could probably ask for someone to help you. I've asked favors of friends that could code before so I could use a computer mod for some build or another.

I can't remember the exact coding required but the gist is to check the level of the tank every so often and output a redstone signal based on that. An if statement, reading a peripheral, a timer function, and a redstone output. Tiny program.

OpenComputers
https://oc.cil.li/index.php?/topic/1205-tank-display-program/
https://oc.cil.li/index.php?/forum/37-tutorials/
https://oc.cil.li/index.php?/forum/42-requests/


ComputerCraft
http://www.computercraft.info/forums2/index.php?/topic/15689-dead-simple-railcraft-tank-monitoring/
http://www.computercraft.info/forums2/index.php?/forum/13-tutorials/
http://www.computercraft.info/forums2/index.php?/forum/14-ask-a-pro/

**Comment by Kobra331** [comment]
Thank you for your tips, at first i tried the computercraft tankmon. it seems to work only with Railcraft tanks. But even this is pretty cool.
Maybe i try something with openComputers next time.
