### ISSUE TITLE
[Rotarycraft] Woodcutter not harvesting TiC Slimy tree blocks

### ISSUE THREAD

**Issue by Braidedheadman** [ReikaKalseki/Reika_Mods_Issues#1774]
Rather than harvesting the congealed slime block, the woodcutter appears to be (randomly?) converting cut slime blocks into single green slime balls. It would seem random for the fact that the conversion is not the expected 4:1 balls per block ratio (as per the crafting/uncrafting recipe) or even, for that matter, a 1:1 ball per block harvested. After an hour or more, and several trees harvested in the meantime, the chest contains only 4 slime balls total.

First tree harvested, adding just two slime balls (from a 5 block tree trunk):
![2018-02-08_00 18 57](https://user-images.githubusercontent.com/13001993/35962937-08842770-0c68-11e8-8688-a958f390df56.png)

Second tree harvested, adding one slime ball (from a 4 block tree trunk):
![2018-02-08_00 30 47](https://user-images.githubusercontent.com/13001993/35962938-08b859f0-0c68-11e8-8763-902fd5b3db84.png)

The setup:
![2018-02-08_00 35 41](https://user-images.githubusercontent.com/13001993/35962939-08d82d52-0c68-11e8-95f4-81006ecde397.png)

The woodcutter itself is enchanted with Infinity and Efficiency V.

Mods used/installed that might have some measure of interaction:
 - Fast leaf block decay mod installed
 - Iguanas Tinker Tweaks installed
 - Vacuum hoppers to collect loose sapplings from leaf block decay
 - EnderIO, ExtraUtilities, and JABBA consitute the logistics infrastructure; however, they are are currently disconnected from the woodcutter's receiving chest.
 - There's an Open Blocks fan to push saplings toward a vacuum hopper when they "get stuck" in union between the 4 hopper's effective AOE; this was added _after_ I first noticed the woodcutter behavior; I only mention it now to explain its presence in the screenshots.

Additionally, and correct me if I'm wrong, should not the sprinkler also be accelerating the slimy sapling growth in addition to cleaning the woodcutter and preventing jams? The manual watering can seems to provide more reliable results. Although the sprinklers do accelerate the plants in my garden just fine, slimy saplings appear to grow at a rate of just a small handful per hour.

**Comment by ReikaKalseki** [comment]
This is not a bug - I never felt "silk-touch-like" behavior on gel-like blocks with spinning blades was appropriate - though you are not the first to complain about the yield ratio. Also, < 1 ball per tree was never the intent.

**Comment by Braidedheadman** [comment]
Understood.

**Comment by ReikaKalseki** [comment]
Having - presumably - left it running for longer, thus giving a better average, what is the average yield?

**Comment by Braidedheadman** [comment]
Oh, I moved on the next day to a system utilizing first an autonomous activator with a TiC lumber axe, which tended to break only the first two blocks in the tree stem and leave both blocks and the leaf canopy behind; to finally an array of activators in order to capture each block in the stem and break the leaf canopy, which, oddly, only requires one leaf block to be broken in order to trigger decay in the entire structure. 

I had left the RotC system running as pictured above overnight but I can't be precise in how many slime balls were captured, as I hooked the chest back up to storage and I failed to note how many were already in the barrel. 

I'd be happy to set up a test site and gather some data for you. Over what time interval would you like this tested? Can you suggest a control case?

**Comment by ReikaKalseki** [comment]
A few dozen trees should be sufficient. Use a CC growth accelerator and that could take less than ten minutes.

**Comment by Braidedheadman** [comment]
All right, I found a moment of free time and finally got around to labbing this properly and the results are in, using the following setup:
![rotc_woodcuttersetup_vs_ 24x slimetree](https://user-images.githubusercontent.com/13001993/36709577-66a7b32a-1b2d-11e8-93e6-4b793aa49809.png)

And the yields from 24 trees cut:
![rotc_woodcutteryield_vs_ 24x slimetree](https://user-images.githubusercontent.com/13001993/36709578-66c23812-1b2d-11e8-8436-c437bb3a46d2.PNG)

The blue slime balls and saplings were acquired as drops from leaf decay (fast leaf decay mod active). I recorded the per-tree drops as well, if you'd like me to provide data more granular than this; however, I had several distractions along the way (including one very insistent cat) and I'm not completely confident in my record keeping. I _do_ know that I processed two dozen trees without doubt, however. :3

If you need more data, I can run another series in the next couple of days, as I have some downtime in my work schedule in the week ahead.

**Comment by ReikaKalseki** [comment]
I will increase the yield, but not the form of the drops.

**Comment by ReikaKalseki** [comment]
Done.
