### ISSUE TITLE
Dragon API/Chromaticraft V19c Loading Issues

### ISSUE THREAD

**Issue by Roboslime** [ReikaKalseki/Reika_Mods_Issues#1777]
Hi there! Today I decided to try out Chromaticraft for the first time. Unfortunately, no matter what i do, nothing seems to be working anymore. I have experienced a variety of issues, without any seeming connection to what has been done.

I cleared out all but a few mods from my mods folder, and added in Chromaticraft. I have put in the newest version of DragonAPI, but that has resulted in several things:

- White screen whenever going full screen, and crashing when trying to load or create a world (seems to have stopped doing this)
- Failing at the texture loading stage before the main menu opens, with an exception about running out of memory (seems to have mostly stopped, still pops up from time to time)
- Seeming to be fine, but then crashing when a world is created or loaded

I would love to be able to play Chromaticraft. Unfortunately, most of this seems to be an issue with DragonAPI, as even by itself it tends to have problems.

This is the window that it froze at most recently.
![error](https://user-images.githubusercontent.com/36549179/36327055-4a01e2fe-132b-11e8-9943-fa102ee47046.png)

Some of the recent crash reports I have been given:
[crash-2018-02-16_14.55.09-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1732657/crash-2018-02-16_14.55.09-client.txt)
[crash-2018-02-16_15.01.51-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1732658/crash-2018-02-16_15.01.51-client.txt)
[crash-2018-02-16_15.04.46-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1732659/crash-2018-02-16_15.04.46-client.txt)

**Comment by OvermindDL1** [comment]
> java.lang.OutOfMemoryError: Java heap space

It's telling you precisely the issue.  ^.^

You need to increase the allocated memory to Minecraft (pretty usual when running mods, textures use a lot of memory after all).  It should never really ever be below 1gig, most use 2gigs, I use 4gigs.  I'd recommend 2gigs.

**Comment by Roboslime** [comment]
I also want to add that I have been happily (though with minor but not game-crashing lag issues) using ReactorCraft, RotaryCraft, and electriCraft as well as a few other mods, with v16 of DragonAPI for while now

**Comment by Roboslime** [comment]
Issue: It is at 1GB right now, and increasing it to 2 messes it up.

**Comment by OvermindDL1** [comment]
> I also want to add that I have been happily (though with minor but not game-crashing lag issues) using ReactorCraft, RotaryCraft, and electriCraft as well as a few other mods, with v16 of DragonAPI for while now

Yeah, Chromaticraft adds a *lot* of textures (and music!) so it's pretty expected.  :-)

> Issue: It is at 1GB right now, and increasing it to 2 messes it up.

Messes it up how?  You have a log for this?  :-)

**Comment by Roboslime** [comment]
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by Roboslime** [comment]
Doesn't even get as far as initializing

**Comment by OvermindDL1** [comment]
> Could not reserve enough space for 2097152KB object heap

Uh, wtf?  How much memory do you have in your system and how much is in use?

For note, if you are on a crappy OS like Windows or so then it will not be able to allocate required memory even if it is unused if too many other programs have allocated too much memory (even if unused), if that is the case then please also take a picture of your program memory usage in the Task Manager (you can paste it right into the Github box, Github is awesome ^.^).

**Comment by OvermindDL1** [comment]
For note, if you hop on EsperNet IRC feel free to PM me at `OvermindDL1` and I can help in more real time.  :-)
