### ISSUE TITLE
Hydrokinetic power output instability.

### ISSUE THREAD

**Issue by waterlubber** [ReikaKalseki/Reika_Mods_Issues#1778]
I'm having issues with my hydrokinetics having really, really strange power output fluctuations. Every few ticks to every few seconds the power out drops down and immediately returns.
I'm running RotaryCraft v19c (public version) and DragonAPI v19c. Forge is 10.13.4.1614.
Here's a video of the issue:
https://youtu.be/LxOKdpyxurU

You can even see it appearing briefly in Sentinalh's videos: https://youtu.be/cNOk_i-hZXc?t=12m40s

It may be of note that my base is chunk-aligned: all of my hydro stuff is in the same chunk.

**Comment by Kobra331** [comment]
Isn't that the reason to use Flywheels? The low pressure Steam turbines have as far as i know the same fluctuation and a turbine flywheel, maybe you should try this?

**Comment by waterlubber** [comment]
Flywheels are death traps (have you seen one explode?), and are a shitty solution to a fundamental problem with the engine itself. IRL the mass of the water + the gigantic spinning steel thing would work as a flywheel.

Additionally, because the average is *slightly* lower than the needed power output, the flywheel is pointless anyway as I'd still need a gearbox to achieve the minimum torque for the extractor.

**Comment by ReikaKalseki** [comment]
I have never seen this; is it related to the block update flicker issue?

**Comment by TomeWyrm** [comment]
"@&#%?!" is right. Last time I checked Hydrokinetics were steady power sources once they get running.

...

Edit: *sigh* that's a really thorough bug report. I've got nothing.

**Comment by ReikaKalseki** [comment]
I currently have no ideas on this, but I will add the "detected waterfall height" to the transducer output, so that it can be determined whether it is a power calculation issue or a waterfall detection one.

**Comment by waterlubber** [comment]
If you have an intermediate build I can drop it on the server and see if the issue still resides.

Also: Would DragonAPI's block data debugger have this information? (The one that shows detailed debug info when you look at a block)

**Comment by ReikaKalseki** [comment]
> Also: Would DragonAPI's block data debugger have this information? (The one that shows detailed debug info when you look at a block)

No, as that data is not saved to the engine's NBT.

**Comment by lee321987** [comment]
I'm seeing the same thing.
Rotarycraft version 20c.
Transducer is reporting "0" waterfall height at about the same frequency as the power loss (it reports the actual "68" the rest of the time).

**Comment by ReikaKalseki** [comment]
The hell....

**Comment by lee321987** [comment]
CORRECTION:  it is not "about the same frequency" -- it is simultaneous .  (sorry)

**Comment by lee321987** [comment]
This ought to help... I just fixed it by removing a 2:1 Bedrock Gearbox.  It was sitting right next to the waterfall, not connected to anything -- a CVT unit is the first thing the Hydrokinetcs output to.
Here's a pic:
![hydrokinetics](https://user-images.githubusercontent.com/18412921/43369699-5e10ac0e-9340-11e8-9408-5a7ff70f6797.jpg)

**Comment by ReikaKalseki** [comment]
So having a gearbox adjacent to the waterfall caused the issue?

Try sending redstone signals into the waterfall.

**Comment by lee321987** [comment]
I tried it...
Redstone signal does it too (I used an Expanded Redstone Clock @ 1s on, 1s off).
Also a bit more info...  the power loss depends on which water column the signal (or Gear Box) is next to.
Next to the first engine (lubricant input), it drops to about 1.5 MW, next engine about 1 MW, next 0.5 MW, and if next to the last engine (power output) it drops to about 1.8 MW (same effect with the block on the side or the back of the water fall).

**Comment by ReikaKalseki** [comment]
What about placing a block manually next to the waterfall?

**Comment by lee321987** [comment]
Yeah, that does it too, but only the moment the block is placed -- then output stays normal.

**Comment by ReikaKalseki** [comment]
So block updates are apparently the cause. I think I know the problem - block updates to water cause it to change block IDs - from BlockStaticLiquid to BlockDynamicLiquid - and do any recalculations on flow if necessary. This must not be 'counted' by the hydrokinetic.

**Comment by ReikaKalseki** [comment]
Fixed.
