### ISSUE TITLE
ME Item Distributors freezing AE2

### ISSUE THREAD

**Issue by Chromotron** [ReikaKalseki/Reika_Mods_Issues#178]
I connected a ME Item Distributor to my fairly huge AE2 network, entered a 10 in the first field and set the two neighbouring ones to ME cables (or probably any other block). After some seconds, the entire ME system became unresponsive, even disconnecting the Distributor and some parts or reconnecting the controller did not fix this. Only a server restart did help.
Opis and CPU usage look normal.

**Comment by ReikaKalseki** [comment]
Use VisualVM and try again while profiling.

**Comment by ReikaKalseki** [comment]
Closed due to no useful information given and repeated prompts for more ignored.
