### ISSUE TITLE
Suggestion - RF Meter

### ISSUE THREAD

**Issue by dieselfuelonly** [ReikaKalseki/Reika_Mods_Issues#1781]
I'd love to have a simple block, just like the dynamometer or electric meter block, that could simply report the amount of RF flowing through the block.  Being able to read the values with a computer would be excellent.  Perhaps something similar to this - https://zi.bymarcin.com/RFMeter/RFMeter.md

**Comment by ReikaKalseki** [comment]
RF does not work that way; there is no "flow" of energy that a block in the middle of a conduit could know about.

The closest that could be achieved is tracking how much energy was added to it in the last tick, but that requires giving it is own internal buffer, which means that it is A) now usable as a battery and B) will erroneously report nonzero values if its buffer is not full, even if the "downstream target" is not receiving energy.
