### ISSUE TITLE
[RoC] Custom Extracts 'Native Ore' is non-functional

### ISSUE THREAD

**Issue by CanisArtorus** [ReikaKalseki/Reika_Mods_Issues#1782]
Using the RotaryCraft_CustomExtracts.cfg file to add variants that should be equivalent to an existing vanilla ore implements the same customextract creation as a completely new ore.
``
Lapis Ore, scarce, gem, gemLapis, 6, 0x1534bc,0x2862af, LAPIS, oreAndesiteLapis, oreBasaltLapis, oreBlackgraniteLapis, oreDioriteLapis, oreGravelLapis, oreLimestoneLapis, oreMarbleLapis, oreMarsLapis, oreMoonLapis, oreMudLapis, oreRedSandLapis, oreRedgraniteLapis, oreSandLapis, oreSandstoneLapis, oreSpaceLapis, oreUmberstoneLapis, oreVanillagraniteLapis, oreBlueschistLapis, oreGreenschistLapis, oreKimberliteLapis, oreKomatiiteLapis, oreQuartziteLapis
``
Produces <Rotarycraft:rotarycraft_item_customextract> named 'Lapis Ore Flake' &c. that does not have the aluminium dust by-product of real <Rotarycraft:rotarycraft_item_extracts> .  
This being the stated purpose of the Native Ore entry, it has failed.
v19c RotaryCraft & v19c DragonAPI

**Comment by ReikaKalseki** [comment]
Done...at significant difficulty.
