### ISSUE TITLE
[GT6] compat update

### ISSUE THREAD

**Issue by CanisArtorus** [ReikaKalseki/Reika_Mods_Issues#1783]
Extending #1605 , but for Gregtech 6, at line 67 of DragonAPI/GregOreHandler.java in function
``
public boolean isGregOre(Block b) {
		return Block.blockRegistry.getNameForObject(b).startsWith("gt.blockores");
}
``

needs to (also) test
  "gt.meta.ore."
which is used in gt6 as a block name prefix, unlike the single meta-item from gt5u you have included.

and also test
  "gt.block.rockores"
for the 6.07 full layer ores: bauxite, lignite, coal, salt, rock salt, oilshale .

IE:

public boolean isGregOre(Block b) {
    string bn = Block.blockRegistry.getNameForObject(b);
    return bn.startsWith("gt.blockores") || bn.startsWith("gt.meta.ore.") || bn.startsWith("gt.block.rockores");
}

**Comment by ReikaKalseki** [comment]
Done.
