### ISSUE TITLE
Large drop lists will break centrifuge processing

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#1787]
There seems to be an issue with the RotaryCraft centrifuge interface (I think) where the Centrifuge stops working correctly under certain circumstances.

As near as I can figure it, if an item's centrifuge drop list is larger than 9 drops (the maximum number of drop slots in the centrifuge),  the centrifuge will, at the end of the first processing cycle, wipe out the existing drops before placing the new ones (sometimes the screen doesn't update properly, and I end up with "ghost" items).  If the second set of drops are not picked up, the centrifuge will then continue to cycle, neither adding new drops, nor consuming source items.

I had originally believed the issue was in JMOD or my own scripts... until, on a whim, I removed both JMOD and the Ex Machina script, and tried to process the "unprocessed radioactive waste" in the centrifuge, only to discover the exact same issue (unprocessed radioactive waste has 17 drops in its list).

**Comment by ReikaKalseki** [comment]
I am not sure there is a good fix for this, but I can increase the slot count to 25 or something.

**Comment by ghost** [comment]
I dunno... as far as I'm concerned, a "good fix" is a fix that's good enough to fix the problem; so your idea qualifies.  By 25, I'm assuming you mean to increase the grid from 3x3 to 5x5?

Under normal circumstances, this really isn't an issue (except where processing nuclear waste is a concern), but for the upcoming SI, the centrifuge is intended to be the automatable version of the sifter, while removing higher-tier materials from the sifter's drop tables.  

There's still some rebalancing to do to keep things fair, however.

**Comment by ReikaKalseki** [comment]
It turns out that I cannot make the output grid larger due to GUI size and space concerns, and as a result I am somewhat stuck for ideas.

**Comment by ghost** [comment]
Hmmm... what do you mean by GUI Size and Space concerns?  Perhaps you could "page" your storage, similar to the scalable chest?  Then, instead of expanding your grid, you can simply have buttons indicating page forward and page back?

**Comment by OvermindDL1** [comment]
@Reteo Make a new intermediate product and just centrifuge twice to get all outputs then

**Comment by ghost** [comment]
The problem with that idea is that I'm attempting to duplicate the drops from Ex Nihilo using the RotaryCraft Centrifuge; I'd rather not make things more complicated for the players than it would otherwise be.

**Comment by ReikaKalseki** [comment]
Paginating the inventory is not an option; it adds severely to both the code complexity and the difficulty of use. I think the idea of splitting the process is the best one, and I even sort of *like* the idea of the user having to feed the outputs back to the inputs, as that sort of logistics puzzle is a core theme in RC.

**Comment by ghost** [comment]
Under circumstances where I'd normally have the creativity to make things up, that _would_ be ideal.    However, in this case, I am attempting to duplicate (to a significant degree) the outputs of the Ex Nihilo sieve; I'm not sure how well things will turn out if I try to enforce another level of processing.

Hopefully, you'll continue looking for a solution; I'll try to find an appropriate split to the processes in the meantime.  I'm assuming you'll do the same with ReactorCraft as well?

**Comment by ReikaKalseki** [comment]
>  I'm assuming you'll do the same with ReactorCraft as well?

I was planning on splitting the waste into a few categories - likely based on periodic table group ("nonmetals", "actinides", "transition metals", etc), yes.

**Comment by ReikaKalseki** [comment]
![https://i.imgur.com/cLUZQIS.png](https://i.imgur.com/cLUZQIS.png)

![https://i.imgur.com/pgRZUb7.png](https://i.imgur.com/pgRZUb7.png)

![https://i.imgur.com/5moumFh.png](https://i.imgur.com/5moumFh.png)

**Comment by ReikaKalseki** [comment]
It has been fully implemented. Also, I put in a hard limit on the output count now; more than nine items and it will not even load.

**Comment by ghost** [comment]
You wouldn't happen to know a formula to duplicate a probability using multiple steps, would you?

**Comment by ReikaKalseki** [comment]
I do not know what you are asking.

**Comment by ghost** [comment]
Let's assume we have something that is generated with a 50% probability.  That means that there is a 1-in-2 chance that it will be dropped during any cycle of the centrifuge.  This is a 1-step probability; the chance is rolled once, and the result is done.

When we enter into a 2-cycle process, each cycle will introduce an additional probability, which will alter the overall probability significantly.  If that second processing is another 50% probability of dropping something, the overall probability is 25%  Of course, you could set the second process to 100%, in which case, the drop returns the the original 50% probability.

Now, let's get complicated.  Suppose we're processing dirt to drop seeds.  The probabilities are: 50% wheat, 25% carrots and potatoes, and 10% pumpkins and melons.  In a one-step system, you can get any of those drops in any combinations at those probabilities.

Now, suppose we need to compress all those seeds into a "seeds" drop, which then needs to be processed.  How do we adjust the probability of the "seeds" drop, as well as the drops for those seeds (wheat, carrots, potatoes, melons, pumpkins) to preserve their original drop chances (50, 25, 25, 10, 10), so that their original probabilities are preserved?

Well, one possibility is that we could simply double the probability of the seeds to counter the 50% probability of the "seeds" drop, right?  The problem here is that if that happens, then a wheat seed is _guaranteed_ to drop if any seeds drop, whereas originally, there was a chance that the other seeds dropped, but not the wheat.  The overall probability of the different seeds in the overall drop process is preserved, but their relative probability with each other is badly skewed in favor of wheat.

I'm working on a potential idea utilizing recursive probabilities, but that will require some experimentation.

**Comment by ReikaKalseki** [comment]
Look to what I did for waste; the new probabilities on the first stage are the sum of the probabilities of all drops on the last, and the second stage are their original values divided by that first stage probability (note that this is dividing by a number less than one).

**Comment by ghost** [comment]
I'll have to look into that.  In case you are interested, the recursive idea was to give the processed material the chance of dropping itself, so that it could be processed again... kinda making the centrifuge work in a way not entirely unlike the extractor.
