### ISSUE TITLE
[Chromaticraft] Chromatic Enchanter not enchanting certain items

### ISSUE THREAD

**Issue by killadonwrath** [ReikaKalseki/Reika_Mods_Issues#1788]
After doing some updates and re-installs, the Chromatic Enchanter no longer enchants every item. As can be seen in the picture, I had two diamond swords to see if it works, and it did. Both enchanted and unenchanted. When I try it on other items (such as the item in the picture or just some random block), it refuses to enchant despite possessing the ability to be enchanted. It didn't enchant even after using an anvil to add another enchantment.
![2018-03-10_21 39 24](https://user-images.githubusercontent.com/37256697/37249014-a8416f1e-24ac-11e8-921d-0fdb7ea7b54f.png)
![2018-03-10_21 45 52](https://user-images.githubusercontent.com/37256697/37249017-b3b6436a-24ac-11e8-8473-8c26e7e154a6.png)

**Comment by ReikaKalseki** [comment]
It was never intended to enchant any random item, and items that are meant to be enchantable should have the item registered as such (ie a nonzero enchantability value).
