### ISSUE TITLE
[Chromaticraft] Draconic armor causing a strange graphics glitch

### ISSUE THREAD

**Issue by killadonwrath** [ReikaKalseki/Reika_Mods_Issues#1789]
Whenever I have Draconic armor on (any piece, doesn't need to be a full set; haven't checked Wyvern set) the Chromaticraft book's graphics are screwed up. This applies to every page of the book (except maybe the notes). Included is the complete log file in which I entered the world, unequiped armor, opened book, re-equipped armor, opened book again, then quit.
![2018-03-10_21 39 44](https://user-images.githubusercontent.com/37256697/37249097-7f58d02c-24ae-11e8-8264-49c0d63cc58b.png)
![2018-03-10_21 39 49](https://user-images.githubusercontent.com/37256697/37249096-7db2ef32-24ae-11e8-9f0e-111a431ab8e8.png)
![2018-03-10_21 40 10](https://user-images.githubusercontent.com/37256697/37249095-7b81f55a-24ae-11e8-9873-c25dcc2c2a06.png)
![2018-03-10_21 40 13](https://user-images.githubusercontent.com/37256697/37249093-7921911c-24ae-11e8-8359-7bfddc621882.png)
https://pastebin.com/PfHWQSjV

**Comment by ReikaKalseki** [comment]
#1402
