### ISSUE TITLE
Vacuum gun crashing and corrupting server

### ISSUE THREAD

**Issue by Chromotron** [ReikaKalseki/Reika_Mods_Issues#179]
I tried the Vacuum Gun. For the first few seconds it worked well (and looked epic at sucking in blocks), but then it disconnected me from the server. Reconnecting gave me another one or two second of animation (now the blocks flying away) before it kicked me again, and this time also crashed the server. It now crashes on restart every time, only reverting to backups or removing the relevant chunks did fix it.

**Comment by ReikaKalseki** [comment]
Again, log and version?

**Comment by ReikaKalseki** [comment]
Anything?

**Comment by ReikaKalseki** [comment]
Closed due to no useful information given and repeated prompts for more ignored.
