### ISSUE TITLE
Creative industrial rotary coil explosion

### ISSUE THREAD

**Issue by EltonSetan** [ReikaKalseki/Reika_Mods_Issues#1790]
Hello,

Today I was getting into RotaryCraft because I wanted to build a nuclear power plant from NuclearCraft but I didn't know how the power worked so I wanted to temporarily get power from the creative coil and once I placed it my whole base exploded destroying everything I had.

Please fix this.
Forge, API and RotaryCraft at latest version.

**Comment by Kobra331** [comment]
AFAIK this only happens if you place the coil without creative mode.

**Comment by ReikaKalseki** [comment]
> this only happens if you place the coil without creative mode.

This. The creative coil is for creative.
