### ISSUE TITLE
[ChC v19c] Warp Node Crashing Upon Generating

### ISSUE THREAD

**Issue by XenoStone1009** [ReikaKalseki/Reika_Mods_Issues#1791]
Whilst walking around for several hundred chunks looking for pylons, the server I played on suddenly crashed. Upon reading the crashlog (and subsequent modlist here [https://pastebin.com/rq5d6heL](https://pastebin.com/rq5d6heL)), I find that the Warp Nodes are what caused it when generating. However, this I can only assume is a random occurrence because I have a Warp Node right above my base which loaded perfectly fine.

_(ModEdit: Fixed URL Link)_

**Comment by XenoStone1009** [comment]
And upon rejoining, the server and chunk loads fine as it assumingly has generated the chunk with a new random number...

**Comment by ReikaKalseki** [comment]
It seems there is a potential crash in the worldgen code.

**Comment by ReikaKalseki** [comment]
Fixed.
