### ISSUE TITLE
Crash while looking up recipes in NEI in "A Polycrhomatic World" modpack

### ISSUE THREAD

**Issue by donoya** [ReikaKalseki/Reika_Mods_Issues#1793]
After talking with the modpack creator of "A Polychromatic World" about this issue, they said I should post this here, so here's the crash report:
[crash-2018-03-17_14.49.13-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1827443/crash-2018-03-17_14.49.13-client.txt)
I don't exactly recall which item I looked up at this point, but it seems to happen slightly often (as in anywhere from 1 in 20 searches to 1 in 100). I do know this happened when right clicking in the recipe window, either to see all recipes for a type of crafting or to see the uses of one of the items.

**Comment by ReikaKalseki** [comment]
I suspect you have an item registered to the game with a null name. Try removing mods.

**Comment by LordPINE** [comment]
Hello Reika, I'm the modpack creator referred to here. Removing mods, while possible stopping the issue, is quite difficult to do in this case with the random nature of the crashes. Would a null check on the name of the item not be a possibility? That might help, and I have a feeling that an item not having a lumen value is less of a problem than the game crashing.

Just looked at the code as well, and it seems that adding a second null check in the getNamespace function shouldn't be impossible. It might however lead to problems when the function is called, but I don't know enough about your code to check this.

**Comment by ReikaKalseki** [comment]
The problem is not the null check, but the fact that such a thing should not exist in the first place; items with null names are clear 'erroneous values' and run the risk of breaking every system with which they interact. Trying to add an increasing number of special exceptions just allows such errors to persist or even multiply. Also, depending on the specific case, there may not be a meaningful 'default/backup result' for unparseable data.

**Comment by LordPINE** [comment]
After doing some messing about with the pack, I've found the offending mod, from what I can tell. Can't get the game to crash anymore anyway. It was caused by extra trees. Thought you might like to know. I think this can be closed now.
