### ISSUE TITLE
Expanded Redstone Block Breaker Affected by Ex Nihilo Hammer

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#1794]
When you hold an Ex Nihilo hammer, cobblestone, gravel, and sand collected by the Expanded Redstone block breaker will be treated as if they were broken with the hammer (cobble becomes gravel, gravel becomes sand, and sand becomes dust).  This only seems to apply to situations where the hammer is in your hand; if it's in your inventory, the block breaker will function as expected.

**Comment by ReikaKalseki** [comment]
I think ExNihilo must be modifying the drop system of those blocks in some way; otherwise, this makes no sense.

**Comment by ghost** [comment]
Huh.  That makes sense.  In a "cart before the camel" kinda way...

**Comment by ReikaKalseki** [comment]
Who is the developer? Are they active on here?

**Comment by ghost** [comment]
The developer is Erasmus Crowley, and he's apparently not on Github.  I see what might be the source [here](https://bitbucket.org/Erasmus_Crowley/ex-nihilo/src/), but the dates don't exactly line up to the last version released; the most recent Ex Nihilo was released in 2016, while the source shows the most recent update was in 2015.  His last post on the Minecraft forum was also on 2016, so I'm under the assumption that this is no longer being supported.

**Comment by ghost** [comment]
Ah, I stand corrected.  Mike Lydeamore took over maintenance of Ex Nihilo, and the more recent source is [here](https://bitbucket.org/MikeLydeamore/ex-nihilo/src).  Even the release and commit dates line up nicely.  It's still not being maintained anymore, though; he's rewriting a new Ex Nihilo from scratch for 1.12 (Ex Nihilo Adscensio).

**Comment by ReikaKalseki** [comment]
Short of explicitly hardcoding the drops for those blocks - which is a messy solution and would break if anyone *wanted* to change their drops - I cannot really fix this without more information from them.

**Comment by ghost** [comment]
Fair enough.  It's not really a problem for me, personally, but I figured you might want to know about it.

**Comment by ReikaKalseki** [comment]
I checked my code again; this has to be on his end.
