### ISSUE TITLE
Chromaticraft crash with fun world gen

### ISSUE THREAD

**Issue by danilbor11** [ReikaKalseki/Reika_Mods_Issues#1798]
Crash: 
https://pastebin.com/qQ5qQKN2
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1849391/latest.log)

**Comment by OvermindDL1** [comment]
> ```java
> java.lang.IndexOutOfBoundsException
>     at java.nio.Buffer.checkIndex(Buffer.java:540)
>     at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
>     at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
>     at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
>     at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
>     at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
>     at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
>     at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
>     at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
>     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
>     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061)
>     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
>     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
>     at net.minecraft.client.main.Main.main(SourceFile:148)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:4> 3)
>     at java.lang.reflect.Method.invoke(Method.java:483)
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> ```
> ```java
> Stacktrace:
>     at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
>     at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
>     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
>     at net.minecraft.client.main.Main.main(SourceFile:148)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:4> 3)
>     at java.lang.reflect.Method.invoke(Method.java:483)
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> ```

This is not a world-gen issue (I've not actually seen a crash in packet 01 before, hmm...)

**Comment by ReikaKalseki** [comment]
I think that is either an OOM error or a packet transmission failure (partial data loss).
