### ISSUE TITLE
(ChromatiCraft) Crash on world starting

### ISSUE THREAD

**Issue by asd1232468** [ReikaKalseki/Reika_Mods_Issues#1799]
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1861575/latest.log)

**Comment by DracoScythem** [comment]
Have you installed DragonAPI? ChromatiCraft, like all of Reikas mods, needs it.

**Comment by asd1232468** [comment]
No going to try

**Comment by asd1232468** [comment]
Thanks man!

**Comment by asd1232468** [comment]
As soon as i started the world it crashed

**Comment by asd1232468** [comment]
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1862055/latest.log)

**Comment by asd1232468** [comment]
Its also saying Dragonapi: _________ not detected

**Comment by DracoScythem** [comment]
Try updating Forge to 1614 (latest)

**Comment by asd1232468** [comment]
Ok

**Comment by asd1232468** [comment]
Thanks again!
