### ISSUE TITLE
bug games

### ISSUE THREAD

**Issue by drdreforgotaboutme** [ReikaKalseki/Reika_Mods_Issues#18]
Help file, again ... wrong in events around very. Game. A lot barrel mall MAKING whos game, nail: I kill monsters because I of such, sometimes die. I year know you to be busy with make to healthy herbal medicine in serious motion, however it it is a very imperfect. Text here capture interval occurs.

![](http://vignette2.wikia.nocookie.net/central/images/c/ca/Chain_Drives_2.png/revision/latest/scale-to-width/400?cb=20150103010429)

**Comment by trajing** [comment]
We need more information about what happened and what you were doing.

**Comment by drdreforgotaboutme** [comment]
Car and I think you should be able to communicate, this should work, but they like, and then the sky will work me if damp cloth

**Comment by drdreforgotaboutme** [comment]
I'm sorry that I'm unjustly about this, so I do not forget to say that in a creative way, I might end up in the hospital.

**Comment by drdreforgotaboutme** [comment]
Is more beneficial I can be creating for helping flatten the ant?

**Comment by shobu9** [comment]
Use Reverso....dictionnary

**Comment by drdreforgotaboutme** [comment]
Why do not you brother help a for to a lot? If? Of trouble to see him to ask for my game? Unless it?

**Comment by Blarghedy** [comment]
What.

**Comment by WayofTime** [comment]
It looks like a random number generator getting it on with a text parser...

**Comment by yrsegal** [comment]
Healthy Herbal Medicine? Someone call @Vazkii over here!

**Comment by PegasusEpsilon** [comment]
@drdreforgotaboutme What is your native language?

**Comment by sProgg** [comment]
what the shit

**Comment by Sinhika** [comment]
Either robot spam is attacking GitHub comments now, or someone is overly trusting of Google Translate.  Or terrorists are communicating in code via GitHub issues reports.

**Comment by trajing** [comment]
Or 4chan is now a language.

**Comment by FlipzMCL** [comment]
This text is virtually identical to a lot of the stuff we get on the FTB forums, particularly the blurb about "healthy herbal medicine".  I'm about 90% certain it's a spambot.

**Comment by Blarghedy** [comment]
I'm impressed that a spambot posted a picture that seemed at all relevant

**Comment by ReikaKalseki** [comment]
The only one going to a hospital is us readers from laughing-induced asphyxiation...

**Comment by coolsquid** [comment]
I'm somewhat unsure about whether we should ever close this... It's way too funny.

**Comment by ReikaKalseki** [comment]
Well, I am going to bed before I lose more sleep... :P

**Comment by jordsta95** [comment]
@drdreforgotaboutme please post in your native language, as it is obvious English isn't your primary language, and I don't think anyone can understand you.
In your native language however, people may understand it. In English? It looks like you let the proverbial monkeys type... and they didn't write shakespear

**Comment by ljfa-ag** [comment]
I ask everyone here to not comment if you have nothing meaningful to contribute to the issue. Please refrain from making fun of the poster.

**Comment by 1Matthias** [comment]
I think he was asking how to connect the belt hubs without leather. Yes, I speak gibberish.

**Comment by drdreforgotaboutme** [comment]
Jordsta95 @ I mean, and he hit the fish? My art apologize.

I have this problem, spiders, my mother and my world is very popular, but the car will not be able to explain the fire.

**Comment by drdreforgotaboutme** [comment]
Progress, it is necessary to know, to my mind, the pain!
![The is banana for rich!](http://s23.postimg.org/rvhq9ujmj/aaa2015_03_14_17_27_33.png)

**Comment by drdreforgotaboutme** [comment]
It is rich, I found another disease = (. When undulate, I for the world flat.
![Because?](http://s15.postimg.org/fcsjpjmsr/2015_04_21_23_06_52.png)

**Comment by drdreforgotaboutme** [comment]
I selection of dishes, so that everyone will know why this concern will be open as soon as possible to wear today. Revelry. It would be better, in my opinion, everyone forgets lunch you can make a choice.

**Comment by KIN0025** [comment]
Please use google translate (https://translate.google.com.au/) , or post in your native language. This will make it easier for us to understand the nature of your issue.

**Comment by drdreforgotaboutme** [comment]
Google is love, but you lose?

**Comment by KIN0025** [comment]
We are unable to understand you in english, can you post in your native language.

**Comment by drdreforgotaboutme** [comment]
What are my words to see the seal?

**Comment by KIN0025** [comment]
I have google translated "Can You speak in your native language?" for you into numerous languages.
你可以说汉语吗？
Pouvez-vous parler dans votre langue maternelle?
당신은 당신의 모국어로 말할 수 있습니까?
आप अपनी मूल भाषा में बात कर सकते हैं?
Можете ли вы говорить на своем родном языке?
Dapatkah Anda berbicara dalam bahasa Anda?
Та төрөлх хэлээрээ ярих боломжтой юу?

**Comment by darkhax** [comment]
If anyone is interested, I pasted my list of translations [here](https://gist.github.com/darkhax/769a2cbf2a5c79c6e3f7). I tend to get private messages like this a lot on the forums and in IRC, so I send this message to help clear things up. It contains the phrase "We can not understand what you are saying. Please tell us your native language so we can better communicate." in several languages.

**Comment by itanshi** [comment]
Adding some belated 2 cents. I appreciate the assumption it was a foreign language being translated, but its probably a spinner, perhaps spinbot. Software that writes blog articles for you, often horribly. I believe you can even submit content to it and spin it again, so it gets more warbled.

**Comment by madolinn** [comment]
Googled Spinbot, typed in a sentence. It made my sentence sound more professional .-.

**Comment by jordsta95** [comment]
@drdreforgotaboutme let me TRY to understand what you have said...
You are having trouble getting the torque you need?
You think you have set up everything correctly, but it doesn't work?
Please reply in your native language.
Por favor, responda en su idioma nativo.
الرجاء الرد في لغتك الأم.
Խնդրում ենք պատասխանել ձեր մայրենի լեզվով:
Калі ласка, адкажыце на вашым роднай мове.
Gelieve te antwoorden in uw moedertaal.
Пожалуйста, ответьте на вашем родном языке.
Se il vous plaît répondre dans votre langue maternelle.

I really don't know what language is your native, I HOPE I got it though. I would much rather have to translate Armenian than the broken English which you are typing in. 
As everyone here has basically said, you are not producing sentences which make sense, which means that we unfortunately cannot help you.

**Comment by 1Matthias** [comment]
> Progress, it is necessary to know, to my mind, the pain!
The is banana for rich!

Ok, the white gear in that splitter needs to be next to the dynamometer for it to transfer power. 

> 

It is rich, I found another disease = (. When undulate, I for the world flat. Controlling the animal local:
Because?

The violation is not healed if. Magic variation for the gone.
The ac engine only works if you give it a redstone pulse going up and down, as well as a magnetized shaft core, like in this video. https://www.youtube.com/watch?v=Z502TmPdgfE

**Comment by ReikaKalseki** [comment]
User error tag removed pending further info.
