### ISSUE TITLE
Replication Wand not working and crashing

### ISSUE THREAD

**Issue by Chromotron** [ReikaKalseki/Reika_Mods_Issues#180]
I am not sure how to actually use it, but it definitely should not cause errors. After making one, at first it did nothing. After some minutes of trying stuff this changed to disconnecting me ("Internal Server Error") every time I right clicked with it.

**Comment by ReikaKalseki** [comment]
Again, log and version?

**Comment by ReikaKalseki** [comment]
Any info at all?

**Comment by ReikaKalseki** [comment]
Closed due to no useful information given and repeated prompts for more ignored.
