### ISSUE TITLE
Crash when server loading

### ISSUE THREAD

**Issue by Zafaranec** [ReikaKalseki/Reika_Mods_Issues#1800]
Hi, I'm sorry, if was duplicating other issue, but I have a problem, here is my crash log: [log](https://pastebin.com/cuYfYrfN) before this, I was logged on server and doing some cosmetic changes near my rotarycraft factory and I see all of block with error purple-black crossed texture, I recently add some decorative tanks and after a few minutes crash my server and crash every time when I try load him with same error. Help me please :)

**Comment by Zafaranec** [comment]
![2018-04-01_16 13 05](https://user-images.githubusercontent.com/32370898/38174065-b10f4ad6-35c7-11e8-81ca-38eff13229d1.png)
today I try singleplayer and place some blocks from RotaryCraft and this is result, what happened? I try again load server with world backup and loads, but when I join, I see this creepy textures and after a few seconds server crash. What I did wrong?

**Comment by uniacke1** [comment]
Textures are expected given the date, however, I too am seeing a server crash in RoC on start. Log:

[crashreport.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1866422/crashreport.log)

Server dies on restart with a similar stack trace:

> [10:30:37] [Server thread/ERROR] [FML]: Caught exception from ExtraUtilities
> java.lang.RuntimeException: Serious error calling getRenderType() on block RotaryCraft:rotarycraft_block_advancedgear
>         at com.rwtema.extrautils.tileentity.enderquarry.BlockBreakingRegistry.setupBreaking(BlockBreakingRegistry.java:85) ~[BlockBreakingRegistry.class:?]
>         at com.rwtema.extrautils.ExtraUtils.postInit(ExtraUtils.java:1326) ~[ExtraUtils.class:?]
>         at com.rwtema.extrautils.ExtraUtilsMod.postInit(ExtraUtilsMod.java:33) ~[ExtraUtilsMod.class:?]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
>         at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
>         at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
>         at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
>         at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
>         at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
>         at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
>         at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
>         at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
>         at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
>         at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
>         at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
>         at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
>         at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
>         at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
>         at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
>         at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
>         at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
>         at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319) [FMLCommonHandler.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) [lt.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
> Caused by: java.lang.NoSuchMethodError: Reika.DragonAPI.Libraries.IO.ReikaRenderHelper.rerenderAllChunks()V
>         at Reika.RotaryCraft.Auxiliary.OldTextureLoader.loadOldTextures(OldTextureLoader.java:76) ~[OldTextureLoader.class:?]
>         at Reika.RotaryCraft.Base.BlockModelledMachine.func_149645_b(BlockModelledMachine.java:43) ~[BlockModelledMachine.class:?]
>         at com.rwtema.extrautils.tileentity.enderquarry.BlockBreakingRegistry.setupBreaking(BlockBreakingRegistry.java:78) ~[BlockBreakingRegistry.class:?]
>         ... 33 more
>

**Comment by ReikaKalseki** [comment]
This is ExU forcing a crash due to a state that he believes to be invalid but is not; getRenderType() is - stupidly, but commonly throughout the game engine - used for more than just rendering, such as actual game logic.

**Comment by ReikaKalseki** [comment]
Never mind, the error at the top half is irrelevant or at least misleading. There was also an issue in RC which is now fixed.

**Comment by Zafaranec** [comment]
Hello, I sorry, English is not my native language, maybe some misleading but I cannot find error. I try re-download dragonapi and rotarycraft, remove last two mods there I add, erase configs, create new world, erase config of optifine and still same problem you can see on picture above. Please, can you help me?

**Comment by uniacke1** [comment]
It will go away on its own if you wait until tomorrow.

**Comment by ReikaKalseki** [comment]
Or change your computer date if you are playing SSP.

**Comment by Zafaranec** [comment]
Wait a minute, it is totally crazy and dump Easter egg? Really? And crashing my server will be too away?

**Comment by Zafaranec** [comment]
It's working, but this bug/feature :D is crazy. Whatever thanks a lot.

**Comment by uniacke1** [comment]
I realize this has been fixed but this seems to have consequences that reach beyond the date; My server is still crashing on startup in the RenderOldTextures() call despite it now being April 2.

Is it possible that once you are in this state it cannot start to disable itself?

Edit: Toggling the flag in DragonAPI made it start, but it still crashes on changing back. Seems the date range is more than just the first?

Caused by: java.lang.NoSuchMethodError: Reika.DragonAPI.Libraries.IO.ReikaRenderHelper.rerenderAllChunks()V
        at Reika.RotaryCraft.Auxiliary.OldTextureLoader.loadOldTextures(OldTextureLoader.java:76) ~[OldTextureLoader.class:?]
        at Reika.RotaryCraft.Base.BlockModelledMachine.func_149645_b(BlockModelledMachine.java:43) ~[BlockModelledMachine.class:?]
        at com.rwtema.extrautils.tileentity.enderquarry.BlockBreakingRegistry.setupBreaking(BlockBreakingRegistry.java:78) ~[BlockBreakingRegistry.class:?]
        ... 33 more
[18:14:51] [Server thread/ERROR]: This crash report has been saved to: /home/gamecreate/minecraft/vaultcraft/./crash-reports/crash-2018-04-02_18.14.51-server.txt
[18:14:51] [Server thread/WARN] [FML]: Can't revert to frozen GameData state without freezing first.
[18:14:51] [Server thread/INFO] [FML]: Applying holder lookups
[18:14:51] [Server thread/INFO] [FML]: Holder lookups applied
[18:14:51] [Server thread/WARN] [EnderIO]: Failed to write Transciever Channels on exit: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[18:14:51] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[18:14:51] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[18:14:51] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
[gamecreate@localhost minecraft]$ ./minecraft_launch.x86^C
[gamecreate@localhost minecraft]$ date
Mon Apr  2 18:16:02 EDT 2018
[gamecreate@localhost minecraft]$
