### ISSUE TITLE
Extra Utilities Ender Quarry causing crash when attempting to mine a tiered ChromatiCraft ore

### ISSUE THREAD

**Issue by Zebralear** [ReikaKalseki/Reika_Mods_Issues#1801]
I was running around in the nether after setting up an "Extra Utilities" ender quarry on the nether roof and my game suddenly crashed; I first tried deleting the "level.dat" file and renaming the "level.dat_old" to "level.dat". Nothing, I still crashed upon spawning in. I then tried again, loaded in fine for about one-second longer before crashing.

Sorry about quotes, Grammarly is a pain in the ass if I don't have them in.

Crash Report Here: https://pastebin.com/LyHQ8EzB

**Comment by ReikaKalseki** [comment]
#1718
