### ISSUE TITLE
Crash with ChromatiCraft opening loot chest

### ISSUE THREAD

**Issue by Kataiser9** [ReikaKalseki/Reika_Mods_Issues#1804]
https://pastebin.com/CW1hiTiM

This occurred in SSP when opening a chest in a desert structure. It is consistent - reloading and attempting to open the same chest again resulted in the same crash - but only happens with this specific chest. I've opened tens of ChC chests in this playthrough before now with no issue.

[edit: removed erroneous references to EnviroMine, misread the log]

**Comment by ReikaKalseki** [comment]
That block appears to have lost its TileEntity (from a cause outside CC), and is thus invalid. Delete it.
