### ISSUE TITLE
[ChromatiCraft] Extremely high CPU usage and errors during world generation

### ISSUE THREAD

**Issue by osmarks** [ReikaKalseki/Reika_Mods_Issues#1806]
I've included ChromatiCraft as part of a large modpack which I am attempting to run on a server. It appears to consume large amounts of CPU (almost 100% on all cores) whilst generating its dimension. When I let it run for long enough, [errors appear](https://gist.githubusercontent.com/osmarks/0d4e84f79c5ee12a9953e9f7de3d7e3f/raw/e122da5b9c7ecdf4752bc41549d5158784fdfcbb/forge-log.log). I have not been able to figure out whether a specific mod causes it, as it appears to just become slower and slower as I add more. The issue does not occur in singleplayer.
If there is any profiling I can do, please let me know, as I am not experienced with this sort of thing.

[Modlist](https://gist.github.com/osmarks/4cb33655939ddcae1bf5ab8d4382f3c5)

**Comment by ReikaKalseki** [comment]
Your error is that you ran out of RAM. Worldgen *does* use a lot of CPU power, both in CC and in anything else MC-related (and worldgen in general in other games as well).

Is the server running on a weak CPU, or with little RAM?

**Comment by osmarks** [comment]
The CPU should be fine, it's probably the RAM. I allocated 3.5GB (the server has 4). The strange thing is that htop only shows RAM use as 35% or so - not anywhere near the maximum.

**Comment by ReikaKalseki** [comment]
3.5GB is nowhere near enough for a large modpack, and there is no way that it even booted using less than 2GB.

**Comment by osmarks** [comment]
It seems that the issue was that I had put the -Xmx argument after -jar, so it wasn't picked up. I moved it to the start and the extreme CPU use stopped quite quickly. The world seems playable.
