### ISSUE TITLE
Electricraft - Suggestion - Resistor and Relay

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [ReikaKalseki/Reika_Mods_Issues#1807]
Would it be possible to make resistors and relays able to be placed vertically on a wall?
Just wondering since it seems like it would make organizing power distribution much easier.

Thanks.

**Comment by ReikaKalseki** [comment]
While I have nothing against the idea on principle, it would greatly complicate rendering, connectivity, (and in the case of resistors, band coloring) logic, for a comparatively small gain.

**Comment by MachiavelliSeraphim** [comment]
No problem.  If it were simple id ask politely, but since its not, no problem.
Thanks for looking.
________________________________

**Comment by ReikaKalseki** [comment]
I am going to close this, as there is a minimal chance of it being implemented.
