### ISSUE TITLE
Blast Furnace with Crafting Pattern wont make Coke

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [ReikaKalseki/Reika_Mods_Issues#1808]
The crafting pattern doesnt seem to lock the slots on the Blast Furnace for making coke anymore.  
Am I remembering how to do this incorrectly or has something changed?
I thought it was just set the pattern to blast furnace and put 9 coal in it?

The regular crafting pattern and worktable portions show an output when you put a pattern in it, but the blast furnace doesnt respond to any pattern I put in it....

Please let me know.
Thanks

**Comment by ReikaKalseki** [comment]
Unless I am forgetting about some fairly recent change, patterns never worked with left-slot-using type recipes, which the coal coke is, though it does not actually *use* those slots.

This is not a *bug*, but it is not really ideal either. That said, I fail to see the need for a pattern for this recipe.

**Comment by MachiavelliSeraphim** [comment]
I seem to remember at one point being able to put 9 coal in and it would prevent the left slots from being used.

That being said, its been quite a while since i used rotarycraft and may not be remembering correctly.

Im trying to automate coke production with applied energistics and it keeps putting the coal in the left slot first making the recipe not work.

**Comment by ReikaKalseki** [comment]
Try putting some coal in the main 3x3 first. Then it should only insert coal into those slots.

**Comment by MachiavelliSeraphim** [comment]
That works until it runs out.
Then it has to be reset by hand.

I seem to remember someone found away to lock it and I thought it was with the pattern...

Maybe Im just losing my mind.... lol.

Thanks for the time.

**Comment by ReikaKalseki** [comment]
Apparently I *did* change it recently: patterns should only affect the central 3x3 of slots; all other slots should act the same regardless of pattern presence or type.

However, this does not help with coal coke, as it uses the central 3x3.

I am going to add a "disable automation connection" feature to the GUI slots.

**Comment by MachiavelliSeraphim** [comment]
Thank you.

**Comment by ReikaKalseki** [comment]
Done. And more performant now as well. I also added a "do not consume last item" (think Railcraft rolling machine) to help as well, as the "can only refill existing slots" mechanic is still present.
![https://i.imgur.com/IXyMTqI.png](https://i.imgur.com/IXyMTqI.pnghttps://i.imgur.com/647SycW.png)
![https://i.imgur.com/KLnpeoZ.png](https://i.imgur.com/KLnpeoZ.png)

**Comment by MachiavelliSeraphim** [comment]
Thank You.

Love the mods, Chromaticraft is killing me right now... lol.

Have a Great Day!
