### ISSUE TITLE
Biome Painter (TF?) crash

### ISSUE THREAD

**Issue by Chromotron** [ReikaKalseki/Reika_Mods_Issues#181]
Placing a Biome Painter causes the server to crash, at least in the Twilight Forest. It instantly crashes again as soon as that chunk is loaded/a player comes close.

**Comment by ReikaKalseki** [comment]
Log and version?

**Comment by Chromotron** [comment]
Sorry, am still a bit confused by GitHub.

Log: http://pastebin.com/k6mHf084 (or can I upload it somewhere here?)

Versions are your newest ones (7f, or the next lower where there is no f), using CrC, RoC, ReC, GeoStr, VoidM and obviously DragonAPI. On Forge-1448.

Do you also want the server log itself?

**Comment by ReikaKalseki** [comment]
OK, this bug is fixed.
