### ISSUE TITLE
Chromaticraft Casting Table Diamonds Red Background

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [ReikaKalseki/Reika_Mods_Issues#1810]
Ive tried to build a casting room but I keep getting a red background on the casting table diamond icons.

![image](https://user-images.githubusercontent.com/10451525/38841090-b41e5f38-41b0-11e8-865d-e5aa16c164fa.png)

I ran through everything in Single Player in a creative test world and it works.

When there is a problem in single player it gets a circle with a line across it, not a red background.

Any ideas?

**Comment by ReikaKalseki** [comment]
The red line across is still there; it is just being layered on additively for some reason, likely due to the rendering of some item (like the enchanted bags). I can force normal blending.

**Comment by MachiavelliSeraphim** [comment]
Actually it was my fault, I accidentally left Offline Mode enabled on the server.
Once I put it back in Online Mode it went away and started working correctly.
