### ISSUE TITLE
Elemental Manipulator and Autonomous Activator (Thermal Expansion)

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [ReikaKalseki/Reika_Mods_Issues#1811]
Just a heads up, if you use an Autonomous Activator from Thermal Expansion to try to automate casting with an elemental manipulator, it causes an irreparable ticking tile entity fault that makes the world unplayable.

Just sorta almost lost a whole world over it.

Not sure if there's anything you can do about it, but an ominous disclaimer of sorts would be nice... 

Thanks.

**Comment by ReikaKalseki** [comment]
The manipulator should not even *do* anything with fake players using it...

**Comment by MachiavelliSeraphim** [comment]
It definitely caused a ticking tile entity crash.  Had to remove thermal expansion and force start the server to clear the fault.

Lost a goob bit of goodies i had set aside in satchels.... :(

**Comment by ReikaKalseki** [comment]
I added a warning to the lexicon:

`	<wand>
		The manipulator is your first foray into this strange new field of crystal elements and chromatic forces. The tool seems to be your main way of activating blocks, either to start some operation or to change settings on a device. It also seems capable of testing the connectivity of segments of a crystal network, and drawing energy off a pylon into yourself. Because of its strong link to your person, it will not work for other users, nor will it fare well in constructs designed to imitate you.
	</wand>`
