### ISSUE TITLE
Crash while staring a server

### ISSUE THREAD

**Issue by TheAtrial** [ReikaKalseki/Reika_Mods_Issues#1812]
Hi! My eng is bad, so im sorry for this.
I have a crash while starting a server. In single everything work alright with the same modpack
When deleting Cromatic Craft server is perfectly start, so the main trouble in CC, as I think. How can I fix this?
Crash log
https://pastebin.com/MGvx93ay

**Comment by ReikaKalseki** [comment]
#815 #858 #834 #1261
