### ISSUE TITLE
Chromaticraft Structure QoL Suggestion

### ISSUE THREAD

**Issue by Fishy51** [ReikaKalseki/Reika_Mods_Issues#1815]
Just wanted to suggest/request a way to automatically store the password given at the end of the dimension structures for those like me who didn't have the foresight to have paper in front of me (or remember that there is a note section in the lexicon) and for those who didn't realize that the colors were even passwords and would have to complete the same structures again (also me).

Maybe a new tab or a fragment for the lexicon that updates when the password is revealed.

P.S. Appreciate all the hard work and polish that you have put into your mods. Most enjoyment I've had in a while! :D

**Comment by ReikaKalseki** [comment]
There is supposed to be some element of it not being an obvious password, but I do agree that losing it forever is somewhat irritating.

**Comment by Kobra331** [comment]
i don't get it. What Password at the end of the Dimension Strucures? I solved all of them 3 times, i never saw a password o.o.

**Comment by ReikaKalseki** [comment]
Done.

![https://i.imgur.com/2jA9AEQ.png](https://i.imgur.com/2jA9AEQ.png)
