### ISSUE TITLE
Electricraft induction generator unable to receive power from shaft power bus

### ISSUE THREAD

**Issue by dieselfuelonly** [ReikaKalseki/Reika_Mods_Issues#1816]
Just as the title says.  Adding a shaft, bevel gear, etc., allows it to work.  But directly connecting the generator to the power bus does not.

**Comment by ReikaKalseki** [comment]
Fixed.

![https://i.imgur.com/g6xFBDN.png](https://i.imgur.com/g6xFBDN.png)
