### ISSUE TITLE
Geostrata ores missing oredictionary [v19a]

### ISSUE THREAD

**Issue by darklordwonton** [ReikaKalseki/Reika_Mods_Issues#1819]
The ores that are generated by geostrata to use the minerals it adds don't have oredictionary tags set and thus cannot be smelted or processed by machines. This is with v19a for minecraft 1.7.10

**Comment by darklordwonton** [comment]
nevermind I now realize this isn't an issue because they drop the normal ores when mined

**Comment by ReikaKalseki** [comment]
That and they were only half-implemented.
