### ISSUE TITLE
Multi-aura Repeater Crash?

### ISSUE THREAD

**Issue by Reignofmagic** [ReikaKalseki/Reika_Mods_Issues#182]
Hey, just got a crash while I was testing my crystal network (was working on tahara which was my 3rd line to my casting temple).

I was right clicking on the repeater at the temple and crashed after I moved a multi-aura repeater.

Any idea on what could have caused this? Also shouldn't be a problem I have auto-back ups every 30 minutes so not much lost on my end. 
http://pastebin.com/pwRrR6yC

**Comment by kolatra** [comment]
Disable the hidden block in the Railcraft config.

**Comment by Reignofmagic** [comment]
Ah that would probably be it. I still have that world save so I'll disable that then test it next time I boot up. Although I coulda sworn I disabled railcraft hidden block....

**Comment by Reignofmagic** [comment]
@ReikaKalseki 
@Kolatra 

Yes it was the railcraft heat/hidden block. World loads fine after that. Sorry for the hassle.
