### ISSUE TITLE
Crash during worldgen

### ISSUE THREAD

**Issue by Timdual** [ReikaKalseki/Reika_Mods_Issues#1820]
I was just moving in my world when I crashed. I can't access the world anymore:
this is the crash that happened when I was in the world
https://pastebin.com/JCDqDz1Z
this is the crash that happens when I try access it again
https://pastebin.com/JUAsNmwC

**Comment by ReikaKalseki** [comment]
You have a block missing its TileEntity, or alternatively two world data storages disagreeing on what is at a given location; neither of these is my doing.

**Comment by Timdual** [comment]
and how to fix it?

**Comment by ReikaKalseki** [comment]
A world editor would be the simplest choice.

**Comment by Timdual** [comment]
I'm not sure what block I'm supposed to modify?

**Comment by ReikaKalseki** [comment]
The one at the location triggering the crash...?

**Comment by Timdual** [comment]
Yes, but there are multiple tile entities and I can't find one in my vicinity that's related to the crash report.

**Comment by ReikaKalseki** [comment]
The crash report explicitly mentions a location.

EDIT:
Apparently not. Normally it does, but this time it is not including that. Check for block ID loot chest (whatever that ID might be for you).

**Comment by Timdual** [comment]
I don't see any numbers that mention any coordinates.

**Comment by Timdual** [comment]
well, i enabled a forge config that deletes tile entities if they error and i got a new crash
https://pastebin.com/isVAeGDv

**Comment by ReikaKalseki** [comment]
That is the same one from before. And your issue is not that a tile is erroring, but that a block is missing its TileEntity.
