### ISSUE TITLE
Random crash when entity walks on Piezo Crystals [ChromatiCraft]

### ISSUE THREAD

**Issue by LordPINE** [ReikaKalseki/Reika_Mods_Issues#1821]
Our server randomly crashes with the following crash report:
https://pastebin.com/uAXC52QE

This seems to be caused by Piezo Crystals, but I can't find the exact cause. It appears to be related to mobs walking on them however.

Relevant versions:
Chromaticraft V19c
DragonAPI V19c

**Comment by ReikaKalseki** [comment]
This is new, and does not make a lot of sense...try removing other mods.

**Comment by ReikaKalseki** [comment]
Fixed.
