### ISSUE TITLE
RoC pipe/machine interaction with AE2 fluid P2P busses

### ISSUE THREAD

**Issue by dieselfuelonly** [ReikaKalseki/Reika_Mods_Issues#1822]
Would it be possible to allow RoC machines and pipes to push fluids into AE2 fluid P2P buses?  I'm using the buses these to route liquids through my base and have to use some rather ugly workarounds to get this to work.  P2P buses have no problem inserting liquids into tanks/machines, but extracting is another story.  So far the only "pure" way I have found to do this is by using CrC fluid link anchors, which cause quite a bit of FPS lag for me when multiple of them are working.  Maybe the particles could be disabled when particles are set to minimal in video settings?

https://i.imgur.com/5Gjg5Jm.jpg

Maybe this could be a new feature for the pipe pump?  I know that RoC pipes seem to store pipe pressure which I'm sure couldn't be carried through the P2P buses, but perhaps the pipe pump could push directly into P2P buses (or any other container/pipe that can accept liquids), with the throughput mB/t obviously varying on input power into the pump.  Being able to push fluids from a P2P bus directly into a RoC pipe would be wonderful as well.  Here's a picture of what I'm envisioning:

https://i.imgur.com/F0SLJAg.jpg

Finally, one more suggestion for the updated pipe pump - allow the pump itself to directly extract fluids from tanks, machines, etc. - in the following picture, envision the pump being able to directly extract from the crystal tank, with the flow rate and pressure depending on input power.  This would also help solve the issue of a full size crystal tank being completely emptied with the connection of one single bedrock pipe :P

https://i.imgur.com/RxcQPlG.jpg

**Comment by ReikaKalseki** [comment]
No, this is not viable. To actively "push" fluids you would need to actively check for receivable blocks, actively attempt to push that fluid (regardless of whether the fluid is actually pushable (eg a disconnected or full pipe), and you would also need some way to control this behavior.

It is far too much logic and complexity - and computation time - to add for something that is only to avoid a bug/design issue in another mod in the first place.
