### ISSUE TITLE
Bug: Chromaticraft v19c Item distribution node eating items 

### ISSUE THREAD

**Issue by Fishy51** [ReikaKalseki/Reika_Mods_Issues#1823]
The item distribution node seems to destroy items when entered into a system to quickly. 
This was my test setup:
![2018-05-19_19 06 26](https://user-images.githubusercontent.com/38511269/40273440-b9647398-5b9a-11e8-9760-b9daaac82a2f.png)
I had no filter on the extraction node and dirt in the insertion node.
When I quickly placed 4 dirt stacks in the diamond chest the stacks would disappear 2 stacks at a time. When I check the normal chest only 2 stacks of dirt remained. It looks like it will grab multiple stacks per operation but only deposit 1 stack.
Also when the receiving inventory is full it will also just void any items heading to it. I don't know if this is intended but it can be seen as both a pro and con as many storage mods require items to void excess but if used in a processing line the losses could add up.

**Comment by ReikaKalseki** [comment]
I think the actual issue is that the hub is connected to the same inventory you are trying to extract from.

**Comment by Fishy51** [comment]
Here is my second setup:
![2018-05-21_14 05 34](https://user-images.githubusercontent.com/38511269/40324704-dfc9de04-5d13-11e8-8bd5-efc48a543c80.png)

The insertion, distribution and extraction nodes are filtered to cobble and both nodes are linked to the distribution node. When I insert cobble into the chest with the extraction node nothing happens. (To be fair I haven't been able to get any items to move with the extractor in any setup I've tried yet.)

When I insert 2 or more stacks into the chest attached to the distributor quickly it will still grab 2 stacks at a time and deposit 1 stack in the insertion node chest, destroying the other stack.

**Comment by ReikaKalseki** [comment]
It turns out the insertion logic, which requires sucking items from the source input, was destroying items not just on the actual transfer but on the containment check as well (and only for non-ME connection). This was easy to fix.
