### ISSUE TITLE
Crash when elc, exu2 and Forestry are together

### ISSUE THREAD

**Issue by sfmiyuki** [ReikaKalseki/Reika_Mods_Issues#1825]
a very.....Interesting crash, though I don't know WHY, it exists.
It's not Forestry or exu problem, they work together safety without elc. If I use elc only one can be installed or it crashes.
[crash-2018-05-24_20.08.13-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2037507/crash-2018-05-24_20.08.13-client.txt)

**Comment by sfmiyuki** [comment]
It seems that BC can solve this issue. a mod between exu and elc  have BC's api and make forestry confusing (thanks 3tusk).

**Comment by ReikaKalseki** [comment]
Someone is including an old API.

**Comment by OvermindDL1** [comment]
> Someone is including an old API.

Anyone including any other mod's API at all is pretty stupid, that definitely needs to be reported to whoever is including forestry's (or anyone else's other than their own) API, but for now you can delete the forestry API class's from the jar that broke it.

If they want to know how they should actually do it, then they either test for the existence of the class before loading it, or (more properly JVM standards) depend on an API-only jar that should also be included (assuming the authors of the original API do things correctly).
