### ISSUE TITLE
[ChromatiCraft] - Crash on server(Thermos)

### ISSUE THREAD

**Issue by SSKirillSS** [ReikaKalseki/Reika_Mods_Issues#1827]
When I start the server, after some time it turns off with this...
crash-report:
https://pastebin.com/RySFm1e0
and log:
https://pastebin.com/tGW6pzyF

(Any other mods have been removed, I am add only ChromatiCraft and DragonAPI v19)
P.S. - sry for my English, I`m speak Russian.

**Comment by ReikaKalseki** [comment]
#1511 #1564 #658 #828 #1233 #1277 #995 and a lot more.
