### ISSUE TITLE
Receiving zero watts of power causes massively negative pressure in compactor

### ISSUE THREAD

**Issue by Xavion3** [ReikaKalseki/Reika_Mods_Issues#183]
![2015-08-05_02 43 01](https://cloud.githubusercontent.com/assets/3487253/9066563/d175063e-3b1b-11e5-88ed-6952c72d1795.png)
So yeah, while trying it in a test world I geared up the speed of a microturbine high enough to set the power to zero which causes it to very quickly drop in pressure to a ridiculous degree as can be seen.

**Comment by ReikaKalseki** [comment]
Welcome to log(0) = Integer.MIN_VALUE.

That said, I cannot reproduce it. What version is this?
