### ISSUE TITLE
[CC] Bug report, questions, and suggestion

### ISSUE THREAD

**Issue by sfmiyuki** [ReikaKalseki/Reika_Mods_Issues#1830]
I am sorry for bothering and putting so many in a issue. 
Bug: Artificial sky could not "cheat" the Basic Solar Panel in Galacticraft. It may due to the different algorithm to detect sky? Not a big problem because no one will use the panel(I think).

Questions: I have no idea how Extraction Node works.  The only thing I can use distribution node is to transfer sth from the chest with Item distribution Node to the chest with Insertion Node. Would you like to show me a screenshot about these three usage? Or just tell me by words.
By the way, I also cannot find how fabrication duplication works, trying crafting table, but no double productions. 

Suggestion: Sometimes I spend half hour, follow the book to build a structure. When I finished and open the GUI, nothing happened, then have to spend another half hour or more to find out What's wrong. Maybe show Virtual Blocks will be very helpful for building.

**Comment by T5UN4M1** [comment]
You have to connect the item distribution node to an AE network and then the extraction node will pull items from the inventory it's attached to and send them to the AE network.

There may be other ways but I haven't figured them out.

On this screenshot, the item distribution node gets ore from the ender chest, sends them to the extractors, gets the flakes from the extractors and sends them to the furnaces and finally gets the ingots.



![screen](https://user-images.githubusercontent.com/12467635/40861292-d69bd3fe-65e8-11e8-94e5-57cd3a031784.jpg)

**Comment by sfmiyuki** [comment]
@T5UN4M1 Very interesting usage...It must connect to AE network, but when I tried, the flakes are always sent to network instead of Furnaces.
Edit: You set all ores and flakes in Insertion Node filter? That's a great work.

**Comment by ReikaKalseki** [comment]
It does not have to be AE-connected; it can also connect to normal inventories.

Also, if GC's solars are using a custom algorithm, nothing I can do will fix it unless they add an API hook.
