### ISSUE TITLE
[CC] Failure to Start with other mods, InvocationTargetException, Can't Find Snowball

### ISSUE THREAD

**Issue by Darkpixel797** [ReikaKalseki/Reika_Mods_Issues#1831]
https://pastebin.com/tPAuW2qA

**Comment by ReikaKalseki** [comment]
Put that in a pastebin.

**Comment by Darkpixel797** [comment]
Done.

**Comment by ReikaKalseki** [comment]
OK, you have an ASM conflict. Try removing mods, especially "de.sanandrew.core.manpack".

**Comment by Darkpixel797** [comment]
It worked, thanks. Just by curiosity, do you think the issue is on his side or your side?

**Comment by ReikaKalseki** [comment]
Neither; they work independently but not together. That said, his one is the one throwing the exception, so it might be more fragile, and thus more easily fixed.

**Comment by ReikaKalseki** [comment]
Who is the dev of this mod? Does he have a GitHub account to ping here?

**Comment by draknyte1** [comment]
https://github.com/SanAndreasP/SAPManagerPack

**Comment by ReikaKalseki** [comment]
So @SanAndreasP, do you have an idea why [this](https://github.com/ReikaKalseki/DragonAPI/blob/master/ASM/Patchers/RaytracePatcher.java#L33) ASM patch is incompatible with ManagerPack?

**Comment by SanAndreaP** [comment]
AFAIK nothing to do with your raytrace patcher, something's messing with EntityThrowable, it can't find the injection point:
`Caused by: de.sanandrew.core.manpack.transformer.ASMHelper$InvalidNeedleException: Needle not found in Haystack!
    at de.sanandrew.core.manpack.transformer.ASMHelper.findLastNodeFromNeedle(ASMHelper.java:75) ~[SAPManPack-1.7.10-2.5.1.jar:?]
    at de.sanandrew.core.manpack.transformer.TransformEntityThrowable.transformLqThrowable(TransformEntityThrowable.java:63) ~[SAPManPack-1.7.10-2.5.1.jar:?]`

TBF, I have not used coremods anymore since 1.10 and I don't have enough time to fix it myself, as I currently focus on the more recent versions of mods, but anyone's welcome to submit a PR.

**Comment by ReikaKalseki** [comment]
My raytrace patcher *is* 'messing' with EntityThrowable. I am more asking what exactly you do with the same class so we can find the incompatibility.

**Comment by SanAndreaP** [comment]
sorry, that wasn't aparrent to me in the class you've linked.

Anyways, I can't tell you what's wrong (both just try to insert code) and I can only deduce that some other coremod is also messing with the throwable in some way it makes my patch incompatible.

@Darkpixel797 try to reproduce this issue with **only** the Manager Pack and DragonAPI. If it doesn't happen with those mods alone, something else is messing it up.
If it does happen, I'll release the 2.6.0 update that was never released, then you can try if that will work.
Question: why do you have the manager pack in there anyway? As far as I can see from your logs you don't actually have any mod that depends on it.

**Comment by SanAndreaP** [comment]
saw your edit just now and the only way the patch is used is by the EnderStuff+ mod, which has not seen an update for 1.7.10 and could easily be removed.
