### ISSUE TITLE
Odd crash while looking through recipes in NEI

### ISSUE THREAD

**Issue by ToastedEggplant** [ReikaKalseki/Reika_Mods_Issues#1834]
Hello, I'm not entirely sure if this crash is related to your code specifically so I apologize in advance if it is not.
I've linked the crash report [Here](https://pastebin.com/whT8sksB)

**Comment by OvermindDL1** [comment]
This is an error in Binnie's mods, not RotaryCraft, it was already fixed at:
https://github.com/ForestryMC/Binnie/commit/87ccfb36c4706f37885d858925528c0e0528a32f#diff-0b706b067386fcbb2f8b15a79790757d

I.E. you need to update Binnie's Mods.

**Comment by ToastedEggplant** [comment]
Ah, Thank you!
