### ISSUE TITLE
[GeoStrata] "Mostly lava" lava rock deals no damage when walked upon

### ISSUE THREAD

**Issue by HellsingDarge** [ReikaKalseki/Reika_Mods_Issues#1836]
I'm referencing to [this](https://user-images.githubusercontent.com/20254450/41218182-6916bbde-6d84-11e8-80ce-e35c8bc6f3bb.png) block variant
It has a meta of 0, if judged by Minecraft's `/give` command

And on a side note `/dragondonators` doesn't work quite [properly](https://user-images.githubusercontent.com/20254450/41217835-54b5a1d8-6d83-11e8-8b53-c514fb4c1e7a.PNG)

**Comment by ReikaKalseki** [comment]
Fixed in both cases.

**Comment by HellsingDarge** [comment]
Just tested v20a - still [no damage](https://gfycat.com/ShimmeringImpracticalHalcyon)
And least-lava variant seems to be lower than mostly-lava one...

**Comment by ReikaKalseki** [comment]
Fixed.
