### ISSUE TITLE
Flying after changing boots

### ISSUE THREAD

**Issue by RickVenema** [ReikaKalseki/Reika_Mods_Issues#1839]
When using floatstone boots, the flight effect remains active when they are removed. This allows you to fly without having them.

**Comment by Kobra331** [comment]
Do you remove them by Bibliocraft armor stands? I have this bug only after shift-rightclicking this armor stand

**Comment by RickVenema** [comment]
I have it when I open my inventory and remove them whilst flying

**Comment by ReikaKalseki** [comment]
This has been fixed for the next version. As best as is possible at all.
