### ISSUE TITLE
Vanilla Textures/Fonts massively broken

### ISSUE THREAD

**Issue by Xavion3** [ReikaKalseki/Reika_Mods_Issues#184]
I've just got rotarycraft and dragon api installed and everything is a horrible visual mess, most items have bizarre broken textures and the fonts are screwed up as well, blocks seemed to come out relatively fine however and RotaryCraft itself seems perfect.

**Comment by ReikaKalseki** [comment]
Screenshots and mods/forge/version? This is the first report like this.

**Comment by Xavion3** [comment]
Mods are just dragon api and rotarycraft, forge is 1448, version of both mods is 7f.

![2015-08-05_11 06 16](https://cloud.githubusercontent.com/assets/3487253/9076186/6e95252a-3b62-11e5-8756-0b4635cb6463.png)

The [log](https://paste.ee/p/FK7nR) if you wanted it.

**Comment by ReikaKalseki** [comment]
That texture is not one of mine....I have no idea what this is.

**Comment by DarkGuardsman** [comment]
What language do you have the game in? and do you have a custom texture pack?

**Comment by Xavion3** [comment]
English and I don't use texture packs.

As some more possible info I encounter the scenario via copying my custom modpack in multimc and then deleting everything from the mods folder except dragonapi and rotarycraft. The pack is a modified version of FTB infinity with a few mods added, notably reika's mods and mekanism. The issue is also definitely related to rotarycraft, disabling it causes text and textures to work fine (so with just dragonapi) and they work fine normally with the 200ish mods I've got in it.

I'll try and see if I can figure out the minimum extra mods to have the bug not occur actually, forgot to do that.

**Comment by ReikaKalseki** [comment]
This...makes absolutely no sense. You could have reported a bug like "when I use a TiC hammer Ars magica makes a potato drop at my feet, then BuildCraft crashes because there is no such thing as a potato facade" and I would have just as much idea what is going wrong.

**Comment by Xavion3** [comment]
So I've worked out it's not an issue with removing everything else from Infinity, I can make a fresh instance in MultiMC with just those two mods and have the weirdness happen. I figured out the minimum mods to have it not occur though, adding CofHCore and Thermal Foundation fixes things. So something about Thermal Foundation fixes the issue if that's any help to you. It's also not an issue with MultiMC instances or starting through it, I can use a modified FTB pack through the FTB launcher and it will still occur.

I can try checking anything if you want but that's what I know so far.

**Comment by ReikaKalseki** [comment]
Just throwing things against the wall, try vary all you can of the following:

Forge version
Java Version
OS

**Comment by Xavion3** [comment]
Error still occurs with Forge 1400 and 1472, and with Java 6. That is with the exception that with Java 6 adding Thermal Foundation does not fix things. I'll try and see if it occurs on windows as well soon, I've been testing on OS X.

**Comment by DarkGuardsman** [comment]
I suggest using java 7 as most mods are still compiled against it. As well your last log shows you using java 8 even though something is loading java 6 jdk. 

Might I also suggest checking your graphics drivers and see if they are updated. Most likely its not the cause but sometimes it happens. 

Another thing to try is loading up the mods in a normal vanilla launcher with just forge installed. The FTB packs could have extra coded installed in there mc.jars.

**Comment by Xavion3** [comment]
Well my only log so far was with java 8, Java 7 does nothing to change it either, it behaves like Java 6 in not having adding Thermal Foundation do anything do.

It's also not an issue with FTB, as mentioned I can create a new instance in MultiMC with just DragonAPI and RotaryCraft added and still have the issue occur.

**Comment by Xavion3** [comment]
Bug did not occur on windows 8, updating everything on mac didn't fix the issue however.

**Comment by ReikaKalseki** [comment]
So it is OS (or hardware) specific...

**Comment by Xavion3** [comment]
Problem solved, well I found out it's [an issue with forge](https://github.com/MinecraftForge/MinecraftForge/issues/1829) on macs at least. No idea why it seemed to be linked to rotarycraft.
