### ISSUE TITLE
DrangonAPI, Rotarycraft, Reactorcraft, Electricraft, Cromaticraft crash

### ISSUE THREAD

**Issue by MrProton657** [ReikaKalseki/Reika_Mods_Issues#1840]
Hi guys, (@ReikaKalseki ) I have a problem: if I add the mods above my minecraft not crashes, but then I start minercraft, the launcher returns! Log: https://pastebin.com/bhEshVPf
Rotarycraft version: V19c
DragonAPI version: V19c
Reactorcraft version: V19c
Cromaticraft version: V19c
Electricraft version: V19b
MC version: 1.7.10
Forge Version: 10.13.4.1614

**Comment by ReikaKalseki** [comment]
This is either due to KCauldron/Bukkit/Thermos/whatever or a mod ASM conflict; you have a great many random mods which are possible culprits; try removing some.

**Comment by MrProton657** [comment]
Solved! TheProblem was Thaumic Infusion! Thank you Reika for your great mods!

**Comment by ReikaKalseki** [comment]
For reference #895 #1003 #1186 #1480 #995 #1094 #1079 #1601
