### ISSUE TITLE
Crash after reloading world with crystal repeaters

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#1841]
When I use the crystal repeaters, they will occasionally, after logging back into a world, make the "repeater is disconnected" sound. When I then try to fix all of them, I must fly out to the pylon or close to it, and then replace a repeater so that the chain will function again. When I then try to close and reopen the world (Hit save & quit to title, then reopen the world), I get this crash: [](url)https://pastebin.com/wwLqh1yD. Then, when I reload the world again, I have no crash, but many of my pylons are disconnected again.

**Comment by OvermindDL1** [comment]
Huh, wow, it's not a crash in the crystal network for once, looks like it is in the recipe handler (something changed recipes while the recipe list was being iterated, a big big big no-no, some modder screwed up as you *DON'T* mutate an arraylist while it is being iterated), so it might be legit, however now the question is which mod specifically is doing stupid things like mutating an arraylist while it is being iterated (java's stacktraces are really crappy at these points...)...

**Comment by voidsong-dragonfly** [comment]
Is there anything else I can give you to help?

**Comment by OvermindDL1** [comment]
> Is there anything else I can give you to help?

At this point, thanks to java's crappy CME stacktraces, the best thing would probably to start try removing mods and try to replicate the crash again until you find the mod that causes it, unless you know how to use a java debugger?

**Comment by voidsong-dragonfly** [comment]
I do not know how to use a debugger. I will remove mods.

**Comment by voidsong-dragonfly** [comment]
The crash is not happening any more, even with the original set of mods. All of my repeaters are staying connected as well. I have no clue why the starting circumstances are not happening anymore. Sorry for being of no help.

**Comment by OvermindDL1** [comment]
CME's are not always reliable to reproduce, they are *very* situation specific and if the world state changes then that situation can be gone.  If you are able to reliably reproduce it with a save then start the mod removing bit again to see what the cause is.   :-)

If only modders would learn to not mutate arraylists while they are being iterated, so many do that so wrong...  ^.^;

**Comment by voidsong-dragonfly** [comment]
[https://pastebin.com/kNV59V62](url) New CME, this time it mentions fastcraft. I was trying to cast something and then this happens. It does not seem to happen without it, however my computer has a hard time so there is not much I can do.

**Comment by OvermindDL1** [comment]
Hmm, no that's a normal fastcraft location (fastcraft gets injected into lots of stacktraces when it is installed, even if entirely unrelated to the issue).  What this indicates is that an arraylist was being iterated, calls were being made, some mod mutated the arraylist at this time, then it returned back to the fastcraft iteration (which is just a normal MC iteration), which then checked for a concurrent modification, which then failed then threw the exception.

So it does not seem to happen without performing a casting, or without fastcraft (which is generally a red herring)?

EDIT:  For note, that stacktrace is the Entity update loop as I recall, so it was probably the player callback upon click to perform the casting.

**Comment by voidsong-dragonfly** [comment]
It did not seem to, however my conputer was not having a good time so I was not in my world for very long. It did not happen without doing casting.

**Comment by OvermindDL1** [comment]
Yeah so that leans to something in Chromaticraft/DragonAPI is mutating the entity arraylist during it's callback instead of deferring as should be done.  I'm surprised you found such a reproduceable example though, usually hard to get.  Can you upload the save and mods and configs that reproduces it reliably somewhere along with instructions on what to do?  :-)

**Comment by voidsong-dragonfly** [comment]
I can try, hopefully(or not?) it will stay repeatable long enough to be fixed.

**Comment by voidsong-dragonfly** [comment]
My base is at ~30, 64, -100 with the item I was trying to cast (Power Crystals) still in the stands. Hopefully starting casting it will trigger the CME.  [https://www.dropbox.com/sh/ecmkhd8h2may7pa/AAC9sGpz5Dv1clRoDBoo649Oa?dl=0](url) Link for dropbox. Also, if you try to take items out of my ME system you may also get a crash similar to this [https://pastebin.com/R0U6RDHD](url) I did not get a CME when I tried to start crafting again, you may be able to. Hope this helps!

**Comment by OvermindDL1** [comment]
Cool, savegames are awesome for Reika as he can then debug in to it, now to wait.  :-)

And clickable URLs:
https://www.dropbox.com/sh/ecmkhd8h2may7pa/AAC9sGpz5Dv1clRoDBoo649Oa?dl=0
https://pastebin.com/R0U6RDHD

And top of the stacktrace (Reikamods are the only mods in the entire stacktrace) for documentation reasons:
```java
java.lang.NullPointerException: Exception preparing structure feature
    at Reika.DragonAPI.Libraries.World.ReikaBiomeHelper.getParentBiomeType(ReikaBiomeHelper.java:232)
    at Reika.CaveControl.CaveLoader.getDefinition(CaveLoader.java:173)
    at Reika.CaveControl.Generators.ControllableMineshaftGen.getConfig(ControllableMineshaftGen.java:44)
    at Reika.CaveControl.Generators.ControllableMineshaftGen.func_75047_a(ControllableMineshaftGen.java:37)
    at net.minecraft.world.gen.structure.MapGenStructure.func_151538_a(MapGenStructure.java:38)
```

**Comment by ReikaKalseki** [comment]
Fixed.
