### ISSUE TITLE
Crash with NEI and Reika's mods

### ISSUE THREAD

**Issue by MrProton657** [ReikaKalseki/Reika_Mods_Issues#1842]
Hi @ReikaKalseki, after finally solved many id conflicts with ChromatiCraft and Biomes' O Plenty, MC finally started. But the I go into a World, and pressing R on a random recipe in NEI MC is "No Response" and nothing is happing anymore.
full log: https://pastebin.com/DB31npXi
I think this is a problem with one from your mods (RotaryCraft, ReactorCraft, ElectriCraft, ChromartiCraft or DragonAPI) because before I had added them, all works fine.
I had seen many bugs like this (https://github.com/Chicken-Bones/NotEnoughItems/issues/360, https://forum.feed-the-beast.com/threads/rotarycraft-crashing-with-nei.49682), but no one from there could me help out.
I hope you can help me somehow, because I really want to play with your great mods!

MrProton657

**Comment by OvermindDL1** [comment]
There is no stacktrace in your log, so it did not crash, the title is inaccurate.

As an aside, your item count is huge, and accessing NEI the first time with Reika's mods in such a setup (and in a few other cases) can easily take 20 minutes the first time per run while it repeatedly scans the recipe map inefficiently to build up a cache.  How long did you wait?

**Comment by MrProton657** [comment]
About 10 minutes, may I have to wait longer? Lets try...

**Comment by OvermindDL1** [comment]
> About 10 minutes, may I have to wait longer? Lets try...

Yeah, sad to say that with some particularly large mod sets combined with Reikamods I've seen it take 30-40 minutes (yet without Reikamods it takes about 20 seconds the first time).

**Comment by MrProton657** [comment]
is it only the first time? If it is then it is ok, but I don't want to wait 40 minutes every time I have to look on a recipe XD

**Comment by MrProton657** [comment]
Thank You! It didn't take so much time only 12 minutes! (my pc is good)

**Comment by OvermindDL1** [comment]
> Thank You! It didn't take so much time only 12 minutes! (my pc is good)

Cool, and yep only the first time per run.  That does mean when closing and re-loading your game it will have to do it again, but only once per gameplay session.  :-)
