### ISSUE TITLE
[CrC]Freeze When Activating Memory Crystal

### ISSUE THREAD

**Issue by Fishy51** [ReikaKalseki/Reika_Mods_Issues#1843]
About 25% of the time when trying to bring up the hexgrid for the first time in a session minecraft will freeze. Music can still be heard if in the dimension but everything else is frozen, eventually I have to manually close the program (program is not responding message) and no crash report is given. 

The log files also seem to cut off at the time I right clicked to bring up the grid.
https://pastebin.com/TPNGxScj

**Comment by ReikaKalseki** [comment]
This needs further info, which v20 will be able to give.

**Comment by Fishy51** [comment]
I can try to send my world save if you would like. Although I am not sure the best method to do so. It also suffers from cronic CME as well.

**Comment by ReikaKalseki** [comment]
Does v20 fix your issue?

**Comment by Fishy51** [comment]
I updated my world to v20 and I get this crash when I try to use the crystal.

https://pastebin.com/fD7XiqzX

**Comment by ReikaKalseki** [comment]
Fixed.
