### ISSUE TITLE
[CrC] Crashing on load with Thaumcraft installed

### ISSUE THREAD

**Issue by rbb30** [ReikaKalseki/Reika_Mods_Issues#1845]
I was playing a personal pack I made today at stable 60 fps and when I decided to add Thaumcraft and some addons to it, the game crashed on load several times.

Crash report: https://pastebin.com/Wz0FBeyq

**Comment by ReikaKalseki** [comment]
If your TC version is not outdated, then someone is shipping a very old TC API. Try removing mods.
