### ISSUE TITLE
Modifying furnace recipe causes game to freeze.

### ISSUE THREAD

**Issue by shagejack** [ReikaKalseki/Reika_Mods_Issues#1846]
Looking up any recipe after modifying furnace recipe caused my client to freeze. And the log seemed to be looping. It has generated a 2 GB log. 
Here's the looping part.
https://pastebin.com/0VjBLr03
No, I tried to remove the Extra Utilities mod, it just didn't work.
Sorry for my poor grammar, English is not my main language.

**Comment by ReikaKalseki** [comment]
While there does appear to be a bug here, it is being triggered by your adding a recipe whose input is invalid in some way; try fixing that.

**Comment by shagejack** [comment]
But all my scripts were removing recipes instead of removing them.

Here are MT scripts:
furnace.remove(<minecraft:iron_ingot>,<minecraft:iron_ore>);
furnace.remove(<minecraft:gold_ingot>,<minecraft:gold_ore>);
furnace.remove(<minecraft:iron_ingot>,<FortuneOres:oreChunk>);
furnace.remove(<minecraft:gold_ingot>,<FortuneOres:oreChunk:1>);
furnace.remove(<libVulpes:libVulpesproductingot:4>,<FortuneOres:oreChunk:2>);
furnace.remove(<libVulpes:libVulpesproductingot:5>,<FortuneOres:oreChunk:3>);
furnace.remove(<IC2:itemIngot:5>,<FortuneOres:oreChunk:4>);
furnace.remove(<IC2:itemIngot:6>,<FortuneOres:oreChunk:5>);

furnace.remove(<mw:SteelIngot>,<mw:SteelDust>);
furnace.remove(<OpenComputers:item:32>,<OpenComputers:item:30>);

//furnace.remove(<*>,<TConstruct:oreBerries:2>);
//furnace.remove(<*>,<TConstruct:oreBerries>);
//furnace.remove(<*>,<TConstruct:oreBerries:1>);
//furnace.remove(<*>,<TConstruct:oreBerries:3>);

furnace.remove(<Thaumcraft:ItemResource:14>,<Thaumcraft:ItemShard:6>);

furnace.remove(<minecraft:coal:1>);

furnace.remove(<Mekanism:Ingot:4>,<Mekanism:OtherDust:1>);

**Comment by ReikaKalseki** [comment]
Then either MT makes invalid recipes as part of the process (which does not seem terribly likely to me) or those lines are not where the problem lies.

**Comment by shagejack** [comment]
I got something weird... This problem didn't appear while I was playing in the server.

**Comment by ReikaKalseki** [comment]
I had an idea for a fix:

![https://i.imgur.com/BmrKROR.png](https://i.imgur.com/BmrKROR.png)

**Comment by AnrDaemon** [comment]
@ShageJack can you show your modlist?

**Comment by shagejack** [comment]
All right... Even though this could be meaningless(321 mods active).
https://pastebin.com/d6csycWW

**Comment by AnrDaemon** [comment]
Why? It was very informative. [Update modtweaker](https://minecraft.curseforge.com/projects/crafttweaker/files?filter-game-version=2020709689%3A4449), please.

**Comment by ReikaKalseki** [comment]
Fixed.
