### ISSUE TITLE
[CrC] Game doesnt launch with OpenComputers

### ISSUE THREAD

**Issue by rbb30** [ReikaKalseki/Reika_Mods_Issues#1848]
So I added OpenComputers and the game doesnt seem to crash I've tried to do it without OCJS (OpenComputers addon) and it still crashes when launching don't know what the problem might be.

https://pastebin.com/1GBMhzws

**Comment by ReikaKalseki** [comment]
#1732 #1683 #1681 #1493 #1257 #1280 #1238 #481
