### ISSUE TITLE
Ammonium Nitrate uncraftable

### ISSUE THREAD

**Issue by Xavion3** [ReikaKalseki/Reika_Mods_Issues#185]
This is reproducible with only rotarycraft and dragonapi, I think it's because when adding the shapeless recipes you used the oredict entry "redstone" instead of "dustRedstone". This is corroborated by the fact adding redstone dust to the oredict entry of "redstone" with minetweaker makes the recipe work.

**Comment by ReikaKalseki** [comment]
Fixed.
