### ISSUE TITLE
[RoC/ElC] Request: vertical power distribution/splitting

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1850]
Currently Shaft Power Bus only works on horizontal plane, and due to #1849 ElC cannot distribute power to a full vertical stack either. I would like to have full-stack vertical distribution for purposes of better-looking fermenter towers as well as any other case where vertical stacks could be desirable for aesthetic reasons.

Whether through making SPB vertical as well, making induction motors stackable, or adding something new for it wholesale (e.g. several-output-blocks belt/chain drives).

**Comment by ReikaKalseki** [comment]
I enabled the bus to work vertically.

![https://i.imgur.com/Za5zTXt.png](https://i.imgur.com/Za5zTXt.png)
