### ISSUE TITLE
[RoC v20a] Worktable error?[API v20b]

### ISSUE THREAD

**Issue by monatann** [ReikaKalseki/Reika_Mods_Issues#1853]
Hi Reika, thank you for making nice mod:)
I'm sorry for my poor English.

<ul>
<li>Forge 10.13.4.1614</li>
<li>DragonAPI v20b</li>
<li>RotaryCraft v20a</li>
<li>Java 64bit 1.8.0_51</li>
</ul>

When I make modpack, it always crashes because of this error.
(Maybe it's my fault? I go back to check what mods conflict. There are 300+ mods lol.)
https://pastebin.com/7wF5J1mN<br>

I wondered there are errors in "WorktableRecipes", so I tried to check Workstable without other mods. Then I found this error.
<img src="https://i.imgur.com/IdhWVwK.png">
<img src="https://i.imgur.com/5oj1HCz.png">
<img src="https://i.imgur.com/GbK4meU.png">
I played 19c and there is no error, so I thought this is 20a bug...

If I say something wrong, I sincerely apologize to you.

I'm sorry for your inconvenience.

**Comment by ReikaKalseki** [comment]
This is indeed a mod interaction. Try removing mods.

**Comment by ReikaKalseki** [comment]
Fixed.

![https://i.imgur.com/Be0UKnb.png](https://i.imgur.com/Be0UKnb.png)

**Comment by monatann** [comment]
Hi, Reika, I apologize for the long delay in my response.

After updating 20c, all errors are disappeared! And my modpack has no crush! Thank you very much!

One day I will ask you for modpack permission after making:)
