### ISSUE TITLE
Still crashes when launch GC rocket tier 3 [API v20b]

### ISSUE THREAD

**Issue by vrnRaptor** [ReikaKalseki/Reika_Mods_Issues#1854]
When using API v15a everything was fine.
Mods:
DragonAPI v20b
GalacticraftCore v3.0.12.504
GalacticraftPlanets v3.0.12.504
MicdoodleCore v3.0.12.504
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2216795/latest.log)

**Comment by ReikaKalseki** [comment]
I have another potential fix. Test it in v20c later today.

**Comment by ReikaKalseki** [comment]
And another proper fix is coming this time in v21.
