### ISSUE TITLE
GeoStrata chisel API dependency?

### ISSUE THREAD

**Issue by jpmv2020** [ReikaKalseki/Reika_Mods_Issues#1855]
Hi, I was making a modpack (just for testing purposes) and it worked really fine... But then, I added some of your mods (all latest version), and i keep geting this crash ( https://pastebin.com/0Gdkx2b7 ).
I already tested only with the mods that I had before and "Dragon API", and it works normal, but when I had something like "RoteryCraft", it gives this error (same with the other mods that are dependent of rotery and GeoStrata).

If you could help in anyway I would be so thankfull, becouse I really like your mods, and I would enjoy, being able to run a server with them on a modpack.

PS: the Optifine/EnderIO error doesn't affect anything, I already tested.
PS2: The Server that I prettend to run, is basically a thing between 5 friends.

**Comment by voidsong-dragonfly** [comment]
With any section of mods, does the error “cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/cricketcraft/chisel/api/carving/ICarvingGroup” still happen? Because that seems to be only connected to GeoStrata.

EDIT:Also, what is ‘cricketcraft’

**Comment by jpmv2020** [comment]
No, it doesn't... I will try without GeoStrata, and say something. Thx

EDIT: cricketcraft is related to chisel in some maner... maybe is an core mod or api, something like that, but it isn't "a mod", like, is not on the mods folder or sub-folders

**Comment by voidsong-dragonfly** [comment]
What is the error without GeoStrata? Yeah, I have no clue what CricketCraft is either, I can’t find it in the 1.7 chisel github.

**Comment by jpmv2020** [comment]
Without it, the error is Ars Magica 2 id's are the same as some in rotary mods. And without AM2 the mods run all as normal, wich is good. Now I just have to figure out how to change the id that I need...

**Comment by voidsong-dragonfly** [comment]
It is the rotarycraft freeze potion wih ars magica’s growth potion I thought. Both should be in their config. Actually, could you edit the title to something closer to “Geostrata and chisel issue?” As a side note, I have no issues with Geostrata and chisel.

**Comment by jpmv2020** [comment]
Ok, I will try to fix that.
Thanks for your help and time :)

**Comment by ReikaKalseki** [comment]
No, the issue is that there are two forks of chisel, and I can only have compatibility with one.

**Comment by ReikaKalseki** [comment]
Fixed the crash, however.
