### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by superseth1** [ReikaKalseki/Reika_Mods_Issues#1856]
Error: Reika.DragonAPI.Exception.IDConflictException: The mods were not installed correctly: 
https://pastebin.com/UHpa1S6r is the crash log
i have them all in my mods folder thats where i put them right
i also have a bunch of mods and electricraft rotarycraft reactorcraft chromaticcraft and dragonapi

**Comment by superseth1** [comment]
i have them all in my mods folder thats where i put them right 
i also have a bunch of mods and electricraft rotarycraft reactorcraft chromaticcraft and dragonapi

**Comment by ReikaKalseki** [comment]
Read it. Why? Well, among other things, it contained this:

`This is NOT a mod bug. Do not post it or ask for support or you will look lazy or extremely foolish.`
