### ISSUE TITLE
Questions:Other Versions ,Fps

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#1859]
So i tried playing your mods a long time ago on 1.7.10 but it was to laggy back then now i have a better PC but my real question is why are you still modding on 1.7.10 its very very old i know that many people think 1.7.10 is the best version for modding because nearly any mod has at least on release on it but still versions for newer versions like 1.12.2 would be cool.

**Comment by Kobra331** [comment]
https://www.reddit.com/r/feedthebeast/comments/4x8jgi/a_tale_of_broken_code_hopes_and_respect_or_why_i/

**Comment by ghost** [comment]
thanks that probably means ill never be able to play these mods.kinda sad.

**Comment by ReikaKalseki** [comment]
Now that my internet is back:

**Comment by ghost** [comment]
sorry i dindt know that ok the faq on your website was old and didnt mention it and i had know idea that you had it explained on reddit
