### ISSUE TITLE
[RoC] Blast Furnace Automation Button Tooltip Render Error [20c]

### ISSUE THREAD

**Issue by Ceriole** [ReikaKalseki/Reika_Mods_Issues#1860]
The tooltip for the automation button in the blast furnace is rendered behind other foreground items. Running RotaryCraft 1.7.10 version 20c. See image:
![screen](https://user-images.githubusercontent.com/6519738/43165395-d3566c52-8f61-11e8-8a7b-63f62e846409.png)

**Comment by ReikaKalseki** [comment]
This is not really fixable, much less in a reasonable amount of effort.
