### ISSUE TITLE
[RoC] Recipe For Worktable Is Made In The Worktable [21a]

### ISSUE THREAD

**Issue by Ceriole** [ReikaKalseki/Reika_Mods_Issues#1861]
The recipe for the worktable is only able to be made in the worktable. Running 1.7.10 RotaryCraft 20c. See Images:
![screen](https://user-images.githubusercontent.com/6519738/43166690-33fe2b14-8f65-11e8-9fd3-3d8ebc39855b.png)
![screen1](https://user-images.githubusercontent.com/6519738/43166694-364fb00e-8f65-11e8-949d-eae58dd79156.png)

**Comment by ReikaKalseki** [comment]
Is this with or without the crafting-table-machines config?

**Comment by Ceriole** [comment]
Reika,

“Crafting Table can Make Machines” is false in my config. Would that setting cause it to be unable to be crafted as the Worktable would be considered a machine?

Thanks,
Richard Abbott

________________________________

**Comment by ReikaKalseki** [comment]
Try with the setting on; does the recipe work now?

**Comment by Ceriole** [comment]
Yeah, setting the config to true lets me craft it.

**Comment by ReikaKalseki** [comment]
Hopefully fixed.

**Comment by lAimBotl** [comment]
the latest version (the one you posted today) also has it.

" B:"Crafting Table can Make Machines"=true/false " either way the recipe is the same.

**Comment by ReikaKalseki** [comment]
Fixed.
