### ISSUE TITLE
Client crash when clicking ExtraBees alveary parts

### ISSUE THREAD

**Issue by Kataiser9** [ReikaKalseki/Reika_Mods_Issues#1862]
v20c. Tested on a minimal install (ChC, Binnie's + patcher, NEI, and dependencies). Crash report: https://pastebin.com/KGX2Wt8j - I _think_ this happens with all ExtraBees alveary blocks, but I mostly tested with Frame Housing.

To reproduce, simply place a Frame Housing block in the world, then right-click it. Shift-click and whether or not you're holding anything seem to have no impact; this will always cause a crash as far as I've tested. Unsure if it makes a difference whether the alveary is fully built.

**Comment by ReikaKalseki** [comment]
You are using an out-of-date version of Forestry or ExtraBees.
