### ISSUE TITLE
[RoC] Suggestion: Bigger versions of hydrokinetic generators and wind turbines.

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1863]
Rotarycraft to me was always about complex, dangerous and bulky machines whirring around, drilling in my ears. This, however isn't the case with the aforementioned two engines. 

While hydrokinetic generators do make sense in their size, since water is channeled through a small hole in a dam for increased pressure, an array of interconnected 3mx3m turbines would work. So while I'd much appreciate a bigger version off these, they're alright. 

But wind turbines are these, flimsy, little _toys._ A faint shadow of their real life counter parts. In game, yeah, they work in their way, but they don't have the pzazz of other Rotary/Reactorcraft engines.

Would you consider adding a real life scale (maybe 1:2, considering it'll be about in 20-80 meter range for just the blades) wind turbines? Maybe gated through bedrock shafts, to prevent people from skipping other setups. Adding wind variability to these will also might create some interesting considerations as well. 

Maybe also having some vertical wind turbines with less/no variability as an alternative. These would also have the interesting side effect of being somewhat stackable like solar towers.

**Comment by Kobra331** [comment]
+ 1 for better windturbines. They look so small and more like a fan. Maybe we can "upgrade" them with 4 turbine blade blocks to increase their size to the immersive engineering wind generator size.

**Comment by OvermindDL1** [comment]
As a point of note, there's wind farms everywhere around where I live, the wind turbines are easily 15+ stories tall, and I've seen the blades being driven down the road via a convoy, a single blade is around 4 tractor trailers long, maybe 200 feet.  And they haul quickly for their size when they are being moved by the wind, they make an audible noise.  They auto-rotate to face the wind, they will even veer to face more upwards to slow down in the event of storms (auto-throttling based on speed to keep it below a set max), and if the max speed ever does happen to be hit (can happen here, we get gusts above 100mph at times of the year) then they automatically flip their circuit to supply it's own generated power back into itself to brake the motor, which quickly slows it down to a very slow but constant turn.

And they generate a massive amount of power, fed to the surrounding *states*

**Comment by ReikaKalseki** [comment]
Like #1865.

**Comment by cheesealmighty** [comment]
_You're tearing me apart, Reika!_ 
https://youtu.be/ptmM-m7Cl8U

But joke's aside, while the other idea will require a lot of coding and testing, this one could -I assume- be accomplished by just scaling the model and adding a recipe for it. 

_I just want a wind turbine that has it's blades few times bigger than the generator it's attached to, that's all._

**Comment by ReikaKalseki** [comment]
You are suggesting an entirely new machine, likely a multiblock, as a new engine with a larger power output - and all the resultant balancing uncertainty *that* implies.

**Comment by OvermindDL1** [comment]
For note, #1865 does not include wind turbines, thus the `Like #1865` is inaccurate and incorrect.

**Comment by cheesealmighty** [comment]
@ReikaKalseki 
 I'm indeed aware of that. I know the challenge here isn't the making it a big thing, it's the balance. This is why I suggested them having bedrock cores/shafts. Basically gating it behind the bedrock breaker.

 And once you reach that level, it wouldn't matter much if you're dropping water from 60 blocks high and supplying it with lubricant, or having a 60 block tower (perhaps requires lubricant) that does a similar job but also looks impressive. _It's not that hard to build a fully automated lubricant factory._

 The issue here is that water in minecraft doesn't simulate the real life infrastructure needs of a hydroelectric plant. And subsequently "hydrokinetic" engines are creating energy out of nothing. They make _some_ sense if you're powering a boring machine down in the mines, since you can make it come from a river, for instance (doesn't really answer where the water would go after that really, but eh). 

 What I'm asking for is basically an over the ground version of that. Something to power your day to day machines. _Instead of the glorified weather vane we currently have._ Also, if you just ask someone on the street, "Hey, what's the first thing pops to your mind when I say rotating electric generator?", the answer will probably be wind mill. So I really wouldn't call that a "small feature", frankly. 


PS: Also, this is not an attempt to, uh, insult? Yeah I guess, insult you. It's your mod, if you think that's best, sure, your call, you know the intricacies better than anyone would. But as a player of god knows how many years of modded minecraft, this is how I feel about it.

Edit: *Sigh* Pardon my strong feelings about this. It's just that, your mod captures the essence of so many good things about the old days of modding, _dangerously fun_ and yet complex in the ways you could set it up. I feel somewhat bitter when it falls short in some aspects.
