### ISSUE TITLE
[ElC] Question: Long range energy transmission methods and chunk loading requirement

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1864]
Say I have a nuclear reactor/hydroelectric dam in a facility far away, in order to transfer energy do I need to chunk load every piece of wire/shaft? Or do they have a similar function to Immersive Engineering cables?

I can always do a:  
"Load it up to batteries->Block break->Carry with trains->Break the empties->Place down" loop. But I wanted to check before I start anything big. Using the power to create ethanol and carrying it with tankers would also work/make sense I reckon. 

PS: _There will be stabbings if anyone mentions tesseracts_

**Comment by ReikaKalseki** [comment]
CC world rifts can carry ElC wires directly, and RC shafts can go through most portals. Then you only need chunkload both ends (and world rifts chunkload themselves).

**Comment by cheesealmighty** [comment]
Aww. Shame. I kind of hoped there'd be a good form of semi-realistic overworld transfer. I guess I'll consider the fuel tanker option. Thanks.
