### ISSUE TITLE
[RoC] Suggestion: Run-of-the-river hydroelectricity

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1865]
I believe currently hydrokinetic engines check for water source placed above them and do calculations according to distance traveled down. While this offers variety of builds to be accomplished, it limits the layout of the facility. And it encourages players to build some contraptions that don't make much sense in real world `*cough*` _wall of water, because whatever_ `*unconvincing cough*`.

My suggestion is adding: 
 -Inlet pipe: This'd be where water source block calculation would start.
 -Penstock pipe: This'll be a connector pipe, where water will gain momentum.
 -Outlet pipe: This is the part where it'll "connect" to the hydrokinetic engine. This'll probably look better 
   if it renders water coming out of it.
 Optional: Horizontally placed hydrokinetic engines. To better accommodate this setup. 

This way, you'd be able to build a pipe coming down from the mountain spring/somewhere upstream, gaining momentum, then hitting the blades of the turbine, then be connected back to a naturally generated river. 

Note: This is quite out of my field, so my understanding of these structures might be off, despite my efforts. _Be gentle._

**Comment by ReikaKalseki** [comment]
This, while not bad ideas, is far too much detail and implementation time for a comparatively small feature in the mod.
