### ISSUE TITLE
Fire spread crash?

### ISSUE THREAD

**Issue by Fishy51** [ReikaKalseki/Reika_Mods_Issues#1866]
I started a new world and about an hour in while exploring I had this crash.

https://pastebin.com/r9JW8gCc

I haven't been able to recreate it yet, but I figured it best to at least mention it.

**Comment by ReikaKalseki** [comment]
BlockSpreadEvent is used for grass (and mycelium) spreading control. This code is neither new nor related to worldgen. If it happens again, post here.

**Comment by ReikaKalseki** [comment]
Any updates?

**Comment by Fishy51** [comment]
Hasn't happened again so it was probably just a rare random crash.
