### ISSUE TITLE
[Expanded Redstone] Bug: Setting "Ticking Noises" is not client sided. Intended?

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1867]
Setting "Ticking Noises" to False in client only works in singleplayer. When I join to my server, _I can hear the incessant sound of the ticking of those damn redstone clocks ticking to my magnetizers._ The hell only stops when I change the config settings on the server as well. Is this intended behavior?

PS: No, I haven't started a server without permission, Reika. I'm playing on my own, just subsidizing the calculations to my server till I get the -hopefully- greenlight from you.

**Comment by ReikaKalseki** [comment]
The Minecraft sound system is on the server side, not the client.

**Comment by cheesealmighty** [comment]
Yup, that'd explain it, thanks.
