### ISSUE TITLE
World Gen issues

### ISSUE THREAD

**Issue by 1skandar** [ReikaKalseki/Reika_Mods_Issues#1868]
I'm still tracking this down, but I added Roc, ReactorCraft and Electricraft to an existing modpack and all of a sudden world gen slowed down to a crawl. Creating a new world from scratch took two or three minutes and generating new chunks was extremely slow. And there was severe rubberbanding for the first few minutes on logging into a world. 

This issue is *not* present with just Chromaticraft and DragonAPI. I'm still not exactly sure the underlying cause, as I made several changes to the pack and I'm trying to untangle everything and see if I have a cross mod issue or what is going on. 

I'll update this as I get more info, thanks.

**Comment by 1skandar** [comment]
Ok, fresh instance with just DragonAPI and Chromaticraft world gen was normal. Adding in RoC didn't add in any appreciable slowdown. However, adding in Reactorcraft and finally Electricraft did, to the point where I could catch up to world gen and had to wait up to 30 seconds for new chunks to generate. However, this seems to be inconsistent. Some worlds are fine, and some just aren't.

I'm not sure what is up. I have a decent computer, even if it is 3 years old. 16 GB RAM (8 dedicated to MC), a NVIDIA 970 and i5 and normally I don't have this issue.  

I'll continue to poke at it. This is a weird issue.

**Comment by ReikaKalseki** [comment]
RC has just been found to have an issue with slowing worldgen due to network overload. I have fixed it in the code but DragonAPI is not yet ready for public release.

![https://i.imgur.com/9uKOp6K.png](https://i.imgur.com/9uKOp6K.png)
![https://i.imgur.com/16XUnTR.png](https://i.imgur.com/16XUnTR.png)

**Comment by 1skandar** [comment]
Oops. I find the best issues. Ok, is there any kind of band-aid fix I can do until DragonAPI updates?

**Comment by ReikaKalseki** [comment]
If you can modulate who watches a Forge event, yes. But unless there is a mod to specifically remove hooks from the Forge event bus registrar, I do not know.

**Comment by 1skandar** [comment]
Beyond my abilities. Ah well. Well, at least it is a known thing and a fix is coming. That is all that matters.

**Comment by ReikaKalseki** [comment]
It should not be long.
