### ISSUE TITLE
Casting Table isn't triggering progression when placed

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1869]
Just made my first Casting Table in a new world, but when I place it, nothing happens. Is there now an additional requirement? None of the fragments I have are for things to make in the table, and I have several blank ones yet to be revealed.
![2018-07-28_22 13 57](https://user-images.githubusercontent.com/6917535/43363193-19b4de2c-92b4-11e8-8e5a-0185c94ce39e.png)

**Comment by Shahelion** [comment]
Problem solved, Crystal Lamps was the answer.

**Comment by ReikaKalseki** [comment]
Placing casting tables does not give progression.
