### ISSUE TITLE
ChromatiCraft Pylon? take damage and crash

### ISSUE THREAD

**Issue by seiros** [ReikaKalseki/Reika_Mods_Issues#187]
Whenever I get close to any pylons?(or whatever its called below) I take damage and my game crashes. I have tested most of things in the mod, nothing else happens, just only when i get close to the Pylon thing. I have also tried with only ChromatiCraft installed still the same. i have searched online and here in issues, but no one else has the same issue, also all the mods/forge is the latest version, and using ChromatiCraft 1.7.10_V7e. 
Here are my logs of the crash: 
Crash Log http://pastebin.com/4BaaJ7c0 and Loading Log http://pastebin.com/ZsGwAmEE

![2014-09-03_22 57 20](https://cloud.githubusercontent.com/assets/13675363/9107877/9b26349e-3bf8-11e5-8468-a973a2adadac.png) Picture of the pylon? in question

**Comment by kolatra** [comment]
This looks like an issue with Magic Crusade. It does not point to ChromatiCraft at all, are you sure you tried this with ONLY DragonAPI and ChromatiCraft?

**Comment by seiros** [comment]
I am sorry to mislead you, I thought I did, but I didn't. The mod by itself work fine, must be a conflicting mod that's causing the error with the pylons. I tried it normally again without magic crusade still the same, but as for ChromatiCraft itself no errors, so this issue is closed, thank you for your time.
