### ISSUE TITLE
[DragonAPI] Crash: "SoundPitchEvent"

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1870]
Similar to #1399  and  #1389

Crash log: https://paste.ubuntu.com/p/mCY9jDtq8j/
Nothing of note, but relevant server log: https://paste.ubuntu.com/p/nTw3HrQyQm/

Crash occurred when I placed a wooden buildcraft pipe, extractor/friction heater running in the background, and dynamic surroundings "hunger" sound playing. (Probably not quite related).

**Comment by cheesealmighty** [comment]
Client logs before the crash, snipped for brevity:
https://paste.ubuntu.com/p/HBRVStZGm2/

"Unable to play unknown soundEvent: minecraft:step.null" Yup. Just like those old issues, it seems.

**Comment by ReikaKalseki** [comment]
DynamicSurroundings has been implicated in this before.

**Comment by cheesealmighty** [comment]
_Pitchforks and torches then?_ 

This happened only once in 35 hour game time, so shouldn't be much of an issue, I reckon.

**Comment by ReikaKalseki** [comment]
I do not remember what their original response was.

**Comment by cheesealmighty** [comment]
I may have spoke too soon. It happened again. Not sure why it started happening now, and not during last 35 hours. Could be just random. 

I suppose I'll disable dynamic surroundings for the time being.

https://paste.ubuntu.com/p/7pd8mnhqQM/

**Comment by cheesealmighty** [comment]
I also have "Sound filters" mod. No, it does not coincide with these crashes starting, but it's one other mod that I have relating to sounds.  

https://minecraft.curseforge.com/projects/sound-filters

**Comment by ReikaKalseki** [comment]
I have never had issues with SoundFilters.
