### ISSUE TITLE
Null Pointer Exception after placing shaft

### ISSUE THREAD

**Issue by pyure** [ReikaKalseki/Reika_Mods_Issues#1871]
@Reika I had mentioned I would post the next time I had a crashing issue possibly related to RoC.
https://pastebin.com/yGh5DJ9N

RotaryCraft 1.7.10 V20c.jar
DragonAPI 1.7.10 V20c.jar

I had just logged into the world, removed a shaft, placed a gearbox (which exploded), placed a shaft.  Less than a second after I placed the shaft, I got the NPE.

I believe i've seen the same issue after placing other types of RotaryCraft transmission blocks.

Issue typically resolves itself by reloading the game and world.

Apologies in advance if its not directly related to your mods.

**Comment by ReikaKalseki** [comment]
#652, #590, #855, #161, #1358 #1423 #1474 #1488 #1565

**Comment by pyure** [comment]
One of those tickets implied that it was purely a vanilla issue, but, fwiw, that's clearly not the case, since it only happens (regularly) with RoC machines (by multiple users).  Perhaps a "more trouble than its worth to fix" tag would be appropriate.

**Comment by ReikaKalseki** [comment]
No, the issue is literally entirely inside vanilla code, handling vanilla data.

**Comment by pyure** [comment]
Yes but the issue doesn't occur with other mods, so it logically has to do with RoC.  There aren't actually alternatives.

**Comment by ReikaKalseki** [comment]
Yes, I have seen it - both personally and reported by others - occur with other mods. There might well be something about being modded in general that triggers it, as I doubt it happens in vanilla, but again: That code in the error has *zero* influences from me.

**Comment by OvermindDL1** [comment]
Although it is a Vanilla bug, Forge has code that makes it more easily occurring, when it could have fixed the issue outright, however they no longer care about fixing it outright (or ever actually since they blamed it on vanilla) since 1.7.10 is old so unless someone releases a fixed forge then this is just something that can happen.  It is not really a Reikamods issue though Reikamods could make it occur less by reducing client-side block updates, however that would only delay it happening regardless.

**Comment by ReikaKalseki** [comment]
You mention block updates - you have some idea what causes it?

**Comment by OvermindDL1** [comment]
Been a couple of years but as I recall it was some bad timing with the client receiving a block update and it being processed at a bad time when the event should have been passed to the main thread for synchronous processing or something like that.

**Comment by ReikaKalseki** [comment]
Lovely...
