### ISSUE TITLE
[RoC] Minor Bug: Enchanted tree cutter icon is off set in WAILA

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1872]
This is very, very minor. But just wanted to point it out.
https://puu.sh/B575C/d6090794f8.png

Modlist(Everything up to date/latest version): https://paste.ubuntu.com/p/xTwqWPRwhK/

**Comment by ReikaKalseki** [comment]
Only for WAILA? Not item rendering in general?

**Comment by cheesealmighty** [comment]
https://puu.sh/B5apx/59bedab1a4.png

I think this looks normal? At least the enchantment seems to be *on* the cutter.

**Comment by ReikaKalseki** [comment]
I asked about item rendering.

**Comment by cheesealmighty** [comment]
I'm sorry, just to be clear. By item rendering, do you mean how it looks when I hold in my hand/inventory?

**Comment by ReikaKalseki** [comment]
Yes.

**Comment by cheesealmighty** [comment]
Here it is:
In inventory: https://puu.sh/B5yF8/ccc8f48267.png
In hand: https://puu.sh/B5yF2/90bb0bb13d.png

Yup, it's offset all around.

**Comment by ReikaKalseki** [comment]
Fixed.
