### ISSUE TITLE
[ChromatiCraft] Fix for chromatic bees not properly caching blocks for product checks

### ISSUE THREAD

**Issue by Kataiser9** [ReikaKalseki/Reika_Mods_Issues#1873]
Same issue we discussed in the [forum thread](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=1501). Good news is that after staring at the code for awhile, I've identified the issue and tested a custom solution that appears to fix it (tested for awhile in-game in a dev environment, worked fine).

Problem: The ProductChecks class, when checking for nearby blocks to cache, stores cached data in a HashMap<WorldLocation, Coordinate>, where the WorldLocation is the position of the bee housing and the Coordinate is the position of the relevant block. Since each key can of course only have one value, this means that each bee housing can only "remember" one cached block position at a time - which leads to seriously wonky interactions with bee species that need multiple different blocks. This is most relevant to the more complex species, like Polychromatic, which has multiple products that each require three different blocks. You _can_ get these products, but only if every necessary condition searches and finds the right block in sequence, without ever coming up empty, which is of course extremely unlikely.

Solution: Up to you, of course, but [here's](https://pastebin.com/guj8cW7X) a paste of how I fixed it if you want to take a look. (I'm sure this could be done in a much more elegant and perhaps more performant way - this is just something I slapped together, and I'm certainly not an expert.) The gist is that I changed the HashMap's k/v from <WorldLocation, Coordinate> to <WorldLocation, ArrayList of CachedCheckResult>\*, where CachedCheckResult is just a mini-class that stores a BlockCheck and a Coordinate, letting the AreaBlockCheck keep a single cached result for each block type for a given IBeeHouse.

\* you know what I mean, but apparently you can't nest <>s in github comments or something

(edit: fixed paste)

**Comment by Kataiser9** [comment]
Forgot something tangential - for the ChargedShardCheck function in the same class, lines 328 and 329 ask for crystals with a metadata of 0 (Kuro) in all cases, meaning that every charged shard actually requires [color-appropriate tree + liquid chroma + Kuro crystal]. (I apologize if this would've been better as a separate issue, but I assume this is so trivial to fix that it doesn't really merit a separate post.)

**Comment by ReikaKalseki** [comment]
To me a cleaner fix is to de-static `successfulChecks`. That way every instance of it gets its own cache, and no instance has multiple block types (and no check type has multiple instances).

**Comment by Kataiser9** [comment]
Yeah, that makes more sense. Thanks for getting to it so fast.

**Comment by Kataiser9** [comment]
So, bad news: it's still broken on 21a, AFAICT. Tested with Nila and Polychromatic. Repeated manipulator checks show that just as before, the mod is finding target blocks and then rapidly "forgetting" their locations. I know my setups are correct, because they worked fine with my previous custom fix.

**Comment by ReikaKalseki** [comment]
I just tested and the cache lookups are working fine. I did realize, however, that these caches take quite some time to build (and that this may be the reason for low apparent yields), so I will put in a bit of code to speed that up.

**Comment by ReikaKalseki** [comment]
And the production works fine too:

![https://i.imgur.com/JZ6KxqH.png](https://i.imgur.com/JZ6KxqH.png)

**Comment by Kataiser9** [comment]
Well, I tried a number of things on 21a with no luck - including giving the bees over an hour to detect nearby stuff, so I don't think the problem was a lack of time - but now on 21b everything seems quite fine. Can't say I understand it, but awesome anyway!

**Comment by ReikaKalseki** [comment]
It was probably that the caches had not populated in time for your tests.
