### ISSUE TITLE
Item idea: tourque converter/centrifugal clutch

### ISSUE THREAD

**Issue by CANA-Dan** [ReikaKalseki/Reika_Mods_Issues#1874]
When using more than four shaft junctions in a row, the fifth one blows up. I'm not sure if this is intentional (the inputs, a line of steam engines for example, have ever so slight differences in speed so they put stress on the junctions) or a bug. If this is intentional then a tourque converter could allow for more connections to be made as it would allow the input speeds to slip ever so slightly. A potentually cheaper version, a centrifugal clutch made out of stone, could be used for lower speed, lower tourque applications. As a nurf for these items they would both have a minimum speed, an optimal speed and a maximum speed. The further away they are from thier optimal speed the higher the tourque and speed losses. When they reach their optimal speed they won't have any tourque loss. When they reach their maximum speed they blow up (of course).

Another use for these two items...

industrial coils could be saved just before they reach maximum capacity as the sudden change in speed from the coils no longer accepting power would make the centrifugal clutch/tourque converter blow up before the coil did.

**Comment by ReikaKalseki** [comment]
This limit is specifically imposed, and exists to prevent the use of engine spam to bypass progression.
