### ISSUE TITLE
[RoC]Minor suggestion: Add info to handbook about AC engine shaft core automation

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1875]
After some frustrating trials and errors, I found out you can only pull out shaft cores once they're completely demagnetized. This is great for automation, obviously, but it isn't the regular/expected inventory behaviour. I kinda expected to setup some timers to automate swapping of shaft cores out of the engine and back into a magnetizer.

Would you consider adding info about this to the handbook? 
Edit: As in, "Shaft cores can only be automatically pulled out when they're completely demagnetized."

**Comment by ReikaKalseki** [comment]
I can do that.

**Comment by ReikaKalseki** [comment]
Done.
