### ISSUE TITLE
[RoC-ElC-ReC]Suggestion/Bug: No recipe for ingot blocks

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1876]
Even though chisel adds blocks of nickel and silver, since these are not craftable using your mods. Is this intended?

Also, I realized most of the metals that come with your mod do not have a way of crafting into blocks. This causes some problems/considerations when routing and compressing items (e.g. _they don't look symmetrical in a wall of compressing drawers, petty? Yes._). Would you consider adding in block forms of the ingots? While only a mad person would even try to decorate with say, uranium blocks, it'd be nice to have the option to do so.

**Comment by ReikaKalseki** [comment]
No, it is not worth the dev time and the block IDs.

Also, you should be able to craft them just fine into other mods' blocks, provided those mods use the OreDictionary in their recipes.

**Comment by cheesealmighty** [comment]
This is true, I can use it in other recipes.

I guess chisel didn't add oredict entries for them. I'll minetweak them in. Thanks.
