### ISSUE TITLE
[ExpandedRedstone] Bug: Redstone clock giving signal in all directions

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1877]
Demonstrated here: https://puu.sh/B6aK3/5a9fe0e587.mp4

Is this intended behaviour? 

Edit: Also they don't seem to be overrideable from the back, like redstone clocks from ~Redpower~ Project red. This might be by design, I don't know.

**Comment by ReikaKalseki** [comment]
Yes, this is intentional.

**Comment by Rewyn** [comment]
I believe you can shut them off via redstone signal, but the signal needs to be delivered via an adjacent repeater. Don't quote me on this, though.

**Comment by cheesealmighty** [comment]
@Rewyn Well put me in a dress and call me Sue, you're right. Although it stops on the whatever stage it was in. Which might end up creating some erratic behaviour _that won't do with ReikaMods._ 

I think overriding the actual signal is the better option. Like so: https://puu.sh/B70fy/b1e1a4f704.png

**Comment by ReikaKalseki** [comment]
No, because there is no way to lock it to 'off'.

**Comment by cheesealmighty** [comment]
_Nani?_
https://puu.sh/B7kMY/559babea63.mp4

Edit: I guess this would be the way to go about ensuring it locks on "off": https://puu.sh/B7kZ1/46fbaf3759.png
Obviously this defeats the purpose of using expandedredstone's clock. Well, ability to wind it up to 1 hour is still nice.
