### ISSUE TITLE
[CCv20] When entering a world, pylon compass shows all colors in one direction (south I think)

### ISSUE THREAD

**Issue by kutschkem** [ReikaKalseki/Reika_Mods_Issues#1879]
Pylon compass does not know where the pylons are when loading a save. This has been the case for a few versions now, and I think intended or at least not worked around, and I suppose relates to chunk loading. 

What is new in v20 is that now, instead of not showing the pylon colors, it shows them all in south direction.

**Comment by ReikaKalseki** [comment]
So in other words the data remains uninitialized. I do have some save/load code...

**Comment by kutschkem** [comment]
Apparently this only happens once after the update to v20, if I discover pylons afterwards the data seems to survive save/load.
