### ISSUE TITLE
Chromaticraft Chunkloading strangeness

### ISSUE THREAD

**Issue by Saereth** [ReikaKalseki/Reika_Mods_Issues#188]
We originally had the option on for pylons to chunkload after use, this turned out to be a pretty big performance hit so we turned the options off. It seems however that pylons are still loading now with the option disabled, any work around for this? Latest version of DragonAPi and Chromaticraft.

We've swtiched from cauldron to standard forge 1448. Opis showing thousands of chunks loaded across the world and when I go investigate them with mapwriter all of them are pylons. 

I'm attaching an image from mapwriter showing the chunks as well as our config file.
http://imgur.com/a/EBMP5

**Comment by ReikaKalseki** [comment]
Um...I will look into this.

**Comment by ReikaKalseki** [comment]
Derp...fixed.
