### ISSUE TITLE
[RoC] Suggestion: Internal (GUI based) switch for the fermenter

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1881]
While I assume this was done to create an interesting challenge for the player to overcome, as sides of a block is limited; and/or to facilitate automation of sorts (while I don't think anyone would use one fermenter switching from one state to another, having the possibility is nice).

It creates some distasteful looking structures as trying not to give redstone signal to hoppers or similar devices (ducts) is required. 

Would it be possible to add some sort of internal switch, similar to Thermal * mods/EnderIO? Or a shift+screwdriverRightClick sort of functionality?

_Literally unplayable:_  https://puu.sh/B6ZUr/7bdb18bd0f.png

**Comment by ReikaKalseki** [comment]
This is a relic of some of the oldest code in RC, dating to long before I even knew how to make GUI buttons. But at this point it is not going to be changed because it will break existing builds.

And you can hide a redstone signal in the walls anyways.

**Comment by cheesealmighty** [comment]
Yeah I expected this to be the case. Would it still break the old builds if the default was "respond to redstone"? Or would it be possible to implement an inverted fermenter? Maybe combined with a redstone torch, similar to decorative tanks being combined with glowstone/dye/panes.

Well, not always, seeing that, back is for shaft power, then you need sides for sugarcane, yeast, water and output. That leaves only one side open. You could use complex signalling to bundle yeast and sugarcane together, but that's not really fun, at least for a fermenter.

**Comment by ReikaKalseki** [comment]
The redstone signal need not go into the machine directly - you can power an adjacent block.

**Comment by cheesealmighty** [comment]
I'm aware of this, as it can be seen from my build. But as I said, all the sides are occupied by item/fluid I/Os, except for the back, for the power, and front, because it's supposed to be the visible side of the block. 

_Auto-magical_ pipes (EnderIO, AE2, etc.) have all sorts of tricks that wouldn't be affected by this, of course, but I guess this is on me for deciding not to add anything other than buildcraft + logistic pipes. Logistic pipes would be overkill for a fermenter project, Buildcraft pipes don't seem to be behaving as they should in multiplayer (ie. single pulse mode on autarchic gates have erratic behaviour, not a fan of items overflowing/spewing out everywhere), and hopper ducts are affected by redstone. 

I'll probably find a way around it eventually. But just wanted to ask if it was something you'd like to implement.

**Comment by OvermindDL1** [comment]
@cheesealmighty Just as a side note, but GT5/GT6 pipes are very much like Eloraam's RedPower Tubes, they don't render anything on the client so very efficient, routing is done based on a 'pressure' kind of model and if things fit right.  Not quite as advanced as RP2's but one of the most efficient models out of any mod I've seen, and it can handle sides and routing and all there properly and well, GT5 has some more things than GT6 (which is still building up the technology in active development, although it has some very nice unique things as well, like *very* nice) like the Routing block, but otherwise...

**Comment by cheesealmighty** [comment]
@OvermindDL1 I'm really trying to prevent mod overlap in the pack though. I should be able to handle most of the stuff (if not more) RP2 sorting can do using logistic pipes. I was just looking for a simple solution. Although, good to know. (Also I can disable in pipe rendering if I wanted, but it's more about the whole "well oiled machine" setup I'm going for in my builds.)


On a side note, if I were to be honest, the game turns into a series of "CURSE YOU GREEEEG!" whenever I install GregTech. Liked it a lot better back in 1.2.5, when things were simpler. I'm not saying it's bad, but it's not like Rotarycraft, easy to learn, hard to master. _It's hard, hard always so damn hard._

Edit: Or was it 1.4.7? Those days are a bit hazy.

**Comment by OvermindDL1** [comment]
GT5 is really a catch all addon on IC2, but GT6 is fully standalone, rewritten, should take a [look at it](https://gregtech.overminddl1.com/) (especially the changelog and gallery), and it integrates quite well with Reika's mods.  GT6 is less like GT5 and more like terrafirmacraft by far, lot of early to mid-game things, it doesn't have much of the advanced machines or lategame things.  And it supports a huge variety of mods to get them working together in ways they normally couldn't (a link of first-class supported mods on the download page).  Bear989 (livestreamer) plays GT6+RoC and so forth along with a large bit of a big pack (which he has public as well in a few different build styles) if you are curious how they all work together.

**Comment by cheesealmighty** [comment]
I'll check it out, thanks. It does look a bit different from the GT5, credit where it's due, but gotta see it for myself.

**Comment by OvermindDL1** [comment]
> I'll check it out, thanks. It does look a bit different from the GT5, credit where it's due, but gotta see it for myself.

If greg's awake he's usually in #gt-dev on Espernet on IRC if you ever have questions.  Bear and others hang out there to answer questions too.

GT6 is *nothing* like GT5 though, entirely different style, feel, everything.
