### ISSUE TITLE
[Roc v20c] Phantom AC power

### ISSUE THREAD

**Issue by SayethWe** [ReikaKalseki/Reika_Mods_Issues#1882]
Upon placing an AC electric engine that had been providing power in a different location, it seems to output phantom power without a shaft core or redstone signal
![screen shot 2018-08-01 at 3 56 13 pm](https://user-images.githubusercontent.com/18403080/43551277-b6a1d194-95a3-11e8-89b9-8f7f3e8aa6e9.png)
![screen shot 2018-08-01 at 3 56 15 pm](https://user-images.githubusercontent.com/18403080/43551279-b9cecc00-95a3-11e8-86c1-2223f36850b2.png)
![screen shot 2018-08-01 at 3 56 27 pm](https://user-images.githubusercontent.com/18403080/43551284-befb728c-95a3-11e8-8fd6-148f8de84a56.png)

**Comment by ReikaKalseki** [comment]
You have a magnetized shaft core in your inventory.

https://en.wikipedia.org/wiki/Faraday%27s_law_of_induction

**Comment by SayethWe** [comment]
I had not know that was a thing.

but even without the redstone signal it turns?

**Comment by cheesealmighty** [comment]
I believe that's the expected behaviour.
