### ISSUE TITLE
[ChromatiCraft] SuperBuild ability doesn't properly consume blocks

### ISSUE THREAD

**Issue by Kataiser9** [ReikaKalseki/Reika_Mods_Issues#1883]
Using this ability (Linear Construction) to place blocks only consumes a single block from the held item stack, regardless of how many blocks are placed in the world.

Interestingly, using the ability with a small item stack will only place up to (stacksize + 1) blocks, so clearly it _is_ decrementing the stack size each step - it's just not affecting the player's actual inventory for whatever reason.

Tested on a minimal install (ChromatiCraft v20c, NEI, and dependencies).

**Comment by ReikaKalseki** [comment]
Fixed.
