### ISSUE TITLE
Allow Bevels to attempt to place intelligently

### ISSUE THREAD

**Issue by pyure** [ReikaKalseki/Reika_Mods_Issues#1884]
Purely as a quality-of-life feature, I would like to see bevel gears make a fair effort to place "intelligently" by default.

If a bevel is placed such that it can make an L between an input and an output, the first such qualifying L should determine the bevel's orientation.

**Comment by pyure** [comment]
BTW: I feel like this has been requested before, but (after a reasonable search) I couldn't find a related issue.

**Comment by pyure** [comment]
Closing issue in accordance with the repo's rules preferring suggestions.

**Comment by ReikaKalseki** [comment]
I had to rewrite bevel gears to make this work, but it is now done.

**Comment by cheesealmighty** [comment]
Can this also be implemented for regular ol' shafts? I believe they only check for the direction you're placing them from. And this creates issues when pillaring up/down.

**Comment by ReikaKalseki** [comment]
I feared someone would ask this. No, I am not going to do this; rerouting a shaft is comparatively simple, and I do not want to open the can of worms of "what about engines? junctions? machine A? machine B? Turbines? converters? thing from another mod...."

**Comment by cheesealmighty** [comment]
I kinda guessed you would say this, but it's completely understandable. Bevel gears is the odd one of the bunch (requiring fiddling with a GUI), and probably the highest QoL improvement/work on your part ratio of them all. Much appreciated.
