### ISSUE TITLE
[RoC]: Crash: Reika.ElectriCraft.Blocks.BlockElectriOre.func_149691_a(BlockElectriOre.java:68)

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1885]
This is probably due to me breaking my world, removing mods halfway. I know, I know.

Removed steve's carts 2, baubles stuff. Added minefactory reloaded and computronics. Bada-bim-bada-boom. Crash, but only on the client side. Server is still running fine on its own. 

Client crash log: https://paste.ubuntu.com/p/4Nwc5bwQ3q/
Server log piece: https://paste.ubuntu.com/p/WrNygZK5SX/

Okay, this is deeper than I originally thought... Reverting back to a save from this morning, even one from a week ago, even after adding back the removed mods, and removing the ones that were added later, my client is crashing, testing backup on singleplayer before uploading. 

Crashlog: https://paste.ubuntu.com/p/QzQS8CWzb2/

Right before I crash, I can see my items and blocks changed, like somebody shifted the block IDs.

Edit: These crash reports keep changing... https://paste.ubuntu.com/p/KST7xFm78Z/
I'm at a loss here. This one is obviously unrelated to you.

Edit2: I also tried loading from the modpack I made. Instead of my local copy. Nope, still doesn't work. I'll try joining to my server, maybe it doesn't like being swapped to MP->SP. _Never heard of that, but hey, I'm out of ideas._

**Comment by ReikaKalseki** [comment]
This is world corruption - you have a block ID/metadata mismatch.

**Comment by cheesealmighty** [comment]
Yup. Assumed as much. I'll carefully tread my steps back, maybe I missed something. Thanks. 

Edit: That took unnecessarily long to fix. I missed a small mod, apparently. _At least it is fixed._

Edit 2: _I guess you'll be subjected to my ramblings and "bug" reports for a bit longer._ Hope you don't mind.
