### ISSUE TITLE
(chromaticraft+FunWorldGen) crush on chunk generation

### ISSUE THREAD

**Issue by nuclear123** [ReikaKalseki/Reika_Mods_Issues#1886]
*sory for my bad english

use FunWorldGen- sky dimension (https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1281910-teds-world-gen-mods-realistic-world-gen-alpha-1-3)

with chromaticraft installed, after some exploration - crash:
https://pastebin.com/VZxQLrhr
(try create 4 test worlds - all reports nearly same)

with chromaticraft disabled - no crash

world is not corrupted and can be reloaded

**Comment by ReikaKalseki** [comment]
Either he is firing the event and passing in the wrong Block[] array format (more likely), or he is changing how the terrain system works entirely (much less likely). Either way, this is not my doing.
