### ISSUE TITLE
Inventory and NEI GUI blank when opening Inventory Screen

### ISSUE THREAD

**Issue by Tryfan26** [ReikaKalseki/Reika_Mods_Issues#1889]
![2018-08-04_19 19 30](https://user-images.githubusercontent.com/19435516/43681520-6d475b84-981b-11e8-8aa1-18b7f88804e2.png)

As pictured in the screenshot.

Part of the log is included; I hope the relevant part is in the bit I pasted. The console spammed a Couldn't Render Entity report.

https://pastebin.com/1vgGM77d

This may be linked to the donor render; when I go into the DragonAPI configs and set the following:

B:"[C39B765D7] Custom/Donator Renders"=false

The issue clears right up.

**Comment by ReikaKalseki** [comment]
Do RC gears render normally for you?

**Comment by Tryfan26** [comment]
THIS happens in world:

![2018-08-05_14 07 37](https://user-images.githubusercontent.com/19435516/43689025-4f65c288-98b9-11e8-87a4-c67774128c23.png)

When I have a RoC item selected in the hotbar.

And when I don't:
![2018-08-05_14 07 39](https://user-images.githubusercontent.com/19435516/43689032-6a6a2614-98b9-11e8-86f3-38af128c6956.png)

Additionally, in that 3rd person view, when I ESC/pause the game, the pause menu is invisible as well. It reappears if I pause when back in 1st person.

And again, it's all completely fine if that donor render is turned to False.

**Comment by ReikaKalseki** [comment]
No, I mean gear items.

**Comment by 1skandar** [comment]
I can confirm this as well. Trying to go into F5 mode does not work, I get a white screen. It looks like the player entity cannot be rendered. If I am holding a RC gear I get this: 
![2018-08-06_06 27 53](https://user-images.githubusercontent.com/4127779/43711811-f7a468fe-9941-11e8-8f20-f2ff45445e53.png)

Please note, I have NEI installed and unhidden, but it, too, is as invisible as everything else in my inventory.

**Comment by OvermindDL1** [comment]
Log file?

_/me is wondering if any `(OpenGL Error)`'s are appearing potentially due to bad GPU drivers_

**Comment by ReikaKalseki** [comment]
Fixed.

![https://i.imgur.com/S9BVAnR.png](https://i.imgur.com/S9BVAnR.png)
