### ISSUE TITLE
[Dragon API] More health mod hearts broken when dragon API installed

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#189]
Without dragon API more health mod's heart hud does its normal thing, however when I tested this with the following
![m test](https://cloud.githubusercontent.com/assets/8153290/9121803/96ab5e76-3c39-11e5-9f89-60bd6b9042b7.PNG)
Things get weird... first of all, heart rows are now color coded (can get confusing unless one memorizes what color is what row which lets face it, few even dare to do that) and after the 12th row hearts go white.., after getting rows 13-15 row 16+ turns into a overlapping mess:
![2015-08-06_12 42 52](https://cloud.githubusercontent.com/assets/8153290/9121853/f7c16188-3c39-11e5-90cb-0664f0f7f501.png)
Its probably best to remove this as a thing when that mod is installed (if it was intentional) OR atleast let us choose in the config wether we wish to have colorful hearts. 

P.S. I tested this with JUST heart mod and TCon and everything works as it should, only once dragon API is added everything breaks.

Edit 1: Normally the HUD shows no colored hearts even when TCon is installed and instead shows heart row number and the hearts in that row next to it.

**Comment by ReikaKalseki** [comment]
DragonAPI or ChromatiCraft?

**Comment by Zedrimar** [comment]
DragonAPI; Chromaticraft wasn't even installed for the test! :P Also did you happen to put any heart patches by any chance?

**Comment by Ianaver** [comment]
also did you happen to put any heart patches by any chance? without TCon everything works, with it the color hearts show instead

**Comment by Zedrimar** [comment]
I do realize that realistically few get to that much health fast, but still if you decide to keep this thing at least make it an option that can be set separately rather than forced :P

**Comment by ReikaKalseki** [comment]
Though there is a special file in DragonAPI with the GUI textures (including the health bar) and the code to draw it, that code is never called from anywhere.

As a test, try deleting the image  DragonAPI/Resources/gui.png

**Comment by Zedrimar** [comment]
that fixes it :) I still don't know why the health mod or (unlikely) your mod is forcibly replacing the health GUI... 

I will leave this open until you update dragon API

**Comment by ReikaKalseki** [comment]
Deleting the image file caused it to work (rather than causing it to draw missingtex)?

**Comment by Zedrimar** [comment]
Yup, even without the health mod, no missing textures :) After all, if what you said is correct and that its not called anywhere (unless you have a specific mod that uses extra health), then it is just using minecraft's version of the health HUD

(oh and turns out that TCon has nothing to do with this)

**Comment by ReikaKalseki** [comment]
Then some other mod is - somehow - reading my file preferentially.

**Comment by Zedrimar** [comment]
yeah, probably just the health mod because it sees that there is a GUI image

**Comment by Zedrimar** [comment]
well I don't know how your mod did it, but after adding the latest version of TiC hearts broke again! I searched the edited dragonAPI (without the GUI image), TiC, mantle AND the heart mod and found nothing that has the heart images... This now only occurs when the latest TiC is installed WITH dragonAPI and the heart mod otherwise it works as it should (tested with just the heart mod and DragonAPI and it worked, then added TiC and mantle and it went back to the weird colored hearts).
BTW the version of TiC I tested was 1.8.7 (for MC 1.7.10) and mantle 0.3.2a

**Comment by ReikaKalseki** [comment]
Clearly TiC is involved if update broke it again.

**Comment by Zedrimar** [comment]
yup :(
