### ISSUE TITLE
[RoC v20c]Boring machine digs nothing but stone after a certain distance + GUI Sync

### ISSUE THREAD

**Issue by Kwantuum** [ReikaKalseki/Reika_Mods_Issues#1890]
I feel like there's something wrong with my setup since it feels like it's impossible something this big hasn't been reported and fixed yet, but it's happening to me on the latest version. Here's my mod list:

- Code chicken core 1.0.7.47
- NotEnoughItems 1.0.5.120
- DragonAPI v20c
- RotaryCraft v20c
- JourneyMap 5.1.4p2-unlimited
- Veinminer 0.36.0.496+28a7f13

that's it.

Some additional info that may be useful: while testing I ran down the path of the boring machine after digging, and at one point, the digging pipes were cut off by a mineshaft, as though the mineshaft was generated after the boring machine went through there.

The boring machine interface also doesn't update when clicking 'toggle all', I have to close the interface and reopen it for the squares to update. Should I file a separate issue for this?

**Comment by ReikaKalseki** [comment]
> Some additional info that may be useful: while testing I ran down the path of the boring machine after digging, and at one point, the digging pipes were cut off by a mineshaft, as though the mineshaft was generated after the boring machine went through there.

This is probably related.

Try removing Veinminer and JourneyMap temporarily; my system used to work without issue.

**Comment by Kwantuum** [comment]
Happens even with only DragonAPI and RotaryCraft installed, sometimes an item that's not stone will pop up, but it goes through thousands to tens of thousands of stone before it happens, looks like some sort of race condition over chunk generation.

I let it run for a while a y=11, sampling one 5 block column for ease of testing, and the yield was:
- 16 Lapis
- 34 Redstone
- 77 Dirt
- 4 Coal
- 6 Emeralds
- 6 Iron ores
- 2 Gold ores
- more than 20 pages of scaleable chest inventory of cobblestone, or about 80,000. 

Notice the complete absence of diamonds or gravel, and the especially abysmal levels of coal which is supposed to be fairly common. The only item that tended to pop up after the borer was outside of loaded chunks was emeralds, if that may help with the debugging (if they're generated early or differently that would support the case of a race condition). 2 more popped up after the 80,000 stone mark while no other items ever seem to appear.

The boring machine was supplied with power using a gas turbine and a 4:1 bedrock gear on speed mode and operating at 1 op/tick.

Feel free to ask for any more info, can you not reproduce this on the latest version?

Edit: Update: there seems to be some errors thrown in the console:

DRAGONAPI ERROR: Chunk at X, Y failed to allow population due to a ConcurrentModificationException! Contact Reika with information on any mods that might be multithreading worldgen!

(reminder that this was with dragonAPI and RoC exclusively)

less than one a minute though. Update on the yields: now at 18 emeralds after digging probably 3 times as many blocks, nothing else has appeared.

**Comment by ReikaKalseki** [comment]
That makes this #275.

**Comment by Kwantuum** [comment]
Although I am getting CME's (which seem to have something to do with structure world gen), the stone problem seems unrelated as the stone output is consistent even in the absence of CME's. I'll test this later today with structure generation turned off to see if the problem and/or the CME's persist.

Have you not been able to reproduce this?

**Comment by ReikaKalseki** [comment]
Not in any form I can actually debug, no. Also, if you are pulling up stone, it means the population on the chunks failed, which would happen due to the aforementioned CME and little else (that would not crash the game outright, at least).

**Comment by Kwantuum** [comment]
Wouldn't that throw an error on every chunk the borer goes through? Also, when running through the tunnel, the sides of it are full of ores so the chunks do get populated at some point.

After testing with structure generation off, I am no longer getting any CME's, but yields are the same, though I am now getting dirt and emeralds.  Interesting note: going through the tunnel I've encountered a lava pool that was not dug through by the boring machine (or more likely the tunnel was overriden by subsequent generation of the lava pool). Same thing happened with a mineshaft when structures were on, no CME.

This was on 20c, going to update now and test on 21a to make sure this still happens and will update this post with results. This is also on the latest version of java (currently 1.8.0_181-b13).

update: confirmed to happen on v21a

second update: this happens even when the boring machine is operating much more slowly. (1-5 ops/sec), not just when operating at 1op/tick. Teleporting to the boring head fixes the issue until the head runs unto ungenerated chunks again.

**Comment by ReikaKalseki** [comment]
> when running through the tunnel, the sides of it are full of ores so the chunks do get populated at some point.

When you approach in person; that causes the population.

> After testing with structure generation off, I am no longer getting any CME's,

The CME is apparently related to vanilla mineshaft code, so that does not surprise me.

>  but yields are the same, though I am now getting dirt and emeralds.

*That*, however, does. Emeralds are generated in a different way from dirt - at least in vanilla - but dirt is generated in the same call set that also gens all the other ores and gravel:

![https://i.imgur.com/lIF9Pqj.png](https://i.imgur.com/lIF9Pqj.png)

Which is also called right among the *other* vanilla decorators:

![https://i.imgur.com/DY9BXjH.png](https://i.imgur.com/DY9BXjH.png)

**Comment by Kwantuum** [comment]
It's possible the dirt was from previously generated chunks? Otherwise that would mean you're accessing the chunk right in the middle of decoration, but surely that would cause CME's from writing to the blocks? And it would also not happen at low operating speed. Unless the base minecraft code always accesses the chunk after your code, and silently stops population on CME, and attempts it again on chunk loading. Just thinking out loud here. I might toy around with this if I ever get a mod dev environment set up again.

Either way, since you're unable to reproduce, if you'd like to add some logging to dragonAPI or the minecraft world gen and have me run the test and send you the logs I'd be happy to oblige, if however this bug seems to only affect me and you'd rather not spend the time to track it down I would understand also. I used to have no problems with this when I last played with Rotarycraft on this same machine but this was probably over a year ago, maybe more, and I've reinstalled my system since. Maybe I'll try to downgrade and see if I can find a version where it works properly, I'll keep you posted if I find anything.

Thanks for your time!

**Comment by ReikaKalseki** [comment]
> Unless the base minecraft code always accesses the chunk after your code, and silently stops population on CME, and attempts it again on chunk loading. 

This may well be the case.

**Comment by 3bygone3** [comment]
I think I had this exact issue since v19c. I may be able to dig up some logs if needed. Sometimes server restart temporarily fixed the issue, sometimes server wouldn't start at all without removing borers first.

**Comment by 3bygone3** [comment]
https://pastebin.com/30Fr19cc
This is what shows up in server logs every ~5 minutes, it is from mystcraft age made of netherrack with a single borer. It had nether quartz and some other ores generated around spawn area, but borer is only pulling netherrack for a few weeks now.  Sadly I don't have older logs from different dimensions anymore.

**Comment by ReikaKalseki** [comment]
The relevant code here is not new - it would go all the way back to like v6.

**Comment by ReikaKalseki** [comment]
I fixed the sync issue.

**Comment by lAimBotl** [comment]
Not sure if this should be a different issue, but um:
![2018-09-14_17 39 18](https://user-images.githubusercontent.com/10777735/45576435-29e61980-b845-11e8-81a5-5fa62aa073b3.png)

 random unmined wall?

**Comment by ReikaKalseki** [comment]
Chunk gen issues, probably.

**Comment by lAimBotl** [comment]
Not sure if it is intended, but it also will not mine spawner rooms

**Comment by ReikaKalseki** [comment]
Spawner rooms?

**Comment by lAimBotl** [comment]
The vanilla spawner rooms with the chests  mob spawner and cobble/mossy cobble

**Comment by ReikaKalseki** [comment]
Dungeons? It should mine those without issue. And it does.

**Comment by lAimBotl** [comment]
![2018-09-14_17 36 17](https://user-images.githubusercontent.com/10777735/46232138-36399e80-c33c-11e8-9ca3-c54721e9b1c6.png)

**Comment by ReikaKalseki** [comment]
That probably generated later.

**Comment by madsamjp** [comment]
I'm getting this issue in V33. Was it ever fixed? My boring machines work fine up until a certain point, then only mine stone and certain RC ores such as pitchblend/indium etc. I dont get any diamonds, gold, redstone or coal, If I travel down to the end of the tunnel, I can these ores do generate in the sides of the tunnel, so they load when a player is present. The only solution I've found is to break the borer and place it elsewhere. Perhaps it is a mod interaction? I'm playing Surviving with Rotarycraft.
