### ISSUE TITLE
Chromaticraft fragment gui (recovery/adding fragments) crashes game (SP) (BR modpack)

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1891]
I pretty much just hobbled together your mods and mods in the Beyond Reality modpack.

Single player.

RotaryCraft, Chromaticraft, DragonApi, Reactorcraft = v20c .

Void Monster, Expanded Redstone, Electricraft = v20a .

I had to turn on :  | B:"Use HashMap for Sound Categories - Only use if necessary"=true | incase that is relevant.

Crash logs:
Client : https://pastebin.com/uwHezQ23
Server: https://pastebin.com/znEpxXgB

I also got these once:
other Server CL: https://pastebin.com/rVPEpMU2 .
other Client CL: https://pastebin.com/50Y6djyF .

**Comment by ReikaKalseki** [comment]
This is the fault of "com.amadornes.trajectory.hax", whatever that is.

**Comment by lAimBotl** [comment]
Found it, also found a github, yey .

https://minecraft.curseforge.com/projects/trajectory
https://github.com/amadornes/Trajectory/issues

Guess I will see what happens if i remove it.
Removing it also removed the crash.

**Comment by ReikaKalseki** [comment]
He is doing something with GUI handling.
