### ISSUE TITLE
v21a - Crash when loading current world

### ISSUE THREAD

**Issue by lee321987** [ReikaKalseki/Reika_Mods_Issues#1892]
I can start a new world, but when I try to load my current one, it crashes every time.

Description: Updating screen events
io.netty.channel.ChannelException: connection refused

(full crash report attached)

DragonAPI V21a
ElectriCraft V21a
ExpandedRedstone V21a
ReactorCraft V21a
RotaryCraft V21a

[crash-2018-08-06_07.11.46-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2262319/crash-2018-08-06_07.11.46-client.txt)

**Comment by lee321987** [comment]
I just realized 2 crash log files were created (sorry).
Here's the server one (which one do you need?):
[crash-2018-08-06_07.11.42-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2262474/crash-2018-08-06_07.11.42-server.txt)

**Comment by ReikaKalseki** [comment]
Well this is new...

**Comment by lee321987** [comment]
I restored the world from a pre-v21 backup, opened the world with v20 mods, broke the block (called "Block entity being ticked" in the crash report), and was then able to load the world with v21 mods.  However if i place block back, the game instantly crashes.
The block is insulated super-conducting wire connecting a resistor to an Electric Meter.
Then I restored the backup, loaded with v21, and placed a _new_ electric meter, and resistor in a new location.  As soon as I put wire in between them, it crashed.
I don't know if this helps, but after one of the first crashes, I loaded the world (without restoring from backup) with v20, and I noticed all my Bevel Gears had been re-oriented at some point before the crash.

**Comment by lee321987** [comment]
Okay I just made a new world with no other mods besides DragonAPI, Rotarycraft, and Electricraft.
Place Electric Meter, and Resistor one block from that.
Put wire (seems any wire does it) connecting them = crash.

**Comment by Kobra331** [comment]
My world crashes too. But with an other crash description: concurrent modification exception

https://pastebin.com/d4euu2KG

**Comment by ReikaKalseki** [comment]
The code giving you the error is not new; does this happen in older versions?

**Comment by Kobra331** [comment]
if you mean my log than no, this only happens with V21 a with v20 everything works fine.

**Comment by kida62** [comment]
I'm sorry. I am not good at English.

The symptoms appeared at the following times.

dragonAPIv21a
chromaticraftv21a

It is the server which installed only these two.
The server closed when loading the chromaticraft tower.

**Comment by ReikaKalseki** [comment]
That is a completely different issue not relevant here.

**Comment by kida62** [comment]
oh I'm sorry. I will report it again in another place.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by lee321987** [comment]
Curseforge page for DragonAPI says "No project files were found.".
