### ISSUE TITLE
[ExpandedRedstone]Bug: Block breaker respects NBT data, while block placer does not.

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1893]
_You're killing me here._ 

https://puu.sh/B9FrK/afc3cf1ea5.mp4

And the funny thing is, open blocks block breaker doesn't respect NBT data, but their block placer does.
So uh, everything turned out fine at the end. 

Asked dev about how the data is stored: GrowthcraftCE/Growthcraft-1.7#458

**Comment by ReikaKalseki** [comment]
This is not about "Respecting NBT". His placer item has custom code for setting TileEntity values. While I could theoretically add an API hook to ExR, for callbacks, there is nothing I can do to fix this directly.

**Comment by cheesealmighty** [comment]
https://puu.sh/B9HW0/8b1cd5574e.jpg
(Though to be honest I already have a workaround as it is.) 

I just wanted to see if it was an easy fix/something you missed. _Got my answer._
