### ISSUE TITLE
Worktable requires Worktable v21a

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1894]
With other mods (br pack I am playing):

![2018-08-06_15 53 54](https://user-images.githubusercontent.com/10777735/43737946-065f98ec-9991-11e8-882e-3d23252afad4.png)

![2018-08-06_15 53 48](https://user-images.githubusercontent.com/10777735/43737955-0a0abb98-9991-11e8-976d-bbea39de3618.png)
__________________________________________________________________________________________________________
With only your mods:

![2018-08-06_16 02 22](https://user-images.githubusercontent.com/10777735/43738330-37d26cfa-9992-11e8-8a33-62a89b4a284d.png)

**Comment by lAimBotl** [comment]
Oh sorry about the edit spam, couldn't make up my mind :I

**Comment by ReikaKalseki** [comment]
#1861 - why did you open a new issue?

**Comment by lAimBotl** [comment]
Because I am blind
oh I should mention its in the latest version (the one you posted today)
and also no matter what :  "    B:"Crafting Table can Make Machines"=true " is set to it is uncraftable.
I should probably continue with anything else on the "real" post :)
