### ISSUE TITLE
[Rotarycraft] [V21a] Bevel gears reset orientation upon world loading

### ISSUE THREAD

**Issue by Kowalskicore** [ReikaKalseki/Reika_Mods_Issues#1895]
For some reason most bevel gears reset, or reconfigure automatically whenever I reload my world. This seems to mostly happen to ones with an upward or downward out/input though. Possibly related to the bevel gears attempting to auto-direct on placement?

**Comment by cheesealmighty** [comment]
This happened in my world as well, but I would assume it's a one time thing.  _I hope it's a one time thing?_

_It was a mad dash to fix all the things before things got... Explody._ Funny thing is, I heard an explosion, and can't find out what went out. I hope it ain't something important.

> mostly happen to ones with an upward or downward out/input 

Same here. But seen some that didn't have the upward-downward orientation.

**Comment by ReikaKalseki** [comment]
This is because I rewrote the bevel gears. Read the changelog.

**Comment by ReikaKalseki** [comment]
This happens *every* time you reload?

**Comment by cheesealmighty** [comment]
> This happens every time you reload?

Oh god. It seems yes. Confirmed on multiplayer server. _Reika help us all._

Edit: Logged few of the gears that were switched. 
No specific pattern: 
Input-Output
W-S
S-W
S-U
W-N
N-E
D-N
S-U
E-U

And so on.

Edit 2: Also, how intelligent are they supposed to be? https://puu.sh/B9QgI/8c886b50da.mp4

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by Kowalskicore** [comment]
Well that was quick. Am I glad I always have either access tunnels, or exposed machinery though.
