### ISSUE TITLE
[Rotarycraft] Adding Buildcraft fuel and/or crude oil as flamethrower fuels?

### ISSUE THREAD

**Issue by Kowalskicore** [ReikaKalseki/Reika_Mods_Issues#1896]
I just noticed the flamethrower turret existed, but then found out only ethanol and jet fuel can be used for it. Perhaps Buildcraft fuel and/or crude oil could be used as alternatives?

**Comment by EyeDeck** [comment]
Coincidentally, Reika implemented both of those and a few others as of last night.

**Comment by Kowalskicore** [comment]
Ha, didn't even realize. Great to know though!
