### ISSUE TITLE
[RoC] Suggestion: Rotarycraft Screwdriver - Project Red Screwdriver interchangeability

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1898]
Unless I'm doing something terribly, terribly wrong, I can't seem to use RoC screwdriver to configure Project Red circuits. Is this something that could be fixed on your end? Or is it something on their end?

_If not possible, I can just imagine one being a cross screw drive and other a phillips._

**Comment by ReikaKalseki** [comment]
I use my screwdriver on them all the time; it does work.

**Comment by cheesealmighty** [comment]
W-what. I could've swore. But I... 

_Can we just pretend this never happened?_
https://youtu.be/6BCPA2mUuq0?t=11s
