### ISSUE TITLE
[RoC] Question/Suggestion: An online page for Open Computers methods

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1899]
I really appreciate the GUI you did where you can hover over the machines and see what methods they accept. But is there an online list that I can use to copy/paste to my notepad++ when working on scripts?

_I did found this:_ https://github.com/ReikaKalseki/RotaryCraft/tree/e81cef4e22d3fe187fb61d548f75e893bc88ab70/ModInterface/Lua

But they're obviously not very legible _(i.e. it's better to just open up the in game handbook)._

I *can* create a list for myself by hand if this is impossible/hard to implement. 

Edit: I mean something very simple. Just text based would do.

**Comment by ReikaKalseki** [comment]
I do not have the means for this. Add it to one of the wikis.

**Comment by cheesealmighty** [comment]
Fair enough. I assumed you had a handy way of compiling all those methods into one page (similar to the handbook). I reckon it's dispersed throughout the code. Thanks.

**Comment by ReikaKalseki** [comment]
Every `LuaMethod` object specifies the required class/interface of a TileEntity in order to be applicable. These are calculated automatically per tile, at runtime.
