### ISSUE TITLE
DragonAPI crash with ender io

### ISSUE THREAD

**Issue by Xavion3** [ReikaKalseki/Reika_Mods_Issues#190]
[Crash Log](https://paste.ee/p/SHyVW)

Always crashes on world load with that error.

**Comment by ljfa-ag** [comment]
I want to say that we already had a similar issue reported but I can't seem to find it. Well...

**Comment by TomeWyrm** [comment]
It may have been in the MCF thread, and subsequently deleted, but I remember something like this as well.

Did you do anything in that world? Are there any EnderIO blocks placed near 476,64,356?

**Comment by Xavion3** [comment]
I've done plenty in that world, it's actually one of the main single player worlds I play at the moment so it does have some developed infrastructure. Basically nothing from any of reika's mods though, I've only made the blast furnace.

As for ender io blocks near there maybe? I mean I have two ender io blocks placed which are an alloy smelter and a sag mill but they're at least a hundred blocks from there on top of a mountain.

**Comment by ReikaKalseki** [comment]
Something replaced a TileEntity without replacing its block. This falls in the "should be impossible unless someone does something very stupid" category.

Delete the area around that coordinate.

**Comment by Xavion3** [comment]
Deleting the block with MCedit let the world load, however the ids have clearly been mixed up on loading and there was a warning about using the backup level.dat so world corruption could definitely be a cause. Time to downgrade mods until I get a playable world I suppose.
