### ISSUE TITLE
[RoC] Suggestion: Bedrock Flint and Steel.

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1900]
Flint and Bedrock? 

Bonus points if it creates eternal fire when used in an item effector facing upwards. Allowing steam engines to be shut down and then reignited again when needed. _For instance if bevel gears powering the pump supplying water to the engines reorient themselves <sub><sup>joking, please don't hurt me</sup></sub> and system runs out of water._

I'm trying to keep mod overlap to minimum and was looking for something similar to a firestarter from project red. Which they helpfully bundled up with the transportation module. _I swear, I'm gonna end up writing small mods just to fill up these gaps._

**Comment by ReikaKalseki** [comment]
This is really not worth the time it would take to implement.

**Comment by cheesealmighty** [comment]
Not even flint and Bedrock? Basically a flint an steel with no durability(unless I'm missing something about the code related to that). The other thing suggested here is very fiddly, true.

**Comment by ReikaKalseki** [comment]
No. Such items are not used much at all, thus making durability irrelevant.

**Comment by cheesealmighty** [comment]
That really depends on the user. Also should point out a similar thing can be said about the hoe. I mean, this is really the only vanilla tool we're missing from the mod. 

And also, I can't find/remember any mod having an infinite use flint and steel equivalent. Natura has flint and blaze, which just has extra durability. TE Flux igniter and GT lighters are just refillable, but not unbreakable.
