### ISSUE TITLE
Crash on startup with botania and thaumcraft [Chromaticraft]

### ISSUE THREAD

**Issue by danieru-desu** [ReikaKalseki/Reika_Mods_Issues#1902]
https://pastebin.com/YzhrPX68 - crash report.
Works just fine without chromaticraft.
Made the same post in Vazkii's github but guess it's caused by Chromaticraft. https://github.com/Vazkii/Botania/issues/2696
Crash report without botania: https://pastebin.com/sEvmPeGJ
Tomorrow I'll try to remove both tc and botania and see what happens.

**Comment by ReikaKalseki** [comment]
Someone is including an old version of the Botania API, and it is not me.

**Comment by AndreiTS** [comment]
@NightH4nter  try to remove this mod: 
UCE thaumicadditions{0.41} [Thaumic Additions] ([1.7.10]+Thaumic+Additions+-+0.41.jar)

**Comment by danieru-desu** [comment]
@AndreiTS Doesn't help.

**Comment by danieru-desu** [comment]
Okay, figured out the reason why it crashes with TC. Mods `TCBotaniaExoflame` and `Thaumic fixer` seem to throw that error.
Also it looks like you're wrong mr. @ReikaKalseki cuz now I have only one mod using Botania API which is botania itself (it's last version available for 1.7.10 btw), so IDK. https://pastebin.com/V4dmJjG8
UPD: I'll try to figure out which mod causes crash in case mr. @williewillus was right https://github.com/Vazkii/Botania/issues/2696#issuecomment-411645101.

**Comment by danieru-desu** [comment]
I did some testing today. So. Each time I put all 3 mods (Chromaticraft, Thaumcraft and Botania) w/ their libs (Baubles and DragonAPI) together it throws a error. As you can se here https://pastebin.com/vFJ4gZQK, no mods except mentioned above are installed, also all of them are the last versions available for 1.7.10, so please, don't tell me this is not caused by one of them or I'm using a wrong/old copy of someone's API.  
P.S. If I put only 2 of these mods together, each pair works fine (it doesn't throw a error on startup at least).  
P.S.S. I installed all 3 mods, launched the game, then got a error, then removed CC without removing DragonApi, and it worked. Then removed TC, it threw a error (the same crash report as above in this post), installed TC back, launched (successfully), then installed CC back, and it worked. I'm sorry, but it's either me being completely retarded or I've encountered kinda artifact. I'll try to install all other mods from my modpack to see if this will keep working.
