### ISSUE TITLE
[EC] v21a Batteries Void power if powered 

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#1904]
Hi, i found a strange bug.
3 images here: https://imgur.com/a/0oaiVMa
 First image: The batteries get charged by the coil.

Second image: The batteries charge ITSSELF, i use this to avoid energy voiding if i just want to power a small machine which doesn't need the entire power of 2 batteries.
BUT only if they aren't get charged through the coil.
then:
Third image: If the Coil charge the batteries they void all power at the max output rate of the batteries.

I believe this happens because they doesn't adding the charging sources together.

greets

**Comment by ReikaKalseki** [comment]
Does this happen with only one battery?

**Comment by Kobra331** [comment]
no because a single batterie cannot charge itsself. Thats the reason why i use 2 batteries to power machines without loss.

**Comment by ReikaKalseki** [comment]
So A->B and B->A?

**Comment by Kobra331** [comment]
yes as you can see it on image 2.
it works fine until you charge them with something other

**Comment by ReikaKalseki** [comment]
I did some testing - batteries only destroy power if they have nowhere to put the power. This is not a bug - their outputs are fixed, and this is not going to change; batteries were never designed for RF-style large-scale "build up a buffer over a long time and drain it" storage.

Does not void power:
![https://i.imgur.com/6R9rpXO.png](https://i.imgur.com/6R9rpXO.png)

Voids power, as it should (ie the auroral still puts out 268MW):
![https://i.imgur.com/YZXHgKw.jpg](https://i.imgur.com/YZXHgKw.jpg)

**Comment by Kobra331** [comment]
Try the same setup with a smaller battery to charge the others.
I give your batteries names for better description: https://imgur.com/a/Z7zXTLT

If A is a smaller battery or a source with smaller poweroutput than an auroral it will charge B and C, BUT neither B will charge C nor C  will charge B anymore which will ends up in a power loss of 2* 268 MW even if there werent the Battery D.

**Comment by ReikaKalseki** [comment]
No, it is because A is outputting more than is necessary to charge B and C.

**Comment by Kobra331** [comment]
Thats the point. Try a smaller source which doesn't output more then necessary and you will see that both batteries (B and C) lose power.
Proof: https://imgur.com/a/Z7zXTLT
its the same setup just without "D" and with a source lower than the Auroral Power output.
