### ISSUE TITLE
Hopper Stops Chromaberries from being consumed but applies the effect of the berries.

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#1907]
If placing a hopper below liquid chroma and then throwing berries into it. It will dye the liquid chroma the color of the Berries and the berries will not be consumed.  The chroma however is not able to create boosted crystals.

**Comment by ReikaKalseki** [comment]
That sound like client/server desync. Try relogging.

**Comment by ReikaKalseki** [comment]
Hello?
