### ISSUE TITLE
When adding Forestry to the mod list causes a RotaryCraft based error while "postinitialisaton" 

### ISSUE THREAD

**Issue by ERYK500** [ReikaKalseki/Reika_Mods_Issues#1909]
When I add the Forestry mod to my mod list, crash happens during the entry into "postinitialisation" fase.
Crash log:
[2018-08-12-1.log.gz](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2281050/2018-08-12-1.log.gz)

**Comment by ReikaKalseki** [comment]
There are no errors in that log - at least none pertaining to Forestry or RC - and it in fact has a bunch of stuff from you running around scanning hydrokinetics in it, which you could not have done if the game crashed in postinit.

Additionally, I use both of them together with no issues.

**Comment by ERYK500** [comment]
Sorry, wrong file
[crash-2018-08-12_17.40.22-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2281073/crash-2018-08-12_17.40.22-client.txt)

**Comment by ReikaKalseki** [comment]
Your Forestry version is almost four years out of date.
