### ISSUE TITLE
DragonAPI detected duplicate registration and crash in client

### ISSUE THREAD

**Issue by Bogdan-G** [ReikaKalseki/Reika_Mods_Issues#191]
Hello. MC 1.7.10, Forge 1492
DragonAPI 7f, GeoStrata 7e.
Run game and crash in Pre-initialized (crash-logs):
https://gist.github.com/Bogdan-G/11914f8af306c57b1479
https://gist.github.com/Bogdan-G/e57ef5f5974c120fd522
https://gist.github.com/Bogdan-G/ac2b75cefb4d474b0b25
If del DragonAPI and GeoStrata, then game normal start.
If del addon BigDoors for MalisisDoors and normal start. O_o

**Comment by ReikaKalseki** [comment]
Ping the devs here.

**Comment by Reignofmagic** [comment]
I have Malisis Doors working in my pack, so I'd say the culprit has a higher likely hood of being BigDoors

**Comment by ReikaKalseki** [comment]
Can you ping the developer?

**Comment by coolsquid** [comment]
We have both DragonAPI and Big Doors running in our pack without any issues. Maybe a 3rd mod is messing with stuff?

**Comment by Bogdan-G** [comment]
The author BigDoors says that he is not to blame.
http://minecraft.curseforge.com/mc-mods/232398-big-doors?comment=16

**Comment by TomeWyrm** [comment]
Thought I linked that before.. must've been another issue tracker. Just re-name the BigDoors jar to ZeBigDoors(numbers).jar

Known issue on BigDoors side.

**Comment by ReikaKalseki** [comment]
> Known issue on BigDoors side.

He explicitly said otherwise...

**Comment by TomeWyrm** [comment]
Sorry, bad phrasing. He knows it IS an issue and how to workaround it, he just doesn't know how to FIX the issue from his end.

"Big Doors triggers the problem because it loads before DragonAPI, which causes Malisis Doors to load before DragonAPI, and DragonAPI will crash because Malisis hooked some vanilla blocks before it."

It's actually an issue either for @Ordinastie or you to fix Reika.

**Comment by Ordinastie** [comment]
It happens because between the time the technicalBlocks array is constructed and the time the method registerTechnicalBlocks() is called, the wooden door ans iron doors have changed, both in the registry and in the Blocks class.

**Comment by ReikaKalseki** [comment]
Would checking the namespace (ensuring is "minecraft:") on the technical blocks as I iterate work? Does the modid on the block change? (And, importantly, do the new blocks _have_ itemblocks?)

**Comment by Ordinastie** [comment]
No, as far as Minecraft is concerned, it think it's his own block, and no doors don't have itemBlocks, they have regular items. (Which I change too)

**Comment by ReikaKalseki** [comment]
The blocks need to have ItemBlocks, and that is why I have this whole system in the first place, as otherwise trying to render the blocks as an item crashes.

**Comment by Ordinastie** [comment]
I'm not sure why you can't use the regular item.
But I think building the block array inside the method registerTechnicalBlocks() should fix the issue.

**Comment by ReikaKalseki** [comment]
> I'm not sure why you can't use the regular item.

I often render the blocks as items in GUIs, and that requires they not construct an ItemStack of null.

**Comment by ReikaKalseki** [comment]
OK, I moved the array declaration internal to the method. This should be fixed.

**Comment by Bogdan-G** [comment]
thanks :)

**Comment by ReikaKalseki** [comment]
Something else is going wrong now, as per another user's report:

at net.malisis.doors.door.block.Door.func_149650_a(Door.java:330)
at Reika.DragonAPI.ModInteract.WailaTechnicalOverride.getWailaStack(WailaTechnicalOverride.java:51)
at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:156)
at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:97)
at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:66)
at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:76)

EDIT:

https://github.com/ReikaKalseki/DragonAPI/blob/master/ModInteract/WailaTechnicalOverride.java#L51

It appears calling getItemDropped() in Malisis causes a crash.

**Comment by Ordinastie** [comment]
Because it's not supposed to get called for that block.
Anyway, I still added a check to prevent the NPE. Will be available in the next update.
