### ISSUE TITLE
REPOST:(now with the right file) When adding Forestry to the mod list causes a RotaryCraft based error while "postinitialisaton" 

### ISSUE THREAD

**Issue by ERYK500** [ReikaKalseki/Reika_Mods_Issues#1910]
When I add the Forestry mod to my mod list, crash happens during the entry into "postinitialisation" fase.
Now with the correct file.
Crash log:
[crash-2018-08-12_17.40.22-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2281101/crash-2018-08-12_17.40.22-client.txt)

**Comment by ReikaKalseki** [comment]
Do not post a second issue for the one immediately before it.
