### ISSUE TITLE
[Chromaticraft] Concurrent mods crash 

### ISSUE THREAD

**Issue by danieru-desu** [ReikaKalseki/Reika_Mods_Issues#1912]
https://pastebin.com/mLfKJpZj
It's not a dublicate since no other mods are referred in stacktrace.

**Comment by danieru-desu** [comment]
I saw someone made a suggestion to fix things like this. It was something like this https://stackoverflow.com/questions/8104692/how-to-avoid-java-util-concurrentmodificationexception-when-iterating-through-an

**Comment by ReikaKalseki** [comment]
#1665
