### ISSUE TITLE
[AE CHC]When adding CHC, the ME interface cannot directly display the recipe in the template.

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#1914]
When adding CHC, the ME interface cannot directly display the recipe in the template . Need to hold down shift , Sorry, my English is not very good.
![tim 20180817123843](https://user-images.githubusercontent.com/19620848/44248145-7248f200-a21b-11e8-8f1c-3752be416ddd.png)
![tim 20180817124702](https://user-images.githubusercontent.com/19620848/44248189-b4723380-a21b-11e8-970a-b2fa31bdd400.png)
ae2stuff-rv3-0.5.1.9-mc1.7.10.jar
appliedenergistics2-rv3-beta-6.jar
bdlib-1.9.4.109-mc1.7.10.jar
ChromatiCraft+1.7.10+V20c.jar
DragonAPI+1.7.10+V20c.jar
ExtraCells-1.7.10-2.3.14b200.jar
p455w0rdslib-1.7.10-1.0.4.jar
p455w0rdslib-1.7.10-1.0.4.jar

**Comment by ReikaKalseki** [comment]
That is how crafting patterns normally work.

**Comment by KuroPeach** [comment]
Normally only in the backpack will not directly display the recipe product, the interface and panel are directly displayed products instead of need to press shift , But after adding chc, you need to press shift to display .

**Comment by ReikaKalseki** [comment]
This does sound vaguely familiar upon some more reflection, and if I had to guess it was an ASM conflict, with the shift-display being the best fix possible.

**Comment by KuroPeach** [comment]
Ok, that's it, just let AE use it a bit more troublesome. ：）
