### ISSUE TITLE
[CHC ExtraTrees]crash when search charcoal recipes

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#1916]
crash when search charcoal recipes , like #530
[crash-2018-08-20_19.46.24-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2302240/crash-2018-08-20_19.46.24-client.txt)

**Comment by ReikaKalseki** [comment]
This is a bug in ExtraTrees.
