### ISSUE TITLE
[CHC , InventoryPets] GG , When standing on the CHC's tes block , the player will die

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#1917]
When standing on the CHC's tes block (Like CHC carft table , CHC pylons , chroma collector ... ) , the player will die , and i was dead again in the creative mode test . 
[crash log.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2303030/crash.log.txt)
![tim 20180820235147](https://user-images.githubusercontent.com/19620848/44351249-080ea680-a4d4-11e8-8441-bccebb05e7dd.png)

**Comment by ReikaKalseki** [comment]
If my blocks are killing you, it is not my doing. They do not harm the player.

**Comment by KuroPeach** [comment]
Okay, I'll change the flight . Like Botania . -_-|||

**Comment by ReikaKalseki** [comment]
That has no connection to anything said thus far.

**Comment by KuroPeach** [comment]
Oh, this happens when you use a cloud pet. It may be that it detects the problem with the bottom block.
