### ISSUE TITLE
[RoC] Bug: Obsidian Factory melts into lava clientside

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1918]
Demonstrated here: https://puu.sh/Bhsb6/274091b07f.mp4

This is a system that feeds 500 mb of water when lava is produced (from smooth stone) and 500mb of water when an item passes from the pipe. Maybe due to server restart, it probably bugged and kept 1000mb of lava inside. (So it goes to 2000mb lava + 1000mb water, then down)

Regardless. As you can see in the video, I can't access the obsidian factory. I can't break it normally. I can't place a block there. I was able to break it after right clicking to make it register for a second and break it.  And I can see it's at 2500C from WAILA.  But it also still keeps working.

**Comment by ReikaKalseki** [comment]
Fixed.
