### ISSUE TITLE
ExpandedRedstone: Item Effector does not ignite netherack with Flint and stell

### ISSUE THREAD

**Issue by the-vindex** [ReikaKalseki/Reika_Mods_Issues#192]
I have otherwise working item effector, but Flint and steel won't ignite netherack (durability still lowers, but when it should break, it gets back to fully repaired).

Setup:
http://i.imgur.com/GtyDqpl.png

Mods:
  DragonAPI 1.7.10 V7f
  ExpandedRedstone 1.7.10 V7a
  accidentallycircumstantialevents-1.8.0
  BiblioCraft[v1.10.5][MC1.7.10]
  bUpload-1.7.2-1.4.1
  CodeChickenCore-1.7.10-1.0.6.43-universal
  CoFHCore-[1.7.10]3.0.3-303
  CoFHLib-[1.7.10]1.0.3-175
  D3Core-1.7.10-1.1.0.30
  EnderCore-1.7.10-0.0.1.14_alpha
  INpureCore-[1.7.10]1.0.0B9-62
  supercraftingframe-1.7.10.3
  extrautilities-1.2.9
  GreenThumb-1.7.10-1.1.0.8
  Gyth-1.1.0-1.7.10
  HardcoreEnderExpansion  MC-1.7.10  v1.8.2
  HelpFixer-1.0.7
  Chisel2-2.4.1.40
  InfernalMobs-1.7.10
  InventoryTweaks-1.59-dev-152
  Jabba-1.2.1a_1.7.10
  journeymap-1.7.10-5.1.0-unlimited
  MineTweaker3-1.7.10-3.0.9C
  MineTweakerRecipeMaker-1.7.10-1.1.0.11
  MobProperties-1.7.10-0.4.0
  ModTweaker~2-0.9.1
  neiaddons-1.12.11.36-mc1.7.10
  NotEnoughResources-1.7.10-0.1.0.106
  NotEnoughItems-1.7.10-1.0.4.107-universal
  RedstonePasteMod-1.7.10-1.6.2
  simplefluidtanks-1.7.10-1.2.0.5
  SpecialMobs-1.7.10-3.1.1
  [1.7.10]StatusEffectHUD-client-1.27
  StorageDrawers-1.7.10-1.5.12
  twilightforest-1.7.10-2.3.7
  ToolUtilities-MC1.7.10-0.0.1-10
  Translocator-1.7.10-1.1.1.14-universal
  Waila-1.5.10_1.7.10
  WailaHarvestability-mc1.7.x-1.1.2
  WAILAPlugins-MC1.7.10-0.1.0-16
  Wawla-1.3.1-1.7.10
  witchery-1.7.10-0.24.1

**Comment by ReikaKalseki** [comment]
It is probably counting as the wrong side. Can you try making it use it "over" netherrack?

**Comment by the-vindex** [comment]
http://i.imgur.com/JfEiqr2.png
Like this? Didn't work.

**Comment by ReikaKalseki** [comment]
The problem is that the effector affects the block _directly_ adjacent and on the adjacent side, leaving no space for fire.

**Comment by ReikaKalseki** [comment]
Fixed.
