### ISSUE TITLE
ElectriCraft v21b - Right-clicking resistor with a non-dye item or empty hand causes crash.

### ISSUE THREAD

**Issue by theyugin** [ReikaKalseki/Reika_Mods_Issues#1921]
Accidentally clicked a resistor without a dye in my hand and this happened.
[crash-2018-08-22_05.52.15-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2308523/crash-2018-08-22_05.52.15-client.txt)

EDIT: Clicked with a non-dye item and it also crashes.
[crash-2018-08-22_06.17.58-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2308549/crash-2018-08-22_06.17.58-client.txt)

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by habnabit** [comment]
Is this released? I saw https://github.com/ReikaKalseki/DragonAPI/commit/a78c36929f8c33c850ec3a906e6eb3391b9aa34e but no new corresponding DragonAPI jar since.

**Comment by ReikaKalseki** [comment]
Not yet.
