### ISSUE TITLE
Bevel gears throwing null pointer on client

### ISSUE THREAD

**Issue by Perkinsj** [ReikaKalseki/Reika_Mods_Issues#1922]
![capture](https://user-images.githubusercontent.com/26077516/44446738-00beca00-a5b4-11e8-8d7a-96eeef74a0be.PNG)
![2018-08-22_02 36 06](https://user-images.githubusercontent.com/26077516/44446818-3499ef80-a5b4-11e8-8539-b8ae42c4f046.png)
These are the bevel gears in question. There is nothing particularly odd about their setup, if it is important they connect to a 2:1 gearbox and a steam engine, as well as another pair of bevel gears leading to a woodcutter. 
The server owner confirmed nothing was sent to the console, also whenever it happened each of the shafts and gears in the area around it rendered the green and red colored boxes from when they are originally placed.

**Comment by ReikaKalseki** [comment]
This is fixed.
