### ISSUE TITLE
Casting Table registering invalid recipe, causing crash.

### ISSUE THREAD

**Issue by Bluberry-Kat** [ReikaKalseki/Reika_Mods_Issues#1923]
I'm hosting a custom modpack, with some of your mods included.
This is a client crash.

I added Forestry, netherportalfix, project red (and relevant coremods), and bibliocraft since the last time it launched successfully. Will try with specific mods on request.
[This is the log, crash and forward, including a modlist at the end.](https://gist.github.com/Birgliss/a565593f05f44de19901c384e10e74ce)
It tells me to inform you immediately.

Edit: Upon further reviewing the contribution guidelines, here is the [crash report,](https://gist.github.com/Birgliss/7e6a7e1cd3c297d6660f8df63440ecf0) and the [full log.](https://gist.github.com/Birgliss/217075478854c25be58d92e333362a37)
we are using 21b for rotarycraft, reactorcraft, electricraft, chromaticraft, and geostrata.

**Comment by ReikaKalseki** [comment]
Fixed.
