### ISSUE TITLE
Crash on Startup at v21b, Chromaticraft

### ISSUE THREAD

**Issue by DweiaCaelum** [ReikaKalseki/Reika_Mods_Issues#1924]
https://paste.feed-the-beast.com/view/1d0eb2cf
It's a modified direwolf20 1.7.10 pack. I just updated to the latest Chromaticraft and Dragon API versions and I get this crash. Not sure what to do, couldn't find anything online

**Comment by ReikaKalseki** [comment]
[Try updating BoP](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Registry/ItemMagicRegistry.java#L338).

**Comment by DweiaCaelum** [comment]
It worked, thank you very much!
