### ISSUE TITLE
[Expanded Redstone]Question/Bug?: Analog wireless transmitter doesn't relay redstone signal

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1926]
This is probably on me not understanding how these work, but I can't seem to get them work.

Angular Transducer says they are connected properly. 

Seen here: https://puu.sh/Bkclj/d3a36a8fd1.mp4

**Comment by ReikaKalseki** [comment]
You are not powering them correctly, and vanilla wire and alloy wire do not mix.

**Comment by cheesealmighty** [comment]
> You are not powering them correctly

What is the correct way of powering them? I thought they worked similar to Chickenbones wireless transmitters. 

> vanilla wire and alloy wire do not mix.

Oh, I was just trying to demonstrate that it doesn't work with neither of them. _I just spammed wires in frustration_

**Comment by ReikaKalseki** [comment]
> What is the correct way of powering them? I thought they worked similar to Chickenbones wireless transmitters.

They are analog transmitters - they therefore need a proper analog signal delivered with redstone wire.

**Comment by cheesealmighty** [comment]
Gosh I feel stupid. Yup. You're right. I don't know why I didn't try with only vanilla redstone and transmitters  aligned correctly. -.- 

_This was all I had to do:_ https://puu.sh/Bknhe/7914b58868.png
