### ISSUE TITLE
Two chromatiCraft crash

### ISSUE THREAD

**Issue by marco6971** [ReikaKalseki/Reika_Mods_Issues#193]
i obtain this one trying to recharge elemental manipultor with a strange pylon, strange because the ball in top of it didn't have a colour and when i try to do a right click on a repeater which theoretically would  be connected doesn't show any number, if if it makes a difference the pylon is of zambarau

http://pastebin.com/brzRgBdz

instead I got this when i try to dig the last tier of crafting system with a draconic evolution staff set to 3x3x9

http://pastebin.com/euVD6F0y

**Comment by ljfa-ag** [comment]
The second one might be on Draconic Evolution's side - issuing a BreakEvent with a null player where should at least be a fake player.

**Comment by ReikaKalseki** [comment]
The first is a duplicate of the ["null player in the world list" issue](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/186) and @ljfa is correct about the second.

The former was originally marked as World Corruption. Given the second report here, I now have a suspicion as to the source. @brandon3055

**Comment by kolatra** [comment]
Pinging @brandon3055.
