### ISSUE TITLE
[V21b/DAPIV21c] Wooden gearboxes spawn illusory persistent fire adjacent to themselves

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1930]
![2018-08-31_21 35 22](https://user-images.githubusercontent.com/2338212/44931374-ed002a00-ad50-11e8-8e18-690c4202a0ba.png)

The fire is cleared by logging out (being clientside) but reappears ~2 minutes after login, and doesn't vanish if gearbox is removed - keeps respawning as long as there's non-air at gearbox coordinates. Doesn't react to punching (left-click) but vanishes momentarily and without noise on using (right-click) block sides adjacent to the fire. Gearboxes that have not been used don't seem to spawn the fire. Occupying the space of the fire doesn't prevent it from reappearing once that block is removed. 

Additionally it sounds similar to #1918 in that it's clientside erroneous-heat-triggered behavior.

Gearboxes cooled to -3C via packed ice on the fin, **EXCEPT** for the one pictured in the screenshot (I added packed ice and it keeps spawning fire), do not spawn the fire. It might be dropping erroneous temperature adjustment below 120C.

Livingwood gearboxes don't spawn fire either (no cooling fin because livingwood).

**Comment by ReikaKalseki** [comment]
I made the fire not spawn clientside. That should fix it.
