### ISSUE TITLE
NoSuchMethodError: Reika.ChromatiCraft.TileEntity.Recipe.TileEntityRitualTable.resetGUIs()V [Server] [Crash] [Chromaticraft]

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1932]
[crash-2018-08-31_23.07.53-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2342027/crash-2018-08-31_23.07.53-server.txt)

Crashed when I entered the chroma dimension.

**Comment by ReikaKalseki** [comment]
Fixed.
