### ISSUE TITLE
[RoC]Bug: Tile Entity Bevel Gears throwing a "class java.lang.NullPointerException"

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1933]
I was booted from the server, while not doing anything of relevance. After I logged back in, this message was seen in the chat. Taken from client logs: https://paste.ubuntu.com/p/9ZGTSFMrJt/

Nothing of interest in server logs.

Seems related to the new bevel gear orientation helper?

**Comment by ReikaKalseki** [comment]
#1922

**Comment by cheesealmighty** [comment]
Ah crap. I didn't see that one. Sorry.
