### ISSUE TITLE
[V21b/DAPIV21c] Diffuser Fan isn't harvesting middle left (looking down at the area) row of blocks in 3x3 setups

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#1934]
![2018-09-01_16 56 59](https://user-images.githubusercontent.com/2338212/44946606-f63fd400-adee-11e8-8d47-c2771b7f9b8f.png)
In this example setup, it's the south middle row, my primary oreberry farms are oriented differently and so same unharvested row is east. It's not shifted sideways because blocks on opposite side of that row, outside the AoE, are not harvested.

**Comment by ReikaKalseki** [comment]
Probably fixed.
