### ISSUE TITLE
Chroma dim chests spawn Draconium dust without DE being installed

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1937]
![2018-09-04_13 23 10](https://user-images.githubusercontent.com/10777735/45046978-c2122080-b045-11e8-90d9-79a83b86544c.png)

just a minor thing I found

**Comment by ReikaKalseki** [comment]
I cannot fix this; I already check that the ore has some product in existence; it is not reasonably possible to know if that product is actually useful.
