### ISSUE TITLE
[RoC]Suggestion: Electrical Age Wrench-Screwdriver & Multimeter-Angular Transducer Compatibility

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1939]
This is probably be niche of the niche. But. Yeah. 

Wrench is for rotating/"should cables care about their colors".

And multimeter is a voltage/amp/power/temperature measuring device.

**Comment by ReikaKalseki** [comment]
What interface should my items implement?

**Comment by cheesealmighty** [comment]
~This screenshot was for something else, but should serve our purposes:~
~This reading: https://puu.sh/BpDE4/98b65b1e48.png~
Hold on, I'll launch minecraft and do it properly. 

Here: https://puu.sh/BqjHn/4d9c3e9c92.png
And, couldn't fit this one: https://puu.sh/BqjJ4/a9c6e5506e.png

Is this what you asked for?

Edit: Also wanted to ask, angular transducer doesn't seem to read project red bundled wires. _I swear this is not the screwdriver incident all over again._ Like, this reading: https://puu.sh/BqjPk/b64243158d.png
Was this intentional?

**Comment by ReikaKalseki** [comment]
No, I mean in the Java sense. In order for my items to work as theirs, they need to have an API for it, and an interface for the item class to implement.

> angular transducer doesn't seem to read project red bundled wires.

It never did.

**Comment by cheesealmighty** [comment]
One does not exist:
https://puu.sh/BqCe3/9cc5a6150a.png

> It never did.

Intended then. Alrighty.
