### ISSUE TITLE
ProjectE and RotaryCraft/ReactorCraft Crash

### ISSUE THREAD

**Issue by dfiel** [ReikaKalseki/Reika_Mods_Issues#194]
After Updating ProjectE, RotaryCraft crashes [with this error](http://pastebin.com/4hQDFpsb).

Here is [a list of mods](http://pastebin.com/bpJRWwYK) that I have installed.

From the patch notes of 1.8.0: \* NOTICE: A new and proper API has been introduced with this update, addon authors will need to update to this new API.

So, it looks like ProjectE broke backwards compatibility. 

I have downgraded ProjectE for now, but could you lok into this?

BTW Reika, Im loving all of your mods! The tiered progression is something not many mods have or use correctly. Thank You!

**Comment by ReikaKalseki** [comment]
Quintuplicate and fixed in v8.

**Comment by dfiel** [comment]
Sorry :/
