### ISSUE TITLE
"ItemBedrockSword cannot be cast to ItemAuraPouch" [Single player] [Crash]

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1940]
[crash-2018-09-06_23.24.42-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2359366/crash-2018-09-06_23.24.42-client.txt)

I was holding my bedrock sword in the farlands in the crc dim hitting them purification rock things.

**Comment by ReikaKalseki** [comment]
Did you attempt to open its GUI during/after a lag spike?

**Comment by lAimBotl** [comment]
not sure tbh

**Comment by ReikaKalseki** [comment]
Fixed.
