### ISSUE TITLE
2X bedrock gear used when right clicking a Bedrock shaft junction

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1942]
2x bedrock gears get used up, even after you turn a shaft junction into a bedrock shaft junction.

**Comment by ReikaKalseki** [comment]
That is intentional.

**Comment by lAimBotl** [comment]
Does adding more do something? 
Can they break/take damage?

**Comment by ReikaKalseki** [comment]
Oh, you mean that it is consumed even on an already-bedrock junction.

**Comment by lAimBotl** [comment]
yeah, bad wording on my part lol.

**Comment by ReikaKalseki** [comment]
Fixed.
