### ISSUE TITLE
[RoC]Bug: Woodcutter "forgets" that it has infinity and also occasionally spawns incorrect saplings

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1944]
I've noticed this before. But woodcutter occasionally "forgets" it has infinity and doesn't replant. Occasionally this seems like a desync issue, as when I try to place a block in the empty space, the sapling reappears. But occasionally does not, and you can place a block there.

Also I've noticed few times that there are jungle saplings laying about, even though there are no relevant trees nearby. Can pick them up and plant them, so they're not visual glitches 

The setup: https://puu.sh/BsccU/765ca037d7.png

**Comment by ReikaKalseki** [comment]
I have had the latter half happen too - it has nothing to do with the woodcutter, and has to do with vanilla tree code being stupid.

**Comment by cheesealmighty** [comment]
Apparently it doesn't forget anything. Just decides not to plant. As when I broke the woodcutter, it dropped ~50 saplings.

**Comment by ReikaKalseki** [comment]
That means it never had a valid location at which to plant them.

**Comment by cheesealmighty** [comment]
That doesn't make sense. It started with no saplings in inventory. I just planted one in front of it. Then it got to 59 on its own.

**Comment by ReikaKalseki** [comment]
How does this not make sense?

**Comment by cheesealmighty** [comment]
As in, without any changes to the blocks around. Between the 0 and 59 sapling point in time. How is there no valid location to plant the saplings?

**Comment by ReikaKalseki** [comment]
Wait, you are saying it gained saplings without even cutting a tree?

**Comment by OvermindDL1** [comment]
I 'think' what @cheesealmighty is saying, based on his prior picture of https://puu.sh/BsccU/765ca037d7.png is that:

1. The infinity treecutter machine has an empty block in front of it that is valid for a tree.
2. It plants a sapling.
3. The sapling grows to a tree.
4. The treecutter machine cuts the tree down then immediately plants a sapling.
5. Goto 2.

And sometime during step 4 it just doesn't plant a sapling.  I'm pretty sure I experienced the same when I tried playing a world with these mods before the 1fps thing eventually killed it for me.

**Comment by cheesealmighty** [comment]
@OvermindDL1 's explanation is correct. That is what I think happened. As there are more spruce logs than I began with, and more saplings in the woodcutter's inventory.

**Comment by ReikaKalseki** [comment]
The only way that could happen is if the game crashed or an exception was thrown (causing the functions to stop running) between the cutting and the planting. While possible, as the intermediate code could error in some circumstances (eg invalid world data), that is not something I can fix.

**Comment by OvermindDL1** [comment]
Hmm, I wonder, @cheesealmighty can you show a picture with the chunk boundaries visible?  I'm wondering if the machine and the plot are in different chunks...

**Comment by cheesealmighty** [comment]
@OvermindDL1 I'm out of town so can't provide a precise photo (will do later). This is out of the archive: https://puu.sh/BCmk7/271b03fc94.png

But on the southwestern border, "woodcuttery". Everything seems to be in one chunk.

**Comment by OvermindDL1** [comment]
I'm unsure then, perhaps the woodcutter just needs to try 'on occasion' while it has saplings?

**Comment by ReikaKalseki** [comment]
Saplings are not just planted in front of the woodcutter - they have a more complicated ruleset than that, and one which is not able to be applied after data about the tree no longer exists.

Additionally, that would break setups where people use another replant mechanism, as is necessary for trees that affect the ground (eg Rainbow trees, Twilight Forest trees, and Natura redwoods).

**Comment by OvermindDL1** [comment]
As the woodcutter is a TE then it could hold the necessary data to be able to recreate the proper tree as NBT or so then dump it upon successful planting when checked on, say, the next tick or so.  In addition, storing that data would make debugging easier as well.

**Comment by ReikaKalseki** [comment]
That will not help - there is no guarantee a world data save will happen - or is even possible, given that bad world data is the primary suspect of a mid-execution crash - between cutting and planting.

**Comment by OvermindDL1** [comment]
> between cutting and planting.

Precisely, hence storing the necessary information in the woodcutter's TE NBT storage would fix it if that's the issue.

**Comment by ReikaKalseki** [comment]
> Precisely, hence storing the necessary information in the woodcutter's TE NBT storage would fix it if that's the issue.

No, because in all likelihood that data will never actually get saved to disk.

**Comment by OvermindDL1** [comment]
> No, because in all likelihood that data will never actually get saved to disk.

If a disk save happens during the few ticks that it would have it then it would be saved, else not but it's not needed then either (unless you wanted to keep the 'last' setup as well for other reasons).

**Comment by ReikaKalseki** [comment]
> If a disk save happens during the few ticks that it would have it then it would be saved

Which it would be unlikely to do, as disk saves are fairly rare events. And this does not even consider the fact that since the likely cause of the crash is invalid world data, the save is possible even if it *was* attempted during the time window.
