### ISSUE TITLE
[DragonAPI] Bug: "Detected invalid ME system when running..."

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1947]
Server logs are printing this every two minutes: https://paste.ubuntu.com/p/JjX4KBJvVy/

Although everything seem to be in order (ie. The ME system works fine, items go in items go out.)

Edit: Restarting the server seems to fixed the issue.

**Comment by pjolin** [comment]
I don't have an exact log, but the Unknown Artefact generate the same type of errors (about corruption effects, not radiation effects). 

One time was when an ME network was killed: I had put my first artefact in ME, then read the entry, went "oh shit!", removed the artefact and put it in a chest -- later on, moved home based, dismantled that ME and it started spamming errors so fast that server was ticks got really bad (dropped below 20 TPS). 

Another time at a lower, non-server-messing rate seemed to be when an ME lost power (I made a fake / separate ME to see what corrpution effects did, and its battery ran out).

**Comment by ReikaKalseki** [comment]
#1995
