### ISSUE TITLE
Client crashes related to recipes / transmutation flame

### ISSUE THREAD

**Issue by T5UN4M1** [ReikaKalseki/Reika_Mods_Issues#1948]
Hello,

I'm having client crashes when :

- Trying to visualize transmutation flame recipes.
- Trying to visualize dandelion recipes (maybe other items are causing crashes too, haven't tried many things but nether stars, diamonds and boosted crystals don't cause crash for example).
- Trying to put a dandelion inside a transmutation flame.
- Tried to check recipes for karmir flowers and it causes a crash too.

I'm running latest version of DNS techpack for 1.7.10 with everything updated to 21b and the addition of CC and ER.

Crash reports :
https://pastebin.com/VELgHnpp
https://pastebin.com/xQVzxmRj
https://pastebin.com/ZExg8Lcs

**Comment by ReikaKalseki** [comment]
Fixed.
