### ISSUE TITLE
Rendering issue with RotaryCraft Handbook

### ISSUE THREAD

**Issue by Sinhika** [ReikaKalseki/Reika_Mods_Issues#195]
In my SSP game, at random intervals, when viewing the RotaryCraft Handbook, something throws an exception that dumps exception spam to chat, and all the icons vanish from the handbook tabs. They do not return unless I quit out and restart. I have attached screenshots showing the normal look, followed by the chat spam & missing icons.  There are also gists of both the client & server logs.

Note: I could not duplicate the bug until I resized the Minecraft window from default.

![2015-08-11_15 15 37](https://cloud.githubusercontent.com/assets/5017178/9209853/5d1d9b48-403e-11e5-95b2-77ecdd976807.png)
![2015-08-11_15 24 10](https://cloud.githubusercontent.com/assets/5017178/9209855/641e9a46-403e-11e5-9316-779670828944.png)
![2015-08-11_15 24 20](https://cloud.githubusercontent.com/assets/5017178/9209859/69ab0c10-403e-11e5-8756-ec0296e16e85.png)
![2015-08-11_15 24 42](https://cloud.githubusercontent.com/assets/5017178/9209868/6f22ca0c-403e-11e5-992a-cb270f15b44d.png)

client log: https://gist.github.com/Sinhika/c4b0e357077f154020fb#file-rotarycraft-handbook-issue-client-log

server log:  https://gist.github.com/Sinhika/3f72ca5df660ee285203#file-rc-handbook-issue-server-log

**Comment by ReikaKalseki** [comment]
Something invalid may be in the OreDict. Try removing mods.

**Comment by Sinhika** [comment]
after lots of troubleshooting, I isolated the offending mod: Chisel 2.  After I went through its config file and disabled all chisel bocks from mods I don't have, the issue went away.
