### ISSUE TITLE
[ChC] Crash with Shard of Laputa / Improve compatibility

### ISSUE THREAD

**Issue by kutschkem** [ReikaKalseki/Reika_Mods_Issues#1950]
Botanias Shard of Laputa transposes landmasses up to the sky. Obviously that leads to crashes when Pylons are involved, and probably some other blocks.

In order to exclude blocks from moving, Botania provides the Interface ILaputaImmobile, which has a method to check whether a block can be moved. This needs to implemented by the block.

https://github.com/Vazkii/Botania/blob/483a816616d86f5ff36e1fc150afa1527042efce/src/main/java/vazkii/botania/api/mana/ILaputaImmobile.java

**Comment by kutschkem** [comment]
While you are at it, there is also a rod that can move entities. If you want to exclude some entities from that, there is an API method for that as well:

https://github.com/Vazkii/Botania/blob/483a816616d86f5ff36e1fc150afa1527042efce/src/main/java/vazkii/botania/api/BotaniaAPI.java#L335

**Comment by ReikaKalseki** [comment]
Does that exist in 1.7.10 as well?

**Comment by kutschkem** [comment]
The links point to the 1.7.10 branch, so that's what I assume.

**Comment by ReikaKalseki** [comment]
Not for me, they just go to the latest. But I can get to the 1.7.10 branch easily enough.

**Comment by ReikaKalseki** [comment]
Done.
