### ISSUE TITLE
[RoC] Bug: Fans affect a bedrock armored player and a non armored player the same amount

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1951]
Demonstrated here:  https://puu.sh/BtXLr/5afade5108.mp4

Ignore the 200 value. Repeated testing resulted in 180 (ticks?) for both situations.

**Comment by ReikaKalseki** [comment]
When I said 'dampens', I did not mean 'entirely negates'.

**Comment by cheesealmighty** [comment]
No, I got that. But as you can see, it pretty much does not affect at all.

**Comment by ReikaKalseki** [comment]
Also, fans have more use than blowing crops; the intended use of vertical fans was always as an elevator.

**Comment by cheesealmighty** [comment]
Ah. True. Fair enough. I mean, _why am I working on my farms when the fans are running in the first place._
