### ISSUE TITLE
[RoC] Shaft Junction in splitting mode does not receive power from shaft power bus

### ISSUE THREAD

**Issue by pjolin** [ReikaKalseki/Reika_Mods_Issues#1952]
A Shaft junction in Splitting mode will not accept power from a Shaft Power Bus, even if an angular transducer says it does: 

![image](https://user-images.githubusercontent.com/8095523/45457461-098b5300-b6bd-11e8-8e13-fa34941092a5.png)

The shaft junction does not animate, and whatever is connected to its output does not get any power even if, again, angular transducer says it does: 

![image](https://user-images.githubusercontent.com/8095523/45457549-7a326f80-b6bd-11e8-829c-29312b6df15b.png)

In Merge mode it works as expected:  

![image](https://user-images.githubusercontent.com/8095523/45457502-3475a700-b6bd-11e8-9a9d-b172540f88c1.png)

**Comment by ReikaKalseki** [comment]
Fixed.
