### ISSUE TITLE
[CC] Suggestion: Copy/Save Particle Spawner Settings & Manual Value Input

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#1953]
Being able to 1: copy settings to another spawner, and 2: save settings in case it gets broken, would be amazing.

Also, being able to type in specific values for the various fields would also be fantastic.

**Comment by ReikaKalseki** [comment]
#.2 is impossible - where would they be saved if the block is deleted?

**Comment by OvermindDL1** [comment]
Serialize the NBT state into a special entry on a new item just for saving such data?

**Comment by ReikaKalseki** [comment]
I do not want to add a new item just for this.

**Comment by OvermindDL1** [comment]
Could save it into the world NBT storage keyed on the location to it's data, useable once only or something.

Personally I'm not a fan of editing spawners to be honest.

**Comment by ReikaKalseki** [comment]
This is the particle spawner, not mob spawner.

**Comment by OvermindDL1** [comment]
Oh, my mis-check then!  How about just store the last 'copied' ones necessary data in the player's NBT then?

**Comment by ReikaKalseki** [comment]
As it is, player NBT is prone to being overloaded, which causes it to wipe entirely. Pairing CC and Morph together in a pack already results in a ton of such reports as it is.

**Comment by OvermindDL1** [comment]
> which causes it to wipe entirely.

That bug is *still* there?!  Thought forge was supposed to have fixed that...  >.>

**Comment by Shahelion** [comment]
I don't know if it's possible with these, but I know the draconic evolution particle generators can copy settings using a piece of paper that saves the settings in its NBT or something.

**Comment by OvermindDL1** [comment]
> I don't know if it's possible with these, but I know the draconic evolution particle generators can copy settings using a piece of paper that saves the settings in its NBT or something.

That's what I suggested above but Reika said he didn't want to use a new item for it, but he said nothing about using an existing item...

**Comment by ReikaKalseki** [comment]
And I would be willing to implement that.

**Comment by ReikaKalseki** [comment]
It turns out the linker already has this power.

**Comment by Shahelion** [comment]
WHAt
