### ISSUE TITLE
[CrC & RC] Woodcutter deposits items to inventory due to Inventory Insertion enchant

### ISSUE THREAD

**Issue by Fishy51** [ReikaKalseki/Reika_Mods_Issues#1954]
The woodcutter deposits items to your inventory while holding a pickaxe with the new inventory insertion enchantment. This might affect other machines but I haven't checked.

Edit: Just checked the boring machine and it happens with it as well.

**Comment by ReikaKalseki** [comment]
OK, I can see why this is happening. Fixing it, however...

**Comment by ReikaKalseki** [comment]
Fixed.
