### ISSUE TITLE
Aura tracker particles aren't emitted from the correct location when morphed into small creatures like bats

### ISSUE THREAD

**Issue by T5UN4M1** [ReikaKalseki/Reika_Mods_Issues#1955]
Hello,

I thought at first that the aura tracker wasn't working, but actually the particles are emitted  from above your head when you are morphed into a small creature, which means that you can only see them if you look up.

This is with Morph mod and CC v21B.

![screen](https://user-images.githubusercontent.com/12467635/45532922-224b5400-b7f6-11e8-8bfb-962e7e037b07.png)
![screen2](https://user-images.githubusercontent.com/12467635/45532933-2e371600-b7f6-11e8-938e-bee40f23d625.png)

**Comment by ReikaKalseki** [comment]
I am not sure I can fix this...

And with it being solvable with a simple unmorph, I am not sure it is worth trying.
