### ISSUE TITLE
[ChC] "Inside" block ores have a wrong rotation of base block texture + shading issue(?)

### ISSUE THREAD

**Issue by HellsingDarge** [ReikaKalseki/Reika_Mods_Issues#1957]
It's only wrong on the [sides](https://user-images.githubusercontent.com/20254450/45562549-f327f780-b874-11e8-847e-3aff427af2ed.png)

And they seem to have a shading(?) [issue](https://gfycat.com/OrderlyThriftyHorsemouse) (checked without Optifine and FastCraft)

Both issues are present in v20a

**Comment by ReikaKalseki** [comment]
I have fixed both, but the fix for the first introduces an incorrect rotation on the top surfaces. Honestly, I prefer it.
