### ISSUE TITLE
ChocolateQuest issue

### ISSUE THREAD

**Issue by OvermindDL1** [ReikaKalseki/Reika_Mods_Issues#1959]
The latest most version of ChocolateQuest is giving an error in the ChC log:
```
Could not add ChocolateQuest integration, as his API is not accessible (Java code visiblity). Contact that developer.
```
Well the developer is gone, so I took a look, it appears at in this file:
https://github.com/ReikaKalseki/ChromatiCraft/blob/master/ModInterface/ModInteraction.java#L229-L251

There is this code:
```java
			RegisterChestItem.treasureList.add(new WeightedItemStack(ChromaItems.FRAGMENT.getStackOf(), 40));

			for (int i = 0; i < 16; i++) {
				ItemStack is = ChromaItems.SHARD.getStackOfMetadata(i);
				int wt = CrystalElement.elements[i].isPrimary() ? 50 : 25;
				RegisterChestItem.mineralList.add(new WeightedItemStack(is, wt));
			}
```
However that does not follow the API laid out by the BetterDungeons(Chocolate) mod, what it looks like it should actually be is:
```java
			RegisterChestItem.addTreasureItem(ChromaItems.FRAGMENT.getStackOf(), 40);

			for (int i = 0; i < 16; i++) {
				ItemStack is = ChromaItems.SHARD.getStackOfMetadata(i);
				int wt = CrystalElement.elements[i].isPrimary() ? 50 : 25;
				RegisterChestItem.addMineralsChestItem(is, wt);
			}
```
And that should follow the API correctly at this point and populate the treasure and minerals properly.  :-)

**Comment by OvermindDL1** [comment]
Oh, and also delete the `import com.chocolate.chocolateQuest.API.WeightedItemStack;` at the top of the file as that is a private class, not public.

**Comment by ReikaKalseki** [comment]
My imports are calculated automatically. No edit I make is persistent.

**Comment by OvermindDL1** [comment]
> My imports are calculated automatically. No edit I make is persistent.

As is usual for most IDE's, just stating to be certain.  :-)

**Comment by ReikaKalseki** [comment]
Done.
