### ISSUE TITLE
Crash with Voltz

### ISSUE THREAD

**Issue by OvermindDL1** [ReikaKalseki/Reika_Mods_Issues#1960]
Got a crash with an odd mix of things when I was testing Voltz in this megapack with all dragonapi's mods, it seems that at this line:  https://github.com/ReikaKalseki/DragonAPI/blob/master/Libraries/Registry/ReikaItemHelper.java#L726
```java
((IEnergyItem)i).discharge(is, Double.POSITIVE_INFINITY, true);
```
Is supposed to be:
```java
((IEnergyItem)i).discharge(is, Integer.MAX_VALUE, true);
```
And changing it does indeed get it working.

**Comment by ReikaKalseki** [comment]
Done.
