### ISSUE TITLE
RotaryCraft screwdriver not working on MFR machines

### ISSUE THREAD

**Issue by OvermindDL1** [ReikaKalseki/Reika_Mods_Issues#1961]
Yet it looks like it is supposed to be working according to:  https://github.com/ReikaKalseki/RotaryCraft/blob/master/Items/Tools/ItemScrewdriver.java#L69
```java
powercrystals.minefactoryreloaded.api.IToolHammer, IWrench, ICarpentersHammer, com.bluepowermod.api.misc.IScrewdriver
```
However, checking the MFR API shows that `IToolHammer` does not exist, however it seems it it supposed to be `powercrystals.minefactoryreloaded.api.IMFRHammer`, so  `powercrystals.minefactoryreloaded.api.IToolHammer` needs to be changed to `powercrystals.minefactoryreloaded.api.IMFRHammer` in the implementation, the annotation above it by 2 lines, and the import.  It seems `IToolHammer` is the pre-1.7.10 name but it was changed by 1.7.10 so I'm unsure how this would have worked before?

**Comment by ReikaKalseki** [comment]
Done.
