### ISSUE TITLE
Discovered the massive start-up slowdown cause in ChC

### ISSUE THREAD

**Issue by OvermindDL1** [ReikaKalseki/Reika_Mods_Issues#1965]
When loading ChC it takes a *long* time to load during a specific segment in the log, here is the log snippet, see the times:
```log
...
[11:36:54] [Client thread/INFO] [FML/ChromatiCraft]: CHROMATICRAFT: Loaded Reika.ChromatiCraft.TileEntity.AOE.Effect.TileEntityStabilityCore$InfusionStabilityInterface@318d23f6 for Thaumcraft
[11:46:44] [Thread-11/INFO] [STDOUT/]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[11:46:44] [Sound Library Loader/INFO] [STDOUT/]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:56:44] [Client thread/ERROR] [FML/ChromatiCraft]: DRAGONAPI ERROR: MIDI system unavailable.
[11:56:44] [Client thread/INFO] [FML/ChromatiCraft]: DRAGONAPI: Reading MIDI at Resources/music-demo.mid
[11:56:44] [Client thread/ERROR] [FML/ChromatiCraft]: DRAGONAPI ERROR: Could not load MIDI; MIDI system unavailable.
[11:56:44] [Client thread/ERROR] [FML/ChromatiCraft]: DRAGONAPI ERROR: Sequence is empty!
[11:56:44] [Client thread/INFO] [FML/ChromatiCraft]: CHROMATICRAFT: Loaded demo track [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]
[11:56:44] [Client thread/TRACE] [FML/ChromatiCraft]: Automatically registered mod ChromatiCraft entity Ball Lightning as ChromatiCraft.Ball Lightning
...
```
Watched the system interaction and it is probing *MANY* MIDI interfaces that don't exist (since I have no midi hardware hooked up, who does even have one anymore, that's ancient...  o.O) and that sole MIDI check is taking *20* minutes of probing time (40 non-existing devices at 30-second timeouts a piece).  Some googling reveals this:  https://stackoverflow.com/questions/14842735/midisystem-getsequencer-very-slow

Essentially if you aren't working with MIDI hardware than the Java midi system should not be used.  This slowdown happens on everyone I personally know that has attempted ChC.  Forcing a `return null;` thunk into the javax `MidiSystem.getSequencer` call makes the mod load *SO* much faster, night-and-day difference in loading speed, but that's obviously not something I want to do every-single-load as it's a quite annoying to do and doesn't fix the mods significantly slow loading for anyone else.

Essentially the `MidiSystem.getSequencer` call in ChC needs to be removed, the game should not be accessing MIDI hardware regardless (why would it need to be?!).

**Comment by OvermindDL1** [comment]
Heh, well I found my old synthesizer keyboard and hooked it up to my computer after dusting it off; ChC probes 6 devices at 30-second timeouts each before it finds it, so the game loads 17 minutes faster at least with this keyboard synthesizer plugged in, but it still doesn't fix it for anyone else and I still have 3 wasted minutes worth of it polling.  ^.^

**Comment by ReikaKalseki** [comment]
CC uses MIDIs to store the crystal orchestra data. "Just remove it" is not an acceptable answer.

That said, the IO is clientside, and it is generally a headless server where the MIDI system does not exist, so what is going on?

**Comment by OvermindDL1** [comment]
> CC uses MIDIs to store the crystal orchestra data.

The Midi system in Java is designed for use with Midi hardware, it is not for use as a generic midi playback system as it implements no waveform transformer.  Another library should be used for that.

Specifically, is the `crystal orchestra data` only played via in-game sound effects (because I remember it playing fine, thus obviously not using MIDI hardware to play it) and thus the midi system is only used for reading and parsing the midi file?  If so the midi format is *so* simple that you can parse it yourself (or I can write one for you) but there are tons of libraries out there to do just that because it is so simple as well.

Regardless, the Java Midi system is designed for use with hardware midi interfaces.  *However*, if you only need to read and parse data then I think you can call `MidiSystem.getSequencer(false)` to get an unattached sequencer and it shouldn't poll then.  Let me double check that...  Nope, running `MidiSystem.getSequencer(false)` is still slow (yet not polling *everything*, but still accessing hardware that doesn't exist, wtf...).

So what of the Midi functionality is needed?

> That said, the IO is clientside, and it is generally a headless server where the MIDI system does not exist, so what is going on?

Well when I don't have my synthesizer plugged in I *definitely* don't have any midi hardware installed on my desktop regardless (nor do any of the other people that have the same super-slow-loading issue), thus looooong polling it does (which is odd, I don't know why java is doing it that way when it can just query udev directly and instantly...).  ^.^;

**Comment by OvermindDL1** [comment]
Actually it looks like if you 'just' need the midi track data to perform your own sounds based off of it, then you don't need a sequencer at all, this works just fine and has no speed issues (I'm just using scala here because it has an easy repl that is *fantastic* for testing java code, the equivalent java is obvious):
```scala
╰─➤  scala                                                                                                                      127 ↵
Welcome to Scala version 2.11.6 (OpenJDK 64-Bit Server VM, Java 1.8.0_181).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import javax.sound.midi.MidiSystem
import javax.sound.midi.MidiSystem

scala> import java.io.File
import java.io.File

scala> val seq = MidiSystem.getSequence(new File("./src/main/java/Reika/ChromatiCraft/Resources/music-demo.mid"))
seq: javax.sound.midi.Sequence = javax.sound.midi.Sequence@5b87ed94

scala> seq.getTickLength()
res0: Long = 76684

scala> seq.getTracks()
res1: Array[javax.sound.midi.Track] = Array(javax.sound.midi.Track@fad74ee, javax.sound.midi.Track@1a1d6a08, javax.sound.midi.Track@37d31475, javax.sound.midi.Track@27808f31, javax.sound.midi.Track@436e852b, javax.sound.midi.Track@32d2fa64, javax.sound.midi.Track@1d8d30f7, javax.sound.midi.Track@3e57cd70, javax.sound.midi.Track@9a7504c, javax.sound.midi.Track@2c039ac6, javax.sound.midi.Track@587d1d39, javax.sound.midi.Track@58c1670b, javax.sound.midi.Track@6b57696f)

scala> seq.getTracks().map(_.size())
res2: Array[Int] = Array(9, 119, 26, 37, 7, 52, 126, 11, 70, 1, 126, 1, 47)

scala> seq.getTracks().map(_.get(0))
res3: Array[javax.sound.midi.MidiEvent] = Array(javax.sound.midi.MidiEvent@8807e25, javax.sound.midi.MidiEvent@567d299b, javax.sound.midi.MidiEvent@2b80d80f, javax.sound.midi.MidiEvent@3c5a99da, javax.sound.midi.MidiEvent@7c75222b, javax.sound.midi.MidiEvent@2133c8f8, javax.sound.midi.MidiEvent@1a407d53, javax.sound.midi.MidiEvent@1810399e, javax.sound.midi.MidiEvent@2ef5e5e3, javax.sound.midi.MidiEvent@6f7fd0e6, javax.sound.midi.MidiEvent@66a3ffec, javax.sound.midi.MidiEvent@2ac273d3, javax.sound.midi.MidiEvent@6fc6f14e)

scala> seq.getTracks().map(_.get(0).getMessage())
res4: Array[javax.sound.midi.MidiMessage] = Array(javax.sound.midi.MetaMessage@644abb8f, javax.sound.midi.MetaMessage@1a411233, javax.sound.midi.MetaMessage@70325d20, javax.sound.midi.MetaMessage@7c2327fa, javax.sound.midi.MetaMessage@4d847d32, javax.sound.midi.MetaMessage@5f462e3b, javax.sound.midi.MetaMessage@3d7fa3ae, javax.sound.midi.MetaMessage@58065f0c, com.sun.media.sound.FastShortMessage@3605c4d3, javax.sound.midi.Track$ImmutableEndOfTrack@585c13de, com.sun.media.sound.FastShortMessage@187eb9a8, javax.sound.midi.Track$ImmutableEndOfTrack@726a6b94, com.sun.media.sound.FastShortMessage@6ad11a56)

scala> seq.getTracks().map(_.get(0).getMessage().getMessage())
res5: Array[Array[Byte]] = Array(Array(-1, 88, 4, 9, 3, 12, 8), Array(-1, 3, 8, 86, 105, 111, 108, 105, 110, 32, 49), Array(-1, 3, 8, 86, 105, 111, 108, 105, 110, 32, 50), Array(-1, 3, 7, 86, 105, 111, 108, 97, 32, 49), Array(-1, 3, 7, 86, 105, 111, 108, 97, 32, 50), Array(-1, 3, 5, 67, 101, 108, 108, 111), Array(-1, 3, 4, 66, 97, 115, 115), Array(-1, 3, 7, 84, 105, 109, 112, 97, 110, 105), Array(-57, 98), Array(-1, 47, 0), Array(-56, 24), Array(-1, 47, 0), Array(-53, 48))

scala> // The midi data for this track on this channel!
```

**Comment by OvermindDL1** [comment]
In fact, it looks like `MIDI_LOADER` only exists in https://github.com/ReikaKalseki/DragonAPI/blob/master/IO/ReikaMIDIReader.java and it is only used like: https://github.com/ReikaKalseki/DragonAPI/blob/master/IO/ReikaMIDIReader.java#L100-L107
```java
	private static Sequence readMIDIFromFile(InputStream in) throws IOException, InvalidMidiDataException {
		if (MIDI_LOADER == null) {
			DragonAPICore.logError("Could not load MIDI; MIDI system unavailable.");
			return null;
		}
		MIDI_LOADER.setSequence(in);
		return MIDI_LOADER.getSequence();
	}
```
So yes, in fact a sequence is all that is needed, so replacing that entire function with just this:
```java
	private static Sequence readMIDIFromFile(InputStream in) throws IOException, InvalidMidiDataException {
		return new MidiSystem.getSequence(is);
	}
```
And removing all the `MIDI_LOADER` and the sequencer constructor stuff is all that needed, just looks like it was overly complex was all.  :-)

**Comment by ReikaKalseki** [comment]
I need to test that this still works.

**Comment by ReikaKalseki** [comment]
It works.
