### ISSUE TITLE
um?? (render bug with chromaticraft casting altar)

### ISSUE THREAD

**Issue by Bluberry-Kat** [ReikaKalseki/Reika_Mods_Issues#1967]
forge version is most recent (1614)
modlist [here](http://www.modlister.com/user/Cavariel)
i am using v21b for all of your mods.

the bug itself: 
![the lumen dial takes up the whole screen.](https://cdn.unascribed.com/sleepingtown/media_attachments/files/000/568/104/original/e0ef08564e00b89d.png)

while holding shift:
![displays as normal.](https://cdn.unascribed.com/sleepingtown/media_attachments/files/000/568/105/original/514f4f14ec24db8e.png)

as a sidenote, it's fun seeing which layer each element of the UI is drawn on.
and apologies for the mess of the top left, i've been meaning to look into configs to see if i can move it q.q

**Comment by ReikaKalseki** [comment]
How much energy is in that block? If it has more than its capacity, that will happen.

**Comment by Bluberry-Kat** [comment]
how would i be able to check that? i'll get on that as soon as i know how

though uh
i have noticed some weird interactions regarding the repeater network, i assume it's not giving the altar energy because it already has more than it can hold

**Comment by Bluberry-Kat** [comment]
nevermind, i found out.

and also... _woah_
![image](https://user-images.githubusercontent.com/20749209/45713430-11377580-bb5d-11e8-85e9-3bcb37c8225d.png)

i imagine this probably means there's not a whole lot to fix, huh. i doubt the altar is meant to have this much in it.

**Comment by ReikaKalseki** [comment]
2G is approximately Int.MAX, so I suspect something is very wrong indeed.

**Comment by Bluberry-Kat** [comment]
my personal take is probably file corruption. wouldn't be the first on the server.
"Not Worth Fixing" is only half correct, as there's nothing to fix, i think.

**Comment by ReikaKalseki** [comment]
Well, one could argue it can be fixed by clamping the render, but that is not worth the effort given that such a state should not be possible to begin with.

**Comment by Bluberry-Kat** [comment]
i have no complaints with this outcome.
