### ISSUE TITLE
logspam with the fluid link anchor

### ISSUE THREAD

**Issue by Bluberry-Kat** [ReikaKalseki/Reika_Mods_Issues#1968]
using most recent version of forge (1614)
modlist ![here](http://www.modlister.com/user/Cavariel)
i am using v21b for all relevant mods

i have a fluid link anchor connected to a chroma collector, a crystal tank, and a reservoir
the chroma collector is at pressure +10, the tank at -10, and the reservoir at -20

upon stepping on the chroma collector, the log is filled with [this](https://gist.github.com/Birgliss/dbb1fda3bebf06036d5d76515c755d77) and continues to do so until fluid is no longer transferred.

note that removeErroringTileEntities is set to true on the serverside (only, for some reason? i should fix that) due to a prior crash. i imagine this is related.

EDIT: the logspam persists even when the config is synced between client and server
i could disable it (the bug crashing the server has since been fixed) but it still feels like it's of some concern.

**Comment by ReikaKalseki** [comment]
#1642
