### ISSUE TITLE
[RoC] Machines disappear when broken with critical health pick

### ISSUE THREAD

**Issue by Fishy51** [ReikaKalseki/Reika_Mods_Issues#1969]
When you break most machines (ex. gas turbine) with a pick that's about to break, the pick and machine will disappear.

![2018-09-19_00 39 36](https://user-images.githubusercontent.com/38511269/45729036-41a30200-bba5-11e8-967c-edb3dd41d0ae.png)
![2018-09-19_00 39 41](https://user-images.githubusercontent.com/38511269/45729043-47004c80-bba5-11e8-8c44-6c346605046d.png)
![2018-09-19_00 39 48](https://user-images.githubusercontent.com/38511269/45729048-4a93d380-bba5-11e8-8591-ee2540b5f14d.png)

**Comment by ReikaKalseki** [comment]
This is because drops are processed after the tool is destroyed. The same happens to vanilla blocks.
