### ISSUE TITLE
Industrial Coil Comparator Output

### ISSUE THREAD

**Issue by hilburn** [ReikaKalseki/Reika_Mods_Issues#197]
When the Industrial Coil is fully charged it outputs 15 into a comparator - however the next tick it will explode due to the lag of the comparator updating and the response of any control it is connected to.

While it is possible to shut off at 14 - not utilising 7% of capacity hurts my soul and seems to run counter to the general feel of RotaryCraft - i.e. do everything as ell as possible.

To counter this would it be possible to calculate the comparator output as (energy_stored+power_input) / total_energy_capacity - which would let you turn off the coil when it is actually full.

**Comment by ljfa-ag** [comment]
As far as I know, vanilla chests and other mods' storages such as Energy Cells work the same way - they only emit power 15 when they're _really_ full.
But well, this case might be different due to the explosion risk...

**Comment by ReikaKalseki** [comment]
The /20 conversion factor messes with this, as well as the fact that I still do not see most players being willing to push it to absolute fullness.

**Comment by hilburn** [comment]
@ljfa-ag yeah I wasn't saying there's anything technically wrong with the current system it just... feels wrong.

@ReikaKalseki I understand the implementation might have to be different - but I feel the concept is valid - a big chunk of the fun of these mods for me is designing a system with absolutely no un-utilised capacity, and having to work with long timers rather than the comparator output just feels a bit wasteful to me

**Comment by ReikaKalseki** [comment]
Done.
