### ISSUE TITLE
Bedrock Pipes gone?

### ISSUE THREAD

**Issue by EbonyDean** [ReikaKalseki/Reika_Mods_Issues#1970]
Sorry if I missed something somewhere, but while checking the RotaryCraft handbook I noticed that Bedrock Pipes are gone. And from this I decided to check on my Fractionation Unit, where I found the Pipe gone from the connection. I don't know if this is an intended, undocumented change (quick search for bedrock in the changelogs found only very old changes to bedrock gears and dust drop-rate), or if it's a bug. I use Bedrock Pipes with my Fractionation Unit because after connecting it to my HP Turbine and pumping items with a Steam Engine, it literally destroyed all my fuel lines and voided a huge amount of fuel on its way to my reservoirs, where they're then transferred to Drums and other fluid storage systems.

**Comment by ReikaKalseki** [comment]
Bedrock pipes still exist....

**Comment by EbonyDean** [comment]
Indeed o.o. Found them, but when I updated from V19C to V21a (is that the one available now?) all the pipes I had set up vanished, as well as all the pipes I had crafted (which weren't a lot, thankfully).

Thanks for the help, sorry for the unintended non-issue. I forgot NEI existed and didn't check before posting :/.

**Comment by ReikaKalseki** [comment]
That should not have happened - I did nothing to change them.
