### ISSUE TITLE
[RoC] Suggestion: Dynamometer redstone output for monitoring

### ISSUE THREAD

**Issue by cheesealmighty** [ReikaKalseki/Reika_Mods_Issues#1971]
Basically something similar to Reactorcraft one. But to increase utility with a configurable max value. Since engine outputs varies wildly.

Without this, controls are blind to whether a system is actually running or not. You could check the outputs of the system, but that's not a good metric. I'm also aware of the extensive OC support. But having analog controls for a thing that could have analog controls would be better.

What I mean:
Redstone output = (Current Unit/User set max unit)*15

Unit can be chosen as power, speed or torque. 

Project red support would be a bonus (Just calculate with 255 instead of 15)

Also as side note, something N8Crafter suggested:

 > a remote screen for the dynamometer 

Would be nice too.

**Comment by ReikaKalseki** [comment]
Comparators have this power on the dynamometer.

**Comment by cheesealmighty** [comment]
Oh. Is it possible to add info about this to the handbook then? While it's my bad for not even trying, but still would've been helpful to know.

**Comment by ReikaKalseki** [comment]
Comparators reading stuff is vanilla behavior; this is not the sort of thing to put in the handbook.

**Comment by cheesealmighty** [comment]
I meant how the comparator output is calculated.

**Comment by ReikaKalseki** [comment]
?

**Comment by cheesealmighty** [comment]
I tried hooking up a DC engine to it, RS = 1
And a Gas Turbine, RS= 15

How is this value calculated?

Edit: Is this it?

https://github.com/ReikaKalseki/RotaryCraft/blob/b0186c720410cf61968f17bae46a88cd56185d3d/TileEntities/Transmission/TileEntityMonitor.java#L136-L139

RS = (Current power/1MW)*15

**Comment by ReikaKalseki** [comment]
Yes, that would be it.

**Comment by cheesealmighty** [comment]
Nice. Thanks :3 ~Time to slap monitors everywhere~
