### ISSUE TITLE
[CrC] Alloying tank rendering issue

### ISSUE THREAD

**Issue by Fishy51** [ReikaKalseki/Reika_Mods_Issues#1972]
Not a big deal but when breaking the sheilding glass portions of the alloying tank when full of chroma the chroma texture remains. It will disappear when the main tank block is broken.

![2018-09-24_19 04 58](https://user-images.githubusercontent.com/38511269/46040916-23308f80-c0ec-11e8-8e47-89a407aa5e82.png)

**Comment by ReikaKalseki** [comment]
Fixed.
