### ISSUE TITLE
[CrC] Chromastone not alloying

### ISSUE THREAD

**Issue by Fishy51** [ReikaKalseki/Reika_Mods_Issues#1973]
The chromastone recipe seems to have broken itself and will not work for me anymore. I have tried the alloying tank and in a pool of chroma methods. It was working earlier in my world and I can make other alloys.

Pics of materials and after 5 minutes of waiting:
![2018-09-25_19 03 30](https://user-images.githubusercontent.com/38511269/46044904-a9ea6a00-c0f6-11e8-895f-d36a70b47bf8.png)
![2018-09-25_19 03 58](https://user-images.githubusercontent.com/38511269/46044910-ace55a80-c0f6-11e8-8d3b-1f48d8395305.png)

**Comment by ReikaKalseki** [comment]
Do you still have the required progression?

**Comment by Fishy51** [comment]
I assume I do. I can still make the other alloys.

How can I check?

**Comment by ReikaKalseki** [comment]
That was how you check. Does the issue persist across relogging? Server reboot? Replacing the chroma?

**Comment by Fishy51** [comment]
It has been happening the past few times I have played (single player world) and I tried chroma in different places with and without ether berries.

Haven't tried in a different dimension yet, though I doubt that would make a difference.

**Comment by Fishy51** [comment]
Tried again today and it appears to have fixed itself, which is strange as this is the third day with it broke. Though I moved the tank a couple chunks over when I tried again this time.

**Comment by ReikaKalseki** [comment]
Test if that matters.
