### ISSUE TITLE
[1.7.10] Chromaticraft/Clonecraft Crash on opening Human GUI

### ISSUE THREAD

**Issue by Glitchtone** [ReikaKalseki/Reika_Mods_Issues#1977]
Please don't shoot me on sight for making a thread for a 1.7.10 issue.  I am using a custom modpack that has Chromaticraft, Rotarycraft, Reactorcraft, Expanded Redstone, Electricraft and DragonAPI v21C which just came out a few months ago, as I know Reika updates older versions of his mods.

My issue is a crash that occurs when making a human clone from Clonecraft and right-clicking on them to open their GUI.  The screen freezes and the NEI options start to overlay with the Clonecraft GUI and then crashes.
<script src="https://pastebin.com/embed_js/d7J9gRsk"></script>
https://pastebin.com/d7J9gRsk

Please DO NOT dismiss this issue as redundant, as I am aware it has been brought up twice before in the issues tab; however it has incorrectly been dismissed as a Clonecraft problem both times.  I have reproduced this error in another pack that has all of Reika's mods removed and the clone GUI works fine.  

I would not be posting about a three-year old mod if it were not my only choice.  I am simply trying to create a modpack with as many great mods as possible and I would be extremely overjoyed if I could have this mechanic working. Thanks.

**Comment by ReikaKalseki** [comment]
This code changed for v22 - try again then.

**Comment by Glitchtone** [comment]
Thank you.

**Comment by Glitchtone** [comment]
Any idea when v22 will be out?

**Comment by ReikaKalseki** [comment]
When it is ready.

**Comment by Garr890354839** [comment]
When will it be ready?

**Comment by Glitchtone** [comment]
I'm fine with however long it takes, but a timetable would be nice.  A day, a week, a month?

**Comment by Glitchtone** [comment]
I understand you're probably really busy; but its been two months and all we've asked for is a relative timetable or confirmation that v22 is even going to be released.  I would like to know if I should keep waiting or find another solution.

**Comment by ReikaKalseki** [comment]
It will be released, and not in the distant future.

**Comment by Glitchtone** [comment]
Alright, thank you.

**Comment by Glitchtone** [comment]
Just found out that V22 was out today.  Unfortunately it did not solve the issue and I got virtually the same crash report except this time it thinks its a RotaryCraft problem.

https://pastebin.com/hsXpquAv

**Comment by Glitchtone** [comment]
I can confirm that after removing RotaryCraft and all dependents that opening the gui works fine.  Chromaticraft at least works which is what is important.  This will be the solution that I will use.

**Comment by Glitchtone** [comment]
Is it possible to please get a reasonable estimate as to when this glitch will receive a fix.  
Just something general in terms of weeks or months would be highly appreciated.  This will let me determine if I will be able to use Rotarycraft, Reactorcraft and Electricraft in my modpack.

**Comment by Glitchtone** [comment]
Are there any plans to fix the mod or not for awhile?  I would really like to play minecraft again.

**Comment by ReikaKalseki** [comment]
Is the stacktrace still exactly the same (including line numbers)?

**Comment by Glitchtone** [comment]
The line numbers are the same and the error looks very very similar, except it has some slight number differences with the event manager.  For instance
Crash before v22 line 8: (ChromaticEventManager.java:580)
Crash with v22 line 8: (RotaryEventManager.java:357)
I have no idea what is actually causing it as I have little experience with code, but it seems to be roughly the same error, just caused by different Rotarycraft and Chromaticraft eventmanagers.

**Comment by ReikaKalseki** [comment]
What is the entirety of the new stack trace?

**Comment by Glitchtone** [comment]
The crash report is up there, you'd be able to tell better than me.

**Comment by ReikaKalseki** [comment]
`((InventoryPlayer)evt.inventory).player.stepHeight = 0.5F;`

He must be manipulating a player inventory that has no player. This is invalid. Go ahead and ping him here.

**Comment by Glitchtone** [comment]
Well rip, guess I can't use Rotary or Reactorcraft.

**Comment by Glitchtone** [comment]
This just occurred to me.  One, it is not the other mod's end because this works fine without your mods installed, and two the reason it is manipulating a player inventory is because the event is creating another entity which has a player-like inventory.

**Comment by ReikaKalseki** [comment]
> This just occurred to me. One, it is not the other mod's end because this works fine without your mods installed, and two the reason it is manipulating a player inventory is because the event is creating another entity which has a player-like inventory.

A player-like inventory must always have a player associated with it.

**Comment by Glitchtone** [comment]
Regardless, this function of the mod works perfectly fine without Rotarycraft and Reactorcraft installed.  Plus, years ago this issue was brought to the creator of Clonecraft's attention and they were able to confirm that it was not an issue with Clonecraft.
The individual didn't put their crash report in a link, I apologize, but it did answer some questions.
https://github.com/Jamezo97/CloneCraft/issues/23

**Comment by ReikaKalseki** [comment]
> and they were able to confirm that it was not an issue with Clonecraft.

No, they either failed to understand the report or simply lied to avoid taking responsibility. Just because a mod appears in a stacktrace does not make it responsible for the crash.

**Comment by Glitchtone** [comment]
How then does the mod running fine without rotarycraft make sense.

**Comment by ReikaKalseki** [comment]
Because of the mods you have, I am the only mod actually checking that sort of thing. If you install a mod that causes worldgen hooks to break, and then 19 more that add no worldgen, then add ThaumCraft, the fact that the world generator now crashes with TC and not without it does not make it TC's fault; it remains the fault of the mod which made worldgen break to begin with.

Moreover, this particular hook is one I ASMed in, meaning that most other mods cannot even track the slot events, and thus could not be affected as they never have access to the broken piece of code in the first place.

**Comment by ReikaKalseki** [comment]
Also linking #2081 because it is the same idea - another mod doing something objectively incorrect but which causes a crash as soon as a mod tries to track that action, and which few mods *can* track (in both cases because DragonAPI is what grants that ability) and thus few mods will bring the broken code to light.

**Comment by Glitchtone** [comment]
Alright, thanks for trying anyways.
