### ISSUE TITLE
[Crc v21b] Crash on startup

### ISSUE THREAD

**Issue by PiscesdanAT** [ReikaKalseki/Reika_Mods_Issues#1978]
The crash seems to occur during Phase 1 of the loading process.
The following versions are used:

- DragonAPI 1.7.10 V21c
- Chromaticraft 1.7.10 V21b
- Forge 10.13.4.1448-1.7.10

Link ot the [crashlog](https://pastebin.com/MdMjgsY3)

**Comment by ReikaKalseki** [comment]
If there was a hard dependency on ThaumCraft, it would have been reported by now - v21 has been out for months.

Something must have gone wrong during loading - show me your full loading log.

Also, this was the issue you had @Ariaxis , so that info could be useful as well.

**Comment by PiscesdanAT** [comment]
[Here is the log](https://pastebin.com/MRMpeVBQ)

**Comment by ReikaKalseki** [comment]
@Strippable failed...but I have no idea why. Try adding ThaumCraft to your installation to see if this failure is universal, or just with that one class.

**Comment by PiscesdanAT** [comment]
Since Thaumcraft required me to update to forge 10.13.4.1558 I first tried to only do that and see if it worked. It now loaded everything just fine even without TC, but when trying to create a new world, I got a different crash.

[Here](https://pastebin.com/bGHfW2f9) is the new log.

**Comment by ReikaKalseki** [comment]
Update Forge again.

**Comment by PiscesdanAT** [comment]
Okay, that worked. Thank you for taking the time.
