### ISSUE TITLE
[ChromatiCraft] Cave Crystal dupe with Transmutation Flame and RC Grinder

### ISSUE THREAD

**Issue by jeremiahwinsley** [ReikaKalseki/Reika_Mods_Issues#1979]
Version: v21b (SMP)

A crystal shard provides 80 lumens when used as fuel for the transmutation flame. A cave crystal requires 560 lumens, or 7 shards. The RotaryCraft grinder drops 18 shards from each cave crystal, a total of 1440 lumens.

**Comment by ReikaKalseki** [comment]
Fixed.
