### ISSUE TITLE
Concrete Placement Crash

### ISSUE THREAD

**Issue by egeis** [ReikaKalseki/Reika_Mods_Issues#198]
While working on a modpack I discovered an interesting error caused by placing reactorcraft concrete.  If the block is placed through flowing liquids, grass tiles (not the block), or other no block tiles the following crash results. 

The following error report is when placing in flowing lava, was cleaning up a little mess....
java.lang.ArrayIndexOutOfBoundsException: 9 with a similar error log occurs on grass elements on top of grass blocks.

http://paste.ee/p/txyDP
FastCraft is enabled.

**Comment by ReikaKalseki** [comment]
Is RailCraft's hidden block enabled? Try removing other mods. Something screwed up the in-world metadata.

**Comment by egeis** [comment]
"B:residual.heat=false" It was causing issues in other places already so I disabled it a while ago.  I don't think I have played a pack where this was enabled and never caused issues.

**Comment by egeis** [comment]
I was able to reproduce the bug, with flowing liquids, on a client with only your mods and NEI installed. What I did was dig a channel from a river, and then after the water flowed the entire length, dug down two more blocks; fill the blocks below the flowing water with more flowing water.  I then attempted look down and fill the hole with concrete blocks. 

http://paste.ee/p/ErtFX

**Comment by ljfa-ag** [comment]
Actually, Minecraft calls <tt>getCollisionBoundingBoxFromPool</tt> from <tt>canPlaceEntityOnSide</tt>, i.e. it gets called when it checks whether the block can be placed there.

Stupid vanilla behavior but I guess you have to expect any number as metadata there, at least when the block at that position is not <tt>this</tt>.

**Comment by ReikaKalseki** [comment]
This is....unspeakably stupid and irritating.

**Comment by ljfa-ag** [comment]
Aand another label was born :P

**Comment by ReikaKalseki** [comment]
Fixed.

```
@Override
public AxisAlignedBB getCollisionBoundingBoxFromPool(World world, int x, int y, int z) {
    if (world.getBlock(x, y, z) != this) //because MC is retarded
        return super.getCollisionBoundingBoxFromPool(world, x, y, z);
    MatBlocks m = MatBlocks.matList[world.getBlockMetadata(x, y, z)];
    if (m == MatBlocks.SCRUBBER)
        return null;
    return super.getCollisionBoundingBoxFromPool(world, x, y, z);
}
```
