### ISSUE TITLE
Crystal Orchestra midi use on server under certain size don't play

### ISSUE THREAD

**Issue by Zuler0** [ReikaKalseki/Reika_Mods_Issues#1980]
Having issues using midi files with the Crystal Orchestra on my server which are under a certain size, I am not certain at what point this happens, but it didn't work with files 20 KB or less for me.

**Comment by ReikaKalseki** [comment]
It is not about size, but encoding - those MIDIs are likely encoded differently (and wrongly). There are multiple ways MIDIs are encoded, but only one is "official" and recognized by the Java parser.

**Comment by Zuler0** [comment]
Ah, ok thanks for the quick response, me and my friends are enjoying messing around with the Crystal Orchestra with the midi files that are encoded correctly(working).
