### ISSUE TITLE
1.7.10 Rotarycraft + Thaumcraft research crash

### ISSUE THREAD

**Issue by Alexus13** [ReikaKalseki/Reika_Mods_Issues#1981]
Game crash when i click - open research in RotaryCraft or Chromaticraft tab at Taumonomicon.

(The 'Nuts and bolts modpack')

Crash log, short:

Description: Rendering screenDescription: Rendering screen
Reika.DragonAPI.Exception.MisuseException: DragonAPI or one of its subclasses or methods was used incorrectly!The current error was caused by the following:You cannot query an XML data set before reading it from disk! at Reika.DragonAPI.Instantiable.IO.XMLInterface.getValueAtNode(XMLInterface.java:162) at Reika.DragonAPI.ModInteract.DeepInteract.ReikaThaumHelper$XMLPage.getTranslatedText(ReikaThaumHelper.java:635) at thaumcraft.client.gui.GuiResearchRecipe.drawPage(GuiResearchRecipe.java:352) at thaumcraft.client.gui.GuiResearchRecipe.genResearchBackground(GuiResearchRecipe.java:281) at thaumcraft.client.gui.GuiResearchRecipe.func_73863_a(GuiResearchRecipe.java:236) at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) at net.minecraft.client.main.Main.main(SourceFile:148) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) at org.multimc.EntryPoint.listen(EntryPoint.java:170) at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by ReikaKalseki** [comment]
#1946 #1941 #1913
