### ISSUE TITLE
GeoStrara's ore block variants are show as "Coal Ore" in WAILA for modded ore

### ISSUE THREAD

**Issue by HellsingDarge** [ReikaKalseki/Reika_Mods_Issues#1982]
Ore drop is as expected, judging by the looks of the block 
[Example](https://user-images.githubusercontent.com/20254450/47255029-7b14a900-d494-11e8-82e3-50c4440ab650.png) (dropped Osmium ore from Mekanism)

It also seems that Thaumcraft's infused stones break block [render](https://user-images.githubusercontent.com/20254450/47255052-d777c880-d494-11e8-9da5-50aa1c8b1520.png) (dropped Water Shards, Fastcraft is installed)

**Comment by ReikaKalseki** [comment]
GeoStrata ore is only half implemented because it has far more serious issues than this.
