### ISSUE TITLE
Friction Heater affecting cobblestone causes crash on server.

### ISSUE THREAD

**Issue by Azzezima** [ReikaKalseki/Reika_Mods_Issues#1984]
So i placed a block of cobblestone in this case next to a powered friction heater and i saw "error" on waila when looking at the heater and the server crash shortly afterwards.
A player getting close to it or me in this case logging back in next to it would crash the server again with this report:

https://pastebin.com/qzyVPcMV

Managed to temporarily fix the issue by letting someone else replace nearby blocks from the heater to air with a 300 block radius 300 blocks away using world edit.

**Comment by Garr890354839** [comment]
You're only supposed to put a furnace on it, not cobblestone

**Comment by ReikaKalseki** [comment]
This is already fixed for release.
