### ISSUE TITLE
Steam line capacity issue with ammonia

### ISSUE THREAD

**Issue by dieselfuelonly** [ReikaKalseki/Reika_Mods_Issues#1986]
I've discovered an issue with the fact that steam lines have a basically unlimited capacity - with a liquid such as ammonia that isn't as easy to produce in essentially limitless quantities like water is, how is one supposed to keep an ammonia reactor running?  I have a fission reactor producing ammonia steam and a single HP turbine.  The reactor produces a slight excess of steam in order to keep the turbine running at full power without studdering.   The steam lines start filling up with ammonia steam faster than the turbine consumes it  since their capacity is unlimited.  Since the only ammonia that is recaptured and repressurized is what is run through the turbine, it's easy to run out of ammonia and lose the ability to cool the reactor which doesn't end well.

**Comment by ReikaKalseki** [comment]
I do not want to impose a capacity limit - there needs to be another way.

**Comment by dieselfuelonly** [comment]
What about capacity dependent on pressure? Unpressurized a limit of say, 50m3 of steam per section of steam line?  Use a pipe pump to increase the pressure, with the pressure increasing with the amount of torque put into the pipe pump?  Currently a pipe pump is required to keep my turbine running without a stutter in power output.  This leads to all of the steam being compressed into the single steam line that is part of the turbine multiblock as I have the pipe pump placed directly before that.  So the pipe pumps currently seem to extrapolate the issue.  However, even running without the pipe pumps (and therefore causing the stutter) the steam lines still seem to fill to a possibly infinite capacity.  I've tested this with about 40,000mb of ammonia and it shows no signs of leveling out the amount consumed and stored in the steam lines to the amount returned into the system.

**Comment by ReikaKalseki** [comment]
No, that is still a capacity limit, which will end up changing how reactor dynamics work in all cases.

Also, pressure implies the ability to *over*pressure, and thus an explosion. I do not want that implication either.

**Comment by dieselfuelonly** [comment]
Ok what about allowing turbines to pass excess steam through a steam output eventually ending at a condenser directly connected to a steam line that converts it to low pressure which can flow back into the pressurizer loop.  
![img_20181028_133735](https://user-images.githubusercontent.com/11864247/47619675-fa6b3380-dab7-11e8-8051-71fb241c843d.jpg)

**Comment by dieselfuelonly** [comment]
Here is a perhaps better illustration of what I envision

![editme](https://user-images.githubusercontent.com/11864247/47622453-5e532380-dadb-11e8-8266-1e052fbf26bc.jpg)

**Comment by ReikaKalseki** [comment]
That is just voiding energy, which is even worse.

**Comment by dieselfuelonly** [comment]
Depends on the setup.  Obviously a massive reactor and a single LP turbine would be wasting a large amount of energy.  Size the reactor appropriately to the load (turbines) and there should be little energy wasted if you choose to recover the ammonia from the unused steam.  It still leaves the ability to fill the unlimited capacity steam lines if one chooses to do so but would also give those that want to use ammonia the ability to recover excess without having hundreds of thousands of buckets worth of ammonia steam suck in the lines.  The only other option using current mechanics that I see is setting up more turbines than can be powered by the reactors steam production and using the extra turbines as a way to recover the ammonia.  However I feel like a turbine not running at full capacity with rapidly fluctuating output would probably not be a good thing for performance.

**Comment by EyeDeck** [comment]
I have solved this with a ComputerCraft script before, like so:
```lua
function toggleGrates(on)
	redstone.setOutput("left", (not on))
	redstone.setOutput("right", (not on))
end

target = 1000
line = peripheral.wrap("back")
venting = false
toggleGrates(venting)

while true do
	steam = line.getSteam()
	if (venting) then
		if (steam < target * 0.9) then
			venting = false
			toggleGrates(venting)
		end
	else
		if (steam > target * 1.1) then
			venting = true
			toggleGrates(venting)
		end
	end
	print("steam: " .. steam .. "; venting: " .. tostring(venting))
	sleep(5)
end
```

**Comment by ReikaKalseki** [comment]
Honestly, I think a better approach here is to design the reactor to be able to be shut down if cooling supply is lost.

**Comment by dieselfuelonly** [comment]
That's too bad that you feel that it is an issue not worth addressing.  To me it feels like using a completely unrelated and unrealistic method in order to work around an issue that is definitely worth finding a realistic and reasonable solution to.   Your mods such as ReC feature such a wonderful amount of immersion and realism I would really hope to see (and help with if needed) some kind of a fix rather than having to use a janky workaround.

**Comment by ReikaKalseki** [comment]
I do not mean relying on something like ComputerCraft; I mean a simple mechanism like a control rod deployment system, using either the native reactor CPU or some sort of temperature control.

**Comment by dieselfuelonly** [comment]
Using current mechanics I guess the steam line can be viewed as more of a "tank" than a pipe since it has a seemingly infinite capacity.   I could use OpenComputers to read the amount of steam stored in a steam line, probably the piece of line furthest from the reactor, and modulate the control rods in order to keep a certain amount of steam stored in that piece of line in order to keep the turbine running at full speed, but not allowing an infinite buildup that would quickly deplete stored ammonia and overload the generation system.

Is there a reason you are totally against introducing some kind of capacity limit to the steam lines?

I'd love to see you keep this issue open so we could still work on ideas for some kind of a solution.

**Comment by ReikaKalseki** [comment]
> Is there a reason you are totally against introducing some kind of capacity limit to the steam lines?

Because it will fundamentally change how literally every reactor design works, and in many cases will result in reactors suffering meltdowns as they lose the ability to export coolant.
