### ISSUE TITLE
Make GPR not have fixed Y range

### ISSUE THREAD

**Issue by Garr890354839** [ReikaKalseki/Reika_Mods_Issues#1987]
Before you ask, yes. I am giving it 419TW of power (1TW=1000GW), which is _WAY_ bigger than the 32768W minimum, and also much bigger than 1TW of power maximum, calculated by math.

As usual, config below:

# Configuration file

"Control Setup" {
}

"achievement ids" {
    I:BEDROCKBREAKER=24015
    I:BEDROCKSHAFT=24019
    I:BEDROCKTOOLS=24020
    I:BORER=24009
    I:CUTKNOT=24037
    I:CVT=24018
    I:DAMAGEGEARS=24026
    I:DIAMONDGEARS=24027
    I:DOUBLEKILL=24041
    I:EXTRACTOR=24005
    I:FAILSTEEL=24002
    I:FLOODLIGHT=24025
    I:GIGAWATT=24029
    I:GPR=24008
    I:GPRENDPORTAL=24036
    I:GPRSPAWNER=24035
    I:GRAVELGUN=24032
    I:INSANITY=24042
    I:INSTANTBED=24043
    I:JETCHICKEN=24021
    I:JETENGINE=24012
    I:JETFAIL=24022
    I:JETFUEL=24010
    I:LANDMINE=24033
    I:LIGHTFALL=24023
    I:MAKERAILGUN=24013
    I:MAKESTEEL=24001
    I:MAKEYEAST=24004
    I:MASSIVEHIT=24039
    I:MRADS32=24028
    I:NETHERHEATRAY=24034
    I:OVERPRESSURE=24040
    I:PCB=24006
    I:PULSEFIRE=24044
    I:PUMP=24007
    I:RAILDRAGON=24030
    I:RAILKILLED=24031
    I:RAREEXTRACT=24038
    I:RCUSEBOOK=24000
    I:RECYCLE=24011
    I:SPRINKLER=24024
    I:STEAMENGINE=24016
    I:STEELSHAFT=24017
    I:SUCKEDINTOJET=24014
    I:WORKTABLE=24003
}

"client specific" {
    B:"[CF79601FF] Color Blind Mode"=false
    D:"[EA6BD5812] Engine Volume"=1.0
    D:"[M40529FFC] Machine Volume Multiplier"=1.0
    B:"[R16E21C4C] Run power transfer code on client"=false
    B:"[RCAB28114] Reload Handbook Data on Open"=false
    B:"[REC3B0099] Render projector lines"=true
    I:"[S65D526A4] Sprinkler Particle Density"=4
    B:"[T5E3169BA] Tools Clear Chat"=true
}

"control setup" {
    B:"Allow Bedrock Breaker to Break Y=0"=false
    B:"Allow Bedrock Pickaxe to Harvest Spawners"=true
    B:"Allow Blast Glass to be Used as TE Hardened Glass"=false
    B:"Allow Build Blocking of Some Machines"=false
    B:"Allow Craftable Bedrock"=true
    B:"Allow EMP"=true
    B:"Allow Frames to move Machines (May cause corruption)"=false
    B:"Allow Gravel Gun PvP"=true
    B:"Allow Nonstandard Recipe Modifications"=false
    B:"Allow RC steel to be used in other mods"=false
    B:"Allow TNT Cannon"=true
    B:"Allow other mods' aluminum dust to make Silicon"=true
    B:"Allow special bedrock tool abilities in automation"=true
    B:"AutoCrafter Lag Profiling And Compensation"=true
    I:"Bait Box Range"=24
    B:"Block Damage from Destructive Machines"=true
    I:"Block Ram Range"=512
    I:"Borer Chunk Gen Radius"=0
    D:"Borer Power Requirement Factor"=1.0
    B:"Borer Requires Maintenance"=false
    I:"Breeder Range"=128
    I:"Cave Scanner FOV"=16
    I:"Chest Generation Tier"=4
    I:"Chunk Loader Max Radius in Chunks"=8
    B:"Conservative Jetpack Firing"=true
    S:"Core Recipe Editing"=X
    B:"Crafting Table can Make Machines"=true
    I:"Difficulty Control"=2
    B:"Direct Block Damage from Machine Failures"=false
    B:"Disable Automining Machines"=false
    B:"Disable Silver Iodide Cannon Rain"=false
    I:"EMP Charging Speed"=4
    B:"Enable Achievements"=true
    B:"Enable Blast Furnace recipe gating"=false
    B:"Enable Chunk Loader"=true
    B:"Enable Item Cannon"=true
    B:"Enable Light Bridge"=true
    B:"Enable Worktable recipe gating"=false
    B:"Extractor Drill Wears Down"=false
    I:"Fluid Flow Speed"=5
    B:"Force Inter-Mod Ore Compatibility"=true
    B:"GPR Renders Ores"=true
    B:"Hard Mode EU Compatibility"=false
    B:"Harder Converter Unit Recipes"=false
    B:"Hardmode Gravel Gun"=false
    B:"Increased Harvest Level for HSLA"=false
    B:"Instant Woodcutter"=true
    D:"Iron Ore Density"=1.0
    B:"Item Pump Spills Items If Dumping To Air"=true
    B:"Jetpack Requires Jet Fuel"=false
    B:"Jetpack bypasses allow-flight property"=true
    I:"Liquid Spiller Range, Use Zero to Disable"=16
    B:"Lock enchants on bedrock tools"=false
    B:"Log Block Placement and Removal"=false
    B:"Machine Warning Alarms"=false
    I:"Max Aerosolizer Range"=128
    I:"Max Bait Box Mob Count"=256
    I:"Max Bridge Range"=512
    I:"Max Fan Range"=128
    I:"Max Floodlight Range"=512
    I:"Max Force Field Range"=128
    I:"Max Heat Ray Range"=512
    I:"Max Sonic Weapon Range"=128
    I:"Max Vacuum Range"=128
    B:"Owner-Only Machine Use"=false
    D:"Pipe Block Hardness"=0.0
    I:"Player Detector Range"=128
    I:"Power Converter Loss Percent"=0
    B:"Railgun Block Damage"=true
    B:"Rotate Hose/Pipe/Fuel Line Recipes"=false
    I:"Rotational Dynamo Recipe Difficulty"=0
    I:"Sonic Borer Range"=512
    B:"Spawn Mobs When Harvesting Spawners By Hand"=true
    B:"Spawn XP from Friction Heater"=true
    B:"Spawn with RC Handbook"=true
    I:"Spawner Mob Limit"=100
    B:"Strong Recipe Editing"=false
    B:"Terraformer Block Editing"=true
    B:"Turrets can target players"=true
    B:"Tutorial Mode"=false
    I:"Use Forestry Bees To Produce Yeast"=0
}

"other ids" {
    S:"Bedrock Tool Material ID"=80
    S:"Freeze Potion ID"=35
    S:"HSLA Tool Material ID"=81
}

"other options" {
    S:"Alternate Blast Furnace Materials" <
     >
}

**Comment by ReikaKalseki** [comment]
Define "Not working".

**Comment by Garr890354839** [comment]
I feed it power and I open the GUI and it shows me a pink line, not the ground beneath. It also doesn't show the green power inputs, and it is as if no power is going into it.

**Comment by ReikaKalseki** [comment]
"Pink" is unrecognized blocks, and block-type machines do not have IO render. Neither of those are issues.

What does the angular transducer say?

**Comment by Garr890354839** [comment]
> "Pink" is unrecognized blocks, and block-type machines do not have IO render. Neither of those are issues.
> 
> What does the angular transducer say?

Nothing. I even thought of that before I asked you (See fig. 2+3) I also tried experimenting with power values less than 2147483647W (maximum 32-bit signed integer). Still nothing.

Also, the power bar in the GPR GUI is reading as if no power is going in. (See Fig. 1)

![2018-10-31_15 36 22](https://user-images.githubusercontent.com/10093603/47814154-508fdf00-dd23-11e8-822c-f60bee0e6740.png)

Figure 1 (above): The GPR GUI 

![2018-10-31_15 36 31](https://user-images.githubusercontent.com/10093603/47814155-508fdf00-dd23-11e8-8442-ae318ddc5785.png)

Figures 2 (above) and 3 (below): Using the Angular Transducer

![2018-10-31_15 36 33](https://user-images.githubusercontent.com/10093603/47814156-508fdf00-dd23-11e8-9f53-c0a121a1d5e9.png)

Figure 4 (below): Power input of 419TW: 4194304Nm @ 99999999rad/s

![2018-10-31_15 39 26](https://user-images.githubusercontent.com/10093603/47814158-51287580-dd23-11e8-8ff0-1d47aeae340f.png)

**Comment by Garr890354839** [comment]
I discovered why: It's because my Y-level was above a certain level. You could've made it scroll like you did with Chromaticraft's undescriptive lexicon.

**Comment by ReikaKalseki** [comment]
This may not be a bug, but that is old code, and the GPR could do with a situational implementation.

**Comment by Garr890354839** [comment]
I am horrible at explaining. I'm sorry for not telling you that.

**Comment by ReikaKalseki** [comment]
The GPR now functions at any altitude, though still limited to a 96-y range.
