### ISSUE TITLE
[ChC] Inv. Insertion Enchant putting stuff in Armor Slots.

### ISSUE THREAD

**Issue by Garr890354839** [ReikaKalseki/Reika_Mods_Issues#1988]
Am I supposed to wear blocks as armor?

**Comment by ReikaKalseki** [comment]
It calls my generic "add to player inventory" code, which in turn calls generic "Add to *any* inventory" code. If that was broken, it would be known by now.

Either you have a mod changing the player GUI filters, or you experienced a case of the occasional slot mixup which I have seen myself, and which is not restricted to any one item or behavior.
