### ISSUE TITLE
XP not being generated by Friction Heater for some items

### ISSUE THREAD

**Issue by vedalken254** [ReikaKalseki/Reika_Mods_Issues#199]
Hey Reika!

Having an issue: Some items do not seem to trigger an XP generation from the Friction Heater. Specifically the flakes from RotaryCraft as well as some raw Vanilla ores. I have an item vacuum nearby and when it's smelting Iron Ore Flakes, the XP is not generated at all. First Discovered when i was smelting Nether Iron Flakes. Also, Item Vacuum next to a vanilla furnace seems to pull inputs out as well before they can be smelted.

EDIT: So after looking further into it, any Iron derivative seems to be affected. Iron Ore, Iron Ore Flakes, Nether Iron Ore, and Nether Iron Flakes do not generate XP... Nether Gold Flakes do generate XP correctly.

**Comment by ReikaKalseki** [comment]
> Specifically the flakes from RotaryCraft as well as some raw Vanilla ores.
> 
> any Iron derivative seems to be affected. Iron Ore, Iron Ore Flakes, Nether Iron Ore, and Nether Iron Flakes do not generate XP.

I know this to be false, as I have it doing this on my server to the point where turning off the vacuum caused the TPS to drop from accumulated XP.

It also makes no sense from a code standpoint, as I do not specifically exclude iron:

https://github.com/ReikaKalseki/RotaryCraft/blob/master/RotaryRecipes.java#L1061
https://github.com/ReikaKalseki/RotaryCraft/blob/master/Auxiliary/RecipeManagers/ExtractorModOres.java#L46

**Comment by vedalken254** [comment]
@ReikaKalseki that's odd then. I've even gone as far as removing the item vacuum which doesn't fix what I'm experiencing. I'll try spawning in some stuff to check more though.

**Comment by vedalken254** [comment]
@ReikaKalseki http://imgur.com/ya0v8m5,qbQRuFo is imaging of the vacuum being gone and the ore being smelted. Still no XP coming from it. I don't think me having vanilla Hoppers feeding the Furnace and auto-extracting ingots from it would cause this type of issue. I can post my modlist if you'd like?

**Comment by ReikaKalseki** [comment]
Is the config on?

**Comment by vedalken254** [comment]
@ReikaKalseki http://pastebin.com/BPnP1B5f

**Comment by ReikaKalseki** [comment]
A "yes" would have sufficed. :P

Try with only my mods.

**Comment by vedalken254** [comment]
Will do. It'll take a few minutes though... need to backup the world and then fire up forge again.

**Comment by vedalken254** [comment]
@ReikaKalseki It appears to be a mod interaction of some kind. Although why even vanilla Iron would be affected is beyond me. Although now that I think of it, Thermal Expansion's Pulverized Iron did give XP earlier in the game.... I'll look into it some more, but it looks like it's some other mod (Probably Thermal Expansion or CoFHCore) causing the problem.

**Comment by vedalken254** [comment]
I take that back... User Error >.<... Apparently without me realizing it, I never downloaded CoFHLib. I noticed that as I was placing my modpack back to the way it was and thought, "Hmmm... that screwup might be the culprit." and it was. /me hits self with self-loathing shunhammer.

EDIT: Apparently CoFHCore now includes CoFHLib by default so there shouldn't be a need to explicitly install it. Guess I get to go digging this weekend.
