### ISSUE TITLE
Chromaticraft Crash happens randomly

### ISSUE THREAD

**Issue by TomSmash** [ReikaKalseki/Reika_Mods_Issues#1991]
[Chromaticraft Crash.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2545072/Chromaticraft.Crash.txt)

Seems to happen randomly, once every few hours or so. I've gone 8+ hours without a crash or sometimes it crashes within 20 mins. It doesn't seem to be triggered by anything I'm doing specifically.

Let me know if you need any other info

**Comment by ReikaKalseki** [comment]
#1100 and others.
