### ISSUE TITLE
[ChC] Lexicon is _severely_ underwritten

### ISSUE THREAD

**Issue by Garr890354839** [ReikaKalseki/Reika_Mods_Issues#1992]
Some examples:
Lumen Relays: didn't know they needed a source. (I do now, but that would've been so helpful)
What the symbols mean (the power symbols that show up when shift-clicking items)
Proxima: Good lord. SO much is missing here. Like what the puzzles are, what the rainbow trails at about Y=512... The only thing I got was the Zambarau Puzzle Lock. (Water Wheel... Thingy) And, also, the restorative ritual. WHAT IS IT? 

Descriptions would help a lot. I do love a good puzzle, if only I know what to do. If you want progression to be paramount, then fill in descriptions as the player progresses. This is acceptable, and better than undescribed

**Comment by Barhandar** [comment]
It's supposed to be ~mysterious\~, including _absolutely everything_ about Proxima.

Moreso that entirety of Lexicon is publicly accessible, and a _lot_ easier to read than code.

**Comment by ReikaKalseki** [comment]
One of the core features of ChromatiCraft is that nothing is spoon-fed to you; the information you need is provided, but in nonobvious form, or is fragmented.

You are demanding I change that so you do not have to do the very thing I designed it to force - figure things out.

**Comment by Garr890354839** [comment]
Very well then. I mean, the dimensional puzzles could use a basic description of how to operate them, but nonetheless, if that's what you want, then have it. I mean, what's the fun of a puzzle if you don't know how to operate it?

**Comment by Duckfan77** [comment]
Part of the puzzle is determining how to operate it. I have  many puzzles that just present you with the puzzle, and then you need to figure out how it works, what the goal is, all of that.

**Comment by ReikaKalseki** [comment]
Not that it is difficult, either. Imagine you are dropped into a Portal map with no explanation of the gun or the puzzle elements - say a faith plate, a funnel, a cube, a button, and a fizzler. Aside from *perhaps* the white-surface rule, is there anything you could not *very* readily work out yourself?
