### ISSUE TITLE
[ChC] java.lang.NullPointerException: Unexpected error 

### ISSUE THREAD

**Issue by Garr890354839** [ReikaKalseki/Reika_Mods_Issues#1996]
After reading the README.md I felt bad for you having to scroll down my crash logs and deal with my temper.

https://pastebin.com/wbdMFUVb <-- Crashlog

Also, living near a pylon (within render distance of one) causes the game to throw this exception in random times:

https://pastebin.com/e8jc3gy5

Details: The pylon in question is a turbocharged pink pylon. (Death message: "%s got in a fight with a Crystal Pylon and lost.")

Also, all your textures animate, but I run a stupidly large modpack (in excess of 300 mods), and it would bring my FPS down to less than 10 if I animate _all_ the textures. This is a problem because things like ability costs and crystal energy in items (read: rune textures) don't show up (just a black rectangle would show up), and the Dimensional Puzzle Locks and Keys' doors would just be black where color would be (except for Kuro, which _is_ black anyway). Would you mind shifting the relevant textures' animation to where their brightest frame is first?

**Comment by ReikaKalseki** [comment]
The first issue is #1921.

As for the second, I remember someone reporting that a long time ago; it was either a mod interaction (a mod calling invalid code or code with invalid parameters) or world corruption (triggering basically the same).

As for the texture issue, that sounds like the sort of thing best implemented in a texture pack; all you would need is a new mcmeta file with custom frame ordering.
