### ISSUE TITLE
Chromaticraft world rifts don't transport shaft power out of a shaft junction

### ISSUE THREAD

**Issue by dwenograd** [ReikaKalseki/Reika_Mods_Issues#2]
When working with world rifts the first time, noticed that they won't transport power straight out of a shaft junction, it needs to go through something else first.

**Comment by ReikaKalseki** [comment]
I will investigate this.

**Comment by 1Matthias** [comment]
What version, and could you post a picture of your setup?

**Comment by dwenograd** [comment]
https://www.dropbox.com/s/bt7y0umstutrd7r/broken.png?dl=0

This is an example of where it wouldn't work for me.

https://www.dropbox.com/s/k6ntlbxj6ifirvg/working.png?dl=0

And this is the way I fixed it in my world currently.

Mod versions:

DragonAPI 1.7.10 V6f
ElectriCraft 1.7.10 V6a
RotaryCraft 1.7.10 V6f
ReactorCraft 1.7.10 V6e
ChromatiCraft 1.7.10 V6f
GeoStrata 1.7.10 V6a

**Comment by ReikaKalseki** [comment]
I have confirmed the bug exists and I am working on it.

**Comment by madolinn** [comment]
This does not only happen with the World Rift. I reported a similar issue back in v6c, here's some screenshot of the same issue with belt hubs.
![Working Side](https://cloud.githubusercontent.com/assets/10469156/7221629/b919f262-e6bf-11e4-89de-d80ee883e208.png)
![Broken Side](https://cloud.githubusercontent.com/assets/10469156/7221632/c4920a44-e6bf-11e4-8c7c-10c69b1b806d.png)
![Fixed Broken Side](https://cloud.githubusercontent.com/assets/10469156/7221635/e654e7aa-e6bf-11e4-96c0-cc9c44964777.png)

**Comment by ReikaKalseki** [comment]
That looks like a different issue, that shaft junctions cannot read from belt hubs.

That said, the shaft junction issue is fixed.

**Comment by ReikaKalseki** [comment]
Also, the shaft junctions are reading the belt hub fine.

**Comment by madolinn** [comment]
On one side they read fine, on the other side they don't read.

**Comment by ReikaKalseki** [comment]
http://i.imgur.com/V9sUfS2.png

**Comment by madolinn** [comment]
Yes, now put another connection where your lever is.

**Comment by ReikaKalseki** [comment]
OK, this is confirmed.

**Comment by ReikaKalseki** [comment]
Fixed.
![](http://i.imgur.com/Po1xat2.png)
