### ISSUE TITLE
Bright Lamp hides Display Screen Hologram.

### ISSUE THREAD

**Issue by madolinn** [ReikaKalseki/Reika_Mods_Issues#20]
[Previously](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/5) this issue was posted and resolved thought to be caused by GC, but it also fails when near Bright Lamps from RoC.

![I dun broke it Reika](https://cloud.githubusercontent.com/assets/10469156/7243212/880b7018-e798-11e4-8a2a-19af9af6fb3c.png)
Bright Lamp on.
![One day](https://cloud.githubusercontent.com/assets/10469156/7243218/9f59a032-e798-11e4-8d2c-6b3f05a9f6d8.png)
Bright Lamp off.

One of these days I'll stop breaking your mods :(

**Comment by ReikaKalseki** [comment]
Understandable, but will be fixed in next version.
