### ISSUE TITLE
Fueling the BCenergy Powered Engine lack of information

### ISSUE THREAD

**Issue by egeis** [ReikaKalseki/Reika_Mods_Issues#200]
I spent the last half hour trying to fuel the BCEnergy Engine Only water and lubricant are accepted in the sides of the engine. I was about for look for a mod that inserted liquids using buckets, similar to Red Power 2 transposer.  Only on a whim did I try the bottom of the machine...

Fuel must be inserted from the bottom, not sure if this is intended or a bug, could you add this information to the handbook?

**Comment by ReikaKalseki** [comment]
All engines behave the same way, and it is expected that you would have tried this.
