### ISSUE TITLE
[ChC] Bonemeal-from-dispenser does not work on dye saplings

### ISSUE THREAD

**Issue by kutschkem** [ReikaKalseki/Reika_Mods_Issues#2000]
I am trying to build a (tahara) tree farm out of 1 Item Inserter (to apply bonemeal), 1 Thaumcraft Golem with a Use core (for planting), and 1 Golem with a Chop core (for felling).

Whenever the tree gets felled and replanted, the item inserter stops applying the bonemeal. When I remove the bonemeal and insert it again, or toggle the "+" which controls which item gets applied to which block, it starts applying again. I also tried applying a red stone signal, suspecting that somehow block updates had something to do with the problem, but applying a redstone signal did not cause the item inserter to reconsider whether he could apply the bonemeal.

I had a dynamism tablet before for applying the bonemeal, but it had similar problems. FYI if that helps with debugging.

**Comment by kutschkem** [comment]
I looked at the code, the issue here is pretty obvious: When the block is air, it gets removed from the routing cache, and rebuilding the cache only happens when I change the configuration (by removing/adding items and triggering the connections). 

That means in the case of a tree farm, which will have an air block between when the tree is felled and the sapling replanted, that the block will be removed from the routing cache once the tree is felled.

**Comment by kutschkem** [comment]
A not so obvious issue is that all the other automated means of applying bonemeal don't seem to work - for example a vanilla dispenser with bonemeal. For the dispenser, the bonemeal is used up, but the tree does not grow.

**Comment by ReikaKalseki** [comment]
This is not really what the item inserter is *for*; it is not a generic right-clicking machine, and handling cases of its right-click block being removed opens up a number of potential issues.

As for dispensers and bonemeal - is that in fact vanilla behavior?

**Comment by kutschkem** [comment]
I looked it up, and yes Dispensers can use bonemeal since 1.5

**Comment by ReikaKalseki** [comment]
I will look into making that work, then.

**Comment by kutschkem** [comment]
:+1:

**Comment by kutschkem** [comment]
OK i tried it again in a test world with just your plugins, and the dispenser bonemeal worked without problems.

Plugins tested:
DragonAPI v21c
Chromaticraft v21b
Rotarycraft v21b
Electricraft v21b

I guess there is some other problem with my original setup, maybe a corrupted chunk, something biome specific (original setup was in a mushroom biome) or some mod interaction. I think we can close this for now.
