### ISSUE TITLE
Infinite CO2 with Extra Cells 2 ME Fluid Import Bus

### ISSUE THREAD

**Issue by Azzezima** [ReikaKalseki/Reika_Mods_Issues#2002]
When i extract cold CO2 from the heat exchanger with an ME Fluid Import Bus; it imports the gas into the network but doesn't actually subtract it from the heat exchanger fluid inventory.
So this basically gives me infinite cold CO2 and i can't empty the heat exchanger without using something else than the import bus.

**Comment by ReikaKalseki** [comment]
This was brought up a year or two ago; there is a bug in ExtraCells and affects far more fluid tanks than just mine.

https://github.com/ExtraCells/ExtraCells2/issues/344
