### ISSUE TITLE
Reactorcraft Fusion Reactor (Plasma spilling everywhere)

### ISSUE THREAD

**Issue by rhys19** [ReikaKalseki/Reika_Mods_Issues#2005]
i know there have been some issues about this but i tried ever single solution i could think of but it still won't work

![image](https://user-images.githubusercontent.com/30848481/49324569-fb97e200-f4f5-11e8-9565-9e2ccff12e6e.png)
that's what i get with the plasma.

things i checked:
Checked Positions of Toroid Magnets
Checked if they had enough power (Well over around 20,00 kV)
Image for power: 
![image](https://user-images.githubusercontent.com/30848481/49324582-31d56180-f4f6-11e8-9817-8d5c2a687ee9.png)

Checked Solenoid position
Checked Solenoid power
Made sure Solenoid speed was at 512 RAD/S
everything above i tried but still nothing ;(

**Comment by rhys19** [comment]
not really worried about the prettiness of it. i just want to get it working so i can pretty it up after ;)

**Comment by rhys19** [comment]
and i tried moving the Toroid magnets around a bit to see if it would fix it but still nothing

**Comment by ReikaKalseki** [comment]
Plasma moves anticlockwise.

**Comment by rhys19** [comment]
so should i move the plasma injector piece in the plasma injectors? to the other side

**Comment by ReikaKalseki** [comment]
No, rotate them all 180 degrees.

**Comment by rhys19** [comment]
ok i will try that

**Comment by rhys19** [comment]
hmm interesting my magnetic pipes randomly turned to water one of the Van de Graaf must've turned off holdon i'll try it in a sec let me fix this issue first

**Comment by rhys19** [comment]
rotated em 180 and still 
![image](https://user-images.githubusercontent.com/30848481/49332492-40159300-f573-11e8-9921-7ebe314a502f.png)

**Comment by rhys19** [comment]
although for some reason all of them won't get a charge until i rotate them a bit to the other side for the charge to reach

**Comment by rhys19** [comment]
or do i need to rotate the plasma injector?

**Comment by rhys19** [comment]
Any idea? i'd like to build it on my survival world but i want to know how to build it first and how to make it work ;)

**Comment by rhys19** [comment]
i even tried debug mode but it still won't i've built the thing about 6 times and one in a different world but still the same issue

**Comment by rhys19** [comment]
i'm relaunching my game with NBT enabled in config to check if all of them are placed correctly

**Comment by rhys19** [comment]
i created a new world just put in the Toroids magnets in place of the frame from the Tokamak Blueprint Highlighter so i know they are in correct placement and i made sure the arrow was facing the middle ;) so i'll report back what it does after i get the solenoid and the injectors setup ;)

**Comment by rhys19** [comment]
interesting on new world the debug mode says 0B ? even though everything is correct

**Comment by rhys19** [comment]
![image](https://user-images.githubusercontent.com/30848481/49334247-d9a26c00-f596-11e8-9ced-749ce401b00b.png)

**Comment by zemerick** [comment]
Ignore debug mode, go back to the original one. ( Note in that last pick that no, you did not build it right. At least 1 toroid is misaligned, and you have multiple gaps. )

With the nbt data on, check your toroids again and report back. Solenoid and hasNext should be 1b on all of the toroids.

**Comment by rhys19** [comment]
so is there anything wrong with this one? 
![image](https://user-images.githubusercontent.com/30848481/49335380-fbf5b300-f5b1-11e8-9c12-1f14ae8887df.png)

**Comment by zemerick** [comment]
Yes, your plasma is going the wrong way.

**Comment by rhys19** [comment]
okay which way do i need it to go? like what do i need to do

**Comment by zemerick** [comment]
There's only 2 options...so if clockwise is wrong, anti-clockwise is correct, just like reika said.

**Comment by rhys19** [comment]
so i placed one of the plasma injecters the other way but it still won't go through the toriod magnets it's like it ignores it.

**Comment by zemerick** [comment]
They ALL have to be facing the correct direction. The loop must be entirely complete.

Once you have things set correctly, you might need to spin some toroids to get them to update.

**Comment by rhys19** [comment]
![unknown](https://user-images.githubusercontent.com/30848481/49335542-8dfebb00-f5b4-11e8-8737-39f66d1aa72e.png)
is that counter clock wise? or would the other way be?

**Comment by zemerick** [comment]
Yes, that is CCW...the opposite of the way a clock goes.

**Comment by rhys19** [comment]
ok so now what? why isn't it working?

**Comment by zemerick** [comment]
Like I said, check solenoid and next on the toroids.

**Comment by rhys19** [comment]
do i have to re do the multiblock on the solenoid

**Comment by rhys19** [comment]
ok

**Comment by zemerick** [comment]
No, you can see the graphics updated, so it is built correct.

**Comment by rhys19** [comment]
![image](https://user-images.githubusercontent.com/30848481/49335564-239a4a80-f5b5-11e8-8a46-f45ff75b2e17.png)
so is the solenoid correct? what am i checking?

**Comment by zemerick** [comment]
You're giving it significantly more torque than it needs, but it seems fine.

Looking at the previous image, with the arrow, you have multiple toroids that are not lined up correctly.

**Comment by rhys19** [comment]
okay should i be lining them using the tokamak blueprint marker? because that's what i used to set it up but i tried to twist them a couple times

**Comment by zemerick** [comment]
the BP marker will work, but you definitely missed it. Especially one on the right side that looks to be about 3 clicks out.

The easy way though is each 1 is just 1 click more than the previous. The ones on each side of the injectors will be straight.

**Comment by rhys19** [comment]
ok let me try that and i'll come back after

**Comment by rhys19** [comment]
ok that's the BP marker it seems right from my side 
![image](https://user-images.githubusercontent.com/30848481/49335617-5b55c200-f5b6-11e8-8de6-7e1a036babcf.png)

**Comment by zemerick** [comment]
You can't see the toroid lines from there, but you can very clearly see 1 in the top right is not even close. There are a couple others that look to be 1 click out, but that's harder to tell. Just recheck them all.

**Comment by rhys19** [comment]
ok

**Comment by rhys19** [comment]
they all look right for now. 
![image](https://user-images.githubusercontent.com/30848481/49335690-16cb2600-f5b8-11e8-8aaf-34cc963e150a.png) i checked them all btw

**Comment by zemerick** [comment]
So rebuild the solenoid and check it...

**Comment by rhys19** [comment]
ok

**Comment by rhys19** [comment]
mhm nope 
![image](https://user-images.githubusercontent.com/30848481/49335710-66a9ed00-f5b8-11e8-9a0f-dae171f6c751.png)
even tried debug mode.

**Comment by zemerick** [comment]
Check the toroids for what is wrong

**Comment by rhys19** [comment]
only one toriod says 1B

**Comment by rhys19** [comment]
![image](https://user-images.githubusercontent.com/30848481/49335725-ac66b580-f5b8-11e8-96ee-6d9461df87a8.png)

**Comment by zemerick** [comment]
Start spinning toroids. If even a single toroid gets to 1b, you have the entire ring correctly aligned.

Obviously when spinning, make sure you get back to exactly where you started since it is right now:)

**Comment by rhys19** [comment]
ok it should auto update ?

**Comment by zemerick** [comment]
There are a number of ways everything updates...but the quickest, easiest, and most reliable is to spin a toroid. Each time they turn, they do an update, so this is a great way to manually force to immediately update. Start with the next one in line from the 1 that is working.

**Comment by rhys19** [comment]
ok

**Comment by rhys19** [comment]
welp i think i might've corrupted that world because it crashed me when i tried to relogin to the world but it crashed when i tried logging into the world so i'll try to build one on my server. see how much success i get out of it. probably 0 but who knows

**Comment by rhys19** [comment]
oh wait nvm i didn't corrupt it holdon

**Comment by rhys19** [comment]
WAIT ALL THE TOROIDS ARE 1B WTF i relogged into my world and they showed as 1b

**Comment by rhys19** [comment]
but the plasma isn't going in the circle still

**Comment by rhys19** [comment]
see there all 1B 
![image](https://user-images.githubusercontent.com/30848481/49335804-9f4ac600-f5ba-11e8-98eb-7d6c2a6eaaa3.png)

**Comment by rhys19** [comment]
but solenoid says 0b and the plasma won't go counter clock wise

**Comment by zemerick** [comment]
Somethings wrong with the solenoid, check its power and such.

**Comment by rhys19** [comment]
![image](https://user-images.githubusercontent.com/30848481/49335807-bf7a8500-f5ba-11e8-94f0-da9041e94f72.png)

**Comment by zemerick** [comment]
Just noticed in an image back a ways, it looks like your solenoid is 1 block too low.

**Comment by rhys19** [comment]
ohh

**Comment by rhys19** [comment]
holdon let me try to rebuild it one more high then

**Comment by rhys19** [comment]
Turning it off so it doesn't blow up xD

**Comment by zemerick** [comment]
For future reference, it only needs 32768nm and 256 rad/s. Giving it too much power is fine, but once you get to building it in survival that will save you a lot:)

**Comment by rhys19** [comment]
ok thanks let me make sure it works before we close the issue

**Comment by rhys19** [comment]
THANK YOU SOOO MUCH 
![image](https://user-images.githubusercontent.com/30848481/49335899-af63a500-f5bc-11e8-9ca9-27d1b600602b.png)

**Comment by zemerick** [comment]
np. GL.

Now remember though, in the future assume that you are doing something wrong, until you know otherwise. Ask questions in the forums, or such, not here. This is for actual bugs.

**Comment by rhys19** [comment]
quick question? is there a way to stop the reaction?

**Comment by zemerick** [comment]
Turn off the injectors. To release the plasma, choose a safe direction and disable the 1 toroid that faces that way. The plasma will then shoot out at that location. ( Plasma will ignite/kill anything it touches, and flies for approx. 100 blocks. )

This will be my last answer. Any further questions please take to the forums where they belong.
