### ISSUE TITLE
Electricraft handbook doesn't mentions input power limit of induction generator

### ISSUE THREAD

**Issue by MatthiasMann** [ReikaKalseki/Reika_Mods_Issues#2006]
Using ElectriCraft+1.7.10+V21b the change log says "ElectriCraft: Induction Generators can no longer safely accept turbine-level power" but the actual limit is nowhere listed in the manual.

Reading through the source code it is still 800MW in v21b but has already been changed to only 400MW (likely included in the next release).

This should be mentioned in the handbook.

**Comment by ReikaKalseki** [comment]
I would rather not mention the specific limit, as that will just encourage people to split it a few times first.

**Comment by MatthiasMann** [comment]
That doesn't make any sense - the wire limits are in the manual as are the shaft/gearbox limits.

**Comment by ReikaKalseki** [comment]
The limits on those are not to force some (much more expensive and involved) alternate method to convert/transport the power. Knowing their exact values and working around them is not like people trying to find ways to avoid building a proper generator.

**Comment by MatthiasMann** [comment]
So - with proper generator you mean the big multi block RF generator thingy? and then run the whole base using a trivial RF distribution system (eg tesseracts & co)?

**Comment by voidsong-dragonfly** [comment]
The Turbine Generator has modes. It can be switched between EU, RF, and ElectriCraft W. Use the Screwdriver to right-click the Turbine Generator Block. Once you have clicked it enough (twice?) you should have it output ElectriCraft W.

**Comment by MatthiasMann** [comment]
Ohh - that is something I didn't knew - and is NOT mentioned in the hand book either.

If you would add this information into the hand book then you could rightfully claim that people asking about such things didn't read your hand book.

**Comment by ReikaKalseki** [comment]
I added a mention that there is a limit.

And the mode switching.
