### ISSUE TITLE
(Reactorcraft) my solenoid magnet refuses to spin

### ISSUE THREAD

**Issue by KP2048** [ReikaKalseki/Reika_Mods_Issues#2008]
I built A fusion reactor, but when I power the solenoid magnet, it does not spin.
this is my reactor
![2018-12-04_17 30 04](https://user-images.githubusercontent.com/39203202/49484051-70b33200-f7ea-11e8-9ba6-ce98b33c7b74.png)
![2018-12-04_17 30 25](https://user-images.githubusercontent.com/39203202/49484057-7577e600-f7ea-11e8-9fad-542064141ccc.png)

**Comment by KP2048** [comment]
![2018-12-04_17 34 54](https://user-images.githubusercontent.com/39203202/49484166-eb7c4d00-f7ea-11e8-9a51-f4d4148cfc12.png)

**Comment by Rewyn** [comment]
Don't have the actual data, but according to what was mentioned in a closed issue it'd need far mor torque?
"needs 32768nm and 256 rad/s."

**Comment by KP2048** [comment]
then the tooltip is wrong

**Comment by zemerick** [comment]
I checked with a bit older version that I have, and it's fine. ( It'd take some work to get it updated ) I see nothing that has changed, and the current commit looks fine. Can you double check that the tooltip is wrong, and if so post a screenshot and verify your version please.
