### ISSUE TITLE
Blast furnace 'leave one item' doesn't work

### ISSUE THREAD

**Issue by MatthiasMann** [ReikaKalseki/Reika_Mods_Issues#2009]
Independent of how the UI switch is set the blast furnace always consumes all items it has.

Looking at the code it seems the packet handler is not reading the payload data of the packet 'BLASTLEAVEONE' inside the first switch https://github.com/ReikaKalseki/RotaryCraft/blob/bc7b97f46faeb6185175448287ecf71cf65d359b/PacketHandlerCore.java#L111

Tested in single player with version RotaryCraft+1.7.10+V21b

**Comment by ReikaKalseki** [comment]
[Yes it is](https://github.com/ReikaKalseki/RotaryCraft/blob/bc7b97f46faeb6185175448287ecf71cf65d359b/PacketHandlerCore.java#L611).

**Comment by MatthiasMann** [comment]
Ok, I read your 2 switch statements wrong (I thought they used the same variable) - but the feature isn't working in single player.

**Comment by ReikaKalseki** [comment]
I believe you on that, but the cause is elsewhere.

**Comment by Ieldra2** [comment]
It works perfectly fine in my single-player game, so it's probably some mod interaction.

**Comment by MatthiasMann** [comment]
Or it depends on the recipe - I was making TRISO fuel.
I also tried locked the 4 corner slots using the middle mouse button - but that didn't seem to affect anything.

I'm using the Ascendant Technical-3.1.4 mod pack.

**Comment by ReikaKalseki** [comment]
The Blast Furnace has two "kinds" of recipes; TRISO is one of them. Try a recipe like HSLA.

**Comment by habnabit** [comment]
Encountered the same bug but haven't traced it down yet. TRISO fuel eats all the inputs regardless of setting; HSLA steel will respect the setting. Putting a crafting pattern for TRISO fuel into the blast furnace was at least enough of a fix for automation purposes.

**Comment by ReikaKalseki** [comment]
Fixed.
