### ISSUE TITLE
Crashing when using Pylon Crafting at crafting temple

### ISSUE THREAD

**Issue by Reignofmagic** [ReikaKalseki/Reika_Mods_Issues#201]
Sorry to bother you with this, I saw on the forums that this was fixed way back in V3, but I seem to have found it again. 

I am getting a few different crashes when I am trying to make the item fabricator with my finally completed pylon network. The network is rather standard, normal repeaters till the last few jumps to the temple due to me being smart and making it high on a mountain. 

Here is the first: http://pastebin.com/MjULYvdW
Here is the second: http://pastebin.com/y0yQeLDq

Prior to the third attempt I tried something different. I popped down a crystal storage thing and it filled up nice and fine, I then started the temple making the item fabricator, it also worked just fine due to all the pylons being drained. One color wasn't fully drained so that one filled up most of the way (I think it was kuro), but as soon as the blue and brown started to pulse into the table the game crashed again with this crash log. 

Here is the third: http://pastebin.com/bmypvpt1

On the fourth restart I gave myself the item fabricator just to test if it would crash me as well. It works just fine by itself, It can absorb all colors at once no problem.

4th crashlog (seems similar to 2 and 3): http://pastebin.com/MeFtVhZ5

The only rather annoying thing is my crystal network isn't saving itself between crashes/logging out. A few of my lines need to have most of their length flown across in order to get the line working again. Note I don't actually do anything to the line other than fly around. It just starts working after some point. 

As an aside to potentially fix the repeater network issues I went ham with a scythe and killed all grass, and botania flowers in between each repeater. 

EDIT:
I successfully made a world rift, then tried making an item fabricator. World rift worked just fine, item fabricator crashed me promptly.

Edit 2: It looks like it is just the item fabricator for some reason. I have done a few other pylon necessary crafting and all of them have worked fine.

**Comment by ReikaKalseki** [comment]
I put some try-catch in to stop the crashes, but this error really should not be happening.
