### ISSUE TITLE
Crash while applying dye to a resistor

### ISSUE THREAD

**Issue by MatthiasMann** [ReikaKalseki/Reika_Mods_Issues#2010]
I was applying minecraft orange dye to the middle band of a EIC resistor when I got this crash. I had applied other dye colors (lapis, red, yellow, cocoa) before without issues.

[crash-2018-12-07_00.29.32-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2655322/crash-2018-12-07_00.29.32-client.txt)

Could be related to #1921 - but that was marked as fixed.

PS: Could be that I right clicked twice and as such had an empty hand - hard to say as the game closed really quick.

**Comment by ReikaKalseki** [comment]
Fixed != released.
