### ISSUE TITLE
Feature request: exempt CC ball lightnings from being targeted by rune-enhanced lumen turrets

### ISSUE THREAD

**Issue by Ieldra2** [ReikaKalseki/Reika_Mods_Issues#2011]
...or else make them vulnerable to them so they're gone fast. The problem: ball lightnings appear to be invulnerable to lumen turrets enhanced to target non-hostile mobs, which results in them being constantly shot at when present, if you build your base in rainbow forests. As opposed to some other supposedly non-hostile mobs, particularly TC wisps which annoy by their lightning, or cows or sheep which annoy by their noise, the ball lightnings are perfectly non-annoying, so they'd be fine to remain if you insist on keeping them invulnerable as far as I'm concerned. In any case, the point is preventing the turrets from targeting mobs against which they're completely useless, resulting in a constant barrage all across your base if you settle in rainbow forests.

**Comment by ReikaKalseki** [comment]
I am not sure how I feel about this.

**Comment by ReikaKalseki** [comment]
Done.

**Comment by Ieldra2** [comment]
Thank you!
