### ISSUE TITLE
Ticking Entity NPE crash in DragonAPI's TinkerSmelteryHandler

### ISSUE THREAD

**Issue by Ieldra2** [ReikaKalseki/Reika_Mods_Issues#2016]
Crash report at https://pastebin.com/XeFEifDJ

"java.lang.NullPointerException: Ticking block entity
    at Reika.DragonAPI.ModInteract.DeepInteract.TinkerSmelteryHandler.isSmelteryController(TinkerSmelteryHandler.java:77)
    at Reika.ChromatiCraft.Block.BlockHeatLamp$TileEntityHeatLamp.func_145845_h(BlockHeatLamp.java:163)"

This seems to be related to one of the new features in V22. I do have a few heat lamps, but a few blocks away from the smeltery. The crash can be triggered reliably by moving far enough away from my base, and it does not go away if I dismantle my smeltery. If I remove all heat lamps, I get no crash, but an almost identical NPE message on the chat under the same conditions, except that it involves a friction heater rather than a heat lamp. This is present in both V22a and V22b.

**Comment by thePalindrome** [comment]
Adding on with my report: https://paste.ee/p/7g49Z (EDIT: New link, MultiMC uploaded the entirely wrong log)

Do note, Tinker's Construct is not even installed in this pack (as you can see in the bottom)

Also V22B (Not sure if you've changed something, since there's no 22b changelog)

**Comment by Ieldra2** [comment]
thePalindrome, your linked crash report does not look as if it has anything to do with this issue. Did you use the correct link?

**Comment by ReikaKalseki** [comment]
His report is indeed entirely unrelated, and due to installation errors.

**Comment by thePalindrome** [comment]
Fixed, thanks!

**Comment by ReikaKalseki** [comment]
Yes, that is the same error as the main post.

**Comment by thePalindrome** [comment]
Yes, I wanted to provide a second log to give additional context. My apologies if the extra log doesn't help.

**Comment by ReikaKalseki** [comment]
Fixed.
