### ISSUE TITLE
Ticking Entity NPE With Whitelist-mode Void Monster

### ISSUE THREAD

**Issue by Justfines** [ReikaKalseki/Reika_Mods_Issues#2017]
This is with Void Monster v22a, and DragonAPI v22b
Upon entering or loading a Dimension in which the Void Monster is not Whitelisted to, the server/client crashes with Ticking Entity NPE. This was tested in both an instance that had only VoidMonster+DragonAPI with the Overworld removed from the dimension list, and an instance that had Aroma's dimensional world with the mining world's Dimension excluded from the list.

Pastebin of Standalone crash: https://pastebin.com/L4i9qmKA
Pastebin of Mining world crash: https://pastebin.com/w9XNYnAP

**Comment by ReikaKalseki** [comment]
Fixed.
