### ISSUE TITLE
Fan only havests in 1x1

### ISSUE THREAD

**Issue by BaronMalkar** [ReikaKalseki/Reika_Mods_Issues#2018]
In V22b the fan only harvests crops directly in front of it even with the Diffuser upgrade. It seems to push entities in the expected wider area with the Diffuser and the angular transducer shows the larger area in blue, just no expansion of the crop harvest area beyond the 1x1 area directly in front of the fan.

**Comment by ReikaKalseki** [comment]
There was a typo - it was supplying X coordinate values as the Z.
