### ISSUE TITLE
Client Crash when mining a steam engine with a heat lamp attached

### ISSUE THREAD

**Issue by AshIndigo** [ReikaKalseki/Reika_Mods_Issues#2020]
Steps to reproduce
1. Start up a steam engine with a heat lamp as the source of heat
2. Mine the steam engine
3. The game should crash then.

Crash Log: https://pastebin.com/8UtULmTC

Mod version: V22

**Comment by ReikaKalseki** [comment]
Related to #2016?

**Comment by ReikaKalseki** [comment]
Yes, it is.
