### ISSUE TITLE
[Reactorcraft] "reactorcraft_item_placer" does not drop when broken with a Tinkers' Construct hammer

### ISSUE THREAD

**Issue by ReactivePlatypus** [ReikaKalseki/Reika_Mods_Issues#2027]
Most tile entities (exceptions listed below) that are variations of "reactorcraft_item_placer" are not dropping themselves when broken with a hammer from Tinkers' Construct. This seemingly only applies to the Tinkers' Hammer AoE - breaking them with with Immersive Engineering's mining drill and Botania's Terra Shatterer AoE mining abilities causes them to drop normally. If the broken TE has an inventory that contains items, those items will still drop regardless.

Weirdly, this does _not_ seem to apply to pipes. Steam Lines, Heat Pipes, Gas Ducts, Magnetic Containment Pipes, and Nuclear Waste Ducts DO still drop themselves as expected when broken with hammers, so they are exceptions. Reactorcraft TEs that are not variations of reactorcraft_item_placer (e.g. tritium lamps) also drop normally when broken with hammers.

This was tested using both a manyullyn hammer and a bedrock hammer from Rotarycraft's TiCon integration, so insufficient mining level doesn't seem to be the problem.

**Comment by voidsong-dragonfly** [comment]
Reika had said it is some sort of mod interaction due to how TiC does its breaking in the AoE. He is not inclined to fix it, however, as smashing your macchines with a hammer is unlikely to keep them intact.

**Comment by ReactivePlatypus** [comment]
I thought I was thorough in my search of closed issues, but apparently not. Even so, if it's not up for fixing, that might be worth a note in the Reactorcraft book just in case someone still thinking with minecraft logic (i.e. me) comes along and decides that whacking a reactor core with a giant sledgehammer _is_ a good idea.

**Comment by ReikaKalseki** [comment]
This is intentional. Smashing machines with hammers is not going to be useful.
