### ISSUE TITLE
[Chromaticraft] Inverted Holiday Pylon render now in Chromic Lexicon's "Ball Lightning" icon

### ISSUE THREAD

**Issue by ReactivePlatypus** [ReikaKalseki/Reika_Mods_Issues#2028]
![2018-12-25_00 19 31](https://user-images.githubusercontent.com/22828039/50417358-c58b0c80-07da-11e9-9cf7-38ff651bbaff.png)

I assume this is related to when the earlier pylon holiday texture issue was fixed, because the "Pylons" entry icon and in-world all in-world renders seem fine now.

Still funny though.

**Comment by voidsong-dragonfly** [comment]
Ball lightnings look like that as well, I thought.
