### ISSUE TITLE
Concrete blocks allow sunlight to pass through.

### ISSUE THREAD

**Issue by CorneliaXaos** [ReikaKalseki/Reika_Mods_Issues#2031]
I dunno if this is a bug, but I noticed that my buildings built mainly out of concrete allow sunlight to pass through (rasing the light level inside a building to 15 during the day). This isn't really a problem, but it's a bit annoying to deal with fluctuating light levels. Are concrete blocks supposed to do this?

**Comment by ReikaKalseki** [comment]
Fixed.
