### ISSUE TITLE
Suggestion: search and/or sort in the Casting Delegate GUI

### ISSUE THREAD

**Issue by Ieldra2** [ReikaKalseki/Reika_Mods_Issues#2033]
Finding a specific item in this GUI if you don't have a sample at hand is rather tedious. A name search would be very good, but a name sort would also be helpful.

**Comment by Kataiser9** [comment]
I'd agree, if not for the feature from a few versions back wherein you can choose Casting Delegate recipes from the book's recipe page. When you can just search an item in JEI and click twice, a search/sort would be kinda superfluous.

**Comment by Ieldra2** [comment]
:/ Must've overlooked this. I certainly would've remembered it, given how much of a bother this was. Eh, and I might've tried to find out what that Casting Delegate icon does. All right, superfluous it is then.

**Comment by ReikaKalseki** [comment]
The list is already sorted by the lexicon ordering.
