### ISSUE TITLE
Lumen Radiation Pedestal constantly draws from the network

### ISSUE THREAD

**Issue by Ieldra2** [ReikaKalseki/Reika_Mods_Issues#2034]
I.e. it connects with the network every second or two for an instant, even if no lumen-consuming blocks are in range, and it appears it connects to all pylons. This does not happen with an Ambient Lumen Distributor which is not on a Pedestal, even with lumen consumers in range.

**Comment by ReikaKalseki** [comment]
Having looked at the code, it looks like it is powering other distributors; there is no ambient energy cost.
