### ISSUE TITLE
AE2 opal cable façades are always white

### ISSUE THREAD

**Issue by InitHello** [ReikaKalseki/Reika_Mods_Issues#2038]
Is that something GeoStrata can even touch? I fear not, so feel free to close this if I'm right. It would be a shame, because opal is easily my favorite construction material, and I'm pretty sure AE2 for 1.7.10 is no longer actively maintained.

**Comment by ReikaKalseki** [comment]
This is indeed a bug on their end, and cannot be fixed from mine.
