### ISSUE TITLE
Right Clicking a structural bypass block after the puzzle is completed causes an internal server error

### ISSUE THREAD

**Issue by AshIndigo** [ReikaKalseki/Reika_Mods_Issues#2039]
Steps:
1. Go complete a puzzle in Proxima that has a structural bypass block (I did it with channeled flows but that shouldn't matter)
2. Go back to the entrance and attempt to use the block (Mine had nothing in it when I tried)
3. If your on a server you should get an internal server and get booted off.

Stack Trace: https://pastebin.com/8cSNbJQQ

**Comment by ReikaKalseki** [comment]
Fixed, as referenced in #2127
