### ISSUE TITLE
Chromatic Craft. Exception getting block type in world. Dungeon Generator. GregTech?

### ISSUE THREAD

**Issue by RoloEdits** [ReikaKalseki/Reika_Mods_Issues#204]
After installing gregtech 5 unofficial I'm getting this crash when making a new world.
http://pastebin.com/J0p7AisH

**Comment by ReikaKalseki** [comment]
This does not happen without GT (and my personal experience can attest to this). Also, the error falls under the "should not be possible" category. He must be modifying worldgen in an incompatible way.
