### ISSUE TITLE
Redstone Flux Radiator

### ISSUE THREAD

**Issue by InitHello** [ReikaKalseki/Reika_Mods_Issues#2040]
Sorry to submit so many issues, I've been getting back into minecraft lately, and your mods are among my must-haves.

I'd like to suggest that the redstone flux radiator is perhaps a bit powerful for its tier.

With just one RFR I can power a vast number of machines, where it would take me dozens of vibrant alloys for conduits, or diamonds for kinesis pipes. I'm not sure how to balance it, but 36 redstone, 4 iron, and a block of glowstone feels remarkably cheap for what it does.

**Comment by ReikaKalseki** [comment]
A) This is not the place for not-bugs.
B) Many people would vehemently disagree with you, as CC requires a great deal of investment, even for its early game.
C) Balancing around costs of conduits, especially when there are like 30 variants, is ridiculous.
