### ISSUE TITLE
[Chromaticraft][Casting Table][Likely User Error][Likely Duplicate] Casting fails beyond the basic crafting

### ISSUE THREAD

**Issue by Garr890354839** [ReikaKalseki/Reika_Mods_Issues#2043]
Alright. I tried everything. I cannot for the life of me craft anything beyond basic crafting. Attached are some screenshots of me trying various recipes, ranging from crystalline stone to the Avolite Defence Beam. I play singleplayer, and is it possible that I am missing something? Or the fact that I am touching on an already-talked-about closed issue? (If you are wondering, yes. I followed the Up=North system like you mentioned in Casting II)

Avolite Defence Beam

![2018-12-29_16 15 43](https://user-images.githubusercontent.com/10093603/50568755-f01e1d80-0d24-11e9-90ec-192316b591db.png)
![2018-12-29_16 15 57](https://user-images.githubusercontent.com/10093603/50568756-f01e1d80-0d24-11e9-97bb-787fdb620c63.png)
![2018-12-29_16 16 06](https://user-images.githubusercontent.com/10093603/50568757-f01e1d80-0d24-11e9-968c-3115ecb070f8.png)
![2018-12-31_16 31 25](https://user-images.githubusercontent.com/10093603/50568758-f01e1d80-0d24-11e9-8dc6-c4e3f760c9de.png)

Heat Lily

![2018-12-31_17 40 18](https://user-images.githubusercontent.com/10093603/50568759-f01e1d80-0d24-11e9-96c9-4a3d4fbae134.png)
![2018-12-31_17 40 24](https://user-images.githubusercontent.com/10093603/50568760-f0b6b400-0d24-11e9-8cd9-689ec6f94c20.png)
![2018-12-31_17 40 28](https://user-images.githubusercontent.com/10093603/50568761-f0b6b400-0d24-11e9-9758-7633b3d35f32.png)

Crystalline Stone (Works)

![2018-12-31_17 41 07](https://user-images.githubusercontent.com/10093603/50568762-f2807780-0d24-11e9-8061-078e2f00af02.png)
![2018-12-31_18 09 19](https://user-images.githubusercontent.com/10093603/50568888-3a080300-0d27-11e9-8cdb-58579c016e55.png)

Kuro Potion Crystal

![2018-12-31_17 41 20](https://user-images.githubusercontent.com/10093603/50568763-f2807780-0d24-11e9-876a-1deaaea3771e.png)
![2018-12-31_17 41 29](https://user-images.githubusercontent.com/10093603/50568764-f3190e00-0d24-11e9-9111-fe0ad6d38682.png)
![2018-12-31_17 41 35](https://user-images.githubusercontent.com/10093603/50568765-f3190e00-0d24-11e9-9a8f-e021bb116779.png)

Storage Crystal Charger

![2018-12-31_17 41 48](https://user-images.githubusercontent.com/10093603/50568766-f44a3b00-0d24-11e9-8a4c-5138d7219087.png)
![2018-12-31_17 47 55](https://user-images.githubusercontent.com/10093603/50568767-f44a3b00-0d24-11e9-819a-dcae87c21516.png)
![2018-12-31_17 48 08](https://user-images.githubusercontent.com/10093603/50568768-f44a3b00-0d24-11e9-944b-e0c25234b745.png)

**Comment by Barhandar** [comment]
You have neither valid structure nor table of high enough level to do these recipes. Do not break the table and craft lower-level items first.

**Comment by Garr890354839** [comment]
> You have neither valid structure nor table of high enough level to do these recipes. Do not break the table and craft lower-level items first.

@Barhandar  I used the "/chromastruct" (casting1, casting2, and casting3) command to build these, maybe it's supposed to be a platform? I'll try to build it by hand, see if that does it.

**Comment by Rewyn** [comment]
Probably because you jumped straight into creative, without knowing how crafting in CrC works in the first place. At least that's what it looks like to me, given it's something you encounter *very* early on in CrC and should know about.

The structures seemed valid. Do note that you can't use a higher tier than your table is, else it won't be able to recognize the structure.
Your problem is the tier of the casting table. It's only on t1, which means it can't do any recipes that require ANY sort of structure, meaning no recipes with the expanded grid, runes, or anything like that.
The table will also tell you if it has the appropriate structure for it's tier.

**Comment by ReikaKalseki** [comment]
Just using commands and expecting it to work means you have no idea how the mod works.

**Comment by Garr890354839** [comment]
> Just using commands and expecting it to work means you have no idea how the mod works.

@ReikaKalseki 
Just came back from manually building the table and it seems as if I cannot do rune crafting or better. I even tried creating lower-tier things, and still nothing.

**Comment by Rewyn** [comment]
And apparently you can't read either.
