### ISSUE TITLE
[DragonAPI] [Crash] [Init] java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by Garr890354839** [ReikaKalseki/Reika_Mods_Issues#2044]
Don't really know what this is about... MAYBE, just maybe one forgets with a 100MB file that Java arrays start at 0 instead of 1?
https://pastebin.com/YxGZQqJE

**Comment by ReikaKalseki** [comment]
No, there is an invalid entry; the error is not in the code.

**Comment by ReikaKalseki** [comment]
However, nothing looks wrong with the file...

**Comment by Tiger00008** [comment]
Hi, 
I tried to install your Rotary-, Reactor- and ElectriCraft (all Minecraft 1.6.4 and newest versions (including DragonAPI)) and after some weird ID problems, I got to the point where I get a "java.lang.ArrayIndexOutOfBoundsException: -1" error. According to the log and OpenEye (https://openeye.openmods.info/crashes/b81bbba4c584bf5be94b7e45ef8a86e5) it is connected to the SimpleRecycling Mod. However, this issue only exists if your mods are installed...
I would really like to integrate these mods into my private mod-pack and hope that you can provide a solution!
[crash-2019-06-21_00.17.12-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/3312290/crash-2019-06-21_00.17.12-client.txt)

**Comment by ReikaKalseki** [comment]
You are reporting an issue with a version five years out of date on an unrelated post.
