### ISSUE TITLE
[CC] Several low-level tools can't be enchanted with anything useful

### ISSUE THREAD

**Issue by Ieldra2** [ReikaKalseki/Reika_Mods_Issues#2046]
This applies, so far, to the multitool and the ore harvester. The list of available enchantments is extremely limited, and almost none of the enchantments available is useful. In particular, neither Efficiency, Fortune or Mending work, not does Silk Touch on the Multitool.

**Comment by Barhandar** [comment]
Can confirm, tried to stick ore harvester into vanilla enchantment table, nothing appeared. Which is bad because it's S L O W

**Comment by ReikaKalseki** [comment]
Unbreaking, Efficiency, and Soulbound can now be applied with the CC enchanter.
