### ISSUE TITLE
Steam/Performance Engine explodes instantly in Rainbow Forest

### ISSUE THREAD

**Issue by bpwhelan** [ReikaKalseki/Reika_Mods_Issues#2048]
I'm not sure if this is intended, or if it's possibly another mod overwriting temperatures for this specific biome, I'm guessing this is also the reason for random forest fires as well... The temperature in the rainbow forest in my world is ~ 300C (maybe a misplaced 0?) which causes engines to instantly explode. It is not the same for other CC biomes such as the Ender Forest where it's 30C as expected. I can post a video if not clear enough. Cheers. 

Full modlist: https://pastebin.com/G5RMtRcr

**Comment by ReikaKalseki** [comment]
My temperature code is specific to me, and thus not likely to be modified by another mod. Do you have a biome ID conflict?

**Comment by bpwhelan** [comment]
Yeah that's what I thought was the case... I don't believe I do unless there is a mod that automagically "solves" them.

**Comment by bpwhelan** [comment]
Looks Like that was it! It was in conflict with a nether biome so I guess rotarycraft/dragonAPI was grabbing the temperature from that. Thanks for your help! This may still be a bug but I'll close the issue since it is resolved on my end.
