### ISSUE TITLE
Questions Regarding Mod Customization 

### ISSUE THREAD

**Issue by RoloEdits** [ReikaKalseki/Reika_Mods_Issues#205]
I'm almost certain that this isn't the place to be asking this, but I do not know where i'm actually suppose to ask these type of questions so here it goes.

in your third-party customization's page at the bottom it says 
      "Also, if you are playing singleplayer, you can make whatever kind of changes you like, as long as noone but you is playing that version."

I only play single player as I have no friends to play with.

my question is what is the limits of the changes i can make because I have tried to make recipe changes to some items in minetweaker and they get commented out. Because of this i'm unsure as to how exactly one makes changes or if the only changes you can make are config options.

If the changes I make are getting commented out automatically because it thinks the changes are breaking the flow and balance i dont think there breaking the balance.some of the changes I wish to make are including but not limited to(only saying it like this because i want to reserve the right to change other this if I want or am forgetting some) making bedrock gears in a crafting table just like normal gears with 5 bedrock alloy in the same pattern and the same with shafts,as well as the screw driver recipe, and all the bedrock armor and tools to be crafting in a normal crafting table. there are a few others but i cant think of them off the top of my head right now.

I havent tried with CC but there are recipes i would like to change such as the pendants being crafted in a normal crafting table, but in particular the saturation pendent(I hate having to eat food!!), and making the potion crystals also craft able in a normal crafting table(I know this would be over powered but i'm ok with it).again there are things i cant remember off the top of my head.

if there is somewhere more appropriate that im supposed to talk with you about this kind of stuff then please direct me there.

thanks a lot

**Comment by ReikaKalseki** [comment]
The commenting is happening because the code does not realize you are playing SSP. I can fix this.

As for CC, it completely does not support MT, and I strongly advise against trying to add in recipes for items, as it is likely to break the progression system.

**Comment by RoloEdits** [comment]
thank you for responding so quickly it very appreciated.For CC i know it would break the progression a little but i don't think the potion crystals and pendants affect your progression into the mod that much i think its more of if not anything else just there to be a little OP but i may be wrong.As for the code not recognizing im playing in single player how would it be able to distinguish anyways? Is it something i can change on my end as i dont want to trouble you too much i would hate to be a bother.

**Comment by TomeWyrm** [comment]
No, as in LITERALLY break your ability to progress... at ALL. Don't try to tweak CrC unless you REALLY know what you're doing. I've been building packs for years, and I know the ins and outs of nearly 300 mods. I'm not touching CrC with a tweaking tool EVER unless it's the only reasonable alternative... and even then I'm going to go through some unreasonable alternatives first.

**Comment by RoloEdits** [comment]
Than I wont do CC as I don't want it to break anything thanks for the heads up.

**Comment by ReikaKalseki** [comment]
I am not talking about balance. I am talking about how CC assumes you got everything in order, and violating that may well cause it to become impossible to do various things, or to crash.

**Comment by RoloEdits** [comment]
Ok, yes, then I definitely don't want to mess around with that.

**Comment by ReikaKalseki** [comment]
The RC issue has been fixed.

**Comment by RoloEdits** [comment]
Thank you very much. will the changes be in the next update?

**Comment by ReikaKalseki** [comment]
Yes.
