### ISSUE TITLE
[RoC/Botania] Livingrock gearboxes waste overflow mana with no indication

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#2050]
Specifically, they can receive mana as long as they're not full, and drain is much smaller number than minimum default mana burst size (160 mana). Any overflow vanishes into the Ether, and the spreader refires as soon as gearbox drains a little mana.  
Botania itself avoids this issue because most things that can be full and still drain mana continuously use sparks (which have code to prevent just this issue) instead of spreaders; other stuff is recipe monjolos that immediately stop on filling up and so overflow, if any, happens much more rarely and is not noticeable.

**Comment by ReikaKalseki** [comment]
Fixed.
