### ISSUE TITLE
When I start a world it appears with this crash. ReactorCraft

### ISSUE THREAD

**Issue by Ziggurato** [ReikaKalseki/Reika_Mods_Issues#2051]
I have RotaryCraft, DragonApi and ReactorCraft installed so I can play a bit and when I create a world it crashes. I join again to join that world crashes again. Create another world cause I thought about the world being corrupted and no. It keeps crashing. Here is the crash on Pastebin. Oh I have everything updates btw.
CRASH: https://pastebin.com/dxRsRPM7
Hope you respond to me. Thanks!

**Comment by ReikaKalseki** [comment]
That is all vanilla code and has nothing to do with me. If I had to guess, you are running out of memory.

**Comment by Barhandar** [comment]
...why are you trying to run 1.7.10 with just 1GB of RAM assigned, and not matching minimum and maximum of RAM?
