### ISSUE TITLE
GeoStrata blocks can't be placed in multiplayer?

### ISSUE THREAD

**Issue by InitHello** [ReikaKalseki/Reika_Mods_Issues#2052]
I know it sounds bizarre, but I tested it with four different GeoStrata blocks on a server running forge 10.13.4.1614, V22d of DragonAPI, and V22a of GeoStrata with the client running the same versions. Any block I place is instantly removed, as though the server is telling the client that I didn't actually place the block.

Unfortunately I don't have the tools to record my screen, but if this is an actual error and not caused by some weirdness in my environment on both my macbook (running Oracle java 8) and my dev workstation (running ubuntu and OpenJDK 8) at my lab, it should be easy enough to reproduce.

Edit: I've also observed this behavior with RotaryCraft steel blocks, leading me to suspect even more strongly that it's somehow something weird across all of my environments.

**Comment by ReikaKalseki** [comment]
It is likely an inventory sync problem or some sort of permissions system.
