### ISSUE TITLE
Don't log anything if texture isn't found in resourcepack

### ISSUE THREAD

**Issue by HellsingDarge** [ReikaKalseki/Reika_Mods_Issues#2053]
Whenever ChromatiCraft lexicon is opened [this log](https://pastebin.com/b6KGuuvd) is printed into console

And maybe remove "Loading image at ..." and "Pipelining texture from ... to ..." lines?
As they don't seem to do anything useful, other than cluttering logs

**Comment by ReikaKalseki** [comment]
There is a config to disable those - and many other - messages.

**Comment by HellsingDarge** [comment]
> There is a config to disable those - and many other - messages.

I guess I should have checked...
Still, the error is logged
And by looking at the source code... Shouldn't [this line](https://github.com/ReikaKalseki/DragonAPI/blob/64225713fbe9c2c6806051caac0f6f5487601d8b/Libraries/IO/ReikaTextureHelper.java#L289) check for `FileNotFoundException`?

**Comment by ReikaKalseki** [comment]
No.
