### ISSUE TITLE
NPE Crash when Rendering Chromaticraft Item Elements (Hover + CTRL) [V22d]

### ISSUE THREAD

**Issue by bpwhelan** [ReikaKalseki/Reika_Mods_Issues#2054]
Not sure what the cause of this. All I know is that I didn't crash on this before, but I do now. Whenever hovering over an item and pressing CTRL to view the item's elements. 

I will try investigating further to see if i can find what i broke... In the mean-time here are two different crash-reports.

[Rendering Screen](https://pastebin.com/q1NkQ7tq)

[Updating screen events](https://pastebin.com/6NReZsJx)

**Comment by ReikaKalseki** [comment]
You have either an invalid recipe in the game data or something wrong with your mod installation.

**Comment by bpwhelan** [comment]
For future reference, seems that it is an outdated version of magical crops. Had to downgrade because of a (didn't know at the time) bad config. Upgraded/deleted config and works fine. Thanks for the hint.

**Comment by Atm2222** [comment]
What version were you on, and what did you do to fix it? I'm having the same issue.
