### ISSUE TITLE
[Rotary][Suggestion] TE Fluidtransposer recipes for Filling Station

### ISSUE THREAD

**Issue by VersedXth** [ReikaKalseki/Reika_Mods_Issues#2056]
I think it would be great to having the Option to using the Filling Station from rotary for filling Tesseracts like you can do it in Tinkers Construct with the Smeltery and the Bottler from immersive engineering . also Itemducts would be nice

**Comment by ReikaKalseki** [comment]
Not possible - the transposer works on discrete recipes requiring X amount of fluid; the filling station gradually adds fluid.

What would happen if you tried to fill a Tesseract with 476mB of ender? Or a glowstone lamp with only 103mB of glowstone?

**Comment by Rewyn** [comment]
If by "itemducts would be nice" you mean you'd like to see item transport pipes in RoC, those already exist.

**Comment by VersedXth** [comment]
> If by "itemducts would be nice" you mean you'd like to see item transport pipes in RoC, those already exist.

no i mean filling the itemducts with energized glowstone to get impulse itemducts

**Comment by Rewyn** [comment]
Ah, makes sense.
