### ISSUE TITLE
[RoC] Fractionation Unit loses pressure on rebooting SP world

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#2057]
Fully spun up (1000 kPa/250% efficiency), with 4 sufficiently fueled microturbines that do not have redstone anywhere nearby; drops to ~700-800 kPa/~130% efficiency after reloading world whether after a crash or regular full instance reload.
![2019-01-25_11 40 10](https://user-images.githubusercontent.com/2338212/51735556-bed10d00-2098-11e9-919e-ffdedf68736a.png)

Checking with `/mt blockinfo` reveals that it does indeed have significantly lowered "press" parameter.
EDIT: 
```
Reika: and ther torque for pressure is the running average over the last 40ticks
Reika: to prevent people trying to 'game' it
Barhandar: whiiich is probably why they drop in pressure on reboots, because they init with 0 and 0 + 1024/2=512
Reika: that is probably true
Reika: I can fix it by making the MovingAverage be written to NBT
```

**Comment by ReikaKalseki** [comment]
Does it always drop to the same value?

This might be due to the fact RC power can take a few ticks to propagate, depending on TE tick order.

**Comment by Barhandar** [comment]
Very approximately so, yes - it starts growing back too quickly to determine precise value (hence the range).

**Comment by ReikaKalseki** [comment]
Fixed, hopefully.
