### ISSUE TITLE
Villagers only want Lumen Pods

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2059]
![2019-01-27_10 31 02](https://user-images.githubusercontent.com/6917535/51805160-f7025800-221e-11e9-8c0b-f5daea67f1d3.png)

Every villager I talk to only wants to trade a Lumen Pod for 20 Emeralds. both vanilla and mod-added villagers. New world created after updating mods to latest versions.

Reika mod version: v22d

Mod list: https://gist.github.com/Zsashas/b85cf50c5a63144b7ab24585615b5668

**Comment by Rewyn** [comment]
Tried clicking on that arrow, next to the emerald?

**Comment by Shahelion** [comment]
The problem is that EVERY SINGLE villager shares the same trade. That wasn't the way it was before.

If that's intentional for some reason, then disregard.

**Comment by ReikaKalseki** [comment]
Villagers have a 1/4 chance of getting that trade.
