### ISSUE TITLE
Dragon API spams over 100k lines of Log for Oredict stuff....

### ISSUE THREAD

**Issue by Speiger** [ReikaKalseki/Reika_Mods_Issues#2060]
As stated in the title. Dragon API logs every single thing that changes during game start.
Yes that kind of stuff might be useful but over 100k lines of text?
Seriously, which player or server owner needs so much information? Just throw in a config for extendet "Log Detail". MultiMC even stops the log because its to much....

And for "I need it" case, there is ways to detect in dev things too, and the extended config could be used by you too. (Oh and it should default to small NO CONFIG SPAM)

**Comment by ReikaKalseki** [comment]
There *is* a config.

**Comment by Speiger** [comment]
@ReikaKalseki WHY THE FUCK IS THAT NOT ENABLED BY DEFAULT TO NOT SPAM?

**Comment by ReikaKalseki** [comment]
Because I expect people to realize that the point of configs is so that they can change the behavior as they see desirable, *without* resorting to pointless and inane complaints that they have to - *gasp* - **change** the options to get the setup ideal for their tastes.

**Comment by Speiger** [comment]
Well for those who want to setup a quick modpack for compat check may not want to setup configs.

I just wanted to make a test with your mod and a lot of other mods so chunkpregen runs smooth on that sadly your mod in that test flew out because it was not default compatible with my tests.

No problem but all bugreports withchunkpregen you have to deal with, until i can start it up without getting my debug disabled because you say spam is important.

**Comment by ReikaKalseki** [comment]
> Well for those who want to setup a quick modpack for compat check may not want to setup configs.

A compat check does not require modifying configs. Setting up a "real" *pack* does. And it should.

> No problem but all bugreports withchunkpregen you have to deal with, until i can start it up without getting my debug disabled because you say spam is important.

If your console shuts down with *that*, your launcher sucks.

**Comment by Speiger** [comment]
>  No problem but all bugreports withchunkpregen you have to deal with, until i can start it up without getting my debug disabled because you say spam is important.
>If your console shuts down with _that_, your launcher sucks.

@ReikaKalseki if your mod spams so much shit that it creates a +50MB log on startup and spams nothing important into it, creating overwelming garbage around the useful stuff, then the mod is garbage too.

**Comment by ReikaKalseki** [comment]
>  if your mod spams so much shit that it creates a +50MB

50MB? Are you kidding?

A typical launch log is only about 5-6MB; here are the logs from my test pack, which has *all* logging - more even than you - enabled, with 150+ large mods, and multi-hour game sessions:

![https://i.imgur.com/hRZbcS0.png](https://i.imgur.com/hRZbcS0.png)

Now, the amount of log output is in a big way dependent on what else is going on in the environment. For example, if you register 80000 things to the OreDictionary, that will create 80000 lines of log; registering 500 invalid recipes (eg an output of a stack of a null item) will cause 500 stacktraces, of about 50 lines each. But that sort of thing is firmly outside the domain of things which I am the cause of, and *is* well within the domain of things one should not do.

**Comment by Speiger** [comment]
![explorer_2019-02-09_08-54-19](https://user-images.githubusercontent.com/2556269/52518268-5b261280-2c48-11e9-8f95-dbcdded10f33.png)

**Comment by ReikaKalseki** [comment]
See above.

**Comment by Barhandar** [comment]
I see Greg in there. Consider not running two mods with EXCEPTIONALLY DETAILED, LONG AND WORDY DEBUG OUTPUTS with said debug outputs enabled at same time.
