### ISSUE TITLE
DragonAPI + Chisel + Optifine crash

### ISSUE THREAD

**Issue by CursedWolf** [ReikaKalseki/Reika_Mods_Issues#2061]
So just installed Dragon API v22d, Chisel v2.9.5.11, any version of Optifine and that crash appear after Forge loading complete and Main menu should appear.

Also have simple cores like CodeChikenLib, MrTJPCore, EJML.
[Crash log](https://pastebin.com/mGMwQkgA) and [fml-client-latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2806313/fml-client-latest.log) for help.

But the weird thing is that if I remove one of three mods, all worked fine.
For example: DAPI + Chisel, Chisel + OF, DAPI + OF.

Also if I add simple mods like JourneyMap, FastLeafDecay, FastCraft then I can create world and game crashed after few minutes. If I add Optifine in last queue on bunch of mods then world can't load up.
[List of mods without OF](https://user-images.githubusercontent.com/6039225/51889498-fc4cd780-23c3-11e9-92d6-56805f55cb02.png)

**Comment by ReikaKalseki** [comment]
I have all of those mods installed without issue. You are either using an invalid Optifine version - most are, for Forge setups - or have other mods messing with it.
