### ISSUE TITLE
Fragments of UA can be used in trades

### ISSUE THREAD

**Issue by Prunoideae** [ReikaKalseki/Reika_Mods_Issues#2063]
![l x elgv_6 5c_o eeem p](https://user-images.githubusercontent.com/24620047/52028731-0fd67a80-254b-11e9-938d-5134ef183923.png)

Is this a mistake or something? One UA block can drop many artefact fragments which is safe to carry, there's no meaning to use silk touch and carry tons of dangerous artefacts if I can trade with fragments.

**Comment by ReikaKalseki** [comment]
This is because village trades are not metadata-specific, and changing it now will break saves.
