### ISSUE TITLE
"CHROMATICRAFT ERROR: Could not load cached player progress" when starting server

### ISSUE THREAD

**Issue by 321nick** [ReikaKalseki/Reika_Mods_Issues#2069]
as the title says, i get this error in the CMD console of the minecraft mod pack server when it is running, and after generating spawn i get a crash. im not sure if this is the specific thing that is causing it, but i think it might as i tried removing most other things that would be causing issues. 

whats wierd is no crash-report generates, and the server.fml.log seems to be missing some of the server output, so i have to ctrl-a ctrl-c ctrl-v the cmd console log into a text file as soon as the last lines appear before it closes, which is odd. i did the AE-2 config change that caused issues in single player with chromaticraft crashes, the one where setting the config "B:exportItemNames=false" fixes it occurring too another issue i saw on the github. i tried with the 2 Dsun file encoding arguments and without, this time was without i think, which i saw on the minecraft forums as sometimes fixing crashes with rotarycraft (which i also have installed), but i still crash regardless so im not sure if those are related too the issue

im willing to provide any more information on my end on request.

https://gist.github.com/f9306c7eb0a2ac2237d6ca69414cee0a

CMD server console output^

https://gist.github.com/caaaeeecc1a4dd4507e19db6b162a48d

fml-latest-log^

**Comment by ReikaKalseki** [comment]
That is not the cause of the crash; it is the GC API referencing client code, the same as in issues #1477 #1110 #620 #501 #484.

And given how old those issues are, I suspect you are using an outdated GC version.

**Comment by 321nick** [comment]
thats odd. my versions of galacticraft are the most recent 504 build, the most recent for 1.7.10, from the micdoodle8 website. could it be possible it was fixed but more recent updated of galacticraft reversed the fix, maybe accidentally?

**Comment by ReikaKalseki** [comment]
> could it be possible it was fixed but more recent updated of galacticraft reversed the fix, maybe accidentally?

Possible, but such things are rare.

At any rate, *someone* is referencing `net/minecraft/client/multiplayer/WorldClient`, which does not exist on the server.

**Comment by 321nick** [comment]
any way to find out which mod it is, besides just trial and error, and method of elimination?

edit: my god im a dumbass. i had optifine in a forge server. its client side only. sorry
