### ISSUE TITLE
Suggestion: GitHub Release Hosting

### ISSUE THREAD

**Issue by jeremiahwinsley** [ReikaKalseki/Reika_Mods_Issues#207]
I have had trouble with Mediafire not letting me download files on my connection. Since GitHub offers [free release hosting](https://help.github.com/articles/distributing-large-binaries/), I figured I'd suggest upgrading to that. None of the legal issues like Curse, and with direct links instead of Mediafire ads, it would be a better experience for users as well.  [Here's](https://github.com/copygirl/BetterStorage/releases) a mod that uses them, for example.

This does necessitate linking a release to a specific commit as the example shows, but you could release in a separate repository if this is a concern.

**Comment by ReikaKalseki** [comment]
v8 and later is already being moved to Curse.
