### ISSUE TITLE
[Bug][GeoStrata] java.lang.ClassCastException on PartialBoundsBlock placement

### ISSUE THREAD

**Issue by Darkos333** [ReikaKalseki/Reika_Mods_Issues#2070]
So, this happened while I was trying to decoreate my base a little bit using PartialBounds block... Btw, I had no idea Railcraft has some hidden TEs xD

```
[14:00:10] [Client thread/FATAL]: Unreported exception thrown!
java.lang.ClassCastException: mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to Reika.GeoStrata.Blocks.BlockPartialBounds$TilePartialBounds
	at Reika.GeoStrata.Blocks.BlockPartialBounds.func_149668_a(BlockPartialBounds.java:165) ~[BlockPartialBounds.class:?]
	at net.minecraft.world.World.func_147472_a(World.java:3317) ~[ahb.class:?]
	at net.minecraft.item.ItemBlock.func_150936_a(ItemBlock.java:159) ~[abh.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(Unknown Source) ~[bje.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

To be honest I do not have time right now to prepare pull request, but I suppose catching this exception will solve the issue. Sounds like a simple fix.
[Full log](https://gist.github.com/Darkos333/60c824db67d2be5fa77fffc8373b2c58)

**Comment by ReikaKalseki** [comment]
This is RailCraft's fake air again.

**Comment by Darkos333** [comment]
Are you **sure** the problem is on Railcraft's end?
What I see in your code is that you cast whatever world.getTileEntity(x, y, z) returns to TilePartialBounds - making an assumption that this cast will always be valid. What if I place Partial Bounds block next to some other entity, lets say Thaumcrafts runic matrix??

**Comment by OvermindDL1** [comment]
> This is RailCraft's fake air again.

Doesn't RailCraft's fake air (tracking te) implement `isAir()==true` though, so it should work fine in any mod that tests air correctly?

Although if Railcraft doesn't implemen `isAir()==true` then it's all on it, but I thought it did?

**Comment by ReikaKalseki** [comment]
This is not about detecting air. This is about how "replaceable" blocks interact with the fact MC block/TileEntity changes in chunk data are non-atomic, namely the creation of a period of time where the block has been changed but the TE has not.

**Comment by OvermindDL1** [comment]
> This is about how "replaceable" blocks interact with the fact MC block/TileEntity changes in chunk data are non-atomic, namely the creation of a period of time where the block has been changed but the TE has not.

That means that a block is accessing it's TE without appropriate checks then.  That should be very defensive in those calls.

**Comment by ReikaKalseki** [comment]
> That means that a block is accessing it's TE without appropriate checks then. That should be very defensive in those calls.

No. Certain things should not have to be checked. A proper match between ID and TE is one of them. (Another example is a non-null world arg into a `WorldGenerator`). That some mods make that mistake is not reason to silently tolerate it. Besides, in many cases, this mismatch causes other, more persistent errors like NBT failure and failure to properly initialize.

**Comment by OvermindDL1** [comment]
> No. Certain things should not have to be checked.

You'd hope that, but MC is anything but stable.  ^.^;

> That some mods make that mistake is not reason to silently tolerate it.

A mismatch between Block and TE is something that's been happening even in pure vanilla randomly for many many years.  Like replacing a chest with an armor stand in the same tick can crash the game with not even forge installed.  It's good to be vigilant against those.

> Besides, in many cases, this mismatch causes other, more persistent errors like NBT failure and failure to properly initialize.

Not as long as everything is only initialized at the right times.  I've personally always scheduled a tick after block set and initialized on that next tick.

**Comment by ReikaKalseki** [comment]
> Not as long as everything is only initialized at the right times. I've personally always scheduled a tick after block set and initialized on that next tick.

Which fails when it is the fake air block receiving the tick instead of your block (ie the updateTick() is invoked on that block instance and not yours), because the system has not fully realized that your block now occupies that space. Or when the TileEntity your block requires is *never* placed, as often happens.

**Comment by OvermindDL1** [comment]
Hence why you schedule it for the next tick, not the current one, thus after everything is updated.

**Comment by ReikaKalseki** [comment]
> Hence why you schedule it for the next tick, not the current one, thus after everything is updated.

You have missed what I said entirely - even if the update comes at the next tick, it is often *still* sent to the block instance previously at that position, and sometimes, the appropriate Tile or Block ID is *never* placed to match its counterpart. Not one tick after, not 2487535497 ticks after.

**Comment by OvermindDL1** [comment]
> You have missed what I said entirely - even if the update comes at the next tick, it is often _still_ sent to the block instance previously at that position, and sometimes, the appropriate Tile or Block ID is _never_ placed to match its counterpart. Not one tick after, not 2487535497 ticks after.

If that happens just resubmit the change to the chunk at that point.

**Comment by ReikaKalseki** [comment]
While that might well work, it is also far too much of a time investment to fix a rare bug due to a stupid mistake/decision.

**Comment by Darkos333** [comment]
@ReikaKalseki : May I ask what kind of behaviour change you would like to see on Railcraft's side?
Its mostly just my curiosity, but since Im writing some "bring it all together" mod for my modpack, I may as well write ASM fix for that one day.

**Comment by ReikaKalseki** [comment]
ASM is not needed - that block can be disabled in the config.

Replaceable Tile Entities are dangerous, ones that are *likely* to be replaced by another are far worse, and ones that cannot even be detected are the worst of all.

**Comment by Darkos333** [comment]
To be honest Im not a fan of "cut if off if its broken" approach (_winks at BoP Promised Land_), but having read some posts about how it breaks other things... I will just disable it. At least until someone will complain about disabled tracking feature, which wont happen anytime soon :)

Thank you for your explanantions, this whole thread was a very interesting read. Btw have you ever thought about writing a book about modding, or at least some "advanced mod development" blog, or something like that? You seem to have a lot of precious knowledge, especially about 1.7.10, which makes it even more precious for those few still living on this forgotten land.

**Comment by ReikaKalseki** [comment]
> Btw have you ever thought about writing a book about modding

A long time ago, back during the summer of 2015, I was one of several people consulted - though AbrarSyed - regarding someone wanting to make a book onthat very subject. I have no idea what became of the project, as I never heard more again.
