### ISSUE TITLE
[Chromaticraft] Crystal shrine

### ISSUE THREAD

**Issue by chotke** [ReikaKalseki/Reika_Mods_Issues#2072]
![2019-02-10_08 51 07](https://user-images.githubusercontent.com/47343555/52537929-f0262a00-2d74-11e9-8814-ba5ef88755c8.png)
Mineshaft have been generated over crystal shrine and there is no pylon to break it, also cant open chests. This is totally stopped my boring machine.
BTW a lot of shrine generates in deep ocean, average 1700 blocks per shrine. This also makes boring machine useless.

**Comment by ReikaKalseki** [comment]
Welcome to MC worldgen.

**Comment by chotke** [comment]
> 
> 
> Welcome to MC worldgen.

But what about uncommon shrine generation in deep ocean biome?

**Comment by ReikaKalseki** [comment]
?

**Comment by chotke** [comment]
> 
> 
> ?

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=30704
Useless boring machine in deep ocean biome

**Comment by ReikaKalseki** [comment]
Why even mention the oceans? Shrines are rarer there than anywhere else.

**Comment by chotke** [comment]
> Why even mention the oceans? Shrines are rarer there than anywhere else.

But why do you think so? I assume that cavern structure cannot generate in a water. So it must be between bedrock and y=40, depends where solid blocks 
And can i ask one question about ElectriCraft there? Idk its a bug or feature..

**Comment by ReikaKalseki** [comment]
> But why do you think so? I assume that cavern structure cannot generate in a water. So it must be between bedrock and y=40, depends where solid blocks

It sounds like you are assuming that with a reduced viable range, the structures are generated more frequently in the remaining space to keep the rate per chunk the same.

That is not how it works. Does iron ore (normal range 0-64) generate 4x as often if you generate a world that is 0-16 of stone? No. The upper 3/4 just never appear.

**Comment by chotke** [comment]
> It sounds like you are assuming that with a reduced viable range, the structures are generated more frequently in the remaining space to keep the rate per chunk the same.
> 
> That is not how it works. Does iron ore (normal range 0-64) generate 4x as often if you generate a world that is 0-16 of stone? No. The upper 3/4 just never appear.

Ok thanks for ur reply and time, i found a way.
