### ISSUE TITLE
ChromatiCraft Multi-Aura Reapeaters Issue When Placed Horizontally

### ISSUE THREAD

**Issue by InstantKor** [ReikaKalseki/Reika_Mods_Issues#2073]
When trying to use a multi-aura repeater placed horizontally as Im trying to run a leyline to my underground ReC/RoC area. The repeater does not get recognized as a valid structure forcing me to route the leyline diagonally underground instead. Using the latest mod version v22d.

**Comment by ReikaKalseki** [comment]
You are building it wrong. I have a horizontal one myself.

**Comment by Barhandar** [comment]
Have you actually built it as the multi-aura repeater page specifies for horizontal cases?

**Comment by ReikaKalseki** [comment]
Me or him? I know full well that I have.

**Comment by Barhandar** [comment]
Him, obviously, it wouldn't work if you didn't.

**Comment by InstantKor** [comment]
Thanks after you said that I immediately went and tried a certain other crystalline stone block that forms in horizontal orientation. If only I would have experimented first instead of thinking that repeaters only will form with the listed blocks in the lexicon.
