### ISSUE TITLE
Compound Turbine and Compressor uncraftable

### ISSUE THREAD

**Issue by interlamer** [ReikaKalseki/Reika_Mods_Issues#2074]
Unless I am completely stupid (which is not impossible), the compound components seem to be uncraftable, which means it's impossible for me to obtain a Gas turbine. I am playing in Minecraft 1.7.10 witch Rotarycraft v22d, Reactorcraft v22a and Electricraft v22a (There are other mods, can get the full list if necessary).

The recipe for compound turbine and compound compressor is not showing in NEI. I tried looking it up on a wiki, which gave me the recipe with 2 relevant lower tier components, 4 tungsten ingots and 1 shaft core. I tried that recipe in a crafting bench, nothing happened.

**Comment by chotke** [comment]
![11](https://user-images.githubusercontent.com/47343555/52560578-70926c80-2e01-11e9-945c-12b7e7981e8d.jpg)

**Comment by ReikaKalseki** [comment]
They are indeed craftable and always have been. And NEI shows the recipes for me without issue.

**Comment by interlamer** [comment]
Then please tell me what am I doing wrong and if there's something I can do about it.
![2019-02-11_21 41 37](https://user-images.githubusercontent.com/22588596/52585551-28e20400-2e46-11e9-9cb5-cbe9cd1089b2.png)
![2019-02-11_21 41 45](https://user-images.githubusercontent.com/22588596/52585552-28e20400-2e46-11e9-9289-1230ac117c6f.png)

**Comment by chotke** [comment]
Delete all mods and redownload rotary

**Comment by interlamer** [comment]
There's a lot of other mods, some of which I would be really sad to delete, like Thaumcraft, for instance. I guess since I'm playing in SP, i could just delete the items i needed to craft them and give myself the components, but still.

**Comment by chotke** [comment]
You can temporary remove other mods and start a new game to check if components craftable

**Comment by ReikaKalseki** [comment]
I can assure you it is not TC.

**Comment by Barhandar** [comment]
Is the pack public or custom? If you rename scripts folder and reload world (or use `/mt reload`) do the recipes reappear?

**Comment by Rewyn** [comment]
A full list/packname would be interesting.
I wouldn't be too surprised if someone was stupid while messing with recipes.
