### ISSUE TITLE
RotaryCraft Handbook Fluid Compression Chamber Capacity Formula is Inaccurate

### ISSUE THREAD

**Issue by Skyler-Altol** [ReikaKalseki/Reika_Mods_Issues#2076]
So after looking into toying around with the FCC in a single player world, I have found that the capacity formula listed in the handbook does not align with the formula used in RotaryCraft's actual code. I have therefore reverse engineered a new formula from the code that matches the operations undertaken in the code base. This isn't a high priority issue, but also shouldn't be too hard to fix either.

The new formula is as follows: `factor * (10^floor(Log_2(torque) / 2) / 40)`

**Comment by ReikaKalseki** [comment]
Done.
