### ISSUE TITLE
server crash on start

### ISSUE THREAD

**Issue by marco6971** [ReikaKalseki/Reika_Mods_Issues#2083]
hi, I'm creating a modpack, I've already created the client modpack and I can play with it but when I try to create a server after disabling the client-side mod and run it dies with this crash report https://pastebin.com/d5mJ7da4

**Comment by OvermindDL1** [comment]
That's an impressive amount of mods...  o.O

A lot of the mods I don't recognize, but I do initially see:
```java
                  * The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.3.1 from CoFHCore-[1.7.10]3.1.4-329.jar).
```
And looking back up in the API section it's seen:
```java
        * CoFHAPI (1.7.10R1.0.2) from BrandonsCore-1.0.0.12.jar
```
So I'd start with removing that mod, it appears to be including an API that it absolutely should not be including, and an ancient version of it at that.  As it's a core mod for brandons whatever, some other mod probably depends on it and it would need to be removed too.

Other than that if it doesn't fix it, then this also looks wrong:
```java
        * CoFHAPI|transport (1.7.10R1.0.13) from EnderCore-1.7.10-0.2.0.39_beta.jar
```
As that endercore version appears to also be including an ancient version of cofhapi when it should not be including that API at all as it is not CoFH, though I doubt this one would be the issue.

Other than that then start removing mods until it loads, then refine it until you found out which one specifically is breaking it?

I'd bet some mod that ChromatiCraft uses or so touching a client file that it shouldn't be touching.  Maybe even start with 'just' reika's mods and build up from there?

**Comment by ReikaKalseki** [comment]
`As it's a core mod for brandons whatever, some other mod probably depends on it and it would need to be removed too.`
DraconicEvo.

And yes, this crash is due to API issues; given that the Rift uses like 12 mods' APIs - RF, OpenComputers Networking, TC Essentia, IC2 Power, ElectriCraft, BC pipes, AE networking, Mana Bursts, ComputerCraft networking, and more - it is unsurprisingly the first affected.

**Comment by marco6971** [comment]
can I extract the file of draconic evo and remove the cofhapi?

**Comment by OvermindDL1** [comment]
> can I extract the file of draconic evo and remove the cofhapi?

Assuming the mod doesn't rely on something from the old API then you should be able to.

**Comment by ReikaKalseki** [comment]
> Assuming the mod doesn't rely on something from the old API

Or sign the jar making the hash check fail.

**Comment by marco6971** [comment]
I don't know how to do it, i know the basics of programming but i never try to Code minecraft.
There's a big difference from the two approach?
How difficult could be the second one?

**Comment by marco6971** [comment]
Can you tell me if I'm doing it right? 
- I downloaded the 1.7.10 branch of brandon's core from github
- I deleted the cofh folder
- run sh gradlew build from terminal
but at the and it give me this error https://imgur.com/a/LrHdQKw reading this line:
/Users/marcogiunta/Downloads/BrandonsCore-1.7.10/build/sources/java/com/brandon3055/brandonscore/common/utills/InfoHelper.java:3: error: package cofh.api.energy does not exist
The code need this file but I think it has to being used the one from the cofh jar and not the one provided from the mod itself, I'm confused maybe (I'm almost sure) I'm missing something

**Comment by OvermindDL1** [comment]
@marco6971 You wouldn't want to rebuild it (although you can if you want, just exempt storing the cofh stuff in the final jar, you still need it to build, though that should be done by dependency resolution, anyone who copies source files in is *always* doing it wrong), rather just open up the jar (it is just a zip file) and delete the cofh directory from it and all files in it.  :-)

**Comment by marco6971** [comment]
that's exactly what I thought at the start, so I simply extract the file from .jar, deleted the cofh folder then zipped and renamed the mod folder but it give me this crash https://pastebin.com/GjD2QUb4 so I tried to recompile, i've tried to recompile even replace the cofh folder with the one inside enderIO but now it gives me this error:

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not find :forgeSrc:1.7.10-10.13.4.1614-1.7.10.
  Searched in the following locations:
  
this goes on with 8 link where it try to download  forgeSrc-1.7.10-10.13.4.1614-1.7.10.pom and  http://files.minecraftforge.net/maven//forgeSrc/1.7.10-10.13.4.1614-1.7.10/forgeSrc-1.7.10-10.13.4.1614-1.7.10.jar


I know that is not a bug related to this mod but i'm glad if you can help me anyway

**Comment by OvermindDL1** [comment]
> cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: com.brandon3055.brandonscore.BrandonsCore

Ah, that sounds like it wasn't deleted right or rezipped right or something other than the cofh directory was touched.  If you can give me a direct url to the jar I can do it right quick?

As for that other error, that sounds like forge's maven server broke again or its a bad forge versions,.  ^.^;

**Comment by marco6971** [comment]
https://minecraft.curseforge.com/projects/brandons-core/files/2292125
what? I'm simply using the utility compressor of mac OS but you are right i've just retry with another compressor (it didn't work) and now i read an error in the log: 

java.util.zip.ZipException: invalid CEN header (bad compression method)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_144]

so what I'm doing wrong? it isn't a simply compression or I'm just stupid?

**Comment by OvermindDL1** [comment]
Hmm, that link downloads a webpage and not a jar/zip?  I'm not at a GUI right now, in a terminal (I'm still at work), is there a direct link?  Otherwise ping me later and I can try to get to it this weekend.

**Comment by marco6971** [comment]
https://minecraft.curseforge.com/projects/brandons-core/files/2292125/download

**Comment by OvermindDL1** [comment]
Sorry for the delay, yeah that mod definitely includes an API that no mod should include, wiped it, see if this works:  https://overminddl1.com/minecraft/fixes/BrandonsCore-1.0.0.12.jar

**Comment by marco6971** [comment]
Unfurtunaly it doesn't work, it gives me the same error. 
In the log I find this https://pastebin.com/39Gb02gH (If do you need all the log just ask)
Can you plase tell me what I was doing wrong? I like to learn new things (I don't won't you to waste your time if is a very complicated thing don't worry)

**Comment by OvermindDL1** [comment]
```
[20:08:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: Reika.DragonAPI.ASM.InterfaceInjector$ImproperImplementationException: Error ASMing Reika/ChromatiCraft/TileEntity/Transport/TileEntityRift:
Could not inject interface li/cil/oc/api/network/Environment;
Reika/ChromatiCraft/TileEntity/Transport/TileEntityRift does not implement the following required methods:
    node ()Lli/cil/oc/api/network/Node;
    onDisconnect (Lli/cil/oc/api/network/Node;)V
    onMessage (Lli/cil/oc/api/network/Message;)V
```
This actually looks like quite a different error now...  o.O

What version of OpenComputers are you running?  Is it 'at least' MC1.7.10-1.7.2.1204 or newer?  I don't know what version Reika requires but I'm pretty sure it runs with the modern versions of OC.

**Comment by marco6971** [comment]
I didn't install nor opencomputer nor computercraft but installing the first one solves the problem

**Comment by OvermindDL1** [comment]
> I didn't install nor opencomputer nor computercraft but installing the first one solves the problem

Hmm, that tells me that either that some other mod is including OC's API or Reika's mods are requiring the API non-optionally, interesting, wonder which.  If you care to find out then uploading your entire mod pack so I can scan it would work, but honestly I'd say just include OC, it's an awesome mod.  :-)

**Comment by marco6971** [comment]
oh yes, i don't want to waste time when i can simply install a mod and honestly I forgot to install it
