### ISSUE TITLE
Feature Request for World Rifts

### ISSUE THREAD

**Issue by InstantKor** [ReikaKalseki/Reika_Mods_Issues#2085]
Hello, 
World rifts are fantastic blocks, I use them extensively to help distribute fluids and such around. Just started using these blocks to help manage my steam distribution to my turbines. But suing ammonia as the working fluid its important that steam doesnt build up in the steam lines. So my request is for world rifts to respond to redstone levels just like how adjacency cores do. 

This would allow me route steam to the different turbines as a duty cycle rather then having 1-2 turbines running at a fraction of their capacity. I realize I could do this with pipe pumps since engines can respond to redstone but with world rifts would just be more covenant.

**Comment by ReikaKalseki** [comment]
World rifts *carry* redstone. Responding to it would break that.

**Comment by InstantKor** [comment]
Was not aware rifts also carry redstone!

**Comment by Rewyn** [comment]
You could also shut down the turbines when there's insufficient steam build up in the steamlines to run them at maximum capacity.

**Comment by InstantKor** [comment]
Yes, this is what I ended up doing using the clock from extended redstone to have the steam grate turn off and alloying the steam to build up.
