### ISSUE TITLE
Engine Control Unit not working

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#2088]
I set my engine control unit to 25% and redstone activated, gave it a redstone signal, and put it under my gas turbine. However, it still put out the full 67 MW according to the dynamometer. I'm not sure if it's a bug or I'm just doing something wrong, but I don't know how to get it to work.

**Comment by chotke** [comment]
> or I'm just doing something wrong
![1](https://user-images.githubusercontent.com/47343555/53911919-70803800-4060-11e9-8476-d3c3ee23deb3.png)

**Comment by DFliyerz** [comment]
Ok, so what did you do? Did you use the redstone mode?

**Comment by chotke** [comment]
It works only at 2 modes: redstone (true/false) OR manual (100% 50% 25% 6.25%)

**Comment by DFliyerz** [comment]
I'm not sure I get you considering it shows 0.00% as an option on manual but I'll try again when I get a chance.

**Comment by ReikaKalseki** [comment]
In redstone mode, give it analog redstone.
