### ISSUE TITLE
Crashing when using Chroma Ritual for personal enchantment

### ISSUE THREAD

**Issue by Reignofmagic** [ReikaKalseki/Reika_Mods_Issues#209]
So when trying to give myself surge protection with the chroma ritual I instantly crashed after trying to activate the ritual. Before I had my crystal network set up I could start this up just fine, but as soon as I have it able to connect to the pylon network I will crash on start. I'll try only using single repeaters to it to see if blocking the multi aura repeater helps any

Using the latest versions of all your mods, and Java 8 v51

http://pastebin.com/KKWxery0

Update:

Using a single repeater helped, although I did crash a few more times I was able to get myself enchanted.

**Comment by ReikaKalseki** [comment]
Same as https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/201

**Comment by Reignofmagic** [comment]
I mainly opened this as well because it was a different crafting table (ritual as opposed to casting)
