### ISSUE TITLE
Tile Accelerator not Working

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#2093]
I have an 8x tile accelerator and when placing it next to most machines (such as the EIO alloy smelter) it has no effect whatsoever. I checked my config and it shouldn't require power, so I'm not sure what's going on.

**Comment by ReikaKalseki** [comment]
Yes, there were issues with the logic. These have since been fixed.

**Comment by DFliyerz** [comment]
So any ETA on a release with this fix?

**Comment by ReikaKalseki** [comment]
Next release.
