### ISSUE TITLE
Spawner controller nonfunctional unless player directly touching spawner

### ISSUE THREAD

**Issue by dalapo** [ReikaKalseki/Reika_Mods_Issues#2094]
Spawners controlled by a Spawner Controller remain inactive unless in direct contact with the player. Tests with /nbtedit and /blockinfo confirm that the timer does not count down when this is the case.

The Spawner Controller edits the spawner's maximum range to Integer.MAX_VALUE; however, likely due to this data being stored as a short in the NBT data, the actual number used becomes -1. It is unclear why this prevents the spawner from working, as Vanilla code seems to indicate a -1 value should give infinite range as intended; however, editing the maximum range to be 16 causes the timer to count down normally until a spawn is performed and the range is reset to -1. At this time, the spawner begines spawning every tick, regardless of input speed, because the timer is now stuck at zero and does not reset.

It is suggested to either completely override the spawner's timing with a timer implemented in the controller itself; or to override the criteria for whether or not the spawner is active instead of simply expanding the range.

**Comment by ReikaKalseki** [comment]
I just converted the limit to Short.MAX instead of Int.MAX.
