### ISSUE TITLE
[CrC] Focus crystals don't seem to work

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#2095]
Focus crystals don't seem to speed up crafting when placed in the crafting area, do they need to be posted in a certain area to work?

**Comment by ReikaKalseki** [comment]
Yes. You will know when they are correctly placed.

**Comment by Barhandar** [comment]
And because Reika's answer is incredibly unhelpful, they're placed over the gaps in the ring of blocks-at-same-level-as-table.

**Comment by DFliyerz** [comment]
Yup, I figured it out after looking deeper in the code.
