### ISSUE TITLE
[AM2+CrC] Progression Manager + Fire Guardian Boss Spells Crash

### ISSUE THREAD

**Issue by DiamondSentinel** [ReikaKalseki/Reika_Mods_Issues#2097]
What Happened: Was playing in a custom modpack and the game crashed whenever I spawned a boss from another mod. Considering most of the crash-report concerns CrC (and AM2's dev is kinda frozen), figured I'd come to you. 

Basically, the boss would work just fine while in creative (or it wasn't aggro'd), but whenever you'd switch to survival mode and aggro the boss, the game would crash about .5 seconds after his first attack began. We've looked into it on our end, but we don't exactly know how the progression manager works, so we came here. 

Crash Report: https://pastebin.com/PGY0iat5

**Comment by bencerda1** [comment]
To add, the client and server both crashed (I help administer the server he was on).

**Comment by ReikaKalseki** [comment]
Fixed.
