### ISSUE TITLE
RotaryCraft Machines do not Recpect Advanced Rocketry Atmosphere, or the lack Thereof

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2099]
As the title says, RoC things(machines, items) have no concept of no atmosphere
Here are the problematic ones:
_**BLOCKS**_
- Combustion engines and turbine engines turn on and run with no atmosphere
- Fans push with no atmosphere
- The Dew Point Aggregator can collect water with no atmosphere
- The compactor reports an ambient pressure with no atmosphere
- The water from sprinklers does not automatically sublimate with no atmosphere
- The sonic borer runs with no atmosphere
- The sonic weapon runs with no atmosphere 
- The air pressure gun runs with no atmosphere
- The Aerosolizer gives me potion effects with no atmosphere
- The pulse jet furnace runs with no atmosphere
- The refrigeration unit works with no atmosphere
- The internal liquid of machines (Grinder, liquefaction machine, drying bed) does not sublimate with no atmosphere 
- ReC Steam blocks do not disperse immediately with no atmosphere
- The Fermenter works with no atmosphere
- The item vacuum has suction with no atmosphere
_**ITEMS**_
- The jetpack with wings still glides with no atmosphere
- The handheld vacuum still sucks with no atmosphere
- The ultrasound might work with no atmosphere(IDK what it does)

And Lastly: would it be possible to have the bedrock armor have with their space suit, so you can have both at once?

**Comment by ReikaKalseki** [comment]
@zmaster587 - is there an API for this stuff?

**Comment by voidsong-dragonfly** [comment]
In addition: These machines should not work in *pressurized* environs, only planetside in natural air

- DPA
- Refrigeration Unit

And these machines should vary production/effectiveness rates based on the density of the atmosphere

- DPA
- Refrigeration Unit
- Fan
- sonic borer
- sonic weapon
- air pressure gun
- Aerosolizer

**Comment by voidsong-dragonfly** [comment]
https://github.com/zmaster587/AdvancedRocketry/tree/MC1.7/src/main/java/zmaster587/advancedRocketry/api/atmosphere This might be what you want

**Comment by ReikaKalseki** [comment]
On its own that is not enough information to fetch atmosphere data; there is no way to get the string lookup IDs.

**Comment by voidsong-dragonfly** [comment]
Perhaps this: https://github.com/zmaster587/AdvancedRocketry/tree/MC1.7/src/main/java/zmaster587/advancedRocketry/atmosphere
And then lines 108-131 of this?:
https://github.com/zmaster587/AdvancedRocketry/blob/MC1.7/src/main/java/zmaster587/advancedRocketry/dimension/DimensionProperties.java

**Comment by ReikaKalseki** [comment]
Those are not part of the API.

**Comment by voidsong-dragonfly** [comment]
https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/api/AdvancedRocketryAPI.java#L16
Zmaster said this is what you want. Hopefully it is.
Edit: oops, pasted wrong thing,

**Comment by ReikaKalseki** [comment]
Those are not fetchable objects either.

**Comment by voidsong-dragonfly** [comment]
https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/api/AdvancedRocketryAPI.java#L16
Zmaster said you would want this.

**Comment by zmaster587** [comment]
https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/api/AdvancedRocketryAPI.java#L16

Calling `getAtmosphere` on this will get you an [IAtmosphere](https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/api/IAtmosphere.java) object, that will have info about whether or not combustion is allowed.  Generally if it's a combustible atmosphere, there will be pressure.  1.7 will not be getting updated atmospheres where that's not the case, so as long as you stay on 1.7, it's safe to say that if it's not combustible, then there's no pressure.  

1.12.2+ does have atmospheres that are not combustible and have non 0 pressure.

There's currently no way to get atmosphere at a specific block thru the API alone, however 1.7.10 is no longer updating at all, so I don't think accessing `zmaster587.advancedRocketry.atmosphere.AtmosphereHandler.getOxygenHandler(dimid).getAtmosphereType(BlockPos)` would be problematic for getting the atm type at a certain location.  For 1.12+, that will be part of the API.

**Comment by ReikaKalseki** [comment]
Fixed, and I made several of the above not work in zero-atm environments. Not all, because I do not want them all being nonfunctional in such cases.
