### ISSUE TITLE
Machines all purple and black cubes

### ISSUE THREAD

**Issue by dothemonstermash** [ReikaKalseki/Reika_Mods_Issues#21]
All my rotarycraft machines are purple and black cubes?

**Comment by trajing** [comment]
Issue with textures?
I honestly haven't a clue what's happening. I'm going to go with the obligatory "what version are you using?".

**Comment by coolsquid** [comment]
Please post your FML log at Pastebin.

**Comment by trajing** [comment]
If the log's too big, try [Gist](https://gist.github.com).

**Comment by dothemonstermash** [comment]
https://gist.githubusercontent.com/dothemonstermash/462fc63648a4d99a74b4/raw/gistfile1.txt

**Comment by zemerick** [comment]
I'm trying to read through the log, but there's the obvious downside of it being quite large. As usual with these large packs, there's also a lot of errors.

Are you able to test disabling mods?

I haven't found anything about it yet, but are you using a resource pack?

Can you also double check your computers date? Reika did a recent April Fools prank, and a number of people instead of seeing the intended textures, saw the missing texture. ( That's the purple black and squares. )

Also, do you know anything about this:

[21:39:35] [main/INFO] [FML/]: DRAGONAPI: Loading on Reika's computer; Dev features enabled.

I would imagine you're not on Reikas computer, so that shouldn't be there. I'm not sure if there's a simple debug config setting, or what more might be required for this, but you should definitely try reverting any such thing.

**Comment by dothemonstermash** [comment]
I tried faking it being reika's computer (not an easy task, not gonna lie, had to make a hard drive partition and everything) to fix the bug, but no dice.

Want ingame screenshots?

**Comment by zemerick** [comment]
First, revert all of that so we can see everything from scratch.

I think the issue is:

```========================================= ROTARYCRAFT ===============================================
[21:40:15] [Client thread/INFO] NOTICE: It has been detected that third-party plugins are being used to disable parts of RotaryCraft.
[21:40:15] [Client thread/INFO] Because this is frequently done to sell access to mod content, which is against the Terms of Use
[21:40:15] [Client thread/INFO] of both Mojang and the mod, the mod has been functionally disabled. No damage will occur to worlds,
[21:40:15] [Client thread/INFO] and all machines (including contents) and items already placed or in inventories will remain so,
[21:40:15] [Client thread/INFO] but its machines will not function, recipes will not load, and no renders or textures will be present.
[21:40:15] [Client thread/INFO]All other mods in your installation will remain fully functional.
[21:40:15] [Client thread/INFO] To regain functionality, unban the RotaryCraft content, and then reload the game. All functionality
[21:40:15] [Client thread/INFO] will be restored. You may contact Reika for further information on his forum thread.```

Something is attempting to overwrite or modify part of Rotarycraft. Part of the disabling as a result of this, is to remove all textures.

**Comment by dothemonstermash** [comment]
How did you get that

**Comment by zemerick** [comment]
It's your log that you provided.

**Comment by dothemonstermash** [comment]
So the mod is stopping me from getting donations? How does he expect me to run the server?

**Comment by zemerick** [comment]
You need to talk to Mojang, not Reika. They specifically prohibit blocking any paid features. ( It's not a donation if it's for a feature. That's paywalling. )

It should be noted that doing so could get you into trouble with Mojang.

To answer your question though: The same way all of the legitimate people do it. Actual donations ( which can be rewarded with trinkets, like capes or special renders, but not a part of the actual game. ), fees to have access to your server ( you can't block single features, but you can ask for a fee for use at all. ), or sponsorships. There's probably more I can't think of. Suffice to say, you can easily run a server without paywalling.

**Comment by zemerick** [comment]
Here's the Mojang post detailing this nearly a year ago:

https://mojang.com/2014/06/lets-talk-server-monetisation-the-follow-up-qa/

and Reika does also explicitly prohibit this as well:

https://sites.google.com/site/reikasminecraft/licensing

Namely section 6: Monetization.

**Comment by dothemonstermash** [comment]
How does everyone else on my network do it? I talk to all these other admins and they sell lots of content. Applied Energistic and Thermal expansion sell really well, like half of them get most of there money from those.

I'll go ask them for help with a workaround.

**Comment by zemerick** [comment]
If you read the Mojang post, they can sell access on a server basis. So, for example, someone could pay $10 for a server to have access to TE. However, every single person on that server much be able to access all of the same stuff, regardless of any money they did or did not pay.

Most likely though: They're doing it against Mojangs will, and probably without their knowledge. They should be reported to Mojang.

For your specific problem the solution is simple. Remove all of Reikas mods.

Many mods like TE don't have built in protections against such practices, but Reikas mods do. If you don't like it, don't use his mods.

**Comment by dothemonstermash** [comment]
So I talked with the rest of the server admins on my skype group and they have some ideas. I don't wanna remove reika mods because they could make some real dough. I don't care what the rules say, if mojang wanted us not to be able to run servers then they would just ban it.

**Comment by madolinn** [comment]
On a scale of one to greedy retarded, where do you lie? You're stealing his content and committing fraud to your customers. Do you not see how big of a scummy act that is on top of being illegal? Majong doesn't need to "ban" it, because the government already did.

**Comment by zemerick** [comment]
They did ban it. Just because they haven't found you, and sued you yet, doesn't mean it's allowed.

**Comment by ReikaKalseki** [comment]
Congratulations. A new tag got created for you and your lawbreaking friends. Enjoy!

**Comment by 1Matthias** [comment]
Too bad I couldn't find your server address in that log, because I found Mojang's Google form for matters like this. https://docs.google.com/forms/d/1jUIPyvww8E5LfzrGDJ828AtuucPOf2gE87i06g7xT-U/viewform

**Comment by madolinn** [comment]
Yeah next time we should ask for the IP to "check it out" since we "have no idea what the issue is".

**Comment by 1Matthias** [comment]
Oh...yeah...

**Comment by zemerick** [comment]
Yup, I realized this too late as well.

At least we have a better idea how to handle it next time.

**Comment by ljfa-ag** [comment]
> Yeah next time we should ask for the IP to "check it out" since we "have no idea what the issue is".
I'm not sure if it's a good idea to trick people like that.

**Comment by zemerick** [comment]
I was thinking more like just asking for a download of the pack to check some things out.

Namely, we also can't always assume that the person is trying to do something like this on purpose, or that they may not know what they did is against the rules. So, one of the best ways is to download it ourselves, and look for any plugins or such in question.

We need to verify first, then worry about alerting Mojang if they are indeed found to be monetizing in ways against the T&Cs.

**Comment by TomeWyrm** [comment]
Well, this guy flat-out confessed.

**Comment by keybounce** [comment]
I'm wondering if letting the server be destroyed by selling bedrock tools might be the answer. Reika already destroyed one pay server that way.

**Comment by madolinn** [comment]
I think a better option would be to instead of Black and Purple checkered squares, machines would have a random assigned number from 5 - 20 minutes in ticks, and upon reaching the number would explode as large as a reactor. Then a hologram would appear thanking them for stealing his content.

**Comment by coolsquid** [comment]
While I would love some of those ideas, I think they might cause quite a bit of drama...

**Comment by 1Matthias** [comment]
I like Madolinn's idea. I like it a lot.

**Comment by zemerick** [comment]
Yea...as hilarious as it would be in cases deserving, there are a number of possibilities where the person wouldn't deserve it. Either they didn't know what they were doing was wrong, or it was a false positive. Reika put a lot of effort into making sure his current method was non-destructive.

**Comment by ReikaKalseki** [comment]
And I explicitly spoke with Jaded and slowpoke to make sure the current method did not run afoul of their rules - they were very clear it had to remain non-destructive.

**Comment by coolsquid** [comment]
"Their rules"? Uhm, since when were they able to set rules for mods?

**Comment by madolinn** [comment]
Ah bummer. I was just reminded of old school C&C:RA2 days where your base would randomly explode if you pirated it.

But if it has to be non-destructive, I suppose this will do.

**Comment by ReikaKalseki** [comment]
> "Their rules"? Uhm, since when were they able to set rules for mods?

Rules for FTB pack mods.

**Comment by ljfa-ag** [comment]
We'll just leave it as is - someone who does this will not be able to use the mods and that should be it.
