### ISSUE TITLE
Electricraft crash when rotating motors

### ISSUE THREAD

**Issue by alyip98** [ReikaKalseki/Reika_Mods_Issues#210]
http://pastebin.com/F9UHLBMi

**Comment by ReikaKalseki** [comment]
WTF?

Is this repeatable?

**Comment by ReikaKalseki** [comment]
Hello?

**Comment by Zedrimar** [comment]
No problems here :/ I have the latest version too

**Comment by zemerick** [comment]
I think this might be something else triggering it. Perhaps forge, or java.

http://pastebin.com/1QVCh1QU

No electricraft, not repeatable. We are both on Java 1.8 update 45 and forge 1448.

I only got the crash once, and have had a ton of random problems with my modpack, so I never posted it. ( Mostly it's my computer going downhill. I think I have some bad HD sectors. Possibly my northbridge on MB is going. )
