### ISSUE TITLE
RoC Flamethrower Turret causes crash

### ISSUE THREAD

**Issue by Acroficer** [ReikaKalseki/Reika_Mods_Issues#2100]
Started playing around with turrets recently and noticed that whenever the flamethrower turret, I crash either as soon as it fires, or within a few seconds. I was able to fix it by removing the turret in MCedit so it wouldn't fire as soon as I joined the game.

I am running a private modpack, so I apologize if it's some sort of conflict I didn't catch. 

[Crash Report](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2976239/crash-2019-03-17_23.08.55-client.txt)

Unrelated, but I love what you've done with Rotarycraft, I've been using it forever and I find most other tech mods are just too easy to use compared to this.

**Comment by ReikaKalseki** [comment]
It looks like the parameters are never initialized from the server for the client.

**Comment by ReikaKalseki** [comment]
Fixed.
