### ISSUE TITLE
RoC Fertilizer Triggers Redstone Repeaters

### ISSUE THREAD

**Issue by Acroficer** [ReikaKalseki/Reika_Mods_Issues#2103]
Noticed the other day that after I installed a fertilizer in my sugar cane farm, the repeats would randomly get powered very briefly (probably for about a single tick), causing all the pistons on one side to extend then reset. Did some testing in creative to confirm that it is, in fact, the fertilizers causing this. 

Even if there are no crops around for the fertilizer to grow, repeaters around it will occasionally be randomly powered. Not every repeater in the area will be triggered simultaneously, just singular ones. Not sure about this part, but it seems like it happens more frequently the more crops there are for the fertilizer to grow. 

![Example](https://user-images.githubusercontent.com/29238115/55266902-ac6c7e80-5255-11e9-8521-7a31be90d084.png)

Wasn't able to capture one of them powered in this screenshot because it is for such a short duration, but this was the setup I used to test it.

**Comment by ReikaKalseki** [comment]
The fertilizer spams block ticks, and redstone works on scheduled ticks; this is not a surprise.

**Comment by ReikaKalseki** [comment]
Fixed.
