### ISSUE TITLE
RoC Grinder (And possibly other machines) Does not Allow OreDict inputs from CustomRecipe system

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2104]
The grinder, when presented with an oredict entry as an input, will not register the recipe, citing that 'that item does not exist'
Log: https://pastebin.com/RreBwrWE
Script:
{
    type = "TFSilver"
    input = "ore:ingotSilver"
    output = "ThermalFoundation:material:34"
}

**Comment by ReikaKalseki** [comment]
Now you can specify an `ore_input` tag, which is an OreDict tag string, *without* the `ore:` prefix.
