### ISSUE TITLE
Rotarycraft crashes on v22

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#2105]
I couldn't play minecraft with the mod Dragon API and Rotarycraft and Reactorcraft.
they crashed.
but i could play minecraft when the mod only Dragon API. it didn't has any crashes

https://pastebin.com/M6JDsaWn

**Comment by Rewyn** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2021

**Comment by ghost** [comment]
Thank you so much, it fixed
