### ISSUE TITLE
[CrC] Tile accelerator works only when placed on top of machine.

### ISSUE THREAD

**Issue by Hiranus** [ReikaKalseki/Reika_Mods_Issues#2106]
As title says, tile accelerator works only when placed on top off machine, which makes it impossible to accelerate things like smeltery. 
Previously they worked on all connected tiles, which made it amazing. 
If this limitation is not a bug, then could you alter them so that we could pick a side which will be accelerated, similar to lumen relays?

**Comment by ReikaKalseki** [comment]
#2093
