### ISSUE TITLE
Woodcutter does not fully cut birch trees

### ISSUE THREAD

**Issue by Hiranus** [ReikaKalseki/Reika_Mods_Issues#2107]
As title says, woodcutter has issues with top of birch trees. It seems like this is only problematic tree.
https://imgur.com/a/2oxLwhn
Woodcutter was set to 1 operation /tick and enchanted with infinity.

Also, woodcutter can be used to multiply silverwood sapling. When woodcutter enchanted with infinity replants silverwood saplings it places 9 saplings instead of 1. You can then harvest additional saplings and let one in the center grow, and repeat.

**Comment by Hiranus** [comment]
This issue also appears with CrC trees, but this time my woodcutters are set to 3 operations per tick.
Also, Could you prevent woodcutters from replanting Rainbow Trees? They cant do this properly, so its just a waste of saplings.

**Comment by ReikaKalseki** [comment]
I adjusted the coded size for birch trees; try again in the next release.
