### ISSUE TITLE
The Chinese localization of RotaryCraft Handbook.

### ISSUE THREAD

**Issue by UUUii** [ReikaKalseki/Reika_Mods_Issues#211]
Hi @ReikaKalseki , my partners @IamAchang, @3TUSK , @bakaxyf and I finished the localization of the [manual](https://github.com/UUUii/Reika_mods_Localization/tree/master/Rotarycraft/Resources). We appreciate @Mrkwtkr for using his translation as reference. We love this job, can let more people enjoy this translation is our desire. I want to ask if you can add the Simplified Chinese localization for RotaryCraft Hankbook, thanks for your time.
Anyway, thank you for bring us  so much fun.

**Comment by 3TUSK** [comment]
Hold on... the link should be [this one](https://github.com/UUUii/Reika_mods_Localization/tree/master/Rotarycraft/Resources/zh_CN).

**Comment by ReikaKalseki** [comment]
Implemented. https://github.com/ReikaKalseki/RotaryCraft/commit/98ee66481db1b5c80e39f5f22c8e970b8ce9cc60

**Comment by UUUii** [comment]
Thanks a lot. :)
