### ISSUE TITLE
Essence Item (Magic Crops' smelted Essence Flakes from RC Extractor) crash the game when put into crafting grid

### ISSUE THREAD

**Issue by Goddfrey** [ReikaKalseki/Reika_Mods_Issues#2110]
https://pastebin.com/vUPh3jGb

Instant crash when trying to put into 2x2 grid or AE2 crafting terminal

**Comment by ReikaKalseki** [comment]
Fixed, but there is a problem in fetching the item, which indicates deeper problems. Ones I may not be able to fix.
