### ISSUE TITLE
BlockArray StackOverflowError

### ISSUE THREAD

**Issue by DracoScythem** [ReikaKalseki/Reika_Mods_Issues#2111]
[Original discussion was on the discord server]
The [BlockArray](https://github.com/ReikaKalseki/DragonAPI/blob/master/Instantiable/Data/BlockStruct/BlockArray.java) recursive methods spam the log with SOEs due to the maxDepth value never being changed from the initial Integer.MAX_VALUE.
One trigger is changing large (multiple thousands of blocks) structures built from crystaline stone (resulting in logs like [this](https://pastebin.com/rKrP75qK) ).

**Comment by ReikaKalseki** [comment]
Fixed.
