### ISSUE TITLE
[CC] Particle Spawner particle selection is off the screen

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2113]
![2019-05-05_09 06 13](https://user-images.githubusercontent.com/6917535/57197254-f95d0800-6f19-11e9-886e-131804f30bea.png)

Maybe a scroll bar? Another page?

**Comment by ReikaKalseki** [comment]
Fixed. ![https://i.imgur.com/1zqQXTg.png](https://i.imgur.com/1zqQXTg.png)
