### ISSUE TITLE
DragonAPI not allowing edit to Chromaticraft dimension biome IDs

### ISSUE THREAD

**Issue by NanoViridescence** [ReikaKalseki/Reika_Mods_Issues#2116]
(THIS WAS A REDONE POST.)
So I have a conflicting biome id with Skylands and some wierd biome from the mod Caveworld 2. I attempted to change the biome id via Chromaticraft as i couldn't figure out how to edit the Caveworld biomes, and I was met with this. "The game crashed whilst initializing game
Error: Reika.DragonAPI.Exception.StupidIDException: ChromatiCraft was not installed correctly:". I do not know how to tell DragonAPI that I editted it because of a conflict. Help please.

**Comment by NanoViridescence** [comment]
Nevermind, i was able to find the cause. turns out DragonAPI doesn't use negative biome numbers. I never knew that it would be a problem

**Comment by ReikaKalseki** [comment]
> Nevermind,  i was able to find the cause. turns out DragonAPI doesn't use negative  biome numbers. I never knew that it would be a problem

*Nothing* uses negative biome IDs; what gave you the idea that it *would* work?
