### ISSUE TITLE
IC2 classic E-net test / discussion

### ISSUE THREAD

**Issue by Carbon-Ghost** [ReikaKalseki/Reika_Mods_Issues#212]
I'm gonna open this ticket for testing how well IC2 classic e-net works with Rotary craft, this is more a discussion ticket. 

Ofc if there is an issue with Rotary craft gonna post it here, if IC2 classic on IC2 classic Git, you know how it works etc... 

Anyway gonna test those aspects : 
- Multipackets handling with Both IC2-C and Rotary craft & addons
- If recipes works or if we need to add our own
- Energy loss
- Old IC2 uranium with reactor craft just for fun :3 ( it's OD but I never got a chance playing much with Réactor craft ^^°'' )
- IC2 classic Easy mode E-net

Reika, thanks for your amazing mod btw. If possible keep this open for possible compat suggestions for both mods interactions ^^

**Comment by Carbon-Ghost** [comment]
Reminder to myself, 1EU/t=268MW.

**Comment by ReikaKalseki** [comment]
> Reminder to myself, 1EU/t=268MW. 

This is wrong (by a factor of 129000x) and this issue tracker is not for discussions. The [thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=1140#c23091) is.

**Comment by Carbon-Ghost** [comment]
Kk, sorry I just didn't have a MC forum account ^^°'' ( and you don't visit a lot the IC2 forum :C my pseudo is Mine_Sasha there btw ). 

Also the value was the RF one times 4 following the RF conventional conversion ( 1 eu = 4 rf ). 

Though may I ask you one thing, for scaling purposes, how powerful do you consider the IC2 uranium bar ? ( knowing it's ingotUranium ), just out of curiosity ^^ ( compared to the IC2 classic normal and steam reactor ? ).

**Comment by Carbon-Ghost** [comment]
Note that I didn't meant to anger you or anything, just wanted to talk about the current compat of both mods because it's one of the few I didn't had time to test so far due to the fact that this mod is so huge and awsome that it needs a lot of time and patience to try everything that they can do together :D

**Comment by ReikaKalseki** [comment]
> Also the value was the RF one times 4 following the RF conventional conversion ( 1 eu = 4 rf ). 

1 RF/t = 520W (and so 1EU/t = 2.08kW), so I have no idea how you got the numbers you did.

> Though may I ask you one thing, for scaling purposes, how powerful do you consider the IC2 uranium bar

I do not compare against other mods. I compare against real life.

**Comment by Carbon-Ghost** [comment]
"The ratios I pick are picked for multiple and specific reasons and will remain fixed. Adding configurability just opens up the problem of people ignoring the fact that ReC scales exponentially and making everything completely implausible and unbalanced, as well as the possibility for packs where 1RF/t=67MW." so it's less than that from what I understand ^^'' Nvm didn't understood it properly. 

@Uranium : So what values then ?

**Comment by ReikaKalseki** [comment]
> as well as the possibility for packs where 1RF/t=67MW." so it's less than that from what I understand

That was saying someone _could make_ such a pack if I made it configurable, and I deliberately picked ridiculous values.

> @Uranium : So what values then ?

Uranium does not have a set "energy value". ReC does not work like that. Nothing is hardcoded like "X energy per fuel", "Y cores per boiler", or "Z boilers per turbine".

**Comment by Carbon-Ghost** [comment]
@Energy : Sorry for derping up the values

@Uranium : I might need to replay RoC and it's sister mods, has been quite some time since I last messed around it ^^ Hadn't much time to play though :C ^^''
