### ISSUE TITLE
[ChC] [Thaumcraft] Energized Rock drops nothing when using Excavation Wand Focus

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2121]
Nothing at all. Mining with a pickaxe drops Chromic Dust as usual.

**Comment by ReikaKalseki** [comment]
Not fixable; these ores have custom harvest code that can only be interfaced with by the other mod.

**Comment by Shahelion** [comment]
I figured that would be the case with the ores that are only revealed later, but this one is visible from the start, so I thought it might be different. Oh well.

**Comment by ReikaKalseki** [comment]
> this one is visible from the start

No it is not.
