### ISSUE TITLE
Ticking block entity  java.util.ConcurrentModificationException [CRC]

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2124]
[crash-2019-06-11_15.15.18-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/3278133/crash-2019-06-11_15.15.18-server.txt)

Happened after I moved a multi aura repeater in line of sight of my new lumen tree,
my network was also feeding my Item fabricator in case that is relevant.

Seems to be a one time thing, the second lumen tree didn't crash me.

**Comment by lAimBotl** [comment]
[crash-2019-06-11_15.33.56-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/3278225/crash-2019-06-11_15.33.56-server.txt)

here is another, it was just powering my Item fabricator now, and I recently put a item in it to fabricate.

**Comment by lAimBotl** [comment]
[crash-2019-06-11_16.30.11-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/3278449/crash-2019-06-11_16.30.11-client.txt)

I believe I have fastcraft installed. I will remove it and see if it shows up again.

Oof, same thing without fastcraft.  I added 8 more Item fabricators recently.
[crash-2019-06-11_16.44.01-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/3278487/crash-2019-06-11_16.44.01-client.txt)

**Comment by OvermindDL1** [comment]
Yeah that's the same thing I've reported in the past, the container is being modified while it is being iterated from code that it is calling from within the iteration.  It's existed for a long time.

**Comment by lAimBotl** [comment]
Not sure if this is related, but I thought I may as well put up as much info on it as possible,
since I hear CME's are hard to track down.

![2019-06-12_13 55 08](https://user-images.githubusercontent.com/10777735/59374426-d3493580-8d19-11e9-8e22-ad42951f583a.png)


![2019-06-12_13 55 26](https://user-images.githubusercontent.com/10777735/59374408-cb899100-8d19-11e9-9163-8aeb0e46a7ca.png)

**Comment by lAimBotl** [comment]
"https://pastebin.com/5yc5wePm" Rendering crash (unsure how related it is to this though)

**Comment by ReikaKalseki** [comment]
This is the CrystalNetworker CME issue - referenced in #1299, #1100, #1290, and more - again.
