### ISSUE TITLE
DragonAPI Causes Memory Issue - 1.7.10 V22d

### ISSUE THREAD

**Issue by Rytech2** [ReikaKalseki/Reika_Mods_Issues#2126]
Im trying to pull together a personal mod pack with minimal mods to try and get the full Rotery/Reactor/Electric Craft experience and only include other mods like a mini map, NEI, and a inventory organize mod. nothing else. No changes to configs or anything. But it crashes in the middle of startup with OutOfMemory errors. Strange since I made much bigger personal packs with little over 80 mods at once.

So I pulled out a few mods and tested until I got down to only the DragonAPI. I made a separate instance to where I only have minecraft 1.7.10, forge 10.13.4.1558, and DragonAPI 1.7.10 V22d as the only mod installed for testing, yet it still hits OutOfMemory errors during startup. I can't wrap my mind around on why this 1 mod is so demanding on memory when its only a API and the only mod running where my other 80+ mod pack is fine. I tried redownloading the mod twice from the curseforge site but didn't fix the issue.

During startup the task manager shows it will hit around 520 MB of memory used before it crashes and Its nowhere near maxing out what its given. Is there a function or process the DragonAPI does during the startup that requires a lot of memory? The 1.6 V23b version loads fine (From FTB Tech World 2 which is where I recently discovered the mod in) but I wanted to try a up-to-date version.

Anyway, here's the log. Hopefully this can be resolved.
Removed.

**Comment by lAimBotl** [comment]
A crash report is preferred (assuming it is generating one?).
Have you already tried increasing the ram?
1GB really isn't "that" much.

**Comment by Rytech2** [comment]
It did generate one but its the same as whats at the bottom of that log.
Removed.

1GB is indeed not much by todays standards but im unable to assign anymore memory without stability issues since im stuck on a old 32-bit OS (not by choice sadly). Even with that, it should still be plenty enough for a few mods.

**Comment by Rytech2** [comment]
Also noticed this error. Is it anything to be concerned about?

[23:54:25] [Client thread/ERROR] [DragonAPI]: The mod DragonAPI is expecting signature 32:F5:F4:E8:44:C0:EA:C8:6F:46:8A:8E:F3:05:05:7B:6F:90:0F:78 for source DragonAPI 1.7.10 V22d.jar, however there is no signature matching that description

**Comment by lAimBotl** [comment]
32 bit cannot allocate more than 4 gb, that doesn't mean you cannot use 1.1/2gb
though if you cannot go up to 2 gb you can go up somewhere in between "1.0-1.9"
("-Xmx1248m")

**Comment by Rytech2** [comment]
Thats possible without issues? Launchers like Technic and a few others don't allow for setting above 1GB for some reason (for 32-bit java installs) and ive herd stability issues can happen if you attempt to go higher. Even with a 1GB setting, ive seen memory usage in task manager for java reach up to around 1.5GB usage along with all 512MB of my video memory many times on heavy mod runs which I don't understand why it does that. Issues do start once its maxed out. Its like 1GB means 2GB to it or whatever its set to means double of that. Why?

Anyway, I have around 2.5GB system memory free and tried with 1408MB and still hitting out of memory issues. Any higher and java spits out a error of not being able to reserve enough free memory.

"Error occurred during initialization of VM
Could not reserve enough space for 1572864KB object heap"

**Comment by ReikaKalseki** [comment]
1GB is nowhere near enough for a MC modpack; you simply need to allocate more RAM, and to acquire more if you currently lack the hardware to do so.
