### ISSUE TITLE
Right clicking completed puzzles "BlockStructureDataStorage" thingy: Ticking memory connection

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2127]
I completed a puzzle, and for the lulz I right clicked that thing you see at the start, apparently that crashes your game.
I see there is another, but it is about a server kicking you, but I am in single player.

https://pastebin.com/1edyhE4H

**Comment by ReikaKalseki** [comment]
This sort of crash normally is restricted to puzzles whose data has been lost but whose blocks persist (which normally is only possible due to a hard crash preventing the normal deletion-on-unload behavior). If you solved the puzzle, that clearly is not happening here.

**Comment by ReikaKalseki** [comment]
So it turns out it was trying to manipulate the core you already mined. Fixed.
