### ISSUE TITLE
Fuel Cores return incorrect percentage on checkFuel()

### ISSUE THREAD

**Issue by Thorinair** [ReikaKalseki/Reika_Mods_Issues#2128]
Found a small issue when using OpenComputers to read the fuel level of the ReactorCraft Fuel Cores. The reported fuel percentage is not multiplied by 100 even though the returned string has a percentage symbol in it.

For example, the returned value is: `0.785%`

The issue is specifically in this line of code: https://github.com/ReikaKalseki/ReactorCraft/blob/899bf8ff8951fc556bcd0cecd9947cc4dde351bf/Auxiliary/Lua/LuaReactorCheckFuel.java#L59

**Comment by ReikaKalseki** [comment]
Fixed.
