### ISSUE TITLE
Fluorite Gem does not work in fuel enhancer with thorium

### ISSUE THREAD

**Issue by Goddfrey** [ReikaKalseki/Reika_Mods_Issues#2129]
You need specifically Fluorite Crystal which can be made from said Fluorite Gem. I don't know if its intended behavior but Fluorite Gem works in Uranium Processor just fine

**Comment by ReikaKalseki** [comment]
As the gem is an RC item, not an ReC one (and thus ReC cannot access it), plus the fact that the enhancer does not use the OreDict, this cannot be fixed without major rewrites.
