### ISSUE TITLE
OreType$OreRarity Crash When Updating To Dragon API v8a

### ISSUE THREAD

**Issue by RoloEdits** [ReikaKalseki/Reika_Mods_Issues#213]
http://pastebin.com/SY20w7X2

**Comment by RoloEdits** [comment]
After removing AOBD it didn't crash anymore. Maybe the problem is an interaction between the two mods.

**Comment by ReikaKalseki** [comment]
AOBD needs to update. @ganymedes01

**Comment by buttilda** [comment]
Fixed.

**Comment by RoloEdits** [comment]
Thanks A Lot :)

**Comment by TomeWyrm** [comment]
Have either of you managed to figure out (and fix) the AOBD/Extractor interaction issues?

**Comment by ReikaKalseki** [comment]
Not yet.
