### ISSUE TITLE
Expanded Redstone ID conflict unresolvable

### ISSUE THREAD

**Issue by Tiger00008** [ReikaKalseki/Reika_Mods_Issues#2130]
Hello,
I wanted to put the expanded Redstone mod on my server (--> and on my computer). However, the item slot 3000 was already occupied by some Mekanism item. On my computer, I just changed the Item IDs from Resonant Redstone in the config file and it worked just fine. Nevertheless, when I copied the file on my server, I got the ID conflict error again. So I checked whether I copied the right one, copied it again and got the same error. Do you know what caused this error/how to resolve this? Both expanded Redstone and dragonAPI are the latest files from your website.

The error message on the server is:
Reika.DragonAPI.Exception.IDConflictException: Expanded Redstone was not installed correctly:
CONFLICT: Slot 3000 is already occupied by mekanism.common.block.BlockBasic@79a3195f when adding Rei
ka.ExpandedRedstone.ItemBlocks.BlockRedTile@42d6ea5c

The Config File:

# Configuration file

####################
# block ids (changed)
####################

"block ids" {
    I:"Lapis Wire"=3619
    I:Tileentity=3618
    I:Tileentity2=3620
}

####################
# control setup
####################

"control setup" {
    B:"Ticking Noises"=true
}

####################
# item ids
####################

"item ids" {
    I:"Lapis Wire"=20500
    I:Placer=20501
}

**Comment by Tiger00008** [comment]
I just realized that the configs aren't as single files in the config folder, but in a Reika folder...

**Comment by ReikaKalseki** [comment]
Moreover you are still playing 1.6, a version that went obsolete in September 2014.
