### ISSUE TITLE
Addition of Way to Seperate Pipe Connections

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2131]
Two ideas:
 #1- Have the screwdriver be able to separate pipe connections, and therefore let two pipes run side by side independently
 #2- Have pipes have no directionality when placed, and need screwdriver to connect to other pipes or machines. When placed _by clicking on another pipe block_ they autoconnect, but only then. Allows for pretty much the best control over piping solutions you could ever want.
I personally like the idea of #2 better, but it may be harder to implement. GT6 has done something similar to this if you want an example.

**Comment by ReikaKalseki** [comment]
....Is this not what the sandstone pipes are?
