### ISSUE TITLE
Liquid pipe crashes client

### ISSUE THREAD

**Issue by Gamemaster21981** [ReikaKalseki/Reika_Mods_Issues#2134]
Here's my mod just in case that's required (pulled from the same crash log), however I doubt that it would be needed since when I was playing with ReactorCraft I had only used RotaryCraft, ReactorCraft itself, and Better Builder's Wand here and there :

UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJAAAA	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAA	ActuallyAdditions{1.7.10-r21} [Actually Additions] (ActuallyAdditions-1.7.10-r21.jar) 
	UCHIJAAAA	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCHIJAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCHIJAAAA	ae2stuff{0.5.0.56} [AE2 Stuff] (ae2stuff-0.5.0.56-mc1.7.10.jar) 
	UCHIJAAAA	aether{1.7.10-1.6} [Aether II] (aether-1.7.10-1.6.jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJAAAA	Avaritia{1.13} [Avaritia] (Avaritia-1.13.jar) 
	UCHIJAAAA	aobdsingularities{1.0.4} [Another One Bites The Dust: Singularities] (AOBDsingularities-1.0.4.jar) 
	UCHIJAAAA	betterbuilderswands{0.8.1} [Better Builder's Wands] (BetterBuildersWands-0.8.1-1.7.10r92+aec06c3.jar) 
	UCHIJAAAA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHIJAAAA	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	SonarCore{1.1.3} [SonarCore] (SonarCore-1.7.10-1.1.3.jar) 
	UCHIJAAAA	Calculator{1.9.11} [Calculator] (Calculator-1.7.10-1.9.11.jar) 
	UCHIJAAAA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	CompactMachines{1.7.10-1.21} [Compact Machines] (compactmachines-1.7.10-1.21.jar) 
	UCHIJAAAA	CompactSolars{4.4.39.315} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.39.315-universal.jar) 
	UCHIJAAAA	controlling{1.0.0} [Controlling] (Controlling-1.7.10-1.0.0.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h.jar) 
	UCHIJAAAA	DragonAPI{v22d} [DragonAPI] (DragonAPI 1.7.10 V22d.jar) 
	UCHIJAAAA	RotaryCraft{v22d} [RotaryCraft] (RotaryCraft 1.7.10 V22d.jar) 
	UCHIJAAAA	ElectriCraft{v22a} [ElectriCraft] (ElectriCraft 1.7.10 V22a.jar) 
	UCHIJAAAA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b200.jar) 
	UCHIJAAAA	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCHIJAAAA	forgeendertech{1.7.10-1.9.2.0} [Forge Endertech] (ForgeEndertech-1.7.10-1.9.2.0-build.0061.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	FTBL{1.0.18.2} [FTBLib] (FTBLib-1.7.10-1.0.18.3.jar) 
	UCHIJAAAA	FTBU{1.0.18.2} [FTBUtilities] (FTBUtilities-1.7.10-1.0.18.3.jar) 
	UCHIJAAAA	advgenerators{0.9.20.123} [Advanced Generators] (generators-0.9.20.123-mc1.7.10.jar) 
	UCHIJAAAA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJAAAA	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJAAAA	je_calculation{0.3.4} [Just Enough Calculation] (JustEnoughCalculation-1.7.10-0.3.4.jar) 
	UCHIJAAAA	Mekanism{9.1.1} [Mekanism] (Mekanism-1.7.10-9.1.1.1031.jar) 
	UCHIJAAAA	MekanismGenerators{9.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.1.1031.jar) 
	UCHIJAAAA	MekanismTools{9.1.1} [MekanismTools] (MekanismTools-1.7.10-9.1.1.1031.jar) 
	UCHIJAAAA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.0-1.jar) 
	UCHIJAAAA	NotEnoughWands{1.2.3} [Not Enough Wands] (notenoughwands-1.2.3.jar) 
	UCHIJAAAA	NuclearCraft{1.9g} [NuclearCraft] (NuclearCraft-1.9g--1.7.10.jar) 
	UCHIJAAAA	OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
	UCHIJAAAA	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UCHIJAAAA	origin{8.0.3} [Origin] (Origin-1.7.10-8.0.3.jar) 
	UCHIJAAAA	addonscrewdriver{1.0.0} [OriginAddonScrewdriver] (Origin-1.7.10-8.0.3.jar) 
	UCHIJAAAA	p455w0rdslib{1.0.4} [p455w0rd's Library] (p455w0rdslib-1.7.10-1.0.4.jar) 
	UCHIJAAAA	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6-fix-1.jar) 
	UCHIJAAAA	ProjectE{1.7.10-PE1.10.1} [ProjectE] (ProjectE-1.7.10-PE1.10.1.jar) 
	UCHIJAAAA	HeroSuits{1.2} [Project Superhuman] (ProjectSuperhuman - v1.2 - 1.7.10.jar) 
	UCHIJAAAA	ReactorCraft{v22a} [ReactorCraft] (ReactorCraft 1.7.10 V22a.jar) 
	UCHIJAAAA	reauth{3.5.0} [ReAuth] (ReAuth-3.5.0.jar) 
	UCHIJAAAA	rftools{4.23} [RFTools] (rftools-4.23.jar) 
	UCHIJAAAA	rivalrebels{1.7.10Z1} [Rival Rebels] (rivalrebels-1.7.10Z1.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.10.9} [Storage Drawers] (StorageDrawers-1.7.10-1.10.9.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	UCHIJAAAA	weatherManMod{RELEASE} [Weather Carpets] (Weather Carpets Mod-1.2.5.jar) 
	UCHIJAAAA	weather2{v2.3.19} [Localized Weather & Storms] (weather2-1.7.10-2.3.20.jar) 
	UCHIJAAAA	zettaindustries{1.1} [Zetta Industries] (zettaindustries-1.1-120.jar) 
	UCHIJAAAA	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.31-universal.jar) 
	UCHIJAAAA	aobd{2.9.2} [Another One Bites The Dust] (AOBD-2.9.2.jar) 
	UCHIJAAAA	UniDict{1.7.10-2.9.2} [UniDict] (UniDict-1.7.10-2.9.2.jar) 
	UCHIJAAAA	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 6/27/19 12:29 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at Reika.RotaryCraft.Blocks.BlockPiping.func_149668_a(BlockPiping.java:130)
	at portablejim.bbw.core.WandWorker.getBlockPositionList(WandWorker.java:126)
	at portablejim.bbw.core.BlockEvents.blockHighlightEvent(BlockEvents.java:49)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_648_BlockEvents_blockHighlightEvent_DrawBlockHighlightEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:256)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1254)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Reika.RotaryCraft.Blocks.BlockPiping.func_149668_a(BlockPiping.java:130)
	at portablejim.bbw.core.WandWorker.getBlockPositionList(WandWorker.java:126)
	at portablejim.bbw.core.BlockEvents.blockHighlightEvent(BlockEvents.java:49)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_648_BlockEvents_blockHighlightEvent_DrawBlockHighlightEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:256)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1254)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Gamemaster2198'/1416, l='MpServer', x=129.54, y=56.10, z=-1789.40]]
	Chunk stats: MultiplayerChunkCache: 15, 15
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (137,4,-1769), Chunk: (at 9,0,7 in 8,-111; contains blocks 128,0,-1776 to 143,255,-1761), Region: (0,-4; contains chunks 0,-128 to 31,-97, blocks 0,0,-2048 to 511,255,-1537)
	Level time: 205740 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 55 total; [EntityDischarge['entity.RotaryCraft.Discharge.name'/1922, l='MpServer', x=141.50, y=58.25, z=-1761.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1923, l='MpServer', x=141.50, y=54.75, z=-1761.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1924, l='MpServer', x=142.88, y=56.50, z=-1760.47], EntityDischarge['entity.RotaryCraft.Discharge.name'/1925, l='MpServer', x=140.09, y=56.50, z=-1762.56], EntityDischarge['entity.RotaryCraft.Discharge.name'/1936, l='MpServer', x=143.50, y=58.25, z=-1771.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1937, l='MpServer', x=143.50, y=54.75, z=-1771.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1938, l='MpServer', x=145.25, y=56.50, z=-1771.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1939, l='MpServer', x=141.75, y=56.50, z=-1771.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1825, l='MpServer', x=123.50, y=58.25, z=-1782.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1826, l='MpServer', x=123.50, y=54.75, z=-1782.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1827, l='MpServer', x=122.78, y=56.50, z=-1784.13], EntityDischarge['entity.RotaryCraft.Discharge.name'/1828, l='MpServer', x=124.19, y=56.50, z=-1780.91], EntityDischarge['entity.RotaryCraft.Discharge.name'/1841, l='MpServer', x=127.50, y=53.75, z=-1783.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1850, l='MpServer', x=115.50, y=58.25, z=-1765.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1851, l='MpServer', x=115.50, y=54.75, z=-1765.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1852, l='MpServer', x=113.78, y=56.50, z=-1765.19], EntityDischarge['entity.RotaryCraft.Discharge.name'/1853, l='MpServer', x=117.19, y=56.50, z=-1765.84], EntityDischarge['entity.RotaryCraft.Discharge.name'/1854, l='MpServer', x=117.50, y=58.25, z=-1761.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1855, l='MpServer', x=117.50, y=54.75, z=-1761.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1856, l='MpServer', x=116.09, y=56.50, z=-1760.47], EntityDischarge['entity.RotaryCraft.Discharge.name'/1857, l='MpServer', x=118.88, y=56.50, z=-1762.56], EntityDischarge['entity.RotaryCraft.Discharge.name'/1858, l='MpServer', x=116.50, y=58.25, z=-1763.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1859, l='MpServer', x=116.50, y=54.75, z=-1763.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1860, l='MpServer', x=114.88, y=56.50, z=-1762.81], EntityDischarge['entity.RotaryCraft.Discharge.name'/1861, l='MpServer', x=118.09, y=56.50, z=-1764.22], EntityDischarge['entity.RotaryCraft.Discharge.name'/1862, l='MpServer', x=115.50, y=58.25, z=-1773.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1863, l='MpServer', x=115.50, y=54.75, z=-1773.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1864, l='MpServer', x=113.78, y=56.50, z=-1773.84], EntityDischarge['entity.RotaryCraft.Discharge.name'/1865, l='MpServer', x=117.19, y=56.50, z=-1773.19], EntityDischarge['entity.RotaryCraft.Discharge.name'/1866, l='MpServer', x=116.50, y=58.25, z=-1775.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1867, l='MpServer', x=116.50, y=54.75, z=-1775.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1868, l='MpServer', x=114.88, y=56.50, z=-1776.22], EntityDischarge['entity.RotaryCraft.Discharge.name'/1869, l='MpServer', x=118.09, y=56.50, z=-1774.81], EntityDischarge['entity.RotaryCraft.Discharge.name'/1872, l='MpServer', x=115.50, y=58.25, z=-1767.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1873, l='MpServer', x=115.50, y=54.75, z=-1767.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1874, l='MpServer', x=113.75, y=56.50, z=-1767.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1875, l='MpServer', x=117.25, y=56.50, z=-1767.50], EntityClientPlayerMP['Gamemaster2198'/1416, l='MpServer', x=129.54, y=56.10, z=-1789.40], EntityDischarge['entity.RotaryCraft.Discharge.name'/1762, l='MpServer', x=127.50, y=53.75, z=-1783.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1763, l='MpServer', x=129.50, y=63.75, z=-1799.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1764, l='MpServer', x=131.50, y=53.75, z=-1783.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1894, l='MpServer', x=129.50, y=63.75, z=-1799.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1895, l='MpServer', x=131.50, y=53.75, z=-1783.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1896, l='MpServer', x=141.50, y=58.25, z=-1777.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1897, l='MpServer', x=141.50, y=54.75, z=-1777.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1898, l='MpServer', x=142.88, y=56.50, z=-1778.56], EntityItem['item.item.item.placer.17'/107, l='MpServer', x=125.25, y=55.13, z=-1788.09], EntityDischarge['entity.RotaryCraft.Discharge.name'/1899, l='MpServer', x=140.09, y=56.50, z=-1776.47], EntityItem['item.tile.sandStone.default'/112, l='MpServer', x=132.88, y=55.13, z=-1791.03], EntityDischarge['entity.RotaryCraft.Discharge.name'/1904, l='MpServer', x=131.50, y=58.00, z=-1783.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1905, l='MpServer', x=131.50, y=55.00, z=-1783.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1914, l='MpServer', x=142.50, y=58.25, z=-1763.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1915, l='MpServer', x=142.50, y=54.75, z=-1763.50], EntityDischarge['entity.RotaryCraft.Discharge.name'/1916, l='MpServer', x=144.09, y=56.50, z=-1762.81], EntityDischarge['entity.RotaryCraft.Discharge.name'/1917, l='MpServer', x=140.88, y=56.50, z=-1764.22]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Gamemaster21981** [comment]
Also if you don't mind me asking, why haven't you been active lately on updating your mods?

**Comment by OvermindDL1** [comment]
Unsure if this is 'this' problem, but it is definitely 'a' problem:

https://github.com/ReikaKalseki/RotaryCraft/blob/master/Blocks/BlockPiping.java#L127

The return value is not checked for validity before it is used, a common programmer error that Kotlin makes impossible to ignore (you either have to lie or you are forced to check validity).  This can and *will* return `null` at times depending on the client-side state of the world build-up from packet data, so I'd bet that it is this issue.

> Also if you don't mind me asking, why haven't you been active lately on updating your mods?

Reika seems to vanish for long periods so that's not uncommon.  In addition Reika doesn't code in the open, instead opting for large `squash`'d git dumps into this public repo, which makes it amazingly irritating to actually follow what's going on, which I think is precipitated by the fact that Reika uses a custom build system instead of something standard like gradle combined with not using git appropriately.

I.E. this is normal, just wait for suddenly a large chunk of code to suddenly be merged in when a new release is made.  ^.^;

**Comment by ReikaKalseki** [comment]
This is not an error. Like stated on past issues, I have an explicit policy of not checking things which would only deviate from what they should be if something else has gone seriously wrong.

In this case, the WandWorker thing is passing in the wrong coordinates (ie it gets block at x1,y1,z1 and queries its collision box at x2,y2,z2, which is in violation of the contract of that function). Had I had a simple sanity check here, that error would go unnoticed.

> Also if you don't mind me asking, why haven't you been active lately on updating your mods?

What?

![https://i.imgur.com/0dRldEW.png](https://i.imgur.com/0dRldEW.png)

**Comment by Gamemaster21981** [comment]
Thanks for replying, also I mean that like you haven't been online on [Curse](https://www.curseforge.com/members/reika_kalseki/followers) since Christmas, and was wondering if you discontinued development of your mods or what. Sorry about that.

**Comment by Gamemaster21981** [comment]
Also I think I should've mentioned this before hand, the crash came from a world that was already being worked on (and multiple crashes had occurred prior to this crash, however this crash was the one to actually break the world and make it inaccessible).

Oh and also sorry for not looking deeper into the crash log and wasting your time that you could've used for other things.

Edit: Just disabled Better Builder's Wands via Twitch Client, I am indeed able to access the world again, thanks.
