### ISSUE TITLE
[RC] Enable Forcefield/Containment field functionality for players

### ISSUE THREAD

**Issue by CraftedMods** [ReikaKalseki/Reika_Mods_Issues#2135]
I suggest to expand the functionality of the force- and containment fields so that they work with players too. The fields don't apply to the player who placed them, but to any others not whitelisted. Players could be whitelisted the same way as it's possible with the cannons currently (with the cannon key, though the name doesn't fit anymore then). 
I also suggest that this feature would be configurable, because some servers maybe don't want that these fields apply to players. For my (private) server it would help a lot, because we then can stay with RC, without the need of another force-field mod (Advanced Repulsion Systems), and other than that, I think that this features adds nicely to the idea of a forcefield.
A question that could arise with that is, what to do if two forcefields placed by two different players who don't whitelist each other intersect. The best answer would be to simply disallow this kind of intersections if the fields are not placed by the same player, but only if the fields blocks players.

**Comment by ReikaKalseki** [comment]
I see no value in a containment field - simply trapping a player will see them destroy the emitter, or, if not possible, be trapped forever, which is not fair.

**Comment by CraftedMods** [comment]
Indeed. Therefore I think making it configurable would help. I still have use-cases for that (designing traps, adventure maps, server events, ...), but eventually the majority of players hasn't. So if you think this is too problematic/not worth your time, I understand that. The main reason for this suggestion are the forcefields, I suggested the containment field changes because of these use-cases and because of analogy reasons. So if it isn't not too much effort to apply this effect to containment fields too and making it configurable, I would appreciate that.

**Comment by ReikaKalseki** [comment]
Thinking about this further, players have custom movement logic due to their method of control (ie the game's input interface, and the packet handling for MP). I am not sure this would even *work*.

**Comment by CraftedMods** [comment]
Can't say anything about that, I never worked with player movement extensively. I'll play around with the code at a private clone of the repo, to get some information. Please notify we when you came to the conclusion whether you want to implement something like that or not.

**Comment by ReikaKalseki** [comment]
Players are now bounced off.
