### ISSUE TITLE
[RoC/EletriCraft] [Suggestion] Energy door.

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2136]
This obviously isn't a high priority.
I have noticed no mods have a "energy door", 
I guess the only reason I recommend this is, well, its a energy door.

I guess if you wanted it be more "advanced" it could "open/close" (turn on/off)
when players get near it, if you want it to (gui thingy, maybe even change its size/shape in the gui (maybe similar to how you setup the boring machines radius/shape)).

Maybe add a cool sound when it turns on/off.

Probably make it cost a lot of power like the light bridge (yay more things to pump reactor power into)

(On a "unrelated" note: are the puzzle structure shield door things obtainable?)

**Comment by ReikaKalseki** [comment]
ChromatiCraft's Ethereal Barrier is very close to this.

> are the puzzle structure shield door things obtainable?)

Which things?

**Comment by ReikaKalseki** [comment]
ChromatiCraft's Ethereal Barrier is very close to this.

> are the puzzle structure shield door things obtainable?)

Which things?
