### ISSUE TITLE
Chromaticraft Random progression resets.

### ISSUE THREAD

**Issue by Azzezima** [ReikaKalseki/Reika_Mods_Issues#2139]
On our server something's causing resets on chromaticraft progression and also the thing that checks for the reika books. So at random times and almost always on a relog the progressions get's reset and 3 new books spawn in our inventory.

**Comment by Azzezima** [comment]
Found out it's Advent of Ascension 1.1.3
Fixed it by removing the mod.

**Comment by ReikaKalseki** [comment]
#1852
