### ISSUE TITLE
[FR] Electrolyser Custom Recipe System Support

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2142]
Add the ability to make custom recipes for the electrolyser. Recipes would include fluid+item -> fluid+fluid, and any smaller subset of those inputs and outputs. Possibility of electrolysis with a solvent that does not get used, which in other terms means an option for whether the fluid input is used or not.

**Comment by ReikaKalseki** [comment]
Done.

Sample:

    {
    type = "test1"
    fluid_in = {
        type = "water"
        amount = 200
    }
    item_in = {
        is_catalyst = false
        items = {
            "minecraft:leaves*3"
            "rotarycraft_stack:silumin"
            "reactorcraft_stack:maxMagnet"
        }
    }
    fluid_out_up = {
        type = "rc lubricant"
        amount = 10
    }
    fluid_out_down = {
        type = "lava"
        amount = 50
    }
    temperature = 570
    }
