### ISSUE TITLE
Start the server and stuck at one location

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#2143]
The server did not crash, and no any error log, it was just stuck here.

> [20:23:43 INFO]: DRAGONAPI: Pre-initialized DRAGONAPI; preloaded 1/3 mods.

I waited for an hour and was still stuck here. No other Mod was installed, ony installed DragonAPI, Rotaycraft and Reactorcraft, use the Forge 1614 Server.

What should I do? Please help me, thanks.

**Comment by ghost** [comment]
I think it's network problem. My server redirected some IP, resulting in Mod not triggering a timeout. I would like to ask how to completely cut off / stop / shutdown the Mod trying to connect the network? Why checks for updates or other operations, force try networking? Can you add a configuration option to disconnect the mod all networks?

**Comment by ghost** [comment]
-DragonAPI_NoInternet
You know what, I love Reika very much.

**Comment by ReikaKalseki** [comment]
You realize that will break things, right? That is for when you are running completely without internet and otherwise cannot run the game at all.
