### ISSUE TITLE
[CC] Magical Alloy NEI Issues & Crash

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#2146]
When using NEI to view the recipe for one of the magical alloys, it will instead take you 1 page ahead, displaying the wrong recipe. For instance, if you press the view recipe button over a Chroma Alloy Ingot, it will instead redirect you to the Resonating Ingot recipe, which is 1 page ahead. This isn't much of a problem unless you try to look at Chromastone's recipe, in which case the game crashes.

My theory is that an array or something is 1 value higher than it should be, thus when it reaches the end (chromastone) there isn't anything higher than that so it crashes. The crash report is right here. https://pastebin.com/Eb34L39D

**Comment by ReikaKalseki** [comment]
I think this is a disagreement between list lengths, where one (smaller) list is filtered to only those recipes you have progression for, and the other is not. I also think I put a fix in for this for the next version.
