### ISSUE TITLE
Freeze During Startup

### ISSUE THREAD

**Issue by Thorinair** [ReikaKalseki/Reika_Mods_Issues#215]
For a few months (ever since I started playing with 1.7.10 versions of your mods), I had a very weird issue that would make starting up the game very troublesome. In 80% of cases or so (but not always), the startup of Minecraft will get randomly frozen/hangs. There is no error, no crash, nothing. The loading simply stops and the CPU relaxes back to 0% like it is done loading. It always happens at this point when it does:
![image](https://cloud.githubusercontent.com/assets/7534126/9580786/cca0e4f8-4ffb-11e5-96ab-78722c7ee6d2.png)

It is enough to have just DragonAPI and RotaryCraft installed, nothing else. However, when I took this screenshot and logs, I had the following installed (Version V8a of all mods):
DragonAPI
ChromatiCraft
ElectriCraft
ExpandedRedstone
ReactorCraft
RotaryCraft

Here is a full log: http://pastebin.com/kdcGShE6

I would tell you how to recreate the issue, but I don't know how. Issue is identical on both Java 7 and 8, and in all launchers I tried to use. Oddly enough, the last line that is listed is "Sound engine started", as if it tries to open the menu before finishing the loading procedure. None of my friends were able to get this same issue. The only fix I found so far is to keep trying again and again until I manage to get into the game.

**Comment by ReikaKalseki** [comment]
Allocate more memory, particularly PermGen.

**Comment by Thorinair** [comment]
Sadly, that doesn't help, already have 1024 min, 4096 max and 256 permgen. I just tried with 512 permgen, same results. A friend of mine is running it at 512 min, 4096 max and 256 permgen in a 100+ mod pack without any issues.

**Comment by ReikaKalseki** [comment]
Freezing in the middle of loading is a typical result of running out of memory. If adding more memory is not helping, you may have a deeper issue.

**Comment by Thorinair** [comment]
Note that this happens ONLY with DragonAPI + RotaryCraft or whatever, and doesn't happen with any other mod, even if I had hundreds of them. I already had memory issues before, and I know how they look like (usually an error that it is out of memory). Also note that the game doesn't go not responding, it simply just stops loading, as if it is done.

EDIT: If it helps anything, when I close the game by clicking on the Windows' close button, it returns an exit code of -805306369. Here is a log file of an instance with only DragonAPI and RotaryCraft installed: http://pastebin.com/KqLTQL49
Here, the last line seems to be "DragonAPI: Successfully applied WORLDRENDER ASM handler!".

**Comment by Xavion3** [comment]
It's [a memory issue](http://hopper.minecraft.net/help/exit-code/code-805306369/), it may be related to something that DragonAPI or RotaryCraft are doing that cause it to appear unusually often but it's almost certainly related to memory running out.

**Comment by ReikaKalseki** [comment]
I do not have this issue in my game, and have no idea what I would be doing to trigger it. RC is not exactly memory-heavy. CC, sure, but RC?

**Comment by kolatra** [comment]
Looking at the initial log, how long did you wait before killing it? Because it doesn't look like it took long to get from launch to where it apparently froze.

**Comment by Thorinair** [comment]
I once waited over half an hour before killing it. After that point, nothing happens and the game sits in idle. And yeah, I do agree that DragonAPI + RotaryCraft aren't memory heavy and I have no clue how they would be causing any memory issues.

EDIT: I am able to make it freeze with literally only DragonAPI installed. http://pastebin.com/GhGNX2ZE

**Comment by ReikaKalseki** [comment]
DragonAPI has no content...

**Comment by Thorinair** [comment]
Indeed, maybe it is somehow related with the ASM handlers? It appears to generally be the last sign of breath from the mod before the freeze.

**Comment by ReikaKalseki** [comment]
ASM does not cost any significant amount of memory.

**Comment by Thorinair** [comment]
Maybe it does something in such a way that, under special situations, it makes the memory shoot upwards instantly, or at least makes Java think that this is what happens.

**Comment by ReikaKalseki** [comment]
No, it does not.

**Comment by Thorinair** [comment]
Honestly, I have no clue what might be happening, but something is obviously different than any other mod, as DragonAPI is the only mod that brings this issue to surface.

**Comment by ReikaKalseki** [comment]
Noone else has this issue (at least noone has reported it), and on top of that there is no reasonable way ASMing a class could cause the memory usage to skyrocket.

**Comment by TomeWyrm** [comment]
Couldn't  @Thorinair just run jprofiler or something to try and figure this out? There are fancy debugging tools for java that I know nothing about, one of them should be able to give relevant information.

**Comment by ReikaKalseki** [comment]
I do know it is possible; @zmaster587 did once trace almost 2GB of RAM to an AE OreDict cache.

**Comment by Thorinair** [comment]
I installed jprofiler and successfully connected it to the Minecraft instance, however, I am not sure what should I be looking for and what would actually be useful for this issue.

The only odd thing I am noticing is that when Minecraft gets frozen, the count of char[]'s keeps growing relatively quickly, around a thousand per second, and Strings around 400 per second. If Minecraft starts successfully, this doesn't seem to be the case, and both move up/down by 1 instance count or so. These measurements were taken with only DragonAPI installed.

Frozen startup:
![image](https://cloud.githubusercontent.com/assets/7534126/9653572/7dde208a-5224-11e5-9898-ebab01a4c83b.png)

Successful startup:
![image](https://cloud.githubusercontent.com/assets/7534126/9653629/091b6a18-5225-11e5-9a0c-280ecd7ca992.png)

If you guys have any idea what I should look for, please tell me!

**Comment by Thorinair** [comment]
Posting this as a separate comment because I found the issue and solution, or at least, a user workaround. It seems that there is some sort of a clash with the Forge splash screen, similar to issue #132. The difference is that I don't even crash. Disabling the splash screen fixes the issue. 

Looking at the threads and calls, I came to believe that it happens when calling WORLDRENDER ASM handler if you are doing some sort of calls to org.lwjgl, because it is not that good at handling two threads at the same time (the splash screen also calls it to render the progress bar on a separate thread). Nevertheless, I don't know how your code works, so I won't be a smartass.

![image](https://cloud.githubusercontent.com/assets/7534126/9658945/70414654-524d-11e5-8085-231e69e91783.png)

**Comment by ReikaKalseki** [comment]
char[] is so high because java Strings are internally char[].

And no, the ASM has no render code in it. ASM is class editing, not execution. All I do is add a function call.
https://github.com/ReikaKalseki/DragonAPI/blob/master/ASM/DragonAPIClassTransfomer.java#L515

**Comment by Bogdan-G** [comment]
@Thorinair a typical conflict of mods and splash loading screen Forge. Only code problem. Screen Forge trying to learn what makes a particular mod when it fails, it may happen in your case.

**Comment by ReikaKalseki** [comment]
> @Thorinair a typical conflict of mods and splash loading screen Forge. Only code problem. Screen Forge trying to learn what makes a particular mod when it fails, it may happen in your case.

????

**Comment by Bogdan-G** [comment]
@ReikaKalseki the problem is the compatibility mod(s) and loading screen forge. Starting a game is suspended because it was not able to track the forge action correctly and mod show on the screen.
