### ISSUE TITLE
Player Imitation Core - what does it even do?

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#2150]
The documentation for the Player Imitation Core is a bit lacking, so I tried some experimentation and could not figure out its purpose for the life of me. I tried putting it near some Zambarau potion crystals because the book (and a previous bug report) hinted that it would do something to automate it but nothing happened when placed in the area or adjacent to the crystals while I was standing on the core. I put the core over a chroma collector, nothing happened. I tried with a T1 and a T3 one, but to no avail. After a bit of further testing, I also figured out that the core doesn't load chunks or activate mob spawners, so what is its purpose? Is there something I'm missing?

**Comment by ReikaKalseki** [comment]
Is it missing energy?

**Comment by Mettymagic** [comment]
None of the cores require energy from the ambient lumen distributors with the default config, so no. Just tested in creative with a very simple set-up and nothing seemed to happen. https://i.imgur.com/wL7EKUN.png

**Comment by ReikaKalseki** [comment]
That is supposed to work, and *was* working for me in February...

**Comment by Kobra331** [comment]
At the moment it works only if the imitation core is afaik ABOVE the Zambarau crystal. All other adjacent Crystals are ignored. You cannot use the core to extract the experience into the chroma collector.

**Comment by ReikaKalseki** [comment]
> At the moment it works only if the imitation core is afaik ABOVE the Zambarau crystal. All other adjacent Crystals are ignored. You cannot use the core to extract the experience into the chroma collector.

Both of these are wrong.

But the public version might have the "adjacency cores ignore some sides" issue I fixed in January.

**Comment by Kobra331** [comment]
to the "adjacency cores ignore some sides" issue you are right. I tested it today on my server with the latest Public version.
On latest Dragon realms it works.

But you cannot use the Chroma collector on it:
https://cdn.discordapp.com/attachments/436609255575912460/612810477613088778/2019-08-19_02.45.25.png

https://cdn.discordapp.com/attachments/436609255575912460/612810500111204377/2019-08-19_02.45.35.png

i tried it on the other sides too. It isn't working for me.

**Comment by ReikaKalseki** [comment]
So I forgot to register the collector effect....
