### ISSUE TITLE
Repeater networks keep breaking [CrC]

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#2151]
My repeater networks stop working whenever I join my world.

For example:

Yesterday, my Kitrino repeater network was working. It was transferring lumens with no problem.

But today, the network stopped transferring Kitrino lumens. Sometimes I have to remove the repeater block, and replace it again. Sometimes I need to get the first repeater closer to the pylon. And sometimes... I need to relocate the repeaters. Just to get it to work. And it does this to all kinds of repeaters. Not just the Kitrino repeaters.

It happens everytime I log out of my world. 

It's not a Multiplayer server, so nobody's messing up the repeaters just to f*** around with me.

**Comment by OvermindDL1** [comment]
It's been a long time bug, there is an open issue about it somewhere here I think (at least I don't think it's closed).  I've experienced every time I've tried ChC.

**Comment by ReikaKalseki** [comment]
#1100
