### ISSUE TITLE
Alloying tank freezes up when automated

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#2152]
I have a simple set-up involving the alloying tank and a chest with a pneumatic item pump piping items into the tank and a fluid link anchor refilling the chroma. When I throw a batch of ingredients into the chest, they all enter the tank and it starts to craft the alloys. However, it seems to have a short-term memory because after 2 or 3 operations it just freezes despite having all the necessary components. Breaking the alloying tank base drops all the ingredients, so it's not a problem of it voiding the ingredients. Adding the base of the alloy (iron or gold, usually) one-by-one seems to solve this problem but I'm not sure if this behavior is intentional.

**Comment by ReikaKalseki** [comment]
I changed how it works recently; try again in the next release.
