### ISSUE TITLE
Crash on startup - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by SKProCH** [ReikaKalseki/Reika_Mods_Issues#2155]
Crash on startup.
Crashlog: https://pastebin.com/y1RvSUrE
Latest.log: https://pastebin.com/LS9YP18q
[fml-client-1.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/3488634/fml-client-1.log)

**Comment by ReikaKalseki** [comment]
This makes no sense, especially given that noone else is reporting it...

**Comment by SKProCH** [comment]
I solved this problem by reinstalling the assembly several times. In the process, the computer also rebooted. Some of this helped.

**Comment by ReikaKalseki** [comment]
WTF...
