### ISSUE TITLE
[ReC] Ruthenium-106 seems to be recognised as long-lived Isotope

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#2156]
As the Title Says Ruthenium-106 can not be automaticly transfered into Spent Fuel Containers and lands instead in Nuclear Waste Disposal Drums wich also dont overheat. Which is probably not intended because 373,6 d < 6y.

**Comment by ReikaKalseki** [comment]
In MC, it is; a year is only 6 months, each of which are only 8 days (as per the moon cycle).

**Comment by ghost** [comment]
It than seems, that there is an inconsistency with your internal time conversion, because than would Cesium-134, with it's half life of about 2 years so nearly twice that of Ruthenium-106 also be an long lived isotope and apperently it is'nt. So the internal half life of Ruthenium-106 should be ![img](http://www.sciweavers.org/tex2img.php?eq=%288%20d%2A6%29%2A%20%5Cfrac%7B373%2C6%20d%7D%7B365%2C24%20d%7D%20%3D%2049%2C09%20d&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0)

**Comment by ReikaKalseki** [comment]
There *is* a conversion issue, but it is not what you said; the half-lives are coded in according to their real world values, *using the units specified*. So while a half life of 320 days is less than 1.2 years in the real world, coded into MC that is 320 days and 1.2x6x8 = 57 days.

This is unavoidable without converting all of them, which I will not do, as I want to keep the recognizable half-life values.
