### ISSUE TITLE
[RotaryCraft] Ethanol Description Outdated

### ISSUE THREAD

**Issue by WiduX** [ReikaKalseki/Reika_Mods_Issues#2158]
Pretty minor issue, the page for the Fermenter never got updated in the handbook when the Ethanol production process got changed.

It says "To make sludge, put yeast on top and plant matter on the bottom. Put that in a furnace, and you will get crystals of ethanol."

This is no longer accurate since a centrifuge is now required before it can be put into a furnace.

**Comment by ReikaKalseki** [comment]
Done.
