### ISSUE TITLE
[Suggestion] Lack of CC documentation on a few entries

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#2159]
Just reached the endgame dimension in chromaticraft and it's absolutely amazing! CC is one of my favorite mods but too many times have I had to google to even understand how to use a block or item because the documentation is either too vague or simply doesn't include crucial information. I understand the mod has a keen sense of discovery in experimenting what certain tools do, but some cases are just too vague. Here are the ones I've had problems with, anyways:

Alloying Tank - nowhere in the book does it say the tank is a multiblock that requires shielded glass, or that shielded glass is only obtainable from Ocean Temples. I get that the book refers to a "shielded glass tank" and needing a way to fit more than one block of fluid but that's a pretty far stretch. A description that more clearly states "Perhaps ancient glass found in an underwater temple could be placed on top to expand the tank's storage." or something could fix this.

Focus Crystals - the book doesn't detail where exactly these need to be placed within the casting structures. A diagram or description is needed, or at least something detailing that a beam will form when successfully placed would be nice, it literally took me an hour searching through google to find where to place them haha.

Coalescence Orchid - the book should detail that combining liquid chroma with a hot liquid could prove useful or something, I had no idea it could create crystalline stone until I found a random forum thread. A feature like this shouldn't be this hidden imo.

Subterranean Route Finder - apparently you said there was a second mode to this item that lets you find the deepest point in a cave but I can't for the love of me figure out how to use this.

Abilities - there should be an entry in the introduction section that explains how abilities work, how you can give certain abilities different charge levels and how they require a certain amount of lumens in your elemental manipulator to function. Not the biggest deal but it was pretty alien at the start.

Applied Hotbars - it should be explained that you have to have the ability active and right-click the controller with an elemental manipulator. The book doesn't really describe what the ability does exactly, it should explain that it automatically replaces blocks and takes extra items from your hotbar.

Item Inserter - the GUI is very alien, and while I did eventually figure it out the utility on this block is amazing but a lot of people are turned off by how confusing it is to use. Explaining how the lines correlate to the slot in the book could solve this.

Warp Glass - it should be explained that it can be linked both ways. Not much else to this one, just a QoL addition to the book.

The final ones are nearly nitpicks but I still thought I should include them here.

**Comment by ReikaKalseki** [comment]
> "Perhaps ancient glass found in an underwater temple could be placed on top to expand the tank's storage."

That is ridiculously direct and specific.

> Focus Crystals - the book doesn't detail where exactly these need to be placed within the casting structures

This is valid, but see below.

> Coalescence Orchid - the book should detail that combining liquid chroma with a hot liquid could prove useful or something,

This is not a required feature to progress, and not the intended main method of producing crystalline stone.

> Subterranean Route Finder - apparently you said there was a second mode to this item that lets you find the deepest point in a cave but I can't for the love of me figure out how to use this.

Items have three ways to use them; you should already know this...

> Abilities - there should be an entry in the introduction section that explains how abilities work, how you can give certain abilities different charge levels and how they require a certain amount of lumens in your elemental manipulator to function. Not the biggest deal but it was pretty alien at the start.

> Applied Hotbars - it should be explained that you have to have the ability active and right-click the controller with an elemental manipulator. The book doesn't really describe what the ability does exactly, it should explain that it automatically replaces blocks and takes extra items from your hotbar.

Both of these are valid.

> Item Inserter - the GUI is very alien, and while I did eventually figure it out the utility on this block is amazing but a lot of people are turned off by how confusing it is to use. Explaining how the lines correlate to the slot in the book could solve this.

Conceptually valid, but see below.

> Warp Glass - it should be explained that it can be linked both ways. Not much else to this one, just a QoL addition to the book.

I fail to see why that needs to be explained, why a player would ever assume otherwise.



Now, some of your suggestions run into a problem: The CC lexicon has an explicit policy of NOT mentioning "out of universe" concepts like mods, GUIs, or clicking. This makes explaining how to use a GUI, or what the process of activating an ability, impossible to explain directly.

**Comment by Mettymagic** [comment]
Thanks for the response! I respect that the documentation is stylized to not be direct but there needs to be some sort of compromise to prevent unneeded frustration or confusion. 

For the Subterranean Route Finder, I think the book should at least mention its other mode, and from there it's self-explanatory. Everything else I agree that it shouldn't be too direct, and that might have just been me being a bit dumb haha. For the Item Inserter though, for example, the GUI itself could be cleaned up a bit, like giving the 6 slots a different color and each of the ticks that color to let the player understand that the ticks link to a slot.

**Comment by ReikaKalseki** [comment]
> For the Item Inserter though, for example, the GUI itself could be cleaned up a bit, like giving the 6 slots a different color and each of the ticks that color to let the player understand that the ticks link to a slot.

This I can look into.

**Comment by Barhandar** [comment]
>That is ridiculously direct and specific.

Especially since ocean temple is no longer the only structure with the glass.
>This is not a required feature to progress, and not the intended main method of producing crystalline stone.

Reika. It produces _so much more_ than the other, explicitly shown method (crafting with shards) that yes, it is in fact the main method of producing crystalline stone for anyone who knows about it, however unintended. Even if it didn't, chroma and lava are effectively free, while shards at that point of progression are not.  
But yes, that feature isn't actually necessary for progression and fits within the general, er, veil of mystery Chroma has. At most state that Orchid can produce more than just cobblestone, if it doesn't already.

**Comment by ReikaKalseki** [comment]
> At most state that Orchid can produce more than just cobblestone, if it doesn't already.

I think it does say that.

**Comment by ReikaKalseki** [comment]
![https://i.imgur.com/2sje9IO.png](https://i.imgur.com/2sje9IO.png)
![https://i.imgur.com/wL6bK30.png](https://i.imgur.com/wL6bK30.png)

I also added some extra info to Applied Hotbars.


The alloying tank and focus crystal issues have not had a viable solution envisioned thus far. Additionally, as of the next version, focus crystals will be valid on more than just the casting table, making a render of "where to put them" even more difficult to imagine.

**Comment by ReikaKalseki** [comment]
I devised a way:

![https://i.imgur.com/gSwRRmG.png](https://i.imgur.com/gSwRRmG.png)
![https://i.imgur.com/bWaf9xe.png](https://i.imgur.com/bWaf9xe.png)
![https://i.imgur.com/fQO0QNd.png](https://i.imgur.com/fQO0QNd.png)

**Comment by ReikaKalseki** [comment]
Has there been anything not yet addressed?

**Comment by Mettymagic** [comment]
The new solutions are amazing! I love the new Item Inserter GUI and the particles in the altar are super helpful. The particles are a great idea, maybe the Alloying Tank could have a similar solution and have liquid spewing particles 2 blocks above it to convey the idea that something needs to contain it. Great job, man!
