### ISSUE TITLE
DragonAPI v8b crashes when loading world

### ISSUE THREAD

**Issue by mystise** [ReikaKalseki/Reika_Mods_Issues#216]
https://gist.github.com/adudney/8ce386153ebd338dba8b

This is a creative flatland world, created with DragonAPI as the only installed mod. This happens whenever the world is loaded.

Mods:
MC 1.7.10
Forge 10.13.4.1448
DragonAPI v8b

**Comment by Optimoos** [comment]
This appears to be the error that was supposed to be fixed in DragonAPI V8b according to the changelogs, but I'm also seeing the same crash.

https://gist.github.com/Optimoos/e4f5298bae2d99540afa

**Comment by ReikaKalseki** [comment]
Use v8a for now.

**Comment by quedral** [comment]
same cause of crash on world load. i am linking the log for informational purposes hope it helps.
http://pastebin.com/fXCG1iSN

reverted back to 8a as suggested.

**Comment by ReikaKalseki** [comment]
Fixed in v8c.
