### ISSUE TITLE
[CC] Collective Aura sound breaks my ears

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#2160]
The sound repeats itself too often it seems, and makes using the ability have the additional cost of making my ears bleed. It's way louder than everything else in the mod, so either a volume decrease, a decrease in the frequency of the sound or a config to change the volume of CC sounds would be nice.

**Comment by ReikaKalseki** [comment]
It plays the sound with some overlap to ensure smooth looping, but it does not make sense that it would be "louder than everything else in the mod"; that sound file is used elsewhere, and the playback volume is **0.2**, compared to the typical 1.

**Comment by ReikaKalseki** [comment]
OK, I tweaked it to further prevent sound stacking.
