### ISSUE TITLE
[Suggestion] [RC] Sprinklers supplied with fuel spray fire

### ISSUE THREAD

**Issue by ReactivePlatypus** [ReikaKalseki/Reika_Mods_Issues#2161]
Somewhat inspired by Immersive Engineering's chemical thrower, together with the damaging effect of ground sprinklers - A new feature of sprinklers where supplying them with liquid ethanol or jet fuel (or potentially any highly combustible fluid: BC fuel, fire water, etc.) instead of water turns them into automatic flamethrowers for base defense purposes. Both sprinkler types would require some sort of upgrade to function this way, as they would realistically need some way of lighting the fluid.

**Comment by ReikaKalseki** [comment]
No, this is neither useful nor sensible. And somewhat redundant with the flame turret.
