### ISSUE TITLE
[CC] Lumen Fence still deals damage after drained of power

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#2162]
I powered a lumen fence by placing a relay next to it until it activated, then took the relay away to test it out. When the internal storage of the Lumen Fence Emitter completely drained, the fence visually disappeared but where the fence would be still repels and damages mobs. I'm assuming this isn't intended because it means that the upkeep isn't necessary.

**Comment by Mettymagic** [comment]
Edit: it seems like the fence doesn't drain anything at all. I linked one up to a power source and the visual fence wasn't there yet it still worked. It seems like the issue is a bit bigger, being that the fence acts like it's there even though it isn't draining power or is visually there.

Again, this could be wrong but I'll look into it as I play.

**Comment by ReikaKalseki** [comment]
I just looked at the code; Its energy drain is on action, not over time, and it *does* check for having sufficient energy.

**Comment by Mettymagic** [comment]
Just did a bit more testing, I can't seem to reproduce it so I'm either going to write it off as a mistake on my part or some obscure cross-mod bug that doesn't matter. But for some reason the fence can just turn invisible, so there's that. Not sure if it's intentional or not.

**Comment by ReikaKalseki** [comment]
Under what conditions?

**Comment by Mettymagic** [comment]
Going to test a few things. Using a dedicated server, will edit this post as I test.`

EDIT 1: A friend that just joined the server said he couldn't see the fence. Going to try and reproduce on my own.
EDIT 2: Found the problem: restarting a dedicated server make the fence invisible. Right-clicking to redo the border fixes this. Weird.

Picture of my simple set-up if it would help: https://i.imgur.com/b4WC6uj.png

**Comment by ReikaKalseki** [comment]
Desync, perhaps...

**Comment by ReikaKalseki** [comment]
Hopefully fixed.
