### ISSUE TITLE
[CC, RoC] Fix spelling errors

### ISSUE THREAD

**Issue by truenachtara** [ReikaKalseki/Reika_Mods_Issues#2163]
RotaryCraft Handbook, Ground Sprinkler page: "...variety of the overhea**t** sprinkler..."

Chromaticraft: Data tower, the highlighted letter is incorrect: 
![image](https://user-images.githubusercontent.com/16340367/63047783-bdcbc580-be9a-11e9-8694-aa6c87f47878.png)

**Comment by ReikaKalseki** [comment]
Linking to #2029

**Comment by ReikaKalseki** [comment]
And that letter is NOT incorrect.

**Comment by Barhandar** [comment]
That's the UK spelling, the rest of the mod uses US spelling.

**Comment by OvermindDL1** [comment]
> That's the UK spelling, the rest of the mod uses US spelling.

> And that letter is NOT incorrect.

Soooo, it's the rest of the mod that's spelled incorrect then?  ^.^

**Comment by ReikaKalseki** [comment]
`That's the UK spelling, the rest of the mod uses US spelling.` The *entire* mod uses Canadian spelling, which is a hybrid of both.
