### ISSUE TITLE
[CC] Endgame Ritual fragments discovered before you can actually make them 

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#2165]
After obtaining the Unusual Structures progression, rituals such as the Location Warp, Passive Draw, Piercing Vision and Matter Dissolution appear before you are actually able to perform the ritual in the enhanced ritual altar. Not the biggest problem but just a bit confusing, I cheated in all progression in a single-player to test and eventually the rituals unlock so there must be a desync between when the fragments are given and when the progression unlocks it.

**Comment by ReikaKalseki** [comment]
This is not a desync; There is another requirement you are missing. That said, some indication is a good idea.

**Comment by Mettymagic** [comment]
Oh haha, I just reached this point and was confused by what happened, my bad.

**Comment by ReikaKalseki** [comment]
OK, these fragments will no longer appear too early.
