### ISSUE TITLE
[CC] Tiny bug with particles in Locks puzzle

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#2166]
The most absolutely gamebreaking bug:

In the key/lock puzzle, when a Kijani (green) key is active, the opened gate displays orange particles instead of green ones.

Literally unplayable. /s

Edit: Lime shows as yellow as well. Just makes things a bit confusing in the later puzzles.

**Comment by ReikaKalseki** [comment]
THis is a desync, probably.

**Comment by ReikaKalseki** [comment]
I think this is now fixed.
