### ISSUE TITLE
Game crashing on load up

### ISSUE THREAD

**Issue by WanderingLily** [ReikaKalseki/Reika_Mods_Issues#2167]
[Crash Log](https://pastebin.com/mG0JPNRi)

Hi there, I recently installed Nuts and Bolts looking to play, but I keep crashing on start up. I've tried reinstalling, updating java, trying different java arguments (not sure if that would even help) and I'm still crashing like this every time.

**Comment by WanderingLily** [comment]
The modpack does load up, however, when I remove ChromaticCraft, ReactorCraft, ElectriCraft, RotaryCraft, and DragonAPI.

**Comment by AshIndigo** [comment]
Add -Dfile.encoding=utf-8 to your jvm args and that should fix the crash

**Comment by WanderingLily** [comment]
> -Dfile.encoding=utf-8

Thank you so, so much. This fixed it!

**Comment by ReikaKalseki** [comment]
#2021 #2065 #2105 #2112 #2137
