### ISSUE TITLE
[CC] Either a desync with the lexicon structure keys or it's just confusing

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#2168]
The pictures in the Structure Keys puzzles don't correlate to the puzzle that color was. For instance, I completed the Zambarau puzzle (lumen burst mirrors) and it shows up as one of the mazes. All of the puzzle icons are screwed up this way, with no rhyme or reason. Even if two colors had the same puzzle, they have different images. Is there just something I'm missing here? I tried using the code in the puzzle resembling the picture but that didn't work. Just wanted to report in case it's a bug because there's absolutely nothing on the internet showing their keys so I don't know if this is the case or not haha, if this is intentional please close this report.

**Comment by ReikaKalseki** [comment]
I believe I fixed this with some tweaks.
