### ISSUE TITLE
Turbine Gemerator limited to 1.67GW

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#2169]
I connected a Turbine Generator running in ELC mode to a HiP Turbine which produced 8.59 GW (so the maximum) and noticed that the Turbine Generator was only outputting 1.67 GW so 6.92 GW are lost. I don't know if thats intended because i was unable to find an obvious limitation in the Code and in the ReC Book is also none mentitoned, if this is intended i would suggest adding a note in the Handbook and also adding an upgraded Version of the Turbine Generator (maybe using a Rotor upgraded with Bedrock to withstand the high stresses), because this limitation renders the HiP Turbine useless for me.

**Comment by truenachtara** [comment]
![image](https://user-images.githubusercontent.com/16340367/63218730-4f029c80-c126-11e9-839a-ecc0209fee1d.png)
Confirmed that this is the current behavior.

**Comment by ReikaKalseki** [comment]
Does this only happen in ElC mode?

**Comment by ghost** [comment]
In RF mode it produces 1.651.904,985 RF and 1 RF was 520W so it uses 8,589GW so it seems to be only in ElC mode.

**Comment by ReikaKalseki** [comment]
Strange...

**Comment by ReikaKalseki** [comment]
Having looked at this, it does not make sense; yes, the generator calls "clampTorque", but that explicitly has an exception for HP turbines:


	public static int clampTorque(TileEntityTurbineCore te) {
		return te instanceof TileEntityHiPTurbine ? te.getTorque() : Math.min(te.getTorque(), te.isAmmonia() ? MAXTORQUE_AMMONIA : MAXTORQUE);
	}

**Comment by ReikaKalseki** [comment]
So it turns out that code never made it to release, and it *has* been fixed.
