### ISSUE TITLE
[ElC] EU Splitter has erroneous logic and only doesn't explode with IC2E because IC2E does not have overvoltage explosions in 1.7.10

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#2170]
https://github.com/ReikaKalseki/ElectriCraft/blob/master/TileEntities/ModInterface/TileEntityEUSplitter.java#L80-L82

This is returning null/0 before input. It doesn't have a chance to process the input and hence update the input tiering because it explodes (or is supposed to explode), since tier 0 is 8 EU/p.

It should probably be returning maximum possible value because input tier isn't really relevant to this at all, it's not a transformer than goes 4X-1X; only the EU in is relevant for determining tier out, or rather, packet size.

**Comment by DracoScythem** [comment]
Additional information:

When dealing with IC2 Classic, the returned value should be 13, which is the highest "safe to use" tier with its internal logic and equates to 536870912 EU/t.

For IC2E, a value of Integer.MAX_VALUE marks any EnergySink as a "dynamic sink", meanaing it will be considered of the same tier as the highest source of the local e-net. This is presumably the approach expected by the IC2E api.

**Comment by ReikaKalseki** [comment]
Done.
