### ISSUE TITLE
[Suggestion] [ChC] Equipable powerup/badge system

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2174]
Now, I know this will likely overlap a bit with some of the infusion abilities, I haven't unlocked all of those yet so I'm not sure how much. This is just a base to work with.

The base idea is a system like the Badges in Paper Mario. Everlasting Abilities is the closest I've seen, and while it's good, it's 1.12.2 only, it's limited to existing potion effects, and it's only really purely positive for the player. No negatives in exchange for greater power. Plus, you can just stack all the good stuff to the sky.

Here's how I imagine such a system could work. A UI that has a number of slots in it, perhaps tied to progression. Certain mandatory progression points (getting all colors, casting table upgrades, proxima?) would unlock a new slot for a badge to go in, up to a maximum number. A lot of the badges could actually work pretty well translated to Minecraft, I feel. And either they could have a small passive Lumen cost while equipped, or just use that lumen color to craft. Some should be limited to finding as loot, or maybe villager trades. Only a small amount should be craftable.

HP Plus, similar to Absorption. Increases max HP.
Happy Heart, similar to regeneration, ticks less often but lasts as long as the badge is worn.
P-Up D-Down and P-Down D-Up. Apply a multiplier to both incoming and outgoing damage, of 1.5 and 0.5 respectively.
Feeling Fine, nullify the effects of poison and nausea (not wither, probably). Probably uses Tahara.
Power Plus and Defend Plus would be a straight stat increase, but should be more expensive in some way than the ones with the downsides.
HP Drain would decrease damage output in exchange for a small amount of lifesteal.
Damage Dodge for increased defense while blocking in some way.

And of course, let's not forget the danger badges. Danger could be something like 2-3 hearts left, Peril would be half a heart. Mega Rush would be like a few levels of Power Plus, but only active at half a heart left. Last Stand has obvious utility, halving (or severely reducing) damage when very low on health. Not sure if Close Call/Pretty Lucky are possible or not (dodge chance).

Ice Power to increase damage against fire-based enemies, and Fire Shield to reduce incoming fire damage (could also just combine them into one Ice Power badge).

Double Pain badge for those masochists out there.

Return Postage, a thorns-esque effect but the damage reflected is based on incoming damage, and Zap Tap, a weak thorns effect but electric-themed, which could have some interesting side effects...

The main limiting factor to keep this from getting too out of hand, would probably have to be something like only one of each badge can be equipped at a time. So, you could stack P-Up D-Down and Power Plus, but not two Power Pluses.

And of course, Attack FX badges to have a sound effect when attacking, if that's possible.

As a balancing feature, perhaps only include the badges with downsides or the conditional ones.

**Comment by ReikaKalseki** [comment]
No. And this is not the place for suggestions.
