### ISSUE TITLE
[ChC] Entry-level pages in Recovery tab by default

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2175]
The Crystals and Pylons pages are in the recovery tab right from the start, or very shortly thereafter, but I have never lost a page. Seems to me that they should either be in the book already, or reveal themselves as fragments normally.

If this is intended to be an introduction to the Recovery Tab, then something should definitely point that way, as I stumbled on it purely by coincidence. I wouldn't normally have checked it unless I actually lost something.

![2019-08-24_21 19 15](https://user-images.githubusercontent.com/6917535/63645545-7f61b200-c6b5-11e9-9dc5-2636e1cc8604.png)

**Comment by ReikaKalseki** [comment]
I fail to see how those would appear there if you have never gotten a fragment.

**Comment by Shahelion** [comment]
I have no idea. A number of other fragments revealed themselves, but not those ones.

**Comment by ReikaKalseki** [comment]
Do you have "auxiliary fragment acquisition" on?

**Comment by Shahelion** [comment]
Looks like I do. Is this what that does?

**Comment by ReikaKalseki** [comment]
No, but you were granted fragments without being given the items, hence why they ended up in recovery.

**Comment by ReikaKalseki** [comment]
Now that option will also give you the items.
