### ISSUE TITLE
[CHC] ME Item Distributor item dupe

### ISSUE THREAD

**Issue by AlexanderADM** [ReikaKalseki/Reika_Mods_Issues#2177]
The ME Item Distributor causes an item dupe based on the number of items set, up to a maximum of 64 at once. the item in the first field is duplicated up to a full stack when at at least 1 is present within a network.

Testing on various items shows it will duplicate any stackable item from any mod also copying the item exactly. Tested on various CHC,RC,AE2,EIO,Vanilla, etc items.

For any amount of items entering the system it will be extracted by the item distributor to it's attached storage raising the item count to a full stack as long as the number field is set to above 64 items. If set to 64 items it will increase the stack but only up to 63 items while still duplicating the items if inserted one at a time.

GIF/Video of the duplication can be found here:
https://gfycat.com/DefensiveWiltedKoi
A simple AE network is enough to get this duplication to work.

Issue present on Chromaticraft version 22d, on the Nuts and Bolts modpack.

**Comment by ReikaKalseki** [comment]
This issue is in DragonAPI's ME System handling, not the Item Distributor; it should also be fixed.
