### ISSUE TITLE
[RoC]Block filler replaces blocks it shouldn't.

### ISSUE THREAD

**Issue by AssasinAsha** [ReikaKalseki/Reika_Mods_Issues#2178]
Hello everyone,

the block filler can replace bedrock, including the lowest layer.
This works even in ChC dimension, with obvious implications.
Further testing shows it replaces everything, including chests, furnaces, beacons as well as ChC worldgen structures (pylons, dungeons).
Worst part, it only takes a DC electric engine to work, at least when using dirt or glass.

Reproducing:
1. Grab a block filler, a DC electric engine, a lever and some dozen or two stacks of dirt, maybe some automation to feed the filler.
2. Make way to the bottom of the world, get to bedrock.
3. Slap the filler down, load with dirt, plug DC engine and lever, turn on.
4. Wait.
5. Dig down through dirt and fall to your doom.

Instance details:
1. Minecraft 1.7.10
2. Forge 10.13.4.1614
3. DragonAPI v22d
4. Rotarycraft v22d
No other mod present.

Cheers
Assasin_Asha

Edit:
Darn, finger slipped and hit enter while editing, please hold... Done! ish.

**Comment by ReikaKalseki** [comment]
I rewrote the block filler; try again in the next release.
