### ISSUE TITLE
[ChC] Crash While Generating a RainbowTree

### ISSUE THREAD

**Issue by Lonemind** [ReikaKalseki/Reika_Mods_Issues#2179]
While exploring and generating new chunks I received multiple crashes. After reloading it would be fine until I started generating new chunks in the same area, causing one of these crashes. The first crash log was more common than the second.

[crash-2019-09-01_15.50.51-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/3563968/crash-2019-09-01_15.50.51-server.txt)

[crash-2019-09-01_16.07.48-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/3563966/crash-2019-09-01_16.07.48-server.txt)

**Comment by OvermindDL1** [comment]
Same bug, my gut reaction is that one of the many installed mods with tree's have a bugged tree code.  You could try to disable the `Generate Mod Logs` option to see if that fixes it?

**Comment by Lonemind** [comment]
Ah! Now that you mention this I remember changing the config to not generate vanilla logs, only mod logs. I'll revert the change and try again in the same area. Hopefully I can find a place where a rainbow tree is called to generate.

**Comment by Lonemind** [comment]
It is either fixed or I was unable to find a place where the rainbow tree would generate. I'll close this for now. Thank you.
