### ISSUE TITLE
Cant make tinkers bedrock pick head

### ISSUE THREAD

**Issue by RoloEdits** [ReikaKalseki/Reika_Mods_Issues#218]
I seem to be able to make other parts just fine, but I cant seem to make the pickaxe head. I have not tried all the parts but if others are not able to be made then i'm guessing it a similar issue, if this is indeed an issue.

![2015-09-01_22 08 50](https://cloud.githubusercontent.com/assets/12489689/9623484/3e3143f6-50f6-11e5-9619-5e67c5c9fc9c.png)

**Comment by ljfa-ag** [comment]
This is intentional: Pickaxe, axe, shovel, sword and scythe heads are disabled. Use the regular RoC bedrock tools instead I guess.

**Comment by ReikaKalseki** [comment]
Correct. RC provides those tools natively, where they are more powerful.

A clarification: The mattock works (I think) but the lumber axe was disabled.

**Comment by ljfa-ag** [comment]
How can you make a mattock when you can't make axe and shovel head?

**Comment by RoloEdits** [comment]
OK, thanks for the clarification.

**Comment by ReikaKalseki** [comment]
> How can you make a mattock when you can't make axe and shovel head?

Hence the "I think". :P
