### ISSUE TITLE
[RoC] Turrets do not actually function anymore

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#2181]
For example, gatling turret only tracks enemy mob once after placement, and afterwards only if said mob is punched by me (it gives a small burst of shots and rotates slightly in the direction of the mob, then freezes again).

Also, (9x4+1)x64 reserve of bearings, per turret? _Seriously_?

**Comment by Aivech** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1099 has been open for three years now

**Comment by Barhandar** [comment]
That's fucking hilarious. Seems like turrets are one of the most unused features of Rotarycraft.
