### ISSUE TITLE
ChromatiCraft - RF Radiator sends power to Redstone Fluxducts.

### ISSUE THREAD

**Issue by waterlubber** [ReikaKalseki/Reika_Mods_Issues#2185]
The RF radiator sends "blobs" of power to TD "Redstone Energy Fluxducts" as well as EnderIO Vibrant Capacitor Banks. 

Screenshots:
(I don't have any screenshots of the vibrant banks, but they also cause the issue. I get very odd fluctuations in my power when this is occurring.) 
Apologies for the aneurysm-inducing FOV. I tried to get the whole setup in the screenshot.
![2019-09-17_21 11 16](https://user-images.githubusercontent.com/7517025/65095595-d6deff00-d98f-11e9-9199-7b92ef19cd2e.png)
![2019-09-17_21 11 21](https://user-images.githubusercontent.com/7517025/65095596-d6deff00-d98f-11e9-9f0b-8937cb9feb85.png)
![2019-09-17_21 11 24](https://user-images.githubusercontent.com/7517025/65095602-de060d00-d98f-11e9-8143-fa38378d5150.png)

**Comment by ReikaKalseki** [comment]
Fixed. Thank you regex hell...
