### ISSUE TITLE
Mana booster particles stuck

### ISSUE THREAD

**Issue by DevonX** [ReikaKalseki/Reika_Mods_Issues#2189]
Hi i am running the latest version of Chromaticraft and am having some issues with the mana booster particles being stuck. This builds up over time and eventually causes the client to lag.
![mana 1](https://user-images.githubusercontent.com/1227739/66240224-54c73800-e6fc-11e9-9607-0cb01a396618.png)
![mana 2](https://user-images.githubusercontent.com/1227739/66240225-54c73800-e6fc-11e9-9feb-e9b3577c9f92.png)

**Comment by ReikaKalseki** [comment]
Fixed.
