### ISSUE TITLE
java.lang.NullPointerException: Updating screen events

### ISSUE THREAD

**Issue by Tsyklop** [ReikaKalseki/Reika_Mods_Issues#219]
I tried to look up all possible craft LGP bucket of Pneumaticcraft and received a crash.

http://pastebin.com/3Nx7FNvg

**Comment by ReikaKalseki** [comment]
Fixed.

Oddly, this does not happen for me. What is LGP?

**Comment by Tsyklop** [comment]
@ReikaKalseki Fluid

**Comment by ReikaKalseki** [comment]
...

**Comment by Tsyklop** [comment]
@ReikaKalseki What???

**Comment by TomeWyrm** [comment]
@ReikaKalseki He means LPG. Light Petroleum Gas. Along with Kerosene, Gasoline, and... um... diesel? There's a 4th one and I don't remember the name and don't feel like researching at this precise moment. They're the new/upcoming method of obtaining plastic for pneumaticraft, instead of the seeds.

**Comment by ReikaKalseki** [comment]
> @ReikaKalseki What???

Because I asked what it was and you told me it was "fluid", which I already knew from this issue. That is like having a crash with some machine and saying "it's a block" when trying to explain it, or when you ask what a bedrock scythe is, I say "item".

**Comment by Tsyklop** [comment]
@ReikaKalseki Sorry.
