### ISSUE TITLE
Crash. NoClassDefFoundError: ic2/api/item/ElectricItem

### ISSUE THREAD

**Issue by rkane31174** [ReikaKalseki/Reika_Mods_Issues#2190]
[crash.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/3694918/crash.txt)

I had just finished digging a big hole at the bottom of the world and started placing empty nuclear waste storage drums when I was afflicted with radiation poisoning and the server crashed. I was wearing a full powersuit from Modular Powersuits. IC2 is not installed.

I think the dechargeItem function in the ReikaItemHelper class might have mistook my MUSE armor for IC2 armor and crashed because I don't have IC2.

**Comment by ReikaKalseki** [comment]
I thought MPS depended on IC2...

**Comment by rkane31174** [comment]
No, I don't think MPS requires IC2 to be installed. I'll try to reproduce this crash in SinglePlayer when I get home. I'll let you know how that goes.

**Comment by OvermindDL1** [comment]
MPS does not require IC2.

**Comment by rkane31174** [comment]
[crash-2019-10-07_18.21.01-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/3699823/crash-2019-10-07_18.21.01-server.txt)

I was able to reproduce this crash in single player

**Comment by rkane31174** [comment]
I have additional information if it will help. My MPS doesn't have any batteries in it and I power it with a Thermal Expansion redstone energy cell that I carry around. The powersuit has full energy shielding.

**Comment by ReikaKalseki** [comment]
I just double-checked my code; that line throwing an error is only called if the item implements `ic2.api.item.IElectricItem`. Which the MPS item must, and apparently does not stop doing so if the IC2 API is not present.

**Comment by rkane31174** [comment]
Okay, now I have a better idea of what's going on. Thanks for your help!
