### ISSUE TITLE
Poor lua block recipe documentation

### ISSUE THREAD

**Issue by pajrle** [ReikaKalseki/Reika_Mods_Issues#2191]
Hello, I would like to request some proper custom recipes documentation. Right now there is only your post from 2017 which contains only pictures so I cannot conveniently copypaste (XD) but also I cannot figure out how to use it for Chromaticraft because there is no info on required parameters and if I can lock recipes behind Chromaticraft progression like you can do with Thaumcraft via minetweaker. Can you please at least include some example files, like you have in loot tweaks github ?

**Comment by ReikaKalseki** [comment]
Yes, I can do that.

**Comment by voidsong-dragonfly** [comment]
If you need help with the RoC custom recipes right now, I can help you.

**Comment by pajrle** [comment]
Thanks @Silfryi but I  am intersted in CC recipes. Proper documentation would propably be appreciated by more people than me.

**Comment by ReikaKalseki** [comment]
Done.
