### ISSUE TITLE
[Chromaticraft] NullPointer Exception when mining Aura Node in Secret Burrow

### ISSUE THREAD

**Issue by TheNodop** [ReikaKalseki/Reika_Mods_Issues#2193]
The title says everything.
Here is the crash-log: https://pastebin.com/VjPCKM1q

**Comment by TheNodop** [comment]
I tried it again, this time I didn't use my bedrock pickaxe and it worked.
I would assume this happens because of silk touch/fortune, but that's just my guess.

**Comment by ReikaKalseki** [comment]
I put some debugging code in for the next version:

`throw new IllegalStateException("Block type "+c+" returned null ItemStack when silk touched!");`

**Comment by ReikaKalseki** [comment]
Continued in #2225.
