### ISSUE TITLE
(Reactorcraft) Crash when using second reactor remote

### ISSUE THREAD

**Issue by rkane31174** [ReikaKalseki/Reika_Mods_Issues#2194]
[crash-2019-10-13_10.26.48-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/3721851/crash-2019-10-13_10.26.48-server.txt)

The first remote I have works. I can open it without a problem. Some other mod does try to access its inventory, but thanks to you that doesn't crash the game.

The second remote, regardless of what controller it's linked to, crashes the game immediately. This can be easily be reproduced in any world, in any gamemode.

**Comment by ReikaKalseki** [comment]
That is the PacketC08 issue; it is not my doing.

#1936, #1423, #652, #590, #855, #161, #1358, #1474, #1488, #1565, #1871

**Comment by rkane31174** [comment]
In that case, I apologize for the inconvenience.
