### ISSUE TITLE
EIO Conduits can't pull liquid xp from Item Vaccum

### ISSUE THREAD

**Issue by thePalindrome** [ReikaKalseki/Reika_Mods_Issues#2196]
More or less what it says on the tin. They interact with reservoirs well enough, it's just the item vacuum that they don't like. Reading the code for that TE, I don't understand why they wouldn't, but it means I have to use liquid pipes placed underneath (which is a problem due to issue #2197  )

It's possible this may be an EIO bug, and TD or whatever wouldnt' have it, but since those mods aren't exactly working on their 1.7.10 ports, a fix might be needed on this side.

**Comment by ReikaKalseki** [comment]
Can other pipes work?

**Comment by thePalindrome** [comment]
Alright, I just tested with TD fluiducts, and those work (with the expected caveat of the servo)

As an additional point, the EIO fluid conduit *does* "connect" with the item vacuum, in case that's indicative of anything. From what I saw in the item vacuum, I'm not sure *why* EIO conduits aren't pulling from it, when they pull from reservoirs just fine

**Comment by ReikaKalseki** [comment]
That is very strange indeed.

**Comment by ReikaKalseki** [comment]
Looking at the code, I only have one guess:

The vacuum has code to prevent liquid drain that would equate to less than 1xp (since it stores the XP as a number, not a liquid); if anything only tries to pull out that tiny quantity, it will be rejected.

Maybe the EiO pipe makes many tiny draws, or does an initial 1mB "probative" draw?

**Comment by voidsong-dragonfly** [comment]
I think it does the latter. I saw that somewhere....

**Comment by ReikaKalseki** [comment]
Can you verify?

**Comment by voidsong-dragonfly** [comment]
Can't find it, sorry. It also may have been for a later version so disregard it.
