### ISSUE TITLE
RotaryCraft - Using Angular Transducer on empty pipe causes a crash

### ISSUE THREAD

**Issue by TDplai** [ReikaKalseki/Reika_Mods_Issues#2198]
Mods list: Forge 10.13.4.1558, DragonAPI V23a, Rotarycraft V23a

I have confirmed that Liquid, Valve, Bypass, Separation, Suction and Bedrock pipes all crash when empty and all pipes do not crash when full (unable to test Suction when full as I don't actually understand what it even is). Steam Pipes from ReactorCraft are fine (obviously that was tested with ReactorCraft installed). Tested in a completely empty Superflat world, all pipes tested at y=4 (if that makes any difference).

Here's the crash report: https://pastebin.com/vAcpcWsZ

Reproduction steps: Place any pipe except a Steam pipe, do not fill it with anything, right-click with Angular Transducer. The game will then crash.

Have confirmed it is not an issue with having a corrupt copy of the mod by checking the MD5 against the one listed on the CurseForge.

**Comment by ReikaKalseki** [comment]
Fixed.
