### ISSUE TITLE
ChromatiCraft v23 Crash

### ISSUE THREAD

**Issue by Urbanxx001** [ReikaKalseki/Reika_Mods_Issues#2199]
World loaded fine with Rotary, Electric, and Reactor. It was when I added ChromatiCraft that it crashed upon loading world. Expecting a stackmap frame at branch target 259. No other mods were involved. Using Forge 10.13.4.1558 and running on Windows 10 Intel i5 Lenovo laptop.

Crash report: https://pastebin.com/N3nHKJQy

**Comment by ReikaKalseki** [comment]
#1740 #1437 #1566 #1583

**Comment by Urbanxx001** [comment]
Ah it's duplicate, sry thank you for bringing it to my attention.
