### ISSUE TITLE
ゲームがクラッシュ

### ISSUE THREAD

**Issue by kytoyte** [ReikaKalseki/Reika_Mods_Issues#22]
ヘルプ、私のゲームは鉱石フレークでクラッシュ？私確認していますが、でも、唯一の他のMODで発生していない。

**Comment by coolsquid** [comment]
Please provide a crash report and a FML log.

**Comment by coolsquid** [comment]
We only provide support in English.

**Comment by kytoyte2** [comment]
申し訳ありませんが、私のアカウントが壊れた
http://pastebin.com/fH3kBNVt

**Comment by madolinn** [comment]
Google translate says it's the NEI flakes issue. It's resolved in the next patch buddy!

今後のリリースで修正された

Yay bad Japanese translation.
