### ISSUE TITLE
rotarycraft drying bed recipe handler crash

### ISSUE THREAD

**Issue by eletrolitico** [ReikaKalseki/Reika_Mods_Issues#220]
just updated NEI and your mods to v8, whenever i click an item to get its recipe my game crashes.
log:https://www.dropbox.com/s/yyyxk25d7wyepv4/crash-2015-09-02_17.53.04-client.txt?dl=0
PS: removing the drying bed handler class file from the rotarycraft zip solves the issue, but, of course, i can't see the drying bed recipes.

**Comment by kolatra** [comment]
Duplicate issue, this is already fixed.
