### ISSUE TITLE
Uses Consistent Efficiency enchanted tools on Structure Pylon crashes the client

### ISSUE THREAD

**Issue by Prunoideae** [ReikaKalseki/Reika_Mods_Issues#2201]
As the title said.
Pictures will be added if I find more structure later...

**Comment by ReikaKalseki** [comment]
I need a stacktrace.

**Comment by Prunoideae** [comment]
……weird, my client had the 'internal server error' when i'm on server, but nothing happens when i'm in single player

**Comment by ReikaKalseki** [comment]
The server will have an error in its log; get it from the owner.
