### ISSUE TITLE
Light gun projectiles seemed to be incorrectly spawned

### ISSUE THREAD

**Issue by Prunoideae** [ReikaKalseki/Reika_Mods_Issues#2202]
![38TA$%7}XNZ(W F`VPFJ7%K](https://user-images.githubusercontent.com/24620047/67198079-c6a7bd00-f430-11e9-868d-9ab17c9059a5.png)

I just pressed the right button down then soon my room was filled with the entities...
On a server of mine.

**Comment by Prunoideae** [comment]
TPS and network just fine on the server, and it comes really funny that the projectile will just fly away if I clicked it.

**Comment by ReikaKalseki** [comment]
You are saying that the entities did not get an initial velocity?

**Comment by Prunoideae** [comment]
Yes, but it disappeared when I restarted the server once, it looks like a bug of forge server itself, or just the server is taking heavy load...

**Comment by ReikaKalseki** [comment]
Odd.
