### ISSUE TITLE
Chromaticraft - Casting table filled up by merely being in debug mode unsure if feature or bug

### ISSUE THREAD

**Issue by Megablocklobster** [ReikaKalseki/Reika_Mods_Issues#2204]
<s>I went to do crafting with the casting complex and wondered why it didnt pull lumen but still wroked, broke it and it said 2G for every element. Only happened in casting complex structure, not the lower tiers. I also got it recreated with only chromaticraft and dragonAPI loaded. </s>
EDIT: see my latest comment for the issue

**Comment by voidsong-dragonfly** [comment]
Do you have debug mode on?

**Comment by Megablocklobster** [comment]
One time yes, one time no. The first time experienced it I didnt have debug mode on, when testing around I had debug on to set the stages of the table to the one that works in the casting complex. Gotta test it again without debug i guess.

**Comment by Megablocklobster** [comment]
Oh apparently merely being in debug mode fills the table up without a need to klick on it. Thats weird. Is that supposed to happen? Its hard to decide if thats a bug or intended. Is there any documentation for the debug mode? I'm unable to find any. And in my survival world where this happened the first time i was more than 300 blocks away from my casting table when using debug

**Comment by voidsong-dragonfly** [comment]
Yes, that's supposed to happen. Debug should _never_ be used if you plan to use the world for Survival play at all, as it has quite a few effects. Debug has little documentation that I know of, I think it's mostly for Reika's use.

**Comment by Megablocklobster** [comment]
thank you for helping! Now I know where the mistake was and that it totally is on my end.
