### ISSUE TITLE
ExU Ender Quarry crash

### ISSUE THREAD

**Issue by Prunoideae** [ReikaKalseki/Reika_Mods_Issues#2205]
https://pastebin.com/4drj6ZZM

Looks like some fake player issue, again...

**Comment by Prunoideae** [comment]
![image](https://user-images.githubusercontent.com/24620047/67293849-97b84680-f517-11e9-8203-0e0b5356e9d0.png)
……What?
A reason for this is that the this.getHarvestedItemStack returned null, and it triggered the NPE when the code was trying to access the is.stackTagCompound...

**Comment by ReikaKalseki** [comment]
Is `is` in fact null?

**Comment by ReikaKalseki** [comment]
Interestingly the same crash is present in #2193, despite being far more specific, and not involving an ender quarry.

**Comment by ReikaKalseki** [comment]
So does that new debugging code help?

**Comment by Prunoideae** [comment]
Ahh sorry, I'm off server now as there is some personal problem which I must handle, so it could be impossible for me to track this issue at this time.

**Comment by ReikaKalseki** [comment]
Continued in #2225.
