### ISSUE TITLE
[RoC] Perma-magnet upgrade dupe?

### ISSUE THREAD

**Issue by Notawallplan** [ReikaKalseki/Reika_Mods_Issues#2206]
Reproduction instructions:
Get RotaryCraft 23a, Tinker's construct(?), Reactorcraft 23a, all dependencies.
Place down Magnetizer.
Upgrade it with Integrated Redstone Upgrade
Power it till it starts ticking.
Break it (fortune may be required. Try with Tcon pick too.)
Magnetizer should drop along with the Integrated Redstone Upgrade (expected) and Permanent Magnet Upgrade (%&@#?).

**Comment by ReikaKalseki** [comment]
Fixed.
