### ISSUE TITLE
[Chromaticraft]Retroactive Recognition Cannot complete

### ISSUE THREAD

**Issue by kida62** [ReikaKalseki/Reika_Mods_Issues#2210]
I don't know the progress of Retroactive Recognition, but it has a clear mark.
However, the Reveal is not displayed.

![2019-11-03_02 55 23](https://user-images.githubusercontent.com/42175918/68075016-cb338480-fde5-11e9-8ab8-ca7f649a8a25.png)

**Comment by ReikaKalseki** [comment]
That is only granted under special circumstances, and gates nothing.
