### ISSUE TITLE
Redo VM Drop system and add LuaBlock recipes for neutron irradiation chamber

### ISSUE THREAD

**Issue by pajrle** [ReikaKalseki/Reika_Mods_Issues#2211]
Hello, I hope you do not mind few suggestions.
Void monster: Example files for custom drops. I do not know syntax again.
Reactorcarft: Option to add custom lua block recipes for Neutron Irradiation Chamber. It would be nice for some end-game modpack recipes.
Electricraft: Alternative for some rotarycraft machines. Electricraft voltage and current system can make them gated and balanced same as rotarycarft machines (voltage and current can be used in same way as rotation speed and torque).  For example resistive heater would be alternative for friction heater with same temperature formula but silent :O . Bright lamp and floodlight powered by electricity would be nice too, plus it is more realistic to create light with electric energy rather kinetic energy.

**Comment by ReikaKalseki** [comment]
I can certainly add the VM and ReC suggestions, but I am not adding duplicate machines to ElC.

**Comment by pajrle** [comment]
Ok, I understand that having 2 machines for same job is pointless. Will you do other suggestions ? And also please make some documentation for all lua block configurations. I do not want to bother you again
if I find some more configs with unknown syntax.

**Comment by ReikaKalseki** [comment]
Done, though I do not really like the autogenerated useless example file; it seems like external documentation somewhere would be much cleaner.
