### ISSUE TITLE
Hardcore Ender Expansion towers crashing game while DragonAPI is installed.

### ISSUE THREAD

**Issue by wapachoo** [ReikaKalseki/Reika_Mods_Issues#2212]
Crashes as long as the tower is in render distance, screen is covered in pink.
https://gist.github.com/wapachoo/131556ceb467f5cce5447943351114d2

**Comment by Kataiser9** [comment]
Same issue. It appears this is the offending snippet:

`TileEntityMobSpawner te = (TileEntityMobSpawner)lgc.getSpawnerWorld().getTileEntity(lgc.getSpawnerX(), lgc.getSpawnerY(), lgc.getSpawnerZ());`

I'm not an expert, but it seems like this could be trivially band-aided by checking the TE's block name before the cast, and returning early if it's "tile.mobSpawner". (Assuming, of course, it's acceptable to let HEE's spawners _not_ properly trigger the event for now.)

**Comment by ReikaKalseki** [comment]
Fixed.
