### ISSUE TITLE
Client Side settings not client sided

### ISSUE THREAD

**Issue by Rewyn** [ReikaKalseki/Reika_Mods_Issues#2213]
Main setting in question being the 
"B:"[T0D020A6B] Tools Clear Chat"=false"
line in the RoC config.
ExpandedRedstone for ticking noises as well, and yes, I saw the previous issue for that one. 
Wouldn't it be possible to have a volume setting like there is for RoC machinery, as that one seems to work clientside just fine?

**Comment by ReikaKalseki** [comment]
The RC and ExR sounds work completely differently; the latter uses the server sound system.

**Comment by Rewyn** [comment]
Ah, gotcha. Guess it's not _that_ big of a deal either way for ExR. Maybe needs to be moved from the clientside part of the config then, however?

**Comment by ReikaKalseki** [comment]
The chat issue was in fact specific to the transducer; all other chat clearing *was* clientside.

**Comment by Rewyn** [comment]
Huh. Fair enough, I guess other tools (not) clearing the chat came up so little, that I never noticed.
