### ISSUE TITLE
[CC] Wooden repeaters become impossible to move after overloading

### ISSUE THREAD

**Issue by ReactivePlatypus** [ReikaKalseki/Reika_Mods_Issues#2214]
This was tested using a modpack containing:
DragonAPI V23b
ChromatiCraft V23b
RotaryCraft V23b
ElectriCraft V23a
ReactorCraft V23b
Thaumcraft version 4.2.3.5

After a wooden repeater overloads, the tile entity remains in-world with a damaged-looking texture (guessing this is related to the change in v23a: "ChromatiCraft: Wooden repeater end-of-life behavior is less punishing"). The repeater seems to become unlinked from the player who placed it and cannot be removed by normal means. It is seemingly unbreakable except in creative mode. To test, a repeater and charger were cheated in and both were placed while in survival mode:
![2019-11-05_21 28 56](https://user-images.githubusercontent.com/22828039/68266751-aa517600-0015-11ea-88f7-67d2cc14640d.png)
Immediately after the destruction of the repeater.
![2019-11-05_21 29 28](https://user-images.githubusercontent.com/22828039/68266763-b6d5ce80-0015-11ea-86dc-315be7b3960b.png)
Attempted to remove it by shift+rightclick with elemental manipulator and breaking with a variety of tools. It would not break. In this test instance, progression was maximized through commands, but it was first seen on a survival server playing legitimately.

**Comment by ReikaKalseki** [comment]
Fixed.
