### ISSUE TITLE
[Suggestion] Bedrock Boots preventing harmful effects when stepping on things

### ISSUE THREAD

**Issue by Rewyn** [ReikaKalseki/Reika_Mods_Issues#2215]
Main things that come to mind being the grinder/friction heater.

**Comment by Rewyn** [comment]
Another thing I thought of would be to have the bedrock armor set work as the apiarists clothes from forestry, so it protects you from harmful bee effects?

**Comment by ReikaKalseki** [comment]
There is already a helmet upgrade for that.

**Comment by ReikaKalseki** [comment]
Done.
