### ISSUE TITLE
Void moster mod 1.7.10 and more

### ISSUE THREAD

**Issue by avescarelo** [ReikaKalseki/Reika_Mods_Issues#2216]
Hello, i installed your mods: VoidMonster and ChromatiCraft. 
I has been generated new world and my game has been crashed after some minuts :/
I not doing anything strange in the world, i only walked on the map.

My latest.log: [*tup*](https://gist.github.com/pingvikin/c3c64951119523fe4386467f1193d99d)
My crash-report: [*tup*](https://gist.github.com/pingvikin/79d1eb622badda0a42b4cb151a96c349)

Also, i want make localization for ChromatiCraft, but i can't find localization file for book in mod archive. Only file for items :/ Please, make localization file for book.

**Comment by ReikaKalseki** [comment]
#2209.

Also, the locale is XML inside the resources folder.
