### ISSUE TITLE
Crash with crafting patterns

### ISSUE THREAD

**Issue by Rewyn** [ReikaKalseki/Reika_Mods_Issues#2217]
First off, this is probably not something you'd encounter unless deliberately, so probably not too high on the priority list.
Open crafting pattern GUI, move the crafting pattern item from your selected hotbar into any other slot, icons (like the crafting table) will disappear from the GUI. Then attempting to use a button to change amount of crafted results will lead to a crash.
https://pastebin.com/HgPFGwbu

**Comment by ReikaKalseki** [comment]
Fixed.
