### ISSUE TITLE
Autocrafter dupes items when crafting ingredient is removed from the instance

### ISSUE THREAD

**Issue by Rewyn** [ReikaKalseki/Reika_Mods_Issues#2222]
Using Industrial Hemp Fiber from Immersive Engineering as an example, craft that into regular string using an RoC autocrafter.
If you remove Immersive Engineering, the autocrafter will keep crafting the string, even though the ingredient for it doesn't exist anymore. Even temporarily removing the pattern doesn't change that, only on actually opening the pattern GUI it updates and becomes empty.

**Comment by ReikaKalseki** [comment]
Fixed.
