### ISSUE TITLE
[Suggestion/Request] Config option to prevent the Spillway from acting as an infinite Water Source

### ISSUE THREAD

**Issue by Rewyn** [ReikaKalseki/Reika_Mods_Issues#2223]
Alright, since the title is fairly self-explaining, here's a bit of an explanation of why.
One of the more popular packs to have included RoC was/is Revolution 3. This pack has a certain quirk, not found in many others, specifically having a mod for finite water. So no 2x2 pools for infinite water etc.
The RoC pump already respects that purely by design, which is great. Well, almost.
For lategame water requirements there's also a very viable option with the DPA.
And earlygame there's a few ways of getting water, like reservoirs in rain. Just not in infinite amounts. Which is perfectly fine for running most things, just not a dozen of steam engines permanently.
This leads to an earlier investment into other, far less used, power generation like Wind Turbines. Also earlier setups for Gasolines. And kinda stops almost entirely relying on steam engines all the way up to jet fuel.

And while I know that RoC isn't exactly intended in a finite water environment, I feel like it really isn't hurt all that badly by it. It working perfectly fine before the introduction in Rev3 for quite some time should be enough proof of that.
On the contrary, I feel like with machines as the DPA, it fits very well into it.

On the same note, I'd request to make the "duplication" of water from the pump to either be a config option as well, or affected by the same config option as the Spillway.
It does take a bit of thinking and setup (aside from most people not even knowing about it I'd guess), but it's pretty simple to get a feedback loop with the pump and a liquid spiller with even just a single steam engine.
On the one hand, I'd be willing to leave this one in, as it requires some thinking, on the other hand it completely circumvents a core feature of the pack for relatively little cost.

**Comment by ReikaKalseki** [comment]
I added a config multiplier which bottoms out at 0.1x, making it still possible but much less effective.

**Comment by Rewyn** [comment]
... I really don't want to sound too ungrateful, but I'd imagine the only thing this'd lead to is having people who want to avoid finite water simply spam 10x as many of them.
Ah well, guess I'll have to take what I can get. I at least appreciate the consideration. :p

**Comment by ReikaKalseki** [comment]
I can consider anti-spam measures.
