### ISSUE TITLE
Opencomputers not showing all components

### ISSUE THREAD

**Issue by MixaMortiferum** [ReikaKalseki/Reika_Mods_Issues#2226]
So i've seen alot of people mentioning how their adapters are showing all of their rotarycraft machine components connected together even though it's not connected to the adapter itself, although i'm having the complete opposite issue. I want to control a reactorcraft reactor using opencomputers but connecting adapters to each part of the reactor is impossible, and they will only show the parts directly adjacent to an adapter how can I get all of the components to show on a computer? Not sure if it's a version issue, using 1.7.10

**Comment by voidsong-dragonfly** [comment]
There's a config for this I think.

**Comment by MixaMortiferum** [comment]
I've had a look but can't really find anything to change it, do you have an idea which setting it would be?

**Comment by Rewyn** [comment]
I believe it might be the "Direct OpenComputers Support" line in the DAPI config. Don't take my word for it, just seemed like the one that makes the most sense.

**Comment by OvermindDL1** [comment]
For note, the recursive search for OC 'through' all RC items is known to cause quite a bit of lag, so it's usually best to keep it off and connect cables directly instead.

**Comment by MixaMortiferum** [comment]
yeah I found the correct config option, working now, thanks guys. And yes I would connect cables to each one but that would be impossible to do on a reactor since all of the faces are obstructed
