### ISSUE TITLE
[CritterPet] Rendering a tamed wisp causes a client crash

### ISSUE THREAD

**Issue by Not-February** [ReikaKalseki/Reika_Mods_Issues#2229]
Tested in a small standalone instance after experiencing the issue in another modpack.

The normal(and hostile) wisps from Thaumcraft itself are fine, it's just the ones tamed by CritterPet that are causing the crash.

https://gist.github.com/Febilian/8e95b2fcaabf373935490b90e8d3fd99

**Comment by ReikaKalseki** [comment]
Fixed.
