### ISSUE TITLE
Reflective Mod Handler (Mystcraft) 

### ISSUE THREAD

**Issue by jasonvuori** [ReikaKalseki/Reika_Mods_Issues#223]
Error received in the Game Output:

DRAGONAPI ERROR: Some reflective mod handlers have failed.
DRAGONAPI ERROR: Please try updating all involved mods, and if this fails to fix the issue, notify the author of the handlers.
DRAGONAPI ERROR: 1 failure for Mystcraft ('Mystcraft'):
DRAGONAPI ERROR: ModReflectionException "DragonAPI had an error reading Mystcraft:
Could not find a field for decay
Please notify Reika as soon as possible, and include your version of Mystcraft" thrown from Reika.DragonAPI.Base.ModHandlerBase

DragonAPI version is v8d and Mystcraft is 0.12.3.00. 

No negative effects apparent in-game.

**Comment by ReikaKalseki** [comment]
Can I see your loading log?

**Comment by jasonvuori** [comment]
I believe this is the correct log: http://pastebin.com/mKf5RQst

**Comment by ReikaKalseki** [comment]
OK, this should be fixed now.
