### ISSUE TITLE
Crash when rendering AR Holoprojector placeholder blocks

### ISSUE THREAD

**Issue by Kataiser9** [ReikaKalseki/Reika_Mods_Issues#2230]
Crash report from a minimal install: https://pastebin.com/cSACi6QF

**Comment by OvermindDL1** [comment]
```text
java.lang.NoSuchMethodError: zmaster587.libVulpes.tile.multiblock.TilePlaceholder.getReplacedBlockMeta()I
    at zmaster587.advancedRocketry.client.render.RendererPhantomBlock.func_147500_a(RendererPhantomBlock.java:44)
```

Hmm, this looks more like a bug in `advancedRocketry` *or* the `libVulpes` version you have is wrong for the `advancedRocketry` version...

**Comment by Kataiser9** [comment]
...Good lord, I'm an idiot. I double-checked to ensure I had the right AR version but somehow failed to check LibVulpes, which wasn't quite up to date.

I apologize. Closing issue.
