### ISSUE TITLE
Spawner controller not functioning correctly: Over-Powered spawning 

### ISSUE THREAD

**Issue by madsamjp** [ReikaKalseki/Reika_Mods_Issues#2231]
Rotarycraft V23b - spawner controller is out of control, spawns hundreds of mobs within a few seconds of operation with only minimal power supplied. It's not useable in this version of rotarycraft. 

I've tested this multiple times on fresh installations of minecraft with only Reika mods loaded (latest versions) to rule out interactions with other mods. 

![1](https://user-images.githubusercontent.com/49611363/70374339-05aea680-18e9-11ea-8745-c0b9245b4f8d.jpg)

**Comment by Notawallplan** [comment]
Have you tried other spawners too?

**Comment by voidsong-dragonfly** [comment]
This happens with magma cube spawners as well, _and_ with the borer. I got close enough to the spawner to hit TAB while looking at it, so I saw that the delay on the spawner never gets higher than zero after the first operation, giving it one op/t.

**Comment by madsamjp** [comment]
> 
> 
> Have you tried other spawners too?

Yes, I've tried skeleton and zombie - same effect.

**Comment by ReikaKalseki** [comment]
Fixed on the controller; does not happen for the borer.
