### ISSUE TITLE
Game crashes whenever I enter a world

### ISSUE THREAD

**Issue by NuclearAtoms** [ReikaKalseki/Reika_Mods_Issues#2232]
So, whenever I join a world, my game crashes. I have DragonAPI installed. I've tried this with and without mods and I get the same result always.

Here's the crash report:
https://pastebin.com/A7vNnBpP

**Comment by Kataiser9** [comment]
I'd try updating Forge to 1614, which is the latest for 1.7.

**Comment by NuclearAtoms** [comment]
Oh, no wonder. Let me try that, thanks for the help.

**Comment by NuclearAtoms** [comment]
It worked, thanks alot.
