### ISSUE TITLE
Crash on Japanese Windows

### ISSUE THREAD

**Issue by WiduX** [ReikaKalseki/Reika_Mods_Issues#2233]
Hello,

I had a server set up and running fine on an English installation of Windows. I then decided to simply move the entire directory onto a different computer, that has a Japanese installation of Windows. Since then, the server will no longer start, citing these two errors that I believe are relevant:
`java.lang.RuntimeException: Could not load XML at Resources/trans.xml relative to Reika.RotaryCraft.RotaryCraft`
`com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: 2�o�C�g��UTF-8�V�[�P���X�̃o�C�g2�������ł��B`
(The characters that appear wrong above are actually that way in the log)
I have tried re-copying the folder, in case the files somehow got corrupted during the first copy, but this changed nothing.
Here is the crash log file: https://pastebin.com/mEcPNAwk
I can post the full log as well if it'd help, it's just excessively long.

**Comment by WiduX** [comment]
FYI I changed the system language to English, and got the same error again. It resolved itself after changing the system locale from Japanese to English.

Theoretically then it should be possible to reproduce this issue by changing your locale to Japanese?

**Comment by Rewyn** [comment]
I don't think so, I've had my system locale set to japanese for quite some time, and never ran into that issue.

**Comment by ReikaKalseki** [comment]
When your language is set to a language the mod has locale for, it will load that locale instead of the English defaults. Apparently the Japanese one has issues.

However, this reminds me of the similar issue with the Spanish locale. Try setting your file encoding to UTF-8.

**Comment by WiduX** [comment]
I'm not quite sure what you're asking me to do. That file appears to already be UTF-8, but I'm guessing you want me to set an option somewhere?

**Comment by Rewyn** [comment]
Probably referring to this
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2167

**Comment by ReikaKalseki** [comment]
Yes, that.

**Comment by WiduX** [comment]
Sorry for the delay. This does resolve the issue.

For people finding this later on, just add `-Dfile.encoding=utf-8` to the JVM arguments and it should work.
