### ISSUE TITLE
[Suggestion] Sparkling Block Variants?

### ISSUE THREAD

**Issue by Notawallplan** [ReikaKalseki/Reika_Mods_Issues#2235]
Title, really. Adding Sparkling Stone Bricks (and chiseled) and adding Sparkling Wood Planks.

Could possibly integrate into Geostrata to add sparkling variants of those stone variants variants. Possibly dynamically for ease of implementation?

**Comment by ReikaKalseki** [comment]
Sparkling blocks are intended to be for worldgen, not crafted blocks. And it would take massive rewrites to have dynamic creation of variants, and would probably run into the same issues as the Geostrata ores.
