### ISSUE TITLE
Massive clientside VM chatspam while inventory open

### ISSUE THREAD

**Issue by Rewyn** [ReikaKalseki/Reika_Mods_Issues#2236]
I'm not really sure where to start or how to help figuring this out, but it's gotten to a point I'd consider an active issue with playability.
Whenever I have my inventory open, the chat is getting spammed by the usual clientside vm message, about 20 times per second. This does not stop as long as the inventory GUI is open (as well as having any other GUI open that includes the player inventory) and is completely consistent for me at this point. It only started to come up after making a Travellers Gear Armor Stand and happened even while having it only on the hotbar or when opening an inventory with it in it. At this point (basically a day later, with no apparent other changes) it happens regardless, even with an entirely empty inventory. It does not occur withing the first few seconds of joining a server when opening the inventory immediately, but has no such delay after that.
[fml-client-1.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/3962523/fml-client-1.log)
Not sure if there's anything relevant in the log, the clientside void monster message itself doesn't seem to contain anything unusual, I think..? But it's the only thing I got, so might as well include it.
Spam starts at line 37395.

**Comment by ReikaKalseki** [comment]
It makes no sense that your armor or what GUI is open would affect it; this code is called by the entity's update tick, which is independent of either thing.

**Comment by ReikaKalseki** [comment]
I have removed the logging, as I doubt this is ever going to be fixed.
