### ISSUE TITLE
[CC] Adjacency Core Upgrade Issue

### ISSUE THREAD

**Issue by Astrolight** [ReikaKalseki/Reika_Mods_Issues#2237]
You are not able to upgrade a adjacency core after it has been placed in world.

Example.
1. Create a tile accelerator
2. Place tile accelerator (2x) with the required materials to upgrade it to the second tier (4x), Chroma table shows that it is a valid recipe.
3. Place 2x accelerator in world, pick up using shift-click wand and place in chroma table
4. No longer a valid recipe

I imaging it has to due with NBT data being added when the item is placed in world which makes the recipe no longer valid.

**Comment by ReikaKalseki** [comment]
I fixed this recently.
