### ISSUE TITLE
RoC Sandstone pipes attach to all kinds of fluid tanks

### ISSUE THREAD

**Issue by Rewyn** [ReikaKalseki/Reika_Mods_Issues#2238]
RoCs Sandstone fluid pipes are supposed to only connect to other (non-sandstone) fluid pipes, but not any form of fluid inventory. This isn't the case for at least a few tanks, however. Tested with ExU drums and the crc alloying tank. Also ender tanks according to Silfryi on discord.

**Comment by ReikaKalseki** [comment]
Fixed. ![https://i.imgur.com/m7zx5kG.png](https://i.imgur.com/m7zx5kG.png)
