### ISSUE TITLE
[Question] Turbine Generator

### ISSUE THREAD

**Issue by Gandalf360one** [ReikaKalseki/Reika_Mods_Issues#2239]
On what does it depent how much energy I get from it or do I always get infinity energy from it when the turbine slowly rotats ?

**Comment by Rewyn** [comment]
Huh? It depends on the output of the turbine, obviously?

**Comment by voidsong-dragonfly** [comment]
Can I see screenshots of "infinity energy"?

**Comment by ReikaKalseki** [comment]
Why did you close it?

**Comment by Gandalf360one** [comment]
Because I dont know the mod very good and I got my answer from already. Thanks for the support

**Comment by ReikaKalseki** [comment]
...?

**Comment by leonbaronick** [comment]
He thought that your issue page is also the right place for asking questions, which it is not.

He didn't understand how the mod works, hence the question. You can close this issue.
