### ISSUE TITLE
Hydrokinetic Engine and Streams Interaction Failure

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2240]
The hydrokinetic engine does not chain after four in streams water, breaking and outputting no torque nor passing torque instead. It exhibits standard broken behavior even when upgraded with a bedrock shaft unit. 
![2019-12-22_14 54 57](https://user-images.githubusercontent.com/40431605/71327413-2294cd80-24d6-11ea-93ae-930c686336b5.png)

**Comment by ReikaKalseki** [comment]
This was not actually true; it just broke before you applied the upgrade. Doing that will now (temporarily) repair it.
