### ISSUE TITLE
Void Monster attack fails against players with unbreakable armour

### ISSUE THREAD

**Issue by dalapo** [ReikaKalseki/Reika_Mods_Issues#2243]
The routine for the Void Monster's attack has it fully drain the player's armour before depleting their health; however, this results in a player wearing one or more pieces of unbreakable armour (e.g. Thaumic Tinkerer Ichorcloth) being immune to it. damageAmor in ReikaEntityHelper is supposed to ignore such armour, but only checks for instances of UnbreakableArmor (a DAPI class) and fails for such armour from other mods.

**Comment by ReikaKalseki** [comment]
Fixed.
