### ISSUE TITLE
java.lang.NoClassDefFoundError: Reika.VoidMonster.Entity.EntityVoidMonster

### ISSUE THREAD

**Issue by aetherpirate** [ReikaKalseki/Reika_Mods_Issues#2245]
CTD on singleplayer and server worlds. 

Created test modpack with just these mods

Forge 1614

DragonAPI{v24b} 
ChromatiCraft{v24b} 
RotaryCraft{v24b} 
ElectriCraft{v24a} 
ReactorCraft{v24a} 
[crash-2019-12-23_15.32.30-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/3996235/crash-2019-12-23_15.32.30-client.txt)

**Comment by ReikaKalseki** [comment]
Fixed in v24c.
