### ISSUE TITLE
Sludge can't be smelted

### ISSUE THREAD

**Issue by itsCryne** [ReikaKalseki/Reika_Mods_Issues#2246]
It's plainly impossible to smelt sludge to obtain ethanol crystals although the manual states, that it should be possible

**Comment by aetherpirate** [comment]
What versions of Reika's mods are you using?

**Comment by Barhandar** [comment]
Because you're supposed to centrifuge it now. If you're using any manual but the built-in books, you're doing it wrong (but that can be outdated too).

**Comment by ReikaKalseki** [comment]
This was changed a long time ago.

**Comment by itsCryne** [comment]
_Of course_ it is the Handbook
![2019-12-24_01 10 40](https://user-images.githubusercontent.com/51213332/71385936-9c1de000-25ea-11ea-8d5a-3f5951d3e06a.png)

**Comment by Barhandar** [comment]
Translation: actual issue is "handbook is not updated to describe the sludge centrifuging change", @ReikaKalseki
