### ISSUE TITLE
[RoC] Handbook incorrectly asserts you smelt sludge, rather than centrifuge

### ISSUE THREAD

**Issue by thePalindrome** [ReikaKalseki/Reika_Mods_Issues#2249]
The handbook has lists the machines needed as fermenter->fermenter->furnace,
it should instead properly mention the centrifuging step.

**Comment by Barhandar** [comment]
Ditto for jet fuel - the book doesn't reflect the changes (liquid ethanol instead of crystals, coal dust instead of coal, and pink dye).

**Comment by ReikaKalseki** [comment]
Both of these were done a very long time ago.
