### ISSUE TITLE
Magnetic coil upgrade wont be magnetized

### ISSUE THREAD

**Issue by slain92** [ReikaKalseki/Reika_Mods_Issues#2252]
As title says 
Magnetic coil upgrades  won't be magnetized anymore after the last update
But shaft coils will be magnetized  and work fine

**Comment by ReikaKalseki** [comment]
WTF? I did not even change the magnetizer...

**Comment by slain92** [comment]
shaft coils perfectly working [https://puu.sh/ETb8h/9d29c91b21.png](url)
but magnetic coil upgrades dont work [https://puu.sh/ETb8W/ebd6eb6778.png](url)
had the upgrade for like 3 hours in it and was afk but nothing happened

**Comment by Rewyn** [comment]
How much speed/power are you giving it? I've noticed in v23 at least, that the upgrades take more ... power, I think it was, compared to shaft coils. Not just for maximum charge, but to start charging at all.

**Comment by cyberdragon442** [comment]
I can't even physically place the upgrade in the magnetizer at all.

**Comment by ReikaKalseki** [comment]
Unstack it.

**Comment by cyberdragon442** [comment]
It was just one...

**Comment by ReikaKalseki** [comment]
What happens if you put it in the slot? I do not prevent direct manual placement regardless of item validity.

**Comment by cyberdragon442** [comment]
EDIT: I found what was happening. You can't open the gui while holding the upgrade item, but you can when holding any other item (besides a screwdriver).

**Comment by ReikaKalseki** [comment]
That would be because it is trying to upgrade the machine and failing.
