### ISSUE TITLE
DragonAPI V24c changed sky color.

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#2253]
Please look at the picture. The difference between the clients of the two screenshots is only whether a mod of dragonapi is installed.

Just installed Forge 1614:
![1](https://user-images.githubusercontent.com/25248285/71468277-5470a180-2800-11ea-8a27-d5db47568dfe.png)

Forge 1614 + DragonAPI V24c (There are no other mods installed.):
![2](https://user-images.githubusercontent.com/25248285/71468292-62262700-2800-11ea-8b06-76c73c83fb1a.png)

This is obviously not right. What's the problem?

**Comment by Rewyn** [comment]
Not sure if that has anything to do with it, but the 2 screenshots seem to be of different times?
In the second it's closer to dusk, so a different looking sky would actually make sense.

**Comment by ORANG4** [comment]
Same problem (any time of day)

**Comment by voidsong-dragonfly** [comment]
Intentional. It'll go away after Christmas, it makes the sky look like a snowstorm is imminent throughout the Christmas season, to accompany the snowflakes.

**Comment by ghost** [comment]
> Not sure if that has anything to do with it, but the 2 screenshots seem to be of different times?
> In the second it's closer to dusk, so a different looking sky would actually make sense.

Tested. Any time of day, same problem.

**Comment by ReikaKalseki** [comment]
It is in fact dependent on game time, but not time of day; it is more random (noisemap-based) than that.

And Silfryi is right; it makes the sky fade between the normal color and a slate blue-gray, like the sky when a snowstorm is near.

**Comment by ghost** [comment]
@ReikaKalseki Wow you pay too much attention to the details. I also see some Christmas patterns on the machine.

**Comment by ReikaKalseki** [comment]
:P
