### ISSUE TITLE
[DAPI v24c] Disabling holidays has no effect

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#2254]
`B:"[numbers] Enable Temporally Dependent Amusement Behavior"=false` does not affect presence of Chromaticraft decorations, RoC decorations, or the snowflakes. Running self-hosted dedicated, both client and server instances have it set to false.

**Comment by ReikaKalseki** [comment]
Those are not disableable, nor will they ever be; they do not get in the way, like some of the other effects could be argued to do, nor do I feel that is at all appropriate.

**Comment by Barhandar** [comment]
Remove the config option then, since it's useless. 

Also, it's completely irrelevant whether they get in the way or not (also snowflakes DO get in the way), things like these should be disableable without time tinkering.

**Comment by ReikaKalseki** [comment]
> Remove the config option then, since it's useless.

Hardly.

**Comment by Barhandar** [comment]
This issue isn't a bug because the option isn't "holidays", despite the client-facing name indicating otherwise; it's dedicated solely to April Fools' Day. Nonetheless, the snowflakes, or rather, _their associated shader_ warp-thing do get in the way; I would mind them far less if they lost the shader.

Also the holidays still should be disableable entirely without having to mess with instance time. Moreso _specifically_ they're cosmetic and nothing else, they do not affect actual objective gameplay, only the subjective experience of it; there's no reason to force them on people.
~~Also users in Philippines should have Christmas effects start at September 1~~
