### ISSUE TITLE
[DragonAPI V24c] TheBetweenlands compatibility

### ISSUE THREAD

**Issue by ORANG4** [ReikaKalseki/Reika_Mods_Issues#2255]
#### Forge version:
1.7.10-Forge10.13.4.1614

#### Installed mods:
DragonAPI V24c
TheBetweenlands v1.0.6

#### Problem:
Game crashes almost instantly

#### Link to full crash log
https://gist.github.com/ORANG4/ab84b0e216fac436872fbe25d70656c5

**Comment by ReikaKalseki** [comment]
Linking to https://github.com/Angry-Pixel/The-Betweenlands/issues/950

**Comment by ReikaKalseki** [comment]
Fixed.
