### ISSUE TITLE
ChromatiCraft's Casting Stand Insertion Focus swallows output items without a Casting Delegate

### ISSUE THREAD

**Issue by habnabit** [ReikaKalseki/Reika_Mods_Issues#2256]
I've been trying to put together a demo/tutorial for the insertion focus/casting delegate, since I don't think it's possible to understand without a lot of source diving, and I found a bug while I was submerged.

This looks like just a bit of oversight for the case of using an insertion focus without a delegate. Its output item will be swallowed until the focus is broken or some conduit etc. can pull the item out. Normally, it's supposed to be returned or recovered like an ingredient is if a recipe is changed mid-cast, but instead you'll get a spam of `NullPointerException` if you haven't also placed a casting delegate: https://github.com/ReikaKalseki/ChromatiCraft/blob/11a726354c573cd32c99e30a3444130ea5ccaec9/TileEntity/Recipe/TileEntityCastingInjector.java#L111-L112

If `delegate` is `null`, the method will fail before getting to the `recoverItem` path. Presumably you meant to test `delegate == null` before doing that method call. Java's implicit nullability strikes again..

The fix is straightforward and mechanical, but between this and #2147, I'm just remembering how difficult it is to reason about java's implicit nullability and its long-reaching implications.

**Comment by ReikaKalseki** [comment]
This was fixed long ago...why did it not get closed?

**Comment by habnabit** [comment]
What commit was this fixed in?

**Comment by habnabit** [comment]
Apparently https://github.com/ReikaKalseki/ChromatiCraft/commit/0842eeee82251af475ff3750c9691d9c2cfe4da9

**Comment by ReikaKalseki** [comment]
Yes, so it was released in v25.

**Comment by MinerUser** [comment]
This is happening to me right now. Everything I craft while having a Casting Stand Insertion Focus underneath the Casting Table disappears.
