### ISSUE TITLE
[FR] Advanced Rocketry Solar Intensity and Solar Tower Compat

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2257]
Here's what you can get from Advanced Rocketry in terms of solar data, and how to get it.

- Solar distance: dimensionProperties
- Atmosphere density: dimensionProperties (Like for turbine engines etc)
- Size and Temperature and Brightness of star: getting the star from the dimensionProperties `getStar ()`
    - Note that temperature is normalised to 100 is Sol, with lower being cooler and higher being hotter
    - size is a multiplier, with 1.0 being Sol
 - Substars (Binary, Trinary): list in the method for getting all substars, the length of that list is the number of stars, and each entry has a star Properties associated with it

**Comment by ReikaKalseki** [comment]
What is `dimensionProperties`?

**Comment by voidsong-dragonfly** [comment]
@ReikaKalseki  this https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/api/dimension/IDimensionProperties.java

**Comment by ReikaKalseki** [comment]
Done.
