### ISSUE TITLE
[RoC v24c/Thermal Expansion] Ethanol Extract cannot be melted into Liquid Ethanol in Magma Crucible while Ethanol Crystals can

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#2258]
For consistency with Rock Melter it probably should be able to do so.

**Comment by waterlubber** [comment]
Seconding this suggestion - the additional step of processing is unnecessary.
I would also suggest allowing sludge to be melted, but at the very least allow extract.

**Comment by ReikaKalseki** [comment]
Melting sludge would allow skipping the centrifuge, which is not appropriate.

**Comment by ReikaKalseki** [comment]
Done.
