### ISSUE TITLE
Friction Heater Heat Distortion Rendering Crash

### ISSUE THREAD

**Issue by SisterJacq** [ReikaKalseki/Reika_Mods_Issues#2259]
https://gist.github.com/Mortvana/0811d9901b76cfdff4ae4e39af1a4362

I was tinkering on my self-sufficient jet fuel system, upgrading it to work for the changed production, and when placing a fluiduct for the jet fuel line, accidentally connected it to the water. I clicked with my screwdriver, the game crashed with the rendering issue. When I reloaded, same issue (the log is from when I reloaded) the moment I loaded the world. I'm gonna see if downgrading back to v22d (previous installed version) fixes it (it should) until an update comes out.

**Comment by ReikaKalseki** [comment]
This appears to be in the TESR itself, not so much in the actual shader code.

**Comment by ReikaKalseki** [comment]
I am closing this since noone else has reported it and it should have been impossible anyways.

**Comment by SisterJacq** [comment]
Yeah, it seems like a weird one-off, as it hasn't happened since for me either.
