### ISSUE TITLE
error when trying to craft engraved crystalline stone

### ISSUE THREAD

**Issue by Adraxas** [ReikaKalseki/Reika_Mods_Issues#226]
This gets printed in chat whenever i try to craft engraved crystalline stone

http://pastebin.com/j3dH5GER

**Comment by Adraxas** [comment]
also happens when i try to craft beams

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by theron61** [comment]
I am having this exact issue with CC v10d..
