### ISSUE TITLE
Minecraft crashes when world is generated.

### ISSUE THREAD

**Issue by OmegaboyHD** [ReikaKalseki/Reika_Mods_Issues#2262]
I wanted to combine DragonApi with DragonBlockC and the core mods of it. Does anyone know how to fix the issue? The log is included
[Log.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4008714/Log.log)

**Comment by ReikaKalseki** [comment]
#2203 #2199 #1740 #1437 #1566 #1583
