### ISSUE TITLE
[VM] Void Monster corruption effect not fully appearing

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2266]
I know it worked in my test world, so I'm baffled as to why it's doing this now. Never goes past the second stage in the texture overlay.

https://www.youtube.com/watch?v=tEeoNY1o4YQ

**Comment by ReikaKalseki** [comment]
It falls off with distance, and it looks like you are several blocks away.

**Comment by Shahelion** [comment]
It's directly below me. I can't get any closer without breaking the y=0 bedrock.

**Comment by Shahelion** [comment]
![2019-12-31_09 41 19](https://user-images.githubusercontent.com/6917535/71629400-36b18c80-2bb2-11ea-9dec-39f4e574c229.png)
Something weird seems to be going on with the falloff of the effect, perhaps increase the range? Also, maybe a config option to also have the corruption appear on bedrock?

**Comment by ReikaKalseki** [comment]
It is not really meant to be seen on the world floor.

**Comment by Shahelion** [comment]
The effect seems to have a greater range when the Void Monster is above y=0, which is strange.

**Comment by ReikaKalseki** [comment]
That sounds intentional, or the result of simple geometry.
