### ISSUE TITLE
Crash：Invalid casting recipe was going to be added！

### ISSUE THREAD

**Issue by jinshuguangze** [ReikaKalseki/Reika_Mods_Issues#2267]
> Description: Exception in server tick loop
> 
> Reika.DragonAPI.Exception.RegistrationException: CHROMATICRAFT has a registration error:
> Invalid casting recipe was going to be added: class Reika.ChromatiCraft.Auxiliary.RecipeManagers.CastingRecipes.Blocks.PathRecipe
> Contact Reika immediately!
> Include the following information:
> 	at Reika.ChromatiCraft.Auxiliary.RecipeManagers.CastingRecipe.validate(CastingRecipe.java:441)
> 	at Reika.ChromatiCraft.Auxiliary.RecipeManagers.RecipesCastingTable.addRecipe(RecipesCastingTable.java:992)
> 	at Reika.ChromatiCraft.Auxiliary.RecipeManagers.RecipesCastingTable.loadRecipes(RecipesCastingTable.java:591)
> 	at Reika.ChromatiCraft.Auxiliary.RecipeManagers.RecipesCastingTable.reload(RecipesCastingTable.java:1153)
> 	at Reika.ChromatiCraft.ChromatiCraft.overrideRecipes(ChromatiCraft.java:899)
> 

full crash file：https://1drv.ms/t/s!AsVqNA3Tvx-OmjPj9sRODpwihONe
it is as same issue as issue[＃1923](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1923),launched successfully and crashed when created a new map.but i used the newest version of reika's mod.

**Comment by ReikaKalseki** [comment]
Noone else has reported this - what mods do you have that might be removing vanilla blocks?

**Comment by jinshuguangze** [comment]
i have no idea，the modpack is too large...gregtech6 maybe？wait a minute，i will test and find out which mod with ChromatiCraft cause  that issue.

**Comment by jinshuguangze** [comment]
finally,i find out the mod "[spmodAPI](https://www.curseforge.com/minecraft/mc-mods/spmodapi)" override a block from vanilla...so just turn off the spmodAPI's config to ` B:"Override Glowstone"=false` and `B:"Spmod API Mode"=false` could prevent this carsh.

**Comment by ReikaKalseki** [comment]
Removing vanilla blocks is never defensible.

**Comment by Jonius7** [comment]
> finally,i find out the mod "[spmodAPI](https://www.curseforge.com/minecraft/mc-mods/spmodapi)" override a block from vanilla...so just turn off the spmodAPI's config to ` B:"Override Glowstone"=false` and `B:"Spmod API Mode"=false` could prevent this carsh.

---

I had a very similar crash (reproducible) and setting `B:"Override Glowstone"=false` in SpmodAPI got the world to load with ChromaticCraft.

> Description: Exception in server tick loop
> 
> java.lang.NullPointerException: Exception in server tick loop
> 	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
> 	at Reika.DragonAPI.Libraries.ReikaRecipeHelper.getRecipeItemStack(ReikaRecipeHelper.java:449)
> 	at Reika.DragonAPI.Libraries.ReikaRecipeHelper.calculateRecipeToItemStackArray(ReikaRecipeHelper.java:646)
> 	at Reika.DragonAPI.Libraries.ReikaRecipeHelper.getRecipeCacheObject(ReikaRecipeHelper.java:520)
> 	at Reika.DragonAPI.Libraries.ReikaRecipeHelper.getRecipeArray(ReikaRecipeHelper.java:530)
> 	at Reika.ChromatiCraft.Auxiliary.RecipeManagers.CastingRecipe.getRecipeArray(CastingRecipe.java:160)
> 	at Reika.ChromatiCraft.Auxiliary.RecipeManagers.CastingRecipe.validate(CastingRecipe.java:443)
> 	at Reika.ChromatiCraft.Auxiliary.RecipeManagers.RecipesCastingTable.addRecipe(RecipesCastingTable.java:1043)
> 	at Reika.ChromatiCraft.Auxiliary.RecipeManagers.RecipesCastingTable.loadRecipes(RecipesCastingTable.java:586)
> 	at Reika.ChromatiCraft.Auxiliary.RecipeManagers.RecipesCastingTable.reload(RecipesCastingTable.java:1201)
> 	at Reika.ChromatiCraft.ChromatiCraft.overrideRecipes(ChromatiCraft.java:922)

**Comment by ReikaKalseki** [comment]
That is a different error, though sharing the same cause.
