### ISSUE TITLE
[ReaC] Fusion solenoid should explode in a more realistic manner

### ISSUE THREAD

**Issue by waterlubber** [ReikaKalseki/Reika_Mods_Issues#2269]
Current Behavior:
Currently, the solenoid violently explodes when overpowered. This is unrealistic and boring, as there is no stored energy immediately available _for_ the explosion.

Suggested Behavior:
When overtorqued, the solenoid should take significant damage and make some loud noises, but no massive explosion (maybe a little one). This is to simulate the destruction of important structural members. 

When oversped, the solenoid should accelerate normally and beyond, eventually exploding after reaching an absurd speed. This explosion should be the current one, as there would be bits of magnet _everywhere_, very unfortunate.

**Comment by ReikaKalseki** [comment]
There is no such thing as an overtorque failure - it has no such limit.

**Comment by ReikaKalseki** [comment]
Done.
