### ISSUE TITLE
Ore harvester doesn't work on active redstone ore

### ISSUE THREAD

**Issue by Adraxas** [ReikaKalseki/Reika_Mods_Issues#227]
if the ore lights up, the ore harvesting pick doesn't seem to work on it

it also doesn't seem to work on the crystals, but i'm not sure if it is supposed to

**Comment by ReikaKalseki** [comment]
If possible, spawn some active redstone ore as an item and try processing it in RC's ore processing devices. Does it work? If not, the problem is in DragonAPI's registries.

**Comment by Adraxas** [comment]
no it doesn't work.
btw, to get active redstone ore, you have to activate it and use pick block whil in creative mode, you cant actually spawn it in

**Comment by ReikaKalseki** [comment]
/give would probably work. But OK, so the registries are missing an entry.

**Comment by Adraxas** [comment]
actually /give doesn't work. they don't allow you to spawn it in with /give

**Comment by ReikaKalseki** [comment]
Fixed.
