### ISSUE TITLE
[CrC] Problem drawing pylon haze ConcurrentModificationException

### ISSUE THREAD

**Issue by chrisfirefox** [ReikaKalseki/Reika_Mods_Issues#2270]
Hello Reika, after upgrading from v22 to v24 of your Mods, I seem to have problems with the "haze" of pylons, here is a crash log: https://pastebin.com/djast4mt

EnderIO complains about an "unknown AE2 API" from DragonAPI, can't tell if that is anyhow related. Maybe you can have a look and point me in the right direction to fix this, e.g. deactivating some of the other mods.

**Comment by voidsong-dragonfly** [comment]
Do you have the latest v24c?

**Comment by chrisfirefox** [comment]
UCHIJAAAA   DragonAPI{v24c} [DragonAPI] (DragonAPI 1.7.10 V24c.jar)
    UCHIJAAAA   ChromatiCraft{v24c} [ChromatiCraft] (ChromatiCraft 1.7.10 V24c.jar)
    UCHIJAAAA   RotaryCraft{v24c} [RotaryCraft] (RotaryCraft 1.7.10 V24c.jar)
    UCHIJAAAA   ElectriCraft{v24a} [ElectriCraft] (ElectriCraft 1.7.10 V24a.jar)
    UCHIJAAAA   ReactorCraft{v24a} [ReactorCraft] (ReactorCraft 1.7.10 V24a.jar)
    UCHIJAAAA   ExpandedRedstone{v24a} [Expanded Redstone] (ExpandedRedstone 1.7.10 V24a.jar)

**Comment by ReikaKalseki** [comment]
This is another version of #1299 and all its siblings.
