### ISSUE TITLE
Rotarycraft AC Electric Engine 

### ISSUE THREAD

**Issue by EreticKB** [ReikaKalseki/Reika_Mods_Issues#2271]
If i have (both placed or in inventory) AC Engine or Magnetizing Unit without Shaft Core into it, then ALL OF my placed AC Engines generate small unstable amount on torque and rotation speed and totaly ignors redstone signal and presence/absent shaft core into them.
![2020-01-03_16 25 53](https://user-images.githubusercontent.com/59476878/71725652-d3d82380-2e45-11ea-9bc0-e6c15ffdf577.png)
![2020-01-03_16 25 55](https://user-images.githubusercontent.com/59476878/71725659-d6d31400-2e45-11ea-9567-3f678d4d304a.png)
![image](https://user-images.githubusercontent.com/59476878/71725735-041fc200-2e46-11ea-8e94-43636b2a2d88.png)

Forge10.13.4.1614

**Comment by Barhandar** [comment]
Remove magnetized shafts from your inventory and try again.

**Comment by EreticKB** [comment]
Yes, it works, thx.
