### ISSUE TITLE
/biomepng arg length check too late

### ISSUE THREAD

**Issue by EyeDeck** [ReikaKalseki/Reika_Mods_Issues#2278]
https://github.com/ReikaKalseki/DragonAPI/blob/e39e7ba053176f97cd7a7cf0ee85407e3fbddc72/Command/BiomeMapCommand.java#L99
The `if (args.length < 2)` check should be toward the top of the method, otherwise this will error when it tries to operate on args[0] if called with no parameters.

**Comment by ReikaKalseki** [comment]
Done.
