### ISSUE TITLE
VoidMonsterDestructionRitual branch always true?

### ISSUE THREAD

**Issue by OvermindDL1** [ReikaKalseki/Reika_Mods_Issues#2282]
At: 
 https://github.com/ReikaKalseki/ChromatiCraft/blob/b83986f9ea41ca4ce2c81d6e14d6f32d7a1c4107/ModInterface/VoidRitual/VoidMonsterDestructionRitual.java#L180

The `VoidMonsterDestructionRitual` function of `doAttack` is this:
```java
		@ModDependent(ModList.VOIDMONSTER)
		private void doAttack(EntityVoidMonster e, DamageSource src, int amt) {
			if (e.getHealth() >= e.getHealth()) { //kill
				e.setHealth(0.1F);
				e.attackEntityFrom(src, 1F);
			}
			else {
				e.setHealth(e.getHealth()-amt+1);
				e.attackEntityFrom(src, 1F);
			}
		}
```
The `//kill` line seems odd, as it's doing the comparison of `e.getHealth() >= e.getHealth()`, which will always be true, so the void monster is always being insta-killed instead of having it's life being whittled away.

Is this intended?  My gut reaction guess is that it should have been `e.getHealth() < 0` instead or so?

Then again, why is it also both calling `setHealth` and also calling `attackEntityFrom` as well?

**Comment by ReikaKalseki** [comment]
the first e.getHealth() is supposed to be "amt".

And it calls attackEntity from so that the code paths go through the correct places; merely setting health to zero does not trigger all the appropriate death events.

**Comment by ReikaKalseki** [comment]
Fixed.
