### ISSUE TITLE
[Dragon API] Can't launch game after DragonAPI installation

### ISSUE THREAD

**Issue by thaarael** [ReikaKalseki/Reika_Mods_Issues#2283]
Hello there.

So, I wanted to include GeoStrata in my private modpack, and I get regular warning about missing depedence (DragonAPI). After downloading and installing lastest one (1.7.10 V24c), Minecraft refuses to launch at all, and launcher reappears after few seconds. It isn't even crash at all, since game technically doesn't even launch, but still seems to be exacly DragonAPI issue. As I have also The Betweenlands in the pack and I am aware of compatibility conflict, I ran -DragonAPI_disable_ASM_THIRDPERSONDISTANCEDISPATCH JVM argument (both in launcher Java settings - I am using Technic Launcher - and directly in version.json file), but it still doesn't fix issue. 

Issue seems to be centered on lack of definition of "Reflector" class - not sure what is going on here, but it seems to be different issue than one with just The Betweenlands incompatibility. Also, running Optifine HD U D3 for 1.7.10, lastest one compatibile with The Betweenlands.

UPDATE

Nevermind, issue on my part. Technic Launcher ignores JVM arguments, thats why it didn't want to work. Swapped to MultiMC and now it launches without any problem.

**Comment by ReikaKalseki** [comment]
"Reflector" is part of Optifine.
