### ISSUE TITLE
[DragonAPI 24c] Minecraft crash "IllegalStateException: Already tesselating!"

### ISSUE THREAD

**Issue by thaarael** [ReikaKalseki/Reika_Mods_Issues#2285]
Hello (again).

I have DragonAPI and GeoStrata running in my private modpack, and for first 30 minutes it went smooth (save for strange light glitches, which, in contrary to regular MC ones, couldn't be fixed by placing block), but then... Game crashes for me now every time I place few dirt cubes, each time with same crash reason: "IllegalStateException: Already tesselating!". Crash report specifically points to DragonAPI as cause - any sollution to this? I really like idea of GeoStrata and look of its decorative stone, and while there are other "stone overhaul" mods doing similar thing, I really want to stick to that one, as I find it most suitable to my needs. Can I get some help? :)
Crashlog attached. Also, issue seems to be related to rendering of dropped items - got earlier crashes due to remaining leftover wood after cutting down tree, and next ones after I returned into my chicken pen rendering range.
[crash-2020-01-07_15.40.36-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4031095/crash-2020-01-07_15.40.36-client.txt)

List of mods in my pack:
mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
sdnf{1.0} [Storage Drawers NEI Fix] (minecraft.jar) 
ThE-core{1.0.0.1} [Thaumic Energistics Core] (minecraft.jar) 
ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
gilded-games-util{1.7.10-2.1} [Gilded Games Utility] (gilded-games-util-1.7.10-2.0.jar) 
bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
BNBGamingLib{2.3.2} [BNBGamingLib] (BNBGamingLib-2.3.2.jar) 
AdvancedSpawnControl{0.9.1} [Advanced Spawn Control] (AdvancedSpawnControl-0.9.1.jar) 
aether{1.7.10-1.6} [Aether II] (aether-1.7.10-1.6.jar) 
AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0.jar) 
appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
IC2{2.2.999} [Industrial Craft Classic] (IC2Classic-Version-1.2.2.0.jar) 
Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar) 
Forestry{4.2.16.64} [Forestry for Minecraft] (forestry_1.7.10-4.2.16.64.jar) 
koresample{1.7.10-1.3.2} [Kore Sample] (KoreSample-1.7.10-1.3.2.jar) 
StorageDrawers{1.7.10-1.10.9} [Storage Drawers] (StorageDrawers-1.7.10-1.10.9.jar) 
dendrology{1.7.10-1.6.4} [Ancient Trees] (AncientTrees-1.7.10-1.6.4.jar) 
antiidconflict{1.3.5} [Anti Id Conflict] (AntiIdConflict-1.3.5-1.7.10.jar) 
ArchitectureCraft{1.7.2} [ArchitectureCraft] (ArchitectureCraft-1.7.2-mc1.7.10.jar) 
bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
BinnieCore{2.0.22.7} [Binnie Core] (binnie-mods-1.7.10-2.0.22.7.jar) 
Botany{2.0.22.7} [Botany] (binnie-mods-1.7.10-2.0.22.7.jar) 
ExtraTrees{2.0.22.7} [Extra Trees] (binnie-mods-1.7.10-2.0.22.7.jar) 
Genetics{2.0.22.7} [Genetics] (binnie-mods-1.7.10-2.0.22.7.jar) 
ExtraBees{2.0.22.7} [Extra Bees] (binnie-mods-1.7.10-2.0.22.7.jar) 
Botania{r1.8-249} [Botania] (Botania-r1.8-249.jar) 
shadowfox_botany{0.1.20} [Botanical Addons] (BotanicalAddons-r0.1.20-1.jar) 
CarpentersBlocks{3.3.8.2} [Carpenter's Blocks] (Carpenter's-Blocks-v3.3.8.2---MC-1.7.10.jar) 
MineTweaker3{3.0.13} [MineTweaker 3] (CraftTweaker-1.7.10-3.0.13.jar) 
PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.7.10.jar) 
props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.7.10.jar) 
ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
tc{4.4.1_020} [Traincraft] (Traincraft-4.4.1_020.jar) 
Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
MagicBees{2.4.4} [Magic Bees] (magicbees-1.7.10-2.4.4.jar) 
MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
DragonAPI{v24c} [DragonAPI] (DragonAPI-1.7.10-V24c.jar) 
druidry{2018.6.16-1.7.10} [§2Druidry] (druidry-2018.10.11-1.7.10.jar) 
MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks-MoCreatures-Mod-v6.3.1.zip) 
endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
exoticbirds{1.0} [Exotic Birds] (Exotic-Birds-1.7.10-1.4.6.jar) 
extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b200.jar) 
harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's-HarvestCraft-1.7.10Lb.jar) 
ExtraTiC{1.4.6} [ExtraTiC] (ExtraTiC-1.7.10-1.4.6.jar) 
fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
ForbiddenMagic{1.7.10-0.575} [Forbidden Magic] (Forbidden-Magic-1.7.10-0.575.jar) 
GardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar) 
GardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar) 
GardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar) 
GardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar) 
GeoStrata{v24a} [GeoStrata] (GeoStrata-1.7.10-V24a.jar) 
GollumCoreLib{2.0.0} [Gollum Core Lib] (Gollum-Core-Lib-1.7.10.jar) 
gud_thaumicnei{1.3.0} [Thaumic NEI] (gud_thaumicnei-1.3.0.jar) 
guideapi{1.7.10-1.0.1-23} [Guide-API] (Guide-API-1.7.10-1.0.1-23.jar) 
HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) 
IC2-Classic-Spmod{0.0.0.0} [IC2 Classic Detection Helper] (IC2Classic-Version-1.2.2.0.jar) 
IGWMod{1.1.12-34} [In-Game wiki Mod] (IGW-Mod-1.7.10-1.1.12-34-universal.jar) 
immersiveintegration{0.6.8} [Immersive Integration] (immersiveintegration-0.6.8.jar) 
trackapi{1.2} [Track API] (TrackAPI-1.2.jar) 
immersiverailroading{1.7.2} [Immersive Railroading] (ImmersiveRailroading-1.7.2_1.7.10.jar) 
universalmodcore{1.0.0} [UniversalModCore] (ImmersiveRailroading-1.7.2_1.7.10.jar) 
inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
JammyFurniture{5.0.0 [Build Smeagol]} [Jammy Furniture Mod] (Jammy-Furniture-Reborn-Mod-1.7.10.jar) 
journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
Mekanism{9.1.1} [Mekanism] (Mekanism-1.7.10-9.1.1.1031.jar) 
modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar) 
MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
neresources{0.1.0.ManuallyBuilt} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0-122.jar) 
desertcraft{1.7.2b} [Pam's DesertCraft] (Pam's-DesertCraft-1.7.10a.zip) 
randomplants{1.7.2a} [Pam's RandomPlants] (Pam's-Random-Pants-1.7.2a.zip) 
temperateplants{1.7.2b} [Pam's Temperate Plants] (Pam's-Temperate-Plants-1.7.2b.zip) 
ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
SolarExpansion{1.6a} [Solar Expansion] (SolarExpansion-Basic-1.6a.jar) 
StorageDrawersBop{1.7.10-1.1.1} [Storage Drawers: Biomes O' Plenty Pack] (StorageDrawers-BiomesOPlenty-1.7.10-1.1.1.jar) 
StorageDrawersForestry{1.7.10-1.1.2} [Storage Drawers: Forestry Pack] (StorageDrawers-Forestry-1.7.10-1.1.2.jar) 
StorageDrawersMisc{1.7.10-1.1.2} [Storage Drawers: Misc Pack] (StorageDrawers-Misc-1.7.10-1.1.2.jar) 
StorageDrawersNatura{1.7.10-1.1.1} [Storage Drawers: Natura Pack] (StorageDrawers-Natura-1.7.10-1.1.1.jar) 
thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
thaumicenergistics{1.1.3.0} [Thaumic Energistics] (thaumicenergistics-1.1.3.0.jar) 
ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
thebetweenlands{1.0.6-alpha} [The Betweenlands] (TheBetweenlands-1.0.6-alpha-universal.jar) 
ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
TMechworks{0.2.15.106} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.15.106.jar) 
traindieselfix{1.0.0} [Train Diesel Fix] (traindieselfix-1.0.0.jar) 
WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
wailaplugins{MC1.7.10-0.2.0-25} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.2.0-25.jar) 
wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
witcherypatch{1.0.0} [WitcheryPatch] (WitcheryPatch-1.7.10-1.0.0.jar) 
McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
aobd{2.9.2} [Another One Bites The Dust] (AOBD-2.9.2.jar) 
ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)

**Comment by OvermindDL1** [comment]
Actually I don't think it's related to DragonAPI.  DragonAPI is only in the callstack there to set up it's shaders but it doesn't do anything with the batcher/Tesselator there...

Does it work if you remove *just* Reika's mods?  That would tell for sure.  What about if you run 'just' Reika's mods?

**Comment by thaarael** [comment]
Actually, after meddling for a while, it seems to be problem with Optifine compatibility. As soon as I changed Chunk Loading from Smooth (which I used before - thats why I supposed it's Dragon's issue, since I was playing on this pack for a longer while now without any large issues, and only recently decided to enhance it further with GeoStrata, Druidy and Immersive Railroading) to Deafult, problem ceased. 
Sorry for all the mess, I panicked a bit since I am making gameplays on this pack (nobody is watching them anyway, but...), and rushed for help without double checking every other possibility :/
But anyway, it should be noted that sollution is to change Chunk Loading to Deafult on Optifine.

**Comment by OvermindDL1** [comment]
Optifine does a significant amount of alterations to the entire rendering engine in MC, so it breaks a *lot* of things.  They have to constantly fix things by releasing new versions, lol.

**Comment by OvermindDL1** [comment]
I'll close this then since you resolved it.  If any more questions, just ask here.  :-)

**Comment by ReikaKalseki** [comment]
Only a few OF versions work in modded.

**Comment by OvermindDL1** [comment]
> Only a few OF versions work in modded.

Would you happen to have a list of these somewhere that I could point people to?  GT6 keeps a good list of such things that makes it easy to point people toward and it is a *huge* help!

**Comment by ReikaKalseki** [comment]
I only know for sure of the one I use - `OptiFine_1.7.10_HD_C1`.

**Comment by Barhandar** [comment]
`OptiFine_1.7.10_HD_U_D6` also worked in the "let's take all three of the super-long-loadtime mods and put them in a single pack!" Ascension of the Technomancer; but D8 does _not_.
