### ISSUE TITLE
init crash on update to v24 from v23

### ISSUE THREAD

**Issue by floven1** [ReikaKalseki/Reika_Mods_Issues#2286]
the title and crash report are pretty self-explanatory, more information can be provided as requested
[crash-2020-01-08_19.11.40-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4038334/crash-2020-01-08_19.11.40-client.txt)

**Comment by floven1** [comment]
almost forgot, there's also this incompatability with aether
[crash-2020-01-08_19.05.39-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4038339/crash-2020-01-08_19.05.39-client.txt)

**Comment by ReikaKalseki** [comment]
I need to know what mods.

**Comment by floven1** [comment]
<details> <summary>functional modlist screencaps</summary>
![image](https://user-images.githubusercontent.com/19882085/72207284-16f15280-3455-11ea-9125-5989f07956d7.png)
![image](https://user-images.githubusercontent.com/19882085/72207298-35efe480-3455-11ea-87b8-e49d59cc4d75.png)
![image](https://user-images.githubusercontent.com/19882085/72207324-5ddf4800-3455-11ea-9941-45a9a9107488.png)
![image](https://user-images.githubusercontent.com/19882085/72207340-7ea79d80-3455-11ea-86b1-941087e5cfa3.png)
</details>

this is the modlist of the pack in a functional state (i reverted it so I could still play while we figure this out)
<details> <summary>updated/added mods screencap</summary>
![image](https://user-images.githubusercontent.com/19882085/72207390-f970b880-3455-11ea-8844-a757d4c8aaa4.png)
</details>
these are the mods added, replacing their older versions (except for voidmonster which is straight up removed due to the difficulty it creates in the upper nether)

<s>side note: is there a way to add spoilers?</s> thanks to OvermindDL1

**Comment by OvermindDL1** [comment]
> side note: is there a way to add spoilers?

<details>
<summary>Yes</summary>
Click the `Add Collapsible content` button on the toolbar, or just type out:

<br><code>
&lt;details>
&lt;summary>Title here&lt;/summary>
Stuff here
&lt;/details>
</code>

</details>

Also, pictures of the mods is painful, better to upload the full `fml-client-latest.log` instead, which contains both the mod list, error crash, and other useful logs.

**Comment by floven1** [comment]
post aether removal crash:
[fml-client-latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4080083/fml-client-latest.log)

aether crash:
[fml-client-latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4080077/fml-client-latest.log)


much appreciated OvermindDL1

what's in the fml logs thats not in the posted crash reports btw?

**Comment by OvermindDL1** [comment]
It looks like some mod has altered EntityRenderer while DAPI is also trying to do the same:
```java
Caused by: Reika.DragonAPI.Exception.ASMException$NoSuchASMFieldInstructionException: Error ASMing method func_78467_g (F)V in net/minecraft/client/renderer/EntityRenderer:
Could not find an instruction for a field call to [unspecified]'s field_78490_B:
Found field calls:
    PUTFIELD net/minecraft/client/renderer/EntityRenderer.field_78500_U : Z
```

**Comment by ReikaKalseki** [comment]
Is this the Betweenlands issue again?

**Comment by floven1** [comment]
might be... betweenlands is in the pack

**Comment by floven1** [comment]
will do some tests

**Comment by floven1** [comment]
yep, removing betweenlands (and aether) fixed the issue

I really appreciate your help with this reika and overmind

**Comment by ReikaKalseki** [comment]
#2255
