### ISSUE TITLE
[V24d/TiC/P:R] Flakes that smelt into multiple items in normal furnace still only smelt into equivalent of 1.5 ingots of fluid in the Smeltery

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#2288]
Full disclosure: I only checked redstone flakes, but it probably applies to all of them that can both be processed in smeltery and furnace-smelt into more than one item.

Redstone flakes normally smelt into 4 redstone dust. Project:Red adds a recipe to smelt 1 redstone dust to 144 mB liquid redstone (1 ingot's worth) to the smeltery. Redstone flakes smelt into 216 mB (1.5 ingots) of liquid redstone, while they should be smelting into at least 576 mB (4 ingots), more likely 864 (6 ingots, 4*1.5).

Additionally liquid redstone (`redstone.molten`)'s ONLY use is alloying into molten conductive redmetal; it CANNOT be turned back into redstone dust. As such flakes should probably be smelting into 600 mB (base 100, not 144) of TE Destabilized Redstone (`redstone`) instead, which _can_ be turned back into dust with Fluid Crystallizer.

**Comment by ReikaKalseki** [comment]
I fixed the amount issue like two days ago.
