### ISSUE TITLE
Not enough ingame hints for progression.

### ISSUE THREAD

**Issue by EreticKB** [ReikaKalseki/Reika_Mods_Issues#2289]
There really not enough information in Chromic Lexicon. I play many days and fly around so much (thousand blocks away my home) and still never meet ethereal luma and glowing tower. Also i craft Aura Tracker many days ago, in my chromic lexicon 159 pages now, but still no any hint how to charge it. So it useless stick now.

**Comment by ReikaKalseki** [comment]
The luma is not gating until late game, the towers never are, and there is a method-of-charge indicator on the item itself.
