### ISSUE TITLE
[v24d ChC/Buildcraft] Volume Definition Point is inferior to Land Mark

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#2291]
It still requires block support unless anchored, anchoring requires right-clicking it with manipulator (note that at least some other "transient" Chroma constructs are _picked up_ by sneak-right click) and makes it semi-unbreakable - requiring non-player means of removal such as block breaker - and to top it all off it doesn't have ability to show alignment axii, rendering placing matching VDPs an exercise in coordinate-writing-downery, having to place blocks up to the entire 256 distance, or guessing until you place one in a correct spot and it forms the box visuals.

Note that aformenentioned semi-unbreakability, combined with early-game nature and cheapness of VDP, makes it a _spectacular_ griefing tool - place a bunch around a player who doesn't have means of teleporting and they're fucked.

P.S. Additionally, with (alleged) bug that makes quarry destroy TPS if it has to break blocks for placing the frame, VDP will likely trigger that bug unless player goes and removes them personally.  
P.P.S. VDP could be made better with minimal changes if it can be broken or unanchored with sneak-clicking on it by the manipulator. This will still leave it dropping without support for some reason, however.

**Comment by Barhandar** [comment]
Github is being dumb and I need to go so I can't make it stop being dumb, so I can't edit the issue. The title was suppposed to end with "...and can be used for griefing". Additionally, with (alleged) bug that makes quarry destroy TPS if it has to break blocks for placing the frame, VDP will likely trigger that bug unless player goes and removes them personally.

**Comment by ReikaKalseki** [comment]
The questions of support and axes are valid, though I do not have a good solution.

The fixed-ness is intentional; the lexicon description gives more information on that.

As for the griefing potential, I can easily fix that with something like making them have no collision (they were not supposed to in the first place).

**Comment by ReikaKalseki** [comment]
I implemented the lack of collision, and an axis visualization.
