### ISSUE TITLE
GeoStrata Thaumcraft Aspects

### ISSUE THREAD

**Issue by LukaPix** [ReikaKalseki/Reika_Mods_Issues#2293]
Hey, i think DragonAPI crashes trying to add thaumcraft aspects to some geostrata items.
I am running Optifine and Fastcraft and removed those for Testing, they didn't make a Difference.
[Crashreport](https://gist.githubusercontent.com/LukaPix/e674df40844ce825b303ddc5390375b8/raw/f20b3a75fee8a4d2bceb83956ef1fe9cd6d12b6f/crashreport.txt)

**Comment by LukaPix** [comment]
Maybe this helps, it happens when check enviroment sanity in DragonAPI is true.
`Reika.DragonAPI.Exception.EnvironmentSanityException: thaumcraft.common.blocks.BlockFluxGas@5523b9be (class thaumcraft.common.blocks.BlockFluxGas) returns an invalid (null) value for a critical field or function ('Null-fluid fluid block')!`

**Comment by ReikaKalseki** [comment]
I use GeoStrata and TC together without issue, and I know the aspect code normally works.

Additionally, the error being caught by the sanity checker is either an artifact of your installation or a bug in TC.

**Comment by ReikaKalseki** [comment]
Moreover, that missing field means you are using a different version of the TC API, which must mean a wildly old or too-new-for-the-game-version version of TC.

**Comment by LukaPix** [comment]
Well, which version exactly would you recommend, i am running the last 1.7.10 Thaumcraft release 4.2.3.5
What do you mean by "artifact of my installation" are there caches or something i could clear?

**Comment by ReikaKalseki** [comment]
I use 4.2.3.5 with no issues.

**Comment by OvermindDL1** [comment]
@LukaPix Can you toss over that Thaumcraft jar you are using?  I'm curious to examine it, something seems odd about it...

**Comment by Ushupiuck** [comment]
I should also add to this, that reducing this to a minimalistic environment with just DragonAPI, Chromaticraft, Thaumcraft & Thaumic fixer also causes the crash shown above. Removing/disabling Thaumic fixer fixes the Issue and allows the game to run. However! if sanity check is set to true in the config...

> 
> 
> Maybe this helps, it happens when check enviroment sanity in DragonAPI is true.
> `Reika.DragonAPI.Exception.EnvironmentSanityException: thaumcraft.common.blocks.BlockFluxGas@5523b9be (class thaumcraft.common.blocks.BlockFluxGas) returns an invalid (null) value for a critical field or function ('Null-fluid fluid block')!`

This exact error/crash happens.
