### ISSUE TITLE
RotaryCraft ClassCast Exception with World Rift Power Transfer

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2294]
I had a microturbine going into a world rift so I could power a reactor CPU on the moon, but the Reactor CPU would not work. It looked as though it had power, but never did anything. Upon checking the logs, I found many, many lines of these two errors, with the second shorter one being much more prevalent than the first one. Then I switched to a creative coil on site, at which point I think the error switched types to the second shorter one.
[errors.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4081296/errors.txt)

**Comment by ReikaKalseki** [comment]
This has nothing to do with the shaft power; somehow you have a rift bound to a position with a non-rift at that tile.

**Comment by voidsong-dragonfly** [comment]
I have absolutely no clue how that happened.....

**Comment by ReikaKalseki** [comment]
Nor do I.
