### ISSUE TITLE
Critterpet no more enemy indicies left

### ISSUE THREAD

**Issue by NuclearAtoms** [ReikaKalseki/Reika_Mods_Issues#2295]
This happens everytime I pair Flans with Critterpet. I've already reported it on the flans github and they don't support 1.7.10 https://pastebin.com/yrv8Y6df

**Comment by ReikaKalseki** [comment]
Flans is apparently using all the entity IDs in the game. That is not quite a *bug* per se, but it *is* on their end. There is nothing I can do about that.

**Comment by NuclearAtoms** [comment]
Well, crap.

**Comment by NuclearAtoms** [comment]
If anyone is having this problem in the future, I just used the latest flans version and that seemed to do the trick.
