### ISSUE TITLE
suggestion for mod interaction: bedrockium to bedrock dust

### ISSUE THREAD

**Issue by floven1** [ReikaKalseki/Reika_Mods_Issues#2296]
for an interaction with extra utilities 2, use the bedrock grinder to grind bedrockium(or some level of compressed cobblestone) to generate greater amounts of bedrock dust than vanilla bedrock
(also, a recipe for the bedrockium drum involving bedrock ingots, maybe even in the blast furnace, would be nice, although I don't know how much that fits with your vision for rotarycraft)

**Comment by ReikaKalseki** [comment]
Bedrock is not simply N-compressed cobble.

**Comment by floven1** [comment]
could argue that point, bedrock being at the bottom of the world where the pressure from the rock above would be enormous, however, the main reason I suggest this is because it would supply an alternate means of obtaining bedrock dust in large quantities as the usual method can cause problems with loading faraway chunks (I know this from experience), and with higher levels of compressed cobblestone being relatively hard/time consuming to obtain, I figured it would be a good option

**Comment by ReikaKalseki** [comment]
Loading a chunk from time to time like the breaker does is not a big deal on performance.

**Comment by floven1** [comment]
not really... until you add in traincraft, or any other mod which adds self-chunkloaded worldgen (granted I have doubts about the sanity of anyone who decides this is a good idea, but it looks like a possible oversight in this case) or any mod that has a possibility to cause cascading worldgen
