### ISSUE TITLE
StackOverflowError: Exception while updating neighbours

### ISSUE THREAD

**Issue by shagejack** [ReikaKalseki/Reika_Mods_Issues#2297]
This error just appears randomly when generating new chunks and causes server to crash.
And server crashes again when the player load the chunk.
Any idea to fix it?
crash-report:
https://paste.ubuntu.com/p/9xFSGyYyzT/

**Comment by ReikaKalseki** [comment]
I have never seen this before, and none of the code involved is new (most of it is from 2014 or early 2015).

Does it happen reliably?
