### ISSUE TITLE
DAPI V24C makes  tome of alkahestry not worked

### ISSUE THREAD

**Issue by Nightmare8591** [ReikaKalseki/Reika_Mods_Issues#2298]
as title
when you installed Reliquary and DAPI then tome of alkahestry will be not work.

**Comment by ReikaKalseki** [comment]
That is nowhere near enough information.

**Comment by Nightmare8591** [comment]
ah,at first,if i only installed Reliquary,then tome of alkahestry is funtion normally
but after i installed DAPI,tome of alkahestry becomed broken,it stilled cousumed redstone or glowstone
but all duplication recipe couldn't work.

**Comment by ReikaKalseki** [comment]
What is a Tome of Alkahestry? What does it do?

**Comment by Barhandar** [comment]
It adds recipes (presumably dynamically and tripping your null inquisition code) to duplicate resources using a "reagent", e.g. 1 dirt to 17 dirt at the cost of 1 redstone.

**Comment by EricPfau** [comment]
I am having this same problem. To provide more information to you Reika, the Tome of Alkahestry is an item added by another mod (https://www.curseforge.com/minecraft/mc-mods/reliquary-v1-3). DragonAPI seems to break its recipes and as "Disallow Null-Item ItemStacks to Prevent Crashes" does not seem to be fully implemented yet it breaks this item entirely. This is similar to https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1214 . Crossing my fingers this might be something you can fix.

**Comment by ReikaKalseki** [comment]
OK, I will reopen that issue.
