### ISSUE TITLE
ReactorCraft Radiation Turns Electrical Age Circuits to Dead Bushes

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2299]
Electrical Age circuit parts are apparently registered as Material.PLANTS, meaning that they pop off and turn to dead bushes if the area they are in comes into contact with radiation. If possible, could you implement a blacklist for the block that contains them? The block is `Eln:Eln.SixNode` with any metadata.

**Comment by ReikaKalseki** [comment]
I need something that is not a direct reference, like a class name or an interface.

**Comment by voidsong-dragonfly** [comment]
https://github.com/jrddunbr/ElectricalAge/blob/1.15.x-stable/src/main/java/mods/eln/node/six/SixNode.java Here's the SixNode class, Reika

**Comment by ReikaKalseki** [comment]
Done.
