### ISSUE TITLE
Chromaticraft crash / Lumen relay

### ISSUE THREAD

**Issue by Looma-mc** [ReikaKalseki/Reika_Mods_Issues#23]
Hi,

i got this crash on my server while playing around with omni lumen relay.

first crash:
http://pastebin.com/Ab5SYmzR
crash on restart:
http://pastebin.com/wxz39APm

server was in a restart cycle. i managed to get in fast and remove the omni lumen relays. i think it started when i right-clicked to often on those things with the wand, but i cannot say.

i was trying to power the elemental farmer via omni relays from the relay source. do they need a direct line (only x or y or z changes) or do they work like repeaters? what DOES the wand do to those relays anyway?

latest version of reikas mods are installed.

**Comment by ReikaKalseki** [comment]
I take it you made a loop of relays? This should be an easy fix.

**Comment by ReikaKalseki** [comment]
Fixed.
