### ISSUE TITLE
Multiple Reikas Mods issues, Renderer, Lag & Removal of Disable Alpha Clipping?

### ISSUE THREAD

**Issue by brandyyn** [ReikaKalseki/Reika_Mods_Issues#2302]
Since i'm not getting a reply on discord i guess i gotta submit the issues here.

1: Did you change anything in the renderer for your mod since I'm getting a lot of new issues since the last time I updated.

This is a screenshot of an Actually Additions "Solidified Experience"
With your mods: https://i.imgur.com/UapjJwE.jpg
Without your mods: https://i.imgur.com/l7i6ge3.jpg

i dont know if this is to do with any changes you've made but i've been seeing a lot more odd things since i updated your mods
https://i.imgur.com/NEyjzar.jpg
as you can see the pure black shadow and the villager being really really bright
there are also black shadows under orbs now https://i.imgur.com/Q6sMwcx.png
never seen those before
look how bright villagers are https://i.imgur.com/yUv5dm2.jpg
it wasnt like this before

this is a clean install with just your mods and actually additions
https://i.imgur.com/CdXyUpH.png

also you removed "B:"[DB20D45DD] Disable Alpha Clipping in WorldRenderer"=true" from the configs? how come? I thought it was meant to be a performance boost option

and that ties into my next point too; im getting heavy stuttering with JUST your mods installed, no others and its not present without them.

Happy to help debug in any way just let me know how I can help!

**Comment by brandyyn** [comment]
I forgot to mention, I tried with and without the launch option "-DragonAPI_ForceAlphaClip" to see if it made a difference with the rendering issues, It did not. 

also I don't know if this means anything or if its just a replacement for some type of renderer or what but i'm using warmroast and your mod is showing up in the categories; no clue what it means but maybe its worth a look https://i.imgur.com/59G4VpX.png

**Comment by Skyler-Altol** [comment]
@brandynn try removing ChromatiCraft and see if your issues persist. There was a significant overhaul in DragonAPI that removed the above flag, and replaced it with another solution that means the "performance boost" that flag gives is always enabled now, hence why the flag was removed. However, @OvermindDL1 and I are currently trying to debug performance issues related to ChromatiCraft simply being present in the installed mods.

**Comment by brandyyn** [comment]
I don't have chromaticcraft. 
My Reika mods: 
ExpandedRedstone 1.7.10 24a
ElectriCraft 1.7.10 V24a
RotaryCraft 1.7.10 V24C
DragonApi 1.7.10 V24c

**Comment by Skyler-Altol** [comment]
@brandynn if you could please give me a full list of your hardware specs, that'd be appreciated. CPU, Memory, Graphics Card, etc.

**Comment by brandyyn** [comment]
ofcourse, anything for you ;)

GPU: Nvidia GTX 1060 6GB
CPU: AMD Ryzen 7 2600
RAM: 16GB Corsair Vengeance 3200Mhz
OS: Windows 10
Storage: 4TB HDD & 2TB HDD
MOBO: X470 Gaming Pro

**Comment by Skyler-Altol** [comment]
How much ram are you allocating to the game? Also, are you using the G1GC garbage collector? Also, playing the game on HDDs means your chunk loading / generation is going to be impeded. Would recommend an SSD for a major boost in whole system performance, including all of your games.

**Comment by brandyyn** [comment]
As i said, There are no issues unless i use Reikas mods(which are integral to my pack)- I have 4gb of ram allocated, my pack only uses 2gb and performance doesnt change no matter how much I allocate(the only difference in performance is with reikas mods vs without) either way, this isnt only about performance and more about the rendering issues that are taking place.

**Comment by Skyler-Altol** [comment]
I need the list of arguments you're using to run the game @brandynn. While the arguments are not relevant to the rendering, they almost certainly could be related to the performance issues you're seeing.

**Comment by brandyyn** [comment]
-Xmx 4gb and no others. I tried with the force alpha clip launch command to but it didn't change anything.

**Comment by Skyler-Altol** [comment]
@brandynn try it with these arguments and see if the performance stuttering you're seeing goes away:

-Xms4G -Xmx4G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled

These are what I use when I'm doing performance testing of Reika's stuff, and right now without ChromatiCraft, on a Ryzen 3700X and a GTX 1070, I'm getting close to 400-500 fps at any given moment. 

The rendering issue will be more difficult to diagnose. As for the flag you referred to, as I said, that flag no longer exists, therefore putting it in will do nothing because it doesn't exist.

**Comment by brandyyn** [comment]
I can test it, but if it does work I still see that as an issue since I don't want ever player who plays my pack to have to enter launch options, and is it not sort of an issue that you'd need launch options for something that should run well without it anyway?

**Comment by Skyler-Altol** [comment]
It is a known thing that the G1GC performs significantly better in minecraft than the default garbage collector of Java 8, which is the CMS.

**Comment by brandyyn** [comment]
@ReikaKalseki This also may help with performance debugging, not completely sure but it may help: https://i.imgur.com/pbghDT1.png

**Comment by brandyyn** [comment]
> It is a known thing that the G1GC performs significantly better in minecraft than the default garbage collector of Java 8, which is the CMS.

i can try it but still i shouldn't have to add launch commands.

**Comment by Skyler-Altol** [comment]
Asking Reika to work around the problems of an ancient garbage collector is entirely unreasonable when the fix takes literally 3 seconds of effort on your part, which never has to be repeated unless you delete the installation. Furthermore, the default vanilla launcher installation *comes* with the G1GC arguments by default. 

As of a recent version of the minecraft launcher, the following arguments come with the vanilla launcher profiles:

 -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M

**Comment by brandyyn** [comment]
As I said previously, It's not about ME, it's about the players of my pack; they shouldn't have to go and add a launch command to play properly, it should be plug and play.

**Comment by Skyler-Altol** [comment]
You're apparently not hearing me. By **_*default*_** the vanilla launcher comes with the arguments I just specified. **A player would have to explicitly remove them for them to not be there**, or use another launcher. If they're using another launcher, it becomes their responsibility to optimise their performance via the JVM arguments if that launcher does not come with any arguments by default.

**Comment by voidsong-dragonfly** [comment]
It is _quite literally_ one of the **_most basic options_** of the JVM, the thing that runs behind Minecraft and other Java applications. There is _no way on Earth_ Reika can change _anything_ to do with that.

**Comment by brandyyn** [comment]
Well then it's already being used so I don't see the big deal?

**Comment by brandynn** [comment]
@ReikaKalseki - The Bedrock breaker doesn't have any texture ingame https://i.imgur.com/L4aSNGQ.png

**Comment by brandyyn** [comment]
Nevermind, if you saw my comment I deleted, it was an error on my part.

**Comment by Skyler-Altol** [comment]
@brandynn the big deal here is, you said you're not using those default arguments when you posted. So when I asked you to do the tests with the G1GC to see if the performance issues went away, that's why, because the default Java GC for Java 8 is *not* the G1GC, but the default arguments provided with minecraft explicitly tell the JVM to use the G1GC.

**Comment by brandyyn** [comment]
Then it should be using G1GC by default, i'm on the technic launcher because I like to seperate my instances depending on what i'm working on, but sure, i'll test it just incase the technic launcher doesn't already have it built in(which it should)- and i'll get back to you i guess.

**Comment by brandyyn** [comment]
I crashed and it seems to be due to the renderer

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at Reika.DragonAPI.Extras.ThrottleableEffectRenderer.doRenderParticles(ThrottleableEffectRenderer.java:192)
    at Reika.DragonAPI.Extras.ThrottleableEffectRenderer.func_78874_a(ThrottleableEffectRenderer.java:160)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1275)
    at Reika.DragonAPI.ASM.ASMCalls.onRenderWorld(ASMCalls.java:72)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[crash-2020-01-27_02.16.41-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4115288/crash-2020-01-27_02.16.41-client.txt)
[fml-client-latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4115294/fml-client-latest.log)

**Comment by Skyler-Altol** [comment]
Does that crash happen consistently? We're looking into it.

**Comment by brandyyn** [comment]
I think thats the first time it's occured for me.

**Comment by brandyyn** [comment]
another rendering issue with your mods installed( doesnt happen without ) black pixels on porkchop only when holding / on floor, not in inventory. https://i.imgur.com/r9wtFcP.jpg

**Comment by brandyyn** [comment]
I crashed while playing and the only thing it really links to is again Reika's mods (Never seen this type of crash before and there's nothing note worthy in the logs and I can't upload the log since it's too big) 
[crash-2020-02-15_15.48.51-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4208686/crash-2020-02-15_15.48.51-client.txt)

**Comment by brandyyn** [comment]
This crash happened straight after that one, this time on world creation: 
[crash-2020-02-15_16.20.21-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4208747/crash-2020-02-15_16.20.21-client.txt)

notable part from the log: https://pastebin.com/tUukaDpw

**Comment by Skyler-Altol** [comment]
The first crash you've linked is COFH's issue, not Reika's. Something in that light code decided to crap the bed, and is not within Reika's domain.

The second crash regarding the ThrottleableEffectRenderer, Overmind and I have been trying to convince Reika to implement a better solution for that, that would solve not only this issue, but multiple others, but have had limited success so far. That is likely to be an intermittent issue, and will not happen constantly.

**Comment by brandyyn** [comment]
The first crash does seem to be linked to DragonAPI's renderer- but I wouldn't know

**Comment by Skyler-Altol** [comment]
The only thing related to Reika in that crash is this:

at Reika.DragonAPI.Instantiable.Event.Client.RenderBlockAtPosEvent.fire(RenderBlockAtPosEvent.java:63)

This is simply an event being fired when a block gets rendered. That is not the source of the issue, whatsoever.

**Comment by OvermindDL1** [comment]
For that first error it's referencing indexing into the CoFH TF array of `public static final int[] LIGHT = { 0, 0, 4, 0, 0, 4, 8 };` at index `11`, which obviously doesn't exist.  This is called through a path of vanilla minecraft world rendering functions.

I.E. I'm 85% certain that it is caused by a corrupted block (not necessarily a corrupted world, but could be caused by a variety of things like a chance chunk regeneration between a block and metadata set packets or so).  CoFH TF shouldn't be crashing for this as this condition is possible to happen in the vanilla MC engine.  It is CoFH TF's bug.

**Comment by brandyyn** [comment]
Okay, thanks for the extra knowledge!

**Comment by brandyyn** [comment]
Yo so, the issue still hasn't been fixed in the new updates (25b) https://i.imgur.com/HYKb8vJ.jpg
as you can see in the image, the white is still there and there's still that weird shader issue you can see here: https://i.imgur.com/fI1ejM3.jpg

**Comment by brandyyn** [comment]
this is just with dragonapi: https://i.imgur.com/70kRRWG.png

**Comment by brandyyn** [comment]
https://i.imgur.com/APCwKqf.png

**Comment by OvermindDL1** [comment]
Yeah the mask test that dapi changes is still wrong (too expansive).

**Comment by brandyyn** [comment]
What is that exactly? And is that what's adding the pixels to the items or
affecting the rendering?

**Comment by OvermindDL1** [comment]
In general yes, unless you have some other mod affecting those, DAPI does do substantial changes to rendering.

**Comment by brandyyn** [comment]
Is it likely to be fixed soon?

**Comment by ReikaKalseki** [comment]
DAPI does not add random pixels to items.

**Comment by brandyyn** [comment]
As I said, and showed you in discord, Literally only DAPI installed there
is pixels added, and without it everything is fine.

**Comment by OvermindDL1** [comment]
> DAPI does not add random pixels to items.

Correct, but it does change the GL state, and those pixels look like the mask settings aren't set correctly in the GL state.

**Comment by brandyyn** [comment]
Still not fixed :/ https://i.imgur.com/yOVaGDH.jpg (DragonAPI+1.7.10+V26b)

**Comment by brandyyn** [comment]
interesting note: optifine fixes the issue, but that's not really good enough as you're not allowed to redistribute optifine(to my knowledge), and even still it's imcompatible with a few things in my pack. i assume when you tested it @ReikaKalseki that you played with optifine.

**Comment by ReikaKalseki** [comment]
Not in my dev environment.

**Comment by brandynn** [comment]
Couple things:

Reika's mods don't work with SereneSeasons-1.7.10-1.2.18.jar, just crashes, it's fine by itself.
Error messages:
[message.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5330941/message.txt)
[message (1).txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5330942/message.1.txt)

Reika's mods also don't work with a mod called "Loading Profiler"
https://www.curseforge.com/minecraft/mc-mods/loading-profiler
[crash-2020-10-04_18.06.56-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5330944/crash-2020-10-04_18.06.56-client.txt)

also whatever you changed with GL State and the masks settings not working so i get white pixels on items, like i've mentioned many times

**Comment by brandyyn** [comment]
couple things,
are we able to run thermos/cauldron with your mods yet or is that still a no go?
all i want to do is host a faction server with my pack which includes your mods :P

also,
DragonAPI: Expanded armor handling
does this fix armour invincibility?
does it remove the armour cap when you're above a certain armour amount, similar to attributefix for later versions?

will that GL mask state ever be fixed? It's been nearly a year and a half and it's still a thing :/

**Comment by OvermindDL1** [comment]
> thermos/cauldron

Not supported, too many ASM changes that don't take that into account, [GT6's](https://gregtech.overminddl1.com/) do however if you're wanting to experiment with a giant tech mod on such systems.

**Comment by brandyyn** [comment]
i dont really see how it would break bukkit compatibility.

I assumed that 
> DragonAPI: Expanded armor handling 
would have fixed the armour cap invincibility but it doesn't, so what exactly does it do?

The GL mask state issue is still a problem for me and my friends, not sure why this still hasn't been fixed? have you guys not been able to replicate it? It doesn't show up when using optifine but I can't use optifine in my pack sadly. Again this happens most obviously with the Actually Additions Solidified Experience.

**Comment by brandyyn** [comment]
also #2581 is still an issue
[latest1.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6796308/latest1.txt)

**Comment by brandyyn** [comment]
happened again actually, this time i believe it's from divinerpg sharks
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6796323/latest.log)

**Comment by brandyyn** [comment]
https://i.imgur.com/VAmsWrq.png

**Comment by DDRAIGOCH117** [comment]
I know this is two years later, but do you remeber wich mods is your red sword from? The one in most of your pics @brandyyn

**Comment by brandyyn** [comment]
> I know this is two years later, but do you remeber wich mods is your red sword from? The one in most of your pics @brandyyn

It's the assassin sword from RPG Inventory

**Comment by DDRAIGOCH117** [comment]
Ty very much for your quick response!
