### ISSUE TITLE
[ChC/TC] The 6000 vis storage, all of it self-regenerating wand core doesn't actually require lumens to recharge

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#2305]
Unless you have really bad practice of "crashing the caller function", this piece of code does not care at all about whether it was able to drain any lumens from the player and will regenerate vis in the wand regardless.  

https://github.com/ReikaKalseki/ChromatiCraft/blob/master/ModInterface/ThaumCraft/CrystalWand.java#L101-L110

Also, 1 lumen per 10 vis? Seriously? That wouldn't be noticeable even if it _did_ actually require succeeding at draining lumens; player's basic storage cap is in the vicinity of 24k lumens and every pylon restores many thousands before depleting.

**Comment by ReikaKalseki** [comment]
The lack of validity checking is fixed.

You completely misunderstood the calculation for cost. It is in fact too low, but it is NOT "one lumen per 10 vis".
