### ISSUE TITLE
Chromatic Enchanter didn't check enchantments on items before enchanting

### ISSUE THREAD

**Issue by Prunoideae** [ReikaKalseki/Reika_Mods_Issues#2306]
![image](https://user-images.githubusercontent.com/24620047/73197800-ead01400-416c-11ea-84c0-f9e8b36051cd.png)

While re-enchanting tools, the enchanter didn't check conflicting enchantments between tools and the enchanter. Which caused the conflicting enchantments can be applied through Chromatic Enchanter if enchant the tool for multiple times.

As the image shown, the Looting V and the Repossesion IV, the Bane of Anthropods V, the Smite V and the Sharpness is present at the same time.

**Comment by ReikaKalseki** [comment]
The enchanter is explicitly intended to ignore normal enchant conflicts.
