### ISSUE TITLE
[ChC] Chroma Enchanter can only do conflicting enchantments one at a time

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#2309]
>The enchanter is explicitly intended to ignore normal enchant conflicts.

Meanwhile, if you're trying to, say, add Sharpness to a sword, the enchanter will _not_ increase level on Bane of Arthropods and Smite at all, that is, the + button with an enchant that conflicts with already non-zero-level one selected will make a sound, but that enchant will not increase in level.

**Comment by ReikaKalseki** [comment]
I do not understand what you mean.

**Comment by Prunoideae** [comment]
> I do not understand what you mean.

At my point of view, if a chromatic enchanter do ignore enchantment conflict, why multiple conflicting enchantments cannot be applied at one time?

**Comment by ReikaKalseki** [comment]
They can.

**Comment by Barhandar** [comment]
They cannot. Again, if I have non-zero levels of Bane of Arthropods selected in the UI, I cannot increase level of Smite or Sharpness at all, and vice versa - hence being unable to apply them simultaneously. If I have non-zero level of Fortune selected in the UI, I cannot increase the level of Silk Touch, and vice versa. Ditto armor enchantments.

Or if you want rephrasing, I cannot make unenchanted pickaxe have Silk Touch and Fortune **in a single action**, I have to apply one, reduce its level/reset the enchanter, then apply the other.

**Comment by ReikaKalseki** [comment]
Done.
