### ISSUE TITLE
Add option to disable (specific) shader effects

### ISSUE THREAD

**Issue by Cynosphere** [ReikaKalseki/Reika_Mods_Issues#2310]
For health related reasons (not personally). I saw a config value for "Epilepsy Mode" in Chromaticraft but looked at where it was used and only saw one use of it.

Specifically concerned about the research discovery shader.

**Comment by ReikaKalseki** [comment]
I fail to see how pixelation could cause a seizure; it is not like the screen is flashing.

**Comment by Cynosphere** [comment]
How is big blotches of pixels going into smaller ones not flashing the screen? I know it'll be biased based on what resolution people play at, screen sizes, etc, but even on my 23 inch ultrawide at 2560x1080 I find it pretty annoying depending on the lighting (both IRL and in game). But whatever, you do you then.
