### ISSUE TITLE
[RoC] Microturbine with Integrated Gearbox (next MTG) bug

### ISSUE THREAD

**Issue by EreticKB** [ReikaKalseki/Reika_Mods_Issues#2313]
When i place a MTG(Torque Mode) above a Engine Control Unit it tries speed up a MTG after it reach maximum speed which lesser then default 131072 rad/s and consume fuel as in "speed up mode" instead "stable mode".

**Comment by ReikaKalseki** [comment]
MTG?

**Comment by EreticKB** [comment]
> MTG?

MicroTurbine with integrated Gearbox. As i say into title. Also decent joke about acronyms. :)

**Comment by ReikaKalseki** [comment]
It turns out that this was not true - it is simply (yet another) case of the fact that turbines do not throttle as efficiently being mistaken as a bug.
