### ISSUE TITLE
DragonAPI is missing its ASM transformers. Crash while starting up minecraft.

### ISSUE THREAD

**Issue by jkw666666jkw** [ReikaKalseki/Reika_Mods_Issues#2316]
Crash while starting up minecraft. It said DragonAPI is missing its ASM transformers.
https://gist.github.com/jkw666666jkw/06a64f9f2b2a492656ba003ec9d79282

I reinsalled all of your mod but still crashed.

**Comment by jkw666666jkw** [comment]
that is the log. Here is the crash report
https://gist.github.com/jkw666666jkw/42b47fcd908fdf6c1366db610a891f5c

**Comment by ReikaKalseki** [comment]
As per the error; this is caused by something being wrong with your jar.

**Comment by Aivech** [comment]
@jkw666666jkw Redownload the latest versions of Reika's mods from curseforge and try again.

**Comment by NuclearAtoms** [comment]
I'm having the same problem. I've reinstalled DragonAPI three times now and it still isn't working.

**Comment by ReikaKalseki** [comment]
If something is not wrong with your MC setup, it should work fine, and indeed does for almost everyone.
