### ISSUE TITLE
[FR] Add Bedrock Alloy Immersive Engineering Drill Head

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2318]
As title says, add a bedrock alloy drill head for the IE drill. Unbreakable, and ~16 mining speed because heads have a greater mining speed than the respective pickaxes.

**Comment by voidsong-dragonfly** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/blob/1.7.10/src/main/java/blusunrize/immersiveengineering/api/tool/IDrillHead.java - You probably want this.

**Comment by ReikaKalseki** [comment]
Done.
