### ISSUE TITLE
dragonAPI crash updating from v19 to latest

### ISSUE THREAD

**Issue by RezaSmith** [ReikaKalseki/Reika_Mods_Issues#2319]
so i wanted to try the modpack called Revolution 3 on ATLauncher and i tried updating everything and it crashed , so i tried only updating reika's mods but it crashed again , i updated everything else and it was fine so there is a problem with dragonapi i think , it says something about thaumcraft but i dont know
here is the crash logs from dedicated server(client is the same)
[crash-2020-02-10_11.12.07-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4179553/crash-2020-02-10_11.12.07-server.txt)
let me know if you needed any more info

**Comment by Rewyn** [comment]
disable sanity checker in the dapi config

**Comment by ReikaKalseki** [comment]
And then prepare for a crash whenever anything tries to interact with flux gas.

**Comment by RezaSmith** [comment]
what i don't understand is how come in older versions (19c) everything was fine , surely you must've changed something to cause this?

**Comment by ReikaKalseki** [comment]
No, the sanity checker was added in summer of 2016, first released with v12:

https://www.reddit.com/r/feedthebeast/comments/48pzdu/headsup_for_v12_enhanced_environment_sanity/
