### ISSUE TITLE
Network lag when activating reactors

### ISSUE THREAD

**Issue by Saereth** [ReikaKalseki/Reika_Mods_Issues#232]
For some reasons we're getting alot of neutrons ticking high from our reactor, is there something we're doing wrong here?

here are the opis numbers: http://i.imgur.com/SJgfQsr.png
the reactors
http://i.imgur.com/SPoMWsA.png

Vanilla forge 1448, Nuts and Bolts pack on FTB/Technic

**Comment by ReikaKalseki** [comment]
I recognize that reactor design. :P

But 377 neutrons is rather high, as is 287 micros each. Something else is involved...

**Comment by Saereth** [comment]
it is your design, I wasnt sure if its still valid but in ssp it seemed to work. any idea where I should start looking as to what else might be involved?

Addiitonally when we brought it online we noticed what SEEMED to be a big network performance hit, to the point of a couple players lagging out entirely when they're near it. Here is the before and after snapshot of the traffic if it helps shine any light on things. 

before: http://i.imgur.com/7ht65rc.png
after activating: http://i.imgur.com/HmZf3ZW.png

**Comment by ReikaKalseki** [comment]
I do not use C17 packets, at least not that I know of.

**Comment by Saereth** [comment]
So we updated to V8 latest as of today, killed off all the neutrons with opis, restarted and the timing seems to be reasonable now, nothing like we were seeing. We are unfortunately still having the massive networking issue. As soon as we feed that setup fuel everything starts flickering, waila goes crazy, the turbines start flickering and until you leave the vicinity the network delay gets greater and great. At one point I was up to almost a full minute delay in my actions. the moment I left the vicinity of the reactor it was gone. I made a quick video of the setup to see if there is any more we can do to troubleshoot on our end. https://youtu.be/Y2URwuUFpws

**Comment by ReikaKalseki** [comment]
C17 is, as the name implies, PacketCustomPayload. My TileEntities' sync packets actually extend S35UpdateTileEntity, so are not involved here. Now, neutrons do implement IEntityAdditionalSpawnData; does that use a C17?

**Comment by Saereth** [comment]
Im not sure, I'll do some digging and see what I can find

**Comment by Saereth** [comment]
did some packet monitoring and whenever the reactor gets turned on the traffic more than doubles essentially dosing the client. with the reactor off there is no issue at all. I can see the traffic but I dont know what exactly is being sent. Also the flickering of all the textures starts when we turn on the reactor, with it off the textures are just fine (you can see this demonstrated in the video). could this all be connected some how?

**Comment by Saereth** [comment]
#blameextracells.
