### ISSUE TITLE
Generation structures problem

### ISSUE THREAD

**Issue by EreticKB** [ReikaKalseki/Reika_Mods_Issues#2320]
After i add Twilight Forest into this mod list and delete all old chunks in world except my base i found that Crystall Shrine and Frozen Outpost never generate in my wolrd.
![Снимок](https://user-images.githubusercontent.com/59476878/74151587-86598e00-4c1d-11ea-8cae-e1d1bf35eb48.PNG)

**Comment by ReikaKalseki** [comment]
They generate; I have several in mine, and I have all of those mods installed.

**Comment by EreticKB** [comment]
Strange. I can't find any. Even there where they was before delete old chunks. M.b. this world`s local glitch.
