### ISSUE TITLE
ChromatiCraft | Alredy Tessalating

### ISSUE THREAD

**Issue by avescarelo** [ReikaKalseki/Reika_Mods_Issues#2321]
Hello, i get crash when played in MC before ChromatiCraft.
Please, see crashlog. Maybe it help you Reika-san.

Crashlog: [see](https://gist.github.com/pingvikin/99f322ea391e39f5d3ece78948b7e0dc)

**Comment by Rewyn** [comment]
possibly related/similar to https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2285 ?
Maybe try what is suggested there (setting chunkloading setting to default in optifine), or straight up try removing optifine temporarily=

**Comment by ReikaKalseki** [comment]
I doubt this is my doing; I just have a hook there.
