### ISSUE TITLE
Fluid Radiator Cannot Input Liquid Nitrogen to Toroids

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2323]
Toroid magnets are not IFluidHandlers, and so as such the Fluid Radiator does not work on them. They store it only from RoC pipes that are one-block separated from the TE. Current the amount of coolant is stored in the toroid NBT tag

**Comment by ReikaKalseki** [comment]
Fixed.
