### ISSUE TITLE
Mana Pod/Bean max growth meta value incorrect in ModCropList

### ISSUE THREAD

**Issue by BlueAgent** [ReikaKalseki/Reika_Mods_Issues#2324]
Ripe mana pods have a metaripe of `7` (was `3` in older versions of TC).

Currently the [registry has the old value](https://github.com/ReikaKalseki/DragonAPI/blob/1fddfe12998033eb2d1afdcdfffff4df6037bb7f/ModRegistry/ModCropList.java#L51).

**Comment by ReikaKalseki** [comment]
Fixed.
