### ISSUE TITLE
DragonAPI V24c wool related recipes bug

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2327]
It will cause some items crafted by any color wool to be crafted by only white wool.(Ex: bed.)

**Comment by ReikaKalseki** [comment]
I cannot find any code that would do this - can you elaborate?

**Comment by XenonDB** [comment]
This bug disappears in V29d.

By the way, this bug seems caused by something making recipe not accepting various damage.
![2021-03-27_16 58 26](https://user-images.githubusercontent.com/58476103/112716031-e513c100-8f1e-11eb-88e7-8f387fbab583.png)

V29d:
![2021-03-27_17 00 26](https://user-images.githubusercontent.com/58476103/112716036-ed6bfc00-8f1e-11eb-8c13-e7d0d73cb36b.png)

**Comment by ReikaKalseki** [comment]
OK then...
