### ISSUE TITLE
[CrC] Crystalline Stone uses wrong texture when connected texture is enabled

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2329]
Looks like the Shielding Stone texture?

![2020-02-19_22 41 52](https://user-images.githubusercontent.com/6917535/74908206-1c05c380-536a-11ea-9c8b-8bc37093aa6b.png)

**Comment by ReikaKalseki** [comment]
That *is* the texture for connected crystalline stone, being the texture of the stone without the edges. What else would it use?

**Comment by Zsashas** [comment]
Shouldn't it at least have edges around...the edges? Or is it trying to connect textures with everything?
