### ISSUE TITLE
ElectriCraft 1.7.10 V8a crashes with RotaryCraft 1.7.10 V8d and NEI

### ISSUE THREAD

**Issue by twospheres** [ReikaKalseki/Reika_Mods_Issues#233]
Hello Reika!

I had a stable server running many mods along with rotarycraft (v7f). Loved it so much I added in several more of your mods, along with updating all mods & apis to the latest version.
After booting the server and logging in, if a lubricated gearbox was rendered on the screen, or if I opened a chest with gearboxes that had lubricant in them the client would crash. (server continued just fine)

crash dump from opening a chest with lubricated gearboxes (existing world):
http://pastebin.com/3xgWuGq3 (1 month expiry)
crash dump from viewing a working lubricated gearbox (new world, creative)
http://pastebin.com/pBkm5mN4 (1 month expiry)

It would also display lubricant hoses being filled with the 'texture missing' pink and black chequered pattern instead of the orange\yellow texture.
NEI would also crash when trying to view recipes of ANY item (usage worked without crashing however) this crashlog was viewing a recipe of a stick from the TC natura mod:
http://pastebin.com/NvA98fWZ (1 month expiry)
The NEI version used with the crashdump is 1.0.5.111, but I have also tested with the latest 1.0.5.118.

Initially I thought it might be optifine so that was removed, but it did not help. In the end I rolled back entirely, transferred the server files to my machine for faster singleplayer testing, and then by slow process of elimination I found that it was caused by adding ElectriCraft v8a.

On an unrelated note, thank you for your excellent mods. I think you have hit the right ratio of complexity and fun that still feels like minecraft. I hope you continue to build!

**Comment by twospheres** [comment]
Just had a quick look through the recently solved issues,
#224 and #219 looked similar so I tested a little. The 3 crash scenarios are fixed after I remove PneumaticCraft.
Should I create a bug report for PneumaticCraft?

**Comment by TomeWyrm** [comment]
Have you tried any of the fixes in #224?

Also yes, you should report this as a bug to @MineMaarten... which I kinda just did, but please make a proper bug report here: https://github.com/MineMaarten/PneumaticCraft/issues

**Comment by ReikaKalseki** [comment]
Triplicate and confirmed to be due to something dumb going on with PnC lubricant.
