### ISSUE TITLE
Linked Pylon's Crystal Growths not occuring

### ISSUE THREAD

**Issue by BlueAgent** [ReikaKalseki/Reika_Mods_Issues#2331]
Energy is shared after the pylon is recharged.

This means that there can be a situation that the pylon is never full when the check (energy full) for crystal growth is done.

That situation is when the non-first pylon to tick is missing energy.

This means that for two pylons in a network (1 "link"), it is a 50% chance (depending on tick order) that the pylons will stablize such that crystal can grow.

The chance is `1 / number of pylons in a networks` (or `1/(1 + number of "links"`).

Possible fix
------------
Recharge the pylon after sharing energy to other pylons.
This means that the pylon can fill up fully, allowing crystals to grow again.

~~Alternatively, move the part that caps the energy to after it is shared.~~ Turns out energy is [capped inside the charge method](https://github.com/ReikaKalseki/ChromatiCraft/blob/b3b8dce5a9ba8dc6dd9dca8fa2b069f113888774/TileEntity/Networking/TileEntityCrystalPylon.java#L694) as well, so this didn't work.

Current Implementation
======================
For both even and odd number of links, the crystals don't grow in certain conditions because when the condition for growth is checked, the pylons are not full.
This depends on the tick order of the pylons (if the first pylon to tick is the one that is missing energy it is fine)

Operation order
---------------
1. [Recharge](https://github.com/ReikaKalseki/ChromatiCraft/blob/bfeff881e5438e8d0024de3bb6c362765b221212/TileEntity/Networking/TileEntityCrystalPylon.java#L328)
2. [Share (if energy >= half capacity)](https://github.com/ReikaKalseki/ChromatiCraft/blob/bfeff881e5438e8d0024de3bb6c362765b221212/TileEntity/Networking/TileEntityCrystalPylon.java#L389)
3. [Grow Crystals (if energy is full)](https://github.com/ReikaKalseki/ChromatiCraft/blob/bfeff881e5438e8d0024de3bb6c362765b221212/TileEntity/Networking/TileEntityCrystalPylon.java#L411)

Example A1.1
---------
A single server tick with 2 pylons (1 "link") where the last pylon to tick is missing energy

| A   | B   | Notes                                           |
| --- | --- | ----------------------------------------------- |
| 100 | 99  | Initial Energy Levels                           |
| -   | -   | Tick A: Recharged nothing (already full)        |
| 99  | 100 | Tick A: Shared 1 energy to Pylon B              |
| -   | -   | Tick A: Crystals do not grow since energy < 100 |
| -   | -   | Tick B: Recharged nothing (already full)        |
| 100 | 99  | Tick B: Shared 1 energy to Pylon A              |
| -   | -   | Tick B: Crystals do not grow since energy < 100 |
| -   | -   | End Tick: The cycles repeats again next tick    |

Example A1.2
---------
A single server tick with 2 pylons (1 "link") where the first pylon to tick is missing energy

| A   | B   | Notes                                           |
| --- | --- | ----------------------------------------------- |
| 99  | 100 | Initial Energy Levels                           |
| 100 | 100 | Tick A: Recharged 1 energy                      |
| -   | -   | Tick A: Shared nothing since all links are full |
| -   | -   | Tick A: Crystals grow since energy == 100       |
| -   | -   | Tick B: Recharged nothing (already full)        |
| -   | -   | Tick B: Shared nothing since all links are full |
| -   | -   | Tick B: Crystals grow since energy == 100       |
| -   | -   | End Tick: The cycles repeats again next tick    |

Example A2.1
---------
A single server tick with 3 pylons (2 "links") where the last pylon to tick is missing energy

| A   | B   | C   | Notes                                           |
| --- | --- | --- | ----------------------------------------------- |
| 100 | 100 | 99  | Initial Energy Levels                           |
| -   | -   | -   | Tick A: Recharged nothing (already full)        |
| 99  | 100 | 100 | Tick A: Shared 1 energy to Pylon C              |
| -   | -   | -   | Tick A: Crystals do not grow since energy < 100 |
| -   | -   | -   | Tick B: Recharged nothing (already full)        |
| 100 | 99  | 100 | Tick B: Shared 1 energy to Pylon A              |
| -   | -   | -   | Tick B: Crystals do not grow since energy < 100 |
| -   | -   | -   | Tick C: Recharged nothing (already full)        |
| 100 | 100 | 99  | Tick C: Shared 1 energy to Pylon B              |
| -   | -   | -   | Tick C: Crystals do not grow since energy < 100 |
| -   | -   | -   | End Tick: The cycles repeats again next tick    |

Example A2.2
---------
A single server tick with 3 pylons (2 "links") where the first pylon to tick is missing energy

| A   | B   | C   | Notes                                           |
| --- | --- | --- | ----------------------------------------------- |
| 99  | 100 | 100 | Initial Energy Levels                           |
| 100 | 100 | 100 | Tick A: Recharged 1 energy                      |
| -   | -   | -   | Tick A: Shared nothing since all links are full |
| -   | -   | -   | Tick A: Crystals grow since energy == 100       |
| -   | -   | -   | Tick B: Recharged nothing (already full)        |
| -   | -   | -   | Tick B: Shared nothing since all links are full |
| -   | -   | -   | Tick B: Crystals grow since energy == 100       |
| -   | -   | -   | Tick C: Recharged nothing (already full)        |
| -   | -   | -   | Tick C: Shared nothing since all links are full |
| -   | -   | -   | Tick C: Crystals grow since energy == 100       |
| -   | -   | -   | End Tick: No more balancing since all full      |

Example A2.3
---------
A single server tick with 3 pylons (2 "links") where the second pylon to tick is missing energy

| A   | B   | C   | Notes                                           |
| --- | --- | --- | ----------------------------------------------- |
| 100 | 99  | 100 | Initial Energy Levels                           |
| 99  | 100 | 100 | Tick A: Recharged nothing (already full)        |
| -   | -   | -   | Tick A: Shared 1 energy to Pylon B              |
| -   | -   | -   | Tick A: Crystals do not grow since energy < 100 |
| -   | -   | -   | Tick B: Recharged nothing (already full)        |
| 100 | 99  | 100 | Tick B: Shared 1 energy to Pylon A              |
| -   | -   | -   | Tick B: Crystals do not grow since energy < 100 |
| -   | -   | -   | Tick C: Recharged nothing (already full)        |
| 100 | 100 | 99  | Tick C: Shared 1 energy to Pylon B              |
| -   | -   | -   | Tick C: Crystals do not grow since energy < 100 |
| -   | -   | -   | End Tick: Example A2.1 for next ticks           |

Proposed Solution
=================
We could swap the "Recharge" and "Share" code.

This allows the pylons to eventually all fill up.

Operation order (NEW: Swapped Recharge and Share)
---------------
1. [Share (if energy >= half capacity)](https://github.com/ReikaKalseki/ChromatiCraft/blob/bfeff881e5438e8d0024de3bb6c362765b221212/TileEntity/Networking/TileEntityCrystalPylon.java#L389)
2. [Recharge](https://github.com/ReikaKalseki/ChromatiCraft/blob/bfeff881e5438e8d0024de3bb6c362765b221212/TileEntity/Networking/TileEntityCrystalPylon.java#L328)
3. [Grow Crystals (if energy is full)](https://github.com/ReikaKalseki/ChromatiCraft/blob/bfeff881e5438e8d0024de3bb6c362765b221212/TileEntity/Networking/TileEntityCrystalPylon.java#L411)

Example B1
---------
A single server tick with 2 pylons (1 "link") with the proposed fix applied

| A   | B   | Notes                                           |
| --- | --- | ----------------------------------------------- |
| 100 | 99  | Initial Energy Levels                           |
| 99  | 100 | Tick A: Shared 1 energy to Pylon B              |
| 100 | 100 | Tick A: Recharged 1 energy                      |
| -   | -   | Tick A: Crystals grow since energy == 100       |
| -   | -   | Tick B: Shared nothing since all links are full |
| -   | -   | Tick B: Recharged nothing (already full)        |
| -   | -   | Tick B: Crystals grow since energy == 100       |
| -   | -   | End Tick: No more balancing since all full      |

Example B2
---------
A single server tick with 3 pylons (2 "links") with the proposed fix applied

| A   | B   | C   | Notes                                           |
| --- | --- | --- | ----------------------------------------------- |
| 100 | 100 | 99  | Initial Energy Levels                           |
| 99  | 100 | 100 | Tick A: Shared 1 energy to Pylon C              |
| 100 | 100 | 100 | Tick A: Recharged 1 energy                      |
| -   | -   | -   | Tick A: Crystals grow since energy == 100       |
| -   | -   | -   | Tick B: Shared nothing since all links are full |
| -   | -   | -   | Tick B: Recharged nothing (already full)        |
| -   | -   | -   | Tick B: Crystals grow since energy == 100       |
| -   | -   | -   | Tick C: Shared nothing since all links are full |
| -   | -   | -   | Tick C: Recharged nothing (already full)        |
| -   | -   | -   | Tick C: Crystals grow since energy == 100       |
| -   | -   | -   | End Tick: No more balancing since all full      |

**Comment by ReikaKalseki** [comment]
`Alternatively, move the part that caps the energy to after it is shared.` Done.

**Comment by BlueAgent** [comment]
Still broken with the changes.

This is because the `charge` method also [caps the charge](https://github.com/ReikaKalseki/ChromatiCraft/blob/b3b8dce5a9ba8dc6dd9dca8fa2b069f113888774/TileEntity/Networking/TileEntityCrystalPylon.java#L694).

Seems like you'll need to reorder the charging to be after sharing then.

Or make the charge method not cap (might need to update ` = getCapacity()` to ` >= getCapacity()` in a bunch of places though.

**Comment by BlueAgent** [comment]
In hindsight, uncapping isn't a great idea.

You could store a flag for full charge after the charging, then use it for the growth check.

Changing the order to be sharing followed by charging is the most correct way though, imo.

**Comment by ReikaKalseki** [comment]
Done.
