### ISSUE TITLE
Weather Attentuation occurs under glass roof

### ISSUE THREAD

**Issue by Aivech** [ReikaKalseki/Reika_Mods_Issues#2333]
For the purposes of being sheltered from weather a glass roof should probably count as sky obstruction.
![image](https://user-images.githubusercontent.com/16143392/75078565-f0065180-54d3-11ea-8cda-d998e3968119.png)

**Comment by BlueAgent** [comment]
IIRC the whole link between repeaters need to be protected from the weather, not just above each repeater. Is that what you've done there?

**Comment by ReikaKalseki** [comment]
I just checked the code and it looks fine, so I also suspect this.

**Comment by Aivech** [comment]
I don't know, as since I submitted this issue I've since built the rest of the roof. Will test if i notice it snowing again.

**Comment by Aivech** [comment]
Seems to work fine, closing.
