### ISSUE TITLE
[REQUEST] Decorative runes in certain constructs

### ISSUE THREAD

**Issue by Aivech** [ReikaKalseki/Reika_Mods_Issues#2334]
Allow replacing visible crystalline stone with runes of the players' choice in certain constructs for aesthetic purposes:

- Ritual Altar
- Warp Glass frame

**Comment by ReikaKalseki** [comment]
Not in the warp glass, no. Consistency between ends is crucial.

**Comment by Aivech** [comment]
Then force it to match on both ends or something. As far as I know the frame material already doesn't have to be consistent, it just has to be "some crystalline material".

**Comment by ReikaKalseki** [comment]
Now it does.

Also, done.
