### ISSUE TITLE
[CrC/DAPI] Pigmen do not aggro

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2337]
Pigmen simply never aggro when one is hit. Tested with all sorts of weapons over the last month or so. Vanilla swords, Tinker weapons, various magic spells, nothing. Something regarding the Aggro Mask enchant, perhaps? Can't think of another reason for it, really.

**Comment by OvermindDL1** [comment]
Does it require only having DAPI and ChC, or does it break with just DAPI as well?  You were not in creative mode yes?

**Comment by Shahelion** [comment]
Definitely not in creative mode. I should clarify, the pigman being hit does aggro, but none of the others nearby.

**Comment by ReikaKalseki** [comment]
I just tested, and it works fine for me. Even in creative.

**Comment by Aivech** [comment]
Works for me on a server as well.
