### ISSUE TITLE
[CrC] Sandy Burrows generate with crystal stone variants instead of shielding stone

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2338]
With the notable exception of the shielding stone that appears to lock the player inside.

![2020-02-09_09 14 45](https://user-images.githubusercontent.com/6917535/75517015-8645e600-59b2-11ea-963d-11a08b2c62eb.png)

**Comment by ReikaKalseki** [comment]
I already fixed this.
