### ISSUE TITLE
[CrC] Nether Structures contain exact same loot

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2339]
Specifically, the small structures that explode when the chest is opened. Exact same items and layout in every one. 

EDIT: Ok, I just found one that had different items, but I DID find five in a row with this exact layout first. No idea why.
![2020-02-27_22 35 53](https://user-images.githubusercontent.com/6917535/75517070-aaa1c280-59b2-11ea-92c5-66c1a27aca11.png)
![2020-02-27_22 36 28](https://user-images.githubusercontent.com/6917535/75517072-ab3a5900-59b2-11ea-96ed-9777ddd285d9.png)

**Comment by ReikaKalseki** [comment]
This is a very old issue, and never made any sense. And its lack of reproducibility has made investigation extremely difficult.

**Comment by Shahelion** [comment]
Still happens, still no idea why. Often up to 8 loot chests will have the same loot before finding chests with different items in them. Only applies to the small exploding structure.

**Comment by ReikaKalseki** [comment]
I have changed which random generator this is using which should help.
