### ISSUE TITLE
Bedrock Chisel Head Texture is one pixel up from where it should be.

### ISSUE THREAD

**Issue by BlueAgent** [ReikaKalseki/Reika_Mods_Issues#2342]
Bedrock Chisel
![Bedrock Chisel](https://user-images.githubusercontent.com/630920/75602337-2577f400-5aff-11ea-95eb-7796c04136a3.png)

Stone Chisel for comparison
![Stone Chisel](https://user-images.githubusercontent.com/630920/75602342-30328900-5aff-11ea-9c23-e56c966a1054.png)

Both are using a bedrock tool rod, only the chisel heads are different.

**Comment by ReikaKalseki** [comment]
Fixed.
