### ISSUE TITLE
Crash when shift-clicking ores into the extractor.

### ISSUE THREAD

**Issue by Amperthorpe** [ReikaKalseki/Reika_Mods_Issues#235]
http://pastebin.com/CVkxh1aL

**Comment by Amperthorpe** [comment]
It's a client only crash for me.

**Comment by Saereth** [comment]
Similar issue, but server crash https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/236

**Comment by ReikaKalseki** [comment]
This is caused by AOBD.
