### ISSUE TITLE
Thorium Reactor Components does not have a tab in the ReactorCraft Handbook's Table of Contents

### ISSUE THREAD

**Issue by BlueAgent** [ReikaKalseki/Reika_Mods_Issues#2351]
Thorium Components section is between Breeder Components and Fusion Components but it does not have an associated tab on the Table of Contents section at all. (I think it's meant to be between the two).

Table of Contents (page 0), there is a Breeder Components tab and a Fusion Components tab
![Table of Contents](https://user-images.githubusercontent.com/630920/75858508-545dd500-5e33-11ea-94ea-0530e5bd0553.png)

Breeder Reactor Components (page 9)
![Breeder Reactor Components](https://user-images.githubusercontent.com/630920/75858635-90913580-5e33-11ea-8f59-b29ca36242a3.png)

Thorium Reactor Components (page 10)
![Thorium Reactor Components](https://user-images.githubusercontent.com/630920/75858665-9edf5180-5e33-11ea-8ed6-7071a257b27e.png)

Fusion Reactor Components (page 11)
![Fusion Reactor Components](https://user-images.githubusercontent.com/630920/75858692-ab63aa00-5e33-11ea-8582-28f354034cb8.png)

**Comment by ReikaKalseki** [comment]
Fixed.
