### ISSUE TITLE
Friction heated furnace does not properly switch to lit_furnace

### ISSUE THREAD

**Issue by BlueAgent** [ReikaKalseki/Reika_Mods_Issues#2352]
Furnace is meant to be lit as long as there is burn time remaining.

`BlockFurnace.updateFurnaceBlockState(this.furnaceBurnTime > 0, this.worldObj, this.xCoord, this.yCoord, this.zCoord);` might be helpful. It is used in `TileEntityFurnace.updateEntity()`.

I think the reason why it's not working is usually TileEntityFurnace saves the state of `furnaceBurnTime > 0` within it's update method and then if it's different by the end of the update method then it calls `BlockFurnace.updateFurnaceBlockState`.

There seems to be a [commented out attempt](https://github.com/ReikaKalseki/RotaryCraft/blob/b92426180e5ac6a7fe7e3a4537710ab097eb3a82/TileEntities/Auxiliary/TileEntityFurnaceHeater.java#L294-L299) at getting it to properly update to a lit furnace in the Friction Heater code already. But it's called every tick instead of only when needed.

**Potential code change**

[Before](https://github.com/ReikaKalseki/RotaryCraft/blob/b92426180e5ac6a7fe7e3a4537710ab097eb3a82/TileEntities/Auxiliary/TileEntityFurnaceHeater.java#L221-L224)
```java
int burn = Math.max(this.getBurnTimeFromTemperature(), tile.furnaceBurnTime);
this.setFurnaceBlock(world, burn > 0);
tile.currentItemBurnTime = burn;
tile.furnaceBurnTime = burn;
```

After
```java
boolean wasBurning = tile.furnaceBurnTime > 0;
int burn = Math.max(this.getBurnTimeFromTemperature(), tile.furnaceBurnTime);
tile.currentItemBurnTime = burn;
tile.furnaceBurnTime = burn;
if (!wasBurning && tile.furnaceBurnTime > 0) {
	BlockFurnace.updateFurnaceBlockState(true, world, fx, fy, fz);
}
```
Also removing the now unused `setFurnaceBlock` method (or you can update the method too if you'd like)

We only update the furnace `unlit -> lit` (when the burn time was 0 before we update it) and let the furnace's natural burn time decay set itself back to unlit (since the friction heater never decreases the burn time).

So, with a properly powered friction heater, this should only be updated to a lit furnace once and stay lit till the minimum power requirements are no longer met and the burn time naturally runs out.

**Comment by ReikaKalseki** [comment]
I remember why this was removed - it caused the furnace to drop its contents.

**Comment by BlueAgent** [comment]
> I remember why this was removed - it caused the furnace to drop its contents.

The code I've given above does not result in the furnace dropping its contents.

I've implemented that code (with a few trivial modifications to update for the changes to `fx, fy, fz`) in this video:
https://www.youtube.com/watch?v=XjZzEnqMMu8

The reason why it was dropping items (in your past memory) is the furnace block has the field `field_149934_M` which is a flag to not drop items when being removed (which wasn't being set). But if you just use the public static method `BlockFurnace#updateFurnaceBlockState`, as shown in my suggested fix, it properly uses that flag for you and updates the block.

**Comment by ReikaKalseki** [comment]
Done.
