### ISSUE TITLE
ChromatiCraft V24c Personal Infusion Stand bug on server

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2354]
Placing a personal infusion stand in server cause client disconnection by internal server error.

Also, a personal infusion stand(placed by player, /chromastructure, or ThermalExpansion4 Activator. Placed by Activator also cause server crash.) in server doesn't have tile entity(check by "/nbtedit"), the command line rapid report a lot of error and causes tps decrease a lot.

**Comment by ReikaKalseki** [comment]
I need the internal server error log.

**Comment by XenonDB** [comment]
Server side:
[fml-junk-earlystartup.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4316987/fml-junk-earlystartup.log)
[fml-server-latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4316988/fml-server-latest.log)
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4316990/latest.log)

Client side:
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4316997/latest.log)

**Comment by ReikaKalseki** [comment]
It works for me, and that code should never throw that error.
