### ISSUE TITLE
ChromatiCraft V24c Dimensional Core can't be mined by player

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2355]
As title.

Additionally, I found onlyAllowOwnersToMine() is overrided in [source code](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/TileEntity/Technical/TileEntityDimensionCore.java)
but not in the compiled class.

Test by CustomNpcs script, it also say !this.hasStructure() is false but onlyAllowOwnersToMine() is true.
![1](https://user-images.githubusercontent.com/58476103/76137573-b6a81700-6079-11ea-9be8-fde6114fb882.png)
![2020-03-07_13 27 13](https://user-images.githubusercontent.com/58476103/76137576-b871da80-6079-11ea-905d-a2a32c6d961a.png)
![2020-03-07_13 27 59](https://user-images.githubusercontent.com/58476103/76137577-b90a7100-6079-11ea-9af9-3449308f4af8.png)

**Comment by ReikaKalseki** [comment]
I confirmed this for myself, but what the ***hell***?!

**Comment by ReikaKalseki** [comment]
That code is not in the released version yet.
