### ISSUE TITLE
Geostrata slab lighting broken

### ISSUE THREAD

**Issue by Aivech** [ReikaKalseki/Reika_Mods_Issues#2356]
![HAYO](https://user-images.githubusercontent.com/16143392/76139110-4074c780-601b-11ea-9f87-4e5a4c0ddf51.png)

**Comment by Aivech** [comment]
On further investigation, it appears they take their lighting level from underneath them, whether the slab is placed on the top or bottom of a block.

**Comment by ReikaKalseki** [comment]
Fixed.
