### ISSUE TITLE
VoidMonster Crash Due to Missing ThaumCraft IWarpingGear 

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2357]
As said, missing some TC armor thing. As you can imagine, no TC in the pack, and I was in the lowest levels of the world, where Voidy was likely trying to eat my armor. Dev v24d, not quite the latest as of Sat. 7 March 2020.
[ThaumCraftVM_Crashlog.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4302599/ThaumCraftVM_Crashlog.txt)

**Comment by ReikaKalseki** [comment]
Fixed.
