### ISSUE TITLE
ChromaticCraft Crash When CritterPet is not Installed

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2358]
When CritterPet is not installed, CrC tries to access a class you _thought_ was in DAPI [As you said in Discord], but is not. It's `Reika/CritterPet/Interfaces/TamedMob`. Crash
[ChromatiCraftCritterPet_Crashlog.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4302601/ChromatiCraftCritterPet_Crashlog.txt)
 is currently occurring on bats.

**Comment by ReikaKalseki** [comment]
Fixed.
