### ISSUE TITLE
Server crash when extracting ores

### ISSUE THREAD

**Issue by Saereth** [ReikaKalseki/Reika_Mods_Issues#236]
Latest V8 updates as of today, aobd 2.8.2 with rotarycraft support disabled
Crashlog
http://pastebin.com/ey9byubT

Seems related to https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/235

**Comment by kolatra** [comment]
You don't need to create a separate issue for the same crash, even if it's on different sides. Keep it on #235.
