### ISSUE TITLE
Lumen Fence issues

### ISSUE THREAD

**Issue by Aivech** [ReikaKalseki/Reika_Mods_Issues#2361]
- Lumen Fence Relays do not display their input and output states until the chunk is rerendered, and do not trigger such a rerender themselves
- Breaking vertices of the fence perimeter does not remove the fence unless one breaks the emitter that was originally right-clicked to calculate the fence
![image](https://user-images.githubusercontent.com/16143392/76378577-22151180-6324-11ea-801c-a6bcf6db0114.png)

**Comment by ReikaKalseki** [comment]
Fixed.
