### ISSUE TITLE
[Rotarycraft] ElectriCraft Aluminum ingot does not craft into Aluminum ingot alloy in blast furnace 

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2365]
Using ElectriCraft aluminum ingot to make Aluminum ingot alloy in a blast furnace does not work as compared to using RotaryCraft aluminum ingot. Is this intended? I was assuming that both mod ingot are a general aluminum ingot that can be use to manufacture the alloy in blast furnace.

File versions:
DragonAPI V24C
ElectriCraft V24A
Rotarycraft V24C

![2020-03-14_20 40 09](https://user-images.githubusercontent.com/62176592/76682273-935f0800-6635-11ea-973f-7811fdab33a5.png)

![2020-03-14_20 51 12](https://user-images.githubusercontent.com/62176592/76682290-c73a2d80-6635-11ea-9117-7c6a49c70750.png)

**Comment by voidsong-dragonfly** [comment]
Normally, only the RoC aluminium that is the extractor byproduct is accepted for the Aluminium-Silicon alloy. However, there is a config to enable any OD aluminium to work in the alloy in the RotaryCraft config.

**Comment by tiny-maple** [comment]
> Normally, only the RoC aluminium that is the extractor byproduct is accepted for the Aluminium-Silicon alloy. 

I have tested that both types of RoC aluminum can be used to make the aluminum alloy with Silicon Powder. I suppose this would be a minor issue since there is a config to allow OD aluminum. However for complete environment integration since ElectriCraft is Reika's mod, shouldn't ElectriCraft Aluminum be allowed by default to combined with Silicon Powder in blast furnace to produce Aluminum Alloy ingot?

**Comment by ReikaKalseki** [comment]
No, ElC aluminum is not equivalent to RC aluminum, as the latter requires the extractor to make.
