### ISSUE TITLE
[Request] Chisel integration: add a bedrock chisel

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#2366]
No, there aren't "three valid Chisel versions for 1.7.10", there is only one version that changed hands three times; Chisel-Team's one is the latest and the only remaining.

Your item merely needs to implement this interface: https://github.com/Chisel-Team/Chisel/blob/1.7/release/src/main/java/com/cricketcraft/chisel/api/IChiselItem.java

**Comment by ReikaKalseki** [comment]
Done.
