### ISSUE TITLE
[Chromaticraft] Missing progress information on infusion stand.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2367]
![2020-03-22_01 36 14](https://user-images.githubusercontent.com/62176592/77232772-ee68a000-6bdd-11ea-9d1f-f1426564414b.png)

#NULL on lexicon progress. What was the intended information for this progress?

**Comment by ReikaKalseki** [comment]
This is fixed in the next release.
