### ISSUE TITLE
[Request] Inserting and Extracting Reactors with Distribution Node

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#2369]
Hi,
It would be really nice if the item distribution Node from Chromaticraft extract Waste/Plutonium/depleted Uranium from the reactor cores, because there is no "Reikamods" method to extract them.
Inserting is possible with the item inserter from CC but for Extracting i have to use Itemducts or inventory manager.

**Comment by voidsong-dragonfly** [comment]
You can use Pneumatic Item Pumps, they're the RoC-native item transport.

**Comment by Kobra331** [comment]
They need energy directly under the reactor for each reactor core. there is no space for the engines through the waterpipes for the boilers.

**Comment by voidsong-dragonfly** [comment]
Hoppers? They're vanilla and at least work. I do agree this isn't ideal, but it's also not impossible.

**Comment by ReikaKalseki** [comment]
That is not how PiPs work, and the nodes work fine.
![https://i.imgur.com/5qsnjZj.png](https://i.imgur.com/5qsnjZj.png)
