### ISSUE TITLE
"Heat Lamp" oddities.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#237]
1) The Chromaticraft heat lamp temperature is unstable and the heated block flickers between the set temperature and +/-2 degrees up down (down if biome temperature is lower, up if higer). So setting it to 600°C on a RotaryCraft Blast Furnace can't make HSLA Steel because the temperature keeps dropping below 600.

2) If the Heat Lamp is left-clicked with anything but an appropriate mining tool it is instantly destroyed (like in creative).

3) The inventory icon changes based on what block face you last placed a lamp on.

**Comment by ReikaKalseki** [comment]
3) is unfixable without major rewrites.

2) is easy to fix.

1) ...I have not had this issue at all.

**Comment by lossycrypt** [comment]
3) I'll just pretend it's an easter egg.
2) yay.
1) I just tried in a fresh singleplayer creative superflat desert and snowy kingdom. Neither of them works for 600°C HSLA steel. I then tried to make coal coke with the heatlamp at exactly 400°C and 401°C, neither of which works. It only works if set to 402°C, which negates the -2°C flicker i described above. Putting heatlamps on more than on side (i usually had one on the top) makes the temperature display in the gui stop flickering but still doesn't make the furnace work.

Here's a bad gif of the flickering:
![heatlamplq](https://cloud.githubusercontent.com/assets/14168854/9745582/fc15ac32-5672-11e5-8f95-aed3a6c1089a.gif)

**Comment by ReikaKalseki** [comment]
I just fixed 2).

1) Sounds like a "fight" between the temperature update code in the RC machines and the heat lamp. If so, it is not fixable. That said, I increased the max temperature of the lamp to 615C to help combat it.

**Comment by lossycrypt** [comment]
2) double yay.
1) In that case i wonder why you're not experiencing the same problem.
If i may suggest a workaround: You could increase the maximum temperature for heat lamps to 602, or 640 like lava. That would allow HSLA steel production :).

**Comment by ReikaKalseki** [comment]
See my edit.

**Comment by lossycrypt** [comment]
Great, thanks. =)
