### ISSUE TITLE
[ChC/NEI] Crash when looking at usages for Items

### ISSUE THREAD

**Issue by DerWahreQwert** [ReikaKalseki/Reika_Mods_Issues#2370]
I've looked around here for quite a while and found some similar problems, however nothing matched this one perfectly, so I hope this isn't a duplicate

Here's the Crashlog https://pastebin.com/niPEfAc7

I'm not super knowledgebal on how to interpret most of it, tho from the mentions of that ElementCalculator thingy it seems to have some relation to ChC. 

This happens in both singleplayer and multiplayer.
It happens with most Items, but not all.
I've also folowed instruction from the aforementioned similar problems and
can confirm that it is neither Extratrees nor Gregtech.
And yes, I am in 24c, tho I've encountered this same issue in previous versions as well.

**Comment by ReikaKalseki** [comment]
You have a mod adding items to the game without actually registering them to Forge. This is entirely on their end.
