### ISSUE TITLE
[RoC] Friction Heater Causing Nebulous Rendering Crash

### ISSUE THREAD

**Issue by Shadowsoftime99** [ReikaKalseki/Reika_Mods_Issues#2371]
Hey, so as I was setting up an autosmelter system, the same as my server has had before with a friction heater aimed at a furnace to power it as I feed items in via EnderIO conduits. However, in the middle of setting it up, after the furnace and heater were both placed, my Minecraft would crash. Logging back into the server would sometimes work fine for a bit before crashing again, or sometimes it would just crash immediately on render.

The error is the same each time: a NullPointerException with the description "Rendering Block Entity":
 https://pastebin.com/yvnugxer

**Comment by ReikaKalseki** [comment]
I am pretty sure this is fixed for the next release.

**Comment by Shadowsoftime99** [comment]
Is there a way to avoid this crashing the game during the interim before next update? If it's just visual rendering causing it I'll bury the setup under the floor or something.

**Comment by ReikaKalseki** [comment]
That will not cause it not to render. You would need to put it somewhere far away or in another dimension, or in an ArchiSections room.
