### ISSUE TITLE
ReactorCraft V24a Concrete can't block neutrons.

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2373]
It implements NeutronBlock and the function onNeutron() always return false
as well as neutrons first determine whether the block implements NeutronBlock.
This causes concrete lost the ability to block neutrons.
![1](https://user-images.githubusercontent.com/58476103/77681384-33bb1200-6fd0-11ea-80f6-d7147629612c.jpg)
![2](https://user-images.githubusercontent.com/58476103/77681391-3584d580-6fd0-11ea-8caa-d548a4027e83.jpg)
![3](https://user-images.githubusercontent.com/58476103/77681688-adeb9680-6fd0-11ea-9f76-1a55829527a1.jpg)
![4](https://user-images.githubusercontent.com/58476103/77681690-b04df080-6fd0-11ea-8c5d-830352090481.jpg)

**Comment by ReikaKalseki** [comment]
Fixed.
