### ISSUE TITLE
[CrC] Unable to break dimension core of completed dungeons

### ISSUE THREAD

**Issue by ninjanomnom** [ReikaKalseki/Reika_Mods_Issues#2377]
This has happened to every dimensional core I've been able to reach so far. The first time was with the switch dungeon and the core couldn't be broken. I searched for similar issues and apparently that dungeon has some anti-bruteforcing so I assumed that had triggered. The second time was the non euclidean maze which I got through fairly normally and couldn't break the core. The most recent time was the 3d maze.

After getting to the core in the 3d maze I finally decided to look into the code and nbt data to try and figure out what could be preventing me from mining it. No luck, the closest thing that seems a bit off is the struct tag being 0 when it looks like the code is supposed to be using that value to link it to the structure.

**Comment by ReikaKalseki** [comment]
Already fixed for the next release.

**Comment by ninjanomnom** [comment]
That would explain why I couldn't find any problem in the code, I was looking at the most recent
