### ISSUE TITLE
[CC] [v25a] Game crashes while trying to craft Crystalline Stone Columns

### ISSUE THREAD

**Issue by wamc2017** [ReikaKalseki/Reika_Mods_Issues#2379]
Hi,

the game crashes when trying to craft Crystalline Stone Columns in the casting table.
I tried it with only DragonApi and ChromatiCraft installed and it's reproducable.

Versions:
Forge: 10.13.4.1614
DragonApi: 1.7.10 V25a
ChromatiCraft:  1.7.10 V25a

Crash Report can be found here: https://gist.github.com/wamc2017/14c3776fb3fc8cb1f14cfcec8d5908bc

Thanks for looking into it.

Kind regards,
wamc

**Comment by ReikaKalseki** [comment]
Fixed.
