### ISSUE TITLE
[RoC] [Request] Update Fractination Unit Recipe Preview in NEI

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2380]
The new Jet Fuel Recipe looks like this: 
![Screenshot_149](https://user-images.githubusercontent.com/41554385/78162694-86208680-7447-11ea-95f9-52291201c936.png)

While the Recipe Preview still looks this: 
![Screenshot_150](https://user-images.githubusercontent.com/41554385/78162749-9df80a80-7447-11ea-8240-d2876c0bbb07.png)

Is there something that can be done about this?

**Comment by ReikaKalseki** [comment]
That the GUI layout is dissimilar is not important, but the lack of mention of liquid ethanol is.

**Comment by ReikaKalseki** [comment]
Done.
