### ISSUE TITLE
[Chromaticraft] Tile Accelerator self-throttling messages spam log, slow down server

### ISSUE THREAD

**Issue by eugennc** [ReikaKalseki/Reika_Mods_Issues#2386]
- Issue:
Chromaticraft's Tile Accelerators spam the server log with throttling messages, e.g.:
> [15:47:22] [Server thread/INFO] [FML/]: CHROMATICRAFT: Tile Accelerator Tile Entity Tile Accelerator @ DIM0: 738, 6, 7631 is self-throttling due to lag (1000706 ns), accelerating com.rwtema.extrautils.tileentity.transfernodes.TileEntityTransferNodeInventory@12254bd7

This I/O further slows down the server, resulting in a chain reaction of throttling messages spam.
(This is not particular to the Transfer Node. Tile Accelerators adjacent to Blast Furnaces, Chroma Collectors, Item Fabricators get it as well.)
- Mod version:
  I've only observed this issue after upgrading to v25b. Never had it in v24c.
- Suggested fix:
  Add a Chromaticraft configuration option to turn off self-throttling messages. Or, a more involved solution: have Tile Accelerators have a visual feedback when they've self-throttled often in the recent past. This moves the error feedback from the slow file I/O to the faster visual interface.
- Partial workaround:
I've mapped the logs directory to a tmpfs (ramdrive), as opposite to the SSD it was residing on previously. Increasing the I/O speed did reduce the server slowdown, but the issue still remains.

**Comment by ReikaKalseki** [comment]
It should run at most once per second per accelerator, and only in cases where accelerating that particular tile took more than the maximum allowed per-accelerator-tick time.

In other words, sufficient spam as to cause lag is not supposed to be possible.

That said, visual feedback is probably better.

**Comment by ReikaKalseki** [comment]
Done.

**Comment by eugennc** [comment]
Thank you. I was/am using multiple accelerators, each for 3 or 4 machines each.
