### ISSUE TITLE
[CrC] [V25b] Transposition gate crashes on first use

### ISSUE THREAD

**Issue by LilithThePowerful** [ReikaKalseki/Reika_Mods_Issues#2389]
Crash log: [https://pastebin.com/cauzG4CE](https://pastebin.com/cauzG4CE)
How to reproduce: Load a game with DragonAPI V25c and Chromaticraft V25b.
Build (or spawn) a transposition gate.  Step inside.  The game will crash.
Subsequent uses will work normally.  Everything else seems to work fine, although I haven't thoroughly tested all of it.

**Comment by ReikaKalseki** [comment]
Fixed.
