### ISSUE TITLE
Crash When Pressing Page Down When using The Exchanger From Ender Tech

### ISSUE THREAD

**Issue by RoloEdits** [ReikaKalseki/Reika_Mods_Issues#239]
When pressing the page down key to change the size of the exchanger i'm getting this crash

http://pastebin.com/63McLBm9

galactic craft core is also reporting something in the crash log, but I believe I see that the dragon api is watching for keys so i'm reporting this here, but i'm not sure if i should be reporting this to you or not.
if its the case that i'm reporting to the wrong place then i'm sorry for troubling this with you and if you could direct me in were the problem lies so i could report it to them that would also be extremely helpful.
Thank You In Advance.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by RoloEdits** [comment]
Thank You Very Much
