### ISSUE TITLE
Texture issues

### ISSUE THREAD

**Issue by MuiGoku123432** [ReikaKalseki/Reika_Mods_Issues#2392]
My game textures for rotarycraft are extremely messed up.
![image](https://user-images.githubusercontent.com/59211627/78301023-18836180-74fe-11ea-8d65-32215c75cedc.png)

**Comment by wamc2017** [comment]
Either set "Enable Temporally Dependent Amusement Behavior" in DragonAPI.cfg to false or wait until 4/3/2020 and the textures should revert back to normal... ^^

**Comment by LilithThePowerful** [comment]
This is not a bug.  It is the april fools joke for rotarycraft.
Take a close look at the crystal pylons for chromaticraft's joke.
