### ISSUE TITLE
[DragonAPI] [V25c] DragonAPI fails to force load dimensions for chunk loading

### ISSUE THREAD

**Issue by LilithThePowerful** [ReikaKalseki/Reika_Mods_Issues#2393]
Effected blocks: Pylons and world rifts(with rift chunkloading turned on), rotarycraft chunk loader.
The nether and end are unaffected, but in all other dimensions, chunk loading fails until something else loads that dimension, upon which DragonAPI based chunk-loaders work correctly.
I achieved this using a chicken chunks spot-loader.  It does _not_ need to load the other chunkloader for it to work either.

Mods used:
Forge 10.13.4.1614-1.7.10
DragonAPI V25c
Rotarycraft V25b
Chromaticraft V25b
CodeChickenCore 1.7.10-1.0.7-47
ChickenChunks 1.7.10-1.3.4.19
Mystcraft 1.7.10-0.12.3.04

Steps to replicate:
Create another dimension (like with mystcraft) or add a mod that adds a dimension (such as extra utilities)
Set up a chunk loader or drain a pylon.  Return to the overworld.
Save and quit, then reload the world.
Use /chunkloaders to view currently loaded chunks.  The chunkloaded dimension will not appear.
Return to the dimension.  Add a chickenchunks (or other chunkloader) to the dimension (it does not need to overlap with the other chunkloader you placed earlier.)
Return to the overworld.  Save and quit again.
Check with /chunkloaders again.  The dimension is now loaded, and all the chunkloaders are functioning correctly.

Addendum: It seems that once a chickenchunks loader has force loaded the dimension at least once, the issue resolves itself permanently. (see dimension 2)

Log: https://drive.google.com/open?id=1xqIoYvLd5mzsGx1B7IMOajHiBAZLTupQ
World download: https://drive.google.com/open?id=1ikv8AS5e8vmRqv6V6_U_8Iyxg4ukC07c

**Comment by ReikaKalseki** [comment]
I do not have any code to force-load dimensions. Forge tends to do that itself.
