### ISSUE TITLE
[RC] [V25b] Rotarycraft fluid pipes try to connect with any ME cable, even when there is no appropriate fluid bus.

### ISSUE THREAD

**Issue by LilithThePowerful** [ReikaKalseki/Reika_Mods_Issues#2395]
It seems to be only a visual glitch, but it still causes problems when you run ME and fluid pipes in the same space, making seeing where your fluid pipes have connected to much harder than it should be.

![Rotarycraft_Pipes_Connect_to_ME_cables](https://user-images.githubusercontent.com/2541297/78401326-7d09f380-75c6-11ea-93e1-2a8a6a2b3d0e.png)

**Comment by ReikaKalseki** [comment]
Because all ME blocks are IFluidHandlers, and there is no way to know if it "really" can carry liquids. BC pipes, EiO conduits, and every other pipe do the same, to ME blocks and to each other.
