### ISSUE TITLE
[DragonAPI][v25c]Version tracker throws ArrayIndexOutOfBoundsException when encountering a mod without a version number.

### ISSUE THREAD

**Issue by AssasinAsha** [ReikaKalseki/Reika_Mods_Issues#2397]
This took a moment to figure out but here goes.
The new tracker system crashes when the file it creates on world load has a mod with no version number at all.
In this case the offender is Micdoodlecore, the dependency of Galacticraft. I think it's because it doesn't have mcmod.info inside itself, so it gives no version number when asked.
Crash report here:
https://pastebin.com/Xfc0wyef

The list generated by the tracker on world load, located in save folder.:
https://pastebin.com/j3xsZY8a
Note lack of value by Micdoodlecore.

Manually adding a number to Micdoodlecore on the list or deleting the file entirely allows the world to load. Obviously, next world load crashes again due to list update. 

Galacticraft is in the instance because Micdoodlecore crashes the game (on world load at that) without its presence. -.-

I added the exception to issue title for search purposes.

**Comment by ZenSkylark** [comment]
I do have the same problem as well...
From me,  I have Galacticraft and other 130+ mods as well...
But when I run it for the first time it....... it works, then the 2nd time in open the world, Boom It crashes.

Note:
- I'm using the latest version of Minecraft Forge 1.7.10
- 64x bit Java user
- 8 GB memory
- It runs normally without your mods.

Here is the Crash Report.
[2. (Same) crash-2020-04-07_16.51.29-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4443144/2.Same.crash-2020-04-07_16.51.29-server.txt)

But most likely I am referring to no.2
If you want, I can give you my mod I'm using and the world.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by Goddfrey** [comment]
It still does crash (v25c)
https://pastebin.com/Eipi8rvt

**Comment by Goddfrey** [comment]
It still does crash for me (v25c)  upon loading the world in single player. The same exception about index out of bounds and version tracker.

**Comment by ReikaKalseki** [comment]
Fixed != Released.

**Comment by lAimBotl** [comment]
Same crash as op, giving mcdoodle core a version also lets the world load (SP).

**Comment by AnrDaemon** [comment]
To clarify the actual fix, find the `~/world/modversions.list` file, and remove the line saying `Micdoodlecore=` from it, then start the server. The line will be replaced with `Micdoodlecore=[NONE]` and server will work onward.
