### ISSUE TITLE
Severe FPS lag

### ISSUE THREAD

**Issue by dadude857** [ReikaKalseki/Reika_Mods_Issues#24]
Rotarycraft really hurts my fps!

![Like 10 fps](http://s1.postimg.org/loy7tgkxb/2015_04_21_12_34_28.png)

**Comment by 1Matthias** [comment]
Mods, versions, and what were you doing? Anything in the FML log?

**Comment by dadude857** [comment]
latest rotarycraft plus tinkers plus thaumcraft plus applied energistics plus natura plus biomes plenty plus enderio plus thermalexpansion plus minefactory. I was just getting ready for grinding ores, notthing wierd.

**Comment by 1Matthias** [comment]
Odd. What kind of a drop are we talking about here? From 40 to 12, or 15 to 12?

**Comment by dadude857** [comment]
I normally get like 70 fps

**Comment by 1Matthias** [comment]
Hmmm....any other machinery nearby? Also, is this spikes of low FPS, or is a sustained issue?

**Comment by dadude857** [comment]
FPS stays bad, got a grinder and some thermal expansion in the basement.

**Comment by 1Matthias** [comment]
Hmm. What are the specs on your computer, and have you tried giving minecraft more RAM? Just noticed, you are only giving it 1.2 GB.

**Comment by dadude857** [comment]
My computer is good, its almost 2k$ and I get much better FPS without rotarycraft installed!

**Comment by 1Matthias** [comment]
I am not interested in how much it cost, I just want to know the specs. it is not a reflection on your computer, I just have to ask to be able to provide support.

**Comment by dadude857** [comment]
its an X51

**Comment by 1Matthias** [comment]
I need CPU, RAM, Graphics card, OS and Java version.

**Comment by dadude857** [comment]
I don't know all that!

**Comment by zemerick** [comment]
To clarify, removing Rotarycraft doesn't specifically mean it causes FPS issues. There are a number of other possibilities still, such as a mod interaction that is going bad, or a problem in say your specific installation of Java that is being called only by Rotarycraft.

The setup you show there is incredibly simple, and shouldn't cause any FPS issues. It normally takes something on the nuclear reactor level, or at least a very large machine room to see any changes, and we're normally talking 10-30%, not 75% drop in FPS. ( My fusion reactor in my current world only causes about a 10 FPS drop for example. )

If on windows, can you go to the start menu and in the search bar, type:
dxdiag.exe
and press enter. Select Save All Information, and save it somewhere you can find. Paste the text into pastebin, and send us the link.

Is this single player, or a server?

Can you replicate this in a clean world? Preferably flat, so we can see everything in the view clearly.

Is it a specific machine or something, that caused this?

Try installing Opis and running a scan. It might spot something being troublesome, though it's not really meant to find FPS issues.

**Comment by dadude857** [comment]
All I know is that rotarycraft lag!

**Comment by coolsquid** [comment]
Post your FML log on [Gist](gist.github.com).

**Comment by frogfigther** [comment]
i have a feeling that the minecraft instance just is not getting enough memory so the garbage collector has to run a lot, and causing the fps lag you are experiencing. try dedicating 4 gigs of ram and have a permgen of 256mb. that should (most likely) fix any potential memory issues.

**Comment by zemerick** [comment]
He has very few mods, 4 gigs is not needed. 1820 is probably plenty, but it shouldn't hurt to go up to something like 2 to 2.5 gigs. ( For comparison, the last large pack I ran on 1.7.10 needed less than 2.5 gigs, and it stated well over 200 mods. OPs F3 only counts 40. )

Also, it's usually the other way around. Too much memory allocated causes GC to go nuts. If you don't have enough, it tends to just crash with an OOM message.

**Comment by frogfigther** [comment]
i just said 4 gigs because he seems to using 87% of his memory. and 4 gigs is not enough to get the GC to go crazy

**Comment by zemerick** [comment]
He's got separate min and max memories. 731MB isn't 87% of the max. It just hasn't re-allocated more memory yet.

This does remind me of another issue though. I don't recall the specifics, but I had several issues when my min and max were different values.

OP, you can try setting them both to the same value ( 2G should work, 3G if you want to be safe. )

We also still need the information we posted about. We can't find the specific cause without it.

**Comment by 1Matthias** [comment]
To be able to find out why you are lagging, we need that information. Not giving us this information is like calling a mechanic and saying your car is making a noise, without saying what make, model, year, or type of car you have. So, if you could please just get that information, we can help you with the lag.

**Comment by 1Matthias** [comment]
Also, you mentioned that your computer is worth 2k. If you don't know what you have in your computer, how do you know that you did not get ripped off by whoever sold you your computer? Knowing what you have for hardware is exceptionally useful in this day and age.

**Comment by AssasinAsha** [comment]
Try updating other mods, not only Rotarycraft. I recreated your setup using most up-to-date versions of the mods you listed plus NEI. Works like a charm, but not on your Forge version, doesn't even run with 1291. Which means you have old versions of other mods, which might contribute to the issue. Cross-mod compatibility is a sneaky beast like that.
Or at least give us the versions of the mods you are using, so we can properly create a testing instance.

As for X51, looking it up shows as Alienware brand, with the most expensive default version (about 1,7k, default options) being, copying directly from their site:
CPU: 4th Generation Intel® Core™ i7-4790K Processor (Quad Core, 8MB Cache, up to 4.4GHz w/ Turbo Boost)
GPU: NVIDIA® GeForce® GTX 960 with 2GB GDDR5
RAM: 16GB Dual Channel DDR3 at 1600Mhz
HDD: 256GB SSD SATA 6Gb/s + 1TB SATA 3Gb/s (5,400RPM) 16MB Cache
OS: Windows® 8.1, 64Bit

As I'm not into hardware, I don't have anything to say on this laptop.

**Comment by coolsquid** [comment]
Falsifying images is not supported.

**Comment by zemerick** [comment]
That's actually a desktop, not a laptop. It's also a pretty good gaming rig, certainly well beyond MC.

**Comment by 1Matthias** [comment]
Ok. Just looked really closely at the fps meter, you photoshopped the fps from another image into this image. No more support. (For others, look really closely at the wood texture behind the FPS.)

**Comment by zemerick** [comment]
I wondered if the image was doctored, and should have looked. I couldn't think why it would say 87% usage, when 731 is not 87% of 1820. ( If you actually look, the 87 is VERY obviously shopped. )

**Comment by ReikaKalseki** [comment]
A first time for everything:

![](http://i.imgur.com/blJob4l.png)

**Comment by zemerick** [comment]
<sigh> It seems a lot of our time is going to be weeding out fake stuff.

At least they should make nice additions to your wall of shame!
