### ISSUE TITLE
Chromatic enchanter Crash

### ISSUE THREAD

**Issue by Nisnis39** [ReikaKalseki/Reika_Mods_Issues#2400]
Hello, 
I'm playing chromaticraft V25b with DragonAPI V25c on a private server and when i right-click on the chromatic enchanter the game crash.
It also happen to my friend, on don't know if the bug is related with the update it's the first time i crafted this object.

here my crash log:
https://pastebin.com/6ZjnSvPP

Thank you for this awesome mod =)

**Comment by Nisnis39** [comment]
After testing, it do work well in chromaticraft V24c/Dragon API V24c but crash in V25

**Comment by ReikaKalseki** [comment]
Fixed.
