### ISSUE TITLE
[CrC] Unable to craft lumen repeater after update.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2403]
![2020-04-05_12 06 03](https://user-images.githubusercontent.com/62176592/78466642-173c7980-7736-11ea-8d43-71878a9cb817.png)
I am unable to craft lumen repeater after updating the mod. Not sure if related but I was making 2 stacks of power crystals before I tried to craft the lumen repeater.

![2020-04-04_01 40 34](https://user-images.githubusercontent.com/62176592/78466711-f4f72b80-7736-11ea-9270-2c630d4e204b.png)
The game is also calling for v25d but I've checked the latest download is v25c. 

Game version:
DragonAPI v25c
Chromaticraft v25b

**Comment by tiny-maple** [comment]
![2020-04-05_13 44 12](https://user-images.githubusercontent.com/62176592/78467837-95534d00-7743-11ea-9afe-b22ca3ddd409.png)

I'll temporary roll back to v24c to finish linking all pylon colours to my casting complex.

**Comment by wamc2017** [comment]
Have you checked the Personalized Casting entry? After updating the runes changed on my side, maybe you got the same issue?

**Comment by tiny-maple** [comment]
Oh my Personalized casting entry got altered too. Was this intended as updating the runes position allowed me to craft the repeaters.
