### ISSUE TITLE
(Cromaticraft v25b) Elemental Manipulator resets stored Energy and Capacity 

### ISSUE THREAD

**Issue by ThomasDennisSp** [ReikaKalseki/Reika_Mods_Issues#2406]
I have the problem that whenever I take the Elemental Manipulator out of my Inventory the stored Energy and the Capacity resets it to the point as if I just started but it only happens when I reached max Capacity.
I filled it 4 times already and then I accidentally places in a Chest then it is resetted.

**Comment by Kobra331** [comment]
Afaik the Energy is stored on the Character itself and not on the manipulator. Did you die? After Death you lose all your energy

**Comment by ThomasDennisSp** [comment]
yes i did die thx for answer
