### ISSUE TITLE
Mod does not work ReactorCraft

### ISSUE THREAD

**Issue by kosthar4uk** [ReikaKalseki/Reika_Mods_Issues#2409]
When I started playing with the mod, problems were found in it: the turbine does not work when steam is supplied, the reactor does not heat up, and the boilers do not heat up.

**Comment by eugennc** [comment]
If the reactor does not heat up, how can the boilers produce steam?
Also, what reactor layout are you using?

**Comment by Kobra331** [comment]
Its a simple mechanic. If your reactor doesn't heat up --> More Fuel cores/ Less boilers
If you reactor explodes ---> More Boilers / less fuel cores

**Comment by ReikaKalseki** [comment]
That is a gross oversimplification, but at any rate, it is clear that the designs being attempted are far from viable, and entire sections of the infrastructure are missing.
