### ISSUE TITLE
Irradiation chamber does not accept heavy water.

### ISSUE THREAD

**Issue by quedral** [ReikaKalseki/Reika_Mods_Issues#241]
In my creative test world irradiation chamber near fission core can accept and convert regular water to heavy water as designed however an empty chamber does not accept heavy water. Heavy water gets stuck in pipe and never gets in to chamber from top (or any other side i tried) 

I am not sure if i am missing something or any mechanic that i know of was changed recently

I am using latest version of reactorcraft and Forge 1448

Thanks in advance

**Comment by ReikaKalseki** [comment]
You likely still have normal water in the chamber (or its output tank is full). I have some running as normal as I type this.

EDIT:
I misread the original post. There is no recipe involving heavy water as an input.

**Comment by quedral** [comment]
i assure you that's not the case. it does accept deuterium and water without issue. just not the heavy water for some reason.

![2015-09-10_22 44 37](https://cloud.githubusercontent.com/assets/9392435/9799161/36d46510-580e-11e5-9deb-96bfff621dc2.png)
![2015-09-10_22 44 43](https://cloud.githubusercontent.com/assets/9392435/9799160/36d41222-580e-11e5-95df-565e94cbc4c2.png)
![2015-09-10_22 44 49](https://cloud.githubusercontent.com/assets/9392435/9799163/36db470e-580e-11e5-8b9e-a7e4b89ed385.png)
![2015-09-10_22 44 56](https://cloud.githubusercontent.com/assets/9392435/9799162/36d7db00-580e-11e5-8eb4-79a7577f2a79.png)

**Comment by ReikaKalseki** [comment]
Wait...heavy water? I for some reason read that earlier as deuterium. There is no recipe with heavy water as the input, and what are you trying to make?

**Comment by quedral** [comment]
Don't you make deuterium from heavy water? pump heavy water to chamber and shouldn't it convert to deuterium in any fission reactor?

my initial setup idea was like this:

water -> chamber -> heavy water
heavy water -> chamber -> deuterium
deuterium -> chamber -> tritium

tritium + deuterium + tokamak reactor = profit?

**Comment by ljfa-ag** [comment]
I can't really comment on ReC details but that makes no sense from a chemistry standpoint. Heavy water is a compound of deuterium and oxygen, you need to electrolyze it to get deuterium.

**Comment by ReikaKalseki** [comment]
> Don't you make deuterium from heavy water?

Not by irradiating it.

**Comment by quedral** [comment]
Yeah i forgot a step in production line and made one up it seems.
