### ISSUE TITLE
[Electricraft] RF Battery showing two different type of capacity values.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2411]
![2020-04-07_18 22 25](https://user-images.githubusercontent.com/62176592/78658769-30dbed80-78fd-11ea-8de0-b01df008a7ef.png)
Minor issue, RF battery display the old value of 2147483646/ 2147483646 RF and new 5.115RF/60TRF

**Comment by ReikaKalseki** [comment]
The top one is WAILA's doing, and it cannot handle capacities over Int.MAX - that 2.147 billion value.
