### ISSUE TITLE
[ReaC] Add Valve to Regulate Flow of Fusion Plasma

### ISSUE THREAD

**Issue by developer9199** [ReikaKalseki/Reika_Mods_Issues#2412]
I was thinking, it'd be a really cool feature if there was some sort of a solenoid valve (or just any valve) that could stop the flow of fusion plasma. This would further help manage a fusion reactor. For example, when the fusion plasma starts flowing from the preheaters, I can flip a switch to inject the plasma into the ring, and then flip it back to stop the flow of plasma and prevent it from flowing within the ring. You could stop the fusion reaction by the flip of a switch. I'd be a really useful feature in the already amazing mod.

**Comment by ReikaKalseki** [comment]
Apply a redstone signal to the injector.
