### ISSUE TITLE
[DragonAPI/OpenComputers] getNBTTag() not working

### ISSUE THREAD

**Issue by ninjanomnom** [ReikaKalseki/Reika_Mods_Issues#2415]
It throws the exception 
`li.cil.repack.com.naef.jnlua.DefaultConverter$18 cannot be cast to java.lang.String`

**Comment by ReikaKalseki** [comment]
I have no idea what that means.

**Comment by ninjanomnom** [comment]
The class LuaGetNBTTag which exposes the getNBTTag function in the dragon api code doesn't work and throws that error when you try. It's accessible via opencomputers which I assume is why that was put there.

**Comment by ninjanomnom** [comment]
Just in case it makes a difference, I was trying to use it with the electricraft auroral battery.

**Comment by ReikaKalseki** [comment]
I think you are using it wrong, or they have a bug, because the returned objects are always supposed to be one of a few specific types: ![https://i.imgur.com/FMBRUX4.png](https://i.imgur.com/FMBRUX4.png)
