### ISSUE TITLE
[RotaryCraft:Suggestion] Make Fractionation Unit explode from over-pressure beyond 1MPa.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2417]
![2020-04-10_22 54 48](https://user-images.githubusercontent.com/62176592/79000322-fb463700-7b7e-11ea-8beb-a5720849058e.png)
Was kind of expecting Fractionation unit to explode from over pressure. If the max is 1MPa using 4 microturbine, is it possible to make it explode if the pressure continue to rise beyond that?

**Comment by ReikaKalseki** [comment]
No, I have no desire to do that.
