### ISSUE TITLE
[DragonApi + Thermal foundation -> crash] java.lang.ArrayIndexOutOfBoundsException: 11 	at cofh.thermalfoundation.block.BlockOre.getLightValue(BlockOre.java:51)  

### ISSUE THREAD

**Issue by T5UN4M1** [ReikaKalseki/Reika_Mods_Issues#2418]
I get a crash in a specific location. I remember having this problem a long time ago with older version.
The crash seems to be caused by a compatibility issue bitween DragonApi and Thermal foundation.
I'm not sure which one is at fault.

The crash happens when I visit a specific location (it was the same situation with older version) so I just lay a waypoint and avoid that specific location and I'm fine.

I'm using latest release of DNS techpack with your mods updated to latest version and the addition of Chroma and ER.

I tried updating Thermal foundation and Cofh Core  to latest version but the issue persists.

https://pastebin.com/80CweKFF

edit : fastcraft is also mentioned in the crash report but I highly doubt it's the cause, I found this topic, the situation is similar (it's quite old though) , crash involving DragonApi TF and fastcraft and the crash was still there after removing fastcraft : https://minecraft.fr/forum/threads/crash-apr%C3%A8s-5-minutes.189416/

**Comment by ReikaKalseki** [comment]
This is not my doing either. And probably not CoFH/TF's, either; you have a block with invalid metadata somewhere.

**Comment by OvermindDL1** [comment]
I've seen TF's ores get generated with invalid metadata before, unsure of the cause, but not handling that failure case when the engine is known to do that at times is indeed a bug in TF.  Not a DAPI issue.
