### ISSUE TITLE
applied energistic v3

### ISSUE THREAD

**Issue by aldro01** [ReikaKalseki/Reika_Mods_Issues#2419]
hi reika chromaticraft crash with appliedenergistic rv3

**Comment by wamc2017** [comment]
Without a crash report, it's hard to say, but I guess this is a dupe of https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/481

Try setting exportItemNames to false in AppliedEnergistics2/CustomRecipes.cfg ....

**Comment by aldro01** [comment]
ok I'll try thanks

**Comment by aldro01** [comment]
it works thanks

**Comment by ReikaKalseki** [comment]
#1732 #1683 #1681 #1493 #1257 #1280 #1238 #2390 #1848 #1985
