### ISSUE TITLE
Expanded Redstone Item Effector leaves "ghost" items

### ISSUE THREAD

**Issue by delax** [ReikaKalseki/Reika_Mods_Issues#242]
I've noticed this with records and saplings, two items that should be used up when "activated".

The setup used as an example here is a simple sapling planter:
http://i1120.photobucket.com/albums/l484/delax000/Screenshots/2015-09-10_14.36.16.png
http://i1120.photobucket.com/albums/l484/delax000/Screenshots/2015-09-10_14.36.34.png
http://i1120.photobucket.com/albums/l484/delax000/Screenshots/2015-09-10_14.36.48.png
http://i1120.photobucket.com/albums/l484/delax000/Screenshots/2015-09-10_14.36.54.png
http://i1120.photobucket.com/albums/l484/delax000/Screenshots/2015-09-10_14.37.06.png
http://i1120.photobucket.com/albums/l484/delax000/Screenshots/2015-09-10_14.37.15.png

Modlist:
- Forge 10.13.4.1448
- Dragon API v8g
- Expanded Redstone v8a

**Comment by ReikaKalseki** [comment]
Define "ghost". Stack size of zero (and deleted on inventory resync)? Or an actual item duplication?

Also, the block placer is the one you should be using for saplings.

**Comment by delax** [comment]
Probably the first one.
The item left behind in the effector disappears when manually used (planted) or when the original is in the same inventory (whether yours or the effector's).
It is **definitely** not actual duplication (thus the term "ghost"), but almost more of a visual glitch.

**Comment by ReikaKalseki** [comment]
It was a stack size zero issue. Fixed.

Also, I just blacklisted the effector from placing blocks, as that is the job of the block placer.
