### ISSUE TITLE
[Chromaticraft] Crash with ME hotbar and offline ME system

### ISSUE THREAD

**Issue by ninjanomnom** [ReikaKalseki/Reika_Mods_Issues#2423]
https://pastebin.com/eABZA9wd

I'm playing on a server and when I use the transition star with the ME hotbar and ME system offline it crashes the server. 

Probably related, around the same time if I place a single block of a 64 stack I disconnect due to internal server error, no server crash though.

Neither of these got fixed from the server rebooting but relinking with the ME system did.

**Comment by ReikaKalseki** [comment]
Fixed.
