### ISSUE TITLE
[Chromaticraft]. Unable to turbocharge pylon on biome borders.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2426]
I manged to turbocharge all my other pylons except this pylon on a biome border between a river and desert. 
![2020-04-15_16 51 28](https://user-images.githubusercontent.com/62176592/79318500-a8330200-7f39-11ea-9907-d1a33e9e5a87.png)
Ring is completed around pylon.
![2020-04-15_16 52 37](https://user-images.githubusercontent.com/62176592/79318516-af5a1000-7f39-11ea-96c7-59dc37349db4.png)
Clear view of the sky
![2020-04-15_16 51 49](https://user-images.githubusercontent.com/62176592/79318566-c1d44980-7f39-11ea-8449-b35ec00a315b.png)
Right clicking on the middle foci does not activate the turbocharging ritual. 

![2020-04-15_16 55 43](https://user-images.githubusercontent.com/62176592/79319377-cfd69a00-7f3a-11ea-8f84-bf41f6830059.png)
I tried performing the ritual on other pylons and I am able to activate the ritual. Only this pylon is unable to activate the ritual.

**Comment by ReikaKalseki** [comment]
The code does not check biomes or anything else biome-specific; check for sky obstruction (eg Natura clouds).

**Comment by tiny-maple** [comment]
Yea it the clouds, I thought they were just ordinary clouds.
