### ISSUE TITLE
[ReactorCraft] Neutron Shields have a chance of spawning radiation (Intended?)

### ISSUE THREAD

**Issue by Thorinair** [ReikaKalseki/Reika_Mods_Issues#2427]
Considering I have removed all non-neutron related blocks from the path of my neutrons, I have spent most of the morning today studying the source code of how the neutrons work to try and figure out why am I still having radiation spawning all over.

That said, I have come to a conclusion that shielding blocks themselves can spawn radiation. This happens specifically on this line of code: https://github.com/ReikaKalseki/ReactorCraft/blob/master/Entities/EntityNeutron.java#L105 because the code carries on happily after passing through the shielding block and then triggers this line: https://github.com/ReikaKalseki/ReactorCraft/blob/master/Entities/EntityNeutron.java#L128

In other words, if a shielding block does not manage to stop a neutron, it itself may spawn a radiation blob.

If this is intended behaviour, you are welcome to close this issue, but I remember you saying that a radiation can spawn only if its not a reactor block or an explicit shielding block: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2157#issuecomment-520591083

Below is a screenshot of a radiation inside a steel block. During a very lengthy test, none of the fluorite have lit up (you can see them on the outside perimeter here), so I assume I didn't have any escaping neutrons, other than the ones hitting the shielding.
![image](https://user-images.githubusercontent.com/7534126/79324360-cf74d980-7f0f-11ea-8e55-0a323b303007.png)

**Comment by ReikaKalseki** [comment]
The recent rewrites probably changed this.
