### ISSUE TITLE
Expanded Redstone Item Effector has incomplete jukebox functionality

### ISSUE THREAD

**Issue by delax** [ReikaKalseki/Reika_Mods_Issues#243]
With a simple setup of Jukebox + Item Effector (w/ records) + lever, you can play a record when you pulse the lever.
However, _further_ activations do nothing.
The expected function would be for the record to pop out like you had right clicked on it, and there isn't any documentation to suggest other wise.

http://i1120.photobucket.com/albums/l484/delax000/Screenshots/2015-09-10_14.37.53.png
http://i1120.photobucket.com/albums/l484/delax000/Screenshots/2015-09-10_14.37.56.png
http://i1120.photobucket.com/albums/l484/delax000/Screenshots/2015-09-10_14.38.03.png
http://i1120.photobucket.com/albums/l484/delax000/Screenshots/2015-09-10_14.38.12.png

(you can also see an example of "ghosting" (#242) here as well.)

Modlist:
- Forge 10.13.4.1448
- Dragon API v8g
- Expanded Redstone v8a

**Comment by ReikaKalseki** [comment]
The item effector is not an Autonomous Activator. It is designed for triggering item right-click code. With no item, it does nothing.

**Comment by delax** [comment]
Alright, so "right-clicking" with a second record on a jukebox (to pop out the first) probably isn't part of the _item_ code, but the _jukebox_ code (thus nothing to do with the item effector).
Got it.

**Comment by ReikaKalseki** [comment]
Correct. More technically, onBlockActivated rather than onItemUse.
