### ISSUE TITLE
[Void Monster] GL Error spam

### ISSUE THREAD

**Issue by charagarlnad** [ReikaKalseki/Reika_Mods_Issues#2431]
It seems that the shader used for the Void Monster has some sort of problem, as it generates thousands of GL errors within a few seconds in the log file. No other mods installed other than DragonAPI and Void Monster.

```
[21:56:59] [Client thread/ERROR]: ########## GL ERROR ##########
[21:56:59] [Client thread/ERROR]: @ Post render
[21:56:59] [Client thread/ERROR]: 1282: Invalid operation
...repeats for a few thousand lines until I look away from the void monster
```

Mod Versions:
Forge 1614
DragonAPI v25c
VoidMonster v25b

**Comment by MalTeeez** [comment]
I encountered the same Problem but only with the blackscreen bug being active, the second it was fixed(resizing window) the Errors stopped

**Comment by charagarlnad** [comment]
> I encountered the same Problem but only with the blackscreen bug being active, the second it was fixed(resizing window) the Errors stopped

That's a seperate issue, the black screen bug does cause the same errors to fill the log at a similar rate though. After resizing the errors go away until I look at the Void Monster, and it doesn't happen with other shader effects e.g. CC pylons, warp nexus

**Comment by ReikaKalseki** [comment]
This does not happen for me, and there is not really a way to debug GL errors...

**Comment by charagarlnad** [comment]
It seems this has been fixed sometime since April 15, can no longer replicate on v28a. Likely due to https://github.com/ReikaKalseki/VoidMonster/commit/d3fdb8127e9d132698b7a6efa66fc47b282b0019 as it has been the only change to the shaders since then.

**Comment by ReikaKalseki** [comment]
All that change was is moving a lot of library functions into modular files for a more dynamic and import-like shader programming environment; it resulted in no functional changes.
