### ISSUE TITLE
[Chromaticraft] Energy Focal Point won't stack after placing and breaking.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2434]
![2020-04-17_18 10 32](https://user-images.githubusercontent.com/62176592/79595056-c7d05300-8110-11ea-8ecd-8f66ada15225.png)

![2020-04-17_18 10 12](https://user-images.githubusercontent.com/62176592/79595085-d28ae800-8110-11ea-8f3f-a023fc0a9ac5.png)

Similar issue to the previous version of Crystal repeaters which did not stack upon placement. Energy focal point does not stack with newly made ones.

**Comment by ReikaKalseki** [comment]
What are their NBT tags?

**Comment by tiny-maple** [comment]
Crafted: 
No tag

Placed in world and picked up with pickaxe:
`Owners: "<Tinymaple>"`

**Comment by ReikaKalseki** [comment]
Fixed.
