### ISSUE TITLE
[Chromaticraft] Concurrent exception crash

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2439]
Crash log: https://pastebin.com/sh59Vkab
I have 25 crash reports of this issue. I tried to troubleshoot which repeater is crashing but I can't even go near them without freezing or crashing.

**Comment by ReikaKalseki** [comment]
#1100 #1290 #2270 #2124

**Comment by tiny-maple** [comment]
Any temporary work around for this? I crash often with CME.

Just want to update on CME, I have used matter dissolution + CME crash to successfully duplicate items. 
Items i've duplicated: Ritual Table, Crystal Repeaters, Multi Aura repeaters/ runes, Fabricators.
Things cannot be duplicated: Crystalline stone bricks, their variant, pylon components will revert to their non energized components.
~~I have not yet tried duplicating Reactorcraft components or rotarycraft, will try when I have more resources.~~
Rotarycraft: Steel blocks. Can't really get it to work well, took me a several attempts to duplicate it.
For a higher chance to trigger CME, spam Multiaura repeaters to a several rings of fabricators.

**Comment by ReikaKalseki** [comment]
This is a very old issue that needs major, highly intensive rewrites - themselves depending on significant theoretical background in a lot of computer science and algorithm design - to fix.

**Comment by tiny-maple** [comment]
No worries mate, no rush for a fix on this. 

The positive side is CME + matter dissolution can allow mass duplication of items placed in the world, but doesn't seem like all items can get duplicated. When I begin to crash every 30s from abusing the CME dupe, I had massive number of items on floor and had to break my crystal network to salvage the world.

**Comment by OvermindDL1** [comment]
> This is a very old issue that needs major, highly intensive rewrites - themselves depending on significant theoretical background in a lot of computer science and algorithm design - to fix.

Not really an intensive rewrite, just remove all mutation of the container while iterations happen, easiest way is to just test if an iteration is happening on any mutation point and then saving out that call to run once the iteration is complete.  Though a full rewrite would be better as there are likely other ownership violations as well.  Nothing fancy with theoretical background or so, these are all programming 101 things about the number 1 source of bugs and how not to hit them.

**Comment by tiny-maple** [comment]
>Though a full rewrite would be better as there are likely other ownership violations as well.

I have 108 duplicate crash report on this CME, so I had to disabled anything that needs the crystal network to continue playing in the world. Does this crash often on a server hosting a modpack containing Chromaticraft?

**Comment by ReikaKalseki** [comment]
It never happens on dedicated server, for reasons noone has been able to determine (the claims of a server-specific try-catch are complete fabrications).

**Comment by OvermindDL1** [comment]
That also implies a potential cross-thread ownership violation as well...

**Comment by tiny-maple** [comment]
>It never happens on dedicated server

I suppose I will move my modpack to a server as currently I play on singleplayer.
