### ISSUE TITLE
Dragonapi from version V24 opengl 1283 until fullscreen adn dosent works whit last version Dragonblock C

### ISSUE THREAD

**Issue by Matachusets** [ReikaKalseki/Reika_Mods_Issues#2440]
Hello sir, whit this one i like to kill 2 birds whit 1 shoot if possible:

well, first afther update to this version, istarted to get "opengl 1283" whit black screen until i hit F11 and swich to full screen mode, then I update6to v25 and dragonblock was fine, then i updated (1.4.6.5)  to the last version 1.4.6.7 and dosent work neither V25 or V24 plus the unfixable error than i encounter here : https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2437.

Any ideas, please good sir?

I going to try to ask the dev of dragonblock on his discord, hope i get any reply soon, but the opengl 1282 is very annoying and this "maybe compability issue" i like to read what do you found like i like to read what at dragonblock c founds.

thanks in advance.

**Comment by ReikaKalseki** [comment]
#2397 #2413 #2420 #2435 and #2315
