### ISSUE TITLE
[Chromaticraft] Void linked bucket does not work

### ISSUE THREAD

**Issue by ninjanomnom** [ReikaKalseki/Reika_Mods_Issues#2441]
I've linked it to a crystal tank full of water and tried all combinations of right/left-click and crouching. I can only open the ui, link it to things, or change modes. I've got the max amount of lumen energy in case it needs that to work but no dice.

No errors in either the server or client log either.
![image](https://user-images.githubusercontent.com/1234602/79809381-4bbb5280-833e-11ea-9413-12abfc88bc12.png)

**Comment by ReikaKalseki** [comment]
It does, but it cannot see the data if you are out of client range. I still need to figure out a way around this.

**Comment by ninjanomnom** [comment]
I was right next to the crystal tank and it still wouldn't work

**Comment by ReikaKalseki** [comment]
I only just now realized what you are referring to. I thought you were referring to the missing fluid, but in fact you are referring to the first half of #2481.
