### ISSUE TITLE
[Chromaticraft] Unable to mine dimension core from Filter And Cycle puzzle.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2442]
![2020-04-21_12 54 10](https://user-images.githubusercontent.com/62176592/79826819-4bb76300-83cf-11ea-83eb-bb00775d918b.png)
I finished the puzzle, then tried to mine the dimension core. It does not drop and just keep replacing itself back on the original position. I have tried reach boost and use magnetism to pick up all the shards around it but cannot seem to make the dimension core drop.

**Comment by ReikaKalseki** [comment]
Did you actually solve the puzzle? You are describing the behavior that results when it thinks you skipped it.

**Comment by tiny-maple** [comment]
Yup I solved the puzzle, I could even describe how to solve it + screenshot of the solution if you like

**Comment by ReikaKalseki** [comment]
What NBT is on the core?

**Comment by tiny-maple** [comment]
Only have a color tag

**Comment by T5UN4M1** [comment]
I just experienced the same issue, solved the puzzle but the core doesn't drop.
I also solved that puzzle earlier and got the drop so it doesn't always bug.

I tried getting out of the structure and replaying all steps but that didn't work.

**Comment by tiny-maple** [comment]
Just want to check, was your biome structure field or was it something else? I managed to reproduce this bug multiple times, each time i exited the puzzle the biome was changed from structure field to plains.

**Comment by T5UN4M1** [comment]
I took a screenshot of each structure entrance and the biome was "structure field" for this one (before entering it, I don't know if it changed later).
Or perhaps you mean the biome for the room in which the dimensional core is located? In that case I don't have the information on what biome it was.
I will make sure to report any information if I find that structure again.
![2020-04-28_21 37 40](https://user-images.githubusercontent.com/12467635/80564200-77e56c00-89ed-11ea-8430-7e70f2aeeaed.png)

**Comment by tiny-maple** [comment]
Check out #2438, that was when I left the puzzle for the first time when I couldn't mine the dimension core. I don't know what triggers it, but seem like whenever I couldn't mine the dimension core, the biome was plains and spawning blitz everywhere. Odd part is, this only occur in structure fields and the far lands, I can never reproduce it in luminescent sanctuary or monument field.

**Comment by T5UN4M1** [comment]
I'm playing on peaceful so I don't know if it blitzs would have spawned. 
I sometimes noticed some chaotic worldgen as well.

I don't rush in unloaded chunks because from my experience it used to trigger crashes that reset the progression (I don't know if this has been fixed, it was from years ago, but I prefer to be safe than sorry)

**Comment by tiny-maple** [comment]
I've never had progression reset from racing into unloaded chucks, and that's the first time i heard of this issue. Do make a world backup if you want to try what I do. 

I started racing into unloaded chunks to check what was going on after taking a ride from lumen stream, and at the end of the journey, the biome in the far lands cannot be loaded and would be displaying plains. This require me to exit and re-enter to reload the game to access far lands. Also due to how fast jetpack with gas turbine upgrade is, i always fly into unloaded chunks.

**Comment by ReikaKalseki** [comment]
> Only have a color tag

It should *always* have far more than that.

**Comment by Schadrach** [comment]
Just going to add that I got the same thing just now.  Filter puzzle, solved it, core won't let me mine it.  Definitely in a structure field biome, AFAICT the entire interior of the puzzle was.  Solved the puzzle legitimately, though I did have to go AFK in the middle for a good while, in case there's a time limit.

**Comment by ReikaKalseki** [comment]
There is not.

**Comment by ReikaKalseki** [comment]
Some people reported this recently; the issue was in #2677.
