### ISSUE TITLE
LuaBlock item parser Can't have spaces in between multipliers

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2444]
The fluid synthesizer OreDictionary entries take `"ore:oreCopper * 2"` as "recipe needs the OD entry for `oreCopper * 2`" not "recipe needs 2x `oreCopper` ".

**Comment by voidsong-dragonfly** [comment]
This also happens with standard item definitions, I cannot make it consume 6x gunpowder or whatever I want, it looks for `minecraft:gunpowder  * 6`

**Comment by ReikaKalseki** [comment]
This is too much work for minimal benefit.
