### ISSUE TITLE
[Suggestion][Chromaticraft] Make aura jet change their color when placed on a rune.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2445]
![2020-04-24_14 51 35](https://user-images.githubusercontent.com/62176592/80183417-62fa8880-863b-11ea-82b2-47a031336827.png)
Currently aura jet color does not change when placed on a rune. Is it possible to make it such that it display yellow when placed on a Kitrino rune?

**Comment by ReikaKalseki** [comment]
Done.
