### ISSUE TITLE
[Chromaticraft] Aura jet crash when place on flowing water block.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2446]
![2020-04-25_03 09 40](https://user-images.githubusercontent.com/62176592/80248309-3d549a00-86a2-11ea-853f-9aaa2f46d1fb.png)
If you take a aura jet and try to place it on flowing water, you'll crash immediately.
Crash log: https://pastebin.com/R71ttAf8
DragonAPI 25c
Chromaticraft 25b

**Comment by ReikaKalseki** [comment]
Fixed.
