### ISSUE TITLE
[Chromaticraft/AppliedEnergistics?] Linker in spatial cell dimension think it's in the overworld

### ISSUE THREAD

**Issue by ninjanomnom** [ReikaKalseki/Reika_Mods_Issues#2447]
~~This might be a more generic problem and not associated with applied energistics in particular but when I went to link a warp window that was inside a spatial cell the linker shows that the target is in dimension 0~~

~~This means things inside a spatial cell can't be linked to anything.~~

Nope nevermind it can link within just fine. It does display the coordinate in the tooltip as being in dimension 0 though so this is just a ui bug. Not sure if you intended these to be used cross dimension.

**Comment by ReikaKalseki** [comment]
This should be fixed.
