### ISSUE TITLE
[CC] Tile Accelerator doesn't work Properly on Waste Drums

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#2448]
I tested it with a full drum of Krypton-85 (~10 years half life)
accelerated with 6x 256 accelerator. As far as i know the accelerators work multiplicative so 256^6xspeed. In all version since v7 Krypton disappeared really fast (~2 seconds). If this wouldn't be the case, the accelerator where nearly useless for the waste drums and even not worth the materials + power to maintain.

10 years x 6 month x 8 days = 480 minecraft days would it take fo an unaccelerated drum to cut one stack to 8. Even if the Accelerator works ADDITIVE and not multiplicative it would take only 480 / (256*6) = 0,3 minecraft days to decay. 

there isn't decayed one single Krypton in over 30 minutes (1,5 minecraft days) which is five times of the calculated Half time.

**Comment by ReikaKalseki** [comment]
`accelerated with 6x 256 accelerator. As far as i know the accelerators work multiplicative so 256^6xspeed.` Not true at all.

**Comment by Kobra331** [comment]
ok, but even additive is it too slow. i tested another one. this time 40 minutes. not a single decay process.

**Comment by Kobra331** [comment]
> 
> 
> `accelerated with 6x 256 accelerator. As far as i know the accelerators work multiplicative so 256^6xspeed.` Not true at all.

Here you mentioned that it doesn't scale linearly but Exponentially: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=22092

**Comment by ReikaKalseki** [comment]
That comment was *five years* ago.

**Comment by Kobra331** [comment]
Does that matter? It never Changed until V25. I used them in all versions to decay my waste. Its the only way to handle large amounts like from a breeder reactor or Thorium Reactor without using a trash can or something similar.

**Comment by Kobra331** [comment]
I did some testing and it seems that in v23 the Accelerator works properly on the waste drums. In v24 not, but in the Changelog for v24 isn't any change for the Accelerator. So maybe some strange interactions?

**Comment by VersedXth** [comment]
it still doesnt work on the newest version v29a. Do you still work on it ?

**Comment by ReikaKalseki** [comment]
This was not bugged, it was just balanced poorly.

**Comment by VersedXth** [comment]
Balanced poorly ? I thought this was on purpose since waiting millions of Minecraft years isn't feasible for the long living waste.
Adding the effect of more accelerator and not multiplying them does nothing on this long time spans. I mean yes it isn't really realistic but Chromaticraft is a Magic Mod.

**Comment by ReikaKalseki** [comment]
You are misunderstanding - it was balanced poorly in that the accelerators were making no meaningful difference.

**Comment by VersedXth** [comment]
oh? Does this mean you rework them to let them also be useful for waste ?

**Comment by ReikaKalseki** [comment]
Yes.
