### ISSUE TITLE
server Crash when connecting mekanism fluid pipe to neutron absorber

### ISSUE THREAD

**Issue by Saereth** [ReikaKalseki/Reika_Mods_Issues#245]
accidentally connected a mek fluid pipe to a neutron absorber, server crashed.

http://pastebin.com/mCJZpNzG

Not sure if this is a mek issue or reactorcraft issue, let me know if I need to head over to the Mek github

**Comment by ReikaKalseki** [comment]
Mekanism, specifically some network logic error.
