### ISSUE TITLE
[DragonAPI/Chromaticraft] Render issues + crash

### ISSUE THREAD

**Issue by nnystyxx** [ReikaKalseki/Reika_Mods_Issues#2450]
When I enter any world with DragonAPI v25c installed, the screen starts black (similar to other issues) and can be fixed by resizing the window. The **actual** issue is that with Chromaticraft v25b, at seemingly random points during gameplay, my graphics drivers crash and the game closes without anything special appearing in the output log. (I can tell it's a graphics driver crash due to the screen turning gray or glitchy, then recovering, followed by the game closing.)

I previously had this issue in a custom modpack, so I made a pack with only DragonAPI and Chromaticraft. The crash seems like it MIGHT be tied to proximity to pylons, but seems inconsistent. Thus far I haven't gotten a crash on DragonAPI alone but I will provide an update if I do. Game output log coming shortly; I couldn't use previous logs because they were spammed with GL ERROR.

**SPECIFICATIONS**
Minecraft: 1.7.10 
Chromaticraft: v25b
DragonAPI: v25c
Forge: 10.13.4.1614
RAM Allocation: 8G
Graphics Card: NVidia GTX 980
Drivers: Up to date

**CRASHLOG**
https://pastebin.com/ZNQcjy9y

As said, I have no clear crash error presented- it's not really a Minecraft crash itself. This most recent one occurred about when I got close enough to a pylon to see the runes' color, nowhere near its damage zone. Other times I've been right inside a pylon without a crash.

I have not had this crash before on this hardware setup; I definitely used an earlier version of these mods without either the black screen or the crash issue. I think they're related somehow.

**Comment by ReikaKalseki** [comment]
@OvermindDL1 Why would the pylon shader selectively crash him? It is just basic vecmath.

**Comment by nnystyxx** [comment]
Worth noting I think I have also crashed while being unable to even see a pylon.

**Comment by OvermindDL1** [comment]
From a cursory look over your code a few times I don't see an issue there but I've not tested super close.  However that kind of issue described is impossible in well made drivers, so even if your code did cause an issue it wouldn't cause that kind of failure, so I'm overwhelmingly leaning to that being a bad GPU driver, and with it being an Nvidia thing with their notoriously bad driver quality then I'm leaning even more to a driver issue.

**Comment by nnystyxx** [comment]
Not long after I posted this issue (same day? day after?) it stopped happening. I'm not sure what to credit to, possibly the full driver refresh.
