### ISSUE TITLE
[ChromatiCraft] Cannot mine using ore-finding pickaxe when energy is above 0.00%

### ISSUE THREAD

**Issue by FalsePattern** [ReikaKalseki/Reika_Mods_Issues#2452]
Once a block has been mined using the ore-finding pickaxe and it gains energy, it cannot mine another block until the energy decreases to 0.00%. It starts mining the block, but in the next tick the mining progress is reset to 0.
Also, when trying to use the scan-pulse by holding right-click, the item flickers between the idle and charging positions (only when the energy is > 0).

My guess is that every time the energy is decremented, the item in the inventory is updated, which Minecraft detects as switching items (the pickaxe's name is also shown above the hotbar while it's unusable, just like when switching between hotbar items).

DragonAPI version: 25c
CC version: 25b
Also tested with no other mods added, the same thing happens.

**Comment by ReikaKalseki** [comment]
Your guess is in fact correct. I am not sure how to fix this.

**Comment by FalsePattern** [comment]
my suggestion is that instead of storing rapidly changing values (for example, energy) in the item's data, store a unique id in that item and put the values in a save-specific global container, where the value can be accessed using the item's uid (a global hashmap is a simple but slow solution).

**Comment by ReikaKalseki** [comment]
That adds a ton of overhead, complexity, and points of failure. I would much rather just break the "count as new tool" detection for this item and/or disable discharge while actively mining with it, but neither of those are easy.

**Comment by ReikaKalseki** [comment]
Hopefully fixed; charge will no longer drop during active mining.
