### ISSUE TITLE
[ReactorCraft] Flashing models when steam is in the air

### ISSUE THREAD

**Issue by leonbaronick** [ReikaKalseki/Reika_Mods_Issues#2453]
[Demonstration](https://youtu.be/EFhh5fKgFjE)

The video shows the turbine and the turbine generator rendering weirdly.

I tested some more after recording the video and noticed that when I place a steam scrubber over the steam ouput on the turbine generator, it takes some time until the models render normally. Possibly until the remaining steam in the air has reached a certain height.

I'm playing on the latest version of the mod. It's a modpack based on FTB Infinity Evolved, so if it's not reproducible on it's own, I'll try to figure out which mod it is.

Like I said, the weird rendering can be solved by not letting steam escape, so this issue doesn't have a large priority, but I wanted to let you know nonetheless.

**Comment by Kobra331** [comment]
This is caused by too much block updates and unfixable. Just put a Steam Scrubber on Top or use high pressure turbines.

**Comment by leonbaronick** [comment]
Well that's the next issue I was going to open, as HP turbines don't work in the latest version.

But is it really impossible to fix or just not worth the effort?

**Comment by Kobra331** [comment]
the flashing models are a vanilla bug afaik.

the High pressure turbines doesnÄt work with some reactor types. Pebble bed reactors shouldn't work(intentionally), Plutonium / uranium doesn't work through a bug. Breeder and Thorium works fine. Fusion and Solar Tower i don't know. Fusion reactors should Power them but afaik there is another bug which pretends the generation of steam. Im unsure if this is already fixed.

**Comment by leonbaronick** [comment]
That's the first time I hear about only certain reactors powering the high-pressure turbine. Are you sure about this?

**Comment by ReikaKalseki** [comment]
#2098
