### ISSUE TITLE
[ReactorCraft] High-Pressure Turbine not working

### ISSUE THREAD

**Issue by leonbaronick** [ReikaKalseki/Reika_Mods_Issues#2455]
I've built all stages of the turbine, it is supplied and filled with lubricant and the attached steam line is filled with a large amount of steam and constantly supplied with steam from a reactor.

The turbine just doesn't do anything, it just sits there. When I enable the debug mode however, the turbine starts spinning. Disable it, and the turbine decelerates.

I don't know if I don't understand something important about the high-pressure turbine. If this turns out that this is a user error, it would be great if the information I was missing could be added to the in-game handbook.

**Comment by leonbaronick** [comment]
[Some images to show my setup](https://imgur.com/a/18bphFi)

4th image is with debug mode on, and 5th image shows it spinning back down when debug mode is off (water particles are missing, so it's not running).

**Comment by MalTeeez** [comment]
Duplicate of #2372, #2432

**Comment by leonbaronick** [comment]
Sorry, didn't find that issue as it was already closed.
