### ISSUE TITLE
[Voidmonster] Whitelist config option seems to disable the voidmonster entirely

### ISSUE THREAD

**Issue by ninjanomnom** [ReikaKalseki/Reika_Mods_Issues#2456]
Since we're using a few different mods that have void-like dimensions which really shouldn't spawn it (like space in advanced rocketry or generated rftools void dimensions) I switched the dimension config to whitelist. Before changing the config, the void monster spawned just fine but it seems to be completely disabled after switching to whitelist even in dimensions it supposedly can't be disabled like the overworld.

Dimensions added to the list don't generate the void monster either.

**Comment by ReikaKalseki** [comment]
Fixed.
