### ISSUE TITLE
[Chromaticraft][Suggestion] Possible to change Focus crystal ray beam colors?

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2457]
![2020-04-29_02 13 44](https://user-images.githubusercontent.com/62176592/80522526-4ce42380-89bf-11ea-9ff7-bf2245480357.png)
Here is a ring of Focus crystal, which emit a ray of white light. Wouldn't it make sense to see:
Flawed focus crystal: Green ray beam
Focus crystal: dark red ray beam
Refined focus crystal: Pink ray beam
Exquisite focus crystal: Blue ray beam
Turbocharged exquisite focus crystal: Intense Purple ray beam.

**Comment by ReikaKalseki** [comment]
No, the colors would look bad in a casting context.
