### ISSUE TITLE
[Chromaticraft] It is possible to remove the original water source in the waterlogged puzzle

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2458]
In the waterlogged puzzle, it is possible to break the glass surrounding the original water source and destroy the water source. I tried this a couple of times and had to bring buckets of water to make a water generator to solve the puzzle. Seem like the puzzle only cared as long as it is a water block. Did this in a survival world with no cheat.
Chromaticraft v25b
DragonAPI v25c

**Comment by tiny-maple** [comment]
I mined it with the bedrock pickaxe

**Comment by ReikaKalseki** [comment]
Fixed.
