### ISSUE TITLE
ExpandedRedstone-v25b NEI dependency crash

### ISSUE THREAD

**Issue by ChrisJStone** [ReikaKalseki/Reika_Mods_Issues#2459]
This is the same issue as reported in #2394. I am using forge 10.13.4.1614 with MULTIMC as my launcher. As stated in the above mentioned issue the resolution is the same. Here is my crash log as requested. [https://pastebin.com/tVcsvZfT](url)

Might I humbly suggest adding NEI as a dependency on the CURSE download page for ExpandedRedstone.

**Comment by ChrisJStone** [comment]
Here is the working link for the crash report. Forgive the double post. [Crash-Report](https://pastebin.com/tVcsvZfT)

**Comment by ninjanomnom** [comment]
This is the same version as the issue you linked and has already been fixed

**Comment by ChrisJStone** [comment]
> 
> 
> This is the same version as the issue you linked and has already been fixed

Considering I experienced the exact same issue with the current version of DragonAPI, ExpandedRedstone and the latest version of Forge I would disagree with that @ninjanomnom. Granted it could possibly be a dependency with CodechikenCore or CodechickenLib still the fact remains, if NEI CodeChickenCore and CodeChickenLib are not present the game crashes. With them present it does not. IE The Error is able to be duplicated.

**Comment by ReikaKalseki** [comment]
This *is* already fixed. Whether that fix is in a public version is another matter.
