### ISSUE TITLE
Reactorcraft Magnetic pipes failing on server restart

### ISSUE THREAD

**Issue by Saereth** [ReikaKalseki/Reika_Mods_Issues#246]
Each time we restart the server the pipes inside the plasma injectors melt, every time. We've tried multiple setups with different van de graff positioning and nothing has seemed to help. I took a few screen shots so you can see our setup in case we're doing something wrong.

http://imgur.com/a/x7eJv

the entire area is chunkloaded but it almost seems as if the pipes are loading before the van de graff is fully loaded/ticking.

**Comment by ReikaKalseki** [comment]
Is the NBT data getting lost?

**Comment by Saereth** [comment]
I will check this today and get back with you

**Comment by Saereth** [comment]
The nbt data is saving fine, and upon further testing this seems to be an issue with rftools, we are not experiencing this issue in the overworld with an identical setup. Letting you know in case it crops up again with rftools but it doesnt seem to be on your end.
