### ISSUE TITLE
[CrC] Elemental Lamp doesn't block Death Flower spawns

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2463]
Hardcore Ender Expansion's Death Flower rapidly spawns angry endermen after it decays enough. These still spawn in the Lamp's radius.
![2020-04-29_17 37 49](https://user-images.githubusercontent.com/6917535/80660520-c3753580-8a40-11ea-9967-8bf363e0e2f4.png)

**Comment by ReikaKalseki** [comment]
It must be spawning them directly via something like TileEntity tick; the lamp does not prevent spawners, and this is no different.
