### ISSUE TITLE
Chromaticraft v25b - Pylon permadeath

### ISSUE THREAD

**Issue by Zebralear** [ReikaKalseki/Reika_Mods_Issues#2464]
If a player is killed by a pylon discharge in a dedicated server, they are not given a respawn screen, their hearts are removed and they can’t die from damage. The armor bar sits in the place where the hearts would normally be, and they only gain the space for hearts again of they enter the nether, but the hearts are empty and vanish if the player leaves the nether or relogs.

The only way to solve this problem is to delete their playerdata file which means resetting their ChC progress, and progress in quite a few other mods.

This does not happen on single player or on LAN games, only on dedicated servers.

**Comment by ReikaKalseki** [comment]
I know this is not the case natively, as it has not been a problem on my server, despite *numerous* pylon deaths of others. This has to be another mod.
