### ISSUE TITLE
Bedrock Scythe - thaumcraft manabeans interaction

### ISSUE THREAD

**Issue by LoGaL1000** [ReikaKalseki/Reika_Mods_Issues#2465]
I attempted to chop Mana beans with the bedrock scythe

When i chop mana beans of different types, it only drops the mana bean type i am using the scythe on.

E.g. i have 10 ordo and 10 fire mana beans,

I left click my scythe on a ordo mana bean --> i drop 20 ordo mana bean

I left click my scythe on a fire mana bean--> i drop 20 fire mana bean

The planted beans instead preserve the correct type

Using the latest version, playing on a server

**Comment by ReikaKalseki** [comment]
Given the beans are TileEntities, this is going to be complicated to fix.

**Comment by ReikaKalseki** [comment]
Never mind, typo.
