### ISSUE TITLE
[CrC] Suggestion: Alternate Transmutation Flame Mechanic

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2467]
Putting this here to have it properly written out clearly.

Also, whether this or the current smothering mechanic, put it in the Lexicon. Give the flame a second page.

The lower the average input value gets, the less each input item is worth. If input item drops below a given value, it is then worth nothing. This allows for things like using chroma berries or cobblestone, but attempting to use millions of cheap items to make valuable things will result in cobble being worth nothing, for example. 

Conversely, using valuable input items should give increased efficiency, incentivizing the player to use it how you want, i.e. by using equal value items. 

Efficiency should have a cap, and inefficiency is capped by dropping to zero, which prevents things spiraling out of control either way.

**Comment by ReikaKalseki** [comment]
Done.
