### ISSUE TITLE
[Chromaticraft] Missing component information on Enriched Lumen Tree

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2471]
![2020-05-01_15 55 29](https://user-images.githubusercontent.com/62176592/80791469-52f72180-8bc4-11ea-914c-d0b53f991f8c.png)
I'm assuming it is suppose to be lumen essence because from the photo look exactly like those I found in radiant fissures.

**Comment by ReikaKalseki** [comment]
What do you mean "component information"?

**Comment by tiny-maple** [comment]
The text box is blank when I hover my pointer over the liquid icon shown in the image above. I'm only missing Glowing Towers and Energy Interconnection progression, with a lexicon entry of 284/287. Are these two progress related to the missing text box?

**Comment by ReikaKalseki** [comment]
No, that item is just missing locale data for the item itself. Given that it is rendering a fluid block, that makes sense. It should be rendering the bucket.
