### ISSUE TITLE
[Chromaticraft] Fabricator can't dump fluid into Rotarycraft Reservior.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2472]
![2020-05-01_16 00 54](https://user-images.githubusercontent.com/62176592/80791733-1ed03080-8bc5-11ea-8be3-6e9f8c130f39.png)

![2020-05-01_16 01 37](https://user-images.githubusercontent.com/62176592/80791706-0c55f700-8bc5-11ea-9a64-bfad7e9f63f5.png)

![2020-05-01_16 00 50](https://user-images.githubusercontent.com/62176592/80791762-36a7b480-8bc5-11ea-91fe-cc9f6b09c7ef.png)

![2020-05-01_16 04 07](https://user-images.githubusercontent.com/62176592/80791817-6951ad00-8bc5-11ea-9d95-c3cb065804ab.png)

Fabricator can push fluid automatically into extra utilities drums but cannot push fluid into reservoir? I tried placing a rotarycraft pipe but it doesn't want to connect to the fabricator.

**Comment by ReikaKalseki** [comment]
The reservoir probably cannot accept fluids from above.

**Comment by tiny-maple** [comment]
Would be nice to store fluid pushed out from fabricators using Reservoir than drums, as Reservoirs are expandable as a multiblock structure. A temporary workaround is I dump it into the drum and pipe it out to a Crystal tank.

**Comment by ReikaKalseki** [comment]
I am not willing to change the fluid rules on the reservoirs, nor to make the fabricator ignore fluid access rules.
