### ISSUE TITLE
Friction Heater Recipe Page Does Not Display All Recipes For An Item When R Is Pressed

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2473]
If I press "R", I get this:
![2020-05-01_12 18 47](https://user-images.githubusercontent.com/40431605/80821132-2f24e300-8ba6-11ea-9cfd-7ca0b192cb36.png)
If I go and look at all the recipes, both show:
![2020-05-01_12 18 52](https://user-images.githubusercontent.com/40431605/80821149-38ae4b00-8ba6-11ea-8697-902f34e10721.png)
![2020-05-01_12 18 57](https://user-images.githubusercontent.com/40431605/80821151-39df7800-8ba6-11ea-9955-db0e94bdb082.png)

**Comment by ReikaKalseki** [comment]
Fixed.
