### ISSUE TITLE
[Chromaticraft] Pylon compass "status" display out of sync

### ISSUE THREAD

**Issue by fruitistasty** [ReikaKalseki/Reika_Mods_Issues#2474]
![2020-05-01_20 57 19](https://user-images.githubusercontent.com/63002043/80833510-f65d2c00-8bee-11ea-87ca-d3d39ee53e68.png)
![2020-05-01_20 17 17](https://user-images.githubusercontent.com/63002043/80833558-15f45480-8bef-11ea-89ea-49336b4fdf33.png)
Replacing one of the crystals of the pylon results in the pylon recognising them again. After replacing a crystal, the pylon still wont recongnise 2 power crystals when coming back from another dimension.

**Comment by fruitistasty** [comment]
EDIT: Turbocharging works so i guess is only a visual bug with the compass.

**Comment by ReikaKalseki** [comment]
This is a known issue that has eluded years of attempted fixes.

**Comment by ReikaKalseki** [comment]
Turns out it is already reported here. #1667
