### ISSUE TITLE
DragonAPI and Galactricraft crash when loading a world second time

### ISSUE THREAD

**Issue by LighttronPrime** [ReikaKalseki/Reika_Mods_Issues#2475]
This is a the same problem as my previous issue  #2413 , but put together in a more useful way so it can hopefully be fixed.
This crash can be replicated using Dragon API V25C, and the latest versions of GalactricraftCore, GalactricraftMars, and MicdoodleCore.
The first time a world is loaded with these installations, everything works fine. The second time, and all subsequent times, the game immediately crashes upon trying to load the world. Using only these installations, rather than my full modpack like the previous issue, produces a crash and crash report rather than an illogical server timeout error.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 5/1/20 2:58 PM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 1
	at Reika.DragonAPI.Auxiliary.Trackers.VersionTransitionTracker.loadCacheAndUpdate(VersionTransitionTracker.java:52)
	at Reika.DragonAPI.Auxiliary.Trackers.VersionTransitionTracker.onWorldLoad(VersionTransitionTracker.java:38)
	at Reika.DragonAPI.Auxiliary.DragonAPIEventWatcher.checkModChanges(DragonAPIEventWatcher.java:143)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_21_DragonAPIEventWatcher_checkModChanges_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1164086536 bytes (1110 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAAAAA	DragonAPI{v25c} [DragonAPI] (DragonAPI+1.7.10+V25c.jar) 
	UCHIJAAAAAAA	ChromatiCraft{v25b} [ChromatiCraft] (ChromatiCraft+1.7.10+V25b (1).jar) 
	UCHIJAAAAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.504.jar) 
	UCHIJAAAAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.504.jar) 
	UCHIJAAAAAAA	RotaryCraft{v25b} [RotaryCraft] (RotaryCraft+1.7.10+V25b.jar) 
	UCHIJAAAAAAA	ReactorCraft{v25b} [ReactorCraft] (ReactorCraft+1.7.10+V25b.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

Hopefully, there is some way to resolve this issue, which is likely caused by Galacticraft being written for an outdated forge version.

**Comment by ChrisJStone** [comment]
@LighttronPrime Take a look at #2397 I've run into the same issue myself. Editing the modversions.list and removing the entry for mcidoodlecore resolves the issue so I can reload the world a second time. As @ReikaKalseki stated in the above mentioned issue it has been fixed however the fix is still unreleased on curse.

**Comment by LighttronPrime** [comment]
Thanks, I looked in the open issues before posting this but didn't think to check the closed ones.
