### ISSUE TITLE
[Chromaticraft] accelerator do not stack

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2477]
![2020-05-02_16 18 19](https://user-images.githubusercontent.com/62176592/80859147-ef86f580-8c90-11ea-81e1-8a058a0ee0c9.png)
Tile accelerators placed in the world do not stack with freshly crafted ones.

NBT tag on freshly crafted:
1 entries
`Tier7`

placed in world and removed
2 entries
`energy: 0 entries`
`Tier 7`

seems to be affecting all type of accelerators. I seen this on growth as well.

**Comment by ReikaKalseki** [comment]
They keep their energy when broken. This will break stacking.
