### ISSUE TITLE
[Chromaticraft] Rendering error on amplified relay source?

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2478]
![2020-05-02_16 16 41](https://user-images.githubusercontent.com/62176592/80859208-66bc8980-8c91-11ea-8789-8bc0c87ba69f.png)

![2020-05-02_16 16 52](https://user-images.githubusercontent.com/62176592/80859210-69b77a00-8c91-11ea-852c-e5028e8eb3c2.png)

![2020-04-22_19 33 18](https://user-images.githubusercontent.com/62176592/80859250-bb600480-8c91-11ea-937a-012d598a5e2d.png)

1) Every so often the amplified relay source would have it's rendering disappear. I usually have to break the relay source and put it back to get the energy shielding around it appear back.
2) the particles would also render as shiny pickaxe from COFH? Hilarious rendering tho

**Comment by ReikaKalseki** [comment]
The halo disappearing is desync, with the client data losing the "enhanced" status. As for the particles, I have never seen that, but it is almost certainly something wrong with the MC texture stitching.
