### ISSUE TITLE
NPE probing casting table with examination crystals

### ISSUE THREAD

**Issue by HellsingDarge** [ReikaKalseki/Reika_Mods_Issues#2480]
Be it just casting table or one in a casting room structure
Happens in singleplayer

[Crashlog](https://paste.ee/p/8ud0d)

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by HellsingDarge** [comment]
Upon further testing, the crash happens if casting table is tier 0 (can't be used in casting room structure) otherwise, examination crystals work fine
