### ISSUE TITLE
[CrC] Voidlinked Bucket & Chroma Collector not cooperating

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2481]
A: Voidlinked Bucket cannot place remotely into a linked tank when right-clicking on a Chroma Collector. Just, nothing happens.
B: When remotely placing from a linked Chroma Collector, it ignores the block being placed into and places it in the world instead, on the side of the tank, instead of into it. Tested with Buildcraft tanks so far.
C: How to clear linked tanks? Even breaking the tanks in-world didn't remove them.

**Comment by ReikaKalseki** [comment]
The bucket was never designed to take fluids out of or put fluids into tanks, only world interactions.

C)....I might have overlooked that.

**Comment by Shahelion** [comment]
Update: sometimes, tanks that have been broken ARE cleared from the UI. Haven't found a common cause yet. Maybe just have an X button next to each one or something.

**Comment by wamc2017** [comment]
Hmm, if you put the voidlinked bucket in a crafting grid you're able to clear all the linked tanks...

**Comment by ReikaKalseki** [comment]
So I did not forget it after all.

**Comment by Shahelion** [comment]
Right now, the only two options are to break the source in question, or clear every linked tank. There should be a way to remove sources individually without breaking them.

**Comment by ReikaKalseki** [comment]
The whole thing has more serious issues than that, and any rewrites would probably solve those.

**Comment by ReikaKalseki** [comment]
I am working on redoing it now, and I might end up adding tank interactions as well.

**Comment by ReikaKalseki** [comment]
OK, it has been done.
