### ISSUE TITLE
[Chromaticraft] Pylons generating in Aroma Mining Dimension

### ISSUE THREAD

**Issue by LoGaL1000** [ReikaKalseki/Reika_Mods_Issues#2482]
Hello,

In my current world, even though according to the config file it should not, Chromaticraft is generating pylons in the Aroma Mining Dimension (Non-Overworld), so my borer gets stuck quite often

**Comment by ReikaKalseki** [comment]
Then it either has a dimension ID of 0 - somehow - or thinks it is a MystCraft age: 


```
	public boolean canGenerateIn(World world) {
		if (ModList.MYSTCRAFT.isLoaded() && ReikaMystcraftHelper.isMystAge(world)) {
			return MystPages.Pages.PYLONS.existsInWorld(world);
		}
		if (world.getWorldInfo().getTerrainType() == WorldType.FLAT && !ChromaOptions.FLATGEN.getState())
			return false;
		if (world.provider.dimensionId == 0)
			return true;
		if (Math.abs(world.provider.dimensionId) == 1)
			return false;
		if (world.provider.isHellWorld || world.provider.hasNoSky)
			return false;
		if (world.provider.dimensionId == ExtraUtilsHandler.getInstance().darkID)
			return false;
		if (world.provider.dimensionId == TwilightForestHandler.getInstance().dimensionID)
			return false;
		return ChromaOptions.NONWORLDGEN.getState();
	}
```

**Comment by LoGaL1000** [comment]
According to the config of the mod (attached), the ID is 6. Those are config files, i changed extension to upload them. 
I don't have Mystcraft installed. Can RF Tools give problems? I don't think so but I am just writing it as well
[Aroma1997sDimension.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4589694/Aroma1997sDimension.txt)
[ChromatiCraft.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4589698/ChromatiCraft.txt)

**Comment by ReikaKalseki** [comment]
> Can RF Tools give problems?

No.

In which case this makes no sense.

**Comment by LoGaL1000** [comment]
In case you want to fix it, anything else I can provide you?

> In which case this makes no sense.

Those are the kind of things that make me hate programming. It would not surprise me to see pylons getting generated even with an explicit

if (world.provider.dimensionId == 6)
			return false;
:-)

**Comment by LoGaL1000** [comment]
![ShieldingCloak](https://user-images.githubusercontent.com/64597976/81294397-22edc980-906f-11ea-83fe-44b775a974e7.png)
Just to show you i am not imagining it

**Comment by wamc2017** [comment]
I can only guess, if you found that underground, then that's a crystal shrine, not a pylon (I think Shielding Cloak is not part of the pylon structure.)
Have you tried adding the dimension id to "Structure Dimension Blacklist" in the config?

**Comment by LoGaL1000** [comment]
Well, they usually contain a shiny core inside, called pylon xD. I didn't try chromaticraft yet.

> Have you tried adding the dimension id to "Structure Dimension Blacklist" in the config?

is it as easy as plugging the dimension id inside?

**Comment by wamc2017** [comment]
> is it as easy as plugging the dimension id inside?

Never tried it, but I guess it should work like this:

> I:"Structure Dimension Blacklist" <
>     6
>      >

**Comment by LoGaL1000** [comment]
Tested out in creative world with a bunch of gas turbines spam to run the borer and effectively it did not get stuck anymore --> no shieldcrap
I still think, however, that they should not spawn anyways, independently from the blacklist.

**Comment by ReikaKalseki** [comment]
You *explicitly* said that *pylons* were generating. Not other structures.
