### ISSUE TITLE
[CrC] Ender Essence becomes TiCon Liquified Ender if placed in any tank

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2483]
I know this has a chance of being the other mod's fault, but we know TiCon is never being updated for 1.7.10.

Also, I do not have Thermal Expansion in my mod pack, and won't be adding it, so no Resonant Ender in this equation.

The liquid ender essence from the Ender Forest pools works fine as long as only buckets are used to move it. However, the second it is placed inside a tank, it becomes the much less useful Tinkers Construct Liquified Ender, and I don't know if it can be changed back yet. So far, have tested Buildcraft tanks and TiCon seared tanks.

**Comment by Prunoideae** [comment]
This is also experienced on my previous world. A possible cause is that the fluid names were conflicted when Reika tried to register the fluid, much likely to be CC "ender" and TiC "ender", where both fluid block was registered, but reservoir doesn't know which ender to be put in tank, so then the bug happened.

**Comment by Shahelion** [comment]
After some further investigation, I can't even find a fluid ID in the NEI fluid dump, which is weird because it clearly exists in the game.

**Comment by ReikaKalseki** [comment]
This is what happens when multiple mods all add a fluid with the same ID, and then they all add their own bucket place/bucket pickup/tank fill handling.

**Comment by Shahelion** [comment]
Is it not possible to change at least CC's ender fluid ID or something?

**Comment by ReikaKalseki** [comment]
Not without breaking TE compat *and* worlds.

**Comment by Shahelion** [comment]
I will test to see if other tanks work the same, if not I might be limited to one bucket at a time.
