### ISSUE TITLE
Crash with Thaumic Horizons Liquefaction Focus

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2485]
https://pastebin.com/Jz63JU1N

The focus smelts blocks that it is directed at. I had upgraded it with increased AoE, and I believe it also hit some grass blocks.

**Comment by ReikaKalseki** [comment]
It hit some block with no item at all, and looked up the smelting recipe for null - not a null stack, but a stack *of* null. This is on his end.

**Comment by Shahelion** [comment]
Well, I guess that's not getting fixed. I can't find any sort of issue tracker for the mod, and the author might actually be permanently gone for one reason or another, supposedly...

Just have to be careful with the focus, I suppose.
