### ISSUE TITLE
[CrC] Tile Accelerator + Energized Node = Long Crash Report

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2486]
https://gist.github.com/Zsashas/81877cb636655e012ec707b355908eb1

It was placed next to the normal node without issue. The second the node became energized, however, it crashed. It was a 256x if that makes a difference.

**Comment by ReikaKalseki** [comment]
The accelerator has nothing to do with the crash; the node and the LP pipe are requesting data from each other in a loop.

**Comment by Shahelion** [comment]
There aren't any LP pipes involved, though...
None in the world at all, even.

**Comment by ReikaKalseki** [comment]
LP still has some sort of handler active.
