### ISSUE TITLE
1.7.10 isotope centrifuge and jet fuel maker not accepting hf6 / ethanol

### ISSUE THREAD

**Issue by helphelphelpplease** [ReikaKalseki/Reika_Mods_Issues#2487]
tried piping ethanol in jet fuel maker, no side worked, tried all 5

skippid it and cheated the jet fuel, now at isotope centrifuge. i have hf6 but it wont get piped in either from any of the 5 sides.
tried testing world, at firs the side worked, then it didnt. then the top worked but even at 5x needed spin it still didnt produce. so i went and made a clean profile with only rc and rec. still no hf6 input, even with normal rc pipes.

i am qwuite lost at this poit as to how i am supposed to play, when 2 vital machines dont work 🌵 

also btw, the heavy water extractor thingyhas no mentionion of needing to be in a ocean AND if i line up multiple with CHECKED water source and 16 above in an ocean it wont work, i need tro seperate them by a few blocks for some reason

anyhow i hope i can get some help here as i was literally unable to find these issues NAYWHERE. nobody seemed to have them

**Comment by helphelphelpplease** [comment]
just tried gas pipe for the centrifugal fluid whatevs, also dont work(going from the chical hf6 maker, full with the stuff

**Comment by helphelphelpplease** [comment]
also tried all kinds of other setups from the hf6 maker to the isotope centrifuge and nope, and i checked again, gas pipes are supposed to be used but dont work

**Comment by rkane31174** [comment]
Does the issue look similar to #2391 ?

I'm having a similar issue with the isotope centrifuge on my server, but the fractionation unit works fine for me. I'm not a mod or a dev, but I'll ask you a few questions that will probably help.

1: What versions of the mods are you using? Not the minecraft version, the mod version. For example: the latest version of ReactorCraft at the time of this posting is V25b.

2: Are you encountering this issue in single player or on a server? For me the isotope centrifuge works fine in single player, but not on my server.

3: Are you piping LIQUID ethanol into the fractionation unit? In the latest version of the mod, you have to melt ethanol crystals in the rock melter and pipe the resulting liquid into the side of the machine.

**Comment by ReikaKalseki** [comment]
I have a working fractionator *right now*, and noone else has any issues. I question whether you are trying to put in the wrong fluids and/or the wrong sides.

**Comment by Barhandar** [comment]
Are you _sure_ you're using RoC ethanol fluid (blue) and not Forestry's stupidly-renamed-from-biofuel ethanol fluid (orange)?

**Comment by ReikaKalseki** [comment]
That was my primary suspicion.

**Comment by helphelphelpplease** [comment]
alright hear me out, regarding the spinning things for uranium. me and a much more knowledgeable buddy tried literally EVERYTHING in our mod to try and get fluid into this thhing, including some chromaticraft fluid trafer stuff. nothing worked exept golems rightlciking with canisters. but BUT, it still does not work. if there is any help from me mentioning it: some varieties of pipe dDID get a sort of inflow, however if you looked from the tank back to the spinningthing you could see the number of fluid go down again, but there never even went any fluid into it, as the tank was still full, but it stillshowed some fuid for a little time.... it dunno man, really confusing.

regarding the fractioner we tried the same methods also to no avail...(yes we used normal ethanol, dont have the other mod)

**Comment by rkane31174** [comment]
I'm gonna ask some dumb questions about the fractionation unit, just to make sure we're not missing something simple.

1: Are you powering the fractionation unit?
It accepts power from the BOTTOM and has a required minimum POWER and SPEED. If you don't give it that, it won't work.

2: Are you filling it with all the solid materials it needs?
The machine requires:
-Netherrack Dust
-Tar Sand (ground soul sand)
-Blaze Powder
-Magma Cream
-Coal Dust (NOT pulverized coal!)
-Pink Dye

3: Is there a Ghast Tear in the machine?
The fractionation unit doesn't consume this item, but it does have to be there.

4: Are you piping the liquid ethanol into the SIDE of the machine?
If the machine accepts the ethanol then you're doing this correctly.

5: Are you using the latest version of the mod?

**Comment by tiny-maple** [comment]
Regarding your heavy water issue, have you checked the description of the centrifuge fluid extractor in the Reactorcraft handbook? It explicitly states how to install and operate that machine, as I have also just installed a second Centrifuge fluid extractor beside the first.

Could you follow rkane31174 checklist? You ignored the first list of information to provide.

**Comment by Skyler-Altol** [comment]
@helphelphelpplease the handbook explicitly states for the centrifugal extractor that it needs to be in an ocean. I can recall reading that line numerous times in previous versions.
