### ISSUE TITLE
Issues when parts of RailCraft are disabled

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2489]
#1: Railcraft allows disabling its own steel(and other ingots) in favor of those of other mods. When this is done, RotaryCraft crashes looking for the RailCraft steel ingot to recycle tools and armor into in the Pulse Jet, instead of just going to the `ingotSteel` on the top of the OreDictionary
#2: If you disable the RailCraft creosote bottle and the coke oven simultaneously, forcing RailCraft to try to register a coal->creosote bottle furnace recipe but not work,  DAPI does not let you join a world, instead kicking you out to the main menu and throwing this error in the log.
[fml-client-2.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4602701/fml-client-2.log)

**Comment by ReikaKalseki** [comment]
The first is fixed.

The second one is not on my end; the items involved in the recipe are invalid and throw NPEs on parse. I do not touch the function throwing the error:
        
    private boolean func_151397_a(ItemStack p_151397_1_, ItemStack p_151397_2_)
    {
        return p_151397_2_.getItem() == p_151397_1_.getItem() && (p_151397_2_.getItemDamage() == 32767 || p_151397_2_.getItemDamage() == p_151397_1_.getItemDamage());
    }
