### ISSUE TITLE
Repeater pathing erroneously prefers multi-aura repeaters.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#249]
Lumen path prefer routing prefers multi aura repeaters. The screenshot is just one of many weird routes i've observed with this setup.

Config is:
B:"Make Pylon pathfinding attempt shortest path - can be intensive"=true (default, unchanged)

 (Sandstone was placed after route was established so the left multi repeater was closer from the beginning and it still chose the right one.)

![crystalpathing](https://cloud.githubusercontent.com/assets/14168854/9830245/94e69ac8-5927-11e5-828d-7285ac0147f7.JPG)

**Comment by ReikaKalseki** [comment]
> Lumen path prefer routing prefers multi aura repeaters

This is untrue. Though sources have a given priority sorting, repeaters do not.

Also, "shortest" means the nearest repeater at every jump, not fewest total jumps (which would require trying every path and be incredibly intensive to calculate). And if it picked a repeater that was not closest - in pythagorean distance - then that repeater was either unavailable (i.e. inactive, LOS-blocked, etc) or was not a stepping stone to a valid source.

Also, looking at your image, the red-arrow connection is far too steep to allow LOS, and the lower repeater is visibly closer.

Finally, pathfinding works outwards from the receiver. All distance measurements are thus with that in mind.

**Comment by lossycrypt** [comment]
I was afraid that closest total path might be to expensive to calculate. Thanks for the info that routing works outbound from the reciever. It would be nice if you could include that info in the chromic lexicon. I measured that path and those are indeed the shortest paths, albeit only by 1 block on the last hop:<. I thought i saw them not always take the same path, but i guess that was an observational error.

The red arrow connection is infact an almost exact 45° angle and works just fine if the multi repeaters are unavailable. Tho this is difficult to judge on the screenshot due to high FOV.

**Comment by ReikaKalseki** [comment]
> It would be nice if you could include that info in the chromic lexicon.

I do not see it being very useful to most players, as it usually affects nothing. Also, since it is a result of implementation details, I do not see a good way to explain it without both breaking immersion and being rather technical for the lexicon.

**Comment by lossycrypt** [comment]
Maybe something like "When constructing these bear in mind that lumen - much like air - attempts to balance itself equally. Thus it is drawn towards the low-lumen-aura that forms around constructs which consume it. And it always takes the path of least resistance." Imho you're already having repeaters work as a kind of "magnet" to lumen lore wise or else it wouldn't make much sense that repeaters can draw it from pylons. But this is ofc already entierly unrelated to the original issue ;).

**Comment by ReikaKalseki** [comment]
> When constructing these bear in mind that lumen - much like air - attempts to balance itself equally.

That makes it sound like the exact opposite of the actual implementation.
