### ISSUE TITLE
Rotary Craft Download Issue

### ISSUE THREAD

**Issue by CTH999** [ReikaKalseki/Reika_Mods_Issues#2490]
ALright, technically not an issue with your mod, but, well, it is. I can't download and play with it for the simple, and stupid, reason of forge. I can't download minecraft forge 1.7.10, since it relies on an old version of java, one wich is un-findable. So, here's what I'm saying:

The issue is, I can't use the mod at all. 

But, hey, at least it can't cause any crashes or lag, eh?

If you need any more info, such as screenshots, just ask!

**Comment by wamc2017** [comment]
The latest forge version for 1.7.10  (10.13.4.16.14) runs fine with the latest Java 8 version ([Update 251](https://www.java.com/en/download/manual.jsp), which was released nearly a month ago)...

**Comment by ReikaKalseki** [comment]
And any other J8 version should work too.
