### ISSUE TITLE
Neutron Absorber not transferring energy

### ISSUE THREAD

**Issue by scrouthtv** [ReikaKalseki/Reika_Mods_Issues#2492]
Hello,

I am currently trying to set up ReactorCraft's Fusion Reactor. I think I have everything ready, there are neutrons going into the absorbers and I have Steam Boilers next to them:
![image](https://user-images.githubusercontent.com/23227405/81505651-22646580-92f1-11ea-8aa0-e0ee791291ff.png)
They are also connected to a water source:
![image](https://user-images.githubusercontent.com/23227405/81505662-33ad7200-92f1-11ea-9cd8-3eca60aaff10.png)
However, the heat in the Neutron Absorbers is not heating the Steam Boilers:
![gif10](https://user-images.githubusercontent.com/23227405/81505668-4758d880-92f1-11ea-9f99-aa7fd92672a3.gif)

What am I missing?
Thanks for the cool mods and for any help in advance :)

**Comment by ReikaKalseki** [comment]
#2414

**Comment by KassIsLegend** [comment]
if anyone end up fixing this let me know asap, putting yet ANOTHER build on hold because of a mod bug
