### ISSUE TITLE
[Chromaticraft] Area breaker is able silk touch farmland.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2493]
![2020-05-04_03 24 06](https://user-images.githubusercontent.com/62176592/81506936-4ee9a300-932c-11ea-9f6e-d61782fe89a6.png)
1) Using area breaker is possible to obtain farmland instead of dirt.
2) Using tile accelerator tier 7 + Area breaker would leave a lot of ghost blocks.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by tiny-maple** [comment]
What caused the blocks to ghost out?

**Comment by ReikaKalseki** [comment]
Desync.
