### ISSUE TITLE
[Chromaticraft] Ruined structures.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2494]
![2020-03-08_10 17 36](https://user-images.githubusercontent.com/62176592/81507056-1c8c7580-932d-11ea-8767-d8ec3b6979a1.png)
![2020-03-08_09 57 56](https://user-images.githubusercontent.com/62176592/81507097-83119380-932d-11ea-9d1d-d13628206608.png)

1) Found many of these kind of ruined structures caused by meteorites from AE2. Are there possibilities of world gen protection to protect chromaticraft structures against meteorites?
2) Second image seem to be desync rendering of pylon yet pylon structure seems ok after I checked it. I have encountered multiple pylons in such states.

**Comment by ReikaKalseki** [comment]
1) The structures *do* have protection code, but that fails if the controller is destroyed.

2) #1667, #2474
