### ISSUE TITLE
Dragon api V25c causing complete screen blackout

### ISSUE THREAD

**Issue by KassIsLegend** [ReikaKalseki/Reika_Mods_Issues#2495]
ive tried everything i possibly can, checked forge version, updated gpu drivers, went through a windows update, completely wiped and reinstalled minecraft along with all mods and still...nothing
dragon api is the only mod thats in my mods folder, i am not using optifine or any other shaders or texture packs, i even took those out of the folders too hoping itd do something but still nope, the really wierd thing is.... when i restart my pc and launch minecraft then try it, ITS FINE untill i close and then reopen minecraft. Closing wise as in quitting and saving to tittle screen and clicking quit from there. but as soon as i restart minecraft in ANY way, it just Nopes out again on me. from what i have looked up, this was an issue back in v24 but that was with optifine and im not using optifine what so ever. coming to conclusion here, i can see my hotbar and gui and all of that responds, i can hear when i walk i can hear all animals around me, the menus all work....pretty much all minecraft works I JUST CANT SEE THE WORLD i know im not just spawing in a cave, how is there caves in a superflat world... in the console it just spammms post render error.. like i get over 4k of those in not even 5 seconds someone please help me... ive tried everything i can think of...i dont know what to do...im stuck using really old versions of dragon api, reactor and rotary craft that i had laying around...but them in themselfs barely work....PLEASE HELP ME: 5/11/2020 Okay UPDATE...okay so now its working, when minecraft restarts it still breaks BUT, when i maximize the window BOOM theres everything 
![image](https://user-images.githubusercontent.com/65137073/81626078-89e0ea80-93af-11ea-9ed4-f771995bc13e.png)

heres the log file to it
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4612792/latest.log)

**Comment by ReikaKalseki** [comment]
#2315?

**Comment by KassIsLegend** [comment]
> #2315?

yeah like that the post render error part

**Comment by KassIsLegend** [comment]
if you want, i can throw v25c back into my mods and gather a log if youd like, anything to fix this

**Comment by ReikaKalseki** [comment]
That issue has a temporary fix.

**Comment by AbsoluteOmega** [comment]
i'm having the same problem, but changing the size of the game doesn't work. i've tried optiifine and other things but nothing works.
