### ISSUE TITLE
[Rotarycraft] Desync of Pulse jet furnance

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2496]
![2020-05-11_15 38 54](https://user-images.githubusercontent.com/62176592/81536763-a6285b80-939e-11ea-816e-100ac4195eb2.png)
![2020-05-11_15 39 35](https://user-images.githubusercontent.com/62176592/81536775-a9bbe280-939e-11ea-8251-ca01a4c36502.png)
Pulse jet furnace desync behavior will cause it to look like it has experienced a failure. However, a re-login to the world will show that it is still safe and nothing broken.
Singleplayer world
DragonAPI 25c
Rotarycraftb

**Comment by ReikaKalseki** [comment]
The recent changes to make its temperature code serverside only probably fixed this.
