### ISSUE TITLE
[Rotarycraft][Chromaticraft] Fluid pipe odd interaction with crystal tank.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2497]
![2020-05-12_04 00 36](https://user-images.githubusercontent.com/62176592/81606450-b58ebf80-9405-11ea-89b8-087a4717a0ea.png)
![2020-05-12_04 05 02](https://user-images.githubusercontent.com/62176592/81606491-c6d7cc00-9405-11ea-9b3a-94f66ccaafc6.png)
![2020-05-12_04 08 38](https://user-images.githubusercontent.com/62176592/81607749-c50f0800-9407-11ea-836e-ecceaa26e4dd.png)

1. Attempt to draw fluid out of a crystal tank from the bottom with liquid pipe would result in the pipe being replaced with a water source block. The same behavior is observed when placing a suction pipe to any part of the crystal tank multi block structure. 

~~2. Currently fluid pipe does not extract fluid when placed anywhere other than the bottom of the tank.~~
edit: Fluid pipe intended behavior is to extract fluid from top or bottom of any fluid container.

**Comment by Kobra331** [comment]
fluid pipes can just contain 64 Buckets. Try bedrock pipes or use tanks which can only contains a maximum of 64 Buckets (reservoirs).
Rotarycraft pipes extract Fluids from bottom and top and insert on the other sides.

**Comment by tiny-maple** [comment]
> Try bedrock pipes or use tanks which can only contains a maximum of 64 Buckets (reservoirs).

Yep, bedrock pipes work well with no issues, but its design capacity is too high for my need. Best alternative is to use reservoirs.

> Rotarycraft pipes extract Fluids from bottom and top and insert on the other sides.

I believe I may have misunderstood the intended placement of fluid pipe then. However they still break and get replaced with water source blocks when I attempt to connect via the top or bottom of the crystal tank.

**Comment by voidsong-dragonfly** [comment]
RotaryCraft pipes have pressures, and maximum pressures they can sustain. They will try to draw large amounts of fluid from the tank they're extracting from (I think it's half the tank's capacity per tick), and they will try to take the capacity fluid of the tank in total (90% certain on this). As such if you're trying to extract from something larger than a reservoir, you _need_ to have bedrock pipes extracting.

**Comment by tiny-maple** [comment]
There is no mention of max operational pressure for ordinary liquid pipe in the handbook as compared to bedrock pipe. As quote from the handbook on pipe

> A pipe can hold unlimited amount internally..

lead me to believe that over pressure failure mechanics was not idealized in RotaryCraft. Seem like it was intended to break, is it possible to add a note in the handbook about pipe over pressure failure?

**Comment by Kobra331** [comment]
Unlimited amount is only for steam lines and Bedrock pipes.

Every other Pipe breaks with more than 64 buckets inside.

this can be an issue on the Fractionation unit because they can easy break the fuel line with a full machine.

**Comment by ReikaKalseki** [comment]
And RC pipes, for non-RC blocks, can only pull from top and bottom and insert to the sides.
