### ISSUE TITLE
[Rotarycraft] Crash when Shift+LClicking a Shaft Distribution Clutch with a Screwdriver

### ISSUE THREAD

**Issue by Clinery1** [ReikaKalseki/Reika_Mods_Issues#2498]
## How this happened
I was building in creative when i placed a shaft distribution clutch, then wondering what Shift clicking it would do, I did it and the game immediately crashed with crash log 1.
## What happened after
I loaded the world back up then it crashed with log 2, I loaded it once more to check but the same result.

Glancing over the reports suggests the 2 are nearly the same. I included both Client and Server logs (integrated server).
[Crash logs](https://gist.github.com/Clinery1/9eb80221b46a3c47bd584373a8db249d)

**Comment by rehashedsalt** [comment]
+1. Providing [dedi server crash report](https://gist.github.com/rehashedsalt/1175aad24c7c536003c781e8ef31d053) and [world backup](https://www.9iron.club/files/rotary-main-2020-06-11T02:00:01-05:00-world.tar.gz), still affects v26b.

My player told me he never shift-clicked it with a screwdriver, though. He said he plonked it down, realized he didn't need it, picked it up, and stuffed it in a chest. Server went down afterward while nobody was on. He may very well be full of shit though.

**E**: Oh, and the environment is Ubuntu 18.04, OpenJDK 1.8.0_252. All packages up-to-date.

**Comment by ReikaKalseki** [comment]
That error has nothing to do with the original report; why did you add it here?

**Comment by ReikaKalseki** [comment]
Fixed.
