### ISSUE TITLE
neutron absorbers heating but steam boilers are not

### ISSUE THREAD

**Issue by KassIsLegend** [ReikaKalseki/Reika_Mods_Issues#2499]
build a fusion reactor, set up this little tester based off of what people do in their videos all of the time, but...not much is happening, am i missing something? dont think i am
![2020-05-12_20 12 45](https://user-images.githubusercontent.com/65137073/81767611-af442600-948d-11ea-8b1d-b9f9477eae6e.png)
![2020-05-12_20 12 34](https://user-images.githubusercontent.com/65137073/81767621-b834f780-948d-11ea-8b9d-d54d464f4ca7.png)
![2020-05-12_20 12 56](https://user-images.githubusercontent.com/65137073/81767640-c256f600-948d-11ea-8730-99b74c5359d7.png)

**Comment by ReikaKalseki** [comment]
#2414 #2492

**Comment by KassIsLegend** [comment]
seriously thats how youre gonna respond?? im still having the issue like wtf man

**Comment by KassIsLegend** [comment]
so like what am i supposed to do, just get told to practically fuck myself and deal with it?
really  professional

**Comment by MalTeeez** [comment]
Dude, chill just wait for the new version or downgrade
