### ISSUE TITLE
"Out of Date" mods is annoying

### ISSUE THREAD

**Issue by daladian** [ReikaKalseki/Reika_Mods_Issues#25]
see title

**Comment by madolinn** [comment]
[See rules for posting.](https://github.com/ReikaKalseki/Reika_Mods_Issues/blob/master/CONTRIBUTING.md)

```
For all issues: Make sure you are using the latest version! If you are using an old modpack, your version is very likely old and you need to update.
```

Oh that's weird. Wouldn't have that issue if you followed the rules.

**Comment by zemerick** [comment]
This also isn't an issue. It's a policy disagreement.

You can head over to:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=998
to state your opinion. It probably won't change anything though. You aren't exactly the first to complain, and it being annoying was the intent. ( To strongly encourage updating. )

**Comment by daladian** [comment]
Maybe I don't want to update? Who are you to tell me how to play?

**Comment by zemerick** [comment]
We're not saying you HAVE to update. You do however have to live with the consequences, and it also means you will not receive support.

I personally just barely updated to v6 yesterday.

If you're not too far out of date, you can disable the message.

**Comment by daladian** [comment]
How do I disable the stupid message?

**Comment by Kolatra** [comment]
Not an issue, if you want to talk about it, bring it up on the thread.

**Comment by ReikaKalseki** [comment]
Followed by banned. :P
