### ISSUE TITLE
user error do not bother

### ISSUE THREAD

**Issue by pajrle** [ReikaKalseki/Reika_Mods_Issues#2500]
I am trying to make obtaining different materials behind certain power in rotarycraft by removing furnace recipes with minetweaker and adding friction heater recipes. NEI shows recipes different than I set in config file and crashes after displaying them few times. I used /mt hand command to get item IDS. I tried to replicate it with only nei and rotarycarft and it works fine. I tried to remove recipes that contain rotarycraft ingots as output and it still crashes. I tried replicate issue without botania and it did not crash, but recipe for draconic flakes still got messed up.

![Screenshot from 2020-05-14 11-08-29](https://user-images.githubusercontent.com/56485090/81917004-e96c0f80-95d4-11ea-9e71-a18b770c8276.png)
![Screenshot from 2020-05-14 11-08-36](https://user-images.githubusercontent.com/56485090/81917010-ea9d3c80-95d4-11ea-889e-7bc1c9b6e798.png)
![Screenshot from 2020-05-14 11-08-41](https://user-images.githubusercontent.com/56485090/81917012-eb35d300-95d4-11ea-8ab9-cc5f1030f57b.png)
![Screenshot from 2020-05-14 11-14-50](https://user-images.githubusercontent.com/56485090/81917014-ec670000-95d4-11ea-9816-d6f8aebc61e0.png)

logs:
[2020-05-14-6.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4627414/2020-05-14-6.log)
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4627415/latest.log)

config file:
[test.recipes_friction.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4627489/test.recipes_friction.zip)

**Comment by voidsong-dragonfly** [comment]
They're getting registered to the game just fine it looks like, and I don't see anything wrong with your syntax, so this is a little confusing. I have a set of recipes that's working, but you don't seem to. Also, a bunch of your other recipes have gating items as output, so they won't register [At least for the centrifuge and the drying bed].
```[11:45:48] [Client thread/INFO]: ROTARYCRAFT: Loaded custom recipe 'flake11' for FRICTION
[11:45:48] [Client thread/INFO]: ROTARYCRAFT: Loaded custom recipe 'flake3' for FRICTION
[11:45:48] [Client thread/INFO]: ROTARYCRAFT: Loaded custom recipe 'flake5' for FRICTION
[11:45:48] [Client thread/INFO]: ROTARYCRAFT: Loaded custom recipe 'flake6' for FRICTION
[11:45:48] [Client thread/INFO]: ROTARYCRAFT: Loaded custom recipe 'flake4' for FRICTION
[11:45:48] [Client thread/INFO]: ROTARYCRAFT: Loaded custom recipe 'flake20' for FRICTION
[11:45:48] [Client thread/INFO]: ROTARYCRAFT: Loaded custom recipe 'flake2' for FRICTION
[11:45:48] [Client thread/INFO]: ROTARYCRAFT: Loaded custom recipe 'flake1' for FRICTION

**Comment by ReikaKalseki** [comment]
Try in v26.

**Comment by pajrle** [comment]
I am sorry it is my mistake. When I added recipes I thought all extracts has ID RotaryCraft:rotarycraft_item_extracts:* but I missed modded extracts has ID RotaryCraft:rotarycraft_item_**mod**extracts:* . This caused different inputs than I wanted and in some cases non-existant inputs, therefore causing game to crash.
