### ISSUE TITLE
[Chromaticraft] Drop in FPS after upgrading pylon.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2501]
![extreme lag22](https://user-images.githubusercontent.com/62176592/81973548-da2da600-9656-11ea-8807-fb77c1a93b0f.JPG)
![extreme lag](https://user-images.githubusercontent.com/62176592/81973560-de59c380-9656-11ea-80f3-b6bb1d200b75.JPG)
![2020-05-15_02 52 20](https://user-images.githubusercontent.com/62176592/81973740-22e55f00-9657-11ea-8a5e-f05251f683e7.png)

So after I upgraded the pylon to Atmospheric Lumen Broadcast Frame, the chunks around the upgraded pylon cause a massive drop in fps. I tried to do some lag profiling but all the error locations were just stone blocks or dirt blocks(???) I also regain fps when I use noclip ability around the pylon and when I revert the pylon back to turbocharged frame, the lag goes away.

If anyone could provide me some assistance in lag profiling so as to try troubleshoot why this happens, as this my first time using OPIS based on information off Google, that would be fantastic!

**Comment by ReikaKalseki** [comment]
That structure is not finished, and never will be.

**Comment by tiny-maple** [comment]
Do you mean development for the structure or I have built it wrongly?

**Comment by ReikaKalseki** [comment]
As in the structure's implementation was never finished, and its function has since been supplanted by another mechanism, meaning I never will finish it.

**Comment by tiny-maple** [comment]
I will downgrade my pylon frame to the turbocharged frame as a temporary workaround for now.
