### ISSUE TITLE
[Rotarycraft] Fan is able to blow items through solid blocks.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2503]
![2020-05-15_17 50 52](https://user-images.githubusercontent.com/62176592/82086204-bfbfff00-9720-11ea-912d-b5745220e2c8.png)
Mob farm overview
![2020-05-16_02 53 01](https://user-images.githubusercontent.com/62176592/82086789-9eabde00-9721-11ea-83ec-3409814491ca.png)
Microturbine powered fan
![2020-05-16_02 49 03](https://user-images.githubusercontent.com/62176592/82086356-01e94080-9721-11ea-86d5-96499653411c.png)
![2020-05-16_02 47 37](https://user-images.githubusercontent.com/62176592/82086373-06155e00-9721-11ea-868e-ee01967dfbe8.png)
Items being blown through solid blocks.
![2020-05-16_02 53 33](https://user-images.githubusercontent.com/62176592/82086584-4aa0f980-9721-11ea-8042-e065e1f2a036.png)
Food farm

I have a mob farm that uses a fan coupled to a microturbine to blow monsters straight into a spike to instantly kill them. I noticed that items are being blown right through solid blocks regardless how thick the wall is or the placement of my item vacuum.

In my food farm in the overworld, I also used a fan coupled to a microturbine to blow the items. However, I observed that the items are being stopped by a single layer of solid blocks and they are collected by the item vacuum. However, this farm setup is using 1 microtubrine coupled to 10 fans via shaft power bus as compared to the mob farm which uses 1 microturbine to 1 fan.

I am assuming that this is not intended, and that if a fan is given excess power, it is able to produce powerful winds that is able to push items through solid walls. For temporary measure I placed a lava pool to destroy these items since the item stacking up were causing extreme lag.

**Comment by ReikaKalseki** [comment]
The MC physics engine is stupid and fast-moving entities simply teleport X blocks every tick, ignoring whatever might be in their path. Adding some sort of raytrace is possible - meteors do it - but it is very expensive, and not suitable for mass usage like would be the case here.

**Comment by tiny-maple** [comment]
![2020-05-16_14 05 53](https://user-images.githubusercontent.com/62176592/82112822-6341fb80-9783-11ea-9ae1-4a0761461c17.png)
Extended mob collection
![2020-05-16_13 48 53](https://user-images.githubusercontent.com/62176592/82112829-6b9a3680-9783-11ea-8c43-54a2aebaea1a.png)
Found item piles inside solid chunks of netherracks. 

When these entities are moving at high speed, it seem like they retain this teleportation x blocks behavior and nothing seem to stop their momentum. I set up multiple collection points and have exceeded the fan range of 128 blocks, yet I still find item piles inside solid chunk of terrain. 

Do you refer to raytracing projectile that meteors towers in chromaticraft fires? I feel that is fine, as it is not computationally exhaustive compared to mass mob item farming. Maybe implement a form of attribute check on the speed that the item travel. For example, an item movement speed reduction condition when the item exceed the range of fan. I am not sure how MC engine will like it when such checks are enforced on high entities count. 

I could go for a redesign on the killing chambers and hold some restraint on the rate of mob spawn to work around this.

**Comment by ReikaKalseki** [comment]
`Do you refer to raytracing projectile that meteors towers in chromaticraft fires?` No, MeteorCraft.

**Comment by OvermindDL1** [comment]
Could just slow down how fast the fan pushes things (or cap the speed of the things it does push).  It will slow down processing sure but no weird tunneling effects then.

**Comment by ReikaKalseki** [comment]
I have no desire to change the movement speed of the items.

**Comment by ReikaKalseki** [comment]
There is nothing I can do about this that does not make for worse problems.
