### ISSUE TITLE
[RoC] Railgun Ammunition has no texture/icon

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2504]
It just shows the missing texture icon thing. Seems to apply to all types.

**Comment by HellsingDarge** [comment]
Are you using Unity texture pack by any chance? If so, the pack just has these texture missing.

**Comment by ReikaKalseki** [comment]
^

**Comment by Shahelion** [comment]
If the pack is missing the textures, shouldn't it default to the normal ones? It does that for everything else.

**Comment by ReikaKalseki** [comment]
All of my textures are on spritesheets, not individual texture files.
