### ISSUE TITLE
[Rotarycraft] Bedrock Pipe Pressure Overflow

### ISSUE THREAD

**Issue by timoll** [ReikaKalseki/Reika_Mods_Issues#2506]
Version 1.7.10 V25b

There is an issue with the same Bug #422.

It says it is fixed but if I try it with water, the pressure still overflows:

![2020-05-16_21 14 39](https://user-images.githubusercontent.com/17759381/82128435-7f618f00-97bb-11ea-95e8-3374078c7fc7.png)

Pump is powered by 2MRad/1Nm

**Comment by MalTeeez** [comment]
I have also encountered this, and am now using it as an infinite source for my mekanism Steam-Fusion Reactor since it can produce more water than anything else

**Comment by ReikaKalseki** [comment]
Is the liquid amount overflowed or just the pressure display?

**Comment by MalTeeez** [comment]
The Liquid, assuming I dont need to pump new fluid in it with a usage of over 45.000.000mb/m

**Comment by timoll** [comment]
It is just the pressure display. Water wasn't near a possible overflow.

**Comment by ReikaKalseki** [comment]
Fixed.
