### ISSUE TITLE
[Rotarycraft] Rotarycraft wither skeleton spawner does not spawn in the correct area.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2507]
![2020-05-17_16 14 46](https://user-images.githubusercontent.com/62176592/82139572-41b44300-985b-11ea-87b6-efe93858fee5.png)
Skeleton farm
![2020-05-17_16 11 47](https://user-images.githubusercontent.com/62176592/82139575-44af3380-985b-11ea-8b60-48a42b04ddea.png)
Large congregation of wither skeleton

When a skeleton farm is set up near a nether fortress, exiting the nether and on the next re-entry, wither skeleton will spawn on every available spawning tile in the nether fortress, a source of mass lag generator. I have placed chunk loader on my farm, but i have specify the range to not cover any parts of the nether fortress.

**Comment by ReikaKalseki** [comment]
Ambient spawn logic - which is what normal nether fortress spawns are - has nothing to do with spawners, vanilla or RC.

**Comment by tiny-maple** [comment]
> It checks if the spawn coordinates are within the "bounding box" of the entire fortress and whether the ground consists of nether bricks.

the farm is outside of the bounding box, it should fail spawning them, and I am able to reproduce this mass spawning on each re-entry of the nether. Disabling the wither skeleton spawner will prevent this, or alternatively i just place stone slab on entire available spawning tile.

**Comment by ReikaKalseki** [comment]
Unless the skeletons are coded such that spawns affect future spawns, this cannot be the case.

**Comment by tiny-maple** [comment]
I cannot think of anything else other than this is a broken spawning logic. However, this does resemble MC-182170, although there are no information available of this bug on version 1.7.10.

**Comment by Barhandar** [comment]
>I cannot think of anything else other than this is a broken spawning logic.

I can; It's not Reika's bug, it's EIO.
SleepyTrousers/EnderIO#1899

As said in there, disable wither skeleton override in the config, it's broken.
