### ISSUE TITLE
[RoC] Grinder/Extractor products should use the Ore Dictionary

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2508]
Instead of duplicating all these mod ingot and gem items, just have it output to the actual item if the ore dictionary entry is added by a mod that is loaded, and disable it otherwise. Or whatever way that actually works. The Nether Iron Ingots and Earth Infused Items, etc, don't really need to exist.

At the very least, have config options for it.

Also, if an item IS hidden, make sure it's actually removed from showing in recipes, as well. Nether Ingots being a prime example.

You even do it for materials from the mod itself, which seems unnecessary. RoC adds Calcite itself, so why not just...use it? Same thing goes for the vanilla ones. Just, why?

**Comment by ReikaKalseki** [comment]
These are all autogenerated, and a fetching system has a dozen breakage cases that need special handling. This is not worth the effort.
