### ISSUE TITLE
Expanded Restone: diamond block breaker rebalance request

### ISSUE THREAD

**Issue by the-vindex** [ReikaKalseki/Reika_Mods_Issues#251]
Currently you make it once and you can mine any obsidian you want completely free. You can make (albeit expensive) but quite trivial tree farm with it. Also attacking monster spawners with it becomes very trivial (you can break monster spawner remotely very easily).

**Comment by ReikaKalseki** [comment]
I fail to see any problem here.

**Comment by the-vindex** [comment]
It's not a bug, it's feature request. I think it's too powerful and works for free.

**Comment by ReikaKalseki** [comment]
And I disagree. If you want to make it more expensive, you can. I see no reason to force that on everyone else.
