### ISSUE TITLE
[DragonAPI] Banner says that 31 mods are out of date

### ISSUE THREAD

**Issue by LighttronPrime** [ReikaKalseki/Reika_Mods_Issues#2510]
The Dragon API banner that alerts the player that mods are out of date is claiming that I have 31 mods out of date. None of Reika's mods that I'm using are out of date, and I obviously don't have 31 mods by you installed. This a minor issue, and likely caused by one of the many other mods I'm using, but I thought I might as well report it.
I'm using Rotarycraft, Reactorcraft, Chromaticraft, and Condensed Ores, if that helps
![2020-05-17_22 36 47](https://user-images.githubusercontent.com/55519030/82169879-d4230980-9890-11ea-8a25-1d5c3158306e.png)

**Comment by ReikaKalseki** [comment]
Read what it says: it is not saying they are out of date.

Change the config for which mods the version comparator checks.
