### ISSUE TITLE
[Chromaticraft]Some bugs and some suggestions

### ISSUE THREAD

**Issue by Mr-CHENmatrix** [ReikaKalseki/Reika_Mods_Issues#2511]
Version v25b
Bug:
1,Right click on the chromatic enchanter and it will crash
2,The gold, quartz and obsidian-based glow cannot be crafting
3,The casting table of tier 3 altar (casting temple) with part of the structure replaced by the runes cannot be detected after being placed again, resulting in the common casting table (it was found that I accidentally broke the casting table in a creation mode test... )
4,Sometimes the relay source with weaked lumen inside (not full) will not be able to connect into the lumen network, while the empty relay source in the same position can.
5,Some blocks are mined with particles that appear as broken textures (such as crystal altars)
6,Invisible ores due to no progress is still prompted on the right side of the screen when the pointer points

Suggestions:
1,Storage Blocks:I think it's a good idea to add some storage blocks of materials like the vanilla. They should be decorated with cool textures. It's not a good idea for dusts, but I think those magic alloy blocks should be added. As for gems, there are many "multigems" (such as bundled crystal), so it may not be appropriate, but it's a good idea for lumenite, geode gems and avolite (the chromastone block will the animated texture like the ingot, geode gem block will be the same as glowing gemstone With the coordinate gradient color, a lumenite block should glow).
2,A config to disable refresh of chroma dimension
3,The blue adjacent core (it's bad, although there's no good core function about lighting...)

**Comment by ReikaKalseki** [comment]
1. I know from experience that that is not true, unless you are still using the old version.
2. The recipes work fine, but they were not in the lexicon. This is fixed.
3. Does the structure fail if a block of crystalline stone is placed and removed?
4. That is not at all possible.
5. 
6. This is intentional.

===========================
1. Is not worth the effort.
2. Is not going to happen.

**Comment by BlueAgent** [comment]
For 4: The Relay Source only makes requests for a colour if it drops under 50% storage.
If you would like to fill the relay source for stacking purposes you can charge up an energy crystal and place it in the relay source to fill it up.

**Comment by ReikaKalseki** [comment]
> For 4: The Relay Source only makes requests for a colour if it drops under 50% storage.

That is true for almost all CC constructs.
