### ISSUE TITLE
[Suggestion] Config option to reverse shift behavior with winged jetpack.

### ISSUE THREAD

**Issue by rkane31174** [ReikaKalseki/Reika_Mods_Issues#2512]
What I'm thinking of is similar to the functionality of the MPS glider.
Currently in RotaryCraft: if wings are enabled, they're always active unless you sneak.
What I would like: if wings are enabled, they're only active if you sneak.

As it currently stands, wings make it difficult to handle going down stairs (1-block ledges, not actual stair blocks). Wings can be temporarily disabled by holding shift, but then I'm sneaking and can't step down anyway. I could get around this by formally disabling the wings, but then I'll have to re-enable them again when I want to use them.

With this option I don't think I'd ever need to disable the wings. The only time I'd be sneaking while descending is probably while flying in the first place. I don't think there's any other reason to sneak while flying except for hover mode, but then I'm not descending and I wouldn't be gliding.

**Comment by ReikaKalseki** [comment]
Done. This is unfortunately going to be a serverside config.
