### ISSUE TITLE
[reactorcraft]HP turbine didnt work in new version

### ISSUE THREAD

**Issue by SoUNvAC** [ReikaKalseki/Reika_Mods_Issues#2513]
i know there are serveral updates in V25 but i didnt know why HP turbine didnt work in my game. Enough steam Enough lubric and even use ammonia. When i type /debugtest  it works,When i change Rec to V24 it works too. Just whatever i do it doesnt work.Is there updated a new way to start HP turbine?
![image](https://user-images.githubusercontent.com/36101041/82274509-e5643700-99b2-11ea-86a6-36a86590b2e3.png)

**Comment by ReikaKalseki** [comment]
#2372 #2432 #2455
