### ISSUE TITLE
[DragonAPI] Error loading server

### ISSUE THREAD

**Issue by kprose3154** [ReikaKalseki/Reika_Mods_Issues#2514]
I had everything running just fine but I tried to add a few mods (OreSpawn, MFFS, Voltzengine, ICBM, Rope Bridges) and now the server won't load. Of course, people are going to say remove the mods which I already did, I even reverted it to a backup of the mods and deleted the majority of the config files.

Crash Log: https://pastebin.com/JfLWUPVc
Server Log: https://pastebin.com/NhGYaUB1

**Comment by ReikaKalseki** [comment]
#2397 #2422 #2435 #2437 #2440 #2475 #2466
