### ISSUE TITLE
Knowledge Entanglement Pedestal Crash

### ISSUE THREAD

**Issue by MattmonGaming** [ReikaKalseki/Reika_Mods_Issues#2515]
When using the Knowledge Entanglement Pedestal with identical progression (both in Rune Craft as well), the entangle fails and the client crashes before the reason is posted, the server does not error. Here is the crash log from the client: https://pastebin.com/U2uTk5Vn

**Comment by thePalindrome** [comment]
As a preventative measure for similar bugs in the future, I feel it may be prudent for the server to report it as well, or at least the client log to spit out an error code (something like TIER_MISALIGNMENT or something). With how graphics heavy ChC can be, I think it'd be nice to have a few more "user-debuggable" places to check on the off chance something doesn't work.

**Comment by ReikaKalseki** [comment]
This should be fixed.
