### ISSUE TITLE
DragonApi v25c Black Screen 

### ISSUE THREAD

**Issue by AbsoluteOmega** [ReikaKalseki/Reika_Mods_Issues#2516]
When i try to load a map with the mod installed, i can't see anything, just the toolbar. i've tried to read other issues about this and none of the temporal fixes work. I've tried to change the size of the game and put it at full screen but then, even the toolbar turns black and i can't even see the options on the Esc menu anymore.

**Comment by MalTeeez** [comment]
What is Fast Render Setting at?

**Comment by AbsoluteOmega** [comment]
OFF, i also tried ON but nothing happens. this might be because of the shadders on the DragonApi. i'm trying to find a v23 to be able to play Chromaticraft but nope...

**Comment by AbsoluteOmega** [comment]
I managed to cause a problem in my minecraft and Optifine so that i had a OpenGL error on the chat, then i changed the size of the game and i could see everything again, but now, i can't replicate what happend. honestly, i just wanna play my favorite mod on minecraft -_-

**Comment by AbsoluteOmega** [comment]
v26a Still the same...

**Comment by MalTeeez** [comment]
All the things that could cause something related to an OpenGL Error, that I would change are: FastRender = OFF, Chunk-Loading = Default, Advanced OpenGL = OFF, And something that might work is resizing your game window or fully removing OptiFine

**Comment by GoldArdeo** [comment]
I fixed this by setting 'enabled = false' in config\splash.properties

**Comment by ReikaKalseki** [comment]
@AbsoluteOmega Try that.

**Comment by AbsoluteOmega** [comment]
It worked! now i don't even have to change the size of the window, there is just no black screen anymore. BUT when i get close to a Pylon, the game closes. it doesn't crash, no, instead, i get this error report on the minecraft folder.
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000007f8dff30185, pid=3144, tid=0x0000000000000870
#
# JRE version: Java(TM) SE Runtime Environment (8.0_211-b12) (build 1.8.0_211-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.211-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig7icd64.dll+0x30185]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by AbsoluteOmega** [comment]
I think this has to do with the fact that my GPU doesn't have ANY VRAM, so no mater what, i can't play this version of the mod. Anyway, i thing the fix can work for other people that has a the same problem. i'll keep playing in the v19c that i found on a folder hidden in my computer. THANKS FOR THE HELP!

**Comment by ReikaKalseki** [comment]
No VRAM whatsoever? How old is this PC? My 2012 graphics card - that I replaced at the end of 2017 due to it finally starting to die - had a gigabyte.

**Comment by AbsoluteOmega** [comment]
It's a VERY old laptop and yet it has a Core i7. the problem is the HD Graphics 4000 that really doesn't have any VRAM.

**Comment by OvermindDL1** [comment]
HD Graphics 4000 is am embedded chipset, it uses the systems normal RAM 'as' its VRAM.  That would not be the issue, likely it's the drivers.
