### ISSUE TITLE
[Chromaticraft] Fabricator stop operations indefinitely after being surrounded with tile accelerators.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2518]
![2020-05-23_00 51 16](https://user-images.githubusercontent.com/62176592/82724390-5fc0ee00-9d08-11ea-85c0-993c9ae77f7b.png)
![2020-05-23_00 51 39](https://user-images.githubusercontent.com/62176592/82724391-63ed0b80-9d08-11ea-9bd2-b265d3a5e691.png)

When I surround a fabricators with a tile accelerators, the fabricator stop working after a few cycle of production. All my pylons are turbocharged and I have checked that they are full with lumen.

**Comment by ReikaKalseki** [comment]
Does it stop crafting even if it has energy?

**Comment by tiny-maple** [comment]
yes it stops crafting even if it has energy.

**Comment by ReikaKalseki** [comment]
This is not happening for me. You must have overflowed its numerical values somehow.

**Comment by tiny-maple** [comment]
I am not sure how did I manged to overflow the value other than placing tile accelerators beside the fabricator. I will try to investigate more on my world.

**Comment by tiny-maple** [comment]
![2020-06-04_18 32 38](https://user-images.githubusercontent.com/62176592/83746699-12db0100-a692-11ea-9286-61751508ca3a.png)

![2020-06-04_18 34 41](https://user-images.githubusercontent.com/62176592/83746710-18384b80-a692-11ea-80ae-0dca5050cdfe.png)

On further testing, i found out it is the DOUBLECRAFT ability that is jamming the fabricator. While i did not get a crash as reported in #2536, i did get the same exception. I believe what made me thought it would be the tile accelerator initially was when I first placed the tile accelerators, I did not have the DOUBLECRAFT ability. I did get the ability afterwards. 

You may close this issue.
