### ISSUE TITLE
[RoC] [v26a] "java.lang.ExceptionInInitializerError" on Startup

### ISSUE THREAD

**Issue by Rovinion** [ReikaKalseki/Reika_Mods_Issues#2519]
Deleted Minecraft Folder, reinstalled forge, RotaryCraft and DragonAPI are the only mods, get this crash report on startup:
EDIT: Pastebin

https://pastebin.com/embed_js/027ndtrV

**Comment by tiny-maple** [comment]
Please use a pastebin for crash report.

**Comment by Rovinion** [comment]
Fixed

**Comment by ReikaKalseki** [comment]
#2021 #2065 #2105 #2112 #2137 #2167 #2233 #2328
