### ISSUE TITLE
RC and NEI

### ISSUE THREAD

**Issue by MaciejMalczyk** [ReikaKalseki/Reika_Mods_Issues#252]
I get an error when i want to check any recipe in nei. It happens on the newest version of both mods.

http://pastebin.com/0eQVbq9w

**Comment by ljfa-ag** [comment]
Duplicate of #224. Seems to be a problem with Pneumaticcraft.

**Comment by MaciejMalczyk** [comment]
But I get it without PC too.

**Comment by ReikaKalseki** [comment]
I do not, so clearly another mod is involved.

**Comment by MaciejMalczyk** [comment]
Heh, which versions of PC and RC do you use?

**Comment by ReikaKalseki** [comment]
I do not use PnC in my pack.
