### ISSUE TITLE
[RoC]Breaking Gearbox blocks, breaks the dropped Item

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2520]
Before, freshly crafted:
![Screenshot_182](https://user-images.githubusercontent.com/41554385/82743691-2ec7d400-9d6f-11ea-90d8-be75815d720d.png)

After, broken with bedrock pickaxe
![Screenshot_183](https://user-images.githubusercontent.com/41554385/82743697-35564b80-9d6f-11ea-8b44-305aa87a1005.png)

Also placing the bugged item and destroying it, causes it to become:
![Screenshot_185](https://user-images.githubusercontent.com/41554385/82743840-11940500-9d71-11ea-9708-0ef324e72ae3.png)

PS: Dont set the broken Stone Gearbox onto a turbine, or this will happen: 
![Screenshot_184](https://user-images.githubusercontent.com/41554385/82743770-2754fa80-9d70-11ea-8589-1f0f2015532f.png)

**Comment by MalTeeez** [comment]
Correction, Everything that can break the block, will cause the weird Item

**Comment by tiny-maple** [comment]
Reika, what do you mean by 'craft into new version'?

**Comment by Skyler-Altol** [comment]
@tiny-maple most people would think that's fairly self explanatory, but put the gearbox into a crafting grid by itself, and the output should be the equivalent "new" gearbox.

**Comment by ReikaKalseki** [comment]
Fixed.
