### ISSUE TITLE
crashes my game 

### ISSUE THREAD

**Issue by minecraftmoduser** [ReikaKalseki/Reika_Mods_Issues#2521]
so i downloaded this mod along with electricraft and reactorcraft and went to start minecraft the game crashes but when i remove rotarycraft the game opens up so idk if it cant run with the other mods i have installed or what?

**Comment by MalTeeez** [comment]
Please add logs, either from the /logs/latest.log in your minecraft folder or the /crash-reports one

**Comment by minecraftmoduser** [comment]
[crash-2020-05-18_13.26.27-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4673120/crash-2020-05-18_13.26.27-client.txt)

**Comment by MalTeeez** [comment]
Ok, Since that is not from a 1.7 Version - What do you use to start your modded minecraft?

**Comment by minecraftmoduser** [comment]
minecraft launcher and my bad i guess i didnt see it was a 1.7 version i use 1.12.2 mods so if that was the reason for the issue i have another question but its about a different mod im having issues with so i might go to the issues page for that mod to ask
