### ISSUE TITLE
[CrC] Breaking leaves from hybrid trees crashes the game, v26a

### ISSUE THREAD

**Issue by wamc2017** [ReikaKalseki/Reika_Mods_Issues#2523]
Hi,

breaking leaves from the new hybrid (I tested Kuro and Karmir) saplings crashes the game.
Crash while trying to break them without any tool: https://gist.github.com/wamc2017/b2a6b352bb96e66689d69a191dd97c6b
Crash while trying to break them with a bedrock grafter from RotaryCraft:
https://gist.github.com/wamc2017/6dd8f5a7aa1d52b6e3d9fb1d71716f9d

thanks for looking into it.
Best regards
wamc

**Comment by ReikaKalseki** [comment]
They work for me, and digging through all the relevant code indicates that the only way this can happen is if you have a null-item fruit registered to the fruit system, or if `getMemberStack` in TreeHelper is returning null (very unlikely).

**Comment by wamc2017** [comment]
Hmm, strange, tried it with only Chromaticraft, DragonApi, Forestry, Baubles and Thaumcraft installed (the last two because of #2522) on a new world and it crashes nearly on every hybrid leave I break. It seems to only happen with unripe leaves, if I bonemeal them before, everything seems fine...

**Comment by ReikaKalseki** [comment]
I have one idea; try again in v26b.

**Comment by wamc2017** [comment]
Works great in v26b. Thanks. :)
