### ISSUE TITLE
[RotaryCraft] Fractionation Unit page in handbook describes old recipe

### ISSUE THREAD

**Issue by Gumbo379** [ReikaKalseki/Reika_Mods_Issues#2524]
As said in the title, the Fractionation Unit will not produce Jet Fuel with the listed items in the RotaryCraft Handbook. I am running on version 1.7.10 v26a for both RotaryCraft and DragonAPI. This could either be a misinformation with the Handbook or an actual issue with the Fractionation Unit.

> The fractionator distills various items and refines them into jet fuel for use in some of the engines and machines. Jet fuel requires tar, netherrack dust, coal, blaze powder, ethanol, and magma cream. Additionally, ghast tears are used as a solvent, but are not consumed like the other items. Fuel lines connect only to the top of this machine.

Fractionation Unit filled with items listed in the RotaryCraft HandBook in chronological order.
![Inside Fractionation Unit](https://user-images.githubusercontent.com/19158756/82768358-3eaaeb00-9e37-11ea-877d-ebf0c8638ec6.png)

Fractionation Unit is powered by 4 steam engines with a steel 16:1 gearbox in speed mode. The reservoir connected on top is empty.
![Fractionation Unit Setup](https://user-images.githubusercontent.com/19158756/82768368-4a96ad00-9e37-11ea-8295-1f22df8caae3.png)

**Comment by tiny-maple** [comment]
Mate you are using the legacy recipe for jet fuel. Click on the machine to see the updated recipe.

**Comment by Gumbo379** [comment]
> Mate you are using the legacy recipe for jet fuel. Click on the machine to see the updated recipe.

"The fractionator distills various items and refines them into jet fuel for use in some of the engines and machines. Jet fuel requires tar, netherrack dust, coal, blaze powder, ethanol, and magma cream. Additionally, ghast tears are used as a solvent, but are not consumed like the other items. Fuel lines connect only to the top of this machine."

This is what it says when I click on the machine.
![2020-05-25_03 37 56](https://user-images.githubusercontent.com/19158756/82768681-36ec4600-9e39-11ea-92c2-7a04da5c12a0.png)

**Comment by tiny-maple** [comment]
See #2380

**Comment by MalTeeez** [comment]
Im not an expert, but shouldn't the "ethanol" be fluid and the ethanol crystals be replaced by pink dye?

**Comment by ReikaKalseki** [comment]
Fixed.
