### ISSUE TITLE
Some Feature Suggestions

### ISSUE THREAD

**Issue by Zebralear** [ReikaKalseki/Reika_Mods_Issues#2525]
I’m gonna start with the least likely to be made of the three and work up from there, because why not.

Suggestion 1: “Pocket Proxima”
Basically, a Pocket of stabilized Proxima (though probably easier if it was technically it’s own separate dimension) that can be customized to have different generation from the dimension (like say, a monument surrounded by the outside biomes of Proxima. Would probably be a multi-block construct that would be unlocked after the Aura Locus was obtained.

Suggestion 2: More “failed constructs”
I absolutely love the lumen repeaters. They are amazing, as they show a player’s “learning the hard way” about not being cheap with the construct creation. I would, at least, enjoy having more things like that in the mod, or maybe even a feature where you are slowly given the structure blueprints for things like the portal beacon as you progress and make major discoveries- scattered knowledge coming together in the end is the whole idea of the mod, right?

Suggestion 3: Music Discs
I mean, Proxima music discs. ‘Nuff said, in my opinion.
Seriously though, I love the dimension score, and I have always wished I could bring it with me everywhere...

**Comment by ReikaKalseki** [comment]
1 is not remotely implementable; basically all of the dimension code is written around it being the dimension.

3 is also not implementable; my music is loaded though a custom system which music disks cannot reasonably be made compatible with. There are, however, mp3 player mods - I remember one from 1.1 quite fondly - and so you do have options.

2 is....not going to be popular. Hell, I showed your message to people who had spent an *extreme* amount of time and effort complaining about the weak repeaters and their reaction could basically be summed up as "whatever, they still suck and you should remove them entirely and I am still mad at you for not doing so".

**Comment by Zebralear** [comment]
Well, that’s good information to have. I’ve always wondered how CrC is always so seamless, and the fact that you made everything for the dimension self-contained (for lack of a better term), and went through the trouble of custom-loading the dimension score really makes me appreciate the work you do all the more!

Also, I can’t say I’m surprised a lot of people disliked the failed constructs idea; I used to hate the wooden repeaters, but then I just decided to go to town and make a ‘fireworks’ display out of them at one point (did skystrike with them for fun and watched it all go boom)...

Anyway, thanks for taking the time to respond!

**Comment by OvermindDL1** [comment]
What I dislike about the wooden repeaters is not that they exist, but rather that you are forced to go through them (without exposing secrets).

More failed constructs would be entirely fine and good, if they failed because the player themselves actually failed with their design.  The issue is that the structures are extremely hard-coded and defined instead of being a set of components that the players themselves build up to perform actions, hence why it doesn't fit in CrC as it's currently designed.
