### ISSUE TITLE
Crash when breaking Gearboxes

### ISSUE THREAD

**Issue by GoldArdeo** [ReikaKalseki/Reika_Mods_Issues#2526]
Wood - https://gist.github.com/GoldArdeo/f17ce54d3733d27d86cd2c1d804b2c22

Tungsten - https://gist.github.com/GoldArdeo/ce3508a8d61242c654547ddaedef3ad9

Originally it was just the Tungsten 16:1 but with fastcraft on it's basically random so i've had to turn it off. Wooden 2:1 seems to be a consistent crasher.

Update: so I made a new instance with only NEI / RoC / Avaritia installed and it still happens - https://gist.github.com/GoldArdeo/f4c499f2b2c2bfbf43215dcebc8cccab

When the game doesn't crash, they become whatever this is: 
![image](https://user-images.githubusercontent.com/36109338/82833223-55902280-9eb5-11ea-9d91-f3a4155a6157.png)

**Comment by MalTeeez** [comment]
Sounds similar to #2520
