### ISSUE TITLE
[ReC]HTGR heat gets voided

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2527]
The Pebble beds are full with TRISO fuel and are producing Heat:
![Screenshot_186](https://user-images.githubusercontent.com/41554385/82807621-6f674080-9e88-11ea-955d-7a11755bb767.png)

But the Heat isnt absorbed by the CO2 Heat Exchangers: 
![Screenshot_187](https://user-images.githubusercontent.com/41554385/82807699-96be0d80-9e88-11ea-88ba-34916f909016.png)

**Comment by ReikaKalseki** [comment]
Fixed.
