### ISSUE TITLE
[Crc] Fertility aura bug? 

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2528]
Somehow I was able to launch with crc without thaumcraft yesterday, and all the grass I walked near turned into tall grass, but removing crc stopped making the grass tall (I should mention I am in the very early "stage" of crc and am a long way off from being able to get abilities).

(I am guessing it is fertility aura since that is the only thing I can think of that can do that to the player)

After I removed and re added crc, the thaum bug stopped me from double checking . . .

(The world is a SP world that was made before the 26a updates, if that makes a difference)
Once it is fixed I can go test with only your mods (since I was using a mod pack).

**Comment by ReikaKalseki** [comment]
Yes, that is fertility aura. What is the bug?

**Comment by lAimBotl** [comment]
I don't have the progression to have the ability in that world (which also means I cannot turn it off)

Just confirmed that it only happens in the world that was started before 26a (25c was the version I started the world with)

Dying does not remove it . . .

**Comment by ReikaKalseki** [comment]
The ability is not stuck on for anyone else nor in my testing. Check your player NBT.

**Comment by lAimBotl** [comment]
What would I be looking for?

**Comment by ReikaKalseki** [comment]
The abilities tag.

**Comment by lAimBotl** [comment]
I don't see anything crc related under abilities, strange, for now I will just make a new world, double tall grass everywhere makes it hard to see when you can't fly lol.

**Comment by lAimBotl** [comment]
Ha, found out it is a known bug for a different mod I have, oops.
Sorry for wastin your time lel.
