### ISSUE TITLE
DragonAPI V26a Crashes

### ISSUE THREAD

**Issue by idunnoooooo** [ReikaKalseki/Reika_Mods_Issues#2529]
DragonAPI V26a Crashes on Thermos.

**Comment by Zebralear** [comment]
None of Reika’s mods are designed to work with thermos or kcauldron. Others will be able to explain why, but I don’t know it off the top of my head, so it’s probably just best if I don’t say anything- lest I say something horrendously wrong.

Same as this one:
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2461

**Comment by ReikaKalseki** [comment]
And #2199 #1740 #1437 #1566 #1583 #2262 #2203

And 45+ more.
