### ISSUE TITLE
Mine Tweaker Support: Some But Not All Lines Are Getting Commented Out

### ISSUE THREAD

**Issue by RoloEdits** [ReikaKalseki/Reika_Mods_Issues#253]
DragonAPI 1.7.10 V8g

MineTweaker3-1.7.10-3.0.10

After entering in changes in the MineTweaker script while still in game and manually reloading it works just fine, as in no lines are getting commented out, but if I were to get a crash on world load up or if I close out because its not responsive, the next time I would to load up the world successfully the lines have commented out and I have to manually undo that.

This commenting out of lines has been happening irregularly as it does not always seem to happen, even with what I described earlier about crashing it does not seem to be a 100%  chance of happening, so in saying that I might just be finding a pattern that isn't there and in that case i have no idea whats happening or how to reproduce it at all.

**Comment by RoloEdits** [comment]
After doing a little more testing it seems to happen even if it doesn't crash. the only things that don't get commented out seem to be the bedrock gears, shafts and the screw driver recipe, but all of the armor and tools do. I even tried putting in recipes for the world edit tool and the magic wand but those are fine too.

**Comment by ReikaKalseki** [comment]
Is this a server or singleplayer? If the former, certain items's recipes are "locked", and the behavior your are describing is the correct behavior.

https://github.com/ReikaKalseki/RotaryCraft/blob/master/RotaryCraft.java#L430

**Comment by RoloEdits** [comment]
Single player

**Comment by ReikaKalseki** [comment]
Then the SSP test is failing...I found a potential bug.

For now, try /mt reload while the world is loaded (and after uncommenting the lines). It may work.

...What exactly are you trying to change, anyways?

**Comment by RoloEdits** [comment]
Yes, doing it manually does work. I'm trying to add Crafting table recipes for the armor and tools as well as the gears and shafts which the gears and shafts seem to work.I'm thinking about adding crafting recipes for the magnetostatic upgrades but i,m not sure about that yet.

**Comment by ReikaKalseki** [comment]
...Or you could just use the config...?

**Comment by RoloEdits** [comment]
What do you mean?

**Comment by ReikaKalseki** [comment]
RC has a config to copy all worktable recipes to the crafting table.

**Comment by RoloEdits** [comment]
I should have said the bedrock tools and gears.I already have that option enabled, for ae auto-crafting. sorry for the confusion.

**Comment by ReikaKalseki** [comment]
Bedrock crafting is done in the blast furnace, and this is a strong gating mechanism (to get around the fact that selling bedrock ingots is common on servers).

**Comment by RoloEdits** [comment]
Oh OK that makes sense,I have only ever played single player so I would never have known that.
