### ISSUE TITLE
Elecrical age and dragonAPI not working together

### ISSUE THREAD

**Issue by Rob-exe** [ReikaKalseki/Reika_Mods_Issues#2532]
Hello,
My issue is that my 1.7.10 Minecraft world does not work with both dragonAPI and Electrical age, The relevant issues in ElectricalAge is [Issue 539 in Electrical age](https://github.com/Electrical-Age/ElectricalAge/issues/539). Not a duplicate of the other two bugs since they can get their lights to start. I have Rotarycraft, Reactorcraft, DragonAPI, and Electrical Age installed.

**Comment by voidsong-dragonfly** [comment]
What version of Electrical Age are you using? Are you using 1.17? Are you using 1.15.x-stable from Jrd's branch?

**Comment by Rob-exe** [comment]
I'm using Minecraft 1.7.10 to be exact the version of DragonAPI is 26a and the Electrical age is the latest version, no number included.

**Comment by Rob-exe** [comment]
I would've tested it with the older version of DragonAPI, but Reika only has the latest download on her page.

**Comment by voidsong-dragonfly** [comment]
No number attached..... that's really strange. Try this CF build https://www.curseforge.com/minecraft/mc-mods/electrical-age/files/2937618

**Comment by Rob-exe** [comment]
That is exactly the version I'm using. I've deleted dragonAPI and the mods dependent on it and the lights now work

**Comment by voidsong-dragonfly** [comment]
Well, the one I am using (though it is a little less stable) is https://www.curseforge.com/minecraft/mc-mods/lusty-lavender/files/2830222 , try this one.

**Comment by Rob-exe** [comment]
Works now, thanks
