### ISSUE TITLE
[Reactorcraft] RF turbine multiblock check fails even when structure is built correctly.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2533]
![2020-05-27_01 53 58](https://user-images.githubusercontent.com/62176592/82935803-40ec8100-9fc0-11ea-9183-343f8c773b6a.png)

![2020-05-27_02 02 06](https://user-images.githubusercontent.com/62176592/82935735-1ac6e100-9fc0-11ea-91e5-bcbc046fa3be.png)

![2020-05-27_02 11 28](https://user-images.githubusercontent.com/62176592/82935771-30d4a180-9fc0-11ea-8631-cf1c48bfec32.png)

I cannot seem to trigger the multi-block structure check reliability. At first I thought they were too close from each other, so I spaced them apart of at least 8 blocks distance away from each other, I tried to place the generator rotor core block as the last block, nothing happened. I have observed this behavior in an additional 4 RF turbine I have tried to install. Out of the 4, only 1 managed to successfully change its structure.

Is there a consistent way to ensure the RF turbine always changes its structure?

**Comment by DerWahreQwert** [comment]
Have you tired placing the generator rotor core closest to the turbine last ?

**Comment by tiny-maple** [comment]
> Have you tired placing the generator rotor core closest to the turbine last ?

Yes I did, and I cannot seem to trigger it consistently.

**Comment by ReikaKalseki** [comment]
It works fine for me. You either have something interfering or, more likely, built it incorrectly.

**Comment by tiny-maple** [comment]
Is there a minimal amount of airblocks between the first and second RF generator? I did a check on the structure and all the blocks are placed correctly.

**Comment by ReikaKalseki** [comment]
They cannot be placed adjacent, no.

**Comment by tiny-maple** [comment]
Seem like something is interfering with my rf generators, I only can get them to trigger a structure check only when I space them equally at a minimal of 8 air blocks away from each other. I will just try to find out what is wrong on my end since it work for you and everyone else does not have issues with them.
