### ISSUE TITLE
[RotaryCraft] Array out of bounds rendering dropped gearbox

### ISSUE THREAD

**Issue by mhansen718** [ReikaKalseki/Reika_Mods_Issues#2534]
Crash Log: https://pastebin.com/Ry8wD80H

I broke a 4:1 stone gearbox (iirc) and the client immediately crashed. Now it crashes every time anyone gets close to where the item (item.item.item.gearplacer.6) dropped.

**Comment by ReikaKalseki** [comment]
That suggests a completely invalid item. I already have fixed the drops (#2520, #2526). An item that invalid will now just delete itself.
