### ISSUE TITLE
Essentia Relay crashes game when changing labels on jars

### ISSUE THREAD

**Issue by pittmichaeltd** [ReikaKalseki/Reika_Mods_Issues#2535]
if you add a label to a jar while the essentia relays are active, it crashes the game with a ticking block entitiy error
[crash-2020-05-27_16.48.52-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4691755/crash-2020-05-27_16.48.52-server.txt)

**Comment by ReikaKalseki** [comment]
Fixed.
