### ISSUE TITLE
[DragonAPI] Soft World Lock

### ISSUE THREAD

**Issue by BritishCynic** [ReikaKalseki/Reika_Mods_Issues#2537]
So, since upgrading from v25c to v26a/v26b, there's been consistent reported behaviour from DragonAPI within the console that have co-incided with a soft world lock (i.e. I can move around, destroy blocks, but the world doesn't update). I'm not saying with absolute certainty that DragonAPI is the cause, but as the only mod throwing out an error during this part, it's the only lead I have.

https://pastebin.com/E13Zgvxz

Without an actual error that crashes the client, I don't have a stacktrace, only console outputs in the moments before and after I notice the soft lock occurring. It always coincides with the METADATASPECIFICTRADES patcher applying, where the "Tried to fire an event for chest loot from an unrecognized structure" error occurs. Usually, Forestry and Tinker's Construct structures seem to cause this error.

DragonAPI does still seem to be running tasks in the background, and does output further console text after I notice the softlock at 19:39 in that pastebin, such as a "Loading dynamically sourced asset Textures/warpnode-small.png" at 19:57 as I type this.

Would be grateful if you could take a look.

**Comment by MalTeeez** [comment]
can you provide the fml logs?

**Comment by BritishCynic** [comment]
It didn't generate any fml logs. All I have is the latest.log,

**Comment by BritishCynic** [comment]
I tried to go back into the same world that I had to force quit on, and it hard crashed:

https://pastebin.com/vBGQX2mM

**Comment by ReikaKalseki** [comment]
That crash is due to a vent block with invalid metadata.

**Comment by BritishCynic** [comment]
Either way, I think DragonAPI is still responsible for the worldgen issue mentioned above. As I write this, I've just entered the Nether for the first time on a world where the initial spawn didn't fail due to the condition above (the world as made before the world that soft locked causing me to make this post), and worldgen from GregTech has been continuing non-stop for 35 minutes. I have a sample of here the server thread currently active:

https://imgur.com/jbbRl43

https://imgur.com/OuXTgOb

It mentions DragonAPI a few times. Here is a pastebin of the error left in the console before this runaway worldgen started.

https://pastebin.com/qQdBmxaT

**Comment by ReikaKalseki** [comment]
No, that is just massively chained (due to massively spilling) worldgen. Just because DAPI is in the trace - only because of ASM hooks at that - does not make it responsible, any more than the other mods mentioned there are.
