### ISSUE TITLE
Black screen after upgrading from v16d to v25 & v26 DragonAPI, RotaryCraft, ElectriCraft, ReactorCraft, ExpanedRedstone

### ISSUE THREAD

**Issue by walkerjonny** [ReikaKalseki/Reika_Mods_Issues#2539]
I didn't play Minecraft for some time.
When I now try to upgrade from the old version v16d to the newest version of your mods for some reason my screen remains black and I can't see anything.
The game itself seems to work fine. I can walk around and my machines are all working.
Just the screen doesn't show anything.
Is there something you know that could cause this kind of behavior?
Maybe I just need to change a parameter somewhere in a config file.

**Comment by DerWahreQwert** [comment]
I could resolve similar issues by toggling between fullscreen and window mode.
Might be worth a try

**Comment by MalTeeez** [comment]
Try the tips from #2516
