### ISSUE TITLE
[Feature Request] Repeater enhancements.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#254]
As a follow up to my recent multi-repeater phail i would like to suggest some advanced control mechanism over the repeaters pathing. These could help controlling to which machines, altars, rituals, etc energy can flow. I.e. when lumen is low and you want to speed up machine a and switch off machine b.

1) Facilitate toggling a repeater on/off, i.e. by redstone or similar to the lumen lamp with wireless channels.

2) Facilitate forcing some repeaters selectively to only connect to specific other repeaters, i.e. by using the linker.

3) Facilitate restricting multi-aura repeaters to only work for a limited subset of colors, i.e. "everything but tahara", "tahara and kuro only".

4) Allow repeaters to be constructed vertically and/or upside down. This would, depending on the situation, make building more flexible/compact/esthetically pleasing and allow things like routing lumen as a ceiling light :D. Could be implemented as a "secret" feature not mentioned in the chromic lexicon or as extra research.

**Comment by ReikaKalseki** [comment]
I am not going to implement (2) or (3) - it requires significant rewrites to the pathfinding. (4) is already possible. (1) might also be possible (try pistons to break and replace the structure), but if not I am willing to implement redstone control.

**Comment by lossycrypt** [comment]
4) Dang. I actually tested when i read the v8g changelog but couldn't get it to work. Tested again, and now it does indeed work for single and multi in all directions.

1) Pistons do indeed work if the construct has formed correctly once before. On single-color repeaters moving the rune breaks the repeater tho. On multi all 5 blocks work. (The repeater block itself being unmovable.)

**Comment by ReikaKalseki** [comment]
> The repeater block itself being unmovable.

TileEntities are. :P
