### ISSUE TITLE
[Rotarycraft] Old gear parts can throw OOB

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2540]
Crashlog: https://pastebin.com/5aGFEM64

Was clearing out invalid items from ME system. Immediate crash after I tried to void them in a XU trash can. Any attempt to login to world crashes immediately.

I believe I had a stack of diamond gears made previously in when I was on 25c. They were all invalid in 26b so I tried to clear them out of the ME system.

**Comment by tiny-maple** [comment]
@ReikaKalseki Do you have a list of items that you have made them obsolete? I load a 25c world backup, tried to clear out all old gear parts in my ME System before updating to 26b but i suppose there are other parts that became invalid as I obtain the same crash when accessing the ME system.

**Comment by ReikaKalseki** [comment]
Everything involving crafting gears, as well as other "shaft parts" like cores and the shafts themselves. Not, however, base panels or ingots.

**Comment by tiny-maple** [comment]
>Everything involving crafting gears, as well as other "shaft parts" like cores and the shafts themselves. Not, however, base panels or ingots.

Thanks, successfully updated world to 26b after discarding the legacy items in 25c.

**Comment by tiny-maple** [comment]
Update on this issue
![2020-06-03_02 38 22](https://user-images.githubusercontent.com/62176592/83557002-74408a00-a543-11ea-9252-6f9d75d63031.png)

I noticed that existing diamond, steel, stone, and wood gearboxes made before 26b are mutating into random gearbox material type when left in chest. I never owned a 64x Bedrock Gearbox, and I do not believe 64x actually exist. 

These gearboxes are actually left in the world when I made the update to 26b, then I broke them and left them in a chest. When I boot up the world the next day, all of them mutated. I voided them quickly because they are able to throw the same OOB as well.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by tiny-maple** [comment]
Is this fixed as well? I found there are nbt issues between a newly crafted gearbox and one that placed in the world. 
**Newly crafted**
2 tag
`damage: 0`
`type: Bedrock`

**Placed in world then picked up**
4 tag
`bearing: 0`
`damage: 0`
`Lube: 0`
`type: Bedrock`

This leave me with two types of 2x gearbox inside my ME system.
