### ISSUE TITLE
[Chromaticraft] Lumen Dash during the battle of Gaia guardians

### ISSUE THREAD

**Issue by Arcaneless** [ReikaKalseki/Reika_Mods_Issues#2541]
The battle of Gaia guardians in Botania creates a bouncing barrier around the beacon in a circular shape.
Using the lumen dash to dash out of the area would cause the cancellation of the battle, 
Plus semi-permanent speed and jump boost, until trigger another lumen dash.

**Comment by ReikaKalseki** [comment]
I cannot fix this.
