### ISSUE TITLE
[ReactorCraft] Noise generated from turbine is too soft.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2542]
![2020-05-30_14 20 44](https://user-images.githubusercontent.com/62176592/83321253-f64d5c00-a280-11ea-90c8-5c3619049bdb.png)
Turbines in reactorcraft are too soft, they need to be increased as real turbines are loud, and workers would require ear protection to perform task in fields near the turbines. In this photo I have all my volume turned up and the sound generated by the turbine is softer than a microturbine or magnetostatic engine.

**Comment by Skyler-Altol** [comment]
@tiny-maple this would be an instance where remembering that this is a **game** and not real life would be a wise idea. Real life turbines cause actual damage to human hearing, and emulating that in a game... is not a good idea.

**Comment by tiny-maple** [comment]
>  Real life turbines cause actual damage to human hearing, and emulating that in a game... is not a good idea.


I also believe that idealization of actual turbine sound level is unacceptable in Minecraft. Instead I would propose is to raise the volume to the level same as the Gas turbine engine in Rotarycraft, as that sound level is considered acceptable since it has been around for years. Now compared that volume level to the existing turbine sound level in Reactorcraft, which produce a sound level lower than a Microturbine engine.

**Comment by ReikaKalseki** [comment]
I turned it up a little, but it was already near the clipping point.
