### ISSUE TITLE
[Rotarycraft] V26B - Manual uses incorrect units for engine power

### ISSUE THREAD

**Issue by Sevalecan** [ReikaKalseki/Reika_Mods_Issues#2544]
In the engines manual section for Rotarycraft, it lists the power output of each engine, and the number displayed is in watts, but the unit shown is "kW" or "MW" depending on which engine. For instance, the steam engine should be 16.384kW or 16384W, but instead displays as 16384kW.  The microturbine lists its power output as 2097152MW instead of 2.097152MW or 2097152W

**Comment by ReikaKalseki** [comment]
What locale are you using? People have reported that in the past over '.' vs ','

**Comment by Sevalecan** [comment]
Currently set to 'English (US)'. I will note I have only observed it in the engines section of the manual. Other devices such as the extractor and fan list power ratings in "W" with no decimal, so they appear correct. Usage of the angular transducer correctly uses engineering notation with a '.' such as "16.384kW".

**Comment by ReikaKalseki** [comment]
Fixed in v29.
