### ISSUE TITLE
[Chromaticraft]  Achievement that has been completed in previous version are marked unknown.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2545]
![2020-05-31_22 16 19](https://user-images.githubusercontent.com/62176592/83354649-abb90600-a38c-11ea-9547-88de1084a3c3.png)
I have completed Chromaticraft in 24c, but in 26b I get completed achievement triggering as if i just did them even if the action is invalid. In this picture I just entered my swamp base and the event for completing the achievement is triggered as if i performed it for the first time.

**Comment by ReikaKalseki** [comment]
The progression map changed.
