### ISSUE TITLE
[Rotarycraft] Shaft that are built prior to v26b have their material changed to one tier lower; All shaft recipe are missing. 

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2546]
![2020-05-31_22 42 47](https://user-images.githubusercontent.com/62176592/83355140-1455b200-a390-11ea-8dfe-fd5eb28c6eb6.png)
Previously in my ME system I have 6 diamond shaft, and 8 bedrock shaft in 25c. Updating the version to 26b causes them to downgrade 1 tier lower and bedrock shaft recipe is missing.

[25c] Bedrock shaft -> [26b] Diamond shaft
[25c] Diamond shaft -> [26b] tungsten alloy shaft

edit-
Pressing 'R' button in NEI does not display any shaft recipe available.

**Comment by voidsong-dragonfly** [comment]
It is only gone from the worktable, if you have crafting table crafting on it is craftable there.

**Comment by tiny-maple** [comment]
>It is only gone from the worktable, if you have crafting table crafting on it is craftable there.

Ok it works if crafting machine on crafting table is enabled in the config. Crafting shafts via worktable is not possible for now.

**Comment by ReikaKalseki** [comment]
Fixed.
