### ISSUE TITLE
[CrC] Genetic Storage Container issues (v26b)

### ISSUE THREAD

**Issue by wamc2017** [ReikaKalseki/Reika_Mods_Issues#2547]
Hi,

I tried out the Genetic Storage Container today and it seems to have a few issues:
1) If I right click the Container with let's say 1 sapling, it seems to store the sapling 3 times (so if I take a stack of saplings it adds 192 to the container)
2) The Container can be directly connected to a ME Network, but the including items don't show up in the terminal (so I guess it either should work like a drive or should not connect at all?)
3) If the Container is connected through a storage bus, it looks like only one item can be inserted at a time (for instance through a terminal or through an import bus)

I made a testpack with the following mods (no others) installed:
forge-10.13.4.1614
DragonAPI 1.7.10 V26b
ChromatiCraft 1.7.10 V26b
forestry_1.7.10-4.2.16.64
appliedenergistics2-rv2-stable-10/rv3-beta-6 (tried it with both versions)

Not an issue, but if Binnies Mods is installed, it would be nice if the Container could storage Serum from Genetics and Flowers from Botany as well. Same for Gene Samples from Gendustry.

Thanks for looking into it.
Kind regards,
wamc

**Comment by ReikaKalseki** [comment]
(1) was fixed in v29, and it was always meant to be used with a storage bus, not as a direct connection (only drive-type blocks can be directly connected, and then it would need storage cells).

I added support for the serums and gene samples.
