### ISSUE TITLE
Magnetic Containment pipes continue to fail

### ISSUE THREAD

**Issue by Saereth** [ReikaKalseki/Reika_Mods_Issues#255]
We have been troubleshooting this now for over a week, we've tried nearly every configuration imaginable. Currentlym we moved the entire operation to the over world. admin chunk loaded (all parts of it within the 3x3 chunk boundaries). Vanilla forge. regardless of anything we have tried the pipes continue to melt on the inside of the mutliblock. Our latest attempts use a t5 magnetostatic powering the van de graph directly where the pipe enters. I took screenshots so you can see our setup. This is 100% reproducible by us and happens even if we stand there. Within an hour of operation they inevitably fail each time. We stood there and watched the latest one turn to lava and captured the pipe's NBT data to see if it would shed any additional light on the situation. 

This is the setup and nbt data
http://imgur.com/a/I34qz

We replicated this setup without the plasma injector and it's been running for 3 days without melting, the only difference is the plasma injector. The pipes INSIDE the plasma injector always melt.

duplicate setup without the injector in the mix->
http://i.imgur.com/WInvgPJ.png

**Comment by ReikaKalseki** [comment]
That should work fine...the only thing I can think of is integer overflow, but then the block next to the VDG would melt first...

**Comment by Saereth** [comment]
we hooked it all back up and as soon as the server restarted all the pipes melted again instantly. it happens inside the injector multiblock where we cant even directly pass a van de graaf discharge. We are charging as close to the entrace as possible.

http://imgur.com/a/WvQI2

it's acting like on server startup/shutdown it stops sending the charge into the multiblock or the multiblock fails to recognize it.

**Comment by ReikaKalseki** [comment]
The problem is not one of insufficient charge. I will put some debugging logging into v9.

**Comment by zemerick** [comment]
Where's the chunk boundary? Maybe on restart, it's loading the chunk with the injector and associated pipes, but not the VDG.

You should really change it back to a DC engine too. I am positive that is enough for such a short distance, and it would eliminate any possible overcharge quirks. ( Well, might need a second back towards the preheater wherever that is. DC is good for around 16 blocks from the VDG. When you get towards the limit, it can be a bit iffy, so I don't know an exact max distance. )

**Comment by Saereth** [comment]
all components are within the 3x3 chunks with at least 1 block to spare on all sides. It's admin loaded with a railcraft admin loader and everything else seems have chunk loaded fine. Our liquid nitrogen is down a few floors in the same chunk area and is producing even if no one goes there after server restart. I dunno about the dc engine, we had multiple meltage with a t3 magneto, im willing to try anything at this point though.

**Comment by zemerick** [comment]
Lets try to narrow some things down then.

You say within 1 hour. This is always, right? So, if I'm doing a test, and it's good for at least 1 hour, I have not replicated the problem.

What other mods do you have? Can you replicate this with just Reikas mods?

Forge and java versions?

Can you replicate this in SSP?

Can you replicate this at another location on your SMP world?

Have you tried with the area around the pipe clear?

Have you tried with the pipe out a bit, and putting the VDG under the pipe? ( this is how I run mine. )

This isn't just client side, correct? If you log out and back in, it's still melted, and everyone sees it melt at the same time?

The plasma appears out of the pipe to the top, and has a gap at the bottom in all of your pics. Have you noticed anything else about that visual glitch? ( I notice your test pipe without the injector does not do this. )

That's all I can think of off hand to check.

**Comment by Saereth** [comment]
vanilla forge, 1448 we have moved the entire setup. I have done a test version which never melts that is exactly the same: http://i.imgur.com/WInvgPJ.png

I did a testworld, removed all mods except the ones needed to replicate this brought over the world, obviously a lot of blocks were missing but same issue. 

The only time we get meltage is when you involve the plasma injector multiblock, and the pipes always melt inside the multiblock.I have noticed the graphical glitch in all our tests but didnt think anything of it. We have tried the VDG in several positions along the pipe with the same result.

Once I can login later I'll try the dc engine and I'll remove absolutely as much stuff around the pipe as possible, but in our original setup it was a void setup with nothing around. Thanks for all the suggestions, I'll report back if anything helps, until then we're just waiting for the v9 debug info, no biggie :)

**Comment by zemerick** [comment]
I just hit 1 hour 10 minutes in a SSP test world, so it isn't as simple as just the injector. I do not have quite the same graphical glitch, though the hitbox IS glitched that way. The plasma however flows in the pipe fine. While I don't think that is the cause, whatever is causing it could also be related to the actual problem. Figuring out what causes that might actually give us a clue.

**Comment by aurumvorax** [comment]
I'm noticing something here, it may be relevant.  Do you get the same problem if you have the pipe run horizontally for a block or two before it enters the injector?

**Comment by Saereth** [comment]
This no longer seems to be an issue with v9, at least its been running a couple days with no problem. I did reroute the pipes to give them 2 blocks horizontal space before entering, not sure if thats what changed it or not since we also updated to v9b.
