### ISSUE TITLE
Crash when overloading "sad" repeaters?

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2551]
Here is the crash report:
https://pastebin.com/ChwjnSuz

The repeaters did not transfer any lumens,
they just caught fire and when they where supposed to explode it crashed.

(I should mention I don't have the "Lumen Overload" thing unlocked in my progress tab)

**Comment by ReikaKalseki** [comment]
This seems like a packet race condition.

**Comment by ReikaKalseki** [comment]
Has it ever happened again?

**Comment by FINDERFEED** [comment]
Happened to me too,but it completed an achievement for me.

**Comment by lAimBotl** [comment]
Seems that if you use the repeaters on the charger ya get for lumen storage 2, it will crash and not give ya the progression (since the repeaters don't even send power to the charger at all, so you don't get its progression, so the overload prog is locked and repeaters explode technically before they should)
making it pull directly from a pylon works at getting lumen storage 2 though
(also crash report is the same still)

**Comment by lAimBotl** [comment]
welp, I got them to explode again, but no crash. cool, only thing different is this time the host pc's cpu is overclocked lol.

**Comment by ReikaKalseki** [comment]
Looking again, this is not packet race or anything like that - it is a simply *invalid* packet, one with a null (not empty, null) NBT field.
