### ISSUE TITLE
Handbook icons is wiped out.

### ISSUE THREAD

**Issue by chotke** [ReikaKalseki/Reika_Mods_Issues#2552]
After clicking on ComputerCraft tab in Important Notes section, then ">" button all icons have been erased. It's something like they were shifted to the left. Only restarting the game helped.
![изображение](https://user-images.githubusercontent.com/47343555/83567182-dee4cc00-a529-11ea-8ae6-0d9bd0eabc58.png)

**Comment by chotke** [comment]
It affects RoC, RC, EC and probably CrC handbooks.

**Comment by ReikaKalseki** [comment]
This got fixed in v29.
