### ISSUE TITLE
Creative mode to connect pylon with memory crystal will cause broken pylon

### ISSUE THREAD

**Issue by Mr-CHENmatrix** [ReikaKalseki/Reika_Mods_Issues#2553]
In creativemode, I used memory crystal to connect crystal pylon to the network, and it turned out that pylon can't output any lumen energy. It's not good to breaking the connection node and put it back again. You can only reset pylon by turning on debugtest mode, but there is no such problem in survival mode. It may be a bug

**Comment by ReikaKalseki** [comment]
Was the structure invalid (eg a tree inside it)?

**Comment by Mr-CHENmatrix** [comment]
> Was the structure invalid (eg a tree inside it)?

No, make sure it's not blocked by anything. Even after dig a rune and set it, the structure is set up and starts to recharging energy. But after the chunk is reloaded, it won't work. The only permanent solution is to reset pylon with debug mode.
Besides, how to play the puzzle? I've been looking for it for a long time and I don't know what the rules are

**Comment by ReikaKalseki** [comment]
Are you sure it is not just clientside desync?

**Comment by qwahaha** [comment]
This looks like the issue I'm seeing. Pylons that break when I network them because there's snow or Aura Ivy in them.

So, the pylon structure was correct at first, but then these appeared, breaking the pylons and the change wasn't registered until I tried to network the pylons.

I don't know if this is also causing the problem he's seeing.

**Comment by ReikaKalseki** [comment]
There is not a lot I can do about things invalidating the structure later. Not only would checking the structure validity more often be very expensive - remember how many pylons there are - but that would not really make it less bothersome.
