### ISSUE TITLE
Crash while adjusting key configuration

### ISSUE THREAD

**Issue by Mr-CHENmatrix** [ReikaKalseki/Reika_Mods_Issues#2554]
crashreport:
https://paste.ubuntu.com/p/TWW5JwtYfk/
Because of the conflict between chromaticraft's ability keys and Waila's setting keys（numberpad0-3), I want to adjust the key configuration, and then somehow it crashes After the game starts, it crashes. I don't know why

**Comment by OvermindDL1** [comment]
From an initial guess it looks likw a waila key was changed to something outside the range of what lwjgl handles (which isn't much sadly, lwjgl doesn't know about 20 keys on my keyboard...), how did you set the key and what was it set to?  This does look like a waila bug though.

**Comment by Mr-CHENmatrix** [comment]
> From an initial guess it looks likw a waila key was changed to something outside the range of what lwjgl handles (which isn't much sadly, lwjgl doesn't know about 20 keys on my keyboard...), how did you set the key and what was it set to? This does look like a waila bug though.

I forgot, because I didn't see which key it was, and it crashed Is there any way to reset all key settings outside the game?

Edit:Now I've edited it options.txt Solved
