### ISSUE TITLE
Advanced Rocketry worlds prevent the use of turbines & steam grates

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2556]
As stated, any power generation option that is dependent upon a full atmosphere does not work on them period, whether they're in a sealed environ or not. This is _likely_ because Advanced Rocketry does not seal the actual blocks, only the areas bounded by them, so the tiles' locations are not themselves sealed. This has the simple fix of checking not at the tiles' location but at the input or output location, for instance at the front of the gas turbine or the top of the steam grate. Currently the only high-power sources that work on Advanced Rocketry planets would be I believe HP turbines and 268MW sodium solar, making some of the most useful options not useable.

**Comment by ReikaKalseki** [comment]
Done, but now these machines - especially engines - can fail to function if their back is against a wall.
