### ISSUE TITLE
NoClassDefFoundError: Reika/ChromatiCraft/ModInterface/ThaumCraft/ItemManipulatorFocus

### ISSUE THREAD

**Issue by Ieldra2** [ReikaKalseki/Reika_Mods_Issues#2558]
This happens if I add CoFHCore to a mod setup with only ChromatiCraft, Rotarycraft etc.. and NEI:
https://pastebin.com/rSezNyHV (The log also has a handful of other common mods but I got the same result with those removed).

The problem can be removed by adding Thaumcraft, but it probably is not Thaumcraft-related since the modpack Practical Engineering also has CoFHCore and no Thaumcraft, but loads up without a crash.

**Comment by ReikaKalseki** [comment]
That means that either your pack has a copy of the TC API somewhere, or alternatively is blocking my class reparenter which was made to fix exactly this. Or that PE is using a version predating this item, which was only added in v26.

**Comment by Ieldra2** [comment]
The line "ClassNotFoundException: thaumcraft.api.wands.ItemFocusBasic" seems to indicate that I don't have a TC API present (where would it come from anyway), and PE uses the latest version. So how would such a blocking be possible? The only TC-related things I am aware of is that I have TC ores in my Condensed Ores config files even though TC is not (yet) present, but the same applies to a few other mods I haven't yet added. This is a pack I'm creating from scratch, with only a few config files being inherited from an earlier attempt.

**Comment by ReikaKalseki** [comment]
Does it happen with only CC and DAPI?

**Comment by Ieldra2** [comment]
Yes. If I add CoFHCore to a mod setup with only CC and DAPI, the crash happens.

**Comment by ReikaKalseki** [comment]
*Only* CC and DAPI.

**Comment by Ieldra2** [comment]
A mod setup with only CC and DAPI does not crash.

**Comment by ReikaKalseki** [comment]
Then your copy of CoFH is adding a broken copy of the API, or breaking my class reparenter somehow.

**Comment by MeindertKempe** [comment]
I seem to be having the same issue https://pastebin.com/rcJsYaq8.

When I install Thaumcraft the game starts just fine.

**Comment by ReikaKalseki** [comment]
Does removing CoFH fix it for you?

**Comment by MeindertKempe** [comment]
Yes, removing CoFH Core fixes it.

**Comment by ReikaKalseki** [comment]
Then they are breaking the classloading somehow and/or include an old/invalid copy of the TC API.

**Comment by jadenquinn** [comment]
So what you're telling me is I cannot play with both ANY CoFH mods and any of your mods at all? I don't think they still support a version 6-7 years old, you're the only one that can fix it, since you're still developing for 1.7.10. Can you not just add a fix that only activates when CoFH Core (or CoFH mods at all) is/are installed in a pack with DAPI?

And no I can't do it myself, if I could code mods I wouldn't be playing with other people's stuff.

Sorry if this came off as harsh, that's just kinda what it is. I just find it hard to believe at times.

**Comment by ReikaKalseki** [comment]
That is not at all what it says.

**Comment by Cynosphere** [comment]
> Then your copy of CoFH is adding a broken copy of the API, **or breaking my class reparenter somehow.**

CoFHCore is not shipping TC API at all, so it is class reparenting breaking.

Stacktrace points to `cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:94)` which leads to [this try/catch block](https://github.com/CoFH/CoFHCore/blob/1.7.10/src/main/java/cofh/asm/CoFHAccessTransformer.java#L88-L95)

Unless you can come up with a better alternative on your end, I'm just going to rebuild CoFHCore without this block.

**Comment by XCOAnnika** [comment]
I can play without problem with cofh core and with raika mods as long as I have thaumcraft installed

**Comment by XCOAnnika** [comment]
> > Then your copy of CoFH is adding a broken copy of the API, **or breaking my class reparenter somehow.**
> 
> CoFHCore is not shipping TC API at all, so it is class reparenting breaking.
> 
> Stacktrace points to `cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:94)` which leads to [this try/catch block](https://github.com/CoFH/CoFHCore/blob/1.7.10/src/main/java/cofh/asm/CoFHAccessTransformer.java#L88-L95)
> 
> Unless you can come up with a better alternative on your end, I'm just going to rebuild CoFHCore without this block.

So you need thaumctaft

**Comment by Cynosphere** [comment]
> So you need thaumctaft

I didn't say that at all. All I said is CoFHCore is breaking things.

I have tried making a custom version of CoFHCore and it has worked *to an extent.* Since I had to rework the existing build script since they decided to use a stupid ant/gradle hybrid to just be gradle only, I would have to figure out key signing as it doesn't play well with one unsigned mod providing duplicate classes that signed mods provide.

**Comment by jadenquinn** [comment]
> 
> 
> Then they are breaking the classloading somehow and/or include an old/invalid copy of the TC API.

You broke their code since you're one of the only people that still devs for 1.7.10. I think you should fix it.

**Comment by jadenquinn** [comment]
> 
> 
> > Then your copy of CoFH is adding a broken copy of the API, **or breaking my class reparenter somehow.**
> 
> CoFHCore is not shipping TC API at all, so it is class reparenting breaking.
> 
> Stacktrace points to `cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:94)` which leads to [this try/catch block](https://github.com/CoFH/CoFHCore/blob/1.7.10/src/main/java/cofh/asm/CoFHAccessTransformer.java#L88-L95)
> 
> Unless you can come up with a better alternative on your end, I'm just going to rebuild CoFHCore without this block.

If it's not that much to ask, can you please give me/us a fixed jar file so I/others can use it as well, if that's what you're working on doing?

**Comment by ReikaKalseki** [comment]
Multiple people have already stated in multiple issues that you can just remove the old API from the CoFH jar. Instructions work better when you read them.

**Comment by jadenquinn** [comment]
Ah, I looked twice and there weren't any instructions, so I guess I'll just have to trial and error it.

**Comment by RobTheFox** [comment]
I'm not sure how to remove the old api. I can access and edit the jar, but I don't know where the api is.

**Comment by ReikaKalseki** [comment]
In the jar?

**Comment by Ieldra2** [comment]
I suspect the item to remove is cofh/api/modhelpers/ThaumcraftHelper.class, but I don't exactly know.

**Comment by RobTheFox** [comment]
The api from the CoFH jar. If I need to remove that, I would but I don't know where it is.

**Comment by Ieldra2** [comment]
> 
> 
> The api from the CoFH jar. If I need to remove that, I would but I don't know where it is.

Open the COFH jar with 7-zip. Within the .jar, navigate to the path I mentioned in my previous post, there you'll find it. At least that's the only item referencing TC I can find in the .jar. I have no idea if you can safely delete it, though.

**Comment by RobTheFox** [comment]
I'll give it a shot. I'll reply once I try it.

**Comment by RobTheFox** [comment]
I deleted it, still crashes.

**Comment by ReikaKalseki** [comment]
Show me.

**Comment by RobTheFox** [comment]
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderGenerate.func_147423_a(ChunkProviderGenerate.java:269)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_147424_a(ChunkProviderGenerate.java:110)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73154_d(ChunkProviderGenerate.java:212)

-- Chunk to be generated --
Details:
	Location: 0,0
	Position hash: 0
	Generator: RandomLevelSource
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at net.minecraft.world.World.func_147474_b(World.java:329)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 0 Drop: 0
	Level seed: -6800262745540936932
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.world.World.<init>(World.java:260)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1993543840 bytes (1901 MB) / 3666870272 bytes (3497 MB) up to 7516192768 bytes (7168 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: none
	LaunchWrapper: 52 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: mrtjp.relocation.asm.Transformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: fiskfille.tf.asm.transformers.ClassTransformerRenderPlayer
          - Transformer: fiskfille.tf.asm.transformers.ClassTransformerEntity
          - Transformer: fiskfille.tf.asm.transformers.ClassTransformerModelBiped
          - Transformer: fiskfille.tf.asm.transformers.ClassTransformerGuiContainer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: net.malisis.core.asm.MalisisCoreAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: com.brandon3055.brandonscore.asm.ClassTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: Reika.DragonAPI.ASM.InterfaceInjector
          - Transformer: Reika.DragonAPI.ASM.APIStripper
          - Transformer: Reika.DragonAPI.ASM.DragonAPIClassTransformer
          - Transformer: Reika.DragonAPI.ASM.FMLItemBlockPatch
          - Transformer: Reika.DragonAPI.ASM.FluidNamePatch
          - Transformer: Reika.DragonAPI.ASM.DependentMethodStripper
          - Transformer: Reika.DragonAPI.ASM.ClassReparenter
          - Transformer: Reika.DragonAPI.ASM.Profiling.WorldGeneratorProfilingHooks
          - Transformer: Reika.DragonAPI.ASM.Profiling.MapGeneratorProfilingHooks
          - Transformer: Reika.DragonAPI.ASM.Profiling.ChunkInitProfilingHooks
          - Transformer: Reika.DragonAPI.ASM.StructureLootHooks
          - Transformer: Reika.DragonAPI.ASM.SpecialBiomePlacement
          - Transformer: net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
          - Transformer: net.malisis.core.util.chunkblock.ChunkBlockTransformer
          - Transformer: Reika.RotaryCraft.Auxiliary.RotaryASMHandler$ASMExecutor
          - Transformer: Reika.RotaryCraft.Auxiliary.RotaryASMHandler$InterfaceVerifier
          - Transformer: com.enderio.core.common.transform.EnderCoreTransformer
          - Transformer: com.enderio.core.common.transform.EnderCoreTransformerClient
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8064m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 93
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAA	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHIJAA	BuildCraft|Core{7.1.16} [BuildCraft] (buildcraft-7.1.16.jar) 
	UCHIJAA	BuildCraft|Builders{7.1.16} [BC Builders] (buildcraft-7.1.16.jar) 
	UCHIJAA	BuildCraft|Transport{7.1.16} [BC Transport] (buildcraft-7.1.16.jar) 
	UCHIJAA	BuildCraft|Energy{7.1.16} [BC Energy] (buildcraft-7.1.16.jar) 
	UCHIJAA	BuildCraft|Silicon{7.1.16} [BC Silicon] (buildcraft-7.1.16.jar) 
	UCHIJAA	BuildCraft|Robotics{7.1.16} [BC Robotics] (buildcraft-7.1.16.jar) 
	UCHIJAA	BuildCraft|Factory{7.1.16} [BC Factory] (buildcraft-7.1.16.jar) 
	UCHIJAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAA	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJAA	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
	UCHIJAA	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCHIJAA	Mekanism{9.1.1} [Mekanism] (Mekanism-1.7.10-9.1.1.1031.jar) 
	UCHIJAA	DefenseTech{1.0.1} [DefenseTech] (DefenseTech-1.7.10-1.0.1.46.jar) 
	UCHIJAA	DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h.jar) 
	UCHIJAA	endercore{1.7.10-0.2.0.36_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.36_beta.jar) 
	UCHIJAA	EnderIO{1.7.10-2.3.0.425_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.425_beta.jar) 
	UCHIJAA	numina{0.4.0.131} [Numina] (Numina-0.4.0.131.jar) 
	UCHIJAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
	UCHIJAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJAA	powersuits{0.11.0.300} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.300.jar) 
	UCHIJAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAA	DragonAPI{v28a} [DragonAPI] (DragonAPI+1.7.10+V28a.jar) 
	UCHIJAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAA	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimeVoid-Library-1.7.10.jar) 
	UCHIJAA	DynamicTransport{0.1.2.0} [Dynamic Transport] (Dynamic-Transport-Mod-1.7.10.jar) 
	UCHIJAA	EnderStorage{1.4.7.38} [EnderStorage] (EnderStorage-1.7.10-1.4.7.38-universal.jar) 
	UCHIJAA	Steamcraft{0.29.3} [Flaxbeard's Steam Power] (FSP-1.7.10-0.29.3.jar) 
	UCHIJAA	GollumCoreLib{2.0.0} [Gollum Core Lib] (GollumCoreLib-2.0.0-1.7.10.jar) 
	UCHIJAA	hbm{1.0.27 BETA (3802)} [Hbm's Nuclear Tech] (hbm_1.0.27_X3802.jar) 
	UCHIJAA	hexcraft{0.8.5} [HEXCraft] (HEXCraft-1.7.10-0.8.5.jar) 
	UCHIJAA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJAA	KamenRiderCraft2{1.7.10} [Kamen Rider Craft 2 By Kelco_K22] (KamenRiderCraft2-1.7.10-V0.08 TEST VER.jar) 
	UCHIJAA	lasermod{v1.2.0a} [Laser Mod] (LaserMod-1.7.10-v1.2.0a-universal.jar) 
	UCHIJAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJAA	MekanismGenerators{9.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.1.1031.jar) 
	UCHIJAA	MekanismTools{9.1.1} [MekanismTools] (MekanismTools-1.7.10-9.1.1.1031.jar) 
	UCHIJAA	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6.jar) 
	UCHIJAA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAA	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAA	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
	UCHIJAA	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
	UCHIJAA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAA	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
	UCHIJAA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHIJAA	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAA	RotaryCraft{v28a} [RotaryCraft] (RotaryCraft+1.7.10+V28a.jar) 
	UCHIJAA	ReactorCraft{v28a} [ReactorCraft] (ReactorCraft+1.7.10+V28a.jar) 
	UCHIJAA	sonicmod{1.4.0 MC1.7.10} [Sonic the Hedgehog Mod] (Sonic the Hedgehog Mod 1.7.10 V1.4.0.jar) 
	UCHIJAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UCHIJAA	transformers{0.6.3} [Transformers Mod] (TransformersMod-1.7.10-0.6.3.jar) 
	UCHIJAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.2.1-172
	EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (@aeversion@ from DragonAPI+1.7.10+V28a.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[13:13:51] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:354]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Rmoot\Downloads\mmc-stable-win32\MultiMC\instances\Sonic The Hedgehog 1.7.10\minecraft\crash-reports\crash-2021-03-26_13.13.50-server.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.

I added ThaumCraft and it didn't make a difference. It loaded fine, but crashed once I loaded the world.

**Comment by ReikaKalseki** [comment]
That is an entirely different crash, and you cut off most of it on top of that.

**Comment by RobTheFox** [comment]
I could get the rest of it if you need it. I couldn't post all of it here because of the character limit.

**Comment by ReikaKalseki** [comment]
Open a new issue, and use pastebin.

**Comment by RobTheFox** [comment]
Sure thing.

**Comment by lAimBotl** [comment]
https://pastebin.com/X9AFy8MW is what I get even after deleting the thaumcraft api in cofh.

**Comment by lAimBotl** [comment]
https://github.com/TheCBProject/CoFHCore/blob/master/src/main/java/cofh/asm/CoFHAccessTransformer.java#L59-L190

would I be wrong is saying that this is the line?? (I just looked it up based on the crash report at:
"_at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:94)_")
nm I am blind, someone else already showed this lol.

**Comment by RobTheFox** [comment]
Did you use the most recent version? I'm using an unmodified cofh core and it works fine. But, I am using Thaumcraft with it, so I'm not sure if that makes a difference.

**Comment by ReikaKalseki** [comment]
Yes, that makes a difference - TC (for obvious reasons) includes a copy of its own API.

**Comment by RobTheFox** [comment]
So, I'm not sure if you'll be able to have the mods work without TC (unless Reika says otherwise), but I would recommend have TC with it.

**Comment by lAimBotl** [comment]
I did remove thaumcraft once, and it did stop crashing, though idk why, and I cannot reproduce it with a "clean" modpack . . .

**Comment by lAimBotl** [comment]
Just confirmed that my old modpack launches without Thaumcraft and with a unmodified Cofh

CoFHCore-[1.7.10]3.1.4-329.jar
DragonAPI+1.7.10+V29g.jar
ChromatiCraft+1.7.10+V29g.jar

on the modpack I had, that used to have thaumcraft, but currently does not.

full mod list in case it is important:
https://pastebin.com/h1ih7qjy

**Comment by ReikaKalseki** [comment]
Maybe it is an entirely different mod then...

**Comment by lAimBotl** [comment]
I was going to do a slow thing, adding mods 1 by one till it didn't crash, but I was being lazy and just went "I will just add all the mods I "know" won't crash it" and it didn't crash . . . bruh.

When I find out which it is I will put it here: Chisel-2.9.5.11.jar +  Railcraft_1.7.10-9.12.2.0.jar 
(or at least if I removed one or the other it would crash, but why? why these modss!!!!)

(old bigger mod list) :https://pastebin.com/ABnfvL6e

Minimal mod list: https://pastebin.com/6efe8h34

so yeah, just add railcraft + chisel (has to be both based on my testing) and then you won't need thaum. . .

(Looks like railcraft has a thaumcraft thingy too, but idk why you need chisel with it)

**Comment by ReikaKalseki** [comment]
Welcome to classloading hell.

**Comment by MachiavelliSeraphim** [comment]
Just a FYI.
I have a MUCH larger mod list originally running on V26A.
Updated the Reika's mods to V31 and ended up with this crash.
Yes I have COFH mods installed.

All I needed to add was Railcraft, which doesn't bother me too much.
I did not need Chisel at all.

And Yes, this kind of stuff is pure hell to sort out.

**Comment by lAimBotl** [comment]
Is it possible to have a config thing to disable that "part" of Chromaticraft?
(at least as a bandaid, (assuming it is possible of course))

**Comment by ReikaKalseki** [comment]
It is not possible, because the error is that its class exists at all.
