### ISSUE TITLE
Shaft Core not holding charge

### ISSUE THREAD

**Issue by dc2008** [ReikaKalseki/Reika_Mods_Issues#2560]
Shaft cores do not hold a charge on a multiplayer server (modlist at end of post). The shaft core will show a charge while in the Magnetizing Unit, however the charge is lost when the shaft core is removed.
![Screenshot 2_1](https://user-images.githubusercontent.com/59418891/83950873-c7dcfd00-a7fb-11ea-9131-1eb80d3af2b8.png)
![Screenshot 2_2](https://user-images.githubusercontent.com/59418891/83950875-c90e2a00-a7fb-11ea-8d11-fa407049f769.png)

Note that this problem does not occur when using only Reika mods (as per test in creative):

![Screen Shot 1](https://user-images.githubusercontent.com/59418891/83950885-dc20fa00-a7fb-11ea-99ba-a36526041938.png)
![Screen Shot 2](https://user-images.githubusercontent.com/59418891/83950886-dcb99080-a7fb-11ea-8a21-58d57913c8cd.png)

Modlist

mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar)
Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar)
AM2-Preloader{0.0.3} [AMCore] (minecraft.jar)
appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar)
CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar)
ImmibisMicroblocks{59.1.2} [Immibis's Microblocks] (immibis-microblocks-59.1.2.jar)
NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar)
<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar)
AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar)
arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar)
aether_legacy{v1.0.0} [Aether Legacy] (aether_legacy-1.7.10-v1.0.0.jar)
AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0.jar)
algaecraft{1.5.8} [AlgaeCraft] (algaecraft-[1.7.10]1.5.10.jar)
AppleCore{3.1.1} [AppleCore] (AppleCore-mc1.7.10-3.1.1.jar)
appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar)
MovingWorld{1.7.10-1.8.1} [Moving World] (movingworld-1.7.10-1.8.1.jar)
ArchimedesShipsPlus{1.7.10-1.8.1} [Archimedes' Ships Plus] (archimedesshipsplus-1.7.10-1.8.1.jar)
BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar)
Forestry{4.2.16.64} [Forestry for Minecraft] (forestry_1.7.10-4.2.16.64.jar)
BinnieCore{2.0.22.7} [Binnie Core] (binnie-mods-1.7.10-2.0.22.7.jar)
ExtraBees{2.0.22.7} [Extra Bees] (binnie-mods-1.7.10-2.0.22.7.jar)
BuildCraft|Core{7.1.23} [BuildCraft] (buildcraft-7.1.23.jar)
BuildCraft|Energy{7.1.23} [BC Energy] (buildcraft-7.1.23.jar)
AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar)
TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar)
ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar)
CarpentersBlocks{3.3.8.2} [Carpenter's Blocks] (Carpenter's+Blocks+v3.3.8.2+-+MC+1.7.10.jar)
Mystcraft{0.12.3.04} [Mystcraft] (mystcraft-1.7.10-0.12.3.04.jar)
MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar)
ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar)
Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar)
DragonAPI{v26b} [DragonAPI] (DragonAPI+1.7.10+V26b.jar)
ArchiSections{v@MAJOR_VERSION@@MINOR_VERSION@} [ArchiSections] (ArchiSections+1.7.10+V26a.jar)
ArchitectureCraft{1.7.2} [ArchitectureCraft] (ArchitectureCraft-1.7.2-mc1.7.10.jar)
Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar)
Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar)
BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar)
BiblioWoodsBoP{1.7} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.7].jar)
BiblioWoodsForestry{1.5} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.5].jar)
Highlands{2.2.3} [Highlands] (Highlands-1.7.2-v-2.2.3.jar)
BiblioWoodsHighlands{1.2} [BiblioWoods Highlands Edition] (BiblioWoods[Highlands][v1.2].jar)
malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar)
malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar)
BigDoors{1.7.10-1.1.0} [Big Doors] (BigDoors-1.7.10-1.1.0.jar)
Botany{2.0.22.7} [Botany] (binnie-mods-1.7.10-2.0.22.7.jar)
ExtraTrees{2.0.22.7} [Extra Trees] (binnie-mods-1.7.10-2.0.22.7.jar)
Genetics{2.0.22.7} [Genetics] (binnie-mods-1.7.10-2.0.22.7.jar)
Botania{r1.8-249} [Botania] (Botania+r1.8-249.jar)
brewingapi{1.2.0} [Brewing-API] (Brewing-API-1.7.2-1.2.0.jar)
BuildCraft|Transport{7.1.23} [BC Transport] (buildcraft-7.1.23.jar)
BuildCraft|Factory{7.1.23} [BC Factory] (buildcraft-7.1.23.jar)
BuildCraft|Silicon{7.1.23} [BC Silicon] (buildcraft-7.1.23.jar)
BuildCraft|Robotics{7.1.23} [BC Robotics] (buildcraft-7.1.23.jar)
BuildCraft|Builders{7.1.23} [BC Builders] (buildcraft-7.1.23.jar)
ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar)
chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar)
ChromatiCraft{v26b} [ChromatiCraft] (ChromatiCraft+1.7.10+V26b.jar)
climatecontrol{0.8.1} [Climate Control] (ClimateControl-0.8.2.jar)
cookingbook{1.0.140} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.140.jar)
cosmeticarmorreworked{1.7.10-v6b} [CosmeticArmorReworked] (CosmeticArmorReworked-1.7.10-v6b.jar)
CustomChestLoot{2.0.1} [Custom Chest Loot] (CustomChestLoot-1.7.10-2.0.1.jar)
PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.7.10.jar)
props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.7.10.jar)
MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks+MoCreatures+Mod+v6)
RotaryCraft{v26b} [RotaryCraft] (RotaryCraft+1.7.10+V26b.jar)
ElectriCraft{v26a} [ElectriCraft] (ElectriCraft+1.7.10+V26a.jar)
endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar)
EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar)
EnderStorage{1.4.7.38} [EnderStorage] (EnderStorage-1.7.10-1.4.7.38-universal.jar)
exoticbirds{1.0} [Exotic Birds] (Exotic+Birds+1.7.10-1.4.6.jar)
ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar)
ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar)
ExpandedRedstone{v26a} [Expanded Redstone] (ExpandedRedstone+1.7.10+V26a.jar)
fairylights{1.4.0} [Fairy Lights] (fairylights-1.4.0-1.7.10.jar)
GardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar)
GardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar)
GardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar)
GardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar)
guideapi{1.7.10-1.0.1-29} [Guide-API] (Guide-API-1.7.10-1.0.1-29.jar)
ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar)
JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar)
MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar)
Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar)
cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar)
NEIAddons{1.12.15.41} [NEI Addons] (neiaddons-1.12.15.41-mc1.7.10.jar)
NEIAddons|Developer{1.12.15.41} [NEI Addons: Developer Tools] (neiaddons-1.12.15.41-mc1.7.10.jar)
NEIAddons|AppEng{1.12.15.41} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.15.41-mc1.7.10.jar)
NEIAddons|Botany{1.12.15.41} [NEI Addons: Botany] (neiaddons-1.12.15.41-mc1.7.10.jar)
NEIAddons|Forestry{1.12.15.41} [NEI Addons: Forestry] (neiaddons-1.12.15.41-mc1.7.10.jar)
NEIAddons|CraftingTables{1.12.15.41} [NEI Addons: Crafting Tables] (neiaddons-1.12.15.41-mc1.7.10.jar)
NEIAddons|ExNihilo{1.12.15.41} [NEI Addons: Ex Nihilo] (neiaddons-1.12.15.41-mc1.7.10.jar)
neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar)
recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar)
NOVA{2015-10-09} [NOVA] (NOVA-2015-10-09-universal.jar)
harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's+HarvestCraft+1.7.10Lb.jar)
plantmegapack{4.33} [Plant Mega Pack] (plantmegapack-4.33-1.7.10-1492.jar)
ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar)
ReactorCraft{v26b} [ReactorCraft] (ReactorCraft+1.7.10+V26b.jar)
AS_Ruins{15.4} [Ruins Spawning System] (Ruins-1.7.10.jar)
Sanguimancy{1.7.10-1.1.9-35} [Sanguimancy] (Sanguimancy-1.7.10-1.1.9-35.jar)
secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar)
weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar)
wildmobsmod{1.2} [Wild Mobs] (WildMobs-1.7.10-1.3.2.jar)
witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar)
McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
HungerOverhaul{1.7.10-1.0.0.jenkins104} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jenkins104.jar)
JustAnotherSpawner{0.17.5} [Just Another Spawner] (JustAnotherSpawner-0.17.5.jar)
ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)

**Comment by ReikaKalseki** [comment]
If it does not happen with only RC, it is not my doing. Something is probably f@$%ing with NBT of held items.
