### ISSUE TITLE
[Rotarycraft] Breaking refrigeration unit that contains liquid nitrogen should hurt players.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2561]
![2020-06-07_02 03 49](https://user-images.githubusercontent.com/62176592/83951363-91d36380-a863-11ea-97b1-247eec1dd50f.png)

Breaking a refrigeration unit that contains liquid nitrogen in the tank should hurt players, this is to emulate that rapidly releasing liquid nitrogen will cause freeze burns injury like in real life. The amount of damage dealt to player's hearts should be up to your discretion that you deem appropriate.
For more information: https://www.ccohs.ca/oshanswers/prevention/cryogens.html

However if the player is wearing bedrock armor, it should not deal any damage.

**Comment by chotke** [comment]
Rly?... what a bug

**Comment by ReikaKalseki** [comment]
Done.
