### ISSUE TITLE
Wrong texture for GeoStrata stair and slab "Connected" variants

### ISSUE THREAD

**Issue by HellsingDarge** [ReikaKalseki/Reika_Mods_Issues#2564]
ie if you craft "Connected Marble" into stair or slab, the texture will be that of smooth marble instead of Connected
Also affects Connected 2 variant

**Comment by ReikaKalseki** [comment]
That is because the connected texture system uses a custom renderer to work, something not compatible with the vanilla stair/slab renderer.

**Comment by HellsingDarge** [comment]
Could they at least have right texture without ability to connect?

**Comment by ReikaKalseki** [comment]
That is not a texture - that is part of the connected renderer.
