### ISSUE TITLE
[ElectriCraft] Fuse not being rendered correctly through transparent blocks

### ISSUE THREAD

**Issue by pablode** [ReikaKalseki/Reika_Mods_Issues#2565]
![2020-06-07_12 48 27](https://user-images.githubusercontent.com/3663466/83967188-90d01f80-a8bf-11ea-9413-321381e20f6a.png)

This issue also exists when looking through water.

**Comment by ReikaKalseki** [comment]
This is a render pass thing, with no way around it.

**Comment by OvermindDL1** [comment]
Why would a fuse need to be on the transparent pass?  The masked pass should be correct for it?

**Comment by ReikaKalseki** [comment]
It has transparency in it.

**Comment by OvermindDL1** [comment]
Why not use masking though?  Transparency would work fine though if it were moved to a sorted transparency stage but that requires changing your rendering a bit and thus is a lot more work.

**Comment by ReikaKalseki** [comment]
???
