### ISSUE TITLE
[ReactorCraft] [v26b] Undetermined trigger causes turbines to output 9-10 times the power they should, on world reload, in set chunks.

### ISSUE THREAD

**Issue by Vectrobe** [ReikaKalseki/Reika_Mods_Issues#2567]
For, a not yet known, reason in a test world where I was testing the pebble bed reactor, a specific chunk of turbines will emit over 900MW of power from standard steam, as opposed to their normal 100-110MW, but specifically after the world has been closed and reloaded. Destroying and re-building the turbines fixes them until the next reload.

There's two significant factors that may cause the effect;
 - the turbines cross over a chunk boarder along their length, of which the turbine suffering from this have their base in the same chunk of that of the heat exchanger and pebble reactor
 - the other end chunk of these turbines, had a multiblock generator explode within the chunk. The cause of the explosion is presumed to be breaking a block of it while it was operating, although it may also instead have blown up from a turbine suddenly emitting too much power.

Note that the rad/s is consistently 65536 via the handheld angular transducer, of which is one value above the maximum of a 2-byte integer. The torque on the other hand is about double what it should be, although 7knm torque with 65kr/s is enough to violently explode the electricraft generator, unless a TA shaft is used as a fuse.

**Comment by Vectrobe** [comment]
![Screenshot_19](https://user-images.githubusercontent.com/3912867/83970046-bccabf80-a916-11ea-94c5-398ff537152f.png)

**Comment by Vectrobe** [comment]
... apparently rebuilding the turbines from scratch in the chunk, still maintains their over-production...

**Comment by Vectrobe** [comment]
... I also somehow triggered the affected turbine chunks to be moved over one, of which so happens to be the chunk that I built a new multiblock generator. The old affected chunk seems to now not be affected...?

**Comment by tiny-maple** [comment]
Aren't you using 5 turbines, shouldn't they give you 900MW instead of 110MW?

**Comment by Vectrobe** [comment]
are you supposed to get 900MW from a full row of 5? I only remember being able to get 100-ish. The HP turbines on the other hand do way more, but need a higher steam pressure.

**Comment by rkane31174** [comment]
I'm basically certain that a full row of 5 standard turbines should produce about 900MW from standard steam. If they produce less, it's either because of insufficient steam, insufficient lubricant, damage to the turbine, or any combination thereof.

**Comment by tiny-maple** [comment]
I have 6 turbines running at 900MW each, each turbine stack is built to 5 blocks. You may want to check your set up again.

**Comment by rkane31174** [comment]
To clarify: when I said "a full row of 5 standard turbines", I meant "one standard turbine that's 5 blocks long". I realize my choice of words was rather poor and apologize for any confusion.

**Comment by Vectrobe** [comment]
Alright so yea, it appears that the issue is with the steam grates, they seem to desync at random, be it when built or when the server/world reloads.

It desyncs very often when the grate is only one block below the turbine (one steam block flashing), but can also desync when two blocks below. There's over 3000mB of steam in the pipes.

**Comment by Skyler-Altol** [comment]
It should also be pointed out that turbines have their own ElectriCraft generator, and the regular Induction Generator has been explicitly coded to explode when used with normal turbine power outputs (which as others have said, is ~900MW or so with a fully built one). Also, based on your screenshot, I'd say the other turbine is suffering from space issues. The models are literally overlapping in some bits. Try spacing out the turbines a bit more, give at least a 5 block width for each turbine. (I can't recall the specific space requirements from the code).

But I can definitively say as someone that has been playing RoC for many, many years, 110 MW is *not* normal turbine level power.
