### ISSUE TITLE
Crash when breaking pistons in tape puzzle

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2569]
Breaking the pistons and telling to it play crashes the game
(I know I aint supposed to break them, but I was curious lol).

https://pastebin.com/9GPfinab

**Comment by tiny-maple** [comment]
I had this crash too, it was certainly surprising to see that we are able to break the piston.

**Comment by ReikaKalseki** [comment]
How did you even get at the pistons to break them?

**Comment by tiny-maple** [comment]
You repeatably punch the glass, and the glass is not able to be replaced faster than you breaking the piston during the small period of time which there is an air gap.

This is easier to pull off when you have haste 3 pendant with a efficiency 5 bedrock pickaxe. Instant mine the piston.

**Comment by ReikaKalseki** [comment]
...Replaced? The glass is unbreakable.

**Comment by tiny-maple** [comment]
![2020-04-20_19 23 13](https://user-images.githubusercontent.com/62176592/88421511-46791280-ce1b-11ea-924a-cdd6b4a210a2.png)

Hold on, the glass I meant is not shielding glass, but the color filter shown in this picture, which i have highlighted in yellow. With haste 3+Efficiency 5, its possible to glitch it by spamming the pickaxe to the color filter, breaking the piston

**Comment by OvermindDL1** [comment]
In other words the glass is unbreakable on server, but not client, which allows it to be gotten through just barely fast enough with a super fast pickaxe to be able to break inside it.

**Comment by tiny-maple** [comment]
> In other words the glass is unbreakable on server, but not client

You made me try replicating this by hosting on server, and it's unbreakable. o.o

**Comment by OvermindDL1** [comment]
> and it's unbreakable. o.o

Aaaaand that implies that it's only breakable on the SP client, so that implies that a `world` variable is leaking cross the internal server/client boundary again.  Really need to look over these mods to prevent that from happening.  Thanks for checking that, Reika mainly just checks things in MP so he wouldn't have seen it in SP.

**Comment by ReikaKalseki** [comment]
Overmind you are wrong on every count. One, the testing for all of this was done exclusively in singleplayer, i.e. my dev environment. Two, there is no variable involved; "client being able to break a thing before the server blocks it" is a pretty standard behavior seen in a lot of conditionally-unbreakable blocks; the game code for the client has a lot less of the checks the server side does, and this has nothing to do with mod code.

**Comment by ReikaKalseki** [comment]
I am going to have a hard time fixing this without ASMing into the piston block to make it completely unbreakable in the dimension...

**Comment by OvermindDL1** [comment]
Client being able to break a thing before the server blocks it makes it so players think they can do something that they actually can't, you are tricking them.  The server should definitely perform the same check however.  And why do you need to ASM in to it, there's a block edit hook in forge that you can cancel to prevent replacement.

**Comment by ReikaKalseki** [comment]
> Client being able to break a thing before the server blocks it makes it so players think they can do something that they actually can't, you are tricking them.

That is just how the game code works and always has. A lot of the various methods and hooks are simply skipped by the client.

> And why do you need to ASM in to it, there's a block edit hook in forge that you can cancel to prevent replacement.

That is one of those things that only fires serverside, and does not prevent the client from making it appear to disappear.

**Comment by OvermindDL1** [comment]
> That is just how the game code works and always has. A lot of the various methods and hooks are simply skipped by the client.

The issue is that you don't replace it fast enough on the client, you are waiting for the server to deny the change first, meaning that network roundtrip time on a potentially slow server could make it multiple seconds before it updates, at which point a user could have 'transported' through a solid wall.  It's good to perform replacement checks on the client as well so they are replaced the same tick.

> That is one of those things that only fires serverside, and does not prevent the client from making it appear to disappear.

That would prevent a user from breaking any disallowed block, even if they do break through a single layer of glass to hit a piston quickly, and since OP was about to break the piston then that means that the piston changes weren't disallowed.

**Comment by ReikaKalseki** [comment]
> The issue is that you don't replace it fast enough on the client, you are waiting for the server to deny the change first, meaning that network roundtrip time on a potentially slow server could make it multiple seconds before it updates, at which point a user could have 'transported' through a solid wall. It's good to perform replacement checks on the client as well so they are replaced the same tick.

I do not replace *anything*; that is my entire point. The client just goes ahead and removes the block from the rendering (and from the raytrace calculations), and then only when it gets back from the server that this should not have been done does it undo it. At no point am I involved in the process except for telling the game that the removal should fail, something *only* the server even checks.

> That would prevent a user from breaking any disallowed block, even if they do break through a single layer of glass to hit a piston quickly, and since OP was about to break the piston then that means that the piston changes weren't disallowed.

Also only on the server, and thus they will still be able to crash their client.

**Comment by OvermindDL1** [comment]
Is not `Reika.DragonAPI.Libraries.World.ReikaBlockHelper.extendPiston(ReikaBlockHelper.java:501)` run only on the server?  It would seem odd if it were on the client in that case.  Although it is odd to be unconditionally casting a block to a Piston type without actually checking for validity first.

**Comment by ReikaKalseki** [comment]
OK, all the logic is now properly serverside only.

**Comment by cetirizinehydrochloride** [comment]
![2024-12-29_02 07 47](https://github.com/user-attachments/assets/300318ac-2532-40d2-bcdf-7de3ca3ae284)
Is this puzzle bricked? Was poking around with my pickaxe and mined out the piston. No crash occured.
CC v33a
Self hosted private server.
