### ISSUE TITLE
[Chromaticraft V26b] Creating blocks out of nothing using linear construction

### ISSUE THREAD

**Issue by Tennun** [ReikaKalseki/Reika_Mods_Issues#2570]
Using linear construction with 1 block creates 2 instead and doesn't consume the block itself. After this, the block can be placed infinitely, but you won't be able to pick up same blocks. Dropping the infinite block will delete it and you'll be able to take all the blocks you've just placed. Here's a video showing this bug to make it more clear :
https://youtu.be/x95tZXW6Ujc

**Comment by ReikaKalseki** [comment]
Hopefully fixed.
