### ISSUE TITLE
[ReC] HP Turbines need too much steam to spin up

### ISSUE THREAD

**Issue by Thorinair** [ReikaKalseki/Reika_Mods_Issues#2571]
The High Pressure Turbines still seem to be broken in the new version. I have made sure that they are fed with 100% pure FUSION steam, tried various amounts, from around 600 up to 1600+ m3. As soon as the steam line is connected, the amount drops by a huge amount proportionate to the amount in steam lines (around 500 when at 1600) and is permanently lost to the turbine. The turbine begins consuming large amounts of it, but is not doing anything.

Some pics from my testing:
![image](https://user-images.githubusercontent.com/7534126/84076665-7a68b780-a9d6-11ea-9872-d78d3705d396.png)
![image](https://user-images.githubusercontent.com/7534126/84076683-818fc580-a9d6-11ea-9e80-b29957f73051.png)

One single time, it helped to break all the center turbine blocks and replace them. That allowed the turbine to work until I have stopped it. After it was stopped once, it no longer worked.

The issue still seems to be a duplicate of now closed #2372.

**Comment by Thorinair** [comment]
I was able to start the HPT after I have let steam reach a very high value, we are talking around 12k+ m3. Is there some official amount actually necessary to start the HPT? Such an info would help when designing a reactor.

**Comment by ReikaKalseki** [comment]
That is too much.

**Comment by Thorinair** [comment]
Keep in mind that I haven’t yet had time to try any values between 1600 and 12k, so I do not know if it may start up at something as low as 2000.

**Comment by Thorinair** [comment]
Here is a bit of an update. I have done a setup like on the picture below and all steam measurements were done on the block just before the pump:
![image](https://user-images.githubusercontent.com/7534126/84281577-08f54a00-ab39-11ea-8a36-b49814311903.png)

The pump is powered by 1 hydrokinetic engine, geared in such a way that it transfers all torque into speed. For steam values below 4300 m3, whenever I would turn the hydro on so that the pump works, it would transfer only a small amount of steam over, nothing special, maybe 50% of the amount measured in a single steam pipe, and ofc the turbine wouldn't spin.

Once it was over a certain treshold (3000 m3 didnt work, but 4300 did), there was a MASSIVE rush of steam as soon as I turned on the pump and the turbine turned on. As you can see, the amount of steam on the turbine side is over 330k!
![image](https://user-images.githubusercontent.com/7534126/84281991-815c0b00-ab39-11ea-97a4-69b7350374fb.png)

Removing the pump and placing a normal steam pipe instead lets the steam rush back, but it feels like the overall amount is bigger than before.
![image](https://user-images.githubusercontent.com/7534126/84282121-a9e40500-ab39-11ea-8fa5-1b7071d0e48d.png)

That said, there is something VERY weird going on with steam pipes in general, not necessarily the turbine, as the pump seems to be broken as well.

**Comment by Thorinair** [comment]
Using only 4 DC engines is also enough to get the pump going enough to start the turbine. In fact it will also fill the pipe behind it with hundreds of thousands of steam. The only caveat in all of these: There has to be at least 4000 m3 of steam in the pipe before the pump. And no, those 4000 m3 on their own won't be able to start the turbine.
![image](https://user-images.githubusercontent.com/7534126/84287400-25e14b80-ab40-11ea-9b74-ac2290c31d8c.png)
![image](https://user-images.githubusercontent.com/7534126/84287417-2c6fc300-ab40-11ea-883f-2909423592ef.png)

EDIT: Here is the output from the pump with same setup when there was only 3000 m3 of steam before the pump (and going down by hundreds per second):
![image](https://user-images.githubusercontent.com/7534126/84288159-1c0c1800-ab41-11ea-92e5-2b447c255538.png)

**Comment by ReikaKalseki** [comment]
OK, I adjusted the numbers.
