### ISSUE TITLE
[RotaryCraft] Machine NullPointerExceptions

### ISSUE THREAD

**Issue by pablode** [ReikaKalseki/Reika_Mods_Issues#2573]
Every time I right-click a grinder with a _minecraft:torch_ in the hand, an internal exception is thrown and the player is kicked. I think this can be fixed by [adding a null-check at this line](https://github.com/ReikaKalseki/DragonAPI/blob/19c31bdf8abed120e9d4b6a9581ed569ee0a3137/Base/BlockTEBase.java#L91).

Crash Log: https://pastebin.com/xMN5NFwD

EDIT: It happens with every RotaryCraft machine

**Comment by ReikaKalseki** [comment]
There should never *ever* be a null TE for that block. Just null-checking is covering up a far more serious issue.

**Comment by pablode** [comment]
You're right, I'm pretty sure this is an Enviromine bug: https://github.com/EnviroMine/EnviroMine-1.7/issues/184.
