### ISSUE TITLE
[DragonApi] DragonAPI registration Exception:

### ISSUE THREAD

**Issue by Nemo-Oceansoul** [ReikaKalseki/Reika_Mods_Issues#2574]
Just finished downloading minecraft on a new pc, popped in a couple of mods and keep getting error/crash reports like this https://pastebin.com/Z7GBKkgY

I have attempted to load forge with only dragon api installed. 

I have also tried loading it with just optifine amd dragonapi cause i fogured id check if that could be a reason.

So far every time invariably minecraft crashes before finishing loading at approximately the same point in time . Im unsure what else there is. I also posted this to the minecraft forums, but i figured it wouldnt hurt to toss it on here as well.

**Comment by Nemo-Oceansoul** [comment]
so an update: i downloaded Java 7 update 80, thinking that could be the issue cause i was originally using minecrafts default javaw file. now i get this when i try to run minecraft with JUST DragonAPI.

https://pastebin.com/nsEwcs30

note: i am downloading from curseforge.

**Comment by ReikaKalseki** [comment]
Are you using some sort of tool or something to download? The file is getting damaged, and the filename using "+" for spaces is consistent with that.

**Comment by Nemo-Oceansoul** [comment]
im just downloading from the curseforge linked on your google sites page... ive tried multiple times to redownload the file... so its kinda weird. i can try again though. im wondering if maybe my pc randomly drops a bit or something occasionally when i download stuff.

tried again and apparently its being saved with the +'s so... i wonder if the download link is broken. also interestingly: almost all of your other mods exhibit the "+" in the names. interestingly: the only other mods with "+'s" in the name are 2 of Pam's mods.

for reference: the file names im getting outside of dragonapi with "+"'s are: ArchiSections+1.7.10+v26a, ChromatiCraft+1.7.10+V26b, ElectriCraft+1.7.10+V26a, ReactorCraft+1.7.10+V26b, RotaryCraft+1.7.10+V26b, TreeClimbing+1.7.10+V26a, and VoidMonster+1.7.10+V26a

**Comment by Nemo-Oceansoul** [comment]
im curious: is it possible the files have gotten damaged when you uploaded them?

im gonna try installing via twitch app. will let you know what happens.

**Comment by Nemo-Oceansoul** [comment]
So downloading off twitch launcher is fine, trying it from chrome/firefox/etc even on mobile seems to corrupt it on myend.... idk how.

Uhh nvm, after taking oh 4 hours to load the twitch launcher downloaded file which doesnt appear to have the “+”’s in its name (hence the closing of the issue) still gives same error...

**Comment by Nemo-Oceansoul** [comment]
just in case, heres the error log i get when i run JUST dragon api alone in minecraft as of a few minutes ago. it seems something related to shaders not being linked or _something_ idk.

https://pastebin.com/5iWayVtK

**Comment by ReikaKalseki** [comment]
That error is probably unrelated and usually indicates something wrong with your graphics system.

**Comment by Nemo-Oceansoul** [comment]
any ideas on how to fix,  cause everything is up to date on my end.

edit: it seems to be related to my graphics card. its about 10~ years old so it doesnt surprise me. but still dissapointing i cant enjoy one of my favorite mods again. thank you for taking the time out of your day in helping me out with this and please. keep up the awesome work =D
