### ISSUE TITLE
[Chromaticraft V26b] Repeater networks constantly unlinking

### ISSUE THREAD

**Issue by nicholasandrzej** [ReikaKalseki/Reika_Mods_Issues#2575]
Using the indicated number/text from the elemental manipulator, I find myself repeatedly unable to connect all colors to my casting complex. When I follow a line of one color to the pylon, it triggers a successful connection sound effect and immediately the rest of the line sees the pylon again. However upon running down one line, another previously working line will have ceased to work. Additionally (hesitant to say because it may be my fault for having a bad gpu), I get crashes specifically when I check repeaters near the end of a line due to a rendering error. This happens with or without optifine, I am using ordinary chunk loading.

**Comment by tiny-maple** [comment]
![2020-05-03_14 37 48](https://user-images.githubusercontent.com/62176592/84353814-65687000-abf2-11ea-988a-7516b5a4118b.png)
Do you have a render crash report? I can render this with either an aged GPU HD7870 or intel integrated graphics. I do not chunkload any of the pylons too

**Comment by nicholasandrzej** [comment]
I'm not really concerned about the render issue, it only happens when I click on a repeater with the elemental manipulator (if it happens). I'll post a crash report sometime soon, and I should not that I have no problems whatsoever rendering that, that's just what the crash is labelled as. I'm pointing out the connection difficulties because while my instance of CrC is in a modpack, it worked until I updated CrC (no other mods updated other than the rest of Reika's mods that I have installed). It's made it impossible to recreate my past progress since I cannot progress past the casting complex, you only get the progression when it's all linked/when you craft something I think.

**Comment by nicholasandrzej** [comment]
Here is one of them:
[crash-2020-06-10_17.49.14-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4765014/crash-2020-06-10_17.49.14-client.txt)

**Comment by nicholasandrzej** [comment]
Same crash without optifine:
[crash-2020-06-11_10.39.14-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4765517/crash-2020-06-11_10.39.14-client.txt)

**Comment by nicholasandrzej** [comment]
I got really close this time, I seem to have gotten all 16 colors to link to the table - as soon as I went around the table to check it crashed again. I recall an old but similar bug report saying that these issues disappear on a dedicated server, it is true that while on a server I never experience the issue and I'm currently on SSP.

Upon reloading the world after every crash/exit, about half of the colors unlink.

**Comment by tiny-maple** [comment]
Would be nice if you post the crashlog on pastebin

**Comment by Folanlron** [comment]
It's been this way for awhile, the CME problem via Singleplayer has been a long standing issue.

**Comment by tiny-maple** [comment]
#2439 
I took @OvermindDL1 suggestion to move to multiplayer and I no longer experience any CME throw or any more odd bugs that persist in singleplayer. I do not believe there will be a fix for this anytime soon, so just setup a multiplayer and shift your world over.

**Comment by nicholasandrzej** [comment]
Probably not the right place to ask, but do you have any recommended service/setup for MP?

**Comment by OvermindDL1** [comment]
I just take my same client directory in full and copy it somewhere near, put the server jar and mcforge thing in there, and just run it (config settings and all too).  Don't forget routine backups!

**Comment by Folanlron** [comment]
not interested in starting a server every time I wanna play a game for a few hours,

If I wanted too play on a server I'd just play more FF14 not Minecraft.

**Comment by tiny-maple** [comment]
@Folanlron 
>not interested in starting a server every time I wanna play a game for a few hours,

If that is your gaming need then just don't install Chromaticraft in your modpack and you're good to play.

**Comment by nicholasandrzej** [comment]
https://pastebin.com/f0Axu3Pa - with optifine
https://pastebin.com/e713GtvW - without optifine
I haven't used pastebin before, I hope this is what you wanted.

**Comment by tiny-maple** [comment]
>I haven't used pastebin before, I hope this is what you wanted.

doesn't matter if optifine is installed or not. Just shift your world to MP and you'll be fine

**Comment by nicholasandrzej** [comment]
well thanks for your help, I got a server up and running and it works at least!

**Comment by ReikaKalseki** [comment]
#1100
