### ISSUE TITLE
[Rotarycraft] Blast furnance leave one item function do not work for certain recipes.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2576]
![2020-06-12_00 19 46](https://user-images.githubusercontent.com/62176592/84412953-907ab000-ac42-11ea-9715-1e572e963d28.png)
![2020-06-12_00 21 24](https://user-images.githubusercontent.com/62176592/84413061-b1430580-ac42-11ea-8ad6-87e5b7da7101.png)
In this example, using egg to make quicklime recipe inside blast furnance cannot work with 'leave one item' function, and making automation for ammonia a little more tedious. While recipes like high temperature combustor and TRISO fuel pellets have been verified to be automated using leave one item function,, I believe there may be an oversight in some of the blast furnace recipes.

**Comment by ReikaKalseki** [comment]
Fixed. It was in fact the "crafting type" recipes being compressed into a list of their items, and thus not correctly remembering which slots they use.
