### ISSUE TITLE
Unable to craft crystal repeater 

### ISSUE THREAD

**Issue by ThomasDennisSp** [ReikaKalseki/Reika_Mods_Issues#2577]
![2020-06-13_16 03 50](https://user-images.githubusercontent.com/61876687/84570837-28d27b00-ad90-11ea-929f-92a8145fa324.png)
![2020-06-13_16 06 08](https://user-images.githubusercontent.com/61876687/84570839-2a9c3e80-ad90-11ea-93be-c41abe4d0489.png)
I gave me 16 for the next level because in an older version that fixed it but im still unable to craft them even with the next level. I gave myself all the progression so that I know it isnt that. So Im lost on what to do. And I have all runes in the right place
thx for help

**Comment by tiny-maple** [comment]
Do you have personalized casting runes set up?

**Comment by ThomasDennisSp** [comment]
no what are they? first time hearing

**Comment by tiny-maple** [comment]
You need to set them up to the casting room before you can start crafting the crystal repeater. There should be a page in the lexicon about personalized casting.

**Comment by ThomasDennisSp** [comment]
![2020-06-13_21 23 12](https://user-images.githubusercontent.com/61876687/84577400-1c641780-adbc-11ea-8c58-26f0c933daf3.png)
I found it but i dont understand it

**Comment by tiny-maple** [comment]
You have been placing runes on your casting room based on the recipe. Do the same according to this page.

I didn't know that it takes your player skin as the model.

**Comment by ThomasDennisSp** [comment]
where do i place them?

**Comment by tiny-maple** [comment]
#2403 

Place them according to what the page says. The arrow mean to tell you it is north facing, and each block represent 1 pillar of the casting room.

**Comment by ThomasDennisSp** [comment]
Thank you very much for the help
