### ISSUE TITLE
[Question] Any progress for 1.12?

### ISSUE THREAD

**Issue by whatsapp2** [ReikaKalseki/Reika_Mods_Issues#2579]
First of all, I do not want to sound insistent, much less disrespectful, so I decide to make this clarification.

My question comes because your post on Reddit (about porting your mods to versions greater than 1.8+) has been around for 3 years without any update, and it seems to me that it has already been archived. So I would like to ask, any news about these updates to 1.12.2 (I exemplify this version because it has been a turning point in the "modding" community)? I will gladly await your response

**Comment by chotke** [comment]
No.

**Comment by ReikaKalseki** [comment]
This is not the place for this kind of question, especially ones which have 30 other issues asking the same, all being told the same.
