### ISSUE TITLE
Pressing Page Up key in Chat Window causes crash to desktop

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#258]
http://pastebin.com/uACc6QGp

Unexpected error: java.lang.ClassCastException: net.minecraft.client.entity.EntityClientPlayerMP cannot be cast to net.minecraft.entity.player.EntityPlayerMP

Occurs with latest ChromatiCraft. Simply press T to open the chat window, then press 'page up'. Crashes to desktop with this error.

**Comment by ljfa-ag** [comment]
There was a similar crash: #239 
That one should be fixed in the upcoming version.
