### ISSUE TITLE
random crashes with dragonAPI and DivineRPG mobs

### ISSUE THREAD

**Issue by wasakoki** [ReikaKalseki/Reika_Mods_Issues#2581]
hello, first of all, thank you for updating your mods on CF, i have been having a blast playing these mods after all these years. 

the issue im having is random frequent crashing occurring in my worlds. i cannot find any pattern to it and it happens in every test world i've used so far. (with more or less the same mods) usually i can play about 1 hour before the crash occurs but i've had it happen within 5 minutes of loading up an existing world.

the crash report almost always generates this log: [crash-2020-06-14_19.02.44-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4777457/crash-2020-06-14_19.02.44-client.txt)

however it ONCE did generate this log (line 15):
[crash-2020-06-13_09.21.28-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4777491/crash-2020-06-13_09.21.28-client.txt)

also, feel free to blame the issue on another mod too, i would probably be more than happy to remove it if it fixes my issue.

note: i did find another user with practically almost same issue here (https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2302#issuecomment-578571404), but the issue report has so many other issues that i feel like the specific issue im having was probably buried and forgotten there.

**Comment by wasakoki** [comment]
I looked into my issue more, it appears to be a conflict with fastcraft. who would of known that tweaking a rendering engine that has been heavily modified would cause crashes. my fix to the problem while keeping both mods is changing the following option in the fastcraft.ini config file: `enableFontRendererTweaks = false`

**Comment by ReikaKalseki** [comment]
And that fixes it completely?

**Comment by wasakoki** [comment]
well, I managed to play 3 play sessions of 4-6 hours each without a crash. so, either I was extremely lucky or fastcraft rendering exacerbates the issue. (i pretty sure I was extremely lucky :c ) 1 of the 3 play sessions was without fastcraft at all, which at the end of it did crash at the very end with the same log. 

i think i'm going to gather more information before reopening it as the information i provided right now isn't very helpful

**Comment by OvermindDL1** [comment]
The Font Renderer isn't a particle and doesn't use the particle system at all, so I'm leaning to a red herring?

**Comment by wasakoki** [comment]
ok, i come back with (hopefully) promising information. it is an issue with divineRPG mob particles and dragonAPI. I tested it with rainbours, which have a rainbow particle attached to them. here are some crash logs generated in a test environment with only those two mods loaded:

generic crashlog: [crash-2020-06-23_00.07.06-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4817252/crash-2020-06-23_00.07.06-client.txt)

latest.log (probably useful information starting at line 3312): [fml-client-latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4817281/fml-client-latest.log)

generated files in a "FailedClasses" folder (file extension changed from CLASSDATA to TXT for github's file uploading convenience): 
[Reika.DragonAPI.ModInteract.DeepInteract.FrameBlacklist.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4817259/Reika.DragonAPI.ModInteract.DeepInteract.FrameBlacklist.txt)
[Reika.DragonAPI.ModInteract.DeepInteract.ReikaMystcraftHelper.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4817261/Reika.DragonAPI.ModInteract.DeepInteract.ReikaMystcraftHelper.txt)

i think there are other DRPG mobs with special particles that cause practically the same crash, since i did get this crash log in the past while in a dimension where rainbours have 0% chance of spawning, but i will leave that for another testing day.
please let me know if i can gather/share more information to help you in any way.

slightly unrelated: the fastcraft red herring happened because I lowered the rainbour overworld spawn rate at the same time i messed with fastcraft config, oops :p

**Comment by wasakoki** [comment]
same crash, but with a different mob (twilight demon's projectile particles):

[crash-2020-06-23_09.17.07-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4819977/crash-2020-06-23_09.17.07-client.txt)
[fml-client-latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4819980/fml-client-latest.log)

this crash also generated the same "failedclasses" files, the contents of those files are exactly the same ones i uploaded in my previous comment.

i think i'll leave it at that for now, since i assume you wont need the name of every single mob that creates particle effects to diagnose the problem

**Comment by ReikaKalseki** [comment]
Are they adding particles at a weird time (eg during the render loop)?

**Comment by OvermindDL1** [comment]
> Are they adding particles at a weird time (eg during the render loop)?

According to the stacktrace and a bit of decompiling, it's calling `addEffect` during and inside of its entity `onUpdate` callback of its projectile entity.

**Comment by ReikaKalseki** [comment]
So the normal time then. That should work without issue; it does for every other particle-spawning entity.

**Comment by OvermindDL1** [comment]
From what it looked like yeah, I didn't see any smoking gun from a 2 minute look.

**Comment by brandyyn** [comment]
I got the same crash again, same as you on a new world creation. 
[crash-2020-10-06_02.35.06-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5330934/crash-2020-10-06_02.35.06-client.txt)

**Comment by brandyyn** [comment]
It actually happened twice in a row 
[crash-2020-10-06_03.04.44-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5331037/crash-2020-10-06_03.04.44-client.txt)

**Comment by ReikaKalseki** [comment]
My particle engine has proven itself with more than three (maybe even four) years of use and very few reported crashes (almost all of which are due to mods doing weird things). I am going to write this off as a random one-off.

**Comment by wasakoki** [comment]
i've disabled mobs using particles effects from DRPG and never came across the crash again, so it's not really a concern to me either at this point

**Comment by brandyyn** [comment]
> i've disabled mobs using particles effects from DRPG and never came across the crash again, so it's not really a concern to me either at this point

how did you do that?

**Comment by wasakoki** [comment]
> how did you do that?

i probably should have been more specific, i disabled the mob from spawning by using [bad mobs](https://www.curseforge.com/minecraft/mc-mods/bad-mobs/files/2250741)

**Comment by brandyyn** [comment]
> i probably should have been more specific, i disabled the mob from spawning by using [bad mobs](https://www.curseforge.com/minecraft/mc-mods/bad-mobs/files/2250741)

which mob? the rainbour?

**Comment by brandyyn** [comment]
this still happens btw, still an issue. 
[latest1.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6796306/latest1.txt)

**Comment by brandyyn** [comment]
happened again actually, this time i believe it's from divinerpg sharks
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6796323/latest.log)
