### ISSUE TITLE
[Chromaticraft v26b] Techguns weapons bypass chromaticraft protection beacon

### ISSUE THREAD

**Issue by Juha686** [ReikaKalseki/Reika_Mods_Issues#2582]
Techguns version:
Techguns.beta.1.2 FINAL 1.7.10 version

This is the latest 1.7.10 release. Looks like all guns bypass protection beacon so you can still die. Zombie miners and farmers that melee you dont deal damage as intended, but all gun mobs still deal damage.

I am playing the "SetGameDifficulty Reika" pack but we have manually updated all of your mods to latest versions, and techguns is also on latest 1.7.10 update.

**Comment by ReikaKalseki** [comment]
Do they do their damage in an unusual way?

**Comment by Juha686** [comment]
It seems that theres a small projectile being spawned as the mob fires a gun that causes damage on hit, the 1.7.10 source sadly doesnt seem to be available but the 1.12.2 port just uses `ent.attackEntityFrom(src, dmg);` in `GenericProjectile.java` to deal it's damage. 

I'm not familiar enough with the enviroment to really debug the issue further.

**Comment by ReikaKalseki** [comment]
`attackEntityFrom` is the standard way and will go through all the handlers that the beacon uses. But I need the 1.7.10 implementation - open the jar with some decompiler like Luyten or JDGui.

**Comment by Juha686** [comment]
Contents of `GenericProjectile.java` seem similiar in the decompiled version, in the `onImpact` function of `GenericProjectile.java` there's a `ent.func_70097_a((DamageSource)src, dmg);` call which I assume is the same `ent.attackEntityFrom(src, dmg);`

**Comment by ReikaKalseki** [comment]
Yes, it is. So why then would it bypass the protection? Does it also bypass normal powered armor/thaumic shielding/etc stuff (which also use that event)?

**Comment by Juha686** [comment]
The damage does not bypass thaumcrafts runic shielding. I could not really test other types of shielding as the modpack is a bit limited, so I did not have access to quantum suits etc but runic shielding handles the damage properly

**Comment by ReikaKalseki** [comment]
Then my only guess is that it is something specific to the beacon code, such as the damage being too much for the beacon to block or something failing one of its checks...

**Comment by ReikaKalseki** [comment]
The only checks it has - beyond basic range stuff - is whether it has enough energy to block the damage. Unless the guns are dealing some absurd amount of damage, it should be blocked.

**Comment by Geminiquasar47** [comment]
A lot of techguns weaponry seems to have armor piercing properties or just not work right with certain armors.  For example, Metroid cubed 3 armor seems to get pierced by the weaponry before the armor's energy is depleted.  Hope that info helps.

**Comment by ReikaKalseki** [comment]
They are probably dealing damage in a nonstandard way, possibly specifically to bypass these kinds of protections.
