### ISSUE TITLE
[CRC] [Suggestion] Inertia negation upgrade for floatstone boots

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2583]
eg: when you stop, you stop instantly with no "smooth" slowdown.

**Comment by ReikaKalseki** [comment]
I really fail to see any value in this.

**Comment by lAimBotl** [comment]
It is more convenient imo (also reduces the chances of flying into things you shouldn't fly into)

**Comment by ReikaKalseki** [comment]
How is it more convenient?

**Comment by lAimBotl** [comment]
When placing blocks, especially small blocks (like ender io cables, placing ae2 facades, etc) accurately

**Comment by Barhandar** [comment]
Any accurate positioning, including blocks and manipulating them (i.e. FMP, anything that can be precisely configured like OB Builder), functions _much_ better with no inertia. In general MC's own flight is very terrible for any kind of construction with said inertia, controls reuse (in a 100% PC, originally, game!) and disabling flight on ground touch.

**Comment by ReikaKalseki** [comment]
This is a headache to implement, and I do not see enough value to make it worth it.
