### ISSUE TITLE
[ReactorCraft] Magnetic Ore Finder Block Selection

### ISSUE THREAD

**Issue by pablode** [ReikaKalseki/Reika_Mods_Issues#2584]
![2020-06-16_09 58 53](https://user-images.githubusercontent.com/3663466/84748724-4c2c3e80-afb9-11ea-8842-5d325e9bf4da.png)
I stumbled across the Magnetic Ore Finder and noticed that only a handful of blocks are actually supported. Although there is no handbook entry on it, I'm pretty sure most of EC and ReC ores should get detected.

**Comment by ReikaKalseki** [comment]
Note the name: *Magnetic* Ore Finder. Gems, most metals, and so on are not magnetic.

**Comment by pablode** [comment]
Oh god, I totally missed that! You're right, of course.
