### ISSUE TITLE
[ReactorCraft] Magnetic Ore Finder FOV issues

### ISSUE THREAD

**Issue by pablode** [ReikaKalseki/Reika_Mods_Issues#2585]
![2020-06-16_10 07 22](https://user-images.githubusercontent.com/3663466/84749766-b2fe2780-afba-11ea-9854-84eb2fcc6f0b.png)
When setting the field of view to a non-default value, like 90, ore icons are displaced.

**Comment by ReikaKalseki** [comment]
Is there some relationship between FOV and displacement?

**Comment by pablode** [comment]
Normal (70):
![2020-06-19_20 03 39](https://user-images.githubusercontent.com/3663466/85167068-84a57400-b268-11ea-9132-1b20e099ddf4.png)

90:
![2020-06-19_20 03 54](https://user-images.githubusercontent.com/3663466/85167103-8f600900-b268-11ea-9b69-7e4caf02718f.png)

Quake Pro (110):
![2020-06-19_20 04 08](https://user-images.githubusercontent.com/3663466/85167166-aef73180-b268-11ea-92e3-2c708f535d87.png)

The FOV is retrieved and used for some checks, but it does not affect the 2d coordinates directly: https://github.com/ReikaKalseki/ReactorCraft/blob/e1ea9e00b0477fd5bfe49fdf54615d66102fa531/Auxiliary/IronFinderOverlay.java#L68.

**Comment by ReikaKalseki** [comment]
So the larger the FOV, the further off-center they are. Combined with "does not affect the 2d coordinates directly" it sounds like the positions are what would be correct for default FOV in all cases. Your images seem to imply this as well.

**Comment by ReikaKalseki** [comment]
Fixed.
