### ISSUE TITLE
Game crashes on launch, I think it has to do with my language settings?

### ISSUE THREAD

**Issue by impactwinter** [ReikaKalseki/Reika_Mods_Issues#2586]
here's the crash log:
https://pastebin.com/EQWcwr8n

I couldn't find anyone else with this problem in the open issues but I'm sorry if its already there and I just missed it.

**Comment by ReikaKalseki** [comment]
#2021 #2065 #2105 #2112 #2137 #2167 #2233 #2328 #2519

https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2021#issuecomment-449124477
