### ISSUE TITLE
RotaryCraft Blast Furnace Recipes with a minimum number of items show that amount per stack

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2587]
As said, if a recipes need, say, 4 of an item it wants 4 stacks of 4. It also needs to have 4 stacks of 4 to run but will only consume one item once it runs.
![2020-06-17_12 22 15](https://user-images.githubusercontent.com/40431605/84923466-c55d8b80-b0b6-11ea-907b-efc6e1b8f5c6.png)
![2020-06-17_12 22 19](https://user-images.githubusercontent.com/40431605/84923523-d8705b80-b0b6-11ea-9314-f589b76e4aed.png)
NEI shows the same thing

**Comment by ReikaKalseki** [comment]
I fixed the NEI display, but it works fine for me.
