### ISSUE TITLE
Confused by ElectriCraft Battery Outputs in conjunction with Resistors.

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#2588]
Alright, so to clarify, I was messing around with RotaryCraft's gas turbine and connecting it to ElectriCraft's induction generators. Note: I am using the insulated superconducting wire. The engine produces the specified power of 67.109 MW . I have this power charging an aurora battery. The battery is then outputting power into a resistor set to 10 Amps and then into a new battery. However, because the Battery outputs at 65536 Volts and now the adjusted 10 Amps instead of the default 4096 Amps, it should be outputting less power than the gas turbine is generating, specifically 655.35 KW. 

But when I turn on the battery, it drains really fast into the resistor. The electric meter shows its only outputting 655 KW, but its obviously way more than that as the battery is draining. Is the battery actually outputting its designed 268.43 MW and the rest is dissipated as heat or could this be a bug? I didn't see anything in the handbook that resistors generate waste heat.

![2020-06-17_23 22 21](https://user-images.githubusercontent.com/67085483/84974506-6f5a0980-b0f1-11ea-881a-2d4b09d0378f.png)

![2020-06-17_23 21 45](https://user-images.githubusercontent.com/67085483/84974463-5a7d7600-b0f1-11ea-8b1b-bd44fc328008.png)

**Comment by chotke** [comment]
[Answer](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=30734)

**Comment by ReikaKalseki** [comment]
Battery output is always fixed, regardless of "real" load.
