### ISSUE TITLE
[Rotarycraft] [26b] Gearboxes cannot be dissassembled?

### ISSUE THREAD

**Issue by Vectrobe** [ReikaKalseki/Reika_Mods_Issues#2589]
I made sure the disassembly process works for other machines, but gearboxes specifically seem to not be dissassemble-able, or at least not ones that were previously filled with lubricant that's since been removed.

> craft HSLA or diamond gearbox
> fill it with lube, use it
> empty it, put it in the assembler, push redstone button, nothing happens

I'm guessing it's a regression from the new tier that was added, disassembly recipes referencing the old ID's possibly?

**Comment by ReikaKalseki** [comment]
An NBT mismatch seems more likely. Check their tags.

**Comment by Vectrobe** [comment]
This is the NBT an example HSLA box has when placed;

> [CHAT] Block tile..name (ID 659 Metadata 0) @ x=-56, y=55, z=267
> [CHAT] Tile Entity at this location:
> [CHAT] Tile Entity HSLA Steel 2:1 Gearbox @ DIM0: -56, 55, 267
> [CHAT] Tile Entity Direction Data: 4 of 4
> [CHAT] Additional Data (Meaning differs per machine):

item simply states HSLA 2:1 gearbox, 0% damage 0mB lubricant

**Comment by ReikaKalseki** [comment]
No, item NBT.

**Comment by tiny-maple** [comment]
@ReikaKalseki #2540 the nbt tag you're looking for. They cannot be disassembled on the worktable after being placed in world.

**Comment by Vectrobe** [comment]
I don't think this is a duplicate if it still occurs with fresh gearboxes after the update, or has this been patched for a future update?
(no commit marked)

**Comment by ReikaKalseki** [comment]
The fix has not been released.
