### ISSUE TITLE
Expanded Redstone Diamond Block Breakers causing placement graphics to display

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#259]
http://imgur.com/D3YP8c9

Since updating all mods to the latest v8g versions, an odd graphical glitch with the Expanded Redstone Diamond Block Breakers has appeared. Whenever a block breaker is triggered by redstone signal (regardless of what triggered the redstone signal), machines in the same chunk as the breaker briefly change orientation and display the input/output graphics. These disappear a split second later. I have tried this with and without the Unity texture pack (including reloading competely inbetween tests), so I don't suspect the texture pack.

**Comment by ReikaKalseki** [comment]
This is the "too many block updates per chunk causes NBT saving to fail" bug in vanilla (the same as the "lots of flowing water" and "escaped steam" issues).

Though 12 updates is very low, leading me to wonder if something else is spamming them in your chunk, and that 12 just put it "over the limit".
