### ISSUE TITLE
GPR Custom Colors Still Use Integer Block ID

### ISSUE THREAD

**Issue by voidsong-dragonfly** [ReikaKalseki/Reika_Mods_Issues#2593]
As stated in the title. Here's the offending code: https://github.com/ReikaKalseki/RotaryCraft/blob/c97ee05079e17f85a11e14af3a5c76916b66a2a7/Auxiliary/BlockColorMapper.java#L587

**Comment by ReikaKalseki** [comment]
Fixed. It now uses standard 2- or 3-part colon-spaced naming.
