### ISSUE TITLE
[Chromaticraft] CTD:  when click Charcoal

### ISSUE THREAD

**Issue by m0nkm0nk** [ReikaKalseki/Reika_Mods_Issues#2594]
See pastepin, looks like its checking for all possible logs to make charcoal.
Then points null and give CTD.  Any chance, some check can be code/written in?
Binnies hasnt update for a while.. 

(:

https://pastebin.com/pLefaKD5

**Comment by Ieldra2** [comment]
I wrote a CraftTweaker script to get around this: removed the furnace recipe for charcoal which uses the oredictionary for the wood, and added crafting recipes for the types of wood I had in my pack, minus those that caused a crash, without using oredict references. Here's an example:

furnace.remove(<minecraft:coal:1>);
furnace.addRecipe(<minecraft:coal:1>, <minecraft:log:*>);
furnace.addRecipe(<minecraft:coal:1>, <minecraft:log2:*>);
furnace.addRecipe(<minecraft:coal:1>, <BiomesOPlenty:logs1:*>);
furnace.addRecipe(<minecraft:coal:1>, <BiomesOPlenty:logs2:*>);
furnace.addRecipe(<minecraft:coal:1>, <BiomesOPlenty:logs3:*>);
furnace.addRecipe(<minecraft:coal:1>, <BiomesOPlenty:logs4:*>);
furnace.addRecipe(<minecraft:coal:1>, <Forestry:logs:*>);
furnace.addRecipe(<minecraft:coal:1>, <Thaumcraft:blockMagicalLog:*>);
furnace.addRecipe(<minecraft:coal:1>, <harvestcraft:pamMaple>);
furnace.addRecipe(<minecraft:coal:1>, <harvestcraft:pamPaperbark>);
furnace.addRecipe(<minecraft:coal:1>, <harvestcraft:pamCinnamon>);
furnace.addRecipe(<minecraft:coal:1>, <witchery:witchlog:*>);
furnace.addRecipe(<minecraft:coal:1>, <arsmagica2:WitchwoodLog>);
furnace.addRecipe(<minecraft:coal:1>, <TwilightForest:tile.TFLog:*>);
furnace.addRecipe(<minecraft:coal:1>, <TwilightForest:tile.TFMagicLog:*>);
furnace.addRecipe(<minecraft:coal:1>, <ExtraTrees:log:1>.withTag({meta: 1}));

**Comment by ReikaKalseki** [comment]
This is just one more variant of the thing I added my sanity checker for, around this time in 2016. If mods add items to the OreDict, they need to be able to handle those items being queried or manipulated.

**Comment by HellsingDarge** [comment]
I remember getting this crash with Binnie Mods from CurseForge, although it being for a [different reason](https://paste.ee/p/iGAk7)
It was fixed in 2.0.24 (the one I tested) in [GTNH version](https://github.com/GTNewHorizons/Binnie/releases), future version should also have it fixed
And looking at it further... Relevant commit: ForestryMC/Binnie@87ccfb36c4706f37885d858925528c0e0528a32f

**Comment by m0nkm0nk** [comment]
Thanks all for the answers guys, really appreciate it. 
@HellsingDarge I replaced my version with the GTNH version and it works perfectly without crashing, thanks! :)
