### ISSUE TITLE
[CHROMATICRAFT v26b] missing research "MUSICTRIGGER"?

### ISSUE THREAD

**Issue by antrobot1234** [ReikaKalseki/Reika_Mods_Issues#2596]
i'm trying to figure out how to progress to runecrafting for a while now and I realized with the chromaprog debug command that i'm missing research "BASICCRAFT: MUSICTRIGGER" and I can see a block called "crystal music trigger" as a research note in NEI, but all of the research notes I'm finding now are turning up blank and I can't figure out what to do next? I really don't want to cheat the research progress in, but i'm at a loss of what to actually do. does it have something to do with the crystal orchestra?

**Comment by ReikaKalseki** [comment]
The debug command is not meant for anyone but me, as its output is basically guaranteed to be misunderstood by anyone else, you included.

You are simply missing (very basic) progress.

**Comment by antrobot1234** [comment]
actually, I already figured it out via brute force trial and error of progression. I feel like an indication that you need to find a ruin would help a lot for people who were stuck like i was.

**Comment by ReikaKalseki** [comment]
There *is* such an indication, as of v26.

**Comment by antrobot1234** [comment]
well then I didn't notice it before I found the issue manually. on a related note, I'm fairly certian i was unable to progress past wooden lumen repeaters until i went to the twilight forest (which I assumed would be an optional progression point)
