### ISSUE TITLE
Generate error of Crystal Interference

### ISSUE THREAD

**Issue by Mr-CHENmatrix** [ReikaKalseki/Reika_Mods_Issues#2597]
The crystals in this structure often generate errors, and there are often more types of crystal colors than the level of the level (I have encountered 7 crystals of different colors in the first level...) Even if the number is correct, sometimes they are generated. Crystal will cause no solution without destroying the crystal (crystals of the same color are generated in the same row/column/area), although it can be destroyed and then pass normally, but the initial crystal will lose the initial number of Sudoku significance...

Also, what is the role of the runes on the ground? It seems that it can finish level normally without worrying about it...

I see that many players complain that crystal interference is too hard... (16x16 Sudoku is simply not possible for humans)

**Comment by ReikaKalseki** [comment]
I already know about the "initial crystals" sometimes being wrong, though I thought I fixed that.

> Also, what is the role of the runes on the ground?

Runes?

**Comment by tiny-maple** [comment]
>I already know about the "initial crystals" sometimes being wrong, though I thought I fixed that.

Do you have a screen shot of it generating "initial crystals" correctly? I never encountered a correct generation before.

**Comment by ReikaKalseki** [comment]
No, I mean I fixed the issue in the generation logic.

**Comment by ReikaKalseki** [comment]
#2674
