### ISSUE TITLE
Coal Coke not in Ore Dictionary

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#260]
Immersive Engineering and Railcraft both have their versions of Coal Coke in the OreDict as fuelCoke. RotaryCraft however, does not. I tried adding the ore dictionary assignment manually but...even using F3+H, I am unable to figure out what item name to use. "rotarycraft_item_compacts" is shared by several items, it seems.

IE: https://gyazo.com/cf20048e0940549b820e9077781a44a4
Rail: https://gyazo.com/75d78de0565ff47eadf7812a0a8e4cf3
RoC: https://gyazo.com/7feca09ae4851ad479043a471df6e073

This would also explain why I was unable to use the other two types in the Blast Furnace. 
Edit: It seems that RoC coke is also less efficient as fuel than the other two.

**Comment by ljfa-ag** [comment]
You should be able to add only a specific metadata. E.g. with Minetweaker "rotarycraft_item_compacts:8" should work.

**Comment by ReikaKalseki** [comment]
You can only use RC coal coke in the Blast Furnace. This is not a bug and will never change. I will add coke to the OreDict so that other mods can use it.

**Comment by ReikaKalseki** [comment]
Done.
