### ISSUE TITLE
[Reactorcraft] Steam with blank source type past unpowered pump on world reload

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2600]
I was able to get enough steam to start up the turbines yesterday, and sent it through world rifts to the turbines, 
and it worked fine, but I logged in again and now they don't run, probably because the steam type is blank? 

checked by the pumps and only the steam after was unnamed, restoring power fixed it, 
(also apparently the power stopped because rftools shields break conduits/pipes?? bleh)

![2020-06-28_15 13 00](https://user-images.githubusercontent.com/10777735/85956240-9c5cb680-b952-11ea-87d4-aec455d5b848.png)

**Comment by lAimBotl** [comment]
the non hp turbine doesn't care if the source is unnamed so it works fine

**Comment by ReikaKalseki** [comment]
It works fine for me:

![https://i.imgur.com/utAGLjv.png](https://i.imgur.com/utAGLjv.png)

**Comment by lAimBotl** [comment]
I am guessing it is because the steam lines there were disconnected from the boilers steam lines, so it didn't know what made the steam that was in them.

**Comment by ReikaKalseki** [comment]
This has been hopefully fixed once and for all.
