### ISSUE TITLE
[Chromaticraft 26b] progress loss after crash

### ISSUE THREAD

**Issue by antrobot1234** [ReikaKalseki/Reika_Mods_Issues#2601]
[crash-2020-06-28_21.19.27-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4843795/crash-2020-06-28_21.19.27-server.txt)
I had a crash while working with getting pylons setup for the final craft (with creative) and after rebotting my game again, all my progress was reset (everything in the progression tab, as well as the marking of completing tower alpha and tower theta). I kept all my research notes (as I assume those are stored via the book itself via NBT) as well as stored lumens and abilities. I know I can manually mark progress checks with chromaprog and I can force add every progression with maximize, but this has been happening more and more frequently and I don't want to have to either load a backup from up to 30 minutes prior or mess with chromaprog (which i also haven't fully figured out yet). If I can't fix the crash, can you at least give me a way to copy the chromaticraft progress data from the backup to the corrupted reboot (literally nothing was altered besides my progression resetting)

**Comment by lAimBotl** [comment]
"YourWorldName\ChromatiCraft_Data\ProgressionBackup"
Idk if i really used that though, but I do have aromacore that backs up my worlds every hour, 
and I most likely just pulled the crc data from the backup save to the "ded" original save.
(I think that might be in "YourWorldName\ChromatiCraft_Data\ProgressionCache")

**Comment by antrobot1234** [comment]
I tried copying the entirety of the chromatiCraft_data over and it didn't work

**Comment by ReikaKalseki** [comment]
You cannot just copy files; the progress is stored on the player NBT.

And I doubt I can do anything to prevent losses due to save failures, short of a total rewrite on how the data is stored, and in the process breaking every world in existence.
