### ISSUE TITLE
Reika.DragonAPI.Exception.RegistrationException: DRAGONAPI has a registration error:

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#2602]
My game keeps crashing on startup with the same error, been trying to fix it for days now. I really need help, please
here is the link to the latest crash report if it'll help:
[crash-2020-06-29_21.26.12-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4847657/crash-2020-06-29_21.26.12-client.txt)

**Comment by OvermindDL1** [comment]
What GPU do you have, what drivers, and what OGL version does it support (need to see if the log matches)?

**Comment by OvermindDL1** [comment]
Also, it looks like you have Optifine, as that mod breaks a whole lot of things randomly can you try it again without it as a test?

**Comment by ghost** [comment]
only have a CPU, Intel core i5
OGL driver version: 3.2.9704 Forward-Compatible Context
Also I tried opening the game without Optifine, but it still crashes with the same error

**Comment by OvermindDL1** [comment]
Well Minecraft thinks you have this for a GPU:
```java
OpenGL: ATI Mobility Radeon HD 5145     GL version 3.2.9704 Compatibility Profile Context, ATI Technologies Inc.
```
If that's not what you have (and even if you do) you probably need to upgrade your drivers.

**Comment by ghost** [comment]
ok thanks, much appreciated, I'll update and then tell you if it worked
