### ISSUE TITLE
[ReactorCraft] Crash when using itemRender to batch export items

### ISSUE THREAD

**Issue by Mr-CHENmatrix** [ReikaKalseki/Reika_Mods_Issues#2605]
ItemRender is a very useful mod for 3D rendering blocks and item icons. It can export the icons of items in the mod for wiki. The usage is simple: press "[""] "to export 32x and 128x icons respectively, press" I "to export all items and blocks in the game and save them in JSON format. The icons are saved in the exported JSON file in the form of Base64 code.
https://github.com/0999312/Item-Render-Rebirth
At present, it is used in mcmod.cn, a Chinese minecraft mod Encyclopedia with more than 2000 mods.
https://www.mcmod.cn/
But I crashed when I used it to export ReC items......
crashreport:
https://paste.ubuntu.com/p/GP2wZ2SJ4M/

**Comment by MalTeeez** [comment]
Maybe this comes from all textures not being stored in separate files, but rather all in a few ones(1 file for items, blocks, multiblocks)

**Comment by ReikaKalseki** [comment]
No, this is simply that mod requesting invalid metadatas of the block. And my blocks use the standard icon system.

However, that mod will also likely fail with item rendering, because I suspect it assumes they use standard icons.
