### ISSUE TITLE
Expanded Redstone "Ticking Noises"=false --- Does not work anymore

### ISSUE THREAD

**Issue by lee321987** [ReikaKalseki/Reika_Mods_Issues#2607]
Hello.
The option in the config file to silence redstone ticking noises no longer works.

**Comment by ReikaKalseki** [comment]
It is and always has been a server side option. #1867 #2213

**Comment by lee321987** [comment]
I'm sorry, but I don't know what that means.  I'm playing single player at my home.
I thought all I had to do is edit the option "Ticking Noises" in this file:
.minecraft\config\Reika\ExpandedRedstone.cfg

Can anyone please tell me what else I have to do?

**Comment by ReikaKalseki** [comment]
For singleplayer that *is* all you should have to do.

**Comment by lee321987** [comment]
I just deleted all Reika mod config files, and removed all mods except DragonAPI and ExpandedRedstone, and Forge.
I still can't disable the ticking noises...?

Is there some Minecraft option I am using that is making me run as a server in single-player mode?
How would one disable the ticking noises if they were running a server?

**Comment by ReikaKalseki** [comment]
You would disable the option on the server's copy of the configs rather than the client. Obviously, for singleplayer, only one copy exists, and thus that is not at hand here.

**Comment by lee321987** [comment]
I still have this issue.
Can any users please confirm if you can turn off Ticking Noises??
Please.

**Comment by ReikaKalseki** [comment]
I have double checked and all the sound code checks that config.
