### ISSUE TITLE
Shaft Unit crafting glitches

### ISSUE THREAD

**Issue by lee321987** [ReikaKalseki/Reika_Mods_Issues#2609]
NEI does not show the recipes for Shaft Units.
The recipe in the RotaryCraft Handbook is 4 Shaft Units and a Mount (built on the Worktable).
If you craft this recipe it results in a part named "Wood Shaft" [1075:0], but this "Wood Shaft" is not wood, and seems to be a part meant to transmit shaft power in two directions.
Pics attached.

![01 mouse_on_item_in_right-side_grid](https://user-images.githubusercontent.com/18412921/86522853-0c2adf80-be32-11ea-9432-be319aad6f8d.jpg)
![guides_shown_when_block_placed](https://user-images.githubusercontent.com/18412921/86522854-0cc37600-be32-11ea-9a61-523aa323fa54.jpg)
![inside_the_block](https://user-images.githubusercontent.com/18412921/86522855-0d5c0c80-be32-11ea-98bb-b4864b4dbf55.jpg)

**Comment by ReikaKalseki** [comment]
That is the shaft cross, and that is its recipe. The real issue is in its display name.

**Comment by ReikaKalseki** [comment]
Fixed.
