### ISSUE TITLE
World fails to load in DragonAPI version 26b

### ISSUE THREAD

**Issue by MadFrogs1** [ReikaKalseki/Reika_Mods_Issues#2610]
Hello,

I have noticed that DragonAPI version 26b doesn't work on my minecraft setup. When creating a world, the world gets created successfully, however, the only part of the screen that renders is the toolbar and the crosshair. Everything else is black. I tried using an older version of DragonAPI (specifically, version 17c) and it worked perfectly fine. I don't know what's changed between version 17 and version 26, but whatever it is, it seems to have broken my minecraft rendering. If you have any more information on  similar issues, it would help a lot.

Thanks,
MadFrogs

**Comment by MadFrogs1** [comment]
![image](https://user-images.githubusercontent.com/64145059/86627930-01528500-bfc1-11ea-9c7d-432cd737072a.png)

**Comment by MadFrogs1** [comment]
When going into fullscreen, the toolbar and crosshair stop rendering too

**Comment by MadFrogs1** [comment]
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4880728/latest.log)

**Comment by ReikaKalseki** [comment]
#2315 #2495 #2260 #2368 #2440 #2460

**Comment by Jonius7** [comment]
#2368 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2516#issuecomment-633653490 #2606 ("fixes")

> I don't know what's changed between version 17 and version 26,

Since v24 there are new shaders in DragonAPI that are causing these OpenGL 1282 errors...
