### ISSUE TITLE
[ChromatiCraft] Perpetual crashing

### ISSUE THREAD

**Issue by Hiranus** [ReikaKalseki/Reika_Mods_Issues#2612]
https://pastebin.com/k2GWY4tT
Game crashes and refuses to start.

Edit:
As a temporary fix I had to add files mystpages_n.png and mystpages_s.png (copies of mystpages.png) to get my game to work

**Comment by ReikaKalseki** [comment]
This is on their end; they cannot just assume every texture in the game has variants like that.

**Comment by Hiranus** [comment]
But can you fix it on your end? I wont be only one to stumble on this, and you can easily fix it by duplicating mystpages.png file. Its almost 0 work for you.

**Comment by ReikaKalseki** [comment]
I am not going to fill the mod with useless files to work around a simple issue on their end, no.
