### ISSUE TITLE
DragonAPI server crash with Zora No Densha mod.

### ISSUE THREAD

**Issue by Geniu1999** [ReikaKalseki/Reika_Mods_Issues#2619]
Server seams to be crash when i have DragonAPI and Zora No Densha mod on server. On single player works fine. When I remove Zora No Densha or DragonAPI from server everything works.  Any possible fix? (Sorry if my english are not perfect)
[crash-2020-07-22_17.30.31-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4960976/crash-2020-07-22_17.30.31-server.txt)

**Comment by ReikaKalseki** [comment]
You either have mismatches in versions between parts of that mod (or things using its API), or that mod has serious programming errors. The first seems more likely.
