### ISSUE TITLE
ElectriCraft Render Crash

### ISSUE THREAD

**Issue by RoloEdits** [ReikaKalseki/Reika_Mods_Issues#262]
http://pastebin.com/KPD44GTi

I've been getting this crash when entering unexplored areas of my world and have to use mc edit to teleport my self away and after it it fine.

ElectriCraft 1.7.10 V8f

**Comment by ljfa-ag** [comment]
Electricraft ore with metadata 6 shouldn't be happenning I think. Did you maybe use CoFHCore to generate them?

**Comment by RoloEdits** [comment]
No Only Changed Vanilla, Mechanism and the TE Ores.

**Comment by ReikaKalseki** [comment]
Well, something is randomly setting block metadata on the worldgen blocks with no regard as to whether it makes sense or not.

**Comment by RoloEdits** [comment]
OK, thanks for your help.

**Comment by ReikaKalseki** [comment]
Linking to #419 and #342 as they may well have the same root cause.

**Comment by ReikaKalseki** [comment]
[Is Glenn's Gases present](https://github.com/lawremi/PerFabricaAdAstra/issues/56)?
