### ISSUE TITLE
Gatling Gun generates infinite ball bearings

### ISSUE THREAD

**Issue by Acroficer** [ReikaKalseki/Reika_Mods_Issues#2620]
The Gatling Gun, when used, drops far more ball bearing items than it actually fires. I set one up inside my magma cube farm today, partially just to test this turret, as I'd never used it before. I set up a system to collect the fired ball bearings, after realizing they dropped as items, and quickly ended up with an extreme overabundance of ball bearings. I started with 4 stacks of them, and ended up with over 400 stacks in my collection system.

Modlist is here: https://pastebin.com/2yB9Kqq1

**Comment by ReikaKalseki** [comment]
The gatling gun only uses a bearing item about 20% of the item it fires, and those items should be client-only...

**Comment by Acroficer** [comment]
Did some more tests, details here https://imgur.com/a/MUm4KE5

**Comment by OvermindDL1** [comment]
@ReikaKalseki Except when they attack slimes, remember that you have this event hook:
```java
 165   │     @SubscribeEvent(priority=EventPriority.HIGHEST)
 166   │     public void chaosProtection(LivingDropsEvent evt) {
 167   │         if (evt.entity instanceof EntitySlime) {
 168   │             int rounds = evt.entity.getEntityData().getInteger(TileEntityMultiCannon.SLIME_NBT);
 169   │             if (rounds > 0) {
 170   │                 int drop = (int)(rounds/TileEntityMultiCannon.AMMO_PER_SHOT);
 171   │                 while (drop > 0) {
 172   │                     int amt = Math.min(64, drop);
 173   │                     ReikaItemHelper.dropItem(evt.entity, ReikaItemHelper.getSizedItemStack(ItemStacks.ballbearing, amt));
 174   │                     drop -= amt;
 175   │                 }
 176   │             }
 177   │         }
 178   │     }
```

So in short, if it's a slime then it looks up the NBT data on the entity with the key `"embedded_rounds"`, which is set in Entities/EntityGatlingShot.java:232 by just incrementing it by one every time a slime is hit.  So if a slime was hit, say, 3 times then `rounds` above is `3`, so then it does `rounds/AMMO_PER_SHOT`, where `AMMO_PER_SHOT` is `FIRE_RATE/(double)AMMO_RATE`, and those are `1/10`, so it becomes 0.1, so 3/0.1 is 30, converted to integer is still 30.  So then while drop > 0 it makes stacks in stacks of 64 as items, so the duplication is there.

**Comment by ReikaKalseki** [comment]
The real issue is a simple typo. Fixed.
