### ISSUE TITLE
Crash when looking up Recpie for Charcoal [CrC/Crystal Furnace/Binnies Mods]

### ISSUE THREAD

**Issue by Chaoschaot232** [ReikaKalseki/Reika_Mods_Issues#2623]
Normaly, when my client crashes due to recipie look up, it is mostly a failed client render but here it seems to be much more.
I am also unsure if this is only a mod interaction thing because I never have had any problems with this kind of mods together but since CrC (Crystal Furnace) is mentioned in the crash report, I assume that there is maybe a bug between NEI Recipielookup, smth. from Binnies Mods (Log) and the recipies behind the Crystal Furnace.

Full Log: https://paste.ee/p/SGcal
Crash Report only: https://paste.ee/p/WZQkZ#nw0KtvHVxW3Mrq5a2tmEZ3MN4cdeUTzt

Pack depends on FTB Infintiy Evolved and is played only by myself in Singleplayer ;)

**Comment by Ieldra2** [comment]
This has already been reported: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2594
You'll also find a script I've made as a workaround under the linked issue.

**Comment by Chaoschaot232** [comment]
> This has already been reported: #2594
> You'll also find a script I've made as a workaround under the linked issue.

Thanks for your response :)
I'll replace the current version with the GTNHZ Version as it is mentioned there, that it fixes this bug.
