### ISSUE TITLE
[ChromatiCraft] mod compatible bug

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#2624]
The Thaumcraft Infusion Altar cannot recognize the Essentia Jar of ChromatiCraft, nor can the storage bus of thaumicenergistics.

ChromatiCraft+1.7.10+V26b.jar
Thaumcraft-1.7.10-4.2.3.5.jar
thaumicenergistics-1.1.3.0.jar

**Comment by KuroPeach** [comment]
For this, I can only use it like this
![image](https://user-images.githubusercontent.com/19620848/89638301-28f97d80-d8de-11ea-8741-64441cb1a59d.png)

**Comment by ReikaKalseki** [comment]
The essentia jar stores many different aspects, breaking a lot of handling. That said, I have used it with thaumic infusion without issue.
