### ISSUE TITLE
Fertilizer consumes non apatite or bonemeal items

### ISSUE THREAD

**Issue by Arzana** [ReikaKalseki/Reika_Mods_Issues#2625]
The fertilizer will consume the first item in it's inventory no matter if it's a valid fertilizer.
On a smaller note, the handbook states that apatite or bonemeal would work, but apatite itself doesn't work, forestry fertilizer does work. Not certain if it's a mistype or intended as to distinguish the Rotarycraft fertilizer from the Forestry fertilizer.  

Version used: V26b

Steps to reproduce ([Video](https://youtu.be/1zWz2Cs6Lqo)):
1. Add non apatite (fertilizer) or bonemeal in the first slot on the fertilizer (tested with golden sword and apatite forestry item).
2. Add forestry fertilizer to start the machine.

Expected outcome:
Either non-fertilizer items should not be allowed to be placed in the inventory of the machine or non-fertilizer items should not be consumed.

**Comment by ReikaKalseki** [comment]
The fertilizer used to take raw apatite back in 2013 and 2014, because I had no experience with the Forestry fertilizer system. The book was simply never updated.
