### ISSUE TITLE
[ChromatiCraft]Casting Delegate can‘t work，It not push materials to table

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#2626]
Casting Delegate can‘t work，It not push materials to table，like[#2277](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2277)

ChromatiCraft+1.7.10+V26b.jar
appliedenergistics2-rv3-beta-6.jar

![image](https://user-images.githubusercontent.com/19620848/89717669-74e61880-d9eb-11ea-9382-65a6bf4aefd3.png)

**Comment by ReikaKalseki** [comment]
I have never had this issue, assuming it actually had access to the materials.

**Comment by KuroPeach** [comment]
I now know how to use it, so I closed this issue. haha
Need help from other equipment and hope that other players can search for this.
![image](https://user-images.githubusercontent.com/19620848/89868732-df62a880-dbe5-11ea-8854-a07a0f08f0dd.png)
![image](https://user-images.githubusercontent.com/19620848/89868776-f1444b80-dbe5-11ea-8974-863ca7e9dd19.png)
