### ISSUE TITLE
[ChromatiCraft]Casting Delegate crafting bug, when open autocraft with ’Double production skills‘

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#2628]
Casting Delegate crafting bug，when open autocraft with ’Double production skills‘，The world will freeze and pause, and there will be no regular error reports，[sampler stall-report](https://paste.ubuntu.com/p/WcR5YKqQGT/) from 2020-08-12 00:56:07 +0800, 35 threads, stalled for at least **240000 ms**.
![image](https://user-images.githubusercontent.com/19620848/89928469-75c0b980-dc3a-11ea-89ce-df39c5eab596.png)
![QQ图片20200812012821](https://user-images.githubusercontent.com/19620848/89928947-20d17300-dc3b-11ea-9f28-4c91d0905449.png)

**Comment by ReikaKalseki** [comment]
It works fine for me:

![https://i.imgur.com/ds3LSbW.png](https://i.imgur.com/ds3LSbW.png)
![https://i.imgur.com/x2T9toX.png](https://i.imgur.com/x2T9toX.png)


Looking at your log, you probably have an inventory next to it that got stuck processing inventory handling, or an item with an insane amount of NBT on it.
