### ISSUE TITLE
[ChromatiCraft] hey reika，Look at the multi-block structure of voidtrap. @&#%?!@&#%?!

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#2629]
hey reika，Look at the multi-block structure of voidtrap. @&#%?!@&#%?!
![image](https://user-images.githubusercontent.com/19620848/90049229-1aa8c880-dd07-11ea-8a89-42f41185d27c.png)
![image](https://user-images.githubusercontent.com/19620848/90049302-3318e300-dd07-11ea-9ea8-e5a470adacb0.png)

**Comment by KuroPeach** [comment]
There is another problem. When the lumen tree charges the ‘storage crystal charger’, it will take up a considerable amount of network IO, about 200k/s. The upgraded version of the lumen tree is even more exaggerated, so exaggerated that players cannot move in a multiplayer game.

**Comment by ReikaKalseki** [comment]
?

**Comment by KuroPeach** [comment]
The center of this multi-block structure is asymmetrical, and it can’t be seen clearly without magnification

**Comment by KuroPeach** [comment]
Another problem is that the lumen tree will take up considerable network IO when working

**Comment by HellsingDarge** [comment]
And with regards to such "zoomed out"/spacious 2D views, would it be possible to display block name when you hover over it? Would solve quite a lot of pixel counting when you try to decipher the block

**Comment by KuroPeach** [comment]
No, the block name will not be displayed, only the list will display the block name. The asymmetry in the center of this structure I found by zooming in on a screenshot

**Comment by ReikaKalseki** [comment]
I can quite clearly see the differences...

**Comment by HellsingDarge** [comment]
Eh... [No](https://imgur.com/a/vJ8at6p)
For the most part, I do find it _extremly_ difficult to coherently see what block it is without changing GUI scale and/or being 5 cm away from the monitor

**Comment by Shahelion** [comment]
Being able to mouse over the blocks in the 2D view and have a tooltip pop up saying what block it is, would be perfect.

**Comment by ReikaKalseki** [comment]
Done.
![https://i.imgur.com/F5LNJlP.png](https://i.imgur.com/F5LNJlP.png)
