### ISSUE TITLE
Casting delegate can not craft resonance ring.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#263]
When ordering "Resonace Ring" the casting delegate will instead make "Crystalline Stone Beam" because placing the first two blocks of Resonant Ring IS the recipie for Stone Beam, aka it triggers the crafting process before the crafting grid is filled. This will probably also happen any recipies that overlap in this way. (Crystalline Stone Groove 2, ALL rune recipies.... etc)

:p

**Comment by ReikaKalseki** [comment]
Probably fixed, testing now.

**Comment by ReikaKalseki** [comment]
Fixed.
