### ISSUE TITLE
Knowledge entanglement pedestal crashes server

### ISSUE THREAD

**Issue by Lufnar** [ReikaKalseki/Reika_Mods_Issues#2630]
I had a friend stand on the pedestal, right clicked on it and my friend started to float. After a while since nothing seemed to happen i tried to right click on my friend with the manipulator wand and at that moment the server crashed. On server console we found this error log. https://pastebin.com/7gf63cV5 

We have the latest version installed.

**Comment by ReikaKalseki** [comment]
I thought I fixed this...
