### ISSUE TITLE
[Chromaticraft] java.lang.ArrayIndexOutOfBoundsException with Overchanting

### ISSUE THREAD

**Issue by Schadrach** [ReikaKalseki/Reika_Mods_Issues#2631]
When enchanting an item with ChromaticCraft enchants and then using the Overchanting table from Thaumic Bases (https://github.com/Modbder/ThaumicBases) to increase the level of each enchantment on the item by 1, I receive a client crash and the following error:

> java.lang.ArrayIndexOutOfBoundsException: 5
> 	at Reika.ChromatiCraft.Magic.Enchantment.EnchantmentPhasingSequence.getActualDamage(EnchantmentPhasingSequence.java:47)
> 	at Reika.ChromatiCraft.Magic.Enchantment.EnchantmentPhasingSequence.getPenetratingDamage(EnchantmentPhasingSequence.java:51)
> 	at Reika.ChromatiCraft.ChromaticEventManager.applyDamagePhasing(ChromaticEventManager.java:1862)
> 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_385_ChromaticEventManager_applyDamagePhasing_LivingAttackEvent.invoke(.dynamic)
> 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
> 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
> 	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:292)
> 	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:737)
> 	at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:54)
> 	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232)
> 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:406)
> 	at thebetweenlands.forgeevent.BLForgeHooksClient.handlePlayerAttackInput(BLForgeHooksClient.java:40)
> 	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1948)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
> 	at net.minecraft.client.main.Main.main(SourceFile:148)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
>

**Comment by ReikaKalseki** [comment]
Fixed.
