### ISSUE TITLE
Chromaticraft v26b Thaumcraft crash on loading

### ISSUE THREAD

**Issue by madsamjp** [ReikaKalseki/Reika_Mods_Issues#2634]
I get this error when loading minecraft: 

`cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Reika/ChromatiCraft/ModInterface/ThaumCraft/ItemManipulatorFocus`

Same issue as this - https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2522 - except for v26b

Crash log here: https://gist.github.com/madsamjp/93b4b8666387144cef531454e2e14eaf

**Comment by ReikaKalseki** [comment]
The issue you linked explains it.

**Comment by madsamjp** [comment]
> The issue you linked explains it.

Resolving the issue specifically for v26b is not clear from the thread. Should I remove MFR and CofhCore?? Or would adding Thaumcraft to my pack fix the issue (I don't use Thaumcraft).

**Comment by ReikaKalseki** [comment]
Someone is shipping an old TC API. You do not need to remove that mod outright, but you do need to remove the copy of the API from its jar.
