### ISSUE TITLE
[RotaryCraft/DragonAPI] Left with black screen upon loading the world

### ISSUE THREAD

**Issue by pivinx1** [ReikaKalseki/Reika_Mods_Issues#2635]
Hello,

When I load up a new world, I can't see anything, just the quick access bar and the chat, and Minecraft keeps spitting out OpenGL 1282 errors. 
Mods used:
DragonAPI v26b
RotaryCraft v26b
GregTech 5 Unofficial
IndustrialCraft 2 Experimental
Optifine 1.7.10 HD Ultra E7 (I had to use it due to low FPS with only IC2 and GT5U)

See the attached file for what I see.
![2020-09-05_10 37 13](https://user-images.githubusercontent.com/63850629/92301409-0a7db500-ef64-11ea-932b-385d7f63987b.png)

**Comment by MalTeeez** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2606

**Comment by ReikaKalseki** [comment]
#2315 #2495 #2260 #2368 #2440 #2460 #2606 #2610 #2516
