### ISSUE TITLE
RotaryCraft Handbook entry on air compressor is out of date.

### ISSUE THREAD

**Issue by Schadrach** [ReikaKalseki/Reika_Mods_Issues#2636]
The entry in the handbook for the air compressor (use to produce compressed air for pneumatic raft using RotaryCraft power) appears to describe producing buildcraft power instead and also doesn't provide any information on how much power it needs, what effects output, how to determine the output based on the input and whether it will only build to a given pressure based on power input or if it simply adds a fixed mL/t to the line.

**Comment by ReikaKalseki** [comment]
Fixed.
