### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by UltraVolta425** [ReikaKalseki/Reika_Mods_Issues#2637]
hey

I thought I'd just report a stacktrace I've had a couple of times just now.
near the bottom of the stacktrace is the list of mods I use.

[https://pastebin.com/xLzuGMPR](url)

Since this one mentions Chromaticraft specifically, I thought you might want to know about this.

**Comment by ReikaKalseki** [comment]
#1100 #1290 #2270 #2124 #2439 #2575
