### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by UltraVolta425** [ReikaKalseki/Reika_Mods_Issues#2638]
Hey

I just encountered this error, thought you might want to know:

Crash log:
[https://pastebin.com/QAWCvFD5](url)

Latest.log:
[https://pastebin.com/S5zwhGS8](url)

Thanks for looking at this!

**Comment by UltraVolta425** [comment]
It just happened again, here's another Latest.log:

[https://pastebin.com/JBw5y5hi](url)

**Comment by ReikaKalseki** [comment]
Something is very wrong with your tile data; it looks like some of the repeaters have stored target locations outside the world boundary.

**Comment by UltraVolta425** [comment]
Huh, that's bizarre. I've only used the repeater network in the overworld.
I did place down a Transposition Gate in the sanctuary world - which got deleted when I revisited but don't worry about that - and another one after that, but other than that... I mean, some of the crystal pylons were literally a km away so there are a LOT of repeaters, and I'm sure the repeater design INSIDE the base is even worse, but still...

What do you suggest?

**Comment by ReikaKalseki** [comment]
Get rid of/rebuild this multiaura:
	Name: CCchroma.compound // Reika.ChromatiCraft.TileEntity.Networking.TileEntityCompoundRepeater
	Block type: ID #1899 (tile.crystal.pylon // Reika.ChromatiCraft.Block.BlockCrystalPylon)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (2062,62,1864), Chunk: (at 14,3,8 in 128,116; contains blocks 2048,0,1856 to 2063,255,1871), Region: (4,3; contains chunks 128,96 to 159,127, blocks 2048,0,1536 to 2559,255,2047)
	Actual block type: ID #1899 (tile.crystal.pylon // Reika.ChromatiCraft.Block.BlockCrystalPylon)
	Actual block data value: 2 / 0x2 / 0b0010
