### ISSUE TITLE
[RotaryCraft v26b] Woodcutter wont replant saplings

### ISSUE THREAD

**Issue by HonkerBonker** [ReikaKalseki/Reika_Mods_Issues#2639]
Saplings do get deposited in chest below. So trees do produce them. Tried to even manually drop saplings on and near woodcutter , still no replanting.
 Forge 10.13.4.1614 
 Rotarycraft v26b 
 Dragon Api v26b.
 That all , not even NEI , still wont replant.

https://imgur.com/a/2VQuki1

**Comment by ReikaKalseki** [comment]
Does it have valid locations to replant them?

**Comment by HonkerBonker** [comment]
Saplings grow with bonemeal , so must be valid ? I just specifically made excessivly open space for tree to grow  - https://www.udrop.com/1RVc/2020-09-13_06.45.42.png - still no replant.  Also made contraption with AE2 formation plane planting sapling in SMP (there lots of mods there ) , this one works , sapling grows, woodcutter cuts it , but only with use of AE2 it replanted.

 If valid location = sapling can grow,  then yes.  If woodcutter requirements for valid location something else i like to know what it is.

**Comment by ReikaKalseki** [comment]
The woodcutter tries planting saplings everywhere there was a log block at its level and where a sapling is allowed to be planted (ie on suitable ground and not overwriting anything).

**Comment by Goddfrey** [comment]
Wait I thought it's supposed to only replant when it 's enchanted with infinity? That's how it works in my world too, no infinity - no replant, yes infinity - replants every time.

**Comment by ReikaKalseki** [comment]
No, infinity just *forces* it to replant.
