### ISSUE TITLE
[Rotorycraft v8g][Reactorcraft 8f] Energy in tools derp

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#264]
Not sure if this is somehow intentional but I have noticed that as of version 8g of rotorycraft, the tools don't show the max energy as they did a while back instead they have current out of current as shown below:
![2015-09-10_19 17 56](https://cloud.githubusercontent.com/assets/8153290/9868056/1eed0e02-5b29-11e5-8fda-ffc7654de78c.png)

Luckily gameplay wise everything is fine and it works, just a bit of a strange bug. I did find that the rest of the tools like the knockback gun and fireball launcher also have this issue as well as any other tools, gadgets and wearables that use energy. I will report back if I find that there are more items affected and or it extends to reactorcraft or electricraft

**Comment by Zedrimar** [comment]
Even stuff from Reactorcraft has this issue

**Comment by ReikaKalseki** [comment]
This has never changed. That said, displaying twice _is_ a bug.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by Zedrimar** [comment]
ah I see
