### ISSUE TITLE
[RotaryCraft v26b] Cant enchant machines , boring machine , woodcutter , in survival.

### ISSUE THREAD

**Issue by HonkerBonker** [ReikaKalseki/Reika_Mods_Issues#2640]
Trying to enchant bore , woodcutter using avil , machine and enchanted book (silk touch for bore , infinity for woodcutter) in survival not works. In creative with same items in same slots it works.  Machines retain their enchantments , after exiting creative mode. Woodcutter properly replants saplings.
 Forge 10.13.4.1614
 Rotarycraft v26b 
 Dragon Api v26b.

 RC handbook claims it should be possible to enchant machines in survival . So seems like a bug. And woodcutter really need infinity enchant now , cause it wont replant saplings other way.

**Comment by ReikaKalseki** [comment]
That is not how you enchant them.
