### ISSUE TITLE
[Chromaticraft V26b] Casting Table not working after update and OpenGL Errors

### ISSUE THREAD

**Issue by AzuritBadger** [ReikaKalseki/Reika_Mods_Issues#2641]
I've finally decided to update my modpack from V15 to the latest V26b, which by it's own took a whole afternoon. Now, I'm facing the following problems:

- My Casting Table was at Tier 4 before the update, now it shows the 4 diamonds in the top left corner, but the last three are crossed out. I didn't change anything about the casting complex structure, i even tried to build a new casting room to go up every tier again, with no success. 
![2020-09-07_23 28 29](https://user-images.githubusercontent.com/64105171/92417340-28f4d380-f151-11ea-8adb-f92d1e0411bd.png)
![2020-09-07_23 28 39](https://user-images.githubusercontent.com/64105171/92417343-2f834b00-f151-11ea-88b5-bf59a51d45b6.png)
![2020-09-07_23 28 44](https://user-images.githubusercontent.com/64105171/92417369-3f9b2a80-f151-11ea-9cf5-14e3ee666dd5.png)

I hope you can help me here, as i'm pretty much out of ideas about the cause of this problem.

- Something causes an OpenGL Error 1282, which causes the world not to be rendered. I'm not sure if this is due to one of your mods, becaus this never happend on V15. Technically the game works, as i can walk around and interact with the world, it just doesn't get rendered. I'm not exactly sure what causes this behavior, i tried the exact same modpack on a different windows machine and on a linux system, booth didn't have this issue. I already reinstalled minecraft completly. Sometimes changing the window size removes this "bug". See this log of a game session with this bug: 
latest.log: https://pastebin.ubuntu.com/p/BR7F3dJb7g/ 
(Maximizing the window fixed it this time)
![2020-09-07_23 40 49](https://user-images.githubusercontent.com/64105171/92417776-7b36f400-f153-11ea-837b-10bcae098489.png)

General System information:
- Windows 10 Home 1909
- Java Version included with the vanilla launcher: 1.8.0_51
- Forge version 10.13.4.1614
- Optifine 17.10 HD U C1
- Game runs with 8GB of ram
- World is hosted on a seperate Server (Linux), game has 6GB ram there
- Modlist: https://pastebin.ubuntu.com/p/xt2wz2C5b9/

**Comment by AzuritBadger** [comment]
One hour later, and i found the solution for the first problem. The table didn't like the chest above it, removing it solves the issue. I don't know how i could miss out on something so obvious. Probably because this wasn't an issue in the old version.

**Comment by MalTeeez** [comment]
Second error is duplictae of https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2635 and more

**Comment by AzuritBadger** [comment]
Thanks, then this can be closed now.

**Comment by ReikaKalseki** [comment]
> Probably because this wasn't an issue in the old version.

Adjacent blocks have been disallowed for *years*.
