### ISSUE TITLE
[CHROMATICRAFT]Just Crash EXIT CODE 0

### ISSUE THREAD

**Issue by TheMidFord** [ReikaKalseki/Reika_Mods_Issues#2644]
[CHROMATICRAFT] 
Just Crash EXIT CODE 0, 6G ram for minecraft no other mods

**Comment by ReikaKalseki** [comment]
That just means something killed the process. What does the log say?

**Comment by TheMidFord** [comment]
there is no log

**Comment by TheMidFord** [comment]
BUT

**Comment by TheMidFord** [comment]
in MrLololoshka's modpack "Minecraft:Awakining" its not crashing WITH SAME SETTINGS

**Comment by ReikaKalseki** [comment]
There is a log.

**Comment by TheMidFord** [comment]
[2020-09-15-7.log.gz](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5238840/2020-09-15-7.log.gz)
 maybe this

**Comment by MalTeeez** [comment]
So by "no other mods" you meant not even DragonAPI?,
You have to install [DragonAPI](https://www.curseforge.com/minecraft/mc-mods/dragonapi) for Reika's Mods to work.

**Comment by TheMidFord** [comment]
normally when you need CORE mods minecraft tells you, but ill give it a try

**Comment by TheMidFord** [comment]
that works
