### ISSUE TITLE
[ReactorCraft] High Pressure Turbine will not Start but Consumes Steam

### ISSUE THREAD

**Issue by MajorGeneralRelativity** [ReikaKalseki/Reika_Mods_Issues#2645]
I'm having a problem with my ReactorCraft High Pressure Turbines and getting them to start. I'm using ReactorCraft v26b on Minecraft 1.7.10 with the latest Forge. I constructed a fission reactor with the setup being the first attachment. I then fed the steam into a High Pressure Turbine. This is all on a private server I run for myself so my ender quarry can work while I'm sleeping. It worked great and the HPT fed shaft power into a turbine generator to make Electricraft power for all my machines. I left the server running for a couple days and then checked in. Upon not being immediately inundated with machine noises, I checked my turbine, which was not functioning. Upon examining the steam lines, I determined that it stopped working because it had no more steam. The reactor itself had run out of fuel, so I assumed that was the problem. I applied a redstone signal to the turbine, and then refueled the reactor. However, the turbine will not start.

I let steam build up in the pipes but the turbine will still not turn. I have over 100,000 mB of lubricant per block according to my angular transducer, but it wouldn't turn. It rapidly depletes all the steam in the steam lines but fails to animate or generate any power. I let the steam build up to 1000 m^3 per block, and still nothing. I let it build up to 5000 m^3 and it still wouldn't turn. At this point, I decided to destroy the entire turbine and build a new one. After breaking every block in the turbine and the last block of steam line, I constructed a new one consisting of steam bypass + 1 layer of the 'main' HPT. It assembled and began filling with lubricant. After filling, I removed the redstone signal. It began generating a huge amount of water particles from the end (it looked different from the normal dripping) but didn't actually turn. I then constructed a second layer of the HPT. It now exhibits exactly the same problem as the first turbine. It consumes steam very rapidly (over 1000 m^3 of steam in a few seconds) but fails to actually turn or generate power. I've attached the setup in my second attachment.

I did a little more testing the following day. After restarting the server, I attempted to start the HPT. It did not start up, but it didn't consume any steam either. After examining the steam lines, the reactor source types had no source listed afterwards. After starting up my fission reactor to produce a little more steam, it now says FISSION: 100.0% as before, and the earlier behavior has resumed.

What causes this behavior? I'm not using any HTGR blocks and the reactor configuration wasn't changed from when it was working.
![2020-09-08_14 53 50](https://user-images.githubusercontent.com/11295899/93375836-bb1e6b00-f826-11ea-8f2d-5bc68a1ba6e4.png)
![2020-09-08_15 02 38](https://user-images.githubusercontent.com/11295899/93375840-bc4f9800-f826-11ea-9d54-908f371303d0.png)

**Comment by MalTeeez** [comment]
Sounds like duplicate of https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2571

**Comment by MajorGeneralRelativity** [comment]
It does appear that way. Let me do some testing and see if a similar solution will work

**Comment by MajorGeneralRelativity** [comment]
Replicating the setup described in that issue allowed me to use the same workaround. I'm closing the issue because it's a duplicate
