### ISSUE TITLE
RotaryCraft Railgun Fires Without Ammunition

### ISSUE THREAD

**Issue by MajorGeneralRelativity** [ReikaKalseki/Reika_Mods_Issues#2646]
I'm using RotaryCraft V26b, and the Railgun fires without ammunition. As noted in the attached screenshot, the railgun claims to not have ammunition, and the inventory of it is clear, but it happily fires away at zombies. Prior to it firing away with no ammunition, I had inserted 8 or less pieces of 512kg ammunition, and 8 or less pieces of 32000 kg ammunition, but it way exceeded 16 shots.

![2020-09-22_16 14 17](https://user-images.githubusercontent.com/11295899/93932773-afcbb380-fcee-11ea-9ab5-b5458bc761bd.png)

**Comment by ReikaKalseki** [comment]
I see a potential bug - did this gun previously have (and exhaust) ammo?

**Comment by MajorGeneralRelativity** [comment]
From every time I recall, yes. However, even if I cut power and then restored it, it continued firing without ammunition. If you want, I can test placing down a freshly crafted/spawned gun and see if it fires without ammunition.

**Comment by ReikaKalseki** [comment]
Yes, I want to know if having once had ammo is necessary for this behavior to arise. I do not care about what happens in the interim (short of breaking and replacing the machine entirely).

**Comment by MajorGeneralRelativity** [comment]
I spawned in a railgun from NEI, placed it down, powered it, and summoned a zombie. It tracked the zombie, but did not fire due to having no ammunition. I inserted a single 1kg railgun ammo, and it fired repeatedly until the zombie was dead. When it fired, it acted as if it was firing 1kg ammunition. However, when I inserted a piece of 128kg ammunition after the first zombie died, it now shot infinite shots of what appeared to be 128kg ammunition based off the damage dealt to subsequent zombies.

Let me know if you need any more information.

**Comment by ReikaKalseki** [comment]
OK, I know what is wrong.

**Comment by ReikaKalseki** [comment]
Fixed.
