### ISSUE TITLE
Casting Delegate does not work

### ISSUE THREAD

**Issue by Goddfrey** [ReikaKalseki/Reika_Mods_Issues#2647]
I can open the GUI I correctly see the recipes I'm supposed to see, and choose the amount, etc., but other than that no matter what I choose or click nothing else happens, it does not seem to even begin the crafting process, does not put items into stands, etc.

I'm fairly sure it's at the correct height because if I move it I no longer see recipes ;) and I think it has connection to all the colors it needs. Every color is connected to the casting structure anyway. 

I was trying to put a chest on it or connect it to AE system, changes nothing. I also put a charger on top of it to just verify if lumens can reach it.
![2020-09-24_22 34 24](https://user-images.githubusercontent.com/49716936/94191640-7ba2ef00-feb6-11ea-98f0-675c0a5d9a60.png)
![2020-09-24_22 34 43](https://user-images.githubusercontent.com/49716936/94191643-7c3b8580-feb6-11ea-9525-547b4e269f20.png)

**Comment by ReikaKalseki** [comment]
It looks like you are missing the casting injectors.

**Comment by Goddfrey** [comment]
You mean Casting Stand Insertion Relay? 
OK now I understand the capitalized "You DID create a device for placing items in stands automatically" and kinda regret my smug smile thinking I'd be able to go straight to Casting Delegate :) 

Now I DID create eight Insertion Relays and DID place them under eight diagonal / cardinal casting stands in the outer ring as per description as I understood it (screenshot). I also DID craft an insertion focus and placed it under the central table. What else am I missing? Do I need to connect all of them to AE somehow? ME cable does not seem to connect anything but Delegate.

![2020-10-08_16 21 10](https://user-images.githubusercontent.com/49716936/95465207-81eb9d80-0983-11eb-9f2c-31cc6915625d.png)

**Comment by ReikaKalseki** [comment]
To function normally, the one under the table also needs a way to dump its items (or an ME connection). However, that will not prevent the delegate from functioning.

**Comment by Goddfrey** [comment]
Got it working. Thanks a bunch!

**Comment by erplsf** [comment]
@Goddfrey, how did you solve it? I'm having the same troubles - also have crafted and placed focus/relays in the correct places...
