### ISSUE TITLE
NoClassDefFoundError: Reika/ChromatiCraft/ModInterface/ThaumCraft/ItemManipulatorFocus - crash on initialisation

### ISSUE THREAD

**Issue by pesesta** [ReikaKalseki/Reika_Mods_Issues#2649]
Hello,

I am getting a crash on initialising a custom-made modpack (which I was eventually hoping to share with two friends on a private server).

I was using forge-10.13.4.1614 for Minecraft 1.7.10, first through the Twitch launcher, and then through MultiMC..
Using ChromatiCraft+1.7.10+V26b.jar and DragonAPI+1.7.10+V26b.jar, downloaded from here:

https://sites.google.com/site/reikasminecraft/latest-downloads.

(as an aside, the .jar files downloaded through Twitch are missing the + (ie ChromatiCraft 1.7.10 V26b.jar). I'm guessing that's intentional - in any case, using the Twitch files did not work either. The following crash report is for the files on CurseForge itself though.)

***
Edited to put crash report on pastebin:
https://pastebin.com/1CHyCFGS

***

As I can not see any similar open issue having been reported here, I am guessing that I am doing something wrong. I would be grateful if you could confirm whether it is me, or an issue with the file however! If more information is needed, just say - but as I am UK based, a response may take a few hours.

**Comment by pesesta** [comment]
Problem identified between desk and chair.

(I'm not sure what changed, but Chromaticraft is now working as part of a smaller pack. Looking forward to playing it!)

**Comment by ReikaKalseki** [comment]
This is not your fault, it is someone else shipping an old TC API.

#2558 #2604
