### ISSUE TITLE
Chromaticraft/Dragon API 8g weird mod hard dependency

### ISSUE THREAD

**Issue by 1skandar** [ReikaKalseki/Reika_Mods_Issues#265]
Ok, so if you have Thermal Foundation and Chromaticraft you MUST also have either Thermal Expansion installed or Tinker's Construct. Removing TE and TiCo causes a crash. 

Which is a problem if you want Thermal Foundation for centralized ores but don't want TiCo or TE for other reasons.

edit: crash log: http://pastebin.com/HrQKyaJV

**Comment by coolsquid** [comment]
Seems like the error occurs when Thermal Foundation tries to [register liquid glowstone](https://github.com/CoFH/ThermalFoundation/blob/master/src/main/java/cofh/thermalfoundation/item/TFItems.java#L155).

**Comment by 1skandar** [comment]
And forcing Thermal Foundation to load before Chromaticraft fixes the problem. So, at a guess, Chroamticraft is breaking something that TF needs and TiCo or TE fixes it. 

Corner cases, gotta love them. Not.

**Comment by ReikaKalseki** [comment]
My guess is liquid ender is involved somehow. Which mod actually adds ender, TF or TE? I moved my registration check to TF since I thought it was from there.

**Comment by 1skandar** [comment]
Resonant Ender is from TF, yeah.

**Comment by ReikaKalseki** [comment]
I will make v9 force DragonAPI to load after ThermalFoundation, but that may only be masking some other problem...

**Comment by 1skandar** [comment]
As of yet I'm not seeing any other issues doing it that way. I will keep an eye on it, however, and will let you know if anything pops up.

**Comment by ReikaKalseki** [comment]
Closed since no longer crashing, but the actual trigger needs to be addressed...
