### ISSUE TITLE
[ChromatiCraft V26b] Config "Always Respawn EnderDragon" and "Delete End on Unload" not work

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2651]
I'm playing modpack [SetGameDifficulty Reika](https://www.curseforge.com/minecraft/modpacks/setgamedifficulty-reika)

Set "Always Respawn EnderDragon" to true can't make dragon respawn whether restart server, leave and re-enter The End.

"Delete End on Unload" only works when The End is loaded (player in The End or chunkloaded) and stop the server.

**Comment by ReikaKalseki** [comment]
I know the "delete on unload" works normally; I use it all the time, in both server and singleplayer environments. If you place some kind of chunkloader, that will break it, and is not my doing.

As for respawning the dragon, I seem to remember some kind of issue with that, and I do know offhand that it is the worldgen code that spawns it, something that obviously never re-runs until the chunk is regenerated.

**Comment by XenonDB** [comment]
How do "delete on unload" work? Leave The End and go into again?

**Comment by ReikaKalseki** [comment]
As the name says, it has to *un*load. You cannot delete a loaded world.
