### ISSUE TITLE
[RotaryCraft v26b] Distribution Clutch Computer Control

### ISSUE THREAD

**Issue by eqdanteon** [ReikaKalseki/Reika_Mods_Issues#2652]
The distribution clutch does not appear to be recognized as a component by OpenComputers 1.7.5.1290.  I am able to see and access all other RotaryCraft components that have computer/lua functionality.  I have also confirmed that the distribution clutch is set to computer control mode. I have also attempted to control the distribution clutch from ComputerCraft 1.75 however, the lua method to set the clutch output did not appear to function either.

**Comment by ReikaKalseki** [comment]
That makes no sense, given that it is the root parent class for *all* RC (and CC, ElC, ReC, and more) TileEntities that imparts said functionality.

**Comment by ReikaKalseki** [comment]
The method is registered properly: ![https://i.imgur.com/hmOhpre.png](https://i.imgur.com/hmOhpre.png)

**Comment by KassIsLegend** [comment]
so im trying to do a control room with opencomputers, i will be honest and say i have no experience with opencomputers but im going to try and learn my way around it all, my question is what all rotarycraft and reactorcraft items be connected to a computer and recognized as a component and how would you manage to do that(like through an adapter, server or just cabble it straight to the computer) as of what i have tried is right clicking the  liquid pipe, it gives me its address, i connect it to an adapter with a cable, i type "components" and the liquid pipe does not show up, i have tried to look for anyone that has posted bout a project in progress or something along the lines of that involving opencomputers and rotarycraft. haven gotten far what i want to do is get a few screens up in a small room that read off the amount of liquid in some of the pipes in areas of the reactor i have built, if that is even possible, id like to hopefully get temprature readings and maybe some readings for neutron flux, again if possible, im JUST stepping my foot into opencomputers, i have a bit of experiance with Rotary and reactorcraft but none like this, im just trying to find out what exactly is possible and what i can work with, i really apreciate anybody willing to help me or at the very least point me in the right direction, im in no rush, though i am eager to learn and get into a new project!, thank you for listening and thank you for your time

**Comment by ReikaKalseki** [comment]
Do not use adapters - DAPI-inherited blocks work natively.
