### ISSUE TITLE
[DragonAPI V26b] Ambient Pressure Calculation Bug

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2653]
https://github.com/ReikaKalseki/DragonAPI/blob/master/Libraries/World/ReikaWorldHelper.java#L2338

It should be "double f = (128-y)/(192D-128D);"

**Comment by ReikaKalseki** [comment]
Are you sure? The intent of the code is to generate a slope from y of 128 to 192, where as y rises from 128 to 192, f linearly rises from 0 to 1, such that the pressure drops from 1 to 0.8.

**Comment by XenonDB** [comment]
Line 2338 calculates ambient pressure between Y65 and Y128 not Y128 and Y192.
Also, this is how I found the bug:
![1](https://user-images.githubusercontent.com/58476103/97672988-f66ab580-1ac5-11eb-98f9-49fafcb169a1.png)

![2](https://user-images.githubusercontent.com/58476103/97673008-fec2f080-1ac5-11eb-8485-8ea8d683cd80.png)

**Comment by XenonDB** [comment]
Well, it shouldn't be "double f = (128-y)/(192D-128D);". This will cause pressure increase from Y65 to Y128.

It should be "double f = (y-64)/(128D-64D);"

**Comment by ReikaKalseki** [comment]
Fixed.
