### ISSUE TITLE
Patreon Controller Crash

### ISSUE THREAD

**Issue by Price-MA-Butta** [ReikaKalseki/Reika_Mods_Issues#2655]
Hi, both my server and my client crashed one day and will not start. The client crashed first and then the server crashed a few days later. I already know this pack works because it has for months now. Thank you for your time. 

Reika.DragonAPI.Exception.MisuseException: DragonAPI or one of its subclasses or methods was used incorrectly!
The current error was caused by the following:
You cannot have two copies of the same patron!
	at Reika.DragonAPI.Auxiliary.Trackers.PatreonController$Patrons.addPatron(PatreonController.java:163)
	at Reika.DragonAPI.Auxiliary.Trackers.PatreonController$Patrons.access$100(PatreonController.java:154)

Here is the file.

[crash-2020-11-06_03.19.51-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5498884/crash-2020-11-06_03.19.51-server.txt)

**Comment by asdasdasd31** [comment]
I found workaround. I blocked server.techjargaming.com in hosts. It's a crude fix but should do the trick for older version of DragonAPI

**Comment by Price-MA-Butta** [comment]
Hi Asdasdasd31, 
How would I block that website on my server and in my client? I took a look around and I do not see it. Thanks.

**Comment by asdasdasd31** [comment]
### This fix should not be used if you can update DragonAPI. Latest version support 1.7.10!!!!

To block it:
On windows
-Open notepad or any other text editor as administrator 
-In editor open file in your Windows folder/system32/drivers/etc/hosts
-Add at the end of the file 0.0.0.0 server.techjargaming.com
-Save the file 
On Linux 
-Open /etc/hosts with any text editor with sudo
Example: sudo nano /etc/hosts
-Same as on Windows add 0.0.0.0 server.techjargaming.com at the end
-Save the file

After this it should stop crashing but server and clients lose donator features. This should be done on clients and host.

**Comment by Price-MA-Butta** [comment]
I got it to work for the client. How would I do this for multicraft? I might just have to ask them to do this for me but I rather have a better solution if you have one. Thanks for your help.

**Comment by asdasdasd31** [comment]
Sorry I didn't knew that you were using hosting service. I have to try one more thing. I will  comment if I can get it to work. Sorry for broken English.

**Comment by asdasdasd31** [comment]
@Price-MA-Butta  Sorry this fix is stupid. Just update DragonAPI and all other mods that use it.  DragonAPI still support 1.7.10.

**Comment by Price-MA-Butta** [comment]
That's alright. I'm using Thermos on that so I can only use v14 or v15 and back work if I'm remembering correctly. I might try and find v15 or maybe ill backport even more. Normally I won't post my problems for old versions because Reika does not support them and I respect that and I don't want to be sent to the Gulag, but I was told this has to do with a donator website list he controls so I was hoping for a fix. I was told it has to do with invalid UUIDs (from a previous post). Or a way for me just to disable it would be nice. Or if I have to donate  and that's the only way I guess I can. Hopefully that won't be to expensive. Kind of weird after many years it no longer works. Anyway, thanks for your time. I really appreciate the effort.  I'll wait for Reika.

**Comment by asdasdasd31** [comment]
@Price-MA-Butta there is one more way. You can decompile one class from mod, edit url to anyother and recompile it and put it back in. It should not be difficult, I think...
P. S. You don't need to donate to fix it

**Comment by Price-MA-Butta** [comment]
So I just downgraded to V13 by downloading random mod packs off the internet from 4-5 years ago. V15 seems to not work either. So for anyone wondering that is probably the solution. Thanks again @asdasdasd31
