### ISSUE TITLE
Crash the world in minecraft on the newest lololoshka assembly

### ISSUE THREAD

**Issue by StreLite** [ReikaKalseki/Reika_Mods_Issues#2656]
Hello, my world in minecraft is dying, a person from the Time Projects group advised me to contact you, since your mod and the lord of the rings mod are to blame for the beauty of the world. 
I translated all this in google translator

**Comment by kutschkem** [comment]
Can you provide the crash log?

**Comment by StreLite** [comment]
I already solved the problem with the help of LOTR developers

**Comment by ReikaKalseki** [comment]
Also, what the hell is "lololoshka"?

**Comment by DarianLStephens** [comment]
Was there any information about how the crash was resolved?
I've tried disabling everything related to fire in both DragonAPI and LoTR's configs, but no change.

I'd love to use them together, because I've never used them on a server before, and I love the LoTR world map.

**Comment by WolfBV** [comment]
@DarianLStephens Possible fixes/patches 

https://legacy.curseforge.com/minecraft/mc-mods/lotrfixer

and 

https://legacy.curseforge.com/minecraft/mc-mods/lotr-ucp or https://gitlab.com/DwarfyAssassin/LOTRUCP/-/releases from https://lotrminecraftmod.fandom.com/f/p/3664524204835143021
