### ISSUE TITLE
[ChC][26b] Fragment recovery uses more paper / ink than intended

### ISSUE THREAD

**Issue by kutschkem** [ReikaKalseki/Reika_Mods_Issues#2657]
A bug regarding consumed resources for fragment recovery:

If there is only one paper in the inventory, 1 paper and 1 ink are consumed. (as expected)
If there is only one ink in the inventory, 1 paper and 1 ink are consumed. (as expected)

If there are at least two paper and at least two ink in the inventory, the recovery consumes two paper and two ink instead of one. 

Btw. The recovery is pretty punishing with how many fragments there are, even when it just consumes 1 of each resource. Ink isn't a big problem due to the dye trees, but I literally built a sugar cane farm just to produce enough paper to recover from having accidentally tossed my book into the transmutation flame.

**Comment by kutschkem** [comment]
The stacks are decreased two times:

https://github.com/ReikaKalseki/ChromatiCraft/blob/d78df26be1b8c25cba715234c76a1990c997324a/ChromatiPackets.java#L500-L501

https://github.com/ReikaKalseki/ChromatiCraft/blob/e2c0aa7ae10efde4816f7a92772f0567e18eaa17/Items/Tools/ItemChromaBook.java#L190-L191

**Comment by kutschkem** [comment]
The ItemChromaBook.recoverFragment method doesn't seem to do anything that isn't already done before. In fact, it does nothing with the research, or any checks that influence whether the research is recovered. I think it's just some dead remnant, check if it's still needed at all.

**Comment by ReikaKalseki** [comment]
Fixed.
