### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by flyingperson23** [ReikaKalseki/Reika_Mods_Issues#2659]
I'm using the latest version (v26) of all your mods. On world startup, one of your mods tries to retrieve the file "http://server.techjargaming.com/Reika/Donator/donators_chromaticraft.txt", which doesn't exactly exist. This, for some reason, causes 8,631 lines of log spam. Attached is a log file, look at lines 14208-22839 for the error

[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5505819/latest.log)

**Comment by ReikaKalseki** [comment]
This is already fixed - the URL was missing. Additionally, your log spam is from the matter overdrive handler, not anything to do with the patron file.
