### ISSUE TITLE
RotaryCraft Grinder NEI derp?

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#266]
There is an invisible button just to the right of the bottom left slot in the Grinder GUI that, when clicked, shows recipes for the Compacter. The normal recipes button, on the arrow, still works properly.

https://gyazo.com/c1113c0dcf5b32d52fedcb6e6be466c6
https://gyazo.com/6fa5c727c654cae3eae9d2cf4f271884

**Comment by Zedrimar** [comment]
hmmm.... I will go take a look later

**Comment by zemerick** [comment]
It's there on mine as well, current version. Haven't been able to try minimal mods yet, so not sure if its a plugin/addon/or other mod interaction, or if its in RoC/NEI themselves.

**Comment by ReikaKalseki** [comment]
I have confirmed the behavior, but only one transfer rect exists.

https://github.com/ReikaKalseki/RotaryCraft/blob/master/ModInterface/NEI/GrinderHandler.java#L135

**Comment by Modbder** [comment]
And this is why this happens - It happend to me in my NEI handlers too:

https://github.com/ReikaKalseki/RotaryCraft/blob/master/ModInterface/NEI/CompactorHandler.java#L142

```
public Class<? extends GuiContainer> getGuiClass()
{
    return GuiGrinder.class; <------- this
}
```

https://github.com/ReikaKalseki/RotaryCraft/blob/master/ModInterface/NEI/CompactorHandler.java#L104
^
|
Transfer rect

NEI loads transfer rects from all registered handlers for the GUI you are opening. The GUI is checked with this method.

**Comment by ReikaKalseki** [comment]
OK, so there is a bug in the compactor handler.

Fixed.

...Has that been in there since I wrote the handler?
