### ISSUE TITLE
[ChC][26b] Suggestion: configurable blacklist for transmutation flame

### ISSUE THREAD

**Issue by kutschkem** [ReikaKalseki/Reika_Mods_Issues#2660]
The transmutation flame is a very dangerous entity. It asks you to personally toss in items (as far as I remember, it intentionally doesn't allow automated dropping). And it eats everything. A player inventory normally contains some very valuable items (tools etc.) next to the trash. Accidents are bound to happen at some point.

Suggestion: configurable blacklist for the flame to be able to disallow some items from feeding the transmutation flame.

**Comment by ReikaKalseki** [comment]
The flame has no GUI, nor am I willing to give it one. That makes supplying a blacklist insanely difficult, especially when you consider that you may wish to later edit said blacklist.

I have also never heard of a player dying next to the flame, making me doubt how significant this problem really is.

Finally, there are many items it cannot eat - anything for which it cannot calculate a value. That will include many of the most valuable items a player has (as those are made in weird ways not handled), such as many power armors and TiC tools.

That said, it might be worth making it not able to accept items specifically dropped by player death.

**Comment by kutschkem** [comment]
Ok sounds reasonable, but by configurable blacklist, I didn't mean in-game, I meant in the configuration file.
