### ISSUE TITLE
[ChC][v26b] Manipulator focus doesn't work on machines

### ISSUE THREAD

**Issue by kutschkem** [ReikaKalseki/Reika_Mods_Issues#2661]
Steps to reproduce:

I have the transmutation flame fragment unlocked, and the elemental manipulator focus thaumcraft research researched.

1) put iron ingot or ruskea shard into transmutation flame by right-clicking on the flame with item in hand
2) throw cobblestone or ruskea berries to add ruskea to the flame -> I can see this adds ruskea
3) right click with thaumcraft wand with manipulator focus

Result: Just the original item comes out, no ruskea is consumed

To make sure the flame itself isn't broken, I tried the same setup with an actual elemental manipulator, that works as expected

**Comment by kutschkem** [comment]
I also checked the casting table, that too doesn't work. So this part of the code is not reached. I was kind of expecting that to work and somehow the small hitbox of the transmutation flame to be the problem, but that's not it.

**Comment by ReikaKalseki** [comment]
I get the feeling the wand is eating the right clicks somehow...

**Comment by ReikaKalseki** [comment]
Or...looking at it, the focus calls the manipulator right click action. But some of the blocks have the code on *their* side, ie they react to being clicked; the manipulator does not "call" them.

However, both the table and the flame are called by the tool; very little uses the latter structure.

**Comment by ReikaKalseki** [comment]
OK, it was in fact the blocks eating the right click, not recognizing that the wand should bypass their normal right click action.
