### ISSUE TITLE
[ChC] Fertility bloom is underwhelming(?)

### ISSUE THREAD

**Issue by kutschkem** [ReikaKalseki/Reika_Mods_Issues#2664]
Please correct my math, but Fertility bloom adds max(0.4, 0.1*enrichment vine)  growth ticks to one plant at random in its area. Don't I get 1 additional growth tick if I just add a plant instead of the bloom? Making the bloom only worthwile if I have at least 10(!) enrichment vine beneath?

But the enrichment vine break next to liquid, so ender liquid under the direct neighboring plants and enrichment vine are mutually exclusive, meaning I need at least 40 enrichment vine (more or less) to break even if I don't use ender liquid for stuff like ether berries. Since fertility bloom only seems to work on the same y level, the enrichment vine has to go under the farm area.

Am I doing the math wrong? Is Fertility bloom actually bad, at least for the chromaticraft worldgen plants?

**Comment by ReikaKalseki** [comment]
The fertility bloom was always intended for crops. That said, you are right in that it is weaker than it should be.
