### ISSUE TITLE
[ChC][v26b] Crash when opening casting table interface while holding Aura Tracker

### ISSUE THREAD

**Issue by malboro-urchin** [ReikaKalseki/Reika_Mods_Issues#2665]
When I right click to open the casting table interface (with a casting room setup correctly), the game crashes if I am holding the Aura Tracker. The Aura Tracker is powered at the time of the crash.

The log is linked below:

[Pastebin link](https://pastebin.com/2bfbLXSG)

I was able to reproduce this twice under the same conditions.

Modpack info: [Pagemaster](https://www.curseforge.com/minecraft/modpacks/pagemaster/files), using the most recent version of Chromaticraft on Curseforge.

Apologies if this information is insufficient, happy to answer further questions as needed. No rush or anything, since I can just not hold the aura tracker while attempting casting.

**Comment by ReikaKalseki** [comment]
This has nothing to do with the aura tracker or the casting table. That was just what you happened to be doing when it occurred.

#2194 #1936, #1423, #652, #590, #855, #161, #1358, #1474, #1488, #1565, #1871
