### ISSUE TITLE
Unknown (Possible Chunk corruption) taking place only with DAPI dependent mods

### ISSUE THREAD

**Issue by Locoapples** [ReikaKalseki/Reika_Mods_Issues#2666]
Crashes server, Private modpack, did not happen prior to adding Rotary/Reactor/Electric/Chromaticraft/DAPI (no third party modifications... i am a good boy, i promise :) )
Attached are an FML server log, Crash log, Along with a list of mods present on the clients inhabiting the  server
[fml-Log-For-Reika.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5543271/fml-Log-For-Reika.log)
[Crash-Log-For-Reika (server).txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5543270/Crash-Log-For-Reika.server.txt)
[Modslist-For-Reika.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5543273/Modslist-For-Reika.txt)

**Comment by ReikaKalseki** [comment]
That is indeed invalid and corrupted chunk NBT.

However, I have never had something like this reported as being due to my mods, nor have I ever witnessed it, nor do I mess with low-level chunk NBT like that.

I am going to tentatively assume this is a random corruption until more information linking it to my doing is available.

**Comment by Locoapples** [comment]
like I said, this is present only when DAPI and dependent mods exists. same seed. same everything except the lack of DAPI mods. when it spit out the chunk coordinates, through many itterations on different seeds the only thing notable in sight is a chromaticraft pylon, nothing underground either, other than i suppose a forgettable vanilla minecraft dungeon, and vanilla/modded ores. didnt figure attaching more reports of the same would be productive but i may still have them laying around somewhere

it might verywell be something disagreeing with chroma or something? idk

I truly have no idea if this is the fault of chromaticraft. but i am willing to give you any more information you require, to the best of my abilities.

**Comment by ReikaKalseki** [comment]
There is no way to possibly know what the source of the invalid data is - something wrote invalid data possibly long ago and only now does it cause issues.

**Comment by Locoapples** [comment]
alright well thanks for atleast getting back to me, if you ever happen to need more information on the subject i have a zip of the full instance and server files and stuff so just get ahold of me, not that i find that very likely since you seem confident enough. but none of the other authors seem to want to work with me on it

**Comment by ReikaKalseki** [comment]
There is no useful work that can be accomplished; there are literally infinite ways for data to be wrong and only one for it to be correct, and there is no way of knowing exactly how it is wrong, much less why. The cause may not even be within the game; for example random hard drive issues or edits from an external program.
