### ISSUE TITLE
 Hello, I'm stuck with chromaticraft, I can't learn anything else from everything suggested. Advise what to do?

### ISSUE THREAD

**Issue by StreLite** [ReikaKalseki/Reika_Mods_Issues#2668]
list of what is available: 
https://user-images.githubusercontent.com/74067665/100219909-aa295e80-2f27-11eb-8502-8fcff714c821.png
https://user-images.githubusercontent.com/74067665/100220043-da70fd00-2f27-11eb-9d40-300a32080668.png

I don't understand what I need to do

**Comment by Star4Fun** [comment]
Did you bought a focus crystal at a villager?

**Comment by StreLite** [comment]
> Вы купили фокусирующий кристалл у сельского жителя?
Yes

**Comment by Star4Fun** [comment]
Okay, do you already got this fragment? There is an example on the picture. I believe it's on the first row in the handbook.
https://imgur.com/a/nNvpk6k

**Comment by StreLite** [comment]
I don't fully understand where it is. I lined these runes like in this photo, but it does not help.
I looked through the entire color dictionary and found nothing. (Blanks are not studied)

**Comment by Mettymagic** [comment]
If you havent, you need to find one of the Village CC structures and open the chest - either the wooden one with the crafting table in the center or the ruined casting altar should work iirc.

**Comment by kutschkem** [comment]
Regarding casting personalization: According to this, it requires "Resourceful experience", and there is a fragment that then tells you how to do this.

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=31428


... That being said, I have Personalized Casting but not Resourceful experience so either that's wrong or the progression changed.

**Comment by kutschkem** [comment]
@Star4Fun Thanks for that image, I had no idea what the lexicon was trying to tell me.

**Comment by StreLite** [comment]
> Что касается персонализации кастинга: согласно этому, это требует «находчивого опыта», и есть фрагмент, который затем расскажет вам, как это сделать.
> 
> https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=31428
> 
> ... При этом у меня есть персонализированный кастинг, но нет опыта, так что либо это неправильно, либо прогресс изменился.

I understood little, but I understood one thing, to open casting personalization I need to open a resourceful experience, but how to open it?

**Comment by kutschkem** [comment]
@StreLite  I **think** by building the Infusion Ring structure

**Comment by StreLite** [comment]
@kutschkem

 I do not have such a structure, I can throw off any screenshots

**Comment by ReikaKalseki** [comment]
This is not the place for this kind of question.
