### ISSUE TITLE
[Chromaticraft]Breaking Lighted Leaf causes minecraft crash

### ISSUE THREAD

**Issue by FINDERFEED** [ReikaKalseki/Reika_Mods_Issues#2669]
[crash-2020-11-27_10.06.40-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5606420/crash-2020-11-27_10.06.40-client.txt)
Also i think loading a chunk with this leaves causes FPS drops(in chroma dimension i put all the graphic settings to low and lag the same as when i was on max graphics)

**Comment by ReikaKalseki** [comment]
You have another mod removing the vanilla leaf icons. This is invalid.
