### ISSUE TITLE
[Suggestion] [Rotorycraft] Coal Coke Stuff (Efficiency of use)

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#267]
I do realize that coal is EXTREMELY common but I think that these things would really help.

Things to hopefully add:
Coal Coke Block
Coal Coke Chunk (maybe)*
allow torches to be made from coal coke (normal versions, not chunks) (2 sticks for every coal coke and craft into 8 torches)?

*This should only smelt one item like the coal chunks in ztones, useful for not wasting coal, especially in generators that use furnace fuel like those from extra utils. Maybe even a way to craft them back into the normal coal coke?

**Comment by ReikaKalseki** [comment]
I am not adding the chunk, but sure, I will add blocks and a torch recipe.

**Comment by ReikaKalseki** [comment]
Done.

**Comment by Zedrimar** [comment]
ok thanks! :)

**Comment by Zedrimar** [comment]
@ReikaKalseki one last question... was coal coke supposed to be 2 times as efficient as coal or no? if  it wasn't and even if it was, can a method be implemented to allow for refining of the coal coke through by say grinding, washing then compressing or something like that to make it "super efficient"? Maybe then make it 3-4 times as efficient?

**Comment by ReikaKalseki** [comment]
No, that is not worth a new item.

**Comment by Zedrimar** [comment]
ok then
