### ISSUE TITLE
[RotaryCraft] Aluminum Alloy Ingots cannot be made using ElectriCraft Aluminum

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#2670]
For the new recipe involving aluminum ingots and silicon powder in a blast furnace at 900C, the ElectriCraft aluminum ingots cannot be used. Oddly enough, both the :4 and :6 variants from RotaryCraft work, and so does the Immersive Engineering version in the modpack I'm running.

https://i.imgur.com/Mojuplv.png

**Comment by ReikaKalseki** [comment]
There is a config in RC to allow other mods' aluminum in that recipe; by default it forces RC aluminum.
