### ISSUE TITLE
[ChromatiCraft] Vitality Depletion Field Time-Out

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#2671]
Normally, if you place a Vitality Depletion Field it will emit a constant stream of void particles. However, if there is a chunk loader present and you leave/re-enter the area with the Vitality Depletion Field there will just be an extremely dense and laggy cluster of the particles. I left a world running overnight with the depletion field in an unloaded chunk and it caused the server to repeatingly time out whenever the chunk was entered - I believe this is because the void particles are still generated even when unloaded but do not move or despawn as they normally would which just results in a massive cluster of them.

Edit: I also got this problem to occur in a chunk-loaded chunk after leaving it for only like 2 minutes. I think its a weird interaction with fans - testing a bit in single player and I noticed the particles are pushed by fans. Maybe an odd interaction cause the time outs?

**Comment by ReikaKalseki** [comment]
It is spawning particles even with no players nearby?

**Comment by Mettymagic** [comment]
Yes, I don't know how. I've tested it and even when not chunkloaded and even when there isn't a player online I just come back to a massive clump of particles. Simply just setting one up, going out of range for like 2 minutes and running back can reproduce this - you'll come back to a gigantic clump of particles that will either lag your game until they disperse or straight up time it out.

**Comment by ReikaKalseki** [comment]
Those "particles" are not particles at all. They are proper entities, and its mechanism of killing. It would be pointless to make the block only work if there is a nearby player.

However, it sounds like you are encountering the "entities only update when there is a 5x5 of loaded chunks around them, but TEs update as long as their chunk is loaded" behavior, the same thing that causes ReC neutron pileups in unloaded reactors and (years ago) used to cause massive ball lightning accumulation around pylons. Fortunately, I can use the same tools to fix this.
