### ISSUE TITLE
[ChromatiCraft] ISE on player join with Inventory Linker

### ISSUE THREAD

**Issue by icedown** [ReikaKalseki/Reika_Mods_Issues#2672]
I had created an inventory linker in ChromatiCraft and was messing around with it to figure out how it worked.  As i right clicked with it, switching from No Items to the next option, there was an internal server error crash.  Now every time I try to join the world I get the crash instantly.  Tried restarts of both server and client as well as removing fastcraft.  It's calling it a divide by zero error.

I'm running:
Forge: 1614
Reika Mods: V26b
Testing with Fastcraft disabled as well. Same issue

Both logfiles are from a fresh restart of the server, then player tries to join.

fml-server-latest.log
[https://pastebin.com/EuwuiKQr](url)

latest.log
[https://pastebin.com/CsXJzhrg](url)

Note: I currently have the server shut down and can reproduce it at any time.  Waiting a while before restoring the backup of the world

**Comment by ReikaKalseki** [comment]
You bound it to an inventory of size zero. I have no idea who would code such a thing, but will not allow it to connect in the future.

Delete the item and try again.
