### ISSUE TITLE
[DragonAPI v26b]: Can't create / enter a world

### ISSUE THREAD

**Issue by mine-tech-oficial** [ReikaKalseki/Reika_Mods_Issues#2673]
I created a small modpack in ATLauncher just for me that for now only has DragonAPI, and when I try to create / enter a world it throws an error.

Crash report: https://pastebin.com/UQJvdvdT

I also want to ask for permission to include your mods in my modpack because I'm planning on making it public.

**Comment by mine-tech-oficial** [comment]
I don't know if there is already an issue that talks about it, so there is no problem to let me know

**Comment by thehajo** [comment]
I have played a lot of CC and never encountered this type of crash, however i do know of the problem of not being able to create worlds sometimes, it's just weird. That being said, have you tried starting the game and creating the world without mcp? (Whatever that is, never heard of it, sorry)

**Comment by mine-tech-oficial** [comment]
> I have played a lot of CC and never encountered this type of crash, however i do know of the problem of not being able to create worlds sometimes, it's just weird. That being said, have you tried starting the game and creating the world without mcp? (Whatever that is, never heard of it, sorry)

I can create a world without the DragonAPI, but with it I can't.

**Comment by thehajo** [comment]
I... just realized mcp is something that is installed in literally every minecraft modded pack, i just never noticed it in my crash reports. Apologies for that. 
However googling "java.lang.VerifyError: Expecting a stackmap frame at branch target 259" found 2 older issues with the same error. Those suggested updating forge. 
You are running 10.13.4.1558, and, while this is the recommended version apparently, there are newer ones. 
Try updating forge to 10.13.4.1614, as that version works for me. Using 1558, i was able to replicate this crash. 
So, this is just an installation error.

**Comment by mine-tech-oficial** [comment]
> You are running 10.13.4.1558, and, while this is the recommended version apparently, there are newer ones.
Try updating forge to 10.13.4.1614, as that version works for me. Using 1558, i was able to replicate this crash.
So, this is just an installation error.

Yesterday i installed the newer version but I don't tried to open a world with the DragonAPI. I will try now.

**Comment by mine-tech-oficial** [comment]
Thank you, @thehajo, now I can use Reika's mods!

**Comment by The-Tech-Revolutioner** [comment]
@ReikaKalseki, can you give me permission for use your mods in my modpack?

**Comment by ReikaKalseki** [comment]
#2199 #1740 #1437 #1566 #1583 #2262 #2203 and many more.
