### ISSUE TITLE
[ChromatiCraft] Crystal Interference will generate impossible puzzles

### ISSUE THREAD

**Issue by thehajo** [ReikaKalseki/Reika_Mods_Issues#2674]
I noticed that the new Crystal Interference puzzle does not work sometimes. Basically it will just generate not solvable puzzles. I even tried using a jigsaw/irregular sudoku solver online, where the numbers just represent crystals, but with no luck. 
The solver i used was https://www.dcode.fr/irregular-sudoku-solver. 
I also created an Imgur album to show my step by step solving process, as well as the websites outputs. 
https://imgur.com/a/HIrNAg9
This album does include the unsolvable puzzle right at the top.
I am playing together on a server with a friend of mine, and he sometimes encountered the problem that the core is just not there. While i do know that it disappears due to the use of rather... "creative"... means, he assured me that was not the case. However when you cannot get to the core in the first place, doesn't matter if it is there or not.

EDIT: Forgot to add, we are playing on a server with V26b, which to my knowledge is the newest one.
EDIT2: Also this is on "Dimension Structure Difficulty"=1. Not sure if this matters.

**Comment by ReikaKalseki** [comment]
I am pretty sure this is fixed in the next version.

**Comment by thehajo** [comment]
Thank you very much. :D

**Comment by thehajo** [comment]
I apologize if this fix has not been published yet, but we just encountered the same problem on version V29g, with structure difficulty set to 3.

**Comment by lAimBotl** [comment]
I have ran into one on difficulty 2 (it was the first room if that matters)

(ChromatiCraft+1.7.10+V29g)


![CrcCrystalPuzzle](https://user-images.githubusercontent.com/10777735/121624624-dc238d80-ca3f-11eb-814d-49fad926cdab.png)

![CrcCrystalPuzzleCheat](https://user-images.githubusercontent.com/10777735/121624640-df1e7e00-ca3f-11eb-9fbf-348a23cafb37.png)

**Comment by ReikaKalseki** [comment]
That one is trivially solvable...think outside the box. :P

**Comment by cetirizinehydrochloride** [comment]
> That one is trivially solvable...think outside the box. :P

Thanks for the hint, the box is literally on the floor and I only solve this puzzle after reading this issue.
