### ISSUE TITLE
Got an error about install without ThaumCraft

### ISSUE THREAD

**Issue by naruko-hstk** [ReikaKalseki/Reika_Mods_Issues#2676]
Error find @ V26b
Here is crash report(Not full report)
`java.lang.NoClassDefFoundError: Reika/ChromatiCraft/ModInterface/ThaumCraft/ItemManipulatorFocus`

**Comment by naruko-hstk** [comment]
When I remove ChromatiCraft, everything has been normal

**Comment by herp21** [comment]
Either can install thaumcraft, or you can try a fresh install on the server with all your mods loaded first that are not made by reika and then I'd delete the world files and install all of the mods by reika youd like, before restarting the server. That worked for me so far while I've been troubleshooting.

**Comment by ReikaKalseki** [comment]
#2558 #2604 #2649

Check CoFHCore.
