### ISSUE TITLE
[Chromaticraft] Filter Control puzzle locked out

### ISSUE THREAD

**Issue by ChaosReaver118** [ReikaKalseki/Reika_Mods_Issues#2677]
For clarification, its the puzzle with the rotating color tape.
Running on Chromaticraft version 26b, single player world in mod pack SetGameDifficultyReika.  Last dimension core is locked due to structure not thinking its been completed. Debug options limited due to no cheats enabled on world, troubleshot with Reika and found only first door on each floor was flagging as complete.

**Comment by ChaosReaver118** [comment]
On further digging, with Reika, found the cause

"NBT key collision for key 'door' between PistonDoorTile and PistonTargetTile (latter uses for substage, former for door block coordinate)"

**Comment by ReikaKalseki** [comment]
Fixed.
