### ISSUE TITLE
Shafts are not craftable in the worktable

### ISSUE THREAD

**Issue by WeebWalther** [ReikaKalseki/Reika_Mods_Issues#2678]
It works in the crafting table if that is switched on in the config. I know this has been posted in issue #2546 and is marked as "fixed," but the issue still persists. I am playing on the newest versions.

![Screenshot 2020-12-10 141603](https://user-images.githubusercontent.com/75791459/101777454-ce259c00-3af2-11eb-8075-3bf6fb7cb659.png)

![Screenshot 2020-12-10 142745](https://user-images.githubusercontent.com/75791459/101778255-e9dd7200-3af3-11eb-9365-1a0f1801a06f.png)

**Comment by ReikaKalseki** [comment]
Fixed does not equal released.
