### ISSUE TITLE
[RotaryCraft V26b] Interesting, a runtime visible annotation becomes runtime invisible?

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2679]
This causes I can't add new smelting recipes for Friction Heater.
I don't know why this happen.
![1](https://user-images.githubusercontent.com/58476103/101882360-c2100c00-3bd0-11eb-86d3-2f42375f8a75.png)
![2](https://user-images.githubusercontent.com/58476103/101882373-c5a39300-3bd0-11eb-887b-ec3ed7504b84.png)

**Comment by ReikaKalseki** [comment]
That could only be changed with ASM, and I have no reason to do that.

**Comment by XenonDB** [comment]
Did you mean your mod on curseforge was modified by someone?

https://www.youtube.com/watch?v=kvg7m5zsXXI

**Comment by ReikaKalseki** [comment]
No, I am saying that only ASM can change annotations like that, and I have no reason to have done so.

**Comment by XenonDB** [comment]
> Did you mean your mod on curseforge was modified by someone?
> 
> https://www.youtube.com/watch?v=kvg7m5zsXXI

I downloaded RotaryCraft from curseforge and just found that.
If the annotation didn't modified by you, I don't know who did that.

**Comment by ReikaKalseki** [comment]
I cannot tell you.

**Comment by ReikaKalseki** [comment]
I am going to close this until a mechanism by which it occurs is suggested.
