### ISSUE TITLE
Dragon api crashes the creative search menu

### ISSUE THREAD

**Issue by traso56** [ReikaKalseki/Reika_Mods_Issues#2680]
I spent 2 hours debugging this so hopefully I can give all the info needed:

I didn't update my mods in a while because I didn't play in a while, I had dragon api version V24c and everything worked fine but then updated to the latest (V26b) and now when I tried to open the creative menu to search blocks (the compass tab) my game crashed, I isolated the issue to 3 mods, forestry, open computers and zetta industries all of them latest versions for 1.7.10 and if I remove any of them it works fine, only crashes when the 3 are loaded, I also downgraded to dragon api V24c and it works fine
[crash-2020-12-15_17.09.47-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5699432/crash-2020-12-15_17.09.47-client.txt)

**Comment by herp21** [comment]
Use to be an issue years past as well. I have forestry currently installed in my client and have no issues with the search in creative mode. Not sure about zetta industries but if you have NEI installed try turning it off "O" is the default key bind if im not mistaken and try using the search then. May just be overloading the gui or something similiar.

**Comment by traso56** [comment]
well, as I mentioned in my description only when these 3 were installed it crashed, it's not forestry alone because if I remove for example open computers it works also I tried loading only dragon api and these 3 mods and it in fact crashed, so NEI has nothing to do with it

**Comment by ReikaKalseki** [comment]
This has nothing to do with me. The error mentions only `Zetta Industries` and OpenComputers, with the former being likely the real cause.

**Comment by traso56** [comment]
thing is, if I remove dragonAPI it works just fine and an older version of dragon API works as well, all of these worked just fine before I updated dragonAPI so it has something to do right?

**Comment by ReikaKalseki** [comment]
While that logic is valid, I do not modify the creative inventory or its tabs, and if I was doing something it would appear here.
