### ISSUE TITLE
All of Reika's mods including DragonAPI incompatible with Vivecraft.

### ISSUE THREAD

**Issue by brandyyn** [ReikaKalseki/Reika_Mods_Issues#2681]
I am getting a vr headset for xmas and I really wanted to play my pack and reikas mods in vivecraft, however because of reika's mods asm coremod hooks it doesn't allow the game to launch. Any chance for a fix? This was supposed to have been fixed a long time ago: https://github.com/jrbudda/minecrift/issues/132

**Comment by ReikaKalseki** [comment]
This is completely unfixable - both mods require massive amounts of ASM to work. You could in theory disable all the conflicting patches in DAPI, but that will break a great many things.

The only exception to the above is if you can point to specific patches that are incompatible *and* those patches comprise only a minority of the total. I really strongly doubt the latter.
