### ISSUE TITLE
Crash on Startup because of XML/Lang files.

### ISSUE THREAD

**Issue by brandyyn** [ReikaKalseki/Reika_Mods_Issues#2682]
I saw lots of other issues regarding this same thing, but none of the fixes worked, we tried reinstalling, clearing config & adding "-Dfile.encoding=utf-8" to the launch options, nothing worked. I believe this is because his system local language isn't in English, it was in Chinese. His crash reports & logs: 
[latest (2).log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5736894/latest.2.log)
[crash-2020-12-23_18.40.40-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5736895/crash-2020-12-23_18.40.40-client.txt)
[latest (3).log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5736896/latest.3.log)
[crash-2020-12-23_19.46.18-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5736897/crash-2020-12-23_19.46.18-client.txt)

**Comment by ReikaKalseki** [comment]
I cannot fix this without someone giving me a new version of the translated files.

**Comment by XenonDB** [comment]
These four reports show the JVM flag:
"JVM Flags: 3 total; -Xms3072m -Xmx3072m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump"

However "-Dfile.encoding=utf-8" doesn't exist.

**Comment by brandyyn** [comment]
he did use it, it didnt work then he was trying without it, these 4 reports were his latest after removing it. 
what exactly do you need reika?

**Comment by ReikaKalseki** [comment]
> what exactly do you need reika?

Exactly what I said.
