### ISSUE TITLE
[ChromatiCraft] Bezier Crystals are way too strong. 

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#2683]
Not a bug but a pretty large balance concern. For the state of the game in which you get them, I think the Bezier crystals are way too good and act as a completely catch-all weapon that undermines the later-game weapons you can get.

Each hit of the Bezier Crystal deals 6 magic damage (which pierces armor) and can hit multiple mobs from an extremely far distance and through any walls or obstacles. There is no cooldown on the attack, no charge required for it or durability to limit its use, and the recipe is extremely cheap and early in progression.

The Bezier Crystal is far superior to the Chain Gun and Blast Gun as it requires no semblance of aiming due to its auto-homing and can hit through walls. Even the Discharge Gun, which quotes that "up until now you have had no way to attack a mob whose position you know but cannot see" is undermined by one of the first info fragments you will get, and it's rather disappointing given how much fun all the other weapons are.

I think the Bezier Crystal needs a huge nerf or even a rework - for instance, greatly decreasing the range to like ~8 blocks, increasing the cooldown/decreasing the damage, making it require line of sight of the target, and making it require a lumen charge or giving it a durability would make it a safe but slow weapon that still has a use but doesn't undermine the later items that are supposed to be stronger.

**Comment by Shahelion** [comment]
I believe it doesn't give drops, since it doesn't count as a player kill, although I couuld be wrong.

Line-of-sight to the first target and a lumen cost would probably be enough to make it not quite so clearly the best option, while still allowing it to function splendidly.

**Comment by ReikaKalseki** [comment]
It was always intended to require LOS.

EDIT: I can see what is wrong.

**Comment by ReikaKalseki** [comment]
Fixed.
