### ISSUE TITLE
[DragonAPI] Mystcraft ASM error V27a

### ISSUE THREAD

**Issue by Keyarose** [ReikaKalseki/Reika_Mods_Issues#2684]
Getting a crash when starting up minecraft after updating to V27a.  It's throwing an ASM exception trying to find a function in GenLayerAddIsland from Mystcraft.

Log: https://gist.github.com/Keyarose/455d1056f307d0009c3c775430ed941a
Mystcraft Version: 0.12.3.04(latest on forge for 1.7.10)

**Comment by qwahaha** [comment]
I don't think it's a problem with MystCraft. I'm getting the same error with GenLayerAddIsland and I'm not using MystCraft.

**Comment by bpwhelan** [comment]
Similar issue with Gregtech. https://gist.github.com/Beannsss/1d577fc92eb3cbc2a5976fbff158a298.

**Comment by SisterJacq** [comment]
Same, not using MystCraft or GregTech. The relevant (crashy) part of my log: https://gist.github.com/Mortvana/68c2bbf63a508d5a2a43e7e8574a26f2

**Comment by BobbyTables2020** [comment]
Similar issue, no mystcraft, no gregtech https://pastebin.com/AiZpzJkd, think the issue is with climatecontrol in my case.

**Comment by HevTa** [comment]
Where can I get the previous version 26. Please. Also game crash, no files saved
DragonAPI and RotaryCraft

**Comment by Shahelion** [comment]
I'm getting the same issue, but with ATG (Alternate Terrain Generation)

https://gist.github.com/Zsashas/d500c4cc6aaffa33bfe9fc619bb7cb9e

**Comment by ReikaKalseki** [comment]
Fixed, and I have no idea why this works for me.

**Comment by ReikaKalseki** [comment]
I think I figured it out:
![https://i.imgur.com/bktCsL3.png](https://i.imgur.com/bktCsL3.png)

**Comment by XCOAnnika** [comment]
is ther a downlod link or somthin Along that lines ?

**Comment by XCOAnnika** [comment]
Link*

**Comment by brunoquiz2** [comment]
how can i fix this error ?

**Comment by Keyarose** [comment]
Since it's been tagged as fixed I imagine said fix will be in V27b. @XCOYoshi @brunoquiz2

**Comment by XCOAnnika** [comment]
Wen wil it be relized

**Comment by syndicate25** [comment]
I'll come back and edit this again. For some reason it looks like I still have v27a.

**Comment by XCOAnnika** [comment]
i still have a issu with V27C

[crash-2020-12-27_12.24.11-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5744466/crash-2020-12-27_12.24.11-server.txt)

**Comment by XCOAnnika** [comment]
![image](https://user-images.githubusercontent.com/26392051/103170331-b6188100-4843-11eb-9ce4-ff5c4b9ead98.png)
that are the faild classes

**Comment by brunoquiz2** [comment]
I have a problem that even if I enter the world only with the mod dragon api, the game just closes. This version 27a is buggy for me and I don't know how to fix it.
Does anyone know how to help me or where can I download another version?
