### ISSUE TITLE
[Reactorcraft] v27a placing heat exchanger or boiler crashes

### ISSUE THREAD

**Issue by 3bygone3** [ReikaKalseki/Reika_Mods_Issues#2685]
Placing down heat exchanger or boiler crashes, also saves with these blocks already placed crash on load. Using only v27a versions of DragonAPI, Rotarycraft and Reactorcraft.
[log](https://pastebin.com/KAZcmQdP)

**Comment by ReikaKalseki** [comment]
Mine is not doing this...

**Comment by ReikaKalseki** [comment]
Fixed.
