### ISSUE TITLE
Problem after updating all of your mods

### ISSUE THREAD

**Issue by XCOAnnika** [ReikaKalseki/Reika_Mods_Issues#2687]
we are playing A modpack with your mods and after updating V27b The modpack stopt working 

[crash-2020-12-26_23.40.20-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5743820/crash-2020-12-26_23.40.20-client.txt)

**Comment by XCOAnnika** [comment]
i have used google translate to translate it from german

**Comment by ReikaKalseki** [comment]
#2686 #2684
