### ISSUE TITLE
[DragonApi V27b] Instant server crash, launches on clients

### ISSUE THREAD

**Issue by VenomiXeD** [ReikaKalseki/Reika_Mods_Issues#2688]
The server, on startup completely dies because of an ASM fault, probably because there was an attempt trying to ASM a client class. However launching the game with the mods launches fine with no errors spitted out on client log.

Below, is the complete server log.
https://pastebin.com/mmeC7Jew

Note that this did not happen before, with DragonAPI V26, launching the server had no problem.

**Comment by Bobidobi** [comment]
Same here, have to downgrade, even though message about update keep popping in client.

**Comment by ReikaKalseki** [comment]
Fixed.
