### ISSUE TITLE
Game crashing during game load with DragonAPI version V27b - Caught exception from DragonAPI java.lang.NoClassDefFoundError: Reika/ChromatiCraft/ChromatiCraft

### ISSUE THREAD

**Issue by syndicate25** [ReikaKalseki/Reika_Mods_Issues#2689]
New issue occurring during game load with version V27b:

Game crashes at step 2 of 7 with the following:

[19:07:56] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue (see more details in pastebin below)

https://pastebin.com/5wc9WUxJ

**Comment by ReactivePlatypus** [comment]
I've had a similar issue with Expanded Redstone. 

Crash report from a clean instance (only Reika mods):  https://pastebin.com/tm8mFW5T

**Comment by ReikaKalseki** [comment]
Fixed.
