### ISSUE TITLE
java.lang.NoClassDefFoundError: Reika/DragonAPI/Interfaces/ISBRH due to DragonAPI changes

### ISSUE THREAD

**Issue by SisterJacq** [ReikaKalseki/Reika_Mods_Issues#2690]
Likely due to the change of ISBRH from a wrapper interface to an abstract class, Expanded Redstone crashes on startup.

Log: https://gist.github.com/Mortvana/67ad455b48c1db5f97b3e9e7bceefab3

**Comment by syndicate25** [comment]
I think this is related to the same issue which was added/reported under my issue, #2689

**Comment by SisterJacq** [comment]
It is the same issue. Reika snuck out an update 10 minutes before I managed to report this that fixed it. Except on the ElectriCraft front (now crashing from Reika/ElectriCraft/Renders/BatteryRenderer, otherwise the same issue though)

**Comment by ReikaKalseki** [comment]
Update everything to 27b.
