### ISSUE TITLE
[Chromaticraft v27b] Crash when breaking blocks with an empty hand

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2692]
https://gist.github.com/Zsashas/950088daedc40ea3bb2fa1f66ec1edc8

**Comment by BobbyTables2020** [comment]
Similar issue (I think) when breaking ender io conduit, https://pastebin.com/TSg9YZ8e

**Comment by Juha686** [comment]
Seems to happen every time you break something with an empty hand as well, crash report is similiar to one in starting post so I did not include mine. Replicated it by starting a new world with Chromaticraft v27b and trying to break anything (grass, dirt etc) with an empty hand.

**Comment by ReikaKalseki** [comment]
Fixed.
