### ISSUE TITLE
Stil problems with updating your mods

### ISSUE THREAD

**Issue by XCOAnnika** [ReikaKalseki/Reika_Mods_Issues#2693]
[crash-2020-12-27_12.24.11-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5744718/crash-2020-12-27_12.24.11-server.txt)
Fix Your Shit !!

**Comment by XCOAnnika** [comment]
![image](https://user-images.githubusercontent.com/26392051/103174334-85474480-4861-11eb-98f6-5fc4e1a61da2.png)
Ehat are the failiong classes

**Comment by ReikaKalseki** [comment]
Fixed.
