### ISSUE TITLE
[DragonAPI V27d]Method only exists in client side but is invoked in server side

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2696]
![1](https://user-images.githubusercontent.com/58476103/103207380-1c330000-4939-11eb-91cb-6a636e4b040e.png)
![2](https://user-images.githubusercontent.com/58476103/103207386-1dfcc380-4939-11eb-857f-8cf67258f597.png)
![3](https://user-images.githubusercontent.com/58476103/103207390-1f2df080-4939-11eb-9b38-0e8e320a41cd.png)

**Comment by ReikaKalseki** [comment]
....why in the F@#$ is the method client-only in IBA, when every implementor that is not clientside itself does not mark the method as such and can handle serverside invocations of it just fine...

**Comment by ReikaKalseki** [comment]
Fixed.
