### ISSUE TITLE
[ChromatiCraft v27d] Crash hovering over slot in inventory

### ISSUE THREAD

**Issue by RaidhoSketch** [ReikaKalseki/Reika_Mods_Issues#2697]
First freeze-up and then crash while in inventory window seemingly from hovering:
https://pastebin.com/ZjwDBL4p
Second crash on reentering world, seems to be the same issue:
https://pastebin.com/pAX0BY90

**Comment by ReikaKalseki** [comment]
OK, you have a TiC tool with no NBT; this is invalid.
