### ISSUE TITLE
fuck you

### ISSUE THREAD

**Issue by daladian** [ReikaKalseki/Reika_Mods_Issues#27]
sfgargq3treg

**Comment by FurryDJ** [comment]
Please elaborate, and we will be more than happy to appease your inner demons.

**Comment by ReikaKalseki** [comment]
No, my standards are better than that.

**Comment by coolsquid** [comment]
Please do not use swearing in the title of your issues. Also note that reading the rules before posting is required. Thanks for your collaboration.
