### ISSUE TITLE
Older versions of mods not available

### ISSUE THREAD

**Issue by alex-sherman** [ReikaKalseki/Reika_Mods_Issues#2700]
Please consider leaving older versions of mods available.

This has several benefits:

1. When a new version is released that is found to have bugs (like v27d) users will have an older version to fallback to.
2. Support for users that maintain long running worlds and do not wish to take on risk in upgrading.

Most versioned software has a concept for LTS or "stable" for these reasons, and since curseforge has great support for older versions, all you need to do to support this is to not delete the old versions.

It would also be very nice if you could restore some of the older versions, especially since the only available Chromaticraft (and maybe DragonAPI?) contain a crash bug.

**Comment by MalTeeez** [comment]
While 1. totally makes sense 2. seems weird since players who wish to not take on risk in upgrading either thoroughly test the newer versions in their setup or just don't upgrade.
Nonetheless an archive of the last stable version from the previous release would be a appreciated.

**Comment by alex-sherman** [comment]
I agree that 1. is stronger justification, but I do think 2. warrants keeping versions older than just the last "stable" version.

This is a bit of an exaggeration, but without some source of "truth" for older versions there's nothing stopping people from creating fake/malicious versions of the mods and passing them off as the original. Curseforge shows the MD5 of files for exactly this reason.

Another (arguably fabricated) example would be modpacks constructed as dependency lists rather than giant mod-folder zips.

I'm hand-waving but there are security/usability downsides to not keeping all previously published versions and, AFAICT, no upsides to deleting them.

**Comment by ReikaKalseki** [comment]
I know from experience that leaving old versions available results in most people, especially packmakers, using them preferentially, presumably out of some (invalid) assumption that newer always equals more unstable. This resulted in a great many "old version" bug reports, something removing direct access to the old versions almost entirely stopped.

Also, modpacks can continue to access the old files; they are archived and hidden, not deleted.

Finally, this is not the place for this kind of discussion.

**Comment by alex-sherman** [comment]
My apologies, where should I continue this discussion?
