### ISSUE TITLE
Exception getting block type in world

### ISSUE THREAD

**Issue by jadenquinn** [ReikaKalseki/Reika_Mods_Issues#2702]
I created a new world on my custom 1.7.10 pack, which isn't very stable on it's own. I don't really have any additional information to add other than the log(s).

https://pastebin.com/rZ3WNHfd
(I was gonna add the full log but pastebin doesn't even work with a 35MB log, so I'll just use my own site)
http://jadenswebmc.us.to/logs/fml-client-latest.log
http://jadenswebmc.us.to/logs/crash-2020-12-30_22.27.10-server.txt
http://jadenswebmc.us.to/logs/latest.log

**Comment by jadenquinn** [comment]
Oh, and I almost forgot, I'm not on the latest versions of your mods. I'm working on updating them now but it hasn't been too long since I did this so they may have only updated a little.

**Comment by jadenquinn** [comment]
Update: I updated your mods and it now just redirects to the title screen every time I create a world now. No errors in the logs, nothing. Not sure why, I only updated the mods I already had installed so that shouldn't have done much.

Wait no, I did add one mod, Satisforestry.


I was gonna uninstall it but my game didn't even quit fully when I clicked quit. I had to kill it.

**Comment by jadenquinn** [comment]
Alright. I have a new error: Already Tesselating!
https://pastebin.com/jqCLdX7d
Edit: Does DragonAPI not work with Optifine? The game is super laggy without it, I just added it today since I don't think lag is cool.

**Comment by ReikaKalseki** [comment]
DAPI and Optifine work fine together, but you need an Optifine version that is Forge-compatible. Yours is not one of them.

**Comment by jadenquinn** [comment]
Which version is forge compatible? It seems to load fine in other modpacks. I don't see a reason why I would need an old version, they do basically the same thing that I can see. It's just... Optifine. Every version loads up with Forge, is that not Forge-Compatible in this context?
A google search doesn't do me any good, which is why I'm asking.

**Comment by jadenquinn** [comment]
Modpack I'm using here: https://drive.google.com/file/d/12Rmqh2LYFY-BEZ-oW6gIMwimhWaoOkr8/view?usp=sharing

**Comment by ReikaKalseki** [comment]
I use OptiFine_1.7.10_HD_C1.
