### ISSUE TITLE
[ChromatiCraft V27d] Capital Strike with high frequency attacking weapon cause LivingDropsEvent fired multiple times

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2703]
Some mods listen LivingDropsEvent for extra loot drop. This may be abused.

Here are some cases for Capital Strike with high frequency attacking weapon:
1.Kikoku from Extra Utilities enchanted with Capital Strike.
2.Hold weapon with Capital Strike and let lumen turret kill the mob.

Perhaps Checking if target is alive first will be better?

**Comment by ReikaKalseki** [comment]
Lumen turrets should not give drops at all...

**Comment by ReikaKalseki** [comment]
I just made capital strike not apply to lumen turrets, as well as adding a health > 0 check.
