### ISSUE TITLE
[RotaryCraft] The gas turbine does not cool down

### ISSUE THREAD

**Issue by XCOAnnika** [ReikaKalseki/Reika_Mods_Issues#2705]
I have built a gas turbine and had the problem that it no longer falls below the tempratur of 269°C it is already shut down for 2 days 48H. hi I still have pictures of the problem

Translated with www.DeepL.com/Translator (free version)

![2021-01-02_17 50 47](https://user-images.githubusercontent.com/26392051/103462189-d81e7180-4d23-11eb-9504-b784e14a0233.png)
![Screenshot_1](https://user-images.githubusercontent.com/26392051/103462190-d8b70800-4d23-11eb-816b-c520717cdfaf.png)

**Comment by XCOAnnika** [comment]
I have already tried to remove the blocks

**Comment by ReikaKalseki** [comment]
It is working fine for me. ![https://i.imgur.com/1VWNNc9.png](https://i.imgur.com/1VWNNc9.png)

**Comment by ReikaKalseki** [comment]
Once again I tested this and everything worked fine. It is officially not an issue.
