### ISSUE TITLE
Reactorcraft Config Options

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [ReikaKalseki/Reika_Mods_Issues#2709]
"Enable Fast and Thermal Neutrons"
Having a good working understanding of Nuclear Physics, may I ask what exactly this option changes?

Thank you.

**Comment by ReikaKalseki** [comment]
If enabled, it makes ReC neutrons emulate the various energy levels - and resultant reactivities - of the neutrons from various sources, so that you need to moderate "fast" neutrons into a form that are more likely to be useful in triggering fission.
