### ISSUE TITLE
Dimensional Monument in distress!

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#271]
1) Some shielding stone blocks were replaced by "lighted leafes" without a tree. From the looks of it, upon generation of the monument all wood/leafes were removed, except for those that were _exctly_ where the shielding stone was supposed to go.

2) There was also some miasma left inside the structure (4 total blocks). Though not obviously breaking anything.

3) The central pylon makes an error beep every second once activated. (with a distance independent volume)

4) The monument structure is assymetrical.

Via your instructions, assuming the north-western-bottom-most block to be indexed (x/y/z) 0/0/0 and counting towards east as -x, towards south as -z, the four missing blocks are [assuming journeymap "north" is correct]:

-16/0/-4 (north side)
-4/0/-26 (west side)
-26/0/-38 (south side)
-38/0/-16 (east side)

EDIT:
5) Placing any color crystal lamp onto any "shielding stone" that is part of the monument makes the lamp unbreakable.

**Comment by ReikaKalseki** [comment]
5) is unfixable, an artifact of a combination of the music structure and the block class's limited functionality with dynamic hardness.

I need an image of 1).

**Comment by lossycrypt** [comment]
1) I'm afraid i only made one after removing the leaves and adding some glowstone.

![treeatemonument](https://cloud.githubusercontent.com/assets/14168854/9933129/10919d74-5d49-11e5-8f03-c26bf8d9d9f2.jpg)

**Comment by ReikaKalseki** [comment]
That is not helpful...

**Comment by lossycrypt** [comment]
Due to the random nature it's impossible to make a better one tho :|

**Comment by lossycrypt** [comment]
Also 5) The lexicon icon for the monument is a socketed crystal, so ppl will probably try putting lamps/potion crystals in various positions, and i for one thought at first that the lamp becoming indestructible meant that it was "in the right place". So you might at least change the lexicon icon.

**Comment by ReikaKalseki** [comment]
What would you suggest?

**Comment by lossycrypt** [comment]
Suggest about 1)? Probably that you try generating a few monuments on your own pc and teleport there (because you get the coordinates!). And then hope you can observe the leaf-problem yourself.

**Comment by ReikaKalseki** [comment]
No, the icon.

**Comment by lossycrypt** [comment]
I don't know. The Locus maybe. Tho the icon itself doesn't look much different from the dim cores. Or something entierly new.

**Comment by lossycrypt** [comment]
Actually the compass might work. It gives a tiny hint that the monument is linked to the 16 elements, but doesn't give anything away about the structure.

**Comment by ReikaKalseki** [comment]
The thing is, fitting as that may be for the _structures_, I do not see much connection with the monument itself.

**Comment by lossycrypt** [comment]
What connection is there between the current potion crystal and the monument?

I don't even know what you have in mind with the monument. As it stands right now there is no lore at all explaining what the monument is supposed to be or do, or why it needs to be charged with "dimensional cores" which in turn are not explained either. And at the end of it all you get - to keep consistent - a not-explained awesome glowing orb. So it's pretty hard for me to come up with a fitting icon.

6) And i just remembered: The central "crystal.pylon" glowing-orb-magic-ball can be destroyed (before the ritual i mean).

**Comment by ReikaKalseki** [comment]
And everything here that was reproducible has been fixed. Also, I found this in the code for ProgressStages:

`CTM(ChromaBlocks.SUPER.getStackOfMetadata(CrystalElement.YELLOW.ordinal())), //icon is a placeholder`

Note the comment.

I changed the icon to the Aura Locus for now.
