### ISSUE TITLE
[GeoStrata v27b] Glowing Vines is now a block  

### ISSUE THREAD

**Issue by robert-pathy** [ReikaKalseki/Reika_Mods_Issues#2710]
## Description
Prior to v27 when Glowing Vines (GV.) were placed in the world they would attach to the parent block. This mirrored the behaviour that vanilla vines have in base minecraft. 

In v27 all newly placed G.V. and existing ones already placed in the world  now appear as full blocks (also with a strange white texture on the topside) similar to how leaf blocks present themselves.  This change was not mentioned in the change log for the v27 family and may be an accidental change. 

## Motivation and Context
Posted in mincraft forums and was directed by @ReikaKalseki to open an issue:
[minecraft forums post](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=1274#c31451)

## How Has This Been Tested?
Private modpack Without Optifine
Have NOT tested in isolation with only DragonAPI + GeoStrata  

## Screenshots (if appropriate):
Before (v26):
![v26](https://user-images.githubusercontent.com/938018/103553593-a6b8b980-4e7b-11eb-9795-ed74ebf0b2a5.png)

After: (v27b)
![v27](https://user-images.githubusercontent.com/938018/103553596-a91b1380-4e7b-11eb-8e38-3b453ab66fbe.png)

**Comment by robert-pathy** [comment]
Please let me know if you would like me to test this with just DragonAPI + GeoStrata prior to you looking at it. 
Or for that matter if there is any other prior testing you would like me to do to aid you before you look into this.

I will also update the ticket with my Forge Version and a list of the mods in my Private (100% not distributed) modpack.

**Comment by ReikaKalseki** [comment]
I made a typo in specifying the render type during the ISBRH overhaul; it was using the vent renderer.
