### ISSUE TITLE
ChromatiCraft NoClassDefFoundError (Thaumcraft is not installed-It's disabled)

### ISSUE THREAD

**Issue by jadenquinn** [ReikaKalseki/Reika_Mods_Issues#2711]
I'm running this through MultiMC, I made quite a few changes to the modpack I made before (I've posted with issues on it before), and it broke again, but this time it's less obvious what I could do on my own to maybe fix the issue here.

Here's the full Minecraft log:
https://paste.ee/p/HOArg

And here's the actual crash report:
https://pastebin.com/kvhsz452

Thanks,
Jaden.

**Comment by ReikaKalseki** [comment]
#2558 #2604 #2649 #2676
