### ISSUE TITLE
Crashing with Exception Ticking World with Reika v27 mods

### ISSUE THREAD

**Issue by braeden-hambor** [ReikaKalseki/Reika_Mods_Issues#2712]
Hey Reika,

Below is the crash log and mod-pack Mawcraft (on 1.7.10) for the issues that I'm having with exception ticking world. World runs fine on v1.7 of the mod-pack (had them saved as a back up) but when updating and attempting to run the updated mod set that you have cause the crashes on the server with that exception as well as loading the world in single player (EDIT: world loads fine in single player once I had to roll back the server to v1.7, download world save, and relaunch the world in the new pack update but when transferring back to server same crash persists), even when attempting to update the set manually outside of the pack using the mod

https://pastebin.com/50KtpF4S <--- Crash Log
https://www.curseforge.com/minecraft/modpacks/mawcraft <--- Mawcraft (attempted v1.8.5 originally then rolled back to v1.7 only updating your mod set to v27)

**Comment by ReikaKalseki** [comment]
#2696 #2699 #2706
