### ISSUE TITLE
[ChromatiCraft V28a] A max level enchantment can only do it "max level - 1" ability 

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2713]
For example, Capital Strike IV should deal maximum 250 damage one hit.
However it only deal maximum 100 damage, same as Capital Strike III.

https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Registry/ChromaEnchants.java#L98

**Comment by ReikaKalseki** [comment]
Fixed.
