### ISSUE TITLE
[ChromatiCraft V28a] Bezier Crystals causes freezes

### ISSUE THREAD

**Issue by Juha686** [ReikaKalseki/Reika_Mods_Issues#2714]
Using Bezier Crystals in a situation where theres potential LOS issues, like with underground caves or in forests, you can experience freezes for upwards of 1 minute. On a server this can cause all players to time out, but it does resolve itself without a server restart.

I believe issue came after this commit:
https://github.com/ReikaKalseki/ChromatiCraft/commit/1b227d7dea5f0d34261bc4b00204532026368a16#diff-002de817056716f357fb3cb8c024c20a7b287cd5812ec21e3986cd535a2e8034 on file ` Items/Tools/ItemSplineAttack.java`

On a flat world it seems hard to replicate, but during normal gameplay you will more often have freezes than successes.
You can also kill yourself with the crystals now, which I believe was not possible before.

**Comment by ReikaKalseki** [comment]
Both of these should be fixed now.
