### ISSUE TITLE
[Reaktor Craft]  RFtools interaction problem

### ISSUE THREAD

**Issue by XCOAnnika** [ReikaKalseki/Reika_Mods_Issues#2717]
render problems with the space chamber card with a fison reactor removed so that you can set it up again without having to do it yourself. However, then the game of my colleague Gecrascht and he had to restart. the build with the builder goes without problems.

Translated with www.DeepL.com/Translator (free version)
[crash-2021-01-09_13.18.49-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5790995/crash-2021-01-09_13.18.49-client.txt)

**Comment by ReikaKalseki** [comment]
The crash is coming from his code, and your txt file is unreadable.
