### ISSUE TITLE
[ReactorCraft] Steam boilers not heating up from neutron absorbers

### ISSUE THREAD

**Issue by REIT4G** [ReikaKalseki/Reika_Mods_Issues#2718]
![image](https://user-images.githubusercontent.com/77207353/104105524-4b565380-52e1-11eb-8933-4b18eec864c8.png)
![image](https://user-images.githubusercontent.com/77207353/104105527-5ad59c80-52e1-11eb-882d-59253071e966.png)

**Comment by REIT4G** [comment]
version v28a

**Comment by MalTeeez** [comment]
Since your absorbers seem to be cooling down anyways, can you try removing the boilers from a section and see if they're still loosing heat? - Just referencing this from an earlier issue #2414

**Comment by ReikaKalseki** [comment]
Those boilers seem *exceptionally* cold...why?

**Comment by REIT4G** [comment]
> Since your absorbers seem to be cooling down anyways, can you try removing the boilers from a section and see if they're still loosing heat? - Just referencing this from an earlier issue #2414

yeah. they`re still losing it

**Comment by REIT4G** [comment]
I just now realized that I also have water that turns to ice just in caves soo..... i`m sorry maybe it`s some mod in my minecraft that adds a realistic temperature, but i have no idea which one 
(I'm Russian and not very good at English)

**Comment by REIT4G** [comment]
but anyway, I kind of saw in earlier issues that this bug still isn`t fixed, am i right?

**Comment by REIT4G** [comment]
omg it`s dynamic lights, i`m sorry guys, now it`s heating 
![image](https://user-images.githubusercontent.com/77207353/104179157-fe3bc400-543d-11eb-9a63-a0ee5ff6dd28.png)

**Comment by REIT4G** [comment]
now it`s melting :)

**Comment by ReikaKalseki** [comment]
I am curious how DynamicLights, which sounds like a client-only rendering mod, can be related.
