### ISSUE TITLE
[Chromaticraft 28a] Essentia Relays duplication glitch & Interaction with void jars

### ISSUE THREAD

**Issue by Juha686** [ReikaKalseki/Reika_Mods_Issues#2719]
Breaking Essentia Relays with anything other than Elemental Manipulator after it has been tapped to "activate" it will result in two Relays dropping.

Example of something that can break the relay after activation would be Ars Magica 2 break spells.

Essentia Relays also dont empty essentia from the alembics to full void jars like you would expect.

**Comment by ReikaKalseki** [comment]
I fixed the first issue.

The second is not a bug - they only actively push to jars if the jars are labelled, and I see no reason to make them try to void surplus essentia when that is rarely desirable.

**Comment by Juha686** [comment]
I have labelled my Void Jars. 

The point of making a void jar in the first place is to void essentia thats unnecessary, for example if I have a system set up to do ore multiplication through alchemy and that required Ordo and Metallum. If I get these from chiseled stone and ingots, I have left over Terra and Lucrum, which when stored in void jars should be voided after the jar fills up with 64, but instead currently fills the jar and piles up in the alchemical furnace. I currently dont have thaumic energistics set up so it's not feasible for me to store thousands of useless essentia.

I see your view on rarely needing to void essentia, but the purpose of the jar is exactly to get rid of excess essentia.
Much like you would place void upgrades in barrels or drawers to avoid farms filling up with useless seeds or saplings.

**Comment by ReikaKalseki** [comment]
If any jar - normal, void, mirrored, whatever - is labelled, it will try to fill it from unlabelled jars or alembics.

**Comment by Juha686** [comment]
On EssentiaNetwork.java line 477 you have this:
`int amt = 64-amountField.getInt(tile);`

Which afaik results to 0 pull on a Void Jar that's full at 64 of Essentia.

Here is an image of a full void jar thats not being transferred to, despite the alembic having Terra and there being a valid destination for it
https://i.imgur.com/XYYU6dK.png

**Comment by ReikaKalseki** [comment]
That would do it.

**Comment by ReikaKalseki** [comment]
Fixed.
