### ISSUE TITLE
WTF happend there

### ISSUE THREAD

**Issue by XCOAnnika** [ReikaKalseki/Reika_Mods_Issues#2721]
I loaded the chunk by running there and this happened

![2021-01-10_17 51 50](https://user-images.githubusercontent.com/26392051/104129631-0972ef00-536d-11eb-992e-84d4873859c4.png)

it is in the log of line 24528

LOG:https://paste.ee/p/0bjWW#s=0&l=24528

Translated with www.DeepL.com/Translator (free version)

**Comment by ReikaKalseki** [comment]
Something really broke the OpenGL matrix stack. There is no way to know what it is without removing blocks, but I have never had this happen with anything of mine.
