### ISSUE TITLE
[RotaryCraft 28a] Handbook displays output power using wrong prefix (kW and MW)

### ISSUE THREAD

**Issue by Juha686** [ReikaKalseki/Reika_Mods_Issues#2725]
As example, the handbook displays microturbines output as two megawatts (2097152MW).
Correct display would be 2097152W

Image for reference:
![handbook](https://user-images.githubusercontent.com/57060909/104666934-b4710900-56dd-11eb-931f-226409312084.png)

**Comment by ReikaKalseki** [comment]
Fixed.
