### ISSUE TITLE
Question - Custom Recipe Handler

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [ReikaKalseki/Reika_Mods_Issues#2726]
Ive got the custom recipe handler for the worktable down as explained and demonstrated in 
[Reddit Post](https://www.reddit.com/r/feedthebeast/comments/5o0a2m/by_request_custom_recipe_configs/)
[Imgur Album](https://imgur.com/a/oDj38)

I know the worktable handler file is named custom.recipes_worktable and I have my recipes working in it currently, but is there a name for a standard crafting table recipe handler?

Or do all custom crafting recipes have to be handled by the work table?

If there is not a handler for custom standard crafting table recipes, can one be added?

Thank You.

**Comment by ReikaKalseki** [comment]
I do not add one for standard crafting. That is what Minetweaker is for.

**Comment by MachiavelliSeraphim** [comment]
Only asked because I cannot make AE2 autocrafter patterns for worktable recipes and minetweaker will not let me make alternate recipes for your items/machines.

Thanks for the info.
I will just have to automate a pile of worktables.

Thank you.
