### ISSUE TITLE
Void Opal texture is disconnected

### ISSUE THREAD

**Issue by HellsingDarge** [ReikaKalseki/Reika_Mods_Issues#2727]
[Also seems to have a weird rim](https://i.imgur.com/uiA7KWP.png) (unless it's intentional)

And on a side note: is Satisforestry supposed to be so elevated compared to surrounding biomes (akin to being a mountain forest biome)?

**Comment by ReikaKalseki** [comment]
Yes, that rim is intentional, designed to not create "visual cracks" between opal and other blocks that would otherwise arise due to its multilayered nature.

And yes, the height is intentional: ![https://i.imgur.com/mitdbho.jpg](https://i.imgur.com/mitdbho.jpg)
