### ISSUE TITLE
[Chromaticraft] AggroMask/Areastrike on pigmen stackoverflow

### ISSUE THREAD

**Issue by Zero-ui9** [ReikaKalseki/Reika_Mods_Issues#2729]
https://pastebin.com/KPEwMDLA

http://puu.sh/H8cTO/2ea69cdb7f.jpg

This seems to happen if I have a large amount of pigmen in an area(particularly if I'm using a certain spawner from a structure of yours) and attack one with that sword. The damage seems to almost endlessly chain throughout the group, which can result in that crash if theres enough pigmen. I don't know if its intended, but the attack will also chain to any pigmen within aggro range if I attack them elsewhere(like anywhere in the open nether).

**Comment by ReikaKalseki** [comment]
Does it deal multiple "hits" per pigman?

**Comment by Zero-ui9** [comment]
it appears to, in my pack I'll have the random warded/tainted etc. mobs from thaumcraft which don't normally get 1hit by that sword, but if they're in a pigmen group like that, they'll all die in the single hit.

**Comment by ReikaKalseki** [comment]
OK, then I have an idea what is going on.

**Comment by ReikaKalseki** [comment]
I tested this, and not only does the code run as expected, I do not get any issues:
![https://i.imgur.com/UgACcPs.png](https://i.imgur.com/UgACcPs.png)
![https://i.imgur.com/1ZBA8RV.png](https://i.imgur.com/1ZBA8RV.png)

**Comment by ReikaKalseki** [comment]
And yes, it works for pigmen too:

![https://i.imgur.com/FC70YQr.png](https://i.imgur.com/FC70YQr.png)

**Comment by BlueAgent** [comment]
Seems to happen with following steps:
1. Have a 1x2x1 tall hole to store pigmen
2. Stand inside the hole
3. `/summon PigZombie` 25 times inside the hole
4. Give yourself a diamond sword and enchanted with: Aggro Mask II, Area Strike V and Armor Breach IV
5. Hit them with sword a bunch of times till they die or stop taking damage
Server will freeze or crash depending on JVM settings (if you still can and try to exit to main menu it gets stuck forever).

**Comment by ReikaKalseki** [comment]
It was the interaction between those three enchants, in particular because aggro mask's trigger event extended LivingAttackEvent - and thus was also getting caught by all the handlers - and armor breach using - and refiring - the same event.
