### ISSUE TITLE
Lumen leaves capacity WAILA discrepancy.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#273]
When drawing lumen from lumen leafes with the elemental manipulator, the amount of lumen that Waila shows are drawn vastly exceed the lumen that should be drawn. Example:
If my manipulator has a cap of roughtly 100k and Waila shows the lumen leaves have 1M stored lumen, then after drawing from 0 to capacity of the manipulator Waila will show less than 800k stored lumen left.
(For reference the maximum capacity show by Waila is 10977000)

**Comment by ReikaKalseki** [comment]
Drawing lumens from a source has a [high loss rate](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Items/Tools/ItemManipulator.java#L297).

**Comment by lossycrypt** [comment]
Hrmpf. This is highly unintuitive as the trees only purpose is for the player to draw lumen from it. At the very least there should be a hint about this in the lexicon.

**Comment by ReikaKalseki** [comment]
> as the trees only purpose is for the player to draw lumen from it.

Also false. The tree is a battery, which is meant to power devices the same way pylons do.

**Comment by lossycrypt** [comment]
Hm. The lexicon said something to that extend but ... i guess i need to to some closer observation, sorry ;). 
Btw, the "Lumen Tree" structure info page is still not showing the lumen battery as a component, just 3 glass on top.
(A hint that manual drawing might be inefficient would still be a good idea imho.)

**Comment by ReikaKalseki** [comment]
> Btw, the "Lumen Tree" structure info page is still not showing the lumen battery as a component, just 3 glass on top.

...I can fix that.

> (A hint that manual drawing might be inefficient would still be a good idea imho.)

To me this is one of those "internal mechanic" things the player need not know (and given some playstyles, should not know). Think of Botania's "show no numbers".

**Comment by lossycrypt** [comment]
> no numbers.

Well, but you are showing numbers. The thing is, due to the "intended lack of information" which you're practicing with chromaticraft (and i do like that as a concept), it is sometimes impossible for the player to tell if something is intended to work like it is, or if it's bugged. But if you say this one is intended i will just yield on this one.

> ...I can fix that.

Are you saying that nobody ever reported that in the last 6 month btw? orz.

**Comment by ReikaKalseki** [comment]
> It is sometimes impossible for the player to tell if something is intended to work like it is, or if it's bugged

To me this one seems "natural"....but that may just be me.

> Are you saying that nobody ever reported that in the last 6 month btw? orz.

I have had bugs go unreported for over a year, including a crash bug with the GPR and an NEI dependency.

**Comment by lossycrypt** [comment]
> To me this one seems "natural"....but that may just be me.

As the developer of the mod, that would be obvious ;).

> I have had bugs go unreported for over a year, including a crash bug with the GPR and an NEI dependency.

And there i was worried to bother you with duplicate reports...

**Comment by ReikaKalseki** [comment]
> And there i was worried to bother you with duplicate reports...

?

**Comment by lossycrypt** [comment]
> ?

I mean: The bug was so old that i didn't even consider reporting it seperately because i didn't want to post a bugreport for something i thought _must_ have been reported already.
