### ISSUE TITLE
[Chromaticraft] PylonGenerator CME's

### ISSUE THREAD

**Issue by Zero-ui9** [ReikaKalseki/Reika_Mods_Issues#2730]
https://pastebin.com/kENS2eRd

This is a crash I get very often since putting up a crystal network, I don't know what exactly causes it other than possibly occasional requests on the network(the crashes happen more often since building a lumen tree) but I can't always tell if that's the case because of how seemingly randomly this crash happens.

https://pastebin.com/7ZSTAgjp

Another one that I've only had once afaik. Again, don't know the cause, but hopefully the log itself is a lot more helpful.

https://pastebin.com/SFPjUaT2

This one I get pretty consistently from using a storage crystal charger when I try to charge a crystal with a large capacity, it seems to be from making a lot of energy requests at once(has access to all 16 pylons)

**Comment by ReikaKalseki** [comment]
#1100 #1299 #1290 #1604 #1991 #2035 #2151 #2439 #2575 #2637
