### ISSUE TITLE
DragonAPI gives a crash with no report being given.

### ISSUE THREAD

**Issue by MagmaSlime123** [ReikaKalseki/Reika_Mods_Issues#2731]
No crash report is given. Do not ask for one. If you want the log file then let me know.

![image](https://user-images.githubusercontent.com/51277766/105273918-0d62f600-5b51-11eb-8b03-6cf7934cbd28.png)

**Comment by XCOAnnika** [comment]
Log plese

**Comment by MagmaSlime123** [comment]
Sorry for the late response.

[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5882599/latest.log)

Please*

**Comment by MagmaSlime123** [comment]
@XCOYoshi 7 days. Still waiting.

**Comment by ReikaKalseki** [comment]
Your actual error is #2656. The crash report being hidden is your launcher being stupid.

**Comment by MagmaSlime123** [comment]
Info for that was never given nor any way of fixing this.

**Comment by ReikaKalseki** [comment]
Your error is the same as theirs. With neither of you having provided anything, nor any contact from the LOTR developers, what do you expect me to do?

**Comment by MagmaSlime123** [comment]
The issue is caused by your mod and theirs modifying a file that both mods have. 

And again, no crash report is provided, so I can't give anything besides the log file. Which again, I gave above.

![image](https://user-images.githubusercontent.com/51277766/111008259-89094400-8345-11eb-9a17-94d53d30eae9.png)

**Comment by ReikaKalseki** [comment]
Yes, I already know the crash is an ASM conflict. I need to know what their patch is to be able to do anything about it.

**Comment by MagmaSlime123** [comment]
Ask them.

**Comment by ReikaKalseki** [comment]
I have no idea who "them" is. You do. Hell, you can @ them here if you know their names on GitHub.

**Comment by WolfBV** [comment]
@MagmaBro123 Possible fixes/patches 

https://legacy.curseforge.com/minecraft/mc-mods/lotrfixer

and 

https://legacy.curseforge.com/minecraft/mc-mods/lotr-ucp or https://gitlab.com/DwarfyAssassin/LOTRUCP/-/releases from https://lotrminecraftmod.fandom.com/f/p/3664524204835143021
