### ISSUE TITLE
ArrayIndexOutOfBoundsException with ItemElementCalculator

### ISSUE THREAD

**Issue by RocketMermaid** [ReikaKalseki/Reika_Mods_Issues#2732]
Any time I try to use NEI on a number of items - Osmium Ingots from Mekanism, Enderium ingots from Thermal Expansion, Charcoal - the game freezes and then crashes about five seconds later. From my own Googling, it resembles the ItemElementCalculator interaction that was supposed to be fixed with GregTech several iterations ago. Crash log:

[crash-2021-01-23_14.44.04-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5861269/crash-2021-01-23_14.44.04-client.txt)

**Comment by XCOAnnika** [comment]
i got the same problem

**Comment by ReikaKalseki** [comment]
This is on ProjectE's end - it needs to handle "wildcard" metadata, especially if said metadata is being registered to the ore dict or some recipe.

**Comment by RocketMermaid** [comment]
Thanks!

**Comment by RocketMermaid** [comment]
So, I removed ProjectE and any of its dependencies (Thaumic Equivalency, Equivalent Energistics) and I still get the same problem: 

[crash-2021-02-15_00.37.03-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5980369/crash-2021-02-15_00.37.03-client.txt)

**Comment by ReikaKalseki** [comment]
The same issue applies, this time to ExtraTrees.
