### ISSUE TITLE
Central Control not heating up with blocks around it [ReC v28a]

### ISSUE THREAD

**Issue by Starrmont** [ReikaKalseki/Reika_Mods_Issues#2737]
In the screenshot below, you can see that the Central Control block is sitting at ambient (45C), despite the other blocks around it being around 200C. Naturally this prevents automatic scrams.
![Screenshot (4)](https://user-images.githubusercontent.com/78274726/106364829-e0a4a080-62ff-11eb-9562-7e76d542c8bd.png)

UPDATE: I also just noticed (quite on accident) that when it is "raining" (desert biome), the ambient moves down to 40C, and Central Control temperature moves down with it.

**Comment by XCOAnnika** [comment]
#2705

**Comment by XCOAnnika** [comment]
related Probably

**Comment by rogerwim** [comment]
Probably also related to broken neutron absorbers

**Comment by ReikaKalseki** [comment]
Fixed.
