### ISSUE TITLE
Central Control Rod Malfaunction

### ISSUE THREAD

**Issue by XCOAnnika** [ReikaKalseki/Reika_Mods_Issues#2738]
the Central Control cannot retract or extend all Control Rods  

Translated with www.DeepL.com/Translator (free version)

**Comment by ReikaKalseki** [comment]
Do you have sufficient power?

**Comment by XCOAnnika** [comment]
https://youtu.be/00p0dQm21F0

here you can see the reactor and the power the problem occurs only when there is fuel in the reactor nodded off during the video

**Comment by ReikaKalseki** [comment]
"Straggler" blocks being left behind suggests the CPU is forgetting about certain cores.

That logic is old and probably not very robust; it may need to be redesigned.

**Comment by XCOAnnika** [comment]
ok

**Comment by ReikaKalseki** [comment]
I cleaned it up; we shall see if it helps.
