### ISSUE TITLE
DragonAPI causes WAILA to not show for AgriCraft Crops

### ISSUE THREAD

**Issue by FoxySophie** [ReikaKalseki/Reika_Mods_Issues#274]
AgriCraft 1.3.1
AppleCore 1.1.0
WAILA 1.5.10
DragonAPI V8g

Whenever I have DragonAPI installed the WAILA overlay for Crops does not show. It shows for any other block as far as I can tell, just not the Crops. Removing the API fixes it.

**Comment by quedral** [comment]
try removing wailaharvestibility and / or waila plugins. that fixed my issue.

**Comment by lossycrypt** [comment]
I had a similar issue that was resolved by removing wawla. Agricraft works fine here with "waila plugins". I don't use harvestability.

**Comment by FoxySophie** [comment]
Neither combination of disabling WAILA Plugins and/or Harvestability fixed it for me

**Comment by ReikaKalseki** [comment]
Reported minutes earlier... #272
