### ISSUE TITLE
Knowledge Entanglement Pedestal Server Crash [Chromaticraft v28a]

### ISSUE THREAD

**Issue by The-Dungeon-Master-Coder** [ReikaKalseki/Reika_Mods_Issues#2740]
I saw that there was a crash involving the Knowledge Entanglement Pedestal before that was labeled fixed. This was a Ticking Block Entity crash, so it's already fixed on the server, but I figured I should still report it just in case it has unfixed itself since last year. DragonAPI and Chromaticraft are the current versions according to Curse, though I expect most of the other mods that aren't yours are not up to date as we added DragonAPI and Chromaticraft to an old pack.

Crash log: https://pastebin.com/dwxk7j4j

**Comment by ReikaKalseki** [comment]
This was fixed in v29.
