### ISSUE TITLE
Shafts made with mounts not craftable [RotaryCraft V28a]

### ISSUE THREAD

**Issue by Tronni22** [ReikaKalseki/Reika_Mods_Issues#2741]
Shafts that are crafted with mounts are not craftable in the worktable (or at all). Since this exact issue/an extremely similar issue was fixed a few versions ago, I have tried to see if it is a problem on my end, however the issue still persists with only DragonAPI mods loaded. Wooden and stone shafts are craftable.

**Comment by ReikaKalseki** [comment]
![https://i.imgur.com/Kqxj4bH.png](https://i.imgur.com/Kqxj4bH.png)
![https://i.imgur.com/Ib6hvmA.png](https://i.imgur.com/Ib6hvmA.png)

**Comment by Tronni22** [comment]
I thought the recipe was shapeless and so I have been placing the components incorrectly in the worktable, and it didn't dawn upon me until now. Sorry for opening a non-issue.
