### ISSUE TITLE
Info about recipes

### ISSUE THREAD

**Issue by traso56** [ReikaKalseki/Reika_Mods_Issues#2742]
Hello, I wanted to change some of the futuristic stuff in my game like the rotarycraft light bridge to require rare metals found in other galacticraft planets, I used your documentation to create a new recipe which is basically the materials in the default recipe plus the rare metals, however there isn't a part about removing the old recipe and would like to know how to do it, thank you!

**Comment by ReikaKalseki** [comment]
The system was never designed for that, and Minetweaker never wrote handlers to change the items in the existing recipes (as was originally planned back in 2016).

The only way to accomplish this is with a mod or other "real code" dedicated for the purpose.

**Comment by traso56** [comment]
in that case may I ask if you can make a config option to disable the recipe of "fun machines" that don't affect progression like the light bridge and jetpack for example?

**Comment by ReikaKalseki** [comment]
The light bridge already has such a config. The jetpack is too valuable to make that permissible.
