### ISSUE TITLE
[Chromaticraft] Item Structure Finder (Aura Tracker) sometimes causes error, player to get kicked

### ISSUE THREAD

**Issue by eugennc** [ReikaKalseki/Reika_Mods_Issues#2743]
Issue:
The Structure Finder (Aura Tracker) item from Chromaticraft sometimes causes an 'Internal Server Error', which disconnects the player (on reconnection, the same thing happen).

Reproduction:
Haven't player CC since version 26. Never encountered the error there, despite using the Structure Finder (Aura Tracker) extensively (many tens of structures found). Started a new server with 28a, worked fine at the start, but after uncovering and eliminating a few (about 10-15) structures (the last of which was a Frozen Outpost), the error started happening. Both nearby the Frozen Outpost (10000 away from world origin) and in my base (1500 away from world origin), at a later time.

Workaround:
Edited the player NBT file, drained the energy from the Aura Tracker. While still being the active item in the hotbar, the error stopped happening. This, alongsite the log file below, seems to point to an issue in the actual structure finding logic of the Aura Tracker.

Log:
[errFinder.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/5946088/errFinder.txt)

**Comment by LumberWizard** [comment]
Happened to me as well, no idea what the cause is. Of note is that it kept kicking me until I changed the type of the tracker with NBTExplorer. It happened with multiple types (once with type 1, and once with type 2).

**Comment by HellsingDarge** [comment]
To add to this: the same error occurred in singleplayer once and never happened again - there was no need to change NBT of anything for it to be resolved, happened while tuning for "white" aura, iirc
[Crashlog](https://paste.ee/p/n3tko)

**Comment by ReikaKalseki** [comment]
Fixed.
