### ISSUE TITLE
Crash when connecting to dedicated server with Reliquary and NotEnoughResources installed

### ISSUE THREAD

**Issue by LumberWizard** [ReikaKalseki/Reika_Mods_Issues#2746]
Crash report and log snippet:
https://gist.github.com/LumberWizard/87982ec0d07b5bfd73fff3bd3b1416aa

To reproduce, simply create an instance with DragonAPI, ChromatiCraft, NEI, NotEnoughResources, and Xeno's Reliquary, and attempt to connect to a server with those mods installed (the server doesn't need to have NotEnoughResources, it only needs to be on the client).

**Comment by ReikaKalseki** [comment]
Something is using a null damage source. This is wrong.
