### ISSUE TITLE
Need help，crash with jmap

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#2747]
Need help，crash with jmap。[Ubuntu Pastebin](https://paste.ubuntu.com/p/WZsf3gHJCK/)
![QQ图片20210218215542](https://user-images.githubusercontent.com/19620848/108367208-2a641500-7234-11eb-8a06-3f376180a26c.png)

**Comment by KuroPeach** [comment]
and crash with Xaeros_Minimap  [crash report](https://paste.ubuntu.com/p/pVxjhfMcSd/)
![QQ图片20210218220909](https://user-images.githubusercontent.com/19620848/108369234-52ed0e80-7236-11eb-8d6b-5f7ff88e9c3e.png)

**Comment by ReikaKalseki** [comment]
Both of those represent metadatas of that block that do not exist. Either that map is using the wrong metadata, or - more likely, given you seem to have had two independent map mods have this issue - you have a corrupted block.

**Comment by KuroPeach** [comment]
emmmmm，i will use worldedit regen it
