### ISSUE TITLE
[ChromatiCraft V28a] Enhanced tahara crystal pendant may not clear some negative effects.

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2748]
The "clearBadPotions" function in ReikaPotionHelper (which is how tahara crystal actually clear bad effects) use a pre-generation list "badPotions" to determine whether an effect is negative. 
However, the list is generated at post initialization stage, which may not collect some potion registered after that and not able to clear it.

Maybe use ReflectionHelper or something similer to access isBadEffect(srg name: field_76418_K) is better?

**Comment by ReikaKalseki** [comment]
That field is often an inaccurate representation of whether the potion is actually bad - several bad potions deliberately set that to `false` to stop tools like this, and several "bad in practice" potions were not intended to be bad and as such also have it set to false.

**Comment by XenonDB** [comment]
However, the "loadBadPotions" construct the list by examining "isBadEffect" field (Although I don't know why can it direct access the private filed)
https://github.com/ReikaKalseki/DragonAPI/blob/master/Libraries/ReikaPotionHelper.java#L104

As you say, the "badPotions" list may not contain potion which is actually bad, and may contain some "bad in practice" potions

**Comment by ReikaKalseki** [comment]
Also, potions are not supposed to be loaded later than post-init - that is simply asking to break things.
