### ISSUE TITLE
[ChromatiCraft V28a] The reason about client side freezing in Proxima

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2751]
I notice it may be relative with the bgm of proxima since starting playing these 9 bgms also cause lagging.
![2021-02-23_03 49 50](https://user-images.githubusercontent.com/58476103/108761809-45af8700-758a-11eb-8793-650962b8307a.png)

I register these bgm by sounds.json file either in resource pack form or via CustomNpcs, for example
![1](https://user-images.githubusercontent.com/58476103/108762624-4ac10600-758b-11eb-8518-fd569f8d8f89.png)

Choose one and play it, there is no lagging at starting.

Finally, I made two command block for testing:
1 : playsound customnpcs:chromaticraft.polychromacy_c @p
2 : playsound custom_path:C:/Users/Noone/AppData/Roaming/.minecraft/modpacks/testpack_forge1.7.10/mods/Reika/ChromatiCraft/Music/polychromacy_c.ogg @p

Execute command 1 cause no lagging but command 2 do.

Then I **made some thread dump with JProfiler during lagging while executed command 2** and found something:
![2](https://user-images.githubusercontent.com/58476103/108763670-93c58a00-758c-11eb-994e-7465bd27292a.png)
![3](https://user-images.githubusercontent.com/58476103/108763676-958f4d80-758c-11eb-901e-da9940045c09.png)

**Client thread was blocking because it didn't have lock SoundSystemConfig.THREAD_SYN while IO thread have that lock.**

**This may mean the sound registing you made cause game loads bgm file every time at starting playing bgm. This shouldn't happen.**
Maybe you can make a sounds.json to register these sound or mimic that registering behavior.

**Comment by XenonDB** [comment]
By the way, if I set stream to false for chromaticraft.polychromacy_c in sounds.json above, lagging happeneds **only the first time** I execute command 1, while it happeneds **everytime I execute command 2**.

**Comment by KuroPeach** [comment]
Is there any loading method other than custom npc

**Comment by XenonDB** [comment]
> Is there any loading method other than custom npc

Via resource pack. I made an example here: https://github.com/XenonDB/ChromatiCraftBGM_menu_and_test

Make sure CC is installed.
This pack replace main menu bgm to proxima bgm.

You can follow these steps to use this pack:
1.Download this pack as zip file.

2.Unzip it and put it into resourcepacks folder. Make sure the structure is such:
![1](https://user-images.githubusercontent.com/58476103/110250556-d0df4280-7fb6-11eb-87ed-1cf0992861c0.png)

3.Go to Options../Resources Packs.. and make it into selected pack:
![2](https://user-images.githubusercontent.com/58476103/110250596-0c7a0c80-7fb7-11eb-83a1-3405970d5e57.png)

4.Now the main menu bgm has been changed to bgm in proxima and there isn't any lagging during playing it.

5.You can also get into a single player world and execute this command:
/playsound minecraft:chromaticraft.explorer @p
The bgm "explorer.ogg" will be played without any lagging.

**Comment by KuroPeach** [comment]
Thank you, this problem has bothered me for several game versions.

**Comment by KuroPeach** [comment]
emmmm, there is no effect, in the Proxima world, after the BGM is finished, it will get stuck.

**Comment by XenonDB** [comment]
> emmmm, there is no effect, in the Proxima world, after the BGM is finished, it will get stuck.

In fact, this pack is just telling Reika how may fix this problem rather than actually fix the problem.

Due to the strange registering way of music, I can't fix it even if I make a resource pack to replace those bgm.

I don't know why Reika don't want to use sounds.json but made an own way to register.

**Comment by KuroPeach** [comment]
：）

**Comment by ReikaKalseki** [comment]
The audio files ***are*** set to play as streaming sounds:

https://github.com/ReikaKalseki/ChromatiCraft/blob/master/World/Dimension/ChromaDimensionTicker.java#L75
https://github.com/ReikaKalseki/DragonAPI/blob/master/IO/DirectResourceManager.java#L81-L87

That appears to not matter entirely.

**Comment by XenonDB** [comment]
> The audio files _**are**_ set to play as streaming sounds:
> 
> https://github.com/ReikaKalseki/ChromatiCraft/blob/master/World/Dimension/ChromaDimensionTicker.java#L75
> https://github.com/ReikaKalseki/DragonAPI/blob/master/IO/DirectResourceManager.java#L81-L87
> 
> That appears to not matter entirely.

I _**do know**_ these files are set as streaming sounds.
However _**the behavior of these sounds**_ isn't as same as sounds registered with sounds.json. Just what I said here
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2751#issuecomment-783696282

_**Every time**_ playing sounds registered _**by your way**_ _**always causes lagging**_.
_**Only the first time**_ playing sounds registered by _**sounds.json**_ with _**stream:false**_ _**causes lagging**_.
_**No lagging**_ while playing sounds registered by _**sounds.json**_ with _**stream:true**_.

**Comment by ReikaKalseki** [comment]
I looked into the vanilla code when designing my sound loader and again when replying here. All the "streaming" entry in the json does is set a boolean in the internal object, the same one I linked here.
![https://i.imgur.com/5rQUxVc.png](https://i.imgur.com/5rQUxVc.png)

And there is nothing special about being loaded from json - all that does is list the files and where they are, rather than my direct-in-code system.
![https://i.imgur.com/E9QkWgJ.png](https://i.imgur.com/E9QkWgJ.png)
![https://i.imgur.com/pEDVT4i.png](https://i.imgur.com/pEDVT4i.png)

Also, my resource manager does not load *any* file repeatedly - it caches the byte[] loaded from disk the first time and always reuses that.

**Comment by XenonDB** [comment]
I made a profiling again for bgms both registered by sounds.json and yours.
This is thread dump when playing bgm registered by your custom system:
![1](https://user-images.githubusercontent.com/58476103/111296964-0e636000-8688-11eb-8b4b-97859bcdebda.png)

Since bgm registered by sounds.json doesn't cause lagging, I made a redstone clock to run playsound command lots of time and made a CPU profiling:
![2021-03-16_18 30 22](https://user-images.githubusercontent.com/58476103/111297257-61d5ae00-8688-11eb-9497-234cf2dbd345.png)
![2](https://user-images.githubusercontent.com/58476103/111297315-7619ab00-8688-11eb-8ce1-8079c5fd3d87.png)

I notice _**the call tree after getInputStream here doesn't contain your code (DirectResource etc.)**_ so I try calling getInputStream from these resource respectively.
![2021-03-16_18 36 27](https://user-images.githubusercontent.com/58476103/111300229-cd6d4a80-868b-11eb-9820-2ee0d18519e7.png)

```javascript
var clsRL = Java.type("net.minecraft.util.ResourceLocation");

var rs1 = new clsRL("custom_path:C:/Users/Noone/AppData/Roaming/.minecraft/modpacks/testpack_forge1.7.10/mods/Reika/ChromatiCraft/Music/polychromacy_c.ogg");
var rs2 = new clsRL("customnpcs:sounds/../../../../mods/Reika/ChromatiCraft/Music/polychromacy_c.ogg");

var m = Java.type("net.minecraft.client.Minecraft").func_71410_x().func_110442_L().func_110536_a(rs2);

npc.say(m);
npc.say(m.func_110527_b());
```

func_110527_b() is getInputStream().
Lagging happened at "npc.say(m.func_110527_b())" if I pass rs1 to getResource()
Script run happily if I pass rs2 to getResource().

I also checked which resource manager is used:
![2021-03-16_18 38 28](https://user-images.githubusercontent.com/58476103/111301331-0d80fd00-868d-11eb-87a8-20f8100f1515.png)
```javascript
var clsRL = Java.type("net.minecraft.util.ResourceLocation");

var rs1 = new clsRL("custom_path:C:/Users/Noone/AppData/Roaming/.minecraft/modpacks/testpack_forge1.7.10/mods/Reika/ChromatiCraft/Music/polychromacy_c.ogg");
var rs2 = new clsRL("customnpcs:sounds/../../../../mods/Reika/ChromatiCraft/Music/polychromacy_c.ogg");

var m = Java.type("net.minecraft.client.Minecraft").func_71410_x().func_110442_L();
var mf = m.class.getDeclaredField("field_110548_a");
mf.setAccessible(true);
npc.say(mf.get(m));
```

![2021-03-16_18 38 53](https://user-images.githubusercontent.com/58476103/111301430-2a1d3500-868d-11eb-953f-535138f1a341.png)

Finally,
![10](https://user-images.githubusercontent.com/58476103/111301855-a748aa00-868d-11eb-99af-185379d821e4.png)
![11](https://user-images.githubusercontent.com/58476103/111301859-a7e14080-868d-11eb-9fee-80d3a1154d7a.png)

>  my resource manager does not load any file repeatedly - it caches the byte[] loaded from disk the first time and always reuses that.

~~No, You always create new instance of DirectResource and doesn't prepare cache data for this~~
~~The data of newly DirectResource is always from reading a file instead of any caching data.~~

----------------------------------------------------------------------------------------------------------------------------------------
I think the actual reason is you read the whole bgm file all at once.
![30](https://user-images.githubusercontent.com/58476103/111339790-04a32200-86b3-11eb-8c06-3f7e0722c855.png)

Just give it a FileInputStream or something similar. It may not need to convert into ByteArrayInputStream.
![31](https://user-images.githubusercontent.com/58476103/111341037-19cc8080-86b4-11eb-8a9c-ba85dd4b5943.png)
![32](https://user-images.githubusercontent.com/58476103/111342421-6b293f80-86b5-11eb-9a0c-defcfb2bdde5.png)


By the way,  this is the result of first script above
rs1:
![2021-03-17_00 05 10](https://user-images.githubusercontent.com/58476103/111341745-c27ae000-86b4-11eb-96f8-f367f74d8ff2.png)
rs2:
![2021-03-17_00 05 21](https://user-images.githubusercontent.com/58476103/111341756-c575d080-86b4-11eb-864e-c92d97116342.png)

**Comment by ReikaKalseki** [comment]
The bytearray stream is to do the aforementioned caching - if it was just a plain inputstream it *would* load the file from disk every time.

**Comment by XenonDB** [comment]
However, you _**load whole 10+MB file all at once**_ for just creating ByteArrayInputStream.
JProfiler showed client thread was blocked here.

In the other hand, vanilla sound system _**never do that for streaming sound**_ since it _**loads large size sound segment by segment.**_

What you need to do is _**do not read it**_ and just give an input stream to it.

**Comment by ReikaKalseki** [comment]
I will need to do some redesigning of the loader system.

I suppose the sounds are not queued often enough that caching is a major concern - they are not loaded every few ticks to few seconds like the vast majority of game sounds, so the "disk overload" issue is not in play.

**Comment by ReikaKalseki** [comment]
Well, it works.
