### ISSUE TITLE
Visual issue with casting

### ISSUE THREAD

**Issue by qwahaha** [ReikaKalseki/Reika_Mods_Issues#2754]
I placed enough materials for 128 repeaters on a casting complex (cores on the casting table, and the necessary items on the stands)
There was a loot chest below the table to accept the output items.

It crafted all 128 repeaters in one go, but:
-The casting stands still looked like they had 4 items left (as if only 64 repeaters were crafted)
-When I right-clicked the casting table, the GUI showed 4 of each items on the stands

The items weren't actually there, so I couldn't just put more cores in on the casting table to craft more repeaters. Right-clicking the stands cleared the items. That is, when I right-clicked the stands, they stopped appearing to have items, but they didn't drop any items.

**Comment by qwahaha** [comment]
I got it again, but this time I wasn't crafting more than 64 items at once. Maybe it's because I moved far away from the complex while it was crafting?

**Comment by ReikaKalseki** [comment]
Yes, that is the cause. You were not in range to receive the sync packets. I have seen this myself since 2016; there is not really a fix I know of short of sending the packet to everyone on the server, which is kind of wasteful.

**Comment by ReikaKalseki** [comment]
OK, fixed.
