### ISSUE TITLE
Just implement this fixes in RotaryCraft

### ISSUE THREAD

**Issue by ChefMC** [ReikaKalseki/Reika_Mods_Issues#2756]
Hello, implement please this invulnerability (dupes / regions protecting issues) fixes:
https://github.com/gamerforEA/RotaryCraft-FakePlayers
(this man does them for V4c, just implement them in latest version).

You can search his code by finding all substrings "`gamerforEA code`"

**Comment by ReikaKalseki** [comment]
Most of his changes are just removing features, and the few that are not are done incorrectly and already not necessary with RC.
