### ISSUE TITLE
[ChromatiCraft V28a] A suggestion about the Chroma world.

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#2757]
Hello, reika. Can you change the settings of the Chroma world? The existing settings are too unfriendly to server players. Players will be disconnected when the network fluctuates, the world is refreshed, and the steady crystal of the maze is useless, even if you keep it The labyrinth is often disabled and cannot be interacted with. So recommended to change the setting of Chroma World to refresh the world after a few minutes without people.

**Comment by ReikaKalseki** [comment]
That is not how unloading works, nor is there a way to ensure that it will be deleted after a "deferred" unload.

Moreover, this is what persistence crystals are for.

**Comment by KuroPeach** [comment]
But the persistence crystals did not play a role. It retained the maze, but the maze was invalid and could not interact with the maze.
It is probably related to the tuning value. After logging in again, read the tuning value again?

**Comment by ReikaKalseki** [comment]
Tuning is not lost after relogging.

**Comment by KuroPeach** [comment]
That GG, my server players are crazy about this, :)

**Comment by ReikaKalseki** [comment]
?

**Comment by KuroPeach** [comment]
Refers to the interruption of the network connection, making the maze invalid and causing headaches for the player.

But this is meaningless, I used instructions to help them solve it. . .
