### ISSUE TITLE
Satisforestry Crash while exploring world (poison rock worldgen)

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2758]
https://pastebin.com/PHtxh7Lh

**Comment by ReikaKalseki** [comment]
This needs more information from new debug code.

**Comment by TheNodop** [comment]
Hi @Zsashas
I had a similar problem #2797 and the solution was removing Carpenters Blocks, would you mind trying that for your problem, too?

**Comment by ReikaKalseki** [comment]
....*Carpenters*? How?

**Comment by TheNodop** [comment]
I would like to know that, too. Especially since it did not update for the last couple of years.
But I can't argue with results and that was the solution to my problems. And this bug is "similar" as you said.
Edit: Updated 2019, so not a couple of years but still equally as confusing.
