### ISSUE TITLE
Crash with Mystcraft installed

### ISSUE THREAD

**Issue by Nanabell** [ReikaKalseki/Reika_Mods_Issues#276]
I installed the Ftb Infinity Pack and added some few mods to it e.g. rotarry- reactorcraft and dragonAPI
everything works fine untill i try to load up or create a new world with this error (http://pastebin.com/Bw8LrG7g) once i remove mystcraft everything works fine 
duno im not that good with modding maybe i just did something wrong or maybe its mystcraft fault hope you can help me

**Comment by ReikaKalseki** [comment]
Not on my end, and MapWriter is the only thing in the log.
