### ISSUE TITLE
Fusion Reactor Plasma Not Bending

### ISSUE THREAD

**Issue by SnakingGamer** [ReikaKalseki/Reika_Mods_Issues#2760]
The plasma in my reactor is ignoring the toroids and going in a straight line
![2021-03-10_18 30 16](https://user-images.githubusercontent.com/59903216/110714628-c8168880-81d1-11eb-85d4-48713d8789dd.png)

**Comment by SnakingGamer** [comment]
All my toroids are powered

**Comment by ReikaKalseki** [comment]
Your reactor is incomplete.

**Comment by squeakers0704** [comment]
I keep getting the same issue I checked the blueprint is still is not working

**Comment by ReikaKalseki** [comment]
If your reactor looks like the one here it is still incomplete.

**Comment by squeakers0704** [comment]
It all looks correct I can’t see where it is wrong

**Comment by ReikaKalseki** [comment]
How old is the guide you are following?

**Comment by squeakers0704** [comment]
The video on YouTube it’s the only thing I can find at least with out doing a bunch of digging

**Comment by ReikaKalseki** [comment]
Time to do some digging then. :P

**Comment by squeakers0704** [comment]
thanks i quite like the mod

**Comment by squeakers0704** [comment]
and something else I get is I get blue color plasma in the video its purple colder

**Comment by ReikaKalseki** [comment]
Because that video is seven years old.

**Comment by squeakers0704** [comment]
just tried again with the fusion reactor still isn't working but did get steam from a fission reactor

**Comment by squeakers0704** [comment]
the turbines don't work ether they turn 90 degrees

**Comment by squeakers0704** [comment]
turbines a broken and centrifugal fluid extractor doesn't work
