### ISSUE TITLE
DragonAPI randomly crashes the game.

### ISSUE THREAD

**Issue by ExtraOzone** [ReikaKalseki/Reika_Mods_Issues#2761]
While I'm playing the game will randomly crash out of nowhere with no warning. It apperas that there's no "certain" action that I do which triggers this crash, it just happens out of nowhere.

According to minecraft it has to do with DragonAPI and it trying to render something "Reika.DragonAPI.Extras.ThrottleableEffectRenderer". More specifically it talks about "doRenderParticles".

**Crash report:** https://pastebin.com/4Cy1zq9T

**Comment by ReikaKalseki** [comment]
This is not DAPI in and of itself - DAPI just redesigns the particle renderer.
