### ISSUE TITLE
[TreeClimbing] Natura's nether logs cannot be climbed

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2763]
Normally the trees generate upside-down so it makes sense that it might have been overlooked or whatever, but the logs can also generate in Dye Trees, so should be climbable. The other Natura logs seem to be working fine.

EDIT: None of the nether logs can be climbed. Fusewood, Darkwood, Bloodwood, or Ghostwood.

**Comment by ReikaKalseki** [comment]
Does the bedrock axe work on those trees?

**Comment by ReikaKalseki** [comment]
Fixed.
