### ISSUE TITLE
[CrC] Tool Compression Crate contents cannot be accessed without breaking

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2765]
Right-clicking the crate does nothing. This was previously stated to be the intended method of opening it.

**Comment by ReikaKalseki** [comment]
"Opening" is the wrong word, because it suggests a GUI.

Think more like the bedrock breaker or several Botania blocks.

Also, automation and AE still work.

**Comment by Shahelion** [comment]
Does it require an inventory to be attached to it or something? (Never used the bedrock breaker)

And Botania stuff usually works with left/right-clicking, but that does nothing with this block.

**Comment by ReikaKalseki** [comment]
Right clicking is supposed to remove the last-added item. That has now been added.
