### ISSUE TITLE
RoC turrrets not working

### ISSUE THREAD

**Issue by pajrle** [ReikaKalseki/Reika_Mods_Issues#2766]
screenshot:
![Screenshot from 2021-03-15 22-20-37](https://user-images.githubusercontent.com/56485090/111224839-45ca0200-85df-11eb-829d-cac5cd71a417.png)
log:
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6144701/latest.log)
As you can see on screenshot, laser gun fires its beam that still deals damage, but does not target anything. Gatling gun makes clicking sound when I load ammo, but does not shoot anything. All other turrets do not give any potentially useful info other than not working. I play on SetGameDifficultybyReika modpack ( I removed witchery and added botania and forbidden magic, and replaced nei with nei-GNTH ). Happens in singleplayer and my local server. Fact that laser turret shots beam and gatling gun clicks may suggest it is some issue with targeting. I gave all turrets proper ammo and 4194304 speed and torque, so it should not be my error.
Update: Pack developer tested it too, and it is broken for him too.

**Comment by XenonDB** [comment]
#2733
