### ISSUE TITLE
Rotarycraft pipes won't connect to sides of fuel powered engine.

### ISSUE THREAD

**Issue by atausend** [ReikaKalseki/Reika_Mods_Issues#2767]
![2021-03-16_03 00 32](https://user-images.githubusercontent.com/24421116/111275611-5476e000-8604-11eb-9df7-c9213c96d07f.png)

**Comment by ReikaKalseki** [comment]
The engine only receives fuel from the bottom.

**Comment by atausend** [comment]
It also needs water and lubricant to function. The bottom still accepts piping.

**Comment by ReikaKalseki** [comment]
Fixed.
