### ISSUE TITLE
AutoCrafting Unit Sustain mode not working ?

### ISSUE THREAD

**Issue by Axylxys** [ReikaKalseki/Reika_Mods_Issues#277]
Hello,

After playing a bit with the AutoCrafting Unit sustain mode, i just can't get it to work so far.
Request mode and Continuous mode work fine as usual.
The setup is quite basic (screenshots above), a DC engine powering it, and it's connected to the AE system (the other modes working well are proof it's not a connection issue, i guess).

Screenshot of the setup here: http://pasteboard.co/M9FTIYm.png
The table interface itself:  http://pasteboard.co/M9Y8KoS.png

The recipe is a magical crop one, 8 nether essence to make 8 Soul Sand. The second recipe is a test one (lantern from Railcraft) to confirm it's not a magical crop issue.

The AE network has enough essence and no soul sand, yet the autocrafting unit doesn't craft anything.

Am i missing something, or is there an issue with it ? I found few documentation, even the in game book doesn't seem to mention the Sustain mode so i thought maybe it's not supposed to be working properly, despite being in the patch notes.

Thanks in advance !

**Comment by ReikaKalseki** [comment]
Sustain mode uses the AE crafting CPU. Are they available?

**Comment by Axylxys** [comment]
We have a basic 4K Crafting Storage Unit and it doesn't work. We also tried adding a Crafting Co-Processing Unit and no success either, are there other prerequisites we're missing ? We actually didn't know about the AE crafting CPU requirement (info on the AutoCrafting Unit seems really difficult to find) though we happened to have one already, and we tried all combinations we could think about with it, but our AutoCrafting Unit just seems to be lazy.

Also if it helps, AE version is the rv2 stable-10.

**Comment by ReikaKalseki** [comment]
Is the CPU available (i.e. not busy)?

**Comment by Axylxys** [comment]
It is not busy at all, No crafting Job Active on the AE panel and we almost don't have any pattern anyway as the world is only a few days old.

**Comment by ReikaKalseki** [comment]
I just tested, and it works fine. However, I realized something I forgot and you may not have: The AE crafting system needs the pattern as well, or it cannot craft the item.
