### ISSUE TITLE
from PostInit() to Available : DragonAPI ModCropList crashes (V29a)

### ISSUE THREAD

**Issue by pbk20191** [ReikaKalseki/Reika_Mods_Issues#2770]
I know that my minecraft instance is very huge, but until the very last version update of Reika's mod (before v29a), it was going back without any problems. But after this update, this crash appear.

[crash-2021-03-23_21.40.03-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6189729/crash-2021-03-23_21.40.03-client.txt)

This is the failed classes report file I found in my minecraft instance.
[Reika.DragonAPI.ModRegistry.ModCropList.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6189749/Reika.DragonAPI.ModRegistry.ModCropList.zip)

[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6189738/latest.log)

**Comment by ReikaKalseki** [comment]
The crash is fixed, but the underlying failure to fetch the other mod's data needs more info from new logging.

**Comment by pbk20191** [comment]
> The crash is fixed, but the underlying failure to fetch the other mod's data needs more info from new logging.

You mean, report new log after the bug fix updates? or report several crash logs and new logs after bugfix updates?

**Comment by pbk20191** [comment]
@ReikaKalseki 

no crashing from this issue Hooray!

Here is the new log
[2021-03-24-latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6194955/2021-03-24-latest.log)


This is out of topic, but I wander why this failed class files generated. I don't have mystcraft and frameblacklist(? maybe for projectRed? but I don't think this class file is related to the projectRed, at least what read from this log)
[FailedClasses.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6194948/FailedClasses.zip)

**Comment by ReikaKalseki** [comment]
`Error loading crop ENDER from ExtraUtilities with metadatas [0,7]: Block not instantiated @ com.rwtema.extrautils.ExtraUtils#enderLily!`

And yet...
![https://i.imgur.com/KrWYCky.png](https://i.imgur.com/KrWYCky.png)


...Wait, do you have ender lilies disabled?

**Comment by pbk20191** [comment]
> `Error loading crop ENDER from ExtraUtilities with metadatas [0,7]: Block not instantiated @ com.rwtema.extrautils.ExtraUtils#enderLily!`
> ...Wait, do you have ender lilies disabled?

my Bad. It is. I will send you new log

**Comment by pbk20191** [comment]
@ReikaKalseki 
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6201188/latest.log)

Ender Lily is safe.

**Comment by ReikaKalseki** [comment]
And now everything is loading correctly. OK, I need a way of differentiating a reflective failure from the block being disabled.
