### ISSUE TITLE
V29b crash with 'Tinkerer'

### ISSUE THREAD

**Issue by TheNodop** [ReikaKalseki/Reika_Mods_Issues#2773]
Updated your Mods to V29b, nothing else changed in modpack.
Now it crashes with the newest Tinkerer (TConstruct afaik) Version.
Sorry if I am missing something/this is my fault.
(Currently using the alpha TC Version wanted to see if that works, also did not work with latest stable)
[crash-2021-03-24_11.39.00-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6196367/crash-2021-03-24_11.39.00-client.txt)

Just tested without TConstruct, works. So that must be the culprit.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by TheNodop** [comment]
Thank you for fixing this. :)
But I think I need to wait for the next release, right?

**Comment by ReikaKalseki** [comment]
Yes.

**Comment by jakbruce2012** [comment]
Woops, did a search but did not go back far enough.  Thanks for closing.
