### ISSUE TITLE
[V29b] Hosting a server impossible with DragonAPI and a mod that depends on it

### ISSUE THREAD

**Issue by LokeTheChamp** [ReikaKalseki/Reika_Mods_Issues#2777]
Hello, I was trying to set up a server to play on with a few friends. Installing the mods on a singleplayer world worked perfectly fine, however when trying to set up a Forge server, the server crashes when it contains DragonAPI and another mod that depends on it. (crash log is here https://pastebin.com/pyLdmeQk).

How to reproduce: Download forge-1.7.10-10.13.4.1614 from the official website.
Install the server by choosing "Install server" and a directory of your choice
Execute forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
Open eula.txt and change "false" to "true"
Put DragonAPI and ChromatiCraft [V29b] into the "mods" foulder.
Execute forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
See how the server crashes and generates a crash log similar to that in the pastebin

Is there anything I have done wrong, do I need to change the configuration or what is the issue here? I am sadly pretty illiterate when it comes to crashlogs so I have no idea.

**Comment by Star4Fun** [comment]
It's a problem that already has been fixed, but the fixed version isn't published yet. (#2774)

**Comment by LokeTheChamp** [comment]
Thanks for the info, I'll just wait then.
