### ISSUE TITLE
Tinker's construct incompatibility V29a and b

### ISSUE THREAD

**Issue by jakbruce2012** [ReikaKalseki/Reika_Mods_Issues#2778]
Linked is the crash report citing incompatibility with "tinkerer".

https://pastebin.com/EAZJHjSQ

I have tried several versions all with no better results.  I am really stuck.
This issue began immediately after updating to V29a, and then to V29b.  Please help if I've missed something critical here.
Need a way to get these two playing together again.

**Comment by ReikaKalseki** [comment]
#2773
