### ISSUE TITLE
Some suggestions for ReactorCraft and ElectriCraft.

### ISSUE THREAD

**Issue by OneEyeMaker** [ReikaKalseki/Reika_Mods_Issues#278]
Hello.
Firstly, great thanks for your mods!
Secondly, I have some suggestions for ReactorCraft and ElectriCraft.
1) Add configuration options to increase/decrease turbine output. In some modpacks turbine and HP turbine are too weak or too powerful (second option happens more often). It can look like so:

```
    D:TurbineTorqueMultiplier=1.0
    D:TurbineSpeedMultiplier=1.0
    D:HPTurbineTorqueMultiplier=1.0
    D:HPTurbineSpeedMultiplier=1.0
```

2) Add to ElectriCraft energy storage with larger capacity (for ElectriCraft energy and for RF). Now HP turbine fills any storage too fast...
3) Add to ReactorCraft configuration options to disable world generation of each ore at all (as it made in RotaryCraft and ElectriCraft). 

And thank you for your work!

**Comment by ReikaKalseki** [comment]
1) Absolutely not. Their values are based on their real-world counterparts, and additionally are meant to far outstrip things like BigReactors. There is a reward for the increased difficulty and risk.

2) The RF storage is 1.2 TRF. That takes quite some time to fill. Want more storage? Build more of them. No larger ElC storage is necessary or desirable.

3) No. Wanting to disable the ore with no replacement - and thus make the mod unusable - is pointless.
