### ISSUE TITLE
[RoC] Crash on Server join with RotaryCraft Gearbox Render (29c)

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2780]
Seem to have had a bedrock gearbox left in my Inventory(from 28), now client instantly crashes when joining the server.
```
-- Item being rendered --
Details:
	Item Type: Reika.RotaryCraft.Items.Placers.ItemGearPlacer@391fee00
	Item Aux: 3
	Item NBT: {damage:0,bearing:0b,type:"BEDROCK",lube:0}
	Item Foil: false
```
https://gist.github.com/MalTeeez/8c27c9da33dfeb0a7187a8c2b57416e3

**Comment by MalTeeez** [comment]
I was able to delete the item from my Inventory via the playerdata file, here's a video showing the other bugged items in my ME


https://user-images.githubusercontent.com/41554385/112619311-77389e00-8e27-11eb-937e-35f2cde0b16e.mp4

**Comment by ReikaKalseki** [comment]
I fixed the crash, but you will need to place and re-mine all the gearbox items; they are now invalid.
