### ISSUE TITLE
Satisforestry World not Loading/Creating and type crash after initial start.

### ISSUE THREAD

**Issue by TheNodop** [ReikaKalseki/Reika_Mods_Issues#2782]
Two problems:
The first one is simple, Satisforestry (and also CaveControl) do get the type-error every time I start the game, except when the configs and files are deleted, then they start just fine and create these files.

The second problem is a bit harder to describe..
When the game starts (so the files were deleted first) I can go to the create a World menu and even start creating a world but it stops after a very small time.

The vanilla log just says "Generating Keypair" and nothing more.
The fml-log again talks about this type problem.
I attach the log for the second problem, if you need one for the first please tell me.
[fml-client-latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6213395/fml-client-latest.log)

**Comment by ReikaKalseki** [comment]
#2772
