### ISSUE TITLE
[ReC] Steam line readout returns NaN%

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2783]
When placing a steam line on top of a boiler it first shows the contents with a number (even though it has a lot of post decimal values) but after some time, ~4 mins, it returns NaN%.
![Screenshot_257](https://user-images.githubusercontent.com/41554385/112705589-e5b94280-8e9f-11eb-9425-f00d9aa1485f.png)

![Screenshot_256](https://user-images.githubusercontent.com/41554385/112705576-d1754580-8e9f-11eb-9b1d-796085607f5b.png)

Since the steam lines still work in transferring the steam to the turbines, I assume this is just printing out the insane number being non-functional

**Comment by pbk20191** [comment]
Does it works with HP Turbine too? HP Turbine don't accept steam with invaild Reactor source types.
Any Steam that passes Pump return Reactor source type ` NaN ` to me

**Comment by ReikaKalseki** [comment]
Fixed.
