### ISSUE TITLE
ReC Heat Exchanger cold fluid cannot be extracted with any other fluid system

### ISSUE THREAD

**Issue by pbk20191** [ReikaKalseki/Reika_Mods_Issues#2784]
Only RotaryCraft BedRock and normal fluid pipe can extract cold fluid from heat exchanger.

**Comment by MalTeeez** [comment]
Still works for me with export bus ![Screenshot_258](https://user-images.githubusercontent.com/41554385/112720563-6c513c80-8eff-11eb-8890-63e14c085b73.png)

**Comment by MalTeeez** [comment]
Still works for me with fluid export bus ![Screenshot_259](https://user-images.githubusercontent.com/41554385/112720638-d9fd6880-8eff-11eb-82bb-6273a5c92e32.png)

**Comment by pbk20191** [comment]
> Still works for me with fluid export bus !

Well, I didn't try that one. What I tried with, are Thermal Dynamics, EnderIO and Steve's Factory Manager

**Comment by ReikaKalseki** [comment]
All R(e)C machines, when working with non-RC piping, use up/down as extraction only and sides as input only.
