### ISSUE TITLE
Shaft Junction throws java.lang.ClassCastException with Power Distribution Clutch

### ISSUE THREAD

**Issue by pbk20191** [ReikaKalseki/Reika_Mods_Issues#2787]
This happen whenever Shaft Juction direct input from DistributionClutch. It doesn't matter if it actually have power or not.

I think this handles the information
DRAGONAPI ERROR: Tile Entity Shaft Junction @ DIM0: -1697, 20, -1049 [SERVER] is throwing class java.lang.ClassCastException on update: Reika.RotaryCraft.TileEntities.Transmission.TileEntityDistributionClutch cannot be cast to Reika.RotaryCraft.TileEntities.Transmission.TileEntityPowerBus

When the config `B:"[R9F5AE60F] Run power transfer code on client"=true` is enabled, huge chat message about this error keeps generating.
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6215410/latest.log)

When the config is disabled, chat message does not appear but server log generate same message.
[config disabled latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6215406/config.disabled.latest.log)

![2021-03-27_17 33 05](https://user-images.githubusercontent.com/29122714/112715961-eba63680-8f26-11eb-86c0-6822b3d0b874.png)
![2021-03-27_17 33 11](https://user-images.githubusercontent.com/29122714/112715965-eea12700-8f26-11eb-9e03-94e849c6e819.png)

In my very subjective guess, #2753 and this issue have same causes

**Comment by impbk2002** [comment]
Maybe this is related to the Config : `    B:"[R9F5AE60F] Run power transfer code on client"=true` This issue happen when this config is enabled. I'll test if it happens without this config enabled

**Comment by ReikaKalseki** [comment]
Fixed.
