### ISSUE TITLE
[ReC] Steam lines show reactor source types occasionally, contain NULL type

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2788]
Sorry to bother you again about this, 
After updating the steam line readout now rarely returns the reactor source types, otherwise it just returns the simple info:
![Screenshot_260](https://user-images.githubusercontent.com/41554385/112720966-b9cea900-8f01-11eb-97b5-49d2db553d0e.png)

But sometimes (Only seems to happen near boilers) it returns the Reactor source types, but along with a NULL type:
![Screenshot_261](https://user-images.githubusercontent.com/41554385/112720994-d8cd3b00-8f01-11eb-8e3d-838d8159cfe7.png)

**Comment by ReikaKalseki** [comment]
Fixed.
