### ISSUE TITLE
[ChromatiCraft] A suggestion about the crystal furnace

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#2789]
Recently I tried to integrate ChromatCraft and GregTech to play together. One of the problems is that the Crystal Furnace will double any non-powder smelt, which causes the GT recycled material to double the item. Can you add a custom setting about it in subsequent versions.? Add a custom limit to the crystal furnace, such as ignoring certain mods, so that the smelting recipe is not doubled. 
![image](https://user-images.githubusercontent.com/19620848/112726257-5e2f0a80-8f57-11eb-80bd-904e344f2f8f.png)

**Comment by ReikaKalseki** [comment]
I am not making it configurable - that will just see packs try and make it not duplicate *any* items, as I have already been asked for configs to do.

I need a clean way of identifying these items - do they have a common class or something?

**Comment by KuroPeach** [comment]
Sorry, I don’t know how to read the source code, I only found this about recycling, it feels useless
https://github.com/Blood-Asp/GT5-Unofficial/blob/77a3c956e510b7c8ef4654054bcb16a0fccb86f7/src/main/java/gregtech/loaders/oreprocessing/ProcessingRecycling.java

**Comment by ReikaKalseki** [comment]
This is recipe code. I was asking if all these "recycled parts" are like ItemGregPart or something.

**Comment by KuroPeach** [comment]
Sorry, It's too hard for me to read the source code, or do you use the same processing method as the dust?

toolHeadWrench
toolHeadHoe
toolHeadArrow
toolHeadShove
Universal
arrowGTPlastic
arrowGTWood

gearGtSmall
springSmall
spring
stick
stickLong
bolt
wireFine
wireGt02
pipeTiny
ring
foil
itemCasing
screw
nugget
round

craftingWire
cableGt01
cableGt02

crushed
crushedCentrifuged
crushedPurified

There should be another way. The material and equipment of GT use the same registered ID, the difference is just the damage value.

<gregtech:gt.metaitem.01:*>
<gregtech:gt.metaitem.02:*>
<gregtech:gt.metaitem.03:*>
<gregtech:gt.metaitem.99:*>
<gregtech:gt.blockmachines:*>

**Comment by ReikaKalseki** [comment]
```
There should be another way. The material and equipment of GT use the same registered ID, the difference is just the damage value.

gregtech:gt.metaitem.01:*
gregtech:gt.metaitem.02:*
gregtech:gt.metaitem.03:*
gregtech:gt.metaitem.99:*
gregtech:gt.blockmachines:*
```

This will do it.

**Comment by ReikaKalseki** [comment]
Done.
