### ISSUE TITLE
Cosmetic suggestion for ReactorCraft

### ISSUE THREAD

**Issue by InitHello** [ReikaKalseki/Reika_Mods_Issues#279]
I've been chewing on this idea for a few months now:

When the fusion plasma enters the toroid magnets, I feel it would look cool if it became compressed into a thin stream of plasma rather than balls of plasma spinning around. Maybe a thicker stream as it exits the injector, compressing rapidly in the magnets. I also would like to see the compressed plasma (maybe based on the average number of fusion events in the last 20 seconds, or some such) increasing the light level, since the first fusion reactor I saw in the physical world produced quite a bit of light.

**Comment by ReikaKalseki** [comment]
> I also would like to see the compressed plasma (maybe based on the average number of fusion events in the last 20 seconds, or some such) increasing the light level, since the first fusion reactor I saw in the physical world produced quite a bit of light.

Entities cannot generate light. However, as of v8, active toroids do.

> I feel it would look cool if it became compressed into a thin stream of plasma rather than balls of plasma spinning around. Maybe a thicker stream as it exits the injector, compressing rapidly in the magnets.

This _is_ more realistic, but I think it would look rather worse...

**Comment by InitHello** [comment]
> as of v8, active toroids do.

Ooh, I like that.

> I think it would look rather worse...

Your call, obviously. I'm an absolute chimpanzee when it comes to visual design, so I'll yield to your demonstrated skill in that regard.

**Comment by ReikaKalseki** [comment]
I have decided against this, at least for now.
