### ISSUE TITLE
Crashing While Loading World

### ISSUE THREAD

**Issue by RobTheFox** [ReikaKalseki/Reika_Mods_Issues#2790]
https://paste.ee/p/KZRuT

I tried loading up a fresh world for the first time and this is the result.

**Comment by ReikaKalseki** [comment]
This has nothing to do with my mods - it looks like you have null being placed as a biome.
![https://i.imgur.com/h39GeeO.png](https://i.imgur.com/h39GeeO.png)

**Comment by RobTheFox** [comment]
Is there any way to fix this or am I stuck?

**Comment by ReikaKalseki** [comment]
Check your mods and your configs. Something is likely set up incorrectly.

**Comment by RobTheFox** [comment]
I'll have a look.

**Comment by RobTheFox** [comment]
I tested a new world just using your mods and two things happened. 
I got this for loading a default world: https://paste.ee/p/zvLY4

I got this after loading a superflat world: 
![2021-03-29_14 20 52](https://user-images.githubusercontent.com/80653499/112872181-a3a82080-909a-11eb-8fa8-ce1cbffceffb.png)

Both are using the most recent version.

I can't see anything, and the middle brightens up when I get close to something and makes a loud humming noise.

**Comment by ReikaKalseki** [comment]
You are standing next to a pylon.

As for why your screen is black...try resizing it.

**Comment by RobTheFox** [comment]
That helped. I can see now. Thanks.
What do I do about the default world though?

**Comment by ReikaKalseki** [comment]
See #2797

**Comment by RobTheFox** [comment]
I appreciate the work you put into this Reika. They're really well done mods.

**Comment by ReikaKalseki** [comment]
> I appreciate the work you put into this Reika. They're really well done mods.

:)

Tell me if you see any of the error messages I describe in the other issue.

**Comment by RobTheFox** [comment]
I updated the mods and the default world works fine now. If I come across any more problems, I'll let you know.

**Comment by RobTheFox** [comment]
I just tested the mods with my 1.7.10 modpack (the same one I had trouble with before) and they all work with no problems! Thanks so much for the help and the work you put into the mods to fix the bugs!
