### ISSUE TITLE
breaking chain drive cause Ticking memory connection (NullPointerException)

### ISSUE THREAD

**Issue by pbk20191** [ReikaKalseki/Reika_Mods_Issues#2791]
I placed two chain drive, and then I break one of them and crashed. two are not linked.

[crash-2021-03-28_21.46.45-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6217313/crash-2021-03-28_21.46.45-server.txt)

this log is from normal Java8
[crash-2021-03-28_22.03.54-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6217327/crash-2021-03-28_22.03.54-server.txt)

**Comment by ReikaKalseki** [comment]
Fixed.
