### ISSUE TITLE
[RC] (Feature/Bug) Gas Turbine with ECU doesn't control afterburner

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2793]
The Engine Control Unit doesn't control the afterburner on the gas turbine, furthermore the upgrade seems to overwrite it, E.g. even if a gas turbine is disabled via redstone it will still turn on if someone clicks the afterburner icon.
I tagged this as Feature/Bug since I'm unsure if this was intentional, if it wasn't considered id like to request this as a feature since being able to control the full power gas turbines would be nice to have.

**Comment by ReikaKalseki** [comment]
The ECU was broken completely.

However, *afterburning specifically* is intended to - and is explicitly coded to - bypass the ECU.
