### ISSUE TITLE
(Feature/Bug) Powersuit's Powerfist doesn't return RC&ReC Machines 

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2794]
The Powerfist from Modular Powersuits doesn't harvest machines from RC&ReC, it just seems to delete them.
Since this could be a mistake I looked into their Powerfist class but it seems normal over there, could this be some weird mod interaction? (https://github.com/MachineMuse/MachineMusePowersuits/blob/1.7.10-Java/src/main/java/net/machinemuse/powersuits/item/ItemPowerFist.java)

**Comment by ReikaKalseki** [comment]
This is not a bug. A fist is not programmed as a tool, and for all mining code counts as an empty hand. This has been the case since this was first reported in 2013.
