### ISSUE TITLE
[RotaryCraft+1.7.10+V29g] Crash when launching in Chinese

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#2799]
Crash when launching in Chinese, Only delete the built-in Chinese manual language file to start.
Can you cancel the hash verification of the manual file?
https://paste.ubuntu.com/p/txqvzxtjYW/

**Comment by ReikaKalseki** [comment]
This has nothing to do with hash verification. This is that file being written incorrectly. Because I do not speak chinese, I cannot make a corrected version.

**Comment by KuroPeach** [comment]
It should not be that the file is wrong. I started using the recently submitted pt_BR and it crashed directly. I also tried to directly overwrite the original English manual into zh_CN, which also crashed directly. 

Actually we have players doing the translation, but we are afraid that it will be locked by the hash verification, which will make the translation maintenance inconvenient, so we have not submitted it. https://github.com/MerryYukari/Reika_mods_Localization

[pt_BR](https://paste.ubuntu.com/p/XsBDyms92v/)
[overwrite zh_CN](https://paste.ubuntu.com/p/tdh5vX4Dk8/)

**Comment by KuroPeach** [comment]
And i also tried to add a zh_TW directory, and then copy the initial English manual into it, it will not crash at this time. But copy the initial English manual to zh_CN, it will crash, so I think there is document verification, but you forgot

> This has nothing to do with hash verification.

**Comment by ReikaKalseki** [comment]
> It should not be that the file is wrong. 

That error makes it extremely clear - the file messed with the variable placeholders.

> I started using the recently submitted pt_BR and it crashed directly

That one is wrong too.

> And i also tried to add a zh_TW directory, and then copy the initial English manual into it, it will not crash at this time. But copy the initial English manual to zh_CN, it will crash, so I think there is document verification, but you forgot

No, that (lack of) crash is because moving it to zh_TW causes it to be ignored entirely.

**Comment by KuroPeach** [comment]
> No, that (lack of) crash is because moving it to zh_TW causes it to be ignored entirely.

So then cover into zh_CN should be ignored, but it crashed

**Comment by ReikaKalseki** [comment]
What?

**Comment by KuroPeach** [comment]
According to what you mean, copy the original English manual to zh_CH, should also be ignored, but the game just crash

**Comment by KuroPeach** [comment]
I spent some time sorting out the text. It can start and load normally under zhTW, but zhCN will [crash](https://paste.ubuntu.com/p/2yTHdGt4wq/). Is there really no verification like hash? Can you remove the built-in zhCN manual in subsequent versions?
![image](https://user-images.githubusercontent.com/19620848/113111423-c7a26800-923a-11eb-9a71-4d3bb9686ff1.png)
![image](https://user-images.githubusercontent.com/19620848/113111469-cf620c80-923a-11eb-8004-09d9336adcf5.png)

> What?

**Comment by ReikaKalseki** [comment]
I can certainly move the CN to being a TW localization, but I think that will probably break it for everyone using "native" Chinese. I obviously know nothing about the languages' similarity level, so I have no idea if this is equivalent to switching from US to UK English (aka not a big deal at all) or more like switching from German to Dutch.

Also, I will need the updated files.

**Comment by KuroPeach** [comment]
But the translator is not there, only occasionally someone takes over, and the built-in manual is too old. Often it cannot be used, it is best to delete it directly. In fact, several of your other mods have also been translated. However, after the roc built-in Chinese manual, it cannot be changed. No one is willing to submit a new localization of your mod, worrying that other mod manuals cannot be modified, all only exist in the warehouse. and translators don't have time to update it all the time.

So I still hope you can remove the built-in Chinese manual. Can't change the localization, it's really bad

> but I think that will probably break it for everyone using "native" Chinese.

Don't worry about destroying localization. In the main BBS, we teach players how to add manually localization for mod

**Comment by ReikaKalseki** [comment]
BBS?

**Comment by KuroPeach** [comment]
> BBS?

Bulletin Board System, like https://www.minecraftforum.net/forums

I suddenly encountered a new problem. After restarting the laptop, all the textures of the ROC machine block were lost. It was also lost when I switched to the integrated display. The chat bar indicated an OpenGL1282 error, and I could not find the reason.
![image](https://user-images.githubusercontent.com/19620848/113231697-67f59c80-92ce-11eb-9e2e-1643817b9da7.png)

**Comment by KuroPeach** [comment]
Happy April Fool’s , You fooled me, I asked other players if it’s an April Fool’s Day egg,

**Comment by ReikaKalseki** [comment]
![https://i.imgur.com/jQEBL5c.png](https://i.imgur.com/jQEBL5c.png)
![https://i.imgur.com/EaXzcfJ.png](https://i.imgur.com/EaXzcfJ.png)
![https://i.imgur.com/AiTyFaG.png](https://i.imgur.com/AiTyFaG.png)
![https://i.imgur.com/2HquSQA.png](https://i.imgur.com/2HquSQA.png)

**Comment by KuroPeach** [comment]
![image](https://user-images.githubusercontent.com/19620848/113241148-a72ce900-92e0-11eb-983e-97db4af8ce69.png)

**Comment by ReikaKalseki** [comment]
Oh yes. :P
