### ISSUE TITLE
Last Toroid in Fusion Reactor not active

### ISSUE THREAD

**Issue by zemerick** [ReikaKalseki/Reika_Mods_Issues#28]
I noticed in the code before there appears to be an off by one:

In the Solenoid TE, addToToroids:

```		while ((r == ReactorTiles.MAGNET || r == ReactorTiles.INJECTOR) && c < 38) {```

The c < 38 needs to be <= 38, or <39.

As it is, it is failing to update the very last toroid with hasSolenoid. ( East side, just south of the injector ) Because of this, this toroid is not consuming LN2.

Any action to update this toroid while the Solenoid is running, will properly copy the status of the neighboring toroid and cause it to consume LN2. This includes placing the toroid after the solenoid is running, and the previous toroid has already updated to receive hasSolenoid, or simply spinning the toroid 360 degrees.

**Comment by madolinn** [comment]
Are there 39 magnets or 38? Typically you start at 0, which would give 38 indexes.

**Comment by zemerick** [comment]
36 magnets, 4 injectors. This gives you 40, but it effectively counts the gaps, and you don't need to cross the last gap as it just brings you back to the first injector ( East btw. )

So, that means we need to make 39 checks. It starts at 0, so < 39 or <= 38 would work.

**Comment by ReikaKalseki** [comment]
I changed the counter to <= 38. Oddly, I seem to remember changing this previously; hopefully, I am not introducing an old bug.

**Comment by zemerick** [comment]
I''l try poking through the history of the file and see if it was ever changed. If so, the context might give you an idea of why it was reverted.

I'll also make sure to keep any eye out for anything on the next release related to the fusion reactor toroids.

**Comment by ReikaKalseki** [comment]
I see...
