### ISSUE TITLE
DragonAPI fails to load world

### ISSUE THREAD

**Issue by Samario1** [ReikaKalseki/Reika_Mods_Issues#280]
After finding another, unrelated, bug with Chromaticraft and Gregtech fighting over ore gen, I disabled Gregtech and got it still failing to load a world - I then installed _only_ the latest DragonAPI and it still occurred.
http://pastebin.com/CeZErNy4

**Comment by Samario1** [comment]
This appears to happen even with DragonAPI uninstalled.
EDIT: this appears to be Forge on its own crapping out, this ain't your problem Reika

**Comment by ReikaKalseki** [comment]
That is all vanilla render code.
