### ISSUE TITLE
[RC] Pulse Jet Furnace overheats regardless of water

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2800]
In 29g of RotayCraft the Pulse Jet Furnace overheats (explodes) regardless of water inside it.

![Screenshot_263](https://user-images.githubusercontent.com/41554385/113043060-37ade100-919c-11eb-8ff6-512c6148959f.png)

Overheats:
![Screenshot_264](https://user-images.githubusercontent.com/41554385/113043256-7b084f80-919c-11eb-8ba2-faa4eb2abf8c.png)

Probably related to your recent changes to it (https://github.com/ReikaKalseki/RotaryCraft/commit/f4cbbb2be035c9febd55a475b54055b6b1c8e662#diff-3b439d28df9198820ad1c6c83ec2b44184b49f2baa51b03137786d4e801393b0)

**Comment by ReikaKalseki** [comment]
I accidentally left in the nether testing code.

**Comment by RezaSmith** [comment]
is there any chance we get an update for this? half my storage got blown up and i got fked over this, if not what version has it fixed?(for downgrading) 
thanks

**Comment by ReikaKalseki** [comment]
It is already fixed for the next update.
