### ISSUE TITLE
[v29g] Almost all placable blocks have bad texture

### ISSUE THREAD

**Issue by lee321987** [ReikaKalseki/Reika_Mods_Issues#2802]
First pic is a DC Electric Engine and a couple gear boxes.
Third pic is showing ONLY blocks from RotaryCraft.
![001](https://user-images.githubusercontent.com/18412921/113259778-855d4300-929b-11eb-81f9-9c06bb82ba07.jpg)
![002](https://user-images.githubusercontent.com/18412921/113259781-85f5d980-929b-11eb-8d2f-35f82c76e8a3.jpg)
![003](https://user-images.githubusercontent.com/18412921/113259784-868e7000-929b-11eb-8987-71853e9264b7.jpg)

**Comment by Mettymagic** [comment]
lol

**Comment by Star4Fun** [comment]
Look at the date ;) I was confused too.

**Comment by lee321987** [comment]
@Star4Fun ah lol thank you.

**Comment by squeakers0704** [comment]
I'm getting the same thing

**Comment by squeakers0704** [comment]
I keep getting post render errors

**Comment by squeakers0704** [comment]
i figured it out
