### ISSUE TITLE
(ArchiSections) Serverside crash when ArchiSections and Pistronics2 are installed.

### ISSUE THREAD

**Issue by wasakoki** [ReikaKalseki/Reika_Mods_Issues#2803]
[crash-2021-04-01_22.21.12-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6247523/crash-2021-04-01_22.21.12-server.txt) / https://pastebin.com/pBf2fPpX

to reproduce simply run a forge server with latest version of Archisections + DAPI, and [Pistronics2](https://www.curseforge.com/minecraft/mc-mods/pistronics-2) mod. crash doesnt seem to occur when testing on a singleplayer world.
let me know if more info is needed.

**Comment by ReikaKalseki** [comment]
Fixed.
