### ISSUE TITLE
[RotaryCraft] Texture Error

### ISSUE THREAD

**Issue by wojhd007** [ReikaKalseki/Reika_Mods_Issues#2804]
I have installed the latest version of RotaryCraft for my private package. As I saw, the textures of the machines from this mod are different, gray with purple marks and black inscriptions.
![image](https://user-images.githubusercontent.com/69419360/113413292-9a7cc380-93ba-11eb-954b-fb9f4adc3492.png)

**Comment by MalTeeez** [comment]
Duplicate of #2802 and many more, It's related to April Fools, should go away soon.
