### ISSUE TITLE
Cheating the channeled flow puzzle

### ISSUE THREAD

**Issue by qwahaha** [ReikaKalseki/Reika_Mods_Issues#2805]
If I shift and right click, I can place blocks in the channeled flow puzzle rooms. With just a few cobblestone blocks I can spread the everfluid water to the entire room, or I can place a cobble block then a water bucket, and the water from that can unlock the barriers.

I can also place a block to destroy the everfluid block.

On a side note, I'm trying to get the "Finding a shortcut" progression but nothing I tried triggered it. How exactly do you get that?

**Comment by ReikaKalseki** [comment]
> On a side note, I'm trying to get the "Finding a shortcut" progression but nothing I tried triggered it. How exactly do you get that?

By (trying to) cheat in one of the ways I *did* forsee. :P

**Comment by ReikaKalseki** [comment]
Fixed.
