### ISSUE TITLE
Skystrike destroys the purple barrier at puzzle entrances

### ISSUE THREAD

**Issue by qwahaha** [ReikaKalseki/Reika_Mods_Issues#2806]
At the entrance to most of the puzzle rooms, there's a purple barrier that stops you from falling quickly. I don't know what it's called. The skystrike ability can destroy it.

Skystrike doesn't destroy most of the other blocks in puzzle structures so this seems odd.

**Comment by ReikaKalseki** [comment]
That block is not a dimension structure block; it is not unbreakable. That said, I can make skystrike skip it.

**Comment by ReikaKalseki** [comment]
Done.
