### ISSUE TITLE
Toroid Magnet's switching between "Next: 1/0", weird plasma behavior

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2807]
**To start, this is 99% User Error but since I've run out of ideas might as well consider it an Error.**

My fusion reactors plasma randomly injects towards both sides when the solenoid and the first toroid magnet (from the injector facing direction) are active.
![Screenshot_279](https://user-images.githubusercontent.com/41554385/113510834-fed78880-955c-11eb-958e-17ebe9764383.png)

After having read #1050 I turned on the NBT read feature which returns solenoid 1b on all toroid magnets but active and next are 0b on nearly all magnets, except for those first from the injector facing direction which are mostly on active 1b (also sometimes seem to switch) but next keeps switching between 1b/0b. 
![Screenshot_280](https://user-images.githubusercontent.com/41554385/113511321-95a54480-955f-11eb-8f5e-f5bbcad56c5d.png)

Now as long as the toroid magnets keep switching next the plasma seems to get blocked at the first magnet and thrown back to the other side (specifically when next is 1b) as seen in the first picture. (This also happens in debugtest)
![Screenshot_281](https://user-images.githubusercontent.com/41554385/113511489-54616480-9560-11eb-8d95-2a55cec6d2cb.png)
Side note: The switching seems to happen in regular intervals, as seen in irregular plasma streams: 
![Screenshot_282](https://user-images.githubusercontent.com/41554385/113511646-203a7380-9561-11eb-90cb-1df21bee19ee.png)

Another thing that happened while I was testing around with this situation was that after restarting my server and joining it, the fusion seemed to have happened for a split second since I received the "Stellar Energy" Achievement along with a few neutrons ramming into my Neutron Absorbers, but since this only happened once I wasn't able to investigate it further.

I will do my best to provide more specific info if needed, although I probably just made a really dumb mistake somewhere.

**Comment by ReikaKalseki** [comment]
Check the placement; "next" is the flag for the toroids having valid neighbors.

**Comment by MalTeeez** [comment]
I have triple-checked the Toroid's placements&rotations (Waila, overlay&blueprint highlighter, NBT) and unless my game is bugged they should be placed correctly.

**Comment by ReikaKalseki** [comment]
What about the injectors? This is very old and very simple code - all it does is check block at relative position.

**Comment by MalTeeez** [comment]
I have tried replacing the injectors in both directions and double checked the positions of the multiblocks, according to my knowledge they are placed correctly but feel free to adjust me on that.
![Screenshot_283](https://user-images.githubusercontent.com/41554385/113595632-8abee280-9639-11eb-8cc8-f43f05f14bae.png)
![Screenshot_284](https://user-images.githubusercontent.com/41554385/113595635-8c88a600-9639-11eb-9a15-fa93d019d691.png)

**Comment by ReikaKalseki** [comment]
I meant the injector directions - are any backwards? The fact you have the one at the bottom there going *left* implies as much.

**Comment by MalTeeez** [comment]
That one was left facing that way after another round of testing, I'll try to rebuild the entire thing in a more stable environment and try to reproduce it. But until then I think I should leave this issue closed/unresolved since I can't really blame this on ReC in my weird 250+ mods env.

**Comment by MalTeeez** [comment]
Well it seems this was touched by the magic of "fixed itself", I rebuilt it in another dim, cleared up my setup a little and now it works.
I've observed some other weird N/A% Steam behavior with pumps to Turbines but I'll open up another Issue on that with more Info soon.
