### ISSUE TITLE
Diamond Gears now require double amount of diamonds

### ISSUE THREAD

**Issue by lee321987** [ReikaKalseki/Reika_Mods_Issues#2808]
16x Diamond gearboxes used to require around 20 diamonds to craft.
The new recipe for a Diamond Gear takes 4 diamonds just to craft one, so a 16x Gear Box now requires 46 diamonds.
Is this intentional?
![Clipboard Image](https://user-images.githubusercontent.com/18412921/113570034-82d35400-95e1-11eb-96f9-24c74e7dbea5.jpg)

**Comment by ReikaKalseki** [comment]
How many did the recipe give when it was simply the crafting table? Three?

**Comment by lee321987** [comment]
@ReikaKalseki
It used to be 8 gears for 5 diamonds.
Pic made using:

- DragonAPI V25c
- RotaryCraft V25b

![Clipboard Image (1)](https://user-images.githubusercontent.com/18412921/113619260-c69c7c80-9626-11eb-97d5-ec38d3144db4.jpg)

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by lee321987** [comment]
@ReikaKalseki 
One more question about this -- that 1400 C temperature requirement means you need
2,742,336 MW (1656 torque x 1656 rads) to create a Diamond Gear.
So it seems Diamond Gearboxes are now gated behind the Microturbine Engine.
Intentional?

**Comment by ReikaKalseki** [comment]
Yes.
