### ISSUE TITLE
[RotaryCraft v29g] Blast Furnace takes less ingredients than required

### ISSUE THREAD

**Issue by Star4Fun** [ReikaKalseki/Reika_Mods_Issues#2809]
I created bedrock alloy ingots and recognized that the blast furnace melt the ingot even with less dust than required. (NEI says it uses four but it works with one).

![2021-04-06_10 21 15](https://user-images.githubusercontent.com/37082237/113681700-91de0300-96c2-11eb-936d-e7b62acc0005.png)

**Comment by ReikaKalseki** [comment]
How the hell did *this* happen?

**Comment by ReikaKalseki** [comment]
Fixed.
