### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by ffffff5** [ReikaKalseki/Reika_Mods_Issues#281]
What can I say, installed the mod and getting 3 FPS. TBF, only get 15 at the best of times in vanilla, but still.

**Comment by ReikaKalseki** [comment]
Adding any mods at all has some overhead, as does Forge itself.

But if you get 15FPS "at the best of times", what kind of hardware are you on?

**Comment by ffffff5** [comment]
AMD Duron CPU
1GB RAM DDR2
Intel Integrated HD Graphics
240GB SanDisk HDD
Windows XP

**Comment by ReikaKalseki** [comment]
Your CPU is so old I had to look it up, as it is from *2005*!

Seriously, your hardware is older than a good portion of the *players*, and fails to meet even [MC minimum requirements](https://help.mojang.com/customer/portal/articles/325948-minecraft-system-requirements).
