### ISSUE TITLE
[chromaticraft] GregTech ore compatibility issues

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#2811]
The GregTech ore in the chroma world is fake. The products made by mineral extraction are also fake. can it be shielded? And the ore extractor cannot recognize GregTech ore. This may be related to the GT ore being a TileEntity block. 

![image](https://user-images.githubusercontent.com/19620848/113813628-d5a83980-97a2-11eb-9dbd-cb3297ec0a6d.png)
![image](https://user-images.githubusercontent.com/19620848/113813931-65e67e80-97a3-11eb-9f11-0712f91c5658.png)
![image](https://user-images.githubusercontent.com/19620848/113814667-91b63400-97a4-11eb-90aa-c0a8c305be7c.png)

**Comment by ReikaKalseki** [comment]
...What?

**Comment by KuroPeach** [comment]
The GT ore converted by Mineral Enricher is damaged , Mineral Extractor cannot recognize GT ore , The GT ore generated in the Chroma world is also damaged . Mining no ore drops, this may be related to the GT ore being a TileEntity block . Can you be compatible with it? Forgive my poor english .

**Comment by Beannsss** [comment]
I have experienced this as well. Every single gregtech ore (including small ore) has the same ID, but different nbt, would expect it to work similar to how it works with Fluorite from ReC. Not sure how useful this info is, and how much of a pain it would be to fix.
![image](https://user-images.githubusercontent.com/8314499/114064636-d6ef6a00-9867-11eb-98a0-31579e29a131.png)
![image](https://user-images.githubusercontent.com/8314499/114065193-61d06480-9868-11eb-9792-e0f703758386.png)

**Comment by bpwhelan** [comment]
I have experienced this as well. Every single GT ore has the same id but different (damage?) values. Would expect it to work similar to Fluorite from ReC. Might also note that the Area Breaker completely ignores GT ore blocks. Not sure how useful this information is. But am willing to dig for more if needed.  Like LeaveLeaf also said, they are tileentities, not normal blocks.

Is happening for me on V29g

SS might not reflect, but im looking at the block on the bottom left.
![image](https://user-images.githubusercontent.com/8314499/114065469-b378ef00-9868-11eb-8367-ede8bb143e71.png)
![image](https://user-images.githubusercontent.com/8314499/114065505-ba9ffd00-9868-11eb-9971-70d89eab3339.png)

**Comment by KuroPeach** [comment]
emmmmm, if compatible not easy to do, can you let CC do not generate GT minerals?

**Comment by ReikaKalseki** [comment]
GT ores are TileEntities, which break most recognition systems. Yes, simply blacklisting them is the best choice.
