### ISSUE TITLE
[MeteorCraft] Crash when generating new world

### ISSUE THREAD

**Issue by wojhd007** [ReikaKalseki/Reika_Mods_Issues#2812]
When I generating new world game crashes. In the crash log i see some mods.

Thank you in advance for your help.

Forge Version: 10.13.4.1614
MeteorCraft Version: 29B
Crash Log:
[crash-2021-04-06_18.47.10-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6273110/crash-2021-04-06_18.47.10-server.txt)

**Comment by ReikaKalseki** [comment]
This was caused by someone else removing one of the vanilla blocks.
