### ISSUE TITLE
[MeteorCraft] Ticking Entity Crash

### ISSUE THREAD

**Issue by wojhd007** [ReikaKalseki/Reika_Mods_Issues#2813]
Some meteorites crash the game while rendering the entity.

Thank you in advance for your help

Forge Version:  10.13.4.1614
MeteorCraft Version: 29B
Crash Log: [crash-2021-04-08_08.32.26-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6276557/crash-2021-04-08_08.32.26-client.txt)

**Comment by ReikaKalseki** [comment]
I do not think this is my doing - it is not renderer-related, it is the chunk loading system.

**Comment by ReikaKalseki** [comment]
I put in some protection code, but there is not much else I can do.

**Comment by ghost** [comment]
So, I encountered this same issue (Concurrent modification exception), with both MeteorCraft and ChickenChunks in the pack, to the point that when a meteor shower occurred, my game kept crashing about a second after loading my save.
I believe it's an issue on ChickenChunks' end.
I added this mod to my pack, [https://www.curseforge.com/minecraft/mc-mods/chicken-chunk-patcher](url), which fixes an issue with ChickenChunks, and the crash went away - I was able to load my world without issues.
Maybe it didn't actually fix the core issue, and it just changed the behavior enough that it didn't occur in this particular case, but that's the best I can think of.

**Comment by ReikaKalseki** [comment]
That would indeed make sense.
