### ISSUE TITLE
[Chromaticraft] TileEntityCrystalMusic use client class at serverside?

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#2815]
TileEntityCrystalMusic use client class at server side?
ChromatiCraft+1.7.10+V29g.jar

https://paste.ubuntu.com/p/54bNmBkTDC/

**Comment by KuroPeach** [comment]
This problem occurred after I updated the server version. After removing the problem Tile, the archive can be loaded normally

**Comment by KuroPeach** [comment]
Add a new question. Now the chroma world will not play background music.

**Comment by ReikaKalseki** [comment]
Did you turn it off?

**Comment by ReikaKalseki** [comment]
Fixed.
