### ISSUE TITLE
Botania eye of the flugel can be used to cheat locks and keys

### ISSUE THREAD

**Issue by qwahaha** [ReikaKalseki/Reika_Mods_Issues#2817]
It has a function to bind to a block, then teleport to the bound block. You can cheat the locks and keys puzzle with this. Maybe others, like the shifting maze.

**Comment by Mettymagic** [comment]
AM2 recall spells can probably also be used to cheat them. In my opinion there's nothing wrong with a bit of creative utility though. =)

**Comment by ReikaKalseki** [comment]
Fixed.
