### ISSUE TITLE
[DragonAPI] 1.7.10 Mohist server start blocker/crash

### ISSUE THREAD

**Issue by TekuSP** [ReikaKalseki/Reika_Mods_Issues#2819]
Version of DragonAPI: `DragonAPI 1.7.10 V29g` for 1.7.10, completely blocks startup of Mohist server, version 28.
Attaching logs from server:
[fml-junk-earlystartup.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6303737/fml-junk-earlystartup.log)
[fml-server-latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6303738/fml-server-latest.log)
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6303739/latest.log)

Running on Windows 10 (Build 19042.906 20H2)
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

**Comment by TekuSP** [comment]
I gave up on Mohist.

**Comment by ReikaKalseki** [comment]
What is Mohist?
