### ISSUE TITLE
Rockwool doesn't work to insulate engines

### ISSUE THREAD

**Issue by lee321987** [ReikaKalseki/Reika_Mods_Issues#2821]
I saw in the change log for RC v7:
"Rock wool now works for insulation"

Am I right that this means Rockwool from Thermal Expansion mod?
It doesn't work any more (I tried Rockwool for the first time today).

It would be nice if it worked because they won't burn around Steam Engines.

**Comment by ReikaKalseki** [comment]
The code checks for `Material.cloth` - if rockwool has moved away from that, that is not on my end.

**Comment by ReikaKalseki** [comment]
Why did you close this?

**Comment by ReikaKalseki** [comment]
Looking at his code, he did indeed shift rock wool away from being Material.cloth.

I have updated my handling.

**Comment by lee321987** [comment]
This is no longer fixed.
