### ISSUE TITLE
Cannot craft crystal repeaters

### ISSUE THREAD

**Issue by qwahaha** [ReikaKalseki/Reika_Mods_Issues#2822]
I have all the items placed. The GUI shows the repeater x16 in the output slot, but it's crossed out. Is it saying I don't have progression?
I should be progressed enough to craft them. Post-monument completion, lexicon complete except for that ability that needs painful loss to unlock.
I know all the runes are in the right place because it's not the first time I've crafted crystal repeaters.

Is my character data corrupted?

Seems to not affect all items. I'm able to craft both normal and enhanced pendants.

Also, not sure if this matters, but I was using the recipe to make crystal repeaters from scratch, not the recipe to upgrade wooden repeaters to crystal repeaters.

**Comment by ReikaKalseki** [comment]
Yes, you are missing progression.

**Comment by qwahaha** [comment]
I'm not sure what I'd be missing since I have the fragment for crystal repeaters and all progressions except for Painful Loss and the one for trying to cheat a structure.

My character data must be corrupted somehow. I've had to edit it to fix problems coming from other mods, so the error might not be caused by ChromatiCraft.

**Comment by ReikaKalseki** [comment]
Run `/chromaprog debug all`, and paste the result here.

**Comment by qwahaha** [comment]
Player research: 
Level CTM
Fragments: [WAND, LINKTOOL, SHARDS, LASERBILITY, NETWORKTRANSPORT, PARTICLES, LAMPCONTROL, HICORES, ESSENTIA, MANABOOSTER, BROADCASTER, BURROW, INVLINK, AISHUTDOWN, LEECH, WARP, ASPECTJAR, DESERT, ENCHANTING, BALLLIGHTNING, TICKER, BRANCHES, LASER, FENCEAUX, BUILDER, SUPERLAMP, SEED, LAMPAUX, CHUNKLOADER, AUTO, FLUXMAKER, COMPOUNDSTRUCT, PLANTACCEL, CAPTURE, PURIFY, BOTTLENECK, SHIFT, PYLONLINK, OWNERKEY, FIREBALL, TELEPUMP, CHESTCLEAR, WIRELESS, TRANSMISSION, LENS, FLUIDRELAY, PROBE, ENCHANTS, LAUNCHPADSTRUCT, KILLAURA, ENCHANTDECOMP, REPEATERSTRUCT, RELAY, STRUCTURES, PYLONBROADCAST, AURAPOUCH, MULTIBLOCKS, DYELEAVES, PENDANT, TURBOREPEATER2, BREWER, TREE, TURRET, FERTILITYSEED, BEESTORAGE, REPEATER, RANGEBOOST, PYLONS, BERRIES, BEEALYZE, RELAYSTRUCT, LUMENWIRE, ABILITIES, OREPICK, TNT, NETWORKOPT, PLAYERINFUSION, FOCUSCRYSTALS, ENDERBUCKET, RITUAL, SPLINEATTACK, CASTING1, COMMUNICATE, AREABREAKER, VILLAGEREPAIR, TURBO, GLOW, CAVERN, MOBBAIT, LIFEPOINT, CROPSPEED, SELECTIVEGLASS, BEACONSTRUCT, FIRERAIN, DUSTS, REPEATERLAMP, AURALOCUS, ORECLIP, TURBOREPEATER, IRID, DUPLICATOR, GLASS, ITEMRIFT, PROGRESSLINK, ARTEFACT, ENCHANTER, METEOR, PORTAL, REDSTONEPOD, RIFT, BREADCRUMB, LEYLINES, ALVEARY, RAINBOWLEAVES, DOOR, EXPLOSIONSHIELD, BULKMOVER, INJECTOR, SHOCKWAVE, CHROMACRAFTER, METEOR3, LOTUS, HEATLAMP, DASH, LIGHTGUN, TANK, DOORKEY, LIGHTCAST, POWERTREE, HOVERPADAUX, MUSIC, GUARDIAN, INSERTER, HOVERPAD, LANDMARK, CRYSTALLAMP, PYLONTURBORING, RFDISTRIB, INJECTORAUX, HEALTH, SONIC, COLORALTAR, SHIELD, CASTTUNING, TINKERTOOLS, REACH, FLOAT, TANKAUX, KEEPINV, CAVEEXIT, VACUUMGUN, PLANTHARVEST, WARPLOC, CLOAKING, LAUNCHPAD, SPAWNERSEE, MOBSONAR, WINDOW, DATATOWER, WIRELESSPED2, TRAPFLOOR, PROGLINKSTRUCT, ENDEREYE, HEAL, CRAFTING, SELFCHARGE, PYLON, GROUPS, CAVELIGHTER, DIMENSION2, LAMP, OPTIMISTRUCT, WARPNODE, ENDERCRYS, GATE, ENCRUSTED, PYLONPROTECT, LUMENLEAVES, CASTING2, CHAINGUN, MOBSEEK, BEACON, TRANSITION, INFUSION, RFPOD, TELEGATELOCK, FENCE, DOUBLECRAFT, LILY, ALLOYS, CHROMA, COBBLEGEN, PLAYERINFUSER, ITEMCOLLECTOR, PYLONTURBO, ITEMSTAND, STRUCTUREPASSWORDS, ASPECT, MULTIBUILDER, PATH, OCEAN, FRAGMENT, DIMPING, ORES, METEOR2, HOVER, FUNCRELAY, SPLASH, CASTING3, SNOW, CRAFTING2, CORES, PORTALSTRUCT, MINIREPEATER, TREESEND, REPROGRAMMER, SUPERBUILD, BROADCAST, PROXESSENCE, CRYSTALSTONE, GROWAURA, EXCAVATOR, ENERGY, CRYSTAL, DIMENSION, RITUAL2, SHIELDEDCELL, GROWTH, NUKER, WEAKREPEATER, WIDECOLLECTOR, VOIDCELL, MEINV, MAGNET, TELEPORT, WIRELESSPED, SPAWNERBYPASS, COLLECTOR, FURNACE, TOOLSTORAGE, GATESTRUCT, DIMENSION3, MINER, EFFICIENCY, MULTITOOL, ROUTER, ELEMENTS, CLOAKTOWER, INSCRIPTION, CHROMAFLOWER, BEEFRAME, AVOLAMP, NODENET, FLUIDDISTRIB, RITUALTABLE, GLOWFIRE, RUNES, BEES, CRYSTALS, MUSICTRIGGER, FINDER, CRYSTALCELL, BOOSTTREE, RECHARGE, AVOLASER, STRUCTFIND, FARMER, LUMA, TELECAPSULE, MINIPYLON, STORAGE, LIGHTNING, DIMTUNING, FLOATBOOTS, USINGRUNES, FAKESKY, COMPOUND, METEOR1, ORESILK, INFUSER, SMELTERY, PERSONAL, CHARGER, BIOMEPAINT, ACCEL, JUMPABILITY, MEDISTRIB, FABRICATOR, APIRECIPES, CASTTABLE]
Can step to CTM: F=true && R=true
Missing research for CTM: []
Progress for King__Midas:
[TURBOCHARGE, END, ABILITY, RAINBOWFOREST, KILLMOB, CAVERN, SNOWSTRUCT, FOCUSCRYSTAL, DYETREE, KILLWITHER, TWILIGHT, PYLONLINK, BEDROCK, ENERGYIDEA, NETHERSTRUCT, ARTEFACT, BREAKSPAWNER, RAINBOWLEAF, NETHERROOF, POWERCRYSTAL, ALLCORES, MULTIBLOCK, STORAGE, FINDSPAWNER, CASTING, ALLCOLORS, CRYSTALS, NETHER, CHROMA, REPEATER, SHARDCHARGE, DIMENSION, KILLDRAGON, INFUSE, LUMA, STRUCTCOMPLETE, RUNEUSE, TUNECAST, OCEAN, BURROW, CTM, BYPASSWEAK, BALLLIGHTNING, SHOCK, POWERTREE, CHARGE, PYLON, TOWER, LINK, VILLAGECASTING, BLOWREPEATER, USEENERGY, WARPNODE, ANYSTRUCT, CHARGECRYSTAL, RELAYS, MAKECHROMA, HIVE, DESERTSTRUCT, ALLOY]
Elements for King__Midas:
[GRAY, WHITE, BLUE, LIGHTGRAY, PURPLE, LIGHTBLUE, GREEN, RED, PINK, LIME, MAGENTA, BLACK, YELLOW, CYAN, BROWN, ORANGE]
Structure Flags for King__Midas:
[WHITE, GRAY, BLUE, LIGHTGRAY, PURPLE, LIGHTBLUE, GREEN, RED, PINK, LIME, MAGENTA, BLACK, YELLOW, CYAN, BROWN, ORANGE]
§aTower ? status for King__Midas: true
§aTower ? status for King__Midas: true
§aTower ? status for King__Midas: true
§aTower ? status for King__Midas: true
§aTower ? status for King__Midas: true
§aTower ? status for King__Midas: true
§aTower ? status for King__Midas: true
§aTower ? status for King__Midas: true
§aTower ? status for King__Midas: true
§aTower ? status for King__Midas: true
§aTower ? status for King__Midas: true
§aTower ? status for King__Midas: true
§aTower ? status for King__Midas: true
Puzzle completion for King__Midas:
true

**Comment by ReikaKalseki** [comment]
That looks like fully maximized progression - were you messing with anything else?

**Comment by qwahaha** [comment]
Nothing worth mentioning.

This is probably a duplicate of this issue:
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2825

**Comment by ReikaKalseki** [comment]
I am dubious of the validity of any progression-related data in your save. Flush everything and see if it still happens.

**Comment by qwahaha** [comment]
I don't understand what you mean by flush that data. Clear it out with an NBT editor so it loads the backup? That's definitely not it.

**Comment by ReikaKalseki** [comment]
Wipe the backups too.

**Comment by qwahaha** [comment]
If I use NBT editor to go to level.dat -> Data -> Player -> ForgeData -> PlayerPersisted and clear out Chroma_Progression and Chroma_Research, and then log into my world, all the entries in the Chromatic Lexicon have a question mark over them, as if they're lost. 

Did I do that right? And the backup I should clear out is the file in ChromatiCraft_Data\ProgressionBackup?

**Comment by ReikaKalseki** [comment]
In the intervening days @Zero_ui9 found that his casting runes changed, taking away his ability to run the recipe. Did yours change as well?

**Comment by qwahaha** [comment]
Let's see, below I have the page from my Chromatic Lexicon on runes. It's the -1 level, the one relevant for repeaters.

I took a picture of the underside of my casting complex, then mirrored it for easy comparison with the page. Everything seems to be in place. It's hard to see, but there's a Kuro rune in the bottom middle.

If I hold the elemental manipulator up to the casting table, There's a white circle with a green dot in the middle. If I right click with the manipulator, I get the *bzzt* sound and nothing happens.

I knocked out one of the relevant runes and replaced it with Crystalline Stone. Now, there's a red X instead of a green dot. So, I don't think runes are the problem.

![Rune Page](https://user-images.githubusercontent.com/71056383/120592085-7a897080-c3fa-11eb-8061-649fb42973c4.png)

![My Runes](https://user-images.githubusercontent.com/71056383/120592164-9e4cb680-c3fa-11eb-84f5-cb874eb16f2c.png)

**Comment by qwahaha** [comment]
By the way, I already got the repeaters I wanted by spawning them in and dumping the ingredients. So, if you don't want to look into this any more, I won't complain.

**Comment by ReikaKalseki** [comment]
Not those runes - the tuning runes.

**Comment by qwahaha** [comment]
Ah, the personalized crafting runes. Yep, that was the problem. I don't know when or why they changed. Maybe when I updated to the latest version?

**Comment by ReikaKalseki** [comment]
Yes, my algorithm apparently changed.
