### ISSUE TITLE
Rotarycraft v29g - NEI shaft crafting errors

### ISSUE THREAD

**Issue by thePalindrome** [ReikaKalseki/Reika_Mods_Issues#2823]
Firstly - Only clicking the wooden shaft pulls up the shaft recipes (all of them, including the cross shaft). Clicking the others does nothing

Secondly - It lists the shaft recipes involving a mount as "shaft unit of the material in the top left, mount in the top middle", which is *incorrect* and results in NEI autoplacing items in the wrong spot, leaving the player confused and submitting erroneous bug reports :P

**Comment by ReikaKalseki** [comment]
I just tested and neither of these are true. ![https://i.imgur.com/rx9zw3v.png](https://i.imgur.com/rx9zw3v.png)

Either they are the result of your NEI version, or have been incidentally fixed by intervening code changes (of which I can recall none).
