### ISSUE TITLE
Fusion reactor making fission steam(V29E)

### ISSUE THREAD

**Issue by rogerwim** [ReikaKalseki/Reika_Mods_Issues#2824]
I built a fusion reactor and just after turning it on it made a small amount of fission steam(0.007511825%) after 10min, seems odd

**Comment by rogerwim** [comment]
Another(minor) thing is that when a line is empty all percentages are -0%, should be 0%

**Comment by ReikaKalseki** [comment]
Boilers default to fission type; this is not avoidable, nor does it break anything.

**Comment by rogerwim** [comment]
ok
