### ISSUE TITLE
Can't upgrade lumen repeaters

### ISSUE THREAD

**Issue by Zero-ui9** [ReikaKalseki/Reika_Mods_Issues#2825]
https://puu.sh/HAoc1/c444d15eea.jpg

Even with progress maxed, I cannot use the recipe to upgrade lumen repeaters into crystal. on the "RepeaterUpcraftRecipe" page, it looks like theres no required progress stage set for it.

**Comment by ReikaKalseki** [comment]
Can you make repeaters from the normal recipe?

**Comment by Zero-ui9** [comment]
http://puu.sh/HAt4z/651d5a55ae.jpg

Apparently that doesn't work either.

**Comment by ReikaKalseki** [comment]
See #2822.
