### ISSUE TITLE
DragonAPI v29g screen black

### ISSUE THREAD

**Issue by matchakuya** [ReikaKalseki/Reika_Mods_Issues#2826]
DragonAPI v29g

Nothing is visible except the GUIs

I get the following OpenGL error:
`@ Post render`
`1282: Invalid operation`

**Comment by ReikaKalseki** [comment]
#2315 #2495 #2260 #2368 #2440 #2460 #2606 #2610 #2516 #2641

**Comment by matchakuya** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2315#issuecomment-807938915

well I read some of these before posting, and it said it's supposed to be fixed in v27
So is it fixed only in v27 or another issue after all?

**Comment by ReikaKalseki** [comment]
The attempted fix appears to not work reliably.
