### ISSUE TITLE
Crystal Furnace Nether ores processing

### ISSUE THREAD

**Issue by Hellexar** [ReikaKalseki/Reika_Mods_Issues#2827]
Currently the crystal furnace is processing the nether ores into their overworld counterparts instead of the intended products. Most of them do this, however there are a few that do process into their normal products.
![lapis](https://user-images.githubusercontent.com/38671362/116163530-eecb4880-a6c5-11eb-87a9-80cdabe686ce.png)
![diamond](https://user-images.githubusercontent.com/38671362/116163538-f12da280-a6c5-11eb-8520-730542132c2a.png)
![coal](https://user-images.githubusercontent.com/38671362/116163554-f854b080-a6c5-11eb-8792-2e95e08847bb.png)
![sulfur](https://user-images.githubusercontent.com/38671362/116163561-fc80ce00-a6c5-11eb-8c3f-1cabce066f23.png)
![redstone](https://user-images.githubusercontent.com/38671362/116163569-00aceb80-a6c6-11eb-814b-6a0ce0a04313.png)
Nikolite and Pig iron (steel) seem to process just fine
![nikolite](https://user-images.githubusercontent.com/38671362/116163543-f38ffc80-a6c5-11eb-9c53-0ecf55a535e7.png)
![pig iron](https://user-images.githubusercontent.com/38671362/116163548-f559c000-a6c5-11eb-9a63-3698e2fda28d.png)

**Comment by ReikaKalseki** [comment]
It just looks at the smelting recipe, and will produce whatever that does.
