### ISSUE TITLE
[Chromaticraft] [Server] Breaking crc trees with fortune 5 bedrock axe. java.lang.StackOverflowError

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2828]
I broke 2 trees with a bedrock pickaxe with fortune 5, (unrelated, but I think the amount of berries you get from that might be a little op) then my poor sad server timed out and started spamming this over and over, and doing /stop does nothing. https://pastebin.com/w2W8ZtdH

it spams the stuff under that over and over and over (the log is at 19,315kb atm)

**Comment by ReikaKalseki** [comment]
This crash has nothing to do with the bedrock axe or fortune - it is entirely an issue with the autocollect enchantment.
