### ISSUE TITLE
[ChromatiCraft] Knowledge Entanglement Pedestal not working

### ISSUE THREAD

**Issue by thehajo** [ReikaKalseki/Reika_Mods_Issues#2829]
Hey there, after the pedestal now finally works in multiplayer, me and my friends decided to give it a shot. 
We first tried it while he was ahead, and i was still missing some major progressions parts (didn't even have all colors yet).
Got this funny looking error image: https://imgur.com/a/WGtS4rr
However after i caught up completely, it's still not working. We have the same (missing) progression, we both have the same discovered fragments, there is virtually no difference between our progress. But when we try to link it, it still gives an error sound, however this time it looks different: https://imgur.com/a/VAdvGHu
I understand that this is the image for an item you have not yet discovered but turned upside down. Maybe we also did it wrong?
I stood on the pedestal which was placed upon the structure, my friend clicked with the wand onto the pedestal, the humming started, i started floating for him but just stood still on my end. And then in the end just the errror sound after a few seconds. Just thought i'd post this here, as i have no idea what else could cause the game to act up. The only thing i could think of is, it's because we have no progressed far enough, but why would the pedestal be available so early then?

**Comment by ReikaKalseki** [comment]
The icons are supposed to indicate a failure state, but they are clearly not being rendered correctly. Unfortunately, without that information, it is impossible to know exactly why the linkage failed.

**Comment by ReikaKalseki** [comment]
OK, it turns out the render bug was trivial; I just specified the wrong locations in the spritesheet.

Your errors were "progression too different" and "mismatched progression".

**Comment by thehajo** [comment]
That's... odd. We had everything the same in the book, both of us had the same fragments and none of us could get any more fragments. Oh well, guess we'll have to try again sometime
