### ISSUE TITLE
[Suggestion] [Rotorycraft] Heating Coils and Heater Tweak

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#283]
After seeing that Extra Utils has a heating coil, I thought it would be cool to add a better version(s) here!

The first version probably fits best in rotorycraft. 
Item: "Heating Coil (Portable)" or "Portable Heating Coil"

This item basically acts like chargeable fuel. This is more fit for things that CAN NOT accept the friction heater for heat. Just like the other little gadgets this item is to be charged with a coil in a worktable. It would be extremely useful for things like generators and some unsupported furnaces like those from the better furnaces mod or something. Have this item stop "burning" after the last item is done smelting?

Main Uses:

fuel (for any item that uses furnace fuels)

Possible extra uses:

light sticks to make torches
act like a flint and steel
possibly cook various blocks/entities in the world on right click?
Others not mentioned here?

Edit:

Maybe also allow the heater from rotorycraft to supply heat in the form of "fake fuel" to the block above it to power various unsupported generators/furnaces that use furnace fuels?

**Comment by ReikaKalseki** [comment]
This is not useful in that what little new functionality it offers - most of it is already possible - is basically useless.

**Comment by Zedrimar** [comment]
ok then! :)
