### ISSUE TITLE
[Chromaticraft] [Suggestion] Sun Dial

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2830]
multi block structure capable of changing the time, like the draconic sun dial (I don't like to use crc/drac together due to how it interacts with the gui stuff).

I was tryin to make something in creative as a general thingy for how the multiblock could look  . . . but that might take a while. . .

(obviously not high priority or anything, since it is just a cool thing lel)

**Comment by ReikaKalseki** [comment]
Changing the game time can often break things, and is obnoxious in a MP environment; I have never had a desire to add to that.
