### ISSUE TITLE
[Chromaticraft] Retrogeneration Reika.ChromatiCraft.World.IWG.DungeonGenerator.tryGenerateInChunk

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2831]
Some of my chunks didn't generate properly (probably because I accidentally did a terrain only pregen lol) but I genned too much of the world to redo it, so I tried to use the config pregenerator, but the server gets stuck on it.

Log of error: https://pastebin.com/Q9NiRUyR

If ya need more info leme know.

**Comment by MalTeeez** [comment]
This sounds very similar to #2797 and especially this comment: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2797#issuecomment-811215641

**Comment by lAimBotl** [comment]
mine does not crash, so I didn't see that when I tried to search for a similar thing . . .
also all snow structures spawn with empty chests everytime, and some burrows have unbreakable pylons in them.

**Comment by ReikaKalseki** [comment]
This is #2797.
