### ISSUE TITLE
[Chromaticraft] NPE when leaving Proxima due to monument ritual clearing

### ISSUE THREAD

**Issue by Zero-ui9** [ReikaKalseki/Reika_Mods_Issues#2834]
https://pastebin.com/siQgM5K6

**Comment by ReikaKalseki** [comment]
Was this singleplayer or dedicated server?

**Comment by MalTeeez** [comment]
It seems to be singleplayer but maybe with "Open to Lan" active

**Comment by Zero-ui9** [comment]
can't remember if I answered this is discord or not, but singleplayer.  and I've never touched "open to lan" on this world. didn't happen every time, but often enough

**Comment by ReikaKalseki** [comment]
This is #2864.
