### ISSUE TITLE
[Chromaticraft] Can't make magical alloys.

### ISSUE THREAD

**Issue by yukysh** [ReikaKalseki/Reika_Mods_Issues#2835]
I am on version v29g, which I believe is the latest. When I try to make a magical alloy, nothing happens. I have the research fragment for alloys and the only way I can progress in the mod is by creating alloys. In my example shown, I have attempted to create a Chroma Alloy Ingot, however the issue appears to be with all current alloys I can create. I have tried both throwing items in individually and throwing items in together.
![1](https://user-images.githubusercontent.com/56700514/116791969-d4261480-aab5-11eb-898d-673ef7377a41.png)
![2](https://user-images.githubusercontent.com/56700514/116791971-d5efd800-aab5-11eb-898e-1323be98bb9b.png)
![3](https://user-images.githubusercontent.com/56700514/116791973-d7b99b80-aab5-11eb-8cb1-dc4600fe5184.png)

**Comment by ReikaKalseki** [comment]
The stacks need to be "intact", not one at a time.

Also, run `/chromaprog debug all`, and run `/blockinfo` while looking at the chroma.

**Comment by charagarlnad** [comment]
After a bit of testing with @yukysh, this turned out to be a bug with another mod we were using to reduce the lag of items stacking in mob farms that was conflicting with a similar patch in another mod. Conflicting patch disabled and alloying is working now.
