### ISSUE TITLE
Pojavlauncher error

### ISSUE THREAD

**Issue by kareemnew2019** [ReikaKalseki/Reika_Mods_Issues#2836]
I am using a lancher mc java edition on android
Called pojavlauncher but when I loud any mods from you
While loading it errored
System information
Java 8
Linux 32
Android 10
2 GB ram located 755 mb
Phone Samsung galaxy A10

**Comment by MalTeeez** [comment]
Just assuming things, but the chances of getting mods running on Android, especially with only 2GB's of RAM is VERY unlikely.

**Comment by ReikaKalseki** [comment]
I am not even going to try having compatibility with *phones*.

**Comment by kareemnew2019** [comment]
> I am not even going to try having compatibility with _phones_.

Thanks for being honest
DON'T WORY YOU DIDN'T BREAK MY HEART
