### ISSUE TITLE
boilers are not heated in reactorcraft

### ISSUE THREAD

**Issue by WOSAJ** [ReikaKalseki/Reika_Mods_Issues#2839]
Latest version: V29d, long-standing problem: boilers do not heat up from neutron absorbers, even through the heat pipe, you said that you solved the problem, but in fact no

**Comment by WOSAJ** [comment]
V29e*

**Comment by MalTeeez** [comment]
Still works for me:
![Screenshot_290](https://user-images.githubusercontent.com/41554385/117538283-cddbef00-b005-11eb-9824-2ef0fad91859.png)
Can you post a screenshot with your reactor setup&boilers?

**Comment by WOSAJ** [comment]
I'll send it soon

**Comment by WOSAJ** [comment]
the problem is this: the absorber is heated to 500C°, and the boiler right next to it is 30°

**Comment by MalTeeez** [comment]
Also a modlist would be appreciated

**Comment by WOSAJ** [comment]
Thermal expansion, thermal foundation, thermal dynamics, rotarycraft, reactorcraft, dragon API, nei, waila,

**Comment by MalTeeez** [comment]
Can you still provide the screenshots?

**Comment by WOSAJ** [comment]
You wrote just in time, I came back from the hospital, in 1-3 hours I will send screenshots.

**Comment by ReikaKalseki** [comment]
Boilers work fine, as I have posted a half-dozen images of in various issues.

**Comment by WOSAJ** [comment]
I don't need your excuses!
