### ISSUE TITLE
Expanded Redstone pump liquid duplication glitch

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#284]
When you use the Expanded Redstone pump, it will collect liquid from not only the source blocks, but also from flow blocks.  This means that you can receive many times more buckets of liquid using this pump than you put into it.

Here's a demonstration of the issue using water, lava, and buildcraft oil.  You'll noticed I placed one bucket of water, two buckets of lava (the first didn't reach the pump), and one bucket of oil, and received at least 7 back of each.

[Here's a demonstration](https://youtu.be/s27y9KchTNc).

**Comment by ReikaKalseki** [comment]
Fixed.
