### ISSUE TITLE
[Rotarycraft] Shafts dropping odd things when mined

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2840]
You cannot craft a clutch with a "fresh" steel shaft, you have to place it first.

**Comment by ReikaKalseki** [comment]
What is the difference on those items? It should only be NBT, which recipes ignore.

**Comment by lAimBotl** [comment]
![2021-05-16_15 29 06](https://user-images.githubusercontent.com/10777735/118410055-94396280-b65b-11eb-96e1-bf21913d4b3c.png)
![2021-05-16_15 29 20](https://user-images.githubusercontent.com/10777735/118410058-969bbc80-b65b-11eb-8a8e-efcbc01feedc.png)

**Comment by lAimBotl** [comment]
I am guessing that your items change when placed because of ownership stuff, am I correct? (even repeaters?)

**Comment by ReikaKalseki** [comment]
I asked for NBT, but yours even differ in *metadata*, which makes no sense.

**Comment by lAimBotl** [comment]
it does that after ya place/break it (not sure if using a bedrock pickaxe with item insertion on it makes a difference)

**Comment by lAimBotl** [comment]
Looked at the NBT for it in NBTExplorer, and the differences are:
Unplaced Shaft: Damage: 0 , tag (1): material: STEEL
Preplaced Shaft: Damage: 2 , (no tag folder)

**Comment by ReikaKalseki** [comment]
What are you mining it with?

**Comment by lAimBotl** [comment]
bedrock pickaxe enchanted with the crc enchanter to have inventory insertion/air miner, though it does not auto insert it into the inventory (also it does that to all RoC shafts)

**Comment by ReikaKalseki** [comment]
Try a pickaxe without those enchants.

**Comment by ReikaKalseki** [comment]
Never mind, the issue was a bit of old code that never got updated with the 2020 material overhaul.
