### ISSUE TITLE
[ChromatiCraft] Tile Accelerators are not working

### ISSUE THREAD

**Issue by thehajo** [ReikaKalseki/Reika_Mods_Issues#2841]
Like the title says, they just don't. Tested it in Singleplayer with maximized progression with just CC, CodeChickenCore, DragonAPI and NEI installed, and placing it next to a furnace didn't do anything.
Video Link: https://www.youtube.com/watch?v=7HD4LLzgb_8
During testing i also found the Mineral Enricher not working, so all Adjacency Cores might be affected.
Or am i missing something and they need energy now? Because neither pylon energy, nor a Relay Source work on them

**Comment by ReikaKalseki** [comment]
Do you have the energy config on? If so, they need energy, and the ambient kind. And your video indicates that yes, you have that config on.

**Comment by thehajo** [comment]
How long has that been a feature? Because we looked through the changelog and found nothing of the sort in newer updates.
But yes, after trying the Ambient Lumen Distributor, it worked!

**Comment by ReikaKalseki** [comment]
That was added in April 2016. 

https://github.com/ReikaKalseki/ChromatiCraft/commit/1276b05c1d18c845e03f2484d6a4e53185dd48bc#diff-b1fa3fcf995adee1141f2d8901f6723c7bb7cc39630e47a15548488fc267df37
