### ISSUE TITLE
Game crashes on startup when Chromaticraft is loaded with Mob Spawn Controls 2

### ISSUE THREAD

**Issue by Darkpixel797** [ReikaKalseki/Reika_Mods_Issues#2842]
Shame because chromaticraft is cool but msc2 is the only way I can prevent random mobs from spawning in unrelated dimensions

Crash Report:
[crash-2021-05-13_22.57.59-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6478743/crash-2021-05-13_22.57.59-client.txt)

**Comment by MalTeeez** [comment]
Nothing in that log indicates that ChromaticCraft is the source of this crash, what makes you think it is?

**Comment by Darkpixel797** [comment]
> 
> 
> Nothing in that log indicates that ChromaticCraft is the source of this crash, what makes you think it is?

Without Chromaticraft, the pack runs fine, even with DragonApi, as long as I remove either Chromaticraft or MSC2, it runs completely fine.

**Comment by ReikaKalseki** [comment]
It is still entirely on their end - there is no mention of any of my code whatsoever.
