### ISSUE TITLE
[ChromatiCraft] [Suggestion] A way to turn down the noise of the Lumen Beacon

### ISSUE THREAD

**Issue by thehajo** [ReikaKalseki/Reika_Mods_Issues#2843]
Hey, it's me again, not with a bug or user error this time (At least i hope so).
We've been using the Lumen Beacon for quite some time now and while we do like just having one giant structure in our base instead of having to build around repeaters, it's pretty annoying to hear the sound of it throughout the whole base with no way of turning it down. Especially when you got an Extractor + Crystal Furnace setup, so it's pretty much active all the time.
I just crafted a Luminescent Battery but couldn't hear the special "song" due to the noise of the lumen beacon sadly, due to how loud it was. Turning down the Master Volume down to 0 and then back up a bit stops it temporarily, before the next burst happens.
So all in all, my suggestion would be a way of just turning down the noise, maybe a slider like for the music, or a structure upgrade that you unlock at a later point, like the Atmospheric Lumen Broadcasting Frame.

**Comment by ReikaKalseki** [comment]
Done.
