### ISSUE TITLE
 Magnetizing Unit - 0.05 seconds operation time is impossible?

### ISSUE THREAD

**Issue by lee321987** [ReikaKalseki/Reika_Mods_Issues#2844]
If you get the Magnetizing Unit fast enough that the tooltip says "Operation Time: 0.05 seconds", it only operates at 0.10 seconds per operation.
Unless it's only supposed to charge 0.5 µ Tesla per operation.
I tried with both the "Redstone Clock" from Expanded Redstone  and a 1-tick-on-1-tick-off clock on this page under heading: "Repeater Loop 1-Clock"
https://minecraft.fandom.com/wiki/Redstone_circuits/Clock#Repeater_clock
Also it's running at 2 mega rads.

**Comment by ReikaKalseki** [comment]
It might have something to do with the fact redstone ticks are two game ticks, but half speed is not intended, no.

**Comment by lee321987** [comment]
I don't know if this is relevant, but you might want to know that this machine sometimes adds one µTesla (µT) per operation, but sometimes it adds zero µT's on one operation and then adds two µT's on the next operation.

This actually interferes with automation:
If you use an extraction pipe with a filter on it, with the filter set to look for a certain charge level (e.g. 1000 µT's),  the charging Shaft Unit might go from 999 µT's to 1001 µT's, and the Unit will never be extracted.

My (early game) solution to that has been to use a filter that is set to find Shaft Unit's that are at several diffrent charge levels.
You have put the Shaft into the machine wait ~6 seconds for an operation, take out the Shaft, open the filter's GUI, click the Shaft's info into the filter, put the Shaft back in the machine, wait for another opertion, and do it over again, and again.  I do if 5 times to give the filter 5 different charge levels to look for.  BTW if anyone wants to try this, make sure you have a mix of even and odd numbers for the filter to search for because it could charge like 1000...1002...1004...1006...etc.

edit: added last sentence.

**Comment by ReikaKalseki** [comment]
That sounds more like a race condition.

**Comment by ReikaKalseki** [comment]
I am going to just clamp the operation time to one redstone tick (0.1s), since it is almost certainly the root of both of these.
