### ISSUE TITLE
The hasTrade function doesn't detect that the UA Trades are already in the MerchantRecipeList.

### ISSUE THREAD

**Issue by UristMcFarmer** [ReikaKalseki/Reika_Mods_Issues#2846]
Every time a villager procs the chance to gain a new trade the two UA Trades are added to the villagers trades, even if they already have the trades.

**Comment by ReikaKalseki** [comment]
This appears to have been fixed, given my testing. I also fixed the "every time it adds a trade it rerolls the chance" issue.
