### ISSUE TITLE
"Error creating loot files!" at end of startup With LootTweaks

### ISSUE THREAD

**Issue by ToastedEggplant** [ReikaKalseki/Reika_Mods_Issues#2847]
I'm running the latest version of LootTweaks in a larger pack and am unable to launch the pack with it installed. Due to "Error creating loot files!" This is probably a mod interaction bug but I have been unable to figure out what mod is causing this. I also understand this issue may be caused entirely by another mod being dumb and not be fixable on your end but I'm documenting it here on the off chance that it can be fixed, or at least to provide documentation to whoever googles the error next if the underlying mod interaction is discovered. Anyways, I've attached the startup log and crash report containing the error. [Client Crash Log Here](https://pastebin.com/hPt9p1Kb) and [Full Startup Log Here](https://sebsauvage.net/paste/?f2e642677578bc39#XuD7RKtIehn3SQQ5jTWWqDvEuRWKiTJHZ3u36M+GAe0=)

**Comment by ReikaKalseki** [comment]
This makes no sense, but I added more logging info.

**Comment by gmnovakrc** [comment]
Having exact same problem it seems.

Crash
[crash-2021-09-02_10.18.19-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7099790/crash-2021-09-02_10.18.19-client.txt)

Log
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7099789/latest.log)

**Comment by ReikaKalseki** [comment]
Yes, but the debugging is in the next version. Until then...

...What files do you have in the tweaks folder (`LootTweaksChanges`)?

**Comment by gmnovakrc** [comment]
Hopefully you can view that, again this just after dragging and dropping the mod into the mod folder and trying to launch it.

[LootTweaksChanges.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7105706/LootTweaksChanges.zip)

**Comment by ReikaKalseki** [comment]
I used your folder and it booted just fine, though it never attempted to load all those `vn_*` files; what *are* those? I do not see any mod compatibility using that key, and that looks like another mod added 12 entries to the vanilla chest gen system (which is fine, but means I need it to be able to reproduce the test).

**Comment by gmnovakrc** [comment]
I'm no expert with this, still new to modpack making, but it seems that those "vn_" files are from "[Village Names](https://www.curseforge.com/minecraft/mc-mods/village-names)" mod. 
That makes the most sense to me, otherwise I haven't seen any other kind of indication as to what other mod could be causing the issue.

I sent you a DM on Reddit with the link to the mod pack, its just missing LootTweaks, latest 1.7.10 version to be dropped in the mod folder, and Void Monster because of the recent bug. This is the only way I can really help since I'm still new to all of this, hope this helps.

**Comment by ReikaKalseki** [comment]
I installed the mod and it loaded all those files too, without error: https://i.imgur.com/mdLRurT.png

**Comment by gmnovakrc** [comment]
Well heck... You have the link to the modpack if you wanna look into it. Otherwise idk what could be the issue, I'll post if I find something though.

**Comment by ToastedEggplant** [comment]
When the new version of LootTweaks releases I'll try and run it in the pack I originally posted about and post the hopefully more verbose log. Are there any settings I should set in the config to get you the most information possible at that point or will a stock config do fine?

**Comment by ReikaKalseki** [comment]
Keep your configs as they were when you got the error.

**Comment by ReikaKalseki** [comment]
Someone else posted a log that so happened to contain this error, and this is exactly what I needed to know:

```
Caused by: java.lang.RuntimeException: Error creating loot file 'railcraft:workshop' in C:\Users\<redacted>\Desktop\Desktop Items\Games\MultiMC\mmc-develop-win32\MultiMC\instances\1.7.105\.minecraft\config\Reika\LootTweaksChanges\railcraft:workshop.tweaks
	at Reika.LootTweaks.LootTweaks.createFiles(LootTweaks.java:100) ~[LootTweaks.class:?]
	at Reika.LootTweaks.LootTweaks.postload(LootTweaks.java:127) ~[LootTweaks.class:?]
	... 44 more
```
Some loot tables use a `:` in their ID, and that is then parsed as a drive letter in the filename.
