### ISSUE TITLE
RotaryCraft Boring Machine can produce invalid items

### ISSUE THREAD

**Issue by erplsf** [ReikaKalseki/Reika_Mods_Issues#2849]
Basically what's said in [this](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=12485) comment still happens on last version.

The setup - I have boring machines in Mining Dimension hooked up to Modular Storage from RFTools, and when I open the Storage, my game crashes when it tries to render invalid item.

Here's the crash logs (there's two separate cases of such items with different damage values):
https://pastebin.com/aDqULA7T
https://pastebin.com/UHQ6iHhF

I know that it doesn't clearly showcase the bug, or confirms that the reason is RotaryCraft, and I'll see if I can reproduce it cleanly in the testing.

**Comment by ReikaKalseki** [comment]
I fixed the plant drops, but there can be no generalized fix for all potentially invalid items short of completely discarding the "more powerful silk touch" capability.
