### ISSUE TITLE
[Chromaticraft] [Suggestion] Mob group mover/teleporter vacuum thing?

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2850]
Kind of like the item vacuum, but with mobs. 
(not really sure how lag friendly that would be though, assuming it is possible(only wondering since I haven't seen any mods do that yet))
 
Probably wouldn't "have" to be added to CrC (though if it was in RC, I would imagine it wouldn't discriminate against players)

**Comment by MalTeeez** [comment]
kind of sounds like the fan from RC

**Comment by lAimBotl** [comment]
I mean something that pulls/teleports mobs on top of it, from a radius around it

**Comment by ReikaKalseki** [comment]
This sounds more like the RC baitbox.

**Comment by lAimBotl** [comment]
It would teleport mobs from a position to the top of the block not requiring a direct line of sight to the mob
(was thinking about weird spawn stuff for dungeons that doesn't directly expose the spawner, and is more controlled) 
ideally you would be able to set the area it pulls from (either with another block (kinda like how the item node has insertion/extraction nodes, but the node would be a area marker linked to the teleporter block telling it where to pull mobs from) or something else?)

If Roc it would pull them in like a vacuum (like the gas turbine intake, but all around it, from the top (or bottom?) of the block being the center) 
that or it would be just like the gas turbine intake, but without the exploding. (obviously no power generation)

(though I haven't used the bait box, to me it sounds like it is something the mobs will path to, rather than being forcefully pulled/teleported to(?))

**Comment by ReikaKalseki** [comment]
The actual attraction mechanism varies by mob type, but yes, most of them attempt to use pathfinding if possible.
