### ISSUE TITLE
Reactorcraft centrifugal fluid extractor

### ISSUE THREAD

**Issue by Haegglun** [ReikaKalseki/Reika_Mods_Issues#2851]
What is my fault, i read the handbook, but it doesn´t work

https://user-images.githubusercontent.com/85301812/120669702-fbdf1280-c48f-11eb-857f-fd32d7b9d322.mp4

**Comment by lAimBotl** [comment]
Run the power to the bottom of it, it requires 16m water above it, and my guess is it won't check for water, if there no water on top of it (you can pump water out the sides)

**Comment by Haegglun** [comment]
is 1 block 1m?

**Comment by lAimBotl** [comment]
yes, idk why I put m instead of blocks :s
