### ISSUE TITLE
[Chromaticraft] Client Crash on Monument Restoration

### ISSUE THREAD

**Issue by SteeleJr98** [ReikaKalseki/Reika_Mods_Issues#2856]
The crash happens when you try to activate the ending monument after placing all the blocks in, the client would freeze up for a few seconds and then tries to play some audio before crashing with the message "java.lang.NoClassDefFoundError: Reika/VoidMonster/Entity/EntityVoidMonster"
The pack we're using doesn't have Void Monster.
Server owner confirms all mods are up to date and that the server is unaffected by the activation.

Full crash log:
https://pastebin.com/Q1MuL5Uf

Thanks!
-Steele

**Comment by lAimBotl** [comment]
#2814

**Comment by SteeleJr98** [comment]
Yep, totally missed it when looking through old issues. I'll close this one then.
