### ISSUE TITLE
Reactorcraft translation

### ISSUE THREAD

**Issue by WOSAJ** [ReikaKalseki/Reika_Mods_Issues#2857]
I was able to translate the reactorcraft mod into Russian, but I did not find the lines responsible for the manual anywhere, is it possible to translate the manual at all?

**Comment by WOSAJ** [comment]
[RC_russifer.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6663998/RC_russifer.zip)

**Comment by ReikaKalseki** [comment]
The manual data is in the jar; you need to make russian copies of the XMLs in "Resources".

**Comment by WOSAJ** [comment]
![Screenshot_20210706_115153_com rarlab rar](https://user-images.githubusercontent.com/76728834/124530853-a14f2280-de50-11eb-9b8c-4a77350b12a8.jpg)
I understand that the manual of your beautiful mod is contained here?

**Comment by WOSAJ** [comment]
ugh, I know how to work with this format, so wait for the full translation of reactorcraft

**Comment by WOSAJ** [comment]
I have a question, can this be done in the form of a resource pack?

**Comment by WOSAJ** [comment]
can this be translated?
![Uploading Screenshot_20210706_221212_ru.androidtools.texteditor.jpg…]()

**Comment by ReikaKalseki** [comment]
> Uploading Screenshot_20210706_221212_ru.androidtools.texteditor.jpg…

Your link is broken.

> I have a question, can this be done in the form of a resource pack?

No.

**Comment by WOSAJ** [comment]
I have already done the translation, now you can add localization to the update

**Comment by WOSAJ** [comment]
[ru_translate_full.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6788659/ru_translate_full.zip)

**Comment by WOSAJ** [comment]
I hope I was helpful

**Comment by ReikaKalseki** [comment]
This was added.
