### ISSUE TITLE
[Chromaticraft] Crafting tools/non stackables in casting table with x2 ability hangs server "permanently"

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2858]
Crafting tools/non stackable items (with automation stuff (unsure if that matters though)) with the end game x2 crafting ability will hang a server "forever" (or at least more than 2+ hours) in SP, you can still fly around, but of course no chunks load, and you cannot access any inventories.

no logs for what happens after, and no crash reports. . .

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by ReikaKalseki** [comment]
Even without the fix, I cannot reproduce this.

**Comment by ReikaKalseki** [comment]
Never mind, I found the problem. It *is* only caused by using the casting delegate.
