### ISSUE TITLE
[chromaticraft] i cant do some crafts on my friends shared casting complex

### ISSUE THREAD

**Issue by quindao** [ReikaKalseki/Reika_Mods_Issues#2859]
it seems to be caused by his personalized crafting runes being different than mine. we used the ownership expansion key, and our progression is synced up but I still can't start the craft for the crystal repeaters it shows an x across the output. this seems like an oversight as for the rest of the mod you have integrated co-op compatibility but this breaks said compatibility.

**Comment by ReikaKalseki** [comment]
That is...indeed likely what is going on.

I have no idea how to address this.

**Comment by ReikaKalseki** [comment]
Fixed.
