### ISSUE TITLE
[ChromaticCraft][V8g]Lumen Lamp Controller Issues

### ISSUE THREAD

**Issue by Modbder** [ReikaKalseki/Reika_Mods_Issues#286]
I am currently fully testing ChromaticCraft and it's devices so expect some bugreports from me ;)

Anyway, I am reporting 2 crashes that occurred to me while testing the Lumen Lamp Controller.

1)I do not know how that happened. Honestly. I've broken the controller - and here the crash appeared. I couldn't replicate it afterwards - it was working just fine. Also, if that helps, the TileEntity actually STAYED, but the block was removed after I've reloaded the world. It occurred in Single-player.

Crashreport:
http://pastebin.com/rdBxN1bD

2)This one I can easily replicate. Just have only ChromaticCraft and Dragon API installed and start changing the way the lamp is activated in it's GUI. Once you get to either RF activation(if you do not have CoFH core) or Shaft Power(without RotaryCraft) the game will crash. This crash happens both in Single-player and Multiplayer.

Crashreport:
http://pastebin.com/zF6Q74fT <- SMP
http://pastebin.com/3JxxLKhK <- SSP

**Comment by ReikaKalseki** [comment]
The first is a severe issue with how your world is handling setBlock, and is almost certainly a mod interaction.

The second...I put some code in which may help, but it really should not happen to begin with, as it already verifies those modes and will not toggle to them if they are not available.
