### ISSUE TITLE
Splash Gun Entity Crashes Server when re-loading chunk that it's in

### ISSUE THREAD

**Issue by bpwhelan** [ReikaKalseki/Reika_Mods_Issues#2860]
This seems to have happened when i was using the splash gun and then teleported away and unloaded the chunks before it fizzled out. Crashes as soon as that chunk loads again. 

[crash-2021-06-23_04.35.55-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6698920/crash-2021-06-23_04.35.55-server.txt)

**Comment by ReikaKalseki** [comment]
Fixed.
