### ISSUE TITLE
Shaft Distribution Clutch: setTorqueToSide ClassCastException: double cannot be cast to boolean

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#2861]
As the Title says the CC function setTorqueToSide of the Shaft Distribution Clutch when invoked.

Probably related to this Line:

[boolean enable = ((Boolean)args[1]).booleanValue();](https://github.com/ReikaKalseki/RotaryCraft/blob/480e25137ebea0ded4b3868a6dcde10d073615f1/ModInterface/Lua/LuaSetDistributionClutchOutput.java#L19)

**Comment by ghost** [comment]
BTW why not just do smth. like that 
`boolean enable = ((Double)args[1]).intValue()>0`
?

**Comment by ReikaKalseki** [comment]
Fixed.
