### ISSUE TITLE
[ChromatiCraft] v29g Error During Burrow Generation.

### ISSUE THREAD

**Issue by Lonemind** [ReikaKalseki/Reika_Mods_Issues#2862]
Received an error during multiple Burrow generation attempts. Found the Burrow. It seemed like it generated fine. Triggered progress properly. Loot chests worked. Glow-y light-y block on basement level of Burrow broke and dropped proper items and allowed me to mine the rest of the Burrow.

I don't know why the error shows up.

https://ibb.co/p1LWHyv

https://gist.github.com/Lonemind/47c52ce026f77b8dcf2adc162cacb168

Line in log can be found by searching "burrow".

**Comment by ReikaKalseki** [comment]
This is #2797.
