### ISSUE TITLE
Territory Zone chat does not work interdimensionally

### ISSUE THREAD

**Issue by DrParadox7** [ReikaKalseki/Reika_Mods_Issues#2863]
DragonAPI+1.7.10+V29g.jar
TerritoryZone+1.7.10+V29a.jar

As the title says, specifically referring to the logging option sent to players.
Players do not receive in-game chat logs if outside of that territory's dimension.

**Comment by ReikaKalseki** [comment]
This should be an easy fix.

**Comment by ReikaKalseki** [comment]
Fixed.
