### ISSUE TITLE
[Chromaticraft] Crash when exiting dimension

### ISSUE THREAD

**Issue by Riyshn** [ReikaKalseki/Reika_Mods_Issues#2864]
Crash log: https://pastebin.com/GGgJaZpr

Consistent crash on exiting the dimension.

I doubt it's related, but because I see it referenced in the log - I have not done the monument completion ritual. The crash has happened every time I've entered and then left the dimension, both clearing and not clearing a puzzle structure.

**Comment by ReikaKalseki** [comment]
The crash mismatches my code, and is impossible with the code I have, so I am going to assume this has been fixed in the process of other changes.
