### ISSUE TITLE
[Chromaticraft v29g] Adjacent core sometime randomly causes crash during requiring power

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2867]
https://paste.ee/p/AFyDw

here are things I build:
![2021-07-04_15 57 11](https://user-images.githubusercontent.com/58476103/124378460-fb7ea500-dce3-11eb-9116-75d4dad65136.png)
Also the config "Adjacency Upgrades Require Energy" is set to true.

However,  the crash seems happened very randomly.
Sometimes just join into game and you get crash immediately, or wait for over ten minutes and no crash happened.
Change some block nearby it may trigger crash, or you encounter crash while searching item in NEI.

**Comment by ReikaKalseki** [comment]
Your paste does not exist.

**Comment by XenonDB** [comment]
> Your paste does not exist.

I waited approximate 20 minutes for crash.

https://paste.ee/p/Ncb4N

![2021-08-31_13 02 16](https://user-images.githubusercontent.com/58476103/131444896-729a344c-8d21-41a6-89c2-5c0349f0b168.png)

**Comment by ReikaKalseki** [comment]
This is just another CrystalNetwork CME.

#1100 #1299 #1290 #1604 #1991 #2035 #2151 #2439 #2575 #2637 #2730
