### ISSUE TITLE
Excessive Nether Generation

### ISSUE THREAD

**Issue by CaiB** [ReikaKalseki/Reika_Mods_Issues#2868]
To start, I'm not sure if this is caused by ChromatiCraft, or another mod. But due to the extent that ChromatiCraft changes Nether generation, it's my prime suspect, hence me asking here.

While we've been exploring the Nether, we've noticed that occasionally extra chunks are being generated to the north-west of where we actually explore. They appear to be only in pre-population stage, as lighting calculations are not done in these chunks. It makes these odd tendril-like patterns on our world map, as you can see here:
(circled in red are the extra chunks, in blue is the area we actually explored)
![HighChunkCountNormal](https://user-images.githubusercontent.com/6701127/124582083-89eb4780-de06-11eb-9295-6a21d0a963f1.PNG)

However, we had a much more severe event happen this evening. I noticed that the server started loading an insane number of chunks while I was exploring on the Nether roof, to the point that it started causing enough lag to repeatedly time everyone out until eventually settling down a while later.

It looks like some kind of generation caused more and more chunks to generate in some kind of avalanche effect. I'm worried that this could become significantly worse in the future if it happens again and enters runaway, potentially bringing the server down completely.

Here's a graph of the number of chunks loaded on the server while this was happening. There is absolutely no good reason for it to be loading 20k chunks into memory in the Nether, where we have no chunkloaders and when I was the only player present. Some world ticks during this time took tens of seconds. I left the Nether towards the end, but it continued loading more and more, until stopping, then unloading them all at once.
![HighChunkCount](https://user-images.githubusercontent.com/6701127/124582354-cc148900-de06-11eb-9969-4434f26b53f2.PNG)

Later, I noticed the huge extent on the map that it had generated:
![HighChunkPattern](https://user-images.githubusercontent.com/6701127/124582571-fa926400-de06-11eb-9fb8-478734f5d5a5.PNG)
(the small squares you see are chunks, this is a huge area)

There was no crash or console output signifying a problem, other than the server running behind very significantly during the worst period.

Is there anything about the ChromatiCraft nether generation that could potentially be causing this behaviour? The only other mod I can think of contributing would be Biomes O Plenty, but that seems unlikely.

Here's the list of mod JARs installed:
```
│  1.7.10 - AE2 Stuff 0.5.0.56.jar
│  1.7.10 - AppleCore 3.1.1.jar
│  1.7.10 - Applied Energistics 2 rv3 beta6.jar
│  1.7.10 - BC LogisticsPipes 0.9.3.132.jar
│  1.7.10 - Bdlib 1.9.4.109.jar
│  1.7.10 - BetterFoliage 2.0.17.jar
│  1.7.10 - BiomesOPlenty 2.1.0.1889.jar
│  1.7.10 - BuildCraft 7.1.23.jar
│  1.7.10 - BuildCraft Compat 7.1.7.jar
│  1.7.10 - Carpenters Blocks v3.3.8.2.jar
│  1.7.10 - ChickenChunks 1.3.4.19.jar
│  1.7.10 - Chisel 2.9.5.11.jar
│  1.7.10 - ChromatiCraft V29g.jar
│  1.7.10 - ComputerCraft 1.75.jar
│  1.7.10 - CookingBook 1.0.140.jar
│  1.7.10 - ElectriCraft V29a.jar
│  1.7.10 - EnderStorage 1.4.7.37.jar
│  1.7.10 - ExpandedRedstone V29b.jar
│  1.7.10 - ExtraCells 2.2.73b129.jar
│  1.7.10 - F Binnies Mods 2.0.22.7.jar
│  1.7.10 - Forestry 4.2.16.64.jar
│  1.7.10 - ForgeMultipart 1.2.0.345.jar
│  1.7.10 - ForgeRelocation 0.0.1.4.jar
│  1.7.10 - ForgeRelocation FMPPlugin 0.0.1.2.jar
│  1.7.10 - FW CodeChickenCore 1.0.7.47.jar
│  1.7.10 - FW CoFHCore 3.1.4-329.jar
│  1.7.10 - FW CollectiveFramework 1.0.0.132.jar
│  1.7.10 - FW DragonAPI V29g.jar
│  1.7.10 - FW Mantle 0.3.2b.jar
│  1.7.10 - FW mcjtylib 1.8.1.jar
│  1.7.10 - FW OpenModsLib 0.10.jar
│  1.7.10 - FW QmunityLib 0.1.114.jar
│  1.7.10 - Hopper Ducts 1.3.2.jar
│  1.7.10 - IC2 GraviSuite 2.0.3.jar
│  1.7.10 - IC2 NuclearControl 2.4.3a.jar
│  1.7.10 - IndustrialCraft 2 2.2.827 experimental.jar
│  1.7.10 - InGameWiki.jar
│  1.7.10 - InputFix v5.jar
│  1.7.10 - InventoryTweaks 1.59 dev152.jar
│  1.7.10 - IronChest 6.0.62.742.jar
│  1.7.10 - JABBA 1.2.2.jar
│  1.7.10 - JourneyMap 5.1.4p2.jar
│  1.7.10 - Morpheus 1.6.21.jar
│  1.7.10 - NEI Thaumcraft Plugin 1.7a.jar
│  1.7.10 - NEI Waila 1.5.10.jar
│  1.7.10 - NEI Wawla 1.0.5.120.jar
│  1.7.10 - NotEnoughItems 1.0.5.120.jar
│  1.7.10 - ObsidiPlates 3.0.0.18.jar
│  1.7.10 - OpenBlocks 1.6.jar
│  1.7.10 - OpenComputers 1.7.5.1290.jar
│  1.7.10 - OpenPeripheral AIO8.jar
│  1.7.10 - Pams HarvestCraft Lb.jar
│  1.7.10 - Peripherals++ 1.3.6.jar
│  1.7.10 - ProjectRed 4.7.0pre12.95-Base.jar
│  1.7.10 - ProjectRed 4.7.0pre12.95-Compat.jar
│  1.7.10 - ProjectRed 4.7.0pre12.95-Fabrication.jar
│  1.7.10 - ProjectRed 4.7.0pre12.95-Integration.jar
│  1.7.10 - ProjectRed 4.7.0pre12.95-Lighting.jar
│  1.7.10 - ProjectRed 4.7.0pre12.95-Mechanical.jar
│  1.7.10 - ProjectRed 4.7.0pre12.95-World.jar
│  1.7.10 - Railcraft 9.12.2.1.jar
│  1.7.10 - ReactorCraft V29e.jar
│  1.7.10 - RFTools 4.23.jar
│  1.7.10 - RotaryCraft V29g.jar
│  1.7.10 - TC Forbidden Magic 0.575.jar
│  1.7.10 - TC Inventory Scan 1.0.11.jar
│  1.7.10 - TConstruct 1.8.8.jar
│  1.7.10 - TerritoryZone V29a.jar
│  1.7.10 - Thaumcraft 4.2.3.5.jar
│  1.7.10 - ThermalDynamics 1.2.1-172.jar
│  1.7.10 - ThermalExpansion 4.1.5-248.jar
│  1.7.10 - ThermalFoundation 1.2.6-118.jar
│  1.7.10 - TiC ExtraTiC 1.4.6.jar
│  1.7.10 - TiC Tooltips 1.2.5.jar
│  1.7.10 - Twilight Forest 2.3.8.jar
│  1.7.10 - WR-CBE 1.4.1.9.jar
```

I understand this isn't a very actionable issue, but any guidance or info you may have would be much appreciated. Like said, I'm not sure it's ChromatiCraft, but it's the most likely suspect.

**Comment by XenonDB** [comment]
I made some test and believed this is caused by ChromatiCraft.

These are chunks generated when I first get into nether: (seed: 8971081544338868087)
With ChromatiCraft:
![01](https://user-images.githubusercontent.com/58476103/124811111-b339de00-df94-11eb-91f0-4000ce7441b8.png)
With BiomesOPlenty 2.1.0.1889:
![10](https://user-images.githubusercontent.com/58476103/124811116-b503a180-df94-11eb-87ae-db1570cab982.png)
With BiomesOPlenty 2.1.0.1889 and ChromatiCraft:
![11](https://user-images.githubusercontent.com/58476103/124811119-b503a180-df94-11eb-8538-abdcd08674b6.png)

By the way, this issue is usually caused by generating things in unloaded chunk then make extra chunk loading.
And is usually caused by not making offset of coordinate

Here is the reddit post which explained this in detail:
https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

**Comment by CaiB** [comment]
@XenonDB That post describes pretty much exactly what I'm seeing, just that I saw it to a much more significant extent. Great find, hopefully this can get fixed.

> If you use vanilla classes like `WorldGenMinable` then the offset is already built in, but if you have a custom one make sure it is generating properly.

**Comment by ReikaKalseki** [comment]
I suspect the lava river generator or fluid updates within it - as the generator itself is purely noise-based and chunk-segregated - is involved.

Mezz's post is not relevant here - that only applies to small features - far smaller than a chunk in size - and which are placed as singular entities, not noise-based generation.

**Comment by CaiB** [comment]
Something else I just saw from a comment on that post (emphasis mine)
> By the way, be careful that you don't put blocks on chunk borders that might cause height/material checks in neighbouring chunks, such as torches/fences/walls/redstone trying to attach to blocks in neighbouring chunks or **fluids starting to flow**, this used to trigger chunk population, not sure if it does in 1.11.2.

Definitely sounds like it could be the lava/metals.

**Comment by ReikaKalseki** [comment]
"Don't put liquids on borders" is not productive advice, buuut I might be able to prevent them from ticking.

**Comment by ReikaKalseki** [comment]
Revisiting this, I had an idea.

On the dev server we often saw a lot of lag caused by grass spreading into (or rather, its spread code checking) unloaded chunks, causing them to load - and in some cases generate - and often defeat any attempts at unloading the bases of since-departed players.

I might just end up putting into DAPI a generalized system to prevent "AoE" type block ticking - fluid update, grass tick, etc - unless all nine border chunks are loaded. That would always be true near a player, but would prevent them from ever causing new chunks to load.

**Comment by ReikaKalseki** [comment]
It turns out that system and config already exists for block spreading, so I can just expand it.

**Comment by ReikaKalseki** [comment]
OK, this has been done and should hopefully help. In advance, ensure the following config option is enabled: `STOPUNLOADSPREAD("Prevent block spreading near unloaded chunks", true)`

This will intercept and stop all non-forced (ie not explicitly called by some code specifically ticking that position, like RC fertilizer or CC healing aura ability) block ticks for:
- Grass Spread
- Mycelium Spread
- Liquid Update/Flow
- Lava Spawning Fire
- Fire Spread
