### ISSUE TITLE
Server crash with electricraft. 

### ISSUE THREAD

**Issue by DevonX** [ReikaKalseki/Reika_Mods_Issues#2870]
Got a crash with electricraft. Not sure what caused it or how to reproduce.  https://pastebin.com/raw/rB3urw9C

**Comment by DevonX** [comment]
As an aditional note. the server was running the modpack SetGameDifficulty Reika https://www.curseforge.com/minecraft/modpacks/setgamedifficulty-reika

**Comment by ReikaKalseki** [comment]
Did this involve a world rift? If so, I can see one way this might have happened. I have included a fix for that and additional debug info in the event of future errors.
