### ISSUE TITLE
RotaryCraft boring machine "toggle all" button not works ; v29g

### ISSUE THREAD

**Issue by HonkerBonker** [ReikaKalseki/Reika_Mods_Issues#2872]
To reproduce: open boring machine gui , press "toggle all" , exit gui , open it again , see previous boring machine borer head shape.  It does change shape of bore head (pressed 'cells') in gui , but it neither affects actul bore head shape , nor saved on exit from gui.
     Individual 'cells' in boring machine gui work . If you want to make bedrock to surface line of boring machines and even replace them , cause you come with better setup , it becomes 7x5x(number of boring machines) clicks to toggle them all. Quite _boring_ thing to do.

 v29g and actually previous version too. Either no one bothered to report or its some weird thing only i affected by.   Also tested that on clean , RC only install (dragon api and RC , to be precise. No optifine , not even jei , just dragon api and RC) , still persists.

https://gyazo.com/0dda80fa8b949f2ba9d82cafdc4e50c5

**Comment by Goddfrey** [comment]
Yes this has been the case for years.

**Comment by ReikaKalseki** [comment]
And yet only reported now.

**Comment by ReikaKalseki** [comment]
Fixed.
