### ISSUE TITLE
[ChromatiCraft 29g] Elemental Sonar ability issue.

### ISSUE THREAD

**Issue by antrobot1234** [ReikaKalseki/Reika_Mods_Issues#2873]
I am having issues with the elemental sonar, making progression through the dimension all but impossible. When I entered the dimension for the first time, the elemental sonar worked as expected, I got the Ykri dimensional core, and left the dimension. However, whenever I try to use it again, it saps me of lumens as expected, but no GUI element appears on screen. I have exited and re-entered the dimension several more times now, and each time the ability is run but no map is made. I am at a loss at what to do, as without this ability I don't know of any way around this besides immense cheating.

**Comment by Riyshn** [comment]
I encountered this once, and restarting the game seemed to fix it. Playing SSP, so not sure if it was restarting the "client" or "server" that did it.

**Comment by antrobot1234** [comment]
that did the trick, thank you! however, I'm still going to leave this issue up as it's still a bug that should be fixed.

**Comment by ReikaKalseki** [comment]
Were structures present in the dimension at all? Check the logs for errors regarding its data.

**Comment by ReikaKalseki** [comment]
Given the lack of information, I am going to assume it was indeed a partial deletion failure, which I can do nothing about.
