### ISSUE TITLE
Essentia Relay priority

### ISSUE THREAD

**Issue by Savallator** [ReikaKalseki/Reika_Mods_Issues#2875]
The Essentia Relay currently does not seem to have any priority, so you easily end up with multiple half filled jars of the same type.
It would increase the usability if it would priorize the same order as golems:
Labeled Jar>partially filled jar > void jar > new jar

Edit: As an example, if you have a filled alembic, put down several jars empty and then activate the relay, it will partially fill all of them. But also, sometimes it fills new jars even if partially-filled ones are available for that type.

**Comment by ReikaKalseki** [comment]
They *do* have priority, but that priority is solely based on suction and labelling. Prioritizing void over new has been asked before and rejected on the basis that that is going to be actively undesirable to many players.

**Comment by Savallator** [comment]
Then, it does not work, since it will happily begin new jars even when half-full are available.

As i said: 
"As an example, if you have a filled alembic, put down several jars empty and then activate the relay, it will partially fill all of them. But also, sometimes it fills new jars even if partially-filled ones are available for that type."

That should not be expected behavior, right?

**Comment by Savallator** [comment]
I just confirmed again: It does definitely start new jars even though there are partially filled jars of that aspect in range and bound to it

**Comment by ReikaKalseki** [comment]
I rebalanced the suction values and specifically forced jar sorting based on fill level and type.
