### ISSUE TITLE
RotaryCraft's Rock Melter can't melt pyrotheum dust

### ISSUE THREAD

**Issue by Konrad-Wszelaki** [ReikaKalseki/Reika_Mods_Issues#2876]
I've noticed this when trying to do exactly what the issue suggests. The lava maker was powered with ReactorCraft turbine so it had nearly 1 GW of power, reaching max temperature of 1800 degrees quite easily. This should be sufficient to melt pyrotheum (with which it was filled to the brim), but it isn't.

Looking at the code for lava maker and for the recipe, it is rather clear that it can't melt it. Pyrotheum's melting point is the exact same as lava maker's max. temperature, and the condition to melt something is that the current temperature must be higher than melting point of whatever is inside of the lava maker, and since we can't exceed 1800 degrees we also can never melt pyrotheum which would require at least 1801 degrees. 
Should be an easy fix, either by increasing max. temperature, lowering pyrotheum's melting point or changing the condition to '>='.
Unless of course it's just me who missed something, feel free to correct me if that's the case.

**Comment by ReikaKalseki** [comment]
Fixed.
