### ISSUE TITLE
[RotaryCraft V29g] Can't configure range of Sonic weapon.

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2877]
https://github.com/ReikaKalseki/RotaryCraft/blob/master/TileEntities/Weaponry/TileEntitySonicWeapon.java#L266

Line 267~270 in function "getRange()" are unreachable code because "this != null" is always true.
Thus getRange() always return 16.

**Comment by ReikaKalseki** [comment]
This looks like me deliberately nulling that feature out in such a way to leave a code warning, and I do have some memory of doing this because of the range making the thing useless. I am going to just remove the option.

**Comment by XenonDB** [comment]
Well, actually I want to disable sonic weapon by set it range to 0 because rate of return of this thing is ridiculously high and don't need more progression.

Set the volume to 183 db, you can immediately kill almost any creature in a radius 16 sphere region by giving them 2^31-1 out of world damage.
The power require is 65536Nm * 4 rad/s , You just need 3 AC electric engines and 1 worm gear to satisfy requirement.
The risk is you may be kill by this. However you can just wear a helmet to perfect avoid this.

Compared with railgun, you need to get bedrock alloy ingot to let it deal 2~31-1 damage in one hit.
And the risk is you may be kill or your base may be destroyed by railgun

**Comment by ReikaKalseki** [comment]
> Well, actually I want to disable sonic weapon by set it range to 0

Even had the range config been functioning normally, that would not have been possible.

As for the damage curve on the device, that is worth looking into.
