### ISSUE TITLE
[Suggestion, Chromaticraft] Protection 5

### ISSUE THREAD

**Issue by CFlatFlat** [ReikaKalseki/Reika_Mods_Issues#2878]
Considering that you can add Sharpness X with the chromatic enchanter, it might be worth considering to add Protection 5 as well. There aren't any sources of this enchantment for 1.7.10 that I know of, and Astral Sorcery lets you use it in later versions. 

(Also the protection enchantment specifically is bugging out a little, it applies correctly but there's no animation or change in numbers during the process.)

**Comment by XenonDB** [comment]
> There aren't any sources of this enchantment for 1.7.10 that I know of

You can use Overchanting Table from Thaumic bases to get Protection 5
https://ftbwiki.org/Overchanting_Table

**Comment by ReikaKalseki** [comment]
Done.
