### ISSUE TITLE
Mipmap Problems with DragonAPI, ChromatiCraft

### ISSUE THREAD

**Issue by DarianLStephens** [ReikaKalseki/Reika_Mods_Issues#2879]
I didn't find any mention of this here, and it's unlikely to be fixed if no one does, so here goes.

With only DragonAPI installed, Mipmaps will gain a black border, seemingly where the alpha should be.
After installing ChromatiCraft, Mipmaps will not work period, regardless of any settings in Options.

Personally, I quite like Mipmapping, despite always disabling it in years prior.
It prevents a lot of shimmering in the background, and makes things look more cohesive.
It's not perfect, but it's a sight better than having it disabled.

For comparison, here are screenshots from these two mods being installed, and the effect they have on visuals.

Forge Only. The 3 mods present are Forge, Forge Modloader, and Coder Pack.
![2021-08-14_03 08 04](https://user-images.githubusercontent.com/15375876/129395581-510865c9-13ea-49fe-a58a-540a70b93436.png)

This is after adding DragonAPI. The two added mods are DragonAPI and its ASM Data Initialization.
The mipmaps no longer seem capable of showing alpha, and so blocks like flowers or tall grass have borders when the texture is viewed from any mipmap-showing angle:
![2021-08-14_03 08 44](https://user-images.githubusercontent.com/15375876/129395737-bbc9c786-a6e2-4673-9f08-f6f8adbf594e.png)

And finally, ChromatiCraft. Mipmaps aren't visible period, leading to a very grainy image that only worsens when in motion:
![2021-08-14_03 11 17](https://user-images.githubusercontent.com/15375876/129395797-7d24c05c-f100-49fa-ada0-db18d8b1584c.png)

I hope these issues can be fixed in the future, because despite having wanted to try these mods _properly_ for years, there always seems to be some technical or graphical problem that me and my friends aren't willing to work with.

**Comment by DarianLStephens** [comment]
Make sure you view the images at full size, because the problems, especially in the final one, fade away due to the resolution shrink.

**Comment by MalTeeez** [comment]
I put these in a gif, and a slight change in lighting towards the back is also noticeable
![1-3](https://user-images.githubusercontent.com/41554385/130329327-c51dd093-43e5-4a01-9689-bc9a380f5034.gif)

Also my own test on a tree:
![Unbenannt](https://user-images.githubusercontent.com/41554385/130333133-d4ccb35b-380f-4ac0-a7c0-b53d59fe1c28.png)

**Comment by ReikaKalseki** [comment]
CC has a few tiny textures that cannot be mipmapped, and the game reacts to this by globally disabling mipmapping.

As for the DAPI issues, that sounds like #2302. I suggest you read it and expand upon it if it sounds familiar, because that issue has gone unaddressed for a great length of time because of the original reporter not being able to coherently describe the issues and generally reporting a dozen clearly unrelated behaviors as part of the same issue.
