### ISSUE TITLE
[ChromatiCraft][V8g][Minor]Item Fabricator console error

### ISSUE THREAD

**Issue by Modbder** [ReikaKalseki/Reika_Mods_Issues#288]
After placing the Item Fabricator into world it would start randomly outputting the following in the console:

http://pastebin.com/KFVJgKiC

It is really not an issue, since it happens infrequently and does not affect gameplay at all, the game would not crash, players would not get kicked and everything works fine with the fabricator. I just would like to report that to you in case it is something you might want to know. Feel free to close the issue if it is a very minor thing and is not worth spending time on. Thanks for your awesome mods! :)

**Comment by Reignofmagic** [comment]
I got the exact same thing for one of my Gas Turbines last night. It gets toggled based on my current RF levels in my large capacitor bank. I don't think it is a big issue unless it happens a lot.

**Comment by ReikaKalseki** [comment]
The line of code this points to cannot error, meaning that the code has been changed since v8. If this persists in v9, get me to reopen this.
