### ISSUE TITLE
[ChromatiCraft V29g] Crash with BetterQuesting during selecting item.

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2881]
When you setting item for quest icon or task, client immediately crash.
This doesn't happen with ChromatiCraft V28.

steps of reproducing crash:
1.enable edit mode (/bq_admin edit)
2.open BQ GUI and click "Quest->Edit"
![1](https://user-images.githubusercontent.com/58476103/130179012-af68b950-11e3-4614-bf4f-91ba50915e29.png)
3.Click "Add New->New Quest Line->Icon" and game crash.
![2](https://user-images.githubusercontent.com/58476103/130179030-6ee0864b-6ef3-4512-85be-793cff859058.png)

crash report:
https://paste.ee/p/Rh6RG

**Comment by ReikaKalseki** [comment]
I fixed the crash, but this is due to an invalid item that will likely cause issues later.
