### ISSUE TITLE
[ReC] Null type Steam from HTGR

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2883]
Recently I've noticed NULL type steam in my steam lines coming from the htgr steam boiler.
I've seen #2618 and am on the newest version.
![image](https://user-images.githubusercontent.com/41554385/130680190-5648fdbe-a509-4359-82ac-1ce90e07ac07.png)

**Comment by ReikaKalseki** [comment]
Did this reactor exist before that?

**Comment by MalTeeez** [comment]
The Steam Lines, Boiler and Heat Exchanger have been replaced since the last update, the reactor hasn't but as far as I know that doesn't matter.

**Comment by ReikaKalseki** [comment]
It does.

**Comment by MalTeeez** [comment]
Replaced the whole reactor, steam lines and heat exchanger:
![image](https://user-images.githubusercontent.com/41554385/132349211-5dbd7294-2de5-474d-a7fe-3f1c16325662.png)

**Comment by ReikaKalseki** [comment]
I put in some more checks; at this point, null should be impossible, even on old reactors.
