### ISSUE TITLE
Sugestion for Rotarycraft

### ISSUE THREAD

**Issue by ThomasDennisSp** [ReikaKalseki/Reika_Mods_Issues#2885]
I noticed that the deeper you place maschines the hotter they get to the point that for example the fermenter doesnt produces or gets really slow. So i was wondering if you could add a config in which we could disable the temp getting hotter the deeper we go so we have a overall stable temp of around 30 - 35C at every y level that would be great if not it is no big deal would just be cool for people that build there factorys on the bedrock like me

**Comment by ReikaKalseki** [comment]
No, this is not being changed.
