### ISSUE TITLE
Drop mod dye instead of lapis when breaking rainbow/Nila leaves

### ISSUE THREAD

**Issue by HellsingDarge** [ReikaKalseki/Reika_Mods_Issues#2886]
Config entry that changes what exactly is dropped instead of lapis, i.e. either Biomes O'Plenty blue dye (`BiomesOPlenty:misc:5`) or Natura's blue dye (`Natura:barfleyFood:8`) without having to crack `Vanilla Dye Drop Percentage` to 0 and have another 16 functionally identical dyes. To go with the general idea of them dropping a _dye_ instead of a mineral

**Comment by ReikaKalseki** [comment]
I have no objection to color-specific options for each of the dye drop chances - though implementation is going to be a little annoying - but it is not worth the effort of checking loaded mods and reflectively fetching their items, and hoping that those items never change or are removed.

**Comment by ReikaKalseki** [comment]
Done.
