### ISSUE TITLE
LootTweaker Crash

### ISSUE THREAD

**Issue by gmnovakrc** [ReikaKalseki/Reika_Mods_Issues#2887]
Crashes after mod loading screen before the main menu. 
Using the latest version, I'm sure one of the many mods I'm using that is the culprit.

Crash Report
[crash-2021-09-02_10.18.19-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7099661/crash-2021-09-02_10.18.19-client.txt)

Log
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7099650/latest.log)

Any help is appreciated

**Comment by ReikaKalseki** [comment]
#2847
