### ISSUE TITLE
[ROC v30b] CH XMLs incorrectly formatted

### ISSUE THREAD

**Issue by EnderAvaritia** [ReikaKalseki/Reika_Mods_Issues#2892]
there is a clash when I launch only with ROC

https://paste.ubuntu.com/p/sBtjj7Wpgw/

it occured in the Initializing stage。

**Comment by EnderAvaritia** [comment]
the crash occured when I launch the game with chinses(sinplified) if I change the language after I lauch the game with Engilsh it will not crash.,if I delect the file RotaryCraft\Resources\zh_CN\categories.xml it can also launched 
but the translation can't work in any condition.

**Comment by ReikaKalseki** [comment]
Then that means the chinese localization files are broken, and whoever wrote them messed with them in ways that is not supposed to be done. I need valid files to fix this.

**Comment by EnderAvaritia** [comment]
> Then that means the chinese localization files are broken, and whoever wrote them messed with them in ways that is not supposed to be done. I need valid files to fix this.

whether I have any method to fix the files, I tried to use any other files in the other language ,but it also crashed (https://paste.ubuntu.com/p/QYKr9sBfbP/) 
are different file coded in different formats ?

**Comment by ReikaKalseki** [comment]
No, though some might have weird encodings. I only made the english ones, and can offer no information about what the other ones did.

**Comment by EnderAvaritia** [comment]
> No, though some might have weird encodings. I only made the english ones, and can offer no information about what the other ones did.

it seems I don`t have any methods to make this mod show chinese in the game ?

**Comment by ReikaKalseki** [comment]
If those files are invalid, then no.

**Comment by EnderAvaritia** [comment]
> If those files are invalid, then no.

ok,thank you for your help

**Comment by DarkLei** [comment]
> > If those files are invalid, then no.
> 
> ok,thank you for your help

If you want to use chinese,there is a method to fix it.Delete the file(rotarycraft/Reika/RotaryCraft/Resources/zh_CN/categories.xml )

**Comment by DarkLei** [comment]
@EnderAvaritia

**Comment by EnderAvaritia** [comment]
> > > If those files are invalid, then no.
> > 
> > 
> > ok,thank you for your help
> 
> If you want to use chinese,there is a method to fix it.Delete the file(rotarycraft/Reika/RotaryCraft/Resources/zh_CN/categories.xml )

I have applyed this method but what I need is not only launch the game , I hope I can have a locialized book to guide the players how to enjoy the mod.

**Comment by ReikaKalseki** [comment]
This was fixed in v31.
