### ISSUE TITLE
v30b.ROC caused crash with Botania

### ISSUE THREAD

**Issue by Mgctz** [ReikaKalseki/Reika_Mods_Issues#2894]
https://pastebin.com/EM89Vksb

It looks like bot caused this, but when I ban roc it works.

**Comment by ReikaKalseki** [comment]
You have some mod causing an API classload failure. Try removing mods, or adding the botania API to the DAPI jar (try the former first).

**Comment by Shahelion** [comment]
There are three mods erroring in that report. CrC, Botania, and something called SlashBlade-Terra. I have Botania and CrC and RoC working together just fine in my pack, so my guess is that one. From a quick google search, it looks like a SlashBlade addon that has a Botania dependency, maybe it has an old copy of the Botania API?

**Comment by Mgctz** [comment]
Thank you for your reply. I have solved the problem, it looks like that I should not name the mods with Chinese character.
I delete the config files of Reika's mods and re-download mods. However it still makes a crash.&nbsp;
Then, I ban the mod which casues crash one by one. It still makes some crashes. But I find that there is a sequnce of the mods cause crashes. Their Chinese-translated names are following the order of alphabet in some way.&nbsp;
So I delete the Chinese parts in thier names, these are automatically added by my unofficial launcher. Whatever, it works, I don't figure out which step kicks in.
Thanks for your answer again.

---Original---
From: ***@***.***&gt;
Date: Wed, Sep 29, 2021 13:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ReikaKalseki/Reika_Mods_Issues] v30b.ROC caused crash with Botania (#2894)




 
There are three mods erroring in that report. CrC, Botania, and something called SlashBlade-Terra. I have Botania and CrC and RoC working together just fine in my pack, so my guess is that one. From a quick google search, it looks like a SlashBlade addon that has a Botania dependency, maybe it has an old copy of the Botania API?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
