### ISSUE TITLE
ReactorCraft V30a - Redstone torches no longer shut down fusion injectors

### ISSUE THREAD

**Issue by rkane31174** [ReikaKalseki/Reika_Mods_Issues#2895]
I usually use redstone torches to shut down parts of the fusion reactor. That doesn't seem to work in the new release.
I checked the handbook and it doesn't say anything different, so I figured this might be a reportable bug.

**Comment by ReikaKalseki** [comment]
I know what did this.

**Comment by ReikaKalseki** [comment]
Fixed.
