### ISSUE TITLE
[ElectriCraft V29a] <Reika/ElectriCraft/Network/PathCalculator.recursiveCalaulate> Causing a lot lag

### ISSUE THREAD

**Issue by TheRealKamisama** [ReikaKalseki/Reika_Mods_Issues#2896]
I was playing a server with ElectriCraft and other Reika mods.  
The TPS and Ticktime became unplayable since I started using ElectriCraft's power system.  
![before](https://user-images.githubusercontent.com/35005476/134387527-82127685-d1d4-405d-ba5e-08e6b9daa04a.png)  
All the dimensions' ticktime add up and didn't go above 50ms, but the Overall just broken.  
I ran a profiler on the Server-side and found this:  
Huge spike about a method.

![all](https://user-images.githubusercontent.com/35005476/134387648-a4372920-ae12-4afe-929d-bb091674e550.png)
![spike](https://user-images.githubusercontent.com/35005476/134389693-5268fd53-a1e3-430e-81a7-ac91dc73ef5a.png)
![zoom](https://user-images.githubusercontent.com/35005476/134387653-f5f4b496-2898-4f99-afeb-94ef43990b81.png)

There seems to be a performance issue with the method <Reika/ElectriCraft/Network/PathCalculator.recursiveCalaulate>.  
I only used two normal ReactorCraft turbine with their multiblock generator to power the machines.  
I did a quick test to see what will happen if I delete ElectriCraft.  
Result:
![after](https://user-images.githubusercontent.com/35005476/134388243-5a6d104d-debb-4026-9c5a-d6cee1ade2b4.png)
Hope to see a solution about this, better than just deleting ElectriCraft.

**Comment by TheRealKamisama** [comment]
[profile.html](https://drive.google.com/file/d/13StwB8Yw8YGo5Oy4ajaAgeD6mcLVMUkf/view?usp=sharing)
The full profile file.

**Comment by rkane31174** [comment]
The latest version of ElectriCraft is v30a. Try it with that version.

**Comment by TheRealKamisama** [comment]
> 
> 
> The latest version of ElectriCraft is v30a. Try it with that version.  

Still
![still](https://user-images.githubusercontent.com/35005476/134621688-c57ecd28-958c-4f66-a50f-2b5b36d37e1c.png)

**Comment by TheRealKamisama** [comment]
Also I noticed the Overall ticktime is slowly biasing over time, and reach a 200ms ~ 300ms peak and cripple the server.   
Ran another profiler with ElectriCraftV30a, same result. 
![updated](https://user-images.githubusercontent.com/35005476/134622299-921bc644-7538-431d-a970-5044f0e1cf49.png)

![welp](https://user-images.githubusercontent.com/35005476/134622305-0996e2dc-7518-44b1-a448-ae950c21a4eb.png)

**Comment by ReikaKalseki** [comment]
`recursiveCalculate` is done whenever the network input changes, and thus it needs to recalculate all the current and voltage values across the network. This is a known effect of hooking a rapidly-varying power input to the network.

*However*, the turbine generator is supposed to smooth that out...unless your turbine is underpowered: is your turbine hovering around 950MW, or is it fluctuating below that point? In particular, how much torque is it producing, and does its speed ever vary?

**Comment by ReikaKalseki** [comment]
I put some additional smoothing into the turbine to eliminate all fluctuations in a well-running turbine. Anything beyond that is an artifact of poor power supply.

**Comment by TheRealKamisama** [comment]
Well... I actually found a underpowered turbine in my friend's base and shut it down.  
But... the problem still exists... I wonder if it has to do with RF Transfer Cable Network's logic?
The problem is getting worse over time, so maybe a memory leak or a undisposed object?  
I still think there's a bug within the method itself.  
![ah no](https://user-images.githubusercontent.com/35005476/134781135-c2ded8ec-6101-412f-be09-ddeb16b5f615.png)

**Comment by ReikaKalseki** [comment]
Try again in v30c.
