### ISSUE TITLE
Archisections v30b is causeing server side crashes 

### ISSUE THREAD

**Issue by quindao** [ReikaKalseki/Reika_Mods_Issues#2897]
the mod seems to be attempting to interface with the rendering engine server-side at which point it fails to find files that run the rendering engine as they don't exist server-side

here's the crash log
https://gist.github.com/quindao/6cfe83e715ce272a0ebf3c8e7ef746be

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by ghost** [comment]
When will this be released?
