### ISSUE TITLE
[ChromatiCraft][V8g]Server-side problems

### ISSUE THREAD

**Issue by Modbder** [ReikaKalseki/Reika_Mods_Issues#290]
I have already reported similar issue in #225, but I've found 2 more. One of them might have been reported already, not sure about that one.

Similar to #225 these only occur on server side, client is always fine, and the respective methods have @SideOnly(Side.CLIENT) annotations.

1)Lumen Turret:
http://pastebin.com/E16z0kvb

2)Vacuum Gun
http://pastebin.com/dC0eC6PN

The Lumen Turret issue occurs whenever the turret is attacking.
The Vacuum Gun issue occurs whenever the vortex pulling everything towards is finished.

**Comment by ReikaKalseki** [comment]
1) is already fixed.

**Comment by ReikaKalseki** [comment]
2) is fixed.
