### ISSUE TITLE
[RotaryCraft V30c] Sonic Weapon balancing very broken

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2900]
![2021-09-26_15 29 21](https://user-images.githubusercontent.com/58476103/134798253-a85b6c8b-7a84-41a7-be9f-b944a9f9ba1b.png)
Well...I even don't need gear box to raise torque input for setting high volume output for sonic weapon.

**Comment by ReikaKalseki** [comment]
This is not new to v30.
