### ISSUE TITLE
[ArchiSections V30c] Crash on server trying to load client class

### ISSUE THREAD

**Issue by Milii20** [ReikaKalseki/Reika_Mods_Issues#2904]
Greetings! Sorry to bother, i recently updated a pretty big modpack i play with my fiance from V29's versions to V30, and the server we use crashed with the following Crashlog: 

https://pastebin.com/JcWM6eFj

Please tell me if there is any other log you need

Thank you in advance!

**Comment by ReikaKalseki** [comment]
Fixed.
