### ISSUE TITLE
[Chromaticraft v30c] Huge fps drop and spikes in Ender Forest Biome

### ISSUE THREAD

**Issue by Sipepper** [ReikaKalseki/Reika_Mods_Issues#2905]
From 100+ to 15-30 on a "clean" client.
I`ve created a test modpack to be sure.
Mods: 
ChromatiCraft 1.7.10 V30c.jar
DragonAPI 1.7.10 V30c.jar
NaturesCompass-1.7.10-1.3.1.jar
Thaumcraft-1.7.10-4.2.3.5.jar
Seed of the world :
-3574264238238015576
Coordinates:
x=4212
y=81
z=-3551
Options:
https://pastebin.com/FFVfRwmp
Latest Log:
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7253580/latest.log)

I suppose the problem is in chunk ticking
"[19:12:08] [Client thread/INFO]: Warning: Clientside chunk ticking took 268 ms"

**Comment by ReikaKalseki** [comment]
That warning is vanilla and happens no matter what when chunks are first generated or loaded. And it is not remotely unique to the Ender Forest.

**Comment by Sipepper** [comment]
I know that first loading or generating a new chunk is laggy. But strange thing is that even when i stay afk in ender forest biome, staring in a same spot i have 30 fps average. Before submitting i`ve checked the rainbow forest, and all was fine, even when new chunks are loading first time.

**Comment by ReikaKalseki** [comment]
The only difference between those biomes (where the Ender Forest may be more expensive than the Rainbow Forest rather than the far more common reverse) is in the new biome coloring. Go ahead and try enabling the purple color (and thus bypassing the new color) as a test, but I rather doubt it to be involved.

**Comment by Sipepper** [comment]
Yep, swaping to old colors 
"[E3A9A6252] Ender Forest Coloring"=true
Removes all lags and spikes.

**Comment by XenonDB** [comment]
I making some test and encounter this issue too: (This doesn't happened in V29g)

Creative flying in ender forest cause huge FPS lag:
![2021-10-01_14 26 03](https://user-images.githubusercontent.com/58476103/135579010-8b388e7d-3e73-4a37-bc3e-deb02c0c2587.png)

However, this doesn't happened when I use matter phase ability:
![2021-10-01_14 26 36](https://user-images.githubusercontent.com/58476103/135579235-d78340c0-e631-4b3e-a46b-2ed4cf29c466.png)

I also use VisualVM to make some CPU profiling:
This is CPU profiling in ChromatiCraft V30d
![1](https://user-images.githubusercontent.com/58476103/135579628-c7b8d9cd-f2e9-4b25-a3be-1f8d0cd5a7f5.png)

getMix() seems a function related with grass and leaf color
https://github.com/ReikaKalseki/ChromatiCraft/blob/master/World/BiomeEnderForest.java#L111

I check the call tree of client thread and found a sorting function took almost 10 second during this profiling:
![3](https://user-images.githubusercontent.com/58476103/135579904-d0828d84-fb07-4a75-943d-3b07f28e25cd.png)

Maybe this is the reason?


Compared with profiling in V29g:
![2](https://user-images.githubusercontent.com/58476103/135580323-450f959a-94f3-447b-8c09-a5ea8888c9bf.png)


Some off-topic : rotarycraft V30d seems not to be uploaded

**Comment by XenonDB** [comment]
> Yep, swaping to old colors "[E3A9A6252] Ender Forest Coloring"=true Removes all lags and spikes.

Sadly, this option is bound to client. Modpack maker cannot change this setting for all player playing this pack.

**Comment by Shahelion** [comment]
Ah, so THIS is what was happening. I average 30 FPS normally, down to literally 1 or 0 FPS in the Ender Forest (thought it was Witchwood Forest at first).
Also of note, the most recent update seems to have forcibly changed the config option to the green coloring. I had it set to the purple before, and definitely did not change it myself. I predict a lot of people experiencing this issue because of this.

**Comment by ReikaKalseki** [comment]
I have fixed the lag, but at the cost of making it look as good...
