### ISSUE TITLE
[ChC][V29g] Nether well loot chests all have the same loot

### ISSUE THREAD

**Issue by kutschkem** [ReikaKalseki/Reika_Mods_Issues#2906]
The last ~10-15 (newly generated) loot chests from the nether wells all looked like this:

![image](https://user-images.githubusercontent.com/1106888/135501244-a78d87ee-35f3-461d-a023-d5d07946bdd9.png)

Seems statistically unlikely and probably indicates there is an issue with the randomization?? I think I saw a similar issue here before but couldn't find it.

**Comment by ReikaKalseki** [comment]
This is in v30c? You are thinking of #2339, which I did fix.

**Comment by kutschkem** [comment]
29g, I haven't updated yet. Will check this again after I update.
