### ISSUE TITLE
Curseforge mod release missing?

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2907]
The 30d Version for RotaryCraft is missing from Curseforge and the Satisforestry-JourneyMap fix didn't make it into 30d?

**Comment by ReikaKalseki** [comment]
What SF journeymap fix? Do you mean the CC Ender Forest one? And why would RC update to fix an issue in either mod?

**Comment by MalTeeez** [comment]
Those two were meant separately, mainly why the 30d version of RotaryCraft is missing from curseforge even though its in the 30d changelog (https://reikakalseki.github.io/minecraft/pages/info/changelog.html)

**Comment by ReikaKalseki** [comment]
That is a valid point.
