### ISSUE TITLE
[ChromatiCraft V30d] Place lock onto rune in new overworld puzzle cause game crashing

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2908]
step to reproduce:
1. /chromaprog progress BIOMESTRUCT true
2. /chromaprog progress BIOMESTRUCT false
3. find the struct in ender forest
4. click light switch tile to open door. Go down and gain key then place key onto rune.

https://paste.ee/p/eaUhr

**Comment by ReikaKalseki** [comment]
Fixed.
