### ISSUE TITLE
[ChC v30d]Frozen Outpost loot chests have no loot in them.

### ISSUE THREAD

**Issue by AssasinAsha** [ReikaKalseki/Reika_Mods_Issues#2909]
Hello,

got some time to play around, found some snowy outposts and they don't have loot in chests.
Don't know if it matters but I can open chests while the controller is active, even if they have a solid block above them. After I destroy the controller, I have to break the solid block to access them. They also don't have the purplish glow like in other structures.
Whether I access a chest before breaking the controller or I destroy the controller before opening chests, there is no loot, the chests are empty.
There are no generation errors logged into chat.
I even tried maximizing progression before looking for outposts, nothing changed.
I remember it working in older versions but I can't recall which ones and I haven't played in a long while, so I'm afraid I can't pinpoint a possible change.

I've seen some discussion regarding this on the minecraft forum, something about Geostrata. I think that's a dead-end since I only have these mods in:

Forge 10.13.4.1614
DragonAPI v 30d
Chromaticraft v30d 

That's it, clean install.

I've found a nice Large Biomes seed with plenty of ice plains biome to test, so if you have ideas to check, go ahead.

**Comment by ReikaKalseki** [comment]
Is there a nearby empty copy?

**Comment by AssasinAsha** [comment]
If you mean a copy of the building just without chests then no, or at least, I can't find one. Not over- or underground
And sorry for misnaming the thing, it's Frozen not Snowy. I have no idea what was running through my mind.

**Comment by ReikaKalseki** [comment]
When the structure was generated, were there any messages about a structure gen encountering errors?

**Comment by AssasinAsha** [comment]
I've just re-created the map, spawned an aura tracker, found the Outpost trail right away, hurray! Got there, broke in, broke the controller, no loot in the chests and the only errors were a render error (1282: invalid operation) and something about me losing progression. But I didn't get that last time, so I don't think it's relevant.
Other than that, nothing. It's quite annoying, really. Obviously you can find loot easily, else it would've been dealt with already.

**Comment by ReikaKalseki** [comment]
Fixed. I redid how "active" block placement in the structures were done, and did not account for after-place offsets.

**Comment by AssasinAsha** [comment]
Awww, and I was kinda looking forward to stumbling my way through the code base, trying and mostly failing to understand what am I looking at, hoping to find some clue as to the reason this weekend. And here you go and fix it.
Just kidding, thanks for the work you do with these mods.
If I'm allowed, a quick offtop question. Is it intended that I can see the precursor script through walls? Should I make a new issue?
