### ISSUE TITLE
[Fixed + Closed] Geostrata and Chisel 2 from Resonant Rise 3 don't get along.

### ISSUE THREAD

**Issue by xTwi** [ReikaKalseki/Reika_Mods_Issues#291]
Hi, I've stumbled across this error and I don't exactly know where to find this line, or how to fix it... http://pastebin.com/VyXA5r8Y

It's something breaking with Chisel 2 and Geostrata. I do have DragonAPI installed, the latest version currently available to download as well as Geostrata.

DragonAPI version: v8g
Geostrata version: v8b

I can supply more information if needed dependent of what it is and my understanding of it.
After looking through the log a bit, I've also seen that Gany's End has errored but if push comes to shove, I will disable it if I can't fix it.

Thanks in advance.

EDIT: I updated Chisel 2 which was missing a .class file which made the launcher kill itself, and it seemed to fix it although I was still plagued by other .class files missing. I eventually got the game working again.

**Comment by ReikaKalseki** [comment]
the problem is an old Chisel version.
