### ISSUE TITLE
[ROC v30c] Fractionation Unit not measuring pressure correctly

### ISSUE THREAD

**Issue by QuantxAmpere** [ReikaKalseki/Reika_Mods_Issues#2910]
If I understand the fractionation unit correctly, it requires a minimum speed of 8192 rad/s and the efficiency is determined by the input torque with maximum efficiency reached at 1024 Nm. For some reason a change in torque does not result in a change in pressure / output efficiency for me.

I was playing a modpack with 300 mods, waila kept showing efficiency stuck at around 5%.

I tested it also on a new clean install with the newest version of forge, and the following mods
- Dragon Api V30d
- Rotarycraft V30c
- Reactorcraft V30c
- Electricraft V30a

I have a Gas Turbine, full of jet fuel, running at full speed, directly going into a fractionation unit resulting in 1kNm of torque and more than enough speed.

![2021-10-02_18 25 48](https://user-images.githubusercontent.com/62445139/135726518-02bfcc59-f754-4aec-a732-703e09a2d19e.png)
 
the fractionation unit is full of required ingredients but the pressure is at 101.000 Pa

![2021-10-02_18 25 29](https://user-images.githubusercontent.com/62445139/135726551-99074951-18d9-4740-ae8f-18f84ca4f3f1.png)

this results in an output efficiency of around 5% yielding me around 50-150 mb per operation...

![2021-10-02_18 25 36](https://user-images.githubusercontent.com/62445139/135726582-89df4f32-a699-4168-bb66-1b931bb2e813.png)
![2021-10-02_18 25 44](https://user-images.githubusercontent.com/62445139/135726592-0f3dcce1-67f7-4145-bd5d-3db9c77c1171.png)

![2021-10-02_18 25 54](https://user-images.githubusercontent.com/62445139/135726596-99310337-d08b-44fd-b3f0-0d85445e88eb.png)

**Comment by QuantxAmpere** [comment]
I don't know what's causing the issue, but I'm pretty sure it has nothing to do with Open GL...

**Comment by ReikaKalseki** [comment]
It sounds like my changes to MovingAverage broke it.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by QuantxAmpere** [comment]
Thank you so much!

**Comment by Star4Fun** [comment]
Is the patch released yet? If so when do you plan to publish it?

**Comment by mati294** [comment]
So how to fix this problem?

**Comment by QuantxAmpere** [comment]
If I understand correctly, this is a bug in DragonAPI v30d. 
This bug in particular has been apparently fixed but (not sure why) Reika has not released the next version of DragonAPI.
I would build the current sources myself, but it appears to me that Reika has his own build system (not the default forge gradle) at least I couldn't find any build.gradle file or anything similar. 
The only real fix would be to downgrade to a version of DragonAPI (and Rotarycraft, Electricraft et al) if you can find the files, or to wait for Reika to publish the new version (v30e) which I don't know if it's complete yet, all I know is there is no officially released fix yet. Just keep watching the [curseforge site](https://www.curseforge.com/minecraft/mc-mods/dragonapi) for an update

**Comment by Credit-Score** [comment]
I'm glad to see it's not just a glitch on my end, though if it is fixed I would love to see the fixed version live. Since in the meantime, I'm just constantly living with producing Jet Fuel at 5% efficiency.
