### ISSUE TITLE
[ChromatiCraft v30d] Structure runes are partially visible through blocks

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#2912]
The runes themselves aren't visible, but the lines are.

![2021-10-09_22 56 36](https://user-images.githubusercontent.com/6917535/136684492-9d4ac2b4-4904-4c66-9668-8ede731e80b0.png)
![2021-10-09_22 58 13](https://user-images.githubusercontent.com/6917535/136684496-16f17493-780b-448a-82a2-5c14b5ce810b.png)

**Comment by Shahelion** [comment]
Looks like not just that structure, potentially all of them.
![2021-10-09_23 41 04](https://user-images.githubusercontent.com/6917535/136685570-fb1d8c50-d3e6-44e2-bcaa-9b718c5aadad.png)

**Comment by ReikaKalseki** [comment]
Fixed.
