### ISSUE TITLE
[Chromaticraft v30d] Radiant Bee crashes server

### ISSUE THREAD

**Issue by wamc2017** [ReikaKalseki/Reika_Mods_Issues#2913]
Hi,

tried using a Radiant Bee in an Alveary and my local server crashed with the following report (didn't happen instantly):
https://gist.github.com/wamc2017/b0bbe8450101a37ed8d7ac37c6648db5

After rebooting the server the bee was gone from the Alveary.

Thanks for looking into it.

Best regards,
wamc

**Comment by ReikaKalseki** [comment]
Fixed.
