### ISSUE TITLE
[Chromaticraft v30d] Lumen clarifier throws errors on server

### ISSUE THREAD

**Issue by wamc2017** [ReikaKalseki/Reika_Mods_Issues#2914]
Hi,

everytime I try to assemble the Lumen clarifier the server log gets spammed with the following error:
https://gist.github.com/wamc2017/706a78ba7681397bd4a599f0c97fb700

Thanks for looking into it.

Best regards,
wamc

**Comment by ReikaKalseki** [comment]
Fixed.
