### ISSUE TITLE
[Chromaticraft v30d] Anti cheating protection runs in the overworld

### ISSUE THREAD

**Issue by wamc2017** [ReikaKalseki/Reika_Mods_Issues#2915]
Hi,

tried to use some Travel Anchors from Ender IO in my base and everytime I place them they explode. Also tried the Staff of Traveling with the same result. I guess the anti cheat protection should not run in the overworld. 
On a side note, I currently can't unlock "Finding a shortcut" when I try to place down a Travel Anchor inside a puzzle structure in the dimension (did work this way a few versions ago...)

Thanks for looking into it.

Best regards,
wamc

**Comment by ReikaKalseki** [comment]
Fixed.
