### ISSUE TITLE
Biomestruct progress missing text

### ISSUE THREAD

**Issue by MinerUser** [ReikaKalseki/Reika_Mods_Issues#2918]
I cant get a certain progress. It shows "#NULL!" for both the title and hint. I have not found a way to solve or circumvent this.
By going through progression.xml I have traced it back to being the "stones"(aka Unity of the Elements) progress, since that was the only one I couldnt find elswhere in the tree. Using the command to give me that specific progress didnt work, but using the command to give every progress did seem to activate it.
![2021-10-20_23 09 36](https://user-images.githubusercontent.com/92608706/138173342-066b1e77-7cfd-4e53-b8c2-e919021b41c6.png)

**Comment by wamc2017** [comment]
That should unlock if you visit one of the new biomefrag structures. I did get it by just walking into it, but couldn't solve it because of this bug: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2908

**Comment by ReikaKalseki** [comment]
Fixed.
