### ISSUE TITLE
No output when using Casting Delegate

### ISSUE THREAD

**Issue by MinerUser** [ReikaKalseki/Reika_Mods_Issues#2919]
I am using the Casting Delegate, connected to an ME System. It has been working flawlessly for a few days, even with recursive mode. I use a hopper to get the items out of the Casting Stand Insertion Focus to then put them back into the ME System via an Imprt Bus. 
But all of a sudden I dont get any output anymore. It uses up all the items, casts the recipe but nothing is pulled into the hopper. I also dont get the casted item when I break the Inertion Focus.

**Comment by MalTeeez** [comment]
Does it work when you use an import bus directly?

**Comment by MinerUser** [comment]
Oh well, thats odd. The issue was indeed caused by either the hopper or the item ducts.

**Comment by ReikaKalseki** [comment]
Besides, the tiles natively connect to ME.
