### ISSUE TITLE
GeoStrata additional ore / stone variants

### ISSUE THREAD

**Issue by bookerthegeek** [ReikaKalseki/Reika_Mods_Issues#292]
Hello good sir!

Would their be any way to be able to add other ores into your stone variants? An easy example would be IC2 uranium, Thaumcraft infused stone, or any of the metallurgy ores.

Understand if this is not able to do so, but would love the ability to add them. Even if I have to manually make a .json for each and every ore.

**Comment by ReikaKalseki** [comment]
The ores are currently only half-implemented and rather laden with issues; they are disabled by default for a reason.

Also, uranium and TC ores are automatically handled. Anything on [this list](https://github.com/ReikaKalseki/DragonAPI/blob/master/ModRegistry/ModOreList.java#L40), as well as vanilla, is.

**Comment by bookerthegeek** [comment]
Is that what the "ore mode" in the configs do?

**Comment by bookerthegeek** [comment]
Damn phone, is turning on "ore mode" enable those ores then?

And thank you for the link.

**Comment by ReikaKalseki** [comment]
Yes.
