### ISSUE TITLE
DragonAPI Nether Crash

### ISSUE THREAD

**Issue by gmnovakrc** [ReikaKalseki/Reika_Mods_Issues#2921]
Using latest version of DragonAPI, upon entering the Nether it crashes within a few seconds.
Thought it was FastCraft, was on previous crash report, removed it and it still happens, so now I'm unsure.

[crash-2021-10-23_12.58.51-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7403396/crash-2021-10-23_12.58.51-client.txt)

[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7403398/latest.log)

**Comment by wamc2017** [comment]
Have you tried disabling Smooth Entity Light?

**Comment by gmnovakrc** [comment]
> 
> 
> Have you tried disabling Smooth Entity Light?

Via separate mod like dynamic lights? Or in the config of DragonAPI? 
Not sure, still new to all of this.

**Comment by wamc2017** [comment]
I meant removing the mod from your mods folder for a test, because the first line in your crash-report hints at SEL is crashing the game not Dragon Api....
`at lakmoore.sel.world.WorldSEL.func_72802_i(WorldSEL.java:49)`

**Comment by gmnovakrc** [comment]
> 
> 
> I meant removing the mod from your mods folder for a test, because the first line in your crash-report hints at SEL is crashing the game not Dragon Api.... `at lakmoore.sel.world.WorldSEL.func_72802_i(WorldSEL.java:49)`

Ah, right that did it. Sorry still new to this. Reika's mod was the only name that I 1st spotted, just assumed.
