### ISSUE TITLE
Puzzle Cheat Prevention active in Overworld

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2922]
The Puzzle Cheat Prevention is now active at anytime for certain items in the Overworld, including the Dislocation Charms from Draconic Evolution, Staff of Traveling from EnderIO and probably more.

**Comment by wamc2017** [comment]
Already reported it here: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2915
