### ISSUE TITLE
Crash when in Proxima Dimension

### ISSUE THREAD

**Issue by ThomasDennisSp** [ReikaKalseki/Reika_Mods_Issues#2923]
So when i joined the Proxima Dim for the first time it took around 1 hour of no responding to finally respond because minecraft run out of memory but i have 12Gb given to minecraft from my 32Gb
when i tried again i got into the dim but it chrashes every few minutes and gives me the error: java.lang.NullPointerException: Invalid Biome id    and it is every time a different biome id so i dont khow what to do as the ids are from vanilla biomes.

Chromaticraft V30d
Dragon Api V30d
Electricraft V30a
Rotarycraft V30c
Optifine
and many many other mods

 
[crash-2021-10-25_14.09.43-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7409830/crash-2021-10-25_14.09.43-server.txt)

[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7409831/latest.log)

and what happened with your website i cant open it anymore?

**Comment by Jonius7** [comment]
> and what happened with your website i cant open it anymore?

New, updated site at https://reikakalseki.github.io/

**Comment by ThomasDennisSp** [comment]
video if needed from world loading till crash
https://youtu.be/r3-6RnUGlpI

**Comment by ReikaKalseki** [comment]
When this error happens it means something is messing with the chunk provider system, and many optifine versions do exactly that, in ways that are not compatible with forge or mods.

**Comment by quindao** [comment]
sorry to necro this issue but,
we had this issue, and removing optifine has not fixed it, here's the crash log post removing optifine [https://gist.github.com/quindao/93b44aa6ebb9dd9ff6fb88a83b818365](url)

**Comment by ReikaKalseki** [comment]
Then something else is doing it.

**Comment by quindao** [comment]
again sorry to necro but I have done testing with just chroma and dragon API on a fresh install and it's still happening so I am unsure how to proceed 
here's the crash log [https://gist.github.com/quindao/35d594d634db0a08cdd4375809ccfad5](url)

one thing of note is the biome id is always vanilla but it is often different

the steps to reproduce are 
1 enter dimension
2 run/fly around for a while 
3 game should crash after about 5 mins

**Comment by ReikaKalseki** [comment]
Well it has not happened once for me, either with just my mods or with a 200-mod pack.
