### ISSUE TITLE
[RotaryCraft V30c] Handbook document in simplified chinese version doesn't update cause crash

### ISSUE THREAD

**Issue by XenonDB** [ReikaKalseki/Reika_Mods_Issues#2924]
https://paste.ee/p/UZUw0

I think the reason may be in flywheels document:
https://github.com/ReikaKalseki/RotaryCraft/blob/master/Resources/info.xml#L49
https://github.com/ReikaKalseki/RotaryCraft/blob/master/Resources/zh_CN/info.xml#L47

**Comment by XenonDB** [comment]
Also, this document doesn't have tungsten(钨) material description. May cause data shifting and incorrect description?

**Comment by ReikaKalseki** [comment]
In order to do anything I need correctly updated files.

**Comment by XenonDB** [comment]
I made a pull request:
https://github.com/ReikaKalseki/RotaryCraft/pull/43

However, due to the hash checking for every file, I cannot test these changes locally.
Maybe you need to test these by yourself.

**Comment by ReikaKalseki** [comment]
Done.

**Comment by KuroPeach** [comment]
You can consider removing the expired language files. Players’ enthusiasm for translation does not always exist, so that it will not cause crashes because the default game language is an expired language file. :)

**Comment by ReikaKalseki** [comment]
I mean I *can* do that, but then people will complain because they think I have no localization at all and they (think they) have to start from scratch.

**Comment by KuroPeach** [comment]
Don’t worry, just like CC has no localization, we have some information in the domestic BBS and mcmod, although they haven’t been updated all the time, but at least we can avoid a lot of detours
https://www.mcmod.cn/class/462.html
https://www.mcmod.cn/class/85.html

The localization is stored on GitHub, but the follow-up is not so fast, and players need to supplement the missing items by themselves
https://github.com/KuroPeach/Reika_mods_Localization

**Comment by ReikaKalseki** [comment]
OK, I will remove the chinese locale for RC.
