### ISSUE TITLE
Void Monster V30c Spawn Issues

### ISSUE THREAD

**Issue by gmnovakrc** [ReikaKalseki/Reika_Mods_Issues#2927]
Dragon API V30d
Void Monster V30c
RecurrentComplex-0.9.7.1.2_Unoffical(bugfixes)

It appears its spawning above bedrock for some reason, happen to be with this RCU structure.
No open void under structure, definitely high enough above bedrock, when looking at cords. 
Just spawned underneath within a block.
I dug out a 3x3x3 square to free it then flew above ocean surface then it proceeded to phase through blocks and chase after.

![2021-10-30_15 31 42](https://user-images.githubusercontent.com/74471865/139556726-44933d80-7d68-4515-affb-9d4007c14870.png)

**Comment by wamc2017** [comment]
Did the monster attack you? If not it's probably the Halloween ghost version you encountered...
(I think this could be disabled by setting "Enable Temporally Dependent Amusement Behavior" to false in the DragonApi.cfg)

**Comment by gmnovakrc** [comment]
> 
> 
> Did the monster attack you? If not it's probably the Halloween ghost version you encountered... (I think this could be disabled by setting "Enable Temporally Dependent Amusement Behavior" to false in the DragonApi.cfg)

It was chasing after me. but was in creative mode so I don't know.
But i'll try that and see what happens.
What is that cnfg setting actually for?

**Comment by wamc2017** [comment]
It does things during specific dates like Halloween or April 1st to scare or troll the player... ^^
