### ISSUE TITLE
DragonAPI/ChromatiCraft Crash MultiMC

### ISSUE THREAD

**Issue by Ranavolio** [ReikaKalseki/Reika_Mods_Issues#2928]
Hello,

I am new to MultiMC 5 and upon starting, it crashes before the first screen even appears (log and modlist in pastebin below). Specifically DragonAPI and ChromatiCraft are the issue. I have read about a Thaumic Infusion conflict on here, but that mod isnt in the pack. I also read about versions being an issue, but I just installed today and they are all V30 versions, ot them all fresh from CurseForge. Could someone help me with that please?

Modlist and log: https://pastebin.com/CZy4WLj1

**Comment by XenonDB** [comment]
You are using Forge 7.99.36.1558.
Use 10.13.4.1614 instead.

**Comment by Ranavolio** [comment]
This didnt work.

Version conflicts within the Reika mods also shouldnt be the issue. I have tried using the mod versions that were installed in the Survival Industry Pack and it didnt work either.

If theres anything new heres the new log (with latest reika mods and updated forge): https://pastebin.com/1gNKLgjG

**Comment by XenonDB** [comment]
Did you install Reika's mod into DW20 1.7.10?

Update fastcraft to 1.25
DragonAPI is now compatible with latest fastcraft instead of outdated version(1.21)

**Comment by Ranavolio** [comment]
Yes I based it on DW20 1.7.10. 

Oh man, literally the second I found the thread pointing to this your answer came, thanks.

And just for record: The same will happen with OptiFine_1.7.10_HD_U_E7
