### ISSUE TITLE
[DragonAPI V30d] Server crash on startup

### ISSUE THREAD

**Issue by Azzezima** [ReikaKalseki/Reika_Mods_Issues#2930]
Updated Rotarycraft, Reactorcraft, Chromaticraft and DragonAPI to the latest version from 29g (Reactorcraft was version 29e) and resulted in a startup crash.
I've read that ClassCastException is often a result of a changed block ID but I haven't at least manually changed any block IDs.
Only ID I've changed is Chromaticraft's new Rainbow Stream Biome due to a conflicting ID.
Figured I'd report it just in case.

[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7522511/latest.log)

[crash-2021-11-11_19.10.31-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7522513/crash-2021-11-11_19.10.31-server.txt)

**Comment by XenonDB** [comment]
A mod may have different amount of item types between different version, thus may have different numerical id mapping in 1.7.10 despite you are playing old world (especially adding new item, compared with old version).

**Comment by ReikaKalseki** [comment]
This is block ID scrambling.
