### ISSUE TITLE
(Reactorcraft) HP turbine won't turn on when inputting ammonia steam into it

### ISSUE THREAD

**Issue by QuantumZizo** [ReikaKalseki/Reika_Mods_Issues#2934]
So when I input the steam into it, it just won't turn on. It just keeps consuming the steam even when i have a massive backlog of it.

**Comment by QuantumZizo** [comment]
I don't wanna risk making the pressure in the lines even higher because it might be able to explode it

**Comment by QuantumZizo** [comment]
Now the turbines won't work at all

**Comment by FavoritoHJS** [comment]
If memory serves, high pressure turbines require a lot of steam to start up.
Try blocking off the steam output for it to build up, then connect the turbine.
If it still doesn't work, remove a turbine or three and try again.

**Comment by QuantumZizo** [comment]
I have 200+ m^3 of steam in the pipe, it cannot be because of enough steam

**Comment by QuantumZizo** [comment]
That's what i mean by "Massive"

**Comment by ReikaKalseki** [comment]
200 is far from massive.
