### ISSUE TITLE
[Chromaticraft v30d] Depth mask problem when rendering dungeon "rune scripts"

### ISSUE THREAD

**Issue by FINDERFEED** [ReikaKalseki/Reika_Mods_Issues#2935]
Runic scripts in dungeons render through walls, i suppose that shouldnt be happening: https://imgur.com/a/P9cQcTu
I have only DragonApi,CC and journeymap installed (it happened without journeymap too).

**Comment by wamc2017** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2912

**Comment by FINDERFEED** [comment]
(closed because the same issue already exists)
