### ISSUE TITLE
[ExpandedRedstone v30d] Crash when turning off stacked camouflage block

### ISSUE THREAD

**Issue by rsaihe** [ReikaKalseki/Reika_Mods_Issues#2941]
I was testing out camouflage blocks in creative mode in my custom modpack and noticed that a crash repeatedly occurs whenever three or more camouflage blocks that are stacked on top of each other are turned off. My crash log can be found [here](https://www.toptal.com/developers/hastebin/ovezapovip.properties).

**Comment by ReikaKalseki** [comment]
The link points to an empty file.

**Comment by rsaihe** [comment]
Ah, it must have expired. Here's another crash log: https://www.toptal.com/developers/hastebin/eqawinukow.php

**Comment by ReikaKalseki** [comment]
This should be impossible - the crash points to having the block and metadata of a camo tile without actually having a camo tile there.

**Comment by ReikaKalseki** [comment]
Never mind, your stacktrace is just a bit incorrect. Fixed.
