### ISSUE TITLE
[ReactorCraft] Silver ore still generates when disabled

### ISSUE THREAD

**Issue by rsaihe** [ReikaKalseki/Reika_Mods_Issues#2942]
Silver ore appears to generate even when I have ReactorCraft's silver ore generation set to false in the config file. Note that I am currently running v30c due to #2937.

**Comment by ReikaKalseki** [comment]
Do you have another kind of silver ore generating? If not, that config is ignored, because silver is a required material.

**Comment by rsaihe** [comment]
I have Thermal Foundation silver ore generating.

**Comment by ReikaKalseki** [comment]
I found some straggler config code that might be involved. If not, the only other explanation is the TF silver not being in the ore dict (unlikely).
