### ISSUE TITLE
Update links on Curseforge pages?

### ISSUE THREAD

**Issue by rsaihe** [ReikaKalseki/Reika_Mods_Issues#2943]
Right now the Curseforge pages link back to the now defunct website: <https://sites.google.com/site/reikasminecraft/home>. They should be updated to point to <https://reikakalseki.github.io/>.

**Comment by Credit-Score** [comment]
I was unaware there was even a new site, I just thought the site was dead in general. Nice to know

**Comment by ReikaKalseki** [comment]
This is not the place for this.

**Comment by rsaihe** [comment]
My apologies.
