### ISSUE TITLE
[RoC] Compactor pressure, even when given minimum power and torque, will rise infinitely until the machine blows up.

### ISSUE THREAD

**Issue by Credit-Score** [ReikaKalseki/Reika_Mods_Issues#2944]
Title is all the description needed.
RoC version: RotaryCraft+1.7.10+V30c
DragonAPI version: DragonAPI+1.7.10+V30d

**Steps to Reproduce:**

1. Put down 4 Gasoline generators. combine their power with shaft units
2. Feed it through an 8:1 torque gearbox to your compactor
3. Sit and wait as your compactor never stops building pressure until it explodes.

I assume this is related to #2910 however even if it is the exact same issue, that ticket was closed over 2 months ago but there still isn't a fixed version released.

**Comment by ReikaKalseki** [comment]
This is where it stopped for me. ![https://i.imgur.com/cwxozr6.png](https://i.imgur.com/cwxozr6.png).

Moreover, that class has not changed since March 2020 and references nothing that has, nor does it use anything relevant to the issue you linked.
