### ISSUE TITLE
[ReC] HP Turbine redstone shutdown undocumented

### ISSUE THREAD

**Issue by Credit-Score** [ReikaKalseki/Reika_Mods_Issues#2945]
![image](https://user-images.githubusercontent.com/63371073/146257682-8f954a36-b398-43ed-9b42-dd1aa4d7c076.png)

That image shows my issue, I've tried going out of debug mode and breaking all the High-Pressure Turbine blocks, then replacing them all, but still nothing. After messing with my steam lines a bit and such I'm sitting at 500k m^3 steam but still nothing.

Other issues keep saying "oh putting 12k steam in the line fixed it", however literally nothing I have tried has fixed this. It has plenty of lube, as you can kind of see by the pump in the screenshot. And I've tried basically anything I could possibly think to try, not going to bother to list them all here but most just involve various situations of breaking/replacing stuff, emptying steam lines, etc. 

I'm losing my mind here, nothing is working, and I'm just happy I went into a creative world to try this out first.

**Comment by Credit-Score** [comment]
Oh my god, even though it's not stated ANYWHERE whatsoever that I've ever found (including the in-game book), HP Turbines will not run if they receive a redstone signal, aka the one given by my high-pressure pump ._.

@ReikaKalseki , please add this to the handbook, this wasted multiple hours of my life for no reason.

**Comment by ReikaKalseki** [comment]
I do not recall that even being a feature, but if it is it was probably added - likely by request - as an afterthought.

**Comment by ReikaKalseki** [comment]
Done.
