### ISSUE TITLE
[Chromaticraft v30d] Class Registration Issue with CartLivery and SGCraft, on dedicated server - computer APIs

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#2946]
As the title said - a RegistrationException is thrown when CartLivery and SGCraft are in the modpack, and you're running a dedicated server. That is, SSP loads up just fine - it's only when you load those mods up on a dedicated server that the problem happens.
Minimal mod list:
Railcraft_1.7.10-9.12.2.1.jar 
CartLivery-1.7.10-0.11.1.jar
DragonAPI+1.7.10+V30d.jar
ChromatiCraft+1.7.10+V30d.jar
SGCraft-1.13.3-mc1.7.10.jar

[crash-2021-12-16_20.12.37-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7732030/crash-2021-12-16_20.12.37-server.txt)
[fml-server-3.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7732036/fml-server-3.log)

**Comment by ghost** [comment]
Error also occurs with:
Chisel2-2.5.1.44.jar
ChromatiCraft+1.7.10+V30d.jar
DragonAPI+1.7.10+V30d.jar
Railcraft_1.7.10-9.12.2.1.jar
SGCraft-1.13.3-mc1.7.10.jar

And the forge .jar I've been using is: forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
[crash-2021-12-16_20.43.02-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7732122/crash-2021-12-16_20.43.02-server.txt)
[fml-server-latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7732126/fml-server-latest.log)

Also, I tested on an old version of my modpack, and it happens for Chromaticraft v29g, as well.
It seems like RailCraft and SGCraft, for whatever reason, are causing some type of weird interaction.

**Comment by ghost** [comment]
Can confirm this is still happening with v31 of the mods.

**Comment by ReikaKalseki** [comment]
SGCraft is including an old version of some mod's API.

**Comment by ghost** [comment]
Okay. Do you have any advice on where I could look to fix that? The mod dev hasn't updated the mod since 2017, so I doubt they'll update it. And since I really want to use the mod (or rather, add RailCraft), that means I have to patch it myself. And while I have some experience with modding, inter-mod compatibility is not something I've had to touch yet.
Would it just be a matter of finding the updated API files and dropping them in, and recompiling?
And on that note, why would adding Railcraft and Chisel 2/Cart Livery be a trigger for the issue? Is it because one of them is registering stuff according to a more recent API, which causes an issue when SGCraft registers stuff?

**Comment by ReikaKalseki** [comment]
You can try removing it from their jar yourself; that usually works for most mods. You can also try adding updated copies, yes, but this is a less desirable approach.

> And on that note, why would adding Railcraft and Chisel 2/Cart Livery be a trigger for the issue?

Classloading with intermod APIs is a nightmare that is impossible to properly trace more often than not. Additionally, I can say from experience that RailCraft tends to be involved in a lot of them.

**Comment by ghost** [comment]
Alright, thank you for explaining that. I thought I was going to have to download the source and recompile with updated APIs, but deleting them worked.
I deleted the three apis in the SGCraft jar - cofh, dan200 (ComputerCraft), and li.cl.oc, and it loads correctly now. Just mentioning this here, in case someone else has the same problem.
Seriously, thank you for helping resolve an issue with another mod. Not that it's really the other modder's fault, since they seem to have stepped away from modding, but it was still a problem..

**Comment by ReikaKalseki** [comment]
People shipping old copies of the ComputerCraft API is distressingly common.
