### ISSUE TITLE
[CritterPets] Crash opn loading (all was OK with previous version)

### ISSUE THREAD

**Issue by cyb3rm4n** [ReikaKalseki/Reika_Mods_Issues#2947]
Got strange crash with CritterPets v31a.

Here's full launch log:

[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7739266/latest.log)

Any tips to fix it?

**Comment by Luminisc** [comment]
Same issue here:

> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Reika/CritterPet/Entities/Mod/TameSpitter
> 	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
> 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
> 	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)

**Comment by ReikaKalseki** [comment]
Fixed.
