### ISSUE TITLE
Carpenter's Blocks loading after Rotarycraft appears to cause ClassNotFound exception

### ISSUE THREAD

**Issue by zmaster587** [ReikaKalseki/Reika_Mods_Issues#295]
Crash with Rotarycraft loading before carpenter's blocks:
http://pastebin.com/PaGbGrY5

However when the load order is different with the same mods and Carpenter's Blocks loads before RotaryCraft the game launches fine:
Examples of working load order:
http://pastebin.com/sm582HjT

To be clear, niether LibVulpes nor Advanced Rocketry reference Carpenter's blocks in any way shape or form and a used solely in this instance to control load order.

**Comment by ReikaKalseki** [comment]
Try Carpenter's 3.3.5.

**Comment by zmaster587** [comment]
Same issue seems to occur in carpenter's blocks 3.3.5
Crash with this load order:
http://pastebin.com/9QZN0bnS

No crash with this load order:
http://pastebin.com/gxKWb1q3

I also want note this does not happen when Rotarycraft is not installed and this issue occurs at least as far back as Rotarycraft version 7f.
Could this perhaps be involving the API stripping code?

**Comment by ReikaKalseki** [comment]
So it is more classloading stupidity....

**Comment by DarkGuardsman** [comment]
You could create a log of all the things your API stripping code touches. That way we could trace this problem a bit more for you. Just make it output to its own log file like your are already doing for logs.

**Comment by ReikaKalseki** [comment]
I already do.
