### ISSUE TITLE
reactorcraftcrash

### ISSUE THREAD

**Issue by TheMgfeedthebeast** [ReikaKalseki/Reika_Mods_Issues#2951]
my reactorcraft world crashes when i open it
[crash-2021-12-20_17.28.40-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7746654/crash-2021-12-20_17.28.40-client.txt)

**Comment by ReikaKalseki** [comment]
This looks like something is corrupt - you have the block ID of a duct (gas duct, waste duct, etc) but no TE from it. Can you open it in MCEdit?

**Comment by TheMgfeedthebeast** [comment]
how do i do that

**Comment by TheMgfeedthebeast** [comment]
by the way this has hapend multiple times when iv playd before making a fusion reactor the crash log looked the same

**Comment by TheMgfeedthebeast** [comment]
the block id for bedrock/or regular ducts in mcedit is 195 block data is 1

**Comment by ReikaKalseki** [comment]
Does the specific location have a TileEntity associated with it?

**Comment by TheMgfeedthebeast** [comment]
i will check

**Comment by TheMgfeedthebeast** [comment]
if i remove all the ducts will my problem be fixed?

**Comment by ReikaKalseki** [comment]
Yes.

**Comment by TheMgfeedthebeast** [comment]
then i will do that thanks reika!
