### ISSUE TITLE
[ChromatiCraft] Optimizatiion of WorldGen is too poor

### ISSUE THREAD

**Issue by cyb3rm4n** [ReikaKalseki/Reika_Mods_Issues#2952]
**Case:** generate game world in creative, just to test how fastly chunks are creating.
**Test Environment:**
- Hardware specs:
   - **CPU:** AMD Ryzen 5 3600
   - **RAM:** 16GB
   - **Disk:** 256GB SSD
   - **GPU:** NVIDIA GeForce 1660
- Minecraft related specs:
   - Forge 10.13.4.1614
   - Java memory: 4096 MB
   - World Generation: Default
   - Insrtalled mods:
      - DragonAPI V31b
      - ChromatiCraft V31b
**Expectation:**
> Chunks will load as normal, maybe little slower then in vanilla world genetator

**Reality:**
> Chunk loading sometimes freezes, so i can fly to the chunk border and watch underground

![2021-12-21_12 35 59](https://user-images.githubusercontent.com/1812907/146918887-2799afa6-f8be-486e-a5f8-30358dbcab19.png)
![2021-12-21_12 36 25](https://user-images.githubusercontent.com/1812907/146918890-3b3237a4-b27b-4bfb-ab21-24e37eed56c6.png)
![2021-12-21_12 36 39](https://user-images.githubusercontent.com/1812907/146918893-60a574cf-245f-4bf2-973a-30727cd542e5.png)
![2021-12-21_12 37 58](https://user-images.githubusercontent.com/1812907/146918898-2d27271a-1351-43e8-b623-9380eba42e45.png)

**Comment by ReikaKalseki** [comment]
Modded MC worldgen is slow at the best of times - getting to the edge of the loaded area is far from rare even in "basically vanilla" - and CC adds a very large amount to that. There is no way to eliminate the load from worldgen without just removing that worldgen.

**Comment by Cynosphere** [comment]
I last played with ChromatiCraft back on v22d. I went to remake that modpack with less and different mods on the latest version (v31b) and it is literally unplayable now as world gen takes almost 5-10 minutes.

Sampler stall reports point to
```
Reika.ChromatiCraft.World.GlowingCliffsColumnShaper.getBiome(GlowingCliffsColumnShaper.java:359)
Reika.ChromatiCraft.World.GlowingCliffsColumnShaper.getInvertedDistanceFactor(GlowingCliffsColumnShaper.java:312)
Reika.ChromatiCraft.World.GlowingCliffsColumnShaper.blendEdge(GlowingCliffsColumnShaper.java:187)
Reika.ChromatiCraft.World.BiomeGlowingCliffs.blendTerrainEdgesAndGenCliffs(BiomeGlowingCliffs.java:221)
Reika.ChromatiCraft.ChromaticEventManager.blendCliffEdgesAndShapeCliffs(ChromaticEventManager.java:900)
cpw.mods.fml.common.eventhandler.ASMEventHandler_189_ChromaticEventManager_blendCliffEdgesAndShapeCliffs_ReplaceBiomeBlocks.invoke(.dynamic)
```

**Comment by ReikaKalseki** [comment]
It should not take anywhere near *that* long. Also, the luminous cliffs tends to generate the entire biome at once, which results in a large lag spike when it generates but then no more lag afterwards. Overall, the per-chunk time is similar.
