### ISSUE TITLE
Satisforestry has a registration error

### ISSUE THREAD

**Issue by litten8** [ReikaKalseki/Reika_Mods_Issues#2954]
While I initially encountered this crash using more mods, I tried disabling all mods except DragonAPI and Satisforestry, and got this crash log
[crash-2021-12-21_22.57.54-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7760651/crash-2021-12-21_22.57.54-client.txt)

**Comment by ReikaKalseki** [comment]
Read it.

**Comment by litten8** [comment]
sorry, I just saw the contact reika immediately thing and didn't scroll down since I figured that the rest was just technical stuff

**Comment by ReikaKalseki** [comment]
That is a fair point - I need to change that message.

**Comment by ReikaKalseki** [comment]
Done.
