### ISSUE TITLE
[ReC v31b] Can't form plasma injector multiblock

### ISSUE THREAD

**Issue by Credit-Score** [ReikaKalseki/Reika_Mods_Issues#2956]
Title says it all. If you try to form the plasma injector multiblock it simply won't happen.       
Previously formed multiblocks stayed intact, but the second they unform you are unable to rebuild it :(

I do not know if this effects any other multiblocks.

Images below just to prove I built it right

First layer
![image](https://user-images.githubusercontent.com/63371073/147164666-9c023c8e-109d-4d4a-9a6d-12a620d8b0d0.png)

Second layer, corners are column pieces and sides are side panels.
![image](https://user-images.githubusercontent.com/63371073/147169077-dd1fe3d8-e3fd-4c0b-a377-5281cfe8ad4f.png)

Third layer
![image](https://user-images.githubusercontent.com/63371073/147169170-fba48431-a0a4-4575-b438-0690f44313ec.png)

Fourth Layer
![image](https://user-images.githubusercontent.com/63371073/147169231-265f6d98-1898-459e-85e8-f56169bcab41.png)

Fifth and final layer
![image](https://user-images.githubusercontent.com/63371073/147169329-5b5ed3ed-b6fa-405c-856b-f2bb63477aea.png)

Now a few images of it fully built from different angles
![image](https://user-images.githubusercontent.com/63371073/147169479-02d38a07-6d52-4d6b-8b30-f6771264ec69.png)
![image](https://user-images.githubusercontent.com/63371073/147169418-41f8f06a-c709-4eef-b954-108b070730ca.png)
![image](https://user-images.githubusercontent.com/63371073/147169496-009dca38-2ad0-45ee-967e-2c5ff17c6d4f.png)
![image](https://user-images.githubusercontent.com/63371073/147169512-6c684f31-23c4-4f6c-8cc6-99d13dc70a2b.png)

**Comment by MalTeeez** [comment]
Did you try replacing the Hysteresis Cores at the front middle?

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by TheMgfeedthebeast** [comment]
how do i fix it?

**Comment by Kjller12** [comment]
I'm having the same issue and cant fix it. My question is what do you mean by front middle

**Comment by MalTeeez** [comment]
Usually any of the Hysteresis Cores has to be placed last, but in this case it seemed to be a genuine bug, you will probably have to wait until the next update fixes it

**Comment by Appa1990** [comment]
BUMP FOR GOOGLE!
Here is the current live version!
Dont use it from Curse!!! Otherwise you get very frustrated after hours of survival ftb infinity evolved or what ever modpack you use or dont use.
https://dragonrealm.overminddl1.com/mods.php

@ReikaKalseki if you give me permission i reupload it there. there are still players for your mod ;p
