### ISSUE TITLE
[ReactorCraft] Crash When Raising Individual or All Control Rods

### ISSUE THREAD

**Issue by MajorGeneralRelativity** [ReikaKalseki/Reika_Mods_Issues#2957]
I'm running ReactorCraft 1.7.10 v31a, and I get the following crash whenever I attempt to raise a control rod in the reactor CPU. It also happens when I click the retract all button. However, inserting rods does not appear to cause a crash.
https://gist.github.com/MajorGeneralRelativity/1630534a32564c604ae82ee34fc9c20e

**Comment by ReikaKalseki** [comment]
Fixed.
