### ISSUE TITLE
DragonAPI signature

### ISSUE THREAD

**Issue by bookerthegeek** [ReikaKalseki/Reika_Mods_Issues#296]
```
[Client thread/ERROR] [DragonAPI]: The mod DragonAPI is expecting signature 32:F5:F4:E8:44:C0:EA:C8:6F:46:8A:8E:F3:05:05:7B:6F:90:0F:78 for source DragonAPI 1.7.10 V9a.jar, however there is no signature matching that description
```

Using the latest API from the website. Mod list is [HERE](https://github.com/MyM-ModpackTeam/B2B/blob/master/Credits.rs)

Does not cause a crash or any negative effects that I can see.

**Comment by ReikaKalseki** [comment]
I know about this. As far as I can tell, the Forge signature system is either malfunctioning or does not work in a way that is actually useful.
