### ISSUE TITLE
DragonAPI.Libraries.World.ReikaWorldHelper.isFakeWorld Taking Significant Tick Time

### ISSUE THREAD

**Issue by CaiB** [ReikaKalseki/Reika_Mods_Issues#2960]
Hi there,

I noticed our server is running significantly slower than it should be. I ran a profiler, and noticed that every single `BlockTickEvent` when instantiated, goes up to a `PositionEventBase` which in the constructor checks `isFake()`. This call to `ReikaWorldHelper.isFakeWorld()` takes significant amounts of time, using reflection and string comparison. It seems this happens for every single event in every single tick (?!?!)

This is by a decent margin the single most expensive method call in the server tick loop. Please consider only checking if a world is fake once, or at worst, once per tick, and storing that for subsequent events.

**Comment by CaiB** [comment]
It looks like almost half (!) of the server's tick time is spent checking the world for fakeness. Some more places where this takes noticeable amounts of time (each of these eventually turn into `ReikaWorldHelper.isFakeWorld()`)
- `BlockGrass.updateTick()` becoming your `BlockSpreadEvent`
- `Chunk.getPrecipitationHeight()` becoming your `BlockStopsPrecipitationEvent`
- `World.canBlockFreeze()` becoming your `IceFreezeEvent`
- `SpawnerAnimals.findChunksForSpawning()` becoming your `GetYToSpawnMobEvent`

I think you get the point. Turning each of those into a reflection call is insanity.

Finally, another decent chunk of time is spent managing the `NumberFormatException` occuring in `Block.getBlockFromName()` being called by `RotaryCraft.Auxiliary.RotaryAux.isMufflingBlock()` when you pass in `"Rockwool"` and it tries to parse that as an int. Once again, why is this being checked every tick? Whether or not a certain block muffles sound doesn't change between ticks.

These are super obvious optimizations that are readily apparent by spending just a few minutes with a profiler.

**Comment by Aivech** [comment]
I remember the fake world check being a fix for an issue with another mod creating fake World instances (for rendering purposes, I think?) and breaking certain assumptions in one of Reika's mods.

**Comment by ReikaKalseki** [comment]
Fixed.
