### ISSUE TITLE
i updated to the latest version and i get this error on my server

### ISSUE THREAD

**Issue by electrolys** [ReikaKalseki/Reika_Mods_Issues#2963]
crash report: https://pastebin.com/XFqr8FRG
loading log: https://pastebin.com/BL5XqyYv
i was on version 30b i think and i updated now i get this error i saw one of the issues saying to delete some mods mainly tc addons and i removed all my tc addons and that didn't work

**Comment by chotke** [comment]
It's not TC (Thaumcraft). Neither TiC (Tinkers mods).
The problem is in CoFH core. Reika broke compatibility with the new update.
#2948

**Comment by electrolys** [comment]
hmm i really don't want to remove cofh mods nor do i want to remove rotary craft guess i have to go back to an old version

**Comment by electrolys** [comment]
oh i can't go to an old version

**Comment by chotke** [comment]
@electrolys https://drive.google.com/drive/folders/1vNyq61scRZVcONP1uq_eIlaT3QykICqn?usp=sharing

**Comment by electrolys** [comment]
well now that i thought about it i want a lot more reika mods than just rotary craft so ive decided to remove cofh and just get tubes mod to replace the only thing we really cared about in it thanks for sharing this though

**Comment by ReikaKalseki** [comment]
Nothing said here is true.

**Comment by electrolys** [comment]
well i removed cofh mods and it fixed the error
could it be something with more than one mod making a mess after they all are in the pack like having tinkers cofh and dragon api?
