### ISSUE TITLE
[Suggestion] Make the config option "Temporally Dependent Amusement Behaviors" in Dragonapi.cfg also take effect on christmas content

### ISSUE THREAD

**Issue by JohnsonJohnsonson** [ReikaKalseki/Reika_Mods_Issues#2964]
I've spent the past 2 weeks playing with random, light-distorting snow blowing around my player and crystal pylons being giant christmas stars. At first it was fun, yeah, but the snow especially becomes so intrusive over time.

Also, christmas ended a week ago, when will it stop?

**Comment by Aivech** [comment]
There is already a config option:
`    B:"[E4353273F] Enable Temporally Dependent Amusement Behavior"=true` in DragonAPI.cfg

**Comment by JohnsonJohnsonson** [comment]
oof, I tried "holiday", "seasonal" or "christmas" with ctrl+f

**Comment by jajifo2213** [comment]
The code suggests that the config option only affects April Fools' day:
https://github.com/ReikaKalseki/DragonAPI/blob/618fd81039df125af73ce922eab3f49bf507dd2f/DragonOptions.java#L46
https://github.com/ReikaKalseki/DragonAPI/blob/2885133cf21ea6bd76f686edeade11e2329e2e8f/Auxiliary/Trackers/SpecialDayTracker.java#L32-L40

**Comment by JohnsonJohnsonson** [comment]
Yup I just noticed that as well. Snow is still present as of January 5th. From what jajifo linked, it seems like it'll stop at Jan 6.

Adjusted the suggestion accordingly

**Comment by ReikaKalseki** [comment]
No, this will not be configurable.
