### ISSUE TITLE
Constantly skipping ticks

### ISSUE THREAD

**Issue by KydZombie** [ReikaKalseki/Reika_Mods_Issues#2967]
Regularly, with intervals ranging from 3 to 20 seconds, both LAN and dedicated servers run incredibly behind on tick speed. The worst it has been is about 19500ms, with the lowest being ~1800ms. Reika mods installed are: DragonAPI, ElectriCraft, and RotaryCraft. Some other mods that might relate to it are TiC, Iguana's Tinker Tweaks, Thaumcraft, and FoamFix.

**Comment by KydZombie** [comment]
Tested it without FoamFix, no different.

**Comment by KydZombie** [comment]
With testing in singleplayer, it does not give the big "behind _ ticks" message, but it does give multiple things saying chunk ticking took too long, ranging from 100ms to 220ms.

**Comment by CaiB** [comment]
I'm curious if it's the same issue I had. Try adding the Java launch argument `-XX:+DisableExplicitGC`, and see if that makes any difference.

**Comment by ReikaKalseki** [comment]
If you have not built anything, this should be impossible, and at any rate neither I nor basically anyone else has this issue.
