### ISSUE TITLE
Server crash while flying through an rftools void age, seems to be related to Satisforestry

### ISSUE THREAD

**Issue by JohnsonJohnsonson** [ReikaKalseki/Reika_Mods_Issues#2968]
https://pastebin.com/9zh6Qz2w

Here's the crash log.

I made a void age for some miscellaneous stuff and noticed that on my minimap, there was a slime island from Tinker's Construct, so I flew towards it. At about 140 blocks off, the game crashed with that crash log.

What I think _may_ have happened was that the island spawned over a pink forest and the biome generator tried to decorate terrain that wasn't there? I'll try to make a second void age with just a single biome.

**Comment by ReikaKalseki** [comment]
I fixed this some time ago.
