### ISSUE TITLE
DragonAPI V31b crashes with Climate control during init

### ISSUE THREAD

**Issue by VenomiXeD** [ReikaKalseki/Reika_Mods_Issues#2973]
During server startup and client startup, both clients terminate because of a crash relating to ClimateControl mod.

This did not happen with previous versions of DragonAPI and both client and server could initialize without any issues.

[crash-2022-01-22_00.15.52-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7917111/crash-2022-01-22_00.15.52-server.txt)

**Comment by ReikaKalseki** [comment]
I remember fixing this.
