### ISSUE TITLE
Mohist and DragonApi

### ISSUE THREAD

**Issue by Fehrstix** [ReikaKalseki/Reika_Mods_Issues#2975]
Greetings. I'm sorry if my question will sound stupidly, but I have a problem with launching my Mohist 1.7.10 server with DragonApi installed. The logs are here: https://mclo.gs/vNrDhvu
I will be grateful for your help and answer.

**Comment by ghost** [comment]
Please close this Issue now: DragonAPI will **NEVER NNNNEVER NNNNNNNEVER EVER SUPPORT** the Cauldron Servers (Cauldron, KCauldron, Thermos, Uranium, Mohist, Crucible, or any others).

**Comment by Fehrstix** [comment]
On purpose?
Doesn't it work for any version?

**Comment by ghost** [comment]
It was intentional by Cauldron and has nothing to do with DragonAPI.
Yes, without any version support.

**Comment by Fehrstix** [comment]
Oh, thanks(
