### ISSUE TITLE
DragonAPI v9a: Issue with Extra Utilities when TConstruct is also installed

### ISSUE THREAD

**Issue by dirtyfargo** [ReikaKalseki/Reika_Mods_Issues#298]
When I craft unstable ingots from Extra Utilities, with these mods enabled, they are unusable. By unusable I mean the ingots cannot be used to craft any of the recipes that they are supposed to. Also, while unstable ingots usually start animating and flashing red after crafting them, they are not. They do however still kill you when you leave the crafting table as per usual, but the ingots do not disappear and will keep killing you every time you pick them up.
Mods used for testing this issue:
DragonAPI v9a
Extra Utilities 1.2.11
TConstruct 1.8.7
Mantle 0.3.2a
CoFHCore 3.0.3-303

Also, I was going to revert to the previous DragonAPI to test whether it's just the most recent version that causes this, but I don't have v8 anymore. Cannot reproduce this issue without TConstruct + DragonAPI present. Thank you for your time =)

**Comment by ReikaKalseki** [comment]
Someone else reported the same yesterday (and that shift-clicking in the recipe affects the output). I have nothing that could possibly affect this.

**Comment by dirtyfargo** [comment]
Ah alright sorry I didn't see that. Should I report this on the Extra Utilities or Tinkers Construct issue tracker perhaps?

**Comment by ReikaKalseki** [comment]
You can try asking either, but good luck getting RWTema.

**Comment by dirtyfargo** [comment]
Alright, I'll try both, see what happens. Thanks again. :)
