### ISSUE TITLE
[Chromaticraft v31b] Console spamming

### ISSUE THREAD

**Issue by Star4Fun** [ReikaKalseki/Reika_Mods_Issues#2981]
I tried to transform berries to shard, and it works the first time without problems, but after that the flame does consume the item but does not gain any energy from it.

Also I notice a console spam from Chromaticraft:
`CHROMATICRAFT ERROR: Looking for progression data on player [Minecraft], with no NBT?!`
The log does not provide any detailed information about that.

**Comment by Star4Fun** [comment]
I don't know why but now the transmutation flame is working, but the log spamming keeps happening.

**Comment by ReikaKalseki** [comment]
How did the flame get placed? Was it placed by worldedit or something?

**Comment by Star4Fun** [comment]
No I placed it normal after crafting it.

**Comment by ReikaKalseki** [comment]
Then why does its player seem to be "[Minecraft]"? Break and replace it and see if the issue continues.
