### ISSUE TITLE
[DragonRealmCore] Iridescent Crystal Chunk not able to be crafted using Lensing Crystals

### ISSUE THREAD

**Issue by fndragon** [ReikaKalseki/Reika_Mods_Issues#2982]
Screenshot attached

I cannot craft the Iridescent Crystal Chunk using the Lensing Crystals.  As you can see the altar seems to know about the recipe and shows the image in the top-right but when I attempt to craft it, an error beep occurs.

Finding the Lensing Crystals was hilarious btw.  I honestly enjoyed it.  Generating them when you do is a neat trick.  :D

I have a Tier 4 Crafting Altar with all 16 color pylons connected to it.  All of the repeaters gave # of hops away successfully when pinged.  The altar recipe doesn't list any runes required, but even if it did, the final product wouldn't be visible until all runes were added to its liking.

I really hope this is a one-off issue because these are on the main progression pathway (Power Crystals).  I don't have any idea what could be causing the issue other than some issue with the change to the recipe.
![2022-02-01_13 43 50](https://user-images.githubusercontent.com/3648933/152033938-7beedd65-126b-4129-a879-ceedd20972b5.jpg)

**Comment by fndragon** [comment]
Dropping this issue.  I don't know why but I looked at the recipe today and the outer ring of lensing crystals were replaced by Binding Crystals.  Now it is able to craft.  Unsure what the issue was.

**Comment by ReikaKalseki** [comment]
This is a known issue that occasionally happens, and has as yet eluded identification as to a cause, much less a fix.

**Comment by DFliyerz** [comment]
Could you maybe give a hint on how to find the lensing crystals? I've been searching everywhere and even looked through the code to get an idea of where they show up but still haven't found any.

**Comment by EyeDeck** [comment]
You have to use a little-known RotaryCraft machine.
<details><summary>Spoiler</summary>
The Ground Penetrating Radar.
You'll know them when you see them.
</details>

Also the correct Iridescent Chunk recipe does indeed have only the one lensing crystal in the middle, the outer four are supposed to be Binding Crystals. Even if it doesn't look like it'll work, set the recipe up and try triggering crafting anyway, it should work.

**Comment by ReikaKalseki** [comment]
The issue is also fixed.
