### ISSUE TITLE
CondensedOres Feature Suggestions: Easier weighting, sparse veins, and more biome controls

### ISSUE THREAD

**Issue by SisterJacq** [ReikaKalseki/Reika_Mods_Issues#2983]
Since I'm setting up a non-skyblock pack to finally play with ChromatiCraft, I was comparing the features of CoFH Core's .jsons and CondensedOres, because I want big, biome specific ore veins. While Condensed Ores has proximity spawning (which I can think of fun things to do with), and more importantly the ability to replace ReactorCraft oregen (biome specific fluorite colors, anyone?), CoFH Core has a couple things CondensedOres could benefit from having analogs to in my opinion.

First is better weighting of mixed block veins. CoFH has a simple (optional) weight value, while CondensedOres... doesn't. To get the same effect, you to spam stuff in `blocks = {...}`. For example to reproduce the default AE2 Certus Quartz to Charged Certus Quartz ore values, it just takes:
```
"block": [
    {"name": "appliedenergistics2:tile.OreQuartz", "metadata": 0, "weight":92},
    {"name": "appliedenergistics2:tile.OreQuartzCharged", "metadata": 0, "weight":8}
],
```
Meanwhile, to do the same thing, CondensedOres currently needs:
```
blocks = {
    "appliedenergistics2:tile.OreQuartz:0" //1
    "appliedenergistics2:tile.OreQuartz:0" //2
    "appliedenergistics2:tile.OreQuartz:0" //3
    "appliedenergistics2:tile.OreQuartz:0" //4
    "appliedenergistics2:tile.OreQuartz:0" //5
    "appliedenergistics2:tile.OreQuartz:0" //6
    "appliedenergistics2:tile.OreQuartz:0" //7
    "appliedenergistics2:tile.OreQuartz:0" //8
    "appliedenergistics2:tile.OreQuartz:0" //9
    "appliedenergistics2:tile.OreQuartz:0" //10
    "appliedenergistics2:tile.OreQuartz:0" //11
    "appliedenergistics2:tile.OreQuartz:0" //12
    "appliedenergistics2:tile.OreQuartz:0" //13
    "appliedenergistics2:tile.OreQuartz:0" //14
    "appliedenergistics2:tile.OreQuartz:0" //15
    "appliedenergistics2:tile.OreQuartz:0" //16
    "appliedenergistics2:tile.OreQuartz:0" //17
    "appliedenergistics2:tile.OreQuartz:0" //18
    "appliedenergistics2:tile.OreQuartz:0" //19
    "appliedenergistics2:tile.OreQuartz:0" //20
    "appliedenergistics2:tile.OreQuartz:0" //21
    "appliedenergistics2:tile.OreQuartz:0" //22
    "appliedenergistics2:tile.OreQuartz:0" //23
    "appliedenergistics2:tile.OreQuartzCharged:0"
    "appliedenergistics2:tile.OreQuartzCharged:0"
}
```
Doable, obviously. Easy, sorta, but not as easy as it could be.

Second is an analog of CoFH Core's sparse veins, since combining that with your proximity spawning sounds cool. Alternatively, maybe some sort of fuzzy vein mode where the vein sort of mixes around the edges? Or at least a way to not replace blocks as a thing in weighting? (Thinking I could just use veins of 85% ore and 15% unreplaced blocks as a simple solution if you just implemented the not-replacing bit)

Third is adding more biome-based controls, two of which you could add. The first of the two would be easy, adding temperature as a type to do things with. The second part is biome based weightings (probably between 0~1), as opposed to having multiple entries for the same generation for different biomes (the hard part would probably be the config stuff, since it would probably just be a second generation chance in generation, though I'm unsure how you would want to prioritize for multiple rarities).

These are all just suggestions, so feel free to be all "These ideas don't deserve a place in my mod, but they might make a good coaster for my drink!"

**Comment by ReikaKalseki** [comment]
The chief barrier to any of these would be implementation difficulty, either in the parsing to the internal data structures or use of said data at generation time.

However, I have no idea what "sparse veins" are.

**Comment by SisterJacq** [comment]
I'm referring to the "sparse" option in CoFH worldgen configs for the "large-vein" generator, which in the CoFH documentation says "If true, veins will be smaller and more spread out, and will look somewhat like neurons. The clusterSize value in entries then determines roughly how many blocks a single vein contains." I'm not sure how you would implement this, which is why this and the third suggestion are less important in my opinion.

I gave some thought to the first one, and if it used `* #` after the block (if this is already a thing, I didn't know, since I'm having trouble getting my configs to actually generate in the world to begin with), like some of your other configs (which often deals with stack size, but could probably easily translate to weight, since it takes the blocks from a weighted random to generate). Thus the Certus Quartz example would become:
```
blocks = {
    "appliedenergistics2:tile.OreQuartz:0" * 23
    "appliedenergistics2:tile.OreQuartzCharged:0" * 2
}
```

If you need any other information, let me know.

**Comment by ReikaKalseki** [comment]
It looks like the item-based weights already exist, and has for some time, being specified with an (admittedly undocumented) `blockSet` parameter, as an alternative to `blocks`.

..."For some time" being since Oct 2019. https://github.com/ReikaKalseki/CondensedOres/commit/a44c046d5b6ea428f22d33f9db5675f72c337985#diff-e22ff8c3940230092d069cee9373c3d2cc54c225629f5e390549f992757688c5R205

**Comment by ReikaKalseki** [comment]
This has finally been implemented. I actually added three new ore gen presets, two of which resemble what you asked for. The first is "tendril", designed to emulate a fissure, and the second is "star", more like the neurons you describe. The latter also supports "have a few blocks of something special in the center" as an optional feature.

###Tendril
![https://i.imgur.com/0HHNIhQ.jpg](https://i.imgur.com/0HHNIhQ.jpg)
![https://i.imgur.com/tdLJHLE.jpg](https://i.imgur.com/tdLJHLE.jpg)
![https://i.imgur.com/m3QhkQ3.jpg](https://i.imgur.com/m3QhkQ3.jpg)


###Star
![https://i.imgur.com/N3iZd86.jpg](https://i.imgur.com/N3iZd86.jpg)
![https://i.imgur.com/EPYTFVA.jpg](https://i.imgur.com/EPYTFVA.jpg)
![https://i.imgur.com/SA6M85J.jpg](https://i.imgur.com/SA6M85J.jpg)
![https://i.imgur.com/hgiVNXW.jpg](https://i.imgur.com/hgiVNXW.jpg)
![https://i.imgur.com/0sREpqq.jpg](https://i.imgur.com/0sREpqq.jpg)
