### ISSUE TITLE
[old problem]Compatible work

### ISSUE THREAD

**Issue by layue13** [ReikaKalseki/Reika_Mods_Issues#2984]
Hello author, I'm sorry to ask you this question, because there have been many similar issues before.  Because I want to run your DragonAPI on Cauldron, I wrote the corresponding patch, the result is: I solved the problem of ASM NullPointer, I mean the problem caused by the patch of ChunkProviderServer.  But there is still a crash problem after the startup is successful, I will add a log to you in Chinese.  I hope to get your help, thank you 🙏

From Google Translate, the expression may not be very accurate.

**Comment by layue13** [comment]
I clear the method，And recreated a patch for hook event。
https://github.com/ReikaKalseki/DragonAPI/blob/master/ASM/Patchers/Hooks/Event/World/Gen/ChunkGenerationEvent.java#L31

**Comment by layue13** [comment]
I'll add the log file to you when I wake up

**Comment by layue13** [comment]
https://paste.ubuntu.com/p/GzgF6pzfkF

**Comment by layue13** [comment]
`package patches;

import me.layue13.rainbowpatcher.patch.Patch;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.*;
import squeek.asmhelper.me.layue13.rainbowpatcher.ASMHelper;

import java.util.ListIterator;

public class ChunkProviderServerPatch extends Patch {
    public ChunkProviderServerPatch() {
        super("net.minecraft.world.gen.ChunkProviderServer");
    }

    @Override
    public byte[] apply(byte[] bytes) {
        ClassNode classNode = ASMHelper.readClassFromBytes(bytes);
        for (MethodNode methodNode : classNode.methods) {
            if (methodNode.name.equals("originalLoadChunk")
                    && methodNode.desc.equals("(II)Lnet/minecraft/world/chunk/Chunk;")) {
                ListIterator<AbstractInsnNode> iterator = methodNode.instructions.iterator();
                while (iterator.hasNext()) {
                    AbstractInsnNode node = iterator.next();
                    if (node instanceof MethodInsnNode) {
                        if (((MethodInsnNode) node).name.equals("fetchDormantChunk")) {
                            InsnList insnList = new InsnList();
                            insnList.add(new VarInsnNode(Opcodes.ALOAD, 5));
                            insnList.add(new MethodInsnNode(Opcodes.INVOKESTATIC, "Reika/DragonAPI/Instantiable/Event/ChunkGenerationEvent", "fire", "(Lnet/minecraft/world/chunk/Chunk;)V", false));
                            methodNode.instructions.insert(node, insnList);
                            return ASMHelper.writeClassToBytes(classNode);
                        }
                    }
                }
            }
        }
        return bytes;
    }
} `

**Comment by ghost** [comment]
**FUCK ASM CLASSLOADING.** :) :) :)

If you want to using the Cauldron like Server side, you just need add some Jvm's Args:
`-DragonAPI_disable_ASM_CHUNKGENERATIONEVENT -DragonAPI_disable_ASM_STOPCHUNKLOADWORLD`

But, this only support Thermos Build 57, And it is easy to cause extremely serious and devastating problems. This is not recommended.

**Comment by layue13** [comment]
> But, this only support Thermos Build 57, And it is easy to cause extremely serious and devastating problems. This is not recommended.

So I want to find a good solution😀

**Comment by layue13** [comment]
> **FUCK ASM CLASSLOADING.** :) :) :)
> 
> If you want to using the Cauldron like Server side, you just need add some Jvm's Args: `-DragonAPI_disable_ASM_CHUNKGENERATIONEVENT -DragonAPI_disable_ASM_STOPCHUNKLOADWORLD`
> 
> But, this only support Thermos Build 57, And it is easy to cause extremely serious and devastating problems. This is not recommended.

I have solved the problem with CHUNKGENERATIONEVENT, thanks for the tip!
I hooked it in again!
