### ISSUE TITLE
[Suggestion][CC] Item Rift Upgrade

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2985]
I have had at multiple points in tech and sometimes magic endgame had the problem of thousands of items coming into a container per second but no way of transporting all these out fast enough, so I thought that the item rift would be a cool solution to that problem. 
In a possible upgrade for the item rift it would only transport every second or so, but each time it would transport batches of a few thousand items each, and not one single or tens of items as it does now. Maybe just a Turbocharged version of the rift would fit this.

**Comment by MalTeeez** [comment]
Empowering them with asveste has proven to be a little slow and very costly so maybe a more efficient clustered solution for this might be good

**Comment by ReikaKalseki** [comment]
It is hard to believe you have inflow greater than a stack per tick.

**Comment by MalTeeez** [comment]
Having Multiple Enderquarrys with Tick Accelerators along with extractors and other ways has at least proven to flood traditional ways of item transport, including the item rift

**Comment by ReikaKalseki** [comment]
This is so niche and requires too much to change to adapt to.
