### ISSUE TITLE
[Rotarycraft] Easy Difficulty Allows you to dupe diamonds from diamond shafts

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2986]
![DiaToShaft](https://user-images.githubusercontent.com/10777735/152661057-9329d293-d1d1-48a2-9cbf-5a939a6ad49e.png)

![ShafttoDia](https://user-images.githubusercontent.com/10777735/152661060-6ab94633-c5c1-40db-a696-782fdf42f2ad.png)

(double checked my mine tweaker scripts, and I have nothing that changes roc stuff in it, since I only added 3 recipes, which are just some crafting recipe's for soul sand/netherrack lel)

**Comment by Holorizor** [comment]
I tested it also, and it works not on the easy difficulty of Minecraft, but if you change the rotarycraft difficulty in the config (Difficulty Control) to 1 (by default  2) you get as shown above 6 diamonds rods.

**Comment by ReikaKalseki** [comment]
Fixed.
