### ISSUE TITLE
[Chromaticraft] Advancements infinitely repeating

### ISSUE THREAD

**Issue by Ranavolio** [ReikaKalseki/Reika_Mods_Issues#2987]
In a custom modpack based on the new Thaumaturges Ascension that includes the newest versions of DragonAPI and Chromaticraft I have the problem that the "magical forest" advancement is infnitely repeating while being in it. I had a similar issue a few weeks ago where the self-augmentation advancements was repeating while having an effect (though I have no log of that). How can I fix this? Its pretty annoying because the advancements are also somewhat laggy.

Log: https://paste.ee/p/ypeKU
Was in the forest for the around last 3-4 minutes

Modlist in the log

**Comment by ReikaKalseki** [comment]
That suggests your progression is failing to save, which in turn might be caused by NBT issues. Either way, every time this has happened in the past it has been due to other mods, often simply massively overloading the player NBT.
