### ISSUE TITLE
Crash in New Rainbow Forest Structure

### ISSUE THREAD

**Issue by Zebralear** [ReikaKalseki/Reika_Mods_Issues#2988]
I was looking at the new structure, using creative to try and figure it out and such. The game crashed once and since then, it has been giving a NullPointer error on login that causes the client to crash (server is unaffected).

https://pastebin.com/cAQzTeNn

**Comment by Zebralear** [comment]
(crash report in comment form)
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2/6/22 9:07 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at Reika.ChromatiCraft.Block.Dimension.Structure.Locks.BlockColoredLock.func_149734_b(BlockColoredLock.java:88)
	at net.minecraft.client.multiplayer.WorldClient.func_73029_E(WorldClient.java:308)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2048)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Reika.ChromatiCraft.Block.Dimension.Structure.Locks.BlockColoredLock.func_149734_b(BlockColoredLock.java:88)
	at net.minecraft.client.multiplayer.WorldClient.func_73029_E(WorldClient.java:308)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Zebralear'/17296665, l='MpServer', x=3954.51, y=69.62, z=-107.23]]
	Chunk stats: MultiplayerChunkCache: 391, 391
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-100,64,220), Chunk: (at 12,4,12 in -7,13; contains blocks -112,0,208 to -97,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3270513 game time, 3270513 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 235 total; [EntityClientPlayerMP['Zebralear'/17296665, l='MpServer', x=3954.51, y=69.62, z=-107.23], EntityItem['item.item.chickenRaw'/17296671, l='MpServer', x=3961.13, y=62.13, z=-111.44], EntitySkeleton['Skeleton'/17296670, l='MpServer', x=3954.70, y=39.00, z=-105.37], EntityBat['Bat'/17296669, l='MpServer', x=3955.44, y=41.10, z=-105.25], EntityZombie['Zombie'/17296668, l='MpServer', x=3954.46, y=39.00, z=-106.17], EntityZombie['Zombie'/17296667, l='MpServer', x=3963.50, y=38.00, z=-108.03], EntityBat['Bat'/17296666, l='MpServer', x=3952.75, y=41.10, z=-96.69], EntitySheep['Sheep'/17296679, l='MpServer', x=3932.41, y=64.00, z=-83.19], EntityBat['Bat'/17296678, l='MpServer', x=3951.25, y=39.10, z=-87.34], EntityCow['Cow'/17296677, l='MpServer', x=3982.47, y=64.00, z=-101.47], EntitySlime['Slime'/17296676, l='MpServer', x=3937.31, y=40.00, z=-104.72], EntityCow['Cow'/17296675, l='MpServer', x=3959.94, y=66.00, z=-99.53], EntityCow['Cow'/17296674, l='MpServer', x=3958.50, y=63.00, z=-109.41], EntitySheep['Sheep'/17296673, l='MpServer', x=3965.75, y=63.00, z=-103.13], EntitySheep['Sheep'/17296672, l='MpServer', x=3956.22, y=63.00, z=-105.59], EntityZombie['Zombie'/17296687, l='MpServer', x=3961.84, y=63.00, z=-69.75], EntityCow['Cow'/17296686, l='MpServer', x=3994.06, y=64.00, z=-103.58], EntitySlime['Slime'/17296685, l='MpServer', x=3985.31, y=30.00, z=-103.38], EntityCow['Cow'/17296684, l='MpServer', x=3963.78, y=71.00, z=-130.75], EntitySheep['Sheep'/17296683, l='MpServer', x=3983.03, y=64.00, z=-80.97], EntitySlime['Slime'/17296682, l='MpServer', x=3979.31, y=37.00, z=-121.69], EntitySlime['Slime'/17296681, l='MpServer', x=3981.31, y=36.00, z=-118.28], EntityWolf['Wolf'/17296680, l='MpServer', x=3937.78, y=60.00, z=-125.41], EntityItem['item.tile.cloth.white'/17296695, l='MpServer', x=3947.13, y=55.13, z=-136.47], EntityWolf['Wolf'/17296694, l='MpServer', x=3945.22, y=58.00, z=-141.50], EntityWolf['Wolf'/17296693, l='MpServer', x=3935.50, y=67.00, z=-119.22], EntitySheep['Sheep'/17296692, l='MpServer', x=3925.43, y=63.00, z=-127.84], EntitySheep['Sheep'/17296691, l='MpServer', x=3935.16, y=63.00, z=-123.88], EntitySheep['Sheep'/17296690, l='MpServer', x=3922.16, y=65.00, z=-81.06], EntitySheep['Sheep'/17296689, l='MpServer', x=3934.00, y=63.00, z=-69.85], EntityBat['Bat'/17296688, l='MpServer', x=3950.32, y=21.11, z=-64.62], EntityCow['Cow'/17296703, l='MpServer', x=3974.80, y=74.00, z=-138.44], EntityWolf['Wolf'/17296702, l='MpServer', x=3971.31, y=70.00, z=-136.31], EntityWolf['Wolf'/17296701, l='MpServer', x=3972.50, y=71.00, z=-136.50], EntityCow['Cow'/17296700, l='MpServer', x=3938.03, y=64.00, z=-140.06], EntitySheep['Sheep'/17296699, l='MpServer', x=3945.13, y=64.00, z=-134.19], EntitySheep['Sheep'/17296698, l='MpServer', x=3950.31, y=68.00, z=-141.31], EntitySheep['Sheep'/17296697, l='MpServer', x=3946.78, y=64.00, z=-136.81], EntitySheep['Sheep'/17296696, l='MpServer', x=3944.56, y=68.00, z=-139.47], EntityHorse['Horse'/17296711, l='MpServer', x=3991.44, y=69.00, z=-125.25], EntityCow['Cow'/17296710, l='MpServer', x=3982.91, y=71.00, z=-131.09], EntityCow['Cow'/17296709, l='MpServer', x=3974.91, y=75.00, z=-139.54], EntityCow['Cow'/17296708, l='MpServer', x=3969.31, y=74.00, z=-139.47], EntityItem['item.item.egg'/17296707, l='MpServer', x=3974.25, y=76.13, z=-143.00], EntitySheep['Sheep'/17296706, l='MpServer', x=3976.68, y=75.00, z=-142.47], EntityChicken['Chicken'/17296705, l='MpServer', x=3977.28, y=74.00, z=-138.97], EntityCow['Cow'/17296704, l='MpServer', x=3979.47, y=73.00, z=-133.44], EntityChicken['Chicken'/17296719, l='MpServer', x=3991.53, y=71.00, z=-130.56], EntitySlime['Slime'/17296718, l='MpServer', x=3921.69, y=12.00, z=-131.69], EntitySpider['Spider'/17296717, l='MpServer', x=3930.81, y=47.00, z=-71.97], EntityZombie['Zombie'/17296716, l='MpServer', x=3926.54, y=41.00, z=-73.50], EntityZombie['Zombie'/17296715, l='MpServer', x=3930.50, y=47.00, z=-67.50], EntitySlime['Slime'/17296714, l='MpServer', x=3995.70, y=25.33, z=-83.31], EntityCow['Cow'/17296713, l='MpServer', x=3999.19, y=69.00, z=-122.81], EntityCow['Cow'/17296712, l='MpServer', x=3989.84, y=69.00, z=-123.88], EntitySlime['Slime'/17296727, l='MpServer', x=4014.31, y=14.00, z=-96.53], EntityChicken['Chicken'/17296726, l='MpServer', x=3962.95, y=76.00, z=-156.52], EntityChicken['Chicken'/17296725, l='MpServer', x=3967.19, y=76.00, z=-147.38], EntityCow['Cow'/17296724, l='MpServer', x=3909.59, y=65.00, z=-104.16], EntityItem['item.item.egg'/17296723, l='MpServer', x=3907.13, y=65.13, z=-102.94], EntityChicken['Chicken'/17296722, l='MpServer', x=3910.53, y=65.00, z=-103.19], EntityChicken['Chicken'/17296721, l='MpServer', x=3997.19, y=71.00, z=-142.78], EntitySheep['Sheep'/17296720, l='MpServer', x=3996.84, y=72.00, z=-142.12], EntitySheep['Sheep'/17296735, l='MpServer', x=3916.28, y=64.00, z=-83.41], EntitySheep['Sheep'/17296734, l='MpServer', x=3914.81, y=66.00, z=-91.81], EntitySkeleton['Skeleton'/17296733, l='MpServer', x=3917.31, y=12.00, z=-84.50], EntityBat['Bat'/17296732, l='MpServer', x=3958.96, y=47.86, z=-55.68], EntitySpider['Spider'/17296731, l='MpServer', x=3967.00, y=63.00, z=-52.47], EntityBat['Bat'/17296730, l='MpServer', x=3958.25, y=50.10, z=-49.66], EntityBat['Bat'/17296729, l='MpServer', x=3961.44, y=49.10, z=-52.75], EntityCow['Cow'/17296728, l='MpServer', x=4015.47, y=68.00, z=-101.41], EntitySlime['Slime'/17296743, l='MpServer', x=3951.31, y=40.00, z=-158.69], EntitySheep['Sheep'/17296742, l='MpServer', x=3908.47, y=65.00, z=-119.38], EntityCow['Cow'/17296741, l='MpServer', x=3909.91, y=65.00, z=-114.94], EntitySheep['Sheep'/17296740, l='MpServer', x=3917.81, y=64.00, z=-115.28], EntitySheep['Sheep'/17296739, l='MpServer', x=3919.94, y=64.00, z=-121.06], EntitySlime['Slime'/17296738, l='MpServer', x=3904.30, y=19.26, z=-119.69], EntitySlime['Slime'/17296737, l='MpServer', x=3919.69, y=12.00, z=-114.55], EntityTrail['unknown'/614, l='MpServer', x=3954.51, y=69.62, z=-107.23], EntitySlime['Slime'/17296736, l='MpServer', x=3910.31, y=13.13, z=-119.69], EntityItem['item.item.egg'/17296751, l='MpServer', x=4003.63, y=70.13, z=-122.25], EntityPig['Pig'/17296750, l='MpServer', x=3982.31, y=75.00, z=-151.56], EntityItem['item.item.egg'/17296749, l='MpServer', x=3979.38, y=75.13, z=-145.28], EntityCow['Cow'/17296748, l='MpServer', x=3969.91, y=76.00, z=-149.16], EntityPig['Pig'/17296747, l='MpServer', x=3972.09, y=76.00, z=-154.25], EntityChicken['Chicken'/17296746, l='MpServer', x=3983.53, y=72.00, z=-156.41], EntitySheep['Sheep'/17296745, l='MpServer', x=3972.97, y=76.00, z=-150.81], EntityPig['Pig'/17296744, l='MpServer', x=3977.91, y=76.00, z=-145.78], EntityZombie['Zombie'/17296759, l='MpServer', x=3973.88, y=63.00, z=-61.63], EntityCow['Cow'/17296758, l='MpServer', x=4009.50, y=66.00, z=-80.25], EntitySlime['Slime'/17296757, l='MpServer', x=4008.31, y=18.76, z=-84.20], EntityItem['item.item.slimeball'/17296756, l='MpServer', x=4006.13, y=15.13, z=-90.13], EntityItem['item.item.dyePowder.green'/17296755, l='MpServer', x=4006.13, y=15.13, z=-90.13], EntitySheep['Sheep'/17296754, l='MpServer', x=4013.16, y=73.00, z=-112.78], EntitySheep['Sheep'/17296753, l='MpServer', x=4000.66, y=70.00, z=-121.56], EntitySheep['Sheep'/17296752, l='MpServer', x=4005.44, y=72.00, z=-115.47], EntitySlime['Slime'/17296767, l='MpServer', x=3925.69, y=13.00, z=-154.69], EntitySheep['Sheep'/17296766, l='MpServer', x=3917.09, y=65.00, z=-137.13], EntitySheep['Sheep'/17296765, l='MpServer', x=3915.38, y=65.00, z=-136.47], EntitySheep['Sheep'/17296764, l='MpServer', x=3913.34, y=66.00, z=-128.44], EntitySheep['Sheep'/17296763, l='MpServer', x=3914.06, y=65.00, z=-140.06], EntitySheep['Sheep'/17296762, l='MpServer', x=3912.38, y=66.00, z=-131.56], EntityChicken['Chicken'/17296761, l='MpServer', x=3914.53, y=65.00, z=-141.53], EntitySkeleton['Skeleton'/17296760, l='MpServer', x=3907.84, y=17.00, z=-78.34], EntityPig['Pig'/17296775, l='MpServer', x=3988.47, y=70.00, z=-151.47], EntityCow['Cow'/17296774, l='MpServer', x=3993.69, y=72.00, z=-147.50], EntityItem['item.item.egg'/17296773, l='MpServer', x=3985.13, y=73.13, z=-149.06], EntityChicken['Chicken'/17296772, l='MpServer', x=3986.97, y=73.00, z=-150.06], EntityPig['Pig'/17296771, l='MpServer', x=3992.66, y=71.00, z=-149.53], EntityCow['Cow'/17296770, l='MpServer', x=3986.41, y=73.00, z=-152.09], EntityCow['Cow'/17296769, l='MpServer', x=3987.81, y=70.00, z=-153.88], EntitySlime['Slime'/17296768, l='MpServer', x=3921.31, y=13.00, z=-153.69], EntitySheep['Sheep'/17296783, l='MpServer', x=4004.66, y=71.00, z=-139.28], EntityPig['Pig'/17296782, l='MpServer', x=4011.78, y=73.00, z=-141.47], EntityPig['Pig'/17296781, l='MpServer', x=4003.44, y=71.00, z=-138.22], EntitySlime['Slime'/17296780, l='MpServer', x=4009.31, y=14.00, z=-132.31], EntityPig['Pig'/17296779, l='MpServer', x=3989.88, y=71.00, z=-150.91], EntityChicken['Chicken'/17296778, l='MpServer', x=3988.16, y=71.00, z=-150.22], EntityPig['Pig'/17296777, l='MpServer', x=3984.53, y=73.00, z=-144.66], EntityHorse['Donkey'/17296776, l='MpServer', x=3998.03, y=72.00, z=-146.66], EntityChicken['Chicken'/17296791, l='MpServer', x=3898.16, y=68.00, z=-111.66], EntitySheep['Sheep'/17296790, l='MpServer', x=3897.47, y=67.00, z=-103.63], EntitySheep['Sheep'/17296789, l='MpServer', x=3901.50, y=74.00, z=-104.50], EntityCow['Cow'/17296788, l='MpServer', x=4015.13, y=70.00, z=-74.47], EntityBat['Bat'/17296787, l='MpServer', x=4014.88, y=52.10, z=-66.97], EntityPig['Pig'/17296786, l='MpServer', x=4007.09, y=72.00, z=-140.94], EntityChicken['Chicken'/17296785, l='MpServer', x=4007.47, y=71.00, z=-130.47], EntityPig['Pig'/17296784, l='MpServer', x=4005.09, y=71.00, z=-137.81], EntitySlime['Slime'/17296799, l='MpServer', x=4020.31, y=14.00, z=-101.69], EntityCow['Cow'/17296798, l='MpServer', x=3904.53, y=67.00, z=-112.69], EntitySheep['Sheep'/17296797, l='MpServer', x=3904.47, y=67.00, z=-108.75], EntitySheep['Sheep'/17296796, l='MpServer', x=3894.16, y=67.00, z=-102.38], EntityItem['item.item.egg'/17296795, l='MpServer', x=3899.53, y=68.13, z=-108.69], EntityItem['item.item.egg'/17296794, l='MpServer', x=3895.22, y=69.13, z=-110.88], EntityCow['Cow'/17296793, l='MpServer', x=3895.41, y=68.00, z=-105.50], EntityChicken['Chicken'/17296792, l='MpServer', x=3896.75, y=69.00, z=-110.19], EntityCow['Cow'/17296807, l='MpServer', x=4021.59, y=71.00, z=-102.27], EntityChicken['Chicken'/17296804, l='MpServer', x=4018.26, y=70.26, z=-103.53], EntitySheep['Sheep'/17296803, l='MpServer', x=4018.91, y=67.00, z=-99.13], EntitySheep['Sheep'/17296802, l='MpServer', x=4025.16, y=68.00, z=-98.08], EntityCow['Cow'/17296801, l='MpServer', x=4017.17, y=70.00, z=-106.71], EntitySlime['Slime'/17296800, l='MpServer', x=4029.69, y=15.00, z=-100.31], EntityCow['Cow'/17296815, l='MpServer', x=3901.81, y=68.00, z=-118.50], EntitySheep['Sheep'/17296814, l='MpServer', x=3894.09, y=69.00, z=-117.38], EntitySlime['Slime'/17296813, l='MpServer', x=3903.11, y=20.00, z=-119.69], EntityBat['Bat'/17296812, l='MpServer', x=3955.66, y=49.68, z=-45.47], EntityBat['Bat'/17296811, l='MpServer', x=3953.91, y=51.10, z=-44.72], EntityChicken['Chicken'/17296810, l='MpServer', x=4023.53, y=73.00, z=-111.56], EntitySheep['Sheep'/17296809, l='MpServer', x=4019.19, y=68.00, z=-100.50], EntityChicken['Chicken'/17296808, l='MpServer', x=4025.83, y=68.00, z=-98.84], EntitySheep['Sheep'/17296823, l='MpServer', x=3893.03, y=68.00, z=-120.97], EntityChicken['Chicken'/17296822, l='MpServer', x=3894.78, y=69.00, z=-113.06], EntityCow['Cow'/17296821, l='MpServer', x=3891.50, y=69.00, z=-115.50], EntityCow['Cow'/17296820, l='MpServer', x=3895.69, y=69.00, z=-115.06], EntityCow['Cow'/17296819, l='MpServer', x=3895.50, y=69.00, z=-113.84], EntityCow['Cow'/17296818, l='MpServer', x=3894.09, y=68.00, z=-122.94], EntityCow['Cow'/17296817, l='MpServer', x=3899.72, y=68.00, z=-117.06], EntityCow['Cow'/17296816, l='MpServer', x=3892.94, y=69.00, z=-114.13], EntityCow['Cow'/17296831, l='MpServer', x=4029.84, y=78.00, z=-127.06], EntityChicken['Chicken'/17296830, l='MpServer', x=4030.53, y=77.00, z=-123.47], EntityChicken['Chicken'/17296829, l='MpServer', x=4028.73, y=75.00, z=-118.16], EntityHorse['Horse'/17296826, l='MpServer', x=4021.94, y=73.00, z=-113.06], EntityChicken['Chicken'/17296825, l='MpServer', x=3972.69, y=70.00, z=-170.53], EntityChicken['Chicken'/17296824, l='MpServer', x=3981.09, y=68.00, z=-171.41], EntityHorse['Horse'/17296839, l='MpServer', x=3919.28, y=66.00, z=-146.47], EntityHorse['Horse'/17296838, l='MpServer', x=3914.50, y=65.00, z=-148.50], EntitySlime['Slime'/17296837, l='MpServer', x=3915.69, y=33.00, z=-149.28], EntityChicken['Chicken'/17296836, l='MpServer', x=4019.53, y=66.00, z=-93.53], EntityCow['Cow'/17296833, l='MpServer', x=4019.44, y=70.00, z=-89.72], EntitySlime['Slime'/17296832, l='MpServer', x=4016.69, y=19.77, z=-82.31], EntitySlime['Slime'/17296847, l='MpServer', x=3921.56, y=17.00, z=-170.69], EntityPig['Pig'/17296846, l='MpServer', x=4008.88, y=72.00, z=-147.84], EntityCow['Cow'/17296845, l='MpServer', x=3997.98, y=71.00, z=-141.54], EntityPig['Pig'/17296844, l='MpServer', x=4001.58, y=72.00, z=-148.44], EntityChicken['Chicken'/17296843, l='MpServer', x=3912.84, y=64.00, z=-144.19], EntityItem['item.item.egg'/17296842, l='MpServer', x=3912.47, y=64.13, z=-144.91], EntityChicken['Chicken'/17296841, l='MpServer', x=3904.91, y=64.00, z=-151.41], EntityChicken['Chicken'/17296840, l='MpServer', x=3909.25, y=65.00, z=-147.47], EntityCow['Cow'/17296855, l='MpServer', x=4025.53, y=74.00, z=-79.41], EntityCow['Cow'/17296854, l='MpServer', x=4018.31, y=72.00, z=-75.53], EntityCow['Cow'/17296853, l='MpServer', x=4029.97, y=74.00, z=-78.53], EntityCow['Cow'/17296852, l='MpServer', x=3999.94, y=67.00, z=-173.34], EntityCow['Cow'/17296851, l='MpServer', x=3998.84, y=67.00, z=-173.97], EntityPig['Pig'/17296850, l='MpServer', x=3993.22, y=67.00, z=-175.16], EntityPig['Pig'/17296849, l='MpServer', x=3995.28, y=66.00, z=-164.16], EntityCow['Cow'/17296848, l='MpServer', x=3990.81, y=66.00, z=-167.88], EntityCow['Cow'/17296862, l='MpServer', x=4000.69, y=69.00, z=-162.54], EntityPig['Pig'/17296861, l='MpServer', x=4004.69, y=71.00, z=-167.50], EntityPig['Pig'/17296860, l='MpServer', x=4003.53, y=70.00, z=-163.19], EntityPig['Pig'/17296859, l='MpServer', x=4013.69, y=71.00, z=-169.53], EntityHorse['Horse'/17296857, l='MpServer', x=3901.34, y=66.00, z=-150.97], EntitySheep['Sheep'/17296856, l='MpServer', x=3876.19, y=67.00, z=-106.81], EntityZombie['Zombie'/17296879, l='MpServer', x=3957.31, y=63.00, z=-28.34], EntityZombie['Zombie'/17296878, l='MpServer', x=4010.24, y=67.00, z=-46.58], EntitySkeleton['Skeleton'/17296877, l='MpServer', x=4001.94, y=66.00, z=-36.31], EntityChicken['Chicken'/17296875, l='MpServer', x=4033.47, y=73.00, z=-101.44], EntitySlime['Slime'/17296886, l='MpServer', x=3946.31, y=26.00, z=-183.69], EntitySlime['Slime'/17296885, l='MpServer', x=3949.69, y=26.00, z=-176.31], EntityCow['Cow'/17296884, l='MpServer', x=3887.47, y=68.00, z=-123.53], EntitySheep['Sheep'/17296883, l='MpServer', x=3884.28, y=68.00, z=-116.13], EntitySheep['Sheep'/17296882, l='MpServer', x=3884.31, y=65.00, z=-81.75], EntityChicken['Chicken'/17296891, l='MpServer', x=3977.44, y=70.00, z=-185.47], EntityChicken['Chicken'/17296889, l='MpServer', x=3974.88, y=70.00, z=-184.75], EntitySheep['Sheep'/17296888, l='MpServer', x=3939.50, y=67.00, z=-186.50], EntityChicken['Chicken'/17296902, l='MpServer', x=4033.50, y=76.00, z=-119.50], EntityPig['Pig'/17296896, l='MpServer', x=3976.16, y=70.00, z=-184.19], EntityChicken['Chicken'/17296918, l='MpServer', x=4034.40, y=76.00, z=-83.81], EntitySheep['Sheep'/17296927, l='MpServer', x=3991.50, y=86.00, z=-182.50], EntitySheep['Sheep'/17296926, l='MpServer', x=3991.50, y=86.00, z=-180.50], EntityPig['Pig'/17296925, l='MpServer', x=3994.47, y=70.00, z=-185.50], EntityChicken['Chicken'/17296924, l='MpServer', x=3984.81, y=70.00, z=-187.38], EntityCow['Cow'/17296920, l='MpServer', x=4033.53, y=74.00, z=-95.36], EntityChicken['Chicken'/17296934, l='MpServer', x=4033.47, y=75.00, z=-82.35], EntityCow['Cow'/17296932, l='MpServer', x=4034.84, y=64.00, z=-64.22], EntitySheep['Sheep'/17296943, l='MpServer', x=3880.72, y=64.00, z=-53.84], EntityChicken['Chicken'/17296940, l='MpServer', x=4033.27, y=73.00, z=-170.41], EntitySlime['Slime'/17296939, l='MpServer', x=3895.69, y=13.00, z=-170.91], EntitySlime['Slime'/17296938, l='MpServer', x=3890.31, y=13.00, z=-174.50], EntitySlime['Slime'/17296937, l='MpServer', x=3888.44, y=27.00, z=-40.31], EntitySlime['Slime'/17296951, l='MpServer', x=4007.31, y=31.00, z=-187.69], EntitySlime['Slime'/17296950, l='MpServer', x=4002.31, y=31.00, z=-179.69], EntitySlime['Slime'/17296949, l='MpServer', x=4003.31, y=29.00, z=-180.31], EntitySlime['Slime'/17296948, l='MpServer', x=4002.31, y=28.00, z=-183.43], EntitySlime['Slime'/17296947, l='MpServer', x=4012.31, y=22.54, z=-183.31], EntityHorse['Donkey'/17296946, l='MpServer', x=3876.28, y=67.00, z=-156.63], EntitySheep['Sheep'/17296953, l='MpServer', x=4000.09, y=68.00, z=-183.83], EntityPig['Pig'/17296952, l='MpServer', x=4006.50, y=65.00, z=-177.03], EntitySheep['Sheep'/17297047, l='MpServer', x=3888.85, y=64.00, z=-49.32], EntityZombie['Zombie'/17297046, l='MpServer', x=3881.53, y=33.00, z=-31.00], EntityPig['Pig'/17297054, l='MpServer', x=4024.50, y=67.00, z=-29.16], EntitySheep['Sheep'/17297052, l='MpServer', x=4031.50, y=70.00, z=-176.50], EntitySheep['Sheep'/17297051, l='MpServer', x=4023.09, y=64.00, z=-182.97], EntitySlime['Slime'/17297050, l='MpServer', x=4016.69, y=24.00, z=-182.31], EntitySheep['Sheep'/17297049, l='MpServer', x=3880.34, y=66.00, z=-42.50], EntitySheep['Sheep'/17297048, l='MpServer', x=3886.90, y=65.00, z=-37.29]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3495814592 bytes (3333 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 15 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -Xms6G -Xmx6G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal (2).jar) 
	UCHIJA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	DragonAPI{v31b} [DragonAPI] (DragonAPI 1.7.10 V31b.jar) 
	UCHIJA	ChromatiCraft{v31b} [ChromatiCraft] (ChromatiCraft 1.7.10 V31b.jar) 
	UCHIJA	jinryuujrmcore{1.3.38} [JinRyuu's JRMCore] (JRMCore-v1.3.38.jar) 
	UCHIJA	jinryuudragonblockc{1.4.76} [Dragon Block C] (DragonBlockC-v1.4.76.jar) 
	UCHIJA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJA	jinryuubetterrenderaddon{1.6.48} [JinRyuu's Better Render Addon] (JBRA-Client-v1.6.48.jar) 
	UCHIJA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJA	MobDismemberment{4.0.0} [MobDismemberment] (MobDismemberment-4.0.0.jar) 
	UCHIJA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJA	Shatter{4.0.0} [Shatter] (Shatter-4.0.0.jar) 
	UCHIJA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 511.65' Renderer: 'NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2'
	Launched Version: forge-10.13.4.1614
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 511.65, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by ReikaKalseki** [comment]
#3005
