### ISSUE TITLE
[CC] Extreme Server Lag with Fragments

### ISSUE THREAD

**Issue by MalTeeez** [ReikaKalseki/Reika_Mods_Issues#2989]
When a player has about an inventory full of undiscovered fragments and can't discover any new ones because of progression the whole server (so far only tested on dedicated) goes on it's knees, the fragments seeming to take up about 65% of server thread time, mostly hashing?.
![image](https://user-images.githubusercontent.com/41554385/152824737-d1b0127a-d648-480b-a2cb-7d38dacb57e4.png)
![image](https://user-images.githubusercontent.com/41554385/152824869-0fffac37-bdb7-48b3-902f-cfe9e7290542.png)
![image](https://user-images.githubusercontent.com/41554385/152824989-1d71b9c1-f0b6-4296-83a6-67758ae31ded.png)

**Comment by ReikaKalseki** [comment]
This is going to be rendered largely redundant in the next update.
