### ISSUE TITLE
[ROC] translating problem - cannot try modified resource XMLs due to hash check

### ISSUE THREAD

**Issue by EnderAvaritia** [ReikaKalseki/Reika_Mods_Issues#2997]
there are some problem when I try to translate the book.
the hash checking include the other language of the book so that we can't update the translation of the book . As a result , the translation of the book will be out date at least one version and we can't check the new translation working condition.

**Comment by ReikaKalseki** [comment]
I will look into making those files immune to the hash check, but I can make no promises.

**Comment by EnderAvaritia** [comment]
Thanks for your understanding。

**Comment by EnderAvaritia** [comment]
Thanks for your understanding。

**Comment by ReikaKalseki** [comment]
This is not within my control - hashing is done by an external process and operates monolithically on the JAR.

Your problem is a legitimate one, but I do not see a solution.
