### ISSUE TITLE
Reactorcraft steam turbines causing major spinning glitch

### ISSUE THREAD

**Issue by dwenograd** [ReikaKalseki/Reika_Mods_Issues#3]
Just moving this here so it's easier to track.

Everything was going fine during my first test run with the first two turbines. The moment I put on the steam line connecting the other two turbines, everything started spinning, and not in the way it's supposed to. It started leaking steam everywhere from the third turbine (seemingly out of a solid basalt block that I put there to catch it on the third turbine, visible in the video) and wasn't generating any power at all (on the third turbine at least), and it all fixed itself once I shut the other two down. Oddly, the glitch seemed to be contained to a handful of chunks, the line of glitched shafts ending the moment it crossed into the next one. It also didn't resurface when I turned the turbines back on a few minutes later.

Preview of bug:
https://www.youtube.com/watch?v=kra5OLUPkzU

**Comment by ReikaKalseki** [comment]
This is a vanilla bug triggered by letting steam escape and float freely. Capture (and either recondense or void) the steam.

**Comment by zemerick** [comment]
Can you also verify your version? From what I saw, it looks like you're on an extremely old version. Bug reports should only be for the current version. ( v6f atm. )

**Comment by dwenograd** [comment]
It's on the latest version, v6f Rotarycraft/DragonAPI and v6e Reactorcraft.
