### ISSUE TITLE
Ore / Stone Generation Heights & Configs

### ISSUE THREAD

**Issue by bookerthegeek** [ReikaKalseki/Reika_Mods_Issues#300]
May we please have a list of the min/max height for each of the:
- Stone variants from GeoStrata.
- Ores from Electricraft

Thank you in advance.

Have an option to enable "extended y axis placement" which would increase the max y level, maybe be a config option  to specify max y, but have a default min of 64, less then 64 would be ignored to prevent people from setting it to zero.
Create a couple different generation options... "distinct bands" which have a separation between each, "Mixed bands" that would have a partial overlap of stones, but you would never touch more then two types at the same y level?

**Comment by bookerthegeek** [comment]
Have an option to enable "extended y axis placement" which would increase the max y level, maybe be a config option  to specify max y, but have a default min of 64, less then 64 would be ignored to prevent people from setting it to zero.
Create a couple different generation options... "distinct bands" which have a separation between each, "Mixed bands" that would have a partial overlap of stones, but you would never touch more then two types at the same y level?

**Comment by ReikaKalseki** [comment]
Banded generation has been implemented.

**Comment by bookerthegeek** [comment]
Thank you good sir.
