### ISSUE TITLE
RotaryCraft Grinder Loses Enchantment on Server Restart

### ISSUE THREAD

**Issue by CaiB** [ReikaKalseki/Reika_Mods_Issues#3002]
I enchanted a Grinder with Fortune V using an enchanted book, and noted that the output increased (so the enchantment appears to have applied successfully). After a server restart, it has lost the enchantment, and is back to outputting the standard amount of lubricant per canola seed.

**Comment by CaiB** [comment]
Correction: it doesn't require a server restart. Simply relogging is sufficient, and I'm not even sure it applied it in the first place anymore. The enchanted book does disappear permanently however, and until relogging, it glows purple and the enchantment is shown in WAILA.

**Comment by EyeDeck** [comment]
The enchantment _does_ work, but the grinder's missing code to read/write an appropriate NBT tag, so the enchantment is lost every time the TE unloads.
Working example, the woodcutter: https://github.com/ReikaKalseki/RotaryCraft/blob/ff7ba46cba5134c8cea59b416703ab348424cca3/TileEntities/Farming/TileEntityWoodcutter.java#L595
Grinder should have similar code, but doesn't: https://github.com/ReikaKalseki/RotaryCraft/blob/ff7ba46cba5134c8cea59b416703ab348424cca3/TileEntities/Processing/TileEntityGrinder.java#L152

Edit: oops, mutilated that second link after an edit.

**Comment by EyeDeck** [comment]
Looks like this one should be fixed with v32c:
https://github.com/ReikaKalseki/RotaryCraft/blame/b3f3e8dceb1d7c629c9f828fb21393f2e1357e0a/TileEntities/Processing/TileEntityGrinder.java#L157

**Comment by ReikaKalseki** [comment]
#3135
