### ISSUE TITLE
ChromatiCraft crash with GTNH's AE2

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#3003]
ChromatiCraft crash with GTNH's AE2. https://pastebin.com/NmvvGmkg

Their AE changes are very useful, Hope you can be compatible with their AE changes

![image](https://user-images.githubusercontent.com/19620848/156164135-5428c97b-dc46-4fe4-a33d-181709b2f6f5.png)

https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial

**Comment by MalTeeez** [comment]
Duplicate of #2977
