### ISSUE TITLE
[ChromatiCraft] AE2 main issue reports being ended once and for all [Recomendation] 

### ISSUE THREAD

**Issue by Shibva** [ReikaKalseki/Reika_Mods_Issues#3004]
Hi, I was going to give up on this mod till I found out that it was acting this way because of AE2 beta r3

and by the looks of things, this has been a reoccurring report and a nuance. and if it wasn't for me looking on here, I would have never found the issue out. So here is my Solution to this issue

in newer versions, Twilight Forrest has added a thing that appears each time you load up the game (unless it is configured off) and this serves as a purpose of informing the user of an issue that might occur when using shaders. what am I getting at? well it is simple really, why not do the same thing for this damned issue

If the version of AE2 is the bugged one, then it will display a waring as long as in internal config is set to true, if this is set to false the message will stop appearing per every game bootup

**Comment by ReikaKalseki** [comment]
It is not "a bugged AE version", it is an AE config not being set correctly.

https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1732 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1683 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1681 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1493 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1257 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1280 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1238 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2390 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1848 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1985 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2419 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2502 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2595 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2903 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/3032

**Comment by OvermindDL1** [comment]
It is not a bugged AE version or a misset AE config, AE2 is performing things properly, something in ChC is not instancing items completely and fully in preinit.

**Comment by Shibva** [comment]
The interesting part of this is that it's only doing this when it's not a aE2 release; if you're using an actual release and not one of the ones flagged on the beta or alpha this issue is nonexistent

**Comment by Shibva** [comment]
The issue itself is not that critical; it just means that whenever you change the mod pack once it'll crash and then it'll boot up the next time to completion

The question is why part of chromatic craft is causing this sort of trip to happen within the research that self resolves itself after a second boot
