### ISSUE TITLE
ChromatiCraft: Ruints shield DOES NOT LIKE TO BE TOCHED!

### ISSUE THREAD

**Issue by Shibva** [ReikaKalseki/Reika_Mods_Issues#3005]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 3/9/22 2:29 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at Reika.ChromatiCraft.Block.Dimension.Structure.Locks.BlockColoredLock.func_149734_b(BlockColoredLock.java:88)
	at net.minecraft.client.multiplayer.WorldClient.func_73029_E(WorldClient.java:308)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2048)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Reika.ChromatiCraft.Block.Dimension.Structure.Locks.BlockColoredLock.func_149734_b(BlockColoredLock.java:88)
	at net.minecraft.client.multiplayer.WorldClient.func_73029_E(WorldClient.java:308)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Shibva_'/613, l='MpServer', x=-44.00, y=75.61, z=240.32]]
	Chunk stats: MultiplayerChunkCache: 574, 574
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-40,64,252), Chunk: (at 8,4,12 in -3,15; contains blocks -48,0,240 to -33,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 11628 game time, 11628 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 41 total; [EntityBat['Bat'/283014, l='MpServer', x=-32.53, y=20.79, z=306.41], EntitySquid['Squid'/283018, l='MpServer', x=0.13, y=59.34, z=266.50], EntitySquid['Squid'/283019, l='MpServer', x=-9.50, y=58.00, z=271.53], EntityBat['Bat'/283045, l='MpServer', x=-23.40, y=26.58, z=281.23], EntityBat['Bat'/283046, l='MpServer', x=-20.59, y=26.00, z=281.75], EntityItem['item.item.porkchopRaw'/270790, l='MpServer', x=-102.94, y=65.13, z=204.88], EntityItem['item.item.porkchopRaw'/270796, l='MpServer', x=-101.44, y=65.13, z=206.38], EntityItem['item.item.porkchopRaw'/270794, l='MpServer', x=-100.75, y=64.13, z=204.22], EntityBat['Bat'/283088, l='MpServer', x=-119.31, y=38.16, z=221.06], EntityItem['item.item.porkchopRaw'/270802, l='MpServer', x=-102.19, y=67.13, z=286.19], EntityItem['item.item.porkchopRaw'/270816, l='MpServer', x=-97.84, y=66.13, z=286.81], EntityItem['item.item.porkchopRaw'/270853, l='MpServer', x=-93.81, y=63.13, z=198.09], EntityItem['item.item.porkchopRaw'/270859, l='MpServer', x=-88.19, y=63.13, z=203.09], EntityItem['item.item.porkchopRaw'/270869, l='MpServer', x=-73.09, y=66.13, z=283.41], EntityItem['item.item.porkchopRaw'/270867, l='MpServer', x=-96.84, y=64.13, z=208.41], EntityItem['item.item.porkchopRaw'/270876, l='MpServer', x=-72.47, y=66.13, z=284.72], EntityItem['item.item.porkchopRaw'/270884, l='MpServer', x=-76.13, y=64.13, z=286.06], EntityBat['Bat'/283183, l='MpServer', x=-97.25, y=43.10, z=287.41], EntityItem['item.item.porkchopRaw'/270890, l='MpServer', x=-77.03, y=63.13, z=290.47], EntityBat['Bat'/283186, l='MpServer', x=-79.63, y=6.10, z=190.28], EntityItem['item.item.porkchopRaw'/270911, l='MpServer', x=-62.47, y=66.13, z=223.66], EntityItem['item.item.porkchopRaw'/270914, l='MpServer', x=-45.88, y=64.13, z=229.53], EntityItem['item.item.porkchopRaw'/270931, l='MpServer', x=-41.22, y=63.13, z=213.16], EntityItem['item.item.porkchopRaw'/270937, l='MpServer', x=-23.44, y=63.13, z=246.59], EntityItem['item.item.porkchopRaw'/270964, l='MpServer', x=-16.63, y=62.13, z=238.75], EntityItem['item.item.porkchopRaw'/270980, l='MpServer', x=-18.47, y=70.13, z=300.56], EntityItem['item.item.porkchopRaw'/270983, l='MpServer', x=-6.34, y=62.13, z=253.72], EntityItem['item.item.porkchopRaw'/270995, l='MpServer', x=-13.38, y=63.13, z=249.03], EntityItem['item.tile.cloth.white'/271006, l='MpServer', x=-12.03, y=75.13, z=292.91], EntityItem['item.item.porkchopRaw'/271001, l='MpServer', x=-5.19, y=59.13, z=266.47], EntityItem['item.item.porkchopRaw'/271011, l='MpServer', x=-2.81, y=75.13, z=288.41], EntityItem['item.item.porkchopRaw'/271018, l='MpServer', x=-2.91, y=76.13, z=289.91], EntityItem['item.item.porkchopRaw'/271059, l='MpServer', x=5.63, y=76.13, z=300.91], EntityItem['item.item.porkchopRaw'/271069, l='MpServer', x=1.06, y=76.13, z=300.81], EntityItem['item.tile.cloth.white'/271079, l='MpServer', x=7.97, y=77.13, z=293.63], EntityItem['item.tile.cloth.white'/271083, l='MpServer', x=4.63, y=76.13, z=301.16], EntityClientPlayerMP['Shibva_'/613, l='MpServer', x=-542.65, y=124.33, z=-3.24], EntityItem['item.item.hev_legs'/285834, l='MpServer', x=-43.01, y=73.49, z=239.43], EntityBat['Bat'/283949, l='MpServer', x=5.28, y=22.00, z=245.75], EntityBat['Bat'/283952, l='MpServer', x=-91.25, y=6.95, z=314.41], EntityClientPlayerMP['Shibva_'/613, l='MpServer', x=-44.00, y=75.61, z=240.32]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2413917280 bytes (2302 MB) / 6643777536 bytes (6336 MB) up to 11240734720 bytes (10720 MB)
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10720m -Xms256m -XX:+UseG1GC -XX:ParallelGCThreads=4 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	OpenComputers|Core{1.7.5.1290} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	legends{8.5.1} [Legends Mod] (1Legends-1.7.10-8.5.1.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJAAAA	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	BloodArsenal{1.2-5} [Blood Arsenal] (BloodArsenal-1.7.10-1.2-5.jar) 
	UCHIJAAAA	DragonAPI{v31b} [DragonAPI] (DragonAPI 1.7.10 V31b.jar) 
	UCHIJAAAA	ChromatiCraft{v31b} [ChromatiCraft] (ChromatiCraft 1.7.10 V31b.jar) 
	UCHIJAAAA	controlling{1.0.0} [Controlling] (Controlling-1.7.10-1.0.0.jar) 
	UCHIJAAAA	extracells{2.4.0} [Extra Cells 2] (ExtraCells-1.7.10-2.4.0.jar) 
	UCHIJAAAA	fbp{2.4.1} [Fancy Block Particles] (FancyBlockParticles-1.7.x-2.4.1.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (4144)} [Hbm's Nuclear Tech] (HBM-NTM-[1.0.27_X4144].jar) 
	UCHIJAAAA	NOVA{2015-10-09} [NOVA] (NOVA-2015-10-09-universal.jar) 
	UCHIJAAAA	OpenComputers{1.7.5.1290} [OpenComputers] (OpenComputers-MC1.7.10-1.7.5.1290-universal.jar) 
	UCHIJAAAA	p455w0rdslib{1.0.4} [p455w0rd's Library] (p455w0rdslib-1.7.10-1.0.4.jar) 
	UCHIJAAAA	Sanguimancy{1.7.10-1.1.9-35} [Sanguimancy] (Sanguimancy-1.7.10-1.1.9-35.jar) 
	UCHIJAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHIJAAAA	ae2wct{1.7.10-rv3-1.8.7.4b} [AE2 Wireless Crafting Terminal] (WirelessCraftingTerminal-1.7.10-rv3-1.8.7.4b.jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAA	witcherypatch{1.0.0} [WitcheryPatch] (WitcheryPatch-1.7.10-1.0.0.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 472.12' Renderer: 'NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2'
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:OFF, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:ON, PneumaticCraft:OFF
	Launched Version: forge-10.13.4.1614
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 472.12, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	
	How To reproduce: have any entity in creative (or survival, not sure it matters) touch the shield, even items will work

**Comment by ReikaKalseki** [comment]
I fixed this a long time ago, though I am not 100% sure it was released.
