### ISSUE TITLE
(Reactorcraft V31. b) Controll Rods causing crash when rasing or lowering them

### ISSUE THREAD

**Issue by Hirqx** [ReikaKalseki/Reika_Mods_Issues#3006]
When raising or lowering the control rods (individually or all together) the game crashes. 
I'm running V31. b of Reactorcraft.

https://pastebin.com/tWEQZc3j

**Comment by MachiavelliSeraphim** [comment]
Ive never had good luck getting the control rods to work, but I havent tried to use them since like V24 or V26.

Had some time so I just tested the control rods.
Immediate crash when they pulled up.

https://pastebin.com/WEuTHasd

**Comment by ReikaKalseki** [comment]
I remember fixing this.
