### ISSUE TITLE
Angular transducer readouts use int-casted power and have overflow

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [ReikaKalseki/Reika_Mods_Issues#3007]
Version Info
RotaryCraft+1.7.10+V31b
ReactorCraft+1.7.10+V31b
ElectriCraft+1.7.10+V31a
DragonAPI+1.7.10+V31b

The angular transducer is showing extremely buggy readings on shafts and shaft junctions.

I was building a creative HP Turbine dummy to test some machinery layouts and this is what I found.

Power is moving according to the Dynamometer, but the transducer does not show the same on the junctions and shafts, sometimes showing negative numbers.

![Layout](https://user-images.githubusercontent.com/10451525/159298867-85747118-3efa-4596-95bd-cdf67fdfd77b.png)
![1st Junction](https://user-images.githubusercontent.com/10451525/159298896-c78c5dc8-7e22-47ab-bc23-62134e4999d1.png)
![2nd Junction](https://user-images.githubusercontent.com/10451525/159298912-952002fc-3f33-4eea-b349-040c15681c1e.png)
![3rd Junction](https://user-images.githubusercontent.com/10451525/159298922-a177a679-6723-4a82-971f-833026c59137.png)
![End Bevel](https://user-images.githubusercontent.com/10451525/159298939-e77945e3-92f6-467d-88b0-ca2b6dc49e3d.png)
![8GW Shaft after Bevel](https://user-images.githubusercontent.com/10451525/159298944-7402e2cb-2cb5-48b3-afc8-be52367c2176.png)
![Second String Input Bevel](https://user-images.githubusercontent.com/10451525/159298959-e6aa1fce-6ab8-4b73-b782-c9960bd0d14e.png)

Also on a side note, what is the power limit on the induction generator now if you don't mind me asking?
They definitely explode at 1 GW.
Its nothing I cant plan around, I just used to use them to segregate my power grid into sub-grids before.

Thank you.

**Comment by ReikaKalseki** [comment]
It looks like you hit the integer limits and are experiencing overflow. Power is a `long` internally, so the right amount is being transmitted, but something is casting it to `int` in the rendering here.

**Comment by MachiavelliSeraphim** [comment]
Whats odd is that I havent had a problem on a multiplayer world that I can think of.  
This only happened in a single player world.  

Just realized it.  Dont know if it helps.

**Comment by ReikaKalseki** [comment]
Turns out it was not a display bug - the power value actually *did* overflow because of all TE types shafts forgot to cast `omega` and `torque` to `long` before multiplying them.
