### ISSUE TITLE
[Chromaticraft v31b] Crash in Chroma dimension due to invalid biome id

### ISSUE THREAD

**Issue by Dotz0cat** [ReikaKalseki/Reika_Mods_Issues#3008]
After getting to the chroma dimension I have crashed 3 times due to a nullPointerException from an invalid biome id. 

Here is the crash report:
https://pastebin.com/K3aiVuBA

Here is the log:
https://pastebin.com/EJYEcrgW

**Comment by ReikaKalseki** [comment]
#2962
