### ISSUE TITLE
ItemScrewdriverFocus issue (presumedly?)

### ISSUE THREAD

**Issue by shrilleth** [ReikaKalseki/Reika_Mods_Issues#3009]
Log: [New Paste 1.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/8354177/New.Paste.1.txt)

Crash Report: [crash-2022-03-25_17.43.28-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/8354178/crash-2022-03-25_17.43.28-client.txt)

**Comment by ReikaKalseki** [comment]
#2948
