### ISSUE TITLE
Block Model incorrectly rendering (V31b)

### ISSUE THREAD

**Issue by Keepsedge** [ReikaKalseki/Reika_Mods_Issues#3010]
Similar to issue #715 However the blocks were not spawned in.

All things were fine last night while playing on an open LAN game with my wife. This morning I start up the game, and none of the models, or textures load correctly. I tried removing blocks and replacing them, unloading and loading the chunks. 

All the TileEntities still work, UI's still open, data is present, and updating. They just look a bit weird. I've seen this happen a few times, and typically just waiting a few minutes will sort out the issue. Since 31b though this does not seem to help.

**Comment by Hirqx** [comment]
It's an April fools joke. It will go back to normal tomorrow or after the 3rd, not 100% sure on that.

**Comment by Keepsedge** [comment]
OoOo. well, I'm officially Got then. Well played.
