### ISSUE TITLE
Fusion Reactor Injector Multiblock Not Completeing

### ISSUE THREAD

**Issue by An-nym-us** [ReikaKalseki/Reika_Mods_Issues#3011]
I've been having problems with trying to get multiblock for the fusion reactor fusion injector to correctly complete.  I know for 100% certainty that I was assembling the multiblock correctly, and went as far as to open an old 1.6.4 world with reactor craft and all installed, made the model exactly as I did in the 1.7.10  v31b version, and it assembled correctly in the 1.6.4 version of the game. I also went ahead and install the 1.7.10 v31b into 2 other personal mod packs and all the other multiblock structures work fine for reactor craft, but the fusion injector multiblock does not want to work. Is there a new multiblock set-up for the injectors that is different from the 1.6.4 version? I'm not sure where to go from here.

**Comment by Holorizor** [comment]
Hi,
I have the same problem but the problem is known and fixed (see https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2956). We have to wait for the next release.
