### ISSUE TITLE
Rotarycraft (V31b) Achievement "Engaged" does not trigger

### ISSUE THREAD

**Issue by Holorizor** [ReikaKalseki/Reika_Mods_Issues#3013]
MC Version: 1.7.10
Rotarycraft Version: V31b

Hello,
I am back in playing Reikas Mods and have problems getting the engaged achievement (Make a steel shaft). I tried in several ways. Crafting it, getting it from the creative menu, getting it per command (the HSLA steel shaft), Loading it with power, overloading it with power.

Do I misinterpret the requirements or is this a bug?

Best
Holorizor

**Comment by ReikaKalseki** [comment]
Fixed, one year after reporting and three years after introduction. :P

**Comment by Holorizor** [comment]
Yes it is fixed in version V33a
