### ISSUE TITLE
Cromaticraft Crashing Reika.DragonAPI.Exception.RegistrationException: CHROMATICRAFT has a registration error: Failed to load REPEATERLAMP due to a missing class:  Contact Reika immediately!

### ISSUE THREAD

**Issue by ThomasDennisSp** [ReikaKalseki/Reika_Mods_Issues#3014]
Error: Reika.DragonAPI.Exception.RegistrationException: CHROMATICRAFT has a registration error:
Exit-Code: -
[crash-2022-04-09_16.14.22-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/8457094/crash-2022-04-09_16.14.22-client.txt)
1

**Comment by ThomasDennisSp** [comment]
the culprit was fluxed Crystals and fluxed Crystals2

**Comment by ReikaKalseki** [comment]
This was a mod API issue.
