### ISSUE TITLE
ReactorCraft format error crash

### ISSUE THREAD

**Issue by Plugner** [ReikaKalseki/Reika_Mods_Issues#3015]
Crash report: https://pastebin.com/SWQdBWeM
Hello, I'm having some issues with ReactorCraft, that one I couldn't fix in my modpack, I searched the internet but nothing related to forge/reactorcraft.

**Comment by ReikaKalseki** [comment]
What language are you playing in? Does it still happen in English?

**Comment by Plugner** [comment]
Sorry for the delay, I'm playing in English.

**Comment by ReikaKalseki** [comment]
This does not happen for me and noone else has reported this, which is exceedingly unlikely for a crash-on-load. The files must be corrupted.
