### ISSUE TITLE
ChromatiCraft java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by Plugner** [ReikaKalseki/Reika_Mods_Issues#3016]
Crash logs: https://pastebin.com/gwg1NrvZ

Environment:
 VMWare ESXi 6.7 Debian 11 virtualized machine.
 2 cores + 8GB ram
 i5-7400
 Linux Kernel: 5.10.11-lts
 Java version: openjdk version "1.8.0_322"
                       OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
                       OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b06, mixed mode)
Server Jar file: forge-1.7.10-10.13.4.1614-1.7.10-universal.jar 
Server start command: java -XX:+UseG1GC -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:MetaspaceSize=1024m -XX:MaxMetaspaceSize=2048m -XX:+AggressiveOpts -XX:MaxGCPauseMillis=10 -XX:+UseStringDeduplication -Dfile.encoding=utf-8 -Xms128M -Xmx2G -XX:hashCode=5 -Dfile.encoding=UTF-8 -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar nogui

**Comment by ReikaKalseki** [comment]
Recheck your downloads.

**Comment by Plugner** [comment]
Somehow that worked, sorry.
