### ISSUE TITLE
Confusion with Crafting pattern´s differend modes

### ISSUE THREAD

**Issue by ThomasDennisSp** [ReikaKalseki/Reika_Mods_Issues#3017]
so i want to automate the crafting of rotarycraft recepes from the worktable and in the crafting pattern is an option for the blast furnace and for the worktable but how do i get it crafted if i put the pattern in an autocrafting unit it doesnt craft it cause it can just do vanilla crafting table and if i put a worktable next or on top of it it still doesnt work so where do i put the pattern with the other modes (exept vanilla) or do i have to put someting speciale next to it ore connect both with each other in a special manner

**Comment by Holorizor** [comment]
Hi,
i just tried it out and you can put the crafting template (normally used in the auto crafting unit) also in the rotarycraft worktabel. simply put it in the lower left corner. if so you can put materials inside via ducts or hopper and the worktable will only accept the items in the recipy template. with a redstone signal you can let the worktable craft your item. WIth another item duct oder hopper you can remove the crafting items.

**Comment by ThomasDennisSp** [comment]
ok thx
