### ISSUE TITLE
Crashes when Control Rods are inserted.

### ISSUE THREAD

**Issue by ThatCat287** [ReikaKalseki/Reika_Mods_Issues#3018]
When I use the Central Control, and insert any connected Control Rods, immediately after they insert, the game will crash. I have no mods installed other than RotaryCraft, ReactorCraft, ElectriCraft, and DragonAPI.

Crash Log:
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 4/19/22 1:27 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.nbt.NBTTagCompound.func_74762_e(NBTTagCompound.java:173)
	at Reika.ReactorCraft.TileEntities.Fission.TileEntityControlRod.readSyncTag(TileEntityControlRod.java:158)
	at Reika.DragonAPI.Base.TileEntityBase.onDataPacket(TileEntityBase.java:422)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1144)
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.nbt.NBTTagCompound.func_74762_e(NBTTagCompound.java:173)
	at Reika.ReactorCraft.TileEntities.Fission.TileEntityControlRod.readSyncTag(TileEntityControlRod.java:158)
	at Reika.DragonAPI.Base.TileEntityBase.onDataPacket(TileEntityBase.java:422)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1144)
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['SlimeCat287'/21, l='MpServer', x=656.88, y=9.03, z=281.81]]
	Chunk stats: MultiplayerChunkCache: 552, 552
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (653,4,282), Chunk: (at 13,0,10 in 40,17; contains blocks 640,0,272 to 655,255,287), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 2060 game time, 2060 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 163 total; [EntitySlime['Slime'/156427, l='MpServer', x=689.38, y=4.85, z=260.48], EntitySlime['Slime'/221706, l='MpServer', x=623.34, y=4.00, z=298.81], EntityChicken['Chicken'/114445, l='MpServer', x=721.44, y=4.00, z=298.56], EntitySlime['Slime'/685316, l='MpServer', x=695.50, y=4.00, z=300.50], EntitySlime['Slime'/576792, l='MpServer', x=733.08, y=4.95, z=216.34], EntitySlime['Slime'/285206, l='MpServer', x=650.90, y=4.00, z=221.18], EntityChicken['Chicken'/114450, l='MpServer', x=722.75, y=4.00, z=304.72], EntityClientPlayerMP['SlimeCat287'/21, l='MpServer', x=656.88, y=9.03, z=281.81], EntityChicken['Chicken'/114455, l='MpServer', x=720.56, y=4.00, z=304.72], EntitySlime['Slime'/611605, l='MpServer', x=588.75, y=4.00, z=304.46], EntityChicken['Chicken'/114460, l='MpServer', x=723.66, y=4.00, z=302.13], EntityHorse['Horse'/114465, l='MpServer', x=722.75, y=4.00, z=298.16], EntityHorse['Horse'/114213, l='MpServer', x=652.56, y=4.00, z=242.19], EntityHorse['Horse'/114214, l='MpServer', x=642.19, y=4.00, z=258.88], EntityHorse['Horse'/114470, l='MpServer', x=717.00, y=4.00, z=304.72], EntitySheep['Sheep'/114217, l='MpServer', x=642.19, y=4.00, z=256.22], EntityHorse['Horse'/114216, l='MpServer', x=658.56, y=4.00, z=251.22], EntityCow['Cow'/114219, l='MpServer', x=652.31, y=4.00, z=246.41], EntityCow['Cow'/114221, l='MpServer', x=676.16, y=4.00, z=240.13], EntityHorse['Horse'/114476, l='MpServer', x=716.25, y=4.00, z=302.38], EntityCow['Cow'/114222, l='MpServer', x=651.44, y=4.00, z=274.72], EntityHorse['Horse'/114481, l='MpServer', x=724.63, y=4.00, z=305.63], EntityChicken['Chicken'/114224, l='MpServer', x=651.75, y=4.00, z=362.31], EntitySlime['Slime'/562490, l='MpServer', x=725.05, y=4.33, z=339.61], EntitySlime['Slime'/291126, l='MpServer', x=734.93, y=5.00, z=287.47], EntityChicken['Chicken'/114487, l='MpServer', x=719.41, y=4.00, z=301.84], EntitySlime['Slime'/329010, l='MpServer', x=624.50, y=4.00, z=362.54], EntityHorse['Donkey'/114235, l='MpServer', x=607.50, y=4.00, z=329.50], EntitySlime['Slime'/316223, l='MpServer', x=609.59, y=4.00, z=266.74], EntityHorse['Donkey'/114236, l='MpServer', x=608.38, y=4.00, z=332.19], EntityChicken['Chicken'/114492, l='MpServer', x=731.44, y=4.00, z=304.47], EntityPig['Pig'/114239, l='MpServer', x=611.97, y=4.00, z=335.94], EntityPig['Pig'/114240, l='MpServer', x=605.81, y=4.00, z=328.31], EntityHorse['Horse'/114243, l='MpServer', x=612.50, y=4.00, z=328.50], EntitySheep['Sheep'/114499, l='MpServer', x=675.13, y=4.00, z=212.94], EntitySlime['Slime'/463685, l='MpServer', x=591.31, y=4.00, z=307.28], EntityPig['Pig'/114242, l='MpServer', x=610.16, y=4.00, z=336.34], EntityChicken['Chicken'/114498, l='MpServer', x=716.50, y=4.00, z=300.50], EntitySlime['Slime'/389190, l='MpServer', x=681.63, y=4.95, z=245.19], EntityHorse['Horse'/114245, l='MpServer', x=615.50, y=4.00, z=328.50], EntityHorse['Horse'/114244, l='MpServer', x=614.50, y=4.00, z=326.50], EntityPig['Pig'/114247, l='MpServer', x=643.22, y=4.00, z=350.50], EntityHorse['Horse'/114503, l='MpServer', x=661.38, y=4.00, z=204.50], EntityPig['Pig'/114249, l='MpServer', x=636.16, y=4.00, z=345.34], EntityHorse['Horse'/114505, l='MpServer', x=657.75, y=4.00, z=207.44], EntityPig['Pig'/114248, l='MpServer', x=641.50, y=4.00, z=349.50], EntityHorse['Horse'/114504, l='MpServer', x=650.06, y=4.00, z=210.16], EntitySheep['Sheep'/114251, l='MpServer', x=634.31, y=4.00, z=359.09], EntitySlime['Slime'/101963, l='MpServer', x=655.78, y=4.85, z=284.22], EntityPig['Pig'/114250, l='MpServer', x=640.50, y=4.00, z=341.50], EntityHorse['Horse'/114506, l='MpServer', x=656.09, y=4.00, z=207.00], EntityChicken['Chicken'/114509, l='MpServer', x=662.69, y=4.00, z=204.50], EntitySheep['Sheep'/114252, l='MpServer', x=643.16, y=4.00, z=357.50], EntitySlime['Slime'/484682, l='MpServer', x=678.29, y=4.00, z=271.67], EntitySheep['Sheep'/114255, l='MpServer', x=644.81, y=4.00, z=350.50], EntitySlime['Slime'/184140, l='MpServer', x=672.65, y=4.00, z=301.92], EntitySheep['Sheep'/114511, l='MpServer', x=712.50, y=4.00, z=361.50], EntitySheep['Sheep'/114254, l='MpServer', x=641.19, y=4.00, z=356.19], EntityChicken['Chicken'/114510, l='MpServer', x=659.69, y=4.00, z=204.31], EntitySheep['Sheep'/114257, l='MpServer', x=644.44, y=4.00, z=357.16], EntitySheep['Sheep'/114256, l='MpServer', x=648.91, y=4.00, z=349.94], EntitySheep['Sheep'/114259, l='MpServer', x=590.50, y=4.00, z=339.50], EntityChicken['Chicken'/114515, l='MpServer', x=713.63, y=4.00, z=358.03], EntitySheep['Sheep'/114258, l='MpServer', x=653.50, y=4.00, z=352.50], EntitySheep['Sheep'/114261, l='MpServer', x=593.50, y=4.00, z=340.50], EntityChicken['Chicken'/114517, l='MpServer', x=726.31, y=4.00, z=357.53], EntitySheep['Sheep'/114260, l='MpServer', x=590.50, y=4.00, z=335.50], EntityChicken['Chicken'/114516, l='MpServer', x=714.50, y=4.00, z=357.50], EntityChicken['Chicken'/114263, l='MpServer', x=585.66, y=4.00, z=343.09], EntityPig['Pig'/114519, l='MpServer', x=713.88, y=4.00, z=361.72], EntitySheep['Sheep'/114262, l='MpServer', x=592.50, y=4.00, z=337.50], EntityChicken['Chicken'/114518, l='MpServer', x=717.38, y=4.00, z=362.28], EntityChicken['Chicken'/114265, l='MpServer', x=578.72, y=4.00, z=346.44], EntityPig['Pig'/114521, l='MpServer', x=706.06, y=4.00, z=353.94], EntityChicken['Chicken'/114264, l='MpServer', x=582.19, y=4.00, z=347.34], EntityPig['Pig'/114520, l='MpServer', x=718.75, y=4.00, z=348.59], EntityHorse['Horse'/114267, l='MpServer', x=589.50, y=4.00, z=346.50], EntityChicken['Chicken'/114266, l='MpServer', x=582.50, y=4.00, z=345.50], EntityPig['Pig'/114522, l='MpServer', x=717.34, y=4.00, z=359.69], EntityHorse['Horse'/114269, l='MpServer', x=591.50, y=4.00, z=352.50], EntitySlime['Slime'/640853, l='MpServer', x=722.21, y=4.69, z=207.83], EntityHorse['Horse'/114268, l='MpServer', x=587.50, y=4.00, z=351.50], EntityCow['Cow'/114271, l='MpServer', x=713.75, y=4.00, z=224.44], EntityHorse['Horse'/114270, l='MpServer', x=593.50, y=4.00, z=351.50], EntityCow['Cow'/114273, l='MpServer', x=712.50, y=4.00, z=230.50], EntityCow['Cow'/114272, l='MpServer', x=719.84, y=4.00, z=232.06], EntityChicken['Chicken'/114275, l='MpServer', x=714.44, y=4.00, z=231.34], EntityCow['Cow'/114274, l='MpServer', x=715.44, y=4.00, z=230.91], EntityChicken['Chicken'/114277, l='MpServer', x=708.50, y=4.00, z=231.50], EntityChicken['Chicken'/114276, l='MpServer', x=710.50, y=4.00, z=228.50], EntityCow['Cow'/114279, l='MpServer', x=712.50, y=4.00, z=217.50], EntityChicken['Chicken'/114278, l='MpServer', x=706.47, y=4.00, z=230.59], EntityCow['Cow'/114281, l='MpServer', x=715.50, y=4.00, z=215.50], EntityCow['Cow'/114280, l='MpServer', x=715.50, y=4.00, z=217.50], EntityChicken['Chicken'/114283, l='MpServer', x=603.44, y=4.00, z=359.41], EntityCow['Cow'/114282, l='MpServer', x=713.50, y=4.00, z=214.50], EntityChicken['Chicken'/114285, l='MpServer', x=603.44, y=4.00, z=340.56], EntityChicken['Chicken'/114284, l='MpServer', x=598.25, y=4.00, z=349.22], EntitySheep['Sheep'/114287, l='MpServer', x=590.03, y=4.00, z=357.09], EntityChicken['Chicken'/114286, l='MpServer', x=593.50, y=4.00, z=345.50], EntitySlime['Slime'/624742, l='MpServer', x=580.88, y=4.00, z=336.11], EntitySheep['Sheep'/114289, l='MpServer', x=604.50, y=4.00, z=352.50], EntitySlime['Slime'/420470, l='MpServer', x=697.66, y=4.02, z=259.62], EntitySheep['Sheep'/114288, l='MpServer', x=599.19, y=4.00, z=350.22], EntityPig['Pig'/114291, l='MpServer', x=602.03, y=4.00, z=346.09], EntitySheep['Sheep'/114290, l='MpServer', x=603.50, y=4.00, z=354.50], EntityPig['Pig'/114293, l='MpServer', x=600.81, y=4.00, z=346.69], EntityPig['Pig'/114292, l='MpServer', x=601.50, y=4.00, z=343.50], EntitySheep['Sheep'/114295, l='MpServer', x=604.25, y=4.00, z=295.47], EntitySlime['Slime'/624255, l='MpServer', x=583.50, y=4.02, z=338.37], EntityPig['Pig'/114294, l='MpServer', x=602.06, y=4.00, z=350.16], EntitySheep['Sheep'/114297, l='MpServer', x=594.21, y=4.00, z=284.31], EntitySheep['Sheep'/114296, l='MpServer', x=603.06, y=4.00, z=295.41], EntityPig['Pig'/114299, l='MpServer', x=609.50, y=4.00, z=303.50], EntitySheep['Sheep'/114298, l='MpServer', x=607.47, y=4.00, z=296.38], EntityPig['Pig'/114301, l='MpServer', x=610.81, y=4.00, z=301.50], EntityPig['Pig'/114300, l='MpServer', x=609.22, y=4.00, z=301.50], EntitySlime['Slime'/380280, l='MpServer', x=636.97, y=4.00, z=205.28], EntitySlime['Slime'/671095, l='MpServer', x=601.21, y=4.00, z=304.09], EntityChicken['Chicken'/114303, l='MpServer', x=606.81, y=4.00, z=297.78], EntityPig['Pig'/114302, l='MpServer', x=610.50, y=4.00, z=304.97], EntityChicken['Chicken'/114305, l='MpServer', x=602.22, y=4.00, z=295.47], EntitySlime['Slime'/244611, l='MpServer', x=634.00, y=5.00, z=312.51], EntityChicken['Chicken'/114304, l='MpServer', x=604.50, y=4.00, z=293.50], EntityChicken['Chicken'/114306, l='MpServer', x=607.50, y=4.00, z=294.50], EntitySlime['Slime'/270722, l='MpServer', x=629.78, y=4.00, z=248.03], EntitySlime['Slime'/416652, l='MpServer', x=649.13, y=4.00, z=302.63], EntitySlime['Slime'/685952, l='MpServer', x=715.50, y=4.00, z=353.50], EntitySlime['Slime'/660615, l='MpServer', x=596.01, y=4.60, z=320.28], EntityChicken['Chicken'/114319, l='MpServer', x=722.59, y=4.00, z=321.56], EntityChicken['Chicken'/114321, l='MpServer', x=730.50, y=4.00, z=326.50], EntityChicken['Chicken'/114320, l='MpServer', x=725.56, y=4.00, z=319.63], EntityCow['Cow'/114323, l='MpServer', x=716.13, y=4.00, z=330.13], EntitySlime['Slime'/240785, l='MpServer', x=703.14, y=4.60, z=270.58], EntityChicken['Chicken'/114322, l='MpServer', x=732.66, y=4.00, z=331.72], EntityCow['Cow'/114325, l='MpServer', x=717.97, y=4.00, z=324.56], EntitySlime['Slime'/440722, l='MpServer', x=610.32, y=5.04, z=222.27], EntityCow['Cow'/114324, l='MpServer', x=723.81, y=4.00, z=326.31], EntityCow['Cow'/114327, l='MpServer', x=722.47, y=4.00, z=323.16], EntityCow['Cow'/114326, l='MpServer', x=722.81, y=4.00, z=325.16], EntitySlime['Slime'/566687, l='MpServer', x=735.50, y=4.00, z=336.75], EntityCow['Cow'/114329, l='MpServer', x=720.72, y=4.00, z=329.06], EntityCow['Cow'/114328, l='MpServer', x=723.19, y=4.00, z=327.50], EntityCow['Cow'/114330, l='MpServer', x=719.09, y=4.00, z=322.97], EntityChicken['Chicken'/114333, l='MpServer', x=723.94, y=4.00, z=207.13], EntityChicken['Chicken'/114332, l='MpServer', x=728.31, y=4.00, z=204.66], EntitySheep['Sheep'/114339, l='MpServer', x=725.34, y=4.00, z=205.78], EntitySheep['Sheep'/114341, l='MpServer', x=722.56, y=4.00, z=217.75], EntitySheep['Sheep'/114340, l='MpServer', x=723.16, y=4.00, z=211.59], EntitySheep['Sheep'/114342, l='MpServer', x=721.75, y=4.00, z=210.28], EntitySlime['Slime'/214959, l='MpServer', x=678.69, y=4.85, z=251.09], EntitySlime['Slime'/629936, l='MpServer', x=595.43, y=4.00, z=287.28], EntitySlime['Slime'/584372, l='MpServer', x=707.48, y=5.06, z=290.27], EntityPig['Pig'/114368, l='MpServer', x=577.91, y=4.00, z=205.78], EntityPig['Pig'/114375, l='MpServer', x=577.94, y=4.00, z=208.78], EntitySlime['Slime'/241861, l='MpServer', x=589.84, y=4.00, z=234.46], EntitySlime['Slime'/299980, l='MpServer', x=611.93, y=4.47, z=223.63], EntityHorse['Horse'/114381, l='MpServer', x=581.88, y=4.00, z=204.19], EntitySlime['Slime'/448982, l='MpServer', x=587.34, y=4.00, z=274.03], EntityCreeper['Creeper'/567002, l='MpServer', x=735.59, y=4.00, z=357.00], EntitySlime['Slime'/31206, l='MpServer', x=708.25, y=4.00, z=329.31], EntitySlime['Slime'/33767, l='MpServer', x=646.17, y=4.61, z=275.11], EntitySlime['Slime'/151286, l='MpServer', x=574.53, y=4.00, z=215.31]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 361842800 bytes (345 MB) / 738197504 bytes (704 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	DragonAPI{v31b} [DragonAPI] (DragonAPI+1.7.10+V31b.jar) 
	UCHIJAAAA	RotaryCraft{v31b} [RotaryCraft] (RotaryCraft+1.7.10+V31b.jar) 
	UCHIJAAAA	ElectriCraft{v31a} [ElectriCraft] (ElectriCraft+1.7.10+V31a.jar) 
	UCHIJAAAA	ReactorCraft{v31b} [ReactorCraft] (ReactorCraft+1.7.10+V31b.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.15' Renderer: 'NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.15, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by ReikaKalseki** [comment]
#3006
