### ISSUE TITLE
Dye Vines "eat" blocks (Chromaticraft V31B)

### ISSUE THREAD

**Issue by Milii20** [ReikaKalseki/Reika_Mods_Issues#3019]
Greetings! 

I was just randomly checking my base, and found out the dye vines that grow from Chromaticraft's trees can eat blocks, and even worst, they can eat gearboxes, which kinda renders Rotarycraft's woodcutters useless for a berry farm

![2022-04-21_09 35 02](https://user-images.githubusercontent.com/10578092/164459384-a20eee3f-2b5e-4885-a012-e4eb9a247154.png)

Thank you for your time

**Comment by ReikaKalseki** [comment]
Fixed.
