### ISSUE TITLE
Mined blocks do not update the light Level of the below block (Dragon API V31B)

### ISSUE THREAD

**Issue by ThyUnsuspicious** [ReikaKalseki/Reika_Mods_Issues#3020]
Hello! I happened to notice your mods had updated since March and decided to try out the newer versions. However, upon replacing the older files with the updated versions and creating a new world, any blocks mined appear to fail to "update" the below block's light level. According to Walia, the Light Level of said blocks is 0. This does not update unless I close the world and re-open it; no amount of torches or blocks placed to "force" an update work. I'm not sure what to do. This bug only seems to happen with the newest version of Dragon Api (V31B). I was planning on verifying if an older version would work (the older one I still have, V29G, has no such issue), but I was unable to find another version publicly available besides the current. 

_Below: picture of sand where the above layer has been mined_

![2022-04-22_22 33 06](https://user-images.githubusercontent.com/104242803/164873646-f50bd9ab-210e-4c8a-8cd0-2e677fa7b549.png)

_Placing a light source nearby will temporarily fix the issue, but when broken, the issue returns._

![2022-04-22_22 33 28](https://user-images.githubusercontent.com/104242803/164873672-478285a8-a8d2-4c2e-9c6a-21a02272b027.png)

![2022-04-22_22 33 36](https://user-images.githubusercontent.com/104242803/164873699-fb2d8a31-d034-4e4f-bf2f-b69741102c58.png)

Once a single block is broken or placed in the world and said glitch occurs, there is about a 2-3 minute timer before the world completely desyncs. Anything I do is no longer logged in the console (playing on AT Launcher), the world does not save on opening the pause menu, etc. Everything freezes. After a while, the game will crash with no crash report because Java apparently couldn't take it anymore, I guess?

Any help would be much appreciated! I'd like to get back into Chromaticraft and other 1.7.10 mods, but this bug is super demoralizing.

**Comment by ReikaKalseki** [comment]
This is not my doing - I do not touch this kind of thing, and very similar errors are widespread even in vanilla.
