### ISSUE TITLE
[Dragon API] Crash when launching with TerraFirmaCraft+

### ISSUE THREAD

**Issue by Jerome226** [ReikaKalseki/Reika_Mods_Issues#3024]
Dragon API seems to conflict with TFC+ when launched together, here the log: 
[crash-2022-04-26_17.01.54-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/8567102/crash-2022-04-26_17.01.54-client.txt)
I'm not sure if it's Dragon API or TFC+ fault, but since TFC+ is still supported there probably a way to make it work

**Comment by ReikaKalseki** [comment]
This is an ASM conflict. Ping them here so the patches can be discussed.

Also, #2396 is very closely related.

**Comment by ReikaKalseki** [comment]
> Also, https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2396 is very closely related.

In fact it is the same.
