### ISSUE TITLE
[Chromaticraft] Crystal Orchestra Improvement Suggestions

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#3025]
1: Use a dedicated folder within the instance that midis can be placed in, so the whole path doesn't have to be typed out. Lesser importance.

2: The block shouldn't require Silk Touch to harvest, especially considering how early it can be crafted. Maybe have to shift-right-click with the Manipulator to pick it up instead if you don't want it to be mined normally? If you're set on Silk Touch only, then other forms of Silk Touch other than just Vanilla should work.

3: The fragment in the Lexicon really needs to mention the ring of crystal lamps SOMEWHERE. Either on another page, or even add a structure page for it if you have to, especially considering the precise order the colors need to be in.

4: The buttons in the UI should have tooltips, or the book should say what they do. The musical ones on the right side are clear enough, it's the ones on the left, and the colors along the bottom, that are unclear.

5: A way to export a custom song created in the orchestra. Maybe create a midi file? Not sure.

6: Perhaps a way to have more than one midi loaded, and then the player can select from a list instead of having to put in the whole file path each time. Alternative: two boxes. One sets the folder path, the other just sets the file name. The folder path wouldn't be cleared upon closing the UI.

7: A way to stop playback once started. Currently, a redstone signal merely starts playback. What if it only played when powered, so turning off the Orchestra stopped the music?

It's very fun to play around with this thing, it's just a bit frustrating to figure out how it works the first time.

**Comment by ReikaKalseki** [comment]
1 is flatly rejected - I want them able to load from anywhere on the filesystem.

5 Exporting a MIDI is much harder than reading one, and I cannot guarantee that the conversion is lossless, either. And I think the RC music disc works with them.

6 This is not useful enough to be worth the effort or NBT space.

**Comment by ReikaKalseki** [comment]
Someone else asked for relative paths recently, and I looked at the code - you *can* give them relative paths, but I have no idea what the home path would be.

Also, since this was submitted, 7 was added and 3 has the hint FX. The lexicon was also updated.
