### ISSUE TITLE
[Chromaticraft] Crystal Orchestra Bugs

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#3026]
1: Sometimes after loading a midi, the Esc key stops working and the UI cannot be closed. Going in and out of the midi loading part of the UI a couple of times seems to fix it. Inconsistent.

2: The loading UI says to use / but the paths only work when using the normal \. See attached image below. The path shown for that file does work.

3: As per discussion on Discord, not all midi files work, based on some criteria that I do not fully understand but I include it here for completion's sake.

![2022-04-27_10 18 07](https://user-images.githubusercontent.com/6917535/165583502-6b960b92-93e3-4bc3-8555-726c2e3b3e50.png)

**Comment by ReikaKalseki** [comment]
None of your listed issues have happened for me.
