### ISSUE TITLE
[Chromaticraft] Fragments revealing themselves before all requirements are met

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#3027]
The Nether Layer Crystal fragment revealed itself, but the item itself was still obfuscated. Not sure what was missing, yet.

The Suspension Field Controller revelead before one of the ingredients, making it rather difficult to actually make it. The item appears to be an ore, so this fragment should be gated after whatever progression also reveals that ore.

Should be simple enough to shift things around into the proper order, I'd imagine.

![2022-04-27_22 12 03](https://user-images.githubusercontent.com/6917535/165683735-52fdf139-58c4-4314-9edc-a33f605f58df.png)
![2022-04-27_22 34 48](https://user-images.githubusercontent.com/6917535/165683737-0ed0814a-a597-4d72-a79d-4c8f3756b01d.png)

**Comment by ReikaKalseki** [comment]
This is not abnormal, and not a big enough problem to warrant the total restructuring of the progression system.
