### ISSUE TITLE
Cannot extract dusts from Isotope Centrifuge

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [ReikaKalseki/Reika_Mods_Issues#3029]
I know this used to work without issue, but for the life of me I cannot get anything to extract dusts from the side of the Isotope Centrifuge.

Ive tried the AE2 import bus, Thermal Expansion item ducts, and Rotarycraft Item Vacuums. Nothing works anymore.

Am I seriously missing something here or is this a Bug?

All your mods are current.  I just triple checked versions.

EDIT : Also tried the Extra Utilities item movers to no avail.

Test Setup
![2022-05-02_13 30 08](https://user-images.githubusercontent.com/10451525/166295777-fa01749a-e38c-48d4-aade-0cb4785f05bd.png)

Block Inventories
![2022-05-02_13 31 56](https://user-images.githubusercontent.com/10451525/166296429-a4bdfe31-a7df-495f-a0d2-51709c1ffc98.png)
![2022-05-02_13 31 51](https://user-images.githubusercontent.com/10451525/166296450-d1e241fb-ee04-4923-a0ad-f3dd781b54b7.png)
![2022-05-02_13 31 46](https://user-images.githubusercontent.com/10451525/166296470-43a2c809-6ad4-43c6-afde-05fb1900f8f3.png)
![2022-05-02_13 31 53](https://user-images.githubusercontent.com/10451525/166296486-8fe4598e-d8ff-40cd-9ccc-6f5b7bf7eebf.png)

As is apparent, nothing is moving.

**Comment by Holorizor** [comment]
I tried it also, and the only way i find to extract stuff in an automated way is below, but there is the energy input. Seems like a problem to me too

**Comment by MachiavelliSeraphim** [comment]
Thanks for confirming.
That leads me to believe its a typo in code/bug.
It used to work correctly.  
Hopefully something easily fixed.
Ive made workarounds in the mean time.... lol.

**Comment by ReikaKalseki** [comment]
I changed the sided logic in late December, but I had it working automatically just fine. Items are extracted from the top.

**Comment by MachiavelliSeraphim** [comment]
So I assume the hexafluoride is then piped in from the side now?

Ill test later today.

Thanks.

**Comment by MachiavelliSeraphim** [comment]
It appears that the only side that can Input or Extract from the centrifuge is the top.

I assume by your earlier comment, that this is correct and intended?

Thanks.

**Comment by rkane31174** [comment]
I don't know what the intention behind this change is.
If items are extracted from the top and fluids are inserted into the top, then both cannot be done at once.
Unless there's a mechanism for simultaneously inserting fluids and removing items from the same location, then it's impossible to fully automate this machine. Is this the desired outcome?

**Comment by Holorizor** [comment]
I used a hopper-minecart below the centrifuge inside the bevel gear to extract the products of the isotope centrifuge. Yes it is not the intended way but i found so far no other way to pump in gas from the top and at the same time pump the products out.

**Comment by rkane31174** [comment]
Good idea. EnderIO works too, since it allows insertion and extraction from the same face.

**Comment by MachiavelliSeraphim** [comment]
I would honestly like a snapshot of how Reika automates some of these things.  
Either Im totally missing some secret functions of some of his stuff, or hes using some mods very creatively.

**Comment by chotke** [comment]
Did you try Steve's Factory Manager?
