### ISSUE TITLE
[DragonAPI][v9b][ModInteraction][ASM]PotionEffect ASM conflict with PotionIDHelper

### ISSUE THREAD

**Issue by Modbder** [ReikaKalseki/Reika_Mods_Issues#303]
Hello. I've encountered a rather interesing problem with the way DragonAPI's ASM interacts with PotionIDHelper's ASM. You both modify the same methods in PotionEffect.class - readCustomPotionEffectFromNBT and writeCustomPotionEffectToNBT. The problem is - PotionIDHelper modifies those methods in a way, that it always writes 0 as a potion ID, but it instead will write and read a custom SHORT called ExtendedID as potion ID. It works fine, unless you add DragonAPI. With DragonAPI you always end up getting a potion effect with ID 0 - since the id is exactly 0 due to PotionIDHelper's modification. 

PotionIDHelper's modifications:
https://github.com/brandon3055/PotionIDHelper/blob/master/src/main/java/com/brandon3055/potionidhelper/asm/ClassTransformer.java#L43
https://github.com/brandon3055/PotionIDHelper/blob/master/src/main/java/com/brandon3055/potionidhelper/asm/MethodHolder.java#L26

Your modification:
https://github.com/ReikaKalseki/DragonAPI/blob/master/ASM/DragonAPIClassTransfomer.java#L229

Maybe you could check if the PotionIDHelper is installed and... I do not know... Do something? :D

Anyway, if you feel like it is a fault of PotionIDHelper feel free to close the issue - I will report it to brandon3055 then.

**Comment by ReikaKalseki** [comment]
I find his solution incredibly hacky and vulnerable to other problems.

But in that transformer I only delete the byte casts. That should not affect anything on its own.

**Comment by Modbder** [comment]
Could this happen because DragonAPI does it's modifications first, and changes the writeByte and readByte in the packet handler to writeInt and readInt, and since PotionIDHelper is looking for a method node with name writeByte and readByte (which no longer exist because of DragonAPI) - it can't modify them to readShort and writeShort the packet handler tries to read integer(which is 0 for ID), and is not reading short, which defaluts to 0 and PotionIDFix in it's readCustomPotionEffectFromNBT reads 0 as ID anyway? 

EDIT: links:
PotionIDHepler:
https://github.com/brandon3055/PotionIDHelper/blob/master/src/main/java/com/brandon3055/potionidhelper/asm/ClassTransformer.java#L256

DragonAPI:
https://github.com/ReikaKalseki/DragonAPI/blob/master/ASM/DragonAPIClassTransfomer.java#L300

**Comment by ReikaKalseki** [comment]
I will just make the ASM not run if his mod is present, as anything else is going to be a headache.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by ReikaKalseki** [comment]
And adding the Loader.isModLoaded() test causes a crash with LiteLoader.

He is going to need to add something on his end, because I am unable to do so on mine.
