### ISSUE TITLE
Satisforestry biome gen error ("Bound must be positive")

### ISSUE THREAD

**Issue by CPSRYAN** [ReikaKalseki/Reika_Mods_Issues#3030]
Satisforestry has caused the same error a few times in different chunks of satisforestry biomes. Seems to be the same error as #2968 
Crash caused by error during chunk gen, random gen seems to be getting an illegal value (negative?)
Here are two crash reports for comparison (Pastebinned for neatness)
https://pastebin.com/9TRdKNEU
https://pastebin.com/hZVXeipN
Full mod list can be found in crash report
Any tips on having better world gen would be appreciated
Any suggested mods would be nice, Reika :)
Also no idea why bedrock is flat in overworld and nether, should have default world gen, I don't understand condensed ores I am smooth brain :(

**Comment by ReikaKalseki** [comment]
There has not been a release since this fix was implemented.

> Also no idea why bedrock is flat in overworld and nether, should have default world gen, I don't understand condensed ores I am smooth brain :(

CondensedOres does not touch bedrock.

**Comment by CPSRYAN** [comment]
Right, I thought this was the case but decided it would be best to report it anyway. Also yes, I realise condensed ores doesn't touch world gen, I was making another point sorry I should have been clearer. I still have no idea why there is flat bedrock, I was hoping it might be a chromaticraft thing, what with the bedrock from the nether roof.
