### ISSUE TITLE
[Chromaticraft] Crash when Modlist changes

### ISSUE THREAD

**Issue by antrobot1234** [ReikaKalseki/Reika_Mods_Issues#3032]
Whenever I add or remove a mod, the game will crash the first time I try to run it. After that, however, it runs fine.

[HERE](https://pastebin.com/ZAhrVvU3) this is the crash log

**Comment by ReikaKalseki** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1732 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1683 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1681 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1493 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1257 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1280 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1238 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2390 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1848 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1985 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2419 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2502 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2595 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2903

**Comment by OvermindDL1** [comment]
It is not a bugged AE version or a misset AE config, AE2 is performing things properly, something in ChC is not instancing items completely and fully in preinit.
