### ISSUE TITLE
Rtoarycraft machines not accepting enchantments

### ISSUE THREAD

**Issue by Riyshn** [ReikaKalseki/Reika_Mods_Issues#3033]
Rotarycraft machines that are intended to be enchantable (or at least, the Woodcutter and Boring Machine. Couldn't think of any others to test.) aren't accepting any enchantments other than Soulbound. Checking them through both the Chromaticraft Chromatic Enchanter and NEI's enchantment info page, both seem to agree on this (all other enchantments in the Enchanter show as the "not applicable to this item" yellow text, and nothing else listed in NEI).

All mods installed are v31b.

Not sure if it's helpful, but at a guess, the first things that stand out as possibly related recent changes are
"Enchanter can now process any tool- or weapon-type item (including function stars, RC spring-powered, TiC, TC wands, and more) for some enchants (eg soul-bound)"
and
"All spring-powered tools now accept soulbound"
from v31a.

**Comment by Holorizor** [comment]
Hello,

in the ingame rotarycraft handbook ist a section about enchanting the machines. There you can find, which machines, and what kind of enchantment can be applied via an enchanment book. simple use the correct enchantment book with right click on the machine.

**Comment by Riyshn** [comment]
...well I feel like an idiot now. Could have sworn I remember being able to directly enchant them in the last world I played with Rotarycraft.
