### ISSUE TITLE
[RotaryCraft] Unable to add Thaumcraft native clusters to RotaryCraft_CustomExtracts.cfg

### ISSUE THREAD

**Issue by elijahlorden** [ReikaKalseki/Reika_Mods_Issues#3034]
I am attempting to add Thaumcraft 4's Native Clusters to the Extractor such that the smelted flakes would produce two iron ingots.  I have no clue what I'm doing wrong here, but for some reason the smelted flakes are producing iron ore (and only one, shouldn't it produce two?), as shown in the screenshot.

Config line (ignore the color): Iron Cluster, SCARCE, Ingot, ingotIron, 2, 0xffffff, 0xffffff, IRON, clusterIron

Extractor recipe in NEI:
![image](https://user-images.githubusercontent.com/13923468/168456366-fe301430-2ae1-4f2a-a7a1-502105fb9135.png)

Flake smelting result in NEI:
![image](https://user-images.githubusercontent.com/13923468/168456383-3d036983-bf13-4788-8634-b421b59c6339.png)

**Comment by ReikaKalseki** [comment]
No, flake smelting only produces one, and the reason it is producing iron ore is that the native-ore system makes it produce the same thing the ore does, not what it smelts to. That said, I am not sure that is a good idea, so I have changed it.
