### ISSUE TITLE
[ChromatiCraft] (v31b) Inventory Network Relay crashes when you click a slot

### ISSUE THREAD

**Issue by mhansen718** [ReikaKalseki/Reika_Mods_Issues#3036]
Specifically the slots on the right side.

The crash report points to [this function,](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Container/ContainerNetworkItemTransporter.java#L54) and says that it can't find the GuiScreen class.
[crash-2022-05-17_21.27.57-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/8712586/crash-2022-05-17_21.27.57-server.txt)

**Comment by ReikaKalseki** [comment]
I am not sure how it took a full 18 months for someone to find this issue...

**Comment by ReikaKalseki** [comment]
Fixed.
