### ISSUE TITLE
[Chromaticraft] Biome ID crash in dimension

### ISSUE THREAD

**Issue by Riyshn** [ReikaKalseki/Reika_Mods_Issues#3037]
https://pastebin.com/bsrGZXW8
https://pastebin.com/8c4TG78q

Consistant crash in the dimension. Crash occurs ~30sec-2min after loading in. After multiple round of crashes (all gave one of the two reports above), finally resorted to going into Creative to dig straight down to leave dimension before the next crash.

**Comment by FavoritoHJS** [comment]
Seems to be related to #2962.
