### ISSUE TITLE
[ChromatiCraft, DragonRealm] Research Fragments cause a crash in multiplayer.

### ISSUE THREAD

**Issue by FavoritoHJS** [ReikaKalseki/Reika_Mods_Issues#3038]
Trying to research a research fragment causes a game crash if on a multiplayer server.
[crash-2022-05-28_00.17.03-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/8847694/crash-2022-05-28_00.17.03-client.txt)

This seems to be caused due to the new fragment UI that will be added in v32.

I think [this](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/GUI/GuiFragmentSelect.java#L240-L246) is the problematic code:
```java
                   [...]
/*240*/            Selection s = GuiFragmentSelect.this.getContainer().getOption(id);
                   [snip]
/*246*/            s.fragment.drawTabIcon(itemRender, (int)(xPosition/sc), (int)(yPosition/sc));
                   [...]
```
It might be possible that `s` is null in a multiplayer server, especially since it seems to be dependant on the contents of the container, which might be ever-so-slightly desynced. Further research is needed.

This was tested on the latest version of [DragonRealm](https://dragonrealm.overminddl1.com/), with the following mods added: Ars Magica, Advanced Botany, AM2PlantFix and AnimationAPI. I doubt any of these would cause the crash, though.

**Comment by DarkAhri** [comment]
Do you know how to research the  fragment in V32a ? It's different from V31.

**Comment by FavoritoHJS** [comment]
Right-click the research fragment to open up an UI.
Place the fragment on the top slot
3 buttons will appear below with hints of what you will get.
Click on one of those to research.

**Comment by DarkLei** [comment]
> Right-click the research fragment to open up an UI. Place the fragment on the top slot 3 buttons will appear below with hints of what you will get. Click on one of those to research.
THX!

**Comment by DarkAhri** [comment]
THX! Helpful!

**Comment by FavoritoHJS** [comment]
I imagine instructions would have appeared in a tooltip/lexicon entry... if Reika didn't abandon his MC mods, again, again.

Don't worry, he'll be back... eventually... I hope...

**Comment by ReikaKalseki** [comment]
The feature was half-implemented.
