### ISSUE TITLE
[NonCritical] Mineral Extractor eats cpu cycles when nobody is looking.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#304]
So under certain circumstances the mineral extractor will use an additional ~20ms while scanning (i7-3630QM mobile cpu):
1) Place Mineral Extractor (MiEx) in non-overworld (tested in aroma1997's mining dim).
2) Place Immibis Dimensional Anchor set to force load 1x1 chunks in same chunk as MiEx.
3) Leave the dimension, go back to overworld.
4) The scan will take about 90 seconds.
= The dimension will use an extra 10ms (or 20ms with speed module) which it doesn't use if I stand right next to the extractor during the scan.

**Comment by ReikaKalseki** [comment]
Wait...are you saying it accelerates when noone is near?

**Comment by lossycrypt** [comment]
That's what i thought at first, and it does seem to be very slightly (10%ish, aka might be measurement error) faster, but otherwise it seems to just randomly use a lot more cpu cycles compared to standing right next to it during the scan.

**Comment by ReikaKalseki** [comment]
That would probably be chunkloading related. Every time it queries a block at a position, the chunk needs to be unloaded. It will then unload the next tick (but be loaded again shortly by the MiEx).

The only fix for this is to make the MiEx a very wide-range chunkloader, at least while it is scanning and mining. I am willing to do this, though it is somewhat difficult to implement.

**Comment by lossycrypt** [comment]
The Ender Quarry from Extra Utilities has a rather neat implementation for this. It forceloads one chunk, completely mines that, and then unloads the chunk and continues with the next one. That way only one additional chunk is loaded at any one time. This could be used for both scanning and mining.

(Forgot to mention in the first post btw, that during actual mining the MiEx consumes about 2ms, i guess because it's mining much slower than scanning.)

**Comment by ReikaKalseki** [comment]
Fixed.
