### ISSUE TITLE
Performace issue inside chromaticraft structure generation

### ISSUE THREAD

**Issue by jonab03** [ReikaKalseki/Reika_Mods_Issues#3041]
When doing some performace investigation in visualVM I noticed that your structure generation code in chromaticraft gets the path to something (the save folder?) every time it updates the noise maps. 

In my profiling (See [With Reika.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/8884740/With.Reika.zip)) this takes ~13% of the total CPU time and from looking at the code the result of these operations shouldn't be different unless you load a different world.

Would it be possible to do this check once at world load and avoid doing it constantly?

**Comment by ReikaKalseki** [comment]
This was fixed in v32b with #3167.
