### ISSUE TITLE
[ReactorCraft] Crash upon retracting/lowering control rods via central control.

### ISSUE THREAD

**Issue by Konrad-Wszelaki** [ReikaKalseki/Reika_Mods_Issues#3044]
I was attempting to test a fission reactor that I have build in my world and the game keeps crashing with a null pointer exception when I move the control rods. The rods themselves do actually move and are in the new position upon launching the game and loading the savefile. The crash happens no matter if the rods are moved together or individually.

I tested whether the issue is connected to some other mods by creating a fresh instance of minecraft with only ReactorCraft, RotaryCraft, DragonAPI, and the newest version of forge available for 1.7.10 (10.13.4.1614) installed, and the issue exists even on this fresh instance.

Here's the test setup for the reactor in the fresh instance, in case I'm just missing something:
![2022-06-16_10 44 00](https://user-images.githubusercontent.com/58418997/174032688-cb60f25f-5585-4055-8e60-3b0e6dbfacc3.png)

The game crashes even with just 1 control rod connected to the central control (the presence of fuel cores does not actually make any difference).
The game does not crash if I remove all control rods and click on either button in central control GUI.
The game also does not crash if the control rods are there but they don't actually move (e.g.: I try to retract them when they are already fully retracted)

And here's the crash report (from the fresh instance, since other mods don't seem to be an issue):
https://pastebin.com/BDMAWdVi

**Comment by Herebedragons1** [comment]
I don't think Rika is working on the mod anymore as the mod hasn't been updated since 2021 so you may need to use an older version of reactor craft and it's required mods

**Comment by ReikaKalseki** [comment]
#3006
