### ISSUE TITLE
[ChromatiCraft] Aura Pouch Item Dupe/Loss

### ISSUE THREAD

**Issue by SteeleJr98** [ReikaKalseki/Reika_Mods_Issues#3045]
Clicking the aura pouch in your inventory while it's open closes the pouch without updating the items within allowing duplication of items and loss of items.
Loss: Placing and item in the pouch and force closing it will cause the item to be lost.
Dupe: Taking an item from the pouch and force closing it will cause you to keep the item taken out with it still being in the pouch after picking it back up.

Video of the dupe/loss taking place: https://youtu.be/EKPMOce_XjM

ChromatiCraft version: 1.7.10 V31b
Modpack: Pagemaster-1.3.8

**Comment by Shibva** [comment]
Can confirm this bug; my guess is because of how it waits till the container is closed before it updates it's contents

**Comment by ReikaKalseki** [comment]
This was triggered by the - comparatively new - recursive pouch config enabling bypassing some safety code. This was only fixable by removing that ability.
