### ISSUE TITLE
ChromatiCraft dumping the entire contents of any tool compression crates into the log

### ISSUE THREAD

**Issue by jonab03** [ReikaKalseki/Reika_Mods_Issues#3049]
When loading a chunk containing a tool compression crate it''s entire contents are serialized and placed in the log. [Example Log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/9002080/fml-client-latest.log)

This is a very minor issue but it would be nice to not have it dumping it's data in the log as it gets rather large.

**Comment by ReikaKalseki** [comment]
This was old debug code that was removed long ago.
