### ISSUE TITLE
RotaryCraft Music Box throws errors when placed

### ISSUE THREAD

**Issue by Solidflip** [ReikaKalseki/Reika_Mods_Issues#305]
When i placed the music box from RotaryCraft in the world i got this error: http://pastebin.com/S0FU2Rek

I updated to the latest version of your mods hoping it would fix, however i got the same error:
http://pastebin.com/EWtEFQXC

This is all that pops in the console when the block is placed nothing else. (the log is full of us spawning in items as were testing mods out so thats why its not the full log) This doesnt cause anyone to crash or anything, but wanted to report it anyway and i didnt see a topic about this in the github.

**Comment by ReikaKalseki** [comment]
The music box save system needs a rewrite...

**Comment by Solidflip** [comment]
Sounds like loads of fun, It wouldnt be against the perms to disable placing of this block to prevent console spam as it isnt a part of progression then correct?

**Comment by ReikaKalseki** [comment]
Correct, though all spam is entirely clientside and thus of no concern.

**Comment by Solidflip** [comment]
Awesome thanks, Also the spam goes into the server console as well, not sure if that helps but it isnt just client side. Not a modder so idk what helps and what doesnt. =)

**Comment by ReikaKalseki** [comment]
> Also the spam goes into the server console as well

Oh...

**Comment by ReikaKalseki** [comment]
Fixed...hopefully.
