### ISSUE TITLE
[ChromatiCraft] Data Nexuses can be overwritten by other mods

### ISSUE THREAD

**Issue by jonab03** [ReikaKalseki/Reika_Mods_Issues#3050]
In my case it happened with Matter Overdrive ![image](https://user-images.githubusercontent.com/57867790/177572725-4005a333-7269-49fe-a5fc-660574396f03.png)

My first instinct was to fix Matter Overdrive however this might not be an isolated issue with just that mod as I have observed other mods behaving similarly on various structures.

While this might not strictly be a bug in ChromatiCraft I though it would be best to let you know as you are in the best position fix this for all mods.

While implementing a fix in Matter Overdrive [\(see here\)](https://github.com/jonab03/MatterMegadrive/commit/87b71d4c7e6531e34d9a42971c3346d7ab3465d6) I found that the core (chroma.datanode) is destructible which prevented a simple fix via an hardness check from working. Is this necessary or could it be made indestructible?

**Comment by ReikaKalseki** [comment]
I can rather easily prevent the TE blocks themselves from being overwritten but there is nothing I can do to prevent the others.

**Comment by ReikaKalseki** [comment]
I also added some code to make worldgenned TE blocks rebuild their structure if it is missing, further helping this issue.
