### ISSUE TITLE
[ChromaticCraft Feature Suggestion] Adding a casting table level to multiblock and item tooltips

### ISSUE THREAD

**Issue by Shibva** [ReikaKalseki/Reika_Mods_Issues#3053]
Hi, I've been learning how this mod work and testing it out in creative; for some reason, the structure for a next-level casting room was not forming and I was wondering what I was doing wrong, it was only when I found some old helpful videos on V19 that I learned that its only accepts tables that have a level requirement

tbh, I was a bit annoyed but then I thought; "why doesn't it show up in the structure preview with the book?"

my suggestion: whenever you have a casting table, it will also show the level that it's at within the tooltip, just like how it shows stored chroma. The same could also be done when hovering over it in the multiblock menu to show emphasis on the table needed such as "lv 2 or greater required'. that way such confusion can be avoided in the future by newcomers like me.

**Comment by Shibva** [comment]
![image](https://user-images.githubusercontent.com/38770780/179145928-65190682-e649-41a2-9517-4951fd1495a4.png)
this is an example of the idea, made possible using CraftTweaker and its ability to add tooltips to stuff with specific NBT tags

**Comment by ReikaKalseki** [comment]
I added the tooltip.
