### ISSUE TITLE
[Chromaticraft Suggestion] QoL improvment to Crystal Orchistra File grabing + message

### ISSUE THREAD

**Issue by Shibva** [ReikaKalseki/Reika_Mods_Issues#3055]
The idea is simple; I noticed that chromaticraft adds its file inside of the mods folder; I thought what if it also generated a sound file for custom midi for the orchestra?

what it could do is that files in this folder can be pulled by just typing the name acting as a default path
(ie, typing MidiFileName.mid would tell it to look into that folder; while the long path name system can still be used as well)

it's a QoL suggestion. It also is nice if within that file there can be more specifications on what type of files it will accept (because some midi files I have don't work, though I understand its caused by limitations or something)

Final note: IDC if this mod never gets ported to a newer version; the visuals in this mod are over-the-top INCREDIBLE! it makes people like me that say visuals are the game's soul in awe. I thank you for the visuals and experience being (while annoying to progress) unlike any other I've ever seen. Pat yourself on the back bud ^W^

Edit: grammar & spelling corrections (PS: even if its confusing looking into the files helps understand some things for a newcomer like me exploring)

**Comment by ReikaKalseki** [comment]
What are you suggesting?

**Comment by Shibva** [comment]
Just giving this real quick it seems like they the idea is that instead of him putting a file path if you have a music file within the generated folder within the mods section can you just type in that folders name it'll check that directly as default.

Ie: "song.mid" is put inside of the assets folder chromcacraft generated in the mods folder and just putting "song.mid" into the file path of the orchistra, it will default search for the file in a default path to the mods folder (.../.Minecraft/mods/chromaticraft/)

**Comment by Shibva** [comment]
It also seems like that I was suggesting some sort of an error Message based on if the file name is incorrect or the path is invalid

**Comment by ReikaKalseki** [comment]
There *is* such an error, and you can already specify a relative path. Standard java `File` pathing rules apply, though I do not know which directory is "home" - probably the instance folder.

**Comment by Shibva** [comment]
I guess I wasn't really sure if it specified it or not
