### ISSUE TITLE
[CC V31b] Repeater Issues

### ISSUE THREAD

**Issue by DerWahreQwert** [ReikaKalseki/Reika_Mods_Issues#3056]
Sometimes when right-clicking a repeater with the manipulator to check whether it still has a connection to its pylon the game freezes and subsequently crashes. It doesn't seem to be  affectd by the total distance/number of repeaters to the pylon, since it has occoured with both a short and very long line. The Crash log is attached below.

[crash-2022-07-22_12.47.33-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/9167065/crash-2022-07-22_12.47.33-client.txt)

**Comment by ReikaKalseki** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1100 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1299 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1290 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1604 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1991 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2035 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2151 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2439 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2575 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2637 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2730
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2867
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/3204
