### ISSUE TITLE
[1.7.10 Chromaticraft & Terrafirmacraft+] Crash on startup, narrowed it down to Chromaticraft and Terrafirmacraft when together.

### ISSUE THREAD

**Issue by ThePixelist** [ReikaKalseki/Reika_Mods_Issues#3058]
### Summary
I'm making my own private modpack and after a long while of disabling and re-enabling certain mods I've discovered **Chromaticraft** and **Terrafirmacraft+ crash on startup together**. I've tested each **mod on it's own** ("DragonAPI with Chromaticraft" and "Just Terrafirmacraft+") and **each one works on it's own**, but **together they crash on startup**. I've looked at the logs for a long while (I hate having to submit bug reports) but can't seem to figure out the issue.

### Logs
[Crash report](https://gist.github.com/ThePixelist/7af5cbb48e9ddf1c5b5a4d2f9b9f9ecd#file-crash-2022-07-28_16-11-53-client-txt)
[FML Client Log](https://gist.github.com/ThePixelist/3151e9cd9e8de17dc043b0c60578aab6)

### System Details
Minecraft Version: **1.7.10**
OS: **Windows 10 (amd64) version 10.0**
Java Version: **1.8.0_311, Oracle Corporation**
Java VM Version: **Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation**

### Thank you (I know dealing with bug reports is a tedious and thankless task).

**Comment by ReikaKalseki** [comment]
Ping that developer here; there is an ASM conflict.

**Comment by ThePixelist** [comment]
Despite my best efforts, I can't seem to find their (dunkleosteus/nikstick22) GitHub account.

**Comment by ReikaKalseki** [comment]
Well, I cannot do anything without information from them.

**Comment by ReikaKalseki** [comment]
#3024 and #2396 is this issue anyway.
