### ISSUE TITLE
TerritoryZone config tutorial seems to be wrong

### ISSUE THREAD

**Issue by Somn-** [ReikaKalseki/Reika_Mods_Issues#306]
Attempting to make a zone with one of the example zones in the territoryzone config file like so:
http://pastebin.com/y0U1n9mZ
Doesn't work: http://i.imgur.com/Be9cK03.png
Looking at the server log shows this: 
http://pastebin.com/kmvb9Jtq

Which suggests that the error is this:  ERROR: Malformed zone entry [Invalid UUID string: CUBE]
So I'm assuming that the order of the parameters is wrong?

I've also tried this using a different player name and UUID and had the same error. Am I doing something wrong or is it an issue with the order of the parameters being different to the example provided?

**Comment by lossycrypt** [comment]
Looking at https://github.com/ReikaKalseki/TerritoryZone/blob/master/TerritoryLoader.java#L96 the actual code doesn't mention any enforcement/logging levels on a per zone level and instead declares them in the config globally.

**Comment by Somn-** [comment]
Yes I'm using the latest version.

**Comment by Somn-** [comment]
Will attempt with that format and let you know.

**Comment by ReikaKalseki** [comment]
@lossycrypt That was changed in v9.

**Comment by Somn-** [comment]
Attempting to remove the parameters for enforcement/logging, such that it reads: 
0, -10, 64, 120, 32, 0xff0000, CUBE, SomePlayer, 504e35e4-ee36-45e0-b1d3-7ad419311644
Results in: 
java.lang.IllegalArgumentException: Invalid parameter count.
03.10 20:15:57 [Server] Server thread/ERROR [FML]: TERRITORYZONE ERROR: Malformed zone entry [Invalid parameter count.]: '0, -10, 64, 120, 32, 0xff0000, CUBE, SomePlayer, 504e35e4-ee36-45e0-b1d3-7ad419311644'

So clearly the version I'm using isn't the one @lossycrypt is suggesting, but I'm still having the issue, any idea what it could be @ReikaKalseki ?

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by mrdeadlocked** [comment]
has this been fixed in a released version? I'm still getting this error.

**Comment by lossycrypt** [comment]
If reika fixed it it will be in v10.
