### ISSUE TITLE
[CrC] [Request] A way to sync particle spawners

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#3061]
Right now, even toggling them with redstone at the same time, off then on, does not make them line up, they keep the timing they had from being placed.

![2022-08-05_05 20 11](https://user-images.githubusercontent.com/6917535/183076963-29b3c8e7-3b01-47fd-82a2-7fe7ffe0af74.png)

**Comment by ReikaKalseki** [comment]
Now they use a resetting timer.
