### ISSUE TITLE
[ChromatiCraft + Biomes O'Plenty] Ticking entity crash in Dimension

### ISSUE THREAD

**Issue by darkmazer** [ReikaKalseki/Reika_Mods_Issues#3062]
Upon entering the Dimension, I get a crash within a few seconds of getting to the ground.  I've isolated the issue to some sort of incompatibility with Biomes O'Plenty, since removing BoP from my mods stops the crash from occurring.  

The crash log can be seen here:
https://pastebin.com/QkaP8tdm

**Comment by Zero-ui9** [comment]
I occasionally also get a similar crash, I don't think BOP has anything to do with it, since I don't have it. looks like its luma flies.
https://pastebin.com/ZJ3CMvWx

**Comment by DerWahreQwert** [comment]
I found a workaround for the time being: Disable MobSpawning via gamerule for the periods of time you're planning to be in Proxima. This prevents the volatile Lumafly from ever coming into existance

**Comment by HelluvaRoman** [comment]
I am having the same crash as Darkmazer and Zero with the Luma flies seeming to crash my game upon reaching the ground of the Dimension. Will try disabling mob spawning. 

Update: Turning off mob spawns via game rule did in fact stop me from insta-crashing in the dimension. Seems the crash is indeed most likely related to the Luma Flies

**Comment by ianlavr** [comment]
Do lumaflies even do anything? If they are purely for ambience then disabling their spawn would be a better temporary fix before an update fixes this for good.

**Comment by ReikaKalseki** [comment]
Something looks very wrong with your biome allocation.

**Comment by ReikaKalseki** [comment]
#3134

**Comment by ReikaKalseki** [comment]
And #3172
