### ISSUE TITLE
[Chromaticraft] Request: option to always re-open the lexicon on the same page which you were reading when you closed it

### ISSUE THREAD

**Issue by DoomFruit** [ReikaKalseki/Reika_Mods_Issues#3065]
Normally, when you exit the lexicon and then re-open it, you're brought back to the front page. Pages have an option, Save & Exit, which closes it and brings you back to the same page you were reading.

Problem is that I keep forgetting that this button exists and end up having to search through several screens of slow-scrolling icons to find where I last was.

What I'd like is an option which treats every "close the book" event as a "save and exit" button press. Basically, like how the Botania, Ars Magica, Immersive Engineering, EssentialCraft and, to a lesser extent, Thaumcraft books work. Close them, re-open them and you're back on the same page where you left off. Sure, I could have missed it somewhere, but I've looked through the config file and I can't see anything there that looks like it would do the trick. Neither is there anything visible in the book itself for "options", "persistence", "bookmarks" or anything similar.

**Comment by rkane31174** [comment]
I'd love to have this option for all of the handbooks: Rotary, Reactor, and Electric.

**Comment by ReikaKalseki** [comment]
No, I am not doing this.
