### ISSUE TITLE
Fusion Plasma Injector does not form

### ISSUE THREAD

**Issue by Danceswith5heep** [ReikaKalseki/Reika_Mods_Issues#3066]
I am on version 31b for reactorcraft rotarycraft and dragon api and only have these mods enabled but the injector for the fusion reactor will not form.
![image](https://user-images.githubusercontent.com/89492119/185882819-c2aac694-3a91-489c-8ba3-4dbe82c0b633.png)

**Comment by Danceswith5heep** [comment]
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/9392857/latest.log)
i forgot to include the latest.log so here is that

**Comment by theTyrfing** [comment]
Have not been here a while. Is this still an issue though? Also, this issue was mentioned a few months back in #2956.

**Comment by Danceswith5heep** [comment]
> Have not been here a while. Is this still an issue though? Also, this issue was mentioned a few months back in #2956.

ya its still an issue in the newest version

**Comment by Holorizor** [comment]
It is fixed in the code in the git but the new version is not rolled out so far

**Comment by MalTeeez** [comment]
The last version is actually out, but as far as I am aware it doesn't work with Chromaticraft from that same version, but as long as you dont have both in your pack it should work. The link to the updated mods is under /mods.php of his DragonRealm Pack website - you can find the link to that on his reddit post for that pack, not sure if im allowed to post that, maybe dm's if you cant find it?

**Comment by Holorizor** [comment]
Wow, thank you! I was not aware of it! I just checked his github.io page with all the mod explanations etc. which links reactorcraft for Minecraft 1.7.10 to curseforge (and there the version is V31b from December 2021). I saw in his GitHub that he fixed it.

So with your hint, I found it. Thank you!

**Comment by theTyrfing** [comment]
> The last version is actually out, but as far as I am aware it doesn't work with Chromaticraft from that same version, but as long as you dont have both in your pack it should work. The link to the updated mods is under /mods.php of his DragonRealm Pack website - you can find the link to that on his reddit post for that pack, not sure if im allowed to post that, maybe dm's if you cant find it?

Wait, So it does not work when Chromaticraft is also installed? I am using four of his main mods in my pack. Also, those are dev builds so they could come with some fun bugs. So technically, has not rolled out the latest version.

**Comment by theTyrfing** [comment]
> Wow, thank you! I was not aware of it! I just checked his github.io page with all the mod explanations etc. which links reactorcraft for Minecraft 1.7.10 to curseforge (and there the version is V31b from December 2021). I saw in his GitHub that he fixed it.
> 
> So with your hint, I found it. Thank you!

On a side note here: I was legit going to compile from source that version of the mod.

**Comment by Holorizor** [comment]
> On a side note here: I was legit going to compile from source that version of the mod.

Okay, yes I will test the versions, and if too many bugs or not stable i will shift back to the V31b version

**Comment by theTyrfing** [comment]
> > On a side note here: I was legit going to compile from source that version of the mod.
> 
> Okay, yes I will test the versions, and if too many bugs or not stable i will shift back to the V31b version

Any luck. As I just tested it and it has not formed?

**Comment by theTyrfing** [comment]
Nvm, It is very fickle about it. Sometimes it does. Sometimes it does not form for whatever reasons. Also, this multiblock is very confusing to build to began with.  
![2022-09-15_19 35 57](https://user-images.githubusercontent.com/7342368/190526759-933c5093-75d7-4af5-a760-45a005909831.png)

**Comment by Holorizor** [comment]
In my test it worked. So I will stay for now with the new version.

**Comment by Baaleos** [comment]
Im on 31b - and it doesn't seem to be forming - is there a newer version to download from somewhere?

**Comment by Holorizor** [comment]
there is a new version (labeled as 32a on the website) with the bug fix. See the comment from  Malteez.

**Comment by Baaleos** [comment]
Yup - did find the right website in the end - curseforge and all the other websites keep pointing at 31B - but I eventually found the php website with 32a - which did resolve it.

**Comment by RapFab** [comment]
Hey, after a bit of searching I wasn't able to find the new version anywhere. Could someone maybe be so kind and provide a download link?

**Comment by TheMgfeedthebeast** [comment]
32a works for me, but it is really unstable, minecraft just randomly crashes.
