### ISSUE TITLE
DragonAPI crash with Harder Underground

### ISSUE THREAD

**Issue by Rotzo** [ReikaKalseki/Reika_Mods_Issues#3067]
Hi. As statet above i get a crash with this two mods installed together. I can't really understand crash reports, but it seems it has something to do with the gas the Harder Underground mod spawns.

here's the report: https://pastebin.com/LrpppkkL

Only mods installed:

CustomOreGen
DragonAPI
Harder Underground
HardLib

**Comment by ReikaKalseki** [comment]
This is not my doing.
