### ISSUE TITLE
[Chromaticraft] Crash error

### ISSUE THREAD

**Issue by ZodiacLittlepaws** [ReikaKalseki/Reika_Mods_Issues#3069]
So I was trying to add Chromaticraft to a mod pack, but I got this error code and don't know how to fix it.

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Could not initialize class Reika.ChromatiCraft.Magic.Progression.ResearchLevel

**Comment by ZodiacLittlepaws** [comment]
I do have dragon api installed as a btw.

**Comment by DarianLStephens** [comment]
I get this error quite often when starting the game. If I launch a second time, it's fine, but the first launch almost always has that.

**Comment by ReikaKalseki** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1732 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1683 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1681 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1493 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1257 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1280 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1238 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2390 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1848 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1985 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2419 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2502 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2595
 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/656
 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2903
 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/3032
 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/3004
