### ISSUE TITLE
[Chromaticraft] Request: a friendlier UI for the ritual table

### ISSUE THREAD

**Issue by DoomFruit** [ReikaKalseki/Reika_Mods_Issues#3072]
I've been applying abilities to myself on several occasions, usually when I unlock something new, but sometimes because I've died for whatever reason and need to stick everything back on or occasionally because the ability didn't do anything when I tried to use it and I thought that it didn't get applied properly.

The issue here is that navigating the list of rituals in the table is a horrible, tortuous process. Click, wait for it to scroll, look at name, look at picture to see if it's grey or black and white (and some pictures are not clear on that), click, wait, look at name, click, wait, look at name, click, wait, look at name, click, wait, look at name, click, wait, etc. etc. Very annoying.

What I'd like to see instead is a grid view or a manually scrolled list (a *rapidly* manually scrolled list) like the ability selection menu. Below each picture is the ability's name. Instead of being coloured or black and white, it would have a green tick or a red cross in a little sub-icon over one of the corners to say whether you have it installed or not. If you don't have the fragment, give it a yellow question mark. Click on an ability to bring up the description and see the flavour text that's present now, click either on an explicit "back" button or some unoccupied part of the UI to go back to the selection menu. Then ideally a button that says "prime ritual table with this ability" or something similar, because it's not obvious that clicking on the picture makes it active.

On a somewhat related note, it would also be nice to have some descriptions of how you actually use these abilities, or whether there's a pre-requisite amount of stored lumens that you need in order to activate it. For instance, the pylon surge protection only seemed to activate when I had more than some amount (which I don't yet know) stored in my personal bank. I had no idea that this was a thing. Sure, I saw a pie chart and a total lumen requirement in the manual, but I thought this was what it cost to put it on the player. Then there are the lumen flood and Fortresscraft "build to me" powers. I tried both, they did nothing. No result, no error message, nothing at all. I have absolutely no idea what I'm supposed to be doing with them. The manual tells me what they do, but not what I need to do in order to use it.

**Comment by ReikaKalseki** [comment]
I added a minor QoL feature in v32 to remove redundant entries, but no, I am not going to fundamentally change the GUI.

Also, you can use PGUP, PGDN, and HOME and END to scroll quickly.

As for the "how to use", that is what the lexicon info is for.
