### ISSUE TITLE
[Rotarycraft] Unable to use Vein Miner with HSLA Steel Tools

### ISSUE THREAD

**Issue by Gronglegrowth** [ReikaKalseki/Reika_Mods_Issues#3075]
I've tried adding the HSLA steel tools to Vein Miner's config, under both its tools-and-blocks file and modsupport file, and neither result in these tools being able to vein mine. Unless I overlooked something, this doesn't seem like expected behavior.

**Comment by ReikaKalseki** [comment]
There is nothing at all special about HSLA tools. I have zero knowledge of the VeinMiner configuration system, but either you specified the items incorrectly or that mod does not load/recognize modded items properly.
