### ISSUE TITLE
[Dragon API] Breaks Ars Magica

### ISSUE THREAD

**Issue by Gargule** [ReikaKalseki/Reika_Mods_Issues#3076]
Some buffs (Regeneration, for example) from AM2 do nothing in presence of new version DragonAPI. With old version (tested on v26b) everything worked as intended. Need a fix, or at least need someone who can guide me where exactly i can fix it in AM2 by myself.

**Comment by Gargule** [comment]
I guess, it was broken somewhere here: `ASM/Patchers/Hooks/Event/Entity/EntityAddPotionEvent.java`
But i'm total idiot in asm and i'm not sure.

**Comment by Gargule** [comment]
Sorry for mention, but @DrParadox7, if you care about AM2, you might be interested.
(I know no one else who have forks of AM2 with new fixes)

**Comment by Gargule** [comment]
@TCLProject, you may be interested as well.
(Very sorry for bothering all of you, but i really want to play with these mods)

**Comment by theTyrfing** [comment]
hmmm, I am going to test this myself as I have ars magica in my pack too. What were the steps to recreate this if you mind sharing?

**Comment by TCLProject** [comment]
> @TCLProject, you may be interested as well. (Very sorry for bothering all of you, but i really want to play with these mods)

I will not be able to do anything to try to fix this on account of Dragon API making a black screen when I load the game - with or without optifine. I am fairly certain AM2 buffs do not do anything too unique, though - If I were to guess, dragonAPI somehow manages to prevent mods from retrieving active effects (although this is just an assumption and I have absolutely no idea how one would manage to achieve something like this).

**Comment by Gargule** [comment]
> hmmm, I am going to test this myself as I have ars magica in my pack too. What were the steps to recreate this if you mind sharing?

Just use last version of DragonAPI and try to cast regeneration spell, or something like that.

**Comment by Gargule** [comment]
> I will not be able to do anything to try to fix this on account of Dragon API making a black screen when I load the game - with or without optifine. I am fairly certain AM2 buffs do not do anything too unique, though - If I were to guess, dragonAPI somehow manages to prevent mods from retrieving active effects (although this is just an assumption and I have absolutely no idea how one would manage to achieve something like this).

Interesting. My friend have permanent black screen with theese either. But i do not have any problems with this.
Anyways, my debug messages isn't appear with last version of DAPI:
`	
	@Override
	public void applyEffect(EntityLivingBase entityliving){
		LogHelper.info("GARGULEDEBUG: Regen applied");
	}

	@Override
	public void stopEffect(EntityLivingBase entityliving){
		LogHelper.info("GARGULEDEBUG: Regen stopped");
	}

	public boolean onUpdate(EntityLivingBase entityliving){

		LogHelper.info("GARGULEDEBUG: Regen ticking");
		…
		`
But appear with "old" version. My guess, it's because of potion effect event, that i mentioned above, but idk how that class transformation can break executing these three methods.

Edit: idk, what's wring with code.

**Comment by Gargule** [comment]
Also
>I am fairly certain AM2 buffs do not do anything too unique

It's buff extends PotionEffect, not Potion, as most mods do.

**Comment by theTyrfing** [comment]
I tested it, and I am getting the potion buff status. However, it seems like the actual effect does not occur. Also, spell with Mana shield on them don't even cast properly. I think this is good place to start looking for a cause might be here: [EntityAddPotionEvent.java](https://github.com/ReikaKalseki/DragonAPI/blob/master/ASM/Patchers/Hooks/Event/Entity/EntityAddPotionEvent.java)

**Comment by TCLProject** [comment]
> Also
> It's buff extends PotionEffect, not Potion, as most mods do.

Minecraft uses `PotionEffect` to apply potion effects regardless. If the cause would be something to do with this, minecraft itself would be broken. All it does is call `performEffect` of the `Potion` from the `performEffect` of the `PotionEffect`, and Ars uses that in half the cases (and checks for whether the potion effect is active in an event in the other half).

**Comment by FavoritoHJS** [comment]
> I will not be able to do anything to try to fix this on account of Dragon API making a black screen when I load the game [...]

Ahh, @TCLProject, the good ol' 4+(or was it 2?)-year-old bug (#2315, though the fix is unstable, further talk is in #2260) that breaks world rendering until the screen is resized.
Try resizing your screen, that might fix it.

**Comment by ReikaKalseki** [comment]
#3212

**Comment by TCLProject** [comment]
> #3212

I apologize for the late reply. However I don't feel these two issues are related, 3212 being the result of me changing a few things in the early loading order to maintain compatibility with another mod, and I've wrote a workaround for that. So 3212 is, in fact, fixed.

This issue on the other hand I believe is something different, so without further confirmation I wouldn't be so quick as to assume it's fixed (and, as stated beforehand, I do not believe I can solve it on my end- AM2's `onUpdate` overwrites `PotionEffect`'s `onUpdate`, and I would rather not write crutches and/or reinvent bicycles).
