### ISSUE TITLE
[Chromaticraft] Request: a lumen fabricator recipe for Piezo Crystals

### ISSUE THREAD

**Issue by DoomFruit** [ReikaKalseki/Reika_Mods_Issues#3077]
I've been using piezo crystals to make paths in my base and I've nearly run out. The only way for me to get a decent amount of them is to quarry a luminous cliffs biome, something that I'm somewhat reticent to do. Mainly because I've banned quarries in the overworld, but even if I hadn't, doing so would ruin the biome for anyone else who finds it.

A lot of blocks in CC are able to be replicated in the lumen fabricator, but unfortunately piezo crystals aren't one of them. Can we get a way to make more of them? They're not exactly a particularly complicated or functional block (at least, I don't think they are) and there are several other blocks which are more "important" (various fancy pylon components) and can be made there.

**Comment by ReikaKalseki** [comment]
Done.
