### ISSUE TITLE
[Chromaticraft] Elemental manipulator wand focus cannot drain power from crystal pylons

### ISSUE THREAD

**Issue by DoomFruit** [ReikaKalseki/Reika_Mods_Issues#3079]
I built myself an elemental manipulator wand focus in the hope that I didn't have to carry so much junk around and while it shows my current colour levels and it does work to activate the crafting table, I can't use it to drain power from crystal pylons. It "activates" (and yes, I'm close enough for the normal elemental manipulator to work), I hold my wand out (technically a staff, but I'd be surprised if that broke anything), I move more slowly, but nothing happens.

This happens both before and after I got the pylon-sourced vis research.

**Comment by darkmazer** [comment]
It works.  You just have to be farther back.  If you're too close to the pylon it thinks you're trying to use your wand on the aura node.

**Comment by DoomFruit** [comment]
Huh. So it does. Annoying, that, but I can see why it happens.
