### ISSUE TITLE
[ChromatiCraft] Transition Star Shift-Right-Click Crash

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#3081]
I shift-right-clicked'd on empty air to open the UI (thought shift was needed), and it just froze then crashed. Usually no issues, but sometimes this happens.

https://gist.github.com/Shahelion/a517eafddb6437eb4c952bb98fd59f37

**Comment by ReikaKalseki** [comment]
Link 404s.

**Comment by OvermindDL1** [comment]
It's a private gist I guess?

**Comment by Shahelion** [comment]
Forgot to update the link with the username change. Fixed.

**Comment by ReikaKalseki** [comment]
Fixed.
