### ISSUE TITLE
[DragonAPI] HEXCraft compat uses API not present in public versions.

### ISSUE THREAD

**Issue by FavoritoHJS** [ReikaKalseki/Reika_Mods_Issues#3083]
While trying to set up a development enviroment to help debug some long-standing bugs, I've found that the HEXCraft compat in DragonAPI, specifically, the class `Reika.DragonAPI.ModInteract.ItemHandlers.HexBlockHandler`, imports classes in the `com.celestek.hexcraft.api` package, which is not included in public versions of that mod, or even the latest development version on Github...

This makes finding the correct build files kinda difficult...

Interestingly, the bundled version in DragonRealmCore _does_ include that API. I can only hope no drama was behind this discrepancy...

EDIT 26-09 I'd also take this opportunity at the soapbox to say that you're using `Block.blockHardness`, a `protected` field, instead of `Block.getBlockHardness(World, int, int, int)`, which due to an overdose of notchcode might as well be a `Block.blockHardness` getter.

**Comment by ReikaKalseki** [comment]
There are two different HexCraft handlers, for two different builds of HexCraft.
