### ISSUE TITLE
[DragonAPI] Framez API doesn't match any public version.

### ISSUE THREAD

**Issue by FavoritoHJS** [ReikaKalseki/Reika_Mods_Issues#3085]
It's #3083 all over again, but with another mod.

The versions of Framez that are available on Curseforge are 0.2 and some alphas of v2.

The API you used in DragonAPI is a work-in-progress one that works with neither -- if #1956 (aka Reika trying to Graaₐₐ... and failing) is to be believed, it was made in preparation of a release that never came.

Except instead of that case where there's no "new" API, I have reason to believe that a version with the "new" API got released (considering how it ended up on the Gregtech maven)... somehow.

Almost tempted to drag `amadornes` into this mess to set the record straight on this.

PS: Please _please_ use a more normal setup, I'm not hunting down 30 billion deobf versions and I'm scared of how spaghetti the reobf process will be just so I can actually _check if i'm breaking everything_...

**Comment by ReikaKalseki** [comment]
This was fixed in v32.
