### ISSUE TITLE
Fan does not push entities in 3x3; maybe should call getWideBlowZone

### ISSUE THREAD

**Issue by jarrett** [ReikaKalseki/Reika_Mods_Issues#309]
When the fan is configured for a 3x3 area of effect, it only pushes entities in a 1x1 column. I think this is because `makeBeam` ignores `wideArea` and always calls `getBlowZone` instead of `getWideBlowZone`:

https://github.com/ReikaKalseki/RotaryCraft/blob/ac8cd8b8e4e1b9919d138b9adfecb63969359dd4/TileEntities/Farming/TileEntityFan.java#L160

I'm not familiar with the codebase, but maybe something like this would work:

```
AxisAlignedBB zone = wideBeam ? this.getWideBlowZone(meta, range) : this.getBlowZone(meta, range);
```

Thanks!

**Comment by ReikaKalseki** [comment]
Not a bug.

**Comment by jarrett** [comment]
Hmm, in that case, what is the wide beam intended for? The fan does harvest in the 3x3 column, but because the entities don't get pushed, they go to waste. 3x3 harvesting without 3x3 pushing seems unusable--or am I missing something? The item vacuum doesn't seem to interact well with fans, so I'm guessing that's not how the fan is meant to be used.

**Comment by ReikaKalseki** [comment]
Yes, that is exactly what the item vacuum was designed for. Alternatively, you can turn off wideArea on the fan, and use 3x as many fans, with the accompanying costs both in terms of ingame resources and computational load.
