### ISSUE TITLE
[Chromaticraft] Applied Hotbars ability too overzealous about sending items to ME

### ISSUE THREAD

**Issue by EyeDeck** [ReikaKalseki/Reika_Mods_Issues#3090]
So as I understand it, this is the _intended_ functionality of Applied Hotbars, assuming a operational ME system is appropriately linked, and resources/storage space are available.
- When placing a block from a full stack, blocks will be remotely withdrawn from ME as long as resources are available, before items from one's inventory are used.
- When picking up an item, your hotbar(s) are checked, and if there's already a full stack of the same item on your hotbar, the item will be sent to ME instead.

Currently the first point works as intended, however the second point does not.

Instead, when picking up an item, first your hotbar(s) are checked for a matching item, and the hotbar stack will be filled if it isn't already a full stack. After that, _all_ items picked up with the ability active are sent to ME, regardless of presence/absence of the item on your hotbar.
Functionally, this is _nearly_ equivalent to an Intentory Warp set to send all items.

The culprit seems to be here: https://github.com/ReikaKalseki/ChromatiCraft/blame/fe9038796d08d33f1096ac4502d96c1581701bbc/Auxiliary/Ability/AbilityHelper.java#L719
Before that we get the ItemStack being picked up. Next, hotbar slots are checked for a matching item, and if found the hotbar stack is filled from the ItemStack.
After that, if the ItemStack still exists (i.e. it hasn't previously been merged with a hotbar stack), it's sent to ME (line 720). _Always_.

Presumably the matching changelog entry is the one from v29d that reads
>Applied Hotbars now properly intercepts returned items from the Transition Star

Which I guess is technically true—except it's intercepting _everything else_ as well.

**Comment by ReikaKalseki** [comment]
Fixed.
