### ISSUE TITLE
Void Monster sound config not respected

### ISSUE THREAD

**Issue by DarianLStephens** [ReikaKalseki/Reika_Mods_Issues#3091]
I don't know for absolute certain, but no matter what I set the 'Sound Interval in Ticks' option to, it always seems to play the at the same rate, even in the 8000+ range.
I'm trying to greatly reduce the frequency these sounds are played at, because we find them annoying more than scary when they play so often.
If that doesn't do what I think it does, then could there be an option for it? And maybe a way to change the level it starts playing at?

**Comment by ReikaKalseki** [comment]
That config controls the sounds from the creature itself, not the ambient sound system. But I halved the frequency of the latter.
