### ISSUE TITLE
[Chromaticraft] Outer Regions (FARLANDS) progression trigger missing

### ISSUE THREAD

**Issue by EyeDeck** [ReikaKalseki/Reika_Mods_Issues#3092]
The progression trigger for FARLANDS doesn't exist, and apparently never has.
Evidently nobody noticed, or at least cared, since FARLANDS wasn't actually gating until recently. In the current version it's mandatory to step to CTM, so ChC cannot be completed without commands.

This progression is _supposed_ to unlock as soon as you visit the Farlands in Proxima, with effectively no prerequisite (only things you need to get to Proxima in the first place).

For the moment, the best workaround is to manually trigger progression with a command:
`/chromaprog <playername> progress FARLANDS true`

---
The old name for this progression was DIMENSION3, here are the relevant commits that reference either one in any way:
![unknown](https://user-images.githubusercontent.com/2722970/198850936-b4dfcdbb-1c96-4d52-90fb-de3857ef664f.png)

https://github.com/ReikaKalseki/ChromatiCraft/commit/dcfc22a2b1fec57c163aedd7a29121e484b3c38e 481 (v13b), DIMENSION3 was added
https://github.com/ReikaKalseki/ChromatiCraft/commit/58b867759b8571552998d49b1696385f5949cc10 487, a change to the UI effect
https://github.com/ReikaKalseki/ChromatiCraft/commit/e6c2963566eef7e75d4c5b396aa10fbd2bcadfdc 1118, added FragmentCategorizationSystem.java 
https://github.com/ReikaKalseki/ChromatiCraft/commit/f873670a00a3ac7fc1b693afaa7fe06e0b51ef22 1120, renaming to FARLANDS

None of them have ever included code for triggering the progression. If it existed, it would most likely be in:
https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Auxiliary/ExplorationMonitor.java
Which would presumably have an extra block of code to check that you're in Proxima + any of the ChC Farlands biomes, and trigger progress like
`ProgressStage.FARLANDS.stepPlayerTo(ep)`

**Comment by ReikaKalseki** [comment]
Fixed.
