### ISSUE TITLE
[DragonRealm] For some reason horses aren't tameable

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#3094]
Horses will never kick you off if you ride on top of them. I didn't see any obvious AI change mods or configs so I don't really know what's causing this.

**Comment by EyeDeck** [comment]
Might be caused by this in LegacyCraft: `B:"New Mob AI"=false`
That setting affects a ton of things, e.g. sheep not regrowing wool. It's mostly only set that way because the old mob AI is cheaper computationally, and falling back to the old AI clawed a few TPS back on one of Reika's old (struggling) servers.

**Comment by Mettymagic** [comment]
> Might be caused by this in LegacyCraft: `B:"New Mob AI"=false` That setting affects a ton of things, e.g. sheep not regrowing wool. It's mostly only set that way because the old mob AI is cheaper computationally, and falling back to the old AI clawed a few TPS back on one of Reika's old (struggling) servers.

I did try this and it didn't seem to fix the issue. Even tried a completely fresh install in case some weird edge case improper installation occurred and the horses won't kick me off. You can use /summon to spawn a horse with the tamed tag but from my testing changing the movementSpeed attribute doesn't actually change the riding speed and it's pretty slow and useless.

EDIT: Probably has to do with this change that can be found in the changelog https://i.imgur.com/UKS1oCL.png

**Comment by ReikaKalseki** [comment]
I removed horses from the AI blacklist.
