### ISSUE TITLE
[DragonRealm] Is it safe to add small, non-impactful mods to the pack?

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#3100]
I saw a warning against unsanctioned modification of the DragonRealm pack but I was wondering if it would be safe to add minor mods like a Gravestone mod or BiblioCraft to the pack or if this would mess things up. I don't know how DragonRealmCore works but I do know it's very finnicky and I want to know if this would ruin things or not. Any advice would be very helpful, thank you.

**Comment by EyeDeck** [comment]
The warnings are primarily to avoid breaking the very carefully balanced pack progression, mostly with regards to tech mods. If you dropped in something like Mekanism or RFTools, chances are it'll _work_, but without extensive recipe tweaks, and machine rebalancing/removal/etc, it'll probably make a complete mess of pack balance at the same time.

The magic side of things is less sensitive, so you could probably drop in new ThaumCraft addons or whatever without breaking much. Old versions of the pack (~2016) had Blood Magic, which, other than having a minor amount of feature overlap with Chromaticraft, worked fine.

BiblioCraft _used_ to be in the pack, but was removed (2017 or 2018, I think?) for two reasons:
- Endgame bases with this pack tend to perform badly enough _without_ Bibliocraft's fairly complex/expensive-to-render decorative TESRs, so it ended up being very rarely used. Not a lot of motivation for decoration when you're at single-digit FPS counts.
- There was a non-negligible decrease in client launch time by removing it (especially for a few users with really weak hardware, some of whom literally took over half an hour to load), just on account of the number of things Bibliocraft adds.

If those things don't bother you, go ahead and re-add it.

Reika hates gravestones, and _likes_ the "items flying everywhere" vanilla death mechanic, that's the only reason there isn't a gravestone mod in the pack.

**Comment by ReikaKalseki** [comment]
> The warnings are primarily to avoid breaking the very carefully balanced pack progression, mostly with regards to tech mods.

Not just tech mods. Also to avoid triggering mechanical issues as mods start toggling features or whatever based on the presence of the new mods and breaking ASM or reflective patches.
