### ISSUE TITLE
Snowy Outpost Loot Chests

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#3102]
The chests on the upper level are able to be opened at first, despite having solid shielding stone above them. However, after breaking the core, the chests are NOT able to be opened, or even broken, until the stone above them is broken.

The chests on the lower level are NOT able to be opened, they also have shielding stone above them. Even breaking the core does not allow opening them without breaking the stone above.

**Comment by ReikaKalseki** [comment]
I fixed this in v32.
