### ISSUE TITLE
[DragonRealmCore, TerritoryZones] Empty TerritoryZone_zones.cfg results in infinite function call

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#3103]
If you have a TerritoryZone_zones.cfg file without any defined territories (either deleted or commented out), for some reason generating a stronghold cache fails and will result in an infinitely repeating message in the console:

"Stronghold Cache Generated: {}"

This results in extremely slow performance and spams the logs. The issue is easy to reproduce and can be fixed by just adding any territory zone to the config, or if really desired, starting the server with a territory defined, removing it, then reloading territories through /reloadterritories.

**Comment by EyeDeck** [comment]
This was fixed months ago according to Reika, but there hasn't been a release for a while.
