### ISSUE TITLE
Chromaticraft Info Fragment Issue

### ISSUE THREAD

**Issue by Hellexar** [ReikaKalseki/Reika_Mods_Issues#3104]
TLDR blank info fragments when picked up off the ground become learned fragments

To my understanding blank info fragments have a different method of being "learned" now, which doesn't involve them automatically converting to a learned fragment upon acquisition. Upon looting some directly from a chest (inventory to inventory), and me not knowing of the change, I thought it might have been a bug, and tried dropping them onto the ground before picking them back up, which promptly converted them into learned fragments.

**Comment by DFliyerz** [comment]
I thought I was going crazy! Finally I can use all my blank fragments

**Comment by ReikaKalseki** [comment]
This system was not fully implemented then. Now it is.
