### ISSUE TITLE
Rotarycraft v31b Engine Control Unit (ECU) not responding to redstone signal

### ISSUE THREAD

**Issue by rkane31174** [ReikaKalseki/Reika_Mods_Issues#3107]
I have a performance engine on top of an ECU (though I tested a microturbine as well). Manually adjusting the ECU speed with the screwdriver works perfectly well, but I can not turn the engine off using redstone.

**Comment by EyeDeck** [comment]
Have you tried a _strong_ redstone signal, i.e. a lever directly on the ECU, or a repeater going into it? I swear this has worked for me recently, but I almost always just have a lever directly on the ECU.

**Comment by rkane31174** [comment]
I tried putting a redstone torch directly beneath it. I'm pretty sure that's a strong signal. I don't remember whether or not I tried a lever. I'll try it when I have time.

**Comment by rkane31174** [comment]
It does not respond to levers.

**Comment by lee321987** [comment]
Redstone Conduit form EnderIO works.  (there is a checkbox to force the Conduit to give a a strong Redstone signal).
EnderIO is nice because you can have a Fluid Conduit (for your fuel) inside the same block as the Redstone Conduit.

**Comment by rkane31174** [comment]
That doesn't seem to work either.

I've tried vanilla redstone going directly into the ECU, I've tried a redstone repeater pointing into the ECU, I've tried putting a redstone torch directly beneath the ECU, I've tried putting a lever on the ECU, I've tried using EnderIO conduits in strong signal mode (both insulated and uninsulated), I've tried Thermal Expansion redstone relays (even though I know by experience they don't directly work).

**Comment by lee321987** [comment]
Did you Ctrl+Right-Click the ECU with a screwdriver?  If you do it right, the chat should say:
"ECU is now Redstone-operated"

**Comment by rkane31174** [comment]
I had no idea I needed to do that. Thank you so much!
It works now. 100%.

I checked the handbook. It doesn't say anything about doing that.
