### ISSUE TITLE
[Suggestion] Cooling down Spent fuel container with liquid Nitrogen

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#3109]
Hi,
I love to dispose the nuclear waste on "the proper way". The Tile accelerator works really fine for the long living waste, but the passive cooling mechanic for the spent fuel container doesn't work really well. It may be Lag related on my Server, but even if i give them enough Space in the Ocean they explode sometimes. Even if I give them Liquid Spiller support they consume sometimes all 4 Sources around them and the Vanilla Mechanic to refill the holes doesn't work Properly.

It would be nice if you could Pipe in Liquid nitrogen on the top of a container tower to cool them down Manually and prevent exploding if they become too hot or at least as an Alternative cooling method without consuming the Water sources.
The water may still be necessary to Shield the Radiation or just checking if there is a Source, without consuming it.

Regardless which Countainer setup i use (higher but fewer towers, or more Spreaded lower Towers) sooner or later they explode.

Even this setup is not safe:
https://ibb.co/hLRzBHF

There was a middle Tower, i removed it after the first explosion but i got still 2 Explosions in the Corners.

Another unsafe Concept: https://ibb.co/kMs9jFs https://ibb.co/hmfsXck
I know they get hotter on Lower levels, but i changed the Biome to End for a -100°C base Temperature

**Comment by ReikaKalseki** [comment]
There is no need to make spent fuel containers that cold, and I have no interest in it being a pipe and a tank either.
