### ISSUE TITLE
ReactorCraft Handbook "Structure Guide" Improvements.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#311]
R1: Sturcture Guide is lacking N# like in CC, which is currently the only way of getting the block names. Having hover-over-text in 2D mode would be very useful too.
R2: Structure Guide doesn't have the names of the structures.
R3: Ferromagnetic Base and Magnetic Linkage are near undistinguishable in Structure Guide (would be fixed by R1).

**Comment by ReikaKalseki** [comment]
The page is only half implemented...

**Comment by ReikaKalseki** [comment]
Fixed.
