### ISSUE TITLE
[Rotarycraft V31B] Friction heater sets players on fire when unpowered in hot ambient temperature

### ISSUE THREAD

**Issue by Acroficer** [ReikaKalseki/Reika_Mods_Issues#3110]
Unpowered friction heaters are able to set players on fire if the ambient temperature is high enough. Notably, the 300c ambient temperature in the nether - place a friction heater and step on it. Inactive blast furnaces do not set the player on fire at this temperature.

**Comment by ReikaKalseki** [comment]
This makes sense, though I am going to fix it.

>  Inactive blast furnaces do not set the player on fire at this temperature.

Because you cannot enter their block space.
