### ISSUE TITLE
Idea: Essentia managment

### ISSUE THREAD

**Issue by Shibva** [ReikaKalseki/Reika_Mods_Issues#3112]
This is an idea regarding the essentia relay and an annoyance that I have experience while trying to work with it, the idea is to include some way better to control the routing and extraction of essentia from sources

Linking: maybe if you link a relay node to a jar it will act as an "empty buffer" thats behavior is to empy all contents as much as possible except to the thing is linked and acting as the final priority when filling new things

this would be more practical when using the essential resovar

**Comment by ReikaKalseki** [comment]
The essentia transfer system works on a priority system, based on things like producers and consumers and whether a jar is labelled or not.
