### ISSUE TITLE
[ChromatiCraft] Displacement Wand from Not Enough Wands can be used to bypass puzzles in the dimension

### ISSUE THREAD

**Issue by Maxwell-lt** [ReikaKalseki/Reika_Mods_Issues#3114]
As with the Staff of Traveling from Ender IO, the Displacement Wand and Moving Wand from [Not Enough Wands](https://www.curseforge.com/minecraft/mc-mods/not-enough-wands) should be added to the cheat prevention blacklist.
Both can be used to bypass structures in the dimension:
The Displacement Wand can push or pull blocks to open up gaps.
The Moving Wand can pick up and relocate blocks.
This includes blocks such as shielding stone, glass, light, cobble, etc., as well as Ethereal Barrier.

Both items are in the dungeon loot table, and can therefore be obtained inside the dimension puzzles.

**Comment by ReikaKalseki** [comment]
Can you get me `/mt hand`s of these items?

**Comment by Maxwell-lt** [comment]
Moving Wand: `<NotEnoughWands:MovingWand>`
Displacement Wand: `<NotEnoughWands:DisplacementWand>`
Both wands can also have tag content, which I excluded from this output.

**Comment by ReikaKalseki** [comment]
Done.
