### ISSUE TITLE
[ReactorCraft] Solenoid won't form

### ISSUE THREAD

**Issue by aigri22** [ReikaKalseki/Reika_Mods_Issues#3116]
Injectors and solenoid wouldn't form in v31b, I then updated to v32a and now injectors are working fine but solenoid still doesn't seem to work. Here is my build :
![2022-12-11_18 38 10](https://user-images.githubusercontent.com/102556048/206919699-224b535a-c579-443f-847e-382799e5557d.png)
I also tried placing each block last.

**Comment by Kobra331** [comment]
AFAIK you need to place the main solenoid block at last. If still not forming double check every block

**Comment by Kobra331** [comment]
I tested it, it works. I tried it with a random solenoid block.

**Comment by aigri22** [comment]
My bad, I used data found on internet that is apparently wrong : 
![image](https://user-images.githubusercontent.com/102556048/208265387-6bf5831f-f356-4f1c-8031-45448b976660.png)

Hubs and Magnets are reversed.
