### ISSUE TITLE
[Chromaticraft] save unplayabe after a dye tree-vine became a fallingBlock

### ISSUE THREAD

**Issue by Shibva** [ReikaKalseki/Reika_Mods_Issues#3119]
Apperently the mod dosent like it as a falling block and crash/soft-locks the world

[crash-2022-12-22_06.06.04-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/10286472/crash-2022-12-22_06.06.04-server.txt)

**Comment by Shibva** [comment]
Upon futher examination and testing, I found that its not caused by the leaves but the vines, apperently they dont like it when they become falling blocks, either in the part they become it or most likey when they come out of a falling block state


world will become SOFT-LOCKED until thing is removed

**Comment by Shibva** [comment]
Confirmed to be a bug on chromaticraft end https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/issues/854

"Just checked the code on both vanilla's falling blocks and ChromatiCraft's dye vines, apparently this happens due to the vines' canReplace method assuming that the passed stack is not null, while the vanilla falling block entity uses this method with a null parameter to check if the falling block can be placed as a static block. ..."

**Comment by Shibva** [comment]
To reproduce the issue:

1. Find a dye tree with vines or place them

2. Cause the vine to become a fallingBlock; in this case I would use an Impulse Grenade for HBM's nuclear tech mod because when it detonated it turns any blocks around it into falling block 

3. Crash
4. Reboot the game and enter the world.

If your game crashes again then you have not only the crash but also the soft lock that comes with it

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by Shibva** [comment]
@ReikaKalseki eeee thanks!
