### ISSUE TITLE
"Enable Temporally Dependent Amusement Behavior"=false" does not affect winter/christmas content and it is causing problems

### ISSUE THREAD

**Issue by brandyyn** [ReikaKalseki/Reika_Mods_Issues#3121]
"Enable Temporally Dependent Amusement Behavior"=false"

I have spent 2 days trying to figure out why there is no rain sound in my modpack and after hours of binary searching through mods and comparing my old versions of my pack, it came down to Reika's mods, I use dynamic surroundings which overwrites Reika's snowfall effect so I didn't even know it was happening and just saw rain with no sound. This should be a config option to disable the constant snowy weather, especially since i'm sure i'm not the only one that this has caused a headache for ESPECIALLY since I ALREADY had the first line set to false and I didn't know this would be a thing even with the rest of the effects off...

![image](https://user-images.githubusercontent.com/11356565/209236609-b6a5d616-24a7-4288-ab46-0e3f3317d233.png)

**Comment by brandyyn** [comment]
in dsurround.cfg

    # Disable ASM related to weather effects [default: false]
    B:"Disable Weather Effects"=true

fixes the rain issue, this is a good enough fix for me but i still think that the line being false should disable the winter effects too

is there a place where i can see all of the different effects like for halloween, april fools and winter? i'm curious what it adds.

**Comment by ReikaKalseki** [comment]
Christmas is not able to be disabled.
