### ISSUE TITLE
Client crash when rendering an Opalized Travel Path placed in negative X coordinates when Geostrata is not installed

### ISSUE THREAD

**Issue by Maxwell-lt** [ReikaKalseki/Reika_Mods_Issues#3122]
I placed an Opalized Travel Path in the world, and instantly encountered a client crash due to an OOB array access.
Relevant section of the stacktrace:

    java.lang.ArrayIndexOutOfBoundsException: -15
     	at Reika.ChromatiCraft.Registry.CrystalElement.getBlendedColor(CrystalElement.java:227)
     	at Reika.ChromatiCraft.Block.BlockPath.getBasicRainbowColor(BlockPath.java:118) 
    	at Reika.ChromatiCraft.Block.BlockPath.func_149720_d(BlockPath.java:114) 
    	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4232)

Looking through the stacktrace, it's pretty obvious why this happens.
```java
@Override
public int colorMultiplier(IBlockAccess world, int x, int y, int z) {
	return world.getBlockMetadata(x, y, z) != PathType.RAINBOW.ordinal() ? 0xffffff : ModList.GEOSTRATA.isLoaded() ? this.getOpalColor(world, x, y, z) : this.getBasicRainbowColor(world, x, y, z);
}
```
https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Block/BlockPath.java#L114
When Geostrata is not installed, this will call getBasicRainbowColor().

```java
private int getBasicRainbowColor(IBlockAccess world, int x, int y, int z) {
	return CrystalElement.getBlendedColor(x, 10);
}
```
https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Block/BlockPath.java#L118
Then, CrystalElement.getBlendedColor() is called with the x coordinate as the `tick` parameter, and 10 as the `mod` parameter.
```java
public static int getBlendedColor(int tick, int mod) {
	CrystalElement e = CrystalElement.elements[(tick/mod)%16];
	CrystalElement e2 = CrystalElement.elements[(tick/mod+1)%16];
	float mix = tick%mod/(float)mod;
	return ReikaColorAPI.mixColors(e2.getColor(), e.getColor(), mix);
}
```
https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Registry/CrystalElement.java#L225
Here the x coordinate is divided by 10, and then the remainder modulus 16 is used to access the CrystalElement.elements array.
In Java, the modulus operator returns a negative result when the dividend is negative, as is the case when the X coordinate is -10 or lower. This then causes the sign of the array access to flip to negative values, causing the array out of bounds exception.

After finding the likely cause in code for this crash, I was able to validate the issue in a test world. Placing the travel path did not cause crashes until the 10th block placed past negative x.

**Comment by ReikaKalseki** [comment]
This got fixed in v32 by changes in that same function for rendering purposes.
