### ISSUE TITLE
[Chromaticraft v31b] ccstructmap shows only "unexpexted error"

### ISSUE THREAD

**Issue by NysanderBTF** [ReikaKalseki/Reika_Mods_Issues#3123]
Hello, I've been trying to use ccstructmap to find some DataNodes, but the only respond i could get was 
<img width="463" alt="image" src="https://user-images.githubusercontent.com/101735656/209522726-f2adc3cb-f54d-40b5-993a-6973f5e35cb4.png">
I have tried such command variations:
/ccstructmap 8218887610620323043 datadower 1000
/ccstructmap datadower 1000
(and some variations with range)

The world is singleplayer, so i'm not sure that `@Override
	protected boolean isAdminOnly() {
		return true;
	}` can cause such behavior

**Comment by NysanderBTF** [comment]
Attempt to place datanode with /chromastruct datanode causes same error

**Comment by ReikaKalseki** [comment]
You are using them incorrectly. While the various mods' commands should be documented, this is something that I do not have a good way to do.
