### ISSUE TITLE
ChromatiCraft v31b WorldGen crash (1.7.10 server)

### ISSUE THREAD

**Issue by Khaleas** [ReikaKalseki/Reika_Mods_Issues#3124]
Hello. When playing with my friends using custom-made modpack(1.7.10 version), we have discovered server-crashing bug. When anyone tries to access sunset dimension from ArcanaRpg mod, server crashes.

![image](https://user-images.githubusercontent.com/108265069/209645286-9948c061-884a-4253-8ffc-3af22d76ee21.png)

From my understanding, ChromatiCraft tries to determine the possibilty to spawn decorative flowers in dimension's biom and fails to recognise whether it is a snow biom. Sadly, there is no way to contact ArcanaRpg mod's author. Thus, i have 2 questions:

1) Is it possible to lock ChromatiCraft from spawning anything in non-standart dimensions/bioms? If it is, then how?
2) If disabling spawning is impossible, how can i prevent crashes without removing one of abovementioned mods?

I should also mention, that i am usingAternos for server hosting, which limits my abilities in troubleshooting.

I look forward to your response. 
Thanking in anticipation.

**Comment by ReikaKalseki** [comment]
`ArcanaRpg` biomes have null names. This is invalid and will crash all sorts of things.
