### ISSUE TITLE
Satisforestry consistent crash on getting block type

### ISSUE THREAD

**Issue by brandyyn** [ReikaKalseki/Reika_Mods_Issues#3128]
Crash when approaching Satisforestry biome in my modpack- I tried 3 times, the third time after enabling "Attempt to Repair Environment Sanity"

[crash-2022-12-29_19.22.23-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/10321353/crash-2022-12-29_19.22.23-server.txt)
pastebin: https://pastebin.com/qNFF0vZM

[crash-2022-12-29_19.23.30-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/10321354/crash-2022-12-29_19.23.30-server.txt)
pastebin: https://pastebin.com/BQ2v7129

[crash-2022-12-29_19.28.32-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/10321355/crash-2022-12-29_19.28.32-server.txt)
pastebin: https://pastebin.com/mztcyVAh

here's are the logs:

[2022-12-29-7.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/10321358/2022-12-29-7.log)

[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/10321359/latest.log)

**Comment by brandyyn** [comment]
started a new world and went to another one and same crash: 

[crash-2022-12-29_19.53.41-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/10321850/crash-2022-12-29_19.53.41-server.txt)
pastebin: https://pastebin.com/sqz30KwA

[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/10321851/latest.log)

**Comment by brandyyn** [comment]
things i have tried:
changing biome id to 95 instead of 147
turning off all changes to random from bugtorch
removing optifine 
removing alreadydecoratingfix

[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/10321953/latest.log)

removing bugtorch
removing archaicfix

[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/10322282/latest.log)
crash report as pastebin: https://pastebin.com/5wnmr4Dg

**Comment by brandyyn** [comment]
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11483706/latest.log)

[crash-2023-05-16_04.22.57-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11483707/crash-2023-05-16_04.22.57-server.txt)

**Comment by brandyyn** [comment]
[log1.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11648535/log1.txt)
[log.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11648536/log.txt)

**Comment by brandyyn** [comment]
log1 is after removing these mods:
![image](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/11356565/751f2f5b-9e67-4f12-842d-71bd1c2ba322)

**Comment by ReikaKalseki** [comment]
This is vanilla code. And having 4000 mods is not going to help.

**Comment by brandyyn** [comment]
@ReikaKalseki thanks to your information on discord earlier, the culprit has been found. 

the mod that makes the server thread crash on the satisforestry's biome spawn is justanotherspawner, luckily this mod is forked by @makamys and the fork is the version i was using but i tested it with the original latest version and the crash still occured

i hope that you two are able to work together to solve this because the other mod i was using, mobspawncontrols 2 crashes with chromaticraft. #3127

just to add the context for @makamys
![image](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/11356565/52425f12-c4e1-4d8e-9398-5328960b15c0)

![image](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/11356565/5b4ed5d5-7dd2-42ad-80da-db5c3b123da0)

here is a log in a test instance of the original latest version of justanotherspawner too. 
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/12021731/latest.log)

should I move this issue to makamys repository?

**Comment by brandyyn** [comment]
setting ["Empty vanilla spawnlists": false] in Justanotherspawner fixes this @makamys
