### ISSUE TITLE
[ChromatiCraft, Suggestion]Please add a configuration file to Mineral Extractor

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#3131]
Please add a configuration file to Mineral Extractor, so that modpack authors and players can add some extra mineable ores. 
There are a lot of ores for HBM's Nuclear Tech, TerraFirmaCraft, MineFantasy2, Metallurgy 4, ManaMetalMod, etc. that are not included by DragonAPI, which makes Mineral Extractor unable to mine them. 
I tried to decompile Dapi but the signature could not pass. It's even better to add a configuration file to ModOreList.java

**Comment by ReikaKalseki** [comment]
Fixed in v32.

**Comment by ReikaKalseki** [comment]
I added a config to specify them, in a `<item string>#<category>` format: `customMappings.put(BlockKey.fromItem(is), MineralCategory.valueOf(parts[1].toUpperCase(Locale.ENGLISH)));`

The item string is in the same format used in the custom LuaBlock-based recipes. The default value for the config will show the category options.

**Comment by KuroPeach** [comment]
Thanks, is there an example?
    S:"Custom Mineral Extractor Mappings" <
        none#UBIQUITOUS_ORE
        none#COMMON_ORE
        none#UNCOMMON_ORE
        none#RARE_ORE
        none#MISC_UNDERGROUND
        none#MISC_UNDERGROUND_VALUABLE
     >

like this?
hbm:oreuranium#UNCOMMON_ORE
or
ore:oreAluminium#COMMON_ORE

**Comment by ReikaKalseki** [comment]
It uses the same format as the custom recipes - look to them for some examples. `ore:tagName` and fully namespaced item registry names are both valid.

**Comment by KuroPeach** [comment]
Hello reika, I have an additional request, can I add a download for your mod on [MCMOD](https://www.mcmod.cn/) in China, because of the transoceanic network and GFW, the download through curseforge will be very slow, or directly Lost link, need help from vpn, but vpn is not very stable, and most players aren't buying a VPN
So can i do it? This is a public welfare website, only rely on donations and advertisements to maintain the server.

**Comment by ReikaKalseki** [comment]
No. A slow download once every few days for a week, and then not for another several months, is not worth caring about, and I will not allow alternate hosts.

**Comment by KuroPeach** [comment]
Ok, I will not be uploading to mcmod.
