### ISSUE TITLE
[Chromaticraft v31b] Ticking entity (Tunnel Nuker) crash.

### ISSUE THREAD

**Issue by NysanderBTF** [ReikaKalseki/Reika_Mods_Issues#3134]
Hello. I faced this ticking entity crash and i even can't load into the world for more than a few seconds. Don't you have any suggestions how to make world at leats playable again?

https://pastebin.com/YaePQjTu

**Comment by DraconianBeryl** [comment]
I've encountered the same issue.

Playing the modpack "SetGameDifficulty Reika" on curseforge, modpack version 2.1.

I've added the mod "Real Time Clock", but have otherwise not changed anything in the mods or configs.

I've noted that the Lumafly being ticked is in a different location with each crash, and also isn't always in the list of forced entities in the crash report.  The stack trace always seems to be in BoP worldgen, though the specific function varies.

I've looked at the world data with MCEdit and there don't seem to be any Lumaflies saved in the world, implying that they are crashing either during, or immediately after, spawning.

A selection from the crash reports: https://pastebin.com/i0e8Wjy6

**Comment by DraconianBeryl** [comment]
I was able to return my game to a playable state by

1. Restarting and, when lucky enough to have the time, issuing the `/kill` command, I chose this as the shortest and easiest command to get me out of the area.
2. Once out of the area I issued the command `/gamerule doMobSpawning false` to turn off mob spawning.
3. Teleporting to the place where I died to recover my things
4. Teleporting back home
5. Issuing the command `/gamerule doMobSpawning true`

I plan to do further testing to see if I can identify any contributing factors.

**Comment by DraconianBeryl** [comment]
First test:

1. new world, survival, cheats enabled, BoP generation
2. switch to creative+ mode
3. use Nature's Compass to find nearest Mountain biome
4. flew up to an altitude of 303 blocks to be high enough to prevent any proximity-based mob spawning
5. flew over to Mountain biome and mapped it completely remaining at Y 303.
6. stopped flying - the sun was just setting
7. flew around the area at low altitude all night and through the next day
8. no lumaflies (Tunnel Nuker) spawned, no crashes
9. speculation that their appearance may be progression-based
10. ~~reconstructed my progress from my survival world~~
11. still no lumaflies or crashes

Edit: I've realized I didn't completely recreate my progress from the survival world

**Comment by DraconianBeryl** [comment]
Second test:

1. re-create my survival world, also survival with cheats enabled
2. changed mode to creative and started moving toward crash site
3. noted along the way that the relics spawn in the same area
4. zoomed up to Y>300 as I approached and flew over the region to generate all the chunks and check biomes
5. cataloged: Mountain, Chaparral, River, and Birch Forest
6. noted that the location where the crashes started happing after traversing the narrow width of the Mountain biome and was starting to transition to Chaparral
7. touched down at the same location as my first crash.  no crash.
8. noticed a lumafly downslope from me in the Chaparral biome
9. noticed a lumafly behind me in the Mountain biome
10. still no crash
11. started trying to recreate my CC progress and realized I hadn't done it right in the prior test
12. recreated most of my CC progress
13. progress obtained: HARVEST, SHOCK, NODE, CRYSTALS, BREAKSPAWNER, KILLMOB, DYETREE, BALLLIGHTNING, BEDROCK, NETHER, FINDSPAWNER, DEEPCAVE, RAINBOWLEAF, MINE, POTION, PYLON, RAINBOWFOREST
14. progress *not* obtained: ANYSTRUCT, SNOWSTRUCT
15. returned to crash site, found lumaflies, but no crash

**Comment by DraconianBeryl** [comment]
Third test:

1. Return to my survival world
2. make the walk back to the location where the crashes were happening
3. wander around
4. see lumaflies
5. do not crash

**Comment by DraconianBeryl** [comment]
So, in summary, I have no idea what was going on, unless the crashes depend on some condition that only happens when chunks generate.

**Comment by ianlavr** [comment]
The only way right now to fix it is to disable their spawn using Bad Mobs.
Example:
S:bannedMobs <
        ChromatiCraft.Tunnel Nuker
        example2
        example3
     >

**Comment by ReikaKalseki** [comment]
This is BoP's fault - I fail to see how tunnel nukers cause it beyond "they happened to be the thing that loaded that chunk".

**Comment by ReikaKalseki** [comment]
Turns out there was a minor oversight in them specifically. #3172
