### ISSUE TITLE
[Rotarycraft v31b] Grinder loses enchants when unloaded

### ISSUE THREAD

**Issue by Rubyheart** [ReikaKalseki/Reika_Mods_Issues#3135]
I right clicked a grinder with a fortune 2 book, it got the enchant, glowy, extra output, etc, but when changing dimensions, the enchant was gone.  I later applied fortune 5 to the same grinder, left the area without leaving the dimension, and the enchant was gone again.

**Comment by Goddfrey** [comment]
Apparently it's not about being loaded - chunk loading does not help.  v32b

**Comment by ReikaKalseki** [comment]
Fixed.
