### ISSUE TITLE
[Chromaticraft V31b] sneak opening book to see fragments shifts items 5+ over - shuffling inventory

### ISSUE THREAD

**Issue by DoomSquirter** [ReikaKalseki/Reika_Mods_Issues#3138]
ChromatiCraft 1.7.10 V31b
DragonAPI 1.7.10 V31b

been playing rev3 for about 2 weeks.  The last week I've been playing on a server because of the errors that ctd that you are aware of that disappear on the server.

I've had issues but the book worked fine.  I finally got a new progression (alloying) and sneak opened the book and all the items in my inventory got jumbled around.  

restarted client and server both and problem persists.

While looking into this, I decided to check my single player instance before I moved to a server and the book works fine there.

I have opened the book SEVERAL times while on server and not had this issue.  I am not sure when this started but it was within the last day.  

unrelated but maybe informative.  I have had some severe progression issues. I spent days trying to figure out why I couldn't finish the liquid chroma progression.  I made the chroma collector, got a bucket of liquid chroma from it, put it in world, walked in it, submerged in it, etc.  I never got the progression bump and thus couldn't get to boosted shards.  Finally I just did a /chromaprog command to give me that progression since I couldn't find help anywhere.  I continued on.  this was many days ago tho. I know for a fact that the book issue didn't happen after this since I put quite a few fragments into book afterwards.

**Comment by ReikaKalseki** [comment]
This is not happening for me, and I cannot imagine a mechanism by which it would be my doing, either.
