### ISSUE TITLE
personalized casting - server/client reboot and my "head" is now a skeleton skull

### ISSUE THREAD

**Issue by DoomSquirter** [ReikaKalseki/Reika_Mods_Issues#3139]
ChromatiCraft 1.7.10 V31b
DragonAPI 1.7.10 V31b

I just unlocked retroactive recognition and casting complex

I have the bug listed in #3138 

Somehow it corrupted my book because I got 3 fragments (repeater, crystal repeater and casting complex) and after "trying" to put them in the book, none of them showed up as pages

I removed all my items cept the book after restoring a backup from an hour prior.  I had personalized casting working and my skull was my skin's skull at that point.  

I added the three fragments and I have entries for all three which is great.  but my head's a skull and probably causing this issue:
I can't craft crystal repeaters (shows up like the other 2 issues here, shows the items in output with a red slash through it.

I know the personal casting directly relates to the crystal repeaters.  it's about the only thing I can think of that's blocking me here.

**Comment by DoomSquirter** [comment]
more info.  links are in rev3 discord which I know you are in reika

https://cdn.discordapp.com/attachments/768285772326764584/1074316258243248138/image.png
https://cdn.discordapp.com/attachments/768285772326764584/1074359727586299954/image.png

those 2 images are basically an hour or two apart.  nothing changed on server except I rolled back the world because of that bug previously mentioned.  

the fact that this is supposed to link to my user (uuid) and my skin's skull used to be associated with it and now it doesn't seem to know about my uuid, I am assuming the personalization is invalid or something.  just guessing here tho

on server, the /uuid command shows the correct uuid for me

**Comment by DoomSquirter** [comment]
so I made progression via relay source and can make crystal relays now.

but, it is still disconcerting that my head turned into a skull.  especially in a mod like this where everything is guesswork and no tangible hints are given freely.  One chooses to suspect every odd man out as a culprit in their circumstance.  I'm assuming now that the skull icon means nothing gameplay wise.  it is still strange tho

**Comment by ReikaKalseki** [comment]
The skull just means it failed to load your player skin.
