### ISSUE TITLE
Having DragonAPI suddenly changes TechReborn's Macerator hard recipe to easy

### ISSUE THREAD

**Issue by Rongmario** [ReikaKalseki/Reika_Mods_Issues#314]
https://github.com/TechReborn/TechReborn/issues/169

**Comment by Rongmario** [comment]
When the user installs the mods:
- IndustrialCraft #720
- TechReborn Latest (#896)
- Reika's latest installments of DragonAPI, RotaryCraft, ReactorCraft and Electricraft

TechReborn + IC2's Macerator recipe converts from Hard recipe into easy recipe even if config is written correctly.

**Comment by ReikaKalseki** [comment]
....How could I have interactions with a mod I have never heard of?

**Comment by Rongmario** [comment]
Seems like it's solved, sorry for the false alarm Reika ^^
