### ISSUE TITLE
[Chromaticraft v31b] Unknown Artefact can't be placed into an AE2 system

### ISSUE THREAD

**Issue by Rubyheart** [ReikaKalseki/Reika_Mods_Issues#3140]
Not for long anyway.  If I have an Unknown Artefact anywhere in my system, the power usage spikes randomly, and there never seems to be enough to keep it powered.  Removing the Artefact from the system lets it operate as expected. Unknown Fragments do not have this issue.

**Comment by Star4Fun** [comment]
I am pretty sure that this behavior is intended. If I remember correctly then there is a disk where they could be safely be stored.

**Comment by Rubyheart** [comment]
I seem to recall that as well, but I couldn't find the lexicon entry, and I just spent several days figuring out my power issues.  The book could really use a search feature.

**Comment by Rubyheart** [comment]
I apparently hadn't picked up an info fragment since discovering Unknown Artefacts, that's why I couldn't find it in my book.  The corrosion resistant cell is what I'm looking for.  Working as intended.
