### ISSUE TITLE
high pressure turbine isn't working 

### ISSUE THREAD

**Issue by squeakers0704** [ReikaKalseki/Reika_Mods_Issues#3141]
steam line has 65 kpa of steam at the turbine but the turbine wont. spin

**Comment by Kobra331** [comment]
65 KPA is way too low for a HIGH pressure turbine, how long should it spin? 0,5 seconds?
Additionally check if it has lube in it.

The last condition is the source: Some kind of Reactors cannot be used for a HPT, the pebble bed reactor for example or the solar tower.

**Comment by ReikaKalseki** [comment]
^
