### ISSUE TITLE
[DragonAPI] Massive Console Spam with Matter Overdrive?

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#3145]
https://gist.github.com/Shahelion/a208d7198028d8a969612c9c7dd1d347

Why

**Comment by ReikaKalseki** [comment]
The handler is outdated - where do I find your jar?

**Comment by Shahelion** [comment]
https://www.curseforge.com/minecraft/mc-mods/matteroverdrive-17-edition/files/2331162

**Comment by ReikaKalseki** [comment]
This should be fixed.
