### ISSUE TITLE
How to add Netherlicious ores to MeteorCraft?

### ISSUE THREAD

**Issue by nicogranelli** [ReikaKalseki/Reika_Mods_Issues#3148]
Hello!

I'm trying to add a couple of ores from Netherlicius to the nether type meteor. The error I'm getting is:

`[17:48:40] [Client thread/ERROR] [FML]: METEORCRAFT ERROR: Malformed custom ore entry [Cannot have entries with no corresponding ores!]: 'netherlicious:NetherIronOre, 5, 1, oreNetherIron'`

I tried several differnt ways: 

```
//this doesn't work
netherlicious:NetherIronOre, 5, 1, oreNetherIron
//this doesn't work
Nether Gold Ore, 10, 1, oreNetherGold
//this one work
Efrine Ore, 1, 1, oreEfrine
```

netherlicious doesn't add its ores to oreNetherIron nor oreNetherGold oredics. I tried to add them myself (with craftweaker), and also tried with custom oredicts created by me. Nothing seems to work.

I can use oreIron and oreGold, but that will use a random selectron from every gold ore, including Atum 2 for example. That ends up as a really ugly nether meteor. 

![2023-03-21_17 59 09](https://user-images.githubusercontent.com/406462/226739514-52e29b36-58ea-4ec3-8de9-f50235fc3494.png)

I'm using the last version of anything, in a personal pack.

**Comment by nicogranelli** [comment]
versions used:

* DragonAPI 1.7.10 V31b.jar
* MeteorCraft 1.7.10 V31a.jar

**Comment by ReikaKalseki** [comment]
Use the custom ore config - but this will not work , but be aware it is changing to LuaBlock in v32.

Your issue seems to be because the ores are not being added to the OreDict under any tag - and CraftTweaker does so too late to matter - but the new system can also take direct item names, solving the issue.
