### ISSUE TITLE
[Chromaticraft v32a, DragonRealm] StackOverflowError when combining Flux Pod and Redstone Flux Distributor

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#3151]
Placing a Flux Pod on a Redstone Flux Distributor with power flowing between the two results in a crash that makes the world unplayable until the offending blocks are removed via MCEdit.

https://pastebin.com/6Cn1VsUE

**Comment by ReikaKalseki** [comment]
Fixed in v32.
