### ISSUE TITLE
A lot of machines does not keep fluids/items when harvested

### ISSUE THREAD

**Issue by koravel** [ReikaKalseki/Reika_Mods_Issues#3154]
Why do machines not keep their inventory after being harvested?

It seems that you fixed it here for IC2: https://dragonrealm.overminddl1.com/chgqol.php
"Storage blocks keep 100% of their energy when broken"

But why not do this in your own mod?

**Comment by ReikaKalseki** [comment]
Because I do not want them to, and it is not how vanilla or 99% of mods do it, either.

**Comment by koravel** [comment]
@ReikaKalseki Oooook, understood.
