### ISSUE TITLE
[DragonAPI] Mods removal had broke world entirely

### ISSUE THREAD

**Issue by koravel** [ReikaKalseki/Reika_Mods_Issues#3155]
After deleting:
DragonAPI 31b
ElectriCraft 31a
MeteorCraft 31a
ReactorCraft 31b
RotaryCraft 31b
TreeClimbing 31a
VoidMonster 31a

Server is not starting. Here's error log: https://pastebin.com/CkwT4avg

After testing it on clean server with just DragonAPI got the same crash: https://pastebin.com/zeQr06Mx
This problem had been seen a lot time ago since versions 2xx.

**Comment by chotke** [comment]
There is no point in deleting core mods but there is some info:
https://reikakalseki.github.io/minecraft/index.html

**Comment by ReikaKalseki** [comment]
This is what happens when you do not read the information on the front page.

**Comment by koravel** [comment]
@ReikaKalseki Then its place is on CurseForge mod page instead of "Information for Developers", not only on the site.

**Comment by ReikaKalseki** [comment]
The site is the place where you are meant to get the information. And it is not on the DAPI page, it is on the front page of the entire MC section of my site.

**Comment by koravel** [comment]
@ReikaKalseki It is on you to choose after all, my point is - duplication is a good thing, current state of providing info is not intuitive enough. Of course the one should go to the website, but I think it worth at least warning, or something like that:

```
More information can be found on my site:
https://reikakalseki.github.io/minecraft/index.html
Please, read important notes in case you have troubles.
```

Not many mods or modders have its own website, and as consequence someone like me does not expect something valuable to be found
