### ISSUE TITLE
[ReactorCraft] Weird crash with uranium processor and Thermal Expansion fluiduct

### ISSUE THREAD

**Issue by koravel** [ReikaKalseki/Reika_Mods_Issues#3156]
Destroying fluiducts that contain sulfur hexafluoride does not decrease the amount of liquid stored in the remaining connected pipes
(e.g. you have placed 3 ducts, fill them up to 9000mB and then remove one pipe - remaining two will still show to be containing 9000/6000mB)
After uranium processor tries to fill such overflowed fluiduct - client-side render crash happens.
Log: https://pastebin.com/240ZWLQE

Also, there was random server crash that happens during another test: https://pastebin.com/T8EJz3E6.

I have encountered this problem since 2xx versions.

**Comment by ReikaKalseki** [comment]
The first is fixed; The second error has nothing to do with me.

**Comment by koravel** [comment]
@ReikaKalseki Thank you! The second one obviously not related, my bad.
