### ISSUE TITLE
[RotaryCraft] Visual glitch with Rotarycraft tile entities near hydrogenerator

### ISSUE THREAD

**Issue by koravel** [ReikaKalseki/Reika_Mods_Issues#3157]
When hydrogenerator have a block of water above it and flow water is blocked by piston, all machines are randomly showing axis lines and coloured sides. Also gearboxes render turns into wooden.

Like this one:
![image](https://user-images.githubusercontent.com/26851016/232247321-944e034d-6470-45e2-aec5-d1001c4d02d6.png)

In this case pistons are located near source blocks of water and water is falling down. But, this happens also if no floating water is present.

Mods presented:
https://pastebin.com/QMqfTHdJ

**Comment by ReikaKalseki** [comment]
This is on my FAQ. Which makes for a second issue you report after having pointedly not read the site.

**Comment by koravel** [comment]
@ReikaKalseki Found it. Again, why should I, and how could I know it was there. I have no desire to search the entire site for the one little peace of info. Some kind of "If you have issues/problems, procced to X point" should be on curseforge pages or at least at main page of the site. Just reroute pointless complains at the beginning. "More information can be found" does not tells you that there is some valuable info. Again, provide some pictures so someone like me can be 100% sure that this is it and this is not an issue.
