### ISSUE TITLE
[RotaryCraft] Some items are not searchable via NEI GUI

### ISSUE THREAD

**Issue by koravel** [ReikaKalseki/Reika_Mods_Issues#3161]
Shaft cross is not searchable, though it is presented in "Rotarycraft Power" creative tab:
![image](https://user-images.githubusercontent.com/26851016/232251165-ab3f5c28-6541-4101-89ba-a172f6f84477.png)

Items present in creative tabs are also not searchable: infinite industrial coil, pre-filled reservoirs, magnetized shaft core, pre-filled fluid compression chamber, magnetized magnetic coil upgrade, magnetostatic engine tier 5 and pneumatic engine tier 5
![image](https://user-images.githubusercontent.com/26851016/232251279-1f18e3a0-bb5d-49b9-b897-666382c0f2fa.png)

**Comment by ReikaKalseki** [comment]
A couple of those - eg the upgrade - *do* show up, and the others are not shown because does *anyone* actually like there being 300 pages of "tank, now with fluid #183" in their NEI?

**Comment by koravel** [comment]
@ReikaKalseki Yes, the mentioned items does not show up. I can agree that fluid compression chamber is not a necessity, but grabbing every time infinite coil and upgraded magnetostatic engines from creative tab was not a satisfying experience. Especially when I messed up with mods and my mid-click was not working.

Also, I like these pre-filled reservoirs, after all I can disable them for showing. But this is more like a personal preference.

My main complain was about all tiers of magnetostatic engine, and an infinite coil, these ones are pretty usable in debug situations. If someone did not like it, they never had built fusion reactor.
