### ISSUE TITLE
[ReactorCraft] Handbook lacks some information and is hard to navigate

### ISSUE THREAD

**Issue by koravel** [ReikaKalseki/Reika_Mods_Issues#3162]
Multiblocks schematic are located in "Structures" with no links to it. Table of contents does not have any link to page 3. It will be more logical to place this information into according pages, such as "Hydrogen preheater",  "Turbine generator" etc.

Next, there's all info we have about electrolyzer:
![image](https://user-images.githubusercontent.com/26851016/232252334-826cbe66-fbf8-4478-9501-61b01583c32b.png)
There's no info about temperature that is required to electrolyze water and rad/s|Nm for van de graaff generator.

**Comment by ReikaKalseki** [comment]
Water does not *have* a minimum electrolysis temperature and the VDG is an RC machine - why would the *ReC* book list that information?

And no, that is not "all the information you have", either: ![https://i.imgur.com/kciXuG0.png](https://i.imgur.com/kciXuG0.png)

**Comment by koravel** [comment]
@ReikaKalseki Maybe I told it in a false manner. I mean that there is no info about VDG, the trial&error path in this case was not very clear, at least for me.
