### ISSUE TITLE
[Rotarycraft] Engines' upgrades are not described in handbook

### ISSUE THREAD

**Issue by koravel** [ReikaKalseki/Reika_Mods_Issues#3163]
1-5 tier upgrades for magnetostatic engine are not shown, so the only way to upgrade it is guessing.
It is unknown, according to the handbook, how to upgrade the pneumatic engine.

Also, there is no description of performance engine upgrade and that it can upgrade gasoline engine to performance engine.
The name of the item shows that this is an upgrade for performance engine, not the gasoline one.

**Comment by ReikaKalseki** [comment]
Done. Added to the tooltip, too.

**Comment by koravel** [comment]
@ReikaKalseki Thank you! That was nice one)
