### ISSUE TITLE
[RotaryCraft] Handbook page of the pipe pump is not descriptive enough

### ISSUE THREAD

**Issue by koravel** [ReikaKalseki/Reika_Mods_Issues#3166]
There's no description about how much power is required to increase pressure by 1MPa.
![image](https://user-images.githubusercontent.com/26851016/232254451-663b1c32-5bb0-436e-8011-bad03f88d4ab.png)

**Comment by rogerwim** [comment]
Or in fact it's use on steam line

**Comment by koravel** [comment]
@rogerwim I tried it and it really works for steam lines lol. It give me a much easier control over high-pressure turbines in bond with fusion reactor, thank you for information.

**Comment by ReikaKalseki** [comment]
Why would you need to know the specific amount of power to achieve a given pressure differential? This is not useful information.

**Comment by koravel** [comment]
@ReikaKalseki Because then I can calculate how long can be the pipe at a specific point. 

My case: I have a little distant lake and I want to make here a pump station. It is kind of RP, of course I can just make a lake near the consumer. Here are some difficulties arises. I don't know how long can be pipe to satisfy 4 steam engines, or 4 combustion engines. As I remember, increasing power supply on a water pump would do nothing, so I can use a pipe pump. But, the knowledge of a minimum amount of power needed to deliver enough pressure is achievable only through dozens of repeatable tries. And I must do it for every different configuration of my system. So, some kind of alternative to mb/t, but with Pascal unit would be appreciable. That also relies to #3174, as I said - no info about fluid mechanic, nor about pipe pump coefficients.

Also, what about usage with steam lines? Should I have a lucky guess that "pipe" pump works with steam lines? And don't said that steam like "obviously" can be treated like usual pipe, as they have different mechanics.
