### ISSUE TITLE
Chromaticraft Ticking Pylon Crash

### ISSUE THREAD

**Issue by Darkpixel797** [ReikaKalseki/Reika_Mods_Issues#3169]
I crashed in my creative world just  while flying around, it generated two blank crash reports, one for the client and one for the server, and when I attempted to restart the game and reload into the world  it crashed again, only the server this time, and with actual text complaining about chromaticraft.
[crash-2023-04-17_15.17.35-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11255117/crash-2023-04-17_15.17.35-server.txt)

**Comment by ReikaKalseki** [comment]
This very much looks like corrupted world data.
