### ISSUE TITLE
[Dragon Realm] Config to disable or turn down radiation poisoning

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#3173]
I believe one of the additions to the dragon realm pack is players being poisoned by being near radioactive ores, but the effect is so intense that you end up not being able to jump up any blocks and instantly drained down to 3 hunger bars whenever you get near any radioactive ore. This seems quite extreme especially considering the modpack changes states "Radioactive ores now give very weak radiation effects to nearby entities." A way to either turn off this effect in the config or turn it down would be greatly appreciated.

**Comment by ReikaKalseki** [comment]
I think that *is* a config.

**Comment by DFliyerz** [comment]
I couldn't find anything in the config file, what is the option called?

**Comment by voidentente** [comment]
B:"Make Fuel Ores Weakly Radioactive" in ReactorCraft.cfg
