### ISSUE TITLE
[RotaryCraft 31b] Hanbook does not contain any information about Pascal unit

### ISSUE THREAD

**Issue by koravel** [ReikaKalseki/Reika_Mods_Issues#3174]
Pascal unit and related physics are not described in the book, and there is no info about correlation between pressure, flow speed and amount of liquid, i.e. stored in the pipe(-s). And so, there is no ability to predict pressure behaviour.

**Comment by ReikaKalseki** [comment]
Flow speed has no relationship to pressure in RC pipes and explaining what basic units - that are not required to understand the deep meaning of beyond their magnitudes - is not the place of the book.
