### ISSUE TITLE
[Reactorcraft 31b] Centrifugal fluid extractor requirements

### ISSUE THREAD

**Issue by koravel** [ReikaKalseki/Reika_Mods_Issues#3175]
There's no info about type of water blocks required above the centrifuge - source of flowing. 
There is also no info that extractor requires 3x3 area around and all the way above itself to be water source blocks to be functional.
If we block any of the corners - pump will not work:
![image](https://user-images.githubusercontent.com/26851016/233848372-18efa001-e11f-4547-94e3-39345154f825.png)
But, according to the book, we have to leave free "at least three sides in contact with" :
![image](https://user-images.githubusercontent.com/26851016/233848427-0700ba41-9bbd-4327-8171-2e1e1997206f.png)

**Comment by ReikaKalseki** [comment]
This was originally present but got lost in the conversion from being purely heavy-water focused: ![https://i.imgur.com/W9xgzOz.png](https://i.imgur.com/W9xgzOz.png)

**Comment by koravel** [comment]
@ReikaKalseki So, I believe now it is present. Thank you!
