### ISSUE TITLE
[RotaryCraft 31b] Crash with CoFH Core

### ISSUE THREAD

**Issue by koravel** [ReikaKalseki/Reika_Mods_Issues#3176]
As it is known, CoFH Core 3.1.4-329 has an outdated Thaumcraft API, which leads to a crash if combined with RotaryCraft 31b.
In my case I had to install Thaumcraft in my modpack just because its presence prevents this crash.

Crash: https://pastebin.com/vPj6vHAp

I suggest creating a config toggle for Thaumcraft integration in RotaryCraft.

**Comment by koravel** [comment]
After investigating another issue #2558 
I see that problem is not in the API, but still, is it possible to add an on/off switch for TC integration during pre-init/init phase?

**Comment by ReikaKalseki** [comment]
The issue is that some other mod is including the TC API and tricking the game into thinking part of TC is installed.

**Comment by koravel** [comment]
@ReikaKalseki Definitely it is, and we all don't like workarounds. But reality is that nor CoFH Core nor any other mod with this issue would update 1.7.10 versions to fix that. I suggest do this just for easier integration, especially in cases when you do not need Thaumcraft at all.
