### ISSUE TITLE
[Dragon API 31b] Black screen, shaders problem

### ISSUE THREAD

**Issue by koravel** [ReikaKalseki/Reika_Mods_Issues#3177]
Starting MC just with Dragon API, without ANY mod at all (regardless of Optifine) leads to a black screen.
![2023-04-23_19 12 15](https://user-images.githubusercontent.com/26851016/233851315-ca9ee901-2622-4eef-9e3c-6afe6b6d707f.png)

It happens only during the first world loading, after which the glitch disappears.

Minecraft logs repeat the same OpenGL error when this glitch happens:
`[Client thread/ERROR] [FML]: DRAGONAPI ERROR: GL ERROR 1282: FB #1 was unrecognized (status=36053)`

**Comment by MalTeeez** [comment]
This seems like #2315 although apparently not fixed

**Comment by jeremiahwinsley** [comment]
I can reproduce this consistently, happens on every restart, with a larger modpack. As in #2315 maximizing fixes the issue temporarily. Anything I can do to help diagnose the issue?

**Comment by ReikaKalseki** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2315 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2495 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2260 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2368 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2440 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2460 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2606 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2610 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2516 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2641
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2826
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/3068

**Comment by koravel** [comment]
@ReikaKalseki If you won't fix it, this info should go to important notes to the website to prevent people from asking or arguing

**Comment by XenonDB** [comment]
Actually this issue can be resolved by setting "enabled=false" in config/splash.properties
This will disable startup loading screen.
In large pack, disabling this will cause player not able know whether game is halt or not and cause bad user experience. (The screen may only show Mojang logo for minutes)
An alternative way to add back the loading screen is adding Custom Loading Screen (which name is Better Loading Screen before 1.12.2)
It provide loading bar when game starting without enabling splash.

So this might be a way to fix this issue while keeping good user experience.
