### ISSUE TITLE
[RotaryCraft 31b] Pump destroys water sources

### ISSUE THREAD

**Issue by koravel** [ReikaKalseki/Reika_Mods_Issues#3178]
Pump destroys water sources after a while because it consumes corner blocks.
I assume that "Free Water Production Factor" option set to "1.0" should mitigate that.
Otherwise, settings file lacks explanation of what exactly this option does.

**Comment by ReikaKalseki** [comment]
Water in corners should regenerate, unless you mean 1-wide dead-ends, in which case yes, and that is a failure of your pool design.

**Comment by koravel** [comment]
@ReikaKalseki It was rectangle 7x7x1(XZY) pool

**Comment by ReikaKalseki** [comment]
Those will regenerate, so long as they are chunkloaded.
