### ISSUE TITLE
[DragonAPI 31b] No settings description 

### ISSUE THREAD

**Issue by koravel** [ReikaKalseki/Reika_Mods_Issues#3179]
What do the following parameters do?

- "[EAE994752] Enable Temporally Dependent Amusement Behavior"
- "[D35216698] Debug Overlay Key (LWJGL ID)"
- "Sync Packet ID"
- "Log Sync Packet CME Avoidance"
- "Slow Sync Packets - Only use this as a last resort"
- "Check Environment Sanity"
- "Attempt to Repair Environment Sanity"
- "Use HashMap for Sound Categories - Only use if necessary"
- "Automatic Reboot Interval (Seconds)"
- "Extra Block Ticks When Raining"
- "Player-Specific Mob Caps"

- "Bytecodeexec command user UUID whitelist"
- "Bytecodeexec command notifies other admins"

There's confusion and uncertainty in following config settings:

- "Biome Humidity Dependent Fire Spread" - some details maybe?
- "Automatic Collection of Inventories; set to 'NULL' to disable" - only Reika's mod TEs' inventories or ALL inventories? What do you mean by "Automatic Collection"?
- "AFK Timer Threshold (Seconds); Set to 0 to Disable" - does this one correlate with "Prevent Mobs From Targeting Players Immediately After Logging In"?
- "Prevent block spreading near unloaded chunks" - I can probably guess what this is, but can't be certain

- "Expected Approximate Maximum World Size (Radius)" - for what purpose? OreGen, mob spawning, weather, humidity, biome related stuff???
- "Expected Approximate World Center Location X" - same
- "Expected Approximate World Center Location Z" - same

*_PackModifications.cfg files - these are not listed anywhere, neither on CurseForge, nor on your website. 
What if someone isn't interested in looking into it? They will just not know about warning inside. 
Why not post info for modpack creators on the main page and on Curseforge mod pages as well?

**Comment by voidentente** [comment]
Maybe all these documentation-related issues should get a central parent issue for coordination?

**Comment by ReikaKalseki** [comment]
This is something that should best go on the site.
