### ISSUE TITLE
DragonAPI TinkerToolHandler crash

### ISSUE THREAD

**Issue by MJRLegends** [ReikaKalseki/Reika_Mods_Issues#318]
Dont know if this is just a memory crash and not a problem but here is a link to the issue over at my mod pack's issue tracker https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/69

**Comment by ReikaKalseki** [comment]
What kind of TiC tool was being used at the time (or was any)?

**Comment by MJRLegends** [comment]
A tinkers axe

**Comment by ReikaKalseki** [comment]
Of what type?

**Comment by MJRLegends** [comment]
I dont know the person who reported it to me didnt say.

**Comment by ReikaKalseki** [comment]
I need to know.

**Comment by OneEyeMaker** [comment]
Have the same crash (http://pastebin.com/vLfTVbwE)
It occurs when players make left click with tool (from ANY material), that hasn't left-click action. For example, I got this crash when I clicked block of dirt with Signalum Crossbow, Berdock Javelin or another TiCon weapons, that act on right click.

And I think, that this problem can be associated with https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/293

P. S. Sorry for my English, I'm from Russia.

**Comment by ReikaKalseki** [comment]
It has nothing to do with left-click actions.

**Comment by OneEyeMaker** [comment]
@ReikaKalseki, see here: https://github.com/ReikaKalseki/DragonAPI/blob/master/ModInteract/ItemHandlers/TinkerToolHandler.java#L568

Firstly you try to get tool from map, secondly you try get tool part. But this crash happens with weapons (wepon != tool, as I understand) => this map doesn't contain weapons => NPE.

Any weapon hasn't left click action, as you said. But this method (https://github.com/ReikaKalseki/DragonAPI/blob/master/ModInteract/DeepInteract/TinkerMaterialHelper.java#L77) overrides this event.

If I understand correctly, you should split code for tool handling and weapon handling.

**Comment by ReikaKalseki** [comment]
OK, this is an easy fix. How do I tell a tool from a weapon based on the ItemStack?

**Comment by OneEyeMaker** [comment]
Excuse me, I didn't understand last quesion...

**Comment by ljfa-ag** [comment]
He doesn't know how to see if some item is a tool or a weapon.

All the different tool/weapon types have different item IDs, and their items are instances of different classes: https://github.com/SlimeKnights/TinkersConstruct/tree/master/src/main/java/tconstruct/items/tools

**Comment by ReikaKalseki** [comment]
That does not help me. All of the tools ultimately inherit from ToolCore, which is the class DragonAPI looks for. Unless there is a common parent to all tools, and a different common parent to all weapons, I need a different way of identifying them.

**Comment by MJRLegends** [comment]
Whats even the point of the TinkerMaterialHelper? @ReikaKalseki

**Comment by ReikaKalseki** [comment]
It is how I add custom Tinker tools.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by MJRLegends** [comment]
When will the update be out @ReikaKalseki as i would like to add it before releasing the next update for my mod pack

**Comment by ReikaKalseki** [comment]
Not today.
