### ISSUE TITLE
[RotaryCraft 31b] No settings description

### ISSUE THREAD

**Issue by koravel** [ReikaKalseki/Reika_Mods_Issues#3181]
There are uncertainties in following config parameters:
- "[R8B16664A] Reload Handbook Data on Open" - reload for what purpose? what will change?
- "[RD7460182] Run power transfer code on client" - what are the reasons and consequences of this?
- "Difficulty Control" - and what will it change?
- "Machine Warning Alarms" - does it make machines finally warn you that they have no water and are dangerous?
- "EMP Charging Speed" - in what units? Ticks, ms, sec, min, h?
- "Chest Generation Tier" - what does this affect?
- "Fluid Flow Speed" - in what units? maybe something related to pressure? Related to #3174 
- "Hardmode Gravel Gun" - what does it do? Increases/decreases damage/cost of ammo/gravel gun itself?
- "Hard Mode EU Compatibility" - same question
- "Power Converter Loss Percent" - is it for any power converter (e.g. RF, EU, PNEUMATIC)
- "Streams Waterfall Min Height for Max Hydrokinetic Yield" - is it integration with Streams mod?
- "Free Water Production Factor"=1.0 - what exactly changes with the value here? Related to #3178

Which materials should/can I put in these?
- "Alternate Blast Furnace Materials"
- "Bedrock Armor Gating Material"
- "Gravel Gun Gating Material"

Which exact group of recipes do these options allow/disallow:
- "Allow Nonstandard Recipe Modifications"
- "Strong Recipe Editing"
- "Core Recipe Editing"

RotaryCraft_CustomGPRColors.cfg - what can I do with this settings file? What format should I use?

**Comment by ReikaKalseki** [comment]
While your core point is valid, putting these as a dozen different issues borders on spam, especially when this issue tracker is not the place for any of them. I am going to close all of them, and if you want them addressed, collect them all in *one* place and send it to me via one of the platforms listed on my site (go ahead and post here that you did that).

**Comment by koravel** [comment]
@ReikaKalseki kk
