### ISSUE TITLE
[DragonRealm] Tried to access energization manager from client!

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#3187]
I get this crash a lot when using either the ritual altar or casting table. So far it's crashed almost every time the repeater network is called, but it usually is done charging once I restart the game. I've attached a couple of error logs, the more recent one is using the ritual altar and the slightly older one is using the casting table:

[crash-2023-05-02_08.58.56-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11375693/crash-2023-05-02_08.58.56-server.txt)
[crash-2023-05-02_08.54.33-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11375694/crash-2023-05-02_08.54.33-server.txt)

**Comment by DFliyerz** [comment]
Also it might be worth noting that my lumen tree has no problems requesting energy from any of my pylons.

**Comment by DFliyerz** [comment]
It seems to be getting worse over time, my world is nearly unplayable now.

**Comment by ReikaKalseki** [comment]
This is an old DR feature that I largely abandoned, and is not enabled by default. I suggest disabling it.
