### ISSUE TITLE
[DragonRealm/Cave Control] Crash related to world gen

### ISSUE THREAD

**Issue by DFliyerz** [ReikaKalseki/Reika_Mods_Issues#3189]
Even though I'm just hanging around my base which was fully generated a long time ago, I'm getting this crash consistently which mentions Clime Control and Cave Control
[crash-2023-05-05_19.08.32-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11410999/crash-2023-05-05_19.08.32-client.txt)

**Comment by ReikaKalseki** [comment]
#3215 #3205
