### ISSUE TITLE
[Chromaticraft v32a] An Abandoned Puzzle does not give progress flag

### ISSUE THREAD

**Issue by Mettymagic** [ReikaKalseki/Reika_Mods_Issues#3191]
Spent multiple hours completing the magic outpost structure (and i even broke the colored locks in creative, i have NO IDEA how anyone is expected to do the combination lock without that) but did not get any progress upon completing the puzzle and breaking the glowing node. Low priority since the progression doesn't actually lead to anything and isn't mandatory.

**Comment by EyeDeck** [comment]
Same for me when I did it a few months ago, no progression flag.
I also punched some shortcuts in creative, because the one I had was 25 notes and required like 15 lock changes.

**Comment by Mettymagic** [comment]
> I also punched some shortcuts in creative, because the one I had was 25 notes and required like 15 lock changes.

How does the song combination even work? I just brute forced it lol

**Comment by EyeDeck** [comment]
Oh, yeah, you need the structure debug crystal thing in your hand to get the melody to play.

**Comment by ReikaKalseki** [comment]
Fixed in v32.
