### ISSUE TITLE
[Chromaticraft v31b] Game crashes on startup

### ISSUE THREAD

**Issue by TheFieryFalcon** [ReikaKalseki/Reika_Mods_Issues#3192]
https://gist.github.com/TheFieryFalcon/e2194352648eba037ef8061ad4e9c718

**Comment by MalTeeez** [comment]
The log you have provided does not indicate a crash, could you maybe provide one from "crash-reports" regarding your crash

**Comment by TheFieryFalcon** [comment]
https://gist.github.com/TheFieryFalcon/983b791aaabdecf183c34223f81b098e
Note: this crash does not say it's because of chromaticraft, but the logs told me to report this immediately

**Comment by Shahelion** [comment]
The problem is with Et Futurum. I had this same issue, disabling the enchantments from that mod fixed it. I do not know what is causing it yet, but that is a temporary solution. It seems to be an interaction with some other mod.

**Comment by ReikaKalseki** [comment]
I do not see how this could be my doing either. I do not ASM that class.
