### ISSUE TITLE
[RotaryCraft V31b] ClassCastException in Deobfuscated Environment

### ISSUE THREAD

**Issue by voidentente** [ReikaKalseki/Reika_Mods_Issues#3194]
**Where**: Forge Development Environment

**What**: `java.lang.ClassCastException: Reika.RotaryCraft.TileEntities.Processing.TileEntityGrinder cannot be cast to li.cil.oc.api.network.Environment`

**When**: Calling runClient while RotaryCraft is loaded (either as mod or as library)

**Setup**: All mods/libraries are deobfuscated using BON2. RotaryCraft as well, but after stripping it of its digital signature so it would work, it behaves the same as the non-deobfuscated RotaryCraft jar.

When only running DragonAPI V31b and RotaryCraft V31b, ClassNotFound ItemScrewdriverFocus throws.
This is fixed by adding the mods Railcraft and Chisel. Then, ClassNotFound TeleposeEvent throws.
This is fixed by adding Blood Magic. Then, ClassNotFound EMCRemapEvent throws.
And that is fixed by adding ProjectE... which then in turn throws ClassNotFound LuaException, which is fixed by adding ComputerCraft. Which then again throws ClassNotFound SidedBlock, which is fixed by adding OpenComputers. Which *then* throws ClassNotFound LootDiskProgrammableRecipe, which is fixed by adding Buildcraft! Which then finally ends my little scavenger hunt with a very blunt `ClassCastException: Reika.RotaryCraft.TileEntities.Processing.TileEntityGrinder cannot be cast to li.cil.oc.api.network.Environment`.

It doesn't seem to matter whether I deobfuscate the mods up-front or run them through CCC. It also doesn't seem to matter whether I load RotaryCraft as mod or as library. The full log is at https://pastes.io/odlwu8uviu.

I know that the live development environment is not a prime support target, but it seemed a little weird to me to have RotaryCraft behave so weirdly while DragonAPI just... worked.

Edit: Well, Pastebin insta-deleted my paste twice in a row. So much for that.

**Comment by voidentente** [comment]
Related: #3133, #630

Why aren't the access transformers (DragonAPI_at.cfg) and the dependency list publically available?

Edit: The ATs are in META-INF and being loaded.

Edit 2: Link to the line that fails. https://github.com/ReikaKalseki/DragonAPI/blob/268f209b15d3e2572ed0674cff7c75375fbb061d/Base/TileEntityBase.java#LL985C3-L985C3

**Comment by voidentente** [comment]
This seems to work: compile files("./lib/OpenComputers-MC1.7.10-1.7.5.1356-api.jar")

**Comment by voidentente** [comment]
Ah, that's funny.

```
TERRAFORMER failed to instantiate its TileEntity of class Reika.RotaryCraft.TileEntities.World.TileEntityTerraformer
Contact Reika immediately!
```

```
Include the following information:
	at Reika.RotaryCraft.Registry.MachineRegistry.createTEInstanceForRender(MachineRegistry.java:1400) ~[MachineRegistry.class:?]
	at Reika.RotaryCraft.Items.Placers.ItemMachinePlacer.getSubItems(ItemMachinePlacer.java:239) ~[ItemMachinePlacer.class:?]
	at net.minecraft.creativetab.CreativeTabs.displayAllReleventItems(CreativeTabs.java:326) ~[CreativeTabs.class:?]
	at Reika.DragonAPI.Instantiable.GUI.SortedCreativeTab.displayAllReleventItems(SortedCreativeTab.java:47) ~[SortedCreativeTab.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.setCurrentCreativeTab(GuiContainerCreative.java:508) ~[GuiContainerCreative.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.mouseMovedOrUp(GuiContainerCreative.java:482) ~[GuiContainerCreative.class:?]
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:354) ~[GuiScreen.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.handleMouseInput(GuiContainer.java) ~[GuiContainer.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.handleMouseInput(GuiContainerCreative.java:598) ~[GuiContainerCreative.class:?]
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:313) ~[GuiScreen.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1731) ~[Minecraft.class:?]
	... 11 more
```

Edit: This happens when opening either the RotaryCraft and RotaryCraft Power creative menus.
All other menus are unaffected.

Edit 2: It seems that while the mods build, APIs are still missing. For example, when building the Block Breaker, it throws a `NoClassDefFoundError: biomesoplenty/api/biome/BOPBiomeDecorator`. Is there an official list of all APIs required?

Edit 3: Gear box, not block breaker.

**Comment by voidentente** [comment]
Well, the Terraformer error just fixed itself. Somehow. I don't know how.

Edit: Guess that closes this issue. For anyone wondering how to use DragonAPI/RotaryCraft/ReactorCraft as library, see my repo https://github.com/voidentente/forge-1.7.10-offline-template

**Comment by MajgerOut** [comment]
Hi i dont Know if u get this message but excuse me for maybe bad english writing skills (Im German) but i wondered if there is a possability if u could/can update ur mods maybe to 1.19.2 because im such in love with the multi Structures and im building a Modpack but it is in 1.19.2 and as we know we cant just mix diffrent versions of minecraft mods. Ur Mods are really nice, I hope u have a great day.    -Daniel

**Comment by MalTeeez** [comment]
Reika himself has written something about this topic on his website: https://reikakalseki.github.io/minecraft/pages/info/updating.html @MajgerOut

**Comment by voidentente** [comment]
The "pls update" requests really will never end, huh?

Completely wrong place to start that issue. I think that Reika will probably not port his mods to newer versions anytime in the future, and since they are so complex, I don't think anybody would want to do that without his support.
