### ISSUE TITLE
Config options for Reactorcraft ores

### ISSUE THREAD

**Issue by brandyyn** [ReikaKalseki/Reika_Mods_Issues#3197]
i've added all the reactorcraft ores to the nether in my pack and used a resourcepack to retexture them to a nether version- but the problem is, i can't get rid of the ores spawning in the overworld. I've tried turning ore density percentage to "0" and "-1" but the ores still spawn, and likewise with the "generate (ore) even if other mods do", what can i do? or is there any hope for a config option for me?
i moved all magic ores to the twilight in my pack, i'm trying to have each dimension represent a theme.

**Comment by ReikaKalseki** [comment]
They cannot be disabled, because there is no way for ReC to know that they have another mod generating them.

**Comment by brandyyn** [comment]
@ReikaKalseki there could be a check to see if any or all of the ores generate in nether and disable the overworld generation in turn, it could also just be a config option for us pack devs that want to do that? not having this option means I can’t really include reactorcraft in my pack and I’d really like to. I’m sure there’s a solution that fits us both. Please consider.

**Comment by ReikaKalseki** [comment]
There is no such thing as "check if they generate in the nether". How would ReC detect an entirely separate mod being set up to generate its blocks?

**Comment by brandyyn** [comment]
> There is no such thing as "check if they generate in the nether". How would ReC detect an entirely separate mod being set up to generate its blocks?

I’m just using COFHWorld. It could just check that mods configs, specifically for my pack?

**Comment by ReikaKalseki** [comment]
And then someone else using some other mod asks "just add a check for that mod". And then some other person does the same for a third mod. And then one of those mods ends up having three versions people use, all with different internal structures.

This is a lot of work for zero benefit.

**Comment by brandyyn** [comment]
> And then someone else using some other mod asks "just add a check for that mod". And then some other person does the same for a third mod. And then one of those mods ends up having three versions people use, all with different internal structures.
> 
> This is a lot of work for zero benefit.

Or pack creators can have the option to turn off ore generation so this isn’t a problem for either you or the pack creators

**Comment by ReikaKalseki** [comment]
I do not *want* people being able to just turn off the ore generation. That is how people make ReC impossible and I get spurious bug reports. That is what happened before I locked this system down.

**Comment by brandyyn** [comment]
I think it’s pretty elegant to have a universal toggle for all ore generation to be off in reactorcraft so that it’s obvious to the player that if no ores are spawning it’s a pack decision. I think this is a huge limitation and I don’t see any issue that would arise in my implementation of moving ALL of the reactorcraft ores to the nether. Perhaps you could add that as it’s own config option, just to move the ores to the nether, I’ve already done the retexturing.

**Comment by brandyyn** [comment]
@ReikaKalseki again i'd like to suggest an option in the reactorcraft config just to move all of the ores to the nether. I can send you all of the retextured files too. It's an elegant solution for both of our problems. 
[Reactorcraft Nether Ores.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/12008724/Reactorcraft.Nether.Ores.zip)
