### ISSUE TITLE
Cant upload file to crystal orchestra on remote server

### ISSUE THREAD

**Issue by sebastiancat** [ReikaKalseki/Reika_Mods_Issues#3198]
I am playing on a remote server hosted by [exaroton](https://exaroton.com/) with one of my friends and we cannot upload a .midi file from either of our computers to the crystal orchestra. I have tried it on a singleplayer world and it worked, but not on the server. I am not sure if it is an issue on the server's end or if it just requires a prefix to the path to work.

**Comment by ReikaKalseki** [comment]
I tested a bunch of them recently. Also, the parsing is done clientside, so being on a server does not affect it. Assuming the MIDI is not overly large, and that the server is not choking on the NBT, this works.
