### ISSUE TITLE
World rift pipe connection issues

### ISSUE THREAD

**Issue by Looma-mc** [ReikaKalseki/Reika_Mods_Issues#32]
I have found some issues when trying to connect Buildcraft pipes with world rifts. Other pipes have the same issue.

1. Transport pipes do not connect at all. no matter what i do. i even set the output side with the wand.
2. Kinesis pipes connect sometimes, but only one side. sometimes nothing connects.
3. RF transfer cables from electricraft also do not connect. they should as all other cables from his mods do connect.
4. Transfer pipes from ExU also do not connect

1,2 and 4 might be intended, but i remember Reika saying in ftb forums that this should work.

I tried to put those unconnected pipes on the world rift and tried to push energy/items through it, hoping it was a visual bug. no luck :(

latest Reika mods installed.
BC 6.4.2 + compat + additions 2.1.2
ExU 1.2.2

**Comment by ljfa-ag** [comment]
As for the Electricraft RF cables, they do connect to the rift for me, but only if there's another cable on the other side of the rift. Same thing for Fluxducts from Thermal Dynamics, however you need to use a wrench to establish the connection on one side.
Fluiducts work properly, itemducts however won't connect at all.

**Comment by Looma-mc** [comment]
tried the rf cables again. not happening :(.
i don't have thermal mods installed, so i cannot test. i also don't have enderio. I can only use buildcraft, ExU or RoC,EC cables.

what am i doing wrong? http://imgur.com/SEmoAIN

**Comment by ljfa-ag** [comment]
Hm, the RF transfer cable sometimes renders as if it didn't connect but it updates when I place a block in the same chunk. Apart from that, the RF cables seem to have other problems which I reported in another issue.

**Comment by ReikaKalseki** [comment]
Everything is working for me.

![](http://i.imgur.com/56KRGWW.png)

**Comment by ljfa-ag** [comment]
So I guess in order to use item pipes through the rift, there has to be an inventory on the other side rather than a pipe?

**Comment by ReikaKalseki** [comment]
Yes.

**Comment by Looma-mc** [comment]
The RF cables do not connect for me. guess there is some mod in my pack that is the issue here. tested it without any other mods and it worked ...
Kinesis pipes with a battery on the other side (like chests for transport pipes) do work though.

Edit: Fun fact: if it use the same settings/mods in a superflat test world, everything works. same mods, same configs as the server.

Edit2: Downloaded the map into singleplayer. Everything works. Uploaded map again onto server and it is broken again. something seems to break it, if it is loaded on a server instead of a singleplayer instance :(. I have no idea what could cause this issue.

**Comment by ReikaKalseki** [comment]
This has to be a mod interaction issue. API versions maybe?

**Comment by Looma-mc** [comment]
do you mean forge version? that is still on 1291. I can give you an unrelated crash report that shows the mods that i have installed: http://pastebin.com/BrUrDh7Q

I have no idea where to look. Maybe i will create a second server and try to find the bad mod.

**Comment by ReikaKalseki** [comment]
No, I mean mod interactions. If one instance has the problem and another does not, it is a mod interaction.

**Comment by Looma-mc** [comment]
that's what i am also thinking. just made a small local server with just a few mods and yours and i already have this issue. will update once i have found something.

**Comment by Looma-mc** [comment]
i am now left with only chromaticraft, dragonapi, rotarycraft and electricraft. latest version and forge 1291. i go on the server and give myself 2 world rifts and a stack of rf transfer cables (in creative mode). they do not connect to the rifts. i put them all around them and even try to block update trick. nothing :(

i use the same client and create a singleplayer world and do the same steps: works. now i am really confused.

just to make sure, I re-downloaded the mod files and created fresh server/client instances in case something got corrupted.

**Comment by ReikaKalseki** [comment]
...

**Comment by Looma-mc** [comment]
tried latest forge version with server/client combo. still not working. can anyone reproduce this? I am not touching any configs. just create a server + client with the mods and try to put cables around the rift. works perfectly fine in singleplayer without the server ...

if it is working for anyone, i am interested in the setup, because it is not working on any server i use :(.
![2015-04-28_11 18 19](https://cloud.githubusercontent.com/assets/12052854/7366472/c85b020e-ed98-11e4-9180-7c636c61da8f.png)

**Comment by ReikaKalseki** [comment]
....
