### ISSUE TITLE
[Chromaticraft V32a] Setting B:"Spawn Pylons in Overworld"=false does nothing

### ISSUE THREAD

**Issue by Milii20** [ReikaKalseki/Reika_Mods_Issues#3201]
Hello!, 
Just for testing something, i changed B:"Spawn Pylons in Overworld" in the chromaticraft's config to false, but pylons are still spawning in the overworld.
Nothing major to be honest, just wanted to report it.
Thank you for your time

**Comment by ReikaKalseki** [comment]
~~You need somewhere else for them to spawn; the mod does not let you turn off pylons completely.~~

That option was never implemented - likely for the above reason - and will be removed.

**Comment by Milii20** [comment]
Greetings!, thank you and sorry to bother but just curios, any chance of getting a whitelist/blacklist for dimensions for pylon and/or structure generation instead then? just for some fine tunning of modpacks i think would be useful
Just curios, and thank you for the mods!

**Comment by ReikaKalseki** [comment]
Not for the overworld, but there are options to control other dimensions (and in the case of Mystcraft, a custom page).
