### ISSUE TITLE
[SeaToSea] Finding breathing fluid blueprint requires suicide runs?

### ISSUE THREAD

**Issue by rkane31174** [ReikaKalseki/Reika_Mods_Issues#3202]
I only just found the databox for the breathing fluid, but it required traversing a decent portion of a wreck slightly below 500m depth in order to get it. The only way I was able to retrieve it was to do build a small base just outside the wreck and do multiple suicide trips.

It could be that there was another solution I wasn't able to see, since I feel like it would be odd for an extensive in-depth mod like this to require something as cheap as suicide runs. I only went so far because I checked the source code and I knew the breathing fluid was there, otherwise I would have assumed that I didn't have the necessary equipment (the breathing fluid) and looked elsewhere.

Could it be that the databox containing the breathing fluid and the one containing the seamoth speed module were accidentally swapped? They're both in the same wreck, but the seamoth speed module doesn't require going below 500m to get and can be picked up without dying. The speed module also requires materials that can't be collected without the breathing fluid, making it seem like a "come back here later" item.

**Comment by ReikaKalseki** [comment]
No, it does not, and you are still using the wrong issue tracker.
