### ISSUE TITLE
crash on startup after update to V32a

### ISSUE THREAD

**Issue by Goddfrey** [ReikaKalseki/Reika_Mods_Issues#3203]
https://pastebin.com/jC5YXnJx

AbyssalCraftIntegration related, if I remove this mod it works fine. Worked fine before the latest update of your mods, not sure which one is causing the crash.

**Comment by ReikaKalseki** [comment]
That recipe is invalid and will cause crashes elsewhere if not filtered. That said, I adjusted the code to avoid an outright crash, but you still have a bug in that mod.
