### ISSUE TITLE
[Chromaticraft V32a] Random crashes, probably duplicated issue with a twist

### ISSUE THREAD

**Issue by Milii20** [ReikaKalseki/Reika_Mods_Issues#3204]
Greetings!, I know this may be a duplicated issue (see #2867 #1100 #1290 #1604 #2035 #2439 #2637 #2730 )  so here it goes:

It is a big modpack (over 500 mods but really stable), and i am not moving at all from my base. 
Probably the most important part: I haven't done anything with Chromaticraft yet, since i started the save about 4 days ago, the only thing i did was to mine some ores, look at some pylons, and get blasted by them, so there is no crystal network, which seem to be the difference between the referenced issues and this one.
It happened similarly in other saves.
Every 15/20 minutes it may or may not crash, and the crash report is always the same. 
This happens only if i am in the overworld (the only dimension where pylons are enabled to spawn according to the config)
The world generator is RWG or Realistic World Generator (Pretty old, but really cool, same one as GTNH uses)

Here is the crashlog: https://pastebin.com/kcHvyVh0

I know the modpack is huge, so i am free to try any combination of mods you tell me, but i also had the same crash months ago with only RWG, Reika's mods (all of V32a but not dragonrealms), and then enderio, thermal mods, mekanism, thaumcraft (and thaumic tinkerer), and tconstruct.

Thank you for your time!

**Comment by ReikaKalseki** [comment]
This is the same issue as all of those. The Crystal Network is a conceptual entity and exists in any world with CC installed, regardless of whether you built anything.
