### ISSUE TITLE
[ChromatiCraft+1.7.10+V32a/ ClimateControl] Crash related to world gen

### ISSUE THREAD

**Issue by mcmso** [ReikaKalseki/Reika_Mods_Issues#3205]
The 'customGenLayer' problem has been around for a long time, and I'm sure you hate it,
How about you take him out once and for all
[crash-2023-06-27_13.47.27-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11884130/crash-2023-06-27_13.47.27-server.txt)
[crash-2023-06-27_20.28.15-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11884131/crash-2023-06-27_20.28.15-server.txt)

**Comment by ReikaKalseki** [comment]
This is another mod.

**Comment by mcmso** [comment]
https://paste.ubuntu.com/p/H4qct2fRb3/
When I copied the mod name, I copied it wrong It's my fault
I actually wanted to report climateControl
But after I updated it to 0.8.2, the problem was not solved

**Comment by mcmso** [comment]
> This is another mod.

https://paste.ubuntu.com/p/f7s3cpdPrJ/
When I copied the mod name, I copied it wrong It's my fault
I actually wanted to report climateControl
But after I updated it to 0.8.2, the problem was not solved

**Comment by ReikaKalseki** [comment]
ClimateControl is not my mod.
