### ISSUE TITLE
[ChromatiCraft v32a] Game crashes when breaking any Crystalline Stone or Crystal Rune

### ISSUE THREAD

**Issue by Gronglegrowth** [ReikaKalseki/Reika_Mods_Issues#3206]
This appears to happen only on a world that previously had v31 of the mods. Unsure what other information to provide here.

Two crashlogs are generated for this crash:
Server - [crash-2023-06-27_14.09.40-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11885871/crash-2023-06-27_14.09.40-server.txt)
Client - [crash-2023-06-27_14.09.43-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11885873/crash-2023-06-27_14.09.43-client.txt)

**Comment by ReikaKalseki** [comment]
Already fixed.
