### ISSUE TITLE
Chromaticraft crashes

### ISSUE THREAD

**Issue by Goddfrey** [ReikaKalseki/Reika_Mods_Issues#3207]
When digging dirt or placing crystalline blocks near the Casting Table (not necessarily touching it), I get disconnected pretty much every time, this appears in server logs:
https://pastebin.com/22pgQRe2

When I tried to just place a crystalline stone block somewhere far away from the casting table to check whether the proximity has anything to do with the bug, the game client crashed altogether. Server still running.

server log: https://pastebin.com/6MSibvcZ
client crash report: https://pastebin.com/e4cpa7HN

**Comment by ReikaKalseki** [comment]
Already fixed.
