### ISSUE TITLE
[DragonRealm V32a] [ArchiSections] java.lang.NoSuchFieldError: renderer

### ISSUE THREAD

**Issue by Cheeseypop** [ReikaKalseki/Reika_Mods_Issues#3210]
Downloaded version: Wed, 28 Jun 2023 16:45:57 -0700

After getting around the TerritoryZone problem the server now crashes with this error when trying to launch:
[crash-2023-06-29_13.11.20-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11906005/crash-2023-06-29_13.11.20-server.txt)

This doesn't seem to happen when loading into a singleplayer game or when hosting a server with the standard DragonAPI and ArchiSections downloaded from CurseForge

**Comment by ReikaKalseki** [comment]
Already fixed.
