### ISSUE TITLE
[Aqueous Engineering] Bioreactor not accepting small alien fecal matter

### ISSUE THREAD

**Issue by rkane31174** [ReikaKalseki/Reika_Mods_Issues#3211]
Self explanatory. When I try to put the small alien fecal matter into the bioreactor, it says that the bioreactor only accepts organic items. Since standard sized fecal matter is considered organic, I feel like the small fecal matter should be organic too.

**Comment by ReikaKalseki** [comment]
Wrong issue tracker, but I added it anyway.
