### ISSUE TITLE
DragonAPI+1.7.10+V32a with AM2-1.6.2 crash

### ISSUE THREAD

**Issue by mcmso** [ReikaKalseki/Reika_Mods_Issues#3212]
https://paste.ubuntu.com/p/nbJMfq9SMY/
This issue will occur after DragonAPI+1.7.10+V32a is installed with AM2-1.6.2 when using any potion or getting any Effect
am2.5's 1.5.0hotfix won't be a problem
As far as I know, during 1.5.0-1.6.2, there was no update to the code regarding potions
If you need any additional information, please contact me
https://modrinth.com/mod/ars-magica-25/version/v1.6.0

**Comment by TCLProject** [comment]
Solved in dev environment. I will release a fix later. This issue can be closed.
