### ISSUE TITLE
DragonAPI V32a update checker fails on Java 8u51

### ISSUE THREAD

**Issue by jeremiahwinsley** [ReikaKalseki/Reika_Mods_Issues#3213]
With Forge 1614 and no other mods, DragonAPI fails to connect to the update server while using Curseforge launcher (which is limited to 8u51), due to the update server using Let's Encrypt which isn't in the default trust store in 8u51.

https://gist.github.com/jeremiahwinsley/99b2e0d4c833f5fef2d9389d44b8b116#file-fml-client-latest-log-L1733

**Comment by ReikaKalseki** [comment]
I have minimal influence on that - you need to ask @OvermindDL1 , who is the host - or find a way to use a newer java version. It is working fine for me and presumably most others, however, so the issue is by no means unavoidable.

**Comment by OvermindDL1** [comment]
> which isn't in the default trust store in 8u51.

That is remarkably and impressively old and rife with horrible security issues, who on Earth would be using that?!  Should at least update to something to the past decade, that is terrifying...  O.o

But no, obviously nothing I can do about it, literally 8 years of advanced warning was given, that is more than sufficient time.

I guess you could manually inject the modern Mozilla certificate store into your Java to get that up-to-date at least, but it's horrifying that that's not automatically updating is that is horribly insecure...

**Comment by jeremiahwinsley** [comment]
> > which isn't in the default trust store in 8u51.
> 
> That is remarkably and impressively old and rife with horrible security issues, who on Earth would be using that?! Should at least update to something to the past decade, that is terrifying... O.o
> 
> But no, obviously nothing I can do about it, literally 8 years of advanced warning was given, that is more than sufficient time.
> 
> I guess you could manually inject the modern Mozilla certificate store into your Java to get that up-to-date at least, but it's horrifying that that's not automatically updating is that is horribly insecure...

Everyone who uses the Curseforge launcher is limited to this version, since it uses the vanilla launcher's built-in JDK. Using other launchers with newer Java versions would certainly be a workaround for this. I have asked the author of ArchaicFix to implement the certificate injection fix for a more general solution to this issue (other mods have run into this too), but I figured I'd mention it here in case you had a good way to implement a solution directly in the mod.

**Comment by ReikaKalseki** [comment]
This is not a mod thing. This is an HTTPS thing, caused by Overmind's box using too new of a certificate scheme. There is literally nothing I *can* do.

**Comment by OvermindDL1** [comment]
It's not even new, it's like 9 years old at this point, there's no excuse, every single browser and os in the world supports it now.

But yeah, just updating the root certificates in the jvm would fix it, archaicfix is a good idea to put it in actually yeah!

**Comment by OvermindDL1** [comment]
To be honest though, it's something the launcher should be injecting itself.

**Comment by ReikaKalseki** [comment]
For what it is worth, as of the next version, the actual error encountered during update checking will be reflected into the popup, as seen with this test message:
![https://i.imgur.com/qCF6snj.png](https://i.imgur.com/qCF6snj.png)
