### ISSUE TITLE
[DragonRealm ModPack v32a] Glass Texture missing from Tyksera Resource pack

### ISSUE THREAD

**Issue by Jkysler** [ReikaKalseki/Reika_Mods_Issues#3214]
Clean installation. The v32a update seems to have broken the glass texture for the Tyksera resource pack that is provided on the website.

![image](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/7318007/bfea1874-6db3-4644-9f9a-8c6da4325d87)

Tyksera resource pack is used. Renders in hand ((edit): and world) correctly only. Invisible in NEI and inventory.
|
|
|

![image](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/7318007/f6b5ed80-2891-4d29-af60-f8c7c2ce5d6f)

Default Minecraft texture pack is used. Renders correctly.

**Comment by ReikaKalseki** [comment]
Works for me. And besides, there is no way to only affect in-world texture for a vanilla block like that. ![https://i.imgur.com/9urN8cO.png](https://i.imgur.com/9urN8cO.png)
