### ISSUE TITLE
[DragonAPI v32b] Crashing on startup with ExtraTrees - NPE

### ISSUE THREAD

**Issue by Falgar** [ReikaKalseki/Reika_Mods_Issues#3216]
The changelog for v32b notes that a fix was implemented for crashes caused by invalid smelting recipes, but, for me at least, it seems to have introduced a crash. I did not crash with v32a, but I do with v32b. 

Here's the crashlog: https://pastebin.com/Q4Q183sx

**Comment by UristMcFarmer** [comment]
I too have this issue after updating to v32b this morning.

**Comment by ReikaKalseki** [comment]
Fixed.
