### ISSUE TITLE
Chromaticraft v32b disconnects when building casting room

### ISSUE THREAD

**Issue by Goddfrey** [ReikaKalseki/Reika_Mods_Issues#3217]
https://pastebin.com/d0KJnt2J error in server logs

Occurs when placing crystalline stone in a way it touches another crystalline stone in a partly built casting room (screenshot)
Neither server nor client crashes, just disconnect

It started around 5 blocks ago :) from what's in the screenshot. 

![2023-07-03_10 29 26](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/49716936/cc343f08-78f9-4346-966b-6bd1c7f1e373)

**Comment by ReikaKalseki** [comment]
Fixed.
