### ISSUE TITLE
[RotaryCraft/ElectriCraft/ReactorCraft v32b] Handbook Issues

### ISSUE THREAD

**Issue by Falgar** [ReikaKalseki/Reika_Mods_Issues#3218]
The text for the Electrical Physics and Boring Machine pages overflows the textbox of the handbook. Electrical Physics is only by one line, and likely can be solved by removing "from point to point", as I think that will shorten it enough while still preserving information.
Boring Machine is two lines and can potentially be fixed by having the torque requirements on the next page or by removing the last lines about the Mazestone needing much higher torque. This also comes up for some of the methods on the ComputerCraft tab, but I don't think there's a good way to solve that issue (unless font size can be changed?).

Further, the tab tooltips display underneath the text/diagram on the Relevant Physics, Config Alert, and Modpack Changes tabs.
The tooltip is also underneath the rendered models, this isn't much of an issue for the big models, as they're far enough away that the text doesn't reach, but for the Machine Tiers and the ComputerCraft tabs, the tooltip is under the models when the tooltip extends to the right of the cursor. When the tooltip extends to the left, such as when you're looking at the rightmost machines,  the tooltip is properly above the models.

The Enchanting Machines tab should label which machine is being displayed on each page for maximizing clarity. Some of the machines are obvious, like the grinder, but some of the more boxy ones are a little ambiguous unless you've been playing with that specific machine.

Salt has a crafting grid, but it is blank like unavailable mod compatibility items or disabled items, implying it too might be unavailable. The text doesn't suggest directly that it is instead obtainable via the drying bed.  

A number of tabs have blank second pages. This is a truly minor issue, feel free to ignore.
ReactorCraft 
- Control Rod
- Coolant Cell
- Thorium Fuel Core
- Fusion Plasma Injector
- Neutron Absorber
- Gas Collector
- Gas Duct
- Spent Fuel Container
- Neutron Reflector
- Tokamak Blueprint Highlighter
- Turbine Flywheel
- Steam Diffuser

ElectriCraft 
- Relay
- Electric Meter

RotaryCraft
- Drying Bed
- Ground Sprinkler
- Soil Hydrator
- All Piping
- Particle Display
- Spillway

**Comment by ReikaKalseki** [comment]
I added the machine names and fixed the overrun on the two named pages, and removed the empty crafting grid for salt. The tooltip one is probably something that should be fixed by reworking tooltip rendering, ie not part of the handbook. As such, open a new issue for that one. I am not going to do anything about blank second pages.

Also, something that should be noted is that the handbook predates my awareness of NEI existing, and I really do not want to sink a lot of time into the part of the feature that is largely supplanted by it, ie the recipe displays.
