### ISSUE TITLE
Chromaticraft v32c disconnecting while building Casting Room

### ISSUE THREAD

**Issue by Goddfrey** [ReikaKalseki/Reika_Mods_Issues#3220]
https://pastebin.com/pxQUfMav

After the update I managed to advance the building about this far, and now I get disconnected every time I try to place a pillar block.
![2023-07-04_12 45 48](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/49716936/5728fca9-c267-443f-9a7e-3544fea6ea09)

Edit: as expected, removing Railcraft fixes this. Which is a good enough solution as far as I'm concerned, especially if the bug is not on your end.

**Comment by ReikaKalseki** [comment]
I did do some fixes anyway.
