### ISSUE TITLE
Disconnect trying to get a GlowCloud spawner with a bedrock pickaxe

### ISSUE THREAD

**Issue by Goddfrey** [ReikaKalseki/Reika_Mods_Issues#3222]
https://pastebin.com/puFbLDsq

![2023-07-04_21 21 32](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/49716936/c83e4135-8715-4660-868b-139afa97223c)

**Comment by ReikaKalseki** [comment]
Fixed, but this should not be happening. It certainly was not for me.
