### ISSUE TITLE
Chromaticraft progression question / probable bug

### ISSUE THREAD

**Issue by Goddfrey** [ReikaKalseki/Reika_Mods_Issues#3223]
So I'm not sure if this is a bug but just in a case, since it's a bit suspicious. 
Screenshots below is about the extent of my progression so far. Which is very little. Since my last non-blank info fragment, I unlocked the following progression 'achievements' (not necessarily in this order):

Weak Magical Foci
The Forested Realm
Refractory Gems
Enriching Solvent
Sandy Burrows
The Alien Realm
Eldritch Nightmare
Painful Loss
Liquid Effects
Crystal Hives
Glowing Terraces
Stopping the Torrent
Ocean Temples
Orbs of Energy

However info fragments are still "undeciphered", none of these unlocked a single fragment. Is that really how it's supposed to work? 

![Screenshot_3](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/49716936/e82f18cf-fc0b-41c7-84af-b14216c3047c)
![Screenshot_1](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/49716936/6afadf84-de3a-45a8-a19e-bb1288a2d7a1)
![Screenshot_2](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/49716936/0150c86c-6b6b-454e-8cee-183b6d9c6dbb)
![Screenshot_4](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/49716936/4e285c5d-01b6-4d30-a9a7-56b2d116d69c)

**Comment by ReikaKalseki** [comment]
What non-exploration CC progression have you done?

**Comment by Goddfrey** [comment]
I've crafted Lumen Turrets, Glows, Pylon Compass, Chroma Collector, leveled table to 2, crafted everything needed for Casting Room of course, built a casting room, crafted and added a couple of runes for a linker crafting, crafted a linker, a tool compression chest. Boosted some shards. I think that's about all.

Oh and this may be relevant: the world started as a single player, I later copied all files to the server. I think the last unlocked fragment was still on SP. Progression does seem to have been transferred though, I can still craft what I have unlocked in SP, Lexicon still shows the progression achievements I got back in SP, etc.

**Comment by ReikaKalseki** [comment]
OK, run `/chromaprog debug all` and show me the result here.

**Comment by Goddfrey** [comment]
![debug-1](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/49716936/f9e5543e-31b5-4462-8052-824c7118555c)
![debug-2](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/49716936/2f787951-a14f-437f-b9ae-c5559087cf17)
![debug-3](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/49716936/1fbb9d58-072f-4afd-8110-51b89add5f5f)
![debug-4](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/49716936/5c54591d-a9f9-4f6c-9c77-195275222762)

**Comment by ReikaKalseki** [comment]
You are missing a *lot* of fragments for your current progression level, and many do not have progress requirements, making their inability to show up-
**wait.**
...Are you using v32 and expecting them to automatically convert as they once did?

**Comment by Goddfrey** [comment]
Damn.  That's exactly what I expected. 

Change log isn't too helpful...

>Completely overhauled fragment choice system, allowing more directed progression unlocks.

But simple wild guess to right click with a fragment worked well :) Sorry for wasting your time.
