### ISSUE TITLE
[RotaryCraft V32a,b,c] Game crashes if "lang" is set to "zh_CN"

### ISSUE THREAD

**Issue by gengyunmaster** [ReikaKalseki/Reika_Mods_Issues#3224]
I am playing many of Reika's mods such as RotaryCraft and its addons, ChromatiCraft, ExpandedRedstone, and GeoStrata. After updating these mods to V32 recently, my game can't start (crash during initialization phase) if "lang" was set to "zh_CN" (Simplified Chinese) in "options.txt" before launching. Set "lang" to "en_US" before launching can start the game properly. The above problem which is suspected to be caused by RotaryCraft does not exist in V31. Can you verify whether there are some bugs in the language file? Thanks for your time reading this issue.
[crash-2023-07-05_16.26.33-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11956077/crash-2023-07-05_16.26.33-client.txt)

**Comment by ReikaKalseki** [comment]
This is the same kind of issue as in #3098 and probably the exact issue as #2924. And like that issue, to fix it I need someone to make updated lang files.
