### ISSUE TITLE
Missing Chromic Lexicon Description

### ISSUE THREAD

**Issue by DerWahreQwert** [ReikaKalseki/Reika_Mods_Issues#3225]
The Entry for "The Far Regions" seems to be missing it's text as it only shows "#NULL!" as can be seen in the below screenshot.
![2023-07-05_20 12 15](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/62576132/d3e9b1b3-fce9-436f-b469-46fa1131cd32)

**Comment by ReikaKalseki** [comment]
This got broken by a rename of the internal registry ID. Fixed.
