### ISSUE TITLE
DragonAPI + TinCon + ExtraUtils stable unstable ingot crafting is broken (again)

### ISSUE THREAD

**Issue by EyeDeck** [ReikaKalseki/Reika_Mods_Issues#323]
Something of a regression of https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/73

Tested with my mod list narrowed down to:
Forge 10.13.4.1448
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
DragonAPI 1.7.10 V9b.jar
extrautilities-1.2.11.jar
Mantle-1.7.10-0.3.2a.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar
TConstruct-1.7.10-1.8.7.jar

Removing either Tinkers' Construct OR DragonAPI restores proper stable unstable ingot crafting. Obviously this could also be Tinkers' Construct's fault, but seeing as this has happened before I suspect it isn't.

**Comment by ReikaKalseki** [comment]
It only happens when TiC is present?

**Comment by EyeDeck** [comment]
When both TiC and DragonAPI are present, yes. TiC without DragonAPI and vice versa does not cause the bug to manifest.

**Comment by ReikaKalseki** [comment]
Which means it is in code in TiC that only runs with DragonAPI, or code of mine that only loads with TiC. There is little of either.

Ask boni to look for all calls to OreDictionary.initialize().

**Comment by EyeDeck** [comment]
I bothered digging into this a little more (which is a fancy way of saying I actually bothered looking at the log). Here are some logs:
[Log sans DragonAPI and TiCon](http://idek.ax.lt/mc/control.log)
[Log sans DragonAPI](http://idek.ax.lt/mc/ticon.log)
[Log sans TiCon](http://idek.ax.lt/mc/dragonapi.log)
[Log with both](http://idek.ax.lt/mc/dragonapi-ticon.log)

Present only in the log with both DragonAPI and TiCon is a bit that looks like:

> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/WARN] [FML/DragonAPI]: ****************************************
> [23:30:51] [Client thread/INFO] [FML/DragonAPI]: Replaced 19 ore recipies

which comes a while after (and is present in all logs)

> [23:30:44] [Client thread/INFO] [FML/]: Replaced 183 ore recipies

Is DragonAPI supposed to do this?

**Comment by ljfa-ag** [comment]
> Is DragonAPI supposed to do this?

This is not DragonAPI, Forge is doing this. Basically it replaces all iron ingots, wooden planks etc. in vanilla recipes by their oredict entries, ingotIron, plankWood etc.

**Comment by EyeDeck** [comment]
I was referring to the line with

> [Client thread/INFO] [FML/DragonAPI]: Replaced 19 ore recipies

not the typical line where Forge is doing its ore dictionary thing. ~~This does not happen unless TiCon is present~~ actually it seems to happen any time there are new things in the ore dictionary, and was the cause of this happening before (the ore dictionary being re-initialized too late in startup). 

I did notice, however, that this does seem to be happening in the section of the log shortly after this:

> DRAGONAPI: Initializing libraries with max recursion depth of 500

which looks to me to mean it's a library somewhere, that DragonAPI is using when TiCon is present, that's tickling the ore dictionary wrong.

**Edit**: I think I figured it out. For some reason, ExtraUtils loads after DragonAPI _unless_ TiCon is present. Normally DragonAPI does [this](https://github.com/ReikaKalseki/DragonAPI/blob/c0ee610610678c3e06a6b104dcb0a3ede65909a1/DragonAPIInit.java#L237), then ExtraUtils registers its recipes and there aren't any problems. With TiCon, ExtraUtils registers its recipes, then DragonAPI makes its `this.initalizeVanillaOreDict();` call and Forge replaces the recipes ExtraUtils registered earlier with broken versions.

This holds true even with a fairly long load order, ExtraUtils loads after DragonAPI unless TiCon is installed. Of course I could be totally wrong, but this is the only potential cause I can find.

Is there any easy way to force ExtraUtils to load after DragonAPI?

**Comment by ReikaKalseki** [comment]
On his end, yes. But I might well force the reverse. This is ultimately a bug on ExU's end.

**Comment by Keridos** [comment]
Can you please just enable your mod to load before any that your this.initalizeVanillaOreDict(); call affects recipes of?

Since It is your mod bugging the recipes, it really should not be RWTemas fault here, to be honest.

**Comment by ReikaKalseki** [comment]
It is not "my mod bugging the recipes". It is Forge doing a blind recipe replacement. And loading before would break most of my handlers.

**Comment by Keridos** [comment]
You cannot change your mods to load differently though since you require TConstruct to load before you load dragonAPI. Since TConstruct must load after ExU, ExU can never load after DragonAPI with your current settings. So unless you change something in your mod so It does not bug NBT based recipes with oredictionary stuff this is always gonna happen.

**Comment by ReikaKalseki** [comment]
No, this is entirely on ExU's end. My call to the OreDict initialization is in preinit, long before any mod should be registering recipes to the game.

**Comment by TomeWyrm** [comment]
DragonAPI merely exposes the bug. It's a Forge/ExtraUtilities problem. If Tema doesn't want to fix it, that's honestly not Reika's problem. Wonder if you can force a load order shift if it's explicitly stated in another mod.

**Comment by ReikaKalseki** [comment]
> Wonder if you can force a load order shift if it's explicitly stated in another mod.

No, load orders are static.

**Comment by Keridos** [comment]
This is a Minetweaker script that should fix the recipes: https://gist.github.com/Keridos/0fca4ad70638f2542988

**Comment by TomeWyrm** [comment]
I love the tag at the end of that Minetweaker script
