### ISSUE TITLE
[RotaryCraft v32c] Unknown crashes when initializing game with only DragonAPI&Rotarycraft 

### ISSUE THREAD

**Issue by zuiBaratheon** [ReikaKalseki/Reika_Mods_Issues#3231]
I did not use other mods but DragonAPI and Rotarycraft, but it still crashed for unknown reasons.
[crash-2023-07-07_10.25.49-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11974286/crash-2023-07-07_10.25.49-client.txt)

**Comment by ReikaKalseki** [comment]
#3224
