### ISSUE TITLE
[CC] Can't craft Repeaters / Multi-Aura Repeaters

### ISSUE THREAD

**Issue by DerWahreQwert** [ReikaKalseki/Reika_Mods_Issues#3232]
After updating to V32 I seemingly can't craft Multi-Aura-Repeaters anymore. I do have the required progression (in fact, I have all progressions) and the Runes of the Casting Complex are arranged as described in the Chromic Lexicon (It seems they are flipped upside down from what they used to be, I dunno if that's even intentional). As can be seen in the attached screenshot, the Casting Table UI shows the Icon of the Multi-Aura Repeater No-ed out, implying the recipe is correct but I'm missing some progression, which, as I said, is impossible, since I have every progression.
Tested a few other recipies:
Normal Reapeaters don't work
Lumen Beacon Transmitters don't work
Adjacency Cores do work
Energy Focal Points do work
![2023-07-08_00 55 22](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/62576132/35e0b938-cf22-4be8-a56d-c5753b8d70a8)
![2023-07-08_01 02 36](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/62576132/d5098a96-5fbe-4d8a-9407-cfa49a87aff6)
Either I'm being dumb and missing some obvious thing or there's an issue here

**Comment by ReikaKalseki** [comment]
The casting tuning key changed in v32. ~~Also, you can mouse over the output to see more information as to why the crafting is impossible.~~ The missing tuning key specifically was not one of the things this showed, but now it is.
