### ISSUE TITLE
[Chromaticraft] Crash with Trajectory when opening page in chromic lexicon

### ISSUE THREAD

**Issue by jonab03** [ReikaKalseki/Reika_Mods_Issues#3235]
When trying to open a page inside the chromic lexicon the game throws an error and crashes, logs and crash report attached.

The only mods needed are [Trajectory](https://www.curseforge.com/minecraft/mc-mods/trajectory/) and ChromatiCraft, make sure you have codechickenlib as it's needed by Trajectory.

To reproduce simply open the chromic lexicon and attempt to open a page inside of it, the game will crash.

I want to use trajectory as it's a required dependency of the newer Framez2 versions.

[crash-2023-07-08_19.54.43-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11991436/crash-2023-07-08_19.54.43-client.txt)
[fml-client-latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11991438/fml-client-latest.log)
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11991439/latest.log)

**Comment by ReikaKalseki** [comment]
This is his code crashing, and on code of mine that is eight years old and has never failed before. It probably fails when opening one GUI from another or something.
