### ISSUE TITLE
[DragonRealm Modpack] Crash when picking up a green power slug from a big backpack

### ISSUE THREAD

**Issue by tprussak** [ReikaKalseki/Reika_Mods_Issues#3236]
I placed a stack of 6 green power slugs in a Big Backpack from the Backpacks mod. I also had a single purple power slug in the bag, and had no issues with that one. When trying to remove the green slugs (by shift-click, normal click, or right-click to split the stack), the client crashes.

Tested with the hard configs, with all the latest files as of 7/10/23. I did place the slugs in the bag with invtweaks, but replicated the crash after disabling invtweaks. 

Inventory layout, the position of the slug likely matters:
![image](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/1276028/3ea7c612-a2cb-4f06-a96a-cc06013fc79a)

Sorting the bag a few times with Invtweaks did allow me to remove the slugs from a different position, though it did create this error on the first sort:
[InvtweaksError.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/12008842/InvtweaksError.txt)

Crash log
[crash-2023-07-10_14.51.13-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/12008770/crash-2023-07-10_14.51.13-client.txt)
Full log
[fml-client-latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/12008772/fml-client-latest.log)

**Comment by tprussak** [comment]
Update on this, I can reproduce it by placing any power slug in that slot of other double chest size inventories, such as loot chests.

**Comment by ReikaKalseki** [comment]
Fixed. Why do you keep tagging mod bugs as DR?
