### ISSUE TITLE
Selective charging of Lumen Storage Crystals

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#324]
Suggestion:
Implement GUI to select which colors a Storage Crystal Charger accepts and which it ignores. This could be a simple red/green gui like the Aura Pouch has. The default should be none, so that simply placing it down for the first time doesn't instantly suck all pylons dry.

Reason:
Charging a storage crystals is currently done for all colors simultaenously even if the intended use case (i.e. a Mineral Extractor) only needs three colors. This means that potentially _millions_ of lumen go to waste instead of being used in more useful places like Lumen Trees, Machines or even just being stored in the Pylons for future crafting. Not everyone has 16 turbo-charged pylons and _recharge is quite slow_ for unboosted pylons.

**Comment by ReikaKalseki** [comment]
This is already on my to-do list.

**Comment by lossycrypt** [comment]
You said i should remind you later on ;)

**Comment by ReikaKalseki** [comment]
:P
