### ISSUE TITLE
[Rotarycraft] The game crashed when using simplified Chinese 

### ISSUE THREAD

**Issue by MOLJOLL** [ReikaKalseki/Reika_Mods_Issues#3242]
In this instance, I only used a few mods for testing. The game in English has no problem, but when I restarted the game in simplified Chinese, the game crashed.(I didn't change any configs)
It looks like an old issue which appeared at v19a(and it had fixed in the newer versions), but it seems to have reappeared.
v31 has no problem, so I think it may be caused by recent changes?
Here is the crash-report.

[https://pastebin.com/13eK3Wx6](url)

My English is very poor, please forgive me...

**Comment by WJXhhh** [comment]
临时解决方案：用压缩软件打开RotaryCraft的jar，进到Reika/RotaryCraft/Resources/zh_CN文件夹里，编辑categories.xml，把"<!--->"插入第一行（引号无需复制，把

<?xml version="1.0"?>挤到第二行），保存。然后来到压缩包根目录的META-INF的文件夹，删去REIKAKEY.DSA和REIKAKEY.SF，编辑MANIFEST.MF，找到"

Name: Reika/RotaryCraft/Resources/zh_CN/categories.xml

SHA-256-Digest: LQS7Sgj8wBLML/uwGgAkz/ezg3x93Dpx5bSR842w9RE=

"这两行，删掉，保存，就可以用了。

**Comment by ReikaKalseki** [comment]
#3224 #3231
