### ISSUE TITLE
cpw.mods.ironchest.TileEntitySilverChest cannot be cast to Reika.ChromatiCraft.Block.BlockRouterNode$TileEntityRouterNode

### ISSUE THREAD

**Issue by Goddfrey** [ReikaKalseki/Reika_Mods_Issues#3243]
https://pastebin.com/hKYxUqn1

when placing silver chest from mod Iron Chests on top of fluid transposer from Thermal Expansion. I dont think it touched any item from any of your mods, however Extraction Node _used to be_ in the same place earlier.

**Comment by ReikaKalseki** [comment]
Fixed.
