### ISSUE TITLE
[DragonRealm Modpack] Server crash during worldgen

### ISSUE THREAD

**Issue by tprussak** [ReikaKalseki/Reika_Mods_Issues#3244]
I have had two server crashes so far when exploring, they appear to be the same and both related to a worldgen issue. Both occurred while exploring in the ocean. In both cases, the client was kicked from the server with an internal server error, and upon rejoining, the server crashed. After restarting the server, I could continue exploring the area without issues. I believe both crashes occurred shortly after generating an ocean temple, but that may be a coincidence. 

Server crash log
[crash-2023-07-14_12.36.40-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/12053460/crash-2023-07-14_12.36.40-server.txt)
The full server log is too large to upload, this is the log around the time the client got kicked:
[kick-error.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/12053514/kick-error.log)

**Comment by ReikaKalseki** [comment]
Occasional issues like this are not unexpected. Reopen this if it happens more than rarely.
