### ISSUE TITLE
Chromaticraft 32c Bezier Crystals cause client crash or disconnect

### ISSUE THREAD

**Issue by reisai1** [ReikaKalseki/Reika_Mods_Issues#3246]
Playing on a server running Dragon Realms, using the Bezier Crystals works occasionally with no issues, both visual and mechanically. However, it also causes my client to either disconnect immediately or crash outright seemly with no reason. 
[Latest crash report](https://pastebin.com/WnmhqB13)

**Comment by Shibva** [comment]
I can second this
https://gist.github.com/Shibva/b8e52d6fd10fa6f6efeb20a9007eedf9

**Comment by Ranavolio** [comment]
Thirding this:

https://paste.atlauncher.com/view/18e50cf1-3fdd-498e-a27f-432f2fd91e7f

**Comment by ReikaKalseki** [comment]
Already fixed.
