### ISSUE TITLE
[ChromatiCraft] Sorting with Inventory Tweaks deletes Info Fragments

### ISSUE THREAD

**Issue by jonab03** [ReikaKalseki/Reika_Mods_Issues#3247]
If you sort the inventory using inventory tweaks any fragments that come after other items get removed.

Interestingly enough items before don't get removed.

Steps to reproduce: 
1. Get some info fragments and another item.
2. Make sure that some of the fragments are after (to the right of) the other item(s).
3. Sort the inventory using middle mouse or R
4. Observe as the items after the other item disappear.

Mods Used:
DragonAPI V32C
ChromatiCraft V32C
Inventory Tweaks 1.59-dev-152
(all of them the lastest versions on curse as of the time of writing)

Logs:
[fml-client-latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/12062523/fml-client-latest.log)
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/12062524/latest.log)
No crash reports as this isn't a crashing issue.

**Comment by ReikaKalseki** [comment]
Inventory tweaks has all sorts of duplication and deletion glitches. This is probably just another one of them.
