### ISSUE TITLE
Bevel Gear GUI crashes the client when there's a sign adjacent

### ISSUE THREAD

**Issue by Goddfrey** [ReikaKalseki/Reika_Mods_Issues#3248]
Crash happens with both vanilla Sign and Tinker's Construct one.
https://pastebin.com/WQUP9ttR

![2023-07-17_22 44 32](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/49716936/8ecb4c1c-9edb-425a-b298-e5ec575bf143)

**Comment by tprussak** [comment]
I was just about to report a similar issue, it also crashes with a Chromaticraft loot chest adjacent to it.

**Comment by ReikaKalseki** [comment]
Adjacent TEs throwing errors will no longer crash the game, but there is not much I can do to prevent other TEs from throwing errors in the first place.
