### ISSUE TITLE
Rotarycraft Jetpack exploid

### ISSUE THREAD

**Issue by Arzana** [ReikaKalseki/Reika_Mods_Issues#325]
If your jet pack is full of ethanol and you try to fill it with jet fuel the remaining ethanol will be converted into jet fuel. Making it so you can fill you jet pack with ethanol for 99% and then adding jet fuel to fill it up with 100% jet fuel.

**Comment by ReikaKalseki** [comment]
Is this in v9? I remember fixing it.

**Comment by Arzana** [comment]
I'm running version V9b.

**Comment by ReikaKalseki** [comment]
Fixed.

It was a typo.
