### ISSUE TITLE
v32c Propeller Blade Cast graphics glitch

### ISSUE THREAD

**Issue by Goddfrey** [ReikaKalseki/Reika_Mods_Issues#3253]
Both propeller blade itself and it's cast displayed sorta diagonally on a casting table 

![2023-07-22_06 21 46](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/49716936/d7061d42-1fd3-4f6c-ae69-18ffa2bfd928)

**Comment by ReikaKalseki** [comment]
I can do nothing about this on my end.
