### ISSUE TITLE
[DragonRealm] Satisforestry node extractor cannot be crafted due to removed machine frame recipe

### ISSUE THREAD

**Issue by tprussak** [ReikaKalseki/Reika_Mods_Issues#3257]
The Satisforestry resource node extractor cannot be crafted in Dragon Realm because the Connecting Rod requires a Hardened Machine Frame, but the recipe for the Hardened Machine Frame has been removed. This makes Charged Certus Quartz unobtainable, and by extension prevents almost all use of Applied Energistics.

**Comment by ReikaKalseki** [comment]
I already fixed this.
