### ISSUE TITLE
[DragonRealm] Nikolite ore dictionary issues

### ISSUE THREAD

**Issue by tprussak** [ReikaKalseki/Reika_Mods_Issues#3258]
Rotarycraft Nikolite can only be crafted into Redpower Nikolite by making nikolite blocks and uncrafting them, while Redpower Nikolite can be crafted directly into Rotarycraft Nikolite. However, very few recipes actually accept Rotarycraft Nikolite, with most of them specifically requiring redpower Nikolite. It would be helpful to fix those recipes, or at least add an easier way to convert from Rotary to Redpower.

**Comment by ReikaKalseki** [comment]
This is an RC bug. That recipe had input and output swapped.
