### ISSUE TITLE
[RotaryCraft] Change minimum power of Dew Point Aggregator to something more correct 

### ISSUE THREAD

**Issue by Mg138** [ReikaKalseki/Reika_Mods_Issues#3263]
![image](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/33348966/0547875f-3bed-4fa3-9338-f544da6ba6c7)
![image](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/33348966/1548e229-b1d7-4268-b334-6072dfbb401c)

The requirements are clearly met, and this setup works when using a Microturbine, but it does not generate any water and has caused us way too much headache researching why.

Is the minimum power actually just wrong? Should it be adjusted to something else, it shouldn't make sense that it doesn't generate any water despite having all requirements met. We tried the same setup in an Ocean biome as well-- it did not work.

**Comment by ReikaKalseki** [comment]
The machine is more complex than simply "meet the minimum requirement and get water". You appear to have already realized it needs cooling, but it also depends on ambient humidity, and the torque input as well.

**Comment by Mg138** [comment]
Perhaps provide the actual formula for the generation instead of a required power?

**Comment by ReikaKalseki** [comment]
I added a note.
