### ISSUE TITLE
[DragonAPI] RetroGenController.updateFile causes huge lag spike on (auto) save

### ISSUE THREAD

**Issue by Mg138** [ReikaKalseki/Reika_Mods_Issues#3265]
Consider using a BufferedOutputStream than a FileOutputStream? org.apache.commons.io.IOUtils.writeLines *seems* to write to the file line by line, which will make it really inefficient.

![image](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/33348966/e4c8fc19-fe83-4c32-b2f7-162cb97de9dd)

[spike-3296-86588289.nps.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/12320380/spike-3296-86588289.nps.zip)
(zipped because Github doesn't like .nps files)

**Comment by Mg138** [comment]
Note: The biggest file is "only" 2.1MiB, and we've tried putting the server onto an SSD.

**Comment by ReikaKalseki** [comment]
I changed it to a `BufferedOutputStream`; we will see how much that helps.
