### ISSUE TITLE
[DragonRealm] v33a Crashes with "Invalid mod jarsign fingerprint"

### ISSUE THREAD

**Issue by tprussak** [ReikaKalseki/Reika_Mods_Issues#3269]
I tried to update Dragon Realm to v33a, but I am getting crashes with this error:

```
Reika.DragonAPI.Exception.InvalidBuildException: DragonAPI is an invalid JarFile:
C:\Users\shala\Desktop\Games\Minecraft\MultiMC\instances\1.7.10\.minecraft\mods\DragonAPI 1.7.10 V33a.jar is likely not a valid compiled copy of the mod.
Invalid mod jarsign fingerprint!
If you are attempting to make a custom build of the code, consult Reika.
Note that not all mods permit this, or of distributed versions of custom code, for security reasons.
If you got this by editing the mod jar, you may have to redownload the mod. Consult the developer for further questions.
```

The same instance works perfectly fine with v32c, and I have tried redownloading, both with the batch download and the individual download, with no success.

**Comment by ReikaKalseki** [comment]
I figured out the problem. I recently had my main storage drive fail, and while I moved the MC workspace to another drive back in February, thus mostly (if inadvertently) protecting it, the keystore for my jar signing was not moved with it. Combine that with gradle silently failing the jar signing in this circumstance and I made jars that looked fine but were not actually usable.

The file is older than my backups, so I do have copies of it, but for now I cannot build signed jars.
