### ISSUE TITLE
AbstractMethod error crash with Forestry 4.0.8

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#327]
The error log:
http://pastebin.com/1ee6v5iq

I have no idea what causes this crash, all i know is that it worked with Forestry 3 builds before i upgraded to forestry 4

**Comment by Duckfan77** [comment]
Forestry 4 is currently unsupported, so this is not a bug.

**Comment by ReikaKalseki** [comment]
Duplicate of #289, #287, #285, and #229.
