### ISSUE TITLE
[DragonAPI] version 33a uploaded to curseforge is corrupted, or internal signature is faulty

### ISSUE THREAD

**Issue by Vectrobe** [ReikaKalseki/Reika_Mods_Issues#3270]
The internal signature check for version 33a of the API fails the check and dumps the game at launch, despite the version being exactly the one supplied via curseforge, and only mods by Reika being present.

[crash-2023-08-25_17.39.39-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/12436856/crash-2023-08-25_17.39.39-client.txt)

**Comment by ReikaKalseki** [comment]
#3269
