### ISSUE TITLE
[Void Monster v32a] Custom drop files fail to load

### ISSUE THREAD

**Issue by Gronglegrowth** [ReikaKalseki/Reika_Mods_Issues#3271]
I am attempting to make a custom drop table, but even when I (at least to my eyes) copied the example file's formatting exactly with my desired values, it'd result in a crash. I had also tested the contents of said example file, in an instance with only DAPI (v32c) and Void Monster, to the same result. [Attached here](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/12442764/crash-2023-08-25_14.46.28-client.txt) is the crashlog from that attempt.

**Comment by Gronglegrowth** [comment]
Through reading the documentation and such, determined that a `type` key is required, though the example file does not list that. Commas also seem to be necessary for it to read multiple items in one file.

Additionally, the default drops are still present even with custom ones being loaded and working properly; is there a way to disable those?

**Comment by ReikaKalseki** [comment]
No, there is no way to disable those. However, they are underpowered/useless if anything.
