### ISSUE TITLE
HSLA TiC Tools not Repairable

### ISSUE THREAD

**Issue by Teryn180** [ReikaKalseki/Reika_Mods_Issues#328]
So, in the Revolution modpack, I used HSLA Steel for a pickaxe head, used it for a while, and discovered it wouldn't repair. The tool's tooltip does report HSLA Steel as the repair material. I tried repairing in both a tool station and tool forge, Crafting station and in inventory grid.

Will provide any more information I can if its asked for. Was directed here by the modpack creator.

**Comment by ReikaKalseki** [comment]
I do not touch any code related to that. Does it need to be manually registered? I doubt it.

**Comment by Teryn180** [comment]
I have noooo idea. I'm not even sure how to test that.

**Comment by ReikaKalseki** [comment]
Ask someone TiC or ExtraTiC related.

**Comment by Haggle1996** [comment]
Some extra details: ExtraTiC is not included in the Revolution pack, so all HSLA compatibility would have come from whatever TiCo compatibility is added in v9b. This is probably not related to SlimeKnights/TinkersConstruct#1768 

There is nothing in Revolution itself that plays with these items' configurations, so I would have to assume its something to do with RotaryCraft or how TiCo/ITT handles HSLA.

**Comment by ReikaKalseki** [comment]
I mention ExtraTiC because they would know if I need to take extra steps.

**Comment by squeek502** [comment]
Your best bet would be to step through [ModRepair.canModify()](https://github.com/SlimeKnights/TinkersConstruct/blob/ac202c3a17be7491b583ad9d21ee39b7b54a51ad/src/main/java/tconstruct/modifiers/tools/ModRepair.java#L26-L47) and see what's going wrong, but it looks like your material might need to be added to [PatternBuilder.materialSets](https://github.com/SlimeKnights/TinkersConstruct/blob/ac202c3a17be7491b583ad9d21ee39b7b54a51ad/src/main/java/tconstruct/library/crafting/PatternBuilder.java#L115-L127).

It's an entirely confusing and convoluted system.

EDIT: Actually, I think I ran into this same problem in one of my mods. [Here's how I solved it](https://github.com/squeek502/VeganOption/blob/master/java/squeek/veganoption/integration/tic/TConstruct.java#L149-L185) (invoking `PatternBuilder.instance.registerMaterialSet()`). Note that the actual pattern recipes are registered separately, this is only used for repairing/shards/rods as far as I remember.

EDIT#2: You'd actually want to use `PatternBuilder.instance.registerFullMaterial`, I use `registerMaterialSet` to register a shard/rod only.

**Comment by ReikaKalseki** [comment]
> EDIT#2: You'd actually want to use PatternBuilder.instance.registerFullMaterial, I use registerMaterialSet to register a shard/rod only.

That is what adds the Pattern Builder recipes...

**Comment by squeek502** [comment]
No, it doesn't. Even in [your code](https://github.com/ReikaKalseki/DragonAPI/blob/master/ModInteract/DeepInteract/TinkerMaterialHelper.java#L410-L414) you can tell that that is not true--`TConstructRegistry.addPartMapping` is what adds the pattern recipes. You just misnamed your `registerPatterns` Method variable.

You make it _really_ hard for me to want to help you. Even when I provide the actual solution, you dismiss it?

**Comment by ReikaKalseki** [comment]
> No, it doesn't. Even in your code you can tell that that is not true--TConstructRegistry.addPartMapping is what adds the pattern recipes. You just misnamed your registerPatterns Method variable.
> 
> You make it really hard for me to want to help you. Even when I provide the actual solution, you dismiss it?

How is (correctly or not) thinking the code does one thing and stating that not to be my intention "dismissing it"?

**Comment by squeek502** [comment]
Because you obviously didn't look into it for a single second. Simply reading the [linked `ModRepair.canModify()` method](https://github.com/SlimeKnights/TinkersConstruct/blob/ac202c3a17be7491b583ad9d21ee39b7b54a51ad/src/main/java/tconstruct/modifiers/tools/ModRepair.java#L26-L47) would show that `PatternBuilder` is the class used for determining which repair materials are valid.

**Comment by ReikaKalseki** [comment]
Fixed.
