### ISSUE TITLE
item collector: NullPointerException: Ticking memory connection

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#329]
hi,
I placed an item collector, couldn't get it to do anything(I placed a chest on top of it) and then broke it with a pickaxe -> game crashed.

http://pastebin.com/5LsRYA4G

**Comment by ReikaKalseki** [comment]
Hopefully fixed.

**Comment by Reignofmagic** [comment]
@ReikaKalseki 

Just to make sure, your fix is also aimed at restoring the Item Collector to normal operations? IE, items don't get destroyed when they drop in its radius, not just the crash on breaking the collector. Thanks in advance!

**Comment by ReikaKalseki** [comment]
They have the same root cause.
