### ISSUE TITLE
Error with mekanism

### ISSUE THREAD

**Issue by valveo** [ReikaKalseki/Reika_Mods_Issues#33]
I was looking error logs and found this message. Now reporting as it says.

[14:15:33] [Client thread/INFO] [FML]: RotaryCraft had an error reading Mekanism:
Null Item for Osmium
Please notify Reika as soon as possible, and include your version of Mekanism
[14:15:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Reika.DragonAPI.Exception.ModReflectionException: RotaryCraft had an error reading Mekanism:
Null Item for Osmium
Please notify Reika as soon as possible, and include your version of Mekanism

Mekanism version 1.7.10-8.1.1.228

**Comment by coolsquid** [comment]
Could you provide your full FML log at [Gist](https://gist.github.com)?

**Comment by valveo** [comment]
https://gist.github.com/valveo/288ae27d5e66fb053d99#file-fml-client-latest

**Comment by zemerick** [comment]
I have tested this with the recommended version of Mekanism ( 225 ), and only DragonAPI and Rotarycraft ( 6f ), and get the same error.

It does not appear to affect the game though. The osmium ore, ingots, dusts, etc. all appear fine.

**Comment by ReikaKalseki** [comment]
Fixed.
