### ISSUE TITLE
cpw.mods.fml.common.LoaderException: java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by Tsyklop** [ReikaKalseki/Reika_Mods_Issues#330]
Crash with Forestry 4.0.9.38  - http://pastebin.com/vmGgbRUp

**Comment by ljfa-ag** [comment]
The mods are not yet compatible with Forestry 4.
Duplicate of #229 and some others.

**Comment by Tsyklop** [comment]
@ljfa-ag  and will fix it?or not?

**Comment by ljfa-ag** [comment]
I hope so. The problem is that they can't be compatible with both 4 and 3, but well, 4 is the latest release now, so I hope Reika will take action on that one.
