### ISSUE TITLE
[Rotary/Reactorcraft v33a]some items missing textures

### ISSUE THREAD

**Issue by KamenriderSuperBee** [ReikaKalseki/Reika_Mods_Issues#3313]
![3GBKA{HL0EM QDT`XDFBO58](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/150350765/ce9d01ce-f1ac-4c42-bf5f-55c834e16ab9)
![4_SNNFUE~)3DPF 5}JIA8PC](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/150350765/42e1d99c-c225-4b74-aa42-620f435dd657)

**Comment by KamenriderSuperBee** [comment]
not only the unnamed items,but also HSLA steel scythe,bedrock scythe ,bedrock grafter....

**Comment by MalTeeez** [comment]
I believe this stems from the texture pack you're using not having all the textures for ReC & RC and since Reika uses spritesheets for his mods the textures have no default texture to fallback to. You could try adding the newest textures to your texture pack.

**Comment by KamenriderSuperBee** [comment]
> I believe this stems from the texture pack you're using not having all the textures for ReC & RC and since Reika uses spritesheets for his mods the textures have no default texture to fallback to. You could try adding the newest textures to your texture pack.

Thank you, After delete the texturepack and overwrite the mods again relaunch the game, I can see the sycthe textures now
