### ISSUE TITLE
mod crash

### ISSUE THREAD

**Issue by badanm** [ReikaKalseki/Reika_Mods_Issues#334]
http://pastebin.com/UuSWenZ0

**Comment by ljfa-ag** [comment]
Please don't just paste logs or anything long into the post

**Comment by ReikaKalseki** [comment]
ClassNotFound on ChunkManager?

Is this v9?

**Comment by badanm** [comment]
Yea I deleted it

**Comment by ReikaKalseki** [comment]
WTF?! And you complain it crashes?
