### ISSUE TITLE
[ChromatiCraft] Suggestion: Mana Booster

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#3348]
Basic idea: split it into two tiers of booster.

Lesser Mana Booster: Increased but still limited throughput, small multiplier (2-3x)

Greater Mana Booster: Unlimited throughput, or maybe just bump the limit way up again, and larger multiplier (3-4x).

Unlimited throughput and 6x feel very high.

Also, the recipe should absolutely require a Gaia Spreader or Gaia Spirit, at least for the second tier (or the current one). The best Botania spreaders are gated behind the boss, this should be as well.

**Comment by ReikaKalseki** [comment]
While I have nothing against the core idea of two tiers, and kind of like the lesser/greater naming scheme (as used by botania), I have zero interest in any of your implementation/behavioral suggestions. *Especially* making anything require a boss battle.

**Comment by Shahelion** [comment]
I honestly don't understand your stance about boss battles. Botania itself gates end-game stuff behind the Gaia Guardian, so your Mana Booster which is unquestionably an upgrade should be the same.

Anyway, what about a config option, that defaults to off, to replace one of the items in the recipe with Gaia Spirits or something. Mana Booster Hard Mode Recipe.
