### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Tsyklop** [ReikaKalseki/Reika_Mods_Issues#337]
I try to look recipe "Steel Grate" from Catwalks 2 and game crash. 

Error - http://pastebin.com/a6mD1Ymu

DragonAPI 1.7.10 V9b, RotaryCraft 1.7.10 V9b, ReactorCraft 1.7.10 V9b

**Comment by ReikaKalseki** [comment]
This is caused by PnC and should be fixed in v10.

**Comment by MJRLegends** [comment]
when is v10 out?
