### ISSUE TITLE
"Tile Entity Gearbox sent a sync packet from the client! This is not allowed!"

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#339]
###### Minimal mod set to reproduce (Tested in new SP world with default config):
- DragonAPI 1.7.10 V9b
- RotaryCraft 1.7.10 V9b.jar
- [InfiniteInvo-1.0.43.jar](https://github.com/Funwayguy/InfiniteInvo) (a mod that increases the players inventory size)
###### Symptoms:

As long as the player has the gearboxes GUI open the console is spammed with an infinite amount of this at about 10  errors per second.

```
[Client thread/ERROR] [FML]: DRAGONAPI ERROR: Tile Entity Diamond 8:1 Gearbox @ DIM0: -109, 4, -607 sent a sync packet from the client! This is not allowed!
```

This does not happen without InfiniteInvo so if you say it's on the other end i'll post it there too.

**Comment by ReikaKalseki** [comment]
InfiniteInvo is clearly changing the way containers work, calling `detectAndSendChanges()` clientside. This is wrong.

On the bright side, the spam is not going to break anything, nor is it an indication of such, but the calling might well cause desyncs.

**Comment by Funwayguy** [comment]
This was a pretty bad oversight on my part. Should be fixed up now as of the last build of InfiniteInvo.
