### ISSUE TITLE
RF Transfer Cables sometimes destroy energy

### ISSUE THREAD

**Issue by ljfa-ag** [ReikaKalseki/Reika_Mods_Issues#34]
Consider the following setup:
![Imgur](http://i.imgur.com/kGSYbvs.png)

The stirling engine is running and its buffer is empty, however the battery does not fill up. The energy goes to waste.
This does not always happen, but it seems like breaking and replacing the battery or cables will provoke it.

Also, in some cases the cable does not seem to transfer RF at all, even if the network limit is set to non-zero.

Mod versions:
DragonAPI v6f, RotaryCraft v6f, ElectriCraft v6a, BuildCraft 6.4.11 and BuildCraft Compat 6.4.2

**Comment by zemerick** [comment]
That looks like a redstone engine, in which case that one at least may be intended. BC is notorious for restricting what a redstone engine will work with.

**Comment by TomeWyrm** [comment]
Actually it's a Stirling engine. Redstone engines are made of wood.

**Comment by zemerick** [comment]
Ok, that makes sense. You can tell how long it's been since I used BC engines:)

When I get back in an hour or so, I'll try checking some of this out and see if I can narrow any of it down.

**Comment by zemerick** [comment]
Replicated with BC 6.4.13 ( most current ) and no BC Compat.

Unfortunately I haven't really been able to narrow it any. It seems to be a network update issue.

**Comment by ReikaKalseki** [comment]
Confirmed and not just BC engines.

**Comment by ReikaKalseki** [comment]
_Again._ >_<

`EnergyInteraction has = n.getInteractionFor(ei.tile);`
vs
`EnergyInteraction has = getInteractionFor(ei.tile);`
