### ISSUE TITLE
[Suggestion] Improve redability of various lumen gauge HUD elements.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#340]
[Suggestion] Improve redability of various lumen gauge HUD elements.
###### Description:

Various lumen "gauge" HUD elements indicate their fill level by displaying a color specific bar/slice on a dimmed down background of the same color. This makes the gauges very low contrast. Especially on smaller gauges and certain colors this can become difficult to impossible to read. This low contrast problem will be even worse for people who have old or low quality monitors, low screen resolution, bright room lighting or bad eyesight.
###### Affected HUD elements:
- Lexicon: recipe page lumen cost subpage for pylon casting.
- Crafting Altar GUI lumen cost display.
- Personal lumen charge wheel (shown when holding the manipulator).
- Circular crosshair overlay when pointing the manipulator at various blocks:
  - Pylons charge state
  - Crafting/Infusion Altar
  - Machine type blocks (Furnace, Farmer, etc)
###### Possible solutions:
- Show the unfilled part of the gauge as neutral color/transparent.
- Have a white bar/gap to seperate the filled from the unfilled part. (This won't work well for low screen resolutions).
- Show only particles of the color in the unfilled section.

As i've now heared this from several people and find them difficult to read myself sometimes i'm now officially requesting an improvement ;). 
###### I've cobbled together some mockups for "bar"-types:

![improvement_suggestion_1](https://cloud.githubusercontent.com/assets/14168854/10513379/7fc7a8aa-7347-11e5-86cb-997723a2f511.png)

**Comment by ReikaKalseki** [comment]
The first row is what it looks like now. Every other one is actually _harder_ to read - look at Argia in the second row, or kuro in the third - as well as being extremely visually unappealing, some to the point of giving me a headache.

**Comment by lossycrypt** [comment]
The example might be poorly chosen (and i'am not an artist) because the lexicon bars are all very large. Argia on second is slightly worse admittedly, but on the first one Kuro is (to my eyes and screen) only "readable" if i look at it for more than 5 seconds. Also Kijani and Nila are a lot worse on first. But these large bars are not a good indicator due to size. It gets imho a lot more difficult on small bars like the altars and even smaller circular gauges like the manipulator crosshair. (But i don't have any good example pictures right now.)

(And sorry for the headache :P)

**Comment by ReikaKalseki** [comment]
>  Also Kijani and Nila are a lot worse on first.

I find this impossible to believe. They are _extremely_ clear.

**Comment by ljfa-ag** [comment]
How about a config option to switch between, like, two different styles? I guess one size won't fit all.

**Comment by ReikaKalseki** [comment]
That is a significant hassle to implement, makes things like tutorials or screenshots confusing or misleading, and I do not like the stylistic implications of appearances being configurable, especially in a world where modpacks are a thing and users who ask "what's a config" are the majority.

The point is, though, Kuro is one thing, but for things like Nila or Kijani, I literally see no way you could fail to notice the color difference between the dark and light sections. The contrast between them is significant, larger than the contrast between on and off for most car taillights (and yes, I checked) and the on/off state of the (green) "power" LEDs on several of my hardware devices.

**Comment by lossycrypt** [comment]
The Kijani/Nila increased difficulty is mostly due to the darkness of those two colors i think. Lighter colors are far easier to tell apart to me. (Also you misunderstood this as me saying "can't tell them apart", i was merely stating that they are more difficult to tell apart  than row two.) Kuro in comparison feels like guesswork. Also just tested, and both Kuro and Argia are actually impossible to tell apart when i look at the screen from an angle (so much for old screens).

Comparing to real world light sources doesn't work imho because they are usually a) singular light sources on a non-source material (LED + white plastic casing) while the screen is one big source. And b) their surrounding usually contrast against a _different_ color (red taillight + blue car) and not against a weaker shade of the same color.

I thought about suggesting a "high contrast" config option but refrained from doing so because of the same implementation concerns you have.

Also i'm guessing you have a good screen because you do creative work, and you also have good eyesight. And even if those were not the case it is very very difficult to convey my (or anybody elses) physical contrast sight to you over the internet, because my screenshots would always look different to you ;).

Furthermore i haven't had any _really_ good ideas on how to improve the situation with or without major headaches (unless we count transparency). I did however just notice that the circular manipulator overlay for machines and pylons is different. On pylons the non-charged portion is "lighter shade same color" while for machines it's transparent. And transparent is something i suggested above.

Different gauge types:
![different_circular_styles](https://cloud.githubusercontent.com/assets/14168854/10523341/4071dd14-737a-11e5-9463-c1501489daf9.png)

And here's an example where i definetly couldn't tell if Kuro is filled or not:
![filled_multigauge](https://cloud.githubusercontent.com/assets/14168854/10523344/4486d45e-737a-11e5-9407-2679f052b9f6.png)

**Comment by 1skandar** [comment]
Here, I'll move my comments over here, where they look like they may be more helpful. 

Hmm, looks like you're leaving the hue and saturation alone between filled and empty and just, more or less, halving the value? This provides a large contrast for high value color, but less and less for lower value colors, brown, dark grey, and black. 

If I may make a suggestion? You're stamping the rune in the proper HSV for the colors for the elemental manipulator.at least. If you then set the empty background as a set value for all colors it might help. A neutral gray, 7f7f7f seems to provide proper contrast for all the colors.

**Comment by TomeWyrm** [comment]
You might also give a thin bar of a high-contrast/complimentary color past the end of the "fill bar" so as to visually indicate where "the end" is. If the runes are on a higher layer (thus rendered/drawn later) then they aren't screwed up by having a bar running over/through them.

I'd do a mock up... but I suck at doing anything with angles in the digital space. I really should learn the guts of SVG _sigh_

You might also want to do a hue or saturation shift for the background empty color, instead of (or in addition to) value, like Iskandar's comment.

**Comment by Reignofmagic** [comment]
Another Suggestion would be to change the gui to be something more like Thaumcraft's Wand Capacity Gui : http://i.ytimg.com/vi/HTlZ75JMvTE/maxresdefault.jpg
(Have a thinish bar of the full brightness/saturation color past the end of the capacity area and have the capacity area either transparent or a neutral color such as gray (although this would screw with Ykri and Agria) IE Wheel

my Picture done horribly in paint: 
![untitled](https://cloud.githubusercontent.com/assets/10967885/10644708/b21bf110-77ef-11e5-8322-ba0c14a12f38.PNG)

And for machines have the colors pop up as individual Icons similar to the chromatic compass: http://i.ytimg.com/vi/H6njbTeXcm0/maxresdefault.jpg
This is probably a poor suggestion, but it works with thaumcraft which has far more "colors" or types of energy than chromaticraft so it is a possible solution, although I think that using wheel, suggestion above would be better. 

Granted I know that these suggestions are, less than optimal, seeing as you already have a gui created, and it fits thematically.

**Comment by 1skandar** [comment]
I think Reika said that he hates that style. I'm not sure there is a good fix that wouldn't be a pain to implement. I'm still poking at it, but, shrug.

**Comment by Reignofmagic** [comment]
Agreed, anything changed at this point is a pain. I just know where you are coming from, some of the colors (Kuro, Ruskea, Gray/Light Gray and sometimes nila) are extremely difficult, if not impossible to tell the difference between before they receive any energy. Kuro... I never know what it is doing since black on a slightly less black is impossible for me to tell the difference. 

This might just be due to the color settings I have on my monitor (My monitor is great, I just haven't done any configuration since I got it), or my eyesight which is not that great.

**Comment by ReikaKalseki** [comment]
What about this (second row)?

![](http://i.imgur.com/WoTFASy.png)

I think this is the best so far, as it:
- At least partially solves the original issue of distinguishing the background and foreground layers
- Does not introduce auxiliary issues such as eyestrain or impeded readability of other colors
- Is visually and stylistically consistent with the rest of CC
- Is reasonably simple to implement, in contrast to several other ideas

**Comment by Reignofmagic** [comment]
I like it, it fixes most of the problems with visibility rather easily. 

1 Suggestion for Black and the two grays I would make the white designs in the background layer a bit brighter/more saturated so as to increase visibility. (especially helpful when you have large screens and the gui's are small).

**Comment by 1skandar** [comment]
Yes, that is perfect.

**Comment by TomeWyrm** [comment]
The blacks and greys should be higher contrast. Especially dark grey. Great for all the rest of them though.

**Comment by ReikaKalseki** [comment]
Fixed as per #312.
