### ISSUE TITLE
Chromaticraft 9b [The metadata fluctuation issue]

### ISSUE THREAD

**Issue by 1skandar** [ReikaKalseki/Reika_Mods_Issues#342]
Ok, this is weird. One of my Galazio Lumen Lamps just became a Nila Lumen Lamp. I've been crafting crystal runes and crystal seeds and placing the crystal runes around the casting table. At some point the Lumen Lamp changed colors, but exactly when I couldn't tell you. It's a very minor issue, but, well, here it is.
![2015-10-17_02 01 21](https://cloud.githubusercontent.com/assets/4127779/10557274/f987c2ac-7472-11e5-9706-0578e6a169ed.png)

**Comment by ReikaKalseki** [comment]
Actually, that is indicative of a **very** severe issue.

It means something in the vicinity is randomly changing the metadata of blocks it should not be (think like a hungry node affecting the area). This may be the same trigger as people reporting things like the OOB errors in ReC/ElC/CC ores and plants (involving metadatas that do not exist, and I do not generate) or RC machines transmuting themselves (as they are ID:meta pair identified).

Noone else I have asked has ever provided further information, so as yet I have no idea as to the cause. Please investigate the area and/or mods.

**Comment by 1skandar** [comment]
Thought that might be the case, that is why I report even trivial issues, sometimes they are a sign of something worse wrong. What do you need from me to narrow this down?

**Comment by ReikaKalseki** [comment]
The best idea is probably to copy the world and raze everything around it except for anything that might tick in some way (both TileEntity-type and block-type (eg grass, crops) ticks). Right now, I have no leads, but I _have_ had issues with TC nodes in the past passing the wrong xyz into block methods. My big two guesses are a repeat of that (possibly with another mod) trying to set its own metadata (or of a neighbor) or something doing something underwear-on-head idiotic like using block metadata to count with.

You can also try making a giant box of lamps, akin to a neutrino detector.

**Comment by 1skandar** [comment]
I'll poke at it. I did have a few Crystal seeds planted nearby growing away. Beyond that I'm in a desert and there should be nothing else within a chunk or two, though my main base is nearby. Any idea how far I should look around?

**Comment by ReikaKalseki** [comment]
I would be surprised if it was farther than 32 blocks XZ (but even that is not immune to coordinate mixups like swapping X and Z or a typo), though it could be any height or depth. A mod list could also be useful, as I have never seen this happen and thus the issue is likely a mod I never use.

**Comment by 1skandar** [comment]
http://pastebin.com/sBsMuppd

I loaded MCEdit and selected the chunk with the lamp and 2 chunks in every direction. The only tile entities was a Crusher from Immersive engineering, the casting table stuff, the lumen lamps, the lumen lamp controller, a crystal brewery, and a handful of growing crystal plants. The only ticking entities were the plants.

This is the work in progress 1.6 version of Modular Mayhem. If you like I can package my instance and my save and link it somewhere if you want to poke it yourself.

**Comment by ReikaKalseki** [comment]
> Oh, as a question, is it possible to right click harvest a crystal plant and not get anything?

Yes. That is in fact common.

> I loaded MCEdit and selected the chunk with the lamp and 2 chunks in every direction. The only tile entities was a Crusher from Immersive engineering, the casting table stuff, the lumen lamps, the lumen lamp controller, a crystal brewery, and a handful of growing crystal plants.

It could be a non TileEntity, something using block ticks, like crops, trees (saplings + leaves), liquids, grass, plus anything else. The only non-suspects are known inert blocks like vanilla stone.

**Comment by 1skandar** [comment]
Well, I built in a desert. I guess cacti count, but there are no trees, grass, or water nearby.  There is a ravine 4 or so chunks away, but that is it.

I'll keep an eye on it and see what happens. I wish I knew when it changed. I had to move it shortly before this to get it out of the way of crystal runes, but that was a few hours ago. I think it was fine when I came back from grabbing more crystals about 10 or 15 minutes before this, but I can't be 100% sure. with any luck this is simply a hiccup on chunk load/unload and is a 1 off thing. if this is creeping map corruption I'll be more than a bit unhappy.

Sigh, I had hoped I wouldn't find any more weird bugs to bring to you.

**Comment by Turmfalke2** [comment]
In case it matters, using the same pack I had some corruption issues as documented here: [link removed]

**Comment by 1skandar** [comment]
Yeah, that appears to be unrelated. I haven't build one of those yet, and was debating whether I needed any. Now I know to wait for the next update.

**Comment by ReikaKalseki** [comment]
Unfortunately the modlist is not too enlightening, as the vast majority of your mods are completely new to me (I have not even heard of half of them). That means we have not ruled out much.

If nothing of significance is in the area, it may well be a long-range effect.

> ith any luck this is simply a hiccup on chunk load/unload and is a 1 off thing

That is also possible, but that would be in the underlying MC engine, and I suspect we would have heard of it before.

@Turmfalke2: Please do not link irrelevant issues.

**Comment by 1skandar** [comment]
Yeah, lesser known mods tend to be a thing in the packs I put together. 

Eh, the problem here is that there are too many unknowns and I can't replicate it. Yet. I have a talent for both finding odd bugs and then digging out the how, if not the why. 

At the moment it hasn't recurred and no other problems are apparent.  I'll keep an eye on it, but for the moment I'm going to put it in the category of corner cases. On its own this was a trivial issue lacking needed info to properly diagnose so I really wasn't expecting you to be able to do much with it, but I thought it best you at least know it happened.

**Comment by ReikaKalseki** [comment]
Closed since it is not on my end (as far as I know).

**Comment by TomeWyrm** [comment]
You may want to request a mod list from anyone else with the metadata issue... it may help narrow down the offending mods.

**Comment by ReikaKalseki** [comment]
The last mention - with water - would make _vanilla_ that mod. However, despite repeated requests, the user has never provided more information.
