### ISSUE TITLE
RoC Pipe render glitch

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#343]
RoC pipes sometimes (sporadically) glitch out and render in the wrong shape/connection direction. The picture shows the pipes render as not connected at all but if memory serves right they can also glitch into other random connection configurations. This bug is probably quite old as i remember it from playing at least a year ago.
![out](https://cloud.githubusercontent.com/assets/14168854/10558822/6967cfc0-74de-11e5-8bc3-d8d12ea2e730.gif)
The setup is some RoC pipes pulling liquid out of a tank into a sprinkler, meaning there is very low pressure on the pipes. So the glitch might be caused by the pipes switching between "empty" and "contains something" . Or simply might occur when overall frame rate drops very low.
The logs (debug=off) show nothing out o the ordinary.
Shortly after taking the video the pipes on this section of the system returned to normal but the pipes inbetween this and the tank were still flickering.

**Comment by ljfa-ag** [comment]
Looks similar to the kinds of glitches you get when you let steam blocks escape, caused by too many block updates at once. So that might be plausible when your pipes are often switching between empty and not empty.

**Comment by ReikaKalseki** [comment]
> So that might be plausible when your pipes are often switching between empty and not empty.

This is my best guess as well, and the pipes _do_ trigger a block update (so as to trigger a rerender) when they change fluid states.

Increase your water supply and see if it still happens.

**Comment by lossycrypt** [comment]
As i apparently forgot to mention: The portion of the pipes that stabilized afterwards did have water in it constantly. (Albeit without a change to the supply rate which is impossible due to general fps issues in that world.)

**Comment by ReikaKalseki** [comment]
So the issue has been confirmed.

**Comment by jusvit** [comment]
![2016-08-05_16 16 08](https://cloud.githubusercontent.com/assets/4002351/17428029/9a8c0efa-5b28-11e6-9906-441a622fde53.png)
![2016-08-05_16 16 10](https://cloud.githubusercontent.com/assets/4002351/17428030/9a8d684a-5b28-11e6-8604-4980d179fac6.png)
![2016-08-05_16 16 11](https://cloud.githubusercontent.com/assets/4002351/17428031/9a911080-5b28-11e6-9fdd-19cf4c7dcab5.png)

Fluid pipes and other pipes bug out and i have to manually right click them for them to go back to normal appearance (Visual bug)

**Comment by ReikaKalseki** [comment]
That is entirely unrelated, and usually caused by a bad ISBRH, commonly Carpenters Torches.
