### ISSUE TITLE
Bedrock Breaker don't work

### ISSUE THREAD

**Issue by slappyslap** [ReikaKalseki/Reika_Mods_Issues#344]
hello
our bedrock breaker not work on the sever . server is run coldron coreprotect in plugins and more
breaker not break bedrock

**Comment by slappyslap** [comment]
Following a test with the industrial coil Avont we concluded it would take 100 000 speed  100 000 minimum speed and tork per break bedrock is it normal

**Comment by ReikaKalseki** [comment]
The bedrock breaker works fine, and I have been using one for months. If it is not working, you are doing something wrong. Your last comment makes that very clearly the case.

**Comment by slappyslap** [comment]
in solo work but in server not work

**Comment by slappyslap** [comment]
http://prntscr.com/8sicic in server
http://prntscr.com/8sicr5 in solo

**Comment by ReikaKalseki** [comment]
I am using it on a server, and none of the code is side-specific. Given the low torque on the jet engine, I suspect you damaged it but think that is a bug.
