### ISSUE TITLE
Gasoline/Performance engines not working on the moon (Galacticraft)

### ISSUE THREAD

**Issue by Saereth** [ReikaKalseki/Reika_Mods_Issues#346]
You can give the engine water and ethanol and additives and it just sits there, wont turn on. We tried in both an oxygen sealed environment and unsealed also with a bubble distributor. We additionally changed the biome from the default "moon" to magical forest. The engines will not turn on. We tested identical setups in a pocket dimension and in over-world and they work fine. 

Here are some images from us troubleshooting:

http://imgur.com/KYzTAvx,q0LGyJ2,mMxYdEV,Yg490vV,LUsEyyy,BknP22l

**Comment by ReikaKalseki** [comment]
Air is a requirement for combustion.

EDIT:
The not knowing about oxygen bubbles is a known issue, but cannot be fixed unless GC adds API methods that do not rely on core code.

**Comment by Saereth** [comment]
So just so I'm clear. You have checks to disallow the engines on the moon under the assumption of no air, but no way to check if players are using the correct methods of creating a sealed environment, and therefor creating a usable environment? If GC doesn't have the api support you're looking for why bother blocking GC planets at all.? Of course combustion requires air, but when you've got an oxygen rich environment and still no combustion or documentation on the matter it creates a highly frustrating player experience :/

edit; Also: https://github.com/micdoodle8/Galacticraft-API/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/world/OxygenHooks.java

would boolean isAABBInBreathableAirBlock possibly work for you?

As of this commit https://github.com/micdoodle8/Galacticraft-API/commit/cb9bd666a52f573400bb6c9a22e8c6af36d47688 on the 15th it seems most of the core references were all removed.

**Comment by ljfa-ag** [comment]
> but cannot be fixed unless GC adds API methods that do not rely on core code.

Looks like this problem has been fixed: https://github.com/micdoodle8/Galacticraft-API/commit/cb9bd666a52f573400bb6c9a22e8c6af36d47688

**Comment by Saereth** [comment]
Lol yeah I was just editing my post with that when you linked, awesome :p

**Comment by ReikaKalseki** [comment]
In that case I can add it in v10.

**Comment by ReikaKalseki** [comment]
Done.

**Comment by Saereth** [comment]
you the man! Awesome :)
