### ISSUE TITLE
Rotarycraft Clutch npe

### ISSUE THREAD

**Issue by valveo** [ReikaKalseki/Reika_Mods_Issues#35]
I have setup power come from world rift to clutch so i can turn off machines.
When I turn clutch on, console starts filling with error:
https://gist.github.com/valveo/d63e9d443914e7a5c4f2
Mods are latest:
DragonAPI+1.7.10+V6f.jar
ChromatiCraft+1.7.10+V6f.jar
RotaryCraft+1.7.10+V6f.jar

**Comment by 1Matthias** [comment]
Could you please provide the full FML log?

**Comment by valveo** [comment]
I can provide it later if you really want, because it is right now over 180MB. :D
But only error message from log is that error. Game starting logs etc can be found from earlier log I provide with bug #33

**Comment by 1Matthias** [comment]
Ok.

**Comment by 1Matthias** [comment]
Could you provide a screenshot of the setup in question?

**Comment by valveo** [comment]
Power input side: http://tinypic.com/r/2hd0jk5/8
Power output side: http://tinypic.com/r/552iqc/8

**Comment by 1Matthias** [comment]
Have you tried placing a shaft in between the world rift and the clutch?

**Comment by valveo** [comment]
That fixed error.

**Comment by 1Matthias** [comment]
Ok. I will tell Reika about this.

**Comment by madolinn** [comment]
Duplicate. https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2

**Comment by 1Matthias** [comment]
#2 was due to broken splitter code, this may be something else.

**Comment by ReikaKalseki** [comment]
I will look into this later today.

**Comment by valveo** [comment]
I also noticed that power is not going through world rift if it is right next to shaft junction.
Adding shaft between them will solve problem. It may not be bug.

**Comment by ReikaKalseki** [comment]
This sounds like a bug.

**Comment by ReikaKalseki** [comment]
It appears to have been fixed.
![](http://i.imgur.com/WFzefeN.png)
