### ISSUE TITLE
Crash when looking up the recipe of the RF battery from ElectriCraft

### ISSUE THREAD

**Issue by Fadenfire** [ReikaKalseki/Reika_Mods_Issues#350]
http://pastebin.com/YP3Sy3dJ

I have no clue if this is your mod or someone else's mod since the crash report literally doesn't know what category to put it in.

**Comment by ljfa-ag** [comment]
Looks like Minecraft crashed while it was trying to make a crash report...
So this report doesn't contain much useful information...maybe post your log instead?

**Comment by Fadenfire** [comment]
Here is my log: 
I thought it looked like Minecraft crashed while it was trying to make a crash report.

**Comment by Fadenfire** [comment]
This time I looked up the recipe of steel wire and this happened: http://pastebin.com/tm7HNXL8
I must say that that is a <i>very</i> long crash.

**Comment by Zedrimar** [comment]
I don't have this issue so far, have you updated your mods yet? I couldn't find what version of electricraft, dragonAPI and rotorycraft that you had from the log files

Will update if confirmed
