### ISSUE TITLE
[Suggestion/issue] [Rotorycraft] Night Vision Helmets

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#351]
I thought it would be neat if there were dynamically generated nightvision helmets, after all, sometimes people don't want to use bedrock armor as some armors provide better protection (such as draconic evolution with its draconic armor set) Or want to be able to use it on another helmet such as diamond. Now obviously, draconic evolution's draconic set already has night vis on the helm however for other armor sets that don't have this ability, it would be real neat to have!

Issue: it says in the handbook to combine with a diamond helmet in a worktable however that is not true, its the bedrock helm.

**Comment by ReikaKalseki** [comment]
I fixed the handbook, but am not going to add dynamic night vision helmets.

**Comment by Zedrimar** [comment]
ok
