### ISSUE TITLE
Chromaticraft Aspect Former (Essentia Creator Block) = Free Complex Essentia

### ISSUE THREAD

**Issue by Reignofmagic** [ReikaKalseki/Reika_Mods_Issues#352]
Sorry for the vague title, I just don't know how to word this in a concise manner. 

So the Aspect Former (Assuming that is the name of the block, I'm at work so I can't check) will create a large number of essentia types for free (no lumen cost either in gui, and no ley lines going to the aspect former itself). Large meaning half or more of the essentia types in my current modpack. 

The basic essentia types already work no problem, and a few of the complex ones have costs as well. I ran into this potential oversight yesterday as I just built myself the Aspect Former. I wouldn't say this is significant problem, probably just a oversight that can hopefully be remedied easily. 

I can't seem to find the list that the aspect former pulls its cost to create essentia with (From what I've seen in game although it is 4 lumen per essentia), either in Chromaticraft repository or Dragon API.. I just probably wasn't searching for the right criteria. 

Just to make sure I have the Chromaticraft Colors Correct and their intended uses/mechanics so I can help suggest lumen types for the essentia (pulling from this page https://github.com/ReikaKalseki/ChromatiCraft/blob/63b8e8272273450d3fe5da89de86859e81e6f6fa/Registry/CrystalElement.java
and from my observations in game):

Black Kuro: Magic & Protection
Red Karmir: Endurance / Resistance
Green Kijani: Nature / Plants
Brown Ruskea: Mineral / Earth
Blue Nila: Light / Sight
Purple Zambarau: Enhancement & Knowledge 
Cyan Vadali: Water
Light Gray Argia: Deception
Gray Ykri: Change
Pink Ruzova: Aggression & Strength
Lime Aveste: Motion
Yellow Kitrino: Energy / Vigor (mining speed)
Light Blue Galazio: Time
Magenta Kurauri: Life / Healing
Orange Portokali: Fire / Destruction
White Tahara: Purity/Harmony / Unification

Essentia Types that I know have no cost offhand as I am currently using it. (will make google sheets spreadsheet for all essentia types in my game and their lumen type/cost later this evening when I am off of work as well as a suggested lumen type(s))
- Herbia (Suggested: Green, or Green/Magenta)

Spreedsheet: https://docs.google.com/spreadsheets/d/1sJLjB62FRj67q4f5-0Spao2h4a2Oze4-auijlmPt6Xc/edit?usp=sharing

**Comment by ReikaKalseki** [comment]
Wait...so you are saying several Aspects have no cost associated at all?

**Comment by Reignofmagic** [comment]
That is correct.. I'd say about half of them do. Currently booting up minecraft to make that spreadsheet. So I will have a full list of what does and doesn't have a cost for you within 30 minutes, as well as my suggestions for those that do not have a cost

**Comment by Reignofmagic** [comment]
Spreadsheet. 

https://docs.google.com/spreadsheets/d/1sJLjB62FRj67q4f5-0Spao2h4a2Oze4-auijlmPt6Xc/edit?usp=sharing

**Comment by ReikaKalseki** [comment]
I changed the conversions between Aspects and Lumens some versions ago....that is probably the cause.

**Comment by Reignofmagic** [comment]
That'd probably be the cause then since I couldn't find a hard coded list anywhere... not that you actually hard code much haha. Too much dynamically created stuff that is way beyond me.

**Comment by ReikaKalseki** [comment]
Fixed. It was a stupidity on my end, using list == null as opposed to list.isEmpty().

**Comment by Reignofmagic** [comment]
@ReikaKalseki 
Glad you got it fixed! See you in V10
