### ISSUE TITLE
Sigils deactivating with Luminescent Sacrifice active

### ISSUE THREAD

**Issue by Haresus** [ReikaKalseki/Reika_Mods_Issues#353]
Chromaticraft v9b, BM v1.3.0Beta, Java 8

Like the title says, my Sigil of the Green Grove keeps flickering and deactivates when I switch to other item whenever I have Luminescent Sacrifice ritual active. When it is off, Sigil behaves normally.
I have both energy in my Manipulator and LP in Soul Network.

**Comment by ReikaKalseki** [comment]
What is the Sigil of Green Grove (ie what does it do and require)?

**Comment by Reignofmagic** [comment]
Sigil of the Green Grove. Applies bonemeal effect to plant if used directly applied to it. Or Rapid crop growth if activated, but not targeting a plant in a radius around the player. Requires some random plants and a reinforced slate.

**Comment by Haresus** [comment]
That's the one.

**Comment by ReikaKalseki** [comment]
What does it require? I have never used this part of BM.

**Comment by Haresus** [comment]
![straight from BM forum](http://i.imgur.com/VfVFE5u.png)

Image from BM forum

**Comment by Haresus** [comment]
I have just spawned all the BM sigils, none of them work with Luminescent Sacrifice ritual active, even lava and water ones, Divination Sigil will not give me a LP count of my network. Most of them work normally in creative, but bug out in survival.

Should I check on BM v1.3.3?

**Comment by Haresus** [comment]
Still bugging out on BM v1.3.3

**Comment by ReikaKalseki** [comment]
Again, I am unfamiliar with this part of Blood Magic. What do sigils require in order to work?

**Comment by ljfa-ag** [comment]
They drain LP from your soul network. A Blood Orb in an altar will transfer blood from the altar into the soul network.

**Comment by lordandsaviour** [comment]
Why do you interfere with other mods if you don't even know how they work you stupid fuck

**Comment by Reignofmagic** [comment]
@lordandsaviour 
I bet this was a valiant attempt to get on Reika's wall of shame.

@ReikaKalseki 
as Ljfa-ag said, and as do most sigils/things in blood magic do, This sigil drains from a player's Blood network in order to power the effect. I'm not familiar with the luminescent Sacrifice, but my guess is that it is interfering with the way LP is either generated or used, thus causing the flickering described (sounds like if you had faulty wiring and power only got through intermittently.)

**Comment by ReikaKalseki** [comment]
What Luminescent Sacrifice is supposed to do is redirect LP drains onto the Crystal Element buffer, assuming Kurauri energy is available.

**Comment by ReikaKalseki** [comment]
Hopefully fixed.
