### ISSUE TITLE
Chromaticraft 9b Travel Path bug

### ISSUE THREAD

**Issue by 1skandar** [ReikaKalseki/Reika_Mods_Issues#354]
The Jump Boost III effect does not reliably clear if you step off the path onto stairs. The buff will last until you either log off and back in or get back on the travel path and step off onto a flat surface. 

I know it works with Glowing Travel Paths, I imagine it does the same with the rest.

**Comment by ReikaKalseki** [comment]
I suspect this may be clientside only (and would not be the first time). Check if your jumps are still larger.

**Comment by 1skandar** [comment]
Already did and yes they are

**Comment by ReikaKalseki** [comment]
This is very strange, as once you step off the block, the potion effect should decay naturally...

**Comment by 1skandar** [comment]
It is _very_ odd. I can't trigger it reliably, I can only trigger it by going up stairs at the end, and I'm still not sure _why_. From the look of it it only happens if you go up the stairs at precisely the right point in the decay/refresh cycle but what that point is I couldn't tell you.

It is just a minor bug, however. Again, it doesn't persist if you exit out and come back and it appears to trigger only rarely and I can't 100% rule out it isn't some sort of cross mod issue. This is more of a "Ok, I'm seeing this, could this be a symptom of something worse?" than a "you need to fix this."

**Comment by TomeWyrm** [comment]
I've seen this before in all kinds of places. I think this is a vanilla or forge bug. There's some edge cases which can cause potion effects to become infinite so long as no cleanup of potion effects is done (relogging, dimension hopping, reapplying the potion effect, drinking milk). Sometimes it can be achieved by keeping the inventory screen open, sometimes by entering/leaving a beacon, sometimes with splash potions.
