### ISSUE TITLE
Portal Beacon Numbers Changing

### ISSUE THREAD

**Issue by Duckfan77** [ReikaKalseki/Reika_Mods_Issues#355]
When I go to the page in the handbook that provides the number of each block required to construct the portal beacon, many of the blocks flash through possibilities faster than can be read. It is very strange because it appears that the positions of the blocks on the page are switching, as the number of the blocks changes with what block is displayed. I can't record a gif, so here are some attached screenshots.

![2015-10-22_10 00 03](https://cloud.githubusercontent.com/assets/9396248/10668890/e558006e-78a3-11e5-980c-2b976bcde1ba.png)
![2015-10-22_10 00 04](https://cloud.githubusercontent.com/assets/9396248/10668887/e55473fe-78a3-11e5-807b-ac87dd620a2d.png)
![2015-10-22_10 00 06](https://cloud.githubusercontent.com/assets/9396248/10668888/e5573094-78a3-11e5-98c2-ece5191672d4.png)
![2015-10-22_10 00 07](https://cloud.githubusercontent.com/assets/9396248/10668889/e557daa8-78a3-11e5-94a4-29eec50b0a23.png)

**Comment by ReikaKalseki** [comment]
The list is a HashMap, so the order of the keys (block types) is indeed highly volatile and likely to change each time the map is modified. However, it should not be changing from frame to frame, only from GUI reload to reload.

**Comment by Duckfan77** [comment]
After testing again without optifine and fastcraft, the issue remains, although I have noticed that the shielding cloak, portal beacon, buckets of chroma, and buckets of ender are immune from the effect and don't cycle through.

It also is definitely changing every frame, because it slowed down dramatically when I limited the fps to 10.

**Comment by Duckfan77** [comment]
I just created a new world and tested again, and the issue persists. For some reason the positions of the shielding cloak, portal beacon, buckets of chroma, and buckets of ender are not changing with world reload or lexicon reopening, only on game launch, if that helps to discern the issue.

**Comment by ReikaKalseki** [comment]
Fixed, at the cost of some GUI framerate.
