### ISSUE TITLE
Solar Plant outputting 0.000

### ISSUE THREAD

**Issue by notchriss** [ReikaKalseki/Reika_Mods_Issues#358]
I can't get it working, always outputting 0.000 despite the size and towers to mirrors ratio. 

I am using RotaryCraft 1.7.10 V9b, DragonAPI 1.7.10 V9b

Screenshot http://postimg.org/image/qng15c0fn/

Edit: I played around with it and figured it only stops working after I start pumping water into it, not everytime, but most often. I am not sure about the exact mechanism, since I moved it around quite a bit through different biomes. Is it related to temperature somehow? Is it safe to leave it working with no water?

**Comment by Duckfan77** [comment]
There is a known bug where if the tower has more water than the exact amount required to run one step it doesn't work, for now the workaround is to just not feed it water, which acts the same as feeding it water normally.
