### ISSUE TITLE
NEI Crash caused by /0 with ExtractorRecipe

### ISSUE THREAD

**Issue by Erik3003** [ReikaKalseki/Reika_Mods_Issues#36]
Crashlog: http://pastebin.com/EGM42DhQ

The crash happened after I pressed the recipe button ("R") while cursoring over a crushed uranium ore (could be a different uranium product)

This may be on ChickenBones side but because its your recipe handler I think you should be able to fix it.

Using CCC 1.0.4.35 and NEI 1.0.4.90.

**Comment by 1Matthias** [comment]
Already fixed in the upcoming release.

**Comment by Haggle1996** [comment]
Referencing Haggle1996/RevolutionPack#1
