### ISSUE TITLE
Multiplying Portal Beacon structure and /debugtest autoturning off

### ISSUE THREAD

**Issue by Haresus** [ReikaKalseki/Reika_Mods_Issues#360]
All Reika's mods v9b, Java 8

So I just had a GTA (Gas Turbine Accident) and was trying to get back (cheat in) my stuff, when I noticed something weird neaby - my Portal Beacon tripled itself with minimal offsets:

![ummm](http://imageshack.com/a/img911/8438/VKMMu2.png)

Also, /debugtest would almost instantaneously turn off after being enabled (big screen text would literally flash and disappear, it doesn't function either - tried getting all colors from a pylon)

![hmm](http://imageshack.com/a/img903/5328/ijpJnZ.png)

I have no idea if the two are connected

I did restart Minecraft after getting sucked into Gas Turbine to remove that cube of fire graphical glitch (kills my fps)

I didn't edit any of my saves nor added any mods lately

**Comment by Haresus** [comment]
And /debugtest was working fine like 2 days ago.

**Comment by ReikaKalseki** [comment]
Portal blocks, if debugtest is on, will place the portal structure (clearly one per block) and then disable debugtest. This is not really a bug, though in hindsight is not very useful, either.
