### ISSUE TITLE
GeoStrata : Exception getting block(Vent) type in world

### ISSUE THREAD

**Issue by RoloEdits** [ReikaKalseki/Reika_Mods_Issues#363]
http://pastebin.com/93Tg7yYN

**Comment by ReikaKalseki** [comment]
Why did you close this immediately after opening it?

**Comment by RoloEdits** [comment]
Because I was sure it was my fault, I was messing with ore gen and got that error but when I changed to another iteration it went away. Sorry for causing unnecessary trouble. Should it be re-opened?

**Comment by ReikaKalseki** [comment]
What do you mean, messing with ore gen?

**Comment by RoloEdits** [comment]
Changing the ore generation from uniform to a vein type using the cofh config.

**Comment by ReikaKalseki** [comment]
That is unlikely to affect vents.

**Comment by RoloEdits** [comment]
Then I am not sure, because as soon as I change the frequency of the veins, I stopped getting that error.
