### ISSUE TITLE
ChromatiCraft java.lang.NullPointerException: Exception getting block type in world

### ISSUE THREAD

**Issue by RoloEdits** [ReikaKalseki/Reika_Mods_Issues#364]
I was changing my Ore-Gen to a vein type and when I was doing that I was getting this error so I removed CC temporarily to make sure that the world gen was not causing the issue but when I was happy with the generation I added CC back and still I am getting this error.  

http://pastebin.com/XHrP2KYc

**Comment by ReikaKalseki** [comment]
Something (probably another mod) is calling the world generators with a null world. This is - for obvious reasons - stupid.
