### ISSUE TITLE
Pylon Worldgen glitch.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#368]
During some testing in a superflat desert (2;4x7,64x24,8x12;2;village,biome_1,decoration) i came across something odd:
![pylonleft](https://cloud.githubusercontent.com/assets/14168854/10847482/fde0859c-7f16-11e5-9fa0-65c2dced2d62.jpg)
![pylonright](https://cloud.githubusercontent.com/assets/14168854/10847481/fdde50ba-7f16-11e5-9f6a-b0d1a7ee9318.jpg)

Notice how i get the "Near Pylon" HUD effect despite there being no pylon core. Breaking the structure also doesn't clear the effect.

Edit: The building is a witchery hut.

**Comment by ljfa-ag** [comment]
Hm, structures being overwritten by other structures from other mods might happen. But yeah, I guess an inactive pylon should maybe not have the HUD effect.

**Comment by ReikaKalseki** [comment]
Other worldgen destroying the pylon does not notify ChromatiCraft, and I cannot account for it.

**Comment by lossycrypt** [comment]
The point was more about the HUD effect than about $yet_another_pylon_overwritten. If that's normal it might be worth fixing. Especially when they're beyond repair (missing core).

**Comment by ReikaKalseki** [comment]
The HUD effect is tied to the cache, not the TileEntity.

**Comment by lossycrypt** [comment]
I feared that might be the case. So there's no good way to delete the cached entry when there's not actually a pylon around?

**Comment by EyeDeck** [comment]
In my experience just disconnecting and reconnecting will remove the HUD effect if worldgen breaks a pylon.
