### ISSUE TITLE
ReactorCraft: Tritium lamps instantly drain upon placement

### ISSUE THREAD

**Issue by EyeDeck** [ReikaKalseki/Reika_Mods_Issues#369]
As title, after filling some tritium lamps and attempting to place them, they flash with glowstone-level brightness for exactly one tick (which could be slight desync), then go dark. Picking them back up reveals that their tanks have been instantly emptied to 0%. 

Tested with mod list narrowed down to just Reactorcraft and NEI plus prereqs.

**Comment by ReikaKalseki** [comment]
Fixed.
