### ISSUE TITLE
rf engines not Upgradeing?

### ISSUE THREAD

**Issue by dodedo** [ReikaKalseki/Reika_Mods_Issues#37]
I look online And all the tutorials Say You have to upgrade rf engines For making them Better, But i can't Find The upgrades help?

**Comment by dodedo** [comment]
my engine Just make 2048 torque And it Does Let me choose The speed.

**Comment by 1Matthias** [comment]
You will need to craft the different levels of upgrades, which are labelled as upgrades. If you search for upgrade in NEI, you will find them. They are also shown in the handbook.

**Comment by dodedo** [comment]
They are Not in nei, maybe This Is a bug??

**Comment by dodedo** [comment]
maybe they Were Gone for the modpack? is updates a Config Option?

**Comment by ljfa-ag** [comment]
No they're not a config option. They should be in NEI.
They used to be called "Converter Tier x Upgrade", but they have recently been renamed.

**Comment by dodedo** [comment]
looking for upgrade Finds extra Utilities and Some Things from other mods But nothing In roteracraft? maybe the wiki Has Made a mistake?

**Comment by dodedo** [comment]
also the Wiki is wrong, it Says that latest version is latest but I am on The Latest ftb pack.

**Comment by 1Matthias** [comment]
Oh. What version are you using?

**Comment by 1Matthias** [comment]
Actually, what pack are you using?

**Comment by ReikaKalseki** [comment]
This is Monster 1.1.1. From v14 to v19 inclusive, the magnetostatics acted as he describes, and the upgrades were added in v20.
