### ISSUE TITLE
RoC Electric Generator disconnects from IC2 cables on world reload.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#371]
RoC Electric Generator disconnects from IC2 cables on world reload.

Every time the world is reloaded (SP: Save+Quit->Join, MP:Server restart) all cables disconnect from Electric Generators. Manually replacing the connecting block works. (This is not a graphical glitch, power transfer ceases.)
(industrialcraft-2-2.2.782-experimental.jar)

After placing everything works fine:
![out1](https://cloud.githubusercontent.com/assets/14168854/10868532/16f93ca6-8091-11e5-9d17-85ed855b391b.jpg)

After world reload everything disconnects:
![out2](https://cloud.githubusercontent.com/assets/14168854/10868533/16fc04e0-8091-11e5-9569-a049a038052c.jpg)

**Comment by ReikaKalseki** [comment]
This is normal. Their network is rebuilt on world load and the wires need a block update to reconnect.

**Comment by ljfa-ag** [comment]
How come it works with IC2's own machines?

**Comment by ReikaKalseki** [comment]
They probably have special-casing code.
