### ISSUE TITLE
RC extractor invisible when powered.

### ISSUE THREAD

**Issue by ryuben** [ReikaKalseki/Reika_Mods_Issues#372]
Any extractor that i have upgraded to bedrock drill when powered vanishes.
It still works but i as the person who placed it am unable to see it, if i place a block where i know it is - it flashes up then vanishes

RotaryCraft 1.7.10 V9b

**Comment by ReikaKalseki** [comment]
This has never happened to me; something has to be messing with the rendering engine, specifically with TESRs.

**Comment by ryuben** [comment]
mind expanding that comment some?

**Comment by ReikaKalseki** [comment]
For that, I would need further information, information which you are unlikely to have.
