### ISSUE TITLE
[Reactorcraft]Changing turbine generator to EU mode does not allow it to connect to ic2 cables

### ISSUE THREAD

**Issue by wormzjl** [ReikaKalseki/Reika_Mods_Issues#374]
As below
![3](https://cloud.githubusercontent.com/assets/2989009/10879669/a0f733f8-8155-11e5-9534-6d3ffff7d3f2.jpg)

EU splitter from electricraft works fine

**Comment by ljfa-ag** [comment]
You might need to replace the cable or trigger a block update. In this case it might be related to #371.

**Comment by wormzjl** [comment]
The cable was placed after changing the mode

**Comment by wormzjl** [comment]
Any feedback with this?

**Comment by ReikaKalseki** [comment]
Has something changed about the IC2 API?

**Comment by wormzjl** [comment]
There shouldn't be any api breaks recently, perhaps just update to the latest version to be sure?
As the integration stuffs from electricraft and rotarycraft works, it's strange that this one doesn't work

**Comment by ReikaKalseki** [comment]
They all implement the same interfaces; if one works, they all should. And the connection logic in the generator is identical between RF and EU...

**Comment by wormzjl** [comment]
Might be a facing issue? Just guessing

**Comment by ReikaKalseki** [comment]
That is my guess as well - and is implicated in issues like #371 and some variants of it from the past (including with RF systems). However, if placing the wire _after_ still fails, then I have no idea.

**Comment by wormzjl** [comment]
perhaps just let it emit power on all sides and see if it works then

**Comment by wormzjl** [comment]
Seems to my that removing the side check at
https://github.com/ReikaKalseki/ReactorCraft/blob/f4ddf419178332d31ab7e655cff7b95528d795b5/TileEntities/TileEntityReactorGenerator.java#L284
Will work 

Anyway, this block has only one side to connect to other stuffs

**Comment by ReikaKalseki** [comment]
This is true...

**Comment by wormzjl** [comment]
Umm do you still remember this issue?

**Comment by ReikaKalseki** [comment]
Yes, and it makes no sense, as all the other IC2 connectivity works.

**Comment by wormzjl** [comment]
You can just remove the side restriction IMO, or probably try without getOpposite?
