### ISSUE TITLE
Interaction with Harder Wildlife "seasons"

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#377]
I don't know if there's anything that can be done here, but I figured I'd ask.

[Harder Wildlife](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2451299-reasonable-realism-its-a-pack-its-a-mod-it-makes) adds a mechanic that causes the world temperature to change over time (simulating seasons).  Apparently, this is causing issues with RoC machines that depend on biome temperature for their operation (such as the blast furnace) during the "winter" days.  

I was wondering if there was a way for DragonAPI to detect if a block is indoors, and adjust its ambient temperature accordingly, as a way to limit the effects of the simulated seasons.  HW does seem to have some ability to detect such, as crops grown in an enclosed space will respond as if the temperature is halfway between the current seasonal temperature and the biome default.

**Comment by ReikaKalseki** [comment]
There is no way the seasons are affecting anything; I manually specified all of the temperature code. That said, I like the idea of taking it into account.

But detecting "indoors" is impossible.

**Comment by ghost** [comment]
Okay, just to make sure we're on the same page here:

HW seasons periodically [alters the vanilla temp and rainfall values over the course of a configured span of time](http://reasonable-realism.wikia.com/wiki/Seasons).  There seems to be a method of detecting indoors, because the HW has a way of detecting the [use of greenhouses](http://reasonable-realism.wikia.com/wiki/Crops).

So, what you're saying is that DragonAPI's temperature handling code doesn't check the biome's temperature property at all? Its temperature value is strictly dictated by the biome type?  If so, then I apologize for bugging you about this, and thank you for your time.

**Comment by ReikaKalseki** [comment]
> So, what you're saying is that DragonAPI's temperature handling code doesn't check the biome's temperature property at all? Its temperature value is strictly dictated by the biome type?

Correct.

I am going to leave this open, because I like the idea of seasons affecting ambient temperature. Does the mod have a GitHub or somewhere to contact the developer?

**Comment by ghost** [comment]
Me and my big mouth. :p

**Comment by ghost** [comment]
I did not find a github, but you can contact Draco18s on his Minecraft Forum thread [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2451299-reasonable-realism-its-a-pack-its-a-mod-it-makes).  He may be using a different versioning system, for all I know. :-/

Sorry it took me so long, but I had to finish classes and come home to really look.

**Comment by ghost** [comment]
Found a github:

https://github.com/Draco18s/HarderStuff

**Comment by keybounce** [comment]
For what it's worth, the "Greenhouse" detection in harder wildlife is just "Is there a block between me and the sky". Glass works just as well as stone.

**Comment by ReikaKalseki** [comment]
Implemented. I chose a curve where the modifier he specifies (a sine wave from -0.6 to +0.6) is multiplied by 50 and then -25 is added (ie T = T_orig+50 x 0.6 x sin(time)-25).

So, for example, a plains (25C, 30C in full sun, 14C at night) would see variations from [30, 35, 21] in the summer to [-30, -25, -41] in the winter. This is approximately the real-life temperature variation seen in, for example, the Canadian prairies.

Note that not all biomes have equal season effects; things like deserts and ice plains have minimal seasonal variation, and things like plains have high seasonal variation.

So a desert, for example, with a 20% effect, would have the following variation:
[40, 45, 29] to [41, 46, 30] in summer and [29, 34, 18] in winter.

**Comment by keybounce** [comment]
Woot!

**Comment by keybounce** [comment]
wait, canadian plains? No, midwest USA :-)

**Comment by ReikaKalseki** [comment]
I have never been to the US Midwest. I _have_ been to Winnipeg.

**Comment by Nagapito** [comment]
Hi,

I know this is a very old issue but I find a small problem with it. You detect if the mod is loaded and if so, you use his functions to calculate the time of the year but you completely ignore the fact that the season system could be disabled.

This is causing machine temp variations even while seasons are disabled...

Maybe using reflection to also check the static doYearCycle boolean to determine if you should "load the system".

**Comment by ReikaKalseki** [comment]
Done.
