### ISSUE TITLE
chromaticraft instacrash

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#378]
Edit: so I found that chromaticraft would often instacrash, however after trying to load up minecraft multiple times it eventually worked.... not sure why.... or how for that matter....

Here was one of the crashes: http://paste.ubuntu.com/13263650/ 

Will update later on news

Update: sensitive to mods being removed or added (causes same crash)

**Comment by Zedrimar** [comment]
Updated Railcraft and removed enderIO to test, still same crash

**Comment by Zedrimar** [comment]
Seems to be a corrupted dragonAPI, fixed for now

**Comment by Zedrimar** [comment]
Adding a new minimap causes crash (lite loader to journey map), fixed after re-downloading dragonAPI

**Comment by Zedrimar** [comment]
I don't even know that caused it, and I am not falsifying this, I just don't know why I am crashing simply by switching out a minimap, It could just be a corrupted mod file and the corrupted code screws with everything else :/ All I can tell you is that I went and re-downloaded DragonAPI and everything was back on track.... until I started removing mods and adding new ones....

**Comment by ReikaKalseki** [comment]
The "spurious" tag is the closest I have to this - an issue that disappears when examined and likely a corrupt jarfile.

**Comment by Zedrimar** [comment]
ok, I will likely go and do the tedious task of re-downloading my mods since it may be more than one corrupt file.... I hate bit rot... XD

**Comment by Zedrimar** [comment]
@ReikaKalseki so its not corruption, in fact after loading minecraft multiple times after the crash it eventually worked.... not sure how that happened...

Edit: it seems to also be sensitive to mods being removed/added
