### ISSUE TITLE
RF storage battery infinite energy

### ISSUE THREAD

**Issue by AndShy** [ReikaKalseki/Reika_Mods_Issues#379]
RF storage battery infinite charging from connected to top ultimate cable from mekanism and attached redstone signal. 
electricraft v9b, pack - AT Revolution (1.2.2.0)
all information in video - https://youtu.be/EjT86UQIIiI

**Comment by Haggle1996** [comment]
Haggle1996/RevolutionPack#117

**Comment by Reignofmagic** [comment]
It is due to the way that the Universal cables act for some reason. It also happens with Ender IO Capacitor banks, and potentially other power storage modules. Nothing Reika can do about this, short of blacklisting them from connecting to his batteries, if that is even possible.

**Comment by Haggle1996** [comment]
Yar, this is not an ElectriCraft issue.
