### ISSUE TITLE
Empty Canister Issues when Filled

### ISSUE THREAD

**Issue by madolinn** [ReikaKalseki/Reika_Mods_Issues#38]
Empty Canisters come in sets of 16 when made. Recently when being pulled off the crafting table I'll get a stack of 15 that stack, and a single one that doesn't stack with the rest.

When filled inside the Uranium Processor, if you use more than 1 the rest of the stack is deleted, and only 1 is returned. Having multiple filled canisters also don't allow them to stack.

**Comment by 1Matthias** [comment]
I assume this is v6f?

**Comment by madolinn** [comment]
Yes sir man sir.

**Comment by 1Matthias** [comment]
> Yes sir man sir.

At this point, I will just assume that you are up to date.

**Comment by madolinn** [comment]
I mean I can crash my game just for you, but I like to assume I'm in good trust standing :+1:

**Comment by zemerick** [comment]
Ok, I see at least part of the issue.

The canister item extends itemReactorTool, which has a max stack size of 1. The canister does not have its own size set, so despite being created in a stack of 16 it wants to be only 1 per stack. You can test this as the stack splitting doesn't stop at 15 and 1. If you keep splitting off canisters, they will keep refusing to stack.

This might even be related to the stack overwrite in the processor.

**Comment by ReikaKalseki** [comment]
I fixed the canister destruction. The nonstackability is intentional.
