### ISSUE TITLE
Hydrokinetic engines + Liquid Cyanite or Yellorium odd interaction

### ISSUE THREAD

**Issue by Reignofmagic** [ReikaKalseki/Reika_Mods_Issues#380]
Cyanite and Yellorium fluids from Big Reactors. There is no way to make them, plus if you try to move them via buckets you get a bucket of water. These fluids are listed as WIP by the BR Mod Dev and are not intended to appear anywhere but in the reactor itself. 

Not sure if you can do anything about this aside from blacklisting these two fluids, but if you are able to use them as the fluid for the hydrokinetics. (Way I figured out was Rftools/mystcraft world, then move the fluid with the RFTools builder) it only needs a 1 block fall to cause the hydrokinetic to run at full power. Really neat if you want a compact hydrokinetic plant, but also not intended.

**Comment by ReikaKalseki** [comment]
How did you manage to obtain them?

If they are unobtainable, I care little about in-world effects, as it would never be encountered. Also, if it only needs one block of fall, then the fluid has a very low viscosity and a very high density. Ask the mod dev to pick more reasonable values.

**Comment by Reignofmagic** [comment]
@ReikaKalseki 

As I stated in the first post.

Get a Dimlet/Page for fluid cyanite/yellorium (Dimlet is named something like bigreactors.fluids.stillcyanite for the name, haven't looked into mystcraft yet). Have the world generate as an ocean replacing all fluids with the cyanite/yellorium. 

Use a RFTools builder to move the blocks/liquid sources (using either swap or move mode). 

As long as the fluid source is 1 block above the Hydrokinetic it will fully power it. I shall let the BR Dev know this as well. 

Also unfortunately, the last commit to Big Reactors Dev, and the last anyone has seen from him was around 6 months ago.

**Comment by XFactHD** [comment]
Those fluids must not be used nor obtained by the player, they are just for internal use in BigReactors!

**Comment by lossycrypt** [comment]
Maybe @McJty could blacklist the dimlets if the fluids are not supposed to be obtainable?

**Comment by McJty** [comment]
Well I don't necessarily agree about that. There are valid uses for the liquids (make them into ingots) and modpack makers can always blacklist them on their own if they want.

**Comment by XFactHD** [comment]
Take a look at this issue, the developer himself explained it: erogenousbeef/BigReactors#475
