### ISSUE TITLE
ReactorCraft - HTGR core not heating up

### ISSUE THREAD

**Issue by Haresus** [ReikaKalseki/Reika_Mods_Issues#381]
Reika's mods v9b, Java 8

Today I've tried setting up test reactor setup on my creative world, pebble bed cores (4 cores, 4 exchangers, surrounded with RC concrete) won't heat up, oscilating between 180-250C.
It is supplied with fresh pebbles and should be dumping depleted ones through vanilla hoppers

![setup](http://imageshack.com/a/img911/3769/FB7IIu.png)

It's been sitting like that for about half an hour now.

**Comment by Haresus** [comment]
An hour on the clock, it just burned out it's first pebble, still ~190C

**Comment by ljfa-ag** [comment]
IIRC a while ago the heat output of pebble bed reactors have been nerfed quite a bit. I would guess you need more than 4 cores.

**Comment by Haresus** [comment]
8 core cross-shaped setup oscilating around 500C,
12 core 3x3 setup keeps oscilating around 550C,
16 core 3x3 setup finally runs a turbine outputting somewhere around 925MW.

Thanks for the suggestion.

I'd suggest adding info about minimal size requirement into RC Handbook, up to date info on RC is quite hard to come by

Closing

**Comment by ljfa-ag** [comment]
Hm well
testing it in a creative world can be helpful too.
And I guess the minimum also depends on the arrangement of the blocks.

**Comment by ReikaKalseki** [comment]
There is no hard-set minimum size requirement. Reactor design is emergent.

Also, since building it larger did not initially occur to you - which strongly hints at your following some tutorial somewhere, as I would have expected a larger reactor to occur to you if you designed it yourself with an understanding of how they work - what resource were you using that told you "build it like this"?

**Comment by ljfa-ag** [comment]
Well I guess there are many "build exactly this and you get something that works" tutorials. A bit unfortunate that they _will_ become outdated after a while.

**Comment by ReikaKalseki** [comment]
> A bit unfortunate that they will become outdated after a while.

I deliberately break them. That was the core reason for many of the HTGR redesigns.

**Comment by Obliterous** [comment]
At least now I know why my HTRG reactors quit working after updates. A strong argument to stick with BigReactors.

**Comment by Aivech** [comment]
On the original posters note, I was able to run a steam turbine in creative with a 4:1 ratio of cores to heat exchangers, with insulation (glass). Also, who uses HTGR's for primary power if they can get a fission reactor?

**Comment by 1Matthias** [comment]
@Obliterous Also, once you can get get Fission and other, better reactors...HTGRs are only intended to get you started, kind of like the DC engine in RoC. (As far as I know.)

**Comment by ReikaKalseki** [comment]
> A strong argument to stick with BigReactors.

Yes, if you are the kind of person who abhors mental effort and wants everything spoonfed to you. The design of the reactor those nerfs was specifically designed to break was almost without exception copy-pasted from a tutorial with little or no understanding on the part of the user. You are correct in that if you want a mod where you can turn your brain off and copy something off the internet and then forget about it, you want BigReactors.

**Comment by Obliterous** [comment]
Well, considering that I built my reactors using trial and error, and not a tutorial, it appears to me that I've been punished for figuring out something that worked, and I'm saddened that someone sharing the knowledge fruits of their labor offends you in some way.

**Comment by ReikaKalseki** [comment]
Trial and error is not the way to learn how to build reactors. Also, what irritates me was saying

> A strong argument to stick with BigReactors

as if never improving anything is a good thing.

**Comment by Obliterous** [comment]
given the quality of the available documentation, trial and error was the best method that worked for me.

My issue is not with improvements; my issue is with changes that are intended to break things simply because someone decided to share what they figured out, especially when that change punishes the people that figured it out on their own, no matter what method they used.

**Comment by ReikaKalseki** [comment]
There is a large amount of available documentation - including ingame - and more is in the process of being created. On top of that, do you not see the issue with people simply copying someone else's build, in a _knowledge and understanding-gated mod_?

**Comment by Aivech** [comment]
I think the problem he has is with it breaking players builds who figured it out themselves, more so than that of breaking tutorials...

**Comment by WOSAJ** [comment]
Reika just wants to bring the reactors closer to the real thing :)

**Comment by Obliterous** [comment]
> 
> 
> Reika just wants to bring the reactors closer to the real thing :)

thank you for necroing a thread five years dead.
