### ISSUE TITLE
v10 please?

### ISSUE THREAD

**Issue by dwhofan** [ReikaKalseki/Reika_Mods_Issues#382]
Can I please have a link to v10?

**Comment by zemerick** [comment]
https://sites.google.com/site/reikasminecraft/latest-downloads

**Comment by ljfa-ag** [comment]
No asking for ETAs here please

**Comment by ReikaKalseki** [comment]
www.fakeserver.net/mc/mods/doesntexist/rotarycraft-v10.jar

**Comment by lossycrypt** [comment]
Simply set your Tardis to next year and visit the official site on arrival.

**Comment by dwhofan** [comment]
the link doesn't work?

**Comment by ReikaKalseki** [comment]
Glue is an adhesive, not a condiment.
