### ISSUE TITLE
NullPointerException TinkerToolHandler

### ISSUE THREAD

**Issue by NachtRaben** [ReikaKalseki/Reika_Mods_Issues#383]
Using most recent versions of rotarycraft, reactorcraft, electricraft, chromaticraft, tinkers construct, and Iguana Tinkers Tweaks for minecraft version 1.7.10 as of 11/17/2015.

Shift breaking a dirt block with any tinkers shortbow produces this stacktrace and instantly crashes.

http://hastebin.com/ugureqonir.avrasm

**Comment by OneEyeMaker** [comment]
Please, use search before adding issue. 
Seems like a duplicate of https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/318
