### ISSUE TITLE
ChromaticCraft/Compression NPE Crash

### ISSUE THREAD

**Issue by Thiana** [ReikaKalseki/Reika_Mods_Issues#385]
Minecraft is crashing at startup with a NPE error. I initially reported it to Compression's author but they requested I report it here. The Compression issue is at TheTemportalist/Compression#3.

Crash details at http://openeye.openmods.info/crashes/4d42fc1f786603a11d9cbbe8914e7109

To reproduce the error, create an instance with DragonAPI 9b, ChromaticCraft 9b, Origin 6.0.1b1 and Compression 0.0.3. Try to start the game. Crash. Disable either mod and the instance works perfectly.

Thanks.

**Comment by ReikaKalseki** [comment]
It is on their end, no matter what they claim. They are calling player-specific functions with a null player.

**Comment by TheTemportalist** [comment]
I wasnt claiming anything. I just wanted to make sure it wasnt something which was in code I couldn't access. Thank you for your input.

**Comment by ReikaKalseki** [comment]
> I wasnt claiming anything.

I said that pre-emptively. As you may or may not know, most crashes or errors that somehow involve my mods get blamed on me, no matter the actual cause, and often even in the face of glaring evidence to the contrary.

**Comment by TheTemportalist** [comment]
Mhmm. Sorry bout that mate. I can comprehend where you are coming from then. Thanks for providing input on the issue!

**Comment by ReikaKalseki** [comment]
:P
