### ISSUE TITLE
Fermenter ignores redstone from SFM Advanced Cable Cluster Emitter.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#386]
The Fermenter does not switch target to sludge if a redstone signal is applied with a Steve's Factory Redstone Emitter that is inside an Advanced Cable Cluster. (It works as expected if the Emitter is not in a Cluster). The Fermenter block itself is redstone powered and does power other blocks as expected thought.

Here's a screenshot with a redstone torch and redstone lamp for visualization (notice how in the middle case the torch and lamp react to the applied redstone while the Fermenter does not):

![3states_text](https://cloud.githubusercontent.com/assets/14168854/11048043/e2f786e6-8735-11e5-8f5e-572ddc5cbab1.jpg)

**Comment by ReikaKalseki** [comment]
The block is not providing power properly if the tests return false at this location. My guess is rather than powering the block normally, it sets the location to be "strong" powered. Except even that normally works (ie lever on the side).

**Comment by lossycrypt** [comment]
The emitter has two settings weak and strong. Neither works. I just chose strong as an example because in my crude understanding of redstone mechanics that best demonstrates that the block is powered because it propagates to adjacent blocks. I do not understand why the block isn't "properly" powered if it is indeed the same as being powered by a lever.

Btw, if i place a piece of redstone next to the fermenter, then the fermenter powers the redstone and in turn gets powered by the redstone (that's my guess anyway) which makes it switch to sludge mode.

**Comment by lossycrypt** [comment]
So while doing something else i noticed the same issue also occurs with EnderIO Insulated Redstone Conduit.
I also more importantly noticed that it actually does work, it's just the GUI that's not updating (and apparently the dynamometer/engine renderer only work when you look at them directly).

![2015-11-28_17 43 40](https://cloud.githubusercontent.com/assets/14168854/11452916/e3f61df2-95f7-11e5-86c4-b752df662e08.jpg)
![2015-11-28_17 44 05](https://cloud.githubusercontent.com/assets/14168854/11452918/e91f9dbc-95f7-11e5-9dda-f5ed51809811.jpg)

**Comment by ReikaKalseki** [comment]
That is because those mods only supply redstone on server side, which causes a desync between client and server. This is a bug (or, if intentional, a very poor design choice) on their end. Is that also the case for SFM?

**Comment by TomeWyrm** [comment]
Intentional for performance reasons from both mods from what I am lead to understand.

**Comment by ReikaKalseki** [comment]
There are no performance benefits to speak of.

**Comment by ReikaKalseki** [comment]
There are no performance benefits to speak of.

**Comment by TomeWyrm** [comment]
That is apparently the reason that Skyboy and/or PowerCrystals gave for that decision in regards to MFR.

Not as sure on SFM, but there is apparently SOME benefit to doing it that way; otherwise why break from the standard implementation?

**Comment by lossycrypt** [comment]
I only tested SFM on the Fermenter before making the pictures, but yea, it behaves exactly the same. Fermenter makes sludge but GUI shows yeast. Didn't test with rednet cables.

**Comment by ljfa-ag** [comment]
They probably want to avoid doing the same calculation on both client and server, or if they don't do this, the network overhead from sending update packets to the client. Might be sensible if you consider that the redstone signal could change every tick, and that the calculations might be expensive or involve variables that only the server knows.

**Comment by ReikaKalseki** [comment]
Even if the computation were expensive or impossible on the client, sending that data in a packet is easy and causes no load to speak of, especially if done intelligently.
