### ISSUE TITLE
BlockArray.getAllDroppedItems & ProgressiveRecursiveBreaker doesn't call Forge HarvestDropsEvent

### ISSUE THREAD

**Issue by squeek502** [ReikaKalseki/Reika_Mods_Issues#387]
Forge provides an event (`HarvestDropsEvent`) that allows modification of the drops of a harvested block. See [this function](https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/src/main/java/net/minecraftforge/event/ForgeEventFactory.java#L152-L157) and where it is called in Minecraft code.

To add support for this event to `BlockArray` and classes that extend from it (like `TreeReader`), you'd need to add a `ForgeEventFactory.fireBlockHarvesting` call [after this `Block.getDrops` call in `BlockArray.getAllDroppedItems`](https://github.com/ReikaKalseki/DragonAPI/blob/master/Instantiable/Data/BlockStruct/BlockArray.java#L838), which would also mean that the player would need to be passed to `getAllDroppedItems`.

Related: https://github.com/bspkrs/Treecapitator/pull/33 and https://github.com/squeek502/VeganOption/issues/30

**Comment by ReikaKalseki** [comment]
That can probably be done with little difficulty.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by ghost** [comment]
This pleases me. ;)

**Comment by squeek502** [comment]
:+1:
