### ISSUE TITLE
ExtrabiomesXL Grinder Registration error.

### ISSUE THREAD

**Issue by RoloEdits** [ReikaKalseki/Reika_Mods_Issues#388]
http://pastebin.com/uTwYpyT6

**Comment by ReikaKalseki** [comment]
ExtraBiomesXL has multiple block types all registered as "log". I was not aware this was even possible, as FML should stop duplicate names.

**Comment by RoloEdits** [comment]
Very strange, What would even be the purpose of doing this I wonder.

**Comment by ReikaKalseki** [comment]
I have an answer, but I will not say it.

**Comment by ReikaKalseki** [comment]
I put in a workaround.

**Comment by RoloEdits** [comment]
Thanks :)
