### ISSUE TITLE
Geostrata Request: cross-mod interchangeability

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#390]
A few other mods add their own versions of Basalt, Marble, Granite, and Limestone. Currently, they are not interchangeable/convertable. they are functionally the same as far as I know.

Off the top of my head, Chisel, Botania, Project Red, Mariculture, and Et Futurum.

**Comment by ReikaKalseki** [comment]
I have no desire to do this. They are already OreDicted for recipe purposes, but I do not like the idea of actual transmutation.
