### ISSUE TITLE
Crossmod issue Chromaticraft/DragonAPI Matter Overdrive

### ISSUE THREAD

**Issue by 1skandar** [ReikaKalseki/Reika_Mods_Issues#391]
Apparently being an android does bad, bad things to Chromaticraft's GUI's
![2015-11-12_07 20 36](https://cloud.githubusercontent.com/assets/4127779/11118552/bc07cbb8-8910-11e5-8797-2a43f01806dd.png)

I'm not sure who is at fault here, so reporting it in both places.

https://github.com/simeonradivoev/MatterOverdrive/issues/315

**Comment by ReikaKalseki** [comment]
I have custom render code - that included ASMing into GuiContainer's drawScreen - but it should not spontaneously stop working. I suspect MO is doing something odd with zLevel or OpenGL state in his GUI code.

**Comment by ReikaKalseki** [comment]
Fixed on his end.
