### ISSUE TITLE
Rotarycraft--generators & galacticraft 

### ISSUE THREAD

**Issue by apdjz** [ReikaKalseki/Reika_Mods_Issues#393]
I tried to use the gasoline engine as well as the gas turbine in a spacestation from galacticraft. Is there a mechanic that makes it require oxygen?  The engines wont run even with fuel.

**Comment by kolatra** [comment]
Yes. They cannot be used from space. This has been posted multiple times.

**Comment by ljfa-ag** [comment]
We had that discussion in #346. It will be possible in v10 in areas where there is oxygen.
