### ISSUE TITLE
ChromatiCraft: NullPointerException from ItemBlockCrystalColors#getItemStackDisplayName if called before world is loaded

### ISSUE THREAD

**Issue by Choonster** [ReikaKalseki/Reika_Mods_Issues#395]
DragonAPI: 1.7.10 V9b
ChromatiCraft: 1.7.10 V9b
[Crash Report](https://gist.github.com/Choonster/27e37f1fddbd57e18d1b)

If `ItemStack#getDisplayName` is called on a stack of `ItemBlockCrystalColors` on the client side before the world has loaded, a `NullPointerException` is thrown because `Minecraft#thePlayer` is `null`.

My test mod adds use stats for modded items ([implentation](https://github.com/Choonster/TestMod2/blob/f45dc66e8ff004094a481fc2ce9b46b568768f0c/src/main/java/com/choonster/testmod2/tweak/moddedstatsfix/ModdedStatsFix.java), called in postInit) and this involves getting the display name of each item (which causes this crash).

Should ChromatiCraft ignore the obfuscation of crystal names before the world has loaded or should I just defer fetching the display name until it's needed?

**Comment by ReikaKalseki** [comment]
"Display" implies an available rendering context. If you must call display name (as opposed to localized name) name outside that context, use a try-catch. That was the solution when a similar issue came up recently.

**Comment by Choonster** [comment]
Fair enough. I'll still need the display name at some point, so I'll just defer the call until the name needs to be rendered somewhere.
