### ISSUE TITLE
MiEx erratic mining behavior.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#396]
The CC Mineral Extractor behaves unexpected for some types of block. While the GUI counts down the block normally the block is not actually harvested (can be seen on collecting side) and breaking + rescanning the area again after the first mining run "finished" shows the ores with correct numbers again. (Unless otherwise stated i'm using a fully upgraded MiEx with one efficency, speed and silk touch upgrade each.)
##### Erratic mining:
- All CC ores
- All CC plants
- Botania cave mushrooms

Symptoms: Blocks in this category are ignored _most_ of the time. (Meaning _some_ of them are mined properly).
Possible causes: Removing the silk touch upgrade _seems_ to solve most of this. I also tried putting a 19x19 chunk loader but am unsure if that did anything except significantly increase cpu cost (+10ms).
##### Shown in scan, not mined:
- Nether Glowstone blocks
##### Not shown in scan, not mined.

"Forestry":
- Forestry Hives. (It mines CC hives, so this is unintuitive.)

"[Nether Ores](https://github.com/powercrystals/NetherOres)" (incomplete list, cross mod dependant), (NetherOres:tile.netherores.ore.1:n):
- Nether Amber Ore (Thaumcraft, n=11)
- Nether Salt Ore (Pam's Harvest?, n=13)
- Nether Mithril Ore (Thermal Foundation, n=7)
- Nether Ruby Ore (ProjectRed?, n=13)
- Nether Tungsten Ore (Mariculture, n=10)
- Nether Magnesium Ore (Mariculture, n=15)
- Nether Rutile Ore (Mariculture, n=9)

**Comment by ReikaKalseki** [comment]
Everything not shown is deliberately ignored. The ores are not in my registry and the extractor does not mine hives.

**Comment by ReikaKalseki** [comment]
Fixed.
