### ISSUE TITLE
Blast Furnace cools down when heated by heat lamp and tile-accelerated.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#399]
If the Blast Furnace is heated by a heat lamp and a cc tile accelerator (tested with x16) is attached to it, the temperature will drop to far below working temperature (but not quite down to biome temperature). This does not happen when heating with lava. The Fermenter is also not affected. Workaround: Tile-accelerating the heatlamp with a second accelerator.

**Comment by TomeWyrm** [comment]
I suspect this is intended (or a side-effect of intended mechanics). The Blast Furnace is checking 16 times as often for the temperature, which means it most likely only gets 1/16th the temperature adjustment of the Heat Lamp, which being a Tile Entity is likely providing this heat periodically. Lava on the other hand is most likely checked directly in the temperature code.

Note: I'm not digging through the code right now to verify this. I'm betting ANY environmental/block-based temperature adjustments accelerate with a Tile Accelerator. The heat lamp is a TE though, and exists in a different part of the code, and hence requires its own accelerator.

**Comment by ReikaKalseki** [comment]
TomeWyrm is entirely correct. I also added special code as of v10 to fix it.
