### ISSUE TITLE
Pylons don't always shut down when broken.

### ISSUE THREAD

**Issue by madolinn** [ReikaKalseki/Reika_Mods_Issues#4]
Removing blocks from a pylon structure should cause it to shutdown. Occasionally pylons don't abide by these rules and stay powered forever.

![Figure 1: Pylon has Rune removed and a Structural Block](https://cloud.githubusercontent.com/assets/10469156/7221566/35afadce-e6bd-11e4-83a8-ce553dc88d0c.png)
![Figure 2: Caused some more damage. Removed Stabilizer and more runes.](https://cloud.githubusercontent.com/assets/10469156/7221573/857303a6-e6bd-11e4-9686-d20ddf2b1cba.png)

As you can see from Figure 2, even after the events of Figure 1 I was still killed from the pylon.

**Comment by ReikaKalseki** [comment]
Is it only when breaking runes?

**Comment by madolinn** [comment]
Oh, picture ALT text doesn't show.

No that pylon is completely immune to shutting down. I can remove every single block and it will last forever. Removed Stabilizers, more runes, some random structural elements. It remains active.

This happens quite often as well. On my previous world about 1 in 4 would stay alive which made gathering our first few rune sets difficult (since we opted to not craft them).

**Comment by ReikaKalseki** [comment]
Is it tied to specific pylons or colors?

**Comment by madolinn** [comment]
Since the time of posting I've been flying around breaking them trying various things. It seems to be an issue with pylons that generate on uneven grounds so that their base is extended downwards.
![Immortality](https://cloud.githubusercontent.com/assets/10469156/7221714/c43f8fbc-e6c4-11e4-8b08-e0241d8ce2b6.png)
Restarting does not remedy it. Something also to note is that the previous pylon I completely destroyed, which was supposed to be immortal, did end up dying after removing nearly every block. The only difference is from these two, is the pseudo-immortal one was generated "broken" from a world gen ravine going through it, however it was still actively shooting things.

**Comment by madolinn** [comment]
Artificially extending the base downwards on pylons causes them to be unable to reactivate. Removing the placed blocks allows them to reactive. Safe to say this is the issue.

**Comment by ReikaKalseki** [comment]
I have an idea.

**Comment by ReikaKalseki** [comment]
This is probably fixed.
