### ISSUE TITLE
Steam Scrubber Client Crash

### ISSUE THREAD

**Issue by quedral** [ReikaKalseki/Reika_Mods_Issues#40]
Placing steam scrubber while steam flowing causes this client crash: 

http://pastebin.com/KUWPgCYL

it is highly reproducible (at least for me). It only crashes client.

Latest version.

**Comment by zemerick** [comment]
I did just that a number of times yesterday without issue, so it's most likely something specific to your install. Off hand guess would be your much newer forge version. I'll be on to test that in a bit.

If you can, try removing all other mods and testing if that makes any difference.

**Comment by quedral** [comment]
I'll do that when i get back. However i don't think that is a forge issue. It happened on 1291 as i was testing few things on my test world like month ago when this block was introduced. I lost the crash logs regarding of those and i am sorry for that.

**Comment by zemerick** [comment]
No worries, we'll find it yet, and you were right. I just tested with forge 1373, and did not get this crash.

Is there a pack download somewhere so I can start testing as well? ( Well, after lunch:P )

You mention it being "highly reproducible", could you give more specifics? Is it every time? Placed a certain height above the grate? Is it next to a certain other block? Anything you can think of really. Better to provide too much than not enough info:)

**Comment by quedral** [comment]
I was placing one over turbine generator(facing directly steam bypass) then boom.
2nd time i put a stone block near steam flow and i placed the the scrubber pointing stone block then crashed again. My client has optifine installed (server doesn't have that) It maybe optifine issue as well. I will test more.

**Comment by 1Matthias** [comment]
It is not optifine, as the admin on a server I play on has found this error.

**Comment by ReikaKalseki** [comment]
Could not reproduce, and comments from others point to Optifine.

**Comment by 1Matthias** [comment]
If you want, talk to Demo. He has been able to reproduce this issue with his reactor, and he is not using optifine.

**Comment by zemerick** [comment]
Can you get him to post here?

Also, can he reliably reproduce it, or was it a 1 off for him as well?
