### ISSUE TITLE
Ammonia synthesizer temperature drops to ~10°C when player not near but still works.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#400]
(Tested in a desert cave at y=12. Newly placed synthesizer starts at 90°C. Measured with Angular Transducer.)
I have an ammonia synthesizer placed above a block of lava for heat. When i stand near it it heats up slowly as it should. But if i go away to my main base (more than 20 chunks away) and immediately come back it has dropped to 10°C and starts slowly heating up again. (The area is chunkloaded). This drop in temperature does not make it stop work, and it only starts to work if it has reached 200°C at least once. The progress bar in the GUI does not render properly if it is working while below 200°C.

**Comment by ReikaKalseki** [comment]
Player proximity and temperature code do not interact.

**Comment by ReikaKalseki** [comment]
This is a NBT persistence issue (caused by field shadowing) and has been fixed.
