### ISSUE TITLE
Estimated time until updating Forestry interactions?

### ISSUE THREAD

**Issue by border999** [ReikaKalseki/Reika_Mods_Issues#401]
Since this is such a serious issue for those people that use both your mods and any relatively up-to-date version of Forestry, I take it upon myself to launch an inquiry about how long it will be until people are able to use both the latest Forestry and the latest of your mods.

**Comment by border999** [comment]
Or, if it will not be possible to update the API for some time. Might I suggest a temporary measure such as a config option to disable integration between DragonAPI and Forestry.

**Comment by ljfa-ag** [comment]
This has been suggested before but unfortunately it's not as easy as that. It might be possible but it's not worth the effort to implement. Also then people would expect the same thing for all mod interactions.

**Comment by border999** [comment]
Understandable, but it's still a desirable goal to be able to use both DragonAPI and a latest version of Forestry again.
