### ISSUE TITLE
ItemBlockFluorite.getHasSubTypes()

### ISSUE THREAD

**Issue by Thiana** [ReikaKalseki/Reika_Mods_Issues#403]
When ReactorCraft rainbow fluorite is enabled, getHasSubTypes() is returning true when it should probably be false? This forces you to use getSubItems() to check if rainbow or all fluorites are active.

See https://github.com/ReikaKalseki/ReactorCraft/blob/f4ddf419178332d31ab7e655cff7b95528d795b5/Items/ItemBlockFluorite.java#L29

PS: Rainbow Fluorite is localized as 'Blue Fluorite'.

**Comment by ReikaKalseki** [comment]
Even if "Rainbow Fluorite" is enabled, the ore block still has all the subtypes (which are still available in creative). Just the first (originally blue) is retextured and renamed and is the only one to generate.

The whole system is a hack I only added by request from the FTB team, and that I designed to work retroactively.

Why do you need to know if the config is active? Even if getLocalizedName() still returns blue fluorite, clearly some display-name function is returning the appropriate name.

**Comment by Thiana** [comment]
I needed to know the rainbow config is active in order to determine which ores to skin with which textures (to fit in with Underground Biomes).

If the other subtypes exist why does getSubItems() only show one fluorite when rainbow is true? Only the rainbow one appears in the creative menu/output.

**Comment by Thiana** [comment]
Actually, they all seem to return Blue Fluorite not Rainbow. I'm detecting the rainbow config by checking if getSubItems() returns more than one item.

**Comment by ReikaKalseki** [comment]
> If the other subtypes exist why does getSubItems() only show one fluorite when rainbow is true? Only the rainbow one appears in the creative menu/output.

You answered your own question. :P

But more directly, I honestly would rather just remove the rainbow Fluorite entirely than add handling for it.

**Comment by Thiana** [comment]
So just to clarify, since the lack of forge/mc documentation makes things a bit confusing. It's expected behavior for getSubItems() on an item to also return that item in the list? Or is that only happening because of the hack you mentioned? Thanks.

**Comment by ReikaKalseki** [comment]
I am not sure what you are asking.
