### ISSUE TITLE
Server crash on entering dimensions

### ISSUE THREAD

**Issue by El-Gunnie** [ReikaKalseki/Reika_Mods_Issues#404]
The server crashed with the following crash log when we either try entering or exiting a dimension. We spawn inside the correct dimension after the server starts back up. When we remove ChromatiCraft, there are no more crashes. 

http://pastebin.com/QpdNUfa4

We've already tried to follow the instructions for the error on line 394, but the server kept crashing. 
Fastcraft is enabled on the server.

**Comment by ReikaKalseki** [comment]
Your network cache is corrupt. Delete crystalnet.dat.
