### ISSUE TITLE
Issue with Extra Cells Fluid Storage Bus and Reservoirs

### ISSUE THREAD

**Issue by ljfa-ag** [ReikaKalseki/Reika_Mods_Issues#405]
Fluid Storage Buses seem to drain the wrong liquid from Reservoirs and silently convert them to other liquids. I reported it at ExtraCells/ExtraCells2#323, there is a more precise description.

My theory is that firstly, [the `drain` method](https://github.com/ReikaKalseki/RotaryCraft/blob/master/TileEntities/Storage/TileEntityReservoir.java#L313) on the reservoir does not check if the given FluidStack has the same fluid as is in the reservoir, and secondly, that ExtraCells does not check if the returned fluid stack has the same fluid as it requested. I would guess that `drain` is supposed to return null if the fluid types don't match.

**Comment by ReikaKalseki** [comment]
Fixed, with great time investment on my end.
