### ISSUE TITLE
AE2 Charged Certus Quarz Ore returns normal flakes in Extractor.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#407]
The Extractor treats the more valuable "Charged Quarz Ore" as normal "Quarz Ore" and produces normal flakes instead.

**Comment by ljfa-ag** [comment]
When grinding, mixing, sieving, crystallizing and smelting the charged ore, it's reasonable to assume that it loses its charge :p
It's not like you need a whole of it, once you have one you can charge yourself more. Maybe it would be better if instead the ore is not accepted by the extractor.

**Comment by ReikaKalseki** [comment]
They are OreDicted together under the same name, and thus are both treated identically.

**Comment by lossycrypt** [comment]
Charged Ore does infact have two different ore dictionary entries. After checking NEI the EnderIO Sag Mill seems to be the only automatic processing option that actually gets charged crystals from it though (in my pack at least). :|

```
oreCertusQuartz
oreChargedCertusQuartz
```

**Comment by ReikaKalseki** [comment]
oreCertusQuartz includes both. So they both get treated as Certus Quartz.

**Comment by lossycrypt** [comment]
If you checked for oreChargedCertusQuartz first tho it should be possible to tell them apart?
Just to be sure: Are you saying you _can't_ fix this, or you don't _want_ to fix this?

**Comment by ReikaKalseki** [comment]
That is not how the registry works.

https://github.com/ReikaKalseki/DragonAPI/blob/master/ModRegistry/ModOreList.java#L40

**Comment by TomeWyrm** [comment]
Do enums not create ordered lists? Could you not do an if/then check for Certus =/= charged?

**Comment by ReikaKalseki** [comment]
All the Extractor does is ask the registry what enum entry an ore corresponds to, and then process it accordingly.

**Comment by TomeWyrm** [comment]
Does it return the first entry, a random entry, an array, or an ordered list?

Because it not returning EVERY value that an item exist at under the ore dictionary seems a bit odd. In any case how have you handled this in the past? There have to have been goofy oredict double-books like this in the past

**Comment by ReikaKalseki** [comment]
No, in fact, collisions are not a thing. As it currently stands, a double-entry would crash in the grinder code, as it would register the same item to two different recipes.
