### ISSUE TITLE
[Suggestion] Add Info "?" sidebar to Reactor Craft machines.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#408]
All RotaryCraft machines have a small question mark sidebar to quickly open the handbook page for the machine. It would be nice if this could be made available to ReactorCraft machines GUIs too.

**Comment by ReikaKalseki** [comment]
Done.

**Comment by lossycrypt** [comment]
Thanks for the fixing spree.
