### ISSUE TITLE
DragonAPI and Spigot 1.7.10

### ISSUE THREAD

**Issue by Tencao** [ReikaKalseki/Reika_Mods_Issues#409]
This crash is constant, and happens even if no other mods are present except Dragon API. This makes hub worlds, and bungee networks impossible. 

http://pastebin.com/JbvCTVbb

That is the error above, I've tested this on a bungee network, directly connecting to a server, various version of spigot ranging from old to new, and even the recommended and latest forge.(10.13.4.1558 & 10.13.4.1566)

**Comment by ljfa-ag** [comment]
Spigot and other modified server variants are not supported, they make breaking changes to Minecraft and Forge code.
