### ISSUE TITLE
ChromatiCraft Beehives Don't Create Drops Properly

### ISSUE THREAD

**Issue by madolinn** [ReikaKalseki/Reika_Mods_Issues#41]
ChromatiCraft Beehives drop bees when broken with a pickaxe, and do not drop anything when broken with a scoop. This should be flipped.

DragonAPI v6f
ChromtiCraft v6f

**Comment by 1Matthias** [comment]
Well...while it does not make sense, that is how it has been chosen to behave.

**Comment by madolinn** [comment]
... why? If there's already support for Forestry, while not just add when broken by tool scoop?

**Comment by trajing** [comment]
Aren't they made out of stone? It makes sense, if you think about it.

**Comment by 1Matthias** [comment]
> Aren't they made out of stone? It makes sense, if you think about it.

Correct, just like Rock hives from Extra Bees.

**Comment by ReikaKalseki** [comment]
@trajing and @1Matthias are correct, plus the implementation headache of requiring a tool from another mod to harvest.

**Comment by TomeWyrm** [comment]
At the very least you should probably add support for the scoop, that is what forestry users are trained to use for hives. Keep them harvestable with a pickaxe too, but a hive that can't be harvested with a scoop is just... odd

**Comment by ReikaKalseki** [comment]
I really do not want to have to write that handling.
