### ISSUE TITLE
Pump Depth Limit

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#411]
I've heard mention that this is intentional, but figured I'd report it anyways, just to be certain; it doesn't seem to be submitted in this tracker, open or otherwise.

The RotaryCraft pump seems to have a distance of 2 blocks; meaning that when the closest source block beneath it is two blocks down, the pump will stop pumping.  This is not an issue with water, as it has the ability to renew.  However, when pumping non-renewable fluids, such as lava or BC oil, this can be tricky, especially when the source is deeper than 2 blocks.

Is this intentional?  Is there some form of upgrade that extend the pump's depth or withhold collecting the block underneath the pump until all connected fluid blocks are removed?  Or is this an issue that needs to be corrected?

**Comment by ReikaKalseki** [comment]
The pump was never designed for such fluids, though a sufficiently large lava lake will be in fact infinite.
