### ISSUE TITLE
Feature Request: HSLA Pickaxe Harvest Level Configurability

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#412]
This is simply an extension of a request made on the thread.

In the Survival Industry modpack, iron is no longer capable of mining diamonds; it is, in fact, no longer in the mining progression (being completely bypassed by bronze, which makes slightly better hand-held tools in reality).  However, the reason iron is more important than bronze is its ability to make steel, which blows away both iron and bronze in material properties in real life.  This means that while iron (and bronze) cannot mine diamonds in this modpack, steel should have no problems doing so.

So, what I'm requesting is the ability to assign a different harvest level value (currently 5) to HSLA steel in the configuration, if it is at all possible, so it can, unlike iron, mine diamonds.

**Comment by ghost** [comment]
For completeness, here are the stats I'm using through SquidUtils for iron and (non-HSLA) steel:

```
iron {
    D:attackDamage=2.0
    I:durability=250
    D:efficiency=6.0
    I:enchantability=14
    I:harvestLevel=4
}
```

```
steel {
    D:attackDamage=3.0
    I:durability=750
    D:efficiency=8.0
    I:enchantability=18
    I:harvestLevel=5
}
```

**Comment by ReikaKalseki** [comment]
This was already implemented when you asked before.

**Comment by ghost** [comment]
Fair enough; the last I heard on this was you asking what harvest level I intended, so I didn't really know where this was.  Thanks for the clarification.
