### ISSUE TITLE
Extractor "Draconium Item" is ore:draconiumDust instead of ore:dustDraconium.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#413]
Target mod version: Draconic-Evolution-1.7.10-1.0.2-Snapshot_5-Bugfix.jar (latest).

Processing Draconium Ore with the RoC Extractor gives "Draconium Item" with ore dictionary entry "draconiumDust " but the mod actually uses "dustDraconium" and "ingotDraconium".

Edit:
And there's also no crafting recipe to turn it into anything useful like with e.g. Thaumcraft "<$Element> Infused Item"

**Comment by ReikaKalseki** [comment]
So he changed it. Lovely. At least it is correct now...

**Comment by ReikaKalseki** [comment]
Fixed.
