### ISSUE TITLE
NEI Recipe Lookup crash

### ISSUE THREAD

**Issue by robaimes** [ReikaKalseki/Reika_Mods_Issues#414]
http://pastebin.com/bVpF49Aa

Looked up the recipe for an item from Ender IO in NEI, producing this crash.

Using RotaryCraft, ReactorCraft, DragonAPI and Electricraft. All v9b.

**Comment by ReikaKalseki** [comment]
Triplicate or more.

**Comment by robaimes** [comment]
Sorry, my bad. I've actually read about it before but completely forgotten. I know Minemarten said the issue should be fixed, yet I have both the latest versions of your mods and PnC. Any clarity you can provide to a 'fix' or is it still an issue with PnC?

**Comment by ReikaKalseki** [comment]
It is not so much PnC's fault so much as Forge for fundamentally changing the way the Fluid Registry works.

**Comment by robaimes** [comment]
Sorry to bring this up again, but is this the same issue?

http://pastebin.com/kjZeEi4h

This is when attempting to view the recipe, or use of something when logged in on a server, but the server level.dat does not have any of the pneumaticcraft:lubricant entries in the defaultFluidList.

Is this a related issue, or something different entirely?

**Comment by ReikaKalseki** [comment]
No, this is entirely different, involving another mod registering a null item to the Ore Dictionary.

**Comment by ljfa-ag** [comment]
Any clue as to which mod that was?

**Comment by ReikaKalseki** [comment]
Well, it is a Fermenter input, so it is a plant material, likely a sapling. Which points to things like Forestry, Natura, BoP, and other mods with trees.

**Comment by TomeWyrm** [comment]
Betting it's Botany/Extra Trees. Binnies mods are scarily outdated at this point. AgriCraft, Natura, Biomes O' Plenty, Forestry, TwilightForest, and ProjectRed all have stuff that could go into a fermenter as well.

Actually I'm impressed that the modpack even boots. It's like they took a blast-from-the-past list (FZ, MMMPS, Binnies, etc.) and mixed it with "kitchen sink base" and threw in a splash of "let's find the unknown mods that are derivative of old favorites" (peripherals++, MineVinci (minepainter 2), HexCraft).
