### ISSUE TITLE
OpenComputers: networks become infinitely large

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#415]
Since every TileEntity that extends from TileEntityBase (which is pretty much every TileEntity) joins an OC network, networks can become very large with no means of separating them when using RC as your general means of power transfer and/or fluid transportation.

While this is somewhat convenient it also poses problems with bigger setups (my max component count was 200 something, which was basically my entire base). I know that the amount of components a CPU in OC can handle can be adjusted to basically infinity, but it is also sometimes undesired to have two networks physically connect - what is pretty hard when u power them with EC. Having an unlimited amount of components also trivializes network management altogether.

Maybe it would be possible that "dumb" transmission-only parts like pipes, shafts, wires and steam lines do not join a network. Another solution might be that TileEntities do not join a network implicitly, but only after being "assigned" to join by rightclicking it with some kind of tool.

**Comment by TomeWyrm** [comment]
This should probably be brought up with the OpenComputers dev(s). Can someone page them? I'm on my phone, and this UI is terrifyingly bad for anything except raw-text replies.

**Comment by ReikaKalseki** [comment]
This has been raised before. Every TileEntity has to specifically state one of three "visibility" levels - "Component" (ie a component in and of itself, as well as including network), "Network" (like a wire) or "None". Things like shafts and wires are already network visibility. If I were to make them "None", most setups would become impossible to cleanly use with OC.

I do not handle any of the network logic, so I cannot implement anything like "right-click with screwdriver to dis/connect from network" or "only connect to the network if redstone signal/gui toggle".
