### ISSUE TITLE
Fusion Reactor spawns some neutrons above the toroids.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#418]
At certain points in the fusion reactor "pseudo neutrons" spawn from the coolant pipes above the toroids. When these "pseudo neutrons" hit a neutron absorber it momentarily heats up but instantly cools down again (according to WAILA). They also seem to spawn y-aligned to the block border instead of the block center as normal neutrons do (aka half a block too high).

Pseudo Neutrons [(Video)](http://gfycat.com/WindingRealDevilfish):
![fusion_fake_neutrons](https://cloud.githubusercontent.com/assets/14168854/11328933/04f4a3ce-9194-11e5-9baa-1858ea49846d.jpg)

I originally thought this was related to the glitchy plasma balls jiggling up and down that i'm also experiencing. These are caused by having blocks at certain points above the toroid ring (i.e. having the coolant piping ring at the same height as in the picture.)

Jiggly Plasma [(Video)](http://gfycat.com/AmbitiousBadCrustacean):
![fusion_glitch_plasma](https://cloud.githubusercontent.com/assets/14168854/11328934/04f8f140-9194-11e5-9a5e-a9cf59d78c2d.jpg)

**Comment by ReikaKalseki** [comment]
This is known and unfixable, and related to client/server desync.
