### ISSUE TITLE
Crash while mining chromaticraft blocks with water flowing over

### ISSUE THREAD

**Issue by romanticjo** [ReikaKalseki/Reika_Mods_Issues#419]
crash logs:
https://gist.github.com/romanticjo/d9bd487a00cc6536490f
https://gist.github.com/romanticjo/ccf94d3a46e8b8624fe4

Reported in Revolution Pack
https://github.com/Haggle1996/RevolutionPack/issues/119

**Comment by ReikaKalseki** [comment]
This is the same error as #342, and the overall issue is known. However, you are the first to mention flowing water, and I can imagine potential ways in which that could be the culprit.

Can you reproduce this, ie A) does it always happen with the same arrangement and B) never happen without it?

**Comment by ReikaKalseki** [comment]
Someone else has also reported the flowing water connection. However, depending on how it works, it may well be a vanilla bug.

**Comment by ReikaKalseki** [comment]
[Is Glenn's Gases present](https://github.com/lawremi/PerFabricaAdAstra/issues/56)?

**Comment by romanticjo** [comment]
no.
