### ISSUE TITLE
RotaryCraft Gas Turbine heat overriding Friction Heater

### ISSUE THREAD

**Issue by WiduX** [ReikaKalseki/Reika_Mods_Issues#420]
RotaryCraft v9b, placing a friction heater behind a Gas Turbine (in the path of its heat), with the correct 8:1 gear ratio (8192 Nm and 8192 rad/s, should create 2058 °C, 2000 °C with cap). The Gas Turbine overrides this and keeps the Friction Heater at 1200 °C instead. Simply moving the friction heater to not be right behind the Gas Turbine fixes the issue.
Screenshots: http://imgur.com/a/PYUyA

**Comment by ReikaKalseki** [comment]
Blow 1200C air over a 2400C object. Does the object remain at 2400C? Temperature is not a "the highest wins" mechanic.

**Comment by WiduX** [comment]
OK, fair enough, that makes some sense. Sorry for wasting your time.

**Comment by seniordevlry** [comment]
You'r not wasting his time, he's just being obstinate. That's _exactly_ how temperature works.

**Comment by zemerick** [comment]
No, not quite defunker. The real world is far more complicated, but when considered simply: 1200C air over a 2400C object will provide a cooling effect. A perfect representation of thermal dynamics would be way beyond computers, and gameplay trumps real world where the 2 clash: so, setting the temp to 1200C to represent the cooling effect of large quantities of relatively cool air moving over a surface is an appropriate alternative. It penalizes the player for incorrect behavior, and is representative of a real world phenomenon.

**Comment by seniordevlry** [comment]
you're telling me that hot air can make something colder?

Dumbass.

**Comment by zemerick** [comment]
It's all relative. Compared to 2400C, that air is extremely cold...so yes, the air will cool it down, a lot. ( Technically the object makes the air hotter, but it loses its own energy in doing so...)

**Comment by ReikaKalseki** [comment]
@defunker

Generally speaking, when insulting someone, it is advisable to ensure that you do not embody the insult more than your target.
