### ISSUE TITLE
Bedrock pipe pressure integer overflow.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#422]
When a bedrock pipe reaches a pressure of "2.1 GPa" it overflows and continues to rise upwards (towards 0) from "-2.1 Pa" (unit shows wrong and is actually GPa for obvious reasons). Halving the pressure by attaching a second pipe reverses the overflow and it goes back to "1.1 GPa".

So once it reaches 0 again 4.2GPa worth of fluid are lost.

![2015-11-27_02 48 26](https://cloud.githubusercontent.com/assets/14168854/11432708/4f3ac332-94b4-11e5-9281-3ae07a98be8e.jpg)

**Comment by ReikaKalseki** [comment]
Fixed.
