### ISSUE TITLE
Shaft cross does not transfer power to directly connected machines in East/West direction.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#423]
If a machine (test sample: furnace heater, grinder, electric generator and gearboxes) is directly connected to the east or west side of a shaft cross it does not recieve power (even though the angular transducer says it does).

For all four sides:
Directly connected Dynamometer shows 0 torque 0 speed and power dependant on the angle you look at if from either as 0 or the correct value. Directly connected CVT's transfer power without lubricant but even with lubricant can not change torque/speed ratio.

(Oh, and also the shaft cross is not animated and has no handbook entry.)

Summary: Everything that's not a straight shaft works odd.

![2015-11-27_04 35 27](https://cloud.githubusercontent.com/assets/14168854/11433697/2c346fb6-94c1-11e5-89f4-30b4797049b0.jpg)

**Comment by ReikaKalseki** [comment]
If mousing over it changes things, that sounds like a desync. Is the power being functionally transmitted?

**Comment by lossycrypt** [comment]
Yes, the Dynamometer transfers power correctly it seems.
(Also testing in SP. Apparently that can desync too?)

**Comment by ReikaKalseki** [comment]
SP has an integrated server for the past three years.

**Comment by ReikaKalseki** [comment]
Fixed in all cases. It was part derp, part desync, and part error in the renderer.

**Comment by lossycrypt** [comment]
Looks like i won this weeks "most tags on an issue" award again :P
