### ISSUE TITLE
Compatibility issues with Carpenter's blocks/Plus random null pointer

### ISSUE THREAD

**Issue by MJRLegends** [ReikaKalseki/Reika_Mods_Issues#426]
See http://pastebin.com/44BQeFC8
Im not sure if this is your side or a  Carpenter's blocks problem.

Here is a mod list with versions
http://pastebin.com/B9eDS9Zt

**Comment by ReikaKalseki** [comment]
The NPE is the issue from #395. The Carpenter's blocks error is a separate issue and needs more information. Check your logs for reflective handler errors.

**Comment by MJRLegends** [comment]
Here is the log but i cant see any reflective handler errors[Uploading Log.txt…]()

**Comment by MJRLegends** [comment]
Here is the log but i cant see any reflective handler errors 
[Log.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/50369/Log.txt)

**Comment by ReikaKalseki** [comment]
Post it in a format that does not require I download random files.

**Comment by MJRLegends** [comment]
I can't pastebin just freezes if I try to copy and paste in there

**Comment by ReikaKalseki** [comment]
Then try something else.

**Comment by TomeWyrm** [comment]
Here's some options
http://cxg.de
http://fpaste.org
http://p.defau.lt
http://paste.debian.net
http://paste.ee
http://paste.kde.org
http://paste.ubuntu.com
http://paste2.org
http://pastebin.com
http://pastie.org
http://pb.daviey.com
http://slexy.org
http://sprunge.us

**Comment by ReikaKalseki** [comment]
As well as github gist.

**Comment by TomeWyrm** [comment]
Yeah, I just thought of that. Can't believe I added paste.ee and forgot http://gist.github.com

**Comment by MJRLegends** [comment]
Full log: http://paste2.org/nG025JnH

**Comment by TomeWyrm** [comment]
[13:06:24] [Client thread/ERROR] [FML]: CHROMATICRAFT ERROR: Could not add compatibility with Carpenter's blocks!

That would be the error involving Carpenters. The version of Carpenter's Blocks is the latest (3.3.7), which was uploaded to Curse on Sep 6, 2015. (3 months ago).

---

[13:08:18] [Client thread/ERROR] [FML]: DRAGONAPI ERROR: Some reflective mod handlers have failed.
[13:08:18] [Client thread/ERROR] [FML]: DRAGONAPI ERROR: Please try updating all involved mods, and if this fails to fix the issue, notify the author of the handlers.
[13:08:18] [Client thread/ERROR] [FML]: DRAGONAPI ERROR: 1 failure for Arsenal ('RedstoneArsenal'):
[13:08:18] [Client thread/ERROR] [FML]: DRAGONAPI ERROR: ClassNotFoundException "redstonearsenal.RedstoneArsenal" thrown from Reika.DragonAPI.Base.ModHandlerBase

That's the only instance of "reflective" in the whole log.

**Comment by ReikaKalseki** [comment]
It really does sound like the Carpenter handler is failing because of the [DisplayName issue](#395)....that makes no sense.

EDIT:
Oh, I see what is happening. Fixed.

**Comment by ReikaKalseki** [comment]
Did I forget to close it? :P

**Comment by MJRLegends** [comment]
Yeah, and i dont mean to keep going on but whens the release date for v10?

**Comment by TomeWyrm** [comment]
Don't ask for ETA's, please. For any programmer, artist, or really basically anyone. It'll be ready when it's ready and people get entitled when you give any answer to that question.
