### ISSUE TITLE
gregtech 6 integration?

### ISSUE THREAD

**Issue by jkenyonc** [ReikaKalseki/Reika_Mods_Issues#427]
Is it possible you could add GT6 integration? Specifically the friction heater could produce HU (heat) allowing you to heat up crucibles, and shaft power could function as or be converted to RU (rotation).

**Comment by ReikaKalseki** [comment]
The friction heater generates real temperatures, not "heat units". As for RU, I have never heard of them before; please elaborate.

**Comment by jkenyonc** [comment]
Heat units change the temperature of a crucible, on the crucible it says the ratio of heat input to degrees changed. You coild calculate how this rekates to watts of energy. RU are rotational units. They are normally produced by electric motors.They are used by several machines such as a lathe, centrifuge, and rolling machine. I don't know if you could let the shafts produce RU directly or add a converter block. All "units" contain the same amount of energy, though conversion may be lossy.

**Comment by ReikaKalseki** [comment]
How much energy is in an RU (or would I need to calculate it)? Also, does GT have an API for this?

**Comment by jkenyonc** [comment]
GT has an API for this. You could even add your own units if you wanted to, using the API. Let me ask on the forum thread about the energy.

**Comment by jkenyonc** [comment]
Heat units contain the same amount of energy as Rotational Units, which is the same amount as IC2  EU.

**Comment by willis936** [comment]
For typical conversion reference:
http://ftbwiki.org/Power_Converters

LV has an upper bound of 32 EU volt packets, typically sent 1 per tick.  I think this is supposed to be close to equivalent to real world volts and amps ie LV is 32 (volts/packet) \* 20 (packet/s) W.  One second of LV would be 640 joules.  RU are interchangeable with EU except in converting from one to the other there are the expected real world losses.

**Comment by ReikaKalseki** [comment]
Apparently not implementable.
