### ISSUE TITLE
ElectirCraft "Resistor" (and ReC Graphite) recipe does not allow oredicted coal dust.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#428]
Trying to craft an ElC resistor with either IC2 "coal dust" or Thermal Foundation "pulverized coal" does not work, only coal dust produced in the RoC grinder works. This is shown in NEI and i've manually tried both in a normal crafting grid and on the worktable.

Possibly related:
ReactorCraft Graphite can also only be smelted from grinder coal dust with vanilla smelting. (The TE "Redstone Furnace" can still do it with oredicted coal dust.)

(As far as i can see in NEI those are the only two recipes affected in my mod pack.)

**Comment by ReikaKalseki** [comment]
The second is intentional.

**Comment by ReikaKalseki** [comment]
Fixed. Also, graphite is now a Friction heater recipe @ 400C.
