### ISSUE TITLE
Crash interacting with casting table, results in player inventory loss, must restore from backup.

### ISSUE THREAD

**Issue by romanticjo** [ReikaKalseki/Reika_Mods_Issues#433]
https://gist.github.com/romanticjo/e9a93934b4e885850ded.

Last action was bringing up the casting table gui in a crystal group crafting session.  Prior to that, I used my lucky pickaxe to break a few crystals for shards.

This is reproducible, it's the third time it occurred for me.

**Comment by ReikaKalseki** [comment]
That is all vanilla code. Try removing other mods.

**Comment by lossycrypt** [comment]
You say it's reproducible but do not provide instructions on how to reproduce.
I have crafted crystal groups by the stack and never had any issues.

**Comment by romanticjo** [comment]
Haggle (pack maintainer) suggested to run the pack under java7, as this has been seen by other pack players and that seemed to help.

Under java7, no repro, I was able to progress in CC again without any crashes.

**Comment by ReikaKalseki** [comment]
OK, so there is a new Java 8 issue. Lovely.

**Comment by NachtRaben** [comment]
romantic wasn't the only player to have this issue while running java8, but due to other mods requirements in the revolution pack downgrading to 7 isn't a graceful solution. We have had multiple users experience the same issue.

**Comment by TomeWyrm** [comment]
Unfortunately, Java 8 causes some strange issues that are about as easy to diagnose as scaling a smooth glass wall with greased hands.

**Comment by ReikaKalseki** [comment]
I have never seen this, nor has anyone else ever reported it.
