### ISSUE TITLE
Suggestion: need more limiter for shaftpower-> EU/RF conversion in rotarycraft to make it more reasonable to use reactorcraft turbine generator for large outputs

### ISSUE THREAD

**Issue by wormzjl** [ReikaKalseki/Reika_Mods_Issues#435]
It seems to me that currently The EU generator is capable converting infinite amount of shaft power to EU, at the cost of only 20mb of coolant per second regardless of the output.
I'd suggest to nerf it a bit so it's better to invest a huge amount of resources for the turbine generator in the late game, instead of using that single-block converter all the way long.
What is possible:
- add tiered upgrade system to these converters, like the EU/RF to shaft power converters
- make coolant consumption proportional to the out put 
- simply add a up limit for each converter

**Comment by ReikaKalseki** [comment]
I like #2 the best. But that coolant requirement is configurable.

**Comment by ReikaKalseki** [comment]
Done.

**Comment by TomeWyrm** [comment]
Which method did you go with?

**Comment by ReikaKalseki** [comment]
None of the above, but an implementation of torque losses, as well as an overheat mechanic.

**Comment by TomeWyrm** [comment]
Don't all the converters now require the tiered upgrades as well?

**Comment by ReikaKalseki** [comment]
Not the from-RC ones.
