### ISSUE TITLE
Too many mobs(Chromati Craft)

### ISSUE THREAD

**Issue by kabachuha** [ReikaKalseki/Reika_Mods_Issues#436]
Hello, Reika!

Your mod "Chromati Craft" is spawning TOO many mobs and animals (about 9927 in 15 minutes) in "Chromati Craft" 's bioms(if chunks loaded) that causes a lot of lags. 

Can you fix this, please?

**Comment by ReikaKalseki** [comment]
Config.

**Comment by waldahud** [comment]
Or you could fix the bug. :D

**Comment by ghost** [comment]
It isn't a bug, just use the config to make it the way you want to suit your play style.

**Comment by waldahud** [comment]
making the user laggy is a bug.

**Comment by ReikaKalseki** [comment]
The only bug here is in your comprehension and/or reasoning abilities.

**Comment by TomeWyrm** [comment]
No, setting a number higher than your system can handle is USER ERROR. This value is configurable, configure it.

**Comment by kabachuha** [comment]
Thanks a lot!
