### ISSUE TITLE
[ReactorCraft] HazMat Suit Bug

### ISSUE THREAD

**Issue by darqen27** [ReikaKalseki/Reika_Mods_Issues#437]
The ReactorCraft HazMat Suit doesn't prevent radiation poisoning from its own mod

NON-Meltdown level radiation around your own reactors

**Comment by darqen27** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/432

**Comment by TomeWyrm** [comment]
Do not create duplicate issues in an attempt to draw attention to your issue.
