### ISSUE TITLE
ElC Resistor Handbook page lists "5" as green instead of lime.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#439]
Handbook says "green". But in-world it only works with lime dye and renders lime.

**Comment by ReikaKalseki** [comment]
Real-life resistor bands make no such distinction, and the color on most resistors has been - in my experience - closer to MC lime than green.

**Comment by TomeWyrm** [comment]
That might not be a bug, but it IS kinda confusing. If you're colorblind, and the handbook says "Green", are you going to use lime? I'm betting no.

**Comment by ReikaKalseki** [comment]
If you are colorblind, good luck using resistors....

**Comment by TomeWyrm** [comment]
Waila reports the colors, doesn't it?

**Comment by lossycrypt** [comment]
The bug is that you have to use a lime item to color the band but the handbook tells you to use a dyeGreen item. How is that not an error in the handbook? If you don't want to change the handbook text then make dyeGreen items work?

**Comment by ReikaKalseki** [comment]
The handbook explicitly mentions dyeGreen?

**Comment by Barhandar** [comment]
The handbook says "Green = 5", not "Lime = 5".

**Comment by ReikaKalseki** [comment]
Since this issue was opened, I might have made either work; I do not remember. At any rate, real-world resistor green is closer to lime than it is to MC green, which is why I left it as-is before.
