### ISSUE TITLE
Isotope Centrifuge sometimes produces thorium dust from uranium hexafluoride?

### ISSUE THREAD

**Issue by umbralOptimatum** [ReikaKalseki/Reika_Mods_Issues#44]
I'm assuming this isn't an error since I don't know of any other ways to get thorium, but sometimes my Isotope Centrifuge is producing thorium dust instead of enriched uranium dust. If there's already some of one type in the output slot, all additional output is of the same type, but if empty there seems to be about a third chance that it produces thorium dust instead of enriched uranium.

**Comment by zemerick** [comment]
I don't see anything wrong really:
```
	private void make() {
		tank.drain(UF6_PER_DUST, true);
		if (ReikaRandomHelper.doWithChance(FUEL_CHANCE)) {
			ReikaInventoryHelper.addOrSetStack(ReactorStacks.fueldust.copy(), inv, 0);
		}
		else {
			ReikaInventoryHelper.addOrSetStack(ReactorStacks.depdust.copy(), inv, 1);
			if (ReikaRandomHelper.doWithChance(20)) {
				ReikaInventoryHelper.addOrSetStack(ReactorStacks.thordust.copy(), inv, 0);
			}
		}
```

Should be 20% chance, if it fails to make Enriched Uranium, to make Thorium.

**Comment by 1Matthias** [comment]
It is actually an intended feature.

**Comment by zemerick** [comment]
Which part, the getting Thorium, it being blocked by DU dust or both?

**Comment by 1Matthias** [comment]
Both.

**Comment by zemerick** [comment]
Good to know, thanks.

**Comment by ReikaKalseki** [comment]
This is worth investigating.

**Comment by ReikaKalseki** [comment]
OK, I am going to totally redesign the thorium reactors, fuel, and processing.
