### ISSUE TITLE
ElC Band dyeing always consumes dye item even if invalid.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#440]
Trying to dye a resistor band always consumes the dye item, regardless of if the band is already that color or if the color is valid at all.
Invalid dye colors consumed are: Light Gray, Green, LightBlue, Cyan, Pink, Magenta.

**Comment by ReikaKalseki** [comment]
I can easily fix that by making the dyeing method return a boolean.

**Comment by ReikaKalseki** [comment]
Done.
