### ISSUE TITLE
ElC Resistor output current is multiplied by number of input generators.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#441]
The current flowing through a resistor is $band_color_code multiplied by the number of input generators and not always the same as it should be.

Here's  bunch of T0 magnetostatics:
![2015-12-02_22 44 48](https://cloud.githubusercontent.com/assets/14168854/11566344/407135ec-99e2-11e5-80b4-c73cbf885186.jpg)

**Comment by ReikaKalseki** [comment]
See the other, similar issue.
