### ISSUE TITLE
Multi-Operation machine GUIs progress renders multiple times.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#442]
A machine operating at more than 1 operation per tick has its progress bar rendered multiple times. The number of multiple GUIs seems unrelated to the number of ops/tick though.

Refrigeration Unit at 2ops/tick:
![2015-12-03_17 09 41](https://cloud.githubusercontent.com/assets/14168854/11566416/96d6025a-99e2-11e5-8196-adf0302ea4f6.jpg)
Fluid Crystallizer at 4ops/tick:
![2015-12-03_17 09 55](https://cloud.githubusercontent.com/assets/14168854/11566415/96d3c4c2-99e2-11e5-8c04-1f1b33b7e62a.jpg)

**Comment by ReikaKalseki** [comment]
Fixed.
