### ISSUE TITLE
ElC resistor odd current distribution.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#443]
This is a bit difficult to explain so bear with me:
As far as i can tell on a network with several power sinks and one source only one sink can use more than (source current / number of sinks) ampere. If a second sink tries to use more than that then the maximum current one sink can recieve drops to ((source current / 2) - x) ampere. Where x is a number dependant on the total output of all sinks that have an output < (source current / number of sinks). I'm not sure what the exact number is, but it doesn't seem to be a simple sum or division.

I assume this can only happen on networks with more than two sinks where _every_ sink has a resistor and some sinks use very low current.

Example picture:
Same setup twice with an Auroral Battery input each.
Left side is fine.
Right side "motor 4" uses more than 4096/4 thus "motor 3" drops to 2048/2-x
![distribution](https://cloud.githubusercontent.com/assets/14168854/11568366/e3a38cfc-99eb-11e5-9f11-59a86dace038.jpg)

Another example with 1000A input:
![2015-12-03_18 18 00](https://cloud.githubusercontent.com/assets/14168854/11568365/e3949cce-99eb-11e5-9d81-30959bea8b20.jpg)

**Comment by ReikaKalseki** [comment]
Resistors apply their limit "per path", meaning that three paths through a 100A resistor lead to 300A of current. Despite repeated attempts, this is not fixable.

As for the last case, if you put in more current than the total allowed by the resistors, they will be overloaded since the power has nowhere else to go.

**Comment by lossycrypt** [comment]
> Resistors apply their limit "per path", meaning that three paths through a 100A resistor lead to 300A of current. Despite repeated attempts, this is not fixable.

That seems to be the answer to [this issue](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/441). I do not see how that applied here as there is only one power source.

> As for the last case, if you put in more current than the total allowed by the resistors, they will be overloaded since the power has nowhere else to go.

And how would such "overloading" manifest? I have noticed no such thing. Also i do not see how that would even apply here.

I'll give you two actual examples with numbers:

Example 1:
Input current = 8000A with four paths.
P1 = Unlimited
P2 = 1900A
P3 = 500A
P4 = 500A
Total Transfer: 8000A
-> This works as expected because 8000 divided by four paths is 2000A and only one path is allowed for that high current.

Example 2:
Input current stays the same but P2 is modified to allow 2000A.
P1 = Unlimited
P2 = 2000A
P3 = 500A
P4 = 500A
Total Transfer: 6500A (<-PROBLEM!)
-> When a second path (P2) allows more than 8000/4 a large amount of current is NOT TRANSFERRED AT ALL.

Here's a picture of the examples (_please_ look at it):
![1500a_lost_commented](https://cloud.githubusercontent.com/assets/14168854/11589384/5c4b2826-9a88-11e5-8be2-538fed15787a.png)

**Comment by ReikaKalseki** [comment]
As per the teamspeak discussion.

**Comment by lossycrypt** [comment]
Meh. Also as per teamspeak.
