### ISSUE TITLE
Chromaticraft Casting Delegate failing to complete tasks (fails halfway through)

### ISSUE THREAD

**Issue by metnavman** [ReikaKalseki/Reika_Mods_Issues#444]
I don't have any crash logs, since it's not causing a crash. The Delegate simply ceases functioning at a random time. It will complete multiple crafts of single or multiple items, and then just randomly decide to stop what it's doing and fail. The required items for the cast are all in the ME system it's polling, there is sufficient power in the network to complete the craft, and it's not throwing errors. It simply stops.

Upon manually completing the recipe that was queued, no further interactions with the Delegate work. Attempting different recipe selections works in the GUI, but any selection made will not craft. Breaking and re-placing the Delegate (to include destroying and placing a brand new block via Creative) do not solve the issue. Closing the game down completely, and having it restart from scratch does not solve the issue. The only thing I've found that gets it working again is reloading a backup to before the shutdown occurs, and then it's simply a matter of time/crafts before it happens again. 

Right now I'm looking for advice on what files or logs I need to look into submitting so this can be dug into deeper, and what other specifications you'd like to know to further narrow down the troubleshooting.

Modpack - Revolution
Java version - 8 update 66
Chromaticraft V9b

I can't find anything else in-game that this is affecting. No GUI issues, no button issues. Everything else functions, except for the device actually completing a task.

Edit: To add - it is attached to the ME network by a Covered Fluix cable. No bus, just cable directly to delegate. It hasn't had issue pulling from the ME network with this setup.

**Comment by metnavman** [comment]
Update:

Used the java parameter detailed in another report here to successfully enter the Dimension and am slowly progressing through that. Haven't had any crashes there (aside from nasty ctd chest items), so all is well on that front. Casting Delegate has still not been sorted out, and I'm too far along now to revert to a backup. 

What bus is "normally" used to attach a Delegate to the ME network for pulling items? I'll give that a shot before I write this off to a random quirk and just ignore the Delegate until V10 / something pops up.

**Comment by ReikaKalseki** [comment]
I personally use EiO ME conduits, but anything AE should work.

**Comment by metnavman** [comment]
If that's the case, does that mean that the Delegate should NOT be talking to the AE network like it was? That may be where this bug is coming from. Like I said, it was pulling and crafting from the network with nothing connected but a cable. Connecting an ME smart cable directly to it showed the "1 of 8" channel being used, like the Delegate was connected and working. No bus.

**Comment by ReikaKalseki** [comment]
It does not need a bus. It, like RC's autocrafter, connects directly as any native AE tile.

**Comment by lossycrypt** [comment]
I have rarely (2-3 times if memory serves right) had the "delegate forgets its task in the middle of a task" issue as i've told you one ts @reika. And i thought i remember you said you had it too. Just that (with java7 here) it doesn't completely block ever after. From the few cases i have experienced it seems to happen if you order a large amount of items at once (i.e. several hundret runes).
@metnavman: just because you haven't mentioned it explicitly i'm gonna ask if you tried breaking the actual table/temple structure/network connection? (And i guess you can't try if it works again with java7?)

**Comment by ReikaKalseki** [comment]
I still occasionally have this, but it is so random that I can never track it down.

**Comment by ReikaKalseki** [comment]
This seems to have gone away; I have not seen it in over a month now. Has anyone else?

**Comment by metnavman** [comment]
I feel proud having the oldest open issue on this page, haha!

That said, I've finally gotten the delegate set back up, and it appears to be working like a charm. I'll keep my eye out as I use it for various things, but it is rapid-fire crafting multiple stages of items without a hitch. Seems fixed to me!
