### ISSUE TITLE
Redflux Radiator to Magnetostatic Engine problem

### ISSUE THREAD

**Issue by notchriss** [ReikaKalseki/Reika_Mods_Issues#447]
Powering a magnetostatic engine from Chromaticraft's Redflux Radiator won't work unless you attach a cable or conduit (any) to the back of an engine. 

I.e. I use Ender IO's fluid conduits. If I pump liquid nitrogen in from the back problem solves itself, however if I do it from the side, I still need to attach a single conduit (may even be not connected to anything else), or Radiator won't send RF to the engine. 

http://postimg.org/image/inkrydj2f/

ChromatiCraft 1.7.10 V9b, RotaryCraft 1.7.10 V9b, DragonAPI 1.7.10 V9b, MC 1.7.10

**Comment by ReikaKalseki** [comment]
This is a side-effect of old code in them that was designed to defeat the "RF/MJ" unification and ensure only the appropriate engine was used with the appropriate power system. I suppose it is long since defunct....

**Comment by ReikaKalseki** [comment]
Done.
