### ISSUE TITLE
SMP Reactors explode when server runs behind

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#448]
This is the same issue identified in kingrunes/Somnia#29.

When an SMP server lags, Neutrons will ignore shielding, and in some cases, overheat the reactor blocks.  The issue with Somnia simply seems to exacerbate the issue, as it speeds up the game processing multiple times while all players on the server are asleep.

I don't know if anything _can_ be done to fix this (minecraft will "skip ticks" when running behind), but I figured I'd report it at least.

**Comment by ReikaKalseki** [comment]
Just accelerating the tick rate would change literally nothing; if he is accelerating the tick rate, then though neutrons are emitted more rapidly, and heat is generated accordingly, the temperature distribution and cooldown mechanics _also_ run at the same increased rate. Overall, there would be no net change.

Minecraft "skipping ticks" is only for the world time. It could not possibly "extrapolate" to determine what events "should" have happened in the skipped time, and consequently does not.

The only error could come in if TileEntities and Entities start updating at different rates, and even then the issue would not be a simple "more heat to the point of overload" behavior.

**Comment by ghost** [comment]
Fair enough, I'll see what else can be causing this then.

**Comment by ghost** [comment]
I think we found it.  We had assumed that "chunkloaded cores" meant we no longer needed to use a chunkloader on the whole reactor.  Apparently, this is not the case, and it came back to bite us... with radioactive doom.  We'll have to keep an eye on things to make sure that's the problem.

**Comment by ReikaKalseki** [comment]
See the thread; I just fixed the bug related to that. However, that has nothing to do with the server running behind, with sleep, or with Somnia, so this issue will remain marked "Spurious".

**Comment by ghost** [comment]
I understand.  I was hypothesizing based on observations and my (admittedly far from complete) knowledge of how Minecraft works.
