### ISSUE TITLE
crash when pressing U in NEI

### ISSUE THREAD

**Issue by shadoxxhd** [ReikaKalseki/Reika_Mods_Issues#449]
http://pastebin.com/QUfJGaf4

**Comment by ljfa-ag** [comment]
This has already been reported here: #414 
Looks like some mod is adding a null oredict entry

**Comment by shadoxxhd** [comment]
how can i track down which mod/item causes this, and subsequently fix it?
edit: would it be possible to write a minimod which fixed such issues ('mccleaner')?

**Comment by ReikaKalseki** [comment]
To find it? The most efficient is a binary split search.

To fix it? Tell the appropriate developer and hope that they A) did not retire 12 months ago and B) do not say "log has Reika's code, therefore Reika's bug. Goodbye."

**Comment by TomeWyrm** [comment]
If you don't understand what a Binary Split Search is

Step 1: Take out half the mods (be careful not to take out any dependencies; don't remove Dragon API or Forestry, and don't remove RotaryCraft if you're keeping ReactorCraft, etc.), 

Step 1 Results: If the error can be reproduced then the mod causing the error is in the remaining mods, if the error disappears it was one of the mods you removed.

Step 2: If the error stayed, repeat the first step with your halved mod list (still be careful to keep dependencies of mods you aren't removing). If the error was gone, remove all the mods you kept (except for DragonAPI, and Forestry; also once again don't forget dependencies... like if you're keeping Immersive Integration then don't remove Immersive Engineering) and see if the error returns.

Step 3: Continue removing half the remaining mods, either switching which half you're working with or pruning the current set by half until you figure out which mod(s) are required at minimum to make the bug happen. Then (in this case) submit a bug report to the author of the mod that isn't Forestry or DragonAPI. Odds are REALLY high it's just one author.
If adding the mods back didn't recreate the error... you will almost certainly need experienced help.

**Comment by shadoxxhd** [comment]
i knew that, but thanks for taking the time to explain it :D
since my friends did not have this issue, i chose to reinstall the modpack which somehow helped. the strange thing is, the only mod difference was optifine, which should not add any oredict entries.

**Comment by ReikaKalseki** [comment]
Correct, Optifine does not affect the OreDict. There must have been another mod difference, or a version change (or loading order change).

**Comment by shadoxxhd** [comment]
i sent the mods folder to a friend, and he sent it back unmodified...
idk what could have changed there

**Comment by TomeWyrm** [comment]
Eh, now I can refer back to this if I ever need to explain a binary split search for erroring mods :-)

Aren't unexplained bugs that suddenly fix themselves just awesome?

**Comment by ReikaKalseki** [comment]
No, because then the cause is never discovered.

**Comment by TomeWyrm** [comment]
Right. I really need to use /s more often, or be an extra nerd and use angled-bracket-enclosed-tags.

**Comment by ReikaKalseki** [comment]
It is more just with me. :P
