### ISSUE TITLE
Crash when searching in nei

### ISSUE THREAD

**Issue by MJRLegends** [ReikaKalseki/Reika_Mods_Issues#450]
A person that plays my mod pack has reported to me that he typed "planter" in nei and when he clicked on the planter from MFR to see the recipe. He got this crash
http://pastebin.com/0u99iqi1

**Comment by MJRLegends** [comment]
What's the fix for this?

**Comment by WalaoEgg0424** [comment]
Yeah , what's the fix for the crash?

**Comment by ljfa-ag** [comment]
See #337...supposedly caused by Pneumaticcraft, should be fixed in the upcoming version

**Comment by WalaoEgg0424** [comment]
Thx :D

**Comment by robaimes** [comment]
There's no 'fix' as such. Can happen with many mods, I guess.

I got rid of the issue by reverting **Compact Machines** back to version **1.20**
Only just done this so it may go wrong in the future.
