### ISSUE TITLE
If anyone else is having this issue Food particle issue with Chromaticraft 

### ISSUE THREAD

**Issue by Regner6** [ReikaKalseki/Reika_Mods_Issues#452]
Request from MJRLegends,  
Since The past few updates of Space astronomy i noticed the food particle issue.
The first 4 pictures shown will be from Space astronomy.
![53868fb4-9d8f-11e5-9be9-1dcd11886638](https://cloud.githubusercontent.com/assets/16054126/11671628/a91a2740-9dd7-11e5-9ba9-65579d82835c.gif)
![5387b178-9d8f-11e5-8b64-03032ef07397](https://cloud.githubusercontent.com/assets/16054126/11671629/a91c6c76-9dd7-11e5-8299-844e3734c5d0.gif)
![5371b5ee-9d8f-11e5-8e30-36cae107cce2](https://cloud.githubusercontent.com/assets/16054126/11671630/a91d9736-9dd7-11e5-8a0c-8dfb52173f62.gif)
![537e3eae-9d8f-11e5-85e2-701e1af61c96](https://cloud.githubusercontent.com/assets/16054126/11671627/a91a30d2-9dd7-11e5-94da-0e4b12f5cf42.gif)

The next few pictures was testing out on the Modpack Divergence from the Atlauncher. MJR Legends asked me to try Chromaticraft on another pack and Divergence is the only other pack i could think of...Here's the pictures from Divergence. 
![1a4f795f560b0b1970187aa38ebfb1d2](https://cloud.githubusercontent.com/assets/16054126/11671644/cf8d474a-9dd7-11e5-8497-5d4c87747bfd.gif)
![e0bd438029a247373a0e4f9c6aaeb65a](https://cloud.githubusercontent.com/assets/16054126/11671645/cf8fcd94-9dd7-11e5-8126-d2eccf412382.gif)
![e1dc3d3b85b7a7ecfc60e4982be85751](https://cloud.githubusercontent.com/assets/16054126/11671646/cf9208a2-9dd7-11e5-92e0-800d8eb40dcb.gif)

**Comment by ReikaKalseki** [comment]
I have seen this as well, since at least 1.6.4. Are you sure it is on my end?

**Comment by Regner6** [comment]
I'm not sure if Fastcraft was out then but yesterday when i removed Fastcraft and put in optifine it fixed it in the space astronomy pack. Didn't test it for Divergence but i think it's a conflict between Fastcraft and Chromaticraft

**Comment by ReikaKalseki** [comment]
There is a known issue between the two, but it involves mipmapping, a 1x1 texture, and an error on his end. This seems unrelated.

Also, I remember seeing this in 1.6 as well, long before FastCraft existed.

**Comment by artubi** [comment]
I doubt that I'm going to be helpful here since I don't use any of Reikas mods or play Space Astronomy pack but I just wanted to let you know that I have similar issue as you. Not with food thought.
When breaking Mekanism Obsidian TNT the particles shows Chisel fan.
![Imgur](http://i.imgur.com/o3SpGax.png)
Using Fastcraft 1.21 and mipmaps manually set to 1.
Food for me show correct particles, however I don't know whether other blocks do this since I just found this one.

**Comment by Regner6** [comment]
#Fastcraft sucks

**Comment by ljfa-ag** [comment]
I'm getting this even without Fastcraft (but with CoFH tweaks). I'd need to test it further though.
