### ISSUE TITLE
Reactorcraft "The Nuclear Age" Achievement

### ISSUE THREAD

**Issue by eqdanteon** [ReikaKalseki/Reika_Mods_Issues#453]
I am unable to get the Reactorcraft achievement "The Nuclear Age" to flag as complete.  The in game tool tip for the achievement suggests that mining pitchblende would be enough to trigger the achievement.  Based on this I tried mining both versions of the ore without successfully triggering the achievement.  I then reviewed the code for the achievement that you have posted and it stated that I needed to receive the product of pitchblende. Based on this I then processed the ore in the Rotarycraft grinder and smelted the flakes in a vanilla furnace. I have also smelted both versions of the ore itself and neither process appears to flag the achievement.  I am running version v9b of all related mods.  Any assistance would be greatly appreciated.

**Comment by WiduX** [comment]
Yeah, I'm getting this too. I've mentioned this on the forum a couple of times, but never got any responses. Hope this gets fixed, as this prevents you from getting any ReactorCraft achievements.

**Comment by ReikaKalseki** [comment]
It was an order of operations issue, not a drops one.
