### ISSUE TITLE
[Suggestion] Casting Complex Lumen Funnel

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#454]
I've been playing around with Chromaticraft and I was seeing if I could get all of the 16 repeaters of the multiblock to funnel in the lumens to the casting table. However, the eight corners ones do not work due to a column obstruction them. So I was thinking of some type of way to possibly do this. 

Perhaps you could make it so that it'll check for the multiblock structure it's part of and no clip through the column or make it use one of the sides that the inner repeaters would use. 

It's just an aesthetic feature but it'd be nice to have the lumen beams being concentrated into it.

**Comment by ghost** [comment]
In case it's hard to grasp on what I'm saying, the outer repeaters are the two on each corners and the inner are the two in between one corner and another.

I also did a picture on what I'm talking about
http://i.imgur.com/oNU6c9E.png

Sorry for really bad lines.

**Comment by lossycrypt** [comment]
The ring around the table (4 adjacent blocks, 4 corner blocks) have to be air.

**Comment by ReikaKalseki** [comment]
All sixteen repeaters can see the table; it would be stupid if they could not, as those are required for the structure to complete.
