### ISSUE TITLE
DragonAPI causes XU Unstable Ingots to be partially uncraftable

### ISSUE THREAD

**Issue by Keridos** [ReikaKalseki/Reika_Mods_Issues#456]
When having DragonAPI in my modpack with some of your mods, I cannot craft stable ingots with the stable division sigil from XU anymore. Reported this at RWTemas Repository also: https://github.com/rwtema/extrautilities/issues/782

Using Forge 10.13.4.1558, DragonAPI v9b. XU 1.2.12.

The recipe uses NBT data. Do you do something with the recipe list with dragonapi? 

/edit: checking if blacklisting ingotUnstable in the oredictionary helps.

**Comment by TomeWyrm** [comment]
See #323
