### ISSUE TITLE
RotaryCraft tesselation crash

### ISSUE THREAD

**Issue by nathantfaust** [ReikaKalseki/Reika_Mods_Issues#457]
Crash Log: http://pastebin.com/9JqGKxP1

I have crashed after placing one liquid pipe connecting a pump to a fermenter. When I reconnect I crash. I have OptiFine installed which might have caused the issue. If you need to to give more info or recreate problems please let me know because I would love to help fix your mods as they are extremely detailed and high quality in my opinion.

**Comment by ReikaKalseki** [comment]
Something else is messing with the ISBRH rendering process, and Optifine is almost certainly to blame. Things like Liteloader mods are other potential causes. If it were systemic on my end, all pipes would crash at all times.

**Comment by Builderb0y** [comment]
Optifine-related "already tessellating" errors can usually be fixed by setting the chunk loading mode to default.

**Comment by nathantfaust** [comment]
I knew to have multi-core off but I did have smooth on which was most-likely causing the issue. It seems to be working now. Thanks for the help!
