### ISSUE TITLE
Casting table only progresses the player who placed it

### ISSUE THREAD

**Issue by Builderb0y** [ReikaKalseki/Reika_Mods_Issues#458]
The casting table, upon completion of recipes that are required for progression (repeaters, elemental cores, energy storage crystals, etc…), will only give that progress to the player who placed the table, instead of the player who started the recipe. This makes it very useless for shared bases in multiplayer, as it requires that each player have their own table; which is problematic as well, not just due to having to make space for all the tables, but also because it means that the chroma.share item (which still needs localization, by the way) is fairly useless as well. After all, what's the point of crafting items you don't need if you're not going to get progression for them?

Suggested fix: Add an NBT tag to the table that stores the last player who activated it with an elemental manipulator, and call activeRecipe.onCrafted() for _that_ player instead of this.getPlacer() (line [579](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/TileEntity/Recipe/TileEntityCastingTable.java#L579)).

Alternate solution: Give progress to all players who A: own the table, and B: are within range (8 blocks should be good, same size as the complex itself). This would also be very useful for the progression stages unlocked by actually building the multiblock (room/temple/complex), as it means that each player does not have to break/replace the same table, then give it to the next player to do the same, and then distribute chroma.shares to everyone again.

**Comment by ReikaKalseki** [comment]
Changed to only the one who triggered the crafting; that variable - 'craftingPlayer' already existed and was in use, making this the natural choice.

Also changed on the Pylon Energy Focus.
