### ISSUE TITLE
Shaft Power Buses stop working on world reload

### ISSUE THREAD

**Issue by umbralOptimatum** [ReikaKalseki/Reika_Mods_Issues#46]
I have a chain of shaft power buses distributing power to some of my machines, but I find myself often having to break and replace them after loading the save for them to start working again. As far as I can tell, they all stop working and I have to replace them in the order they are in from the controller.

**Comment by zemerick** [comment]
Could you provide more details to replicate this? For a simple setup I don't see this happening.

Is it a server that is restarting, or just single player and you're quitting? Do you have to quit to desktop, or just save and quit back to the world screen, and load the world again?

Can you give specifics of your setup? How many buses, shafts or gears, which faces/directions. Screenshots would help a lot here.

**Comment by umbralOptimatum** [comment]
I'm on SSP and it seems to happen about half the time when I reload the world (as far as I can tell restarting the client doesn't make a difference). I have one controller with six buses attached in a straight line, all outputting to what I believe is the east (whichever side's slot is green). Most of the buses use bedrock gears with one using a bedrock shaft. Which buses stop working is inconsistent; sometimes I have to replace all of them and sometimes only ones past a certain point in the line. The controller is consistently filled with lubricant and I've never had to replace it.

**Comment by zemerick** [comment]
Are they all in the same chunk?

What is your power source? Is it something with a variable power, or consistent power?

Is the power source in the same chunk, or different chunk?

**Comment by ReikaKalseki** [comment]
I cannot reproduce this, and multi-chunk structures are unaffected and working normally. Also, the code seems to contain no errors.

![](http://i.imgur.com/6f0qXRC.png)
