### ISSUE TITLE
Breaking Evolved Skeleton Spawner with a Bedrock Pickaxe crashes server

### ISSUE THREAD

**Issue by notchriss** [ReikaKalseki/Reika_Mods_Issues#461]
Server just stops responding to console commands or anything else. Does not even leave a crash report txt dump file. We tested it a few times to make sure it's indeed this action that stops the server

Evolved Skeleton Spawner on the Moon is from Galacticraft mod, I am not sure if it's their problem or Rotarycraft's, but I'd appreciate if you could look into it when you have spare time.

Note that Bedrock Pickaxe worked fine with Evolved Creeper spawner from the same mod, if that change's anything.

RotaryCraft 1.7.10 V9b
Galacticraft 1.7-3.0.12.375

**Comment by ReikaKalseki** [comment]
Is the spawner a vanilla spawner (Block ID 52)? Is the "spawn mobs when harvesting spawners" option on, and does it fix the issue if not?

**Comment by notchriss** [comment]
Spawn mobs option was on, and DragonApi debug mode was on too. I'll be able to test it with off tomorrow or hopefully tonight.

**Comment by ReikaKalseki** [comment]
"Tomorrow" having come and gone three months ago...

**Comment by notchriss** [comment]
Oops I'm terribly sorry, it completely slipped out of my mind. But it hasn't happened since, so either one of the updates to RC or Galacticraft has fixed it, or none of my players were destroying GC spawners since then. I guess lets just close it, if it happens again I'll post with the info you asked for. Sorry again :)
