### ISSUE TITLE
Gearboxes don't take damage if drawing power from Shaft Junctions

### ISSUE THREAD

**Issue by nanzington** [ReikaKalseki/Reika_Mods_Issues#463]
When drawing directly from a shaft junction for power gearboxes take no damage, which makes it easy to get a grinder going immediately without needing to spend extra stone repairing the gearbox as it takes damage. Can be reproduced by placing a shaft junction down in split mode (not sure if it happens in merge?), running power to it, and sending power directly from a shaft junction output into a gearbox. From what I've seen, no damage is put onto the gearbox when done this way and it continues to operate at 100% functionality despite having no lubricant.

**Comment by ReikaKalseki** [comment]
Fixed.
