### ISSUE TITLE
Chromaticraft 9b XP to liquid chroma incorrect?

### ISSUE THREAD

**Issue by 1skandar** [ReikaKalseki/Reika_Mods_Issues#465]
It is supposed to be 1 XP = 1 mb of liquid chroma, yes? If so, something has gone wrong I think.

I was at level 27 and drained my XP into the chroma collector. Now, according to this: http://minecraft.gamepedia.com/Experience I should have ended up with roughly 1 bucket of liquid chroma and I did not. Instead it looks like I ended up with roughly 600 mb in total.

**Comment by ghost** [comment]
You looked at the wrong XP chart, the one you were looking at was values of Beta 1.8 - before 1.3.1 which was 1.2.5 and below. The correct one is values of 1.3.1 - before 1.8 as 1.3.1+ was changed for reasons I don't know.

27 levels to chroma would be:
beta 1.8 = 1411
1.3.1/1.7.10 = 657

So the rough 600 should be around 657.

**Comment by 1skandar** [comment]
Thanks.

**Comment by ReikaKalseki** [comment]
Also, 1mB of Chroma is very much more than 1XP.

**Comment by 1skandar** [comment]
Wait, what? Um, then the lexicon is incorrect because:

http://i.imgur.com/koub4zw.png

is where I got that information.

**Comment by ReikaKalseki** [comment]
My memory was incorrect; it used to be 5 XP/mB.
