### ISSUE TITLE
Chromaticraft 9b Lumen Lamp issue

### ISSUE THREAD

**Issue by 1skandar** [ReikaKalseki/Reika_Mods_Issues#467]
I think Lumen Lamps are preventing mob spawns even when toggled off. Built a Cursed Earth mob farm and was trying to use Lumen Lamps so I could turn off spawning on demand. Noticed even when the lamps were off nothing was spawning.

**Comment by ReikaKalseki** [comment]
They have no special spawn protection code, just a light level. Are there any other indicators of a glitched light level (eg crops not dying in dark underground)?

**Comment by 1skandar** [comment]
I can check that. But it is certain that it is preventing mob spawning as if the light was still there even though it isn't. Took down the lamps and almost got swarmed before I could safely get out. 

I'll do some more tests.

**Comment by 1skandar** [comment]
Ok, definitely something screwy, but I can't nail a reproducible pattern. Put down a Lumen Lamp and a piece of Cursed Earth. Sometimes the Cursed Earth will act like the lamp isn't there even if it is on, it will spread to other blocks and spawn mobs even if it is right next to the lamp and thus it being, theoretically, too bright to function. Other times the Cursed Earth will act like the lamp is on even when it is not, not spreading when it should nor spawning mobs. 

I'm thinking we have some sort of weird mod interaction going on. Other types of light dependent things do appear to be functioning. for instance, planting mushrooms works just as you'd expect, can't plant them next to an on lamp can if it is off.

Edit: Possible pattern. Cursed Earth within range of 1 Lumen Lamp will always think that lamp is off, even if it is on. Cursed Earth within range of 2 will always think those lamps are on, even when they are not. I have no clue how that works, but there it is.

**Comment by ReikaKalseki** [comment]
What mod is Cursed Earth?

**Comment by 1skandar** [comment]
Extra Utilities, sorry about that.

**Comment by ReikaKalseki** [comment]
Digging through his code, I found some things related to light handling triggering block updates that he then co-opts to reset spawner timing logic. I suspect this is on his end, especially if it only happens with Cursed Earth in proximity.
