### ISSUE TITLE
Unable to leave Chromaticraft dimension with tpx command (mystcraft)

### ISSUE THREAD

**Issue by Looma-mc** [ReikaKalseki/Reika_Mods_Issues#47]
I cannot leave the chromaticraft dimension with the tpx command from mystcraft. Right now i am stuck in this dimension and see no exit. it also resets every time i log in.

is there a legit way to leave this dimension that does not involve a cruel death?

**Comment by 1Matthias** [comment]
Fall into the void, it teleports you out of the dimension.

**Comment by Looma-mc** [comment]
punched a hole through bedrock. that worked. thanks :)

**Comment by TomeWyrm** [comment]
Actually that's still a bug. TPX should be able to transmit you to/from any dimension.

**Comment by ReikaKalseki** [comment]
Looking at the MystCraft code, denying linking books also denies the /tpx command, so this behavior, paired with my linkbook denial for the dimension, is in fact intentional design on MystCraft's part.
