### ISSUE TITLE
Suggestion: bag for runes and shards

### ISSUE THREAD

**Issue by notchriss** [ReikaKalseki/Reika_Mods_Issues#470]
Quite a few Chromaticraft recipes require many different runes, or shards, or structures built with many different runes (sometimes all of them). Notepad checklist somewhat helps, but I figured some item in game would be very useful. 

The item would have an inventory of it's own and could store one (or stack) of each rune, each shard, boosted shard, etc. Upon right clicking with it on i.e. chest it would take some of each rune, shard, etc., similarly to how Lunch Box and Lunch Bag from The Spice of Life mod behaves. Except each slot would be already marked by the symbol of the color that's supposed to go there. This way if a player lacked some runes they would see immediately which ones.

That way if I want to go and craft myself some Multichromic Runes I'd just right click with item in question on my runes chest and voilà, lots of time saved.

Maybe the bag in question could have modes switched with a shit+right click, "takes runes", "takes shards"... or maybe a better idea is to implement a different bag for runes, shards...I don't know.

**Comment by ReikaKalseki** [comment]
I have no interest in reducing the crafting process to clicking in a GUI.

**Comment by notchriss** [comment]
Not crafting, just taking them out from the chest fast, making sure you have all you need and quickly find out which ones you still lack. Crafting goes as usual.

**Comment by TomeWyrm** [comment]
Basically you want a Botania Flower pouch, but more "take from inventory to use" than the Flower Pouch's "collect flowers to store later" idea, right?

**Comment by notchriss** [comment]
Yeah sorry if my post was unclear, English is not my native lang obviously. I don't know Botania's Flower pouch but it's probably something similar. Now when I want to craft something, say a Multichromic Rune, I open my storage, take one of each Rune. Then I count them and I see I am 2 short. I need to figure which ones I still lack. I open a notepad, list all 16 names, then add a + sign to the ones I have in my inventory. The ones without a + are the ones I need to craft before crafting Multichromic Rune. This is the problem that some item could solve, in my opinion.

Now imagine if instead of notepad I have a say Chromatic Pouch, a bag with 16 slot inventory where each slot represents a particular color and that color only (tahara, nila, etc.). I right click a chest (or modular storage, or ae2 chest, or ae2 terminal...) with a Chromatic Pouch and Pouch takes say 16 of each Rune it finds in that storage to it's inventory. I open my Chromatic Pouch and I immediately see that I have slots for Zambarau and Vadali empty. It saves time otherwise spent for collecting each rune individually and also time using notepad figuring out what I still lack. 

That's just one way to implement it, I got the idea from The Spice of Life lunchbox and lunchbag, which are used to quickly take the food you haven't still eaten from the storage. It's probably not the best way to implement it, just an example. For all I care there could be a "Chromic Notepad" item that shows which colors you currently have and which ones still lack in your inventory upon mouseover, it would still be useful. I hope that clarifies :)

**Comment by TomeWyrm** [comment]
http://gamelabo.exp.jp/tumigame/wp-content/uploads/2015/03/botania-gui-flowerpouch.jpg
That is a screenshot of the botania flower pouch

http://youtu.be/O2MX9Ox_jR8
That is a demo video of the lunchbox and lunch bag

**Comment by TomeWyrm** [comment]
I think that the Flower Pouch concept is more useful if you change part of the intended functionality by the addition of a feature from the lunch items. A constant regular grid for your items in a second inventory. This means you take up less precious inventory space with a bunch of different colors of runes while you're transporting them, they're very organized which aids in figuring out information about them (Like "Hey, I'm missing Kuro!" or "I have half as much Vadali as any other color"). They can auto-populate the portable storage, which means you don't have to switch items between lots of GUI's all the time. BUT they should not be able to go the other way automatically; if you can just right-click-complete crafting recipes without thinking, that rather defeats the purpose of having the complex crafting system in the first place. Instead you should have to transfer from your pouch to your normal inventory in preparation for crafting.

Though, that being said... maybe an auto-fill for stacks from pouch might be a nice feature. Think of something like the Forestry Backpack refill mode. If you have a stack of Kuro shards in your inventory and some in the suggested Chromic Pouch, and then use a Chromic Shard? Having the stack in your hand refill could possibly be useful in many places. If that function does appeal, you may want to automatically pull in any items over a stack that are valid for the pouch. A problem I have with the forestry backpacks in restock/refill mode is that if I drop some of the item on the ground and then pick it up, I get TWO stacks in my inventory.

**Comment by ReikaKalseki** [comment]
Upon further thought, shards or other elemental items are rarely collected in great number, aside from elemental stones, making this not really worth the effort.
