### ISSUE TITLE
Fix for the "The Nuclear Age" achievement?

### ISSUE THREAD

**Issue by DeLourium** [ReikaKalseki/Reika_Mods_Issues#471]
A few days ago i stumbled upon the same problem mentioned here:  https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/453  where the first ReactorCraft achievement is unobtainable

When i took a look at this Issue, it was labelled with "fixed", but how?
I didnt find any fix for it there. I assumed that it has been fixed in the newest version of DragonAPI and ReactorCraft, but i downloaded the latest Version (v9b), a few days after this Issue has been labelled with "fixed". So what is the fix for it?

**Comment by ljfa-ag** [comment]
The fix is in the upcoming not yet released version. Sorry, you still have to wait for an unknown amount of time :/

And please do not open a new issue if you only want to refer to a closed issue.

**Comment by DeLourium** [comment]
Okay thanks :)

Didnt know where to post that ^^

so how often does Reika usually update his mods? :D

**Comment by ljfa-ag** [comment]
Hm, I don't remember. It usually takes a while between major releases, but I feel like v10 takes longer than usual. Might just be me though.

**Comment by TomeWyrm** [comment]
Soon™

**Comment by ReikaKalseki** [comment]
:P

**Comment by DeLourium** [comment]
nice one Reika :D
