### ISSUE TITLE
Flourite Crystal color misbehaviour

### ISSUE THREAD

**Issue by DeLourium** [ReikaKalseki/Reika_Mods_Issues#472]
While playing around with ReactorCraft a bit, i found some weird behaviour of the Flourite Crystals:
after mining different kinds of fluorite ore, i always got blue Fluorite crystals. I then checked the configs and enabled both recoloring and rainbow fluorite and after restarting all the flourite crystals dropped, turned orange (and the next time i reloaded the world they turned magenta). Also if i put some crystals in my inventory (from my storage system), they turn to whatever color is dropped this day.

Recoloring doesnt work either (at least NEI tells me that coloring them red, will yield blue crystals).

Im using ReactorCraft along with many other mods so im afraid, that they might cause that problem, but i dont believe it, as none of the other mods have some kind of fluorite themselves
(i use FTB infinity with GregTech and Galacticraft added, aswell as Reikas Mods of course)

EDIT: Just found something in another Issue and it seems like unification might also affect those crystals.
Any known cases of Mods interfering with Fluorite Crystals?

**Comment by Duckfan77** [comment]
There are known instances of that, try turning off Gregtech unification and attempting it again.

**Comment by ReikaKalseki** [comment]
It is a unificator responsible.

**Comment by DeLourium** [comment]
I´ve looked up the config files but i only found a unification entry for the gems (not for the crystals). i´ve tried disabling that but it only made my crystals convert into gems :/

**Comment by ReikaKalseki** [comment]
Keep looking, because this only happens with unificators.
