### ISSUE TITLE
Chromaticraft ctrl tooltip crash with gregtech

### ISSUE THREAD

**Issue by HajimeAnno** [ReikaKalseki/Reika_Mods_Issues#474]
When I press ctrl key while the mouse pointer is on a gregtech item in the inventory screen, minecraft freezes and stops responding.
It doesn't output any meaningful log because it is a "java.exe is not responding" crash.

It doesn't happen in a fresh new world, you need to execute /chromaprog -1 beforehand to make it reproduce, and there's no problem if the pointer is on an item from vanilla, chromaticraft, or other mods like IC2.

Tested on forge-10.13.4.1614

Installed mods:
- ChromatiCraft 1.7.10 V9b.jar
- DragonAPI 1.7.10 V9b.jar
- gregtech-5.08.33.jar
- industrialcraft-2-2.2.810-experimental.jar

**Comment by ReikaKalseki** [comment]
Does this only happen with GT installed?

**Comment by HajimeAnno** [comment]
From what I've been experimenting today, it looks like it's not actually limited to GT items. Some vanilla items like glass block, or items from other mods like stone transport pipe from BC, or ThermalExpansion Machines, can cause the crash. But it didn't happen with some other items like grass block, BC gates, or TE metal dusts.

And yes, it happens only if you have GT installed and you have some chromaticraft progression achieved.

The minimum environment I could reproduce this bug had only four mods above installed. I created a new superflat world, ran "/chromaprog -1", and pressed ctrl while pointing at a glass block in the inventory screen, then it crashed.

**Comment by ReikaKalseki** [comment]
I strongly suspect he is doing something with the tooltips.

**Comment by Haggle1996** [comment]
https://bpaste.net/show/f4d0b9691325
http://pastebin.com/YC4QHW89

I believe these two crashes may be related to the issue. In my pack, CTRL shows some additional tooltip info from the Tool Utilities mod. Several users have reported that pressing CTRL causes the above CTDs, however, I can't replicate these errors on my machine. The two crashes are from other users in separate environments.

**Comment by ReikaKalseki** [comment]
Both crashes are because someone added a null-item ItemStack to the furnace smelting recipe map. This is a very serious error and entirely incorrect.

**Comment by Haggle1996** [comment]
Awesome, thank you! That will help me troubleshoot the offending mod.

**Comment by Haggle1996** [comment]
FWIW, I wrote a small addon to my tweaks code that band-aids the issue for players in my pack. I haven't figured out what mod is registering the bad recipe, but it is a null entry in the getSmeltingList. Thanks for your help, Reika!

```
        for (Iterator<Entry<ItemStack,ItemStack>> iter = FurnaceRecipes.smelting().getSmeltingList().entrySet().iterator(); iter.hasNext();)
        {
            Entry<ItemStack,ItemStack> entry = iter.next();

            try{
                Main.log.info("HaggleTweaks found valid furnace recipe: " + entry.getValue().toString() + " " + entry.getKey().toString());
            }catch(Throwable t){
                Main.log.info("HaggleTweaks is removing invalid furnace recipe.");
                iter.remove();
            }
        }
```

**Comment by ReikaKalseki** [comment]
I have a way that can detect the relevant mod. As of v11, DragonAPI fires a Forge event when smelting recipes are registered (yes, that took ASM), and you can check for null entries and print a stacktrace using `Thread.dumpStack()`. You can also use that to cull the entry pre-emptively and alleviate the need for iteration over the recipe list.

Also, I would explicitly check for itemstack != null and itemstack.getItem() != null. Anything else is superfluous. Yes, a toString() will catch both, but less clearly.

Hell, I might implement this natively into DragonAPI.

**Comment by ReikaKalseki** [comment]
It did get put in DragonAPI. Any info in the logs?

**Comment by Haggle1996** [comment]
Hadn't thought check. I will pull my fix and see what outputs in the log.

**Comment by Haggle1996** [comment]
[fml-client-latest.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/155386/fml-client-latest.zip)

Zipping the log since it's so huge. Many many many invalid recipes output, from many different mods, starting at line 11134 and ending around line 21290.

**Comment by Haggle1996** [comment]
The biggest offender by far is Ztones. If you're not familiar with it, Ztones is a mod similar to chisel, but instead of adding a chisel-like interface for changing blocks, you simply hold the root block in your hand and spin the mouse wheel while holding down the shift key. It's reasonable to assume that all the block variations that can only be crafted in this manner are what's causing near ~9000 lines of null recipes.

**Comment by ReikaKalseki** [comment]
Why would that make him register recipes with ItemStacks of null?

**Comment by Haggle1996** [comment]
Good question. The mod (and author) are found [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2221070-ztones-v-2-2-1-decorative-blocks-16x). I also use a mod called ChiselTones, which allows you to create Ztones blocks via the Chisel mod's chisel, which could potentially be the source of the problem. I'll send the author of ztones a note and ask him to look at this thread.

**Comment by TomeWyrm** [comment]
If you're using Minetweaker, may I suggest http://minecraft.curseforge.com/projects/chizzle-z-tizzle

One less mod, and frankly I prefer the way the MT script does it :-)

Also if it IS ChiselTones causing some of the issue, it will cut down on the spam.

**Comment by Haggle1996** [comment]
Removing ChiselTones (and replacing with the MineTweaker script) removed the overwhelming majority of those errors. Thanks for the suggestion, @TomeWyrm

**Comment by ReikaKalseki** [comment]
We still have a few hundred in our pack; it looks like one for each block type/metadata pair.
