### ISSUE TITLE
Chromaticraft v10 forcing a crash

### ISSUE THREAD

**Issue by 1skandar** [ReikaKalseki/Reika_Mods_Issues#475]
Listen, I get what you are trying to do here, but this is a very, VERY poor idea. As soon as I update my pack I'm going to be fielding hundreds of "this pack is broken because it crashes" because pretty much no one is going to bother reading the crash report nor will most people have any idea how to fix it in the rare case they do. Worse, there is no way to fix this preemptively on my end. I can't warn people, they will update and it will crash, and I have NO WAY to warn them beforehand or tell them how to fix it.

You basically dumped a monster headache on every mod pack dev who uses Chromaticraft.

**Comment by kolatra** [comment]
Oh is this the Java 8 crash if there isn't a certain argument?

**Comment by ReikaKalseki** [comment]
CC has an unknown-source issue where every installation that uses Java 8 will, if not told to use the G1GC, crash as soon as the dimension is generated. I have received several dozen reports of this thus far and that will only increase as more people progress farther through the mod.

http://pastebin.com/LxWv5du7

I have tried addressing the issue directly, but the crash is an actual JVM crash, not a Java exception/error, and everyone I have asked have either had absolutely no idea what the cause is, much less how to fix it (90%) or have blamed me without explanation and refused to elaborate (10%), leading me to suspect a lack of basis for such accusations. If you know someone who both knows enough about the internals of a JVM and who is willing to actually be civil and helpful, by all means contact them and see if we can fix this properly.

Also, do packs not have the ability to specify Java arguments? I remember Monster doing this.

**Comment by 1skandar** [comment]
As far as I know, no. Curse certainly can't. 

I appreciate your problem, but this is still a giant, giant headache for me. Force crashing in a way I can't prevent or warn about is going to come down on my head, not yours. This needs to be an in game warning, or, at worst, crashing the game with this warning when the portal structure is first built. This will give me the ability to warn people about the problem and provide in game resources allowing me to walk them through fixing it.

Edit: a complete tangent, but a very good job on making the lexicon more user friendly and overall better looking

**Comment by Saereth** [comment]
Technic can specify launchers options, but every single user will have to do it manually, same with ftb launcher, no way for pack creators to inherently set java arguments in most of the major launchers.

**Comment by TomeWyrm** [comment]
FTB used to be able to, the modern version might not be able to

**Comment by 1skandar** [comment]
Regardless, for my sanity, and other mod pack devs sanity, this needs to be handled in somewhat of a different manner. If that Java argument fixes it, can't you figure out from there the _why_ of it fixing it?

**Comment by TomeWyrm** [comment]
He's tried. Nobody can tell him.

"everyone I have asked have either had absolutely no idea what the cause is, much less how to fix it (90%) or have blamed me without explanation and refused to elaborate (10%),"

**Comment by keybounce** [comment]
Regarding G1GC:

Every time I have tried using it (J6 and J7), the memory usage of java jumps up to the maximum (worst-case) allocation almost immediately.

This is not pleasant for desktop apps that are sharing a computer with other things. (It's just fine for servers, which I think is Java's target).

(EDIT): Do you know any way to keep G1GC tame and not consume too much memory or CPU?

**Comment by 1skandar** [comment]
Yeah. I hate to say it, but relying on the user to set a Java argument to fix your problem is, oi. I get you can't figure it out, but as far as kludges go this is pretty bad. This isn't a good solution. There is going to be a significant amount of people who will have no clue on how to do this and then there will be people like keybounce who can't.

Please find another way.

**Comment by Duckfan77** [comment]
There _is_ another way to fix it, however that is running Java 7, which is likely far less pleasant to have to do.

**Comment by 1skandar** [comment]
And impossible. There are a few mods that require Java 8 now.

**Comment by Duckfan77** [comment]
Exactly my point.

**Comment by ReikaKalseki** [comment]
I am willing to move the crash elsewhere - though I strongly suspect an ingame one, or even a version-checker-like popup would be far more reviled than this - but that is a bandaid fix at best.

For obvious reasons, actually knowing the difference between the two GCs is the best solution, but I know of noone who can help. The only person I can think of is cpw, and I doubt he will have time to deal with this.

**Comment by 1skandar** [comment]
You can ask. At worst he won't reply and you will be no worse off.

And thank you. It isn't about how much it is hated, it is dumping the problem in my lap without giving me any tools to deal with it. By moving it I can address the problem in a sensible manner and use other tools to more effectively spread the solution.

**Comment by keybounce** [comment]
Actually, if the garbage collector is messing up, I'd open a support request/issue with Oracle.

**Comment by ReikaKalseki** [comment]
> Actually, if the garbage collector is messing up, I'd open a support request/issue with Oracle.

And get a reply six months later, possibly consisting entirely of something like "your game must have an issue, fix its source"....

**Comment by keybounce** [comment]
Maybe; certainly getting a VM crash is probably going to be considered more important.

**Comment by ReikaKalseki** [comment]
I say what I did based on experience; those replying rarely understand that we do not control the "main application" and tell us to fix it. Hell, I have had hosting services say that about _vanilla_.

**Comment by keybounce** [comment]
Ouch.

**Comment by smbarbour** [comment]
Well, it's apparently an issue with garbage collection, and I can see in the pastebin that CMSIncrementalMode is specified (which is a deprecated option).  Could that have something to do with it?

**Comment by ReikaKalseki** [comment]
The pastebin is not mine, and was generated months ago. However, the actual crash is consistent. Here is another example:

http://forum.feed-the-beast.com/threads/chromaticraft-questions-and-suggestions.54905/page-80#post-1522382

I have no idea how the internals of this work. Can someone who has Java 8 try without the CMSIM option? I am not willing to switch everything on my system to Java 8.

**Comment by Haggle1996** [comment]
Due to a bug in ATLauncher, I can't set the java argument automatically for the individual pack. It can only be set globally for all packs by the end-user...this is going to cause a nightmare. Obviously, it would be nice if ATLauncher fixed the bug, but it's been open since August.

**Comment by smbarbour** [comment]
How long ago did this issue start occurring?  I ran Chromaticraft V9b in late October on Java 8 without G1GC.  Does it occur on launch or when first visiting the dimension?

**Comment by ReikaKalseki** [comment]
Only when visiting the dimension, and _always_ when visiting the dimension. The issue started happening as soon as there _was_ a dimension.

**Comment by TheDoctorSoda** [comment]
Forgive me for my ignorance, I have not played with ChromatiCraft, but do you know what part of the dimension is causing it?

**Comment by ReikaKalseki** [comment]
The code referenced has to do with WorldChunkManager, something normally used to generate the biome noise map, specifically [this line](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/World/Dimension/ChromaChunkManager.java#L55).

**Comment by ReikaKalseki** [comment]
Great...

https://www.reddit.com/r/feedthebeast/comments/3xxdb3/reika_screws_over_pack_makers_yet_again_this_time/

**Comment by keybounce** [comment]
So I had a chance to play with Java 8 and G1GC.

Out of the box, it is tame -- it no longer has memory run-away.

I did get stutters and short-term pause/hangs. I don't know if that was from chunkgen, or from G1GC being "stop the world GC".

**Comment by LemADEC** [comment]
Sounds like you are able to reproduce it easily.
Did someone try to reduce the code down, up to an "as small as possible" version of CC that reproduce the issue?

**Comment by keybounce** [comment]
The problem, after reflecting on it overnight, seems to be this:
1. Minecraft forces a garbage collection on the client when the client changes worlds.
2. The compiler triggers an error when either CMS or parallel new are doing garbage collection -- both of these are cleaning / moving the code around.

In J7, permgen was in a separate memory zone.
In J8, it is not.

So, the prediction is: G1GC solves this by being a full "stop the world", and stops the compiler. CMS does not, lets the compiler run while code is being moved. Parallel old ... odd, it is also a stop the world, but for some reason still triggers the compiler.

What would be worth checking, if I had any idea how to enable it, is the really old serial old collector. It is still the best collector for small heap programs (smallest overhead, and there's no benefit from multi-threading a small heap), and it is a full-stop collector.

The big question: Does the server-side -- which does not force a garbage collection when someone moves to a new world -- also crash when you go into the dimension?

**Comment by keybounce** [comment]
Ohh! Worth testing: There's a flag in J7 that tells CMS that an explicit GC invokes concurrent and unloads classes, and another that says an explicit GC invokes concurrent wihtout unloading classes. CMS also has a full "stop the world" worst-case GC -- but you can also set flags to force explicit GC to run that full stop the world worst-case GC. What if I set that on? ... Will test

**Comment by keybounce** [comment]
Nope, forcing full did not work, try cleaning wihtout unloading code ...

**Comment by keybounce** [comment]
Still fails.

*\* But the failures are happening at different times.

One is happening before the "Downloading terrain" message (that's when not unloading code)
One is happening after the "downloading terrain" message (That's when forcing a full GC).

It is definitely a function of the behavior of permgen, which behaves differently in J8 than J7.

**Comment by ReikaKalseki** [comment]
And PermGen is related to the number of classes loaded. Could the sheer number of classes suddenly initialized by the dimension (since the dimension has over 400 dedicated classes) have something to do with it?

**Comment by 1skandar** [comment]
That....might do it, yeah. It's worth a test, at least.

**Comment by keybounce** [comment]
Ohh ... what's a good test case for that? I was thinking of the nether, but there's not that much in teh way of dedicated classes there.

Maybe twilight forest? (testing that)

**Comment by 1skandar** [comment]
Well, I was thinking Reika could more easily temporarily disable some of those classes, or initialize them elsewhere. If it solves the problem then make a more permanent solution, if not, revert.

**Comment by keybounce** [comment]
No, twilight forest does not have any crashing issues with CMS in J8.

**Comment by 1skandar** [comment]
I was talking in Chromaticraft itself. He knows his mod very well, and that should be the easiest test.

**Comment by keybounce** [comment]
Undertstood. I was just thinking that Twilight forest also has a lot of classes, and might be a good confirming test.

**Comment by ReikaKalseki** [comment]
TF _does_ have a great many classes, but he might initialize them differently.

I do not use Java 8 - and am not willing to switch since I have incompatible applications - so I cannot test myself. Is there a way for someone to force-load classes at runtime (outside of having custom-written source)?

**Comment by 1skandar** [comment]
I run Java 8. I can test if you want.

**Comment by Prospector** [comment]
If it comes to it, you could always set up a virtual machine to test some things.

**Comment by ReikaKalseki** [comment]
How does one force-load classes as a user, though? I would prefer not having to make a custom build (and then wait 12h for Curse to approve it) that anyone could download...

**Comment by 1skandar** [comment]
DM me on Twitter with a private link? Or, well, anything else I can do to help.

 I really would like to help out, for not purely unselfish reasons. The sooner we can make this crash go away, the easier it will be on me and the rest of the mod pack devs.

**Comment by LemADEC** [comment]
As far as I understood, Java classes aren't unloaded, so you would just call a random method in your classes to load them during the FMLInitializationEvent event? or simply ask forge to try registering events in there?

**Comment by TomeWyrm** [comment]
Good luck asking forge. They're notoriously uncooperative, and both cpw and lex vocally dislike Reika

**Comment by ReikaKalseki** [comment]
> As far as I understood, Java classes aren't unloaded, so you would just call a random method in your classes to load them during the FMLInitializationEvent event?

Correct, but I was looking for a way to do it without a custom compile.

**Comment by LemADEC** [comment]
By asking forge, I meant the code itself, not the authors :).

From what I read in ChromatiCraft code:
FMLInitializationEvent calls ChromaDimensionManager.initialize();
which calls DimensionManager.registerProviderType, DimensionManager.registerDimension and DimensionManager.registerBiomeType

FMLInitializationEvent continues with calls to RetroGenController.instance.addHybridGenerator
which calls GameRegistry.registerWorldGenerator

Hence 5 generators are instanced in advance.
WorldProviderChroma might be instanced by Forge, just not sure when (1).

FMLPostInitializationEvent calls ChunkProviderChroma.triggerStructureGen()
which starts the "ChromatiCraft Structure Gen" thread
However, the ChunkProviderChroma isn't instanced (2).
Hence, the decorators aren't preloaded.

Is there other dedicated classes you see initializing when dimension is loaded?

**Comment by ReikaKalseki** [comment]
Yes, most of the individual decorator-type generator objects - things like the fissure and floatstone generators - and the dozens of classes associated with the structures and their parts. Plus a significant handful of helper classes that might only be initialized at that point.

**Comment by WesCook** [comment]
Not to interrupt the code sleuthing, but could we entertain a bandaid solution while this is being resolved?

Along with Haggle and 1skandar, I've no way of sending specific Java command lines arguments to my players, so I can't realistically update Chromaticraft right now.  If the crash were moved to later in the mod, or an "at your own risk" alert were implemented instead, that would make life a lot easier for me (and I suspect other pack authors).

I appreciate how tricky a bug like this is to track down.  I'd also be happy to help test if that's something I could do.  Though a shorter-term bandaid fix would also be much appreciated so we can keep the mods up to date.

**Comment by keybounce** [comment]
Actually, does the crash happen client-side?

Single player, crash, fine.
Server crashes, fine
But the client? The client is just rendering. The client should see no difference between ChromaC dim and other dims, right?

If the server is running G1GC, and the client is not, will the client crash in the dimension? Can someone test that with the V9's?

**Comment by ReikaKalseki** [comment]
> Along with Haggle and 1skandar, I've no way of sending specific Java command lines arguments to my players, so I can't realistically update Chromaticraft right now. If the crash were moved to later in the mod, or an "at your own risk" alert were implemented instead, that would make life a lot easier for me (and I suspect other pack authors).

Use the new config.

> Actually, does the crash happen client-side?
> 
> Single player, crash, fine.
> Server crashes, fine
> But the client? The client is just rendering. The client should see no difference between ChromaC dim and other dims, right?
> 
> If the server is running G1GC, and the client is not, will the client crash in the dimension? Can someone test that with the V9's?

The crash comes from worldgen code, which only runs on the server. That said, the client might just crash on one of the renderers.

**Comment by ljfa-ag** [comment]
I tested it: When the server uses the flag and the client doesn't it seems to be fine (although I couldn't actually enter the dimension because it said I'm not ready, but without the flag the server still crashes)

**Comment by MJRLegends** [comment]
Yep im getting loads of people with crashes with mod pack for this issue as well. The information needs to be displayed better than just crashing the client.

This a massive headache for me and no one can use java 8

**Comment by ReikaKalseki** [comment]
> although I couldn't actually enter the dimension

Which invalidates the test.

**Comment by Flabort** [comment]
As a simple player, I understand that there is a command to skip certain progress milestones via cheat mode; it was supposedly used in previous versions of Chromaticraft to get the 'NULL' progress-point (which was the desert temples that weren't generating due to a different bug). 
Ijfa-ag, you probably need to use something like (don't quote me on this) "/chromaticraft progress Num", where Num is each individual progress flag needed before you can enter the dimension; that way you can skip straight to testing the bug properly.

**Comment by ReikaKalseki** [comment]
As of v11, that command has been redesigned.

**Comment by ghost** [comment]
Just to be on the safe side.... does any dimension related code call or reference any system native code or even tries to execute architecture native code? (I don't think so, but it never hurts to ask)

On the other hand.... I get the feeling that keybounce was on the right track here. To me this looks a lot like a race condition in which the GC doesn't finish up while the compiler tries to execute code currently being moved, and G1GC's way of effectively halting the system to perform its tasks does circumvent that. A way to prove or falsify this assumption would be to limit the server ~~thread~~ process to 1 CPU core. While this would not affect OS thread scheduling, it would at least prevent multiple threads running concurrently competing for calculation time.

**Comment by ReikaKalseki** [comment]
> does any dimension related code call or reference any system native code or even tries to execute architecture native code?

No.

**Comment by ReikaKalseki** [comment]
Any updates?

**Comment by ReikaKalseki** [comment]
Well, [I have managed to subvert the issue](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=27198). Hopefully permanently.
