### ISSUE TITLE
4 issues on RCv10

### ISSUE THREAD

**Issue by Duckfan77** [ReikaKalseki/Reika_Mods_Issues#476]
I have 4 errors to report here:
1. After updating to Version 10 of rotarycraft, I am getting chat spam of 
   `<Tile Entity Wood Shaft @ <Insert world location here> [CLIENT] is throwing class java.lang.ArrayIndexOutOfBoundsException on update: null
   []>` The spam is also present in the FML Log, which I will attatch when I find a text host that will accept 20MB of text. Those 20MB were generated by less than a minute in world
2. I am also getting drastically worse FPS, by about half. This is likely related to the first issue.
3. My wooden shafts are continuing to transmit power and rotating despite being disconnected from the power source. 
4. Finally, the overlay from the angular transducer is not disapating, and retains it's rendering across logins.
   All of these issues continued after a relaunch of minecraft.

![2015-12-21_21 54 14](https://cloud.githubusercontent.com/assets/9396248/11947522/a557e34e-a82d-11e5-8c70-add56e0a377d.png)

**Comment by ReikaKalseki** [comment]
The first three are almost certainly related (and possibly due to my cross fixes). The fourth...makes no sense.

**Comment by Duckfan77** [comment]
https://gist.github.com/Duckfan77/8edea46ea3c163002b29 Here is the smaller log I could locate, It doesn't appear to include startup information, and seems to begin at world load. I hope this is sufficient, as the full log is refusing to be hosted anywhere.

**Comment by ReikaKalseki** [comment]
Can you try reloading the game, then getting the log (or disabling stacktrace culling (JVM argument))? A missing stacktrace makes the issue unsolvable.

**Comment by Duckfan77** [comment]
I did reload the game, the first log was 360 MB. I'll try the JVM Arg if you know what it is or I can easily locate it with google.

**Comment by Duckfan77** [comment]
https://gist.github.com/Duckfan77/215d7089567683c29e2a A log that has no world loading involved.
I can try with a new world including no shafts, but that is unlikely to help. The second log is the one that started at 20MB with most of the spam deleted, hopefully without removing anything key.

**Comment by ReikaKalseki** [comment]
I need in game "runtime" logs, not loading logs. The issue is in the TileEntityShaft update somewhere.

**Comment by Duckfan77** [comment]
That is what I expected, hopefully the second file in the gist is more useful.

**Comment by ReikaKalseki** [comment]
It is not.

> [22:02:41] [Client thread/INFO]: [CHAT] Tile Entity Wood Shaft @ DIM0: -714, 77, -886 [CLIENT] is throwing class java.lang.ArrayIndexOutOfBoundsException on update: null
> [22:02:41] [Client thread/INFO]: [CHAT] []

You will need to try the JVM argument.

**Comment by Duckfan77** [comment]
Do you have any idea what said argument would be?

**Comment by Duckfan77** [comment]
> [22:02:32] [Server thread/INFO] [FML/]: DRAGONAPI: 
> [22:02:32] [Server thread/ERROR] [FML/]: DRAGONAPI ERROR: Tile Entity Wood Shaft @ DIM0: -714, 100, -886 [SERVER] is throwing class java.lang.ArrayIndexOutOfBoundsException on update: 0
> [22:02:32] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ArrayIndexOutOfBoundsException: 0
> [22:02:32] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at Reika.RotaryCraft.TileEntities.Transmission.TileEntityShaft.animateWithTick(TileEntityShaft.java:609)
> [22:02:32] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at Reika.DragonAPI.Base.TileEntityBase.updateTileEntity(TileEntityBase.java:560)
> [22:02:32] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:453)
> [22:02:32] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.world.World.func_72939_s(World.java:1939)
> [22:02:32] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
> [22:02:32] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
> [22:02:32] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
> [22:02:32] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
> [22:02:32] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
> [22:02:32] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Is the closest to a stacktrace I am able to locate.

**Comment by Duckfan77** [comment]
https://gist.github.com/Duckfan77/33835659cb3d1d22659e Current best log available.

**Comment by Duckfan77** [comment]
With further testing the issue appears to only occur in already created worlds that were updated while already containing rotarycraft infrastructure. In a fresh world I was unable to recreate the issues.

**Comment by ReikaKalseki** [comment]
Even using the exact same steps?

**Comment by Duckfan77** [comment]
As the steps to produce it are currently unknown to me, I'm not sure. It began happening on all my old worlds, and when I created a new world, placed a power source, shaft, and recipient it didn't occur. It isn't dependent on shaft junctions, as one of the worlds that is giving the error has none.

**Comment by Danvern** [comment]
Hullo,
I am having the same issue as number one, only with stone shafts. I can run them fine in single player, but on my server they cause lag and console spam.

**Comment by Duckfan77** [comment]
When I have more time to test tonight I'll attempt to reproduce it using the v9 files and updating, to try to determine what scenario causes it.

**Comment by ReikaKalseki** [comment]
This has something to do with NBT, which I cannot fix.

**Comment by Danvern** [comment]
Is there a user-fix besides griefing your machines?

**Comment by ReikaKalseki** [comment]
Manual NBT editing, but that is even more work.
