### ISSUE TITLE
Chromaticraft/Dragon API crash after updating to v10

### ISSUE THREAD

**Issue by Saereth** [ReikaKalseki/Reika_Mods_Issues#477]
Getting some class def not found errors now and the server is crashing during start

http://pastebin.com/HpdptFq0

**Comment by ReikaKalseki** [comment]
Is this on a dedicated server?

**Comment by Saereth** [comment]
Yes

**Comment by ReikaKalseki** [comment]
You will have to wait for v10b, which I really would prefer to put off until tomorrow to catch additional issues.

**Comment by Haggle1996** [comment]
Not sure if it's related or if I should open a separate issue, but getting this error in single player: http://pastebin.com/kg4wrwzP

**Comment by ReikaKalseki** [comment]
Unrelated, and try removing mods (and open a new issue).

**Comment by ReikaKalseki** [comment]
The main issue is fixed.
