### ISSUE TITLE
Neutron Absorbtion Rates

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [ReikaKalseki/Reika_Mods_Issues#478]
Ive noticed a varying degree of Neutron Absorption Rates for different materials at different times.

Is there any rough listing of the shielding capabilities of the different materials anywhere?

Currently my reactor is shielded with a layer of neutron reflectors, 2 layers of Bedrock Alloy Blocks, A layer of Neutron Absorber, another layer of Bedrock Alloy Blocks, then a layer of Solid Bedrock blocks.

In the past, I have had issues with neutron buildup outside of my containment systems that would accrue tens of thousands of neutrons and crash my server when I traveled to the reactor location.

Because of this tendency, I have started to run my fission reactors inside of AE2 storage cell dimensions to contain the neutron spread since i cannot safely determine what materials are needed at what thicknesses to contain the neutrons and prevent the buildups.

I'm just trying to avoid that type of situation again.

Also, with the new radiation intensity system, are there any major changes to material's ability to shield?

I just received the update notification today and read the change log and would like some input before upgrading to v10a.

Thanks for the time.
Love the mods.

**Comment by zemerick** [comment]
Can you be a little more specific as to what you are seeing?

It's all a chance system, so there will be times you see more neutrons slip through, and times you see less.

Also, the neutron absorber is limited to Fusion neutrons, so it's doing nothing.

I didn't notice any changes in the code that could be causing new issues, but I have only spent a couple mins looking real quick, and haven't yet tested in game.

**Comment by MachiavelliSeraphim** [comment]
Please mark this informational or a request for a feature.

In the past Ive had massive neutron leaks and buildups.  Thankfully, since then its been pretty stable.  I was wanting to know what a "safe" containment system would be composed of.  Ive heard that 9 layers of concrete is "weak".  

I understand modern nuclear physics and positive void reactors.  I understand realistic shielding materials.  Its the matrrials used in game that leave me in the dark.  So I dont have a problem per say, other than the lack of solid information on the materisls used to block and reflect neutrons.

Its no fault of anyones, so please dont take offense.  

Any information on shielding materials and neutron reflectors would be appreciated, and if the materials could be added with said information to the handbook, that would be perfect.

Ive got no problems searching for what I want to know, as long as it exists to be found.

Than you for your time.

**Comment by zemerick** [comment]
Not sure about ingame, but in the code you can find the answer easily for the proper shields:

https://github.com/ReikaKalseki/ReactorCraft/blob/f4ddf419178332d31ab7e655cff7b95528d795b5/Registry/RadiationShield.java

It's the first number so:

Steel is 90%
Concrete 60%
Water 30%
Bedrock Ingot Block 97.5%
Lead 75%
Obsidian 50%

Neutron reflector is 25% chance to reflect a neutron back the way it came.
Neutron Absorber 100% chance to absorb fusion neutrons.

Non-proper shielding items are based off of hardness, but will never exceed the bedrock ingot block.

For fission reactors, the only 100% safe reactor is one that is out of line of anything you don't want irradiated. ( So, you could put it at a diagonal to your base, out a ways, in the air. Or another dimension like you did. )

**Comment by ReikaKalseki** [comment]
I do not see a bug here, so I am closing the issue. Continue the discussion if you wish.

**Comment by MachiavelliSeraphim** [comment]
Thanks for the info.  Never been much of a java person, so I never tried looking in the source for the values.

Sorry to clutter up your issue tracker Reika.
