### ISSUE TITLE
ChromatiCraft Ore Harvester doesn't work on Magnetite Ore

### ISSUE THREAD

**Issue by umbralOptimatum** [ReikaKalseki/Reika_Mods_Issues#48]
Although the bedrock pick's silk touch works on ReactorCraft Magnetite, the Ore Harvester is just dropping the lodestones for me.

**Comment by 1Matthias** [comment]
Did you put the silk touch upgrade in the ore harvester?

**Comment by umbralOptimatum** [comment]
The book mentions nothing about upgrades for the Ore Harvester.

**Comment by 1Matthias** [comment]
Oh. Oops. Wrong item. Forgot about the pickaxe, thought you were talking about the mineral extractor. Sorry!

**Comment by ReikaKalseki** [comment]
Turns out handling for *every* mod ore was broken. Fixed.
