### ISSUE TITLE
Crash on load with ChromatiCraft v10a and Applied Energistics 2 rv3 beta

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#480]
Receiving this crash in single player with CC v10a: http://pastebin.com/kg4wrwzP

I am actively pulling mods to try and figure out what's causing this issue. Will update this thread shortly.

**Comment by 1skandar** [comment]
It's AE rv3, I can virtually guarantee it. The API has changed between rv2 and rv3 and until rv3 is release ready Chromaticraft will not be supporting it.

**Comment by Haggle1996** [comment]
I've already completely pulled AE2 rev3 and Forestry 4 (and related mods), still getting the crash. I'm working on #479 at the moment (down to one of 4 mods), but will move to this one soon.

**Comment by Haggle1996** [comment]
And FWIW, AE2 rev3 has already moved to beta. If you're familiar with the history of AE1/2, beta is about the best you can hope for. :D

**Comment by 1skandar** [comment]
Not related, but last I knew RTG didn't gen oceans. If that is still true you do realize that you are minorly screwed progression wise, right? No oceans, no ocean temples, no ocean temple unlock. Non gating, but...

**Comment by Haggle1996** [comment]
RTG supports oceans now, just FYI, but let's keep this #ontopic. I'm working on this one now.

**Comment by 1skandar** [comment]
Sorry, just looking at your mod list and that stood out. 

As far as it goes, this crash appears to be Chromaticraft trying to load a cross mod support recipe and failing. AFAIK that would be  either AE, Forestry (bees), Thaumcraft, or Thermal Expansion (well, Thermal Foundation). Concentrate on those first.

**Comment by Haggle1996** [comment]
Well, I feel stupid. I was certain I already tested it with AE2rev3 removed -- it was my first suspicion too -- but 479 probably got in the way. Anyway, yes, narrowed it down to AE2 rev3-beta. As AE2 is now in beta after a good, long alpha, I hope Reika updates to rev3 in v10. I'm going to close this issue and create a separate one for [REQUEST] Add support for Applied Energistics 2 - rv3 beta.
