### ISSUE TITLE
RotaryCraft/ReactorCraft v10a Opening the Handbook - Crash 

### ISSUE THREAD

**Issue by letskentots** [ReikaKalseki/Reika_Mods_Issues#482]
as I've mention at the title, my client game crashes every time opening the RoC/ReC handbook (Electricraft handbook seem fine though)

-using latest "v10a" DragonAPI/Rotarycraft/Reactorcraft/Electricraft
-revert to v9b doesn't crash the game when opening the RoC/ReC handbook

Crash Report
"http://pastebin.com/5vQTJZQa"

Latest Log
"http://pastebin.com/jhQ06d22"

-using "v9b" old world

**Comment by zemerick** [comment]
Known issue that should be fixed in 10b. I never had the RoC book crash, so not sure if the fix was just put into the ReC book, or if it was in dragonAPI. Will double check with him on that, and should be a quick fix if it's not already.

**Comment by letskentots** [comment]
thz for the reply ^_^
