### ISSUE TITLE
Just a small typo in ChromatiCraft

### ISSUE THREAD

**Issue by jkuball** [ReikaKalseki/Reika_Mods_Issues#485]
I just found a small typo in ChromatiCraft.

[ChromatiCraft/Resources/info.xml](https://github.com/ReikaKalseki/ChromatiCraft/blob/747ed9981c7a6ad45c6c3634a0d0800f8a5cf765/Resources/info.xml#L19) says "_this world is stange_" instead of "_strange_".

I think this it not worth a full pull request, this is not a gamebreaking bug, but it should be fixed at some time. :)

**Comment by ReikaKalseki** [comment]
Fixed.
