### ISSUE TITLE
Lumen Beacons Not Connecting? (Fixed)

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#486]
Okay, so I tried to connect Lumen Beacons and they don't seem to be connecting even though the multiblocks are complete (checked TAB and said 1b for multi). They is also 176 blocks in between the sending and receiving (Tried with 209/210 in between but didn't seem to work either). They are in-line with each other and same height.

I'm not sure if the receiving end multi-aura repeater at the bottom should do the _ding_ when R-clicked with the manipulator and it doesn't drain lumens into a relay source (Usually use that to test if lumens reach it).

I think the block in the center on the same layer of the Engraved Crystalline Stone is blocking the multi aura from sending/receiving Lumens.

https://www.youtube.com/watch?v=ZG6yhdeHutM

Here's a video I recorded that shows mostly everything I just explained. Excuse the crappy quality.
probably an error on my part though.

**Comment by HyperionNexus** [comment]
close

**Comment by HyperionNexus** [comment]
fixed

**Comment by HyperionNexus** [comment]
> fixed
