### ISSUE TITLE
NEI related crash upon pressing R upon Blaze powder

### ISSUE THREAD

**Issue by Adraxas** [ReikaKalseki/Reika_Mods_Issues#488]
Crash log
http://pastebin.com/GrKMBnYL

**Comment by zemerick** [comment]
Does it do this every time? I can not replicate it, but I have NEI 1.0.5.118 where you have 1.0.5.111, so it might be something fixed on their end. You also have lots of other mods I don't have on my test.

Can you try removing any extra mods and checking again?

**Comment by ReikaKalseki** [comment]
Oh no...

**Comment by Adraxas** [comment]
it does not seem to happen every time.

> Oh no...

that doesn't sound good.

**Comment by Haggle1996** [comment]
I had this crash in my pack when another mod updated a couple of weeks ago, prior to the release of v10. Moving to NEI 1.0.5.118 resolved the problem.

**Comment by zemerick** [comment]
ZodiacK256B on the MCF ( http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=25532 ) got the crash with NEI 118.

**Comment by Haggle1996** [comment]
Ah! I know where I saw that...try rolling back to Forestry 4.2.2.50 and Forge 1558 (current recommended version of forge). 

1566 introduced some new funkyness with fuels and 1614 has barely been out; I'm surprised mezz required it for Forestry 4.2.3.51.

**Comment by Zodiack256b** [comment]
After following Haggle1996's recommendation on reverting forestry and forge i have not seen this issue again. I will update if i get the issue under these file versions.

**Comment by Zodiack256b** [comment]
After multiple client restarts i have re-created the crash on forge 1558 and forestry 4.2.2.50.

http://pastebin.com/NfeuaNMw

Seems intermittent. Sometimes it happens and other times the client completes the startup without an issue.

**Comment by ReikaKalseki** [comment]
The crash has nothing to do with other mods.

**Comment by amesgen** [comment]
I have the same problem, minecraft crashes sometimes when I joined my server, with the same error like Adraxas, but after some restarts, it works again. Somewhat weird. This occured after updating forestry.

**Comment by Reignofmagic** [comment]
Any possible fix for this, in my crashlog it says that NEI Integration might be the source, and I do have the latest version for that. I'll try disabling the integration with rotarycraft see if that fixes anything.

**Comment by Saereth** [comment]
I'm also getting this crash http://pastebin.com/fjxNZEYF
when pressing R on mekanism salt

**Comment by ReikaKalseki** [comment]
Fixed...hopefully.

**Comment by ReikaKalseki** [comment]
Fixed...hopefully.

**Comment by Drethic** [comment]
@ReikaKalseki Do you have a release date for the version that will include this fix?

**Comment by TomeWyrm** [comment]
@Drethic

> Do you have a release date for the version that will include this fix?

Do not ask for ETA's. It will be released when it is ready to be released.

**Comment by Shahelion** [comment]
Wow...the number of duplicates, this has to be some sort of record. That dang Grinder...

TomeWyrm considering the number of times it's being reported, it makes sense to ask when it will be fixed.

Until then, is there a way to disable Grinder recipes in NEI?

**Comment by TomeWyrm** [comment]
Unfortunately "when it's done" is literally the only ETA I can give. Reika increments versions when he feels like it. I think it'll unfortunately be v11 before the fix goes live... he's doing a lot of new content on the dev server now.

As for disabling grinder recipes in NEI... Let me ask

**Comment by TomeWyrm** [comment]
Looks like there are no workarounds, and v11 will be the release for the fix.

**Comment by Saereth** [comment]
I understand it doesn't account for much but  I did want to stress the severity of this.  We've been getting literally dozens of crashes from this daily. We've been explaning this to players and asking not to continue opening duplicate issues here but that's where we're at.  Guess for now, we keeping waiting :/

**Comment by ljfa-ag** [comment]
Welp, it would've been nice indeed if there was a v10e to fix that...not the first time that an issue is marked as "fixed" but I have to explain that the fixed version is not yet released

**Comment by ReikaKalseki** [comment]
> not the first time that an issue is marked as "fixed" but I have to explain that the fixed version is not yet released

The alternative is me making a new release every time I fix a bug. That would effectively mean daily updates and every server becomes my dev server.

**Comment by Saereth** [comment]
Honestly for crash bugs, I'd be ok with more frequents, or even volunteering to test. The bugs that dont crash the client and/or server are of less concern.

**Comment by ljfa-ag** [comment]
Yeah I was just saying that some bugs are more urgent that others and might warrant an unplanned release with just the bugix and no half-finished features.
I can wait but it is still a nuisance for people ^^

**Comment by ReikaKalseki** [comment]
> Yeah I was just saying that some bugs are more urgent that others and might warrant an unplanned release with just the bugix and no half-finished features.

No such thing exists.

**Comment by TomeWyrm** [comment]
Unfortunately VCS doesn't work for Reika (no, don't try to sell him on one. He's aware of them, they DO NOT WORK because of things I'm not going to explain here. Don't PM him about Tortoise or the git clients or how your VCS is awesome, ok?). Which means he doesn't really have the code from v10d anymore, so he CAN'T release fixes without a bunch of half-finished content.

**Comment by Aknotsdeath** [comment]
I just got this crash today after updating to v11 http://pastebin.com/RB8C0x5f clicking on sugar to view the recipe.

**Comment by Daminer5** [comment]
I know that this is an old thread, but I'm having the same issue but this is different from other errors that I have seen (slightly), so it doesn't warrant to open a new thread. At least I don't think so. For about 90% of recipes that are compiled and reported by NEI, all of them cause the game to crash when anyone attempts to look up the recipe and usages. when it crashes it calls up:
java.lang.NullPointerException: Updating screen events
	at net.minecraftforge.fluids.FluidRegistry.getFluidID(FluidRegistry.java:199)
	at net.minecraftforge.fluids.FluidStack.getFluidID(FluidStack.java:121)
	at Reika.DragonAPI.Libraries.ReikaFluidHelper$FluidStackComparator.compare(ReikaFluidHelper.java:115)

Full Crash log:
https://pastebin.com/uLWNpPQA

Any suggestions for possibly fixing this?

**Comment by Shahelion** [comment]
If it is a different issue, open a new issue. Also, definitely don't post to one as old as this. It is almost 100% not going to be the same issue.

This one is almost two years old at this point.

**Comment by ReikaKalseki** [comment]
It is also a duplicate and related to extremely old versions of my mods.

**Comment by facepalmgamer** [comment]
i might just be an idiot like 100% but i keep getting this error and everything i search leads me hear or to a duplicate thread, but this issue has been send to be resolved so can someone please tell me either why i'm still crashing or if this is different then this long solved error. and yes all of my mods all updated according to the twitch launcher.
https://pastebin.com/CsP1fmxW
just in case it is a different error it just happens anytime i click on a recipe on nei

**Comment by ReikaKalseki** [comment]
You are using all the newest versions, so you likely have a mod doing something invalid to the fluid registry.

**Comment by facepalmgamer** [comment]
well damn not even gonna act like i know what that means but thanks for looking at it love the mods btw.
