### ISSUE TITLE
ElectriCraft Infinite power?

### ISSUE THREAD

**Issue by Demosthenexx** [ReikaKalseki/Reika_Mods_Issues#49]
I've got a stack of boring machines, each with an Azulant battery to supply it power. These batteries are hooked to my auroral battery at a distance, but still chunk loaded. I applied redstone power, and the batteries ran the bores until they ran out of power...

And they are still running.

Rotarycraft v6f, ElectriCraft v6a

![2015-04-27_13 12 59](https://cloud.githubusercontent.com/assets/12004642/7354394/db53458c-ece0-11e4-8c99-21f0c18c1708.png)
![2015-04-27_13 13 01](https://cloud.githubusercontent.com/assets/12004642/7354395/db5517a4-ece0-11e4-8a55-666c24a3e3b0.png)
![2015-04-27_13 13 03](https://cloud.githubusercontent.com/assets/12004642/7354397/db562824-ece0-11e4-990c-1c0938a68088.png)
![2015-04-27_13 12 56](https://cloud.githubusercontent.com/assets/12004642/7354396/db55c06e-ece0-11e4-8911-df8515cc74f3.png)

**Comment by ReikaKalseki** [comment]
It looks like the battery did not cause a network update when it finished draining. Can you test this?

**Comment by Demosthenexx** [comment]
How would I test this?

If I break the wire between the battery and the motor, and then replace it, it stops.

I thought it odd that WAILA and the transducer said they were empty, yet continuing.

**Comment by 1Matthias** [comment]
Try flipping the lever on the battery on and off again. That will narrow it down a lot.

**Comment by Demosthenexx** [comment]
I have EIGHT boring machines setup identically to this with individual batteries, they all continue to run when the battery runs down.

**Comment by Demosthenexx** [comment]
Right, flipping the lever on the battery to OFF stops the motor. Turning the lever back on and the motor runs though the battery is empty. It still shows 57.120 kW @ 255 rad.

**Comment by zemerick** [comment]
You said breaking and replacing a wire fixes the problem, correct? I think that's what you meant at least by:

"If I break the wire between the battery and the motor, and then replace it, it stops."

That's the kind of thing Reika was talking about "cause a network update". Basically, change the network itself, so the network needs to be recalculated.

It sounds like it's not updating when the battery reaches 0 power. The motor thinks it is still receiving power from the azulant battery, so it keeps running. The auroral battery doesn't recognize the azulant needs more power, so it doesn't lose any. Voila, power from nothing.

**Comment by Demosthenexx** [comment]
I agree, but there's a disconnected relay between the auroral battery and the azulant one...

**Comment by ReikaKalseki** [comment]
So far I have had no ability to reproduce the issue. The network below works exactly as intended.
![](http://i.imgur.com/8IGrV1v.png)
![](http://i.imgur.com/ptO9seh.png)

**Comment by Demosthenexx** [comment]
I have a much longer circuit, and it crosses a chunk boundary. Would a diagram help? Do distances matter?

**Comment by zemerick** [comment]
Everything you can think of would help. Too much information is better than not enough.

**Comment by Demosthenexx** [comment]
This may only occur after the chunk issue...

**Comment by ReikaKalseki** [comment]
As in the unloading issue?

**Comment by Demosthenexx** [comment]
Yep. I think perhaps this was cause by an incomplete update with the unloading issue. I've made a bunch of wiring changes with chunkloading always on and I haven't been able to reproduce it since.
