### ISSUE TITLE
DragonAPI and others update message on mac

### ISSUE THREAD

**Issue by nathanenns** [ReikaKalseki/Reika_Mods_Issues#490]
Yes I play on a mac.  With that out of the way, Since the new update was released, I have an invisible mouse bug, and I cannot seem to press any button that allows me to get rid of the message.  Nor does changing the 2 config lines regarding showing the message only to op/ssp or mod pack creator hide the message either.  

I am having issues playing because of this, is there a way to add a mappable button to get rid of it?  Also as I play on a server, the command has been blocked.  I am trying to get access to it, but so far nothing.

**Comment by TomeWyrm** [comment]
Update to v10b

**Comment by keybounce** [comment]
The chat log has a message. It says,
/checker <modname> to elimiante the message

And it works
/checker DragonAPI
/checker RotaryCraft
etc

**Comment by nathanenns** [comment]
I am in the process of trying to get the server admisitrator to give access to that command, since it has been accidentally blocked by them.  

Second, I cannot simply update to v10b, I am on a modpack I am not the creator of, and I did try to manually update the mods to v10b, but in doing so causes other crashes as there was an issue with another mod, which I think I might have to.

ALSO, I managed to hold control, and get my mouse to be visible by moving it off the screen, I don't play full screen, but when I went to click the message nothing happened.

It would be nice if these issues are actually addressed since not everyone can just update, or this or that.

**Comment by ReikaKalseki** [comment]
The issue you are experiencing was - ironically - fixed in v10.

**Comment by keybounce** [comment]
You might try starting up a single player game on that pack, and then using the /checker command there. I don't know if it would work, but it's worth a try

**Comment by ljfa-ag** [comment]
The issue is already addressed in v10, but obviously v9 still has it and will have it forever.
