### ISSUE TITLE
Reactorcraft server crash

### ISSUE THREAD

**Issue by VX7NORBA** [ReikaKalseki/Reika_Mods_Issues#493]
I have no idea why my server crashed. Client side works fine. Please help me with this.

Crash log.
http://pastebin.com/TrUqVqSs

**Comment by zemerick** [comment]
Redownload the mods. There was a hotfix for this yesterday without a version change. Let us know if it did work.

**Comment by VX7NORBA** [comment]
Crash again. Nothing changed in crash log.
And you have missing steam boiler top texture.
http://i64.tinypic.com/2cf2rk1.png

**Comment by Towsty** [comment]
Same issue here, retried the download last night and this afternoon, same crash. 

http://pastebin.com/pe3WQx8E

( @VX7NORBA You'll probably want to post the texture issue as a separate thread)

**Comment by Tencao** [comment]
Same issue here as well, worked perfectly on v9

http://pastebin.com/UzjMpYfC

Edit - Caused by: java.lang.RuntimeException: Attempted to load class Reika/RotaryCraft/API/BlockColorInterface for invalid side SERVER

**Comment by ReikaKalseki** [comment]
Again, redownload RC.

**Comment by Tencao** [comment]
I downloaded both today, about an hour ago from curse, so unless the hotfix is uploaded elsewhere, this issue is still present

**Comment by Tencao** [comment]
For a list of mods from you that I'm currently using, it's:

DragonAPI v10b
ElectriCraft v10b
RotaryCraft v10b
ReactorCraft v10b

**Comment by thepete89** [comment]
Also confirming that this issue still exists, altough RotaryCraft itself is fine now. Affected mods are ChromatiCraft, ExpandedRedstone, GeoStrata and ReactorCraft. They all try to access methods from BlockColorInterface on load/postload stage which is fine on client-side but gets interrupted on server-side.

All crash with java.lang.NoClassDefFoundError: Reika/RotaryCraft/API/BlockColorInterface (as it is not loaded for the server)
- at Reika.ChromatiCraft.ChromatiCraft.addDyeCompat(ChromatiCraft.java:582)
- at Reika.ExpandedRedstone.ExpandedRedstone.postload(ExpandedRedstone.java:119)
- at Reika.GeoStrata.GeoStrata.postload(GeoStrata.java:171)
- at Reika.ReactorCraft.ReactorCraft.postload(ReactorCraft.java:394)

seems they also need a server/client check in these places.

**Comment by zemerick** [comment]
Download the latest DragonAPI as well please.

If you get a crash with that, post the log, and I'll re-open.

**Comment by Tencao** [comment]
http://pastebin.com/HBiYPjCJ

I'm now getting this error. I've checked and double checked to see if this was this mod, and I can confirm this error is exclusive to the updated versions. v9 didn't have this.

**Comment by thepete89** [comment]
From my side I can confirm that DragonAPI 10c fixes the NoClassDefFoundError problem. Thank you :-)

**Comment by zemerick** [comment]
Tencao: I don't see any Reika code in there, but I do see Minetweaker. Might want to double check that side of things first.

thepete: Good to hear, thanks.

**Comment by Tencao** [comment]
Ok, so after removing it, the problem is at ChestGenHooks, but the only problem is, every mod that has some kind of ChestGenHook, crashes. I've tried removing lycanites mobs, and then it points to Railcraft, and since it's only showing this on the latest updates here, I'm certain it's something from one of your mods (v10+), as this crash doesn't happen on v9

http://pastebin.com/asqYJG7c
http://pastebin.com/37jJuPXH

**Comment by zemerick** [comment]
Try posting to the MCF, and maybe someone will spot something else.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=1260

Also, do you need forge 1566? 1558 is the recommended version, and the one that Reika specifically built against.

**Comment by Towsty** [comment]
The version of Agricraft he is using requires 1566 and there may be others, I know Gany's requires 66 as well.

**Comment by Towsty** [comment]
@Tencao this appears to be a conflict with kcauldron and (guessing) dragonapi. I had the same crash using the same version of KCauldron as you, just booted up with forge and the issues went away.

**Comment by Tencao** [comment]
Yeah, this wasn't an issue in v9, so I'm not sure whats changed in v10, but it's defo something related to the ChestGenHooks. I wouldn't mind if there was a way to disable DragonApis chestgenhook, but there isn't

**Comment by zemerick** [comment]
DragonAPIs is the way it is for a reason, so that would just break Reikas mods.

A lot was changed in V10, so it's not surprising something working with 9 broke with 10. He even changed which forge version he built against.

You can try taking this up with KCauldron, but I kinda doubt they will fix it. For the time being, you'll have to choose between Reikas mods and KCauldron.

**Comment by Towsty** [comment]
Ya, I would avoid the mentality of "it worked in v9" with his mods, a lot has changed on his side as well as the mods that dragonapi communicates with. Its also a beta version of an unoffical fork of kcauldron, I'm going to see if the guy who made the kcauldron build has any ideas.

**Comment by Tencao** [comment]
I understand alot has changed in his mods, I'm just speaking from a modpack makers point of view. Right now, I personally have more reason to stay on v9 as almost every modded server runs on cauldron, however, I would like to get the issue fix so everyone can benefit it. I'll wait to see how kcauldron respond to this, see if something can be done.

**Comment by ReikaKalseki** [comment]
Usually a ClassNotFound on ChestGenHooks, in my experience, is because the World class it references (and it apparently is one of the first classes to reference World, causing class init) being invalid. This is almost certainly an ASM conflict.

**Comment by Towsty** [comment]
@Tencao the guy that did the fork isn't .... well he's not the easiest person to work with, but he won't make any patches or anything for mod compatibility

**Comment by ReikaKalseki** [comment]
Then he has no business managing a project of the nature he does.

**Comment by Towsty** [comment]
Agreed. I know cauldron does a lot of messing with ASM hooks, its definitely something an issue that should be handled by cauldron people but that's not gonna happen any time soon it looks like. OHhhhhh well. I can survive without it

**Comment by spannerman79** [comment]
> the guy that did the fork isn't .... well he's not the easiest person to work with, but he won't make any patches or anything for mod compatibility

Pretty simple solution - the repo on github is now gone.

**Comment by LemADEC** [comment]
@Prototik any idea how to fix that?

**Comment by ReikaKalseki** [comment]
Do not restart an old and long-solved issue.

**Comment by webbster64** [comment]
got the same problem, so looks like i have to remove all of ReikaKalseki's mods considering im going choose thermos over DragonAPI RotaryCraft ReactorCraft ElectriCraft GeoStrata, i want to give my players a stable and fun server running at 20-19tps over a server with 5 extra mods thats running at 5tps
