### ISSUE TITLE
Bedrock Pipe not connecting to some RoC machines

### ISSUE THREAD

**Issue by zemerick** [ReikaKalseki/Reika_Mods_Issues#495]
So far I have:

Sprinkler
Liquid Spiller
Refrigeration Unit
Extractor
Solar Tower
Bucket Filler
Filling Station
Lava Smeltery
Liquid Distillery
Magnetostatic Engine
Ground Sprinkler
Steam Engine
Performance Engine
Valve Pipe
Suction Pipe
Bypass Pipe
Separation Pipe

**Comment by OmegaHaxors** [comment]
Bedrock Pipes will not connect to the various RoC pipes. The suction pipe, for instance.

**Comment by TomeWyrm** [comment]
I noticed this a while ago, but thought it was intended.

**Comment by zemerick** [comment]
I confirmed with Reika back before making the list: Bedrock pipe should connect to everything the standard liquid pipe does.

**Comment by ReikaKalseki** [comment]
Fixed.
