### ISSUE TITLE
Empty versions of fluid containers missing from Creative Inventory

### ISSUE THREAD

**Issue by zemerick** [ReikaKalseki/Reika_Mods_Issues#496]
Confirmed on more than 1 install, and with only DragonAPI, RoC and ReC installed. Forge 1558, J8_u45.

Includes at least the Reservoir and Fluid Compression Chamber.

NEI, when installed, does have the empty versions.

**Comment by ReikaKalseki** [comment]
Fixed quite some time ago.

**Comment by ReikaKalseki** [comment]
Fixed quite some time ago, though not in time for v10.
