### ISSUE TITLE
Diamond Shaft ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Jono-c** [ReikaKalseki/Reika_Mods_Issues#497]
Upgraded from 9.0b to 10.0b (with DRAGONAPI 10c) on my local test server and got the following error spamming the console

http://pastebin.com/PcLyZLQt

I cannot upload the whole log as there's about 180mb of that error repeated for various shafts.

Here's what happened immediately before these errors appeared in the console.
http://pastebin.com/pp4XEgZ5

Edit: Removing fastcraft from the server provided the following error

[10:50:21] [Server thread/INFO] [FML/]: DRAGONAPI: 
[10:50:21] [Server thread/ERROR] [FML/]: DRAGONAPI ERROR: Tile Entity Diamond Shaft @ DIM0: 1962, 191, -1055 [SERVER] is throwing class java.lang.ArrayIndexOutOfBoundsException on update: null
[10:50:21] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ArrayIndexOutOfBoundsException

**Comment by zemerick** [comment]
You most likely need to break and replace all shafts. Known issue with updating from 9 to 10.

Will close this as duplicate for now, if it's something else and replacing doesn't fix it, let me know and I will reopen it.

https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/476

**Comment by Jono-c** [comment]
Is there a way I can remove all of them with a command? I've got a few hundred out there in various locations, or do I have to remove them all by hand?

**Comment by zemerick** [comment]
Not that I'm aware of unfortunately.
