### ISSUE TITLE
Ender Forest does not color Birch leaves

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#499]
It even gets Greatwood leaves along with the Oak, but Birch are still green.
![2015-12-23_21 42 14](https://cloud.githubusercontent.com/assets/6917535/11990154/441a893c-a9be-11e5-8400-44f2819aab42.png)

**Comment by ReikaKalseki** [comment]
That is because birch and spruce leaf colors are hardcoded.
