### ISSUE TITLE
Display Screens don't always display

### ISSUE THREAD

**Issue by og1996** [ReikaKalseki/Reika_Mods_Issues#5]
Display screens don't always display information. Placing and replacing the display will occasionally fix it, but most of the time its just random where and when they will function. Walking through a display screen will also deactivate it. Sometimes, you can replace the display screen, but most the time it doesn't come back no matter what you do. Latest version (6f). UI says the displays are active. Logging in and out doesn't fix the problem.

**Comment by ReikaKalseki** [comment]
Did the coil discharge?

**Comment by strawberryshortbread** [comment]
Don't bother trying to get support, all reika is going to do is blame you then post you on his wall of shame where he shames people who disagree with him.

**Comment by madolinn** [comment]
I'd put your post on my wall of shame too because obviously you have enough to go around.

**Comment by og1996** [comment]
It would slowly discharge as though it was functioning, but the coil (and I tried different ones -- fully charged, part charged, diamond and regular.

**Comment by zemerick** [comment]
I've not been able to reproduce this yet. Do you have any more details you could provide?

What is the text? Is the holographic screen part showing, just without the text? Are you trying from both sides? ( Only 1 side displays the information. ) What other mods do you have installed? ( If it's a lot, you can just pastebin your log. Ask if you need help with this. )

Tested with CCC 35, NEI 90, DragonAPI 6f, RoC 6f. Appears to work as intended every time. Tried both in and out of creative mode. Simple signed book with title "A Test" and text "test", no special characters.

**Comment by og1996** [comment]
They exhibit the problem even without a book being bound -e.g., the ghost screen doesn't appear, but I've tried clicking on them with a book. Same book, some work some don't. The problem appears regardless of the orientation. I will try running it with a minimal set of mods to see if that clears it up, as I'm running a hefty modpack.

**Comment by zemerick** [comment]
Definitely sounds like a display issue then. Things like Optifine and Fastcraft are the first you should try removing.

The holographic grid background should always be visible with a coil in the display. Even without a book.

**Comment by og1996** [comment]
Appears to be a y-level issue, which is probably a graphics problem (not necessarily with RoC)...with the same modpack, I was able to lay dozens down anywhere at reasonable y-levels (up to about 150 -- the tallest mountain I could find). However, at a platform at y-level 240, they exhibit the bad behavior. Returning back down to y-level 64 and they function again.

**Comment by zemerick** [comment]
Yea, still appears to be something other than RoC. Just tested at 241 and 254. All 4 directions, still works fine.

Are you using optifine? If so which one?

Going to try adding fastcraft and see if anything changes on my end.

**Comment by og1996** [comment]
I do not have optifine installed - but I do have fastcraft. Will limit the modest and try again, see if I can narrow down the list. Also, did you try several different areas at high y-level? It doesn't happen on every square (I just flew from one cloud to the next -- sometimes it works, sometimes it doesn't. Can't figure out a rhyme or reason. However, one dead square will always be dead).

**Comment by zemerick** [comment]
See my edit above.

I did try a number of squares and heights originally, but not since. Can you provide coordinates ( the F3 ones please, in parenthesis so we get the same exact coordinate. )

**Comment by zemerick** [comment]
I can confirm a block in the screen area will completely disable the display, but the spring will continue going down.

I'll bet you have a mod, such as Railcraft, leaving behind invisible blocks. Other culprits are lights with extended range. ( Such as the Wrath Lamps. ) For Railcraft, there should be a config option to disable it.

**Comment by og1996** [comment]
I reduced my mod set down to all of reika's, plus NEI and fastcraft and I cannot replicate the issue, so it must be a mod interaction. I'm going to continue testing which mod causes the problem, then report back and close the issue.

**Comment by zemerick** [comment]
For Railcraft, in blocks.cfg you want:

    B:residual.heat=false

This will disable the tracking feature of the goggles, but it is notorious for causing problems like this. It leaves these invisible blocks all over as you walk. I'm quite confident this is the issue.

**Comment by og1996** [comment]
It's galacticraft arc lights causing the problem. What's odd is that they're affecting everything at their y-level, regardless of distance. I replicate the behavior consistently.

**Comment by zemerick** [comment]
<sigh> Another light causing problems. At least the issue has been found. You might want to contact the GC people about the odd behavior of it.

**Comment by 1Matthias** [comment]
Thank you for testing and tracking this issue down. It is nice to see someone taking initiative to do that.
