### ISSUE TITLE
Electricraft chunk loading sensitivity causing timeouts

### ISSUE THREAD

**Issue by Demosthenexx** [ReikaKalseki/Reika_Mods_Issues#50]
I wanted to open this as an issue because several times now our server has been crippled by Electricraft networks not being chunk loaded. 

Rotarycraft v6f, ElectriCraft v6a

Symptom: Create a moderately sized EC network (1 or two batteries, 50 silver insulated wire, relays, ALL OFF). Power on the network is not required. Walk out of player chunk loading radius (8+ chunks away) and server times out. TPS on console shows 0.3 TPS in overworld. jvisualvm shows all the time is being spent in EC's recursive network update and Minecraft's chunk file IO functions.

Chunk loading the chunks with EC wiring eliminates the problem.

I think this is a big issue because it can render your base unreachable or otherwise give the impression of a corrupted save game. If you leave and can't make it back in without timing out it's a big deal.

I had a conversation with Reika at one point that this was a known issue and caused by the unload chunk event causing a network update in EC (I'm paraphrasing).

**Comment by ljfa-ag** [comment]
Hm, I'm not sure if just keeping all those chunks loaded all the time is a good idea.

**Comment by ReikaKalseki** [comment]
I do not see a way around this.

**Comment by Demosthenexx** [comment]
None of the other mod cables have these kind of issues. Can we figure out why?

**Comment by Demosthenexx** [comment]
Wow, here's a new item. With the EC chunks being chunkloaded, walking out of their range causes a 2 second lag spike which does not repeat or reoccur when entering the area again.

**Comment by ReikaKalseki** [comment]
O_O

**Comment by ghost** [comment]
That face just says it all

**Comment by approject41** [comment]
Same thing is happening to me.

I have a HP turbine, some steam lines, some superconducting wires, and a handful of auroral batteries in a mountain base.

The game comes to a grinding slowdown when I leave the area. Chunk loading the area (5 chunk radius) does not help. I have removed all the batteries and broken the turbine - no change.

This also happened when I tried to dump radioactive waste in to the end. I had to delete the file.

The world is currently unplayable.

**Comment by ReikaKalseki** [comment]
If the problem persists after removing the ElC blocks, it is not ElC doing it.

**Comment by TomeWyrm** [comment]
He didn't say he broke the superconducting wires.

Incidentally, the performance issues are the largest reason I'm not using Electricraft. Luckily I can use World Rifts for long-distance transport of Shaft power... but them lag problems, they be serious

**Comment by ReikaKalseki** [comment]
v7 may fix this.

**Comment by ReikaKalseki** [comment]
Some new code I introduced may fix this further.

**Comment by Demosthenexx** [comment]
Would you consider changing the recursive network calculation to not go past a relay that's off? That'd allow for breaking up the network into smaller chunks, and cause a recalculate when the relay is turned on.

**Comment by ReikaKalseki** [comment]
I believe it already stops at disconnected relays.

**Comment by ReikaKalseki** [comment]
So, is this fixed?

**Comment by ReikaKalseki** [comment]
@Demosthenexx ?

**Comment by redelman** [comment]
It appears to be. At least, I'm not able to reproduce this anymore.
