### ISSUE TITLE
Crash on startup when I add Chromaticraft to my modpack

### ISSUE THREAD

**Issue by michelegargiulo** [ReikaKalseki/Reika_Mods_Issues#500]
When I add Chromaticraft v10b in my modpack it crashes on startup. Rotarycraft, Reactorcraft, Electricraft and DragonAPI v10b are installed as well. I can't figure out what is causing this crash.. Removing Chromaticraft makes minecraft load successfully.

Crash: http://pastebin.com/TYrxwFis

Thanks in advance

**Comment by zemerick** [comment]
You need to either use the java argument -XX:+UseG1GC or set the "Forge G1GC to prevent crashes - Disabling this disables some content" to false in the CC config. Note, the second option disables the chroma dimension, as you would crash anyways if you tried going there without G1GC.

Also note that you might need to remove some of the other GC related arguments if you decide to use the G1GC arg.

**Comment by ljfa-ag** [comment]
A NullPointerException? Don't tell me that the forced crash when the wrong garbage collector is used is that one. That seems to be unrelated.

**Comment by zemerick** [comment]
Yea. The forced crash would have a bit about what is going on, and that you need to add it. Specifically:

"You are running Java 8, and need to use the JVM argument "-XX:+UseG1GC" or you will suffer memory allocation-related crashes."

I think Smokey was trying to set the CC option to false, and typoed something. He does not have the argument, and is on J8. However, the code is tripping up when checking what the config is set to.

**Comment by ReikaKalseki** [comment]
Redownload CC.
