### ISSUE TITLE
Galacticraft OxygenHooks crash

### ISSUE THREAD

**Issue by xKillerbees** [ReikaKalseki/Reika_Mods_Issues#501]
http://pastebin.com/d5KKm45R
Didn't start until I updated to V10, now it crashes the server when players login. 
forge-1.7.10-10.13.4.1558-1.7.10-universal.jar

**Comment by zemerick** [comment]
Galacticraft problem unfortunately.

**Comment by xKillerbees** [comment]
Guess I'll have to downgrade Reika mods then as it'll probably be awhile for fixes on the other end. Sad that it was working fine before.

**Comment by ljfa-ag** [comment]
Already reported: #484
