### ISSUE TITLE
Crash when looking up recipies from rotarycraft

### ISSUE THREAD

**Issue by Nanabell** [ReikaKalseki/Reika_Mods_Issues#503]
first of all i know that a newer version got released just 1 day ago or so but i tried updating to that version and we crashed aswell (also when i tried to look up recipes, but i sadly lost the crash report) 

crash report: http://pastebin.com/82ixHMPE

maybe as a side info why we cant update, i and a firend of mine are playing on ftb infinity evoled and there seems to be a problem for them to upgrade forestry to 4.x but your newest version cant "handle" or work with the old version we use
hope you can help

**Comment by Nanabell** [comment]
~~EDIT
Well we got the newest version of rotarycraft working though now it crashes when you try to open the handbook or it crashes Randomly when looking up rotarycraft recpipes
e.g:
http://pastebin.com/Y0fZfNch
or
http://pastebin.com/ybDHDZ5m
or
http://pastebin.com/uenQY4Rx  <-- lookup for extractor recipes
O.o

**Comment by TomeWyrm** [comment]
First try forge 1558 not 1614

Second I think that's a known issue. One of the other collaborators will have to confirm, I'm not familiar with the NEI crashes we've been getting.

**Comment by zemerick** [comment]
Yes, it's a duplicate:

https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/488
