### ISSUE TITLE
ExpandedRedstone: make blocks use direct input from comparator

### ISSUE THREAD

**Issue by the-vindex** [ReikaKalseki/Reika_Mods_Issues#505]
![2015-12-25_18 25 07](https://cloud.githubusercontent.com/assets/5522688/12003980/bab9b094-ab36-11e5-84df-d5b9f61c37f9.png)
If I do this setup, signal scaler won't read input from comparator. Vanilla repeater does read this input this way, so I would expect consistent behavior.

Overall I've found following blocks fail to read input:
- Scaler
- Arithmetic Operator

**Comment by ReikaKalseki** [comment]
This is a known issue that is eluding fix. Redstone in vanilla is a massive hack built upon smaller hacks.

**Comment by TomeWyrm** [comment]
He really isn't kidding by the way. I've seen SO many bugs related to redstone in mods interacting with other mods and giving the strangest results simply because practically nobody understands the various idiosyncracies of Minecraft redstone.
