### ISSUE TITLE
[CC] Pylon HUD effect persists

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#506]
Even if the pylon was destroyed by another worldgen structure (in the linked gif, an AE2 meteor) or if a pylon is placed in creative and broken, the HUD effect remains, even after exiting and re-entering the game.

https://gyazo.com/0aa5076c8960d4652773a1c55b0aa65f

**Comment by ljfa-ag** [comment]
This is a known issue (#368) and it can't be easily fixed.
