### ISSUE TITLE
[CC] Nether Crystals

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#507]
Night Vision (Light Blue I think?) in the Nether still gives Night Vision, instead of a negative effect.
![2015-12-25_23 57 17](https://cloud.githubusercontent.com/assets/6917535/12005612/67856bf2-ab63-11e5-8bf2-39c03622825f.png)

**Comment by ReikaKalseki** [comment]
Night vision in the nether _is_ detrimental.
