### ISSUE TITLE
Chromaticraft Item collecter does not collect

### ISSUE THREAD

**Issue by Looma-mc** [ReikaKalseki/Reika_Mods_Issues#51]
The item collector from chromaticraft refuses to pick up items. Lumen energy is supplied via relays. the elemental farmer on the same relay line works just fine. Am I missing other colours than those two?
The collector is just above the crops, so it should work.
![2015-04-29_20 41 44](https://cloud.githubusercontent.com/assets/12052854/7398614/666f8c40-eeb0-11e4-87e4-ed9c43d43e76.png)

**Comment by ReikaKalseki** [comment]
Do you tell it what items to pick up?

**Comment by Looma-mc** [comment]
How can i do that? i noticed the GUI with the inventory area. i put canola seeds in both/just one area, but nothing happens. Do i need another item?

Edit: i think the bottom part of the gui is the filter, but even if i put the seeds inside, nothing happens.

**Comment by ReikaKalseki** [comment]
Fixed.
