### ISSUE TITLE
Electricraft: Power spikes?

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#514]
hi,
This might be an undocumented feature, but I can't really explain to my self why it is happening.
So I have been testing some setups in creative to figure out how to use electricraft as more than a glorified shaft bus. I have sofar come to the conclusion that the only wait to limit power without turning massive amounts of it into heat is by chaining batteries. 
First of all the tests were done with superconducting wire, which should be loose less.
First of all I found that if I take a full Lustrous Battery(max 16.777 MJ) and empty it into an Azulant Battery (max 268.435 MJ) I only end up with 16.776 MJ. I assume this from some kind of rounding?

Next I have tried this:
http://ibin.co/2RV3LOsWhqml
This an azulant battery charging a redstone Battery that empties into another azulant battery. This turned out to be massive waste power. I assume the power gets lost when a power "packet" from the first azulant battery hits the redstone battery, while the battery is unable to hold all of it.

I thought I could prevent this by only pulsing the redstone battery, so it would never get fully charged. For this I am using redstone comparator, a not gate and a relay.
http://ibin.co/2RV513Zh34lW
While this seems to work 90% of the time, in that it keeps the redstone battery at around 40% charge, occasionally the battery gets hit by a power spike that instantly charges it to 100%.
I have no idea why this is happening. It feels like it is more likely to happen when I am no actively watching it, but that might very well be confirmation bias.
At the end of the day, due to the power spikes, when charging the second azulant battery 2.938MF of the 16.776MJ are lost.

**Comment by ReikaKalseki** [comment]
Battery outputs are fixed.

> how to use electricraft as more than a glorified shaft bus

It _is_.
