### ISSUE TITLE
Crash in Grinder GUI

### ISSUE THREAD

**Issue by BakermanLP** [ReikaKalseki/Reika_Mods_Issues#515]
I opened the grinder gui and clicked on the recipes in the gui:

"Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!" The full client log is here:
https://paste.ee/p/zQAts

The crash report is here:
https://paste.ee/p/FfN5s

The used versions of this modpack can be found here ("Reika mods" are the newest):
https://github.com/BakermanLP/ProjectRETv8/blob/master/Versions.md

**Comment by ReikaKalseki** [comment]
#488
