### ISSUE TITLE
Metallurgy Ores added by AOBD arent working in Rotarycraft extractor

### ISSUE THREAD

**Issue by BakermanLP** [ReikaKalseki/Reika_Mods_Issues#516]
Hello,

this is kind of a cross post to:
ganymedes01/Another-One-Bites-the-Dust#72
ganymedes01/Another-One-Bites-the-Dust#114
BakermanLP/ProjectRETv8#25

This is something special I think. The ores of Metallurgy are added to the grinder and to the extractor. I don't really know, if Rotarycraft or AOBD adds these ores. The recipes are shown in NEI, but I can't put them in the extractor. 

When I disable the integration of one ore in the aobd.cfg ( Adamantine { ... B:RotaryCraft=false ... } ) then the recipes are gone. So I think, that this is added by aobd. 

Further testing has given me the following additional informations:
- ores of Metallurgy have a oreDict entry (ex. ore:oreMithril )
- ores of Metallurgy that are in a "common" oreDict group like tin are working
- ores added by AOBD to Rotarycraft only can be processed in the extractor, NOT in the grinder

Could the last point be the issue?

Is there any way to help you debug this issue further?

All "Reika mods" are the latest versions, also AOBD is the latest version. All other mods are listed here:
https://github.com/BakermanLP/ProjectRETv8/blob/master/Versions.md

**Comment by ReikaKalseki** [comment]
I do not natively handle Metallurgy ores in my processing systems.
