### ISSUE TITLE
Steam Boiler missing texture

### ISSUE THREAD

**Issue by csdivad** [ReikaKalseki/Reika_Mods_Issues#518]
Steam Boiler from ReactorCraft is missing its top and bottom texture. (V10d)

**Comment by sam2864** [comment]
The carbon dioxide heat exchanger also,
http://puu.sh/m5umI/e73943b0a5.jpg

**Comment by Zedrimar** [comment]
Confirmed
![2015-12-29_22 47 23](https://cloud.githubusercontent.com/assets/8153290/12047793/5bb9a178-ae86-11e5-8ab1-23079e7d0003.png)
![2015-12-29_22 47 21](https://cloud.githubusercontent.com/assets/8153290/12047795/5e85e7ae-ae86-11e5-9e34-64a7c2d639e4.png)

**Comment by Haggle1996** [comment]
Haggle1996/RevolutionPack#166

**Comment by cosmicdan** [comment]
Similar issue with Carbon Dioxide Heat Exchanger

**Comment by Zedrimar** [comment]
@cosmicdan confirmed: 

![2016-01-09_15 11 21](https://cloud.githubusercontent.com/assets/8153290/12218917/578765f8-b6e3-11e5-8039-ab98672998b3.png)
![2016-01-09_15 11 27](https://cloud.githubusercontent.com/assets/8153290/12218918/5851b3f8-b6e3-11e5-95d6-c6fa5be2c8dc.png)

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by Zedrimar** [comment]
just curious, what was it that caused the top and bottom textures to disappear?

**Comment by ReikaKalseki** [comment]
Indexing errors.

**Comment by Zedrimar** [comment]
ah

**Comment by Archangel8913** [comment]
How do you fix this issue?

**Comment by leonbaronick** [comment]
@ReikaKalseki 
The bug is still present in the latest version. Is there a way to fix it?

**Comment by Builderb0y** [comment]
It's fixed in V11. Be patient.

**Comment by Archangel8913** [comment]
@Builderb0y
Any projection on a release date for that?

**Comment by Builderb0y** [comment]
No. Be patient.

**Comment by TomeWyrm** [comment]
> Any projection on a release date for that?

Sometime between now and December of this year
