### ISSUE TITLE
[Suggestion] diamond manufacturing related

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#521]
what about the use of charcoal in the compressor? after all charcoal is nearly 100% carbon which is what diamonds are made of! :P

**Comment by ReikaKalseki** [comment]
This I will do.

**Comment by Zedrimar** [comment]
hooray! XD

**Comment by TomeWyrm** [comment]
Best part is, it's a more pure form of carbon than coal (which is what every other mod that has coal>diamonds uses)

**Comment by Zedrimar** [comment]
indeed

**Comment by ReikaKalseki** [comment]
Done, with a 50% output boost. Now you can use RC to literally farm diamonds.

**Comment by OmegaHaxors** [comment]
I love you so much for suggesting this.
