### ISSUE TITLE
ChromatiCraft Server crash (Endless Mobs progress trigger)

### ISSUE THREAD

**Issue by DracoScythem** [ReikaKalseki/Reika_Mods_Issues#526]
Whenever any Player on the server destroys a mob-spawner for his first time the server crashes.
(The Progress is successfully completed after the server restarts ; The spawner destruction isn't saved ; After a player has the Endless Mobs progress it does no longer happen)
Crashlog: http://pastebin.com/71aPaVBG
(Dedicated Server running on a Debian root server (jessie) with java 8u66 ; JVM Arguments: -Xms6G -Xmx12G -XX:+UseG1GC )

**Comment by ReikaKalseki** [comment]
For now, turn off the new config.

**Comment by SonarBeserk** [comment]
How does one turn off the new config?

**Comment by ReikaKalseki** [comment]
> How does one turn off the new config?

...

**Comment by SonarBeserk** [comment]
Are you suggesting to revert versions or wait? Surely you cant just revert the config itself, doesn't usually work that way.

**Comment by ljfa-ag** [comment]
I guess he meant turning off the "Spawn Mobs When Harvesting Spawners By Hand" option

**Comment by SonarBeserk** [comment]
Well the thing is that the issue is bigger than just this feature. Ive had the server crash nowhere near spawners. So that is not really a fix.

**Comment by ReikaKalseki** [comment]
> I guess he meant turning off the "Spawn Mobs When Harvesting Spawners By Hand" option

No, wrong mod and wrong config.

**Comment by Haggle1996** [comment]
I hate asking, because it makes me feel like a moron, but I can't figure out what option you mean by looking at any of the linked issues...can we get the right config option? As in:

B:"Reika, what's the text we're supposed to search for here"=false

**Comment by zemerick** [comment]
I think it's:
B:"Notify other players of progress gains"=true

Busy with family atm, so can't check more thoroughly or verify with Reika atm.

**Comment by Aivech** [comment]
> ChromatiCraft: Added achievement-style server notification, with config
> _v10d changelogs_

That would be it then, it is new and it is a config...

**Comment by Haggle1996** [comment]
Thanks!
