### ISSUE TITLE
[question] Autocrafting Unit request mode

### ISSUE THREAD

**Issue by shadoxxhd** [ReikaKalseki/Reika_Mods_Issues#529]
how does it work? i connected an autocrafting unit in request mode with some recipes in it to my ME system, but the recipes don't show up under craftable items. 
how does the ACU/ae2 interaction work? does it work with logistic pipes, too? is there any detailed documentation on this block except from the short handbook entry?

**Comment by zemerick** [comment]
This is the issue tracker. It's for reporting bugs, not asking questions.

Please head over to the MCF post:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=1267
and ask your questions there. If you find the item is bugged, then post the details of the specific bug here.

**Comment by shadoxxhd** [comment]
i don't know for sure whether it's a bug or my own stupidity, although i'd guess it's a bug. I'm pretty certain that i tried every possible build, but as I don't know which one is supposed to work I can't say _what_ is bugged
