### ISSUE TITLE
Server crash with Railcraft

### ISSUE THREAD

**Issue by cbcercas** [ReikaKalseki/Reika_Mods_Issues#53]
I get a crash with Railcraft
here the crash report https://clitxt.com/t/n7v-1430496575.txt

Railcraft bug repport [#601](https://github.com/CovertJaguar/Railcraft/issues/601)

**Comment by liach** [comment]
It seems [here](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Magic/Network/CrystalNetworker.java#L133) it is.

**Comment by ljfa-ag** [comment]
It's the infamous hidden block. Try disabling it in the Railcraft config.

**Comment by cbcercas** [comment]
I can't find _hidden_ in railcraft config

**Comment by liach** [comment]
Then try to find "heat".

**Comment by cbcercas** [comment]
thanks
