### ISSUE TITLE
[Suggestion] Electricraft: make battery output rate configurable (like industrial coils)

### ISSUE THREAD

**Issue by pjolin** [ReikaKalseki/Reika_Mods_Issues#531]
I noticed that battery output is fixed (pulling 1 amp or 4096 amps out of an Auroral Battery drains it at the same rate) but that prevents using big batteries as "stick them there and forget about them for a month" energy sources for operations that require little power. 

A great improvement would be if they gained a a configuration interface similar to the industrial coil (enter desired output amperage, and possibly voltage, up to the battery's maximum output power), maybe requiring an upgrade of some sort to offer that level of control.

**Comment by shadoxxhd** [comment]
you can charge up an industrial coil, turn the battery off and set the coil to ouput. repeat when coil empty. if you require constant power output for some reason, use 2 coils and switch between them.

**Comment by Reignofmagic** [comment]
The main problem with that is the industrial coils can only hold up to 720 mw. Which is filled extremely quickly once you get to late game rotarycraft, and early game reactorcraft (lp turbines output 800~mw with the flywheel).

**Comment by pjolin** [comment]
I get that an industrial coil can perform that function already - and the bedrock one stores 240 TJ, so it's certainly great for many scenarios. In fact my current setup has spare electric power just feeding a line of induction motors charging up coils. 

A bedrock coil (240 TJ) can output 16.7 MW for roughly 15 time longer than an auroral battery (281 TJ) because of the fixed output. The graphene battery outputs 16.7 MW too, but 1.1 TJ capacity is obviously incomparable to the 240 TJ of the coil. 

What I'm suggesting is simply a way to have similar control on the batteries. Electricraft is meant as a way to ease power transport and splitting, but having no control on the battery output tips the balance immensely in the coil's favor for low-power situations because low-output batteries have proportionally low storage capacity. 

This reduces battery usefulness to very high power scenario (i.e. the Auroral's battery 268 MW output sure comes in handy).

**Comment by shadoxxhd** [comment]
as soon as you have bedrock dust available, you can make a 210TJ (if i remember correctly). the main limitation is that a single bedrock industrial coil can only output up to 16MW (4096x4096), but you can go higher by using multiple coils.
EDIT: seems like I didn't hit refresh before posting

**Comment by ljfa-ag** [comment]
Well I guess if batteries had something like this they would be pretty much obsoleting coils and be basically like Redstone Flux.
One possible way of working around this is using a second battery where you send all the excess power to.

**Comment by TomeWyrm** [comment]
There are a few methods that are commonly used to "work around" the battery limits. Reika explicitly wants to not invalidate the use case of the industrial coils. My suggestion would be to understand how electricraft transfers power and use that to design a battery-runoff system, use batteries as outputs, utilize a switching coil system, or another similar mechanic.
