### ISSUE TITLE
Server Crash when trap in ocean temple triggered

### ISSUE THREAD

**Issue by jstoneburner** [ReikaKalseki/Reika_Mods_Issues#535]
Was in the first floor of the ocean temple in the point where the two hallways meet. There was an explosion and the server crashed.

Running  ChromatiCraft 10d in the Space Astronomy 1.3.4 modpack.

Full server crash report attached:
http://pastebin.com/D97c5p8t

**Comment by zemerick** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/520
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/526
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/527
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/528

Known issue. For now, disable the progress reporting config.
