### ISSUE TITLE
[CC] missing GUI texture

### ISSUE THREAD

**Issue by shadoxxhd** [ReikaKalseki/Reika_Mods_Issues#536]
http://imgur.com/a/oHa0V
using v9b
the casting table is useable, but it's annoying when you always have to try out where the slots are.
EDIT: found this in my log file: http://pastebin.com/qrVXL6PZ

**Comment by zemerick** [comment]
Current version is v10d.

**Comment by shadoxxhd** [comment]
as many other users, i am not able to upgrade to v10d because of the forestry 4 requirement (other mods I am using conflict with it). apart from that, this doesn't seem like an issue that'd require lots of effort to fix (in the worst case, the missing textures could be supplied via resource pack)

**Comment by ReikaKalseki** [comment]
> as many other users, i am not able to upgrade to v10d because of the forestry 4 requirement 

That does not add any validity to any reports.

**Comment by TomeWyrm** [comment]
> ... the forestry 4 requirement (other mods I am using conflict with it)

Give me a list, as far as I can see every mod dependent upon forestry has updated. Reika was the last author I am aware of to support 4.

**Comment by shadoxxhd** [comment]
binnies mods, for example (extrabees, extratrees, ...)

**Comment by TomeWyrm** [comment]
Oh, yeah. Those mods that never ever update. There's a reason that when I get a bit of free time I'm replacing the "bees" portion of that via Gendustry.
