### ISSUE TITLE
Odd bug between Chromaticraft and Natural Absorption

### ISSUE THREAD

**Issue by aurumvorax** [ReikaKalseki/Reika_Mods_Issues#539]
When I select the Elemental Manipulator, I lose all of my absorption hearts added by natural absorption.  Now, this is a common visual glitch when crossing dimensions, the hearts just don't show up until you do something to recalculate health(use another book of absorption, take damage, etc).  Except that in this case, it's not visual, those hearts are actually gone.  This is triggered simply by scrolling past the Elemental Manipulator in the hotbar.

**Comment by ReikaKalseki** [comment]
This is when you hold the manipulator? That does not trigger any special code aside from some rendering overlays.

**Comment by aurumvorax** [comment]
Yeah, this is why I thought it was a visual thing at first, but it does actually remove the absorption hearts.  I've removed NA from my pack for now, as I can't find a bugtracker for it.

**Comment by ReikaKalseki** [comment]
This has to be on NA's side, since holding the manipulator triggers nothing.
