### ISSUE TITLE
Chromaticraft Aspect jar not recognized by infusion altar

### ISSUE THREAD

**Issue by Looma-mc** [ReikaKalseki/Reika_Mods_Issues#54]
I charged the aspect jar with multiple aspects and tried to use it in an infusion of thaumcraft. the altar does not pull any aspects from it. It only uses normal jars.

latest Chromaticraft.
thaumcraft 4.2.3.5 + few addons

**Comment by ljfa-ag** [comment]
Can confirm that.

Also, not sure if intended but there seems to be no way to retrieve essentia from them, golems, tubes and phials don't work.
Furthermore, the jar does connect to tubes but it doesn't seem like it accepts essentia from them.

**Comment by ReikaKalseki** [comment]
Almost all of the TC jar and infusion handling is hardcoded to his own jars. Not fixable by me.

**Comment by ljfa-ag** [comment]
Which means the jars are useless since you apparently can't pull essentia from them?

**Comment by ReikaKalseki** [comment]
Until he implements some sort of compatibility with his own API, yes...

**Comment by Looma-mc** [comment]
Maybe Thaumic energistics has the answer. Don't know how they do it, but i think you can use their interface for the infusion. Haven't used it for a long time. They could have the answer on how to implement the interaction to the infusion table.

https://github.com/Nividica/ThaumicEnergistics

**Comment by ljfa-ag** [comment]
Yup, looks like you just have to implement IAspectSource rather than just IAspectContainer.

**Comment by ReikaKalseki** [comment]
Done.
