### ISSUE TITLE
RotaryCraft Manual on v10D won't open.

### ISSUE THREAD

**Issue by TsumiHokiro** [ReikaKalseki/Reika_Mods_Issues#540]
Ever since I have updated to Rotarycraft v10d I have been unable to open the RotaryCraft Manual. I also have ElectriCraft and ReactorCraft installed (all are the latest to date versions [Electri: v10b, Reactor: v10d] and so is DragonAPI: v10d).
In case it is relevant, in past versions of Rotarycraft I was getting a "crash-ish" problem with the manual when it would render wood recipes. Depending on the wood type it would use to render the recipe in the manual it would cause a crash in the chat-log and the manual recipes would all go blank and wouldn't reappear until I re-opened the game client (closing and opening worlds would not reset this).
The crash-log is located in the following link: https://gist.github.com/TsumiHokiro/92c20d7a11e95fb3af40

**Comment by ReikaKalseki** [comment]
#534, #522, #515, #488
