### ISSUE TITLE
Two compatibility issues with cauldron (Server Side) IMPORTANT!

### ISSUE THREAD

**Issue by MJRLegends** [ReikaKalseki/Reika_Mods_Issues#541]
Right im using KCauldron-1.7.10-1614.UNOFFICIAL and Im using a local server setup with just KCauldron and Dragon API..

The first crash im getting is http://pastebin.com/hX97tNjt and this was first reported to me from the servers owners that host my mod pack on there server network. The crash log I have provided was from my mod pack, so it shows loads of other mods were loaded but I was able to reproduce the issue with just KCauldron and Dragon API so its not a problem coming from other mods.

When trying to fix the issue I came across this crash http://pastebin.com/Us165EXe with just using the same KCauldron and Dragon API as the first crash, so then I thought lets remove Dragon API and see if it crashes again as i thought it was a KCauldron issue but after removing Dragon API it didn't crash any more.

Just to put this out there dont say it works with forge and KCauldron isn't supported because nearly all popular modded servers hosted by server networks companies use KCauldron, meaning its a big deal for this mod if it doesn't work.... 

Also I would just like to point out this only started happening with the latest version of Dragon API (v10d) and it was working all fine with V9b

**Comment by ljfa-ag** [comment]
The first one was reported in #493 and the second one in #523.
Well it's actually not trivial to guarantee it working with KCauldron because the mods were made on the basis of vanilla Minecraft with Forge's patches. KCauldron adds more patches on top of that, causing incompatibilities. It would be a lot of effort to code with two different versions in mind, and KCauldron is not the only one of its kind. You would need to have special treatment for Spigot, Sponge and whatever else there is too.

**Comment by ReikaKalseki** [comment]
On top of that, it is impossible to build against anything but Forge.

**Comment by MJRLegends** [comment]
Yeah but the changes made since V9b have broken it working with cauldron meaning it was working for ages before v10+

**Comment by MJRLegends** [comment]
@ReikaKalseki when will a update be out to fix the first crash listed above because these are causing major problems within my mod pack for players

**Comment by MJRLegends** [comment]
@ReikaKalseki Also would removing dragoon API from a world cause issues/corruption?

**Comment by ReikaKalseki** [comment]
When Cauldron decides not to play "take it or leave it".

**Comment by TomeWyrm** [comment]
No, this is not Reika's problem. It is KCauldron's

**Comment by MJRLegends** [comment]
@TomeWyrm So why did it work fine with the same version of KCauldron with v9 version of the mods but now with v10 it doesn't. 

@ReikaKalseki And this puts me in a really crappy place because i need my mod pack to be working on servers but the latest versions are causing the issue for me but i cant downgrade the mod versions because they are not available. And there's nothing i can do about it :/ 

So what do i do?

**Comment by TomeWyrm** [comment]
Because KCauldron breaks forge. Any compatability is on KCauldron's end. The reason v9 worked is because the KCauldron devs MADE it work.

As for your second issue, don't use Bukkit, or it's 5 billion derivatives. Problem Solved.

**Comment by MJRLegends** [comment]
@TomeWyrm I cant choose what server owners use, they just complain to me if KCauldron doesn't work and im expected to fix it, which i cant do. Its stressful from a mod pack developers side because it breaks my mod pack and causes people to use older updates, which makes them complain to me. Also with the older versions not being available for all the v10 versions i cant test other versions to find one that works in the mean time. If  i downgrade to v9's i get all old bugs that i reported...

**Comment by TomeWyrm** [comment]
Then warn them it's not bukkit compatible. If they complain, that's THEIR problem. If you don't provide support for KCauldron, they use it at their own risk. If they continue to moan at you, block them. Nobody should be using bukkit or derivatives anymore, they're illegal to distribute.

**Comment by MJRLegends** [comment]
Yeah but then thats just makes a loads of servers close and i lose out due to mods not working with kCauldron. Thats like taking away half my players for my mod pack. Look at the end of the day i need a solution here even if its a temporary one and very quickly so i can update my mod pack. Saying to server owners they cant use KCauldron and to shut up and i dont care isn't a solution because im trying to grow my mod pack here not lose players due to problems.

**Comment by MJRLegends** [comment]
@TomeWyrm The only solution i can see here would be to use the v9 mods or if @ReikaKalseki can provide me with all the other v10 versions then i might be able to use them...

**Comment by TomeWyrm** [comment]
Your point? It's not an issue that you, or we, can solve. It's THEIR issue for using KCauldron in the first place. Post this as an issue on the KCauldron issue tracker, and see if they feel like fixing it, otherwise the server owners only choices if they want your pack is to use a forge server, or put up with the update notifications from reikas mods and lose support.

It's not the best situation for you to be in, but it's what the realities of the situation require. I'm closing this now because there's literally nothing we can do. It's FULLY on cauldron's end.

**Comment by zemerick** [comment]
For the record: All of the v10s don't work with kCauldron, and plenty of previous versions didn't either. This is a problem that has cropped up from time to time.

The answer really is to just take what Tome has said, and relay that to anyone using the modpack. If enough people start complaining to kCauldron, they might work a little more on compatibility.
