### ISSUE TITLE
[CC] Server freezes when Mineral Extractor is placed

### ISSUE THREAD

**Issue by Kataiser9** [ReikaKalseki/Reika_Mods_Issues#543]
No crash or error messages; the server just stops responding (console remains open but commands have no effect, everyone times out after a brief period).

Tested on Forge 1558 and 1566 with fresh worlds and fairly minimal load orders - your mods, NEI, Waila, Opis, and dependencies. All your mods are on the latest versions, of course.

I wish I had more info to give you, but that's all I have at the moment.

EDIT: If it helps, I ran a similar server in V8 or V9 (can't recall which) on the same computer. The mineral extractor caused no issues then. Did another test on V10 to see if anything would happen if I left the server running for some time after the freeze; I was able to get one chat message to go through with a delay of about two minutes.

**Comment by lossycrypt** [comment]
Can you tell if the server freezes because of high memory load (swapping to disk) or high cpu load?

**Comment by Kataiser9** [comment]
Lossycrypt - just tested again with a resource monitor running. Server CPU load went from ~11% to ~25% when the block was placed and things stopped responding. The CPU's quad-core - I'm not at all an expert but I assume that means the server is maxing out CPU-wise?

Memory use didn't seem to change significantly.

**Comment by ReikaKalseki** [comment]
Fixed. I screwed up badly.

**Comment by EyeDeck** [comment]
For the curious, here is what was happening... oops.
https://gfycat.com/SeparateJointBuckeyebutterfly
