### ISSUE TITLE
Void Cells not Correctly Rendering items

### ISSUE THREAD

**Issue by Reignofmagic** [ReikaKalseki/Reika_Mods_Issues#545]
As you can see from the screenshot, the items do not correctly render over the void cells. The big blocks work most of the time, but the smaller items don't show up.

![2016-01-05_21 43 19](https://cloud.githubusercontent.com/assets/10967885/12134515/84362e0e-b3f5-11e5-8e6c-1c4ed3e3cc6b.png)

**Comment by ReikaKalseki** [comment]
Fixed.
