### ISSUE TITLE
Woodcutter does not replant Slimy Saplings

### ISSUE THREAD

**Issue by amesgen** [ReikaKalseki/Reika_Mods_Issues#546]
The Woodcutter, even with the Infinity Enchantment, does not seem to replant Saplings from the Slimy Trees from Tinkers' Construct, even though it cuts them down as expected.
Tested with newest version of RotaryCraft

**Comment by ljfa-ag** [comment]
Probably intended, the v10 changelog says:

> Woodcutter can now cut slime trees, but gets sticky and jams; needs to be kept clean with sprinklers

So try using a sprinkler near the woodcutter.

**Comment by amesgen** [comment]
Oh thanks.

**Comment by ReikaKalseki** [comment]
Does the woodcutter turn green?

**Comment by amesgen** [comment]
Sorry for the late response (European time zone): No, it does not turn green (even after harvesting the tree), and a sprinkler above the woodcutter does not seem to change the replanting behavoir.

**Comment by ReikaKalseki** [comment]
In which case it is not getting jammed. Did the tree drop any saplings? Does the woodcutter have Fortune or Infinity?

**Comment by amesgen** [comment]
The Woodcutter has Infinity I and Efficiency V. It places the saplings (the tree dropped at least one sapling as far as i watched) in the chest below.

**Comment by ReikaKalseki** [comment]
Including slime saplings?

**Comment by amesgen** [comment]
Yes, it places the slime saplings as well as the slime balls in the chest.

**Comment by ReikaKalseki** [comment]
I have an idea what might be wrong.
