### ISSUE TITLE
[CC] Discovering a new Pylon color with the Manipulator makes the screen go black

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#549]
I can still see the HUD (health, hunger, hotbar, etc) but everything else is black except a very small band at the bottom of the screen (maybe a pixel or two high, the width of the screen). Seems to last roughly 15-20 seconds. If I'm looking directly at the Pylon, there are rings of gray shading to black instead of just solid black.

This is not caused by TC Warp as I first thought.

![2016-01-07_02 23 01](https://cloud.githubusercontent.com/assets/6917535/12168213/a5dd62f2-b4e5-11e5-8305-39fa8fa29f5f.png)

https://i.gyazo.com/ebb5526e6a496cc0717a28cd6992ae0f.mp4

Also the second time (in the GIF), it didn't say in the chat that I found a new color which I thought was odd...

**Comment by ReikaKalseki** [comment]
Does it only happen when you are discovering a new color? Does it happen without TC installed?

**Comment by Shahelion** [comment]
Not always,  and yes.

**Comment by Shahelion** [comment]
By not always I mean not every time. But only when finding new colors.

**Comment by ghost** [comment]
I had this happen too, happened after I casted a ChC item... not sure what though

**Comment by ReikaKalseki** [comment]
Does it happen when you learn other things (ie trigger the top-right popup)?

**Comment by Shahelion** [comment]
I have only had this happen so far when discovering a new color, and only with some of them (roughly half).

**Comment by ReikaKalseki** [comment]
wtf...

**Comment by ReikaKalseki** [comment]
wtf...

**Comment by Shahelion** [comment]
Ok, after some further testing (giving myself knowledge fragments in creative mode, for example) occasionally a fragment would make the grey-ring version of the black screen appear, but for less than a second. About 1/4 of the fragments did this.

**Comment by ReikaKalseki** [comment]
...

**Comment by Shahelion** [comment]
More specifically:
Notes that give a black screen: Pylon Compass, Aura Cleaner, Other Recipes, Crafting with Runes, World Authoring, A Volatile World, Item Casting Stand
Notes that do not: Tinted Crystal Lens, Crystal Glass, Leaf, Warp Glass, Crystal Lamp, Crystal Enchanting

Some of these, the black screen lasted a few seconds.

Will continue trying more things...

In addition: immediately after discovering a new color, the black screen goes away if I am holding a Pylon Compass. Holding anything else, or an empty hand, makes it return. If I am holding the compass when the grey rings would normally appear, instead I see the overlay briefly as it should be, dark grey rings at the edge of the screen but not covering it.

AHA seems to be connected to the box in the upper right corner that says what color you just discovered.

https://i.gyazo.com/9ced42bb05f5a63824fea4eb50209f7a.mp4

Also it seems the grey-ringed version is the "wearing off" period of whatever it is, like how night vision flashes.

**Comment by ReikaKalseki** [comment]
wtf...

**Comment by Shahelion** [comment]
As you can see in the upper-right corner, the box is just disappearing. It also makes a lot of other parts of various GUIs darker, but that happens at other random times as well so idk if it's related...

![2016-01-08_17 02 21](https://cloud.githubusercontent.com/assets/6917535/12213263/0e2dc366-b62a-11e5-859f-18f2215debb7.png)

**Comment by Shahelion** [comment]
To add more to this: I have two worlds, my main one and my testing superflat one. The black screen when discovering colors only happened when I hadn't found that color yet in EITHER world. I found three or four colors in my main world and it happened with all of them. I discovered all 16 in my test world later, and it only happened with the truly new ones. Going back to my main world a bit later and discovering some more colors, it didn't happen at all. I had completely restarted the client between these three occasions.

**Comment by ReikaKalseki** [comment]
I am completely at a loss...

**Comment by Shahelion** [comment]
Since making a new world, this has not happened again (yet). I have so far discovered all 16 colors, and have found 15+ fragments, with related progress (total progress is more than in both previous worlds now). No mods have been changed.

**Comment by ReikaKalseki** [comment]
I just checked, and that wavy vignette you see on the above image is indeed a Thaumcraft Warp effect.

**Comment by Shahelion** [comment]
Either the CC notifications are using the same effect, then, or I got a warp effect at the exact same time, every time it happened. Or the CC notifs are CAUSING the warp effect, which I find unlikely.

**Comment by ReikaKalseki** [comment]
A shader conflict?

**Comment by Shahelion** [comment]
I have no shader mods if that's what you mean.

**Comment by ljfa-ag** [comment]
Well it might be that Thaumcraft is using shaders that are causing conflicts. Some warp effects, like bluriness, are definitely using them.

**Comment by TomeWyrm** [comment]
Try turning off the shaders in thaumcraft.cfg
B:shaders=true
to
B:shaders=false

It should be right about in the middle of the file (was line 102 for me)

**Comment by Shahelion** [comment]
Apparently this was an issue as far back as a year ago, it starts happening as soon as you have your first TC Warp effect. Doesn't matter which one, but it screws up the rendering in that world from that point on.

**Comment by ReikaKalseki** [comment]
TC warp shaders are still not working properly with even basic overlays.

**Comment by Shahelion** [comment]
There doesn't even have to be any warp effect happening at the time but it still breaks.

**Comment by TomeWyrm** [comment]
That very well may be, but does having the shaders off fix the issue?

Because TC shaders have been a problem all over the place for many people. Even ForgeCraft had a bunch of people with problems.

**Comment by Shahelion** [comment]
So after updating to the latest mod versions, AND disabling Thaumcraft shaders, this is still happening.

**Comment by Aivech** [comment]
I had the same problem in v10d - hard to test since it ONLY happens when you have a warp effect and gain progression simultaneously. It is then permanent for the remainder of the world (as far as I know) - relogging hasn't fixed it.

It happened in a creative world after I used the /chromaprog command and had gotten a bunch of warp from the creative thaumonomicon.

**Comment by ReikaKalseki** [comment]
I wonder if there is an issue in TC where the shader option is not fully functional?

**Comment by Shahelion** [comment]
It seems that it does not happen with certain notifications. For example, the "Forested Realm" for going to the Twilight Forest doesn't cause the issue, yet every time I discover a new color, it does, without fail. Maybe it doesn't affect progression notifications, only content unlocks?

**Comment by ReikaKalseki** [comment]
Their renderers are all identical.

**Comment by Shahelion** [comment]
And with the addition of V11b, this appears to have finally been resolved! Yay!

**Comment by Aivech** [comment]
Ooh, I'll have to upgrade...

**Comment by Shahelion** [comment]
Finally, I can collect a new color without having to stand still on Peaceful, afraid to move lol. I almost fell into a Hungry Node once...

**Comment by Aivech** [comment]
meh

MatterOverdrive black holes are worse, the range is bigger

**Comment by Shahelion** [comment]
Looks like I spoke too soon...it no longer happens when discovering colors, but now happens when finding structures and ores.

**Comment by ReikaKalseki** [comment]
Those use the same render code as everything else.
