### ISSUE TITLE
Crash with RotaryCraft, latest build: duplicate Entity ID registration

### ISSUE THREAD

**Issue by walkerjonny** [ReikaKalseki/Reika_Mods_Issues#55]
I'm getting the following crash with the latest build of RotaryCraft.
It complains something about duplicate Entity ID registrations but I have no idea how to fix it.
Hopefully you can help me out there.

_Moderator edit (CoolSquid):_
Please use Pastebin or Gist for future crash reports and/or logs.
http://pastebin.com/mhL17e0z

**Comment by Duckfan77** [comment]
[Pastebin](http://pastebin.com) or [Gist](http://gist.github.com) please for the crash report, this makes it easier to view, and shortens the issue thread so it is easier to read. As for the issue, at a first look through I haven't seen anything, I will look more later. Also, try to reproduce the problem without Optifine, as Forestry suggests at the end, I doubt that is the issue, but would be smart to test what the log recommends just in case.

**Comment by walkerjonny** [comment]
OK, thank you about Pastebin. I'll keep that in mind the next time.
I tried it without Optifine but just got the same crash again.
Must have another reason.

**Comment by Duckfan77** [comment]
It seems that the issue is that 2 mods are registering on the same entity id. I can't see anything that would point to which mod it is in the logs, but maybe someone else can. To figure out what mod causes the issue manually, you can remove mods and test again to narrow it down to which mod is causing the conflict.

**Comment by madolinn** [comment]
```
61 : int id = EntityRegistry.findGlobalUniqueEntityId();
...
102 : EntityRegistry.registerGlobalEntityID(EntityFlakShot.class, "Flak Shot", id);
```

What. If Entity 31 is not available, why did it just return the next available one was 31..

**Comment by Duckfan77** [comment]
Missed that. That's confusing. @OP, specifically try removing whatever mod adds "Flack Shot" and see if that fixes the issue, as that seems to be the register conflict.

**Comment by walkerjonny** [comment]
So it took a while but I figured out the other mod that tries to register Entity ID 31:
It is IC2 Combo Armors. Since the mod thread at the IC2 forum seems to be abandoned now and only a few links to the version 1.14.5.05 for MC 1.7.10 exist I decided to drop it.

**Comment by ljfa-ag** [comment]
So it looks like it's a problem with IC2 Combo Armors.
