### ISSUE TITLE
Crash when right-clicking on RotaryCraft machine with Enviromine torch in hand.

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#552]
Cross posting this to the related trackers.

When a player, on a server, right-clicks on a RotaryCraft machine with a torch in-hand, they receive this crash: https://gist.github.com/mamykin/a201ba803a938fbdfd2f

I believe the issue is caused when Enviromine is dynamically replacing the vanilla torch with a custom Enviromine torch (which burns out, burns other things, etc), during the onPlayerInteract event. A similar issue exists with Inventory Tweaks when items are sorted on the client then updated on the server.

Haggle1996/RevolutionPack#172

**Comment by ReikaKalseki** [comment]
This crash has nothing to do with the torch. This crash is because the TileEntity at that location is missing, despite the block persisting.
