### ISSUE TITLE
Crash when breaking Crystal Tank

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#556]
Breaking the crystal tank block, not the controller. The tank was empty at the time (I just built a new tank then broke a few tank blocks to try to reshape it).

http://hastebin.com/emedevezuh.coffee

**Comment by Shahelion** [comment]
Going back into the world, it seems that two controllers were touching the same tank, that is probably what caused this.

**Comment by ReikaKalseki** [comment]
Fixed.
