### ISSUE TITLE
Rotarycraft Dyamo outdated?

### ISSUE THREAD

**Issue by joshiejack** [ReikaKalseki/Reika_Mods_Issues#56]
It seems your dyamo is still only providing power to IEnergyHandlers, when in newer RF api, it should send power to machines that are IEnergyReceiver also. (Unless your repo is not up to date).  (IEnergyHandler extends receiver)

https://github.com/ReikaKalseki/RotaryCraft/blob/master/ModInterface/TileEntityDynamo.java#L78

**Comment by ReikaKalseki** [comment]
Fixed.
