### ISSUE TITLE
Console error messages

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#560]
hi,
First of all, nothing of this prevents me from playing - but I wish modded minecraft would throw less errors/warning when you start it.

overview:
Forge would like mods to have a name and version number, currently Rotarycraft,Electricraft,Reactorcraft,VoidMonster and Chromaticraft all have a name, but DragonAPI does not. ( https://github.com/ReikaKalseki/DragonAPI/blob/b5593f348e77f8026e3203d17d5ddfbaa46683f5/DragonAPIInit.java#L189 )
Also none of your mods have a version number as part of the annotation, while again not strictly required it would help with early detecting an outdated mod and provide better feedback to the user.

The next error happens because "blacklistTile" is called with null as the second argument, it would probably be a good idea to add torcherino to DragonAPI.ModList.

After that there is a couple of errors, because no mod added electrum - that probably shouldn't count as an error in the log.
Then again, a bit like with torcherino dragonapi tries to blacklist your blocks for "framez" and fails to do so. I am not sure why your code breaks, but something isn't working right.
And finally most of your donators are listed without their uuid, which means all your mods try to register their special renderer and fail doing so. This pretty predictable and probably also shouldn't be considered an error.
snippets from the log:
http://pastebin.com/raw/nvfw4fcc

**Comment by ReikaKalseki** [comment]
I removed the error status from some. No others will change.
