### ISSUE TITLE
Sorting machine works without power

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#563]
hi,
Booth the book and the angular transducer state that the sorting machine requires at least 1kW.
But https://github.com/ReikaKalseki/RotaryCraft/blob/32ae6d07a3ae3d3bb106180a78a7b062095318a5/TileEntities/TileEntitySorting.java#L108 always returns at least 1, so there is no difference between providing 1kW and providing no power at all.

Also it would be nice if we could directly attach a pneumatic item pump to the sorter.

**Comment by ReikaKalseki** [comment]
Fixed.

> Also it would be nice if we could directly attach a pneumatic item pump to the sorter.

Not possible. Neither are inventories. And you can use multiple pumps to sort, if somewhat clumsily.
