### ISSUE TITLE
Rotarycraft/Reactorcraft/Electricraft  NPE with Matter Overdrive

### ISSUE THREAD

**Issue by viper2g1** [ReikaKalseki/Reika_Mods_Issues#566]
This is a paraphrase of the error I submitted to the dev of Matter Overdrive. They say the fault lies with DragonAPI and how it handles IMC calls. 

I tried to update to the latest version of Matter Overdrive  released (0.4.1) and also install Electricraft. I immediately got errors and narrowed it down to the new version of Matter Overdrive. With Electricraft installed and the server running fine using Matter Overdrive (0.4.0) I try to install the 0.4.1 version and I get errors. I tried with and without CoFHLib since I saw it's dependency was removed.

I use Reactorcraft, Rotarycraft, Electricraft and a few others that all work nicely together. I only get errors when using the latest version of Matter Overdrive. I created an issue in their github tracker but it was closed saying the fault lies in DragonAPI.  

A copy of the NPE and their response is here in their Github tracker:

https://github.com/simeonradivoev/MatterOverdrive/issues/382

**Comment by viper2g1** [comment]
I asked the dev on Minecraft Forums and he stated that the problem is with the API implantation, it needs to be repaired on your side he says. I'm not sure if you already know this or not but trying to help. 

Here is where he mentioned this:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2398952-wip-beta-1-7-10-matter-overdrive-replication?page=17#c331

**Comment by ReikaKalseki** [comment]
As per my reply on the other thread, I am still waiting on a response from them.
