### ISSUE TITLE
Dragon Api Server crash

### ISSUE THREAD

**Issue by Saereth** [ReikaKalseki/Reika_Mods_Issues#567]
We are getting random server crashes maybe once a day, with no one even online as this is a test server. Looks like possible a DragonAPI/Forestry issue?

Here is the crashlog
http://pastebin.com/vGAd9Zua

Relevant info:
Forge 1558
DragonAPI v10d
Forestry 1.7.10-4.2.2.50

**Comment by Turmfalke2** [comment]
I feel like the implementation of getFlags for the ItemComperator is questionable. https://github.com/ReikaKalseki/DragonAPI/blob/master/Libraries/Registry/ReikaItemHelper.java#L414
It depends on hard coded values and is based around assumptions that can't be guaranteed to be true.
Like a stack of 101 with damage value of 0 has the same flags as a stack of 1 with a damage value of 1. Yes vanilla minecraft has no stacks larger than 64, but rotarycraft machines are quite able to generate larger stacks.

**Comment by ljfa-ag** [comment]
Using lexicographical comparison would probably work better and may be faster

**Comment by ReikaKalseki** [comment]
#564, #550, #544, #540, #534, #522, #515, #488
