### ISSUE TITLE
Casting Table is throwing class java.lang.NullPointerException on update

### ISSUE THREAD

**Issue by midorlo** [ReikaKalseki/Reika_Mods_Issues#568]
Summary:

The last 2 items I tried to craft using the casting table caused a npe, printed to chat and forgelog. The game is still playable and the item was crafted. Wether this affected any progression or not is unknown to me. 

Setup/Modpack:

Current stables of Win10x64, Java8,Chromaticraft, DragonAPI; Modpack is Interminatus (Compiled by me, http://www.curse.com/modpacks/minecraft/233642-interminatus). Game Enviroment is SMP on a dedicated server.

Changes made to Chromaticraft/DragonAPI:

```
B:"Reload Handbook Data on Open"=false
B:"Notify other players of progress gains"=false #caused disconnects on SMP
```

Repeating the bug:

Have an elemental manupulator with sufficient energy. Place required crafting ingredients for a Crystal Brewery into a Casting Table. Right-click it with your manipulator. The chat returns the following error:

http://pastebin.com/raw/xyjpvGSX

**Comment by ReikaKalseki** [comment]
Break and replace the table. Aside from that, I know of no way to debug this seeing as I do not see it myself.

**Comment by midorlo** [comment]
I am recreating the issue using only Forge, DragonAPI and Chromaticraft:

http://imgur.com/a/QnhJJ

**Comment by ReikaKalseki** [comment]
Go to #538.

**Comment by Turmfalke2** [comment]
breaking and replacing table does nothing for me, @ReikaKalseki have you tried it your self with java8?

**Comment by ReikaKalseki** [comment]
I am not willing to install Java 8, as it will break my J7 installation, which I have programs that require it.
