### ISSUE TITLE
Crafting Magnetite Gems to Lodestones causes serious lag

### ISSUE THREAD

**Issue by umbralOptimatum** [ReikaKalseki/Reika_Mods_Issues#57]
I haven't tested with the other products of smelting mod flakes, but crafting magnetite gems into lodestones causes lag proportional to the amount being crafted.

**Comment by ljfa-ag** [comment]
Can you provide more details on that?
So you say it gets stuck for a while when you craft them? How long does it take, e.g. for crafting a full stack?
I've noticed brief lag spikes upon crafting large as well (not sure if with Reika's mods though), but they were so short that you almost didn't notice them.

**Comment by umbralOptimatum** [comment]
The game freezes for about half a second when I craft a full stack. When I craft many stacks at once with the use of the ME Crafting Terminal, it takes much longer for the game to update my inventory and the log has messages that the server is running several seconds (usually about five) behind and is skipping ticks. I've never had this issue when crafting anything else.

**Comment by ReikaKalseki** [comment]
Do you have any unificators (eg GT) enabled? Also, I know from experience that Minechem can do this, but it does it will all crafting.

**Comment by cypren** [comment]
The lengthy delay when crafting stacks of items at the ME Crafting Terminal is a problem with AE2. You'll notice it when attempting to craft any recipe that can produce a stack of 64 items one at a time. Recipes that produce more items in a single stack go much faster; I would speculate that AE2 is doing a full command-update-response cycle between the client and server for each crafting operation, as this problem seems to be exacerbated by latency between client and server.

**Comment by umbralOptimatum** [comment]
I do have Minechem installed but I only have the issue with crafting the various items produced from flakes into mod items. It's pretty laggy even without the ME Crafting Terminal.

**Comment by ReikaKalseki** [comment]
This answers none of the questions I asked.

**Comment by umbralOptimatum** [comment]
I'm not sure what you mean by unificators enabled, but I don't have GT installed.

**Comment by ReikaKalseki** [comment]
GT - and some other mods - have mechanisms to auto-unify (with the Ore Dictionary) items upon crafting or similar. Try in an environment with only my mods.

**Comment by ReikaKalseki** [comment]
So...

**Comment by umbralOptimatum** [comment]
The issue with that is my computer is fast enough to not have any noticeable lag in any form in an environment with just your mods.

**Comment by 1Matthias** [comment]
I might be able to test it today with my junkheap.

**Comment by ReikaKalseki** [comment]
> The issue with that is my computer is fast enough to not have any noticeable lag in any form in an environment with just your mods. 

To me that means the problem went away.

**Comment by umbralOptimatum** [comment]
Fair enough.

**Comment by ReikaKalseki** [comment]
So....is that you saying you cannot reproduce this?
