### ISSUE TITLE
Progress is not unlocking

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#571]
I may just be misunderstanding how this works, but some of the progress is not unlocking/activating when it seems like it should.

Casting Table: I made the table, placed it, still hasn't lit up in the Lexicon yet.

The Evil Realm: This IS the Nether, right? I've been there several times, rebuilt and relit the portal a few times as well.

Magical Trees: Isn't this for the Rainbow Trees?

**Comment by ReikaKalseki** [comment]
It is fairly clear you are both misunderstanding what several progress flags are, as well as how the progression system works (for example prerequisites). Also, I know for a fact it is working fine since I have 16 people on my server all progressing normally.
