### ISSUE TITLE
Cannot use Manipulator on Pylons in a new world

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#573]
In my previous world it works just fine. However, in a new world, I am unable to interact with the pylons at all with the Manipulator. No collection, no discoveries, nothing. Not even when standing close enough to be killed by it.

**Comment by ReikaKalseki** [comment]
Lack of progress again.

**Comment by Shahelion** [comment]
I got EXTREMELY close (within 2 blocks of the orb) to the Pylon, holding right click with the manipulator the whole time, and suddenly got 4 progress notifications in the corner of the screen all at once. (Pylons, Galazio, Energy Internalization, Energy Beacons).

**Comment by ReikaKalseki** [comment]
Yes, that is to be expected.
