### ISSUE TITLE
Pylons kill twice

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#574]
Two death messages in the chat, and two graves (OpenBlocks) at the spot where I died.

**Comment by ReikaKalseki** [comment]
I have noticed this as well. What do the two graves contain?

**Comment by Shahelion** [comment]
The first grave contains the items I had, as normal, plus a player head. The second contains nothing except an additional player head (I forget which mod adds these). Presumably, both graves would each have items that are created at death.

**Comment by Shahelion** [comment]
At least the entire inventory isn't being duplicated or anything. If I didn't have whatever mod adds player heads on death, the second grave w̶o̶u̶l̶d̶ ̶b̶e̶ ̶e̶m̶p̶t̶y̶ wouldn't even generate.

**Comment by ReikaKalseki** [comment]
Can you try reproducing this with only CC? The pylon attacks twice if it needs to forcibly setHealth(); that may be the error. I also put in a possible fix.
