### ISSUE TITLE
Reactorcraft Neutron absorber melting problem

### ISSUE THREAD

**Issue by tvk1372** [ReikaKalseki/Reika_Mods_Issues#576]
Hello!
I have a big problem with the fusion reactor,beause the neutron absorber melt's to lava when It gets to 1-1,2K celsius.
And I dont know how to cool it down,I use this type of absorber and boiler setup with 4 injectors.
![1280x720-zgz](https://cloud.githubusercontent.com/assets/8401485/12332600/a7a66042-baef-11e5-968e-49e567a11407.jpg)
I tried to put more boilers next to it but I get the same temp's,I used liquid nitrogen on the bottom but it doesent connect to the absorber wih the liquid pipe.
I use the latest version of the mod.
Please help me how to cool down the absorber's to not to melt but work optimal.

**Comment by zemerick** [comment]
More boilers is the correct solution. Make sure you aren't running out of water.

If you're only going to run 4 HPTs, you could probably get away with just 1 injector, maybe 2. 1 preheater is enough for about 50 injectors also, so you can cut that down.

Also, the issue tracker is for issues/bugs/etc. For questions or suggestions you should use the MCF thread: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=1281
