### ISSUE TITLE
crafting sawdust in the grinder

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#577]
hi,
Somehow I can only make sawdust from oak and acacia logs, for birch and spruce I have to craft it into stairs first.

DragonAPI 1.7.10 V10d.jar
RotaryCraft 1.7.10 V10d.jar
forge-1.7.10-10.13.3.1403-1.7.10-universal.jar

**Comment by ReikaKalseki** [comment]
Fixed.
