### ISSUE TITLE
Tried to give progress 'CASTING' to null player???

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#578]
hi,
I would like to reopen #538.  The original bug reporter assumed that it was just related to the chest next to his casting table, the actual issue has nothing todo with the chest or the items crafted, but with the casting progress.
error  log: http://pastebin.com/sKxHhKnm
What I did to trigger this bug:
I crafted a casting table and placed the items required for crafting crystalline stone in the table. I noticed that I wasn't able to craft it due to missing the required fragment. After I came back from hunting for borrows with the missing fragment, I right clicked the table with the elemental manipulator without opening the gui first. I heard the sound for successful crafting and the error appear in my chat/console.

DragonAPI 1.7.10 V10d.jar
ChromatiCraft 1.7.10 V10d.jar
forge-1.7.10-10.13.3.1403-1.7.10-universal.jar

E: It appears to happen every time I crafting something in the casting table.

**Comment by ReikaKalseki** [comment]
Do not deliberately make a duplicate report asking to reopen the original.
