### ISSUE TITLE
Crash on Mod Update

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [ReikaKalseki/Reika_Mods_Issues#579]
I updated the following mods
DragonAPI v9b
Reactorcraft v9b
Rotarycraft v9b
Electricraft v9b
UsefulTNT v9a
to the current versions (v10d) today.  Then I loaded up the world ive been working in and had graphical issues (missing textures) on the Sodium Heater and Heat Exchanger.  I didnt think anything of it (not the first time I had a missing texture).  Also, Thermal Expansion Resonant Retrievers could no longer draw hot molten sodium from the heaters to my Fluid Interface, so I changed to Resonant Servos.  Its not the first time an update has changed mechanics on me, so I just went with it.

I then closed the world and attempted to re-open it later and got this crash, Repeatedly:

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 1/14/16 8:30 PM
Description: Unexpected error

java.lang.StackOverflowError: Unexpected error
    at java.lang.Class.newInstance(Unknown Source)
    at Reika.ReactorCraft.Registry.ReactorTiles.createTEFromIDAndMetadata(ReactorTiles.java:161)
    at Reika.ReactorCraft.Blocks.BlockReactorTile.createTileEntity(BlockReactorTile.java:114)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
    at net.minecraft.world.World.func_147438_o(World.java:2540)
    at Reika.DragonAPI.Base.BlockTEBase.onNeighborChange(BlockTEBase.java:51)
    at net.minecraft.world.World.func_147453_f(World.java:3875)
    at net.minecraft.world.World.func_147455_a(World.java:2603)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851)
    at net.minecraft.world.World.func_147438_o(World.java:2540)
        [more]
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851)
    at net.minecraft.world.World.func_147438_o(World.java:2540)
    at Reika.DragonAPI.Base.BlockTEBase.onNeighborChange(BlockTEBase.java:51)
    at net.minecraft.world.World.func_147453_f(World.java:3875)
    at net.minecraft.world.World.func_147455_a(World.java:2603)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.lang.Class.newInstance(Unknown Source)
    at Reika.ReactorCraft.Registry.ReactorTiles.createTEFromIDAndMetadata(ReactorTiles.java:161)
    at Reika.ReactorCraft.Blocks.BlockReactorTile.createTileEntity(BlockReactorTile.java:114)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
    at net.minecraft.world.World.func_147438_o(World.java:2540)
    at Reika.DragonAPI.Base.BlockTEBase.onNeighborChange(BlockTEBase.java:51)
    at net.minecraft.world.World.func_147453_f(World.java:3875)
    at net.minecraft.world.World.func_147455_a(World.java:2603)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851)
    at net.minecraft.world.World.func_147438_o(World.java:2540)
    at Reika.DragonAPI.Base.BlockTEBase.onNeighborChange(BlockTEBase.java:51)
    at net.minecraft.world.World.func_147453_f(World.java:3875)
    at net.minecraft.world.World.func_147455_a(World.java:2603)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851)
    at net.minecraft.world.World.func_147438_o(World.java:2540)
    at Reika.DragonAPI.Base.BlockTEBase.onNeighborChange(BlockTEBase.java:51)
    [more]
    at net.minecraft.world.World.func_147453_f(World.java:3875)
    at net.minecraft.world.World.func_147455_a(World.java:2603)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851)
    at net.minecraft.world.World.func_147438_o(World.java:2540)
    at Reika.DragonAPI.Base.BlockTEBase.onNeighborChange(BlockTEBase.java:51)
    at net.minecraft.world.World.func_147453_f(World.java:3875)
    at net.minecraft.world.World.func_147455_a(World.java:2603)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Machiavelli'/352, l='MpServer', x=60.43, y=78.62, z=28.98]]
    Chunk stats: MultiplayerChunkCache: 9, 14
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 2577591 game time, 2577591 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 1 total; [EntityClientPlayerMP['Machiavelli'/352, l='MpServer', x=60.43, y=78.62, z=28.98]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Any thoughts?

**Comment by ReikaKalseki** [comment]
Try to reproduce the crash, because if there was a crash bug in this code, it should have been found years ago.

**Comment by MachiavelliSeraphim** [comment]
I crashed it 2 more times trying to load the world after I reported this with the same error.  Then I loaded up a few other worlds to see if they had problems.  They loaded fine.  Then I tried one more time, and it loaded up no problems.  I still have no textures on the Sodium Heater or Heat Exchanger, and the Retriever still cant pull from a sodium heater, but the world is loading.

**Comment by MachiavelliSeraphim** [comment]
Just got the crash again, or at least a very similar one.  
I teleported from the Nether to my home location.

http://paste.ee/p/zvBBP

**Comment by TomeWyrm** [comment]
PLEASE for the love of Notch!
USE A PASTE SERVICE

Do NOT break our screens with mile long reports!

**Comment by MachiavelliSeraphim** [comment]
Sorry, not used to having to ask for help with crashes....

**Comment by TomeWyrm** [comment]
We all learn sometime.

In the future, if it's more than say two dozen lines, and is code, a crash log, or configs? Use a paste service like pastebin or paste.ee

**Comment by ReikaKalseki** [comment]
Try recreating this in an entirely different world. Not dimension, but a new save.

**Comment by MachiavelliSeraphim** [comment]
Might be easier said than done, ive got about 2 months development in ths world, and more mod interactions than i can count...

Any suggestions on what that particular bit of code does, so i can try and rebuild those portions of the world?

I.E. rotarycraft and thermal expansion, or rotarycraft and ender chests... that sort of thing.

Thanks.

**Comment by MachiavelliSeraphim** [comment]
And are there broken textures in v10d?  Or is it possible that i have a bad jar file?

**Comment by zemerick** [comment]
Missing textures on a couple of reactorcraft items is a known issue, that is fixed for the next update. CO2 heat exchanger and the boiler are 2 examples.

It's a reactorcraft tile entity that's having the problem, so look for that kind of stuff. Specifically it's about a neighbor changing. I don't know that specific function, but I think it might be when the block is changed to something else. I would look for anything involving pistons next to ReC stuff, frame type stuff, maybe lights which place invisible lights to affect a larger area, anything you can think of around ReC TEs that are changing. Pics might help as well, as someone might see something that is a bit dangerous to do.

**Comment by MachiavelliSeraphim** [comment]
Thats a good puzzle then, the only ReC things in that area are 2 HPTs, 6 Heat exchanger banks with steam lines, 1 RF turbine (the big one), and 2 isotope centrifuges with uranium processors....

I dont use pistons or anything of that sort normally.  I havent changed anything to do with lighting in the ReC area either...

And i know the railcraft hidden block is disabled.

The wierd part is that everything was rock solid in v9...

Ill try to get screenshots tomorrow.

**Comment by TomeWyrm** [comment]
You might also use MCEdit to remove everything but the HPT and surroundings see if it's still reproduceable, and then send us that (significantly smaller) world file.

**Comment by MachiavelliSeraphim** [comment]
Its in a AE pocket dimension, mcedit causes horrific corruption with those.  

The world file is fairly small as is, i can purge the overworld and nether clean out.  Itd be 20 chunks in 2 dimensions total size.

I tend to build small.

I can pack it up, along with the mod set and configs, if that would be helpful...

**Comment by ReikaKalseki** [comment]
Again, try reproducing it in a new world.

**Comment by MachiavelliSeraphim** [comment]
I will try, might take a few weeks though... there is a lot packed in 8 chunks....  full power station, 3 ae systems, reactor fueling control system... :(

**Comment by ReikaKalseki** [comment]
Only replicate ReactorCraft tiles. Ignore everything else. And do it in creative.

**Comment by MachiavelliSeraphim** [comment]
Okey.  Ill try and let you know.

**Comment by MachiavelliSeraphim** [comment]
Got a stranger crash now....
http://paste.ee/p/kIgFX

Rebuilt as much as I could remember without being able to see the world again, left the world, logged back in and get this now on loadup.  I also removed all mods that werent Reikas, AE2 or OPIS related.

**Comment by MachiavelliSeraphim** [comment]
Got this on the second attempt to load the world.
http://paste.ee/p/PFi1n

Im completely lost now, it doesn't make any sense to me....

**Comment by MachiavelliSeraphim** [comment]
Crashes only occur if I am PHYSICALLY in the area.  The whole space is chunk loaded with no issues, everything functions normally when I am not there.

I reset my character to the overworld and teleported to every other dimensions without issues.
Once i jumped to dimension 2, i got another different crash log....

http://paste.ee/p/i8hr1

It has to be something that is only calculated when a player is present, such as lighting....

**Comment by zemerick** [comment]
The actual issue seems to be the same on all of them, it's just erroring out in a different piece of code each time:

```
at net.minecraft.world.World.func_147438_o(World.java:2540)
at Reika.DragonAPI.Base.BlockTEBase.onNeighborChange(BlockTEBase.java:51)
at net.minecraft.world.World.func_147453_f(World.java:3875)
at net.minecraft.world.World.func_147455_a(World.java:2603)
at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851)
```

is the part that is looping, so it's something about onNeighborChange. It might be for example 2 TEs that are updating each other back and forth until finally they overflow.

Are you able to get a picture of what you have built before it crashes? If not, can you describe it?

**Comment by MachiavelliSeraphim** [comment]
I pulled up an old backup and loaded up the old mod versions to get some screenshots and noticed something i hadnt thought of, Are Neutron Absorbers Tile Entities?

I have a few dozen as decorative frames around my command block teleporters.....

![2016-01-17_13 47 10](https://cloud.githubusercontent.com/assets/10451525/12379087/07fb8656-bd21-11e5-81ad-86eafa46131d.png)

![2016-01-17_13 48 28](https://cloud.githubusercontent.com/assets/10451525/12379097/0ef50fd6-bd21-11e5-97e4-550bddf872e5.png)

![2016-01-17_13 48 18](https://cloud.githubusercontent.com/assets/10451525/12379100/13df9048-bd21-11e5-9ba7-0dd8f012f79e.png)

**Comment by MachiavelliSeraphim** [comment]
thats pretty much ALL of the Reactorcraft components in that dimension, everything else is in Dim 3 and its ROCK SOLID.... never had an issue...

**Comment by zemerick** [comment]
Yes, absorbers are TEs. Anything that does something is.

So, it's possible something something about those are updating eachother. Try removing them and placing a normal block around them. ( Such as iron blocks. )

**Comment by MachiavelliSeraphim** [comment]
Will do, ive gotta pack up for work and will get to that sometime tonight.

Sorry this caused so much trouble so far....
Thanks for the help.

**Comment by zemerick** [comment]
Finding problems is a good thing:)

**Comment by ReikaKalseki** [comment]
Absorbers can be safely placed next to one another, or the Fusion reactor would crash. And yes, they are TileEntities, meaning that while building with them should be _safe_, it will not be performant.

**Comment by zemerick** [comment]
I'm thinking it's the command block telportation he has interacting badly with the absorbers.

Edit: Can you also post the full code from the command blocks? Additionally, you mentioned it only occurs when you are there in person. Did you always try to use the command blocks for the teleportation there? If they're not getting activated at all, it might not be the source. It's just the only thing I can notice from those images that's at all unusual.

**Comment by MachiavelliSeraphim** [comment]
Command on each is
/cofh tpx @p (coordinates) (dimension)

After the crashes, i used the same commands from the command line, but did not use the blocks.

I have been using them to come and go in the past with no issues.  The crashes started on login when having been logged off from there.

Its a wierd puzzle unfortuately :(

Ill try pulling the absorbers out then updating again and see if it fixes anything.

**Comment by MachiavelliSeraphim** [comment]
Replaced ALL absorbers with Nether Quartz Blocks and re-ran the updates.  Everything APPEARS to be behaving now.

![2016-01-17_19 23 17](https://cloud.githubusercontent.com/assets/10451525/12381051/e38c2ee0-bd4f-11e5-9050-8eeaa04b3ae2.png)

![2016-01-17_19 23 32](https://cloud.githubusercontent.com/assets/10451525/12381054/e81b06f2-bd4f-11e5-91dd-4ab0ebb5bca4.png)

![2016-01-17_19 23 35](https://cloud.githubusercontent.com/assets/10451525/12381056/eb19cffa-bd4f-11e5-8812-7f0099f0faa1.png)

![2016-01-17_19 25 25](https://cloud.githubusercontent.com/assets/10451525/12381067/18094ad6-bd50-11e5-97ab-4a77fc045616.png)

Seems to have remedied the problem.  Hopefully it wont re-occur.

Last thing, Has anyone else had a problem with Thermal Expansion Retrievers not beiang able to draw Hot Molten Sodium from a Sodium Heater?  It worked quite well in V9, but appears broken in V10.

Thanks Guys.

**Comment by MachiavelliSeraphim** [comment]
After 2 days, I have had no further issues with crashes.  

Should I open a ticket for the sodium heater/Thermal Expansion interaction issue, or just assume its being fixed?

Thanks for all the help.

**Comment by ReikaKalseki** [comment]
The TE interaction is likely due to a fluid behavior change on my end, one that I was told I needed to do. As I understand it, if fluid transfer fails, the caller is improperly coded.

**Comment by MachiavelliSeraphim** [comment]
Ive tried with TE tanks as the caller, with all TE components in between, and it failed.  Not a big deal, just a nuisance.  Thanks for looking at it.
