### ISSUE TITLE
DragonApi crash on startup

### ISSUE THREAD

**Issue by nogamenofun98** [ReikaKalseki/Reika_Mods_Issues#580]
http://pastebin.com/0PGaM2UY

forestry_1.7.10-3.6.12.3
binnie-mods-2.0-pre14

do i need to update forestry? or downgrade it?

**Comment by ljfa-ag** [comment]
You need to update Forestry to version 4.

**Comment by ReikaKalseki** [comment]
"Old version" is for when my mods are out of date.

**Comment by ljfa-ag** [comment]
Welp, close enough :p

**Comment by nogamenofun98** [comment]
but the binniemod only can support below v4
is any dev / alpha version support v4
or i need to abandon binniemod?

Edit: is v9b is the last version for forestry 3? but how to download it? curseforge only have lastest version)

(or where is the last version of dragonapi that support below v4? thank you)

**Comment by ReikaKalseki** [comment]
Drop Binnie's mods.

**Comment by TomeWyrm** [comment]
Drop Binnie's mods, you'll be glad you no longer have a support nightmare weighing down your pack that won't be updated for months at a time.

**Comment by nogamenofun98** [comment]
ok , thank you. :)
