### ISSUE TITLE
Problem with NEI

### ISSUE THREAD

**Issue by MaciejMalczyk** [ReikaKalseki/Reika_Mods_Issues#582]
When I checked a sand recipe I got  <a href="http://pastebin.com/usECmSPz">this<a/> error.

**Comment by Builderb0y** [comment]
#581, #567, #564, #550, #544, #540, #534, #522, #515, #488

**Comment by ReikaKalseki** [comment]
Seriously? Over 10 previous reports, _including the one immediately previous_, and you **still** report it?
