### ISSUE TITLE
Can't plant canola seeds with floodlight

### ISSUE THREAD

**Issue by amesgen** [ReikaKalseki/Reika_Mods_Issues#583]
I have found a weird issue: I wanted to build a canola farm in a Mystcraft Eternal Rain World, but as the dimension has a day-night-cycle, I used floodlights (with ac-engines). I first placed the floodlights, and after that, I planted the canola seeds. Note that the y-Co. of the floodlights is one block higher than the dirt of the canola seeds. Everything worked fine, but in the direct line of the beam (only the "center" of the floodlight). I could not place canola seeds, they dropped instantly. If I turn off the floodlights, and place the canola seeds afterwards, I can place the canola seeds like everywhere else as expected, and they grow after the light has been turned on again. Additionally, if I move the floodlights one block higher, I CAN plant canola seeds in these lines with the floodlights turned ON or OFF. I am able reproduce this behavoir as far as I tested.
This issue is not really severe, as it can easily be avoided, but it is still a bug that might be of interest.

**Comment by ReikaKalseki** [comment]
wtf...I just rewrote canola seeds; wait until v11 if that happens to fix it.

**Comment by TomeWyrm** [comment]
Yeah, it's the invisible light block bug. It's why EVERYONE says to disable Railcraft's "hidden heat"

**Comment by ReikaKalseki** [comment]
Except he sees it when the light blocks are above the canola.

**Comment by ReikaKalseki** [comment]
I misread the original post as saying the problem happens when the lights are one block above the canola, not the dirt.

**Comment by TomeWyrm** [comment]
Apparently Canola doesn't want to replace the light blocks… odd

**Comment by ReikaKalseki** [comment]
I just checked, and it should be able to overwrite light blocks.

**Comment by ReikaKalseki** [comment]
Any change?

**Comment by amesgen** [comment]
Sorry for the late response, I'll try  it today.

**Comment by amesgen** [comment]
It works now as you would expect! Thx!
