### ISSUE TITLE
NotEnoughItems and DragonApi crash

### ISSUE THREAD

**Issue by Zidiath** [ReikaKalseki/Reika_Mods_Issues#584]
It seems whenever I would click on any type of dust in NEI it causes my client to close to desktop. This is a fairly large pack so I wouldn't be surprised if this is caused from another completely different mod but this is the most I could gather.

http://pastebin.com/taZZ46Rk

My best guess is the grinder from Rotarycraft is having a issue showing recipes in NEI so it resorts to the crash but i'm no coder so i really don't know.

**Comment by ReikaKalseki** [comment]
#582, #581, #567, #564, #550, #544, #540, #534, #522, #515, #488
