### ISSUE TITLE
Opening a specific chest crashes the game (Contains seeds/plant stuff)

### ISSUE THREAD

**Issue by robaimes** [ReikaKalseki/Reika_Mods_Issues#586]
https://gist.github.com/anonymous/ac066644b81f39e2128d

Looks to be an issue with Magical Crops compatibility?

Using the latest version (BETA 5) found here: http://minecraft.curseforge.com/projects/magical-crops-core

**Comment by ReikaKalseki** [comment]
Where did you get the idea it was MagicCrops?
http://pastebin.com/uJNPLEkw

**Comment by robaimes** [comment]
Edit: Forgot to view the full file. Proceed with laughing.

**Comment by zemerick** [comment]
You have like 20 errors in there, with tons of different mods. Forestry, iguana tweaks, error with a script ( AllLaserOres.zs ), factorization, magical crops addons...yea. You've got a lot of work to fix that pack. It could be any of those that is triggering the crash later on, or it could be a bug in any of the mods specifically, or it could be from your scripts and such, or incompatible versions between mods. Even if you were to get in, you would likely be bumping into stuff pretty frequently that isn't working right.

**Comment by robaimes** [comment]
As Reika kindly pointed out, it's due to an invalid allele in Forestry. Specifically, due to the removal of Binnie's Mods.

I had a _moment_, and forgot to view the full file, so assumed the crash was due to DragonAPI. I'm aware of the other issues, however some are due to user addons.

**Comment by zemerick** [comment]
That'll get ya:) I figured it was the allele problem, but was looking back to see what all mods you had to see if anything was going weird, because the modlist at the end is missing almost all of them. That's when I noticed lots of other errors. I do not envy you atm:)
