### ISSUE TITLE
RotaryCraft hand book crash.

### ISSUE THREAD

**Issue by StrayanDropbear** [ReikaKalseki/Reika_Mods_Issues#587]
When I open the handbook the client crashes. I'm using a modpack and tried disabling to find the cause but it seems like multiple mods in certain combinations is causing this.

Crashlog:
http://pastebin.com/r9wMRsDx

Also the other handbooks from your other mods works fine.

**Comment by ljfa-ag** [comment]
Duplicate of #544, #540, #534, ...

**Comment by ReikaKalseki** [comment]
#582, #581, #567, #564, #550, #544, #540, #534, #522, #515, #488
