### ISSUE TITLE
rotorycraft handbook crashes when opened in rotorycraft 10d

### ISSUE THREAD

**Issue by greg2-1** [ReikaKalseki/Reika_Mods_Issues#589]
when ever a page of the rotorycraft handbook would open it crashes, the report linked here: http://pastebin.com/E2TeuRHN

**Comment by ljfa-ag** [comment]
This has already been reported often
#588, #587, #582, #581, #567, #564, #550, #544, #540, #534, #522, #515, #488

**Comment by ReikaKalseki** [comment]
Again, the _very last issue_ was the same!
