### ISSUE TITLE
ReactorCraft HPT steam injectors won't accept lubricant from non-Lubricant Hose methods

### ISSUE THREAD

**Issue by umbralOptimatum** [ReikaKalseki/Reika_Mods_Issues#59]
I've assembled a couple HPTs but they refuse to do anything because, as the Angular Transducer reports, there's no lubricant in them. The steam injectors only take lubricant from the Lubricant Hose, with other mod methods like Temperate Fluiducts from Thermal Dynamics and tanks that directly output not adding any lubricant to the injectors. Breaking and replacing parts of the multiblock to update it doesn't do anything,

**Comment by umbralOptimatum** [comment]
![2015-05-05_20 57 32](https://cloud.githubusercontent.com/assets/12092270/7485912/c78fcc60-f36a-11e4-9ca6-915a83d5c080.png)

**Comment by theoanden** [comment]
that picture doesnt seems right, are you sure you built correctly?

**Comment by umbralOptimatum** [comment]
I didn't as of the time of the screenshot, but steam injectors don't need to be part of the multiblock to accept lubricant.

**Comment by ReikaKalseki** [comment]
Built wrong as per the thread.

**Comment by umbralOptimatum** [comment]
Even with it built correctly only the lubricant hose inputs into the steam injectors. For example placing a Thermal Expansion portable tank on top of the injector and setting it to output has no effect.

**Comment by ReikaKalseki** [comment]
I know from experience that conduits hook up fine, so that issue is internal to the tank.
