### ISSUE TITLE
crash upon opening the grinder gui (Ticking memory connection,NullPointerException)

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#590]
hi,
I just had my game crash after opening the grinder gui. Before that I had rotated the grinder by mistake with a screwdriver. The output slot contained a few flakes, the tank and the input slot were empty. The grinder was being powered by steam generator, at least before I rotated it.

http://pastebin.com/YZZKbsDb

RotaryCraft 1.7.10 V10d.jar
DragonAPI 1.7.10 V10d.jar
Forge 10.13.3.1403

**Comment by ReikaKalseki** [comment]
Your crash is entirely vanilla code, though a couple people have reported it being due to Java 8.
