### ISSUE TITLE
Feature Request - Make Fuel Pellets 2-way Accessible

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [ReikaKalseki/Reika_Mods_Issues#591]
Currently Breeder Cores and Fuel Cores can only have fuel inserted from the top.  
I use an AE storage Bus to do this currently so I can remotely control my fueling through my AE system.  
Would it be difficult to make the fuel pellets removeable from the top surface also, similar to how a chest or MFR DSU works?  
The fuel could be inserted or removed from the top, while waste could only be removed from the bottom.

I would like to set up a SCRAM function to remove the fuel if the cores start to run away, since ive had it happen once, and I occasionally have to defuel all my cores so I can make changes to the cooling loop.
Defuelling by hand is a pain...

Just curious.
Thanks.

**Comment by ReikaKalseki** [comment]
Fuel cores are gravity-fed.

**Comment by ljfa-ag** [comment]
What does that have to do with being able to remove fuel by automation?

**Comment by ReikaKalseki** [comment]
Gravity feed is downwards, meaning that output is only from the bottom.

**Comment by MachiavelliSeraphim** [comment]
Ill roll with it.  Thanks for at least looking.
