### ISSUE TITLE
division by 0 in TileEntityCrystalFence

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#593]
hi,
When placing a fence the game starts throwing division by 0 exceptions on update. Found that in creative while testing something else, so not sure whether it only happens with creative spawned fences.

http://pastebin.com/LxYAjuEy

**Comment by ReikaKalseki** [comment]
Post a screenshot of the setup.

**Comment by Turmfalke2** [comment]
Not really much of a setup:
http://ibin.co/2UFdmeBQw82A

**Comment by ReikaKalseki** [comment]
Does the error go away if it has relays?

**Comment by Turmfalke2** [comment]
An empty relay source with an omni relay next to it pointing at the emitter does indeed stop the error messages after a while. After doing so I can even remove the relay source and the omni relay without the error resurfacing, unless I right click the emitter with an manipulator.
Actually scratch that, the error messages stop after a while regardless of whether I placed a relay nearby or not and I have apparently completely forgot how the relays work - was the cracked side the input or the output?

**Comment by ReikaKalseki** [comment]
By relays I mean the fence relay.

**Comment by Turmfalke2** [comment]
like this? http://ibin.co/2UKN6Pa3ZWvZ
still the same error that disappears after a while.

**Comment by ReikaKalseki** [comment]
Now connect them and try again. :P

**Comment by ReikaKalseki** [comment]
So,...

**Comment by Turmfalke2** [comment]
Real life stuff happened and I had no time to to further test this. Maybe someone else can test it?

**Comment by ReikaKalseki** [comment]
Fixed.
