### ISSUE TITLE
My server dont start after i install DragonAPI, Rotarycraft and Reactorcraft

### ISSUE THREAD

**Issue by thebalck** [ReikaKalseki/Reika_Mods_Issues#594]
Hi, after i install this mods the server won't start, theres no crash, simply the server dont start can u help me ?
theres the latest fml log 
[fml-server-latest.pdf](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/99496/fml-server-latest.pdf)

**Comment by ljfa-ag** [comment]
Why a PDF file? oh well
That is certainly strange. The log just stops always at that point? What happens if you remove ForgeRelocation?

**Comment by thebalck** [comment]
GitHub dont read RTF, PDF was the first universal that i saw in save options (Sry im lazy xD)

Some times stops in other points, i think it was a server memory problem so i deleted the world backup but its all the same it stops from the air

**Comment by ReikaKalseki** [comment]
I am not downloading a random PDF.

> Sry im lazy

If that is intended to get you sympathy or lenience, know that it will have exactly the opposite effect.

**Comment by Duckfan77** [comment]
Try pasting it into gist.github.com

**Comment by thebalck** [comment]
[fml-server-latest.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/100703/fml-server-latest.txt)

here you have txt

**Comment by thebalck** [comment]
This one is from today 
[fml-server-latest.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/100737/fml-server-latest.txt)

**Comment by ReikaKalseki** [comment]
You were explicitly linked to GitHub gist. Use it.

**Comment by thebalck** [comment]
okok
https://gist.github.com/thebalck/898433da46bfff08e632

There are 2 logs in that link from 2 different days

**Comment by ReikaKalseki** [comment]
That log contains no crash.

**Comment by ReikaKalseki** [comment]
12 days is a rather long time to take to post a crashlog that one already has...

**Comment by ljfa-ag** [comment]
Well he said that there is no crash, just the server not starting
But seems like noone else is having this issue

**Comment by ljfa-ag** [comment]
Hm, I see that they have Equivalent Exchange 3 installed....maybe it just takes a while for it to recalculate the EMC values after adding a new mod?
