### ISSUE TITLE
Client crash when looking up NEI recipes on server

### ISSUE THREAD

**Issue by imIrony** [ReikaKalseki/Reika_Mods_Issues#595]
Looking up recipes in NEI causes a client crash while on my server, the log states it has something to do with RotaryCraft and/or DragonAPI.

Log:
http://pastebin.com/L0XCCtuU

**Comment by ljfa-ag** [comment]
Already reported a lot
#589, #588, #587, #582, #581, #567, #564, #550, #544, #540, #534, #522, #515, #488
