### ISSUE TITLE
[CC] X [Thaumcraft] Vacuum Gun "breaks" Warded Glass

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#596]
If a Vacuum Gun is used and catches some Warded Glass, the glass becomes impossible to remove, even by the person who originally placed it. 

It's already supposed to be unbreakable otherwise, but I suppose the gun isn't really breaking it which is the problem.

It works just fine with an Arcane Door (doesn't affect the door at all). Same with blocks warded using the Warding wand focus.

**Comment by ReikaKalseki** [comment]
The TileEntity data is probably being lost (is warded glass a TileEntity?).

EntityFallingBlock _does_ support NBT, so I should be able to save the TileEntity data.

**Comment by Shahelion** [comment]
I believe so. It should just be ignored like the Door and Warded blocks, though.

**Comment by ReikaKalseki** [comment]
I rather like the idea of penetrating it...

**Comment by ReikaKalseki** [comment]
Owner loss should be fixed.
