### ISSUE TITLE
Coils will overload shaft junctions, even if deactivated

### ISSUE THREAD

**Issue by OmegaHaxors** [ReikaKalseki/Reika_Mods_Issues#597]
My switcher coil setup is completely unusable due to this issue.

BEFORE:)
![2016-01-23_03 56 11](https://cloud.githubusercontent.com/assets/16057503/12530058/1a1d6638-c186-11e5-820d-d28f0af53fd2.png)
AFTER:(
![2016-01-23_03 56 18](https://cloud.githubusercontent.com/assets/16057503/12530059/1f3dd68e-c186-11e5-9074-9c0ad60599df.png)

**Comment by ReikaKalseki** [comment]
So off-state coils are being counted towards the total?

**Comment by OmegaHaxors** [comment]
Yes.

**Comment by ReikaKalseki** [comment]
Fixed.
