### ISSUE TITLE
Strange Fractionation Unit Slot Numbering

### ISSUE THREAD

**Issue by amesgen** [ReikaKalseki/Reika_Mods_Issues#598]
In order to automate the Fractionation Unit, I tried to insert the items via ComputerCraft/OpenPeripherals by using the method exportItem(table fingerprint, string side, number amount, number intoslot) of an ME Interface. But the slot numbering is a bit confusing, so I recommend changing them:
I expected the inventory of the FracUnit to be numbered like this (only the left, input side):

```
1 2                 1 4
3 4       or        2 5
5 6                 3 6
```

With the abbreviations B = Blaze Powder, C = Coal, N = Netherrack Dust, T = Tar Sand, E = Ethanol, M = Magma Cream, NEI shows the following ordering:

```
B C
N T
E M
```

Therefore, I tried both numbering possibilities, but only Magma Cream and  Blaze Powder were exported.
 After experimenting a lot, I found out that if I use this numbering:

```
1 4
2 5
3 6
```

with these inserted items:

```
B T
C E
N M
```

works very well, and JetFuel is produced and I am very happy ;)
This explains why only M and B were exported, but it is nonetheless very weird and not intuitive. As I don't know where the affected code can be found in the source code, I just write in pseudo-code what I expect to be the mistake (of course this is no code u would use in a mod), assuming this to be "real" slot numbering:

```
1 4
2 5
3 6
```

```
jetfuelingredients = { blazepowder, coal, netherrackdust, tarsand, ethanol, magmacream }
fracunit_input_inv_width = 2
fracunit_input_inv_height = 3

method getSlotForNEI(ingredient) {
 index = jetfuelingredients.indexOf(ingredient) //1-based (as the slot numbering)
 return (index - index % fracunit_input_inv_width) * fracunit_input_inv_width + index % fracunit_input_inv_width
}

method getSlotForComputerCraft(ingredient) {
 index = jetfuelingredients.indexOf(ingredient) //dito
 return (index - index % fracunit_input_inv_height) * fracunit_input_inv_height + index % fracunit_input_inv_height
}
```

This code explains the behavoir, but certainly, the reason might be different.

**Comment by TomeWyrm** [comment]
Huh, that is an odd slot/ingredient interaction there. Unfortunately, I don't know enough about java to help.

**Comment by ReikaKalseki** [comment]
https://github.com/ReikaKalseki/RotaryCraft/blob/master/TileEntities/Production/TileEntityFractionator.java#L40

https://github.com/ReikaKalseki/RotaryCraft/blob/master/TileEntities/Production/TileEntityFractionator.java#L196

**Comment by amesgen** [comment]
The code is not really helpful, as BOTH versions work: The one shown in NEI, and the one you have to use with OpenP. The code only seems so admit ONE version of inserting the items.

**Comment by amesgen** [comment]
So do you consider this to be a bug or an intended behavoir?
Because it is indeed very confusing.

**Comment by ReikaKalseki** [comment]
I am considering a fractionator rewrite.

**Comment by Reignofmagic** [comment]
You can also just have a buffer chest with 1 stack of every resource in it, then just pipe the ingredients in from that chest. The Frac unit will not accept an item into the incorrect slot this way. I use item consuits from enderio and it works.

**Comment by amesgen** [comment]
I tried to do this, but, for example, if I run out of Netherrack Dust for some reason, item pipes will insert ethanol into two slots (see my initial post), which results in a mess even if Netherrack Dust is avaiable again later on.

**Comment by Aivech** [comment]
Most "smart" pipes have a way of putting exactly a certain number of items in an inventory.
Thermal Expansion and Mekanism pipes (with the logistical sorter) can do this.

**Comment by amesgen** [comment]
Yes, of course, but I mean two slots in the FracUnit, not in the chest. Just feed Ethanol into a FracUnit with a pipe, and two slots will fill.

**Comment by Aivech** [comment]
I know what you mean. A Resonant Retriever/Servo, which you would want anyways for speed, can specify the number of items to keep in the **destination** inventory.

Same with the logistical sorter.

**Comment by amesgen** [comment]
Ah know I understand ^^. Thanks!

**Comment by ReikaKalseki** [comment]
Closed since I redesigned the Fractionator item handling in v12.
