### ISSUE TITLE
Crash on startup with Chromaticcraft v10d

### ISSUE THREAD

**Issue by Aivech** [ReikaKalseki/Reika_Mods_Issues#599]
On a custom pack.

Crash can be temporarily avoided by toggling "Notify Others of Progress Gains", e.g., if it is false set it true, and vice versa.

Crash report: http://paste.ee/p/0csQN

FML log: https://gist.github.com/DaMachinator/4621d4703e15c7cd4f9d

**Comment by ReikaKalseki** [comment]
Wait...the config affects this crash? Try removing other mods, with the config enabled.

**Comment by Aivech** [comment]
Yes.

Cycle goes as follows:

Launch pack [enabled] --> starts
Play for an hour or so
Save, quit, and close
the next day, I play again
Launch pack [enabled] --> crash
Change config
Launch pack [disabled] --> no crash
play for an hour, then put it away until the next day
The next day 
Launch pack [disabled] --> crash
change config
Launch pack [enabled] --> no crash
play for an hour

And so on.

Using MultiMC to launch and Notepad++ for configs.

**Comment by Aivech** [comment]
So I'll enable the config, get it to crash, and then disable mods until it stops crashing?

**Comment by ReikaKalseki** [comment]
Yes.

**Comment by Aivech** [comment]
Any suggestions on what mods to start with?

**Comment by Aivech** [comment]
I don't see any mods that add extra functionality or otherwise modify vanilla achievement or chat, and the log did not give me any clues, so I'll start removing mods, starting with the ones I do not care to lose.

**Comment by ReikaKalseki** [comment]
No idea, no. Have a look at #585 and #592.

**Comment by Aivech** [comment]
I will, thanks.
I didn't see these, despite looking through a month's worth of open issues.

**Comment by Aivech** [comment]
In common with #592 I have Applied Energistics and Thaumic Energistics.
However, Revolution|2 on the ATLauncher has both these and I have never had this issue.

I do not have Fastcraft or Optifine or other similar mods.

**Comment by Aivech** [comment]
It might be a while before I get to test this due to Real Life.

**Comment by Zedrimar** [comment]
I have this issue, however I have not linked this to a config issue, It seems like it for some odd reason is not cooperating well with some mods (some that have little to no connection to the mod such as voxelmap and liteloader). As soon as I added it, I got the same crash. I will post a link later with a temporary download link to the mods I use (chromaticraft not included) and the crash and log. I have noticed one thing though, it seems to react badly to many mods and the interaction keeps changing..... if anyone has a working mods and or .minecraft folder with most if not all the mods that I will include later please let me know, I really want to be able to play with Chromaticraft one day without all these random crashes! XD 

P.S.: to users who will test this: BOP has biome ID issues with chromaticraft so make sure to change the IDs in chromaticraft's config (I set mine with the range of 201-204)

**Comment by Aivech** [comment]
I am using Journeymap, do not have lightloader, and am not using any worldgen mods. I don't even have Natura.

In addition, another pack, albeit a heavily tweaked one, has many of the same mods without issue.

The subtractive method of testing is taking forever due to having a single cheap HDD, can I start with _just_ Reika's mods and add mods one at a time?

**Comment by ReikaKalseki** [comment]
Use a binary split search.

**Comment by Aivech** [comment]
Could you explain further?

**Comment by TomeWyrm** [comment]
Step 1: Take out half the mods (be careful not to take out any dependencies; don't remove Dragon API or Forestry, and don't remove RotaryCraft if you're keeping ReactorCraft, etc.),

Step 1 Results: If the error can be reproduced then the mod causing the error is in the remaining mods, if the error disappears it was one of the mods you removed.

Step 2: If the error stayed, repeat the first step with your halved mod list (still be careful to keep dependencies of mods you aren't removing). If the error was gone, remove all the mods you kept (except for DragonAPI, and Forestry; also once again don't forget dependencies... like if you're keeping Immersive Integration then don't remove Immersive Engineering) and see if the error returns.

Step 3: Continue removing half the remaining mods, either switching which half you're working with or pruning the current set by half until you figure out which mod(s) are required at minimum to make the bug happen.

**Comment by Aivech** [comment]
Keep in mind I have to run it again after it succeeds once due to the nature of the problem - namely that taking certain actions allows it to start once.

**Comment by TomeWyrm** [comment]
And this is the most time efficient method. It sucks, we've all done it before.

**Comment by Aivech** [comment]
I know.

I REALLY need an SSD - even a small one.

**Comment by Zedrimar** [comment]
Strangely enough I have noticed that if the game is ran with the _EXACT SAME_ layout as before, the game will likely recover and boot with subsequent boots being successful (if it works).

**Comment by Aivech** [comment]
I found the culprit:

Applied Energistics 2.

**Comment by Aivech** [comment]
I have Rev3-Beta4

**Comment by Aivech** [comment]
https://gist.github.com/DaMachinator/8bee9761b4485c62f28a

**Comment by Aivech** [comment]
Tested again with everything _but_ Applied Energistics and its addons. No crash.

**Comment by Aivech** [comment]
#481 

Just had this pointed out to me, will downgrade AE2 and Thaumic Energistics to see if problem persists.

**Comment by TomeWyrm** [comment]
Reika, you may wish to tag this. I have no idea about the appropriate tags.

Additionally, @DaMachinator it would be helpful once Reika updates to the new AE for you to test this again.

**Comment by Aivech** [comment]
When will that be?

**Comment by TomeWyrm** [comment]
When it happens? Trying to get even a ballpark ETA out of Reika is like squeezing blood from a stone

**Comment by Aivech** [comment]
True...

**Comment by ReikaKalseki** [comment]
Especially considering I mark this one as low priority.

**Comment by Aivech** [comment]
Well, as long as whatever upcoming Extra Cells update fixes the fluid storage bus works with AE2 rev 2, I'm happy.

**Comment by Webzoner97** [comment]
How long could it take? Just change "false" to "true" for "AE rv3 compatibility".

**Comment by Aivech** [comment]
wait, what?

**Comment by Webzoner97** [comment]
I don't know exactly what your code looks like, but something like this:

```
boolean isCompatibleWithRV3()
{
    return true;
}
```

**Comment by ljfa-ag** [comment]
It's probably not as simple as that

**Comment by Webzoner97** [comment]
Why wouldn't it be?

**Comment by Aivech** [comment]
We're talking about switching API's here...

**Comment by Aivech** [comment]
It's similar to the reason why certain versions of programs only work with certain versions of Windows or OS X or Linux

**Comment by Webzoner97** [comment]
You mean because the companies making them took bribes? Is that what's going on here too?

**Comment by Aivech** [comment]
I strongly doubt that you have ever written a program that depended on or could interact with another program.

And no, it isn't bribery.

**Comment by Webzoner97** [comment]
I have better things to do with my life. :D

**Comment by Aivech** [comment]
:expressionless: 
1. I wouldn't say that if I were you, especially not here. Also, if you think coding programs is a waste of time, what on earth are you doing on GitHub?
2. An API is a set of special functions that one programmer provides to other programmers to do special things with his program. Like for instance being able to power your ME system with Rotarycraft power. It also explains why mods require a certain version of Forge and why a given version of a mod only works with one MC version. When the API changes, things break. How much breaks depends on what changed and how much.

**Comment by Webzoner97** [comment]
Whatever helps you sleep at night, I'm off.

**Comment by Aivech** [comment]
That made no sense...

**Comment by TomeWyrm** [comment]
@Webzoner97 try asking someone to turn the lights off on their Camero when they have a Mustang and watch the confusion. It's similar (but worse) trying to use an API that has changed. Computers cannot improvise, so if you tell it to pass Rotarycraft power to AE with "IAEPowerProvider" and they changed it to "AEPowerAcceptor", it basically says "hey, that made no sense" and in PC speak? That means a crash

**Comment by Aivech** [comment]
Someone is way better at explaining things than me...

**Comment by TomeWyrm** [comment]
Nice thing about computers, they do what you tell them to, if you tell them to do something they don't know about, they say "nope" and yell at you for being a space cadet

**Comment by Aivech** [comment]
I know that much...except the part about a space cadet
