### ISSUE TITLE
Crash with NEI

### ISSUE THREAD

**Issue by strawberryshortbread** [ReikaKalseki/Reika_Mods_Issues#6]
EVery time I look up recipes for reika's ore flakes they crash me. Fix it.

*Edit from CoolSquid:*
Please use Pastebin. 

http://pastebin.com/2awhaDzn

**Comment by TomeWyrm** [comment]
We need the versions for CodeChickenCore, NotEnoughItems, DragonAPI and RotaryCraft, as it's likely you're using incompatible versions

**Comment by strawberryshortbread** [comment]
All my versions of Reika's stuff are 6f, so it's gotta be reika's mods, not anyone else.

**Comment by 1Matthias** [comment]
If you could put the entire log onto pastebin and put a link to it, that would be helpful. Also, an older version of NEI or CodeChickenCore may be incompatible with v6f.

**Comment by zemerick** [comment]
Not true. If you were using an older NEI, or codechicken core, it could easily be the cause as well. Or, if you use a newer one than what v6f was built with, it could also cause a problem. Also, different versions of java can cause issues. Or forge.

All of these details are contained in the log that you pulled the above details from. This is why it's always best to include the full log.

**Comment by strawberryshortbread** [comment]
Not sure why you guys are so defensive, to me it's kind of suspicious. It's ovbious I'm not goint to get any real support so good day.

**Comment by 1Matthias** [comment]
We are trying to fix this, however we do need some details. We are not defending anything, just explaining possibilities and trying to understand what is happening.

**Comment by zemerick** [comment]
Sorry, but this is how you do get "real support". Step one is always information gathering. Code is very complex, and without very specific details it can be hard to track down any issues.

When it comes to problems across multiple mods, it very often does indeed come down to the wrong versions. Sometimes there are simple work arounds, such as removing or adding an API folder to one of the jars. Other times, the only solution is to update or downgrade one or more of the mods.

Mod version mismatches are seriously one of the most common problems, and not knowing the exact versions prevents us from helping with that.

**Comment by strawberryshortbread** [comment]
No, I'm pretty sure the problem is crappy code. :)

**Comment by zemerick** [comment]
Reikas mods are open source, and you could easily provide a pull request for Reika to implement the fix if you know the problem.

**Comment by strawberryshortbread** [comment]
I have better things to do than do someone else's job for them.

**Comment by coolsquid** [comment]
So, 4 people comes to help you immidiately after you open the issue, and it's bad service?
> Reikas mods are open source

*Visible source
> I have better things to do than do someone else's job for them.

This is not Reika's, nor our job.

**Comment by 1Matthias** [comment]
You know, you could have provided some basic information and we could have looked into the issue, but you chose to not do this. We have actually seen this bug before, and needed more information on its exact conditions.
