### ISSUE TITLE
Reactor Fuel Suggestion

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [ReikaKalseki/Reika_Mods_Issues#600]
Reika, 

Since we acquire such a large stockpile of depleted uranium (U-238) and the only required process to convert U-238 into Pu-239 is neutron absorbtion and then to allow beta decay, I would like to inquire if it would be feasible to use something like a Neutron Irradiation Chamber to bombard Depleted Uranium cells and convert them into Breeder Fuel Cells.

 http://www.3rd1000.com/nuclear/nuke101g.htm
This link is only a basic explanation that I found very quickly.

My argument for breeder cells is that Breeder Fuel can be Pu-239 and U-238 wrapped into a cell.  Currently in game, our breeder fuel is U-235 wrapped in U-238 and it creates Pu-239 through neutron absorbtion from the U-235 fission events.  If we were to bombard the depleted uranium cell and partly convert it to plutonium (I.E. Using a Neutron Irradiation Chamber), then it in essence would be converted into breeder fuel that could then be fed to a Breeder Reactor to fully convert it.

Its just a suggestion based on theory.  I find that after a good long time, I tend to have a few thousand depleted uranium cells worth of material for every couple of plutonium cells I stockpile.  This system would allow us to operate in more of a closed fuel loop which would represent more of what India and Russia are trying to achieve in modern day.

Thanks for the time.

**Comment by ReikaKalseki** [comment]
The Neutron Irradiation Chamber operates on fluids. Make a breeder reactor. Breeder fuel can be directly crafted with U235 and U238.

**Comment by MachiavelliSeraphim** [comment]
Would you consider adding an additional recipe to allow making of Breeder Reactor Fuel with Plutonium substituted instead of the Enriched Uranium? 
You would be able to use either Fissile material combined with Depleted Uranium to make Breeder Fuel?

Thanks for your time.

**Comment by ReikaKalseki** [comment]
No, because that is not what breeder fuel is made from.
