### ISSUE TITLE
Some recipes don't work

### ISSUE THREAD

**Issue by ChestBras** [ReikaKalseki/Reika_Mods_Issues#601]
Lots of the recipes don't make anything. The GUI doesn't show the output and using the wand just makes buzzing noises.

**Comment by ghost** [comment]
I'm guessing you don't have the required structure for Chromaticraft around the casting table or you don't have the runes in the structure.

**Comment by ChestBras** [comment]
No, I have everything, and the screen shows the diamonds.

**Comment by Builderb0y** [comment]
Screenshots would help diagnose this farther, as would a more specific list of which items don't work.

**Comment by ChestBras** [comment]
Crystal Tank Controller:
![](http://i.imgur.com/OLLeCHJ.png)

Enchanter:
![](http://i.imgur.com/wJOs4VL.png)

Block Accelerator:
![](http://i.imgur.com/GloPVm4.png)

Casting Delegate:
![](http://i.imgur.com/njhiDRC.png)

Crystal Brewer:
![](http://i.imgur.com/bkdFn4a.png)

RF Spreader:
![](http://i.imgur.com/SjCIGFC.png)

**Comment by Builderb0y** [comment]
Most of the ones that don't work look like you're using the wrong color shards. I don't know all of them off-hand, but I know the tile accelerator requires nila shards.

**Comment by ChestBras** [comment]
You know, how about you don't bother if you don't know what you're talking about. The recipes just say shards, and I put shards in.

**Comment by ghost** [comment]
The recipe doesn't say "put any shard in". If you looked on the first page of that item for crafting it tells you what you need (list). If the name of the shard cycles then it can be any, if it doesn't then it HAS to be that color.

**Comment by ChestBras** [comment]
If you're too lazy to check the recipes or NEI, stop polluting my bug report. All of them mix up the shards because it uses the ore dictionary.

![](http://i.imgur.com/AmUKu4m.png)

**Comment by EyeDeck** [comment]
Yes, a few recipes can use any shard, but most of them require specific colors.

**Comment by TomeWyrm** [comment]
Chromaticraft is nearly universally color-dependent recipes. You really need to learn how to RTFM.

**Comment by ChestBras** [comment]
Well that's just ~~fucking retarded~~ stupid. Why would some recipes accept any color of shard and others act all special and only allow their favorite? Is this some of that "tricking the player" as difficulty again?

**Comment by TomeWyrm** [comment]
Because theme. Some recipes utilize the magical nature of ANY shard, some utilize the nature of the magic of a specific shard. Nila for instance influences vision. Tahara is purity.

That you are missing the theme will cause a lot of difficulties with ChromatiCraft

**Comment by DolphinMana** [comment]
You might want to look into changing this. He has a good point that the differences are needlessly confusing, and I think it's best for all involved if we make sure that there aren't any weird snags to trap a player.

Just because theme is obvious to you doesn't mean it is to everyone, or that they'll agree on what the theme is or what it means for the recipes.

**Comment by kolatra** [comment]
If they don't "agree with the theme" then that's just too bad. It's Reika's mod, and it's being made in his vision.

**Comment by DolphinMana** [comment]
There's no one vision here, it's all up to your personal interpretation.

**Comment by TomeWyrm** [comment]
> You might want to look into changing this.

Yeah... no. Read the manual and learn the mod. None of this is that complicated, and nobody is going to help you if you're unwilling to put in some modest effort.

Kuro = Magic/ (Mob Confusion/Wither)
Karmir = Endurance/Protection (Resistance/Damage)
Kijani = Nature (Poison)
Ruskea = Mineral (Saturation(food)/Nausea)
Nila = Light/Vision (Night Vision)
Zambarau = Enhancement (Experience)
Vadali = Water/Fluid (Water Breathing, Hunger (no thirst in MC :-p))
Argia = Deception (Weakness)
Ykri = Change (Slowness/Blindness)
Ruzova = Aggression (Strength)
Asveste = Motion (Jump Boost/Jump Removal)
Kitrino = Energy (Haste/Mining Fatigue)
Galazio = Time (Speed/Slowness)
Kurauri = Life/Health (Regeneration)
Portokali = Fire/Heat (Fire Resistance/Fire Damage)
Tahara = Purity/Harmony (Clear Effects/Mob Invisibility)

**Comment by Aivech** [comment]
> Kuro = Magic/ (Mob Confusion/Wither)
> Karmir = Endurance/Protection (Resistance/Damage)
> Kijani = Nature (Poison)
> Ruskea = Mineral (Saturation(food)/Nausea)
> Nila = Light/Vision (Night Vision)
> Zambarau = Enhancement (Experience)
> Vadali = Water/Fluid (Water Breathing, Hunger (no thirst in MC :-p))
> Argia = Deception (Weakness)
> Ykri = Change (Slowness/Blindness)
> Ruzova = Aggression (Strength)
> Asveste = Motion (Jump Boost/Jump Removal)
> Kitrino = Energy (Haste/Mining Fatigue)
> Galazio = Time (Speed/Slowness)
> Kurauri = Life/Health (Regeneration)
> Portokali = Fire/Heat (Fire Resistance/Fire Damage)
> Tahara = Purity/Harmony (Clear Effects/Mob Invisibility)

Cool, someone posted these before I got tired of waiting :stuck_out_tongue_closed_eyes:

**Comment by TomeWyrm** [comment]
You could have, I dunno. Read the manual. I was getting tired of people being too damn lazy

**Comment by Aivech** [comment]
I read the manual, I just was having a hard time figuring out which was which.

Well, most of it.

**Comment by TomeWyrm** [comment]
_cough_ NEI _cough_
