### ISSUE TITLE
Some plasma remains stuck in the magnetic pipe after the stop of the reactor

### ISSUE THREAD

**Issue by Wolffgar** [ReikaKalseki/Reika_Mods_Issues#602]
A quantity of 5mB of the plasma stays in the magnetic pipe and in the hydrogen preheater (tank 2) after the stop of the reactor and the preheater. I don't find a way to empty the plasma without melting the pipe. Anybody has an idea to resolve my problem?

**Comment by ReikaKalseki** [comment]
That is not how RC pipes work.

**Comment by Wolffgar** [comment]
If the problem doesn't come from the pipes, how i can empty the 6 mB of plasma in the tank 2 of the preheater ? When i stopped the VDG, my pipes melted in lava.

**Comment by zemerick** [comment]
You're really not meant to turn it off. There's really no reason to unless you are breaking the stuff to move it anyways.

**Comment by Wolffgar** [comment]
I play in Survival mode. So I wish switch off all the engines when I don't make turn the reactor (full batteries) to save energy and nitrogen. If I understand well, I must keep the VDG on the magnetic pipes ?

**Comment by zemerick** [comment]
There's not really any reason to bother with batteries with the tokamak either. You should just leave it running. It doesn't hurt to produce more power than you use.

Yes, you will need to keep the VDG running, but that's free, so why bother to turn it off?

**Comment by TomeWyrm** [comment]
Very little in modded minecraft appreciates duty cycles, reactorcraft especially so.

**Comment by Aivech** [comment]
If you have "too much power", make some expensive RFTools dimensions or an absurd amount of MFR mining lasers. A fusion reactor can easily sustain itself indefinitely given the proper infrastructure.

**Comment by TomeWyrm** [comment]
Or, you know, just don't care about voiding power :-p
