### ISSUE TITLE
Spaces in unlocalised fluid names

### ISSUE THREAD

**Issue by 666lumberjack** [ReikaKalseki/Reika_Mods_Issues#603]
Minetweaker freaks out when attempting to use RotaryCraft fluids because they are registered as <liquid:rc some fluid>. If possible, please change to <liquid:rc_some_fluid> or <liquid:rc.some.fluid> instead.

**Comment by ljfa-ag** [comment]
Hm I guess that is Minetweaker's problem. There is no rule in Forge that would forbid spaces in fluid names.

**Comment by ReikaKalseki** [comment]
Yes, this is entirely on MT's end.
