### ISSUE TITLE
Boring machine @ casting table

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#607]
Hey there,
i just found a bug when i tested the boring machine. i accidently mined my casting table from chromaticraft and instead the table, it dropped a chromatic enchanter

not sure if a rotarycraft issue or chromaticraft one. guess CC.

version: latest from current date

**Comment by DaMachinator** [comment]
Revolution|1 or Revolution|2? Can you reproduce this behavior?

**Comment by DaMachinator** [comment]
Sorry, wrong issue tracker.

**Comment by ReikaKalseki** [comment]
Some code I added today could fix this quite easily...

**Comment by ReikaKalseki** [comment]
Fixed.
