### ISSUE TITLE
Blast Furnance config option for using steel instead of iron for HSLA?

### ISSUE THREAD

**Issue by pharaun** [ReikaKalseki/Reika_Mods_Issues#609]
I am making a custom pack for my own enjoyment and one thing I was trying to do was to have some additional early-game progression in the sense of:
1. Normal metal (iron, copper, etc...)
2. Steel (regular steel via say railcraft blast furnace for ex)
3. HSLA steel

I saw that in the config I could gate the rotarycraft blast furnace by making it require one or more of an pre-approved list of materials, which could work quite well, but I was hoping to be able to add a bit more work required to get HSLA steel if it is possible.

Basically I would like to be able to make the blast furnace require regular steel instead of iron so that the steel can be refined into a higher grade steel (HSLA).  The pulse furnace (the one with jetfuel) can keep on refining iron directly to steel since its later in the tech tree and it would would give myself additional incentives to acquire it (on top of the existing incentives).

If you feel that adding this toggle to the blast furnace violates the sprint of your mod, feel free to close and disregard, the regular blast furnace gating would probably be an alright substitute. I just think it could be neat to have to reprocess the iron a few times in stages for early game.

**Comment by ReikaKalseki** [comment]
Adding yet more carbon to the steel would make it brittle, making the option unrealistic.

That said, I am willing to consider an option that takes generic ingotSteel and adds the other products, forgoing the carbon component.

**Comment by pharaun** [comment]
Ahh I see, I'm not super familiar with the steel production pipeline myself (I should read up on it). 

That could be a good alternative, then it would be possible to do some sort of progression with other stuff depending on the HSLA steel for higher tier stuff yet having regular steel available for earlier tier stuff.

**Comment by ReikaKalseki** [comment]
I just remembered - the Steel Purifier has exactly this functionality. Adding it to the Blast Furnace would make that machine useless.

**Comment by pharaun** [comment]
Awesome, I missed that machine I'm going to take a peek at it. :+1:
