### ISSUE TITLE
Server crash NullPointerException: Exception ticking world

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#610]
http://pastebin.com/W1c7ax1V for full error.

```
java.lang.NullPointerException: Exception ticking world
    at Reika.ChromatiCraft.ChromatiCraft.isRainbowForest(ChromatiCraft.java:807)
    at Reika.ChromatiCraft.Block.Dye.BlockRainbowLeaf.convertPureNodeMagic(BlockRainbowLeaf.java:333)
    at Reika.ChromatiCraft.Block.Dye.BlockRainbowLeaf.onRandomUpdate(BlockRainbowLeaf.java:290)
    at Reika.DragonAPI.Base.BlockCustomLeaf.func_149674_a(BlockCustomLeaf.java:114)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

As far as I can tell, no one was doing anything with Rainbow Forests, nor were fresh chunks being generated. If this is a mod interaction problem, any hints at what I might be looking for?

EDIT: Error has happened a second time. The crash log timestamp matches exactly with this line, then the server gracefully shuts down:

```
[20:50:44] [ChromatiCraft Structure Gen/INFO] [FML/]: CHROMATICRAFT: Initializing dimension structure generation thread...
```

**Comment by ReikaKalseki** [comment]
The biome at the position was null:

```
    return b instanceof BiomeRainbowForest || b.biomeName.equals("Rainbow Forest");
```

**Comment by Haggle1996** [comment]
Thank you for the help; turned out to be a poorly generated silverwood tree. Regenerating the chunk cleared the problem.

**Comment by Haggle1996** [comment]
@ReikaKalseki regenerating the chunk only fixed it for a while. We've replicated this issue in a clean single-player world with Thaumcraft and ChromatiCraft. Specifically, when `B:"Rainbow Trees Spread Rainbow Forests"=false` is set to false, the error will occur when a Silverwood tree is within range of a Rainbow tree. When the spread option is set to true, the error does not occur. This occurs with both manually planted rainbow and silverwood saplings. We have not tried it with naturally occurring trees, but will test further.

Additionally noted during testing, with spread set to false, when a silverwood sapling grows in range of an existing rainbow tree, there's a big lag spike. With spread set to true, there's no lag spike.

It seems like the rainbow tree is doing something it shouldn't when spread is set to false. It seems with spread set to false that the rainbow tree should more or less be a passive tree.

EDIT: confirmed with naturally spawning trees as well.

**Comment by Haggle1996** [comment]
I've also verified that the chunk in question's Biomes array contains no invalid values. I can paste a screenshot if it would be helpful.

**Comment by ReikaKalseki** [comment]
[This](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Block/Dye/BlockRainbowLeaf.java#L298) is the only effect of that config. Try a silverwood with no rainbow tree nearby (>=256 blocks), both with and without the config on.

**Comment by Serenitygene** [comment]
Multiple attempts of just silverwood pures with the config both on and off with no rainbow trees around and both stay stable with no issues.

**Comment by Haggle1996** [comment]
SerenityGene is my tester for this issue, btw.

**Comment by ReikaKalseki** [comment]
This makes no sense, as that config literally only controls that one piece of code.

**Comment by Haggle1996** [comment]
What can we provide you to help troubleshoot this?

**Comment by ReikaKalseki** [comment]
Try with only my CC and ThaumCraft. I suspect someone is doing something inappropriate with the the biome list.

**Comment by ReikaKalseki** [comment]
So...

**Comment by Haggle1996** [comment]
Since you changed the behavior of rainbow forest spread in v11, I've just left the option on and we haven't encountered the problem anymore. I'm very happy with the new behavior in v11 (that you can't just plant a rainbow tree anywhere and it makes a safe zone).

I'm sure there's an issue here, but I think the underlying reason for disabling rainbow forest spread is now moot. As it requires a lot more time to test than I have in my schedule, I'm happy to leave this closed.
