### ISSUE TITLE
ChromatiCraft freezes server.

### ISSUE THREAD

**Issue by havokoc** [ReikaKalseki/Reika_Mods_Issues#612]
I've recently encountered an error with what seems to be ChromatiCraft. After it's been up for a while, the server will freeze and not respond to any commands. After this has occured, the server is "permanently broken", where it will immediately freeze when I try to start it again, unless I either remove ChromatiCraft or use a Backup.
The reason why I suspect ChromatiCraft, and not any other mods is because it works fine when I remove ChromatiCraft (It's won't freeze when I start it).
I found this error with ChromatiCraft in the logs, not sure if it's relevant to the issue I'm having though.
http://ix.io/obw

**Comment by Aivech** [comment]
Might want to post the whole log.

**Comment by havokoc** [comment]
Here's a link to the full forge log. It is almost 50k lines tho...
https://gist.github.com/havokoc/1f2a2099717dfcf68f09

**Comment by ReikaKalseki** [comment]
The first log contains an XML parsing error, which should affect nothing, and the second is a log with no errors and a successful launch.

**Comment by havokoc** [comment]
The second is the log from the frozen server though

**Comment by ReikaKalseki** [comment]
Well it launches successfully. What triggers the freeze? Try with only my mods.

**Comment by havokoc** [comment]
It seems to work with only your mods. I have no idea what triggers the freeze as it doesn't really show anything in the console nor the logs. If I'm online when it freezes, I just get "Timed out" and the console becomes unresponsive.

**Comment by TomeWyrm** [comment]
Run a profiler like visualvm. Sounds like something is grabbing all your CPU or RAM

**Comment by ReikaKalseki** [comment]
Anything?

**Comment by ReikaKalseki** [comment]
So?
