### ISSUE TITLE
Feature Request: Config option for turning off ChromaticCrafts endless End

### ISSUE THREAD

**Issue by Iarinu** [ReikaKalseki/Reika_Mods_Issues#613]
This is a little bit between a bug report and a feature request.
The Problem is: when ChromaticCraft is installed it changes the worldgen of the End. The island in the middle continues infinite in ever direction.
This causes some problems, since there are other mods too, which generate stuff in the End. For example the Ender Lillys from Extra Utils, Draconium Ore from Draconic Evolution and the Ender Bees from Binnies. With an endless End its far to easy to collect insane amounts of resources, which aren't supposed to be get that easy and this breaks the entire balancing. The other problem is, that Draconic Evolution adds worldgen in the End too. Every 10.000 block in any direction it generates a special version of the Enderdragon. This one is really hard to fight but nearly impossible when are are dozens of damn vanilla pylons too. The fight just isn't designed to be under the End-island.
So please, add a config option for ChromaticCraft to turn the classic End worldgen back on. Please!

**Comment by TomeWyrm** [comment]
Amount of resource is not balance nor is it gating. Ender Lillies are renewable. Ender Bees are renewable via bee "overwriting". Draconium ore is obtainable in the overworld, hence infinite.

That being said, despite the complete lack of understanding on how balance works shown by @Iarinu this is still a good idea. Infinite end island breaks a very basic assumption, and hence should be configurable.

**Comment by DarkAyron** [comment]
I can confirm Iarinus problem. With the endless End it is much too easy to get tons of Draconium and build several max-sized energy cores. Killing the Ender Dragon was really difficulty with normal weapons, because he escapes often, finds another Ender-Crystal and comes back with full HP. Not to mention the Chaos Guardian, who one-hits you with armor-bypass and has much more HP. Killing him is hard enough with the normal world-gen with all that protected Ender-Crystals.

**Comment by Iarinu** [comment]
@TomeWyrm Ok, Bees can be reproduced, yes, but if you do so you still need to have pristine ones. Which usually takes a little bit of afford to get a lot of. With an infinit End on the other hand you have at least 4 hives in sight at every moment. And yes, I am aware that Draconium Ore spawns in Nether and Overworld but there they are really rare. I think about 1-5 Blocks per Chunk. In the End on the other hand they spawn more often. This means, that its far easier to get them there. So the difference should be, that there is more Draconium Ore but as disadvantage its strong limited due the size of the island. And if you really would know, what you're talking about, you should know that it usually takes a lot of time and automation to get a good amount of Ender Lilly Seeds. Even with speed farming with Lamp of Groth or Bloodmagic it still takes some hours to get some stacks. With an infinite End you can just run around some minutes and get Stacks of them.
This where my thoughts, when I said "balancing" and maybe you now understand what I mean.

**Comment by ReikaKalseki** [comment]
Ender Crystals need to be infinitely obtainable. A finite end ensures that that is impossible, unless other mods - whose existence I will neither assume nor expect - explicitly change that.

**Comment by TomeWyrm** [comment]
> @TomeWyrm Ok, Bees can be reproduced, yes, but if you do so you still need to have pristine ones. Which usually takes a little bit of afford to get a lot of. With an infinit End on the other hand you have at least 4 hives in sight at every moment. And yes, I am aware that Draconium Ore spawns in Nether and Overworld but there they are really rare. I think about 1-5 Blocks per Chunk. In the End on the other hand they spawn more often. This means, that its far easier to get them there. So the difference should be, that there is more Draconium Ore but as disadvantage its strong limited due the size of the island. And if you really would know, what you're talking about, you should know that it usually takes a lot of time and automation to get a good amount of Ender Lilly Seeds. Even with speed farming with Lamp of Groth or Bloodmagic it still takes some hours to get some stacks. With an infinite End you can just run around some minutes and get Stacks of them.
> This where my thoughts, when I said "balancing" and maybe you now understand what I mean.

Mineral Extractor or Digital Miner. Watch as all those assumptions are broken.

You're expecting a certain "kind" of balance. Don't do that. This is modded, resource costs, resource rarity, and "scarcity" are irrelevant. There are ways to automate ALL of the resources you have mentioned. Infinitely.

**Comment by Iarinu** [comment]
@ReikaKalseki 
OK, thats a point and I can understand that. But I saw in the configs an option which seems to allow the End to be reseted every time its unloaded. If this is the case there is a way to obtain infinite amount of Ender Crystals and you dont have to change the way the End generates, which causes trouble with other mods and the way the Enderdragon works. I mean, wouldnt reseting End be enough? This would at least solve the problems with the EnderDragon, the ChaosGuardians from DraconicEvolution and other Mods like Hardcore Ender Expansion or any similar mod.

**Comment by DarkAyron** [comment]
If the Ender Crystals needed to be available infinitely, why not making them respawn after some (real life) time has passed? This would make them infinitely obtainable, without breaking other mods, which assume the End is a finite island.

**Comment by TomeWyrm** [comment]
Because that is unintutive, and irrelevant with a resetting end.

A better suggestion would be making one of the two configs reliant upon the other being on to disable.

In other words, make the infinite end REQUIRE end reset on unload in order to be disabled. If End Reset is disabled, infinite end will be forced on.

**Comment by ReikaKalseki** [comment]
The latter half of that is fine. The former is not.

**Comment by Iarinu** [comment]
The suggestion from @TomeWyrm sounds like an idea.
I mean every suggestion so far is confusing for players who don't know whats going on. But the respawning Ender Crystals are the least conspicuous of them.

**Comment by Shahelion** [comment]
I see a problem with that, though.

Let's say Infinite End is enabled. This interferes with the worldgen from Et Futurum (which isn't too much), Hardcore Ender Expansion, and Draconic Evolution (which I don't have, so know very little about). HEE's worldgen alone is massive. Dungeons, towers, biomes, etc.

Now, if Infinite End is turned off, but that forces End Reset to be on? I don't want the entire dimension resetting every time I leave. What if I die there, and my grave gets wiped? What about all the HEE dungeons?

Both Infinite End Island AND End Reset should have configs to disable, neither should be dependent on the other.

HEE has a way to just regenerate the main island, without touching the rest of the dimension. I'd suggest you take a look at that. That would resolve the End Crystal issue without breaking two other mods.

**Comment by TomeWyrm** [comment]
We keep suggesting ingame mechanics that require no Chromatic Progression to trigger new dragons, or new islands, or other permutations as a replacement for the infinite end and end reset.

There is one other issue Reika: single player. I can reset the end manually when needed, so if I don't want infinite end because it breaks other mods… should I really be forced to have either on?

**Comment by ReikaKalseki** [comment]
There can be no case in which ChromatiCraft progression is impossible for any player. Also, I cannot assume that a player either can or will reset the end as needed; even in singleplayer, most players have little idea how to do this, and even less willingness to try.

**Comment by Shahelion** [comment]
I still think resetting the main island, while leaving the rest of the dimension intact, would be the best solution. New dragon, new crystals, win-win(-win?). HEE's way of doing it uses the Dragon Egg and a dungeon loot item. Not sure about DE, but I think it only respawns the dragon, no world regen.

**Comment by ReikaKalseki** [comment]
And there needs to be world regen too. Also, define "main island", in a format conducive to actually doing it in code.

**Comment by TomeWyrm** [comment]
See how other mods did it. It's obviously possible, why reinvent (or re-describe) the wheel?

Check Hardcore Ender Expansion.

**Comment by Iarinu** [comment]
A radius of 100 - 150 blocks around 0,64,0 in the end. Or a radius of 4-6 chunks, which is more roughly but a safer bet. An easy way to do the reset would be to let it regen from the seed or make a backup from the anvil file(s) of the main iland and roll it back. 
Or you just put your endless end into another dimension which is accessible after the end dragon is killed or so, this would be a solution too.

**Comment by TomeWyrm** [comment]
Apparently MC does dimensions really stupid, though exactly duplicating one is apparently much easier

**Comment by DarkAyron** [comment]
Respawning the Ender Dragon every time you leave shouldn't be forced. If you have Draconic Evolution installed, it implements an other way to respawn the Ender Dragon (and reactivate all the Ender Crystals). What about implementing somthing like that, with a way to disable it by config, if there is an other way to achieve this, which should be used. E.g. Draconic Evolutions resurection ritual.

**Comment by ReikaKalseki** [comment]
> See how other mods did it.

By entirely replacing the original system, which I have no desire to do.

**Comment by TomeWyrm** [comment]
> Also, define "main island", in a format conducive to actually doing it in code.

r.-1.-1.mca, r.-1.0.mca, r.0.-1.mca, and r.0.0.mca

Also giving players the capability via an in-game ritual or even command to trigger the reset would mean it doesn't screw up other mods. Put in safeguards like "not while loaded", and you CAN provide alternate methods of obtaining the ender crystals and resummoning the ender dragon. Just look at 1.9 and a whole host of mods. The point is that both current methods of ensuring a server full of people can get to endgame in your mod are directly interfering with their ability to play other mods, and utilize the end as a base location or as an enderman farm. 

How difficult would it be to make a clone of the end and have THAT end reachable via a special craftable portal using only pre-ender dragon progression materials, which could have infinite end, or always reset, or whatever?

**Comment by ReikaKalseki** [comment]
> How difficult would it be to make a clone of the end and have THAT end reachable via a special craftable portal using only pre-ender dragon progression materials, which could have infinite end, or always reset, or whatever?

That would be a complete mess, not only in implementation but in game as well.

**Comment by Iarinu** [comment]
> That would be a complete mess, not only in implementation but in game as well.

The modders from Mystcraft, Thaumctraft, Witchery, Random Things, Twilight Forest, Extra Utils and many more dont't seem to have a problem with that. So why should you?

> By entirely replacing the original system, which I have no desire to do.

You say so, but replaced the entire way the end work and do much more things with DragonAPI, that any API should do, like iterating the entire oredictionary for no reason or dig such deep into the worldsave data, that you need a patch, because FML can't load it anymore without it. Sorry, but this seems a little bit hypocritical for me.

We offered you so many solution, but you keep rejecting most of them for no apparent reason or at least no real reason.

Yes I got it, that you really want to make everything work exactly the way you intend, but you really shouldn't trampel over the work of so many other modders and then refusing to make a compromise at least. And before you now answer "Then don't use my mods": I would, but because you made it "all your way" I can't without completly destroying the world.

**Comment by Aivech** [comment]
Try removing CoFH Core and all mods dependent on it and see how well your world handles it.

**Comment by Iarinu** [comment]
> Try removing CoFH Core and all mods dependent on it and see how well your world handles it. 

First: I would do so, just to proof you that at least FML could load the world, just with many blocks missing.
Second: But I wont, because I should have to remove **EVERY** Mods using the RF API. You suggesting to remove Coremods for nearly every techmod which uses the RF API. Thats a much bigger thing than just removing DragonAPI, which have much less mods which depend on but does more stuff anyways.

**Comment by Aivech** [comment]
By the way, what is in the end that you can get so much of that you cannot get by other methods if the end is infinite?

**Comment by DaMachinator** [comment]
Just pointing out that in most packs CoFH Core also does oregen...

**Comment by Aivech** [comment]
Ender bees can be bred and multiplied that way, as well as with Calculator item duplicators or similar.

You can get all the draconium dust you will ever need with an RFTools dimension and the mob dragon dimlet. 

Same with Ender Seeds, as they can also be found in dungeon chests, so you can infinitely farm them with the loonium or abovementioned item duplicators. In addition, the plants sometimes drop an extra seed.

**Comment by Iarinu** [comment]
@DaMachinator We already discussed this earlier in this thread and @TomeWyrm made a good point about that. I am aware of all of this, as I already mentioned. The problem isn't that you can't get all of theese infinit otherwise, the problem is that an infinite End makes it much easier than it sould be.
But thats just a little problem which bugs me and apparently @DarkAyron too.

The main reason I am still asking for this, is because it breakes so many other mods, which are based on the End, entirely. Some where already mentioned in this thread, but I bet there are many more.

**Comment by Aivech** [comment]
> so many other mods

I have Draconic Evolution installed alongside Chromaticcraft. Care to elaborate?

NB: Not trying to prove you wrong, just want to be aware of any potential problems.

**Comment by ReikaKalseki** [comment]
> like iterating the entire oredictionary for no reason or dig such deep into the worldsave data, that you need a patch

I do neither.

**Comment by Aivech** [comment]
> iterating the entire oredictionary

I think he means logging it - I noticed this in the log files.

**Comment by TomeWyrm** [comment]
And despite not understanding why, he is correct that your workaround for the forge itemstack issue does require a patch to remove or it scrambles the world.

So, one reason you need an infinite end is the tiered ores. Another is the crystals. Yet another is the progress required via killing the dragon.

Are those 3 things the only reasons for the current reset mechanic and infinite generation, or did I miss something?

**Comment by ReikaKalseki** [comment]
Those three are the most obvious, but they may not be the only ones, or remain the only three.

**Comment by TomeWyrm** [comment]
I can't help but think a second End would solve the problems. That way it only generates vanilla and ChromatiCraft stuff, it can be infinite without screwing up another mod, and you have control over the dimension if some new idea comes up that would REALLY screw over other mods instead of being a minor-to-major nuisance like it is right now.

What would make that messy? You're duplicating a dimension that already exists, that can't have the same problems that creating a dimension from scratch did.

**Comment by Aivech** [comment]
So you can respawn the dragon (its a config option). I had fun fighting multiple dragons due to teleporters and leaving the end w/o killing the existing one.

Why not make floating "End pillars" or something scattered throughout the end that contain Ender Crystals?

**Comment by Iarinu** [comment]
> What would make that messy? You're duplicating a dimension that already exists, that can't have the same problems that creating a dimension from scratch did.

Like I said and Raika ignored: (like every good point anyone makes here)

> The modders from Mystcraft, Thaumctraft, Witchery, Random Things, Twilight Forest, Extra Utils and many more dont't seem to have a problem with that. So why should you?

And yes, I ment the workaround when I said "iterating the ore dictionary"

> I have Draconic Evolution installed alongside Chromaticcraft. Care to elaborate?
> NB: Not trying to prove you wrong, just want to be aware of any potential problems.

DarkAyron and I already did at the beginn of this thread/issue.
But we already found the next one with DraconicEvolution and ChromaticCrafts infinit End. With the new version of DraconicEvolution the Wordgen arround the Chaos Guardians had changed. Now its supposed to be more like the original iland which makes ChromaticCrafts infinit End just make mess up things even more.

Oh, and a friend of mine found out something interessting: By taking a look at the source code from ChromaticCraft he found out, that Raika does consider if Hardcore Enderexpansion is installed. So he whrote a little dummy Mod, which does only one thing: Telling its Hardcore Enderexpansion. It worked, now the end spawned normal again. Besides that everyone should have the possibility to disble this without have to whrite a mod for this my question is:
@ReikaKalseki Why do you accept a non-infinit end when Hardcore Enderexpansion is installed but still refuse to step out of the way for all thoose other mods which want to add something new to the End?
BTW: We are thinking about releasing the "Hardcore Expansion Dummy" Mod, so nobody has to deal with you ignoring every suggestion or every point in a discussion you don't know anything to respod.

**Comment by Aivech** [comment]
> (like every good point anyone makes here)

Don't prod the dragon, bad things happen. I suggest accepting that it's his mod and rolling with it.

So it messes up the Chaos islands. How so? Are they nonexistent? Buried in the infinite End land? Floating above it? REALLY messed up, like Far Lands messed up?

The reason for that is that HEE provides a way to respawn the dragon, which IIRC also respawns the ender crystals and the towers on which they sit. Almost like MC 1.9.

**Comment by Iarinu** [comment]
The Chaos Ilands are burried under the regular End worldgen which isn't supposed to be at this place. Because of this the special Ender Crystals implemented by Draconic Evolution are burried to and since the Chaos Guardian kills you in notime (because his his damageclass has armor bypass and doest 20 points damage per attack) its impossible to kill hin because you can't reach the crystals and destroying them. In this case you cant use any distance weapons and can't even dig because the Guardin keeps pushing you around hard. I am not sure if the regular Ender Crystals add to this problem, but it's possible.
Pretty much gamebreaking I would say.

**Comment by Aivech** [comment]
Doesn't Blood Magic have some kind of projectile AoE dig spell you can use for this?

**Comment by Shahelion** [comment]
As does Ars Magica, and Thaumcraft as well. Even Botania, although inefficient. Pretty much all magic mods have some sort of ranged digging.

Wait, so with Hardcore Ender Expansion, the End generates normally? Or it simply does the check? I haven't entered the End in my current world yet just in case.

**Comment by Iarinu** [comment]
Yes, I am aware of ranged mining tools or AOE minining/damaging tools/spells.
It just dosen't help when you get pushed arround by the Chaos Guarding every so often second and have no time to aim properly. Yes, it makes it a little bit easier but overall its still impossible

> Wait, so with Hardcore Ender Expansion, the End generates normally? Or it simply does the check? I haven't entered the End in my current world yet just in case.

Yes, it's a simple if condition which checks if a mod named "Hardcore Ender Expansion" is installed. If it matches, it's skipping the entire change of the end.

**Comment by Aivech** [comment]
The blood magic projectile AOE spell has a MASSIVE AoE. Almost impossible to miss - its like 16x16. DW20 used it to destroy the end in his last Let's Play.

**Comment by ReikaKalseki** [comment]
> Yes, it's a simple if condition which checks if a mod named "Hardcore Ender Expansion" is installed. If it matches, it's skipping the entire change of the end.

HEE replaces the entire end world generator, overriding any changes I - or for that matter anyone else - makes. And no, it is not a problem, because _I specifically worked with Chylex to ensure that it broke nothing on my end_. It is not a "simple if condition" - the break [here](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Auxiliary/ChromaASMHandler.java#L99) is only to ensure I do not waste time ASMing an unused class, and has **no** effect on actual generation - and I very much resent you saying that in a manner which very much sounds like you are trying to make it sound like you read and more importantly **understood** the source, lending authenticity to your ignorance. My patience for false accusations and needless hostility is depleted. So much so, in fact, that:

**Comment by ReikaKalseki** [comment]
@TomeWyrm: The idea of slaving the two configs together works in that it guarantees that there is always an infinite supply of ores, crystals, and the dragon. Yes, it is somewhat of a clumsy solution, but nothing else thus far has satisfied the requirements:

1 - It has to be able to regenerate all three resources in infinite amounts
2 - It cannot require out-of-game involvement from anyone, be it player or server admin
3 - It cannot be something a pack dev or server admin could disable (and bring back the issue)
4 - It has to function as well with _only_ ChromatiCraft as it does in any large pack
5 - It cannot be unperformant or damaging to pack/mod balance
6 - It has to be thematically fitting, both for ChromatiCraft's design as well as Minecraft, which CC tries to build on
7 - It cannot be arduous to implement
8 - It has to make sense to a player, and not be readily confusing

Dimension duplication fails on the last three, possibly four, points.

**Comment by TomeWyrm** [comment]
The problem being that the current method fails 2, 4, and 5 (possibly 8 as well) from the perspective of other mods and mod packs. It requires intervention from the pack dev, server admin, or player to allows certain other mods to work, it functions WORSE in a large pack because the chances of having an end-affecting mod increases, it thereby damages pack/other-mod balance, and because it breaks two vanilla assumptions, it conceivably makes it confusing.

How about a "ritual" involving the exit portal that will reset the end on next unload? Maybe have two variants, one that will trigger infinite end generation, and one that will trigger standard gen? Basically the idea from 1.9, except not using the End Crystals. Place the rituals in the lexicon behind an early progression flag. Involve no end generation in the actual ritual to avoid this being a problem on an established but unhelpful server.

Also the special end would not fail 8, nor would it necessarily fail 6. You could have a second portal, or the ability to "shift" the destination of the existing portal to a similar, but slightly different end (using the endless generation and constantly resetting). As for 7, you still have yet to explain how making a second end would be somehow meaningfully difficult. I understand that generating a new dimension is a problem... but you're not. You're duplicating already existing content.

**Comment by ReikaKalseki** [comment]
Yes, a special end will fail both 6 and 8. For 6, it is because within MC the end is treated as a singleton, as one place. For 8, it is because 99% of players are not going to know the difference between the two ends. They will look similar, and to them, they will be the same.

Also, duplicating all the behavior of the end does not mean I would not still have to rebuild half of it, doubly so seeing that I would need to make changes to one of the core classes.

**Comment by TomeWyrm** [comment]
Eh, I think you're putting too much stock on people thinking "this is the normal end" when you could do something as simple as changing the skybox texture, when coupled with the whole "end goes on forever" to signify to people, hey this thing is just a bit different. Having to go through a specially modified portal in the actual end could easily help.

Even if a second version is out, the special end portal ritual to trigger a regen of either "normal generation" or "endless End" (the oxymoron of which just makes me giggle) would be more friendly to other mods, and allow you to have builds in the end. How difficult code-wise would toggling the generation be while the game is running?

**Comment by ReikaKalseki** [comment]
> How difficult code-wise would toggling the generation be while the game is running?

Difficult. It is global, not player-specific. Also, it would reset the instant the server restarted.
On top of that, how to handle conflicts?

**Comment by TomeWyrm** [comment]
Is there any reason (besides time investment) why something similar to the end, but not the end could not be made? There are probably a dozen lore ways to justify the creation of an infinite end. "Time travel", it being the "home dimension" for the end creatures who are trying to invade our world, there could be multiple ends (there are different ends for every seed after all, so I challenge your assertion that the end is necessarily a singleton), you could make this secondary dimension similarly themed but different so it isn't "The End" but it does feature endermen/endstone/dragons (ender forest already sets the stage for endermen being heavily present in a non-end place) and end ores... I'm sure there are more ideas that someone actually creative could come up with.

How much time would be wasted by looking into the feasibility of a second "end" which is infinite? I'm sure you could have a lot of interesting things to do in an "end" you control fully. It opens up avenues for all kinds of things that having to play nice with other mods would prevent you from doing. You could make the end into a sky islands type world, or change the initial island into an arena with "normal" islands surrounding it, or a bunch of other things. Plus it prevents any mod interaction problems I can think of.
