### ISSUE TITLE
Glider Chestplate [Feature Request]

### ISSUE THREAD

**Issue by OmegaHaxors** [ReikaKalseki/Reika_Mods_Issues#614]
We can already make glider chestplates by combining glider jetpacks with steel chestplates.

What I want is the ability to make a glider chestplate without the need for a jetpack attachment, to make early-game travel easier.

How to make? 3 steel in a line over a chestplate in the worktable, similar to with the jetpack.

**Comment by ReikaKalseki** [comment]
The jetpack item controls all of that code, meaning I would have to totally redesign the system, and in a way much less expandable and more complex at that.
