### ISSUE TITLE
[CC] Lighted Leaves drop Shimmering Saplings even when sheared

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#615]
The leaf block drops still, but I thought that shearing leaves meant saplings wouldn't drop?

Also, the leaves aren't stacking together. they seem to have divided themselves into 3 stacks of leaves, from shearing a single tree. Although they are all identical.

**Comment by TomeWyrm** [comment]
Vanilla "feature".

As for the second one that's because there are 3 different metadatas for the leaves... for some reason.

**Comment by Builderb0y** [comment]
They change their metadata on random tick, it's how the glowing spots on them move around.

**Comment by Shahelion** [comment]
Alright, that makes sense. Do these trees actually do anything, though? Other than seemingly randomly-oriented particles.

**Comment by TomeWyrm** [comment]
Yes they do. Try using enchanted tools with various enchants on them... you might be pleasantly surprised.

Also the blowing particles aren't random. Try to find the pattern :-)

**Comment by Shahelion** [comment]
God damn I love this mod...

Time to hunt some secrets!

**Comment by TomeWyrm** [comment]
For me it's more knowing the answer and giving other people cryptic hints :-)

I enjoy their hunt vicariously.

**Comment by Aivech** [comment]
> Also the blowing particles aren't random. Try to find the pattern :-)

Or look thru the code and decipher it.

**Comment by Shahelion** [comment]
Well yeah, but that's no fun.

**Comment by Aivech** [comment]
I just tried it, but couldn't find the relevant section.

**Comment by Aivech** [comment]
BTW, the Horn of the Canopy works on rainbow trees - almost as insane as a Bedrock Axe

**Comment by Shahelion** [comment]
Horn of the Canopy works on all leaves, doesn't it? Except for Lighted Leaves, but those aren't exactly normal leaves.

**Comment by Aivech** [comment]
Are the lighted leaves the ones that grow on the Lumen Tree?

**Comment by Shahelion** [comment]
The leaves from the Shimmering Sapling.

**Comment by TomeWyrm** [comment]
> Or look thru the code and decipher it.

And actively subvert half the point of the mod. No thanks.

**Comment by Aivech** [comment]
> And actively subvert half the point of the mod. No thanks.

Well, given that >75% of what I know about Chromaticcraft is from watching LP's and lurking on Reika's MCF thread and the FTB forums and subreddit, it really isn't spoiling much more...
