### ISSUE TITLE
Crash with Growthcraft Community Edition and RotaryCraft

### ISSUE THREAD

**Issue by nmarshall23** [ReikaKalseki/Reika_Mods_Issues#616]
When adding [Growthcraft](http://minecraft.curseforge.com/projects/growthcraft-community-edition) the Bundle version. Well, just the jar `growthcraft-1.7.10-2.4.0-complete-core.jar` will trigger (this crash)[https://gist.github.com/nmarshall23/2a7e48e8ee3ee003832f]. My game does not crash when I add the Complete version. 

I've also reported this crash to the Growthcraft [team](https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/202)

**Comment by ReikaKalseki** [comment]
Known and entirely on Forestry's end; their GrowthCraft handler pulls null items (specifically [here](https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/plugins/compat/PluginGrowthCraft.java#L95)) and inserts them into the Centrifuge recipe, whereupon the DragonAPI interfacing crashes as it does not accept null items. Their error is assuming all modules of GrowthCraft are present if the core is.
