### ISSUE TITLE
[CC] Kuro Pylon has no color

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#617]
The pylon orb itself, as well as the little light particles that fly off, have no color. Also, there is no aura around the edge of the screen when drawing close, yet the pylon appears to be structurally intact.

![2016-02-09_12 42 56](https://cloud.githubusercontent.com/assets/6917535/12930170/913b8cc4-cf2b-11e5-96b4-af228ef06d24.png)
![2016-02-09_12 43 21](https://cloud.githubusercontent.com/assets/6917535/12930171/913d2dd6-cf2b-11e5-88fb-0a4229da3131.png)
![2016-02-09_12 49 21](https://cloud.githubusercontent.com/assets/6917535/12930176/99865684-cf2b-11e5-8b5b-2fd9a3ad5c29.png)

**Comment by Shahelion** [comment]
Ok, it seems that there is indeed an edge aura, but it's nearly impossible to see. 
![2016-02-09_12 52 24](https://cloud.githubusercontent.com/assets/6917535/12930250/049d806e-cf2c-11e5-9be3-581765b4d6ff.png)

**Comment by ReikaKalseki** [comment]
Additive blending.

**Comment by Aivech** [comment]
What does that mean?

**Comment by Shahelion** [comment]
What?

**Comment by TomeWyrm** [comment]
Basically, it's unavoidable. That color is black, and additive blending adds the two colors together... what do you get with 100+0? 100. Kuro only adds a teeny tiny amount to colors, which is STUPID tiny, and hence basically unnoticeable.

Unfortunately using the 16 colors, there's no blending (which is required for transparency) that looks good and works in all cases.

**Comment by Shahelion** [comment]
It looked normal before, though. This is the first time I've seen a Kuro pylon that looked like this.

What is being blended with the black here, though? That's what I don't get.

**Comment by TomeWyrm** [comment]
Whatever else is on your screen

**Comment by ReikaKalseki** [comment]
![](http://docs.garagegames.com/artist/official/3D%20Studio%20Max/AddiBlend.jpg)
![](https://www.scirra.com/images/articles/particlesadditive.png)
