### ISSUE TITLE
Chromaticraft dye trees spawn in kelp forests

### ISSUE THREAD

**Issue by Rdjrjqouqcu** [ReikaKalseki/Reika_Mods_Issues#618]
The title is very self explanatory.  This was generated with RTG, however I suspect it will occur with Biomes O'Plenty worldgen as well.

![fb591813ea9f84b0703c84c8c48ab276](https://cloud.githubusercontent.com/assets/12042902/12939034/0431a97c-cf89-11e5-95a5-4431691b50e2.png)

![8b86aa87fc97cea4aa933c7bc21fd3c4](https://cloud.githubusercontent.com/assets/12042902/12939037/0de46270-cf89-11e5-8e53-f12ad7322496.png)

**Comment by ReikaKalseki** [comment]
Is the biome tagged as forest? Ocean?

**Comment by Rdjrjqouqcu** [comment]
I think it is registered as Ocean:

https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.8.9-3.0.x/src/main/java/biomesoplenty/common/biome/overworld/BiomeGenKelpForest.java#L38

**Comment by ReikaKalseki** [comment]
That is not a BiomeDictionary registration.

**Comment by ReikaKalseki** [comment]
That is not a BiomeDictionary registration.

**Comment by Rdjrjqouqcu** [comment]
I see.  I'm not sure what I'm supposed to be looking for.  Maybe this?:

https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.8.9-3.0.x/src/main/java/biomesoplenty/common/init/ModBiomes.java#L495

registerBiomeToDictionary(BOPBiomes.kelp_forest, Type.WATER, Type.OCEAN);

with:
private static void registerBiomeToDictionary(Optional<BiomeGenBase> biome, Type...types)
    {
        if (biome.isPresent())
        {
            BiomeDictionary.registerBiomeType(biome.get(), types);
        }
    }

**Comment by ReikaKalseki** [comment]
Yes, that is the registration. Now I am wondering why the dye trees spawn at all in ocean-type biomes...

**Comment by Shahelion** [comment]
Perhaps use this as inspiration for future sea-sprouting trees? Would make oceans a little more interesting.

**Comment by ReikaKalseki** [comment]
It looks like their biome does not clear the treesPerChunk check, tricking the tree generator to try generating them. For some reason, it also generates air pockets underwater, and thus the trees. I added another check to fix this.
