### ISSUE TITLE
Geiger counter does not detect radiation from nuclear waste disposal drums

### ISSUE THREAD

**Issue by jackjjames** [ReikaKalseki/Reika_Mods_Issues#619]
Whilst using a charged Geiger counter I was unable to detect radiation coming from fueled disposal drums.

I can only see this as a bug, the disposal drums clearly generate enough radiation to kill. So why do they not trigger the Geiger counter?

Playing ReactorCraft with a serious and realistic mindset as we do on our server, not picking up radiation on our Geiger counters implies that the area is safe, when it is not. Fine, the book says that in close proximity they drums generate lethal radiation but should we being living by book and not our perception and tools?

If this is a game design decision and not a bug, can I propose that a small amount of noise on the Geiger counter coming from disposal drums and even fuel containers may make the identification of contamination more interesting and drive realistic facility design decisions to separate these areas to allow identification of contamination.  

Thanks for some great mods!

**Comment by ReikaKalseki** [comment]
The geiger counter only detects actual radiation entities, which the drums are not. And there is no performant way to find near drums.
