### ISSUE TITLE
Electricraft superconducting cables lose coolant when insulated

### ISSUE THREAD

**Issue by Demosthenexx** [ReikaKalseki/Reika_Mods_Issues#62]
If you fill the wires with coolant, and then craft them with wool to insulate them, you lose the coolant and have to refill them again. v6f

**Comment by ReikaKalseki** [comment]
This is not a bug. Crafting is not NBT sensitive, and though custom recipe objects can be written, it is a pain, can be unstable, breaks a lot of handlers, and is vulnerable to things like recipe unifiers.

**Comment by ljfa-ag** [comment]
Maybe it makes sense to have filled wires have different metadata?

**Comment by ReikaKalseki** [comment]
Filling is an NBT value, and changing it now would break every world as well as making the enum handling messy.
