### ISSUE TITLE
Crash with Railcraft

### ISSUE THREAD

**Issue by bookerthegeek** [ReikaKalseki/Reika_Mods_Issues#622]
[fml-client-lates.log](https://gist.github.com/bookerthegeek/8683173f552230266bb4)
[Crash Report](https://gist.github.com/bookerthegeek/ceb61a5e7c3d92e68f4a)

It seems that there is an issue with Railcraft and ElectriCraft. As stated in the post [HERE](https://github.com/CovertJaguar/Railcraft/issues/622#issuecomment-115155174) that the full logs are needed to see what is happening, I have linked them above. This is the smallest set of mods I can get to have both Railcraft & ElectriCraft.

Relevant Parts of the Crash Report: (Truncated) 

```
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mods/railcraft/common/items/ItemCrowbar
Caused by: java.lang.NoClassDefFoundError: mods/railcraft/common/items/ItemCrowbar
Caused by: java.lang.ClassNotFoundException: mods.railcraft.common.items.ItemCrowbar
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/tools/IToolWrench
Caused by: java.lang.ClassNotFoundException: buildcraft.api.tools.IToolWrench
```

Mod List

```
Forge 10.13.4.1614 
DragonAPI 1.7.10 V10d.jar
RotaryCraft 1.7.10 V10d.jar
ElectriCraft 1.7.10 V10b.jar
Railcraft 1.7.10-9.8.0.0.jar
```

If any other information is needed I'll be more then happy to provide asap. I just need to know what is needed.

Thanks and have a wonderful day.

Cross posted [HERE](https://github.com/CovertJaguar/Railcraft/issues/774)

Related Issues:
- Railcraft [#622](https://github.com/CovertJaguar/Railcraft/issues/622)
- Reika Mods [#110](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/110)

**Comment by ReikaKalseki** [comment]
I doubt I can fix this. Try adding BC's IWrench to the DragonAPI jar.

**Comment by bookerthegeek** [comment]
... Um. I don't Java.

If you can barney style the instructions I will attempt it.

**Comment by kolatra** [comment]
It's not Java. All you need to do is open the BuildCraft jar with something like WinRar or 7Zip, navigate to buildcraft/api/tools/IToolWrench.class, and copy that class file to the DragonAPI jar which you open again in WinRar or 7Zip.

**Comment by bookerthegeek** [comment]
What did I do wrong? Still getting the same crash.

![Inside DragonAPI](http://goo.gl/DmI8KP)

**Comment by kolatra** [comment]
Ah sorry, you need to copy the whole directory structure, so in the DAPI jar you would put the buildcraft folder that just contains the api/tools/IToolWrench.class.

**Comment by bookerthegeek** [comment]
```
...\DragonAPI 1.7.10 V10d.jar\buildcraft\api\tools\IToolWrench.class
```

Grabbed from the Buildcraft Core  and placed into the DAPI caused it to load without any glaring issues. Sadly I can neither verify that this is; without consequence, distribute that file to players of my mod-pack, or know why this happened in the first place.

Good to know it is fixable, and thank you for the help.

**Comment by ReikaKalseki** [comment]
You are free to distribute the modified DragonAPI jar, as all you have done is add in a class that should already be present. And no, this will not break anything else.

**Comment by bookerthegeek** [comment]
Thank you.
