### ISSUE TITLE
HarvestDropsEvent for several auto-breakers

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#623]
Loosely related to https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/387

Several machines perform block breaks, but don't fire the HarvestDropsEvent. Those are RotaryCraft's Woodcutter and Boring machine, and ExpandedRedstone's Block Breakers.

Would it be possible to add those events to the code segments in question?

**Comment by ReikaKalseki** [comment]
Done for all cases except the silk-touched Borer, as I want that to be entirely under my control.

**Comment by ghost** [comment]
Yeah, I can understand that. Thank you!
