### ISSUE TITLE
Radiation spreading in the void, causing severe TPS drop

### ISSUE THREAD

**Issue by Meller127** [ReikaKalseki/Reika_Mods_Issues#625]
Im using the void dimension from ExtraUtilities "The Last Millenium" to set up my reactor, i dropped nuclear waste in the void. And its starts to spread from Y 0 upwards.

Edit: It also spreads down below Y 0, so im trying to figure out how to remove the radiation with MCEdit because i cant select blocks under Y 0

After using command, server is back to normal.
/cofh killall radiation

[13:08:04] [Server thread/INFO]: Removed 12594 entities. (ºc12594ºfxºeReactorCraft.Radiationºf)

Minecraft 1.7.10
Reactorcraft V10d
Forge 1614
![radiationoverview](https://cloud.githubusercontent.com/assets/13392710/13071872/80291bf2-d496-11e5-9a82-ca6531ae96df.png)

50% ish selected over 6000 blocks of radiation
![radiationcount](https://cloud.githubusercontent.com/assets/13392710/13071876/8387a02a-d496-11e5-9a57-b92996e8d838.png)

**Comment by ljfa-ag** [comment]
There is a creative mode tool for cleaning up radiation, try that for removing

**Comment by Meller127** [comment]
The problem is that i cant move in my void dimension TPS 0 (all other dimensions is working fine with 3.5ms), so i cant remove it from in game.

**Comment by Aivech** [comment]
Could you not use an NBT editor tool to edit the save files and remove it that way?

**Comment by Meller127** [comment]
So i deleted chunks 16 in total, and now its running fine again, need some way to control so that no one is dropping waste in the void on my server.

**Comment by Aivech** [comment]
If you absolutely cannot use the intended method of getting rid of waste, does a matter compressor (AE2 machine for making singularities) accept it?

**Comment by Meller127** [comment]
I will direct all waste to the matter or a nullifier

Still a bit of manual clean up lol :D
![2016-02-16_13 00 51](https://cloud.githubusercontent.com/assets/13392710/13075688/6717205c-d4ad-11e5-8ae3-5752f00ac6e7.png)

**Comment by Aivech** [comment]
try /cofh killall radiation

**Comment by Meller127** [comment]
THANK YOU!

All radiation gone, and server rollback in progress. Nice

**Comment by Aivech** [comment]
yeah...I was on a server before, where there was some chunkloading issue with a reactor or the waste canister that made radiation keep building up - that was how they got rid of it.

Then they made the owner of said reactor fix their stuff.

**Comment by Meller127** [comment]
That would even kill the Hulk i think.

[13:08:04] [Server thread/INFO]: Removed 12594 entities. (ºc12594ºfxºeReactorCraft.Radiationºf)

**Comment by Aivech** [comment]
oh gosh

How is that even possible? I thought there was a cap on the number of entities allowed to exist.

**Comment by Meller127** [comment]
Yeah it should be atleast, we have to wait for Reika to respond. Maybe a simpel bugfix

**Comment by ReikaKalseki** [comment]
There is supposed to be a cap. Also, that nuclear waste is still there, accumulating radiation; it cannot be disposed of in the void.

**Comment by Aivech** [comment]
/cofh killall item should get rid of the waste if you aren't going to go down there and fish it out :grinning:

**Comment by ReikaKalseki** [comment]
I applied another spawn cap.
