### ISSUE TITLE
Mekanism Jetpack breakable by RotaryCraft Bedrock Sword

### ISSUE THREAD

**Issue by BlueAgent** [ReikaKalseki/Reika_Mods_Issues#627]
https://github.com/aidancbrady/Mekanism/issues/3105
Relevant files:
https://github.com/ReikaKalseki/RotaryCraft/blob/f7e9b3f91553aae85449dd5b5ce419456a74c32c/Items/Tools/Bedrock/ItemBedrockSword.java
https://github.com/aidancbrady/Mekanism/blob/bfd32a1c3e5cc97b90040e43270c6e87d5180189/src/main/java/mekanism/common/item/ItemJetpack.java

Mekanism overrides damageArmor from ItemArmor to do nothing.
damageArmor is used when the entity wearing the armor is taking damage.

The bedrock sword in addition to dealing damage, does durability damage directly to the item. https://github.com/ReikaKalseki/RotaryCraft/blob/f7e9b3f91553aae85449dd5b5ce419456a74c32c/Items/Tools/Bedrock/ItemBedrockSword.java#L130

Mekanism sets the maxDamage of the item. https://github.com/aidancbrady/Mekanism/blob/bfd32a1c3e5cc97b90040e43270c6e87d5180189/src/main/java/mekanism/common/item/ItemJetpack.java#L40
This causes the jetpack to become damageable.

Mekanism uses the durability value of the item to display the fuel level. If the item is not damageable, the damage bar does not render.

Potential solution:
Set maxDamage to 0 to make the item unbreakable.
Override Item.showDurabilityBar to return true. (By default it returns true if the item is damageable).
Override Item.getDurabilityForDisplay to return the fuel level. (By default it returns the ratio damage/maxDamage)

Off topic: I love both mods and want to make a mod too some day.
Edit: Changed links to files to permalinks

**Comment by Aivech** [comment]
The Mekanism jetpack always took durability damage for me when I PvE'd with it. It has 100 points of durability, you can see them on the tooltip.

**Comment by BlueAgent** [comment]
@DaMachinator The durability is used by Mekanism to show the fuel level. It does not actually break like normal armour (under damage from entities).

**Comment by Aivech** [comment]
The durability fraction on the tooltip does not seem to care about fuel level.

**Comment by BlueAgent** [comment]
@DaMachinator Here is an example of where the durability is set to be equal to the fuel level.
https://github.com/aidancbrady/Mekanism/blob/bfd32a1c3e5cc97b90040e43270c6e87d5180189/src/main/java/mekanism/common/item/ItemJetpack.java#L222
Edit: Changed to permalink

**Comment by Aivech** [comment]
My mistake, I must have looked at it only just after I refilled it or it was almost done filling.

**Comment by BlueAgent** [comment]
@DaMachinator I forgive you :) It is good to make sure that an issue report is accurate.

**Comment by ReikaKalseki** [comment]
Does the durability setting actually break the jetpack and/or cause other glitches (and if so, underwhat conditions)? I kind of like the idea of it causing fuel loss (ie leakage due to cuts into the tank).

**Comment by BlueAgent** [comment]
@ReikaKalseki Yes, the jetpack gets broken with a full jetpack or empty jetpack, tested with both the armored jetpack and the normal jetpack.
The max durability is 100 and the item takes 100 points of durability damage when hit, so it breaks every time.
I'm not sure of any glitches with the sword since the jetpack gets destroyed so I don't get to use it mid way being broken.

Having fuel loss on hit seems like a pretty interesting interaction.
The Mekanism jetpack holds 24000 units of hydrogen gas (by default), and it consumes 1 unit per tick.

Edit:
There's a similar interaction with Ars Magica's Fire guardian "Melt Armor" spell, which does have some interesting effects. I describe it here: https://github.com/aidancbrady/Mekanism/issues/3105#issuecomment-185568444

**Comment by ReikaKalseki** [comment]
How does 100 points of durability yield 24000 units of fuel?

**Comment by BlueAgent** [comment]
@ReikaKalseki The durability is used to display the fuel level, it's not actually used as durability in the usual way.

It is updated whenever the fuel level changes: https://github.com/aidancbrady/Mekanism/blob/bfd32a1c3e5cc97b90040e43270c6e87d5180189/src/main/java/mekanism/common/item/ItemJetpack.java#L222

The range is from 0 (100 damage) when there is no fuel to 99 (1 damage) when the jetpack is full (since if 100 the durability bar would disappear).

**Comment by ReikaKalseki** [comment]
In which case I would have to edit the NBT to actually change the fuel level?

**Comment by TomeWyrm** [comment]
It certainly looks like that.

**Comment by ReikaKalseki** [comment]
Now there is a question on how to detect it. ISpecialArmor is not exclusively used for unbreakable armor items, and there is no way to tell that the method body is empty.

**Comment by BlueAgent** [comment]
@ReikaKalseki Without including Mekanism, or reflection, you would have to edit the NBT.
The jetpack implements IGasItem.
removeGas seems to just return null.
getGas and setGas work and they will also update the durability bar as well.

Maybe an assumption could be that gas storing items are unbreakable?
The two wearable gas storing items in Mekanism are:
Jetpack (and Armored version)
Scuba Tank

Edit:
Mekanism has fixed the item and it is unbreakable now. https://github.com/aidancbrady/Mekanism/issues/3105#issuecomment-186636311
Having the sword interact with the gas still sounds great :)

**Comment by ReikaKalseki** [comment]
This was not fixed...

**Comment by BlueAgent** [comment]
There is no commit from Mekanism that fixes this yet, despite @aidancbrady saying that it is fixed.
Are you still planning to have the sword remove gas on hit? It sounds like a great interaction.

Edit: Fixed on Mekanism's side as of March 18th.
https://github.com/aidancbrady/Mekanism/commit/650b725567f97d236864b98fcc79aac8518b5d7e

**Comment by ReikaKalseki** [comment]
Done. It removes 1+25% of the gas inside per hit.
