### ISSUE TITLE
Chroma Collector Issue

### ISSUE THREAD

**Issue by Keyarose** [ReikaKalseki/Reika_Mods_Issues#628]
The Chroma Collector will accept Liquid Xp from EnderIO, but will not process it into Liquid Chroma.

Chromaticraft V10d
EnderIO 2.3.0.423_beta

Setup screenshot
![2016-02-18_09 22 00](https://cloud.githubusercontent.com/assets/1906772/13144461/1f640494-d621-11e5-9b2c-a809cd1a633d.png)

**Comment by Aivech** [comment]
How fast can the chroma collector take EXP from your player?

**Comment by ReikaKalseki** [comment]
Is OpenBlocks installed? Currently (I may change this) DragonAPI can only accept one type of liquid XP.

Also, what is the fluid name and XP/mB conversion ratio?

**Comment by Keyarose** [comment]
OpenBlocks is not installed. When it is EnderIO disables their liquid xp and uses OpenBlocks' instead.  As far as I know EnderIO's liquid xp is a carbon copy of OpenBlocks'

**Comment by Keyarose** [comment]
Here is where EnderIO is defining their liquid xp(around line 490):
[https://github.com/SleepyTrousers/EnderIO/blob/f3ba01ab26d558c53bb6eaa8e30b68dfc27c2876/src/main/java/crazypants/enderio/EnderIO.java](url)

**Comment by ReikaKalseki** [comment]
The link is a 404.

**Comment by Keyarose** [comment]
Whoops, not very familiar with the github markup.
Fixed:
[https://github.com/SleepyTrousers/EnderIO/blob/f3ba01ab26d558c53bb6eaa8e30b68dfc27c2876/src/main/java/crazypants/enderio/EnderIO.java](https://github.com/SleepyTrousers/EnderIO/blob/f3ba01ab26d558c53bb6eaa8e30b68dfc27c2876/src/main/java/crazypants/enderio/EnderIO.java)

**Comment by TomeWyrm** [comment]
always go with the master branch on the left hand dropdown unless you know what you're doing with branch selection

https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/EnderIO.java

**Comment by Keyarose** [comment]
Ah sorry, I didn't check the branch when I found the file through the search.

**Comment by ReikaKalseki** [comment]
Done.
