### ISSUE TITLE
Crashing: Forestry 4 and RotaryCraft 10

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#632]
I've sat on this one, because I figured that it would take some time for things to get sorted out.  However, it's been two months, and the issue continues to persist, so I figured I'd at least make a ticket out of it.  (I probably should make 2)

The latest versions of RotaryCraft and Forestry are causing the game to crash (specifically, at "Loading - Initializing mods Phase 3" (5/7).  How latest, you ask?  Well, RotaryCraft is v10d, while the version of Forestry I'm attempting to use is 4.2.8.56... so it's pretty up-to-date.

I've done some searching, but so far, I've seen no references to this issue, so I'm worried I'm doing something wrong.  But, lacking anything to go on, I figured I'd post the bug report anyway.

Here's the link to the log from the launcher:  http://paste.atlauncher.com/view/4c832b27

I don't know if you can help, but I hope I offered enough information for you to have some idea of what can be done.

**Comment by zemerick** [comment]
Have you asked over at Forestry? It looks to be their plugin, not anything on Reikas end that is crashing.

Is there a config to disable rotarycraft integration? It looks like the "plugin" is in their jar file, so probably can't just remove it. If you can't find a config, I would try removing the plugin anyways and see what happens.

**Comment by ghost** [comment]
I was going to send something there next, just double-checking here first.  I'll post the bug there, then.

Okay, so I copy/pasted the issue to ForestryMC/ForestryMC#1075  This should link the two bug reports together, in case one or the other comes up with anything to resolve the issue.

**Comment by Nirek-K** [comment]
Any plugin can be disabled in the config entirely. As to the error, will be fixed momentarily and does not actually have anything to do with RotaryCraft, sorry.

**Comment by zemerick** [comment]
Figured it would be, and thanks for the confirmation.
