### ISSUE TITLE
Checking Furnace recipes shows only Friction Heater recipes

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#633]
When clicking the smelting arrow to show NEI's Furnace recipes, it goes straight to the Friction Heater.

Normal furnace recipes can still be viewed via the Fuel recipes.

https://i.gyazo.com/ed7606cf75c79131a2c16fab7cd4da94.mp4

**Comment by ReikaKalseki** [comment]
Not for me.

**Comment by MaciejMalczyk** [comment]
So @ReikaKalseki  it's Forge issue. On Forge 10.13.4.1566 everything works well.
Newer Forge versions are broken.
Still Nei Hints works bad but Furnace smelts things propertly.

**Comment by ReikaKalseki** [comment]
Probably something to do with their fuel handler change.
