### ISSUE TITLE
Repeater energy falloff

### ISSUE THREAD

**Issue by StrayCargo** [ReikaKalseki/Reika_Mods_Issues#634]
I have built about 32 repeaters about 14 blocks apart since the max 16 range on them. The lumens seem to be falling off about 10 repeaters in and the repeaters are not chunk-loading along with the pylons.

**Comment by ReikaKalseki** [comment]
Repeaters do not chunkload, their max range is 32, not 16, and what do you mean "falling off"?

**Comment by ghost** [comment]
Think they mean doesn't ding or has a drop off in lumens.

**Comment by StrayCargo** [comment]
Exactly what HyperionNexus stated

**Comment by Reignofmagic** [comment]
To answer the original question you had @JosephRymer 

Repeaters do have a signal loss although this is very minor and only really becomes an issue after 40+ repeater lines (1k~ distance to travel)
As Reika stated Repeaters have a max distance of 32 blocks, they also have a maximum angle vertically they can transmit (30~ or so degrees depending on distance)

The Lumen Relays (different power system entirely) on the other hand do have a much shorter range which I do think that is 16 by default.

**Comment by StrayCargo** [comment]
@Reignofmagic me and another mod on the server tried to get it to work with 32 block range and it wouldn't. Even after we had put them 14 apart it still would not travel unless the pylons were chunk-loaded. Sometimes it didn't even work then.

**Comment by ReikaKalseki** [comment]
Pylons do not need to be chunkloaded to function.

**Comment by StrayCargo** [comment]
Apparently on the Revolution 2 modpack they do. Also the repeaters when I click them with my focal manipulator after about 10 sometimes 9 they stop working and wont continue to number accordingly

**Comment by Aivech** [comment]
Haggle1996 turned off pylon chunkloading in the configs.

**Comment by ReikaKalseki** [comment]
That is off by default, and does not have any effect on their actual functionality.

**Comment by StrayCargo** [comment]
Whats the solution

**Comment by ReikaKalseki** [comment]
So far no problem has been clearly described.

**Comment by Aivech** [comment]
Can you make a video with OBS or other screen-capturing software?

**Comment by StrayCargo** [comment]
ill try give me some time

**Comment by Keyarose** [comment]
One thing to check is that the Pylon has a charge.  In my experience the repeaters will not register as connected if their respective Pylon is out of energy.

**Comment by StrayCargo** [comment]
Thats the problem @Keyarose they are running out of power 9 or 10 in.

**Comment by Keyarose** [comment]
Repeaters won't draw energy unless there is something within the chain's range that can hold power.  If you are just hitting them with the manipulator and nothing is drawing from the network then the Pylon should have power.  If the 10th or 11th repeater that wont show a number and the previous one still does then something is blocking between those two.

**Comment by ReikaKalseki** [comment]
And if the pylons are nearly empty, they will not be able to transfer across very many repeaters.

**Comment by StrayCargo** [comment]
ok whats the solution to fix that problem because nothing blocking them

**Comment by ReikaKalseki** [comment]
If they are not connecting, then yes, something is blocking them.

**Comment by TomeWyrm** [comment]
Literally. Imagine the repeaters shoot laser beams. Something is almost certainly in the way of that laser beam.

I would suggest checking line-of-sight at one of the beacons and removing possible conflicting blocks. Don't use ANY invisible light blocks ANYWHERE near the things. Make sure no leaves, glass, anything is in the way.

If there's still a problem, make a glass "rod" between the two. If that works, then yay. If that doesn't and someone that can actually remember tells you that glass doesn't work as a block to pass through like Air does, remove the glass "rod"... if it still doesn't work, something else is wrong.

**Comment by ReikaKalseki** [comment]
Glass works.

**Comment by StrayCargo** [comment]
alright ill give it a try
