### ISSUE TITLE
Pylon Interaction Range?

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#635]
I can't interact with a Pylon with the Elemental Manipulator unless within ~5 blocks of the Pylon, which was definitely not the case before. This makes it impossible to collect lumens without getting blasted several times.

![2016-02-22_21 32 54](https://cloud.githubusercontent.com/assets/6917535/13242801/6ead332e-d9ad-11e5-9da9-1ae30aac5191.png)

**Comment by ReikaKalseki** [comment]
I can see the problem in your screenshot. You lacked the required progression.

**Comment by Shahelion** [comment]
Those only triggered when I got this close. And the problem still exists with other pylons. So far, two Tahara and one Portokali pylons in this world.

**Comment by Aivech** [comment]
When you first trigger the progression you have to get close (for me it was close enough for WAILA to see it - yes I died multiple times trying to do this). Afterwards I was sucessfully able to discover and charge from pylons at the normal range of the manipulator.

**Comment by zemerick** [comment]
If only there was a certain pylon whose benefits negated the damage...HINT HINT:)

**Comment by TomeWyrm** [comment]
> Those only triggered when I got this close.

Yes, because you don't understand the required progression flags to get "absorb pylon energy with manipulator"

It's not a built-in ability, you MUST get certain progression flags before you gain this ability (like basically freaking everything in the mod).

Just because I'm feeling nice: You need to get within WAILA tooltip distance of at least one pylon before you can use the manipulator to discover colors and store those lumens in your personal pool.

**Comment by Aivech** [comment]
> You need to get within WAILA tooltip distance of at least one pylon before you can use the manipulator to discover colors and store those lumens in your personal pool.

I swear I just said this exact same thing :D

**Comment by TomeWyrm** [comment]
Yes you did. I felt like drilling home a point to someone who made an assumption about ChromatiCraft progression. It really isn't that hard to understand the mod, but people continually make really monumentally stupid mistakes that come from seeing someone do something and going "hey I can do that!" Without any background in the mod whatsoever.

**Comment by Shahelion** [comment]
I had been playing on my last world for quite a while, so hadn't realized that you had to get this close to trigger the whole thing.

Although, the distance required means you'd have to build up to it, which means being subjected to rapid energy blasts. Or find one next to a hill, I guess...

**Comment by Aivech** [comment]
There are several ways of getting up to X place without building. The potato jetpack comes to mind...

**Comment by Shahelion** [comment]
Doesn't that require Thermal Expansion? I have no CoFH mods.

**Comment by Aivech** [comment]
Botania?
Thaumcraft?

**Comment by ReikaKalseki** [comment]
RotaryCraft?

**Comment by Aivech** [comment]
> RotaryCraft?

Nice one, although I was thinking more creative-style flight, it is very manageble with Rotarycraft.

**Comment by zemerick** [comment]
There's also the bit I mentioned. No need to fly or anything. Walk under the pylon and jump. ( Might need like 1 block of dirt. ) No anything needed at all.

**Comment by TomeWyrm** [comment]
Or you can fall down with any slow fall effect, or use a certain color, or just run in there, place down a block, jump and look at the pylon, and run away giggling.

There are a multitude of strategies, get creative :-p
