### ISSUE TITLE
Grinder NEI Crash

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#636]
I just got this crash today after updating to v11 http://pastebin.com/RB8C0x5f clicking on sugar to view the recipe.

**Comment by ReikaKalseki** [comment]
This should be impossible. Try removing mods.

**Comment by ghost** [comment]
Will start removing mods and let you know.

**Comment by globsb** [comment]
I have exactly the same crash since v10.

**Comment by ghost** [comment]
globsb it was removed with v11 thats why I made a new post. Are you on v11 or v10 right now?

**Comment by globsb** [comment]
v11. Since v10 pretty much everything which can be made in grinder crashing game upon looking the recipe in nei any kind of ore dust, glowstone, blaze powder ect. Was hoping it will get fixed with v11 but no luck unfortunately.

**Comment by ReikaKalseki** [comment]
Again, try removing mods.

**Comment by ghost** [comment]
Avaritia. For some reason will get that crash every time even if the pack has just that along with yours.

**Comment by ghost** [comment]
http://i.imgur.com/aYLfwyR.png if you click on sugar with this mod pack it will crash is what I meant.

**Comment by ReikaKalseki** [comment]
...Does it add custom sugar or sugarcane?

**Comment by ghost** [comment]
Nope.

**Comment by ReikaKalseki** [comment]
This makes no sense...

**Comment by ghost** [comment]
And its more then just sugar. Just tried it with bedrock dust as well and it crashed.

**Comment by ReikaKalseki** [comment]
Is it any grinder recipe?

**Comment by globsb** [comment]
Just checked it and yes avaritia is triggering the crash. Any grinder recipe. Only thing which is grindable from avaritia are fracured ores. Braking any ore with world braker (avaritia pickaxe) drops 5 fracured ores which can be grinded to dusts. This is only thing connected which comes to my mind.

**Comment by ReikaKalseki** [comment]
Is there any way to disable that to test?

**Comment by Aknotsdeath** [comment]
What he said ^

**Comment by ghost** [comment]
Disable the grinded dusts? Not that I know of.

**Comment by ReikaKalseki** [comment]
The fractured ores.

**Comment by ghost** [comment]
No there isn't.

**Comment by ReikaKalseki** [comment]
In that case, there is nothing I can do without further information. As the crash is supposed to be impossible, the only thing I can think of is them switching ItemStacks around after registering some of them to the OreDict or something.

**Comment by redelman** [comment]
In case anyone's watching this, the issue has been fixed with Avaritia-1.11
