### ISSUE TITLE
Blast Furnace produces Base Panels instead of HSLA steel

### ISSUE THREAD

**Issue by MidgeFree** [ReikaKalseki/Reika_Mods_Issues#637]
I tried to begin playing RoC in Survival yesterday, and wondered that the Blast Furnace produces Base Panels instead of Steel Ingots, which makes it impossible to start over with the Mod. It really looks like this recipe has been disabled somehow, as NEI and the recipe in the handbook at the HSLA steel page are proving that the Blast Furnace gives Base Panels, and you only can get steel by uncrafting steel blocks or using the Pulse Jet Furnace. After I updated today to V11a, the issue is still occuring.
![The Handbook](https://cloud.githubusercontent.com/assets/17410988/13251591/876d4d5c-da31-11e5-9e14-fb3d32ffe0e3.jpg)
Also, see here the blast furnace producing base panels: https://youtu.be/_wG2piLoYGA

I have MineTweaker installed, but neither it changes any RoC recipe nor a new recipe uses RoC resources.

**Comment by ReikaKalseki** [comment]
Someone else reported this in the past ([on the FTB subreddit](https://www.reddit.com/r/feedthebeast/comments/3znk3f/custom_mod_pack_help/)).

Thre, Loot+++ was identified as the cause.

If that is the cause here, I am going to want to talk to the mod author (and does the mod have a GitHub?).

**Comment by MidgeFree** [comment]
Yes, I had Loot++ in the Pack, disabled it and it works now. Thanks!

**Comment by zemerick** [comment]
I couldn't find a github, just their curse and MCF pages.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2290059-loot-the-addon-update-now-with-the-ability-to

http://www.curse.com/mc-mods/minecraft/225880-loot

It sounds highly configurable, so might need a config file known to cause the issue.

**Comment by ReikaKalseki** [comment]
Yes, it is configurable, and my digging through its source last time yielded nothing, and the user never replied with the configs or any additional information.

@MidgeFree 

Please provide your exact configs.

If this is not fixable (or worse, is intentional on their end, and they refuse to fix it), I may be forced to prevent installation of the two mods together.

**Comment by MidgeFree** [comment]
I hadn't used the mod at that point, so I had the standard configs.

**Comment by ReikaKalseki** [comment]
I have spoken with the developer and he claims to have fixed the issue. We shall see if this is the case.
