### ISSUE TITLE
Pump drains all water in 3x3 pool

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#64]
We're running into a problem on our SMP server (ATLauncher RevolutionPack with FastCraft installed) where the RotaryCraft pump will drain all the water out of a 3x3 pool. I cannot replicate the problem in SSP. 

Basically, a full 3x3 pool of water. It appears to happen when the server reboots -- the pump will drain out all the water before the server has a chance to replace water blocks. The chunk the pump is in is not chunk loaded. 

Any thoughts on what might be the problem and/or resolution?

**Comment by ReikaKalseki** [comment]
This is caused by the pump being faster than the water flowing to refill itself. Use a larger pool, ideally 5x5.

**Comment by Haggle1996** [comment]
Awesome. Thank you.
