### ISSUE TITLE
[Suggestion]Add something native in rotarycraft/reactorcraft to consume the enormous amount of energy produced by reactorcraft

### ISSUE THREAD

**Issue by wormzjl** [ReikaKalseki/Reika_Mods_Issues#641]
Like...a particle accelerator?

Currently the amount of energy produced is not quiet useful in a RoC environment, it would be nice if they could find some usefulness in this framework

**Comment by Aivech** [comment]
The fusion reactor is more of a community build or a team build to provide power for a small server of lategame players. But such a thing could be nice in SSP or 2-player games.

**Comment by Aivech** [comment]
I would personally like some form of all-out base defence...

**Comment by th4umiel** [comment]
Maybe an item duplicator? Like the one that you can find in Calculator

**Comment by Aivech** [comment]
A cubic meter of sandstone weighs about 2.5 short tons, or 2,268,000 grams. Given E=MC^2, it would take 203 sextillion\* joules of energy to synthesize one block of sandstone from energy.

I am pretty sure that is more than the output of the fusion reactor.

*203837674537510240752000 is the answer my calculator gave me

Incidentally, this means that Chromaticcraft lumens represent a ridiculous amount of energy in joules.

**Comment by Aivech** [comment]
I found a source saying someone was producing 60 GW of power with their fusion reactor. At this rate, it would take (assuming a constant 20 TPS) ~105 millenia to amass that much power.

**Comment by ReikaKalseki** [comment]
You already have places to sink that power. RotaryCraft.

**Comment by zemerick** [comment]
60 GW is low for a fusion reactor. 120GW is easily achieved with the very basic 4 injector design, and nearly 150GW can be achieved. My personal best was around 1TW, but it unfortunately also brought my computer to its knees preventing an actual measurement.

Granted, that still makes raw matter production way out of the realm of possible ( without taking significant liberties ala EE ), and it would quickly make sense why: Fusion only converts something like 1% of the mass to energy. The reactor only fuses a small amount of fuel at any given time. Finally, 100% efficiency isn't possible, so there is energy loss added on top of that.

**Comment by Aivech** [comment]
I was ignoring practical matters like resistance and the feasibility of storing such quantities of energy and getting it to make what you want it to make and just dealing with numbers.

**Comment by TomeWyrm** [comment]
But seriously, you can pump an entire fusion reactor into a single machine to make it function at ludicrous speed. RotaryCraft is all the energy sink you need.

**Comment by wormzjl** [comment]
that was quiet...pointless

**Comment by TomeWyrm** [comment]
What was?
