### ISSUE TITLE
RotaryCraft java.lang.NullPointerException crash on start v11a

### ISSUE THREAD

**Issue by Schadrach** [ReikaKalseki/Reika_Mods_Issues#642]
Updated private server pack from v10d to v11a, began receiving this error.

Crash report: http://pastebin.com/ZndAsR2t

**Comment by ReikaKalseki** [comment]
It is failing to parse a vanilla recipe, because one of the items inside is a null-item ItemStack. Some other mod is removing a vanilla item yet leaving all the references.

**Comment by Schadrach** [comment]
For reference, the mod misbehaving ended up being Reliquary.

**Comment by ReikaKalseki** [comment]
What vanilla item does it delete?

**Comment by Schadrach** [comment]
Honestly, I didn't get that far.  Was more worried about getting the server up and running again.

**Comment by ReikaKalseki** [comment]
Is their source available?

**Comment by Schadrach** [comment]
https://github.com/TrainerGuy22/Reliquary

**Comment by ReikaKalseki** [comment]
Looking into their code has found nothing, but it may just be buried somewhere. I will put additional debugging information in; when the next version is released, try again and look for errors related to vanilla recipes. V11b is coming later today.
