### ISSUE TITLE
Strange code in ReikaMathLibrary.java in DragonAPI

### ISSUE THREAD

**Issue by dmitry64** [ReikaKalseki/Reika_Mods_Issues#644]
I have looked in ReikaMathLibrary.java and saw some strange code:
https://github.com/ReikaKalseki/DragonAPI/blob/master/Libraries/MathSci/ReikaMathLibrary.java#L251
This function must return true if both args are zero, but actually it returns true if (val1 == 0 || val2 == 0). Is that an error? And why is there a multiplier in this condition: ((1000*val1)/val2 > 0)? 
Also this function: 
https://github.com/ReikaKalseki/DragonAPI/blob/master/Libraries/MathSci/ReikaMathLibrary.java#L397
may be unsafe and probably might be optimized with something like this:

```
if (val > 0)
return 1;
else if (val < 0) 
return -1;
return 0;
```

**Comment by ReikaKalseki** [comment]
That is some very early code. It can easily be replaced with `Math.signum(a) == Math.signum(b)`, which I will do.

**Comment by ReikaKalseki** [comment]
Done.
