### ISSUE TITLE
V11a - RotaryCraft pump powered by DC engine no longer works

### ISSUE THREAD

**Issue by MatthiasMann** [ReikaKalseki/Reika_Mods_Issues#645]
The Waila tooltip shows 2.95 seconds per operation - but the pump will not pump any water from the 3x3 water pool directly below the pump.

The Angular transducer did not show any "error" messages like it does when insufficient power is applied to a machine.

This worked in V10d.

**Comment by ReikaKalseki** [comment]
Read the changelog.

**Comment by MatthiasMann** [comment]
The changelog only reads "changed the power curve".

And if the tooltip still shows 2.95 seconds per operations - then I expect that it will also pump water. If I turn off the DC engine - the displayed operating time goes up.

**Comment by ReikaKalseki** [comment]
Time per operation does not have any relation to power sufficiency.

**Comment by ljfa-ag** [comment]
It says "Changed pump power curve and torque requirement"

**Comment by TomeWyrm** [comment]
That 2.95 seconds per operation is WAILA being dumb. It doesn't check to make sure you're supplying sufficient power, it just checks the speed.

**Comment by TomeWyrm** [comment]
If you want to use a DC engine, I suggest reading the manual. Here's a hint: 2x ____ unit

**Comment by MatthiasMann** [comment]
The point is also that the angular transducer also did not say anything about insufficient torque (like it does for the Boring machine):
[21:14:43] [Client thread/INFO]: [CHAT] Pump Receiving 1.024 kW @ 256 rad/s.
[21:14:47] [Client thread/INFO]: [CHAT] Pump Receiving 1.024 kW @ 256 rad/s.

**Comment by ljfa-ag** [comment]
I see, well that doesn't make sense

**Comment by ReikaKalseki** [comment]
That code is automatic, not machine-specific.

**Comment by ljfa-ag** [comment]
I can reproduce that. The pump doesn't pump anything even though there is no mention of the power being insufficient.
On the other hand, when I give it less than 1024 W it will say "Insufficient Power".

**Comment by ReikaKalseki** [comment]
He supplied insufficient torque, not power.

**Comment by sp823** [comment]
I'm new to the mod never having used it before - how are you supposed to know the new torque requirement if the tool doesn't tell you and the wiki still says 4Nm and there is no UI on the machine? Kind of frustrating to run into this especially when it is one of the very first things you build.

**Comment by TomeWyrm** [comment]
By requesting Reika fix the handbook entry :-)

**Comment by Builderb0y** [comment]
Read the tooltip on the pump.

**Comment by ReikaKalseki** [comment]
> By requesting Reika fix the handbook entry :-)

The handbook autofetches the power requirements. There is nothing to fix, as nothing is broken.

> and the wiki still says 4Nm

Your point? There are still wikis saying that you can set magnetostatics to whatever output you want, or that HTGRs can be made in a "+" design.

**Comment by nmarshall23** [comment]
I edited the [pumps wiki page](http://rotarycraft.wikia.com/wiki/Pump).

I had a friend get confused, because he saw that the pump has two input sides. Thought he could just connect two DC engine one on each side. 

This change makes those early steps into Rotarycraft a little more confusing. You need to learn about Shaft Junctions right as you are just starting the mod.

**Comment by TomeWyrm** [comment]
Meh, I just build a steam engine and bypass the whole point of using DC. Not like getting water into a steam engine is difficult for a jump-start on a pump setup.

Honestly if people would quit letting other people be brainless, which Reika subsequently has to break the capability to follow-that-leader? This wouldn't be a problem. As-is, if you don't understand most of the power transmission system at the outset, RotaryCraft is going to be... difficult.
