### ISSUE TITLE
V11a has really strange effect on AgriCraft canola crops

### ISSUE THREAD

**Issue by MatthiasMann** [ReikaKalseki/Reika_Mods_Issues#646]
I have 10/10/10 AgriCraft canola crops which I could harvest by right clicking - after updating to V11a (from V10d) this no longer works. The right click animation is still playing - but nothing happens. It still works on other AgriCraft crops - just not canola.

Also breaking on of the mature crops produces the 10/10/10 seed as expected - but it also produces ~140 canola seeds without NBT data. In version v10d this only produced 4 seeds per crop.

While getting more for the same investment is nice - but more than 2 stacks per crop seems really excessive.

I'm using AgriCraft-1.7.10-1.4.5.jar.

**Comment by ReikaKalseki** [comment]
I added a custom AgriCraft canola handler - hence the now-reasonable seed drop rates - but this is known, almost certainly on his end since I control none of that, and has been reported.

**Comment by TomeWyrm** [comment]
@MatthiasMann The 4 seeds thing is demonstrably worse than a standard canola farm, hence the 140 seeds. The idea being that 10/10/10 seeds have greater yields than standard plants... agricraft just didn't properly special handle canola.

**Comment by redelman** [comment]
This should be fixed in 11b. It's definitely fixed in whatever version will be released next. I got 42 full stacks and a partial stack of 40 seeds from 27 10/10/10 plants.
