### ISSUE TITLE
RotaryCraft v11a Boring Machine Crashes Server

### ISSUE THREAD

**Issue by seemuth** [ReikaKalseki/Reika_Mods_Issues#647]
When playing on a server, if I place a Boring Machine in the world, the server immediately crashes with the exception:

`[15:05:35] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: Could not initialize class Reika.RotaryCraft.TileEntities.Production.TileEntityBorer`

I have uploaded the [server crash log](https://gist.github.com/seemuth/5bc83f23c8cbba8dd419).

I can reproduce the crash with the following process:
1. Create a new Minecraft server with Forge 1.7.10-10.13.4.1558-1.7.10.
2. Add mods `DragonAPI 1.7.10 V11a.jar` and `RotaryCraft 1.7.10 V11a.jar`
3. Start server in Java 1.7 with command `java -server -Xms2048m -Xmx4096M -XX:PermSize=512m -d64 -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -jar forge-1.7.10-10.13.4.1558-1.7.10-universal.jar nogui`
4. Connect to server with Minecraft client using same Forge and same mods
5. Enter Creative mode and give self a Boring Machine
6. Place Boring Machine on the ground
7. Server crashes

I also have tested using Forge 1.7.10-10.13.4.1614-1.7.10-universal.jar with the same results. Oddly enough, I can place Boring Machines in single player with no issues.

**Comment by ReikaKalseki** [comment]
It only being on dedicated servers implies client code somewhere...

**Comment by aking4125** [comment]
Getting a similar crash but for me, the server can't even create the world.

**Comment by ReikaKalseki** [comment]
Fixed in v11b.
