### ISSUE TITLE
BOP now incompatible with Chromaticraft (?)

### ISSUE THREAD

**Issue by dabaer** [ReikaKalseki/Reika_Mods_Issues#648]
At risk of looking "extremely foolish" here, keep in mind this is not a standard "I didn't fix the biome ID configuration" issue report before you scamper over to the close button.

Regardless of whether it is related to #640 or not, it still starts from there. As of v11a i'm having a perpetual biome ID conflict with Chromaticraft, which is unfixable. Judging by the Chromaticraft configuration there is either direct or indirect compatibility with BOP, however even when they are the only mods installed I cannot get them to work together.

Both mods are at the latest versions for 1.7.10, however no matter how I configure the IDs Chromaticraft perpetually crashes complaining of conflict (when there isn't). Reika, you say there is a vanilla bug regarding 128+, however I can find no information on this, and no other mod has this issue. If I put BOP above 128 and CC below, CC complains. If I put CC above 128, and BOP below, it again complains (obviously due to some sort of intended or unintended math error).

According to AntiIDConflict, Forge and several threads around the internet, there should be 255 ID spaces available, yet no matter where I assign CC in that range there is always a conflict when there are no other biomes assigned to those IDs. I have also heard passing comments around so called "null" worlds, but it may be completely unrelated (null/biomesoplenty.common.biome.overworld).

Thanks for listening, and Regards,
Dakora

**Comment by ReikaKalseki** [comment]
As I stated on #640, you cannot have two IDs that are 128 apart. So you effectively do only have 128 slots, even though 255 actually exist. Welcome to vanilla's wonderful - **gag** - implementation.

**Comment by TomeWyrm** [comment]
Basically? If a biome generates in the overworld and there is a biome +128 from that ID, that +128 biome will be used as a "technical" biome and sometimes replace the -128 biome.

This is one of the common causes for Twilight Forest Biomes in the overworld... especially with Biomes Too Many or ExtraBiomes StupidLarge Edition.

check https://github.com/Glitchfiend/BiomesOPlenty/issues/334

**Comment by dabaer** [comment]
Okay, thank you for explaining that bit. I was trying to figure out why this didn't obviously affect other mods (it was just silent). @ReikaKalseki where do we go from there? Are you just now enforcing this in v11, or have you been and just I have another mod that fixes the issue and I should not worry past our previous -9 index out of bounds issue?

Regards,
Dakora

**Comment by ReikaKalseki** [comment]
Use v11b.
