### ISSUE TITLE
Want a config to turn off infinite end

### ISSUE THREAD

**Issue by ValiantRanger** [ReikaKalseki/Reika_Mods_Issues#649]
We want a config to turn off the infinite end. Locking the last request did nothing but show how weak your position was, as you can't even argue against the criticism.

You will not win this.
We outnumber you.
You cannot silence us.

**Comment by FurryDJ** [comment]
Hail Hydra? You supporting a the whole "we" are a silent majority lurking in the shadows ready to attack doesn't work here. This is a developer, not the leader of a fascist regime.

**Comment by TomeWyrm** [comment]
Seriously dude? I WANT the ability to disable the infinite end because it screws up some mods I like, and if all I read was this post, I'd be on Reika's side. @ValiantRanger, quit "helping".

**Comment by DaMachinator** [comment]
I sincerely doubt there are that many people who care enough to be rude about it - certainly not too many to block from the repository.

**Comment by ljfa-ag** [comment]
For the record: Duplicate of #613 
Well there is still no satisfying solution. Locking might have been too hasty.
