### ISSUE TITLE
Chromaticraft Cave Crystals always drop the same color, and color changes randomly

### ISSUE THREAD

**Issue by dwenograd** [ReikaKalseki/Reika_Mods_Issues#65]
Ran into an interesting problem in a new world. All of the cave crystals I broke were dropping orange shards, regardless of color. Weird, but I put them in a chest and moved on. I came back the next day, a stack of orange shards, and when I picked them up, they turned blue. The remainder of the day, every crystal I broke turned blue. A few days later same thing, they all turned white, and had the same problem with all the crystals broken only giving white shards.

ChromatiCraft 1.7.10 V6f
DragonAPI 1.7.10 V6f
RotaryCraft 1.7.10 V6f
ReactorCraft 1.7.10 V6e
ElectriCraft 1.7.10 V6a

**Comment by 1Matthias** [comment]
Any other mods in your minecraft instance? A full list would be helpful. It sounds to me like Something is messing with Metadata.

**Comment by dwenograd** [comment]
Yeah, quite a few, it's a custom pack I put together. Basically just a branch of Infinity with a lot of mods like MFR and Big Reactors that I found myself relying on too much cut out completely (and some additions like Infernal Mobs and Gregtech to make it more difficult)

![modlist](https://cloud.githubusercontent.com/assets/7005012/7550703/bd90d0ac-f620-11e4-977b-c6859fd09de6.png)

Are there any mods you see that would obviously cause something like this? As far as I'm aware, no other items are having this kind of problem on the server so far (only been playing on it for a week).

**Comment by ljfa-ag** [comment]
Might be GregTech's ore unification. Try turning that off.

**Comment by dwenograd** [comment]
Changing the GregTech ore unification config for the Chromaticraft crystals doesn't seem to have any effect, they're all still dropping the same color.

**Comment by ReikaKalseki** [comment]
Try turning off every other unifier. I have never seen this before, and I know that it works for me. This has to be a mod interaction.
