### ISSUE TITLE
Clicking "Yeast" in NEI crashes game

### ISSUE THREAD

**Issue by CrazyPython** [ReikaKalseki/Reika_Mods_Issues#651]
Using latest version. Chest was open. [Error here](http://pastebin.com/MejppTrz)

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by CrazyPython** [comment]
Link to commit that fixed it?

**Comment by CrazyPython** [comment]
Also by the way, thank you for doing what you do. Those people who disrespect (e.g. What Not To Say) you don't realize how grateful they should be.

**Comment by TomeWyrm** [comment]
He does monolithic commits. Look for it when v11b or v12 drop.
