### ISSUE TITLE
Opening any GUI (spotted on RotaryCraft) w/ a tinker's construct tool crashes the game

### ISSUE THREAD

**Issue by CrazyPython** [ReikaKalseki/Reika_Mods_Issues#652]
Not sure if specific to one machine. See [this pastebin](http://pastebin.com/EQeWHkFm)

**Comment by Aivech** [comment]
Does it still happen if the slot to the right of the tool is empty?

[If the tool is in the rightmost slot, then the leftmost should be empty.]

**Comment by ReikaKalseki** [comment]
Same as your other vanilla crash. Did you even check?

**Comment by CrazyPython** [comment]
This only happens with RotaryCraft machines though.

**Comment by ReikaKalseki** [comment]
It is still vanilla code that references absolutely none of mine.

**Comment by ljfa-ag** [comment]
Doesn't necessarily mean that there is no problem with the code...I think I also saw this a few times on RoC machines, but I have no reliable way to reproduce it.

**Comment by CrazyPython** [comment]
But if all the other mods don't behave that way then that must mean there
is something different about this problem.
