### ISSUE TITLE
ChromatiCraft Research Manager crashes

### ISSUE THREAD

**Issue by novasolarius** [ReikaKalseki/Reika_Mods_Issues#656]
Here's a log: http://pastebin.com/qMjc9v7t

I don't know why this happens. All I know is that removing the 'ChromatiCraft_data' folder prevents the crash, allowing for a single launch each time.

**Comment by ReikaKalseki** [comment]
This is likely a mod interaction. Try removing mods.

**Comment by novasolarius** [comment]
...turns out the crash occurs whenever I add or remove a mod.

**Comment by Aivech** [comment]
Use AppliedEnergistics Rev2.

**Comment by Aivech** [comment]
You'll have to downgrade Thaumic Energistics if you have it.

**Comment by novasolarius** [comment]
Eh, Thaumic Energistics is nice but ultimately disposable. Besides, ChC has mass Essentia storage as well, right? An 'aspect jar' or somesuch, I believe.

**Comment by ReikaKalseki** [comment]
Yes, though it does not have AE compatibility.

**Comment by Aivech** [comment]
Revolution|2 on the ATLauncher has the version of Thaumic Energistics you seek.

**Comment by novasolarius** [comment]
Thanks for the tip.

**Comment by Gargule** [comment]
Is there any way for this to be actually fixed instead of messing with up-downrgading mods?
(I'm not a good coder myself and idk what exactly causes it, so i have to ask)

**Comment by Aivech** [comment]
> Is there any way for this to be actually fixed instead of messing with up-downrgading mods?
> (I'm not a good coder myself and idk what exactly causes it, so i have to ask)

There’s an AE2 config setting you can change to use rev3.

**Comment by glencoe2004** [comment]
@Aivech , can you elaborate on what the specific config option you need to change is?

**Comment by ReikaKalseki** [comment]
Not sure why this issue never got linked to the others: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1732 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1683 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1681 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1493 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1257 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1280 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1238 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2390 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1848 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1985 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2419 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2502 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2595 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2903 https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/3032

**Comment by Aivech** [comment]
@glencoe2004 set `B:exportItemNames=false`, not sure what file it's in but i think it's called customextracts.cfg

**Comment by AshIndigo** [comment]
**config/AppliedEnergistics2/CustomRecipes.cfg** is the file you want if I remember correctly
