### ISSUE TITLE
Chromaticraft crash on startup

### ISSUE THREAD

**Issue by echthesia** [ReikaKalseki/Reika_Mods_Issues#659]
[crash-2016-02-28_21.38.06-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/150352/crash-2016-02-28_21.38.06-client.txt)

After resolving #640 by removing HEE and resolving about 10 trillion ID conflicts, I have come up with this. Nothing like it that I can find. I am playing on a modpack based on The 1.7.10 Pack 0.8.0 with a few mods, including Chromaticraft and DragonAPI, thrown in, and a few troublesome ones (mystcraft, HEE) thrown out. Any ideas?

**Comment by ReikaKalseki** [comment]
[This is a mod version conflict, apparently AE-related](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/656).

**Comment by echthesia** [comment]
Well, it still shows up with AE and all of its addons gone. Any ideas?

**Comment by ReikaKalseki** [comment]
Then it is clearly not AE-related, but it is still a mod interaction issue. Try removing mods. Forestry would be my first suspect.

**Comment by echthesia** [comment]
Well, you're right about that. I didn't see the last sentence, so I tested them all anyway (oops), but Forestry 3 is the culprit. Removing all Forestry mods (binnie's, gendustry, etc.) has worked. Thanks for your help! Now I'm starting to wonder if Forestry 4 will work...

**Comment by ReikaKalseki** [comment]
It will.
