### ISSUE TITLE
Zambaru Crystals dish XP for every player nearby, stacking.

### ISSUE THREAD

**Issue by madolinn** [ReikaKalseki/Reika_Mods_Issues#66]
Bad wording. Anyways.

Place a Zambaru Crystal/Potion on the ground, stand next to it, add another person into the mix nearby as well. Now it dishes XP twice as fast. Add another contestant: level up even quicker than two, etc.

/endbadwording

**Comment by 1Matthias** [comment]
Ouch. That is quite an issue. Get your entire server in one place, and ow.

**Comment by ReikaKalseki** [comment]
This makes no sense....the code is not sensitive to the number of players.
https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Base/CrystalBlock.java#L235

**Comment by madolinn** [comment]
```
List<EntityLivingBase> inbox = world.getEntitiesWithinAABB(EntityLivingBase.class, box);
for (EntityLivingBase e : inbox) {
    if (ReikaMathLibrary.py3d(e.posX-x-0.5, e.posY+e.getEyeHeight()/2F-y-0.5, e.posZ-z-0.5) <= r) {
        this.applyEffectFromColor(this.getDuration(color), this.getPotionLevel(color), e, color);
    }
}
```

Is it getting multiple lists of the same thing? Not sure.

**Comment by ReikaKalseki** [comment]
No, it is getting a list of all EntityLivingBase instances in the bounding box. No entry should be duplicated.

**Comment by ljfa-ag** [comment]
I think the problem is the way how crystal effects are being applied: https://github.com/ReikaKalseki/ChromatiCraft/blob/8b3e54ea265bc4f28943d6aa633b89e403bad2f5/Base/CrystalBlock.java#L134

The client sends a packet to the server which triggers the effect. More clients around one crystal means more packets sent.
Apart from that, it could be further expolited by clients sending forged packets.

**Comment by ReikaKalseki** [comment]
OH....yes, that is indeed it. But it is also not really avoidable without making the crystals ticking tile entities....

**Comment by umbralOptimatum** [comment]
Is there some way to add a limit to how often the crystals can activate in terms of time?

**Comment by ReikaKalseki** [comment]
No, because blocks only have one instance in the world.

**Comment by madolinn** [comment]
The only way I could see this working (albeit I didn't spend too much brain power expending ideas) is somehow incorporating a list of "activated" crystals server-side and to do their effects every X ticks.

However It'd be annoying, slow, clunky. Every bad word you can think of.

**Comment by ReikaKalseki** [comment]
What about making it, instead of applying the effects to all entities in the AABB every time the packet is received, pick one random entity from the AABB, making it effectively "auto-divide"? The problem is that non-player entities also get applied effects, meaning large numbers of animals or similar around a crystal will dramatically reduce its per-entity effect, not something I want.

**Comment by madolinn** [comment]
Is there no way to filter through the list and check for Player entities after getting the box? Otherwise yeah, I think that would work well

**Comment by ReikaKalseki** [comment]
> Is there no way to filter through the list and check for Player entities after getting the box? 

??

**Comment by ReikaKalseki** [comment]
> Is there no way to filter through the list and check for Player entities after getting the box? 

??

**Comment by ReikaKalseki** [comment]
> Is there no way to filter through the list and check for Player entities after getting the box? 

??

**Comment by ReikaKalseki** [comment]
> Is there no way to filter through the list and check for Player entities after getting the box? 

??

**Comment by ReikaKalseki** [comment]
> Is there no way to filter through the list and check for Player entities after getting the box? 

??

**Comment by ReikaKalseki** [comment]
> Is there no way to filter through the list and check for Player entities after getting the box? 

??

**Comment by madolinn** [comment]
> The problem is that non-player entities also get applied effects,
> one random entity from the AABB

So, get AABB list, iterate to only find players, pick one random player.

**Comment by ReikaKalseki** [comment]
But effect is also supposed to apply to non-player entities.

**Comment by madolinn** [comment]
Ah, I was assuming this was a Zambaru effect only tweak. Unless you're saying that other things are intended to accumulate XP as well?

**Comment by ReikaKalseki** [comment]
Whatever changes I make will affect _all_ crystals of all colors and variants.

**Comment by madolinn** [comment]
I suppose that's true unless you set a condition based on the color, prior to applying (in addition to during as it is now).

**Comment by ReikaKalseki** [comment]
I do not want to do that.

**Comment by madolinn** [comment]
Yeah I had imagined so.

Unless you pass the list onto applyEffectFromColor, and then filter inside the switch condition, I don't see many elegant options. But that's not very elegant either.

EDIT: Don't mind me I'm an idiot. That's essentially what's going on as it is, sort of.

EDIT: Maybe you should just pass it onto the applyEffectFromColor, and not a single entity. Then have the switch conditions filter on their own. That way at minimum it's still doing the same amount of work, and only under certain conditions does it actually change.

**Comment by ReikaKalseki** [comment]
OK, I think I fixed it.

https://github.com/ReikaKalseki/ChromatiCraft/commit/1acbfa08c05a9a06d613bdc2485450ebe0288e70
