### ISSUE TITLE
Crash Opening Casting Delegate GUI

### ISSUE THREAD

**Issue by Reignofmagic** [ReikaKalseki/Reika_Mods_Issues#660]
Hey Reika,

Found this while on the server, since you were not there I am putting this here so I don't forget myself. 
http://pastebin.com/0YcSuCHZ

What I did was open the casting delegate. My guess is since the chroma flower is the first option it tried to use some leaf block from Natura that doesn't actually exist much like the issue with forestry and the log/slabs in the chroma dimension.

**Comment by ReikaKalseki** [comment]
Yes, this is more OreDict stupidity.

**Comment by Shahelion** [comment]
Is there a way to use MineTweaker to remove this wildcard leaf thing from the OreDictionary? Or would that just cause more issues? Is it even possible?

**Comment by ReikaKalseki** [comment]
Yes.
