### ISSUE TITLE
Chromaticraft crash with AE2 rv3 beta

### ISSUE THREAD

**Issue by xXGandalfXx** [ReikaKalseki/Reika_Mods_Issues#661]
Hey,

just as the title says, Chromaticraft crashes with AE2 rv3 beta.

http://pastebin.com/mym2GrMB

**Comment by Aivech** [comment]
Known issue :D

**Comment by redelman** [comment]
Yes, this is a known issue. No current version of Chromaticraft supports AE2 rv3. Downgrade to rv2 if this really bothers you.

**Comment by Aivech** [comment]
You will need to downgrade Thaumic Energistics if you have it to a version compatible with AE2 rev2

**Comment by redelman** [comment]
See #481
