### ISSUE TITLE
Updating to v11b cleared player lumens

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#662]
I noticed that the manipulator radial was completely empty, when before updating I had at least 5 colors filled.

Nothing else seems to have been affected so far...

**Comment by ReikaKalseki** [comment]
I have not experienced that effect, nor have there been any other reports, nor did the NBT handling change.

**Comment by Shahelion** [comment]
May actually be tied to the research-related crash...it seems to happen every time that does.

**Comment by ReikaKalseki** [comment]
Crashing when loading the player NBT? That could cause File IO issues.
