### ISSUE TITLE
I'm sorry I have to submit so many issues.

### ISSUE THREAD

**Issue by echthesia** [ReikaKalseki/Reika_Mods_Issues#664]
[crash-2016-02-29_19.45.02-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/152037/crash-2016-02-29_19.45.02-client.txt)
Well, I uploaded the wrong crash log on #663, and #659 is still occurring, even after I removed LiteLoader (and its mods), AE2, ExtraCells 2, and Thalamic Energistics. Sorry if I'm being a pest, but I REALLY like your mod and want to get to play it.

**Comment by redelman** [comment]
Try updating your forge version. 1492 is a bit out of date. I believe Reika compiles everything against 1558 now, so you'll need at least that.

**Comment by echthesia** [comment]
1558 installed, it didn't make a difference. Same crash.

**Comment by ReikaKalseki** [comment]
...why open a new issue? Why not just continue on the last one? And this log is the same as before. It is still a mod interaction.
