### ISSUE TITLE
a player broke a piece of liquid pipe with water inside it.

### ISSUE THREAD

**Issue by OmegaCenti** [ReikaKalseki/Reika_Mods_Issues#665]
https://gist.github.com/OmegaCenti/bad0288a693c985b7311

**Comment by ReikaKalseki** [comment]
What the hell? How did this happen? There is a block/TileEntity mismatch. @funwayguy Could "Physics Block" do this?

java.lang.ClassCastException: Reika.RotaryCraft.TileEntities.Farming.TileEntityFan cannot be cast to Reika.RotaryCraft.Base.TileEntity.TileEntityPiping
    at Reika.RotaryCraft.Blocks.BlockPiping.func_149668_a(BlockPiping.java:126)
    at enviromine.EntityPhysicsBlock.func_70071_h_(EntityPhysicsBlock.java:217)

**Comment by Aivech** [comment]
We have enviromine physics turned on. It does wierd things to TE's.

**Comment by Haggle1996** [comment]
We've had enviromine physics on for a while, but it just seems to be coming to a head recently -- unsupported (e.g., free-falling) tile entities from your mods are going crazy when they drop in v11. In v10, they would just turn into the lowest-numbered tile entity (for example, any RoC engine would turn into the DC engine). Now they either crash the game or turn into unbreakable/unmovable blocks. I'm still trying to see if there's a way to exempt the tile entities from physics (there is for blocks, not TEs).
