### ISSUE TITLE
Not a bug

### ISSUE THREAD

**Issue by echthesia** [ReikaKalseki/Reika_Mods_Issues#666]
There is no help whatsoever on how to use /chromaprog, and /chromaprog -1 does not work, it says invalid arguments. Any way you could add some help, or at least tell me here? On the bright side, I fixed all of the fatal issues!

**Comment by ReikaKalseki** [comment]
This is not what the issue tracker is for, and it cannot be summarized in one line.

/chromaprog `item`/maximize/minimize `state`/`type`/all.

**Comment by InitHello** [comment]
@ReikaKalseki I anticipate "hail satin" trolls.

**Comment by ReikaKalseki** [comment]
?

**Comment by InitHello** [comment]
Because of the issue number.

**Comment by TomeWyrm** [comment]
I'm tempted to lock the issue because of The Internet being, well... itself.
