### ISSUE TITLE
RotaryCraft_CustomExtracts.cfg does not work

### ISSUE THREAD

**Issue by BakermanLP** [ReikaKalseki/Reika_Mods_Issues#667]
Hello,

Used versions:
- DragonAPI 1.7.10 V11b.jar  
- ElectriCraft 1.7.10 V11b.jar  
- ReactorCraft 1.7.10 V11b.jar  
- RotaryCraft 1.7.10 V11b.jar
- MetallurgyCore-1.7.10-4.0.4.18.jar
- Metallurgy-1.7.10-4.0.8.97.jar

OK, this issue is reported many times in many ways, but here are some new important informations about that. It doesn't matter, if we try to add new items to the extractor via RotaryCraft_CustomExtracts.cfg or via AOBD. When the ore is not in the list, it doesn't work.
https://github.com/ReikaKalseki/DragonAPI/blob/b9f9529ab22def034009e559c82fdcd65a193de6/ModRegistry/ModOreList.java#L40

@lordjoda has spent many hours debugging this problem. Here is his conclusion:

> The ExtractAPI creates a new Instance of the CustomExtractLoader class. When The class RecipesExtractor (https://github.com/ReikaKalseki/RotaryCraft/blob/master/Auxiliary/RecipeManagers/RecipesExtractor.java#L71) is initialized it adds crafting recipes for all ores registered in the CustomExtractLoader. This is why NEI shows the recipes and the between products do work. But for the check if a ore can be processed or put in the extractor, the ReikaBlockHelper is called to check if the itemstack is an ore(https://github.com/ReikaKalseki/DragonAPI/blob/master/Libraries/World/ReikaBlockHelper.java#L132) but this check does NOT check if the ore is registered inside the CustomExtractLoader. 
> So I guess either the check has to be extended to include also the CustomExtractLoader or the loader has to also register the ores in one of the places that is checked if the item is a ore. 
> So in conclusion I would say that the ExtractAPI is not working. If you want I can also create a issue in the RotaryCraft issues.
> Hope that helps and I did not oversee something.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by BakermanLP** [comment]
Sorry to ask that, but can we have some kind of development build? Or do you release this version in near future?

**Comment by Aivech** [comment]
Number one rule of Reika's mods: There is no such thing as an ETA. :smile:

**Comment by BakermanLP** [comment]
Oh ... Sorry, forgot about that. Never mind

**Comment by TomeWyrm** [comment]
Yeah. V12 could be tomorrow or a month from now for all most of us know :-p

**Comment by BakermanLP** [comment]
Sorry to tell you, but this issue isn't solved with the latest versions. Here are the tested mods (nothing else installed):
- AOBD-2.9.1.jar
- CodeChickenCore-1.7.10-1.0.7.47-universal.jar
- DragonAPI 1.7.10 V12b.jar
- Metallurgy-1.7.10-4.0.8.145.jar
- MetallurgyCore-1.7.10-4.0.4.29.jar
- NotEnoughItems-1.7.10-1.0.5.118-universal.jar
- RotaryCraft 1.7.10 V12b.jar

Here is the file "/config/Reika/RotaryCraft_CustomExtracts.cfg":
`Adamantine, RARE, Ingot, ingotAdamantine, 1, 0x593d40, 0x402c2f, null, oreAdamantine
Prometheum, SCARCE, INGOT, ingotPrometheum, 1, 0xffffff, 0x73cc12, null, orePrometheum`

I have only added two of the metals to test the config.

All settings in AOBD (RotaryCraft related) are disabled / false. In NEI the other ores aren't shown in the recipes for the extractor. 

Complete "latest.log" can be found here:
http://pastebin.com/mkdaGCnE
- In NEI the recipes for Adamantine und Prometheum are shown
- The extractor accepts the "ore block", but nothing happens
- Iron ore for example is working in the same setup
- The dust, slurry and solution of Adamantine are working in the extractor

Cross Refs:
https://github.com/BakermanLP/ProjectRETv8/issues/25
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/667

You already tried to fix it with this commit:
https://github.com/ReikaKalseki/RotaryCraft/commit/c32ed8c053e5e68b75b3f04cae993be20d9c526c

Could you please have a look. Thank you!

Michael (aka BakermanLP)

**Comment by ReikaKalseki** [comment]
So the slot logic is fixed, but now the processing logic cannot accept it...

**Comment by BakermanLP** [comment]
Sorry to ask that, but wouldn't it be easier to add the content of the "/config/Reika/RotaryCraft_CustomExtracts.cfg" to the DragonAPI/ModRegistry/ModOreList.java via function? As far as I have seen, this part will be executed very late in the startup process and all ores are already added to the oredict.
Just my 2 cents :)

**Comment by ReikaKalseki** [comment]
No, because enums are fixed, and that would break the autogenerated extracts.

**Comment by BakermanLP** [comment]
Ah ok, never mind.

**Comment by lordjoda** [comment]
It's possible that I missed something since debuging with code only is kinda hard ;) but I think you have to add

```
ore = CustomExtractLoader.instance.getEntryFromOreBlock(is);
if(ore != null)
return ore;
```

at https://github.com/ReikaKalseki/RotaryCraft/blob/master/TileEntities/Processing/TileEntityExtractor.java#L357
(I only took a look at the extractor so this might be needed elsewhere)

**Comment by ReikaKalseki** [comment]
Done.
