### ISSUE TITLE
[Feature Request] Allow OPs to travel to the ChromatiCraft dimension without research

### ISSUE THREAD

**Issue by WillowMauldin** [ReikaKalseki/Reika_Mods_Issues#671]
Right now, even when OP'd, players will be transferred back to the overworld when teleporting to the ChromatiCraft dimension. This is inconvenient because server admins cannot assist players in this dimension without doing / cheating in the research, which isn't ideal if the admins are playing ChromatiCraft too.

**Comment by ReikaKalseki** [comment]
I am...ambivalent about this, because too many ops abuse such powers.

**Comment by WillowMauldin** [comment]
What do you mean by abuse? Entering the dimension to progress before they have the progress, or harassing players?

**Comment by ReikaKalseki** [comment]
Bypassing locking systems that a normal player could not, including using the dimension prematurely, accessing other players' structures (eg casting, ritual table) and protections (eg Guardian stone), and weaponry (eg ReC defences).

**Comment by WillowMauldin** [comment]
In the end a server owner could do all of those things anyways, as they control pretty much everything. I see your argument that it enables them to do that easily though. Perhaps this could be a config, so only the host can enable it?

**Comment by ReikaKalseki** [comment]
> In the end a server owner could do all of those things anyways, as they control pretty much everything.

See, the thing is, as I have access to the codebase, my power far outstrips theirs, and I can easily completely lock them out (see: current issue, or people who attempt to disable abilities because "they are OP").

> Perhaps this could be a config, so only the host can enable it?

That has occurred to me.

One question though: How did you plan to get to the dimension? I am not going to make the portal just work for admins, even with a config, and /tpx does not work because I stop link books from working.

**Comment by WillowMauldin** [comment]
I was actually planning to test G1GC issues without going through the research tree. I used the CoFH Core tpx command (/cofh tpx) to get there, it teleported me there then directly to the overworld without generating a chunk it seems. (onPlayerChangedDimension hook probably runs before things are generated)

You do control the code and have signed jars, but there's not much stopping a dedicated person from removing those checks and changing it themselves, or even just copying the ChromatiCraft NBT tags from a completed player. In addition, setting the dimension tag there and logging in does not appear to trigger the onPlayerChangedDimension event, bypassing your check and successfully landing in the dimension.

**Comment by ljfa-ag** [comment]
> One question though: How did you plan to get to the dimension? I am not going to make the portal just work for admins, even with a config, and /tpx does not work because I stop link books from working.

What about a command similar to /tpx for CC dimensions?

**Comment by ReikaKalseki** [comment]
Apparently CoFH already has that functionality.

**Comment by WillowMauldin** [comment]
Well it doesn't bypass any protections, it's just a general teleportation command that works across dimensions.

**Comment by ReikaKalseki** [comment]
Right, which works for getting to the CC dimension...assuming CC did not kick you back out. I had an idea: What about a consumable admin-only item that lets you enter (i.e. is consumed on dimension entry but permits actual entry).

**Comment by WillowMauldin** [comment]
That sounds like a good idea.

**Comment by ReikaKalseki** [comment]
After a great deal of thought, I do not see a good way to do this without either removing the protection entirely or nullifying the very idea of progression for admins.
