### ISSUE TITLE
[Reactorcraft] Pebblebed reactor core configuration issues.

### ISSUE THREAD

**Issue by danmarcnichols** [ReikaKalseki/Reika_Mods_Issues#672]
The Version i used :
Rotarycraft V11b
Reactorcraft V11b
DragonAPI V11b

I'll start off by saying I don't know if this has always been the case or only because of the recent update, but the pebblebed reactor core configurations I have tried have not been working. For the sake of this description I'll represent the pebblebed core as, _PBC_, and the carbon dioxide heat exchanger as, _CDHE_. I have tried PBC to CDHE ratios of:

1:8
1:1
4:1
6:1
8:1

None of these configurations ever reach above 240 degrees C and all are in enclosed, air isolated systems with the carbon dioxide inside all the heat exchangers. Again I am unsure if this is a bug or this is an intended trait of these components. If Reika or any other players could shed some light on this matter, it would be greatly appreciated.

I am in creative mode using superflat save file format.

**Comment by ReikaKalseki** [comment]
Already fixed for v12.

**Comment by danmarcnichols** [comment]
Thank you very much Reika. When does v12 launch?

**Comment by danmarcnichols** [comment]
Also I appreciate this mod very much, especially since I'm a Nuclear Engineer. Let me know if you ever need assistance.

**Comment by TomeWyrm** [comment]
> When does v12 launch?

When it's ready. Reika doesn't really have a good idea until it's REALLY close, and even then it's a wild-ass-guess because there's nearly always some error that is eluding fix which is holding back release.

**Comment by danmarcnichols** [comment]
Alright. Thanks for the heads-up

**Comment by ReikaKalseki** [comment]
> Let me know if you ever need assistance.

You are always free to make suggestions, but that is not the purpose of the issue tracker.
