### ISSUE TITLE
ChromatiCraft OreSilker Harvest level should be tied to Diamonds

### ISSUE THREAD

**Issue by nmarshall23** [ReikaKalseki/Reika_Mods_Issues#673]
The modpack, I am playing has changed the harvest level of Diamond tools. 

Looking at the [source code](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Items/Tools/ItemOreSilker.java) theOreSilker's harvest level is hard coded to 3. Could you do something like what you did with the [SteelPick](https://github.com/ReikaKalseki/RotaryCraft/blob/master/Items/Tools/Steel/ItemSteelPick.java) but track diamond pickaxe?

**Comment by ReikaKalseki** [comment]
Done.
