### ISSUE TITLE
DragonAPI v11b removes valid recipes for previously-invalid items.

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#674]
DragonAPI v11 removes items with nulled inputs during startup. This is great and the log helps. However, upon adding a valid crafting recipe for the item using Minetweaker, DragonAPI continues to remove the item. For example, the Apiarist's Chest in Forestry has a null input stack. Adding this line of minetweaker script should add a valid recipe for it:

```
recipes.remove(<Forestry:apicultureChest>);
recipes.addShaped(<Forestry:apicultureChest>, [[null,<ore:blockGlass>,null],[<ore:beeComb>,<ore:chest>,<ore:beeComb>],[<ore:beeComb>,<ore:beeComb>,<ore:beeComb>]]);
```

However, loading the script results in this output in the console:

```
[05/3/2016 13:27:30 PM] [Server thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:158]: MineTweaker: Loading Forestry.zs
[05/3/2016 13:27:30 PM] [Server thread/INFO] [FML]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes.
```

I know there's some other issues with Forestry items (per the reddit thread); I don't know if DragonAPI is also filtering these items because of those issues. If so, DragonAPI should note with an alternate message that the item is invalid, versus just the recipe.

EDIT: To clarify, this only affects previously-erroring recipes. The null stack in the recipe above is used elsewhere and DragonAPI does not remove those recipes.

**Comment by ReikaKalseki** [comment]
It should only remove ItemStacks of null, not null _as_ the ItemStack (i.e. empty slot). Is MT wrapping that null as an ItemStack of null? That may explain the Ztones issue.

**Comment by Haggle1996** [comment]
Like I mentioned in the EDIT, only items previously removed by MT get removed again. For kicks and giggles, I assigned this exact recipe to craft a minecraft:stick and it works fine, so it's something to do with it crafting the apiarist chest, not the recipe itself.

**Comment by TomeWyrm** [comment]
Ah crap. I was going to play Infinity Evolved Expert mod with ChromatiCraft (yes, yes, I know. It won't be part of the progression. That's the point. I want SOMETHING to do while I'm waiting for all the grindfest-of-doomtastic-doom-doom to finish up its shit). But I got a few "DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes." in the middle of the expert mode MT activation.

Is there an indication earlier in the logfile that will tell me WHAT recipes are problematic so I can implement alternatives? Or some way that doesn't involve disabling/enabling lines in the MT scripts and reloading a lot?

**Comment by ReikaKalseki** [comment]
As of v12, it will log more data about the recipe, but I cannot print the whole thing, as doing so would cause a crash (toString() on ItemStack of null throws an NPE).

**Comment by TomeWyrm** [comment]
Could the non-null portions be printed?

**Comment by ReikaKalseki** [comment]
I would have to special-handle the whole recipe, which cannot really be done "generally". I do, however, print the _output_ (if it is safe) but that may not help much here.

Internally, all a recipe is is an array of ItemStack[](or List<ItemStack>, if OreDict); nulls correspond to empty slots, but ItemStack(null) is simply invalid. Even _were_ I to print all of the ingredients, what new information would it provide? We already know some slots are whatever (whatever was specified in the recipe), some are likely "full null", and some are ItemStack(null).

**Comment by TomeWyrm** [comment]
Hmm... mod registering the recipe and output SHOULD give you all the information required. Especially if it's in unlocalized (if you can trivially call the localized version as well, that'd be helpful). I mean knowing that IC2 is registering a null itemstack input to a recipe for "MineFactoryReloaded:plastic.sheet" would be reasonably informative :-)

Especially if it's minetweaker. Seeing this:

DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Registering mod: "MineTweaker3". Recipe output is "ExtraUtilities:angelRing". Removing to prevent crashes.

Would be incredibly helpful... especially if we figure out why it's removing valid recipes along with the invalid ones.

**Comment by ReikaKalseki** [comment]
There is no way to find the mod that created it. I do print the recipe class, but if it is a vanilla/Forge ShapedRecipes or ShapedOreRecipe (or the shapeless counterparts) that provides nothing useful.

**Comment by Haggle1996** [comment]
Despite thread hijacking, the original issue still remains: DragonAPI is removing the item even though a valid recipe is assigned to it via minetweaker. Is the only solution to disable DragonAPI's culling of the invalid items

**Comment by ReikaKalseki** [comment]
It does not cull on an item-by-item basis. It culls individual recipe objects. So it should only be removing recipes that actually are invalid, which I would expect does not include ones added by MT. Try changing the output of the apiarist chest recipe to output something else. Does it still get culled?

**Comment by Haggle1996** [comment]
Yes, as mentioned previously, changing the output to a stick is valid.

EDIT:

This works:

```
recipes.addShaped(<minecraft:stick>, [[null,<ore:blockGlass>,null],[<ore:beeComb>,<ore:chest>,<ore:beeComb>],[<ore:beeComb>,<ore:beeComb>,<ore:beeComb>]]);
```

This results in the invalid recipe message from DragonAPI:

```
recipes.addShaped(<Forestry:apicultureChest>, [[null,<ore:blockGlass>,null],[<ore:beeComb>,<ore:chest>,<ore:beeComb>],[<ore:beeComb>,<ore:beeComb>,<ore:beeComb>]]);
```

**Comment by ReikaKalseki** [comment]
What that then means is that the lookup `<Forestry:apicultureChest>` returns null. Does that item still exist and is that name correct?

**Comment by Haggle1996** [comment]
Yes, it does. Visible in NEI and can /give it.

**Comment by TomeWyrm** [comment]
Erm... unless I can't read the code, shouldn't the message be outputting the class involved?
https://github.com/ReikaKalseki/DragonAPI/blob/master/DragonAPIInit.java#L811

**Comment by ReikaKalseki** [comment]
That change did not make it into v11.

@Haggle1996: Temporarily remove DragonAPI and see if the recipe actually works.

**Comment by Haggle1996** [comment]
As the recipe was the default recipe for the Apiarist's Chest (was trying to add it back after DragonAPI deleted it), it looked like it worked fine (MT didn't report an error). To be certain, I tweaked it to replace one of the 5 combs with a stick. The recipe loaded okay. Reloaded DragonAPI (and the remainder of your mods) and tested with the same recipe -- same error.

**Comment by TomeWyrm** [comment]
I've got an idea... you know, after applying the patch, booting into the world once, then removing dragonAPI (and the rest of reika's mods), and testing to make sure the apiarist's chest works normally sans-dragonAPI

If that does work, try replacing the entire chest recipe with vanilla mats, obviously with DragonAPI removing the null recipe once again.

**Comment by Keyarose** [comment]
As a possibly related side note I was having the same issue with the forestry bee house.  I attempted to fix it by specifying the original recipe with Mine Tweaker, which didn't work.  I then used MT to define my own oredict entry for bee combs and replaced it in the recipe for both the chest and house.  This for some reason worked.

MT script:

> val comb = ore:beeCombs;
> comb.add(Forestry:beeCombs);
> comb.add(Forestry:beeCombs:1);
> comb.add(Forestry:beeCombs:2);
> comb.add(Forestry:beeCombs:3);
> comb.add(Forestry:beeCombs:4);
> comb.add(Forestry:beeCombs:5);
> comb.add(Forestry:beeCombs:6);
> comb.add(Forestry:beeCombs:7);
> comb.add(Forestry:beeCombs:8);
> comb.add(Forestry:beeCombs:9);
> comb.add(Forestry:beeCombs:10);
> comb.add(Forestry:beeCombs:11);
> comb.add(Forestry:beeCombs:12);
> comb.add(Forestry:beeCombs:13);
> comb.add(Forestry:beeCombs:14);
> comb.add(Forestry:beeCombs:15);
> comb.add(Forestry:beeCombs:16);
> comb.add(MagicBees:comb);
> 
> recipes.addShaped(Forestry:apicultureChest, [[null, ore:glass, null], [comb, ore:chestWood, comb], [comb, comb, comb]]);

**Comment by ReikaKalseki** [comment]
I just checked: For OreDict recipes (which use `List<ItemStack>` in place of normal ItemStack for the OreDicted slots), any one of the entries under a tag (and thus in the list) being invalid would trigger a failure. However, such values are not permitted to be added to the OreDict by DragonAPI, and if it is a certain output that is triggering the removal (not an input), then this is irrelevant.

**However:** The `verifyItemStack()` method, used on the output, is as follows:

```
public static boolean verifyItemStack(ItemStack is) {
    if (is == null)
        return true;
    if (is.getItem() == null)
        return false;
    try {
        is.toString();
        is.getDisplayName();
    }
    catch (Exception e) {
        return false;
    }
    return true;
}
```

If either `toString()` (which uses the unlocalized name) or the `getDisplayName()` throw an exception, the recipe will fail. However, I assume the recipe-given version of the apiarist chest is metadata zero, not some wildcard, and _should_ work. If it does not, we will have to wait for v12, where the sanity checker would catch it.

**Comment by ReikaKalseki** [comment]
So...

**Comment by ReikaKalseki** [comment]
Hello?

Also, the Ztones issue has been identified; he adds the recipes using the Ofanix as an input even when the item is disabled (and not in the game registry).

**Comment by TomeWyrm** [comment]
Oversight, or intentional? Because that seems rather a silly thing to do on purpose.

**Comment by ReikaKalseki** [comment]
He is not alone - AE does the same with its cables and channels, and Forestry does it in mod handling - but yes, it is a dumb thing to do, and exactly what my sanity checker is for.

**Comment by Keyarose** [comment]
Just tried the Forestry bee house and apiarist chests with V12e, the recipes are still missing unfortunately. On the positive side another recipe that was disappearing is back, the Factorization packager.

**Comment by ReikaKalseki** [comment]
The recipe will still be missing, but there will be more information in the log as to why.

**Comment by Keyarose** [comment]
Found it in the fml client latest log.

> [10:12:46] [Client thread/INFO] [FML/Forestry]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class forestry.core.recipes.ShapedRecipeCustom, Output=1xtile.for.apicultureChest@0.
> [10:12:46] [Client thread/INFO] [FML/Forestry]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class forestry.core.recipes.ShapedRecipeCustom, Output=1xtile.for.apiculture@2.

Its also finding the Alkahestry recipes from reliquary

> [10:12:32] [Client thread/INFO] [FML/xreliquary]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class xreliquary.items.alkahestry.AlkahestryDrainRecipe, Output is a null-item ItemStack.
> [10:12:32] [Client thread/INFO] [FML/xreliquary]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class xreliquary.items.alkahestry.AlkahestryRedstoneRecipe, Output is a null-item ItemStack.
> [10:12:32] [Client thread/INFO] [FML/xreliquary]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class xreliquary.items.alkahestry.AlkahestryCraftingRecipe, Output is a null-item ItemStack.

and thermal expansion's rock wool and satchel

> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraftforge.oredict.ShapedOreRecipe, Output=1xitem.thermalexpansion.satchel@1.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraftforge.oredict.ShapedOreRecipe, Output=1xitem.thermalexpansion.augment@113.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@0.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@1.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@2.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@3.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@4.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@5.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@6.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@7.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@8.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@9.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@10.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@11.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@12.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@13.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@14.
> [10:13:19] [Client thread/INFO] [FML/ThermalExpansion]: DRAGONAPI: Invalid recipe, such as with nulled inputs, found. Removing to prevent crashes. Class=class net.minecraft.item.crafting.ShapedRecipes, Output=8xtile.thermalexpansion.rockwool@15.

**Comment by ReikaKalseki** [comment]
So the recipe object is a native Forestry one, i.e. not added by Minetweaker. It is not removing the MT ones, so why are they uncraftable?

**Comment by Keyarose** [comment]
The MT recipes I made use my own ore dict definition for the combs, if I make the recipes using the forestry defined ore dict then it does remove them.  So I'm guessing something is adding something strange to the ore dict.

**Comment by ReikaKalseki** [comment]
I just had an idea, which I think will fix it.
