### ISSUE TITLE
Difficulty progressing research level

### ISSUE THREAD

**Issue by Keyarose** [ReikaKalseki/Reika_Mods_Issues#675]
I've been having difficulty progressing to the Multicraft research level. Current research level is Chargeself(5) I think.  I have crafted a number of Temple casting recipes, but the NBT flag for temple is never set. Casting progress flags that are set are crafting, and multiblock(from making crystal core I think).

Temple casting recipes tried: Item Casting Stand, Elemental Lamp, Heat Lamp, Linker, Inventory Warp, and crystal groups required for the crystal core.

Version 11b

**Comment by ReikaKalseki** [comment]
It sounds like it _should_ be giving you the required progress...

**Comment by Keyarose** [comment]
Unfortunately unused fragments remain blank, and NBT gives 5 for the Research Level(I assume I am remembering correctly that Java enums start at 0 like every other language)
I'll hold off on manually changing the Research Level for now if any testing needs to be done.

**Comment by ReikaKalseki** [comment]
Have you charged yourself?

**Comment by Keyarose** [comment]
Yes, not to the point where the limit increases though.

**Comment by TomeWyrm** [comment]
Whyever not? Increasing your limit once is basically the same as going to discover all the colors (at least the way I do it, and I assume many others...)

Now increasing it to the MAX limit? That's a bit of a pain. The only ChromatiCraft-limited strategy I would call viable is using Warp Glass, at least until you have a lumen tree. I personally prefer using another teleportation mod... I find warp glass a bit finicky to use. But it DOES work very well.

**Comment by Keyarose** [comment]
Just hadn't gotten to it, I tried it after I mentioned it and crafted something else just in case.  Wasn't the issue unfortunately.  I didn't do it when discovering the colors cause I died a few times between finding them all.  Grimore of Gaia mobs can be nasty early on, especially the daytime desert ones.

I use journey map with waypoints to go between large distances, it is a little cheaty since its free teleportation though.

**Comment by ReikaKalseki** [comment]
Increasing the limit is not going to fix this issue.

**Comment by TomeWyrm** [comment]
OH... yeah SSP/Admin powers teleports are a bit cheaty :-p

I used Mystcraft Intra-age linking books on the last server I played on. Discovered a few issues... but overall it was pretty good. I dropped right at the edge of manipulator range, and could go right to the next one. I was tempted to go find a few more of the colors I was using a lot of to make smaller, color-specific loops.

**Comment by Keyarose** [comment]
Reika: I didn't think so, but though I should check just in case.

TomeWyrm: I used Mystcraft books on some of my older worlds; unfortunately because I'm using Not Enough IDs it messes with Lookingglass causing a crash caught by Fastcraft.  It's not a 100% of the time crash but it's enough.  I'm hoping for a fix on the next Fastcraft test build.
