### ISSUE TITLE
Portal not working

### ISSUE THREAD

**Issue by echthesia** [ReikaKalseki/Reika_Mods_Issues#676]
The Chromaticraft portal beacon is not working. Whenever I go in, it continuously makes the ring particles like I'm hitting the ground constantly, and makes the "clunk" sound continuously. What am I doing wrong? I have all progress; I have used /chromaprog <username> maximize -1. Oh, and is there a way to place the whole structure in debug test mode? That might help to see if I built it wrong. It is in the Overworld, if that matters.

![2016-03-05_19 23 55](https://cloud.githubusercontent.com/assets/17151810/13551698/474a9150-e308-11e5-81cb-d0e8b134bb7f.png) 
![2016-03-05_19 24 05](https://cloud.githubusercontent.com/assets/17151810/13551702/5b4650e0-e308-11e5-9520-5ee05ae5efc0.png)
![2016-03-05_19 24 12](https://cloud.githubusercontent.com/assets/17151810/13551704/5b723bce-e308-11e5-81d2-38914640f5aa.png)
![2016-03-05_19 24 18](https://cloud.githubusercontent.com/assets/17151810/13551703/5b6dcdaa-e308-11e5-9688-65414e66939a.png)
![2016-03-05_19 24 23](https://cloud.githubusercontent.com/assets/17151810/13551705/5b9b4f0a-e308-11e5-9827-13be5514bae9.png)

**Comment by ReikaKalseki** [comment]
I can see in the screenshot that you built it incorrectly.

**Comment by echthesia** [comment]
Can you tell me what I did wrong? I checked the structure from the screenshot viewpoints (and others) against the lexicon and found no error. I'm probably missing something obvious, but what did I do?

**Comment by Shahelion** [comment]
Did you check the material list beforehand to make sure you had everything you needed?

After looking at each screenshot extremely closely...I have no idea where you went wrong. Looks fine to me...

**Comment by echthesia** [comment]
I didn't; I built it in creative. Can't see any error either. With the power of the screenshots, I summon the wise and powerful Reika, who clearly knows something we don't.

**Comment by Zsashas** [comment]
Do you have the progression required?

**Comment by Shahelion** [comment]
My point wasn't having enough. My point was check the material list in the book to make sure you have all the RIGHT blocks.

Don't build something like this in Creative. If you're gonna use Creative, just give yourself the blocks then switch back to survival to build it.

**Comment by echthesia** [comment]
Actually, I did build it in survival. In any case, in the ring around the portal blocks with the aura stabilizers, I used 12 groove blocks instead of 6 grooves and 6 groove 2s. Reika really makes it hard to build a portal.

**Comment by ReikaKalseki** [comment]
The nonalignment of the grooves should have been obvious.

**Comment by Shahelion** [comment]
Like I said, if you'd used the material list in the book, this probably wouldn't have happened.
