### ISSUE TITLE
Chromaticraft Crashes after Postinitialization

### ISSUE THREAD

**Issue by memzak** [ReikaKalseki/Reika_Mods_Issues#677]
Hi, 

I haven't found anything similar after a quick search of both the MCF and this issues page and could be missing something obvious but given your usually quick response time and better understanding of your mod, could you tell me if / what I'm doing wrong and whether it is indeed an issue? 

Attached is the last section (just after the thousands of Enderchest registries) of the crash log, which includes all the mods loaded. If you need anything else I'll upload it as well, the crash log is too big to post directly to pastebin.

http://pastebin.com/FBGDyd3U

**Comment by Aivech** [comment]
You can use [Gist](https://gist.github.com) to upload the whole file.

**Comment by ReikaKalseki** [comment]
Use Forestry 4 and AE rv2.

#664, #659
