### ISSUE TITLE
NEI search crash

### ISSUE THREAD

**Issue by mathwiz617** [ReikaKalseki/Reika_Mods_Issues#68]
I clicked on "Nether Diamond Flakes" in NEI, out of curiosity, and the game crashed. I believe I am using the latest versions of Rieka's mods. This is a custom modpack, based off of FTB Lite 3, with a few mods added and a few removed. A few RotaryCraft configs were changed, but no code or Minetweaker or anything.

http://pastebin.com/JmrCruUB

It's probably as easy to avoid as "don't do that again", but I figured I'd report it anyway.

**Comment by theoanden** [comment]
Duplicate #10
