### ISSUE TITLE
Inefficient Repeater Pathing

### ISSUE THREAD

**Issue by murapix** [ReikaKalseki/Reika_Mods_Issues#683]
Using Chromaticraft v11a, and just got started on linking pylons up to my Casting Complex. When I started using the pylons for crafting though, I noticed that the colors were going through the repeaters very inefficiently. As you can see in this [image](http://i.imgur.com/TDFaTGu.png), Vadali is going through two multi-aura repeaters before the complex's repeater, while it already has direct access to the complex's repeater. The two Vadali repeaters are in range of each other, have line of sight, and were linked before I placed the multi-aura repeaters. The same happens with other colors, especially Ruskea, which goes completely around the altar before going in, even though the two Ruskea repeaters are only a distance of 25 blocks apart.

**Comment by TomeWyrm** [comment]
First: "Make Pylon pathfinding attempt shortest path - can be intensive". Learn to read a config file and test with it maybe?

Second: Update to v11b. Always try to stay on the latest version of any of Reikas mods unless it really truly is not possible. Even then if it's a person-reason why you cannot? Pester THEM to update. There is a reason that Reika goes to great lengths to remove old versions (actually a lot of reasons :-p).

**Comment by murapix** [comment]
Ah sorry, I should have checked the configs before saying anything about it.

**Comment by ReikaKalseki** [comment]
Also, that means finding the shortest path _per jump_, not in total. _That_ would require a full network scan and be unmanageable.
