### ISSUE TITLE
Could not initialize class Reika.ChromatiCraft.Registry.ChromaResearchManager$ResearchLevel

### ISSUE THREAD

**Issue by bpwhelan** [ReikaKalseki/Reika_Mods_Issues#684]
I've seen an issue with a similar error thrown a full 5 months ago (with AE2), but I am currently experiencing it at sporadic times as of late. I cannot trace this down to anything so this is sort of a desperate call for help. Crash during startup.

Full crashlog: http://pastebin.com/36nNg9xc.

 If it's just me being stupid i would enjoy a slap on the wrist.

**Comment by ReikaKalseki** [comment]
#677, #664, #659

**Comment by bpwhelan** [comment]
For some reason I thought I removed ae2 completely and still had the crash, apparently i was totally derping.

**Comment by ReikaKalseki** [comment]
Even if you did, that would mean little; other mods can also cause it.

**Comment by bpwhelan** [comment]
Yeah, I should have further specified, was already on forrestry 4 and downgrading ae2 fixed it. That's my reasoning for the above comment.
