### ISSUE TITLE
[Feature Request] [Chromaticraft] Particle Generator

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#685]
Similar to the one from Draconic Evolution, combined with the one from Ars Magica 2, and the various particle mechanisms from Botania (flare lens, unstable beacons, etc.).

Things that would have options in the GUI:

1: Type of particle
1a: Colour of particles, either just the 16 MC colours, or three slider scales for RGB
2: Source coordinates, with a second offset slider to allow for randomness within a certain range
3: Direction of motion, in all three axes, again with a second slider to allow for variations
4: Strength of gravity, including negative strength
5: Size of particles, also with a variation slider
6: Duration/lifespan/decay/whatever
7: Block collision toggle

**Comment by ReikaKalseki** [comment]
I can nicely tie this into the internal particle code, as most of those correspond to actual parameters on my EntityFX objects.

**Comment by ReikaKalseki** [comment]
Done.
![](http://i.imgur.com/2nAdfNX.png)
