### ISSUE TITLE
java.lang.ClassCastException: Reika.RotaryCraft.TileEntities.Storage.TileEntityReservoir cannot be cast to Reika.ChromatiCraft.Block.BlockActiveChroma$TileEntityChroma

### ISSUE THREAD

**Issue by Schadrach** [ReikaKalseki/Reika_Mods_Issues#687]
Was juggling some stuff around to set up an automatic filler for my infusion stand and client crashed with java.lang.ClassCastException: Reika.RotaryCraft.TileEntities.Storage.TileEntityReservoir cannot be cast to Reika.ChromatiCraft.Block.BlockActiveChroma$TileEntityChroma

Client crash repeats on login since.

Not sure if your mods or the Witching Gadgets crystal capsule is the cause.

http://pastebin.com/KEwucD7K

**Comment by ReikaKalseki** [comment]
You have a block/TileEntity mismatch, most likely either a random error or caused by someone screwing with how MC handles setBlock and setTileEntity.

**Comment by Schadrach** [comment]
Interestingly, having another player log in and mine up the only reservoir I'd recently interacted with seemed to solve that crash.  It came back a bit later when I was redoing a crop irrigation system, except that now instead of it saying it can't type cast from a reservoir, it's saying it can't typecast from tilled garden soil and the crash occurs upon opening inventory rather than login.  The crash report is identical aside from which class it is trying to typecast from.

I suspect that a Crystal Capsule from Witching Gadgets filled with liquid chroma is doing something really extremely funky to cause it to attempt that typecast (since the rest of the crash report is identical except for which class it's trying to typecast from, appears to be related to the crystal capsule's renderitem method, and the crash at login happened with the capsule in my hotbar while the new crash happens when I open my inventory and the capsule is now in my inventory), which would totally have nothing to do with you, aside from it being filled with chroma and it trying to cast a reservoir the first time.

Sorry for the agitation.
