### ISSUE TITLE
Crash to desktop when looking up sand or gravel recipes.

### ISSUE THREAD

**Issue by demethan** [ReikaKalseki/Reika_Mods_Issues#688]
here is the crash log. http://pastebin.com/DW4LvGuh
pack is https://www.atlauncher.com/pack/BreakfastBuffet

We are on 11b. I am no coder so the crash log doesn't give me any insight on how to fix this. 

Thanks for your help.

**Comment by ReikaKalseki** [comment]
Apparently this is an Avartia bug and is fixed in their update. #680
