### ISSUE TITLE
[Load Issue] mod won't load save file anymore

### ISSUE THREAD

**Issue by danmarcnichols** [ReikaKalseki/Reika_Mods_Issues#689]
Using:
DagonAPI 1.7.10 V11b
Rotarycraft 1.7.10 V11b
Reactorcraft 1.7.10 V11b

I went to load up my save file this morning and after I click on the save file, it starts loading and then crashes with the following error:

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 3/15/16 1:37 PM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: -8
    at net.minecraft.world.chunk.NibbleArray.func_76582_a(SourceFile:28)
    at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76665_b(SourceFile:75)
    at net.minecraft.world.chunk.Chunk.func_76628_c(Chunk.java:548)
    at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:878)
    at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:862)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:500)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
    at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
    at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 425548224 bytes (405 MB) / 787386368 bytes (750 MB) up to 2120679424 bytes (2022 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 7 mods loaded, 7 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FML{7.10.85.1291} [Forge Mod Loader](forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forge{10.13.2.1291} [Minecraft Forge](forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    DragonAPI{1.0} [DragonAPI](DragonAPI 1.7.10 V11b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    RotaryCraft{1.0} [RotaryCraft](RotaryCraft 1.7.10 V11b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ReactorCraft{1.0} [ReactorCraft](ReactorCraft 1.7.10 V11b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

I tried making a copy of the save and manipulating it to work, and I was able to get everything but the r.0.0.mca file to run without the save crashing. The problem is that even copying over the files from the previous save, it will not load the map correctly. It loads only the world seed and the player inventory and all the machines that used to be on the map are gone. Even the terraforming that I did vanished. If you have any advice, I'd love to hear your thoughts

**Comment by ReikaKalseki** [comment]
Something set a block's metadata to -8, either during the world or during the save (or to the file itself afterwards). Your world is corrupt, and nothing short of purging that chunk or manually editing its data can recover it.

**Comment by danmarcnichols** [comment]
I was able to fix it. Thanks for the tip Reika.
