### ISSUE TITLE
Crash to desktop: looking in chroma book

### ISSUE THREAD

**Issue by OmegaCenti** [ReikaKalseki/Reika_Mods_Issues#690]
client log
https://gist.github.com/anonymous/8092868dc49a7ee34cfe

crash log
https://gist.github.com/OmegaCenti/9ebd9b946c6ba8e36a5a

**Comment by OmegaCenti** [comment]
another event like the last
https://gist.github.com/OmegaCenti/273307a4a9be187eff84

**Comment by ljfa-ag** [comment]
Does it also happen without Fastcraft?
Seems like the Tesselator was not used correctly somewhere.

**Comment by ReikaKalseki** [comment]
This is a renderer error, and none of my code is in the stacktrace. Shaders are apparently involved.

**Comment by Builderb0y** [comment]
No, this is natura being dumb, and registering items to the ore dictionary that crash upon being rendered.

(just before the crash):
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
at mods.natura.blocks.trees.NLeaves.func_149691_a(NLeaves.java:159)

**Comment by ljfa-ag** [comment]
Hm, possibly. The renderer starts using the tesselator, throws a caught exception halfway through and doesn't finish drawing.
Try without Natura.

**Comment by ReikaKalseki** [comment]
That would crash anyways, so there is nothing on my end to do.

I actually fixed this for DragonRealm, and it took an ASM patch into BlockNLeaves to fix it.
