### ISSUE TITLE
CromatiCraft crash on startup (crossmod interaction)

### ISSUE THREAD

**Issue by DracoScythem** [ReikaKalseki/Reika_Mods_Issues#691]
The most recent version (11b) of Cromaticraft crashes on startup in my current mod constellation
(that's the head of the crash-report, full log link below)

java.lang.ArrayIndexOutOfBoundsException: 9
    at java.util.EnumMap.put(Unknown Source)
    at java.util.EnumMap.put(Unknown Source)
    at Reika.DragonAPI.Libraries.ReikaRegistryHelper.addSoundCategory(ReikaRegistryHelper.java:324)
    at Reika.ChromatiCraft.ChromaClient.registerSounds(ChromaClient.java:148)

https://gist.github.com/Leguan12/04f242fc1a36015f189e/raw/7ce876c33d4e1fbd9ebc9c79b7b1ffe6962c5a2f/fml-client-latest.log
Removing HardCoreEnderExpansion does fx it, though if I only throw DragonAPI, CC and HEE together it works. (I've read the log file and searched it for any hints, found nothing)
If you need any more info, just ask :)

**Comment by ReikaKalseki** [comment]
#640, #659, [HEE170](https://github.com/chylex/Hardcore-Ender-Expansion/issues/170)
