### ISSUE TITLE
Question: ComputerCraft API for Extractor

### ISSUE THREAD

**Issue by demethan** [ReikaKalseki/Reika_Mods_Issues#693]
Hi Reika, 

I'm trying to write a quick and dirty program to control the extractor setup. 
Do you have any documentation on how to use the functions.
x.getInvSizeInv() give me 10 slots.

for slot 0-9 x.getSlot(slotNumber) doesn't seem to yield any data and  x.getSlot(10) give a java error.  What am I doing wrong?

right now I detect if there is ore to process with x.printInv() and doing a string match. But that only works with the raw ore slot. 

Thank for any help. 

[extractor.lua](https://dl.dropboxusercontent.com/u/2804046/CCPrograms/extractor/extractor)

**Comment by ReikaKalseki** [comment]
`getSlot()` returns a array-format representation of an ItemStack, as []{Item, Damage, StackSize, Display}. Note that in v12 the Item is changed to unlocalized name, and there is a fifth parameter of the NBT.

Also, if the slot is empty, null is returned.

**Comment by demethan** [comment]
Thanks much
