### ISSUE TITLE
[Feature Request] [Rotarycraft] Factorization Bedrock

### ISSUE THREAD

**Issue by Keyarose** [ReikaKalseki/Reika_Mods_Issues#694]
Right now the bedrock breaker seems to be unable to break the Blasted Bedrock from Factorization.  I noticed that it was previously able to break it back in V14 for 1.6.4 and was wondering if it could be added to 1.7.10.  Unless it's something that should be implemented on Factorization's side, then I'll see if I can find where to request it from their dev.

**Comment by ReikaKalseki** [comment]
The handler is still in place. Check your logs for relevant errors.

**Comment by Keyarose** [comment]
Any particular keywords to search for in the log? They get kind of big.

**Comment by Keyarose** [comment]
Just for reference my setup for trying to break a Blasted Bedrock block is just the breaker and a creative Industrial Coil at 99,999 rad/s, 99,999 Nm.  The normal operation sound and particles show up, but the block never reduces to slices or breaks.

**Comment by ReikaKalseki** [comment]
Look for factorization-related errors.

**Comment by Keyarose** [comment]
I ran the bedrock breaker for 20min and then closed out the world before checking the log file.  I couldn't find any errors relating to bedrock or factorization, aside from an issue between it and thaumichorizons.

**Comment by ReikaKalseki** [comment]
The error would be during the boot phase.

**Comment by Keyarose** [comment]
I've combed through the entire boot phase of the log but I couldn't find any errors relating to factorization bedrock or the breaker.  I did find a number of DragonAPI notices about factorization that suggested everything was ok.  I don't know how relevant these are but other than this the only thing I found were oredic registrations.

> [13:07:58] [Client thread/INFO] [FML/ChromatiCraft]: DRAGONAPI: factorization detected in the MC installation. Adjusting behavior accordingly.
> [13:07:58] [Client thread/INFO] [FML/ChromatiCraft]: DRAGONAPI: Attempting to load data from factorization
> [13:08:01] [Client thread/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper/factorization.truth]: DragonAPI: Patching class net.minecraft.inventory.Slot
> [13:08:01] [Client thread/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper/factorization.truth]: DragonAPI: Successfully applied SLOTCLICKEVENT ASM handler 1!
> [13:08:01] [Client thread/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper/factorization.truth]: DragonAPI: Successfully applied SLOTCLICKEVENT ASM handler 2!
> [13:09:40] [Client thread/INFO] [FML/DragonAPI]: DRAGONAPI: Found block class for factorization: class factorization.common.Registry
> [13:09:40] [Client thread/INFO] [FML/DragonAPI]: DRAGONAPI: Loading handler class Reika.DragonAPI.ModInteract.ItemHandlers.FactorizationHandler for mod factorization 0.8.107.
> [13:10:28] [Client thread/INFO] [FML/RotaryCraft]: ROTARYCRAFT: Forcing compatibility with factorization
> [13:10:28] [Client thread/INFO] [FML/RotaryCraft]: ROTARYCRAFT: RotaryCraft dark iron ingots can now be crafted into Factorization equivalents!

**Comment by ReikaKalseki** [comment]
Wait what?

> [Reika.DragonAPI.Libraries.Java.ReikaASMHelper/factorization.truth]:

**Comment by Keyarose** [comment]
I believe that was in the preinit phase(could be wrong), other than that there wasn't any real context for that line.

**Comment by redelman** [comment]
I believe Reika was referring to the fact that there is no such
string "factorization.truth" anywhere in DragonAPI.

**Comment by Keyarose** [comment]
Ah, from what I understand of the log it's a sub module of factorization.

**Comment by ReikaKalseki** [comment]
But why is it showing up in my loggers?

**Comment by Keyarose** [comment]
Dropped the log here if you want to look through it yourself.
https://gist.github.com/Keyarose/43d9d82d05df6854f8f9

**Comment by ReikaKalseki** [comment]
I see nothing either. Then why is it failing?

**Comment by Keyarose** [comment]
I belive I might have found the issue, Factorization adds two kinds of bedrock Fractured Bedrock(factorization:FracturedBedrock), and Blasted Bedrock(factorization:BlastedBedrock).  The bedrock breaker works perfectly on Fractured Bedrock, it's just the Blasted Bedrock which it does nothing to.  So its likely the handler is only targeting the fractured bedrock rather than both.

**Comment by Keyarose** [comment]
Also as far as I know Fractured Bedrock only appears at y = 0, so the breaker wouldn't be able to break it in normal cases anyway.

**Comment by ReikaKalseki** [comment]
Oh...

**Comment by ReikaKalseki** [comment]
Unfortunately, Factorization does not get along with JD-GUI:

![](http://i.imgur.com/byrg1Ms.png)

I need to resort to printing the fields with reflection in the dev environment...

**Comment by ReikaKalseki** [comment]
Done.
