### ISSUE TITLE
Sodium heater doesn't allow extraction of hot sodium via Steve's Factory Manager

### ISSUE THREAD

**Issue by kalenedrael** [ReikaKalseki/Reika_Mods_Issues#695]
...and, I suspect, other mods that use this method:

```
public final FluidStack drain(ForgeDirection from, FluidStack resource, boolean doDrain)
```

rather than this one:

```
public final FluidStack drain(ForgeDirection from, int maxDrain, boolean doDrain)
```

because it appears to be trying to drain from the main tank `tank`, not `output`. Steve's instead fills my output drum with normal sodium, which doesn't seem like something that should ever happen.

**Comment by ReikaKalseki** [comment]
What direction is being supplied?

**Comment by kalenedrael** [comment]
Up.

EDIT: specifying all directions also doesn't work

**Comment by ReikaKalseki** [comment]
Fixed.
