### ISSUE TITLE
the bug on Tokamak

### ISSUE THREAD

**Issue by a342617810** [ReikaKalseki/Reika_Mods_Issues#696]
I come from china，Use google translate，i can not speak English，
There is a movie about the bug，i need your help。
http://pan.baidu.com/s/1pKDLDlL

**Comment by ReikaKalseki** [comment]
![](http://i.imgur.com/arAUoqC.png)

**Comment by Gaelan** [comment]
@ReikaKalseki I managed to get a copy of the video: https://drive.google.com/file/d/0Bx-KqUnOIXbWcXhPcm9Bc0Y4SUk/view?usp=sharing

**Comment by ReikaKalseki** [comment]
Use a distribution platform like Youtube. I am not downloading it as a file.

**Comment by Aivech** [comment]
Google Drive has an embedded player. 

The issue is that the plasma entities are flying out of the tokomak on a curved path - like an inverted spiral. Some of them make it around, but most of them fly out on a curved path at some point or another on the ring.

**Comment by ReikaKalseki** [comment]
That sounds like lag. Are all the reactor components present?

**Comment by Gaelan** [comment]
@ReikaKalseki Here is a youtube link in case Google Drive's player doesn't work: https://youtu.be/NZzjI8ZIHaU

**Comment by ReikaKalseki** [comment]
I see all the parts, the plasma snapping back in, and the neutrons. It looks like lag.
