### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Boxenfreak** [ReikaKalseki/Reika_Mods_Issues#697]
I was wanted to make a private server with Rotarycraft and Reactorcraft but every time i start the server the server crash and i cant figure out why ?

Minecraft Version 1.7.10
DragonAPI V11B
ReactorCraft V11B
RotaryCraft V11B

thanks for helping 

---- Minecraft Crash Report ----
// Don't do that.

Time: 3/26/16 10:35 AM
Description: Exception in server tick loop

Reika.DragonAPI.Exception.IDConflictException: The mods were not installed correctly:
CONFLICT: Potion IDs: am2.buffs.ArsMagicaPotion@c481f1a @ 35 (ArsMagicaPotion & FreezePotion)
Check your IDs and change them if possible.
This is NOT a mod bug. Do not post it or ask for support or you will look lazy or extremely foolish..
    at Reika.DragonAPI.Auxiliary.Trackers.PotionCollisionTracker.onConflict(PotionCollisionTracker.java:77)
    at Reika.DragonAPI.Auxiliary.Trackers.PotionCollisionTracker.addPotionID(PotionCollisionTracker.java:48)
    at Reika.RotaryCraft.RotaryCraft.preload(RotaryCraft.java:297)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 2.6.32-5-amd64
    Java Version: 1.7.0_72, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 622376600 bytes (593 MB) / 1165688832 bytes (1111 MB) up to 1165688832 bytes (1111 MB)
    JVM Flags: 4 total; -XX:+UseConcMarkSweepGC -XX:MaxPermSize=172M -Xmx1150M -Xms1150M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 50 mods loaded, 50 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader](server.jar) 
    UCH Forge{10.13.4.1558} [Minecraft Forge](server.jar) 
    UCH AM2-Preloader{0.0.2} [AMCore](minecraft.jar) 
    UCH appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCH CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) 
    UCH Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCH <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCH <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization](minecraft.jar) 
    UCH AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCH arsmagica2{1.4.0.008} [Ars Magica 2](1.7.10_AM2-1.4.0.008.jar) 
    UCH bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    UCH Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4 %281%29.jar) 
    UCH appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCH Backpack{2.0.1} [Backpack](backpack1.7.x.jar) 
    UCH BattleTowers{1.5.2} [Battle Towers](BattleTowers-1.7.10.jar) 
    UCH CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325 %281%29.jar) 
    UCH BuildCraft|Core{7.1.14} [BuildCraft](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Builders{7.1.14} [BC Builders](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Transport{7.1.14} [BC Transport](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Energy{7.1.14} [BC Energy](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Silicon{7.1.14} [BC Silicon](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Robotics{7.1.14} [BC Robotics](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Factory{7.1.14} [BC Factory](buildcraft-7.1.14.jar) 
    UCH ChickenChunks{1.3.4.16} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
    UCH Mantle{1.7.10-0.3.1.jenkins180} [Mantle](Mantle-mc1.7.10-0.3.1.jar) 
    UCH Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCH ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.3-112 %281%29.jar) 
    UCH ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.2-240.jar) 
    UCH TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct](TConstruct_mc1.7.10_1.6.0d40.1.jar) 
    UCH Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5 %281%29.jar) 
    UCH DragonAPI{1.0} [DragonAPI](DragonAPI 1.7.10 V11b.jar) 
    UCH eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCH FoodPlus{3.0rS} [§bFood Plus](Food-Plus-Mod-1.7.10.jar) 
    UCH GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.445.jar) 
    UCH GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.445.jar) 
    UCH iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCH IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCH ForgeMultipart{1.1.2.331} [Forge Multipart](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCH Mekanism{8.1.9} [Mekanism](Mekanism-1.7.10-8.1.9.264.jar) 
    UCH MekanismGenerators{8.1.9} [MekanismGenerators](MekanismGenerators-1.7.10-8.1.9.264.jar) 
    UCH MekanismTools{8.1.9} [MekanismTools](MekanismTools-1.7.10-8.1.9.264.jar) 
    UCH PortalGun{4.0.0-beta-6} [PortalGun](PortalGun-4.0.0-beta-6.jar) 
    UCE RotaryCraft{1.0} [RotaryCraft](RotaryCraft 1.7.10 V11b %283%29.jar) 
    UCE ReactorCraft{1.0} [ReactorCraft](ReactorCraft 1.7.10 V11b %281%29.jar) 
    UCH rftl{1.7.10} [Rotten Flesh to Leather](Rotten-Flesh-to-Leather-Mod-1.7.10.jar) 
    UCH AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.10.jar) 
    UCH warpbook{2.0.null} [Warp Book](warpbook-1.7.10_2.0.36.jar) 
    UCH McMultipart{1.1.2.331} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCH ForgeMicroblock{1.1.2.331} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.1.2-325
    Mantle Environment: Environment healthy.
    ThermalFoundation: -[1.7.10]1.2.3-112
    ThermalExpansion: -[1.7.10]4.1.2-240
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Aivech** [comment]
It's right there in the crash report. Go into the configs and change the Potion ID for the Rotarycraft Freeze potion to something above 128 and below 256.

**Comment by ReikaKalseki** [comment]
As the log warned, you look lazy or extremely foolish. If you "cant figure out why", I am going to guess the latter.

**Comment by Boxenfreak** [comment]
oh i dont have see it, sry. but one question i dont find the Config from both mods where i can change it so can anyone tell me where i find it ?

**Comment by TomeWyrm** [comment]
Freeze Potion
RotaryCraft

That SHOULD be all the information you need, except for the ID's that are free. Which you'll probably need to guess at until they work.

**Comment by Boxenfreak** [comment]
? sry i m rly stupid in this. i dont know which file i have to edit.

**Comment by TomeWyrm** [comment]
RotaryCraft.cfg

**Comment by Boxenfreak** [comment]
ok i found it thank you very much.

**Comment by DemonExposer** [comment]
> As the log warned, you look lazy or extremely foolish. If you "cant figure out why", I am going to guess the latter.

Why are you such a massive asshole? In your error logs and classnames and all of that. Your shit mods crash my server giving a segfault. A fucking SEGFAULT! In Java! If you're able to achieve that, you're extremely foolish.

Together with that, there is an ID clash when you install your shit mod Rotarycraft after Witchery is already installed. If you install Witchery after Rotarycraft, Witchery simply changes the IDs, which can easily be done with a for loop, something a dumb fuck like you has never heard of I guess, because Rotarycraft does not do it.

Don't be an asshole and make a shitty mod too, you hypocrite. You'll get an asshole response like this.

**Comment by pivinx1** [comment]
Ngl, but it's an closed issue. Maybe open an issue about this.

I'm not trying to ingere into this, but it's just a friendly message.

śr., 23 wrz 2020, 15:48 użytkownik DemonExposer <notifications@github.com>
napisał:

**Comment by DemonExposer** [comment]
@pivinx1 I'm not trying to report a bug or whatever, I just don't accept that this guy writes some mods, and instead of friendly offering help to the users of his mods, he calls them idiots (there is also an error class name something along the lines of "StupidIDException").

I find this unacceptable to do if you're actually releasing your mods into the public.

**Comment by pivinx1** [comment]
Alright, good to knowm

śr., 23 wrz 2020, 20:54 użytkownik DemonExposer <notifications@github.com>
napisał:
