### ISSUE TITLE
Dragon API breaks tardismod

### ISSUE THREAD

**Issue by FoxPotato** [ReikaKalseki/Reika_Mods_Issues#698]
Over at the tardismodissues github there have been a lot of reports of tardismod not working when dragon API is installed.
From what we can see it's because for some reason dragon API seems to break the @Optional annotation for buildcraft and ae. Causing the game to error because it starts looking for mods that aren't there. 
Here are a few of the issues;
DarkholmeTenk/TardisModIssues#467 DarkholmeTenk/TardisModIssues#483 DarkholmeTenk/TardisModIssues#480 DarkholmeTenk/TardisModIssues#318

**Comment by ReikaKalseki** [comment]
This is a new one, but as it is very similar to the "classes not loadable unless in the DragonAPI jar", it is probably the same cause. Something is wrong with the FML classloading, and there is nothing I can do to fix it. My recommendation is to add the relevant APIs to DragonAPI.
