### ISSUE TITLE
[Question] Wrench Issue: Possible Workaround?

### ISSUE THREAD

**Issue by accessdenied0** [ReikaKalseki/Reika_Mods_Issues#699]
Hey @ReikaKalseki,

I'm aware [this issue](https://github.com/nhave/nhwrench/issues/1) isn't your problem and you don't have to worry about, but I reported this issue for a while ago  (I guess the nhave is very busy) and I would love to use Electricraft again... 

My question is now if you can fix this problem on your side until the mod-author is able to do it.

thank you for your time,

access_denied

**Comment by ReikaKalseki** [comment]
There is no reason adding ElC could make another mod fail to load a class file. DragonAPI can trigger some of that due to API classloading errors, but removing ElC does not fix that. Try adding the BC IWrench interface to the DragonAPI jar anyways. And no, there is nothing I can do on my end.
