### ISSUE TITLE
Get rid of crappy people

### ISSUE THREAD

**Issue by strawberryshortbread** [ReikaKalseki/Reika_Mods_Issues#7]
I can't submit a bug repourt without being hounded and derided, and noone is willing to accept responsibility for their own mistakes. Reika, get better reviewers, god bless!

**Comment by coolsquid** [comment]
First of all, we have no responsibility whatsoever. The mods are provided as is, with no warranties. Secondly, if you don't provide the required information, we can't help you.

**Comment by TomeWyrm** [comment]
You were in no way harassed. We asked for some of the basic, REQUIRED information

"Check your versions. Using incompatible versions and complaining about crashes is grounds for ridicule."
