### ISSUE TITLE
[Rotarycraft] Lag with the bait box.

### ISSUE THREAD

**Issue by Sima214** [ReikaKalseki/Reika_Mods_Issues#70]
Tested only with Rotarycraft ,NEI and their cores/libs.
I have a bait box with a block of grass being powered with an AC engine's worth of power.
When activated my fps drops to something like 20fps(from ~100) and a server tick takes about 30 ms.
[Here's a screenshot of the setup I am using,](https://drive.google.com/file/d/0B02EtgYv4Ob0ZTJUcWhfbHdyc1U/view?usp=sharing)
[and a VisualVM cpu sampler snapshot.](https://drive.google.com/file/d/0B02EtgYv4Ob0WVl2V28yUjRlYU0/view?usp=sharing)

**Comment by 1Matthias** [comment]
Odd. Version?

**Comment by Sima214** [comment]
6f for DragonApi and RotaryCraft and forge 1291

**Comment by Sima214** [comment]
Also as I had only tested with an enderman farm design in the End originaly, I did a few more tests(I've also added Opis)
What I gathered:
Opis reports a higher ping(what?).
Visual VM sampling shows some minecraft methods related to pathfinding and hashmaps to take more cpu time when the bait box is active.
The amount of lag seems proportional of the range of the bait box and non-existent when bait box is in "repel" mode.
I've also tested in the overworld with some other types of mobs and animals and the behaviour in terms of lag was the same.

**Comment by madolinn** [comment]
> Visual VM sampling shows some minecraft methods related to pathfinding and hashmaps to take more cpu time when the bait box is active.

Makes sense. Every tick the Endermen probably revert to normal behavior and every tick the bait box overwrites it back with the new path which is recalculated. Multiply that by every Enderman there and you've got a soup server.

**Comment by ReikaKalseki** [comment]
I am not surprised to hear this, but I am not sure I can fix it...

**Comment by ReikaKalseki** [comment]
Yes, I see no way to fix this. Hopefully the AI changes (multithreading) in 1.8 fix it.
