### ISSUE TITLE
v12 ReactorCraft and conflict

### ISSUE THREAD

**Issue by SvEgiiVEteR** [ReikaKalseki/Reika_Mods_Issues#700]
1)On the server side. the client is not checked.
http://paste.ee/p/KBNip
but I do not need to put ChromatiCraft
I have of him the world is generating a long time.

2) PlayerAPI-1.7.10-1.4.jar
If I install this mod
then the server will not start
http://paste.ee/p/qZxGV
full log
http://paste.ee/p/mkgOb

**Comment by amesgen** [comment]
I have the same error (1)
http://pastebin.com/Ae5GZ26p

**Comment by ghost** [comment]
1)If you have the DragonAPI from 12 hours ago, it's a good chance it might be causing the crash. Once Curse approves the working version of it try again and if the crash consists then it might be a bug.

**Comment by ReikaKalseki** [comment]
The second is an ASM conflict. Who makes PlayerAPI?

**Comment by ghost** [comment]
A person named Divisor.

**Comment by Aivech** [comment]
Is that the one that provides access to the player model for mods like AnimatedPlayer and More Player Models?

**Comment by amesgen** [comment]
The error occured with the recent (now 17h (DragonAPI) and 19h (ReactorCraft) ago) versions from Curse.

**Comment by ReikaKalseki** [comment]
1) is fixed. 2) Needs input from @Divisor.

**Comment by amesgen** [comment]
I can confirm 1)

**Comment by ReikaKalseki** [comment]
Somewhat amusingly, it appears that newer FastCraft versions (we are using 1.21 without issue) are also suffering a compatibility issue from the same ASM transformer...and FastCraft is made by @Player. So now I need to contact both a dev named player and the dev of a mod named PlayerAPI.

...Or have people been saying PlayerAPI when they mean FastCraft?

**Comment by Aivech** [comment]
PlayerAPI: 

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277996-player-api

**Comment by ReikaKalseki** [comment]
Are they active on MCF?

**Comment by ghost** [comment]
Last active March 5th soooo ehhh

**Comment by ReikaKalseki** [comment]
In other words, no.

**Comment by crysthala** [comment]
Also getting the errors mentioned in 2), so I created a separate install profile to see if DragonAPI and PlayerAPI are directly incompatible, or if another mod is involved. Forge 10.13.4.1558, DragonAPI V12a, PlayerAPI 1.4, nothing but DragonAPI and PlayerAPI in the "mods" folder. No go. Here, have a log: [fml-client-latest gist](https://gist.github.com/crysthala/93e2bb13fa973c50054f65ca836b4454)

Divisor doesn't normally reply to users, given the number of demands to "make X compatible with Smartmoving!!!", but I wonder whether you'd have more luck as a dev. There is an archive with .java files in the download, if those would be helpful at all.

**Comment by ReikaKalseki** [comment]
It is my new KeepInventoryEvent. Does PlayerAPI change the death behavior at all? It is failing to find the "keepInventory" gamerule lookup.

**Comment by crysthala** [comment]
Not as far as I know. I am not a modder, just a Smart Moving user who's very, very thorough about reading forum posts. :p

Divisor does have some instructions on that post for decompiling the code / adding compatibility, under the FAQ and the "Developing" heading, respectively. There are mods with compatibility that aren't _dependent_ on it, but I've no idea how that works.

**Comment by ReikaKalseki** [comment]
I have PMed him. We shall see if I get a useful response.

**Comment by Keyarose** [comment]
I thought this might be of some use; SpongePowered is having the same issue with PlayerAPI.
https://github.com/SpongePowered/SpongeForge/issues/570

**Comment by ReikaKalseki** [comment]
I saw that by digging through his ASM, and will try directing my ASM at his methods instead.

**Comment by SvEgiiVEteR** [comment]
http://paste.ee/p/ywUzz
V12c:
    DragonAPI: Maybe fixed PlayerAPI incompatibility
    ChromatiCraft: Possibly fixed PlayerAPI incompatibility
problem still exists.

**Comment by ReikaKalseki** [comment]
This one is a different ASM block; I will try fixing it later.

But hence "maybe". I need input from him. If my solution does not work, and he does not provide input, this will not be fixed, as I am not breaking DragonAPI code - which is already used by CC and RC - for it.

**Comment by crysthala** [comment]
Tried 12C on my "crash test profile" and got a pretty much identical log to SvEgiiVEteR. [Gist](https://gist.github.com/crysthala/69adb03871f30fcac7aeeccc729a22ef).

I really wish there were a decent alternative to Smart Moving sometimes. It's really useful, but there are _so many_ compatibility issues. Hopefully Divisor will get back to you.

**Comment by Aivech** [comment]
What does Smart Moving _do_, other than animate your character in a more logical manner?

**Comment by crysthala** [comment]
I wouldn't care if it were just nice animations, but it makes the game handle much more naturally. You can climb the sides of solid blocks, crawl through 1-block-high spaces, dolphin dive (good for hopping fences), and swim with reasonable competency. There's some more parkour-ish stuff, too, and people build obstacle course maps for it. I just like being able to get around more easily in general.

**Comment by FnordMan** [comment]
Tried 12d, still crashes with PlayerAPI
[fml-client-latest.log.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/200930/fml-client-latest.log.txt)

**Comment by ReikaKalseki** [comment]
There was a bug in my compatibility code.

**Comment by TomeWyrm** [comment]
Is there going to be a v12e, or is this fix going to have to wait for v13?

**Comment by ReikaKalseki** [comment]
This alone would not warrant a v12e, but two other combined bugs in CC might.

**Comment by Jorhlok** [comment]
Heyo, Josh here. I've been watching this issue the past couple days. Just downloaded DragonAPI v12e and Rotarycraft v12e and they work with fastcraft 1.22 and PlayerAPI 1.4 (among other things) whereas v12d did not. Was running v10d just before that. Thanks for all you do!

**Comment by ReikaKalseki** [comment]
So it worked? _Finally._
