### ISSUE TITLE
[Issue] (v12a) ReactorCraft crashes without Cromaticraft

### ISSUE THREAD

**Issue by accessdenied0** [ReikaKalseki/Reika_Mods_Issues#701]
The game crashed on Phase 5 by loading up:
[Crash Report](http://pastebin.com/KXX72M0V)
[Console](http://pastebin.com/K0HmG3Ve)

Thank you for your help,

access_denied

**Comment by amesgen** [comment]
#700

**Comment by accessdenied0** [comment]
It seem similar, but I wasn't sure we describe the same Issue, firstly because I can't even start my Client. Secondly the error description is really bad, I just could not tell if this is really the same here... I do not use a Server.

tl;dr:

Client doesn't work at all, is it the same? - Closed - I did my job.
