### ISSUE TITLE
Chromaticraft 12b renderer issue

### ISSUE THREAD

**Issue by 1skandar** [ReikaKalseki/Reika_Mods_Issues#702]
You can file this as low priority, just weird. When drawing from a pylon for the first time for a particular color my screen does that flicker/reload chunks thing just like I had hit the shift-F3-a shortcut. It only does it on initial draw, subsequent draws for that color are fine.

No idea why, and it is completely non-harmful in and of itself, but I figure it is something you'd like to know just in cas it is a symptom of something deeper and potentially more harmful.

**Comment by ReikaKalseki** [comment]
That is not a bug; gaining progress triggers a rerender as things become visible, and I changed the DragonAPI rerender to use the vanilla F3+A method. That said, because of how visually jarring it is, I made CC use the old version in v12b.
