### ISSUE TITLE
ChromatiCraft sound category enum crash still persists (v12b)

### ISSUE THREAD

**Issue by DracoScythem** [ReikaKalseki/Reika_Mods_Issues#703]
(Original issue: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/691 )
The crash happens in the exact same way as before (also has an identical crashlog),
and for me it seems like the HashMap fix isn't triggered (though it should be, from looking at your cc gits code)
(Could be easily veryfied by forcing its' activation)
If that assumation is correct propably a config option to force the use of the HashMap would be the easiest fix.

Up-to-date crash-report:
https://gist.github.com/Leguan12/38111c0fa5210a81aeb8

Up-to-date fml-log (though I don't think I'll help) : 
https://gist.github.com/Leguan12/578da16e46e889e2f658/raw/6e557527a113c3224c63b7dab642e9855ea908d7/2_fml-client-latest.log

**Comment by ReikaKalseki** [comment]
Do not open separate issues, but yes, that is my plan.

**Comment by ReikaKalseki** [comment]
Done.

**Comment by DracoScythem** [comment]
Yes config option works perfectly, thanks Reika ^^
