### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by Pelycosaurus** [ReikaKalseki/Reika_Mods_Issues#705]
I was using the mod:
GeoStrata

Crash report:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2016.03.29. 20:40
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at cpw.mods.fml.common.eventhandler.EventBus.unregister(EventBus.java:124)
    at Reika.DragonAPI.Base.DragonAPIMod.basicSetup(DragonAPIMod.java:141)
    at Reika.GeoStrata.GeoStrata.preload(GeoStrata.java:110)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_80, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1193469464 bytes (1138 MB) / 2293235712 bytes (2187 MB) up to 4772069376 bytes (4551 MB)
    JVM Flags: 3 total; -Xmx5G -Xms1G -XX:MaxPermSize=128m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 104 mods loaded, 104 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader](TekkitLegends.jar) 
    UCH Forge{10.13.4.1492} [Minecraft Forge](TekkitLegends.jar) 
    UCH AM2-Preloader{0.0.3} [AMCore](minecraft.jar) 
    UCH CodeChickenCore{1.0.6.41} [CodeChicken Core](minecraft.jar) 
    UCH OldModelLoader{1.0} [OldModelLoader](minecraft.jar) 
    UCH NotEnoughItems{1.0.4.102} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.102-universal.jar) 
    UCH ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCH <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCH <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization](minecraft.jar) 
    UCH mcdiscord{2.0.0} [MC Discord](minecraft.jar) 
    UCH AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCH arsmagica2{1.4.0.009} [Ars Magica 2](1.7.10_AM2-1.4.0.009.jar) 
    UCH bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    UCH Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar) 
    UCH CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCH BuildCraft|Core{7.1.14} [BuildCraft](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Transport{7.1.14} [BC Transport](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Silicon{7.1.14} [BC Silicon](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Factory{7.1.14} [BC Factory](buildcraft-7.1.14.jar) 
    UCH ComputerCraft{1.74} [ComputerCraft](ComputerCraftPlusComputerCraftEdu1.74.jar) 
    UCH IC2{2.2.791-experimental} [IndustrialCraft 2](Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
    UCH Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCH Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) 
    UCH Forestry{3.6.11.2} [Forestry for Minecraft](forestry_1.7.10-3.6.11.2.jar) 
    UCH Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCH Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCH ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.3-112.jar) 
    UCH ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.2-240.jar) 
    UCH LogisticsPipes{0.9.3.70} [Logistics Pipes](logisticspipes-0.9.3.70.jar) 
    UCH additionalpipes{4.7.0} [Additional Pipes](additionalpipes-4.7.0.jar) 
    UCH ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) 
    UCH asielib{0.4.4} [asielib](AsieLib-1.7.10-0.4.4.jar) 
    UCH Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) 
    UCH bdlib{1.9.3.107} [BD Lib](bdlib-1.9.3.107-mc1.7.10.jar) 
    UCH chocolateQuest{1.0} [Chocolate Quest](Better-Dungeons-Mod-1.7.10.jar) 
    UCH BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
    UCH qmunitylib{1.0} [QmunityLib](QmunityLib-1.7.10-0.1.114-universal.jar) 
    UCH bluepower{0.2.962} [Blue Power](BluePower-1.7.10-0.2.962-universal.jar) 
    UCH Botania{r1.8-249} [Botania](Botania r1.8-249.jar) 
    UCH BuildCraft|Builders{7.1.14} [BC Builders](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Energy{7.1.14} [BC Energy](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Robotics{7.1.14} [BC Robotics](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Compat{7.1.3} [BuildCraft Compat](buildcraft-compat-7.1.3.jar) 
    UCH CarpentersBlocks{3.3.7} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UCH ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCH ComputerCraftEdu{1.74} [ComputerCraftEdu](ComputerCraftPlusComputerCraftEdu1.74.jar) 
    UCH Railcraft{9.7.0.0} [Railcraft](Railcraft_1.7.10-9.7.0.0.jar) 
    UCH Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCH computronics{1.5.7} [Computronics](Computronics-1.7.10-1.5.7.jar) 
    UCH numina{0.4.0.131} [Numina](Numina-0.4.0.131.jar) 
    UCH powersuits{0.11.0.293} [MachineMuse's Modular Powersuits](ModularPowersuits-0.11.0.293.jar) 
    UCH Mystcraft{0.12.3.01} [Mystcraft](mystcraft-1.7.10-0.12.3.01.jar) 
    UCH DragonAPI{1.0} [DragonAPI](DragonAPI 1.7.10 V12b.jar) 
    UCH MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.3.1.zip) 
    UCH DummyCore{1.13} [DummyCore](DummyCore1.13.jar) 
    UCH EnderStorage{1.4.7.37} [EnderStorage](EnderStorage-1.7.10-1.4.7.37-universal.jar) 
    UCH eng_toolbox{1.2.3.0} [Engineer's Toolbox](EngineersToolbox-1.2.3.0-BETA.jar) 
    UCH essentialcraft{4.6.1710.63} [EssentialCraftIII](EssentialCraftv4.6.1710.63.jar) 
    UCH ForgeMultipart{1.2.0.344} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
    UCH ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCH McMultipart{1.2.0.344} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
    UCH gendustry{1.6.1.126} [GenDustry](gendustry-1.6.1.126-mc1.7.10.jar) 
    UCE GeoStrata{1.0} [GeoStrata](GeoStrata 1.7.10 V12a.jar) 
    UCH ImmibisCore{59.1.2} [Immibis Core](immibis-core-59.1.2.jar) 
    UCH ImmibisPeripherals{59.0.2} [Immibis's Peripherals](immibis-peripherals-59.0.2.jar) 
    UCH inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks](InventoryTweaks-1.59-dev-156.jar) 
    UCH IronChest{6.0.60.741} [Iron Chest](Ironchest-1.7.10-6.0.60.741-universal.jar) 
    UCH itlt{0.0.8} [It's the little things](itlt-1.7.10-0.0.8.jar) 
    UCH JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCH lmmx{1.0} [lmmx](littleMaidMobX-1.7.x_0.1.0.jar) 
    UCH MMMLibX{1.7.x-srg-1} [MMMLibX](littleMaidMobX-1.7.x_0.1.0.jar) 
    UCH zabuton{1.0} [zabuton](littleMaidMobX-1.7.x_0.1.0.jar) 
    UCH MapWriter{2.1.8} [MapWriter](MapWriter-1.7.10-2.1.9.jar) 
    UCH MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10.jar) 
    UCH modtweaker2{0.9.4} [Mod Tweaker 2](ModTweaker2-0.9.4.jar) 
    UCH Morpheus{1.7.10-1.6.21} [Morpheus](Morpheus-1.7.10-1.6.21.jar) 
    UCH NEIAddons{1.12.11.36} [NEI Addons](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH neiintegration{1.0.12} [NEI Integration](NEIIntegration-MC1.7.10-1.0.12.jar) 
    UCH NetherOres{1.7.10R2.3.0} [Nether Ores](NetherOres-[1.7.10]2.3.0-12.jar) 
    UCH OCS{1.7.5} [OpenCCSensors](openccsensors-1.7.5.jar) 
    UCH planetguyLib{1.9} [planetguyLib](PlanetguyLib-1.9.1.jar) 
    UCH PowerConverters3{1.7.10-2.11} [Power Converters 3](PowerConverters-1.7.10-2.11.jar) 
    UCH ProjectE{1.7.10-PE1.9.3} [ProjectE](ProjectE-1.7.10-PE1.9.3h.jar) 
    UCH quiverchevsky{b100} [QuiverBow](QuiverBow_1.7.10_b100.zip) 
    UCH RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
    UCH JAKJ_RedstoneInMotion{2.8.8} [Remain In Motion](RemainInMotion-2.8.8.jar) 
    UCH SolarFlux{1.7.10-0.8b} [Solar Flux](SolarFlux-1.7.10-0.8b.jar) 
    UCH spacore{01.05.12} [SpACore](SpACore-1.7.10-01.05.12.jar) 
    UCH thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7a.jar) 
    UCH ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCH Tubestuff{59.0.4} [Tubestuff](tubestuff-59.0.4.jar) 
    UCH WailaHarvestability{1.1.2} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.2.jar) 
    UCH witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    UCH worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
    UCH zettaindustries{1.1} [Zetta Industries](zettaindustries-1.1-105.jar) 
    UCH aobd{2.8.4} [Another One Bites The Dust](AOBD-2.8.4.jar) 
    UCH ForgeMicroblock{1.2.0.344} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
    CoFHCore: -[1.7.10]3.1.2-325
    Mantle Environment: Environment healthy.
    ThermalFoundation: -[1.7.10]1.2.3-112
    ThermalExpansion: -[1.7.10]4.1.2-240
    NetherOres: -[1.7.10]2.3.0-12
    RedstoneArsenal: -[1.7.10]1.1.1-89
    SpACore ASM Transformers: 
        GLStateManager: false
        GLStateManager debug output: false
        Debug screen replacer: true
    List of loaded APIs: 
        \* apAPI (2) from additionalpipes-4.7.0.jar
        \* appliedenergistics2|API (rv2) from ThaumicTinkerer-2.5-1.7.10-164.jar
        \* asielibAPI (1.1) from AsieLib-1.7.10-0.4.4.jar
        \* asielibAPI|chat (1.0) from AsieLib-1.7.10-0.4.4.jar
        \* asielibAPI|tile (1.0) from AsieLib-1.7.10-0.4.4.jar
        \* asielibAPI|tool (1.1) from AsieLib-1.7.10-0.4.4.jar
        \* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
        \* bluepowerAPI (1.0) from BluePower-1.7.10-0.2.962-universal.jar
        \* BotaniaAPI (76) from Botania r1.8-249.jar
        \* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|boards (1.0) from EngineersToolbox-1.2.3.0-BETA.jar
        \* BuildCraftAPI|core (1.0) from extrautilities-1.2.12.jar
        \* BuildCraftAPI|crops (1.1) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|events (2.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|facades (1.1) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|filler (4.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|gates (4.1) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|items (1.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* BuildCraftAPI|library (2.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|lists (1.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|power (1.3) from EngineersToolbox-1.2.3.0-BETA.jar
        \* BuildCraftAPI|recipes (2.1) from EngineersToolbox-1.2.3.0-BETA.jar
        \* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|statements (1.1) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|tablet (1.0) from EngineersToolbox-1.2.3.0-BETA.jar
        \* BuildCraftAPI|tiles (1.2) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|tools (1.0) from extrautilities-1.2.12.jar
        \* BuildCraftAPI|transport (4.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
        \* CoFHAPI (1.7.10R1.0.1) from Railcraft_1.7.10-9.7.0.0.jar
        \* CoFHAPI|block (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
        \* CoFHAPI|core (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
        \* CoFHAPI|energy (1.7.10R1.0.2) from DragonAPI 1.7.10 V12b.jar
        \* CoFHAPI|fluid (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHAPI|inventory (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHAPI|item (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
        \* CoFHAPI|modhelpers (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
        \* CoFHAPI|tileentity (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHAPI|transport (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHAPI|world (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|audio (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|gui (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|gui|container (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|gui|element (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|gui|element|listbox (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|gui|slot (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|inventory (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|render (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|render|particle (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|util (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|util|helpers (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|util|position (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|world (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|world|feature (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* ComputerCraft|API (1.74) from EngineersToolbox-1.2.3.0-BETA.jar
        \* ComputerCraft|API|FileSystem (1.74) from EngineersToolbox-1.2.3.0-BETA.jar
        \* ComputerCraft|API|Lua (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
        \* ComputerCraft|API|Media (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
        \* ComputerCraft|API|Peripheral (1.74) from EngineersToolbox-1.2.3.0-BETA.jar
        \* ComputerCraft|API|Permissions (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
        \* ComputerCraft|API|Redstone (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
        \* ComputerCraft|API|Turtle (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
        \* computronicsAPI (1.3) from Computronics-1.7.10-1.5.7.jar
        \* computronicsAPI|chat (1.3) from Computronics-1.7.10-1.5.7.jar
        \* computronicsAPI|multiperipheral (1.1) from Computronics-1.7.10-1.5.7.jar
        \* computronicsAPI|tape (1.0) from Computronics-1.7.10-1.5.7.jar
        \* ForestryAPI|apiculture (3.5.0) from forestry_1.7.10-3.6.11.2.jar
        \* ForestryAPI|arboriculture (2.3.0) from forestry_1.7.10-3.6.11.2.jar
        \* ForestryAPI|circuits (2.0.0) from forestry_1.7.10-3.6.11.2.jar
        \* ForestryAPI|core (3.2.0) from forestry_1.7.10-3.6.11.2.jar
        \* ForestryAPI|farming (1.1.0) from forestry_1.7.10-3.6.11.2.jar
        \* ForestryAPI|food (1.1.0) from forestry_1.7.10-3.6.11.2.jar
        \* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-3.6.11.2.jar
        \* ForestryAPI|genetics (3.3.0) from forestry_1.7.10-3.6.11.2.jar
        \* ForestryAPI|hives (4.1.0) from forestry_1.7.10-3.6.11.2.jar
        \* ForestryAPI|lepidopterology (1.1) from forestry_1.7.10-3.6.11.2.jar
        \* ForestryAPI|mail (3.0.0) from forestry_1.7.10-3.6.11.2.jar
        \* ForestryAPI|recipes (3.1.0) from forestry_1.7.10-3.6.11.2.jar
        \* ForestryAPI|storage (3.0.0) from forestry_1.7.10-3.6.11.2.jar
        \* ForestryAPI|world (1.1.0) from forestry_1.7.10-3.6.11.2.jar
        \* gendustryAPI (2.2.0) from gendustry-1.6.1.126-mc1.7.10.jar
        \* IC2API (1.0) from Industrial-Craft-2-Mod-Experimental-1.7.10.jar
        \* minechemAPI (1.7.10R1) from DragonAPI 1.7.10 V12b.jar
        \* Mystcraft|API (0.1) from mystcraft-1.7.10-0.12.3.01.jar
        \* ProjectEAPI (7) from ProjectE-1.7.10-PE1.9.3h.jar
        \* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|carts (1.3.1) from EngineersToolbox-1.2.3.0-BETA.jar
        \* RailcraftAPI|core (1.4.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|electricity (1.6.0) from EngineersToolbox-1.2.3.0-BETA.jar
        \* RailcraftAPI|events (1.0.0) from EngineersToolbox-1.2.3.0-BETA.jar
        \* RailcraftAPI|fuel (1.0.0) from EngineersToolbox-1.2.3.0-BETA.jar
        \* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|locomotive (1.0.1) from EngineersToolbox-1.2.3.0-BETA.jar
        \* RailcraftAPI|signals (1.3.4) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|tracks (2.0.0) from EngineersToolbox-1.2.3.0-BETA.jar
        \* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* VoltzEngineAPI (0.5.0) from DragonAPI 1.7.10 V12b.jar
        \* VoltzEngineAPI|crafting-items (0.5.0) from DragonAPI 1.7.10 V12b.jar
        \* VoltzEngineAPI|energy (0.5.0) from DragonAPI 1.7.10 V12b.jar
        \* VoltzEngineAPI|energy-items (0.5.0) from DragonAPI 1.7.10 V12b.jar
        \* VoltzEngineAPI|event (0.5.0) from DragonAPI 1.7.10 V12b.jar
        \* VoltzEngineAPI|explosive-items (0.5.0) from DragonAPI 1.7.10 V12b.jar
        \* VoltzEngineAPI|explosives (0.5.0) from DragonAPI 1.7.10 V12b.jar
        \* VoltzEngineAPI|items (0.5.0) from DragonAPI 1.7.10 V12b.jar
        \* VoltzEngineAPI|recipe (0.5.0) from DragonAPI 1.7.10 V12b.jar
        \* VoltzEngineAPI|tile (0.5.0) from DragonAPI 1.7.10 V12b.jar
        \* VoltzEngineAPI|tools (0.5.0) from DragonAPI 1.7.10 V12b.jar
        \* VoltzEngineAPI|weapons (0.5.0) from DragonAPI 1.7.10 V12b.jar
        \* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by ReikaKalseki** [comment]
This does not happen for me. Can you reproduce it with only it and DragonAPI?

**Comment by Pelycosaurus** [comment]
Okay ill try.

**Comment by Pelycosaurus** [comment]
There are no errors that i found.

**Comment by Pelycosaurus** [comment]
The crash appeared at adding GeoStrata and DragonAPI to Tekkit Legends. It doesn't work with the modified version that i made or the original.

**Comment by Pelycosaurus** [comment]
And it has problems with the littleMaidMob too, that mod started on Direwolf 1.7.10 but not Tekkit Legends 1.7.10. I should find that mod.

**Comment by ReikaKalseki** [comment]
Forge 1492. Update Forge.
