### ISSUE TITLE
The V12b is supported KCauldron and Thermos?

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#706]
I tried it and found that the server no longer crashes, so V12b has supported KCauldron and Thermos?
I want to express is that future versions will no longer cause a crash with KCauldron and Thermos, right? Otherwise server died again. :)
Please give me an answer let me decide whether to continue opening server, rather than wasting my time and effort. Thank you very much! Always support you!
And I have a other question: You are not going to upgrade to 1.8 or 1.9? It has always 1.7.10?

**Comment by ghost** [comment]
To the other question: Reika is most likely going to skip 1.8 and possibly do 1.9 if a majority of the others mods move to 1.9 (iirc) like CoFH mods, enderIO, etc

**Comment by TomeWyrm** [comment]
To the first question. (Please excuse the caps. I'm sick of bukkit being mentioned in any capacity at this point)

NO, THERE WILL BE NO GUARANTEES IN ANY WAY ABOUT COMPATIBILITY WITH A PLATFORM THAT IS NOT FORGE. THIS IS NOT REIKA'S RESPONSIBILITY IN ANY WAY. TALK TO THE <INSERT ILLEGAL PLATFORM HERE> DEVELOPERS FOR ANY FUTURE COMPATIBILITY REQUESTS.

Actually, better option. QUIT USING BUKKIT, or any of its derivatives!

**Comment by ghost** [comment]
@TomeWyrm Yes, you are right, but there are some big problems:
If quit using Bukkit, choose what server software and it must have PLUGINS function?
Is it really only use mojang's server software with forge?
You know, if there is no plugins, you can not protect the server, to achieve more functionality, such as login(like AuthMe), and Plots(like PlotSquared) and some plugins like WordGuard and more and more.
And if there is no plug-in, how anti-cheat? Disable some items(**You know some of the items are dangerous, can destroy the server and players' efforts**)?
There are many problems simply can not be expressed in words. And Reika do not upgrade to 1.8 or 1.9, only support 1.7.10. There are many excellent Mod such as IC2, TF, but they only support 1.7.10, either. (1.8 and 1.9 has Sponge, it's great but it only support 1.8+).
And if using 1.7.10, you can only choose KCauldron or Thermos...............
So, would you please tell me how should I do? Give up all this?
It is obvious that all this is a contradiction.

**Comment by ljfa-ag** [comment]
That is one of the reasons why Sponge was made in the first place. You see how many compatibility problems Cauldron and the like create by modifying large parts of vanilla code. Under this premise unfortunately you _have to expect_ some mods to break.

**Comment by Aivech** [comment]
FTBUtils has a chunk claiming and protection feature. 

Minetweaker and modtweaker can be used to remove the recipies for most items, effectively disabling them.

I believe ForgeEssentials has auth features.

**Comment by ghost** [comment]
Anyway, I believe Reika will make the right choice. Support these two server software is not difficult, in short, in any case, I will support Reika.

**Comment by ReikaKalseki** [comment]
> Support these two server software is not difficult

Yes it is, especially when I am alternately shunned and given nonfunctional fixes, then blamed when the fixes fail to work.
