### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 9 + EnumMap - Issue since trying to update from v10d, Chromaticraft.

### ISSUE THREAD

**Issue by xTwi** [ReikaKalseki/Reika_Mods_Issues#707]
http://pastebin.com/4Jy3wPAb I'm usually good at diagnosing and fixing small stuff, but this EnumMap error has kept me from being able to enjoy any version above v10d. Can you help, please?
Ever since v11a was released, I've tried to update once every mod update and on v12b it still gives the same error.

Chromaticraft trying to add a sound new to v11a and beyond. And I have no idea how to go about fixing this. So I've come to ask for your help in diagnosing this.

**Comment by DracoScythem** [comment]
#703 , #691 , #640  , [HEE170](https://github.com/chylex/Hardcore-Ender-Expansion/issues/170)

**Comment by xTwi** [comment]
Okay, I deleted options.txt and the game is not crashing with that error anymore but now I have a "MAJOR" problem according to the crash log. http://pastebin.com/zG8AdkCX Info fragment about bees.

I don't know if you're still awake Reika but.. "Please contact Reika IMMEDIATELY."
