### ISSUE TITLE
V12 chromaticraft lumen repeater crash

### ISSUE THREAD

**Issue by rejectpretzel** [ReikaKalseki/Reika_Mods_Issues#709]
I created the lumen repeater and went to place it down close to a nearby pylon only to have it (presumably) exploded, placed fire around me, crashed the server and the connected clients and after restarting the server kicks anyone who joins. The client did not have a crash report but I attached the servers crash report.

[crash-2016-03-30_18.31.10-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/196912/crash-2016-03-30_18.31.10-server.txt)

**Comment by rejectpretzel** [comment]
After some testing it only crashes if run on a server, placing the repeater on a single player world works fine. After placing the repeater on the server fire gets placed on top of the repeater then the server crashes.

**Comment by EdwinMindcraft** [comment]
Maybe a missing @SideOnly ?

**Comment by ReikaKalseki** [comment]
Indeed it is. v12d....

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by ReikaKalseki** [comment]
Fixed.
