### ISSUE TITLE
Chromatic Enchanter failing to work

### ISSUE THREAD

**Issue by KeepYourTemper** [ReikaKalseki/Reika_Mods_Issues#711]
I'm currently playing on v12c of Chromaticraft and DragonAPI. I was playing on v12b earlier today and encountering the same issue.

When attempting to use the Chromatic Enchanter, it seems to just indefinitely attempt to apply the enchantments, never succeeding to do so. The console is getting spammed with null pointer exceptions being thrown by it each time it tries to enchant. Below is the looping log from the console:

http://pastebin.com/eV7R8wZA

In addition, here is the Chromatic Enchanter itself. 

http://pasteboard.co/2Fxow0iA.png

All I've done is place the Enchanter, fill it with 6 buckets of Chroma, selected Protection 1 and put the boots in. The purple bar fills repeatedly but never actually enchants. If there's something I'm missing that's causing this, I'm sorry for wasting your time.

**Comment by ReikaKalseki** [comment]
I have noticed it needs to cycle a couple times but I thought that was lag, and it worked well enough. Are you sure it never works?

**Comment by KeepYourTemper** [comment]
I left it run for about 30 minutes trying to apply that Protection I to a pair of golden boots. In addition, I forgot to mention in my original report, whenever I attempt to enchant a book it nearly instantly completes it but just hands me a blank "Enchanted Book".

**Comment by ReikaKalseki** [comment]
That I noticed, though the item seemed to work.

**Comment by KeepYourTemper** [comment]
Tonight I'll try to rule out mod incompatibility on my end by trying just Chromaticraft (and Dragon API) installed. 

Are there any other prerequisites to the Enchanter? Does it need to be placed somewhere specific or have any blocks around it like a regular enchanting table? Trying to find some user error here, because I wouldn't be shocked to hear I screwed something up.

**Comment by ReikaKalseki** [comment]
No, it should work so long as it has the required ingredients.

**Comment by KeepYourTemper** [comment]
Alright, so I'm testing again right now. The problem is weirder than I thought. From my testing, it can't apply enchantments to unenchanted items specifically. I was able to add an enchantment to armor, pickaxes, and bows that were already enchanted, but it stills out indefinitely if the item isn't already enchanted.

As part of my testing, I put a Stone Sword in and tried to add Sharpness I. It cycled forever. I then enchanted it in a regular table and got Unbreaking I, then put it back in the Chromatic Enchanter. In one cycle it finished and applied Sharpness I.

**Comment by ReikaKalseki** [comment]
WTF...?

That also explains why I never had any issues.

**Comment by nmarshall23** [comment]
It happens for me only with items that have no enchants and have a enchantability of 18 or more. I can enchant leather armor and HSLA Steel tools, that didn't have enchants.

But put enchants on gold items or any modded tool with enchantability of 18 or more.

Here is the error from when I try to enchant an item. It's thrown as long as the item is in the Chromatic Enchanter.
http://pastebin.com/NvTr3S8y

**Comment by EdwinMindcraft** [comment]
Maybe adding a null check in remove enchantments after the getEnchantementTag() will solve it ?

**Comment by ReikaKalseki** [comment]
Null should never be present in the enchantment list.

**Comment by EdwinMindcraft** [comment]
Yes but the tag itself might be.

**Comment by Carolly** [comment]
Can confirm I'm having the same experience.

Unenchanted diamond pick just cycles. Pre-enchanted works as intended immediately.

**Comment by ReikaKalseki** [comment]
I have added a null-check, and it seems to work now.

**Comment by TomeWyrm** [comment]
This one definitely deserved the "@&#%?!" tag.

**Comment by RaineAndrews** [comment]
I'm having this issue in v13, was this fixed or not?

**Comment by ReikaKalseki** [comment]
I thought it was.

**Comment by RaineAndrews** [comment]
I'm experiencing similar issues in the revolution 2 mod pack's must recent version.  Replicated this behavior across 2 saves.

**Comment by RaineAndrews** [comment]
I can't duplicate the strange behavior now that I spoke up about it.  Maybe I didn't use the reset button and tried to put enchantments on things where they didn't belong.  How frustrating!
