### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by Pelycosaurus** [ReikaKalseki/Reika_Mods_Issues#712]
Well, i did what you wanted, but now it doesn't even leave a crash-report.

[Though here are the logs](https://gist.github.com/Pelycosaurus/91ece156338c9910f437047f2ea463e7#file-gistfile1-txt)

**Comment by Duckfan77** [comment]
[Github Gist](https://gist.github.com)

**Comment by ReikaKalseki** [comment]
WorldServer class not found, probable ASM crash, probably KCauldron.

**Comment by Pelycosaurus** [comment]
though i use Forge, not Cauldron.

**Comment by ReikaKalseki** [comment]
Ok, that means something else is conflicting. Also, it is a duplicate field error. I add no fields to WorldServer, leading me to wonder if my mods are involved at all.

**Comment by Pelycosaurus** [comment]
i will try out.
