### ISSUE TITLE
[Feature Request] Ability to disable AE2 intergration in config

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#713]
Since we all know the crash with AE2 rv3, why can we not just disable the AE2 intergration in the configs? Since I prefer rv3 to rv2, but I also want to use Chromaticraft.

**Comment by ReikaKalseki** [comment]
No for the same reasons as the interactions with Forestry, TiC, ThaumCraft, or NEI.
