### ISSUE TITLE
Centrifugal Fluid Extractor not working in V12

### ISSUE THREAD

**Issue by Njet75** [ReikaKalseki/Reika_Mods_Issues#714]
I can´t get centrifugal fluid extractor to work.
Cant make heavy water nor lithium.
/Njet

**Comment by ReikaKalseki** [comment]
Then you are using it incorrectly. I have several people using it without issue.

**Comment by Njet75** [comment]
Found the problem.
The Extractor was built to low (-31).
If i build it around -45 to -47 it works fine.

**Comment by ReikaKalseki** [comment]
They have no minimum Y value.
