### ISSUE TITLE
RotaryCraft Block Model Rendering and some names

### ISSUE THREAD

**Issue by WirtsLegs** [ReikaKalseki/Reika_Mods_Issues#715]
Right so experimenting with your latest builds of Rotary and ReactorCraft. I have not found any issues with ReactorCraft but RotaryCraft models do not seem to be working. Further I found a block with what seems to be a broken name.

Here is a album with pics illustrating the issues: http://imgur.com/a/TLdBe

I did find a slew of texture errors in logs http://pastebin.com/zBVXrPN6

I should also mention that I pulled all other mods and ran just with DragonAPI, RotaryCraft, and ReactorCraft and had the same issue.

edit: I will add I am running on Forge 1.7.10 - 10.13.4.1558

cheers

**Comment by EyeDeck** [comment]
The first thing is... well, check the date.

The other thing, you're not supposed to spawn technical blocks. Advanced gears are the technical block type for the CVT, industrial coil and, I think, shaft junction.
