### ISSUE TITLE
Chromacraft crashing when looking at block where progress is not unlocked

### ISSUE THREAD

**Issue by chanzie** [ReikaKalseki/Reika_Mods_Issues#717]
[crash-2016-04-01_10.26.45-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/199882/crash-2016-04-01_10.26.45-client.txt)
I was using the exchanger to finsih rebuilding my base after husband killed last server, when i ran across a chroma block the gray side bar started to show up but did not finish rendering and then the game crashed on my end the server stayed fine.

**Comment by ReikaKalseki** [comment]
Your file is trying to download itself. Use pastebin.

**Comment by Aivech** [comment]
Here is a gist of it: https://gist.github.com/DaMachinator/52296cda1b776a12569e8c3946fdc1cf

**Comment by ReikaKalseki** [comment]
This is the metadata-change crash.

#262, #342, #419

**Comment by ReikaKalseki** [comment]
[Is Glenn's gases present](https://github.com/lawremi/PerFabricaAdAstra/issues/56)?
