### ISSUE TITLE
Strange texture bug ?!

### ISSUE THREAD

**Issue by slasherbane** [ReikaKalseki/Reika_Mods_Issues#718]
what s appening ?
![2016-04-01_18 42 40](https://cloud.githubusercontent.com/assets/18220138/14218622/b8459e6a-f855-11e5-9f99-fa0773c9b630.png)
![2016-04-02_22 03 39](https://cloud.githubusercontent.com/assets/18220138/14218623/b84751ce-f855-11e5-9c95-110364869cb7.png)
![2016-04-02_22 03 42](https://cloud.githubusercontent.com/assets/18220138/14218624/b849ef92-f855-11e5-9b70-29cc023652a7.png)
help me please

**Comment by slasherbane** [comment]
oups the first is wrong

**Comment by Aivech** [comment]
April 1st.

Wait for the 3rd and it should revert.

**Comment by slasherbane** [comment]
seriously i m working on a big machin and....that's mean for me.

**Comment by slasherbane** [comment]
thank for your answer

**Comment by ExtraNautilus** [comment]
Ahhhh So thats what it is! I've been messing around with my mod combos for over an hour to figure out which mod is creating what I thought was a texture conflict... lol

**Comment by ReikaKalseki** [comment]
Also, update.
