### ISSUE TITLE
April Fools texture not even funny.

### ISSUE THREAD

**Issue by demethan** [ReikaKalseki/Reika_Mods_Issues#720]
disappointed.. 

At least make it fun or something. :)

https://dl.dropboxusercontent.com/u/2804046/2016-04-01_20.36.51.png

**Comment by ReikaKalseki** [comment]
I disagree, especially if you know their origin. :P

**Comment by keybounce** [comment]
Apparently, they are the earliest textures from when this was just starting.

**Comment by demethan** [comment]
When is it going back to normal?

**Comment by ReikaKalseki** [comment]
... :)

**Comment by demethan** [comment]
Liggit question.. I still have the derpy textures.

**Comment by TomeWyrm** [comment]
Wait until tomorrow.

Also, this is one of the two reasons I hate holiday shit. The rash of faulty reports/issues, and the difficulty in testing because it's time sensitive.

**Comment by ReikaKalseki** [comment]
It can easily be tested; you just make it not time-sensitive when coding it. :P

**Comment by TomeWyrm** [comment]
Yeah... and what about all the cases you can't test? I only need point to all the freaky interactions iChun's holiday shenanigans caused in years past, or the Pax Pox added by Way of Time (Blood Magic Dev). You can't test all cases, which means you're going to find bugs in holiday code eventually... and most likely that code isn't fresh in your mind when the event happens...

I mean, sure. Texture switching is innocuous enough, but I've had so many damn issues with this kind of feature in the past I just turn them off as a matter of course now.

**Comment by keybounce** [comment]
My personal favorite: Comic sites that turn the graphics upside down, and any accompanying text right to left. I can handle the right/left swap by disabling java script, but the upside-down graphics makes the comic site pointless.

This is _not_ a made-up example. MsPaint Fan Adventures. If you know the sillyness of the homestuck fandom, you can understand it -- but for people who are not hard-core stuck-ups, it's a pain.

**Comment by Barhandar** [comment]
Still better than GregTech's "everything is trollface".
