### ISSUE TITLE
Chromaticraft crash on startup - log included

### ISSUE THREAD

**Issue by plazia** [ReikaKalseki/Reika_Mods_Issues#721]
Adding Chromaticraft and ONLY Chromaticraft (replete with it's dependency DragonAPI) causes the following crash on startup.

http://pastebin.com/4giABFu0

**Comment by Aivech** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/703

contains workaround.

**Comment by ReikaKalseki** [comment]
Use the HashMap SoundCategory config.
