### ISSUE TITLE
EIO Broken spawner dupe with RotaryCraft Bedrock Alloy Pick

### ISSUE THREAD

**Issue by MineWitherMC** [ReikaKalseki/Reika_Mods_Issues#722]
Find a spawner and break it with bedrock-alloy pick:
![2016-04-02_17 18 01](https://cloud.githubusercontent.com/assets/18210824/14226886/f7e3b08c-f8f7-11e5-8e0a-24502b82d7d0.png)
After you kill appeared mobs you will realise that both RC & EIO spawners are dropped (sorry for 2 broken spawners, forgot to make a screenshot first):
![2016-04-02_17 20 24](https://cloud.githubusercontent.com/assets/18210824/14226893/3e2947be-f8f8-11e5-92cc-7bff236e5a04.png)
Then you place RC spawner and break it and 1 more EIO spawner drops:
![2016-04-02_17 21 20](https://cloud.githubusercontent.com/assets/18210824/14226895/4babfb20-f8f8-11e5-986d-bd214949365f.png)
This is tested on RC v12d 1.7.10.

**Comment by ReikaKalseki** [comment]
I know. They have a blacklist - which includes the bedrock pick by default - and which appears not to work.
