### ISSUE TITLE
No textures in RotaryCraft 12d 1.7

### ISSUE THREAD

**Issue by MineWitherMC** [ReikaKalseki/Reika_Mods_Issues#723]
Instead of textures and models I see this...
![2016-04-02_18 01 52](https://cloud.githubusercontent.com/assets/18210824/14227080/0b4501ee-f8fd-11e5-9c52-094fae1ddaf3.png)

**Comment by ghost** [comment]
Duplicate of #716 and #718. Part of April Fools and will end on the 3rd.

**Comment by MineWitherMC** [comment]
OK, can I disable it then?

**Comment by redelman** [comment]
Change the date on your conputer.

**Comment by MineWitherMC** [comment]
Thanks, it worked!
