### ISSUE TITLE
[Feature Request][ModComp] More heatable machines.

### ISSUE THREAD

**Issue by MaciejMalczyk** [ReikaKalseki/Reika_Mods_Issues#724]
Are you thinking about adding more mod compatibility to Friction Heater? For example for Boilers from RailCraft/GregTech, IC2 heatable machines, Modular Systems?

**Comment by ReikaKalseki** [comment]
They need to implement my interface.

**Comment by Aivech** [comment]
The IC2 external heater is able to heat Thaumcraft's alchemical furnace, and IIRC IE came out after TC4.2 went into version lock. I wonder if the friction heater will work on it.

**Comment by ReikaKalseki** [comment]
No. There is no MC counterpart to block temperature. It is possible IC2 uses reflection (or a preexisting interface). In my case, the FrictionHeatable interface needs to be implemented, at which point it will work automatically.

**Comment by Aivech** [comment]
IC2 uses HU, basically another form of power, that is trasferred between adjacent machines.
