### ISSUE TITLE
DragonAPI oredict registration logspam with gregtech

### ISSUE THREAD

**Issue by jkenyonc** [ReikaKalseki/Reika_Mods_Issues#725]
as I am sure you know, dragonAPI logs every oredict registration during game load. This is not usually problematic, expect when GregTech is installed. DragonAPI logs every variant of every meta item and every ore. This adds up quickly, with the (open) mc launcher eating up hundreds of megabytes of RAM. could you add a config to disable this logging? (or exempt GregTech from it)

**Comment by ReikaKalseki** [comment]
Perhaps it will be more obvious this time:

![](http://i.imgur.com/prw1TPF.png)
