### ISSUE TITLE
Lumen Repeater Crash

### ISSUE THREAD

**Issue by KeepYourTemper** [ReikaKalseki/Reika_Mods_Issues#726]
I am currently using DragonAPI and Chromaticraft v12d. This version changelog says it fixed the Lumen Repeater crash, but I'm still crashing. After updating, i attempted to place one (no where near a pylon) and it has brought my server into a crash loop. This is my current crash log:

http://pastebin.com/JpgDTqmM

**Comment by ReikaKalseki** [comment]
Already fixed.

**Comment by KeepYourTemper** [comment]
Is there an ETA for when the download with the fix will be available? I'm currently on v12d and that appears to be the latest.

**Comment by TomeWyrm** [comment]
Do not ask for ETAs

**Comment by KeepYourTemper** [comment]
Sorry, didn't know. I'll keep that in mind in the future though!

**Comment by TomeWyrm** [comment]
Also, v12e was released. So try that :-)
