### ISSUE TITLE
About DragonApi reloading resources

### ISSUE THREAD

**Issue by Sima214** [ReikaKalseki/Reika_Mods_Issues#728]
Some versions back (don't remember which exactly) a new feature was added in DragonApi for downloading and loading into the game external resources. From what I know this is used by Chromaticraft for the dimension music. However the same feature also forces the game to reload its resources (texture packs) after it is done loading them(!), which is kind of redundant. This adds unnecessary load times to every launch of the game, even thought it could be reduced to only happen once (or twice cause minecraft).
My suggestion is to load everything you need at the second "Reloading resources" done by minecraft and there if you need to wait for another thread (like the one downloading) block the client thread and wait for an interrupt, until the data is ready. You could also provide support for the forge loading bars, but I don't know how stable the api for those is. Just don't provide the user with a frozen main screen.

**Comment by ReikaKalseki** [comment]
The frozen main screen is for the final resource reload, which DragonAPI triggers to fix issues with LiteLoader. It has nothing to do with the music.

**Comment by Sima214** [comment]
Sorry @ReikaKalseki, but could you point me somewhere where this issue with LiteLoader is discussed and why this final resource reload is necessary for your mods? Thanks in advance.

**Comment by Sima214** [comment]
I found #97 but I am not sure if is related or not.
My main point is: Is this reload necessary, even when LiteLoader is not part of the mod instances?

**Comment by ReikaKalseki** [comment]
Yes, otherwise sounds fail to work and many textures are broken.

**Comment by Sima214** [comment]
Okay, I don't really get it. However as this is just minor, I don't feel like taking this any longer.
Just for reference thought I started this issue because I had some difficulties with finding just the right heap size.
