### ISSUE TITLE
[CC] Hidden Ores incomplete?

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#729]
I don't know which one this is, but it neither A: has any sort of proper breaking particle effect, or B: drops stone/cobble.

https://i.gyazo.com/cd05edc7f913eb0dfb5cc749e4f5d11e.mp4

**Comment by ghost** [comment]
It's one of Chromaticraft's tiered ores. I don't know which but it may be one that isn't used and therefore doesn't show the proper stone texture. Tiered ores also don't drop stone or cobblestone because it's merely a disguise until it's discovered from progress.

**Comment by Shahelion** [comment]
The other tiered ores have stone particles as normal, it seems to just be this one. Still not sure which it is yet. I have it marked off for when it's revealed.

**Comment by TomeWyrm** [comment]
When did Reika change that? I swear when I was digging around on the server the tiered ores I hit gave me cobble.

Edit: Obviously when I couldn't mine the ore itself because progress

**Comment by ReikaKalseki** [comment]
They do drop cobble.

And the textures are there, and the new ores have all the same code as the old ones.

**Comment by Shahelion** [comment]
Weird...none of them have ever dropped cobble for me, in any version.

**Comment by ReikaKalseki** [comment]
Possibly fixed.
