### ISSUE TITLE
Particle spawner server crash

### ISSUE THREAD

**Issue by lukassoo** [ReikaKalseki/Reika_Mods_Issues#730]
The Particle Spawner works fine on single payer but when placed on the server it couses a crash:

link : http://pastebin.com/mABL2L7W

Of course everything on the latest version (V12e) on a new clear map.

The server still can be started and works but if the player tries to look at the block(as soon as it should start rendering), comes to near to it even not facing it or stays some time in the surroundings of the block it kicks the client off with an error:

link : http://pastebin.com/RwKG2nyK

**Comment by EdwinMindcraft** [comment]
The problem is that particules are stored into NBT and requires an IIcon though this class doesn't exists on server... This means you might need to pass the name rather than the Icon itself...

**Comment by ReikaKalseki** [comment]
Fixed.
