### ISSUE TITLE
Crashing with startup: Using rotarycraft.

### ISSUE THREAD

**Issue by star1954** [ReikaKalseki/Reika_Mods_Issues#731]
Here is the crash report:

[crash-2016-04-04_10.00.53-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/202939/crash-2016-04-04_10.00.53-client.txt)

Also, I noticed it was looking for a config file when it crashed. I didn't see the configuration file in config/Reika.

**Comment by redelman** [comment]
DragonAPI v9b with RotaryCraft v12e? Update DragonAPI to the latest.
