### ISSUE TITLE
Crash on startup (v12e), ArrayIndexOutOfBoundsException: 9 + Could not initialize class Reika.ChromatiCraft.Registry.ChromaResearchManager$ResearchLevel

### ISSUE THREAD

**Issue by lightning02** [ReikaKalseki/Reika_Mods_Issues#732]
http://pastebin.com/9mgtLQtb

on forge 1614 
crash on startup trying to add last version of dragon api with Chromaticraft and Rotarycraft

**Comment by EdwinMindcraft** [comment]
DragonAPI configuration file has a use hash map for sound category, turn it on and it should work

**Comment by EdwinMindcraft** [comment]
I'd say #691

**Comment by lightning02** [comment]
I'm actually using version 12e with java 8 and, yeah I've cheked other similiar issue and I've see that post but after i have found that parameter in the config and changed it, it makes another crash; I've already set on true "Use vanilla keybind system for ability selection GUI". I've set hash map on true but the crash still occur.
![reik2](https://cloud.githubusercontent.com/assets/11884147/14290877/1f64a204-fb61-11e5-8133-2fc6d1eb5f25.png)

**Comment by lightning02** [comment]
Now the crash is this
http://pastebin.com/hYuTxtkT

**Comment by EdwinMindcraft** [comment]
That's an AE2rv3 crash just relaunch after the crash (same launcher instance)

**Comment by EdwinMindcraft** [comment]
#367

**Comment by lightning02** [comment]
Oh right! I was missing ae2 #367 issue post :O
It in fact crash only at the first launch.. so weird.
Well, thanks alot for the patience.. btw the next time I will check way more accurately the already existent issues and  I will take some more time testing before post something. 
Thanks again, you really saved me!
