### ISSUE TITLE
v12 reactorcraft steam bug server

### ISSUE THREAD

**Issue by rejectpretzel** [ReikaKalseki/Reika_Mods_Issues#733]
If you place down a turbine with a dynamometer in front of it facing the wrong direction then start the steam flow so the turbine begins spinning and screwdriver the dynamometer to face the correct way, all of the blocks that transfer shaft power begin rotating many times per second showing the outputs everywhere around them. This also causes a massive lag spike, which appears to be only client side as the tps of the server remains the same. my friend who was on the server at the time relogged and we both saw a copy of his player which he proceeded to kill, take his own items and relog again, logging back into the death screen losing all of his items. The server also was throwing tons of errors in console but not crashing , I attached the error in a txt file. After restarting the server the bug temporarily went away before reappearing despite changing nothing.

[server error.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/207610/server.error.txt)

All engines appear to be reeplaced with dc electric engines as the ones in the screenshot are all microturbines. ![dc engines](https://cloud.githubusercontent.com/assets/18181026/14338245/598f3ac4-fc43-11e5-94ee-1d4c1e856614.jpg)

Here are several screenshots of the bug occurring.

![2016-04-06_21 48 36](https://cloud.githubusercontent.com/assets/18181026/14338276/b501f590-fc43-11e5-8c31-d52d065a8ab9.png)
![2016-04-06_21 51 48](https://cloud.githubusercontent.com/assets/18181026/14338278/b50398c8-fc43-11e5-95e6-438b745bc0be.png)
![2016-04-06_21 54 33](https://cloud.githubusercontent.com/assets/18181026/14338277/b502801e-fc43-11e5-85d0-d0da5526999c.png)

for some reason it appears to only effect blocks within the two chunks that the turbine is located in.

![2016-04-06_22 22 41](https://cloud.githubusercontent.com/assets/18181026/14338571/01c7fbac-fc46-11e5-93e2-27f489d536b3.png)

**Comment by rejectpretzel** [comment]
After some further testing it appears to be steam that is causing the issue. Removing the steam present in the turbine room stopped the turbine rotating and removing the rest of it stopped everything else rotating. However some steam is trapped in the sides of the turbines. 

![2016-04-06_22 39 20](https://cloud.githubusercontent.com/assets/18181026/14339067/ac2263f0-fc49-11e5-8d55-454ffb707c0c.png)

**Comment by rejectpretzel** [comment]
It also happens on a singleplayer world.
![2016-04-06_23 21 53](https://cloud.githubusercontent.com/assets/18181026/14339654/54585990-fc4e-11e5-9da2-c2b280ec10b5.png)

**Comment by ghost** [comment]
This is known. Steam causes a lot of lag and chunk updates causing the inputs/outputs on machines be on constantly. Only fix is to make a steam void where it all goes into one block or use a steam scrubber.
