### ISSUE TITLE
Industrial coils not charging fully.

### ISSUE THREAD

**Issue by stiny861** [ReikaKalseki/Reika_Mods_Issues#736]
Running on dragonapi v12e and rotarycraft v12e. Industrial coils do not charge past a very low certain point, based on engine. A coil, placed in front of a steam engine, will charge to about 1kj, a gas engine will give you just over 3kj, and an ac engine will give just over 6kj. Coil will discharge correctly when given a redstone signal.

**Comment by TomeWyrm** [comment]
Read the manual. You're missing important mechanics about the industrial coils, they're not "plug DC engine in, wait 3 days, power bedrock breaker" any longer.
