### ISSUE TITLE
RotaryCraft conflict cfg NatureOverhaul

### ISSUE THREAD

**Issue by SvEgiiVEteR** [ReikaKalseki/Reika_Mods_Issues#737]
RotaryCraft 1.7.10 V12e.jar
breaks config mod NatureOverhaul-0.10.0(1.7.10).jar
when installation RotaryCraft 
add a line in config
    Spreading {
        # [default: 0]
        I:=0
and
    Flammability {
        # [default: 0]
        I:=0

I:=0 It caused the problem and configuration itself is removed and generates new again.
it does not allow to edit config NatureOverhaul as require.
Corrected please ..

**Comment by ReikaKalseki** [comment]
I need a coherent description first.

**Comment by SvEgiiVEteR** [comment]
your mod there are things that have a name for example. mod which defines as empty.
and adds to config "I:=0"
and breaks them.

in my  300 mods.
none causes a problem in NatureOverhaul

**Comment by TomeWyrm** [comment]
@SvEgiiVEteR What language do you usually speak?

I ask because we can't understand your English very well, and maybe we will be able to talk with your language more easily.

**Comment by SvEgiiVEteR** [comment]
@TomeWyrm I am Russian,enough to put these two mod and verify the problem.
in a related topic the author of another mode already answered.

**Comment by ReikaKalseki** [comment]
They put in a fix, so nothing needs to be done on my end. Especially given that we are still unaware of any error.
