### ISSUE TITLE
Tungsten Flakes lookup in NEI causes game to crash

### ISSUE THREAD

**Issue by widd** [ReikaKalseki/Reika_Mods_Issues#738]
http://pastebin.com/eiyJgCa5 Crash log.

I combed previous issues and apparently Avaritia was causing a similar bug, however this crash occurs without that mod installed.

It happens when clicking on Tungsten Flakes in NEI.

**Comment by widd** [comment]
After more searching I found the cause to be AOBD not playing nicely with RotaryCraft. Disabling all of the RotaryCraft config options (setting to false) in the AOBD config fixed it. I haven't tested each individual option, but I'm assuming that any related ore/dust/flake items will similarly crash unless the option for them is disabled in the AOBD config.

**Comment by ReikaKalseki** [comment]
Did he not fix that long ago?

**Comment by TomeWyrm** [comment]
@ganymedes01 We appear to have an issue.
