### ISSUE TITLE
Kindly asking a full compatibility with FortuneOres (if possible)

### ISSUE THREAD

**Issue by lightning02** [ReikaKalseki/Reika_Mods_Issues#739]
Hi guys,
I've notice that some of the ore chunks from fortune ores works with rotarycraft machines (like grinder); mainly iron and gold. unfortunately it doesn't with ores like copper, tin, osmium etc...from FortuneOres 
[i'm kinda sure you alredy know FortuneOres but if you may don't, it is a mod that just directly convert every metal ore using OreDictionary that makes life easier]  
![img_13042016_194002](https://cloud.githubusercontent.com/assets/11884147/14503360/1134a508-01b0-11e6-8282-5920a25b88fb.png)
![f056de54608d1d701ca33d9085132641f2938204cee7c6760a pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/14503370/16bf0824-01b0-11e6-94a1-6c3cbea0b76c.png)

**Comment by ReikaKalseki** [comment]
They must not be registered as ores in the OreDictionary, at least not by the time RotaryCraft gets its postload.

**Comment by lightning02** [comment]
I've talk to the Owner of FortuneOres and he said that his ores are correctly registered in the oredictionary after i showed to him some screenshots about that.
he suggested the problem is maybe on your side [now that i think about that i did not encountered any issues of his ores on any other mod as long as now].

**Comment by ReikaKalseki** [comment]
I work exclusively off the Ore Dictionary. Any claims he makes that I am hardcoding it are entirely fallacious.

**Comment by lightning02** [comment]
So what he could do in order to make his ore chunks works with your machinery?

**Comment by DemoXinMC** [comment]
I didn't make any claims that you hardcoded it.  I simple said my ores are registered with the OreDictionary.  To be specific, they are registered during FMLInitialization. I don't know why, without looking at your code, they don't work together.

**Comment by EdwinMindcraft** [comment]
You'll might need to create an handler for it to work...

https://github.com/ReikaKalseki/DragonAPI/tree/master/ModInteract/ItemHandlers should help

**Comment by EdwinMindcraft** [comment]
Basically Reika's handlers check for mods not ores so...

**Comment by ReikaKalseki** [comment]
No, those handlers are entirely on my end for loading other mods' items, blocks, and other content, and have nothing to do with ores.

@DemoXinMC 
I have [a large registry](https://github.com/ReikaKalseki/DragonAPI/blob/master/ModRegistry/ModOreList.java#L40) of all the mod ores I care about. This registry is used, among other things, to control Grinder and Extractor ore processing; a recipe is created for every entry, for every item registered as an ore under that entry. Last I remember, that is loaded in postLoad, so if you are registering the items to the Ore Dictionary in the main load phase, it _should_ work.

Also, items as "ore" tags is going to cause issues with MeteorCraft meteors and ChromatiCraft's Mineral Enricher, as both of those assume ores are blocks.
