### ISSUE TITLE
Shaft junction occasionally breaks on switching multi-directional clutch

### ISSUE THREAD

**Issue by ljfa-ag** [ReikaKalseki/Reika_Mods_Issues#74]
Consider the following setup:
![Imgur](http://i.imgur.com/xdcmPGn.png)
Power from four gasoline engines goes through one of two different gear ratios depending on the multi-directional clutch and gets merged again at the red marked shaft junction.
The red marked shaft junction would sometimes break at the exact moment the multi-directional clutch is switched. It does not happen consistently though, I usually only notice it happenning by hearing an explosion from somewhere else.
Green is the input to the clutch, it is hooked up to four gasoline engines.

I'm using a sequencer from RFTools to switch the clutch by the way.

Running DragonAPI and RotaryCraft v6f

**Comment by ReikaKalseki** [comment]
I was sure I fixed this...

**Comment by ljfa-ag** [comment]
Hm: https://github.com/ReikaKalseki/RotaryCraft/blob/master/TileEntities/Transmission/TileEntitySplitter.java#L392
The overload tick is never set to zero. Seems like it just accumulates until it hits 20.

**Comment by ReikaKalseki** [comment]
....Oh.

**Comment by ReikaKalseki** [comment]
Fixed.
https://github.com/ReikaKalseki/RotaryCraft/commit/dfca578f29db5933cefe730de075ea541e6629db
