### ISSUE TITLE
domain minecraft is missing 1 texture

### ISSUE THREAD

**Issue by codycoolwaffle** [ReikaKalseki/Reika_Mods_Issues#740]
I actually have no idea what is going on...
NOTE: running on V12e
http://pastebin.com/TD3whASB

**Comment by ReikaKalseki** [comment]
Your log does not contain a crash, much less a missing texture one. Missing texture errors do not cause crashes.

**Comment by codycoolwaffle** [comment]
@ReikaKalseki While it does not contain a crash, it does not allow me to start the game, killing it at the main screen. Can i have any help there?

**Comment by ReikaKalseki** [comment]
Every log you have posted has been identical and does not contain any fatal errors, much less a crash log. And as I said before, textures are not related in any way.

**Comment by codycoolwaffle** [comment]
@ReikaKalseki 
When i tried to install dragonapi v12e the game quit out and gave me this:
http://pastebin.com/uwD1nm8E
After reading it i concluded it needed me to install framez(Which needs forge multipart), then after that i ran it again, and it quit out with this:
http://pastebin.com/xfUWjdbQ

Help?

**Comment by codycoolwaffle** [comment]
Ok, i realize in all of these cases i sent logs without the proper JVM settings...
I'll fix that when i get back to my computer, then send updated logs.

**Comment by codycoolwaffle** [comment]
Without framez:
http://pastebin.com/39feXuQQ

With framez:
http://pastebin.com/XnYhNCCM

**Comment by codycoolwaffle** [comment]
@ReikaKalseki It doesn't send it to the console, but it stops responding at the main menu, then java tells me it needs to be closed without giving me any other option.

**Comment by redelman** [comment]
There's nothing to help you with here. Missing textures is quite benign. Whatever is keeping your game from starting, it isn't missing textures, and we're not able to help.

**Comment by redelman** [comment]
In fact, your log without framez doesn't even show any missing textures. Only your log with framez does. Whatever on earth possessed you to file a bug here, of all places?

**Comment by codycoolwaffle** [comment]
@redelman Because it crashes with dragonapi. I remove it and everything is fine.

**Comment by redelman** [comment]
Reika's first comment and mine stand. There is no crash in the log, so there is no stack trace. The logs look normal. There nothing for anyone to look at here. Again, we're unable to help. Further, your first paste is titled "Chromaticraft crash", and the issue is supposedly about missing textures supposedly causing crashes, and even aside from framez, your mod lists in the logs don't come close to matching. You're doing all sorts of things wrong here. Troubleshoot this further yourself, then if you find something, come back and try again.

**Comment by redelman** [comment]
One final thing, @codycoolwaffle. Your original log is short by 69 lines. At that point the splash screen isn't even done yet. I suspect a couple of things: your computer is slow, your internet is slow, you are impatient. Using Forge 1558 and DragonAPI v12e and ChromatiCraft v12e, my log is 2709 lines long. while sitting at the main menu.There is a 30 second delay or so at the main menu, before it becomes responsive. I'm not 100% sure of the cause of that, but I have some ideas. Perhaps you should wait longer. The final line in your log should be something like: [Biome FX Loader/INFO] [FML/ChromatiCraft]: CHROMATICRAFT: Constructed biome FX images in 35361 ms.

**Comment by ReikaKalseki** [comment]
That last line will not show if they disable biome FX.
