### ISSUE TITLE
domain minecraft is missing 1 texture

### ISSUE THREAD

**Issue by codycoolwaffle** [ReikaKalseki/Reika_Mods_Issues#741]
When i tried to install dragonapi v12e the game quit out and gave me this:
http://pastebin.com/uwD1nm8E
After reading it i concluded it needed me to install framez(Which needs forge multipart), then after that i ran it again, and it quit out with this:
http://pastebin.com/xfUWjdbQ

Help?

**Comment by ReikaKalseki** [comment]
Do not open new issues every time you update [an old one](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/740).
