### ISSUE TITLE
ClassCastException with DragonAPI & Thermal Expansion

### ISSUE THREAD

**Issue by Grizzord** [ReikaKalseki/Reika_Mods_Issues#744]
i am running a private server mod pack and it randomly crashed today. this is the crash report
http://pastebin.com/cHdF9ByK

im not really sure why dragonAPI is causing this error? any ideas?

**Comment by EdwinMindcraft** [comment]
Did you use a map editor ? Because this should never  append

**Comment by Grizzord** [comment]
no thats the weird thing. the server was running while i was at work and crashed while i was away

**Comment by EdwinMindcraft** [comment]
You have a wrong TE so that may cause a problem

**Comment by EdwinMindcraft** [comment]
Though it seems like an immibis chunk loader issue

**Comment by Grizzord** [comment]
sorry im not quite familiar with TE?
and the chunk loader is having issues?
by chance do you know which dimension it could be in?

**Comment by EdwinMindcraft** [comment]
TE is a tile entity

**Comment by Grizzord** [comment]
oh okay thank you for clarifying. so right it seems that the tesseract is having issues with dragonAPI. but why would it have issues with DragonAPI?

**Comment by EdwinMindcraft** [comment]
Though DragobApi doesn't seem to be the cause and no I can't determine what dimension it is in from the log sorry...

**Comment by Grizzord** [comment]
hhmm thats okay. so you think it might have something to do with the chunk loader?

**Comment by EdwinMindcraft** [comment]
Or a frame mod

**Comment by EdwinMindcraft** [comment]
At least something put a block in a wrong position so maybe a failed save. Which could explain the chunk loaded thingy.

**Comment by Grizzord** [comment]
so would the best thing to do is roll back the server a bit to an early back up?

**Comment by EdwinMindcraft** [comment]
I guess so...

**Comment by Grizzord** [comment]
well dang my last back up was 5 days ago but i guess it will work. thank you. (i am now installing autobackup software for the server now!)
