### ISSUE TITLE
Crash with Abyssalcraft (Cave Control V12a)

### ISSUE THREAD

**Issue by Shadows-of-Fire** [ReikaKalseki/Reika_Mods_Issues#745]
http://paste.feed-the-beast.com/view/d6afd0fc
It seems to be on their end, but I thought it might be worthwhile to mention it here.

**Comment by ReikaKalseki** [comment]
This is not the first time this has been reported, but it is a conflict regarding mineshaft generation objects. Also, last I heard, he was changing the system in such a way that this would not happen.
