### ISSUE TITLE
[SUGGESTION] Change the way the Chromatic Enchanter consumes Liquid Chroma

### ISSUE THREAD

**Issue by Aivech** [ReikaKalseki/Reika_Mods_Issues#746]
Currently, if whatever you are enchanting requires more Liquid Chroma than the buffer holds, you cannot perform the enchantment.
My suggestion is to make it consume Liquid Chroma over time rather than all at once, so that for high-level enchants you can pump more chroma in, but to make the enchanting fail if it runs out of Chroma during the enchanting process. Also, if this were to be implemented, a display of some sort showing how much Chroma would be required would be nice.

**Comment by ReikaKalseki** [comment]
Though I am not against the idea on its own merit, this is rather more difficult to implement.

**Comment by Aivech** [comment]
How much more? Divide chroma consumed by time to enchant in ticks for chroma consumption per tick, if this is less than the buffer size of the chromatic enchanter, use it, otherwise, divide chroma consumed by 3999 mb and use the result as the time to enchant instead. Or instead of making enchants so abusrd they would use that much chroma just take longer, add some way to augment the chromatic enchanter.

**Comment by ReikaKalseki** [comment]
I did increase the storage to 12 buckets.

**Comment by Aivech** [comment]
Thanks!
