### ISSUE TITLE
[Rotarycraft] Requesting a method to edit Jetpack Worktable Recipe

### ISSUE THREAD

**Issue by Shadows-of-Fire** [ReikaKalseki/Reika_Mods_Issues#747]
Is it at all possible for the Ethanol Jetpack (Not the subsequent higher versions, only the base one) to have its empty slot in the worktable recipe changed? I wish to gate it behind the Ender Dragon, and as such make it require Hardcore Ender Expansion's Dragon Essence.

I have not been able to find any method of changing worktable recipes.

**Comment by ReikaKalseki** [comment]
Right now there is none, but this has been planned for a long time. However, it is still waiting on ModTweaker to add some of the framework on its end to call my hooks.
