### ISSUE TITLE
Shaft Junction Outputting wrong direction.

### ISSUE THREAD

**Issue by TheOneOgre** [ReikaKalseki/Reika_Mods_Issues#748]
I'm using the latest version of RotaryCraft and the Shaft Junction seems to be outputting the wrong direction on the opposing side of the input. 
https://www.youtube.com/watch?v=y4sq3fV31jY&feature=youtu.be Is an example of what I'm experiencing. Happens with any kind of input and only the opposite side turns the wrong direction, side outputs work fine.

Mod Versions:
DragonAPI 1.7.10 V12e
RotaryCraft 1.7.10 V12e
ReactorCraft 1.7.10 V12d

**Comment by ReikaKalseki** [comment]
Yes, because the animation direction has to either be ignored or the power system would gain a huge amount of complexity with no benefit.

**Comment by TheOneOgre** [comment]
So RotaryCraft doesn't care about correct rotation? I was thinking it did because when I would connect 2 motors to a shaft junction, it would simply break. Somehow today though it's magically not breaking. Sorry for the confusion!

**Comment by ReikaKalseki** [comment]
The visual direction in which a shaft spins means nothing.
