### ISSUE TITLE
Enchantment Decomposer Crash

### ISSUE THREAD

**Issue by lukassoo** [ReikaKalseki/Reika_Mods_Issues#749]
The Enchantment Decomposer crashes the client after putting anything into the middle slot.

crash log link : http://pastebin.com/DrKjLKG5

Sorry if it's coused by doing something wrong, someone else is discovering it I'm just making crash reports of it lol.

**Comment by ReikaKalseki** [comment]
...What did you put in? I have been using it without issue.

**Comment by redelman** [comment]
The crash log definitely points to the enchantment decomposer, not the chromatic enchanter. IIRC any unenchanted item causes this crash. Can't believe I forgot to report it.

**Comment by ReikaKalseki** [comment]
In the future, @lukassoo, calling machines by the right names helps.

**Comment by lukassoo** [comment]
Sorry my head must have had a crash too

**Comment by EdwinMindcraft** [comment]
You should add a getProgress () != 0 in getCookProgressScaled (I), that should fix it.

**Comment by ReikaKalseki** [comment]
There is a cleaner solution.

**Comment by redelman** [comment]
Can confirm, a non-enchanted item placed into the enchantment decomposer crashes with div by zero. In this case, I used a slightly-worn stone pickaxe.

**Comment by ReikaKalseki** [comment]
Fixed.
