### ISSUE TITLE
The sync packet for {RC TE} would have just CME'd

### ISSUE THREAD

**Issue by csdivad** [ReikaKalseki/Reika_Mods_Issues#75]
I'm running a server with DragonAPI and RotaryCraft version V6f, and I have some concerning messages in the log file, like:

[00:31:16] [Server thread/INFO] [FML/]: DRAGONAPI: The sync packet for Tile Entity Hydrokinetic Engine @ DIM0: 929, 45, 816 would have just CME'd, as the
[00:31:16] [Server thread/INFO] [FML/]: Server-Thread data-writing code has overlapped with the Network-Thread byte[] dispatch.

I checked my <a href="https://gist.github.com/xypista/e4080a2cff2161c232df">last two fml logs</a> and those contains similar lines for 

<ul>
  <li>Pump</li>
  <li>Grinder</li>
  <li>Diamond Shaft</li>
<li>Hydrokinetic Engine</li>
</ul>

I know that the pump one happened randomly, no one was tinkering with it at that time. Although It's pumping an infinite water source into a liquid pipe system, and there is constant water usage on that line.
When the diamond shaft did this, the player who uses RotaryCraft was offline, so he couldn't messing with it. But his base is chunkloaded and that shaft is next to his hydrokinetic engine which is running nonstop.
That grinder also grinding Canola Seeds constantly.

Just to mention, I'm using FastCraft 1.21, don't know if it could cause these.

**Comment by ljfa-ag** [comment]
Are all those machines working correctly and properly synchronized with the client?
This message doesn't seem to appear very often after all.

**Comment by csdivad** [comment]
Everything seems fine in-game.

**Comment by ReikaKalseki** [comment]
This is a warning, not a bug. If you see it more than sporadically, what is happening is that your server thread is starting to lag, causing it to lose sync with the network thread. As the message indicates:

The correct order of operations is:
[Server Thread] Begin Write Data To Sync Packet
[Server Thread] End Write Data To Sync Packet
[Network Thread] Dispatch Sync Packet

However, for you, it is:
[Server Thread] Begin Write Data To Sync Packet
[Network Thread] Dispatch Sync Packet
[Server Thread] End Write Data To Sync Packet

This is fairly clearly invalid, and what results is that error message as a warning. The alternative, aside from a silent error catch, is a crash.
