### ISSUE TITLE
TConstruct-style bedrock alloy tools insta-break

### ISSUE THREAD

**Issue by MineWitherMC** [ReikaKalseki/Reika_Mods_Issues#750]
Some issues with bedrock alloy TConstruct tools...
1) Weapons work fine, battleaxes (as weapon) work fine, chisels work fine.
2) Excavator and hammer work as expected.
3) All other tools (didn't test weapons) have strange behavior: on breaking block they disappear. Even in creative. Also they don't break blocks in creative as the blocks re-appear (they do in survival).
4) Mattock works normally, but only if used as a hoe
RC 12e, TConstruct 1.8.8.991

**Comment by ReikaKalseki** [comment]
Anything that duplicates a RC bedrock tool is disabled, both in recipe and in utility.
