### ISSUE TITLE
Chromaticraft crystal orchestra demo not functioning

### ISSUE THREAD

**Issue by eqdanteon** [ReikaKalseki/Reika_Mods_Issues#751]
Currently running V12e of Chromaticraft and the demo button on the crystal orchestra does not appear to load the track.  I am able to record, playback and make use of all other features.  Any assistance would be greatly appreciated.

**Comment by ghost** [comment]
Did you put the crystal lamps (has to be a certain order and directional) around the crystal orchestra? Reika has a video on it if you're not sure how to place the lamps.

**Comment by ReikaKalseki** [comment]
Does it play buzzing noises or do nothing?

Also, I just tested and it still works.

**Comment by eqdanteon** [comment]
Does nothing.  I only get the buzzing noises if the crystals are in the wrong position when trying to playback anything else.

**Comment by eqdanteon** [comment]
Works perfectly in single player creative mode - original attempts were on a SMP

**Comment by EdwinMindcraft** [comment]
Have you got the midi file server side ?

**Comment by eqdanteon** [comment]
As far as I am aware the midi file is contained in the jar and I am using the same file on both server and client.

**Comment by ReikaKalseki** [comment]
Which is why this makes no sense.

**Comment by ReikaKalseki** [comment]
I put some logging in for the next version.

**Comment by ReikaKalseki** [comment]
It works in a server environment now.
