### ISSUE TITLE
ElectriCraft's IC2 Battery can not be used?

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#753]
It can not storage the IC2 power(EU)......
It looks like ...... above it lacks an interface?
Is it a bug? Or my mistake? Thanks!

**Comment by ReikaKalseki** [comment]
ElectriCraft does not have an IC2 battery.

**Comment by ghost** [comment]
@ReikaKalseki I'm so sorry, this is my mistake. But I mean is the EU splitter has no input side.
![2016-04-21_10 47 31](https://cloud.githubusercontent.com/assets/17511988/14696577/cb2af4cc-07ae-11e6-8e8f-5447a0c4f193.png)

**Comment by ReikaKalseki** [comment]
The yellow side taking up 30% of the picture _is_ the input.

**Comment by ghost** [comment]
@ReikaKalseki Oh...... There is some problem. Please look at the **shortcut bar**, but the input should not at the top of it?
I think the orange point at the top of it should be the input but I can't find it...... and I always thought that yellow side was output...
If the yellow side is the input, but where is the output?

**Comment by ReikaKalseki** [comment]
You select output sides. Read the handbook.

**Comment by ghost** [comment]
@ReikaKalseki Thank you very much! Oh this is interesting!
