### ISSUE TITLE
Chromaticraft Lumen Harnessing not flagging

### ISSUE THREAD

**Issue by eqdanteon** [ReikaKalseki/Reika_Mods_Issues#755]
Running Chromaticraft v12e on a SMP server and we cannot get the Lumen Harnessing progression to flag.  Looking at the source code it appears that it is suppose to happen when you craft the weak repeaters (lumen repeaters) but that is not currently happening.  In case it is relevant we are currently using the casting temple. Any assistance would be greatly appreciated.

**Comment by ReikaKalseki** [comment]
That is not the trigger at all, and I have seen the real trigger work.

**Comment by ghost** [comment]
I'll give you a hint: connect the "dots"

**Comment by ReikaKalseki** [comment]
I **like** that.

**Comment by eqdanteon** [comment]
Hopefully this does not sound rude since I have no intention of being rude we are just completely at a loss.  If you are referring to connecting it to a pylon we have also done that.  The repeater makes particle effects.  We have even strung a few together to see if that triggers it.  If I am not doing the right thing let me know and we will keep trying.

Thanks

**Comment by eqdanteon** [comment]
Please disregard.  We figured out what we were doing wrong.  I apologize for the false bug report.
