### ISSUE TITLE
Overheating my PC

### ISSUE THREAD

**Issue by formerlyknownasprince** [ReikaKalseki/Reika_Mods_Issues#756]
Ever since I installed your mods my game's been overloading my computer, and now my CPU monitoring software says it's overheating. I've half a mind to bill you for damages if your mods fry my computer.

**Comment by redelman** [comment]
Of course, you could always uninstall the mods. Or clean out your computer of the dust bunnies that have taken up residence there.

**Comment by Duckfan77** [comment]
https://sites.google.com/site/reikasminecraft/licensing
Section 1.

**Comment by ReikaKalseki** [comment]
While you are at it cleaning the dust, do it in your head as well.
