### ISSUE TITLE
Uranium processor not processing uranium.

### ISSUE THREAD

**Issue by Troodontid** [ReikaKalseki/Reika_Mods_Issues#757]
I'm currently running the latest version of ReactorCraft, and I ran into an issue where the uranium processor will not process uranium ingots unless it is also processing fluorite crystals. Even when hydrofluoric acid is present in the processor, if I remove the fluorite, the uranium ingot will stop processing, and only resumes when the fluorite is added back into the machine. EDIT: If the processor is completely filled with hydrofluoric acid, the fluorite won't be consumed, but the uranium still won't be processed without it.

**Comment by ReikaKalseki** [comment]
Hopefully fixed.
