### ISSUE TITLE
Crash when breaking Minicio Ore

### ISSUE THREAD

**Issue by abrenneke** [ReikaKalseki/Reika_Mods_Issues#758]
When breaking a Magical Crops Minicio Ore, a crash happens with the following stack trace:

> java.lang.NullPointerException: Playing level event
>     at Reika.ReactorCraft.Blocks.BlockReactorTile.func_149691_a(BlockReactorTile.java:209)
>     at net.minecraft.client.particle.EntityDiggingFX.<init>(EntityDiggingFX.java:26)
>     at Reika.DragonAPI.Instantiable.Effects.ReikaModelledBreakFX.<init>(ReikaModelledBreakFX.java:35)
>     at Reika.DragonAPI.Libraries.IO.ReikaRenderHelper.addModelledBlockParticles(ReikaRenderHelper.java:272)
>     at Reika.ReactorCraft.Blocks.BlockReactorTileModelled.addDestroyEffects(BlockReactorTileModelled.java:63)
>     at net.minecraft.client.particle.EffectRenderer.func_147215_a(EffectRenderer.java:228)
>     at net.minecraft.client.renderer.RenderGlobal.func_72706_a(RenderGlobal.java:2286)
>     at net.minecraft.world.World.func_72889_a(World.java:3757)
>     at net.minecraft.world.World.func_72926_e(World.java:3748)
>     at net.minecraft.client.multiplayer.PlayerControllerMP.func_78751_a(PlayerControllerMP.java:120)
>     at net.minecraft.client.multiplayer.PlayerControllerMP.func_78759_c(PlayerControllerMP.java:247)
>     at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1357)
>     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1967)
>     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
>     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
>     at net.minecraft.client.main.Main.main(SourceFile:148)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>     at java.lang.reflect.Method.invoke(Unknown Source)
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I'm using:

DragonAPI `V12e`
ReactorCraft `V12d`

Magical Crops Core `4.0.0 Public Beta 5`

Seems like a particle thing? Any way to disable that via config?

Not saying it's necessarily ReactorCraft or DragonAPI, it's just in the stack trace is all.

**Comment by ReikaKalseki** [comment]
Client/server block mismatch.

**Comment by abrenneke** [comment]
1.7 has dynamic block IDs. How is that even supposed to be fixed?

**Comment by ReikaKalseki** [comment]
It is probably transient.
