### ISSUE TITLE
Feature Request: Expanded Redstone Block Breaker Harvest Levels

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#759]
At this point, all the tools in RotaryCraft are respecting the modified mining progression in Survival Industry.  However, the iron-level block breaker is still capable of breaking diamond, even though that harvest level is now reserved for steel only.  This, obviously, would allow a player to circumvent progression by using an iron block breaker and a button to harvest enough diamond to make a diamond pickaxe.

Because of this, I'd like to request a feature in which the harvest level of the iron block breaker can be adjusted, or a way to alter the recipe for that one block alone (I can't change the recipe to use a steel pickaxe, since all the block breakers are under the exact same meta).

**Comment by ReikaKalseki** [comment]
> (I can't change the recipe to use a steel pickaxe, since all the block breakers are under the exact same meta)

MT can do NBT. Just change their recipes.

**Comment by ghost** [comment]
MineTweaker is no longer used due to an unacceptable level of inflexibility.

I had a MineTweaker configuration to disable Metallurgy's Manganese because of its completely unrealistic (no-carbon) steel recipe.  However, if a player decides to disable Metallurgy, it breaks MineTweaker enough that all configurations after the manganese settings are ignored.

In other words, MT will work perfectly...right up until the first error.

At this point, we're using [JMOD](http://minecraft.curseforge.com/projects/jmod-the-javascript-mod-loader) to do all tweaking in the game.

That being said, I'll see if JP can simply add the NBT setting to the recipe tweaks.  Thanks for the response!

**Comment by TomeWyrm** [comment]
MineTweaker can use different script, only individual scripts should break.

**Comment by ReikaKalseki** [comment]
It is impractical to put all changes in their own file.

**Comment by TomeWyrm** [comment]
But limiting changes on a file-per-mod basis would prevent such issues easily, and be a logical organizational structure.

**Comment by ghost** [comment]
Maybe so, but when those scripts break, they spew forth a torrent of error messages that can scare players away from the pack, thinking it broken.

The reason @jeffpengMC came up with [JMOD](https://github.com/jeffpengMC/JMOD) was to create a tweaking tool that makes use of a full programming language (using the Nashorn JavaScript engine built into Java 8) to configure the tweaks, including things like conditionals and loops, which MineTweaker's zenscript sadly lacks.

At the moment, it doesn't seem to support NBT data in recipes, or else I don't know how yet.

**Comment by ReikaKalseki** [comment]
It absolutely needs to be able to support it, at least as an output. Many items only differ in NBT.

**Comment by ghost** [comment]
It's something I've got on my to-do-soon. Most things work fine without NBT, but a few critical things do not - correct.

**Comment by TomeWyrm** [comment]
Actually it's one of the more uncommon crafting output differentiators. Metadata is much more common. That being said, it is definitely a good thing to have on your to-do list :-)

**Comment by ghost** [comment]
Really depends on the mod. Some mods use NBT excessively (like ender tools), some just to describe certain states like charge, ammunition, amount of liquid contained etc, others basically not at all. I personally try to stuff as much as I can into metadata before going into NBT.
