### ISSUE TITLE
Iguana Tinker Tweaks conflicts with RotaryCraft 1.7.10

### ISSUE THREAD

**Issue by Wolf68k** [ReikaKalseki/Reika_Mods_Issues#760]
Sorry if this has been mentioned already. I searched some what but didn't find anything.

With RotaryCraft installed, you are able to make Tinkers' tool parts that Iguana Tinker Tweaks (ITT) would other wise prevent you from making.

It also prevents the "Hold Shift for materials list" from working on patterns and casts.

MC version: 1.7.10
RotaryCraft version: V12e
ITT version: 2.1.6

**Comment by ReikaKalseki** [comment]
RotaryCraft only adds HSLA and bedrock, the latter of which is not even made the normal TiC way.

**Comment by Wolf68k** [comment]
I'm telling what I've tested. The least you can do is try it for yourself.
No other mods are installed. Just Tinkers, ITT and RotaryCraft.

**Comment by ReikaKalseki** [comment]
If ITT spontaneously stops working when RC is installed, that cannot be on my end when all I do is add a couple material types.

**Comment by bpwhelan** [comment]
I dont intend to prolong this issue,  but it kind of feels like it (or combination of it with dragonAPI) forces the unmodified patterns to load.  How it does this,  im not exactly sure. Maybe loading sequence?
