### ISSUE TITLE
Heat Exchanger Issues [ReactorCraft]

### ISSUE THREAD

**Issue by danmarcnichols** [ReikaKalseki/Reika_Mods_Issues#762]
The Version i used :
Rotarycraft V12e
Reactorcraft V12d
DragonAPI V11e
ElectriCraft V12c

I have a pebble bed reactor that is setup properly and producing heat and a heat exchanger that is properly powered and producing steam. As time goes on the heat exchanger reduces in temperature and begins to stop producing steam.

I am in creative mode using superflat save file format.

**Comment by danmarcnichols** [comment]
Randomly found the solution

**Comment by ReikaKalseki** [comment]
"Randomly" being that the exchanger was full, or that the hot CO2 supply stopped?
