### ISSUE TITLE
[ReC] Radiation cleanup tool handbook text missing

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#763]
Both the crafting grid and output slot for the Radiation Goggles are empty.

The description for the Radiation Cleanup Tool just says #NULL

**Comment by redelman** [comment]
The radiation goggles aren't craftable. They are a creative-only item.

**Comment by Shahelion** [comment]
Oh...the book should probably mention that, then. And the output slot should at least have the item, if for no other reason than to show what it looks like.

Also, is ReC the proper abbreviation for ReactorCraft?

**Comment by TomeWyrm** [comment]
Technically it should be RC but Railcraft got there first (and is way more popular, sadly). So some of us push for the more clear "ReC" to differentiate Reika's mod.

**Comment by ReikaKalseki** [comment]
Another dumb mistake.
