### ISSUE TITLE
[Suggestion/Request] Meteorcraft - config per-world

### ISSUE THREAD

**Issue by Cronosus** [ReikaKalseki/Reika_Mods_Issues#764]
Hello
Please, is possible add to Meteorcraft per-world(dimension) configurable meteor rarity?
(i use Galacticraft, then i have many dimensions, but i don't want meteors in all of them, only in some)

thanks

**Comment by ReikaKalseki** [comment]
Not in a way that I can see. At the time configs are loaded, most dimensions are not yet registered and thus outside of some basic "if this mod is present, this dimension exists" ones, I have no way of knowing what dimensions for which to create entries in the config. Obviously, creating 4B entries for anything that _might_ be used is not a solution.

**Comment by TomeWyrm** [comment]
Could you not parse a list instead of using 4 billion entries? Like buildcraft's pump blacklist config, for example.

**Comment by ReikaKalseki** [comment]
It is not a simple "blacklist dimension" system; I need multiple options per dimension, a list of lists.

**Comment by ReikaKalseki** [comment]
Closed due to unimplementability.
