### ISSUE TITLE
Chisel Team's Chisel 2 is not compatible

### ISSUE THREAD

**Issue by CrystalMageX** [ReikaKalseki/Reika_Mods_Issues#765]
DragonAPI [seems to only support](https://github.com/ReikaKalseki/DragonAPI/blob/087016b3e4fd2185f07e3e444453a99ab38d2c3e/ModList.java#L112) Cricket [chisel (2&3)](https://github.com/Chisel-2). It looks for `com.cricketcraft.chisel`, which has been renamed to `team.chisel` in the [ChiselTeam](https://github.com/Chisel-Team/Chisel) fork (Chisel 2). It would be nice to have support for it, because both forks seem to be equally popular according to [this page](http://ftb.gamepedia.com/Chisel).

**Comment by ReikaKalseki** [comment]
I doubt I can support both simultaneously.

**Comment by InitHello** [comment]
Damn. I use a few things from chisel2. None of them important enough to choose over ReikaMods, though.

**Comment by TomeWyrm** [comment]
ARGH. How many simultaneous forks do we NEED of that mod?!

I wish the community would pick one and use it already.

**Comment by CrystalMageX** [comment]
> I doubt I can support both simultaneously.

You can try doing handling of this specific case, and test for the classes of both forks.

**Comment by Shahelion** [comment]
Wait, which one is supported?

Cricket's is called ~~Chisel 2~~ Chisel 3. The Chisel Team one is just called Chisel. In the title you say Chisel Team's Chisel 2...which is it?

Also, what is the incompatibility?

EDIT: Apparently Cricket has taken a break from modding (and says he won't be returning to Chisel), so the Chisel Team is the updated one, for now.

**Comment by Barhandar** [comment]
Chisel Team is the actual one and has higher version to maintain compatibility. It's only "equally popular" because Cricket named it "Chisel 2" and CT went back to just "Chisel", resulting in user/modpack maker confusion.

The difference between two in _actual blocks_ is negligible, tteragg ensured it's drop-in replacement.

**Comment by ReikaKalseki** [comment]
I added the dual class search, but I get the sinking feeling the internal registries do not align smoothly. Expect more reflective errors.
