### ISSUE TITLE
Crashed Chromaticraft v12e

### ISSUE THREAD

**Issue by Steve-the-Skunk** [ReikaKalseki/Reika_Mods_Issues#768]
I am trying to run the game with this mod in the launcher called "TLauncher" at version 1.7.10, with pre-installed FML 1558. I enclosed logs errors and crash report. Help to solve the problem!
[crash-2016-04-29_20.03.05-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/242933/crash-2016-04-29_20.03.05-client.txt)
[1.7.10-Forge10.13.4.1558-1.7.10 (2016-04-29).txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/242937/1.7.10-Forge10.13.4.1558-1.7.10.2016-04-29.txt)

**Comment by ReikaKalseki** [comment]
You posted the log yet failed to read it.

**Comment by Steve-the-Skunk** [comment]
How to understand, not yet read? Excuse me, I badly speak English. ^^""

**Comment by Steve-the-Skunk** [comment]
Tell me what I can do to avoid crash client?

**Comment by redelman** [comment]
The relevant section of the log file is here:

[19:24:23] [Client thread/ERROR] [FML]: Caught exception from ChromatiCraft
Reika.DragonAPI.Exception.InstallationException: ChromatiCraft was not installed correctly:
You are running Java 8, and need to use the JVM argument '-XX:+UseG1GC' or you will suffer memory allocation-related crashes.
Note that you may have to remove other GC arguments, such as '-XX:+UseConcMarkSweepGC', which is commonly auto-specified by launchers.

**Comment by Steve-the-Skunk** [comment]
Tell me how can I do it? I do not understand this ...

**Comment by redelman** [comment]
I can't tell you how to change the java arguments in your launcher. Figure
it out yourself, or use a better supported launcher.

**Comment by Steve-the-Skunk** [comment]
I know where can enter in my launcher JVM argument. Tell me what must enter the JVM arguments?

**Comment by Steve-the-Skunk** [comment]
I thank in advance.

**Comment by ghost** [comment]
From the above log section, I'm pretty sure you need to put "'-XX:+UseG1GC" in the JVM arguments.
