### ISSUE TITLE
Flywheels freeze server and singleplayer when powered.

### ISSUE THREAD

**Issue by jakbruce2012** [ReikaKalseki/Reika_Mods_Issues#769]
I do not have a crash log for this one as it does not crash, it just permanently freezes the server and corrupts the single player world.  Test setup: Microturbine -> wooden flywheel.  Add fuel to the turbine and it locks up on the next tick.
Tested with mods:
ChromatiCraft 1.7.10 V12e
CodeChickenCore-1.7.10-1.0.7.47
DragonAPI 1.7.10 V12e
ElectriCraft 1.7.10 V12c
ExpandedRedstone 1.7.10 V12a
NotEnoughItems-1.7.10-1.0.5.111-universal
ReactorCraft 1.7.10 V12d
RotaryCraft 1.7.10 V12e

**Comment by ReikaKalseki** [comment]
#734
