### ISSUE TITLE
#76 is NOT duplicate!

### ISSUE THREAD

**Issue by walkerjonny** [ReikaKalseki/Reika_Mods_Issues#77]
See https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/76 for further comments.
Please explain it better why it got closed or have a deeper look into it and find an answer to my questions.

Although I'm not firm with Java I have long years of scripting skills because I'm working as an IT Specialist for about 20 years. So do not treat my as a stupid idiot, please.

**Comment by kolatra** [comment]
You don't need to open another issue linking back to a different issue.

**Comment by ReikaKalseki** [comment]
Also, you are the only one getting vitriolic in these issues. If you do not remain calm the discussion threads will be locked.

**Comment by ljfa-ag** [comment]
Sorry, I didn't mean to treat you like an idiot.
The error message was the same in both cases, that's why I marked it as duplicate. You can just reopen the old issue.

**Comment by coolsquid** [comment]
> Although I'm not firm with Java I have long years of scripting skills because I'm working as an IT Specialist for about 20 years.

I don't care whether you're a specialist, a beginner, or the queen of England. It's not related to the situation.

> Sorry, I didn't mean to treat you like an idiot.

You didn't.
