### ISSUE TITLE
[CC] Lumen Collection Oddities

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#770]
First of all, I somehow unlocked an expansion (the type with the expanding ring, not the type detailed below) to my internal lumen storage after discovering only two colors.

Second, collecting Karmir drains my store of Ykri, and vice-versa. Haven't found other colors in this world yet, but this makes it seemingly impossible to actually collect any.

EDIT: Ok, it seems that every time I collect Lumens, it increases my cap. I can see the number rapidly going up as I draw in more lumens, but it doesn't keep going once that color is full to my current cap. Is it supposed to do this? At this point I have 7-8 colors discovered, and just over five thousand for my cap.  With just two pylons of different colors, I could keep increasing my cap until I hit whatever limit exists.  GIF: https://i.gyazo.com/9db5d0d153583a70ac1cf52e312124b7.mp4

Also, it seems that death both clears ALL Lumens from my internal storage, and resets the cap to 24...is this intended?

**Comment by ReikaKalseki** [comment]
Read the changelog.

**Comment by TomeWyrm** [comment]
I assume you mean

V12B:
ChromatiCraft: Changed player element buffer cap mechanics
