### ISSUE TITLE
Induction Motor is Extremely loud

### ISSUE THREAD

**Issue by LogicalEnigma** [ReikaKalseki/Reika_Mods_Issues#771]
This isn't exactly a bug but I have nowhere else to ask that I know of. Sorry if this is the wrong place to ask such questions. The Induction Motor is extremely loud and quite obnoxious. I was asking to see if there was any way to configure or change this by any chance. Thank you for the awesome mod!

**Comment by redelman** [comment]
I believe you can surround it with wool to make it quieter, like you can with the other Rotarycraft engines.

**Comment by LogicalEnigma** [comment]
Well that worked. Thanks. I was still wondering if I could configure the engine sound at all?

**Comment by redelman** [comment]
I believe rotarycraft has a config option to disable all engine sounds.
Electricraft may use the same config, or have one of its own. Check the
config files. They are pretty easy to understand.

**Comment by LogicalEnigma** [comment]
Thanks. I was checking Electricraft's config and only saw the option to disable ores and was thrown off. I just checked Rotarycraft's config and saw the option to configure engine sounds and turned it down. I appreciate the help!
