### ISSUE TITLE
[CC] Fertility Bloom cannot be planted on non-vanilla farmland

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#775]
Checked GardenStuff Garden Soil and RandomThings Fertilized Dirt, both regular and tilled varieties. Given I already run a Sprinkler and have plenty of space for water blocks, this doesn't contribute to balance or challenge. I would like it to be plantable on any farmland.

**Comment by ghost** [comment]
I'm pretty sure this was fixed for v13. I do know you can place it on top of enrichment vines prior to the fix though.

**Comment by ReikaKalseki** [comment]
No, it still needs farmland or the vine.

**Comment by Barhandar** [comment]
Speaking of enrichment vines, I can't use them because I can't craft them. Presumably I do something incorrectly - but everything else I tried to craft, including same recipe group (cave lighter, fertility bloom, etc) worked fine, but vines refuse to - with runes in place and recipe seemingly correct (4 leaves, 2 flowers, Galazio crystals, piece of redstone).

**Comment by ReikaKalseki** [comment]
I have several, so I know the recipe works. Double-check that you are using the correct flower block ID (in v13, is OreDict).

**Comment by Barhandar** [comment]
> I have several, so I know the recipe works. Double-check that you are using the correct flower block ID (in v13, is OreDict).

It's not the flower issue, it's the leaf issue. It doesn't take CC leaves present on, and_shorn from trees_ (chromaticraft_block_decay), it takes chromaticraft_block_dyeleaf leaves instead (which I don't know how to obtain legitly save for reaching CC item fabrication). Replacing leaves with vanilla oak resulted in recipe working fine - regardless of flower (which is also cycling in display and OD-ed already).

**Comment by ReikaKalseki** [comment]
One may be in the OreDict and not the other, probably because 'decay' is never supposed to be obtainable.

**Comment by Barhandar** [comment]
> One may be in the OreDict and not the other, probably because 'decay' is never supposed to be obtainable.

That's true, yes. But they look and are named identically, so without a way to check OD people won't know why CC leaves don't work in CC recipe, and might, like me, not try to use vanilla leaves. I'll now check if that behavior is still present with your mods (and WAILA) only and create another issue if it is.

Bedrock shears don't care that they're supposed to be unobtainable and obtain them anyway. Less prideful shears, like vanilla and HSLA, obtain proper, OD-ed leaf blocks.

**Comment by ReikaKalseki** [comment]
Oh, is this only the bedrock shears? I will add an exception for them.

**Comment by ReikaKalseki** [comment]
Closing this as #779 encapsulates it.
