### ISSUE TITLE
[CC] Lexicon ore-dictionary ingredients keep cycling

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#776]
For example, I'm trying to read the list of ingredients for making the Crystal Brewery, but since I also have Geostrata, the list is constantly jumping around with the different types of stone, making it all but impossible to read normally. Possible ways to handle this:

1: Holding shift/sneak stops any ore-dict based cycling, or any other cycling in recipes (shards, for example). I believe this is currently the standard method used by most other mods.
2: Set a default item for all ore-dictionary-using recipes (the vanilla item, if possible), so Stone, Oak Leaves, etc. This should also solve the issue with Natura's OD Leaf thing.

https://i.gyazo.com/893dcfbf9ba37483f06131c346397a00.mp4

**Comment by ReikaKalseki** [comment]
This is neither necessary nor implementable.

**Comment by TomeWyrm** [comment]
Why not use option 2 and have a special tag that says "ore dictionary" or "or similar item" etc, in the tooltip? Because it drives me kinda batty having endlessly cycling items like that. Honestly that behavior in NEI bugs me too, but at least there I can stop the cycling so I can figure out the items used.

**Comment by ReikaKalseki** [comment]
Normally, tooltips cannot even be displayed in NEI handlers. It takes a large and painful hack to pull it off. And that does not even work for the CC lexicon.

**Comment by TomeWyrm** [comment]
Isn't this your custom Lexicon "NEI"?

**Comment by TomeWyrm** [comment]
Because any NEI handled recipe would automatically fit point 1.

Which only leaves handbook display, which you could likely code to display a set item for each oredict tag, then differentiate somehow. Tooltip, colored overlay, box, key press to cycle or stop cycle, whatever.

**Comment by ReikaKalseki** [comment]
No, I merely imitate it.
