### ISSUE TITLE
Pylon cache not cleared correctly on logout

### ISSUE THREAD

**Issue by Builderb0y** [ReikaKalseki/Reika_Mods_Issues#777]
pylonloc.dat starts as empty, and terrain for this singleplayer world has not been generated outside the explored area. Log into multiplayer, which contains pylons at locations that are NOT present in a singleplayer world, then log out again. pylonloc.dat is still empty. Log into singleplayer world, terrain is still not generated outside known area, and pylonloc.dat is still empty. However, upon logging out of singleplayer world, the pylonloc.dat file now contains the locations of all the pylons that were on the server. Logging into singleplayer again will generate terrain at all of those locations, which can freeze the game for a very long time, and can also run out of memory during this time.

"[SERVER] Logout clear" gets printed upon logging out of a singleplayer world, however this is NOT printed upon logging out of a multiplayer server, and deleting pylonloc.dat after this prevents the game from generating terrain to do block checks as expected upon logging back into singleplayer again.

**Comment by ReikaKalseki** [comment]
Now it is.
