### ISSUE TITLE
Block render event only fires in pass 1 with optifine installed

### ISSUE THREAD

**Issue by Builderb0y** [ReikaKalseki/Reika_Mods_Issues#778]
This causes ores to not render correctly with the oreclip ability active; faces will only render if they are adjacent to a transparent block, and even then will not appear at full brightness as intended.

![image](http://i.imgur.com/wXsd0ud.png)

**Comment by ReikaKalseki** [comment]
Fixed. Thanks to some positional reshuffling with Optifine, I was loading the wrong variable, canRender (booleans are integers internally).

![](http://i.imgur.com/LnjJg1y.jpg)
