### ISSUE TITLE
[CC/RoC] Bedrock Shears create block_decay itemstacks instead of block_dyeleaf itemstacks when shearing Dye Tree leaves

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#779]
"Regular" shears (vanilla, HSLA) create block_dyeleaf itemstacks as they're supposed to. I've just read that bedrock shears are supposed to drop plant itself instead of what plant's silk-touch function says, but given block_decay is unusable, it's probably an unintended consequence.

Also bedrock shears don't drop aura bloom blocks, only their dust. And bedrock "scythe" doesn't drop anything at all when breaking them.

**Comment by ReikaKalseki** [comment]
> Also bedrock shears don't drop aura bloom blocks, only their dust. And bedrock "scythe" doesn't drop anything at all when breaking them.

This is not a bug.

**Comment by ReikaKalseki** [comment]
Fixed.
