### ISSUE TITLE
Update AE api

### ISSUE THREAD

**Issue by hayesj1** [ReikaKalseki/Reika_Mods_Issues#78]
I've been struggling for a work around for this for the past few days. DragonAPI crashes on world load because the version of the applied energistics api you have is now outdated. I discovered this because a mod I was trying to add required a newer version of AE so I updated(prior to this everything was working great; besides the weird pipe rendering glitch). Then I started getting this crash log on world load:

http://pastebin.com/E5i1G0y1

My only option is too remove that new mod and revert my AE because I've gotten waaay too deep in RotaryCraft to give it up now in this world. Have you already updated the api in the dev versions and is there another workaround here?

EDIT: how do I attach labels?

**Comment by ljfa-ag** [comment]
You cannot attach labels. Only collaborators can.

Your AE2 version seems to work fine for me together with Reika's mods. Maybe it is some other mod that you have that has the outdated API. Can you reproduce that with just AE2 and RotaryCraft?

**Comment by hayesj1** [comment]
No, but this appears to b related to the autocrafting table bug post, because as soon as I add even a small AE setup and power up an autocafting table with rotarycraft power BOOM crashes. Same crash as before too.

**Comment by ljfa-ag** [comment]
Ah I see, I didn't try the autocrafting unit before. Yup, can confirm.

**Comment by ReikaKalseki** [comment]
Not an AE API version issue and already fixed before the last 75 times it was reported in the last 48 hours.
