### ISSUE TITLE
Null Stack in Rotarycraft causing crash on startup.

### ISSUE THREAD

**Issue by Cylek358** [ReikaKalseki/Reika_Mods_Issues#780]
http://pastebin.com/kLc2ewTm
Not seeing anything else in the crash report, but I'm not the best at figuring this stuff out.
Also seems to be a problem with Reactorcraft and Electricaft as both also error'd in startup.
Warning, this is a heavily modded environment, Resonant Rise 3 to be precise.

**Comment by redelman** [comment]
There is a config to disable crashing due to null-item itemstacks in DragonAPI.

**Comment by Cylek358** [comment]
if you mean
B:"Disallow Null-Item ItemStacks to Prevent Crashes"=true
Doesn't work

**Comment by redelman** [comment]
There's more sanity checking related options than just that.

**Comment by Cylek358** [comment]
I apologize, I was unsure what the sanity options were actually for.  I just saw the option for the null-stack and thought that was the only option.
I get this error when performing Sanity Check: http://pastebin.com/KqLgjhQb
And Attempting repair fails.
