### ISSUE TITLE
1xtile.blockWoodenDevice@0 causing crash

### ISSUE THREAD

**Issue by Cylek358** [ReikaKalseki/Reika_Mods_Issues#781]
I was getting a nullstack crash on launch, sanity check yielded : http://pastebin.com/KqLgjhQb
Any attempt to repair environment sanity failed.  Don't know if its actually related to your mods, but i didn't have a problem until installing them.  So i figured you might know how to fix it.

**Comment by ReikaKalseki** [comment]
I believe that to be a ThaumCraft item, but read the message.
