### ISSUE TITLE
[Feature Request] [Chromaticraft] World Rift AE2 connectivity

### ISSUE THREAD

**Issue by eqdanteon** [ReikaKalseki/Reika_Mods_Issues#786]
I know that this can be done with the AE2 quantum network bridge but I was wondering if it would be possible to allow the world rift to carry an ae2 network for a more compact solution.

Thanks,

**Comment by ReikaKalseki** [comment]
I highly doubt it - AE tends to like requiring everything extend core AE classes. That said, I can look.

**Comment by ReikaKalseki** [comment]
["Not possible", with no elaboration or followup](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2268#issuecomment-218807068).

**Comment by TomeWyrm** [comment]
Yueh is like that. He probably doesn't want you implementing a replacement for the QNB, so he's telling you it's not possible.

**Comment by ReikaKalseki** [comment]
I am not enamored enough with the idea to have the motivation to jump through hoops and play "guess whether I am lying or not" with people who are neither helpful nor responsive.

**Comment by Aivech** [comment]
@TomeWyrm [Someone already did](https://bdew.net/ae2-stuff/)

> Wireless Connector – close range quantum bridge alternative

**Comment by TomeWyrm** [comment]
And Reika said the AE2 stuff code did not help him implement the world rift functionality :-)
