### ISSUE TITLE
Chromaticraft Portal Death

### ISSUE THREAD

**Issue by eqdanteon** [ReikaKalseki/Reika_Mods_Issues#788]
It seems like most times landing on the edge of the portal blocks even when flagged for the dimension results in a "fell from a high place" death.  I am unsure if this is expected behavior or not.

Thanks,

**Comment by ghost** [comment]
If you have ExU installed you can use an angel ring (or any other fall damage prevention item from a mod.)

**Comment by Builderb0y** [comment]
You're definitely going to need some form of fall protection if you plan on going to the chroma dimension.

**Comment by eqdanteon** [comment]
Its not the arrival in the dimension that is the problem.  It is making contact with the side or the top edges of the portal blocks that causes a falling damage death.

**Comment by Builderb0y** [comment]
The portal blocks actually give LESS fall damage than entering the dimension does (simulated fall height of 500 blocks, as apposed to 1000 blocks when entering the dimension), granted they do apply it constantly so it can stack. Still, it was intended to throw the player out of the portal if they fail to enter, but that currently doesn't work either.

**Comment by ReikaKalseki** [comment]
This is even if you have the required progression?

**Comment by Builderb0y** [comment]
Won't matter if you have progress if you not intersecting with the center block, the 8 around it will still deny entry since the structure check technically fails for them.

**Comment by eqdanteon** [comment]
My experience has been that even if I complete the required progression for the dimension any contact with the portal blocks other than the center one results in an immediate falling damage death message.

**Comment by ReikaKalseki** [comment]
I just fixed the kickback. Now working on the side checking.

**Comment by ReikaKalseki** [comment]
I think this will work:

```
@Override
public void onEntityCollidedWithBlock(World world, int x, int y, int z, Entity e) {
    for (int i = 2; i < 6; i++) {
        ForgeDirection dir = ForgeDirection.VALID_DIRECTIONS[i];
        int dx = x+dir.offsetX;
        int dz = z+dir.offsetZ;
        if (world.getBlock(dx, y, dz) != this) {
            int ddx = x-dir.offsetX;
            int ddz = z-dir.offsetZ;
            this.onEntityCollidedWithBlock(world, ddx, y, ddz, e);
            return;
        }
    }
```
