### ISSUE TITLE
Rock Melter melts Petrotheum Dust into Aerotheum fluid and doesn't work on Aerotheum Dust

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#789]
Tested on latest RoC plus latest CoFHCore (3.1.2-325) and Thermal Foundation (1.2.3-112), without Thermal Expansion/Thermal Dynamics.

Both Cryotheum and Pyrotheum work as expected.

**Comment by ReikaKalseki** [comment]
Well, this one was a dumb mistake.
