### ISSUE TITLE
Suggestion: Thinner pipes

### ISSUE THREAD

**Issue by clubpetey** [ReikaKalseki/Reika_Mods_Issues#79]
Allow me to propose a change to your pipes. I fully admit to having a low-grade OCD, but when build out my systems, it bugs me that the pipes in RotaryCraft don't connect right. This can be seen most dramatically when connecting a lubrication pipe to a standard gear box. The outline of the pipe rises above the mount's side walls and the glass texture seems to poke in past the mount.

My suggestion would be to shrink the "Diameter" of the pipes to the size of your steam pipes or TE's fluiducts. The little "bumps" like TE has I don't think are necessary though. I know its a purely aesthetic thing, but I think it will make the larger systems look a lot better.

Thank you for listening to my suggestion and keep up the great work.

-p

**Comment by ljfa-ag** [comment]
I think thinner pipes have been suggested and rejected before.
However, the pipes' glass texture projecting into the block it connects to doesn't look very good indeed.

**Comment by ljfa-ag** [comment]
So yeah, Reika responded at MCF:

> They
> are wide to keep up with the throughput. The glass thing is actually a
> bug, but a minor render bug is unlikely to see a fix soon.

**Comment by ReikaKalseki** [comment]
The pipes' size is not going to change, but the render bug may be fixed once all the other higher-priority things are....do not hold your breath.

Also, this issue tracker is for bugs only, not suggestions or requests.
