### ISSUE TITLE
Packet overload with CC

### ISSUE THREAD

**Issue by dabaer** [ReikaKalseki/Reika_Mods_Issues#793]
I'm having a slight issue with Chromaticraft clients overloading the server with packets (according to the interpretation of a user from Technic's discord).

Here's the stack:
https://gist.github.com/dabaer/8e3f351941db0456e42277169aa6b545

It seems to happen to clients that both have and have not done anything with chromaticraft, but i'm not sure if its an odd configuration or what. This just started happening after we removed Chococraft, but again there is no noticeable correlation there.

Please let me know if you need more of the stack (that was everything that did not appear normally in the tick stack and took a lot longer than everything else to run).

Regards,
Jadenn

**Comment by dabaer** [comment]
Oh as per what I was also asked in the technic discord was that it happens to two different clients, with at most 4 on the server at one time, and I see no evidence of external connections outside of those 4 causing these packets.

**Comment by ReikaKalseki** [comment]
I have no idea what I am looking at, but removeFromPlayer for abilities should not be continuously called.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by dabaer** [comment]
Ah yeah, it was just copy pasted output from WarmRoast, wasn't sure what the best way to express it was.
