### ISSUE TITLE
Rotarycraft flywheel causes server hang

### ISSUE THREAD

**Issue by Kreidos** [ReikaKalseki/Reika_Mods_Issues#794]
Whenever a flywheel is used, it causes the server to hang indefinitely. CPU usage remains at 100% and java must be killed manually.

Discovered in the latest Revolution2 pack. (Running v12e)

Steps to reproduce: 
1. Use a flywheel.

P.S. No log output to show, as the server and client just hang, and do not generate log or console output.

**Comment by Haggle1996** [comment]
Looks like duplicate of #734

**Comment by Kreidos** [comment]
So it does;  I don't know how I missed that one when I looked. Closed.

**Comment by ReikaKalseki** [comment]
And #769
