### ISSUE TITLE
Chromaticraft Lumen Beacon Transmitters extremely slow

### ISSUE THREAD

**Issue by snapx** [ReikaKalseki/Reika_Mods_Issues#797]
As there is no solution in the forum, I'm trying it here:

Only Chromaticraft and DragonAPI installed via curse launcher, nothing else:
forge 10.13.4.1.1558 (also tried it with the newest forge version)
Chromaticraft 1.7.10 V12e
DragonAPI 1.7.10 V 12e
Default configs

However, in the hope to make the problem more obvious, this world is imported from another mod pack where the problem originally occured.

Lumen Beacon 1 with transmitter at 1011, 100, 436, conected to a max empowered pylon via 3 repeaters 
Lumen Beacon 2 with transmitter at  1065, 88, -111, connected to a max empowered pylon via 3 repeaters

After placing a storage crystal charger at the base of one of the two towers, the color of the pylon next to this tower is being fully charged within seconds (at a rate of more than 10k lumen per second), while the connection occours through the multiaura repeater at the base of this tower. As these are empowered pylons, I can repeat this procedure multiple times without any difference in charge rates.

At the same time, while there is a visible lumen beam between the two towers, charge rate is only about 20 (!) lumen per second for the color of the pylon that is connected to the respectively opposite tower, and after about 40 seconds, this beam disappears for only a few seconds.

So no matter what I do, the connection through the beacons is extremely slow, and I observed the same thing, using two different towers in this world.

If orthogonality would be the cause, I'd expect there to be no connection at all. And if this is not a bug in chromaticraft (as Raika seems to believe, and which I am in doubt of), it obviously is a problem that occurs within chromaticraft. So what could be the cause? Maybe some kind of world corruption or something about java? Anything I could have done wrong?

**Comment by ReikaKalseki** [comment]
Again, the broadcaster has the highest throughput of any repeater. Something else is your bottleneck. Also, their high attenuation, paired with a comparatively low throughput on the "main" repeaters, can worsen this.

Turbocharge both the pylon and the normal repeaters.

That said, 20L/t is bit much for this. Something else is probably involved.

**Comment by snapx** [comment]
I don't get it. How could there be a bottleneck, if not within the towers, when even the multiaura repeaters at the bottom of the towers have a throughput of 10 k per second? Shouldn't I expect this to work in a normal, not turbocharged setup? I guess then I'll forget about the towers and make a long line of repeaters instead.

**Comment by ghost** [comment]
Correct me if I'm wrong but based off of the cords of both lumen beacons it sounds like they aren't orthogonal to each other. Which makes it so that those two shouldn't connect at all.

**Comment by snapx** [comment]
Thanks for trying to help! Basically, this is true, but Reika also said in the forum, that they don't have to be exactly orthogonal, and they in deed do connect. This especially makes it possible to fit the at least a little bit into a given landscape. Just to be sure, a reported the coordinates here.
If such a configuration would be critical, I also would expect the mod to give me some feedback about that, maybe by not connecting at all.

**Comment by ghost** [comment]
You're pretty lucky then. Whenever I attempt to use lumen beacons one always fails to connect to the other. Basically there's a "sending" and "receiving" beacon (wanted to test meteor towers far away from an area and not use the creative pylon). The sending one gets the... signal from the repeater below it but the receiving one doesn't get the sending transmitter OR the repeater below it (which I connected to a pylon to see if it was something in between the two.) Doesn't make sense how one connects and the other doesn't. I also did actually line them up exactly and the other is built right as it lights up the transmitter with the repeater particles.

**Comment by snapx** [comment]
This sounds very diferent to what I have observed. My 4 towers in the original world are in a (only almost orthogonal) L-shaped configuration, with 3 towers on the long side of the L. 

It doesn't matter to which tower I connect the charger, always all colors are filled, and afaics, this always works at the same time for both directions, but always so slow for the colors that are connected through the beacons. I woudln't exactly call this lucky;).

Meanwhile I testet it with the update, but still the same problem.
