### ISSUE TITLE
Minecraft crash when Crystal Pylon attacked

### ISSUE THREAD

**Issue by Alrena** [ReikaKalseki/Reika_Mods_Issues#798]
I loaded into my world, went exploring, and quickly discovered a green Pylon nearby. I heard the distinct noise of it attacking and then minecraft promptly crashed with this crash log:

[https://gist.github.com/Alrena/fcd3ea8bc56a9504c512fa7385690fb0](https://gist.github.com/Alrena/fcd3ea8bc56a9504c512fa7385690fb0)

**Comment by ReikaKalseki** [comment]
This looks at first glance like the PotionEffect ASM failing, but that worked for over a year now without issue. Try removing mods. Also, giving potions will trigger this, not just pylons.

**Comment by Alrena** [comment]
I tried removing mods from the pack until it worked again. Apparently once I started re-adding them a few potion ID conflicts came up. No idea why they didn't appear before. On the bright side though that fixed it, thanks for the help!
