### ISSUE TITLE
Incompatability between ElectriCraft and FullThrottle Alchemist

### ISSUE THREAD

**Issue by Alrena** [ReikaKalseki/Reika_Mods_Issues#799]
When attempting to load a custom mod pack with Rotary, Electri, and Chromaticraft along with FullThrottle Alchemist I found that the mod pack consistently crashes when loading with this crash log:

http://pastebin.com/bRu9QDJh

I immediately looked to report it to FTA, since that's the mod showing that it has an issue, but when checking for an existing bug report I found this: http://forum.ftamod.com/viewtopic.php?f=5&t=75

I found it extremely odd that the person reported that it was specifically ElectriCraft causing the crash in conjunction with FTA, but I tested it myself and the mod pack immediately works once ElectriCraft or FTA is removed. It can't possibly be malicious code, since why would it ever be included in a side mod instead of Dragon API, and the issue is odd enough that I thought I would report it to you so that many it'll get fixed in some way

**Comment by ghost** [comment]
Although I have no idea why the incompatibility is happening, I do know that it isn't malicious code. Might be something Electricraft adds causing it to crash.

**Comment by ReikaKalseki** [comment]
This is the API classloading issue again. Add the BC API to the DragonAPI jar.
