### ISSUE TITLE
Sack people leaving bad bug reports or hate mail.

### ISSUE THREAD

**Issue by zerotheliger** [ReikaKalseki/Reika_Mods_Issues#8]
Yeah

**Comment by coolsquid** [comment]
Not really a mod bug.

**Comment by TomeWyrm** [comment]
Also I am actually trying to figure out how to do that right now.

**Comment by coolsquid** [comment]
They will be banned as soon as I figure out how.

**Comment by Kolatra** [comment]
You cannot actually ban people from a repository.

**Comment by coolsquid** [comment]
Doesn't matter. We'll handle them. Report them to GitHub.

**Comment by TomeWyrm** [comment]
https://help.github.com/articles/blocking-a-user/

Actually as long as Reika does it, we can.
