### ISSUE TITLE
Exception walking around EnderForest

### ISSUE THREAD

**Issue by clubpetey** [ReikaKalseki/Reika_Mods_Issues#80]
Just created a new world and was walking around the EnderForest I spawned into and got the following.  I thought it might be an issue with FastCraft, but I have several other worlds with FastCraft and ChomatiCraft and do not have this issue.  Let me know if you need anything else.

MC 1.7.10
Forge 10.13.3.1408
ChromatiCraft v6f
Moderator edited post to remove full crashlog and put on pastebin:
http://pastebin.com/zVqJER83

**Comment by ReikaKalseki** [comment]
Something tried worldgenning ExR blocks. What did you _do_?

**Comment by clubpetey** [comment]
Nothing special that I know of, I generated 10-12 more worlds after that error, about 4-5 of them crashed with a similar error.  Maybe I have a block ID conflict? but I thought those are caught during startup.

I HAVE been messing around with the BiomeTweeker mod.  I'll remove that and see if that's the cause.

**Comment by ReikaKalseki** [comment]
Any more info?

**Comment by clubpetey** [comment]
No, I've created more worlds and not been able to re-create this issue.  I've upgrade my version of BiomeTweaker, so that may have been the cause.  Everythis looks good now.
