### ISSUE TITLE
v13 server NoClassDefFoundError

### ISSUE THREAD

**Issue by SvEgiiVEteR** [ReikaKalseki/Reika_Mods_Issues#800]
https://gist.github.com/5a8d8edfbbc8e165312d3c6fc9832f67
this crash occurs if I delete
Farseek-1.0.11.jar
Streams-0.2.jar very strange
v12 works

**Comment by ghost** [comment]
Hmm, is that the streams that added the cave rivers? If so then the modpack I play on hasn't updated streams and I do have v13. It's either something in streams broke one of Reika's mods for v13 or vice versa.

**Comment by SvEgiiVEteR** [comment]
@HyperionNexus Yes it is this mod Streams
very strange that removing it occurs crash.
and of course it helps remove Reika''s mods
in 12 of these no problem. I have removed\added other mods during tests.

**Comment by Barhandar** [comment]
Does removing ExpandedRedstone (and only it) fix the crash?

**Comment by SvEgiiVEteR** [comment]
@Barhandar I think it will help.. but I returned 12 version... so don't check..
I left DragonAPI 1.7.10 V13a.jar only and everything was OK

**Comment by Barhandar** [comment]
Because it's saying that ExpandedRedstone is checking for _unobfuscated_ version of the class, which it shouldn't.

**Comment by ReikaKalseki** [comment]
This looks like a reference of clientside code - EntityFX, the particle parent class - on a server. But you made no mention of a dedicated server, and though I added the Particle Filter to ExR in v13, it has been working fine on our server.

**Comment by SvEgiiVEteR** [comment]
@ReikaKalseki Yes, dedicated server.
I will try then find a mod, which maybe is causing the problem(I now have another problem, how to solve,search will start)
but with version 12, everything was OK

PS
Oh, those conflicts.. not understand,when a combination of mods causing the problem(( 
have to look for them, sometimes 2 days or more

**Comment by ReikaKalseki** [comment]
Fixed.
