### ISSUE TITLE
Chromaticraft error log after upgrading to v13a

### ISSUE THREAD

**Issue by eqdanteon** [ReikaKalseki/Reika_Mods_Issues#801]
After upgrading to V13a Chromaticraft started to fill the server log with lines similar to the following:

[Server thread/ERROR] [FML]: CHROMATICRAFT ERROR: ID Reika.ChromatiCraft.Block.BlockCrystalTileNonCube@6cfee813 and metadata 0 are not a valid tile identification pair!

Thanks,

**Comment by ReikaKalseki** [comment]
I [warned you](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=27431) in advance. You ignored that warning.

**Comment by eqdanteon** [comment]
I apologize - i read the change log not the forum.
