### ISSUE TITLE
[ChromatiCraft] Crash when trying to open Chromic Lexicon while sneaking

### ISSUE THREAD

**Issue by 3TUSK** [ReikaKalseki/Reika_Mods_Issues#802]
[Crash report](https://gist.github.com/3TUSK/fdeafae7e00544d88ac4b4ef81dfea44) is here. 
I am using ChromatiCraft v13a with Forge 10.13.4.1558, Mekanism 8.1.9, FlaxbeardSteamPower 0.29.2, NEI 1.0.5.118. 
ChinkenCHunks, Chisel, Carpenter's Block, Storage Drawers and Thaumcraft are also present.  
Before crash I took the following screenshot:
![image](https://cloud.githubusercontent.com/assets/9113033/15165064/0669d1ac-16e1-11e6-8425-17d61d9cdeaf.png)
Crash happened when I was opening my lexicon so that I could put new research fragment in. I have tried twice, and both of them resulted in the same crash.
The world I am playing is probably created with ChromatiCraft v10.

**Comment by ReikaKalseki** [comment]
Already fixed.
