### ISSUE TITLE
DragonAPI is trying to register an empty ASM transformer

### ISSUE THREAD

**Issue by CrystalMageX** [ReikaKalseki/Reika_Mods_Issues#803]
Your [ASM Handler](https://github.com/ReikaKalseki/DragonAPI/blob/c0ee610610678c3e06a6b104dcb0a3ede65909a1/Auxiliary/DragonAPIASMHandler.java#L72) is returning an empty string (`return "";`). `cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(LaunchClassLoader, String, File)` has a `null` check, but it does not have a empty string check. This leaves an error in the log.

Note the space at the end of lines 52 and 53 in the [log](https://gist.github.com/CrystalMageX/57814f8e6d24d7ffcb3dbf0f6d345d60#file-gistfile1-txt-L53).

**Comment by ReikaKalseki** [comment]
Fixed.
