### ISSUE TITLE
[ChromatiCraft] Crash when upgrading Sami Energy Storage Crystal

### ISSUE THREAD

**Issue by 3TUSK** [ReikaKalseki/Reika_Mods_Issues#808]
[Crash report](http://paste.ee/p/4t8wc) here. Using ChromatiCraft v13b.
Steps to reproduce:
1.I am trying to crafting the next level energy storage crystal:
![c056663b-1eee-475a-8080-e8a7234eaef9](https://cloud.githubusercontent.com/assets/9113033/15232450/55fec486-186f-11e6-8b5b-ee4083a91d43.png)
Detailed information:
![2016-05-12_18 25 38](https://cloud.githubusercontent.com/assets/9113033/15232473/7da0499c-186f-11e6-851f-40aa351b34eb.png)
2.Add two resonant dust to complete recipe.
3.Game crashes when opening casting table at this time. IIRC it didn't crash in previous version.

I crashed my game three times. However it doesn't affect real casting, as shown below:
![2016-05-12_18 37 14](https://cloud.githubusercontent.com/assets/9113033/15232666/c7123e7c-1870-11e6-8cc0-655ae7d63152.png)
Also the result is normal:
![2016-05-12_18 37 42](https://cloud.githubusercontent.com/assets/9113033/15232668/cdf8c29c-1870-11e6-8c03-d4311273f32f.png)

But, if I put ingredients on casting stands first, and put storage crystal last, [game will crash as will](http://paste.ee/p/K63AN).

**Comment by ReikaKalseki** [comment]
Fixed.
