### ISSUE TITLE
Cave Crystals and Pendents giving negative effects in Over world.

### ISSUE THREAD

**Issue by nmarshall23** [ReikaKalseki/Reika_Mods_Issues#809]
I tested this with just Chromaticraft and Dragon API installed, Cave Crystals give their negative effects in the Overworld. They do the same in the nether.

However back to my modpack, in the Twilight Forest they give the positive effects. But still giving negative effects in the Overworld and Nether.

I have not checked any other dimensions.

**Comment by 3TUSK** [comment]
#806 ?
