### ISSUE TITLE
NEI & RotaryCraft '/ by zero' Crash

### ISSUE THREAD

**Issue by NaggingGullible** [ReikaKalseki/Reika_Mods_Issues#81]
Resources and Information:
Crash Report: http://pastebin.com/LaEtpXAL
Image of my mods folder:
![1 7 10 mods folder](https://cloud.githubusercontent.com/assets/4163802/7943794/7dd6166a-092c-11e5-9b3b-67025786f523.png)
Video of it Occuring: http://youtu.be/qZPd4-dEe7Y (sorry for the mumbling, I need to work on that)

Description:
I am playing in a survival world, and am using NEI for recipes and such. I noticed (due to accidentally left-clicking it,) that when you try to use it to view the recipe (if there even is one, I am not that well versed in your mod at the moment, as I installed it either yesterday or the day before) for item #5526/165, titled 'Cobalt Slurry' (and possibly others, I have not tried, although I by chance have found that it does not crash when I attempt to do the same item #5525/99, titled 'Ruby Flakes.) I believe that it is a problem with the interaction between RotaryCraft and NEI, and is occurring due to an error in the former, and, as such, I am considering this to be an issue to be posted here, as opposed to wherever NEI issues go. If I am incorrect, I will gladly move it.
.                                                                                                                         Many Thanks,
                                                                                                                                    NaggingGullible

**Comment by 1Matthias** [comment]
Already known and fixed in the next version, in fact this was one of our first bug reports.

**Comment by NaggingGullible** [comment]
Sorry... I guess since it was one of the first, I didn't see it. I only thought to look through the issues on here. Oops.

**Comment by 1Matthias** [comment]
#10 #68 #36 There was another, but that was deleted by what we suspect was a troll. It appears to be the single most common issue on here.

**Comment by NaggingGullible** [comment]
I'm gonna leave before I dig myself any deeper down this hole. Thanks for putting up with me.

**Comment by 1Matthias** [comment]
It is perfectly fine. You were reasonable, provided plenty of information, and did not instantly want a fix, so...
