### ISSUE TITLE
ReactorCraft: Radiation entities spawning for no apparent reasons

### ISSUE THREAD

**Issue by Fatmice** [ReikaKalseki/Reika_Mods_Issues#812]
1.7.10-V13b

Per issue.  The test reactor is spawning radiation entities in and round the reactor components.  This is not supposed to happen to a well shielded reactor.  I've witnessed this occurring so far in the Overworld and the Nether.  No doubt the Void will be similarly affected.
![Side view of reactor](http://i.imgur.com/eR2yOi3.jpg)
![Crown view of reactor](https://i.imgur.com/BuBx5y2.png)

**Comment by ReikaKalseki** [comment]
It looks like they are spawning in the CPU.

**Comment by ReikaKalseki** [comment]
By the looks of it, CPUs were not made transparent to neutrons.
