### ISSUE TITLE
ReactorCraft: Thorium core does not allow removal of Nuclear waste out of west/east/north/south face through Steve's Factory Manager's Inventory Cable

### ISSUE THREAD

**Issue by Fatmice** [ReikaKalseki/Reika_Mods_Issues#813]
1.7.10-V13b

Nuclear waste can only be removed through Nuclear Waste Duct.  Please allow interfacing with Steve's Factory Manager's Inventory Cable.

**Comment by ReikaKalseki** [comment]
I excluded mod piping for a reason. Like with the fusion plasma, nuclear waste pipes ensure you cannot route it to a void.

**Comment by Fatmice** [comment]
I know you are paranoid about people voiding your wastes.  But like the item waste, which can be pulled with mod piping, isn't there a more amicable solution to this so that I can use the Inventory Cable?  Otherwise, the thorium design is rather limited in layout since two sides must be used, bottom side to handle hot lifbe and one side to handle waste.  This leaves only 3 sides to interface with other reactor components.  Thus thorium cores can only be placed on the periphery and not packed together.  If packed together, there must be a final layer below them to service waste and hot lifbe.

You have very a knee-jerk reaction to many things.  It is not logical.

**Comment by ReikaKalseki** [comment]
> Otherwise, the thorium design is rather limited in layout since two sides must be used, bottom side to handle hot lifbe and one side to handle waste. This leaves only 3 sides to interface with other reactor components. Thus thorium cores can only be placed on the periphery and not packed together.

This was intentional, as otherwise a thorium reactor could be a big block of cores with nothing else, with none of the traditional "tiling design".

**Comment by Fatmice** [comment]
What tiling the design? Thorium cores can not be tiled and must only be on the periphery.

You can not for instance design this without additional, non contributing bottom layers of T's
TTTFTTT
TTTFTTT
FFFCFFF
TTTFTTT
TTTFTTT

Only this sort of design would work without extra non-fissioning bottom layer of T's

TTTTTTT
TFFFFFT
TFFCFFT
TFFFFFT
TTTTTTT

The latter has 20 Ts vs 24 Ts of the former and uses 4 more fission cores.  Not to mention, the former is ugly looking due to additional non-contributing bottom layers.

T=Thorium cores
F=Fission cores
C=CPU

**Comment by ReikaKalseki** [comment]
> Thorium cores can not be tiled and must only be on the periphery.

...Why?

**Comment by Fatmice** [comment]
If tiling meant something like this, then no it is not tilable.

FTFTFTF
TFTFTFT
FTFTFTF

Such structure has Ts that has no where for waste to go without an extra bottom layer of Ts.  Unless of course you modify it to this

FTFTFTF
TFTWTFT
FTFTFTF

This of course works, but looks damn ugly from the top.

**Comment by ReikaKalseki** [comment]
By tiling I mean any mixed arrangement, not an explicit alternation.
