### ISSUE TITLE
Ender IO/Chromaticraft Compatability issue.

### ISSUE THREAD

**Issue by Cylek358** [ReikaKalseki/Reika_Mods_Issues#815]
Ender IO and Chromaticraft cause a server crash on launch with the log: http://pastebin.com/CZC2jtcD
This issue exists on the latest versions of both mods, but only on the server, clientside/single-player works fine.
Chromaticraft V13b
EnderIO-1.7.10-2.3.0.425_beta

Also wanted to apologize for my earlier stupidity with V12e.  Turns out that nonsense was an out of date forestry.

**Comment by Builderb0y** [comment]
This is on [ender IO's end](https://github.com/SleepyTrousers/EnderIO/issues/3298).
