### ISSUE TITLE
Crash bedrock pickaxe

### ISSUE THREAD

**Issue by 3mia** [ReikaKalseki/Reika_Mods_Issues#816]
Hello, when I open NEI I get crash
Crash log
https://justpaste.it/u8rk

**Comment by Barhandar** [comment]
>    at caveworld.item.ItemMiningPickaxe.func_77624_a(ItemMiningPickaxe.java:687)

Report it at CaveWorld's issue tracker as well. [The line in question](https://github.com/kegare/Caveworld/blob/master/caveworld/item/ItemMiningPickaxe.java#L687) - I suspect they're making assumptions they shouldn't.

**Comment by ReikaKalseki** [comment]
Something is very, very wrong. The function throwing the error is this:

```
@Override
public String getItemStackDisplayName(ItemStack is) {
    return ItemRegistry.getEntry(is).getBasicName();
}
```

Which can NPE if the item is not an RC item (getEntry returns null). However, in such a case, the function should not even be called on my class, but whatever class represents the item in question.

Looking at their code, the ItemStack supplied is coming from Forge/vanilla for addInformation, which _should_ be correct. I suspect something has been corrupted in the ID map. Does this happen in a new world?

**Comment by Barhandar** [comment]
Not limited to RoC.

```
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at Reika.ChromatiCraft.Base.ItemChromaBasic.func_77653_i(ItemChromaBasic.java:117)
    at caveworld.item.ItemMiningPickaxe.func_77624_a(ItemMiningPickaxe.java:687)

java.lang.NullPointerException: Rendering screen
    at Reika.RotaryCraft.Items.Tools.Steel.ItemSteelPick.func_77653_i(ItemSteelPick.java:109)
    at caveworld.item.ItemMiningPickaxe.func_77624_a(ItemMiningPickaxe.java:687)
```

Loaded new world in creative with your mods and Caveworld, placed CW pickaxe into hotbar, pointed at different pickaxe, crash. Crash is guaranteed whenever I point at specific pickaxes in CW creative tab.

It seems like CW is trying to create an "advanced pickaxe" thing with regular pickaxes as "bases", but cannot handle your pickaxes for whatever reason. The name return part is to specify base in "advpick" description. It also cannot fetch the icon, but it defaults to stone pick for it.

**Comment by 3mia** [comment]
Thanks for the effort guys. I tried to contact Caveworld owner, but no answers so far

**Comment by ReikaKalseki** [comment]
@Barhandar So then it appears the issue is that he is trying to wrap my items in his. Yes, this is ...well, not _wrong_, in the sense of "should have known not to do", but will never work with my items. He needs to add some sort of exception.

**Comment by Barhandar** [comment]
> but will never work with my items. He needs to add some sort of exception.

Can your items have some sort of property that means "cannot be wrapped" in case you add more tools, so the other mod doesn't have to exclude per-item?

**Comment by ReikaKalseki** [comment]
He would need to add an API interface or something. There is no such property in vanilla.
