### ISSUE TITLE
[Website] Licensing - broken link

### ISSUE THREAD

**Issue by amesgen** [ReikaKalseki/Reika_Mods_Issues#817]
just for information: on your [Licensing-page](https://sites.google.com/site/reikasminecraft/licensing), the link in "Used Terms" to http://www.minecraft.net/copyright.jsp is broken, as minecraft.net got a major update some time ago.

**Comment by ReikaKalseki** [comment]
I have no idea what the new link is...

**Comment by Duckfan77** [comment]
Might this be it? https://account.mojang.com/documents/minecraft_eula
Under the Content heading it appears to mention what is being referenced within the licensing page.

**Comment by ReikaKalseki** [comment]
That is it. Fixed.
