### ISSUE TITLE
ChromatiCraft: Game freezes on opening screen.

### ISSUE THREAD

**Issue by Logan-H** [ReikaKalseki/Reika_Mods_Issues#818]
The second forge finishes loading up, minecraft freezes.
Using the most up to date version of DragonAPI and ChromatiCraft.
Fresh minecraft install with no other mods.
No crash log, simply says "Not Responding" and stays open into I close it.

**Comment by ReikaKalseki** [comment]
Did you run out of memory? Did you wait for more than 30 seconds? [Are you using BigMobs](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/795)?

**Comment by Logan-H** [comment]
I don't think that I ran out of memory, I have 8GB and have not ran into issues before.
I am currently giving minecraft 4GB.
I waited for around 5 mins.
I am only using DragonAPI and ChromatiCraft.

**Comment by Logan-H** [comment]
I have been playing Revolution 2 which includes both mods with no issue.
This only happens when using the normal minecraft launcher.

**Comment by Barhandar** [comment]
Check the end of the actual game log, instance/logs/ftb-client-latest.log.

**Comment by Logan-H** [comment]
Ok it looked like it was attempting to download something and my internet was down.
I launched it today and it worked, sorry about that.

**Comment by ReikaKalseki** [comment]
If it were down entirely, it would not have tried. Your internet was up...just stupidly slow.
