### ISSUE TITLE
Reika's mods crashing recipes 

### ISSUE THREAD

**Issue by 3mia** [ReikaKalseki/Reika_Mods_Issues#819]
Once again I'm with my problems... :D 

Hi,
I have created my own modpack and I had no issues until I set up hosted server. I want to mention that all the mods, and NEI was working when I tested them on my PC server. But when I got host and started a server, whenever I tried to see recipe through NEI, I get crash. Please help!

Crash log

https://justpaste.it/u9hk

P.S when I took out your mods (expanded redstone, rotarycraft, electricraft, dragonapi, reactorcraft), the problem was solved.
Although I must have your mods in my modpack!!! They're must have. So please help me :D

**Comment by ReikaKalseki** [comment]
Try removing mods.

**Comment by 3mia** [comment]
It works without your mods, although I rly want them in my modpack :/

**Comment by ghost** [comment]
Try removing other mods then. Or you could start with Reika's mods and add the rest until it crashes.

**Comment by implayin** [comment]
try downgrading ae2 to rv2-10

**Comment by 3mia** [comment]
I will do that as soon as I have free time, thanks

**Comment by notchriss** [comment]
Try removing and/or updating Railcraft and/or deleting Railcraft's config for it to generate anew. I had a similar problem with similar crash log and this was what solved it. Not sure if it's the same problem but it's worth trying, as long as you have Railcraft at all, of course :)

**Comment by ReikaKalseki** [comment]
Anything?

**Comment by 3mia** [comment]
I apologize, but I am really not in a mood to search where's the problem, I have exams, so I have to put this away for now. As soon as I have some free time I will try to check where's the problem tho. Although I could send you mods/configs if you're curious. But myself I have no mood and time for it. Sorry! I hope you understand me Reika <3

**Comment by ReikaKalseki** [comment]
I imagine exams are now over; most people are saying as much.

**Comment by TomeWyrm** [comment]
For some schools they are indeed. For others maybe not.

Could you send your mods LIST and an archive of your configs (redistributing mods is often against their licenses). Except Reika's mods, those I'll need a copy of. I'm betting I don't have a backup of that version :-p
