### ISSUE TITLE
Chromaticraft pools of ender not able to pump

### ISSUE THREAD

**Issue by renakitsune** [ReikaKalseki/Reika_Mods_Issues#82]
HI Reika, enjoying your mods so far, using the ReikasWrath FTB modpack with extras added like IC2,Thermal expansion etc, all mods that can interact with yours mainly.

I cam across the pools of ender and with thermal foundation installed, you cannot pump using Buildcraft or the Rotarycraft pump, the only pump that works is the one from IC2
WAILA is showing me <unnamed> chromaticraft, though when I bucket it it turns into a bucket of resonant ender from TE which if i replace in a new space, it can be pumped.

I know its quoted "If Thermal Expansion is installed, its resonant ender is used instead of the one native to Ender Forest." on your website.

Is it intended for it not to be able to be pumped or is this a bug, either with yours or with TE?
I want me ender pearls :)

**Comment by renakitsune** [comment]
ps. all mods are updated to the latest

**Comment by ljfa-ag** [comment]
Did you add Thermal Foundation to an already existing world? Afaik it will not replace the fluid when it was already generated in the world.

**Comment by renakitsune** [comment]
No i added the mods at the start and loaded up a new world, still the pools are show as                   unnamed -chromaticraft and only pumped by the IC2 pump.

**Comment by ReikaKalseki** [comment]
The pump is working for me, and the fluid names in the registry match.
![](http://i.imgur.com/spDzhyw.png)
