### ISSUE TITLE
AC engine/Flywheel causing the game to freeze

### ISSUE THREAD

**Issue by maliciousbloke** [ReikaKalseki/Reika_Mods_Issues#820]
Confirmed in versions 12e and 13a.  

Approaching an AC electric engine with a charged shaft core when it's connected to a flywheel, in turn connected to a bevel gear, causes the game to freeze.

Client log included although it looks to have stopped writing when the client locks up.

[Log.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/264641/Log.txt)

**Comment by ReikaKalseki** [comment]
#769, #734
