### ISSUE TITLE
DragonAPI and fast craft

### ISSUE THREAD

**Issue by 31trainman** [ReikaKalseki/Reika_Mods_Issues#822]
Im getting this in my console upon doing some digging in creative mode in my custom modpack http://pastebin.com/XLw8EyhC

mod list
http://pastebin.com/UMGkDQCt

forge 1416
minecraft 1.7.10
Java 8 update 91
Mac OS X 10.11.4

**Comment by ReikaKalseki** [comment]
Known, probably unfixable (packet fragmentation), and breaks nothing.
