### ISSUE TITLE
Crash on World Load, trying to render TC wand focus

### ISSUE THREAD

**Issue by implayin** [ReikaKalseki/Reika_Mods_Issues#824]
Had this crash on world loading after I upgraded to V13. It looks to me like ChromatiCraft is crashing because it fails to render a TC focus

Crash Report:
http://pastebin.com/BDxVF0cv

**Comment by ReikaKalseki** [comment]
It looks like you tried to put the Aura Cleaner on a wand focus. That should be impossible, and nothing on my end does it.
