### ISSUE TITLE
Crash report connected with DragonAPI

### ISSUE THREAD

**Issue by MrAmazoni** [ReikaKalseki/Reika_Mods_Issues#826]
http://pastebin.com/cCeRTpvr
Can somebody help pls.

**Comment by ReikaKalseki** [comment]
"EC3", whatever that is, is sending null particles to the effect system. Though I can cull them, this is a bug on their end.

**Comment by TomeWyrm** [comment]
The mod with this issue is Essential Craft 3. Just for anyone curious.
