### ISSUE TITLE
weird texture and crash GeoStrata 1.7.10 V13a

### ISSUE THREAD

**Issue by drago87** [ReikaKalseki/Reika_Mods_Issues#827]
I enconterd this error when i tried placing a "Coal Ore Granite" on normal minecraft stone after i noticed that some of the textures on it was weird in the world but worked in the inventory and NEI

Crash Report: http://pastebin.com/qPEjyBwj
Mod dump: http://pastebin.com/g2faaz9R

This is what it looked like
https://www.dropbox.com/s/fz8e137y31ozgg8/2016-05-17_00.43.02.png?dl=0

I'm also trying to change most of the normal minecraft stone to Geostrata stone and have it banded.
I've enabled the Banded Generation setting and set the Ore Mode to 1

i've also changed the rock band heights to values betvene 25-60 but not sure how its suposed to work.
Any pointing in the right direcktion is appricieted (both the crash if its your mod or another and the config settings)

**Comment by ReikaKalseki** [comment]
GeoStrata ores are only partially implemented, and disabled by default for a reason. And the crash is unrelated, and probably unfixable.
