### ISSUE TITLE
kcauldron crash

### ISSUE THREAD

**Issue by leytilera** [ReikaKalseki/Reika_Mods_Issues#828]
at the kcauldron support they said, that this is a dragonapi crash: http://pastebin.com/WAmZsKp9

**Comment by ljfa-ag** [comment]
KCauldron is currently not supported. There are arguments going on between Reika and the KCauldron developers, it seems like there will be no solution until they come to a settlement.
See #523, #658, #823

**Comment by ReikaKalseki** [comment]
And 
#541 #657 #621 #538 #493 #375 #139

**Comment by TomeWyrm** [comment]
There will be no solution unless it's on their end fixing their code. Especially because the dev was complete and total ass to Reika, and gave false/useless information.
