### ISSUE TITLE
Resistor is ignored unless black/black/black

### ISSUE THREAD

**Issue by notchriss** [ReikaKalseki/Reika_Mods_Issues#829]
![2016-05-17_20 52 49](https://cloud.githubusercontent.com/assets/8706925/15333211/75944996-1c71-11e6-9c8e-f948885fdfbe.png)

If I color it anything else than black/black/black, it does not limit amperes at all.

Electric meter is there just for screenshot purposes, I first noticed the issue with no Electric meter at all.

**Comment by ReikaKalseki** [comment]
The limit is per-path, not in total. Each path in that system has less than 80A.
