### ISSUE TITLE
Hydrogen Preheater takes 15-20 minutes real-time to heat-up?!

### ISSUE THREAD

**Issue by alextarbox** [ReikaKalseki/Reika_Mods_Issues#83]
I recently watched your youtube video on how to build this fusion reactor, followed it to the T, but I noticed that when heating the preheater from "room temp" or 32C, up to 150 million C, took me literally almost 20 minutes to heat up. 

I'm doing all this testing in creative mode, and used the same parts as in the youtube video, the heatray attached to the industrial coil creative mode, and gave it a "jet engine's" worth of power. That seems a bit ridiculous for it to take THAT long to heat up. I can understand 2 to 3 minutes to fully heat up, maybe even 5 minutes considering just how hot it has to get, so it's not like it just "instantly" heated up 150 million degrees, but 15 to 20 minutes is way too long.

Not sure if this is a glitch or bug or simply the way the code was wrote.

**Comment by ljfa-ag** [comment]
The code (if I read it correctly) and some math suggest that it should take about 11 minutes, assuming your tickrate is 20 per second. If it takes longer then your server is probably lagging.

Not sure if these values might be too high, considering that you only need to wait that duration once and that building the fusion reactor takes some time so you likely can do somethig else while it heats up. But I'll leave that here in case Reika wants to take a look at the values.

**Comment by ReikaKalseki** [comment]
This is intentional.
