### ISSUE TITLE
Viewing some Chromaticraft recipes in Lexicon and/or NEI crashes the client

### ISSUE THREAD

**Issue by notchriss** [ReikaKalseki/Reika_Mods_Issues#830]
http://pastebin.com/17f4y5pw

As far as I can tell, all the crashing recipes contain items with missing textures. I.e. when you can use many different kind of leaves, they are constantly changing until the leaves with no texture come up, and then crash. I understand the items themselves are not from your mods (apparently from Natura in this particular crash case), but is it possible to make it not to crash anyway? :)

**Comment by ReikaKalseki** [comment]
They need to not register broken items. Same as #530, #660, #690
