### ISSUE TITLE
Update Notifications & Thaumcraft Warp

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#831]
Bringing back an old issue, where having any amount of Thaumcraft Warp whatsoever would cause Chromaticraft notifications to black out the whole screen, it also happens with the messages that a mod is out of date. Makes it nearly impossible to click the X to close it, or to see what mod even has an update (this time it's Reactorcraft, which has a seemingly useless update just to increment the version number).

**Comment by ghost** [comment]
I haven't experienced the black screen issue w/ warp. I have heard of other people getting it but I have been lucky apparently.

**Comment by Shahelion** [comment]
Well, the one with Chromaticraft notifications was apparently fixed, but this is separate, with the update notifier.

**Comment by ReikaKalseki** [comment]
The popup system does not even modify GL state...

**Comment by ReikaKalseki** [comment]
I looked at my code again. I do nothing special, and this has to be a shader issue.

**Comment by TomeWyrm** [comment]
Disable Thaumcraft shaders. Just do it. They've caused SO many bugs. Not quite as bad as the heat block in RC, but it's still 'useless feature that breaks stuff". They're neat the first time, and obnoxious the rest of it.
