### ISSUE TITLE
[CC] Non-stacking Transmissive Dust

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#832]
I have two separate stacks of Transmissive dust that refuse to combine together. One has additional NBT data:

ChromatiCraft:chromaticraft_item_tiered:5.withTag({tooltip: 1 as byte})

Looking at NEI recipes, the untagged dust can be obtained from Chromaflora and the crystal bees, but the tagged dust can only be obtained from the bees. I have only three dust that is untagged, and 72 with this mysterious tag.

EDIT: Clarity.

Additional EDIT: It seems that Ball Lightning drops the tagged dust, while the Radiance Bushes drop the untagged dust.

**Comment by ReikaKalseki** [comment]
The "tooltip" tag is a technical one, intended to only be used for rendering in the lexicon. Are you sure you got them from bees? I have bees running with no such splitting.

**Comment by Shahelion** [comment]
No, NEI says the tagged one can only be obtained from bees, while the untagged one can be obtained from both bees and Radiance Bushes. I have obtained 72 untagged from bushes, and 3 tagged ones from killing Ball Lightning. I have no bees set up yet. I guess the real issue here is that Ball Lightning drops the tagged dust.

**Comment by 1skandar** [comment]
I've seen this too, occasionally across all Chronaticraft items. It's usually only a handful at a time. I'll investigate and see if I can trigger it reliably.

**Comment by ReikaKalseki** [comment]
Ball lightnings reference the global reference ItemStack `ChromaStacks.beaconDust`. I suspect this is another reference modify issue.

**Comment by ReikaKalseki** [comment]
[I found it](http://i.imgur.com/whtlGpJ.png).

**Comment by ReikaKalseki** [comment]
@1skandar, do not waste your time. The trigger is probably opening the lexicon (which renders the "transmitting energy" fragment for the first time and glitching the NBT). It is also fixed.
