### ISSUE TITLE
[CC] Lumen Turrets cause sky to flicker

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#833]
Every pulse the turret sends out causes the sky to become completely blank grey for a fraction of a second, not very long, but very noticeable, especially when repeatedly firing.

**Comment by ghost** [comment]
Is it possible for you to get a screenshot of when it happens?

**Comment by ReikaKalseki** [comment]
And does this happen with no other mods (especially mods like Optifine)?

**Comment by Shahelion** [comment]
I don't have Optifine. I do have an idea of what may be causing it, though...

**Comment by ReikaKalseki** [comment]
And that would be...

**Comment by Shahelion** [comment]
Complicated, but it may not be your mod causing it after all. I'll re-open it if my guess turns out to be incorrect.
