### ISSUE TITLE
ChromatiCraft V13b and EnderIO 2.3.0.425 Server Crash

### ISSUE THREAD

**Issue by MarshallOutlaw** [ReikaKalseki/Reika_Mods_Issues#834]
To explain the situation (Not at all) briefly-

I'm creating a modpack, and it's not my first rodeo, I've been doing this since 1.2.5. But, this time I'm doing it for a group of people larger than 5, so I don't want to muddle through this issue by myself, as I usually just work through it on my own when time doesn't matter as much. The mods present in the crash report attached are the exact mods I've been playing with, minus several removed mods over time and except for the versions of ChromatiCraft and EnderIO present. Previously I was using ChromatiCraft V12e, and EnderIO 1.7.10-2.2.8.381. I've been playing privately on a server for the past month, figuring out what mods are redundant, and which ones to narrow down to a more stable pack. I logged in for the first time in a week, a couple of days ago (Finals), and it told me I should update ChromatiCraft. I put it off till I was done for the night, then I updated to v13b. With that, I also talked to my friend the next day and we eliminated 20 mods from the previously larger collection, and the client ran fine. I thought nothing of the server- but we spent all day today trouble shooting it, and for a long while I was getting an EnderIO crash- but that made no sense to me, since all I did was take out 20 mods, and update ChromatiCraft. So I updated EnderIO to 1.7.10-2.3.0.425, and that stopped telling me a vague tick issue with EnderIO and presented me with the crash below. 

This, for one, confirmed it was a CC issue, but when I looked it up, #804 seemed to express the same sort of crash log but the only advise was to update to v13b, which, uh, obviously doesn't help me much. Removing EnderIO does also fix the issue, so that seems to additionally confirm it. I don't know whether to wait for a EnderIO update or a ChromatiCraft one, but, something that I assume V13b was supposed to fix, didn't fully stick apparently.

Tl,dr; Updated CC to v13b in a previously working pack, which causes a server crash only solvable by deleting Enderio (Latest Release and Beta both tested).

Crash Report: http://pastebin.com/kvzukK04

**Comment by ReikaKalseki** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/3298
