### ISSUE TITLE
mod idea

### ISSUE THREAD

**Issue by jellybeanflames** [ReikaKalseki/Reika_Mods_Issues#835]
game of thrones you can be like the different kingdoms if your dothraki your strong but vulnerable to fire and if your targaryan your fireproof and if you like to be subversive and things you can be jon snow itll be so cool

**Comment by ReikaKalseki** [comment]
WTF?

**Comment by Kolatra** [comment]
Now, what would the purpose be for the Jon Snow characteristics? You gave good reason for Dothraki, and Targaryen, but we need a full page essay on why being Jon Snow in Minecraft would be a worthy quality.

**Comment by TomeWyrm** [comment]
Kolatra... didn't anyone tell you not to feed the trolls? ;-)
