### ISSUE TITLE
EnderIO 2.2.8 + Chromaticraft 13b ExceptionInInitializerError

### ISSUE THREAD

**Issue by MineWitherMC** [ReikaKalseki/Reika_Mods_Issues#836]
This crash doesn't happen without CC nor it crashes without EIO. And it's not the same as plenty of closed CC/EIO issues.
http://codepad.org/SsSzIBKJ

**Comment by ghost** [comment]
Duplicate of #834 #815.

EnderIO is the problem. You do have a different crash but if you're not using 2.3 beta then that might be why it appears different. 

Here's the issue Reika made on EnderIOs tracker: [EnderIO tracker](https://github.com/SleepyTrousers/EnderIO/issues/3298)
