### ISSUE TITLE
ReactorCraft: Unprocessed Nuclear Waste -> Centrifuge -> Nothing

### ISSUE THREAD

**Issue by Fatmice** [ReikaKalseki/Reika_Mods_Issues#837]
ReactorCraft 1.7.10V13b

Spinning unprocessed nuclear waste in a centrifuge does nothing.  It neither transforms the waste nor consumes it.

**Comment by ReikaKalseki** [comment]
I found the problem:
![](http://i.imgur.com/QgLUbTl.png)

**Comment by ReikaKalseki** [comment]
Kind of a crappy fix, but it is fixed as best as I can.

**Comment by Fatmice** [comment]
Oh? What was the problem and how did you fix it?  I didn't think the odd rendering was a problem.

**Comment by ReikaKalseki** [comment]
The issue was that the Centrifuge was essentially saying "not enough empty slots to run recipe". I made it ignore that if there were more than 9 output items and the output slots are all empty, under the assumption that the chance of having 10 or more items all at once is too low to care about.
