### ISSUE TITLE
ReactorCraft: Spent Fuel Container spawning radiation entities when properly shielded

### ISSUE THREAD

**Issue by Fatmice** [ReikaKalseki/Reika_Mods_Issues#838]
ReactorCraft 1.7.10V13b
Per title.
![2016-05-19_01 51 34](https://cloud.githubusercontent.com/assets/8956281/15385017/4bb35f6a-1d64-11e6-8921-e3d088385cfd.png)

**Comment by ReikaKalseki** [comment]
Is this the drum or the short-lived one?

**Comment by ReikaKalseki** [comment]
If the latter, fixed.

**Comment by Fatmice** [comment]
The ones that house the short lived stuff.  The radiation entities spawn right next to them.

**Comment by ReikaKalseki** [comment]
Then yes, it is fixed. The problem was that they were intercepting neutrons.
