### ISSUE TITLE
ReactorCraft: Nuclear Waste Disposal Drum not stacking similar waste

### ISSUE THREAD

**Issue by Fatmice** [ReikaKalseki/Reika_Mods_Issues#839]
ReactorCraft 1.7.10V13b
Per title
![2016-05-19_01 55 26](https://cloud.githubusercontent.com/assets/8956281/15385091/cde7fe32-1d64-11e6-903b-f96f25035d85.png)
![2016-05-19_01 55 29](https://cloud.githubusercontent.com/assets/8956281/15385092/cdeada8a-1d64-11e6-8d68-d66f7d0d3943.png)

**Comment by ReikaKalseki** [comment]
[Both waste types work the same](https://github.com/ReikaKalseki/ReactorCraft/blob/master/Base/TileEntityWasteUnit.java#L113). I remember changing this a long time ago.

**Comment by Fatmice** [comment]
Interesting, so you changed it again. =P

**Comment by ReikaKalseki** [comment]
"Again"? I remember this being changed because stacking the waste amplified the radiation/heat effects of the parent tiles.

**Comment by Fatmice** [comment]
Well, if stacking is not desired, I can tell you it is still stacking.  You just have to remove some for things to filter down and as they do they will start to stack.

Stacking the waste also lowers the chance for them to decay since decay chance is not evaluated per item in a stack but only per stack.

**Comment by ReikaKalseki** [comment]
Wait...it is still stacking, and ignoring IInventory rules?

**Comment by Fatmice** [comment]
Yep, would you like a picture? :smile: 

Stack is no more than sixteen items though, like before.

**Comment by ReikaKalseki** [comment]
Wtf...yes, post an image.

**Comment by Fatmice** [comment]
Here's some.  To get them to stack you just have to remove some waste to make room.  As they filter down, they will start to stack.
![2016-05-19_23 24 19](https://cloud.githubusercontent.com/assets/8956281/15417226/06443930-1e19-11e6-9e81-432937500038.png)
![2016-05-19_23 25 01](https://cloud.githubusercontent.com/assets/8956281/15417227/07f568da-1e19-11e6-92c1-33b66dfefbd9.png)

Eventually, you end up with this
![2016-05-19_23 21 13](https://cloud.githubusercontent.com/assets/8956281/15417238/1bdb6ed0-1e19-11e6-9b5e-cda8bf9df17e.png)
![2016-05-19_23 21 19](https://cloud.githubusercontent.com/assets/8956281/15417237/1bdacc00-1e19-11e6-9e5a-4577768ae64d.png)

This is opposite of what you want.  The behavior that you want is of a spent fuel container where stacking is not possible.  Though to be fair, the waste storage container was for long term.  Waste in these containers do not decay significantly during game play if at all, even under acceleration.  At their current storage size, they are too small.  I suggest you at least quadruple their storage to make up for their lack of stacking...The long-lived wastes build up rather quickly and with only 12 slots per drum you need a lot of drums very fast.  With each drum eating 10us, 100 of them would be eating 1ms.  This is not a stretch of the imagination.  No wonder people like to store your waste in the ME hard drives or void them all together.  It's more tick friendly, no hard feelings.

The alternative is something that I've suggested before.  Make the waste useful, i.e. nuclear batteries, or transmute them with neutron beam bombardment generated by accelerator driven system.  What's all that power you make in the fusion reactor for?  Use it to drive a synchrotron to generate a proton beam and smash it against heavy nuclei source to make the neutron beam to transmute long-lived waste with a chance of turning into something that's more likely to decay within the lifetime of the game.  This latter is not only more fun but feels less overbearing.

The alternative, since I highly doubt you will be willing to do all of that work, is make tile accelerator work super efficient against waste with long half lives.  Instead of a flat 256x, make it scale against the waste such that all wastes that go into the storage drums will decay at the same rate as Cesium-137.  This means the longer the half-lives, the more effective the tile accelerators.

**Comment by ReikaKalseki** [comment]
I cannot reproduce the stacking behavior unless the stack being put in is of a size greater than one. Also, the code seems to imply that they were meant to stack after all, at least to 16.

And I cannot performantly combine different stacks of similar waste. That means iterating over the entire inventory for every slot in the inventory (144 comparisons per tick).

**Comment by Fatmice** [comment]
Well it originally would stack to 16 for each slot.  At least that is how I remembered it about V7 for 1.7.10.

**Comment by ReikaKalseki** [comment]
And it will if you place it manually, or use item automation. But feeding cannot do so performantly.
