### ISSUE TITLE
Rendering Glitch: Hydrogen Preheater Upper Housing

### ISSUE THREAD

**Issue by alextarbox** [ReikaKalseki/Reika_Mods_Issues#84]
When placing the magnetic pipes too close to the upper part of the housing, it messes up the rendering but it does not actually prevent it from functioning normally.

I just left the pipes away from the housing but for someone that wants or needs to run pipes immediately along the preheater housing, may be annoyed by this issue.

![2015-06-04_00 36 12](https://cloud.githubusercontent.com/assets/12375616/7985625/052ae540-0aa0-11e5-8417-f150a57a1d8e.png)
![2015-06-04_00 36 20](https://cloud.githubusercontent.com/assets/12375616/7985624/0529a478-0aa0-11e5-9bf4-1f05d7c5e244.png)

**Comment by ReikaKalseki** [comment]
Fixed.
