### ISSUE TITLE
ReactorCraft: Crash while smacking HP-Turbine steamline with Transducer

### ISSUE THREAD

**Issue by Fatmice** [ReikaKalseki/Reika_Mods_Issues#840]
Per title
https://gist.github.com/Fatmice/5b644a83ddd4b0d96c2d8feed7ad014e

Unrecoverable.  Game will crash when loaded.  Good thing it's only a test world.

**Comment by ReikaKalseki** [comment]
WTF?

**Comment by redelman** [comment]
Wtf is right. I can do this all day long without any problems.

**Comment by Fatmice** [comment]
Indeed.  I don't know why it happened.  Test world had nothing but Reika's stuff and some steve's factory manager.

**Comment by ReikaKalseki** [comment]
Is this repeatable?

**Comment by Fatmice** [comment]
If I can recover world, I'll see if I can smack the steam line again to see if it crashes. =P
If you mean repeatable as in build another test world and see if it crashes again...hard to say.  Seems pretty random.  Although I do have another test world that also crashed, it was testing the control rod issue.
