### ISSUE TITLE
Tryng to make Electricraft ores compatible with Strata

### ISSUE THREAD

**Issue by lightning02** [ReikaKalseki/Reika_Mods_Issues#841]
Hello Reika, I'm writing on your Github because I had some problem tryng to add a 'compatibility' from Electrictraft to another mod called Strata.
This mod makes the stone harder to mine gradually while you go deeper in the ground, changing the texture too and making them darker.
Anyway, even adding the ID-name of your ores the config generate an error and wont load, can you help me to understand what I'm doing wrong? Or how could I fix this in order to make it worker? Or at least what could do the Strata's owner to raise a compatibility?
This is my last try with electricraft;
![840a729320cf77335d879ddb7e35a20eda4ad72e3f694f2056 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/15420599/f7c9e51c-1e6d-11e6-9e37-7f2c3ac87f7b.png)
This is the thread from Strata: https://github.com/blueyu2/Strata/issues/1#issuecomment-220496122

**Comment by ReikaKalseki** [comment]
I have absolutely no idea, and I have never before heard of Strata.

**Comment by lightning02** [comment]
In the end I managed to resolved with the Strata author, my fault being silly ^^
