### ISSUE TITLE
Reactorcraft: HTGR does not heat up properly in certain cases.

### ISSUE THREAD

**Issue by Kowalskicore** [ReikaKalseki/Reika_Mods_Issues#842]
Some HTGR designs which should work do not heat up beyond a certain threshold, thats all.

Minecraft: 1.7.10
Forge: 10.13.4.1614
DragonAPI: v13b
Reactorcraft: v13b
Rotarycraft: v13a

Screenshots uploaded to imgur for convenience: http://imgur.com/a/rhKGp

(my first bug report on github, so if anything is missing or if i did something wrong please do tell me.)

**Comment by Kowalskicore** [comment]
Imgur link doesnt seem to work, heres the plaintext URL: http://imgur.com/a/rhKGp

**Comment by ReikaKalseki** [comment]
Those are all counted as one reactor - were they not the original 8-core cells would not function - and having depleted fuel in a core does not impede it.

**Comment by Kowalskicore** [comment]
I'm quite confused why the reactor 'units' seperated by 1 block all count as a single reactor, but I guess I'll just deal with it.

Thanks for the information though, now I at least know what I did wrong. (hopefully)
