### ISSUE TITLE
Ore-Finding Pickaxe Doesn't "see" harder ores from Reasonable Realism

### ISSUE THREAD

**Issue by RaineAndrews** [ReikaKalseki/Reika_Mods_Issues#844]
https://github.com/Draco18s/HarderStuff/issues/20

If you have time, could you provide assistance/insights/random hilarity as to how the pickaxe "sees" ore?  Thaumcraft ore's are seen just fine.  I suspect it has something to do with the block having 15ish different states (15 seperate hard ore come out of the ore block before it breaks)

**Comment by TomeWyrm** [comment]
It most likely means that the ores aren't in Reika's registry. He rightfully relies a lot upon reference-able code in DragonAPI. Makes writing code much easier and more extensible. Which is unfortunately the extent of my ability to help :-(

**Comment by ReikaKalseki** [comment]
Tome is entirely correct. And this cannot be reasonably done from my end.

**Comment by Haggle1996** [comment]
@ReikaKalseki, is there an API in DragonAPI I could plug into to add these ores programmatically from my end? And if so, I assume it's in compliance with your terms?

**Comment by ReikaKalseki** [comment]
RC's API has an Extractor hook, but it would not work with other registries. The problem is that even if you managed to add them directly, with something like EnumHelper, it would error out on generating things like flakes in RC.

**Comment by Haggle1996** [comment]
Ah, gotcha. Thanks for the reply.
