### ISSUE TITLE
Curse launcher - dragonapi not linked as required dependency to other Reika mods

### ISSUE THREAD

**Issue by jco2641** [ReikaKalseki/Reika_Mods_Issues#847]
Now that the mods are published to curse (which I wholeheartedly thank you for - assembling a pack in the curse launcher is _so easy_)  I noticed that adding RotaryCraft, Reactorcraft, etc to the selected mods does not automatically select DragonAPI.  I know this is a feature curse supports - other mods correctly include their required core-mods.  I imagine its some kind of metadata on the curse site.
I didn't notice it was missing until I tried to launch the pack the first time, since I'm used to dependencies being included automatically.  It'd be a nice-to-have, and hopefully this is an easy fix.

**Comment by ReikaKalseki** [comment]
Links are per-file, not per-project, and I am not relinking it every time I reupload a file.
