### ISSUE TITLE
Chromaticraft: crash when using the Casting Delegate

### ISSUE THREAD

**Issue by Chrondeath** [ReikaKalseki/Reika_Mods_Issues#848]
I created a Casting Delegate and initially set it directly on top of my casting table (and saw pylon beams charge it with energy).  After reading up some on it, it sounded like it needed to be placed higher in the air, so I removed it using a silk touch pickaxe and placed it higher.  Everything I've attempted to craft through it so far (by clicking the green icon; I assume that's how to start crafting) has produced the following crash.

[http://pastebin.com/rhSF43Qt](http://pastebin.com/rhSF43Qt)

**Comment by ReikaKalseki** [comment]
Fixed.
