### ISSUE TITLE
Should Regeneration Pendant affect Mobs too?

### ISSUE THREAD

**Issue by nmarshall23** [ReikaKalseki/Reika_Mods_Issues#849]
I find it's really hard to kill mobs with my boosted Regeneration Pendant is that intended?

**Comment by ReikaKalseki** [comment]
Yes, or use a purification gem.

**Comment by TomeWyrm** [comment]
All the pendants apply their effects. Some are beneficial to you, some to the mobs.

**Comment by ReikaKalseki** [comment]
More exactly, pendants carry their effects on hitting mobs.
