### ISSUE TITLE
Reactorcraft Centrifuge FPS lag

### ISSUE THREAD

**Issue by Demosthenexx** [ReikaKalseki/Reika_Mods_Issues#85]
Reactorcraft 6e.

My base FPS is already very low, I get 14-16 FPS consistently. Activating a centrifuge to make fuel drops it to 6-8. No big increase in chunk updates, I assume this is render only.

**Comment by Demosthenexx** [comment]
Wow. I've got four screenshots, but have to share.

When I looked at the profiler I saw FastCraft was in the hooked functions called. So I removed it. My game went from about 15 FPS in my base to ONE FPS.

I think this isn't really Rotarycraft's issue, MC 1.8 adds the render updates.

All four included for completeness.

http://imgur.com/LP9o0Cw

http://imgur.com/aB8eTVL

http://imgur.com/s6b9QEH

http://imgur.com/gNqi2oR

**Comment by ljfa-ag** [comment]
I would guess testing it on an already laggy late game world isn't very representititve. I still don't see why activated or deactivated centrifuge would make much difference for the FPS though.

**Comment by Demosthenexx** [comment]
I disagree. It's like the reactor neutron lag, if the problem only exists when the machine or item is active, then it's related. I tried to reproduce it in my main base with and without fastcraft. Perhaps I should repeat it in our test server.

**Comment by ljfa-ag** [comment]
Yeah go ahead and do that. I wasn't quite sure how to interpret your findings.

**Comment by zemerick** [comment]
Not something I can really help with, but I did want to point out that your first 2 pics are the same. Different links, so I think you just accidentally uploaded the same image twice.

**Comment by ReikaKalseki** [comment]
Your profiling data suggests a chunk rerender is causing the issue (which was the issue with the changing-power-input and more recently, the heat ray FPS issues) but there is no such code in the centrifuge.

**Comment by ReikaKalseki** [comment]
Also, I cannot reproduce this.
