### ISSUE TITLE
[Chromaticraft] [Crash] Shift Clicking item when in Item Mover GUI causes crash

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#850]
So I found this one out when messing around with the mod in creative as I don't know much about it, when doing so I found the item mover and before reading the instructions, I attempted to shift-click an item into the tool and got a crash.

Crash Report: https://paste.ubuntu.com/16627270/

**Comment by ReikaKalseki** [comment]
Fixed.
