### ISSUE TITLE
[Chromaticraft] [Crash] Breaking Cloaking Beacon Causes Crash

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#851]
sooo.... Crash report is here: https://paste.ubuntu.com/16627398/

And the video will explain the rest (btw when it stops is just when the game crashes): 
[Minecraft 1.7.10 5_22_2016 8_11_41 PM.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/276765/Minecraft.1.7.10.5_22_2016.8_11_41.PM.zip)
This is unedited footage, may not be the best as it was recorded with Microsoft's Game DVR

**Comment by ReikaKalseki** [comment]
Fixed.
