### ISSUE TITLE
Dragonapi and recipes from other mods

### ISSUE THREAD

**Issue by 31trainman** [ReikaKalseki/Reika_Mods_Issues#852]
Im noticing this error in my multimc console for a custom modpack I'm building not sure if it breaks anything but id figure id report it just in case  http://pastebin.com/UHGcWZxH

Mod list:  http://pastebin.com/ss7RbZ2k

Lastest DragonApi, rotary craft and reactorcraft
Forge 1614 mc 1.7.10
Java 8 update 91
Mac os x 10.11.4

**Comment by ReikaKalseki** [comment]
Read it.
