### ISSUE TITLE
Molten Corium Textrue wrong

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#853]
My nuclear power plants is exploded, then suddenly I found this:
![1](https://cloud.githubusercontent.com/assets/17511838/15470331/a177a520-2122-11e6-8aa5-d981fe49e923.png)

**Comment by ReikaKalseki** [comment]
It used to work, and I do not recall changing anything. Is this v13?

**Comment by ghost** [comment]
I can confirm that this happens in v13b

**Comment by ghost** [comment]
YES, my dear @ReikaKalseki , it happens in v13b.

**Comment by MineWitherMC** [comment]
Can also confirm this. Corium doesn't have the texture when placed.

**Comment by leonbaronick** [comment]
Confirmed in V13b: 
![2016-05-25_21 04 02](https://cloud.githubusercontent.com/assets/17071279/15552983/4a520c62-22bd-11e6-993d-12753eb7b4bf.png)

**Comment by redelman** [comment]
It looks like only the texture for the flowing blocks is missing.

**Comment by ReikaKalseki** [comment]
Fixed.
