### ISSUE TITLE
Nullpointer when opening Fluid Crystallizer

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#855]
hi,
I just had my game crash when I opened the gui of a fluid crystallizer. This does not happen every time. I was holding a diamond pickaxe in my hand and the fluid crystallizer was in the progress of making ice.
http://pastebin.com/AHfsKmJa

E: not 100% reproduce able, but happens quite often.

**Comment by ReikaKalseki** [comment]
The trace is entirely vanilla code, and has nothing to do with the block being clicked.
