### ISSUE TITLE
[RoC] Two Aluminum Ingots?

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#856]
One is from smelting aluminum dust, and the other is from aluminum flakes. The flakes one also is MUCH more costly in terms of CC's Crystal Smelting (25/10/50 compared to 100/40/200 (per ingot)).

**Comment by ReikaKalseki** [comment]
It is doubled, unlike the dust.

**Comment by Shahelion** [comment]
But do the ingots need to be two entirely separate items?

I get that there are two different recipes for Aluminum, and that one is doubled, but even considering that doubling, one is much more expensive to Crystal Smelt than the other, and can't they just smelt into the same ingot?

**Comment by ReikaKalseki** [comment]
They are generated different ways.

**Comment by Shahelion** [comment]
I get that there are two different ways to make aluminum ingots. But the question remains, why have two different ingots for the same metal within the same mod? Do they serve different purposes?

Just to make it clear, I'm not confusing one with the Aluminum Alloy Ingot.

**Comment by TomeWyrm** [comment]
He raises a good point. The reason we have an ore dictionary is because seperate mods couldn't rely upon each other's ingots. They should reasonably be equivalent (and many now are) but it was a technical problem.

A mod producing two ingots that are the same for all intents and purposes except their method of generation seems a bit wasteful unless there's something the dust versions do that the flake versions don't... or visa-versa.

**Comment by ReikaKalseki** [comment]
They are both autogenerated, and have different purposes.

**Comment by Barhandar** [comment]
There's also this thing when both redstone/lapis byproduct, and one of the stages of aluminum processing share same name. Maybe change the former's name to something else like alumina?

And no, for the _player_ they serve identical purpose, only creating confusion. They're only different for you, the developer.

**Comment by TomeWyrm** [comment]
What can one type of aluminum do that the other cannot?

**Comment by ReikaKalseki** [comment]
Normally, the dust from the extractor is the only thing that can be used to make silicon and aluminum alloy.

**Comment by Shahelion** [comment]
That's the dust though. If it's only for making the alloy then why does it also smelt into it's own normal aluminum ingot?

**Comment by ReikaKalseki** [comment]
That ingot dates from when it was the only aluminum.

**Comment by TomeWyrm** [comment]
think I know the gist. The dust and flake chains are generated via different processes. Nearly the entire extractor chain is auto-generated... Is there an easy way to link the dust to the extractor ingot for smelting? Basically make it one-way equivalent to the flakes?

**Comment by ReikaKalseki** [comment]
No.

**Comment by ReikaKalseki** [comment]
No.
