### ISSUE TITLE
Chromaticraft (6f) crystal pylon weirdness, bug or not?

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#86]
soo.... when I get near one of those things, the thing just blinds me with the whole screen being an intense shade of the color of the pylon.... not sure if its a bug or intentional as I am still learning about the mod's mechanics however when viewing some spotlights I never saw this happen. here is the madness I deal with:

P.S.: since you may not support optifine, this was run without it, infact here is the mod list I used to test this:

Chromaticraft
Rotorycraft
(the core mods for the above)
NEI and its core

![2015-06-08_21 03 44](https://cloud.githubusercontent.com/assets/8153290/8050495/abf8e388-0e22-11e5-9a1c-3ebb55071d1e.png)
![2015-06-08_21 03 38](https://cloud.githubusercontent.com/assets/8153290/8050496/aca011da-0e22-11e5-8638-64cf981c1ce3.png)
![2015-06-08_21 03 32](https://cloud.githubusercontent.com/assets/8153290/8050497/ade52ce2-0e22-11e5-8253-46f86faad3b1.png)

**Comment by ljfa-ag** [comment]
Those spotlights were probably a bit older. Yes this is intentional.

**Comment by ReikaKalseki** [comment]
No, this is not intentional. This is caused by graphics memory overflow and can be fixed with a config in v7.

**Comment by Zedrimar** [comment]
ohhh ok... I guess its because of my older PC that everything's acting up.

**Comment by Zedrimar** [comment]
@ReikaKalseki do you know of any way that I can disable this at all as of 6f before v7? I really don't want to get rid of this awesome mod and if I am underneath one of the pylons and its blinding me, disasters can occur.

**Comment by ReikaKalseki** [comment]
You can edit the aura-bar-half image in the /Textures folder. Halve its size.

**Comment by Ianaver** [comment]
oh and can I compile the github version if that doesn't work for my self?

**Comment by Zedrimar** [comment]
@ReikaKalseki I halved it, but all attempts had no results... I edited all of the aura pictures but it still blinded me, I guess I will just wait for the next release... or maybe @skyboy can help...

**Comment by ReikaKalseki** [comment]
By 'halve' I meant on each dimension, cutting the image data by 75%.

Also, why would you ping skyboy here? This is not his problem nor do I expect this to be something he can help with, given the fundamental issue is a GPU one.

**Comment by Zedrimar** [comment]
@ReikaKalseki I did "halve" it both vertically and horizontally. Skyboy knows quite a bit about GPUs, that's how he fixed my issue with TE since it was a problem with the way that my GPU processes processes images among other things, so instead of posting the right image my gpu would replace the image with a white box or a box of another color.

oh well it doesn't really matter, I guess I will just wait it out for the next release and reinstall the mod then :)

**Comment by Zedrimar** [comment]
@ReikaKalseki I also tried removing the textures entirely but something even weirder happened! :P 

![2015-06-13_12 46 38](https://cloud.githubusercontent.com/assets/8153290/8145773/d786d5f4-11ca-11e5-9608-d337d8c8e1c9.png)

**Comment by ReikaKalseki** [comment]
No, that is a "missing texture" texture. Why did you think removing the texture entirely would help?

> instead of posting the right image my gpu would replace the image with a white box

That is the issue here too.

**Comment by Zedrimar** [comment]
@ReikaKalseki idk, I just did it for the heck of it. I have done some pretty strange stuff and still achieved results in the past :P 

Can I compile the github version and compile it from there? That way I can just use the config option and disable it for now since the whole system is just being weird

**Comment by kolatra** [comment]
That would be a LOT of effort on your part, and I'm speaking from experience.

**Comment by Zedrimar** [comment]
@Kolatra  the compilation from git versions? That I know, but I really like the mod, I have compiled mods from source before and I am getting desperate since I REALLY want to be able to use the mod without the whole "blinding" gift by my old and strange GPU....

I can live without that special affect until I can build my custom pc I just want to be able to play....

**Comment by ReikaKalseki** [comment]
I told you how to get the fix early. If halving the image size does not help, then likely little will, because at halved size it is already only 120 pixels tall and maybe 2000 wide. You can try going below that, but it is going to look like crap.

Also, if your GPU chokes on an image that takes less than 1MB of graphics memory, you are going to have issues with something else no matter what.

**Comment by Zedrimar** [comment]
my GPU just is weird about certain image sizes on MC. It is also an integrated GPU in my CPU which is well.... old. At-least I can disable this later when it is released. sorry for the trouble. My GPU also uses RAM rather than dedicated graphics memory

**Comment by ReikaKalseki** [comment]
The config coming in v7 allows the use of a downsampled image, not turning the effect off entirely.

**Comment by Zedrimar** [comment]
@ReikaKalseki ok good, I just hope that my GPU might for once cooperate considering it is only an image...

Again sorry for the troubles I have caused with well everything else..

**Comment by Ianaver** [comment]
@ReikaKalseki for some reason I can't apply changes to the compiled jar file (I may have mis-understood you when you said to edit the image as you MAY have meant a master copy), I have to do edits to a master copy then recompile for changes to take effect.... The only problem is that I am not sure where to put the mod's files and where to put the gradle wrapper in order to properly recompile the source because every mod is slightly different in the way that files are arranged

**Comment by Ianaver** [comment]
@ReikaKalseki did you want the changes to be made in the source and then recompiled? If you did well..... No wonder nothing worked because.... I am a modding newbie...

**Comment by Zedrimar** [comment]
incase that downsampling doesn't work, can it be possible to disable it if my GPU decides; "I will not work today"?

**Comment by ReikaKalseki** [comment]
You can do it yourself on your end with further image manipulation, but I am not going to add a config, given how many people wanted that option then, when given it, complained that there was no longer a warning when approaching pylons.

**Comment by Zedrimar** [comment]
@ReikaKalseki I see, ok thanks!

**Comment by skyboy** [comment]
@ReikaKalseki All image textures uploaded directly to the GPU should be a power of 2 on width and height (square not required). Ensures widest compatibility, a few cards will substitute a buffer filled with -1, while others will skew the texture to fit. It's why GUIs all use a 256x256 image despite frequently using a small portion of that.

**Comment by ReikaKalseki** [comment]
The image is a power of 2 on each side.

**Comment by Zedrimar** [comment]
@ReikaKalseki its official, in my case there is no fix :/

**Comment by ReikaKalseki** [comment]
How old is your GPU? 1995? How are you able to even run modded Minecraft?

**Comment by Zedrimar** [comment]
sounds about right, I bought this PC on amazon and they stated that this was "New" but it was actually refurbished from a very long time ago..... Don't bother trying to fix it once I get the last few hundred dollars I need I will build an entirely new PC that is up-to-date. If you are wondering I did try to re size the image but even that resulted in the exact same result (color washout). There was something else I tested that was in the creative menu that also had a similar issue but it was instead that the item's texture was a bad size for my GPU and my GPU doesn't have the capability to "fill" or "Fit" the texture onto the item....

My GPU is integrated into my CPU; the chip is a Q33 chipset which the last update for it was made long ago to windows 7 (I am using a windows 10 BETA) I will post the DxDiag report on pastebin for more info: http://paste.ubuntu.com/11843696/ (the driver version shown is a bad one done by microsoft)

**Comment by Zedrimar** [comment]
forget what I said last time about not trying, I want to figure this out myself and see what else could be doing this.

I resized aurabar half and aurabar quarter to fit within the root of 2 format however the color wash still exists (as I said ealier) but I want to know ALL of the images associated with the effect. (except for aurabar half and quarter I know about those obviously). :P

Theory/idea 1. GPU freaking out bc of the fact that the whole bar is assigned a color (no transparent pixels) thus tries to fill it completely with the energy pylon's color. I will try turning the black to transparent and see what happens

Theory/idea 2. There is some other image(s) involved in the rendering of the effect (unlikely). If true, the image(s) may need to be resized. Speaking of this, are there more images involved in the render?

**Comment by ReikaKalseki** [comment]
No, and switching to transparency will break the renderer.

**Comment by Zedrimar** [comment]
ok, well I still wonder why the heck its still giving me a color washout despite the texture resize! (and yeah transparency doesn't work anyhow for me)

**Comment by ReikaKalseki** [comment]
It really sounds like your GPU just cannot handle an image a few thousand pixels wide.

**Comment by Zedrimar** [comment]
well that makes no sense since the rune animation strips are thousands of pixels long yet they render fine as can be as well as any other mods that have textures that are thousands of pixels long/wide :P

that and the texture atlas that MC forge/MC uses is ATLEAST 2500 (upwards of 3-4K depending on the amount of mods are installed) pixels long and wide yet I see everything just fine (even though that may not count), I believe that its just something with the effect getting screwed up because like I said, everything else loads in fine no problems what so ever just that effect makes my PC go haywire

**Comment by Zedrimar** [comment]
It would be awesome if we could find what the heck is really going on, however if we can't figure it out here I will likely leave this issue on "idle" so to speak and go see if anyone else has any information as to what is going on since I have very little knowledge on the way GPUs render images as of right now. I really want to play with this mod more one day, its awesome! sadly just this one effect is really annoying since it doesn't want to render right.

**Comment by Techtronica** [comment]
I'm also experiencing this issue.  I'm currently running Intel HD Graphics 4000.  My computer is 3 years old so the age shouldn't be a cause of this.

According to steam hardware survey, this is one of the most used graphics cards on the market.
http://store.steampowered.com/hwsurvey

**Comment by ReikaKalseki** [comment]
Even with the resized image?

**Comment by Zedrimar** [comment]
that seems to be a fairly new integrated GPU, that is quite strange :/

**Comment by Techtronica** [comment]
Yes, even with the resized image I still have this problem.

**Comment by ReikaKalseki** [comment]
How much graphics memory does it have?

Also, try rotating the image 90 degrees so that it is vertical. It will render oddly, but do you still get the washout?

**Comment by Techtronica** [comment]
1696MB, 64MB dedicated

**Comment by Zedrimar** [comment]
I think it has very little to do with the memory since I prob. have about 256MB in my GPU (according to the Direct X diagnostic tool) but 0 dedicated because of the age of the GPU and that is FAR less than what techtronica has but but ONLY that specific effect is not wanting to work.

I will also try rotating it myself as well

**Comment by ReikaKalseki** [comment]
Try the rotating.

**Comment by Techtronica** [comment]
Rotating and turning on the downsampling in the config seemed to fix the render problem.  I had to do both together however, rotating alone and turning on the downsampling alone did not solve it.

**Comment by Zedrimar** [comment]
no avail for me :( the images were resized properly and rotated with downsampling enabled and still color wash

**Comment by ReikaKalseki** [comment]
In which case, Techtronica's card seems better able to handle tall images than wide ones (which is exactly the opposite of what I would expect) and lanaver, your card just sucks. :P

**Comment by Zedrimar** [comment]
obviously XD so I guess I will wait then for a bit untill I can upgrade my pc (and card) :P

**Comment by Zedrimar** [comment]
@ReikaKalseki I just ordered a new PC with far better specs than my current machine so everything should be okay now assuming the PC works when it arrives :D
