### ISSUE TITLE
Can't install DragonAPI and SimplyJetpacks together

### ISSUE THREAD

**Issue by jellybeanflames** [ReikaKalseki/Reika_Mods_Issues#861]
Whenever I install DragonAPI and SimplyJetpacks together, my game exists with a crash, saying that the two mods are incompatible. Could you please fix this?

**Comment by ReikaKalseki** [comment]
What does it say, exactly? And I do not have any crash-on-load code, for SJ or otherwise.

**Comment by Ianaver** [comment]
I don't have a problem with the two :/ give a crash report please

**Comment by ReikaKalseki** [comment]
Hello?

**Comment by ReikaKalseki** [comment]
Closed until more information is given.
