### ISSUE TITLE
[ChromatiCraft] ChromaHelpHUD reads invalid block metadata after looked at block changes

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [ReikaKalseki/Reika_Mods_Issues#862]
This is related to an [issue in Glenn's Gases' issue tracker](https://bitbucket.org/jamieswhiteshirt/glenns-gases/issues/43/glenns-gases-causes-crash-with). It is causing a [crash](http://pastebin.com/k9mDmDmE).

What is happening: The player mines a ChromatiCraft ore block. Because Glenn's Gases recognizes this as a stone-type material block, it places dust in place of the ore. This dust uses metadata to track its own volume, and is therefore affecting the metadata in [ChromaHelpHUDs queries in the subsequent ticks](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Auxiliary/ChromaHelpHUD.java#L70).

I think this might be a general problem in any situation in which a block the player is looking at changes.

**Comment by ReikaKalseki** [comment]
I see the problem, yes. For performance reasons it only rescans every 8 ticks, and just reuses the cache every other time. The assumption, here invalid, was that the cache would fully encapsulate the state.

That said, I am not sure of a good way to fix this. The whole point was avoiding blockID/metadata lookups, which means I cannot even check "has block changed".

**Comment by JamiesWhiteShirt** [comment]
You cache the metadata in ChromaHelpHUD and all the necessary functions are exposed. Nothing seems to be in the way of rewriting

`flag = ((BlockTieredResource)block).isPlayerSufficientTier(Minecraft.getMinecraft().theWorld, posX, posY, posZ, ep);`

as

`flag = ((BlockTieredResource)block).getProgressStage(metadata).isPlayerAtStage(ep);`

EDIT: Oops, I realize that would only work for ChromatiCraft-specific blocks.

EDIT 2: Maybe cache the result of `isPlayerSufficientTier`?

**Comment by ReikaKalseki** [comment]
I am trying your second idea.
