### ISSUE TITLE
Chroma Rendering Issue

### ISSUE THREAD

**Issue by RaineAndrews** [ReikaKalseki/Reika_Mods_Issues#864]
This interesting little bug happened only after Rev|2 updated to v13 of Chromaticraft.

https://github.com/Haggle1996/RevolutionPack/issues/430

tldr: berry saturated chroma doesn't lose its color after boosting crystals BUT doesn't retain boosting ability anymore (so its just a rendering error?).

**Comment by RaineAndrews** [comment]
I tried unloading the chunk the chroma was in and coming back and it was no longer berry saturated, and looked like your standard block of liquid chroma

**Comment by ReikaKalseki** [comment]
The chunk needed a render update.
