### ISSUE TITLE
Strange chunkloading issues, items getting thrown all over the place

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#865]
hi,
I have a what I would consider mid game rotarycraft+chromaticraft base (Progression: just made  pulesjet furnace and rune crafting) and I am not aware that I have build a chunk loader, although I assume the tunnel bore has to at least load the chunk it is mining, while the main block in my base is loaded.  
I have noticed that my base does not probably unload when I leave it, several thousand blocks away from it while exploring and collecting flowers for chromaticraft I got the 'you successfully damaged a gearbox' achievement and I found that when ever return to my base I have item entities all over the place. It is most noticeable with sugarcane. My sugarcane farm consists of a block breaker from expanded redstone, a timer and some pneumatic pipes to pump it to a grinder. The grinder is pretty much always topped of with sugarcane, so all the sugarcane should stay in the chest next to the block breaker. The Sugarcane farm is completely within one chunk. I have also found canolaseeds 3 chunks away from my farm and processing area.
While I am in my base, none of my builds drop any items to ground, this only happens while I am away or when I come back.

Using the latest version of all your mods, would also greatly appreciate it if you could release a chromaticraft version with a fix to the cave crystals. Could really use them to get some liquid chroma.

**Comment by ghost** [comment]
Have you tried chunkloading your base (with chickenchunks or something related)? Worth a shot since then your whole base will be loaded.

When you say "fix to the cave crystals" can you explain? If it's a lack of them in a world I haven't noticed it. More detail on that would be good.

**Comment by Turmfalke2** [comment]
No I have not. I don't have chickenchunks installed and in rotarycraft chunkloaders are kind of end game with them requiring nether stars and 16 times bedrock gears.

For the cave crystal thing see #806

**Comment by ghost** [comment]
Ahh, that. The cave crystals are fixed for the next version (whenever that is). It was fixed just after v13b came out.

**Comment by Turmfalke2** [comment]
Yes I can read, I am just hoping that reika is going to release a version with that fixed.

**Comment by redelman** [comment]
He will release a version with that fixed. It'll be in the next version. :P

**Comment by ReikaKalseki** [comment]
Entities, including items, do not update, which includes aging and movement, unless there is a 5x5 of chunks loaded around them. Try that.

**Comment by Turmfalke2** [comment]
huh? Please elaborate. What exactly is causing the pneumatic item pumps to drop the items? There shouldn't be any loaded chunks around.

**Comment by ReikaKalseki** [comment]
The TileEntities are lazyloading the area. Chunkload it.

**Comment by Turmfalke2** [comment]
Ok and lazyloading means that just the machine is loaded, but not the chunk around it? And pressumably the 'is there something at the other end of the pneumatic item pump' fails and the item gets thrown on the ground? Going back to your 5x5, does that limit when a entity can be lazy loaded? Maybe the nearby cc pylon is causing is loading it's chunk?

**Comment by ReikaKalseki** [comment]
Entities cannot be lazyloaded.

**Comment by Turmfalke2** [comment]
Er.. TileEntities are not Entities?

**Comment by Builderb0y** [comment]
If a chunk is loaded, and a 5x5 chunk area around it is also loaded, then that chunk is "fully" loaded, and all processing of blocks, entities, and tile entities occurs normally inside that chunk. However, if the chunk is loaded, but ANY of the chunks in that 5x5 chunk area around it are not loaded, then that chunk is "lazy loaded", which means that blocks and tile entities inside it will tick normally, but entities inside it will not tick at all.

**Comment by Turmfalke2** [comment]
@Builderb0y thank you. So that means something is still loading the chunk and that the pneumatic item pump does not work probably in lazy loaded chunks, which then drops the items. These items can't despawn until I come back, which is causing the issue with hundreds of items on the ground. 
Assuming it is not the pneumatic item pumps, how are block breakers from expandedrestone and fans from rotarycraft expected to function in a lazyloaded chunk?

**Comment by TomeWyrm** [comment]
Unreliably. Don't lazy-load. There are vanilla chunk loaders if you really can't add chickenchunks for some reason. Or add dimensional anchors, or any other chunk loading mod. You're playing modded minecraft. Without access to chunk loading, you're going to have a pretty hard/obnoxious time.

**Comment by Turmfalke2** [comment]
I do have access to chunk loading, I just can't afford it yet. Need to kill at least one more wither and look into producing the required power to run one.

**Comment by TomeWyrm** [comment]
Is there a reason you don't have real chunkloading that doesn't take a reactor to power?

**Comment by Turmfalke2** [comment]
Yes, I made it my self a challenge to play just with Reika's mods and some minor mods like NEI, StorageDrawers and Chisel. That is also why my item item transport purely with pneumatic pipes is extremely clunky, but it proved quite fun figuring out how do certain things that are taken granted in other modpacks. I am probably the first one using multiple sorting machines.

**Comment by TomeWyrm** [comment]
I'd consider actual chunk loaders to be a required mod for modded. You can also do vanilla chunk loaders if you're willing to spend that much iron

**Comment by Turmfalke2** [comment]
Vanilla chunk loader refers to a hopper chain from the spawn chunks to my base?

**Comment by TomeWyrm** [comment]
Not quite a chain, and you need to not lazy load spawn, but yes

**Comment by Turmfalke2** [comment]
Yeah.. I am not going to do that. From the look of it a micro turbine should be able to power a chunk loader, although getting any additional radius on it is going to be tough if the formula of '0+((Power -2097152)/524288)' is correct.

Actually nvm it isn't. 2 microturbines give me a radius of 4.

**Comment by TomeWyrm** [comment]
Eh, I guess that's not TOO horrible... still, in the future I'd suggest using a real chunk loading mod. Reika only added one to RotaryCraft because you basically require chunk loading for many of his fun toys and he tries to let you be capable of everything without having to install another mod, theoretically, at some point.

Also, gear those microturbines for min torque, the chunk loader uses speed from what I recall.
