### ISSUE TITLE
Uranium Processor working without Fluorite

### ISSUE THREAD

**Issue by amesgen** [ReikaKalseki/Reika_Mods_Issues#866]
In v13b, an Uranium Processor supplied with water produces Hydrofluoric Acid without Fluorite present. If I try to insert Fluorite via any Item Conduit (tried with EnderIO, ThermalDynamics), the console is spammed with "Tried to access slot 0, which is empty.", and no Fluorite is placed into the processors. The uranium ingots are necessary though.
I can insert Fluorite manually, which is consumed as expected, but afterwards, Hydrofluoric Acid is produced even without Fluorite once again.

**Comment by ghost** [comment]
I believe this was fixed for the next version.

**Comment by amesgen** [comment]
v14 or v13c?

**Comment by ReikaKalseki** [comment]
Already fixed.

**Comment by ghost** [comment]
v14.
