### ISSUE TITLE
V13a/b RotaryCraft + Reactorcraft: All items vanishing from handbook after looking inside it for some time

### ISSUE THREAD

**Issue by leonbaronick** [ReikaKalseki/Reika_Mods_Issues#867]
Today I tried to build a heavy water extractor and therefor had to look inside the handbook for some time. After about 0.5 - 1 minutes both handbooks looked like this:

![2016-05-26_16 05 35](https://cloud.githubusercontent.com/assets/17071279/15577446/e2ed4870-235c-11e6-9acb-a52fddc3a7a5.png)

And a lot of text appeared in chat:

![2016-05-26_16 06 00](https://cloud.githubusercontent.com/assets/17071279/15577453/ee070d04-235c-11e6-8322-8095a8de5249.png)

Even after restarting the world the handbooks aren't fixed. Only after restarting the whole game.
The whole thing happened a second time after restarting the game.

If you need to know what it says in chat/console, I'm sure I can make the bug happen again.

The modpack can be found on the technic platform including a mod list:
http://technicpack.net/modpack/futurepack-standard.852828

**Comment by ghost** [comment]
This is known. The error you have in chat causes it but it might not have been fixable or easy.

**Comment by ReikaKalseki** [comment]
Probably another invalid item in the OreDict, though I am not sure under what tag, as RC does not use things like leaves and logs.

**Comment by leonbaronick** [comment]
Maybe sticks? There Are a lot of them, with bamboo and such...

**Comment by ReikaKalseki** [comment]
Possibly.

**Comment by leonbaronick** [comment]
Same thing happened again, when I looked at the gearboxes and it cycled through to the wooden gearbox. Looks like it was caused by the wooden planks...

**Comment by TomeWyrm** [comment]
I'd bet either Forestry or Natura. I don't like Technic for personal reasons, so I'm not investigating the link to the pack. If you feel like posting an actual modlist here I'd give it a second look.
