### ISSUE TITLE
[Request] Void Monster Entity ID Config

### ISSUE THREAD

**Issue by Shadows-of-Fire** [ReikaKalseki/Reika_Mods_Issues#868]
It would be nice to be able to manually adjust the entity id for the void monster.  It, and what I can only assume to be an issue with the entity id between dedicated server and client, is causing a fatal error that disconnects the client from the server, but crashes neither.  It works fine in a single player environment.
FML Client and Server logs are provided below.
https://gist.github.com/Shadows-of-Fire/73b8bc9ccfa60cfa32651d7433c65185
https://gist.github.com/Shadows-of-Fire/b3fde11944f816dd2539c7a3968995f8

**Comment by ReikaKalseki** [comment]
Entity IDs are calculated during loading. If they mismatch, you have bigger issues.
