### ISSUE TITLE
Correct registry of fluorite ores in the MFR Laser Drill

### ISSUE THREAD

**Issue by amesgen** [ReikaKalseki/Reika_Mods_Issues#869]
The ores of ReactorCraft have reasonable and IMO appropriate weights and color codes (laser foci) in the MFR Laser Drill **except** Fluorite Ore, which is messed up (Blue Fluorite has a white code, the other ones arent even registered). Blue Fluorite has a weight of 20, which results in my modpack in a chance of 0.76%.
It would be nice if the other Fluorite Ores could also have a MFR Laser Drill entry by default. Currentely I use the following MineTweaker/ModTweaker code to accomplish that result:

```
mods.mfr.MiningLaser.removePreferredOre(8, <ReactorCraft:reactorcraft_block_fluoriteore>);
mods.mfr.MiningLaser.addPreferredOre(11, <ReactorCraft:reactorcraft_block_fluoriteore>);
mods.mfr.MiningLaser.addOre(<ReactorCraft:reactorcraft_block_fluoriteore:1>.weight(20));
mods.mfr.MiningLaser.addPreferredOre(6, <ReactorCraft:reactorcraft_block_fluoriteore:1>);
mods.mfr.MiningLaser.addOre(<ReactorCraft:reactorcraft_block_fluoriteore:2>.weight(20));
mods.mfr.MiningLaser.addPreferredOre(1, <ReactorCraft:reactorcraft_block_fluoriteore:2>);
mods.mfr.MiningLaser.addOre(<ReactorCraft:reactorcraft_block_fluoriteore:3>.weight(20));
mods.mfr.MiningLaser.addPreferredOre(2, <ReactorCraft:reactorcraft_block_fluoriteore:3>);
mods.mfr.MiningLaser.addOre(<ReactorCraft:reactorcraft_block_fluoriteore:4>.weight(20));
mods.mfr.MiningLaser.addPreferredOre(13, <ReactorCraft:reactorcraft_block_fluoriteore:4>);
mods.mfr.MiningLaser.addOre(<ReactorCraft:reactorcraft_block_fluoriteore:5>.weight(20));
mods.mfr.MiningLaser.addPreferredOre(14, <ReactorCraft:reactorcraft_block_fluoriteore:5>);
mods.mfr.MiningLaser.addOre(<ReactorCraft:reactorcraft_block_fluoriteore:6>.weight(20));
mods.mfr.MiningLaser.addPreferredOre(0, <ReactorCraft:reactorcraft_block_fluoriteore:6>);
mods.mfr.MiningLaser.addOre(<ReactorCraft:reactorcraft_block_fluoriteore:7>.weight(20));
mods.mfr.MiningLaser.addPreferredOre(4, <ReactorCraft:reactorcraft_block_fluoriteore:7>);
```

As the other ores are already registered, I think it would not be too difficult to do so for the Fluorite Ores (but I don't know which mod registers ReactorCraft's ores - I assume ReactorCraft does this).

**Comment by ReikaKalseki** [comment]
I do not register any of these. All the handling is on his end.

**Comment by amesgen** [comment]
Thanks, I will report this there.

**Comment by amesgen** [comment]
skyboy removed his fluorite handling due to this problem, if you want fluorite to be registered, you have to use IMC (see referenced issue)

**Comment by amesgen** [comment]
for future readers: Fluorite is now correctly registered (see referenced issue)
