### ISSUE TITLE
Chromaticraft lumen leaves render (6f)

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#87]
lumen leaf blocks render as clay. :/

**Comment by ReikaKalseki** [comment]
Then their TileEntity data is not present. Did you hack the leaves in directly or is this on the tree?

**Comment by Zedrimar** [comment]
I cheated them in, I was curious what they looked like

**Comment by ReikaKalseki** [comment]
See the tags.

**Comment by Zedrimar** [comment]
my bad.... sorry!
