### ISSUE TITLE
Industrial coil only charging for one tick (even with high power)

### ISSUE THREAD

**Issue by Kataiser9** [ReikaKalseki/Reika_Mods_Issues#870]
I've read the manual, and I know about the torque/power requirements for charging industrial coils to higher energy levels. I've checked the formulas, and something is definitely off. Charging an industrial coil with a _gas turbine_ caps out at 9830 kJ... unless you place the coil down after the gas turbine reaches full speed, in which case it caps out at 3.355 MJ, i.e. the amount of energy it would get in one tick. It seems that the coil will only accept energy if it has none at all; as soon as you get the stored energy over 0, it rejects any further input until completely discharged.

This is, I believe, the same issue as https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/736 - those are clearly incredibly low numbers for the given engines, and they're also all 1/20 of the wattage of each engine, in joules.

V13b, bedrock industrial coil, if it matters.

edit: I did not have this issue on my previous RoC playthrough, which was... V10, I think, and definitely no earlier than V9. I assume that might help narrow down possible sources of the problem. (also edited to be Less Grumpy)

**Comment by ReikaKalseki** [comment]
Bedrock takes more torque. It is always going to charge for the first tick, and then you need more. In the case of a accelerating engine, different ticks provide different amounts of power.

**Comment by redelman** [comment]
That being said, I would be interested in the OP sharing how much torque
the industrial coil is getting.
