### ISSUE TITLE
ROTARYCRAFT DEBUG: Player does not exist to receive their achievement "BEDROCKBREAKER"!

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#873]
hi,
Just got above message after coming back from the end in singleplayer. I am wearing full bedrock armour and as such had the achievement for quite a while. Maybe something about the weird way the player is transported back to the overworld is causing the owner of the bedrock breaker to be unknown?

E: I seem to get that message everytime the bedrock breaker mines a block.

**Comment by ReikaKalseki** [comment]
Fixed.
