### ISSUE TITLE
Please hide the forbidden number from coming up

### ISSUE THREAD

**Issue by acidbeans** [ReikaKalseki/Reika_Mods_Issues#875]
I left an Industrial Coil charging and after a while it stopped at...well, I can't write it out, but it's made of the triplicate of the double of three. Please add a config to make this number never come up.

**Comment by freyskol** [comment]
This request makes zero sense.

**Comment by Fuzzeee** [comment]
Satan will not enter your home, to present a temporary fix; I've printed the evil number here: 666.
B̡̀̈͋ͣL̛͌͗ͦ̅ͥO͗̀ͯ̍̅ͫO͓̪̖̖͎ͤD̵̤͈͈̗̈́͌͐̇ͯ̐ͣ ͖͔̮̞͖̑̊̅̈Ỏ̜̻͚̣̪̦̮F̰͕̽ͧ̏ͤ͛̓ͮͅ ̜̬͔̱̞͎ͦ̿̇ͩͯ̆ͬT̎ͮ́̊̎̽͢H̫̫̄̕Ẻ̲̣̯̰̳̓̚ͅ ͚̳͎ͬ͒I̮̤̬͙͊ͮ͡N͇ͥ̌̅͜N̯͇̞͈̆̃Oͪ̔̚͏C̬̩̗̞͙ͮ́̽̈́͢E̫̼̹͔̯ͤ̋͆͘N̯̹͇̈́ͬ̕T̳̹̣̫̻̼̐̒̊̉ ̡̤̝͕̰̥͋͛ͯͧ̅ͅS̶̜ͦ͋̋̂̍̊͑H̤̱͈͉ͧͧ͋ͧ͛A̜͎̱̻̼̳̠ͭL͇̞̹̓̌̏͌̐L̞̬̦̣̗̼̰ ͫ͏̺͎̗B͈̦͎̏̓ͨͬ̀̚E̷͍̺̪̳͆ͬ̽͛ͨ̅̚ ̳̍ͅS̪̗̪̅́͆̐̋͋̀H̯̲̦̪̣̱͛̓̇̏ͤ͂͆ͅĘ̰̰̖̗̺D̛̤̣ͮͫ̈ ̘̼̘͕̓̉F̯ͨ̑͞O̸̠̠̬ͧͤ͑ͣŖ̠ͥͬ ͪ̏ͤͩ̏ͥ̾҉͙̲͓̦̜Y̷͈̤͓̖͔̊ͧ̋͂E͙͌̓̑͋́͒̎A̖̤͔̬ͯ̿ͮͦ͊̍R͕̈S̨̗̹͔̩̝ͧ̇ͧ̈́ͦͯͅ ̥͖̒̀͞T͖̝̬͎O̼̊̆̍̐̀͠ͅ ̧̞̮͔͇̿̈ͭ̔̐ͬͯC͉̺̕Ȯ̷͔͖̮̳̲̖M̵̱͇ͪͨ̔̈ͧE͒̋͂.̝̞͈͍͔̔͂̚̚

**Comment by ReikaKalseki** [comment]
I cannot purge a number from mathematics just because it displeases you. You want _that_...you know who to ask. I am told they often act on such requests, if in roundabout and unfalsifiable ways.

**Comment by MaPePeR** [comment]
Maybe you can, instead of purging the number from mathematics, add some visual indication that a machine is possessed by the devil, when such a number comes up? To serve as a warning for the unsuspecting user. 

I'm sure you can think if proper visual indications for that.

**Comment by asiekierka** [comment]
Note: The original "number of the beast", as per older manuscripts, was likely to be the double of three multiplied by one hundred and one with ten added to it. However, nobody panics about that one - instead, everyone focuses on the much simpler "triplicate of the double of three". I guess it rolls off the tongue easier, or something.

**Comment by tahg** [comment]
How is three doubled three times in a row any different than three doubled multipled by one hundred plus one plus ten?  By my math that's the exact same number

**Comment by DiJuMx** [comment]
@tahg 3 doubled = 6, times "One hundred and one" (101) = 606, plus 10 = 616.

The reading of "one hundred and one plus ten" doesn't mean (100 + 1 + 10) it's read as (101) + 10. (Assuming a premultiplication by 6: 6_(101) + 10, not 6_(100+1+10)).

It's like one of those annoying Bodmas/Pemdas facebook "challenges", where everyone reads the "one hundred and one, plus ten" in two different ways. Hence the "modern" 666 vs the "original" 616

**Comment by Nodachi216** [comment]
@DiJuMx OMG!!! That explains a lot about Marvel Comics main universe! ;)

**Comment by Barhandar** [comment]
> It's like one of those annoying Bodmas/Pemdas facebook "challenges", where everyone reads the "one hundred and one, plus ten" in two different ways.

For the interested, this happens because education is lacking and fails to mention multiplication and division are on same "order of operations", just like addition and subtraction are relative to each other. If someone incorrectly thinks multiplication is done first, they get one result, if they correctly think whichever of the two is leftmost is done first, they get other result.

**Comment by Notawallplan** [comment]
The only place where doing that would make sense is ChromatiCraft.

**Comment by edwanvi** [comment]
> The only place where doing that would make sense is ChromatiCraft.

Even there, it's still a number like all the rest of them. There's no reason to try and remove it from a mod (which would really be difficult anyways.)
@acidbeans Numbers exist. Get over it.

**Comment by Sakata-MC** [comment]
Thank you, author, for not being a "special" person, and deeming this as unreasonable and frivolous.  We have enough of the special-ed religion crud flying around where people cave in to it.

Also, @FurryDJ I love the

B̡̀̈͋ͣL̛͌͗ͦ̅ͥO͗̀ͯ̍̅ͫO͓̪̖̖͎ͤD̵̤͈͈̗̈́͌͐̇ͯ̐ͣ ͖͔̮̞͖̑̊̅̈Ỏ̜̻͚̣̪̦̮F̰͕̽ͧ̏ͤ͛̓ͮͅ ̜̬͔̱̞͎ͦ̿̇ͩͯ̆ͬT̎ͮ́̊̎̽͢H̫̫̄̕Ẻ̲̣̯̰̳̓̚ͅ ͚̳͎ͬ͒I̮̤̬͙͊ͮ͡N͇ͥ̌̅͜N̯͇̞͈̆̃Oͪ̔̚͏C̬̩̗̞͙ͮ́̽̈́͢E̫̼̹͔̯ͤ̋͆͘N̯̹͇̈́ͬ̕T̳̹̣̫̻̼̐̒̊̉ ̡̤̝͕̰̥͋͛ͯͧ̅ͅS̶̜ͦ͋̋̂̍̊͑H̤̱͈͉ͧͧ͋ͧ͛A̜͎̱̻̼̳̠ͭL͇̞̹̓̌̏͌̐L̞̬̦̣̗̼̰ ͫ͏̺͎̗B͈̦͎̏̓ͨͬ̀̚E̷͍̺̪̳͆ͬ̽͛ͨ̅̚ ̳̍ͅS̪̗̪̅́͆̐̋͋̀H̯̲̦̪̣̱͛̓̇̏ͤ͂͆ͅĘ̰̰̖̗̺D̛̤̣ͮͫ̈ ̘̼̘͕̓̉F̯ͨ̑͞O̸̠̠̬ͧͤ͑ͣŖ̠ͥͬ ͪ̏ͤͩ̏ͥ̾҉͙̲͓̦̜Y̷͈̤͓̖͔̊ͧ̋͂E͙͌̓̑͋́͒̎A̖̤͔̬ͯ̿ͮͦ͊̍R͕̈S̨̗̹͔̩̝ͧ̇ͧ̈́ͦͯͅ ̥͖̒̀͞T͖̝̬͎O̼̊̆̍̐̀͠ͅ ̧̞̮͔͇̿̈ͭ̔̐ͬͯC͉̺̕Ȯ̷͔͖̮̳̲̖M̵̱͇ͪͨ̔̈ͧE͒̋͂.̝̞͈͍͔̔͂̚̚

I just need to blow that up and see if I can read what's between the letters

**Comment by 1Matthias** [comment]
@Sakata-MC "BLOOD OF THE INNOCENT SHALL BE SHED FOR YEARS TO COME" is what is says.

**Comment by Barhandar** [comment]
> I just need to blow that up and see if I can read what's between the letters 

Nothing much, it's ZALGO text rendering.

**Comment by Notawallplan** [comment]
Say the numbers in Enochian however...

**Comment by smbarbour** [comment]
Clearly, the only way to satisfy both this superstitious user and mathematics at the same time is to switch all numbers to base 6 (or less) that way the digit "6"is never actually used.

**Comment by Barhandar** [comment]
There is also number 4, which in Japanese shares the name with the word "death" ("shi").

**Comment by kolatra** [comment]
![DrEvil](https://media1.giphy.com/media/JeKLoVq2KzdpS/200.gif)

ty based @Lordmau5

**Comment by Lordmau5** [comment]
I do have my own reaction to this though:
![butwhy](http://i.imgur.com/TnQRX6v.gif)

**Comment by tahg** [comment]
I don't know. The greek seems to be 600 + 60 + 6, which seems pretty hard to screw up mathematically.  I'd like to see what other references exist for this number tho.

**Comment by TomeWyrm** [comment]
@tahg Check the citations here

https://en.wikipedia.org/wiki/Number_of_the_Beast

Also @acidbeans hexakosioihexekontahexaphobia doesn't become you, unless it's actually associated with the Beast, it's just a number. When we see a few hundred thousand Jews being marked as servents of God on their forehead? Then it might be wise to start worrying about 666/616. Until then it's just as much a number as 1, 1000000, 42, 69, 74, or 678642378564532.

**Comment by Barhandar** [comment]
> When we see a few hundred thousand Jews being marked as servents of God on their forehead?

That's equivalent to painting a target on them, though. A proof, right there, that their God is stupid.

**Comment by redelman** [comment]
Alright, this isn't the place for religious discussions and this is getting out of hand.
