### ISSUE TITLE
There are something that should not be localized...

### ISSUE THREAD

**Issue by 3TUSK** [ReikaKalseki/Reika_Mods_Issues#876]
Seriously, there _are_ something that should not be localized...
For example:
When trying to use OpenComputer to access RotaryCraft extractor: (picture is from my friend)
![image](https://cloud.githubusercontent.com/assets/9113033/15624972/7a213842-2465-11e6-8ad0-a01af2522593.png)
Another example:
A copy of [fml log](http://paste.ee/p/V1ZRZ), and you will notice that part of log printed by ChromatiCraft is localized - which should not happen IMO.

**Comment by ReikaKalseki** [comment]
They reference the same code...

Why not just reference it by address instead?

**Comment by ReikaKalseki** [comment]
I cannot change this without significant rewrites. Just reference it by address.
