### ISSUE TITLE
[Chromaticraft] [unsure if intended] Turrets do not allow mobs to drop loot when they are killed

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#877]
Not exactly sure if this is intended. If it is intended it may be to keep the entity count low but I am not sure. Maybe they are too OP for things like mob farming... If it is intended that lumen turrets do not allow mobs to drop loot then just close this and tell me what reason was behind this :P I read through everything and I did not see anything regarding info even hinting at loot drops.

My apologies for my weird sentence structure, I am still not the best with English.

**Comment by ReikaKalseki** [comment]
You guessed the reason.

**Comment by Zedrimar** [comment]
Okie, good to know! XD

**Comment by TomeWyrm** [comment]
> too OP for things like mob farming

That's the reason.

**Comment by Zedrimar** [comment]
okie
