### ISSUE TITLE
HSLA steel scythe has infin. durability?

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#88]
well, I tried both the cheated version and a legit crafted version and all of them had that issue...
Not sure if it was intended or not.

**Comment by ReikaKalseki** [comment]
I fixed that some time ago. What version is this?

**Comment by Zedrimar** [comment]
@ReikaKalseki sorry forgot to put it, I was in a hurry; the version is 6f

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by Zedrimar** [comment]
@ReikaKalseki for the next patch? this one didn't have the fix. sorry got confused what you meant...

**Comment by ReikaKalseki** [comment]
v7.

**Comment by Zedrimar** [comment]
oh XD
