### ISSUE TITLE
Reika mods crashing issue

### ISSUE THREAD

**Issue by rami3361** [ReikaKalseki/Reika_Mods_Issues#881]
so i was playing with FTB Infinity evolved with a few added mods and decided to add some of reika's mods i added dragonaip , rotary craft and reactor craft and the game crashed i have the crash log here 

[2016-05-28-7.log.gz](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/287667/2016-05-28-7.log.gz)

I hope you help i really like Reika mods

**Comment by Duckfan77** [comment]
Not going to download things, try posting the text into something like [gist](https://gist.github.com).

**Comment by ReikaKalseki** [comment]
Hello?

**Comment by 1Matthias** [comment]
It is a single zipped file with the crash log. I have re-pasted it here: http://pastebin.com/eNYtSZnY

**Comment by ReikaKalseki** [comment]
The only error there is a RandomThings one.
