### ISSUE TITLE
[ChromatiCraft]Crash when harvesting invisible tiered plant with excavation star.

### ISSUE THREAD

**Issue by Mr-kk** [ReikaKalseki/Reika_Mods_Issues#882]
MC crashes when harvesting invisible TieredPlant (such as Aura Bloom, Radiance Bush) with Excavation Star.

Crash log
http://pastebin.com/e3gFcpy5

Version
 MC1.7.10 SMP
ModList
 Forge10.13.4.1614
 DragonAPI V13b
 ChromatiCraft V13b

**Comment by TomeWyrm** [comment]
Wait, I thought you fixed that one Reika. Or was that just the grass bug that got fixed?

**Comment by Builderb0y** [comment]
We fixed an issue related to breaking one-hit-break blocks with the excavation star. This is probably a different thing.

**Comment by ReikaKalseki** [comment]
Fixed.
