### ISSUE TITLE
[ChromatiCraft]Crash during ability “Matter Phase” Ritual

### ISSUE THREAD

**Issue by Mr-kk** [ReikaKalseki/Reika_Mods_Issues#883]
MC crashes at the moment to suck the 7th energy, when selecting the ability “Matter Phase” from ritual table and use an elemental manipulator.

Crash log
http://pastebin.com/h4S26ErT

Version
 MC1.7.10 SMP
ModList
 Forge10.13.4.1614
 DragonAPI V13b
 ChromatiCraft V13b

**Comment by ReikaKalseki** [comment]
WTF? Is this reproducible?

**Comment by ReikaKalseki** [comment]
Well...it was for me.

**Comment by ReikaKalseki** [comment]
Fixed.
