### ISSUE TITLE
[ChromatiCraft]Crash when entity collide with Portal Rift

### ISSUE THREAD

**Issue by Mr-kk** [ReikaKalseki/Reika_Mods_Issues#885]
MC crashes when an entity (such as player, item, particle) collides with blockPortalRift.

Crash log
http://pastebin.com/TCwuzWp0

Version
 MC1.7.10 SMP
ModList
 Forge10.13.4.1614
 DragonAPI V13b
 ChromatiCraft V13b

**Comment by Builderb0y** [comment]
Already fixed for V14.

**Comment by Mr-kk** [comment]
I'm sorry. It seems Finding of I did not have enough. Thank you for teaching me.
