### ISSUE TITLE
[ChromatiCraft]Ability “Item Preservation” duplicates Soul Bound Items

### ISSUE THREAD

**Issue by Mr-kk** [ReikaKalseki/Reika_Mods_Issues#886]
It seems unintended behavior.
When player dies with the Ability, “Item Preservation”, Items with the enchantment “Soul Bound” are duplicated.

Version
 MC1.7.10 SMP
ModList
 Forge10.13.4.1614
 DragonAPI V12e
 ChromatiCraft V12e
EnderCore-1.7.10-0.2.0.32_beta
EnderIO-1.7.10-2.3.0.424_beta

**Comment by ReikaKalseki** [comment]
All I do is force keepInventory for that death. This is on EiO's end.
