### ISSUE TITLE
[ChromatiCraft]Item changes with Item Mover

### ISSUE THREAD

**Issue by Mr-kk** [ReikaKalseki/Reika_Mods_Issues#887]
It seems unintended behavior.
Item changes with the flow of player’s actions below.
1. Open the GUI of Item Mover, and set an item(=item_A).
2. Shift + Right clicking a storage like chest, and put the item(=item_A) in it.
3. Open the GUI of Item Mover again, and set another item(=item_B)
4. Shift + Right clicking a storage again, and the stored item(=item_A) changes to the latter one(=item_B)

Version
 MC1.7.10 SMP
ModList
 Forge10.13.4.1614
 DragonAPI V13b
 ChromatiCraft V13b

**Comment by ReikaKalseki** [comment]
Does it dump item B?

**Comment by Mr-kk** [comment]
Please check the reproduction procedure in the video.
https://streamable.com/dav9

**Comment by ReikaKalseki** [comment]
Fixed.
