### ISSUE TITLE
Can not progress, castingprog gets reset(?!)

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#889]
hi,
After trying for hours to get the ritual table to behave and failing to do so. (One line of lumen lumen repeaters is doing a constant firework and while the other does nothing) I dug bit around trying figure out what I really need to progress. From what I can tell all I really need is playerHasCrafted(Recipe.TEMPLE), but in that context I noticed that my PlayerPersisted/castingprog keeps resetting. If I craft a pendant I gain Multiblock 1 in addition to crafting 1, if I then crafting some crystalline stone I lose the multiblock entry again. Is this the correct behaviour? Also a bit unsure on how I gain the temple entry, given that the pendant already requires a casting temple.

**Comment by ReikaKalseki** [comment]
If your player NBT keeps getting reset, you have bigger issues. But yes, that will make progression problematic.

**Comment by Turmfalke2** [comment]
It is not the whole player nbt, seem to be just the castingprog category.

**Comment by ReikaKalseki** [comment]
That makes no sense. If it was the whole DeathPersistent tag, for which there is precedent, it would.

**Comment by Turmfalke2** [comment]
This is my PlayerPersisted http://pastebin.com/iGatvWGN castingprog is at 0x0d08 and 0x0d14. Everything around it looks fine to me. I have my Chroma_Progression, my Chroma_Research and the Chroma_Element_Discovery.

E: Come to think off, I crashed several times with concurrent modification exceptions while trying to figure out the weak repeater. I am still not sure why half of them have a constant firework going. Is that overload or end of life? How ever I did see my deathpersistent tag resetting without crashing, so might not be related.

**Comment by ReikaKalseki** [comment]
Particles are near-end-of-life indicators.

**Comment by Turmfalke2** [comment]
I just regained castingprog multiblock by crafting a void core. For that I had to restart minecraft or it wouldn't display the core in the output slot(?!). Now I have apparently lost it again.
E: crafted the pouch and made sure I had fragments in my inventory to instantly reach networking.

**Comment by Keyarose** [comment]
I'm also having a similar or the same problem. I used NBTExplorer to check my castingprog when my progress stalled at basiccraft.  Despite having crafted a number of things the castingprog tag did not appear at all.  I manually created it and added the crafting and temple flags (temple after having tried crafting a temple recipe), of which the temple flag has since disappeared.

**Comment by ReikaKalseki** [comment]
Something else is at work. I have no code to do this.

**Comment by Turmfalke2** [comment]
I feel like that is not something another mod can just occidentally mess up.
Mod list for me was:
Chisel2-2.5.1.44.jar
DragonAPI 1.7.10 V13b.jar
ForgeMultipart-1.7.10-1.2.0.345-universal.jar
ReactorCraft 1.7.10 V13b.jar
StorageDrawers-1.7.10-1.7.5.jar
BiblioCraft[v1.11.4][MC1.7.10].jar
ChromatiCraft 1.7.10 V13b.jar
ElectriCraft 1.7.10 V13a.jar
InventoryTweaks-1.59-dev-152.jar
VoidMonster 1.7.10 V13a.jar
fastcraft-1.23.jar
Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
ExpandedRedstone 1.7.10 V13b.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar
RotaryCraft 1.7.10 V13a.jar
Waila-1.5.10_1.7.10.jar

Going to update to 14 now, maybe the bug disappears.

**Comment by ReikaKalseki** [comment]
If NBT tags are randomly being deleted, and I have no code to do it...

**Comment by TomeWyrm** [comment]
None of the mods listed should do this either, Reika. I've played with all of them... hell you've got every damn one of those on the Dev server, don't you? Except InvTweaks, and I've used that so no go there.

**Comment by ReikaKalseki** [comment]
We do not have InventoryTweaks.

**Comment by Turmfalke2** [comment]
Not sure whether that is related, but I just noticed the entries in 'Chroma_Progression' or doublicated, I apparently have 136 Chroma_Progression entries and several of them are called PYLON.

**Comment by ReikaKalseki** [comment]
WTF?

**Comment by Turmfalke2** [comment]
Yes.. not exactly sure what to make of that. It has incrementing index numbers, so I presume you are somehow adding the progression flag even though the player has it? I can post the output from /playernbt when I come home from work.

**Comment by ReikaKalseki** [comment]
The numbers are vanilla NBTTagList formatting, and my system is explicitly designed not to give progression if you already have it. On top of that, you are the first to report anything like it. Furthermore, multiple of a progression in and of itself will break nothing.

**Comment by Turmfalke2** [comment]
http://pastebin.com/sDmAt91S
The castingprog looks fine to me, maybe it was related to the old forge version I was using prior to the update?
I suggest closing this and I will occasionally check my nbt data and reopen if the issue is still around.
