### ISSUE TITLE
gravel launcher eats power but doesn't fire when entity is covered by a block such as grass

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#89]
I was testing this on wither bosses for the hell of it and found that if the entity is blocked by a grass "block" it will consume power but not fire.

**Comment by ReikaKalseki** [comment]
Post a screenshot at the exact moment of firing so I can see the raytrace.

**Comment by Zedrimar** [comment]
here; a fraction of a second after firing
![2015-06-09_18 07 16](https://cloud.githubusercontent.com/assets/8153290/8073327/3b12a7ce-0ed8-11e5-9cd4-7f4405f5b269.png)

**Comment by ReikaKalseki** [comment]
So tall grass, not grass blocks? Does it happen with other "soft" blocks like vines? Does it _only_ happen with such soft blocks?

**Comment by Zedrimar** [comment]
I will go test with more then! :P

**Comment by Zedrimar** [comment]
@ReikaKalseki not block specific, even bedrock did the trick!
![2015-06-09_19 11 44](https://cloud.githubusercontent.com/assets/8153290/8073553/88f96524-0edb-11e5-916e-d54a4331de30.png)

seems that if the tile's hitbox is not a full block and there is an living entity behind it, this does not apply and the launcher shoots fine

**Comment by ReikaKalseki** [comment]
Derp. Fixed.

**Comment by Zedrimar** [comment]
:D
