### ISSUE TITLE
Enchantment decomposer is research level basic

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#892]
hi,
Currently the enchantment decomposer is research level basic and just requires that the played has the make chroma progress, but the relay required to power it is research level networking. I kinda like that the need to power the decomposer motives the discovery of the item relay, but realisticly there is quite a bit content between the player getting access to the decomposer and him actually being able to use it. Maybe there could be an inferior way of powering it?

**Comment by TomeWyrm** [comment]
There's a couple of those kinds of research actually. Bit of a limitation of the system used.

**Comment by Turmfalke2** [comment]
Yes, but usually it isn't that extreme. I made a decomposer directly after making the enchanter in the hope of it being an alternative way of get the chroma for the enchanter.

**Comment by TomeWyrm** [comment]
_cough_repeaters_cough_

**Comment by ReikaKalseki** [comment]
More expensive now.

**Comment by TomeWyrm** [comment]
Put a post-networking material in it?

**Comment by ReikaKalseki** [comment]
I stuck a rune in the recipe.
