### ISSUE TITLE
Server crashes when extracting Osmium in an extractor.

### ISSUE THREAD

**Issue by jared-mason** [ReikaKalseki/Reika_Mods_Issues#893]
I am curently hoasting a custom modpack for a small group of friends. One of them recently decided to make an extractor and tried to extract osmium ore. The server then imediatly crashed. Anytime that chunk is reloaded the server crashes. 

Crash log http://pastebin.com/mCENH1KT

**Comment by ReikaKalseki** [comment]
`tile.null:6`

Is Mekanism ore broken? Check your logs for reflective failures.

**Comment by jared-mason** [comment]
The ore itself seems to work in other machines from other mods. I honestly don't know much about programming to fully understand the crash log. I was hoping someone here could help.

**Comment by ReikaKalseki** [comment]
Again, 

> Check your logs for reflective failures.

**Comment by jared-mason** [comment]
Update: Iron Ore also causes it to crash

Crash log: http://pastebin.com/PbbCUc8E

**Comment by jared-mason** [comment]
Update #2:  Seems it was a conflict with Voltz Engine/ICBM. After removing those mods it now works.

**Comment by TomeWyrm** [comment]
Oh joy, UE is at it again. Have you reported the conflict to the Voltz team?
