### ISSUE TITLE
[RotaryCraft Feature Request] Some way to heat composter to required level other than placement

### ISSUE THREAD

**Issue by mystise** [ReikaKalseki/Reika_Mods_Issues#896]
As far as I can tell, the only two methods in RoC to heat things (the heater and the friction heater) don't work on the composter. In addition, the heat lamp from ChC doesn't attach to any face. Because of this, getting the composter to the required heat for it to function is entirely dependent on its position in world.

**Comment by ReikaKalseki** [comment]
Try fire.

**Comment by amesgen** [comment]
and attach cooling fins when the desired temperature is reached

**Comment by mystise** [comment]
Yeah, that makes sense. I don't see why the heat lamp and the heater don't work, but at least there is a way. :) Thanks
