### ISSUE TITLE
[Chromaticraft] Possible race condition in ChunkProviderChroma::finishGeneration

### ISSUE THREAD

**Issue by KevTheCrafter** [ReikaKalseki/Reika_Mods_Issues#897]
Hi Reika,

i found a possible race condition in ChunkProviderChroma::finishGeneration.
It seems very hardware specific. It only appears on one of three servers and only with a chance of about 20% during server start.

I see this bug in two variations.
One is in the log below. All threads are started, two are finished (maybe?) at the same time and boime-generator ended in an endless loop in 'BiomeDistributor::addStructureBiomes'.
The other variation is, that all three generation are finished and the server also stuck at loading DIM60.

Possible solution: Make finishGeneration synchronized?

If you need more information, I would recompile CC my self to log the value of generationFlags.

Log:

> [04:02:56] [ChromatiCraft Dimension Structure/INFO] [FML/ChromatiCraft]: CHROMATICRAFT: Initializing Dimension Structure generation thread...
> [04:02:56] [ChromatiCraft Dimension Biome/INFO] [FML/ChromatiCraft]: CHROMATICRAFT: Initializing Dimension Biome generation thread...
> [04:02:56] [ChromatiCraft Dimension Region/INFO] [FML/ChromatiCraft]: CHROMATICRAFT: Initializing Dimension Region generation thread...
> [04:02:57] [ChromatiCraft Dimension Region/INFO] [FML/ChromatiCraft]: CHROMATICRAFT: Dimension Region generation thread complete; Elapsed time: 1,174s. Central region created; 16222.502463815057 +/- 650.0
> [04:02:57] [ChromatiCraft Dimension Structure/INFO] [FML/ChromatiCraft]: CHROMATICRAFT: Dimension Structure generation thread complete; Elapsed time: 1,571s. 16 structures generated.
> [04:03:05] [ChromatiCraft Dimension Biome/INFO] [FML/ChromatiCraft]: CHROMATICRAFT: Waiting for structure generator to finish to place relevant biomes...
> [04:04:19] [Server thread/INFO] [FML/]: CHROMATICRAFT: Pausing main server thread, since it tried to load the CC dimension, which is not yet ready. Total delay so far: 5 ms
> [04:04:19] [Server thread/INFO] [FML/]: CHROMATICRAFT: Pausing main server thread, since it tried to load the CC dimension, which is not yet ready. Total delay so far: 15 ms
> [...]
> [10:36:44] [Server thread/INFO] [FML/]: CHROMATICRAFT: Pausing main server thread, since it tried to load the CC dimension, which is not yet ready. Total delay so far: 23543835 ms

(There are over 200 mods, so the full log has over 100k lines - if you need the full log, i can upload it)

**Comment by ReikaKalseki** [comment]
Welcome to threading. Done.
