### ISSUE TITLE
[Suggestion] Shaft Power Transfer with Draconic Portals 

### ISSUE THREAD

**Issue by amesgen** [ReikaKalseki/Reika_Mods_Issues#899]
Currentely, RotaryCraft supports Mystcraft-portals and the Netherportal in order to transfer Shaft Power interdimensionally. It would be awesome if you could support the portals from Draconic Evolution; here a few reasons:
- obviously, support for a new mod (integrations are always nice)
- obtaining and building these portals is more difficult than their Mystcraft counterpart, which is nice because inter-dimensional power transfer should be considered to be late-game
- ability to gate this mechanic behind certain late-game materials, as Draconium Infused Obsidian can not be found (like Mystcraft Crystals), and everyone could modify its recipe (or the recipe of the Dislocator Receptable/ the Charm of Dislocation) to include e.g. Sintered Tungsten Ingots or Bedrock Alloy Ingots etc.

**Comment by ReikaKalseki** [comment]
Are these just basic portals (like vanilla or MystCraft)? This being DE, however, would that come with the expectation, requirement, or implementation of something dumb like built-in power amplification or native DE shaft power generation?

**Comment by Kreidos** [comment]
I thought Draconic portals teleported the player to specific dimension/coordinates. They don't 'link' to another portal. 

Edit: Of course, power could be sent to these arbitrary coordinates but that seems dumb.

**Comment by ReikaKalseki** [comment]
> power could be sent to these arbitrary coordinates but that seems dumb.

No, that is not even possible. There needs to be a bidirectional portal at both ends.

**Comment by amesgen** [comment]
Sorry, I thought this would be possible to check whether the "target block" of the portal is a shaft power  consumer. Maybe a very simple RotaryCraft "reciever"-type block could work?

**Comment by amesgen** [comment]
> This being DE, however, would that come with the expectation, requirement, or implementation of something dumb like built-in power amplification or native DE shaft power generation?

No, I don't think that would really suit to the theme of "Draconic Evolution", as Draconic Evolution is "magic-tech" mod (not realistic). Therefore, sth that is not possible in real life (-> transfering mechanical power over a "portal"), could have its place in DE, but not sth like shaft power generation or even amplification (yeah that would be dumb).

**Comment by ReikaKalseki** [comment]
> Sorry, I thought this would be possible to check whether the "target block" of the portal is a shaft power consumer. Maybe a very simple RotaryCraft "reciever"-type block could work?

That is not how the power system works. It cannot send; it receives, propagating up the chain to an engine.

> No, I don't think that would really suit to the theme of "Draconic Evolution", as Draconic Evolution is "magic-tech" mod (not realistic).

That was more a shot at DE's notoriety as "I have interaction with thing X? I _have_ to eclipse the source for power!".

**Comment by amesgen** [comment]
Thanks for the explanation. Keep up the good work!
