### ISSUE TITLE
Rotorycraft: 6f occasional chat spam when clicking bedrock pick under tools section in the handbook

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#90]
pic: 
![2015-06-08_22 27 17](https://cloud.githubusercontent.com/assets/8153290/8072065/cccf39ec-0ec5-11e5-9b89-23862416f09c.png)

still shows info, but shows spam

**Comment by ReikaKalseki** [comment]
Fixed.
