### ISSUE TITLE
Fix the incompatible mod exception to show the mods involved

### ISSUE THREAD

**Issue by mezz** [ReikaKalseki/Reika_Mods_Issues#900]
https://github.com/Chisel-Team/Chisel/issues/157
First, nuke these idiots spamming the issue from space ^

Next, actually make the exception show which mods don't like each other.
Right now it has no information, even the stack trace is about nothing.

**Comment by Drullkus** [comment]
I'm not even sure what they're trying to accomplish from [spamming several repositories' issue trackers](https://github.com/search?p=1&q=%22Can%27t+load+with+Dragonapi%22&ref=searchresults&type=Issues&utf8=✓).

**Comment by ReikaKalseki** [comment]
That exception's output does not look like what they claim it does.

https://github.com/ReikaKalseki/DragonAPI/blob/master/Exception/ModIncompatibilityException.java

**Comment by freyskol** [comment]
They've got a vendetta against Reika.

**Comment by 1Matthias** [comment]
It does not crash the game. They are spamming and attempting to execute a smear campaign.

**Comment by Builderb0y** [comment]
That's because that line of code doesn't exist. DragonAPIInit.java:204 is an import, and ModIncompatibilityException.java is only 47 lines long, not 58.

**Comment by Drullkus** [comment]
@freyskol Based on their posting history, I agree

**Comment by minecreatr** [comment]
Whelp, I guess some people DO survive off of the suffering of others.

**Comment by DarkGuardsman** [comment]
Ignore everything, watch this https://www.youtube.com/watch?v=ANhQZvdNphg

**Comment by minecreatr** [comment]
And the github acounts are gone....

**Comment by TomeWyrm** [comment]
So, did anyone copy what that looked like for those of us that were at work when this happened?

**Comment by mezz** [comment]
> Hello can you help figure out this issue blah blah
> DragonAPI stack trace without the one useful line that says which mods are involved in the conflict.

Pasted to 
every
single
modded minecraft github issue tracker.

So many people reported the idiots doing it, I assume they were nuked by Github shortly after this issue was made.

**Comment by 1Matthias** [comment]
Do you happen to have the full, exact text of the issue? I would like to use it for something.

**Comment by mezz** [comment]
I don't, unfortunately.

**Comment by Drullkus** [comment]
If you need it for something legal, I guess you could make a case to the github team.

**Comment by redelman** [comment]
Turns out I still had a Chrome tab open of the issue on the chisel teams
github, so I took a couple screenshots. I will give an imgur link to anyone
that wants it.

**Comment by 1Matthias** [comment]
I would love a screenshot. Thank you so much.

**Comment by TomeWyrm** [comment]
Oh, yes please. Via PM on Reddit or FTBForums if possible?

**Comment by 1Matthias** [comment]
Mind just posting it here, for posterity? Thank you!

**Comment by Drullkus** [comment]
Yes, I would like it if the screenshots were posted here :)

**Comment by Duckfan77** [comment]
A link here would be appreciated, but if you won't, I'd like a pm over on the minecraft forums or FTBforums under the same name.

**Comment by redelman** [comment]
As requested.

![image](https://cloud.githubusercontent.com/assets/73338/15768520/43d98e90-2917-11e6-9eb3-6a496e76488d.png)
![image](https://cloud.githubusercontent.com/assets/73338/15768521/43ee8494-2917-11e6-8998-7c977fd833f6.png)

**Comment by TomeWyrm** [comment]
AH! That guy. He was probably pissed off at what happened in #860

The relevant parts of the conversation are here: http://i.imgur.com/gx0l03P.png

Because his account and that of the other admin were banned from github, it purged their comments.

**Comment by Drullkus** [comment]
"Take a moment and consider what you're doing wrong." 😂

The link went to the git search page where I found all of their spammed Git Issues and if they're saying one of Rieka's mods have issues with 21 mods, they needed to take a moment and consider. >.>

**Comment by 1Matthias** [comment]
Thank you. I have a plan now. ;D

**Comment by ReikaKalseki** [comment]
> Rieka's mods have issues with 21 mods

Several of which I have _explicit compatibility or interaction features_ for....

**Comment by DaMachinator** [comment]
Bookmarked, this should make good a netiquette education resource...
