### ISSUE TITLE
V14 - CoFH Core doing something.

### ISSUE THREAD

**Issue by Shadows-of-Fire** [ReikaKalseki/Reika_Mods_Issues#901]
https://gist.github.com/Shadows-of-Fire/ffb42f40cc9a61108879e331131668f8
I updated to V14 and well, this happened. I'm not entirely sure what happened, as I've never seen this before.

[FML-Client-Latest.log](https://gist.github.com/Shadows-of-Fire/3a8a07643e720f640730e37086a4bd9e)
This was on a default world. Currently testing with Realistic, BiomesOP, and Superflat.
Update: Realistic works. Default also works. Now I'm just completely unsure of what happened there.
Update 2: Its not tied to the world type, the world itself, or the world seed.  This seems to have been purely random.
Update 3: Happened [again](https://gist.github.com/Shadows-of-Fire/7bfb2ce0fd11f82d61989f5adadf4ab8). This time seems unrelated to the last, but it was on a Realistic (RTG) world type.

**Comment by ReikaKalseki** [comment]
Lava rock generation again... is this common?

**Comment by Shadows-of-Fire** [comment]
Semi Common. I've only had it happen twice since installing, and it only seems to occur on first generation of the world. After the crash, re-entering the world is fine. I've made about 8 world on varying settings so far.

**Comment by Shadows-of-Fire** [comment]
Cave Control seems to also weigh in here. I wasnt using it before with v13, but I am now with v14.  It was unsual before but it seems more common after increasing the size of caves with CC.
I realize this is probably just because there's more lava.

**Comment by ReikaKalseki** [comment]
Hopefully fixed.
