### ISSUE TITLE
With RotaryCraft v14/AOBD, Server crash

### ISSUE THREAD

**Issue by pikkon38** [ReikaKalseki/Reika_Mods_Issues#902]
I just added RotaryCraft to my server and it appears to be conflicting with AOBD. I am not sure if this is a RC bug or an AOBD bug. But the crash report references both.

[crash-2016-06-01_19.48.17-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/294745/crash-2016-06-01_19.48.17-server.txt)

**Comment by Shadows-of-Fire** [comment]
Looks more like Reika changed an API.  Report it to ganymedes.

**Comment by pikkon38** [comment]
I reported it as well to ganymedes.

**Comment by ReikaKalseki** [comment]
He needs to update his copy of the RC API.

**Comment by pikkon38** [comment]
The workaround for this is to turn all RotaryCraft support off in the AOBD config file. Change all isntances of "B:RotaryCraft=true" to "B:RotaryCraft=false". Reika does a good job of supporting many different ores from many mods. So changing this to false really wont hurt much of anything in terms of gameplay.
