### ISSUE TITLE
[Rotorycraft] Jetpacks in 3D one day perhaps?

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#903]
Could you possibly consider making 3D models for the jetpacks some day? Quite honestly I think the 2D versions are somewhat boring.... Maybe even some particles too?

If I missed something or the jetpacks were meant to stay that way then close this and please tell me the reason.

**Comment by ReikaKalseki** [comment]
Not worth the effort.

**Comment by Zedrimar** [comment]
Dang.... well it was worth a shot! :P

**Comment by 1Matthias** [comment]
I do have to say, it would be really neat to have them in 3D.

**Comment by TomeWyrm** [comment]
It would, but it really is a lot of effort for something you personally will never see on yourself, and would probably only rarely see on servers. Custom renders aren't exactly easy after all.

**Comment by Zedrimar** [comment]
Yeah I understand, I was just curious :P
