### ISSUE TITLE
Crash after update to Electricraft 14a

### ISSUE THREAD

**Issue by BakermanLP** [ReikaKalseki/Reika_Mods_Issues#904]
I've loaded my old world and got after a few seconds a crash and minecraft ended.

Here is the full logfile:
https://paste.ee/p/wLBGh

Full mod list:
https://github.com/BakermanLP/ProjectRETv8/blob/master/Versions.md

**Comment by ReikaKalseki** [comment]
Try breaking and replacing all ElC RF cables.

**Comment by BakermanLP** [comment]
I have deleted all cables in the old version, switched to the new ElectriCraft version and ... no crash. But I think, that is not a good update path, just my opinion.

**Comment by ReikaKalseki** [comment]
Do newly-placed cables crash?

**Comment by ReikaKalseki** [comment]
Fixed.
