### ISSUE TITLE
[ChromatiCraft] Crash when opening game with ChromatiCraft v14a

### ISSUE THREAD

**Issue by 3TUSK** [ReikaKalseki/Reika_Mods_Issues#905]
[Crash report](http://paste.ee/p/IAauE) is here. No idea about how that happened.
Also reproduced by @J-swl

**Comment by ReikaKalseki** [comment]
Does this happen every time? It loaded fine for me.

**Comment by ReikaKalseki** [comment]
I put some code in to prevent this from happening, even though it makes no sense.

**Comment by 3TUSK** [comment]
I tried three times, but still no luck. 
Also I wonder whether the network I used matter or not... I did re-download the mod once but that didn't change anything for me.
Anyhow thanks for help!
