### ISSUE TITLE
After 14a update, it crashes while starting

### ISSUE THREAD

**Issue by decrobyron** [ReikaKalseki/Reika_Mods_Issues#906]
https://paste.ee/p/Rz6cZ

Probably AOBD related I think.

**Comment by decrobyron** [comment]
I found same issue closed in closed issue section. (https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/902)
I'll check with AOBD mod writer. Please consider it as closed. 
Thank you.

**Comment by TomeWyrm** [comment]
Linking the relevant issue for AOBD: ganymedes01/Another-One-Bites-the-Dust#125
