### ISSUE TITLE
incorrect "enchanted" overlay on bedpick in NEI rotorycraft 6f

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#91]
pic:

![2015-06-08_22 34 36](https://cloud.githubusercontent.com/assets/8153290/8072171/55454c98-0ec7-11e5-9dc8-02eff475b0e4.png)

**Comment by ReikaKalseki** [comment]
You are mousing over the ammo, not the pickaxe.

**Comment by Zedrimar** [comment]
I will get a better pic then, the issue is real though

**Comment by ReikaKalseki** [comment]
OK, this is a known bug and I have not been able to fix it.

**Comment by Zedrimar** [comment]
sooo its fixed but not fixed, apparently it only happens on some occasions other wise it appears normal like this pic
![2015-06-09_18 10 35](https://cloud.githubusercontent.com/assets/8153290/8073323/1aebe5be-0ed8-11e5-8a3c-4b6e49e9ba00.png)

**Comment by Zedrimar** [comment]
hard to see but it did happen. Meh either way its not a major bug luckily.
