### ISSUE TITLE
Minecraft will not launch after updating to V14

### ISSUE THREAD

**Issue by TemplarThano** [ReikaKalseki/Reika_Mods_Issues#910]
not even 100% sure DragonAPI is even directly causing the crash but its the only mod called out in the log and the crash only happens after updating so here I am.

Log: http://paste.atlauncher.com/view/22bb37e9

V13b launches no problem with nothing else changed 
I re-downloaded DragonAPI just in case it was corrupted somehow but still no go 
I tried a previous version of Java because I had updated it today so wanted to make sure that wasnt the cause, still no go

out of Ideas, any help would be appreciated

**Comment by redelman** [comment]
Update fastcraft to 1.23

**Comment by TemplarThano** [comment]
That worked, Thanks.

out of curiosity how did you know that it was fastcraft that was the issue? i didn't see any mention of it in the log

**Comment by redelman** [comment]
I had the same issue on Reika's dev server after I upgraded fastcraft to
1.23. Something changed between fastcraft 1.21 and 1.23 where Reika's ASM
wouldn't work anymore. So he updated his ASM to work with fastcraft 1.23,
which as a result broke anything below that version.

**Comment by redelman** [comment]
I don't really feel right tagging this with "Installation Error" since I don't believe Reika mentioned that fastcraft must be updated to 1.23, if it is being used.

**Comment by TemplarThano** [comment]
I don't believe he did mention it, maybe he could add a note to the changelog on his page mentioning it?

**Comment by ReikaKalseki** [comment]
Adding now.
