### ISSUE TITLE
v14 update crash DragonAPIMod.basicSetup   EventBus.unregister

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#911]
hi,
Sorry to make another one of these threads, but I couldn't find one with my stacktrace.
http://pastebin.com/HAYnBWiE

**Comment by ReikaKalseki** [comment]
One other person reported this long ago. They disappeared when I asked for more info - they never never said whether it happens once or consistently - and all the code involved is Forge.

**Comment by Turmfalke2** [comment]
well it happened twice now, as in everytime I started it. I could generate a few more logs if that helps?

E:3/3

**Comment by ReikaKalseki** [comment]
Does it happen with the newest version of Forge, and only my mods?

**Comment by ReikaKalseki** [comment]
Wait: Forge 1403? You are not even supposed to be able to load my mods with that version (It needs 1558+, and has for the last six months).

**Comment by Turmfalke2** [comment]
Ah, would be nice to have the required forge version listed on the download page. 1403 worked fine for 13b

**Comment by ReikaKalseki** [comment]
It should not have. v10 and up should have crashed.

**Comment by Turmfalke2** [comment]
well, updated to 10.13.4.1614 and now it works.
