### ISSUE TITLE
Gendustry ReactorCraft support?

### ISSUE THREAD

**Issue by MineWitherMC** [ReikaKalseki/Reika_Mods_Issues#913]
When I load Minecraft with latest mod versions (Forestry 4.2.12.60, Gendustry build 132 - I don't use alphas, DragonAPI 14a, RotaryCraft 14a, ReactorCraft 14a), I get this gem in log:
`[20:07:44] [Client thread/ERROR] [FML/ReactorCraft]: REACTORCRAFT ERROR: Could not add Gendustry integration. Check your versions; if you are up-to-date with both mods, notify Reika.`
This thing didn't happen with ReC v13 (and same Forestry/Gendustry).

**Comment by ReikaKalseki** [comment]
I have not changed that code between v13 and v14. Does nuclear waste still make mutagen?

**Comment by redelman** [comment]
We are using this same version of Gendustry on the dev server and I haven't experienced this issue there.

**Comment by MineWitherMC** [comment]
Next thing I found, this only appears _without BuildCraft_, all is fine with it. However, I can't tell you can Mutagen be created from NW without it as forestry crashes not finding BC Api. Close this if recipe registers w/o BC.

**Comment by ReikaKalseki** [comment]
I have not tried. But that would be on their end, or a classloading failure which can be solved by adding the BC API to the DragonAPI jar.

**Comment by TomeWyrm** [comment]
Heh, it's almost one of those "who plays without NEI?" errors. Just about nobody plays Forestry without BC as far as I know.

Reika is correct though, you can install the BC API to DragonAPI, or possibly as its own mod, I've seen that in some packs, but I'm not sure how that works exactly.
