### ISSUE TITLE
Autocrafting unit working for simple parts crafting, not worktable recipes.

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [ReikaKalseki/Reika_Mods_Issues#915]
Hello,

I place a dc electric engine behind an autocrafting unit, I place 2 patterns, one pattern with base panels crafting and the other with a gearbox in worktable mode, I place a chest on top of the autocrafting unit, i place some hsla ingots, some mounts and the required gears, I press the request button and it's crafting the base panel but not the gearbox. Basically is not pulling the items from the above chest for worktable recipes.

Should you want to check the mod list: https://docs.google.com/spreadsheets/d/1hmepiBej8YqusLC4Ab5_JlIf7Y9Cyww_vEzddCVJcdk/edit#gid=0

Or would you rather prefer a small video/gif to see if I'm doing anything wrong?

Thank you for your time.

**Comment by ReikaKalseki** [comment]
The autocrafter cannot do worktable recipes.

**Comment by Ganjalf-Amsterdoom** [comment]
But I've seen it working in this video https://www.youtube.com/watch?v=MR-bD-tg7Cw

A little after minute 4.00.

Was it an old version and was removed?

**Comment by ReikaKalseki** [comment]
No, it could never do worktable recipes, and they changed a config.

**Comment by TomeWyrm** [comment]
There's a config to enable worktable recipes in normal crafting tables... I think.

**Comment by Ganjalf-Amsterdoom** [comment]
Ok, I see, thank you for the reply and pardon to have bothered, I like the worktable and I wouldn't trade it for a crafting table, meaning I wouldn't turn the config to craft machines in the crafting table on, i'll live with that.
