### ISSUE TITLE
AnotherOneBitesTheDust and RotaryCraft/DragonAPI crashing on launch

### ISSUE THREAD

**Issue by Volen1** [ReikaKalseki/Reika_Mods_Issues#916]
I'm not good with Crashlogs, but this wasn't happening before I updated your mods to v14b, was previously using v13\* 

Crashlog: http://pastebin.com/vsT83z9M

**Comment by ReikaKalseki** [comment]
You are also not good at checking. Quadruplicate. #902 #906 #914

**Comment by TomeWyrm** [comment]
Linking the relevant issue for AOBD: ganymedes01/Another-One-Bites-the-Dust#125
