### ISSUE TITLE
Geostrata Vent Crash

### ISSUE THREAD

**Issue by rockachu2** [ReikaKalseki/Reika_Mods_Issues#917]
[latest-2.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/296739/latest-2.txt)
I'll be worldediting the block out, but I've still got the relevant save. There are a _lot_ of mods here, so it could be nearly anything.

It's not 100% up to date, but there's nothing related in the changelog so I figured I should post it.

**Comment by Shadows-of-Fire** [comment]
Also getting an issue that seems related to Vents, while loading a v13 world.
https://gist.github.com/Shadows-of-Fire/5886a12b940dd2c7d0aec00dcc109956
The fact that it mentions the OreTile is odd to me, as I have them disabled.

**Comment by ReikaKalseki** [comment]
BlockID corrupution, with @rockachu2 issue likely being Glenn's Gases again.

**Comment by Shadows-of-Fire** [comment]
The thing is mine was in a superflat.  And as far as I had seen, vents dont generate there.

**Comment by ReikaKalseki** [comment]
That does not prevent ID corruption.
