### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by Rubyheart** [ReikaKalseki/Reika_Mods_Issues#918]
http://paste.ee/p/RJjge

Version 14b, it doesn't even get to where it should crash because of AOBD, it completely fails to start at all.

**Comment by redelman** [comment]
Update fastcraft to 1.23

**Comment by Rubyheart** [comment]
Beautiful, thank you.  I'm still learning to read logs, where does it mention that it was an issue with fastcraft?

**Comment by redelman** [comment]
It's not really obvious, but DragonAPI mentions it doesn't find fastcraft, so it applies some ASM to a function that fastcraft later attempts to do the same thing to, and fails.

**Comment by Rubyheart** [comment]
Yeah, I read some of the other recently closed issues just now, and reread the changelogs for V14a and I see it now.  My mistake entirely.

**Comment by redelman** [comment]
It wasn't in the changelog originally. Was a small oversight there.
