### ISSUE TITLE
AOBD RotaryCraft incompatibility 

### ISSUE THREAD

**Issue by Solace7** [ReikaKalseki/Reika_Mods_Issues#919]
I get this crash when loading up with RotaryCraft AND AOBD(Another Ore Bites the Dust)
AOBD | 2.9.1
RotaryCraft 14b
DragonAPI 14b

Crash log
https://gist.github.com/Solace7/9bb4ff8e55fe4973451959fbefae16f4

**Comment by ReikaKalseki** [comment]
Seriously?

#902 #906 #914 #916

**Comment by TomeWyrm** [comment]
Linking the relevant issue for AOBD: ganymedes01/Another-One-Bites-the-Dust#125
