### ISSUE TITLE
Chromability pylon surge protection not working?

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#922]
hi,
I did the pylon surge protection ritual twice (stood on it, got lifted in the air and thrown out again), but I still get zapped by the pylons. Am I missing something? The picture of the ability is light up in the middle mouse button menu.

Using 14b.

**Comment by ghost** [comment]
Go into the ability select menu (middle mouse) and click on the bar above pylon surge protection. That way the ability will activate. Also note that the bar (on some abilities) can select the "power" into it by using up or down arrow keys.

**Comment by Turmfalke2** [comment]
OH, thank you didn't knew I had to activate it.

**Comment by ReikaKalseki** [comment]
Note that the main intended means of navigating the GUI is by the scroll wheel (CTRL moves the active region to the power bar). But yes, arrow keys and the Pg/End/Home group can also be used.
