### ISSUE TITLE
[Suggestion] Steam Gate

### ISSUE THREAD

**Issue by amesgen** [ReikaKalseki/Reika_Mods_Issues#923]
What about a redstone-controlled steam gate? A few reasons:
- realism: I don't think it is common praxis to break steam lines in order shut down turbines
- interesting new interactions: computer turns the steam gate off when the steam level drops below a certain value / the main energy storage is empty / just automation things
- balance option (just an idea): make the steam gate explode if there is too much steam (-> pressure)

**Comment by ghost** [comment]
The steam vent can be disabled with redstone.

**Comment by amesgen** [comment]
yes, but this does not work for high-pressure turbines afaik and you have to do it for every single turbine.

**Comment by redelman** [comment]
It does work for HP turbines. Put the redstone on a steam injector. You
don't have to do it for every turbine. You could easily just use wireless
redstone or run redstone to each turbing from a single lever.

**Comment by amesgen** [comment]
Thanks a lot for that information! Where can someone find information like this? Is there a certain website=

**Comment by freyskol** [comment]
im a derp

**Comment by TomeWyrm** [comment]
Incidentally, it's "practice" not "praxis" which means something completely different.

**Comment by ReikaKalseki** [comment]
What does "praxis" mean?

**Comment by TomeWyrm** [comment]
https://en.wikipedia.org/wiki/Praxis_%28process%29

**Comment by amesgen** [comment]
"Praxis" is a german word, and sounds similiar to "practice".

**Comment by TomeWyrm** [comment]
Sound ≠ meaning. If it did, we would not have homophones... and we would also have quite a few more words. At least praxis means practice in German (didn't think to try another language, as the rest was quite good English), but I make it a point to try and educate when I see things that look like honest mistakes. No harm or offense meant, just trying to help you communicate more effectively in the future :-)

**Comment by amesgen** [comment]
The sound-meaning part is so true... yes, that is very nice. Next year, I have my A levels ("Abitur"), and I am happy about every mistake I make now and not in the exams.
