### ISSUE TITLE
Crash with Electricraft RF Transfer Cable

### ISSUE THREAD

**Issue by Kuderion** [ReikaKalseki/Reika_Mods_Issues#925]
Hello,
when I place an RF Transfer Cable next to anything like machines (from Rotarycraft, Thermal Expansion, Ender IO) or even something like forestry apiaries the game crashes and the world can't be loaded without the game crashing again with the same error.
Placing the cable next to any RF Conduit or an Electricraft RF Battery doesnt cause any problem, but anything that transfers anything else (like Rotarycraft's liquid pipes) or an ender ios storage bank crashes.
It doesn't matter if I place the cable first or last.
This crash is repeatable (create new world, place rf cable, place machine next to it, minecraft crashes)

Crash-Log: https://gist.github.com/Kuderion/bbbb9445dd6b163ee491b5c14390a83f

**Comment by ReikaKalseki** [comment]
Fixed.
