### ISSUE TITLE
Reika crash after placing pipe

### ISSUE THREAD

**Issue by slappertins** [ReikaKalseki/Reika_Mods_Issues#926]
heya iv been playing for awhile and had no problems but iv been making a reactor but everytime i place a pipe above the fourth toroid magnet the game crashes (also crashes server) here is a image what we i get when i re-log (http://imgur.com/wyOeZaG) and here is a crashreport from the time this happened (http://pastebin.com/G9ufZjBZ)
i also have a second problem, iv had since i added the mods to the server, the server takes up to ten minutes to boot i dont know why but when i remove the mods it starts in a matter of seconds, server console (http://pastebin.com/r8bwiLnD) (90% of the log - thats as far back as it goes)

**Comment by Turmfalke2** [comment]
Try putting a chest there instead of the pipe, break it and then try placing a pipe again.

**Comment by slappertins** [comment]
i can place a chest there but still when i try replace it the game crashes

**Comment by ReikaKalseki** [comment]
Try putting an actual hose.

**Comment by slappertins** [comment]
Im guessing that your talking about a lubricant hose? (the only item with the word hose) but it also is corrupting world file.

**Comment by slappertins** [comment]
nwm  i can place lubrication hoses if thats what your meaning,

**Comment by ReikaKalseki** [comment]
Then this sounds like another metadata-fail issue. Do you have RailCraft hidden blocks?

**Comment by slappertins** [comment]
nope?

**Comment by slappertins** [comment]
if its conflicting with any other mods i can try be flexible and remove them, it would just be nice to keep the pack the way it is :P

**Comment by ReikaKalseki** [comment]
Try removing mods.

**Comment by slappertins** [comment]
know of any mods that i should try removing?

**Comment by slappertins** [comment]
iv removed a bunch of mods and still happening...

**Comment by ReikaKalseki** [comment]
Keep removing.

**Comment by slappertins** [comment]
removed all the mods all the way down to only your mods and was still crashing on that one map, but i went on a flat land and re made it and i dont crash?

**Comment by slappertins** [comment]
so i set up the rings out side above ground and it didnt crash

**Comment by ReikaKalseki** [comment]
.....

**Comment by ReikaKalseki** [comment]
I just found [this](http://forum.feed-the-beast.com/threads/reika-game-crashing-after-placing-an-item.157473/).

You are on 1.6.4, a version discontinued two years ago, and you come for support, and **never** mentioned your game version?

**Comment by redelman** [comment]
To be fair, the minecraft version used is in the log. But yes, it should
have been mentioned in the original report, along with the version of the
mods.
