### ISSUE TITLE
Pylon not reactivating on reconstruction

### ISSUE THREAD

**Issue by Xavion3** [ReikaKalseki/Reika_Mods_Issues#927]
Pylons are failing to reactivate after being destroyed and repaired, no humming sounds or zapping, and even after days no energy to drain. Screenshots of a pylon that had a crystal stone destroyed by worldgen and I've since replaced [here](http://imgur.com/a/y8mBF).

In addition creating a new world and destroying and then replacing a block of a functional pylon breaks it and causes it to sit there not humming or attacking, I waited next to it for several minutes with no signs of change.

Modlist is [here](http://pastebin.com/Jre6yRaR).

**Comment by Turmfalke2** [comment]
Try standing in the chunk with the pylon and type '/printcrystalnet'. It should print something to log about whether the structure is complete, the energy it has and whether it is boosted or not.

**Comment by Xavion3** [comment]
So tried it in the new world with the pylon I just destroyed and replaced a block from. Reported as follows.

```
[20:33:22] [Server thread/INFO]: DIM0:
[20:33:22] [Server thread/INFO]: 1# [(99, 78, 343 in DIM0 @ YELLOW Pylon [0/180000], Struct=false, Turbo=false)]
```

This is a pylon where I all I did was mine one stone column and then put it back down, and it was working before.

Then flew off to another pylon to test more, started giving this as the result of the command. This was standing right next to another pylon that had yet to be tampered with.

`[20:36:02] [Server thread/INFO]: []`

Restarting the world did not help, breaking and replacing a rune changed nothing. That consistently showed up whenever I did the command.

Heading off to yet another pylon gave the following where it started working again.

`[20:46:45] [Server thread/INFO]: DIM0:
[20:46:45] [Server thread/INFO]: 1# [(179, 84, 539 in DIM0 @ PURPLE Pylon [180000/180000], Struct=true, Turbo=false)]`

Breaking one of the runes gave the following.

```
[20:51:00] [Server thread/INFO]: DIM0:
[20:51:00] [Server thread/INFO]: 1# [(179, 84, 539 in DIM0 @ PURPLE Pylon [0/180000], Struct=false, Turbo=false)]
```

And putting it back changed nothing, I waited for five minutes next to the pylon and still no change in the message.

**Comment by Turmfalke2** [comment]
By default '/printcrystalnet' only checks the current chunk, with '/printcrystalnet  \* x z' you can check a larger area. Unfortunately I have no idea what is causing your issue. What happens to the yellow pylon if you reload the world?

**Comment by Xavion3** [comment]
That makes sense why it wasn't showing anything yeah, must've just been a little too far away. I've reloaded the world as mentioned and it doesn't appear to change, plus while I forgot to mention it the screenshots are from a server I'm on so it's no specific to either SSP or SMP and doesn't seem to be a computer specific issue.

Going through the pack right now to try and figure out if it's a certain combo of mods doing it.

**Comment by Turmfalke2** [comment]
In case of a server you might have to restart the server, by default the pylons chunk load them self once used.

**Comment by Xavion3** [comment]
Server has been restarted several times as I repaired the pylon a few days ago, had to have restarted at least twice for the v14a and v14b updates and I know its done it more than just that.

**Comment by Turmfalke2** [comment]
Looked at the relevant code again. When you place any of the crystalline stones, it checks for all other similar stones that could form a structure around it, finds the centre of it and search for tile entities. Once it finds the pylon's tile entity it compares the structure in the world with how it is supposed to look like (including the colour) and then considers it formed and with that ready for work.  
Somehow this does not appear to propagate through in your case. My best bet currently is that something is replacing the crystalline stone and prevents it from calling triggerAddCheck, because from the printcrystalnet command it looks like the title entity is fine.  
Since you are testing this on a server you could have some protection mod that is overwriting onBlockAdded?

**Comment by Xavion3** [comment]
As said this occurs both on a server and in a single player world for me, I'm currently slowly wading through the modest to look for causes. I've at least tested the minimal case and pylons do correctly and promptly reform if I drop down to just chromaticraft and dragonapi with no other mods, slow going removing chunks of mods and restarting repeatedly though.

As far as protection mods, we have nothing afaik, from spawn protection to town plugins it should just be the server compatible version of the modlist I posted above, with the addition of Morpheus anyway.

**Comment by ghost** [comment]
This happens from time to time. Try covering the whole pylon with chroma (or any liquid) and then replace a rune or something. I usually put chroma on top of all eight runes, four pylon focuses and above and below the pylon tile entity. Once the liquid is removed, as said, replace a rune.

**Comment by Xavion3** [comment]
Ok, so I think I've managed to track this down as I've managed to get tests where a pylon will repair, I'll try the problem and it won't, and then I'll remove it and it'll repair again. Once out of several tests it seemed like that wasn't the case so I'm not 100% sure.

It seems however to be railcraft's heat blocks, pylon reactivates fine while standing next to it and not having walked through, doesn't seem to reactivate after traipsing through it, and then seems to reactivate again after using /cofh clearblocks to get rid of any heat blocks. Disabling them and restarting the server also allowed both pylons I'd had issues with to be reactivated, although oddly I had to remove the second layer of crystalline stone that spawned a layer below the normal pylon base before it activated, tried a few times before that and it didn't work but removing the stone seemed to fix it.

**Comment by ReikaKalseki** [comment]
God damn it, RailCraft!

**Comment by Xavion3** [comment]
Looking at code I see [this](https://github.com/ReikaKalseki/ChromatiCraft/blob/60ee519a62aab7e96c471dff121c3fc344625121/Auxiliary/ChromaStructures.java#L2370) which seems to be checking specifically for air blocks, Railcraft marks heat blocks by [overriding the vanilla isAir function](https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/blocks/hidden/BlockHidden.java#L98-L101), they set the material to the same as air too it seems. It looks like this would actually be on your end, for checking whether a block is air by comparing it to the vanilla air block and not by checking isAir or if it has the air material (what the vanilla code appears to do for isAir).

It also looks like it could be a significant pain to change in Chromaticraft (EDIT: or maybe not? I can't find the definition but you seem to be using a central block check function, could you have it so if it's told to check for an air block to check isAir or something instead?), but at least to my inexperienced eye it looks like this is a result of you checking specifically for the vanilla block and not the other signs a block is supposed to be treated as an air block.

**Comment by ReikaKalseki** [comment]
The problem is that block/tile changes are non-atomic, as well as the fact I cannot account for function returns in my BlockArrays.

**Comment by TomeWyrm** [comment]
Can you check both for Railcraft and then railcraft heat block being enabled? If so, my suggestion is to throw an error. Breaking, non-breaking, logged, yell in chat, something. Because the goddamn heat block makes me want to !@#$%^YU%RTHESGAEAW^W&%*URYTEYWQ$@%#^YRUTJHFGDSAEW$#%^&YURTHGDFV

basically :-p

**Comment by Xavion3** [comment]
If it is all air type blocks breaking it then it should be more complex than just railcraft, I'd expect rotarycraft's flood lights or thaumcraft's arcane lamps to be able to break them too. Of course those are much less likely to occur than walking through a pylon, well, if you account for how often railcraft heat blocks are disabled they may actually be more likely (someone decorating a pylon with arcane lamps? I dunno) but yeah, it's all obscure stuff at best.

And yeah, it did look like it would be a pain to have to special case the comparison for air blocks to check isAir instead, for relatively minimal gain too considering near every pack disables the heat blocks because of cases like this where they screw with things which aren't checking that. I don't know enough theory of programming to be entirely sure of what being non-atomic is and how it matters for the multi block check code.

Hopefully at least this issue provides a reference point in the future for anyone having trouble with the multiblocks.

**Comment by Turmfalke2** [comment]
Atomic usually means that it happens in one step with no mixed state existing between that. Usually this is one of features of a database, where you have one transaction that changes multiple tables, without them ever being exposed to read instruction before the last one got changed.

What exactly isn't atomic here I don't know. I would assume that the setBlock function is, but threading in minecraft is pretty unpredictable.

**Comment by TomeWyrm** [comment]
And also concurrent. Which breaks atomicity most of the time

**Comment by ReikaKalseki** [comment]
> I would assume that the setBlock function is

Setting a block and its metadata are. Setting the corresponding TileEntity - which does happen automatically with setBlock - is not. Thus you can get the TileEntity of one block and the BlockID/metadata of another. Though it never ticks in the interim, the renderer can certainly run, which also includes things like hitbox logic and raytracing. This is where most of the "ClassCastException" with a metadata error come in.

Here the issue is simpler. All CC structures use [FilledBlockArray](https://github.com/ReikaKalseki/DragonAPI/blob/master/Instantiable/Data/BlockStruct/FilledBlockArray.java#L46), which is effectively a blueprint (see the lexicon pages, which reference [the same arrays](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Auxiliary/ChromaStructures.java)).

The [pylon structure](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Auxiliary/ChromaStructures.java#L2365) requires air in some locations. This is a location-block map, so it cannot account for Material.air or isAir().

**Comment by Xavion3** [comment]
Right, and presumably adding a special case for [match in BlockKey](https://github.com/ReikaKalseki/DragonAPI/blob/master/Instantiable/Data/Immutable/BlockKey.java#L94-L100) that calls isAir if it's told to match against air blocks would break that because of a potential issue with tile entities that you mentioned?

And that sentence still seems kinda sarcastic sounding to me even after trying to reword it, it's not meant to be. Just interests me as to why you couldn't intercept and add a check, need to do more minecraft modding to really know I suspect.

**Comment by ReikaKalseki** [comment]
BlockKey is used in dozens of places. I am not going to violate the unity matching for one case.

**Comment by Turmfalke2** [comment]
> Setting a block and its metadata are. Setting the corresponding TileEntity - which does happen automatically with setBlock - is not. Thus you can get the TileEntity of one block and the BlockID/metadata of another

That sounds bad.. is the old TileEntity only removed once the new one gets created? I guess this only really matters if you call setBlock with TileEntity on TileEntity, which never happens in vanilla? Is there any code that depends on the delayed the creation tileEntities or is that something a mod could in theory change?

**Comment by ReikaKalseki** [comment]
> I guess this only really matters if you call setBlock with TileEntity on TileEntity, which never happens in vanilla?

Correct, since there are no replaceable TileEntities.
