### ISSUE TITLE
reliably crashing with a ConcurrentModificationException

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#928]
hi,
I have noticed I reliably crash when ever I start a pylon crafting recipe while my pylons are empty. After ~3 Minutes the game crashes - every single time.
I know these ConcurrentModificationExceptions are kind of tricky, but maybe having a way to reproduce them might help?

E: http://pastebin.com/LwiWadyN

**Comment by ReikaKalseki** [comment]
Though crystal networking has been linked to CMEs before - [example](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/871) - and some hints like GC version and Optifine multithreading have been found, your issue is entirely in vanilla code.
