### ISSUE TITLE
RotarycraftV14a and DragonAPI14a Forestry crash.

### ISSUE THREAD

**Issue by LordPhintex** [ReikaKalseki/Reika_Mods_Issues#929]
Hi Reika. I know this bug was always often be postet and i read much to find a solution by my self 
but i didnt.
I read this: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/229
and this: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/116
and there you wrote that forestry 3.6.x shoud be compatible.
I teste it with DragonAPI, Rotarycraft ( both in the newest version) and Forestry 3.6.20
here the crashreport 
http://pastebin.com/pmL5Qq4e

I hope you can fix it.  not even for forestry 4 but pleas vor Forestry 3 so we all can play and explore your perfect technolegy Mods with the cool things of Forestry 3 <3 

Edit: And yes i have try ALL 1.7.10 Versions of Forestry the crash is allways the same.

mfg LordPhintex 

Edit: Sorry for bag english im from germany :D

**Comment by ReikaKalseki** [comment]
I said that Forestry 3.6 was compatible back before 4.0 was released. And then you wonder why 3.6 is not still compatible, and ask me to move support off of 4.0 to 3.6? Really?

**Comment by TomeWyrm** [comment]
Forestry 4 is for 1.7.10 as well, so no you did not try all the Forestry versions for 1.7.10.

Use Forestry 4. There's no reason to not update at this point.
