### ISSUE TITLE
ug more spam, debug mode

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#93]
![2015-06-09_18 16 58](https://cloud.githubusercontent.com/assets/8153290/8073287/bdce441c-0ed7-11e5-9970-585bebd48ec4.png)

**Comment by ReikaKalseki** [comment]
How did you trigger this?

**Comment by Zedrimar** [comment]
@ReikaKalseki just do the command to go into debug mode, I did do it several times to make sure I could reproduce it. Do you want the log as well?

**Comment by Zedrimar** [comment]
@ReikaKalseki it is searching for the aerial camera.... dropbox (exedes pastebin limit):https://www.dropbox.com/s/a2m9glebi7ogzgy/latest.log?dl=0

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by Zedrimar** [comment]
awesome!
