### ISSUE TITLE
Chromaticraft crashes on launch with FTB infinity

### ISSUE THREAD

**Issue by cyberkitkat** [ReikaKalseki/Reika_Mods_Issues#931]
We encountered a crash if we launch the newest FTB infinity pack with Dragon API, Rotarycraft, Reactorcraft, Electricraft, Voidmonster and Chromaticraft. 

The crash report is saying something about noClassDefFound error within chromaticraft, something with the chroma research manager. ( http://pastebin.com/5R3yr1E4 )

ohh and we removed aobd because of a crash with rotarycraft's custom extract handler.

**Comment by Builderb0y** [comment]
AE2 rv3. Either disable "exportItemNames" inside config/AppliedEnergistics2/CustomRecipes.cfg or downgrade to rv2. Or just launch the game again, it only crashes once each time you change which mods you have installed. See #481.

**Comment by TomeWyrm** [comment]
An aid for configuration that exports item names is breaking because it can't handle research fragments. _sigh_

If true (obviously big caveat), that means it's AE's fault and they probably won't fix it. Great.
