### ISSUE TITLE
[chromaticraft] crash when using elemental sonar

### ISSUE THREAD

**Issue by games4maurice** [ReikaKalseki/Reika_Mods_Issues#932]
my game crashes whenever i use the elemental sonar ability in the chroma dimension
crash log: http://pastebin.com/ePKgCWkJ

**Comment by ReikaKalseki** [comment]
This has been reported before. Are there any patterns?

**Comment by games4maurice** [comment]
as far as i know this seem to be completely random

**Comment by ReikaKalseki** [comment]
You said it was "whenever you use it". Does it happen all of the time you try to use it?

**Comment by games4maurice** [comment]
i just used it and i crashed with a similar log but it took me a lot of tries
new log: http://pastebin.com/qcYC3HW2

**Comment by ReikaKalseki** [comment]
So it is as before, entirely sporadic and impossible to track down.

**Comment by games4maurice** [comment]
it seems at line 12 the first number "256" is counting down when i crash

**Comment by games4maurice** [comment]
got a new crash log: http://pastebin.com/3NXVmW6S
this time the description says "Exception in server tick loop"

**Comment by ReikaKalseki** [comment]
It is exactly the same as before.

**Comment by ReikaKalseki** [comment]
Hopefully fixed.
