### ISSUE TITLE
DragonAPI v14b - particle rendering ingame crash

### ISSUE THREAD

**Issue by walkerjonny** [ReikaKalseki/Reika_Mods_Issues#933]
Hi,
I got this crash as I achieved a goal and some "firework" started to run over my head because of that.
http://pastebin.com/faN9Pt4k
Do you have any idea how I can handle this or is it more related to a coding issue?

**Comment by TomeWyrm** [comment]
Well the firework on achievement get is from endercore, you can disable that but it probably won't fix the underlying problem, which could re-occur at some later date.

**Comment by ReikaKalseki** [comment]
The only reason DragonAPI shows up here is because of my replacement of the particle system. Also, the error truncated 90% of itself.

**Comment by walkerjonny** [comment]
Well, it didn't happen even a single time before you implemented your replacement of the particle system.
Is it possible to disable your particle system and to use the default one?

**Comment by ReikaKalseki** [comment]
> Is it possible to disable your particle system and to use the default one?

And take a 90% FPS hit? No.

**Comment by walkerjonny** [comment]
OK, at least good to know that you try to improve the performance. 
I'll see if I can get a more detailed crash log the next time.

**Comment by redelman** [comment]
Hmm, using v14b and the latest endercore I don't have this problem at all.

**Comment by walkerjonny** [comment]
Interesting, because I have the same versions.
Maybe it's because of some other mod interactions or because I'm playing with that many mods that even my Core i5 4690k has some troubles to handle them all...
For now I have turned off the firework in EnderCore as I don't need it.
I'll see if that's gonna be enough to avoid that crash in the future.

**Comment by TomeWyrm** [comment]
Your i5 should be fine, rotarycraft is one of the few mods that taxes a cpu. Double check that you have the latest EnderCore?

**Comment by walkerjonny** [comment]
EnderCore version is at "EnderCore-1.7.10-0.2.0.35_beta".
That is the last one I know so far.
