### ISSUE TITLE
Crash on loading world with mod versions 14C

### ISSUE THREAD

**Issue by Xireka** [ReikaKalseki/Reika_Mods_Issues#935]
I updated all of the mods that got an update to version 14C on 06.06.2016 namely DragonAPI, Electricraft, RotaryCraft, ReactorCraft and Chromaticraft.

Upon loading my world the client crashes to desktop with this crash report, I tried finding out what it is but no idea :(

http://pastebin.com/jdUE2n2q

I hope it's nothing too bad :(

Edit: tested, this crash doesn't happen with version 14b of the aforementioned 5 mods.

**Comment by ReikaKalseki** [comment]
Something is corrupt with NBT. Break all adjacency upgrades while in v14b.

**Comment by Xireka** [comment]
Thanks for the fast reply, now comes the weird part.

Adjacency upgrades is a Chromaticraft thing I can craft right or what is it exactly? Cause I never crafted any, I'm not even that far into chromaticraft.

Sorry if it's really simple actually and I'm just missing the point :(
