### ISSUE TITLE
ChromatiCraft ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by Shadows-of-Fire** [ReikaKalseki/Reika_Mods_Issues#936]
Using the [Cake Mod](http://minecraft.curseforge.com/projects/thecakemod) with ChromatiCraft installed and hitting the NEI use key on any "large" item from the mod, (and possibly with any other overly-complex item) produces [this crash](https://gist.github.com/Shadows-of-Fire/ba2a55b6ed12c654e20a617d58a6185c).  
[FML Log](https://gist.github.com/Shadows-of-Fire/30f474649a1fad288670ce2e4e015450)

**Comment by Builderb0y** [comment]
```
at binnie.extratrees.block.BlockETLog.getBlockName(BlockETLog.java:136)
at binnie.core.block.ItemMetadata.func_77653_i(ItemMetadata.java:57)
```

Something tells me this has nothing to do with cake.

**Comment by Shadows-of-Fire** [comment]
Oh I realize it looks as odd as it does.  Neither me or @HellFirePvP could figure out that part.

**Comment by Shadows-of-Fire** [comment]
Well,  testing some other things,  removing Binnie's moves it over to a Thaumcraft NEI Plugin issue,  and removing that makes it work fine.  I'm quite confused as to who's end this issue is on.  However, it doesn't seem to be here.

**Comment by Builderb0y** [comment]
If thaumcraft NEI plugin crashes WITHOUT binnie's mods, then there's something else at work.

We've had issues with forestry registering items to the ore dictionary which crash upon being rendered or getting their name or both, and from the stack trace I think it's reasonable to suspect binnie is doing the same. Without binnie's mods though, there must be something else invalid in the ore dictionary. Can you get a crash report **without** binnie's mods?

**Comment by Shadows-of-Fire** [comment]
Removing Binnie's from the instance then makes the error more widspread.  With Binnie's, only the U key on the cake item would cause the crash.  Without it, Thaumcraft NEI Plugin crashes on both U and R.  Without Thaumcraft NEI, all is fine.
R: https://gist.github.com/Shadows-of-Fire/634088ccc61b220e76aab18a1b86c116
U: https://gist.github.com/Shadows-of-Fire/3cd4870d5cae5a36adfb04dfd64806a2
At this point, Chroma is no longer mentioned.

**Comment by Builderb0y** [comment]
Well, at least that crash isn't failing to get some property of an item, so your ore dictionary _probably_ doesn't have invalid items in it.

at codechicken.nei.PositionedStack.setPermutationToRender

I've seen that error a couple of times before, though I have no idea what causes it. Sorry about that.
