### ISSUE TITLE
RotaryCraft Handbook: wrong info/missing info

### ISSUE THREAD

**Issue by L-Clouds** [ReikaKalseki/Reika_Mods_Issues#937]
The handbook states a **Wind Turbine** operates at optimal efficiency at **128m** altitude; but the in-game behavior (and [code](https://github.com/ReikaKalseki/RotaryCraft/blob/master/TileEntities/Engine/TileEntityWindEngine.java#L87)) have its power at maximum when at **Y>=80**.  Is the book wrong or is the gameplay wrong?

The handbook states a **Shaft Junction** in merge mode with two **different speed** inputs will "merely result in a shower of sparks" (implying no output); but the in-game behavior allows a Shaft Junction in merge mode to operate when one of the inputs is at **zero speed** and one is non-zero...and not only when the zero-speed side is air, but when it is a true RotaryCraft output such as a stopped engine.  Is the book wrong, incomplete, or is the gameplay wrong?

The handbook states a **Friction Heater** is  "a tool to warm up a standard furnace without fuel", strongly implying it works only with vanilla furnaces or at least with machines which otherwise use registered fuel items; but the in-game behavior also allows it to heat other blocks such as a Blast Furnace.  I admit the sentence is sufficiently unclear that other interpretations could be argued, but: is the book wrong, incomplete, or is the gameplay wrong?

The **Gas Turbine** requires open space in front of the intake, yet the handbook does not make mention of this that I can see; the entry for the Wind Turbine states its frontal clearance requirement, so this seems like a case where the Gas Turbine's entry is missing info.
---- Unrelated to the handbook, the Gas Turbine's intake is blocked even by partial blocks such as an Expanded Redstone clock, or a slab.  Yet, the Gas Turbine runs when ingesting water?

Gasoline, Performance, Microturbine, and Gas Turbine engines will **"drown"** if they are adjacent to water and blocked from open air on all other sides; this is not mentioned anywhere in the handbook that I've found.  Considering how specific and explicit the handbook is about other requirements and hazards in the mod, this omission seems incorrect.
---- It's odd that it is sufficient for only the outlet end of the Gas Turbine to be exposed to air, to not drown.

The handbook phrases the use of additives in the **Performance Engine** as "... can only reach its maximum output when give the correct additives ... each being more effective than the last."  Again I admit this is open to interpretation, but the most obvious interpretation to me is that each of the three additives will result in a different power output.  The gameplay is that each additive lasts for different amounts of time, but all will allow it to provide its maximum power.  Should this description be revised?

**Comment by ReikaKalseki** [comment]
In order:
- I suspect the code changed since the handbook was written, probably to make the turbine easier to use.
- You are incorrectly assuming "merely" means zero power.
- Again, you are assuming that unless something is explicitly mentioned it does not exist.
- Same as above + common sense.
- Same as above

**Comment by ReikaKalseki** [comment]
I updated the wind turbine entry.
