### ISSUE TITLE
[ChromatiCraft] Crash when opening lexicon entry of Crystal Repeater recipe

### ISSUE THREAD

**Issue by 3TUSK** [ReikaKalseki/Reika_Mods_Issues#939]
Either I look up recipe of crystal repeater through NEI or directly open it in Chroma Lexicon, game will freeze for a while and crash. Do note that _two_ crash reports are generated: [one on server side](https://paste.ee/p/e1nLg) and [another on client side](https://paste.ee/p/rxCs3).
Fastcraft 1.23 with default config also presents here. Forge version is 10.13.4.1558. Both DragonAPi and ChromatiCraft are v14c.

**Comment by ReikaKalseki** [comment]
The two logs are unrelated, the server is a duplicate and the client has also been reported but makes no sense. Also, everything works for me.

**Comment by 3TUSK** [comment]
But, for unknown reason(s), the same client-side error persist to exist on my computer. Today my game has crashed more than five times with the same crash-report. 
I have tried updating Forge, disabling Fastcraft, and regenerating config files, none of them worked. 
Any suggestions? Cause crystal repeaters are necessary for ChromatiCraft.

**Comment by ReikaKalseki** [comment]
Like #938, this is an issue that goes directly against my personal experience.

**Comment by kamyu2** [comment]
For the crystal repeater recipe crash:  you added a ChromaStacks.lumenGem to the recipe which is set to ChromaItems.TIERED.getStackOfMetadata(23) but ItemTieredResource.java still just goes to case 22 so it is returning null.
