### ISSUE TITLE
Casting Delegate appears to be non-functional

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#940]
hi,
After 2 hours of trying to craft the casting delegate and constantly crashing to cmes I finally managed to craft a casting delegate and placed it ontop of my casting table.
The issue is that no matter what button I press in the delegate's gui nothing happens. From my understanding I should be able to select from the list of items I have crafted and then let it craft from an attached inventory. What I actually have is 6 buttons that do nothing when pressed and 2 new item slots. One of them I presume is the output while the top left one is the selection? At least I can put an ghost item in there, but the moment I close and reopen the gui it is gone.

**Comment by Builderb0y** [comment]
Try placing it a bit higher.

**Comment by Turmfalke2** [comment]
tried placing it up 20 blocks above the casting table, changed nothing.

**Comment by Builderb0y** [comment]
I meant that there's a specific location that it has to be at in order to work. 20 blocks is too high.

**Comment by Turmfalke2** [comment]
I checked all the places between directly above it and 20 blocks above it.

**Comment by Turmfalke2** [comment]
Alright, checked the code and I must have missed the 5.
