### ISSUE TITLE
Rotarycraft: magnetostatic engine UI does not update if activated by non-vanilla redstone

### ISSUE THREAD

**Issue by Holi0317** [ReikaKalseki/Reika_Mods_Issues#941]
Step to reproduce:
1. Set redstone control of magnetostatic engine to high
2. Connect it to non-vanilla redstone. (Tested with enderIO both insulated/non-insulated redstone conduit, red alloy wire from project red)
3. Activate that redstone
4. Check magnetostatic engine UI. The speed and power remains at 0. Angular transducer also tells the engine outputs 0 speed.

Expected behavior: Speed and power in UI should change. RF consumed in Waila should not be 0.

Screenshots:

![2016-06-09_20 23 07](https://cloud.githubusercontent.com/assets/6838982/15929571/5cf55e40-2e80-11e6-9445-7ebcc4166ab0.png)
(engine enabled, but waila said it is not. The friction generator and engine are working)

![2016-06-09_20 23 10](https://cloud.githubusercontent.com/assets/6838982/15929573/5d000192-2e80-11e6-8422-b0698ad8a55b.png)
(UI does not change. As if the engine is shut down)

![2016-06-09_20 23 21](https://cloud.githubusercontent.com/assets/6838982/15929572/5cfbec4c-2e80-11e6-853e-3ce069334f27.png)
(Connected with vanilla redstone. The UI updates as expected)

Opencomputes redstone I/O does work, however.

**Comment by amesgen** [comment]
can confirm this

**Comment by ReikaKalseki** [comment]
This is a client/server issue. EiO has the issue, but ProjectRed _used_ to work...

**Comment by ranger135xp** [comment]
From what I've played with, to get RoC to see redstone from other mods, it has to be a strong signal. From testing, ProjectRed alloy wire does not appear to put out a "strong" signal. Therefore, in your images, you'd need to power the block under the engine or the engine's block-space itself. I found this with the engine control unit. Not sure if you can place the alloy wire on the under-side of this engine, but it works if I place it on the engine control unit directly. EnderIO also needs the "strong" checkbox ticked and it works. Again, not sure of this particular machine.

**Comment by ReikaKalseki** [comment]
This was fixed in v16 due to a redstone handling change.
