### ISSUE TITLE
[Chromaticraft] Crash when viewing Crystal Repeater recipe / holding Lumen Gem

### ISSUE THREAD

**Issue by Eb-** [ReikaKalseki/Reika_Mods_Issues#942]
Lumen Gem shows up as "Untitled" in inventory, issues may be related.

Crashlog for viewing Crystal Repeater recipe: http://pastebin.com/CtPyXTmi
Crashlog for Lumen Gem: http://pastebin.com/ARHZApJt

**Comment by 3TUSK** [comment]
#939 Am I not the only one whose game will crash when looking at crystal repeater recipe?!

**Comment by Aivech** [comment]
Could this be related to the progression issues people are having (#889 and others)
