### ISSUE TITLE
game doesn't load anymore

### ISSUE THREAD

**Issue by Webzoner97** [ReikaKalseki/Reika_Mods_Issues#944]
v 1.4

![](http://i.imgur.com/9VPFVDq.png)

**Comment by redelman** [comment]
Are you kidding me? Forge 1558 has been required since v10 (or maybe v12). Update your Forge. This is in no way a bug or even worth me responding to.

**Comment by ReikaKalseki** [comment]
"Not mod related" is for things like "Curse page is not working", "how do I donate", or "how do I get old versions", not "problem is in the user's head, not the mod".

**Comment by TomeWyrm** [comment]
So tempted to put more issue tags on this... I almost can't believe anyone could not know how to fix this... then I remember that curse made it TOO easy to install mods.
