### ISSUE TITLE
Mystcraft/DragonAPI crash

### ISSUE THREAD

**Issue by Keyarose** [ReikaKalseki/Reika_Mods_Issues#947]
When starting a new world a crash happens, it does not happen when opening a preexisting world.

Crash log: http://pastebin.com/F3xJeKig

Versions:
Mystcraft 0.12.3.02
DragonAPI V14d
Chromaticraft V14d

**Comment by ReikaKalseki** [comment]
This is on his end:

`return Mystcraft.registeredDims.contains(Integer.valueOf(dimId));`

http://i.imgur.com/wZmf5vF.png

@xcompwiz

Apparently the `registeredDims` field is null.

**Comment by Keyarose** [comment]
Ok thanks, I'll cross post it over to his repo issues.
