### ISSUE TITLE
V14d Shutting down internal server hang

### ISSUE THREAD

**Issue by Shadows-of-Fire** [ReikaKalseki/Reika_Mods_Issues#949]
Using only V14d DragonAPI and ChromatiCraft, upon creation of a singleplayer world, the game proceeds to finish building the world, then immediately go into shutting down internal server and javae.exe stops responding.

[FML-client-latest.log](https://gist.github.com/Shadows-of-Fire/97e2c1cc876aa47e8006e539c09ae4fd)

**Comment by Shadows-of-Fire** [comment]
And this seems to only be caused by updating from 14c to 14d.  Deleting my install dir allowed 14d to run fine.

**Comment by ReikaKalseki** [comment]
Something in your instance was corrupted.
