### ISSUE TITLE
Bedrock armor overpowered

### ISSUE THREAD

**Issue by djinn70** [ReikaKalseki/Reika_Mods_Issues#95]
so I made some bedrock armor, and now I'm basically unkillable. For what it costs, this is kind of OP, don't you think?

**Comment by djinn70** [comment]
"Not a bug"....well, sorta, but it's still an issue. Can you get @ReikaKalseki

**Comment by djinn70** [comment]
I'm using the latest version btw

**Comment by 1Matthias** [comment]
What exactly did you do to get the bedrock armour? And latest version for what version of minecraft?

**Comment by djinn70** [comment]
I made some bedrock ingots and crafted it?? This is mc 1.7.

**Comment by 1Matthias** [comment]
Elaborate please. Please provide a full explanation of what you did.

**Comment by djinn70** [comment]
Nothing more to elaborate. You make the bedrock dust. Then you craft it with steel. This makes bedrock ingots. Then you make the armor.

**Comment by 1Matthias** [comment]
Include all the intermediate steps. Include everything.

**Comment by djinn70** [comment]
There are no intermediate steps! I make the dust from the **bedrock breaker**. Then I put that in a crafting table with a steel ingot. Then I put those ingots in a crafting table! God you are dense!

**Comment by 1Matthias** [comment]
Please clarify that last statement about the crafting table, also, are you sure that you are using 1.7.10? What pack are you using? Also, how are you powering the bedrock breaker?

**Comment by djinn70** [comment]
Yes I'm using a crafting table, and I'm powering it with malgetonatics. I'm sure it's 1.7, not sure about the 10.

I'm using whatever my server is.

**Comment by 1Matthias** [comment]
What is your server using, and what in the name of pineapples is a "malgetonatic"?!

**Comment by djinn70** [comment]
https://mineyourmind.net/server/ftb-monster.html

The rf thingy

**Comment by 1Matthias** [comment]
You are using an ancient version, which is not only no longer supported, but is also for 1.6.4, not 1.7. It is nether the latest version, being over a year old and 37 major versions out of date at least, nor the correct version to base any balance discussions on.

**Comment by djinn70** [comment]
it's 1.7 you liar!

http://www.feed-the-beast.com/modpacks/FTBInfinity

**Comment by 1Matthias** [comment]
Your server is, as you said, running Monster, not Infinity. Also, Infinity does not even contain Reika's mods by default. This issue is closed.

**Comment by djinn70** [comment]
What's the differenence?

**Comment by Duckfan77** [comment]
Minecraft version, mod versions, mods included, configs, everything except the style of the pack, both being a kitchen sink pack.

**Comment by 1Matthias** [comment]
It is a bit like bringing you can in to a shop to be maintained, and saying that it is 2010 Honda Odessa on the phone, and when you come into the shop, you show up in a 1999 Toyota Camry. They are both cars, but that is where the similarities end. It is completely different, and a headache for us when it occurs. Also, using the changelogs, I found out the latest version that you could be using for this behaviour to be in effect: v12d. https://sites.google.com/site/reikasminecraft/latest-downloads Try these downloads before you make any more balance comments, and make sure you actually use 1.7.10 this time. And finally, calling someone trying to help dense, and then lying about what minecraft and mod version that you have, is a one way ticket to nowhere. In the future, do not do that again. Thank you, and good-day.
