### ISSUE TITLE
Syncing issue when blowing up jet engines

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#951]
hi,
So I noticed that when ever I blow up a jet engine (gas engine) by liberate use of a screwdriver, rotarycraft creates steel scrap client side only.
In addition to that I found the following lines in the log:
 [Client thread/ERROR] [FML]: DRAGONAPI ERROR: Tile Entity Gas Turbine @ DIM0: -309, 5, 2012 sent a sync packet from the client! This is not allowed!

using 14d

**Comment by ReikaKalseki** [comment]
It looks like the client-side scrap is intentional.

http://i.imgur.com/mH7jiVo.png

**Comment by Turmfalke2** [comment]
I am aware of how the code looks, I checked the rotarycraft repo here. Baring jvm errors the code is always going to do exactly what it looks like.
 The question is should it be client-side only? And should dragon api always throw an error due to that client sends a sync package?
I understand that blowing up jet engines is probably not something player do on a regular basis, but I would still prefer sane behaviour.
Not sure how particles sync from server to client, but I think you might have just missed a ! in line 397.

**Comment by ReikaKalseki** [comment]
> The question is should it be client-side only?

It is using the scrap as a sort of particle effect, not a dropped item.

> And should dragon api always throw an error due to that client sends a sync package?

Yes, because that is a code error.
