### ISSUE TITLE
Shaft bus disconnecting

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#952]
hi,
I occasionally have an issue with the shaft bus seemingly disconnecting up on loading the world, it might possibly be related to a chunk boarder that is crossing it.

https://ibin.co/2kHcquSXmXun.png

using 14d

E: the other house also generates with 16 addition doors on the ground in addition to some torches and some random items in the middle. Maybe a chest fails to generate?
E: the loot chest is there.

**Comment by ReikaKalseki** [comment]
Shaft buses are...glitchy.

**Comment by Turmfalke2** [comment]
Closing this since it is unlikely that this report will change anything and according to reddit user Spelly they are fine now.
