### ISSUE TITLE
entity.ChromatiCraft.Ball Lightning.name is not a valid option for the spawner reprogrammer

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#953]
hi,
The first entry in the list of monsters in the reprogrammer is 'entity.ChromatiCraft.Ball Lightning.name', but apparently ball lightning spawners are not a thing or at least it is fails to actually create one.

**Comment by ReikaKalseki** [comment]
It should work...what happens?

**Comment by Turmfalke2** [comment]
The spawner programmer consumes the lumen and the spawner gets moved from the left to the right slot without actually changing.

**Comment by ReikaKalseki** [comment]
WTF....

**Comment by Turmfalke2** [comment]
Can you reproduce that?

**Comment by ReikaKalseki** [comment]
It works for me.

![](http://i.imgur.com/OLZQGbw.png)
