### ISSUE TITLE
REQUEST: Change Biome Detection for Decoflower

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#955]
Due to how some terrain generation mods replace world generators for certain biome types, would it be possible to change the detection mechanism for a couple of the deco flowers? For example, there is no BiomeGenSwamp when using RTG, so the reeds only spawn in an Eerie biome on the extremely rare chance that the eerie biome intersects with a happy spot for sugarcane.

In https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Block/Worldgen/BlockDecoFlower.java#L303-L306

Something like

```
case VOIDREED:
    return b.biomeID == ThaumIDHandler.Biomes.EERIE.getID() || BiomeDictionary.isBiomeOfType(b, Type.SWAMP);
case FLOWIVY:
    return BiomeDictionary.isBiomeOfType(b, Type.HILLS) || (b.rootHeight >= 1 && b.topBlock == Blocks.grass/* && ReikaBiomeHelper.getBiomeTemp(world, b) < 40*/);
```

There's other features that use instanceof _generator_, but wanted to see if this is even feasible  from your perspective. CrC features generate in RTG worlds, but generally with extreme rarity beyond your vision.

**Comment by ReikaKalseki** [comment]
I do not trust the Biome Dictionary. Blame BoP and its "ocean" forests, "magic" cherry trees, "swampy" mushroom forests, "forest" orchards, "lush" deserts...

**Comment by TomeWyrm** [comment]
I wish BoP would die or get rewritten to be not-stupid........ wait... the biome dictionary is a FORGE registry, correct?

I know what I'm suggesting is a bit hacky, but would it not be possible to override/rewrite/overwrite/change the biome tags for another mod? Basically fix Biomes o Plenty from being derp and screwing up your mod, and hence allowing you to support properly functioning/built mods like RTG (I assume).

**Comment by ReikaKalseki** [comment]
That is very easy to do, but I am not able to get away with such a thing.

**Comment by TomeWyrm** [comment]
Wonder if anyone else would be willing to write a BoPFix mod...

**Comment by 1Matthias** [comment]
That sounds like a great first mod for learning Java almost...

**Comment by Haggle1996** [comment]
BiomeTweaker does this already through `removeDicType`

EDIT: Link to [Wiki](https://github.com/superckl/BiomeTweaker/wiki/Basic-Script-Commands)

**Comment by TomeWyrm** [comment]
Yes, but that's not a solution that would allow Reika to quit having to babysit BoP, and thereby screw up easy integration with other mods.

**Comment by Haggle1996** [comment]
Wouldn't that be the same problem as a BoPFix mod? There's no guarantee someone is going to run the mod, so there's no guarantee Reika wouldn't have to babysit anyway. If it's not done in the environment sanity cleanup/checking, or cleaned up in BoP itself, it's probably not going to happen.

**Comment by TomeWyrm** [comment]
Possibly, but part of the point of such a mod would be working out-of-the-box and it could be made a requirement if BoP is present with ChC, even if it's not a Reika mod. BiomeTweaker would not work out of the box, and so would not fix the problem in a way that's remotely idiot resistant. It's like saying "my recipes conflict" and the solution being "install minetweaker". Yes that would fix the problem for someone that knows minetweaker, or packs where the dev knows how to use minetweaker, but it in no way fixes the problem.

An addon/patch mod that is listed as a conditional dependency would serve that purpose however.

**Comment by Haggle1996** [comment]
A very awesome 'fix' for this problem would be if Reika released a biome mod so we don't need BoP/Highlands/ExtraBiomesXL. The problem is the lack of variety in Vanilla worlds. I know he started down that path with the Ender Forest mod, which morphed into ChromatiCraft. :)

**Comment by TomeWyrm** [comment]
Now see, THAT is something that belongs in Geostrata :-)

**Comment by Haggle1996** [comment]
As a solution in BoP, change to `B:Swampland=false` under `"vanilla biomes to override"` in config/biomesoplenty/biomegen.cfg (it's normally true). This instructs BoP (and therefore RTG in my pack) to use the vanilla swamp generator instead of the BoP override generator. Verified void reeds are now spawning as appropriate in the biome.
