### ISSUE TITLE
Crash after crafting chromatic alloy

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#956]
hi,
I was crafting chromatic alloy(the one made out of iron and dust) in a reservoir when suddenly the java process started allocating huge amounts of memory and the game crashed with the following stacktrace.
http://pastebin.com/1scguBEt
Is ei.ticksExisted written from another thread or how can it be less than 600 for the first check and then be more than 600 to create a negative number for nextInt()?

**Comment by ReikaKalseki** [comment]
No, there should not be any multithreading involved.

**Comment by ReikaKalseki** [comment]
Looking at the code, this one makes no sense.

**Comment by Turmfalke2** [comment]
What kind of information do you need from me?

**Comment by ReikaKalseki** [comment]
Does it happen consistently? Try removing mods.

**Comment by Turmfalke2** [comment]
I had it happen once and most the mods I am using are yours.

**Comment by ReikaKalseki** [comment]
If it is a one-time error that has never before been reported, and makes no sense, it is not worth investigating.
