### ISSUE TITLE
Magnetostatic engines double coolant level when broken and replaced.

### ISSUE THREAD

**Issue by Kreidos** [ReikaKalseki/Reika_Mods_Issues#957]
-Place a magnetostatic engine
-Add 1 bucket of coolant
-Break with pickaxe and replace

Expected: Engine has 1000mb of coolant.
Observed: Engine has 2000mb of coolant.
Actually doubles coolant; does not simply add 1 bucket.

Tested with only MC1.7.10, forge 10.13.4.1614, DragonAPI 14d, Rotarycraft 14d.

**Comment by Kreidos** [comment]
[EnergyToPowerBase.java#L352](https://github.com/ReikaKalseki/RotaryCraft/blob/master/Base/TileEntity/EnergyToPowerBase.java#L352)
Tank must already have fluid at this point, perhaps L482? Could use tank.setContents at [L352](https://github.com/ReikaKalseki/RotaryCraft/blob/master/Base/TileEntity/EnergyToPowerBase.java#L352) instead.

**Comment by ReikaKalseki** [comment]
Fixed.
