### ISSUE TITLE
Nullpointer when crafting with casting delegate (getDeathPersistentNBT)

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#958]
hi,
I was crafting 8 iridescent crystal chunks with the casting delegate when I suddenly got the following stacktrace in my log. The crafting was still successful. 
http://pastebin.com/1DaMR7Qe

Also could we have a better way to pick a recipe? With all the items having 16 different ways to craft them it takes quite a while to find the one I am looking for.

**Comment by HellFirePvP** [comment]
This happens client side only by the way.

**Comment by ReikaKalseki** [comment]
> Also could we have a better way to pick a recipe?

Use CTRL or shift.

**Comment by TomeWyrm** [comment]
CTRL and Shift allow you to scroll/shift through lists faster, one of the prime examples being the ability selection for ChC (the middle mouse button "spells")

**Comment by ReikaKalseki** [comment]
Hopefully fixed.
