### ISSUE TITLE
[Rotorycraft] 6f Clicking on flakes causes crash (Dude, don't devide by zero!)

### ISSUE THREAD

**Issue by Zedrimar** [ReikaKalseki/Reika_Mods_Issues#96]
paste http://pastebin.com/sCEzCQz7

**Comment by 1Matthias** [comment]
Instance number 5 of this issue, fixed in v7.

**Comment by Zedrimar** [comment]
ok then, my bad

**Comment by Zedrimar** [comment]
@1Matthias another workaround is to use recommended versions of NEI and codechicken core
