### ISSUE TITLE
Reactorcraft + Rotarycraft / OpenComputers component issues with larger builds

### ISSUE THREAD

**Issue by dieselfuelonly** [ReikaKalseki/Reika_Mods_Issues#961]
I've noticed that when connecting an OC computer/server to RoC/ReC machines (either directly with a cable or through an adapter block), the computer can see all of the components that are adjacent to any other RoC/ReC blocks.  I ran across a reference to this issue on the OC Github that I think was several years old, and it was mentioned that this was intentional so that some blocks (such as the multi-directional clutch) can be controlled by a computer even when all of the other sides are being used.

I wanted to control my fission reactor with a computer, but even with a server filled with component buses, with anything other than a very small setup will cause the OC server to crash because of too many connected components.  I could even build a small reactor and then still have the OC server crash when I connect liquid pipes to the boilers because the connected liquid pipes cause the pumps to be visible components to the server.

I understand the feature is necessary in some situations but it also makes it near impossible to use OC to control connected machines.

If I could suggest a possible fix, it would be something like this:

By default, OpenComputers cable cannot connect to RoC/ReC blocks, with one exception:

A block, called something like a Computer Interface, would allow the connection of OC cable to the server and also act as a "pass-through" cable to any other adjacent RoC/ReC blocks.

For instances where you DON'T want all connected components to be visible, you would use an OpenComputers adapter block connected to the device you want to control through the computer.

**Comment by ReikaKalseki** [comment]
Just change the OC config, or wait for the non-native support feature once OC1.7 becomes widely used.
