### ISSUE TITLE
[ChromatiCraft] Crash in pre-init,  NoClassDefFoundError: TileEntityRift

### ISSUE THREAD

**Issue by PaladinOne** [ReikaKalseki/Reika_Mods_Issues#964]
I was running around the old Modular Mayhem pack and tried to update ChromatiCraft from v12 to v13 and v14 (tried both same error), and started encountering [this error](http://pastebin.com/Rv6YdV3c).

While it references the DragonAPI ASM injector and the ComputerCraft API, the crash occurs with or without CC/OC, and with Direct OpenComputers Support true or false.

edit 1:
After 2 hours of testing, I have determined that there are at least 2 other mods involved. When present in the full pack, Engineer's Toolbox causes a crash, however when only ChromatiCraft and ET are present there is not a crash. Continuing testing to try to find what 3rd mod is required to crash out.

edit 2:
After additional testing, I have determined that there are at least 3 other mods involved. When present in the full pack together, ChromatiCraft, Engineer's Toolbox, and EITHER Modular Powersuits OR Chisel 2 cause the crash. However, a pack containing only these mods, once again, does not crash.

**Comment by PaladinOne** [comment]
After 2 hours of testing, I have determined that there are at least 2 other mods involved. When present in the full pack, Engineer's Toolbox causes a crash, however when only ChromatiCraft and ET are present there is not a crash. Continuing testing to try to find what 3rd mod is required to crash out.

**Comment by ReikaKalseki** [comment]
#845, #804

**Comment by PaladinOne** [comment]
Cool, and confirmed; deleting the CC API from Engineer's Toolbox removes the explosion.
