### ISSUE TITLE
Shaft Junction Failing to Merge Inputs/Outputing Power With No Source

### ISSUE THREAD

**Issue by ErdrickXLII** [ReikaKalseki/Reika_Mods_Issues#965]
I have a power source connected to a shaft junction in split mode (31:1 inline). The inline output connects to a second shaft junction in split mode (1:1), and the bend output connects to a bevel gear that connects to a third shaft junction in merge mode (merging with the bend output of the second shaft junction).

![step1](https://cloud.githubusercontent.com/assets/4296894/16062321/5e729cfe-3260-11e6-91cf-f46b23357520.png)

When the power source is turned on: 31/32 of the torque is sent to Shaft Junction 1 and 1/32 is sent to the bevel gear; Shaft junction 2 splits its torque evenly between the rightmost dynamometer and Shaft Junction 3; Shaft Junction 3, however, only outputs the power received from Shaft Junction 2 and ignores the power received from the bevel gear.

![step2](https://cloud.githubusercontent.com/assets/4296894/16062326/69ac7680-3260-11e6-9f49-f31e7960ac92.png)

Now it gets odd: If, while the power source is running, I switch Shaft Junction 2 into merge mode, its inputs and outputs flip and it no longer transfers any power to anything; I then rotate Shaft Junction 2 around so it is not sending to or receiving from Shaft Junction 3; Lastly, I flip the bevel gear so it is no longer sending to Shaft Junction 3 and turn off the power source.

![step3](https://cloud.githubusercontent.com/assets/4296894/16062330/708d92b8-3260-11e6-8003-dff4f34d042b.png)

The end result is Shaft Junction 3 continues to produce power even though it's not connected to anything.

**Comment by ReikaKalseki** [comment]
Fixed. I was assigning the wrong variable under certain circumstances.
