### ISSUE TITLE
Hopper extracts fresh pellets from pebble bed reactor

### ISSUE THREAD

**Issue by Strange-Account** [ReikaKalseki/Reika_Mods_Issues#966]
Running version V14d of DragonAPI, RotaryCraft and ReactorCraft (and V14c of ElectriCraft).

When placing a hopper under a pebble bed reactor core 1  TRISO Fuel Pellet (Fresh) will be extracted. With multiple cores stacked all pellets will be extracted above the first core.

Tested in my creative and survival world in MC 1.7.10 with Forge 10.13.4.1614-1.7.10

**Comment by ReikaKalseki** [comment]
Read the changelog.

**Comment by Strange-Account** [comment]
Okay, found the entry "ReactorCraft: HTGR cores now feed TRISO pellets continuously". May i ask, why you did this change? What was your intention?

**Comment by ghost** [comment]
It was a solution to the depleted TRISO pellets staying in cores until it could get to the bottom on the set of cores. So Reika made it push TRISO out so the depeleted TRISO could be cycled through and accessible for removal. 

HTGRs might also do this IRL if I'm not mistaken.

**Comment by ReikaKalseki** [comment]
They do.

**Comment by Strange-Account** [comment]
Ah, okay. Thx for the answer. So i have to find a solution to handle this which is not so easy with just RotaryCraft and ReactorCraft. Maybe i have to use many item pumps and work with whitelists.

**Comment by Builderb0y** [comment]
There's a new block from rotarycraft coming in v15 that will help a lot with that.
