### ISSUE TITLE
Request: Trash can in RotaryCraft

### ISSUE THREAD

**Issue by Strange-Account** [ReikaKalseki/Reika_Mods_Issues#967]
Hi,

how do you think about a type of trash can / machine in RotaryCraft which can destroy items? Maybe with various power requirements per item type.

I don't want to kill the nuclear waste but with a fast boring machine i get so much stone which i cannot store without other mods. It would be really nice if there were an option to dispose unwanted items.

**Comment by 1Matthias** [comment]
Cactus, lava, scalable chest, etc. There are many deletion/mass storage
methods in RoC/vanilla.

**Comment by TomeWyrm** [comment]
Pneumatic Item Pump filter it for stone, pump the items into lava. Tiny bit laggier than something like the TubeStuff Incinerator (mentioned because tired of using the common mods for function descriptions. As evinced by referring to a "trash can" not "item deletion block") but functions just fine.
