### ISSUE TITLE
[ChromatiCraft] Crystal Star Core localization

### ISSUE THREAD

**Issue by jeremiahwinsley** [ReikaKalseki/Reika_Mods_Issues#968]
You may have already fixed this for the next version, but the Crystal Star Core for Thaumcraft doesn't have a localized name in v14d. Looks like the name was changed from `chromamod.crystalStar` to `chromamod.crystalwand` and the localization didn't get updated.

**Comment by ReikaKalseki** [comment]
It was a find-and-replace gone wrong.
