### ISSUE TITLE
Electricraft: Superconducting wire can be filled with nitrogen even if it is filled in fluid transposer

### ISSUE THREAD

**Issue by Holi0317** [ReikaKalseki/Reika_Mods_Issues#970]
Reproduce step:
1. Create a fluid transposer filled with liquid nitrogen
2. Put a superconducting wire (filled with nitrogen) in it.
3. Nitrogen is consumed and wire is filled again

Expected behavior:
Fluid transposer should not fill nitrogen into filled superconducting wire

Does not occur with filling station.
Also occur with Thermal Expansion cold liquid.

Mod versions:
DragonAPI 14d
Electricraft 14c
Thermal Expansion 4.1.2-240
Thermal Foundation 1.2.3-112
CoFH core 3.1.2-325

**Comment by ReikaKalseki** [comment]
I do not think the transposer is NBT-sensitive on the input side (like crafting and smelting) and looking at its code seems to confirm this (I see no references to `ItemStack.stackTagCompound`).
