### ISSUE TITLE
Slime Shears give Essence & Resonant Clover

### ISSUE THREAD

**Issue by Morpheus1101** [ReikaKalseki/Reika_Mods_Issues#972]
Im not sure to be honest if this is an issue, however when using Slime Shears from Tinkers Defense to break  Resonant Clover, you get the Energetic Essence but it also gives you the Clover to be able to place back down.

**Comment by Shahelion** [comment]
Only Slime, or any material TD Shears?

**Comment by ReikaKalseki** [comment]
#615
