### ISSUE TITLE
[CC] Pigmen do not aggro

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#973]
Just submitting this here for completeness.

Likely due to the Aggro Mask enchantment escaping its code shackles, Pigmen no longer aggro when other pigmen are attacked. Confirmed not an issue without CC.

**Comment by ReikaKalseki** [comment]
Does it happen with only DragonAPI?

**Comment by Shahelion** [comment]
I'll check in a few minutes once I get home. But isn't the enchantment added by ChromatiCraft?

**Comment by ReikaKalseki** [comment]
The ASM is in DragonAPI.

**Comment by Shahelion** [comment]
With DragonAPI as the ONLY mod in the instance, Pigmen do not aggro.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by Shahelion** [comment]
The strangest part of this is, I hadn't even updated anything yet, and yet Pigmen started aggroing again. Same world, same weapons, same everything. I am a very confused individual right now.

**Comment by ReikaKalseki** [comment]
I am as confused as you, because my code change should not have had any effect, yet did...
