### ISSUE TITLE
Local server crash latest Reika mods versions

### ISSUE THREAD

**Issue by Xireka** [ReikaKalseki/Reika_Mods_Issues#974]
So I am a 99% sure I managed to track down every client side mod, fixed three or so errors prior to this one yet this log just kills me, I literally got no idea how to fix it but your mods are too good to just take out and I'd like to play on a local server :(

This is the latest log I got: http://pastebin.com/2gmJ6MgU

Thanks in advance if it helps to fix my problem and Sorry Reika if it's actually not caused by one of your mods :(

**Comment by ReikaKalseki** [comment]
This crash is so early in loading no mod has had a chance to do much, aside from ASM, but this is not an ASM-related error. Are you sure this is from my mods? Does it happen without them? I have no such issues.

**Comment by TomeWyrm** [comment]
Mod list please?

**Comment by ReikaKalseki** [comment]
Hello?

**Comment by TomeWyrm** [comment]
If I remember when I get a moment, I'll pull it from the log spam. Most annoying way to get the mod list, forge really needs to put that list as early as it can. Even a raw directory dump would be nice without a bunch of other verbiage. _sigh_

**Comment by Xireka** [comment]
I'm sorry I was really busy with work and always pushed further getting you the mod list, uhmm can I dump a mod list with the server console maybe? or some other way since I don't want to copy the client side mods? I'll get to doing that today and pasting it here then :)

Still didn't manage to fix it anyway even though I tried everything I could come up with.

**Comment by Xireka** [comment]
Except if the log is an idiot these should be all the mods I have on the server side

http://pastebin.com/dycPZtRF

**Comment by ReikaKalseki** [comment]
You have a dozen "core"s and "patcher"s. Almost certainly one is to blame. Start with these:

ASP + GS Patcher.jar
KORESAMPLE-1.7.10-1.3.2.jar
LibSandstone-1.0.0.jar
Patcher.jar
SCOTTSTWEAKS-1.7.10-1.3.1.jar
si.core-1.5.0.jar
Stabilizer-3.4-1.7.10.jar
UniversalCore-1.0.1.jar
waterhooks-1.2.1.jar
WTFCaveBiomes-1.7.10_v1.6.jar
WTFCore-1.7.10_v1.7.jar
YuutoLib-1.7.10-1.0.2.jar

Also double-check that everything you have is for 1.7.10.

**Comment by Xireka** [comment]
Everything I have is for 1.7.10 I checked and my client starts flawlessly. I tried and took out all of the ones you mentioned and I got exactly the same error :(

**Comment by ReikaKalseki** [comment]
Then try removing more.

**Comment by TomeWyrm** [comment]
Well, a lot of the ones you took out are auto-downloads, because they're coremod/libraries for other mods.

Was this based off of a public pack?

**Comment by TomeWyrm** [comment]
Also, what Reika is trying to do is find the minimum set of mods to reproduce this. What you should probably do is a binary split search...

I knew I'd be re-using this explanation for years to come.

> If you don't understand what a Binary Split Search is
> 
> Step 1: Take out half the mods (be careful not to take out any dependencies; don't remove COFH Core if you're keeping Thermal Expansion, for example)
> 
> Step 1 Results: If the error can be reproduced then the mod causing the error is in the remaining mods, if the error disappears it was one of the mods you removed.
> 
> Step 2: If the error stayed, repeat the first step with your halved mod list (still be careful to keep dependencies of mods you aren't removing). If the error was gone, remove all the mods you kept (except for dependencies... Don't remove Thaumcraft if you're re-adding Automagy for example) and see if the error returns.
> 
> Step 3: Continue removing half the remaining mods, either switching which half you're working with or pruning the current set by half until you figure out which mod(s) are required at minimum to make the bug happen. Then submit a bug report to the authors of the mods involved.
> 
> If you end up being unable to recreate the error after this process... you need assitance from someone with experience.

**Comment by ReikaKalseki** [comment]
So...
