### ISSUE TITLE
request

### ISSUE THREAD

**Issue by neologisms707** [ReikaKalseki/Reika_Mods_Issues#976]
Could you please move each machine and item onto its own item ID and block ID? My plugin can't handle items with data values. Thanks.

**Comment by ghost** [comment]
No, that is impossible. If doing this, will overthrow everything, killing all the players, so it's impossible. And now it is very good and will not cause item id confusion or item ID not enough to use.

**Comment by redelman** [comment]
Not to mention, would destroy existing worlds. If anything, that plugin needs to be fixed, not Reika's mods.

**Comment by neologisms707** [comment]
Can you please reconsider? Right now I'm left completely without a way to block people from getting certain machines or enforce the ranks.

**Comment by redelman** [comment]
What purpose is there for blocking people from getting certain machines?
And, what machines?

**Comment by ReikaKalseki** [comment]
> Right now I'm left completely without a way to block people from getting certain machines or enforce the ranks.

Good, because you would be violating my rules if you did so. On top of that, 'ranks' implies monetary costs; are you charging for access to my machines?

**Comment by neologisms707** [comment]
> are you charging for access to my machines

Am I not allowed to do that?

**Comment by Duckfan77** [comment]
> The pack may not generate income, either directly from purchases or donations, or indirectly with ad revenue or merchandise, except that which is necessary for maintenance (eg server fees). This includes disabling/banning machines so that users must donate to have access to them or offering packages which include my items. These actions are also explicitly forbidden by the Mojang EULA.

From [the pack rules](https://sites.google.com/site/reikasminecraft/pack-permissions-and-rules), rule 4.

**Comment by ReikaKalseki** [comment]
> Am I not allowed to do that?

Very much not. See above.

**Comment by TomeWyrm** [comment]
Why does nobody link to Mojang's Commercial Use guidelines and Terms of Use? Saying it's part of Reika's rules implies they're allowed to do this with other mods. They're not.

The following is a direct quote

> Servers and Hosting
> 
> With hosting servers we want to enable the community to make money by creating, hosting and maintaining servers for Minecraft, so you may do this subject to these Guidelines. You may have seen the Blog post on server monetization https://mojang.com/2014/06/lets-talk-server-monetisation/ and the follow up Q&A https://mojang.com/2014/06/lets-talk-server-monetisation-the-follow-up-qa. This section of these Guidelines clarifies them. By "server," we mean a single connecting address or IP number.
> 
> Therefore, if you comply with and follow the Brand and Asset Usage Guidelines and Naming Guidelines above YOU MAY:
> - charge for access to your server, including a server which hosts your Mods, BUT only if:
>   - you make a single charge per person that is the same for everyone;
>   - you give everyone you charge, access to all the Mods that you choose to have on your server (except only in respect of genuine admin tools / admin Mods which should be reserved to administrators);
>   - you only give access to your server to users who have a genuine paid for version of Minecraft;
>   - you own or control the server and continue to do so for the whole time that you charge for access to it - so, if you sell the actual servers or server space with Mods pre-installed on them, you must ensure that the person buying the server is aware that she must follow these rules. Essentially you can't get round the rules above by setting up servers with Mods on and then selling those set-ups; and
>   - overall your access charges should be targeted to cover your operational costs of running the server.
> - ask for donations (as opposed to direct charges) IF you do not offer the individual donor something in exchange that only he or she can use. You may offer server wide rewards if donation goals are achieved though.
> - sell cosmetic items, except for "Capes", IF the item sold does not give a user an unfair gameplay advantage over anyone else on the server - i.e there can be no "pay to win".
> - sell positive effects or enhancements (other than "Capes") IF everyone on the server is positively affected in exactly the same way.
> - provide in-game advertising opportunities, sponsorships, or product placement for 3rd parties IF they don't degrade or interfere with gameplay or give a user an unfair gameplay advantage over anyone else on the server.
> - use in-game currencies IF (i) they are "soft currencies" i.e. a currency earned or expended only through gameplay that has no real world value and that cannot be cashed out, used or transferred across free or paid servers, or converted into "credits"; and (ii) you don't give the impression that it comes from or is associated with Mojang.
> 
> In all of these cases above YOU MUST also ensure that:
> - all servers, items and advertising are suitable for the target audience (i.e no gambling, pornography etc.) and don't damage the Brand.
> - you don't pretend to be us or claim to have any association with us (for example, when selling product placement opportunities);
> - you are explicit about who to contact about the server, who the operator is, and that it is NOT Mojang, NOT associated with Mojang and NOT supported by Mojang;
> - Mojang has no liability for anything on the server or that happens on it, including any advertising, purchases or donations;
> - you provide any user who gives you money an online payment /purchase history;
> - you are transparent on informing users with regard to all the content and pricing applicable to your server before a person joins, signs up or logs in;
> - you do not host or distribute malware, spyware, or engage in illegal activity through your server;
> - you comply with all other laws and requirements; and
> - you comply with any other additional requirements applicable under these Guidelines.
