### ISSUE TITLE
geostrata TE write state error...?

### ISSUE THREAD

**Issue by plaguewolf** [ReikaKalseki/Reika_Mods_Issues#978]
getting a bunch of this spammed in my logs, thought id pass it on.

[22:19:40] [Server thread/ERROR]: A TileEntity type Reika.GeoStrata.TileEntityGeoOre has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException

**Comment by plaguewolf** [comment]
ok, hmmmmm. seems that another mod is causing this.
i'll try and narrow it down to find who's responisble...

**Comment by ReikaKalseki** [comment]
The ores are....half implemented.

**Comment by plaguewolf** [comment]
ahh hmmm... and here i thought something was gone funky with gregtech unofficial TE ore/stone generation.
thanks for the info.
