### ISSUE TITLE
[ChromatiCraft] Client Crash when accessing Lumen Network

### ISSUE THREAD

**Issue by Teronial** [ReikaKalseki/Reika_Mods_Issues#979]
This particular crash only occurs when I am trying to use the Lumen Network I have setup in my survival world.

Crash Log: http://pastebin.com/ybqPTTee

It seems to occur if any sort of request is made for Lumens, though I have noticed that although this crash occurred when placing the Storage Crystal Charger, when I logged back in the network successfully sent Lumens into that block.

Currently I am trying to craft a Kuro Potion Lamp, but am unable to due to the crashing that occurs as soon as I use the Manipulator on the Casting Table.

**Comment by Turmfalke2** [comment]
This crash has been reported several times, including by me. From what I recall, Reika considers that bug impossible to fix.

**Comment by Teronial** [comment]
Yes, I can see that from closed issues now. Thank you for the response.

**Comment by ReikaKalseki** [comment]
#871
