### ISSUE TITLE
Donator render things missing (for me)

### ISSUE THREAD

**Issue by SisterJacq** [ReikaKalseki/Reika_Mods_Issues#98]
While working on a mod pack for my friend, I saw this in the MultiMC log:
[19:41:10] [Client thread/ERROR] [FML]: ROTARYCRAFT ERROR: Donator Mortvana UUID could not be found! Cannot give special render!

I guess I was supposed to give you my UUID when you added those nifty renders, but I didn't know that, anyway my UUID is 456226bb-8f9d-4061-a474-0ce94ebecbfb, so if it is not an inconvenience, would you mind taking the moment to add it, I would like to see those nifty renders on me when v7 comes around.
-Mortvana

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by SisterJacq** [comment]
Thanks! /me goes back to coding
