### ISSUE TITLE
Suggestion: Resistor variant (ElectriCraft)

### ISSUE THREAD

**Issue by Ieldra2** [ReikaKalseki/Reika_Mods_Issues#980]
Reason: it is often not possible to supply power in "clean" power-of-two steps with a resistor.
Solution: Make two color bands instead of three. Use all 16 colors and interpret each band as a hexadecimal digit, then you can have values of 0-255 in the two bands. If that number is n, the current limit of the resistor is 2**n, or n = log2(current limit).

**Comment by Rubyheart** [comment]
EletriCraft is based on real world resistors that use three color bands.  This is unlikely to change.

**Comment by redelman** [comment]
Personally I'd much rather see 4 bands, acting as real life 5 band, minus the tolerance band (so you'd have 3 digits and a multiplier).

**Comment by ReikaKalseki** [comment]
I have never seen a 5-band resistor before.

I will admit my initial impulse was to close this as "not how resistors work" but you do have a valid use case.

**Comment by redelman** [comment]
3 band resistors give you 2 significant digits, plus a multiplier. 4 bands are 2 significant digits, a multiplier, and a tolerance band. 5 band resistors are 3 significant digits, a multiplier, and a tolerance band. 6 bands is the same as 5 band, plus a temperature coefficient. 

IMO 4 band with 3 significant digits and a multiplier is the way to go (my suggestion above). That doesn't limit you to powers of 2 only, while allowing them (as 256A is impossible in the current implementation). However with the current model I can see that adding a 4th band may be a little difficult.

http://www.resistorguide.com/pictures/resistor_color_codes_chart.png

**Comment by ReikaKalseki** [comment]
When going to check the model to see if it has space for another band, I found this:
![](http://i.imgur.com/4f2QhfR.png)

The Techne file is missing, and I am not willing to recreate the model, so this has hit an impasse.
