### ISSUE TITLE
PowerSourceList SOE!

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#981]
hi,
I am getting spammed with "PowerSourceList SOE!". The print statement is commented out so the best I can provide is this:
https://github.com/ReikaKalseki/RotaryCraft/blob/c0fed8dd0a483ec7d88fba7866624d311f27a4d7/Auxiliary/PowerSourceList.java#L118

**Comment by ReikaKalseki** [comment]
Post an image of your setup.

**Comment by Turmfalke2** [comment]
The thing is, I am not sure which one is causing it and most of them are buried anyway. I will try around in creative a bit trying to reproduce it.

**Comment by Turmfalke2** [comment]
![2016-06-18_17 56 06](https://cloud.githubusercontent.com/assets/5174562/16172086/6fd13618-3580-11e6-975d-298ca9f4d6fc.png)

Apparently this was already enough to trick it, I am use a construct like this in some parts of my power grid to feedback unused energy to the battery.

E: note that the battery has no redstone signal.

**Comment by Turmfalke2** [comment]
Just updated to V15 and the bug is still around. Also froze, not sure whether related.

**Comment by ReikaKalseki** [comment]
@Ieldra has triggered this on my dev server, so I can confirm the issue exists, and is not the one I fixed before.

**Comment by ReikaKalseki** [comment]
Mostly or entirely fixed.
