### ISSUE TITLE
Village Structure is somewhat broken

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#982]
I've found two now, and both had the same thing happen. The loot chest, sign, and cobblestone/crafting table are all intact, as is the building in general. However, on the floor surrounding the crafting table, were about 3-4 chests' worth of loot as loose items. Also the house was floating 1 block above the flat ground it was on. Also, every single wooden door had 2-3 more wooden door items on the ground next to it.

Maybe it's trying to generate more than one on the same spot?

![2016-06-18_19 50 11](https://cloud.githubusercontent.com/assets/6917535/16174896/bddca2e4-358e-11e6-9522-3e458428cead.png)
![2016-06-18_19 51 11](https://cloud.githubusercontent.com/assets/6917535/16174897/bddccf26-358e-11e6-91b7-f7544fadd42e.png)

**Comment by ReikaKalseki** [comment]
The height code is determined by vanilla Minecraft.

**Comment by ReikaKalseki** [comment]
I cannot stop it from attempting to generate multiple times - welcome to vanilla stupidity - but I _did_ clear the dropped items.
