### ISSUE TITLE
V14d - Pregen Command is broken

### ISSUE THREAD

**Issue by Shadows-of-Fire** [ReikaKalseki/Reika_Mods_Issues#984]
Attempting to use the /pregen command now that it has helper output seems to be futile.  
Using the command in the form "/pregen 0 150 0 0 200" causes the game to output "Invalid arguments. Use [dim] [perTick] [ctrX] [ctrZ] [radius]."
Basically it just seems to always output "Invalid Arguments" no matter what input it's given.

**Comment by Aivech** [comment]
Have you tried pregenning around your current location? World spawn is usually not at 0,0.

**Comment by Turmfalke2** [comment]
@DaMachinator that is not going to help, the command checks for 4 arguments and expects 5.

**Comment by ReikaKalseki** [comment]
Fixed.
