### ISSUE TITLE
Chromaticraft Multi Block forming with Railcraft added

### ISSUE THREAD

**Issue by Ryius** [ReikaKalseki/Reika_Mods_Issues#985]
I tried building the Lumen Beacon But it did not work after 8 hours searching the problem i ended up searching trought my mod list and after i take Railcraft out it work .tried puting it back in the modsfolder and beacon was broken again .

**Comment by KevTheCrafter** [comment]
Same as #927.
I had the same issue. If you use worldedit, replace the heat block with air or disable it in the railcraft configuration.

See also Reikas FAQ and search for Railcraft: https://sites.google.com/site/reikasminecraft/faq

**Comment by Ryius** [comment]
oh thanks i am realy pleaced and i dont use the heat block

**Comment by Ryius** [comment]
and where can i disable this block

**Comment by KevTheCrafter** [comment]
The invisible heat block spawns every time a player moves around.
See here: http://ftbwiki.org/Residue_Heat

You can disable it in your railcraft blocks.cfg, set residual.heat from true to false.

**Comment by Ryius** [comment]
okey thanks i found it .changed the some what to Railcraft?

**Comment by Ryius** [comment]
i often added my world with mcedit and the fly around you ?

**Comment by TomeWyrm** [comment]
I almost want a Railcraft Heat Block tag... almost

**Comment by ReikaKalseki** [comment]
It has only come up a couple times on the tracker.

**Comment by ghost** [comment]
ASM it out :/

**Comment by TomeWyrm** [comment]
Yeah, but you know it's going to keep coming up, even if you disable it programmatically or throw an error, or crash, or do anything or nothing.
