### ISSUE TITLE
Crash when placing the second of a pair of world rifts

### ISSUE THREAD

**Issue by Ieldra2** [ReikaKalseki/Reika_Mods_Issues#987]
Crashlog at http://pastebin.com/ftW2hL3c

This occurs whenever I place a world rift and there exists another one in the world which the newly placed one attempts to link to. Sometimes the second of a pair of world rifts does not attempt to link, then the crash does not occur. This crash has been 100% reproducible in my worlds so far (about 20 attempts). In spite of the crash, the world rift is placed and usually linked correctly when I re-enter the world.

I posted this on the forum some time ago but I thought it's better to post it here as well. This problem has existed in my Revolution 2 worlds at least since V13.

**Comment by ReikaKalseki** [comment]
I am not sure this is on my end, but I know for a fact rifts can be placed given my usage of them on the server.
