### ISSUE TITLE
Function request to ChromatiCraft 

### ISSUE THREAD

**Issue by DukeofSoul** [ReikaKalseki/Reika_Mods_Issues#988]
I want to request a new feature in ChromatiCraft
1. The generation of new energy node which will be spawning in a range of 10 chunks from the block which generates the energy(IC , TE or other kind ) or where the energy is stored. This node will consume energy from blocks that can gen energy or store it. After accumulation a lot of it the node will just explode in range about 20 blocks.
2. Whatever happened above ,  there are 2 ways to control it! 1- Put some kind of protection around the node which will consume energy.2-You will need to find the nodes as quick as possible (It can also be made invisible) and to conclude it in a multi-block structure where it will have 2 modes: 1 - It will store the energy; 2- It will store the items (works only if AE2 installed)  and  will be  a kind of  storage cell .

Generally it is all! I hope you liked my idea to add this functionality. I will be very happy if you will create at least something similar in ChromatiCraft!
But if you take my idea then I'd also like to think about the balance (I.e. storing of objects ,energy,craft, and more)

**Comment by ghost** [comment]
What exactly is the purpose of this in ChC? It doesn't sound really relevant compared to what is actually in it. If it's to create energy, use RoC, ReC, etc. If it's to store energy, use ElC, EiO or DE. If it's items, AE, Jabba, Storage Drawers, etc.

ChC focuses on magic. Making it able to generate RF or EU is wrong for what it's trying to do. This would only make sense in a mod that had nodes, like ThC but highly unlikely. An addon might but still, doesn't make sense.

**Comment by ReikaKalseki** [comment]
This is neither balanced nor thematically appropriate.
