### ISSUE TITLE
Chromaticraft Nether Hut Treasure Generation

### ISSUE THREAD

**Issue by Keyarose** [ReikaKalseki/Reika_Mods_Issues#990]
I don't know if this is an issue with me or if there is an issue with the chest generation, but I've opened around 12 of the loot chests across 50 or more chunks and the loot has been exactly the same in each one.  Other chests like the secret burrows or village structures have not had this issue.

![2016-06-21_17 06 38](https://cloud.githubusercontent.com/assets/1906772/16244667/8c7c0130-37d3-11e6-8dd9-5c9ea47c8eb2.png)

**Comment by ReikaKalseki** [comment]
Someone else reported this, but my experiences have been directly to the contrary. My one guess is something messing with the random instance in the world.

**Comment by Keyarose** [comment]
Alright then, it's probably just the world gen lag doing something weird to the RNG anyway.

**Comment by ReikaKalseki** [comment]
My guess is another mod screwing with the seed on a per-chunk basis.
