### ISSUE TITLE
Void Monster can't be hurt

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#993]
I've tried several ways to hurt the damn thing (Nether Variant, if that matters).

I've tried the following:

Tinkers' Construct Scythe (9 damage)
Matter Overdrive Plasma Shotgun, Phaser Rifle, and Omni Tool (13,9,8 damage respectively)
Thaumcraft Wand with basic Shock Focus

Absolutely nothing hurts it. I have Vazkii's Neat mod to show health bars.

The wand focus and Omni Tool caused it to do some sort of charge-up, and dash at me, at least, the others didn't even do that.

**Comment by ReikaKalseki** [comment]
I know for a fact it can be killed.

**Comment by redelman** [comment]
Having just killed it myself the other day, I concur. It's not difficult at
all, really.

**Comment by Shahelion** [comment]
Is there some specific type of damage that must be used? Or types that it always blocks, like magic damage?

**Comment by Aivech** [comment]
Try fighting it in the general vicinity of an adequately powered RoC laser turret.
Results not guaranteed.

**Comment by redelman** [comment]
Party pooper. I specifically did not mention that hoping that the OP would
be smart enough to give it a shot.

**Comment by Aivech** [comment]
Look again.

**Comment by redelman** [comment]
Edited mine to take out the quoted comment that I was replying to. :)
