### ISSUE TITLE
Canola seeds looks different

### ISSUE THREAD

**Issue by Doppelganker** [ReikaKalseki/Reika_Mods_Issues#994]
Icon for canola seeds looks different when you have them in hotbar or when they are in inventory.

![javaw 2016-06-23 09-23-02-94](https://cloud.githubusercontent.com/assets/17344502/16295114/180e5da4-3925-11e6-9505-4acffa35edc4.jpg)
![javaw 2016-06-23 09-23-00-02](https://cloud.githubusercontent.com/assets/17344502/16295116/1b0d6496-3925-11e6-83dd-77bb0784a411.jpg)

**Comment by ljfa-ag** [comment]
Might be intentional? Seems like otherwise the icon would be hard to see in the hotbar.

**Comment by ghost** [comment]
Looks like the light grey parts blend with the inventory color.
