### ISSUE TITLE
Crash on start with Reika's mods (specifically Dragonapi)

### ISSUE THREAD

**Issue by talianagisan** [ReikaKalseki/Reika_Mods_Issues#998]
So when ever i install Dragonapi (and Reactorcraft,Rotarycraft,Electricraft althought i cant see a crash report with them mentioned) my minecraft wont start up and gives me a short but confusing error i can't solve hence why im posting here. http://pastebin.com/1BtTSBE1 the error is around line 382. ive tried for days to solve this but cant and thankfully i have no lingering issues when removing the mods so it will start again but any idea's on this one as id love to use these mods.

**Comment by ljfa-ag** [comment]
Have you tried removing other mods?
Possible suspects: MobiusCore, Dynamic Lights, Galacticraft, TrashSlot, ItemPhysic. Seems like one of these is causing a conflict.

**Comment by ljfa-ag** [comment]
Appears to be a duplicate of #989. Which is also a duplicate but with no reference.

**Comment by talianagisan** [comment]
i tried removing them and it didnt do anything.

**Comment by Builderb0y** [comment]
Update fastcraft.
