### ISSUE TITLE
client/server wirdness "fatally missing blocks and items.

### ISSUE THREAD

**Issue by plaguewolf** [ReikaKalseki/Reika_Mods_Issues#999]
not a crash, just some really annoying weirdness.

as ive noted on the forums once before, i have some issue with worldgen between gregtech and chromaticraft, that causes worldgen to all but halt. this happens at random when making a new world, and taking gregtech out of the pack, or vice versa, CC, seems to fix that. but i digress.

recently ive taken to running a server to play minecraft, because strangely enough, it uses less resources, and has better performance, than the internal SSP server, among other reasons.

well, during worldgen issues, as mentioned above, i have to stop the server, and start a new map, repeating until worldgen 'takes'. usually i leave my client up during these server restarts, because of how long it takes for ~250 mods (_glares at gregtech_) to load.

then, i had this weird thing, server loaded, mystcraft profiling finishes, tried to join server, got message "Fatally missing blocks and items", which is odd, since i assumed that meant that i had mod discrepencies between server/client. but there's not, the server mods/configs are directly copied from my client folder, minus the mods that are client side only (notenoughkeys). literally nothing has changed since i last had this setup working.

everything still works, i guess, and a simple restart of the client fixes it.

just thought id pass along the info, cause the NPE mentions dragonapi and fastcraft.

http://pastebin.com/nh3wu1DN

**Comment by ReikaKalseki** [comment]
Your section of log is unrelated, and the log will also tell you _what_ blocks and items are missing. Use that for more information.

**Comment by plaguewolf** [comment]
ahh, yes, but heres the thing:

[10:37:00] [Netty IO #9/INFO] [FML]: Attempting connection with missing mods [] at CLIENT

**Comment by ReikaKalseki** [comment]
_That_ is on Forge.

**Comment by plaguewolf** [comment]
sorry, im not sure i understand...? which section of log is relevant? because, even though i know beyond a shadow of a doubt, that i am not, in fact, missing any mods between client/server and my configs are exactly the same, i did look through the log files, and dont see any mention of block/item ID discrepancies.

the only time anything related comes up is when i try to connect, and my server throws a NPE, as posted above.

**Comment by ReikaKalseki** [comment]
If Forge's missing mods system is kicking you with an empty list, there is an issue in Forge.

**Comment by Aivech** [comment]
You could always try a CLEAN install of MC and forge, and if that doesn't work, try a binary split search to find out if it is actually a mod. I get the "attempting connection with missing mods" on the client all the time - it seems to be looking for client-side mods on the server, realizes they don't belong there, and continues on its merry way. So this is odd.

**Comment by plaguewolf** [comment]
mmhmmm, which is why client only mods need a ServerSided section that says "ignore me, derpa derpa."

i'll have to give my server mods list a look through, maybe when my eyes can focus on the words without them swimming all over the place.
insomnia is a curse...
